### ISSUE TITLE
bug: cpu 100% with Edgy

### ISSUE THREAD

**Issue by theoribeiro** [LazyVim/LazyVim#1001]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1888+g8376e8700-Homebrew

### Operating system/version

MacOS 13.2

### Describe the bug

Whenever I have the edgy extra installed if I open NeoTree, go down to symbols outline and press "q" to quit it, the CPU usage jumps to 100% and hangs nvim. 

I tried setting up a minimal repro by just adding edgy, neotree and symbols-outline but couldn't reproduce the error. I believe there is some interaction of the plugins installed by LazyVim that is causing the issue but can't diagnose it. For that reason I'm filing the bug here instead on the edgy repo.

Funny enough, if I open symbols outline directly by pressing `<leader> cs` and then quit it with "q" the issue doesn't happen. I believe that is because this hides Edgy completely since NeoTree is not open. Maybe the issue seems to be related to Edgy still being shown on screen after the Outline window is closed. 

### Steps To Reproduce

1. Press `<leader>e` to open NeoTree
2. Press `<C-j>` to go to Outline window
3. Press "q" to close symbols outline
4. See CPU usage at 100%

### Expected Behavior

Expected CPU usage not to be 100%

**Comment by folke** [comment]
Can you post a link to your setup?

Or at least a copy of all the plugins from `:Lazy`?

Are you using something like `windows.nvim` by any chance? Or another animation plugin?

**Comment by theoribeiro** [comment]
Found the culprit! I was using [stickybuf](https://github.com/stevearc/stickybuf.nvim) so that I wouldn't open files in the explorer window or in the terminal. Removing it stopped the issue from happening. No idea how it was interfering with Edgy but it was! 
I'll close this issue now. Thanks @folke
