### ISSUE TITLE
bug: Default mapping in yanky means that `<c-p>` doesn't work

### ISSUE THREAD

**Issue by briandipalma** [LazyVim/LazyVim#1007]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

Linux

### Describe the bug

From the yanky documentation: https://github.com/gbprod/yanky.nvim#pickertelescopeuse_default_mappings

```
i = {
          ["<c-p>"] = mapping.put("p"),
```

seems redundant and is clashing with the normal previous mapping.

### Steps To Reproduce

.

### Expected Behavior

.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Fixed!

**Comment by dpetka2001** [comment]
I just changed that to `c-v` in my config, though I don't know how often I'll be using it (just for the sake of it existing as a mapping in the telescope extension). Mostly use `p/P/]p/]P` and related for my uses.

**Comment by folke** [comment]
Pressing enter is the same, so really not needed to also have it under `<c-p>` or anywhere else

**Comment by dpetka2001** [comment]
For some reason pressing `Enter` gives me an error related to Telescope it seems, so I'll just keep it like that for now.

**Comment by gbprod** [comment]
Hey!
FYI, I've removed this mapping (https://github.com/gbprod/yanky.nvim/pull/137), so you can revert this IMO ;)

**Comment by folke** [comment]
@gbprod reverted, thanks!
