### ISSUE TITLE
bug: attempt to call field 'nvim_get_hl' (a nil value), Error detected while processing User Autocommands for "LeapEnter"

### ISSUE THREAD

**Issue by beyond-fu** [LazyVim/LazyVim#1020]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0-dev-1083+gf289fc4ab

### Operating system/version

Ubuntu22.04(XFCE) on x86-64

### Describe the bug

Today when I `type 's'(Leap)`, these errors occurs. And `typing 'S/t/T/f/F'` has the same errors, becase they all use Leap.

![errors](https://github.com/LazyVim/LazyVim/assets/54238106/2f3d0ba9-7f51-4461-ac92-ac00fe18c89d)

These days I upgraded some different plugins twice, and I don't know when causing this problem. I cannot find the errors in Leap codes for me. Add honestly, I deleted some config files under my home folder mistakenly yesterday :( . So I don't know if it is because I lost some env variables about nvim in my .zshrc.

### Steps To Reproduce

For now, all my plugins are the latest version.

### Expected Behavior

.

### Repro

```Lua
I did not modify the configs of Leap.
```

**Comment by folke** [comment]
You'll have to report this to the leap repo. It doesn't seem to support your Neovim version.

Alternatively check out [flash.nvim](https://github.com/folke/flash.nvim), one of my new plugins.

I'm planning to make this the default jump plugin soon, but will of course also provide an extra to use leap instead.

See the LazyVim [extra](https://www.lazyvim.org/plugins/extras/editor.flash)
