### ISSUE TITLE
feature: find out which plugin cause neovim crash

### ISSUE THREAD

**Issue by bo-wu** [LazyVim/LazyVim#1026]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Since lazyvim prompts plugin updates at start, I always update the plugins. However, recently after updates ( even I delete all the plugins and start over again) these plugins, nvim always crash when open c/py file or frozen at input commands. I cannot figure out which plugin cause the problem. If I can, I will stick with older version.

### Describe the solution you'd like

after crash, I can find a log  somewhere

### Describe alternatives you've considered

 or hints when opening neovim next time

### Additional context
BTW, 
OS: Windows 10
Terminal: wezTerm
neovim: 0.9.1 LuaJIT 2.1.0-beta3

start with lazyvim starter, after installed all the default plugins, use nvim open  c file crash

checkhealth returns OK and some warnings, no error

_No response_

**Comment by folke** [comment]
LazyVim can't do anything if you get a segfault.

Please refer to the Neovim wiki to get a detailed stacktrace and report this as an issue to Neovim.

On linux, you can typically do `coredumpctl -1 gdb` after the crash.

Then type `where` to see the full stacktrace. More info on the wiki

Segfaults should never happen.
