### ISSUE TITLE
bug: rust-tools `K` binding does not work

### ISSUE THREAD

**Issue by loqusion** [LazyVim/LazyVim#1034]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev-605+g2493815290

### Operating system/version

Arch Linux

### Describe the bug

`K` is set to do `:RustHoverActions` here:

https://github.com/LazyVim/LazyVim/blob/fca09b12e8188fb0a9b7bda040890c096e6cc9be/lua/lazyvim/plugins/extras/lang/rust.lua#L61

However, it's not working for me.

The other buffer-local mappings are working, so it seems as though the original `K` mapping in the lsp plugin module is overriding it.

### Steps To Reproduce

1. Press `K` on a function/module that rust-tools would let you debug
2. It's a regular hover action
3. Running `:RustHoverActions` has the correct behavior

### Expected Behavior

It should do what `:RustHoverActions` does which is let you perform actions like run or debug.

**Comment by folke** [comment]
I've reworked everything related to lsp keymaps.

Should properly override the hover keymap now.

**Comment by dpetka2001** [comment]
From the `extras.lang.rust` I see that now `lspconfig.servers.[server]` now accepts a keys option. Is the configuration from [docs](https://www.lazyvim.org/plugins/lsp#%EF%B8%8F-customizing-lsp-keymaps) needed any more? Can we put all keys directly in `lspconfig.servers.[server].keys` section from now on?

**Comment by folke** [comment]
yes! Need to update that doc indeed. Feel free to submit a PR :)

**Comment by folke** [comment]
actually, it would only work for specific lsp server keymaps. But the code can be updated to support lspconfig.opts.keys as well

**Comment by dpetka2001** [comment]
Does `K` work for you after the latest changes? In Lua files I get `man.lua: "no manual entry for require"` for every entry that I try to get LSP documentation.

**Comment by folke** [comment]
just fixed that. my bad! Will push a new release
