### ISSUE TITLE
bug: Status column showing debugging info does not appear when restoring session.

### ISSUE THREAD

**Issue by kyrillh** [LazyVim/LazyVim#1035]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.1

### Operating system/version

MacOS 13.4.1 and CentOS Linux 8

### Describe the bug

By default there is a thin column to the left of the line numbers on each panel where breakpoint symbols appear and where an arrow appears during debugging, indicating the current line. 

When a previous session is restored using `<leader>qs` or `<leader>ql` this column does not appear and the breakpoint symbols and arrow are not visible. 

### Steps To Reproduce

1. Quit an active session (some open files) using `<leader>qq`. 
2. Restore the session using `<leader>ql` or `<leader>qs`. 
3. Try setting a breakpoint with `<leader>db`. The breakpoint symbol does not appear. 

### Expected Behavior

The thin column is present and shows breakpoints and the debugging arrow.

**Comment by folke** [comment]
breakpoints and debugging symbols never get restored. That's not possivle

**Comment by kyrillh** [comment]
This does not refer to debugging symbols being restored, but rather to the status column in which they appear. When restoring a session this status column does not open, so that new breakpoints that are set and the arrow in while debugging are not visible. 

Expected UI while debugging:
<img width="700" alt="Screenshot 2023-07-02 at 13 00 47" src="https://github.com/LazyVim/LazyVim/assets/49488037/db3caaa4-cccb-4c71-a992-5616fa4e7a8e">

UI while debugging after restoring session: 
<img width="700" alt="Screenshot 2023-07-02 at 13 06 54" src="https://github.com/LazyVim/LazyVim/assets/49488037/08fffc37-2428-45fc-94ea-c799f649bb1b">

**Comment by folke** [comment]
I can't reproduce this. Are you using any plugin that configures statuscolumn?

**Comment by kyrillh** [comment]
Not that I know of. I have installed `clangd`, `cpptools`, and `cpplint` with Mason and added a `dap.lua` file in the `plugins` folder to specify some debugging configs. Apart from a different color scheme, I have not added any other plugins to the default LazyVim setup (which I am enjoying very much b.t.w.!)

**Comment by mikaoelitiana** [comment]
I am having the same issue. If I open LazyVim and load file one by one, the gutter is displayed as expected. When I reload a session with `<leader>qs`, the gutter just disappears. @kyrillh have you found any solution for this?

**Comment by kyrillh** [comment]
Excellent! This solved it for me too. 
Thank you.

**Comment by folke** [comment]
@mikaoelitiana did you have the same problem after using DAP? Or always?

**Comment by mikaoelitiana** [comment]
> @mikaoelitiana did you have the same problem after using DAP? Or always?

I don't exactly recall if it was before or after since I enabled DAP long time ago. I only noticed a few days ago when I started restoring session (I have not used this feature much before)
