### ISSUE TITLE
bug: commands such as `gd` broken after today's release

### ISSUE THREAD

**Issue by fredrikaverpil** [LazyVim/LazyVim#1038]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

macOS Ventura 13.4.1

### Describe the bug

With commit 61e3ce8cdc1159d59e11d92478ca76ea19e44c2a I cannot hit `gd` in my Python scripts.

I haven't investigated the reason, but I can manually revert back to 36774c6 and it works again.

### Steps To Reproduce

1. Revert LazyVim to 36774c6
2. Install the "pyright" LSP in Mason.
3. Open Python script, use `gd` on e.g. an import statement (this works). You can see that which-key also shows the `d` keymap after hitting `g`.
4. Now update LazyVim to 61e3ce8cdc1159d59e11d92478ca76ea19e44c2a.
5. Open up the python script again, now you can't hit `gd` on the import statements. Which-key also doesn't show the `d` keymap after hitting `g`.

### Expected Behavior

I'd expect `gd` to still work after the latest updates.

**Comment by dpetka2001** [comment]
It's on the bugfix list for next [release](https://github.com/LazyVim/LazyVim/pull/1037). There was some refactoring as far as LSP keybindings are concerned from what I've read in another issue and some of the latest PRs.

**Comment by folke** [comment]
Fixed!

**Comment by fredrikaverpil** [comment]
Awesome, thank you! 🎉
