### ISSUE TITLE
bug: "Couldn't connect to localhost:${port}" when debugging JS file

### ISSUE THREAD

**Issue by pcattori** [LazyVim/LazyVim#1044]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

MacOS 13.4

### Describe the bug

Launching a JS debugger does spin up the debug server, but nvim fails to connect to it:

<img width="351" alt="Screenshot 2023-07-02 at 3 47 10 PM" src="https://github.com/LazyVim/LazyVim/assets/1477317/1abb048d-5bff-442a-bacf-92825ad28e0a">

<img width="652" alt="Screenshot 2023-07-02 at 3 36 41 PM" src="https://github.com/LazyVim/LazyVim/assets/1477317/455dfaa7-0c4b-406f-b9c1-855bffc9a01e">

### Steps To Reproduce

1. Create new LazyVim installation

```sh
git clone https://github.com/LazyVim/starter ~/.config/nvim
```

2. Enable Typescript and DAP Core extras

```lua
-- ~/.config/nvim/lua/config/lazy.lua

require("lazy").setup({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    { import = "lazyvim.plugins.extras.lang.typescript" },
    { import = "lazyvim.plugins.extras.dap.core" },
    { import = "plugins" },
  }
-- other code the same
})
```

3. Create a Node JS file

```js
import { createServer } from "http";

const host = "localhost";
let port = 8000;

const requestListener = function (_req, _res) {};

const server = createServer(requestListener);
server.listen(port, host, () => {
  console.log(`Server is running on http://${host}:${port}`);
});
```

4. Open that file with `nvim`
5. Add a breakpoint (`<leader>db`)
6. Start a debugging session (`<leader>dc`)

<img width="753" alt="Screenshot 2023-07-02 at 3 36 48 PM" src="https://github.com/LazyVim/LazyVim/assets/1477317/7c27241c-3217-47de-992d-cb110e10fb84">

### Expected Behavior

Debugger starts, `dapui` opens, and debugger pauses at breakpoint

### Repro

```Lua
`nvim -u repro.lua` results in `Cannot read from "repro.lua"`
```

**Comment by folke** [comment]
Try runnig the file from the cmdline. It should work there before it works in the debugger.

With newer nodejs versions, you needt to set type=module in your package.json, or rename the file to have an mjs extension  for import to work

**Comment by folke** [comment]
well yes, you now renamed it to mjs. Then it should also work in dap

**Comment by pcattori** [comment]
It was always named `server.mjs`

**Comment by folke** [comment]
what if you create a package.json and add type=module?

**Comment by folke** [comment]
Works fine for me without package.json and an mjs file

![image](https://github.com/LazyVim/LazyVim/assets/292349/c340d011-0c5b-4c95-acb9-46ab7a7a7698)

**Comment by pcattori** [comment]
Added the following `package.json`:

```json
{
  "private": true,
  "type": "module"
}
```

but same issue

**Comment by folke** [comment]
Must be something on your end.

For me it works with a default LazyVim install with the following two extras:

```lua
    { import = "lazyvim.plugins.extras.lang.typescript" },
    { import = "lazyvim.plugins.extras.dap.core" },
```

**Comment by pcattori** [comment]
I just created a fresh LazyVim install as `git clone https://github.com/LazyVim/starter ~/.config/nvim-repro`, only added those two extras (no other config/plugins changed), and ran with `NVIM_APPNAME=nvim-repro nvim`. Still getting the same issue.

If you can't reproduce then it might be something else on my system. Will keep looking.

**Comment by folke** [comment]
Nope, all works fine with a minimal install for me. Maybe your node version? Are you starting neovim in the same directory you have that file in? An not using a GUI for example?

**Comment by pcattori** [comment]
Yep, I was also thinking Node version. Just switched from 16 to 18 and that fixed it.
