### ISSUE TITLE
feature: Adding autocmd for noh instead of keymap so multiple keys can remove search highlights

### ISSUE THREAD

**Issue by bassamsdata** [LazyVim/LazyVim#105]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

It's not a problem with LazyVim. It's just a suggestion that might enhance LazyVim I think.

### Describe the solution you'd like

This `autocmd` can remove the search highlights whenever I any keys except that I specify here. so no need to press `<Esc>` before pressing j,k,l or any other key.

```lua
vim.on_key(function(char)
  if vim.fn.mode() == "n" then
    local new_hlsearch = vim.tbl_contains({ "n", "N", "*", "#", "?", "/" }, vim.fn.keytrans(char))
    if vim.opt.hlsearch:get() ~= new_hlsearch then
      vim.opt.hlsearch = new_hlsearch
    end
  end
end, vim.api.nvim_create_namespace("auto_hlsearch"))
return
```

I'm sure people here know about that, it's just a suggestion (I'm not a software engineer and this wasn't my code, I've seen it in reddit and multiple pre-configs..Astrovim..etc).

It can be added directly, but I can do a PR if you want so.

### Describe alternatives you've considered

Despite not implementing it, I still consider LazyVim a greeeeeat one :)

**Comment by folke** [comment]
Thank you for the suggestion!

I'm personally not a fan of clearing search highlights like this, but I'm sure other people might like it.

I've created a new discussions section where you can share things like this:
https://github.com/LazyVim/LazyVim/discussions/categories/recipes

**Comment by bassamsdata** [comment]
Oh thanks for that, yea I think the recipes is the right thing to do
