### ISSUE TITLE
bug: flit.nvim uninstalls after initial install

### ISSUE THREAD

**Issue by gregdan3** [LazyVim/LazyVim#1055]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.1

### Operating system/version

6.3.9-arch1-1 (alpine:edge docker image)

### Describe the bug

`flit.nvim` is errantly uninstalled on latest master, looks to be caused by [this commit](https://github.com/LazyVim/LazyVim/commit/9c120b5ef7dfaba0079ed632859a778b8f103991)

### Steps To Reproduce

1. Run with docker as directed by the README:
```sh
docker run -w /root -it --rm alpine:edge sh -uelic '
  apk add git lazygit neovim ripgrep alpine-sdk --update
  git clone https://github.com/LazyVim/starter ~/.config/nvim
  cd ~/.config/nvim
  nvim
'
```
2. Wait for installation to complete
3. Under `<leader>lC`, observe that `flit.nvim` is installed.
4. `<leader>lU` to update all plugins
5. `flit.nvim` is uninstalled and you are prompted to clean it.

### Expected Behavior

`flit.nvim` should remain installed.

**Comment by folke** [comment]
Are you sure you're using the latest version?

The commit you're pointing to is the fix that reverted another commit that caused that issue

**Comment by gregdan3** [comment]
Ah, I thought I was, but the `lazy-lock.json` confirms otherwise. I'm on the commit of the latest release, both in my own config and in the docker image. Both of these configs have the following in their `lazy.lua` though:

```lua
...
require("lazy").setup({
	spec = { ...
	defaults = {
		lazy = true, -- every plugin is lazy-loaded by default
		version = false,
	},
        ...
})
```
Isn't the purpose of `version = false` to use the latest commit, not the latest release?

**Comment by folke** [comment]
for lazyvim, you need to explicitely set that to false as well . See for more info in the docs.

It seems that that revert didnt trigger a new release. Just made a dummy commit to trigger it.

**Comment by folke** [comment]
A new release will be availble in a minute https://github.com/LazyVim/LazyVim/pull/1056

**Comment by gregdan3** [comment]
Gotcha, thanks for the quick help!
