### ISSUE TITLE
bug: neo-tree does not follow active file, explorer (root dir) overrides cwd on monorepos

### ISSUE THREAD

**Issue by lorenzofero** [LazyVim/LazyVim#1062]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

Linux Fedora 38

### Describe the bug

In general `neo-tree` has a weird behaviour. First, it does not follow the current file even if `follow_current_file = true` is set in the options by default:
[Screencast from 2023-07-05 19-27-00.webm](https://github.com/LazyVim/LazyVim/assets/60553286/7e23ea4d-c203-4ae2-8fd5-cda52cfb7654)
In the video above, I'd expect that `neo-tree` updates showing an expanded view up to the current file.

The second not wanted behaviour is that the default mappings `<leader>e` and `<leader>E` do not work well in monorepos: in particular,  `<leader>e` overrides the current working directory as shown:
[Screencast from 2023-07-05 19-38-05.webm](https://github.com/LazyVim/LazyVim/assets/60553286/88f21733-802a-4571-ae1b-4b13248388d6)
After pressing `<leader>e`, the working directory is overwritten on "frontend", and now `<leader>E` does nothing different than `<leader>e`.

### Steps To Reproduce

I hope the videos are clear enough!
I'm using the starter template with no modifications to neo-tree.

### Expected Behavior

1. Neo-tree follows file/buffer and expands tree accordingly
2. Different behaviour of `<leader>e` and `<leader>E`

Thanks a lot in advance for the support. LazyVim has been just awesome for everything else!

### Repro

```Lua
require("config.lazy")
```

**Comment by folke** [comment]
All of that does work as expected.
You probably changed the config for neo-tree?

In a monorepo `leader-e` would open the folder you're in, but the LazyVim config for neo-tree disables bind to cwd, so your cwd won't change
