### ISSUE TITLE
feature: Disable built-in plugin like lazyterm

### ISSUE THREAD

**Issue by raceychan** [LazyVim/LazyVim#1075]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

builtin plugins can't be disabled right, and keymaps for these plugin can't be changed to others neither.

### Describe the solution you'd like

in the docs, there is a disable.lua
where you can disable plugin,
it would be the best if built-in plugins can be disabled just like that

### Describe alternatives you've considered

there are might be many ways to do that, i wonder if these built-in plugins that are not in seperate repo can be viewed and operate in lazy.nvim

**Comment by dpetka2001** [comment]
Lazyterm is not a builtin plugin. It just makes a new floating buffer out of the default Neovim `terminal`. You can however change the default keymaps if you like in your `lua/config/keymaps.lua`. It's just assigned a filetype `lazyterm` to make things easier to customize in regard with other plugins.

**Comment by raceychan** [comment]
> Lazyterm is not a builtin plugin. It just makes a new floating buffer out of the default Neovim `terminal`. You can however change the default keymaps if you like in your `lua/config/keymaps.lua`. It's just assigned a filetype `lazyterm` to make things easier to customize in regard with other plugins.

yeah,i notice that in lazyvim/config/keymaps.lua, following lua code is executed to add the lazy term functionality

```lua
local lazyterm = function() Util.float_term(nil, { cwd = Util.get_root() }) end
map("n", "<leader>ft", lazyterm, { desc = "Terminal (root dir)" })
map("n", "<leader>fT", function() Util.float_term() end, { desc = "Terminal (cwd)" })
map("n", "<c-/>", lazyterm, { desc = "Terminal (root dir)" })
map("n", "<c-_>", lazyterm, { desc = "which_key_ignore" })
```
and this code gets executed before my local 'lua/config/keymaps.lua', i just wonder if there is way to disable this whole lazyterm things.
perhaps set it to null like 
```lua
-- in my 'keymaps.lua'
local lazyterm = nil
```
would this disable the all lazyterm-related keymaps, or should i disable them one by one?

**Comment by dpetka2001** [comment]
I would think you'd have to disable them one by one. Or change them to whatever you like.

**Comment by folke** [comment]
You can just delete or override the keymaps in your own `lua/config/keymaps.lua` file

**Comment by raceychan** [comment]
> You can just delete or override the keymaps in your own `lua/config/keymaps.lua` file

thanks for the reply, would you mind share a simple example on how to delete the key map that's predefined by lazyvim in keymaps.lua? I'm new to nvim and when I Google most answers show only how to override the Kemap instead of deleting

**Comment by folke** [comment]
This should do the trick:

```lua
vim.keymap.del("n", "<leader>ft")
vim.keymap.del("n", "<c-_>")
```

**Comment by raceychan** [comment]
> This should do the trick:
> 
> ```lua
> vim.keymap.del("n", "<leader>ft")
> vim.keymap.del("n", "<c-_>")
> ```

your help is greatly appreciated, this saves me a lot of time inspired by your answer, i found this vim api which looks more nvim style
```lua
-- Unmaps a global |mapping| for the given mode.
-- 
-- To unmap a buffer-local mapping, use |nvim_buf_del_keymap()|.
-- 
-- See also: ~
--   • |nvim_set_keymap()|
--- @param mode string
--- @param lhs string
function vim.api.nvim_del_keymap(mode, lhs) end
```

i ended up with following lua script which works great and solves my problem

```lua
vim.api.nvim_del_keymap("n", "<leader>ft")
vim.api.nvim_del_keymap("n", "<c-_>")
```
