### ISSUE TITLE
Keymaps overriding plugin key handlers with multiple modes

### ISSUE THREAD

**Issue by jasonobrien** [LazyVim/LazyVim#1087]
I'm having trouble overriding a default keymap in a plugin map, e.g.:

```lua
  {
    "echasnovski/mini.animate", -- any plugin
    keys = {
      {
        "<C-h>",
        function()
          print("foo")
        end,
        mode = { "n", "i", "c" },
      }, 
    }
  }
```

The insert-mode handler will work, but the normal-mode handler will not. I think what's going on is:

The default key maps try to avoid overriding lazy key handlers, but it looks for an exact match of the mode specifier, so e.g. a normal-mode mapping of `<C-h>` (as in the LazyVim defaults) will look for `n` exactly (not `nic`), and end up mapping over the handler.

https://github.com/LazyVim/LazyVim/blob/a38bf3001dc5576110cb0bbcacc262526ddf7bb9/lua/lazyvim/config/keymaps.lua#L8

I guess ideally lazy.nvim's API would support per-mode querying; working around it in keymaps.lua might be clunky (e.g. iterating the table looking for matches).

**Comment by folke** [comment]
If you want to override a keymap, then yes, you need to make sure you're overriding the exact same mode definition.

This is not a bug. This is by design.

**Comment by jasonobrien** [comment]
Devil's advocate - adding another mode to your key mappings feels like a no-op, and having them silently becoming overridden by an upstream curated list (not even for the mode you added!) is "spooky action at a distance". It may be pragmatic, but I wouldn't call it a design choice.

A small gripe in an otherwise very useful framework though, and I really appreciate you sharing it.
