### ISSUE TITLE
bug: fail to jump to next LSP warning 

### ISSUE THREAD

**Issue by XXiaoA** [LazyVim/LazyVim#109]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.0-dev-771+g18fb669b9b

### Operating system/version

Arch linux

### Describe the bug

We have a default keymap to jump to next LSP warning
https://github.com/LazyVim/LazyVim/blob/e2bfd2d66499a208812d815f38d90c0eac9dedda/lua/lazyvim/plugins/lsp/keymaps.lua#L26

But according to my test, we will jump to every diagnostic using this keymap including info, warning , error etc.

### Steps To Reproduce

open nvim with LSP, then press ` ]w`

### Expected Behavior

Only jump to next warning, like `]e` only jump to next error

### Repro

```Lua
default configuration
```

**Comment by folke** [comment]
Fixed! Had to be `WARN` instead of `WARNING`
