### ISSUE TITLE
feature: optimize large file editing

### ISSUE THREAD

**Issue by Innei** [LazyVim/LazyVim#1099]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

I opened a large JSON file of about 400MB, and then neovim hang up, the Neovim memory usage increase to 6GB suddenly.

Then I waited for a long time still stuck, no response, I could not open such a huge file.

<img width="994" alt="CleanShot 2023-07-12 at 4 29 22@2x" src="https://github.com/LazyVim/LazyVim/assets/41265413/e3e57a4a-f2f6-412c-b445-197092f671dd">

<img width="695" alt="CleanShot 2023-07-12 at 4 31 21@2x" src="https://github.com/LazyVim/LazyVim/assets/41265413/f2340d1d-a55a-49d4-832f-983b17c4fd33">

### Describe the solution you'd like

Fast open.

### Describe alternatives you've considered

Disabling all highlights maybe solve this perf issue.

**Comment by folke** [comment]
You can look into https://github.com/LunarVim/bigfile.nvim

**Comment by SichangHe** [comment]
Is there an option for this in snacks.nvim now?

**Comment by folke** [comment]
yes, snacks bigfile
