### ISSUE TITLE
feature: switch to fork of null-ls or an alternative

### ISSUE THREAD

**Issue by wilfriedbarth** [LazyVim/LazyVim#1104]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

https://github.com/jose-elias-alvarez/null-ls.nvim/issues/1621

`null-ls.nvim` is being archived, will need to switch to fork or future replacement. I found the following references to `null-ls.nvim` in `LazyVim` repo:

https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/lsp/init.lua#L209
https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/lsp/format.lua#L60
https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/extras/formatting/prettier.lua#L9
https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/extras/lang/typescript.lua#L56
https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/extras/lang/docker.lua#L11
https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/extras/lang/go.lua#L82
https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/extras/lang/terraform.lua#L22

### Describe the solution you'd like

`null-ls.nvim` is replaced with alternative solution.

### Describe alternatives you've considered

`null-ls.nvim` is replaced with fork of archived repo.

**Comment by folke** [comment]
This is already tracked in https://github.com/LazyVim/LazyVim/discussions/1080
