### ISSUE TITLE
bug: 5.0 breaks search operation using /

### ISSUE THREAD

**Issue by dvic** [LazyVim/LazyVim#1109]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

MacOS Ventura

### Describe the bug

Searching using `/` is not working anymore, in the sense that it quits the search after typing `sk`. If I revert back to v4.28.1 the problem is not present.

### Steps To Reproduce

1. open a lua file (other files are probably also affected, but with a lua file you can reproduce it for sure)
2. type `/`
3. type `sk`
4. search mode is exited

### Expected Behavior

The search mode should not exit after typing `sk`

### Repro

```Lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  { "LazyVim/LazyVim", import = "lazyvim.plugins", tag = "v5.0.0" }, -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
```

**Comment by folke** [comment]
LayVim is now using flash.nvim, which includes jump labels for seach. You can disable it in the config, or install the leap extra instead

**Comment by dvic** [comment]
I was aware of that, but shouldn't it only trigger when I type `s` and not `/s` ?

**Comment by folke** [comment]
Nope, as I said, flash also adds jump labels to regular search.
You can disable that wth `opts.modes.search.enabled = false`

**Comment by dvic** [comment]
I see now where my confusion is coming from, it's a tad unintuitive when your searching for something that's not there (that's what was happening in my case), then the cursor jumps to a location your not expecting. It indeed has nothing to do with the specific `sk` sequence.

**Comment by dvic** [comment]
> Nope, as I said, flash also adds jump labels to regular search.
> You can disable that wth `opts.modes.search.enabled = false`

Clear, thanks!

**Comment by dpetka2001** [comment]
LazyVim also offers a keybinding `<c-s>` which allows you to toggle the labels while in command mode such as search. I'm just mentioning it in case you don't want to disable the labels completely through the option mentioned above. For my personal preference I quite like it since I got used to it and I can still toggle it off whenever I want.
