### ISSUE TITLE
help pls

### ISSUE THREAD

**Issue by K0ha1** [LazyVim/LazyVim#111]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

latest

### Operating system/version

win 10

### Describe the bug

this comes up when i try to open nvim
![Screenshot 2023-01-23 134124](https://user-images.githubusercontent.com/69011302/214156430-b4fe3267-89cf-4c95-b416-60d65b7ecefb.png)

### Steps To Reproduce

instakll nvim
move all the starter files to ..\appdata\local\nvim

### Expected Behavior

for it to work

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Do you have git installed?
