### ISSUE TITLE
feature: TTY support (icons)

### ISSUE THREAD

**Issue by aarondill** [LazyVim/LazyVim#1111]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

When I'm using `nvim` in a tty, it's difficult to what I'm even looking at, due to LazyVim's extensive use of nerd fonts.

### Describe the solution you'd like

When using `nvim` in a tty (or other place where icons can't be displayed?), don't display nerdfont icons (or use ASCII placeholders).

### Describe alternatives you've considered

Creating overrides on the user level for each plugin included in LazyVim. As one might imagine, this is a difficult task, especially as LazyVim's development moves so quickly.

**Comment by folke** [comment]
You'll have to configure those yourself. Not planning to do this for you
