### ISSUE TITLE
feature: please avoid changing and overriding user configuration

### ISSUE THREAD

**Issue by Sleepful** [LazyVim/LazyVim#1117]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

it is very bad to go into my editor to get some code done and find out that I need to change my configuration before I can work just because of an upstream change that overrides my own personal config

https://github.com/LazyVim/LazyVim/commit/ae759b947b1ef16d9814fcddfcafe2cdd767bc6a

### Describe the solution you'd like

d

### Describe alternatives you've considered

d

**Comment by folke** [comment]
btw, the biggest reason I went ahead and made flash the default, is because flit has been breaking completely a couple of times over the past two weeks.

Instead of patching it again, I figured this was a good time to switch the default.

**Comment by Sleepful** [comment]
@folke I habitually update my packages, in my time using neovim I have not had breaking changes to my plugins other than LazyVim. The weird thing is here is that the plugin I am using did not break but now I have to fix it. A better experience for _your_ users would be to prompt them with a question _“do you want to update lazyvim with a breaking change?”_. That would be high end, especially since you control the package manager here. 

Anyway, those are my two cents, last time you discarded my thoughts but whatever, here is this message in the off chance that the suggestion ends up helping some users 🤷 I have nothing to gain from this.

I will vendor LazyVim and stop bugging you 👋

**Comment by Sleepful** [comment]
Either way, thanks for your work here. I will keep using `lazy.nvim`, otoh I could not have gotten up to speed so quickly with noevim if it wasn't for `lazyvim`.

**Comment by al-ce** [comment]
> @folke I habitually update my packages, in my time using neovim I have not had breaking changes to my plugins other than LazyVim. The weird thing here is that the plugin I am using did not break but now I have to fix it. A better experience for _your_ users would be to prompt them with a question _“do you want to update lazyvim with a breaking change?”_. That would be high end, especially since you control the package manager here.
> 
> Anyway, those are my two cents, last time you discarded my thoughts but whatever, here is this message in the off chance that the suggestion ends up helping some users 🤷 I have nothing to gain from this.
> 
> I will vendor LazyVim and stop bugging you 👋

Breaking changes are literally highlighted differently in the lazy UI to let you know they're breaking. If you're habitually updating packages without checking that they're breaking, then you should evaluate your habit. Just don't update until you're ready to handle it! How is this different from other software you use or write?

Your initial and follow up posts were extremely rude. This isn't a customer service center and even if it were you shouldn't be treating people like you're some feudal lord entitled to service. It's even worse that you had so many options to handle this correctly. I wouldn't bother saying anything except that this is a terrible pattern of behavior in the Neovim user base that we need to reflect on and change. It's a constant theme in the community that maintainers have this one-sided relationship where they put in all this effort into a product they're clearly passionate about and want to share and then have to experience this in return.

Sorry for getting on my soapbox but I've seen this a lot this week across multiple repos.

**Comment by Sleepful** [comment]
@al-ce Some feudal lord? I don't really have to explain this but lets do it: 

The software produced an `issue` on my end, so I came here to report it in the `issues` section of the Repo. I am providing free user feedback, I am not demanding anything in exchange. 

That's it 🤷 

Don't get your panties in a bunch just because you disagree with me over the ideal design of a piece of software. I have no interest in emotional arguments, that's immature.

FYI it is clear that you have never worked as a Customer Service rep, the comparison is totally unwarranted.
