### ISSUE TITLE
Null-ls is going to be archieved on August 11, 2023

### ISSUE THREAD

**Issue by gravis** [LazyVim/LazyVim#1118]
Raising awareness on this important plugin being archived next month: 
https://github.com/jose-elias-alvarez/null-ls.nvim/issues/1621

> Any user or organization who wants to fork the project and take over maintenance should feel free to do so (the majority of open issues / PRs are not actionable, so I don’t see value in transferring the repo).

**Comment by folke** [comment]
yes, again, well aware. Check the discussions.
