### ISSUE TITLE
bug: debug menu, adapters item shows around/inside mappings

### ISSUE THREAD

**Issue by abeldekat** [LazyVim/LazyVim#1121]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

arch linux

### Describe the bug

Stock lazyvim, with extra/dap/core: debug-adapters menu shows around/inside descriptions.

I noticed this because of my involvement in a pull request regarding which-key and mini.ai
It happens both on v5.0.0 and v4.27.0

### Steps To Reproduce

1. open any file
2. press <leader>d
3. observe menu items regarding debugging
4. press a, labeled "adapters"
5. observe around/inside descriptions

### Expected Behavior

Anything except those around/inside descriptions...) The menu item is labeled "adapters" 

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  { "LazyVim/LazyVim", import = "lazyvim.plugins", tag = "v4.27.0" }, -- add any other plugins here
  -- { "LazyVim/LazyVim", import = "lazyvim.plugins", tag = "v5.0.0" }, -- add any other plugins here
  { import = "lazyvim.plugins.extras.dap.core" },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Dap keymaps are under `<leader>d`, not `d`.

Just `d` is the detele operator and the `ai` mappings are operator pending mappings, so everything works as expected?

**Comment by abeldekat** [comment]
Hi Folke,

The "leader" I typed in step 2 did not show because of the brackets. Apologies.

In short, the problem is indeed about leader d.

**Comment by folke** [comment]
I know what's happening here.

You don't have the lua debug adapter installes, so the `adpters` menu is empty.

Since you typed `<leader>da`, those keys would have been fed back to Neovim, since there's no match in which-key.

`<leader>d` is not a keymap, so it would have been a `<leader>` which is ignoired, followed by `da`. So then you would indeed see the operator pending maps which is correct

**Comment by abeldekat** [comment]
Thanks @folke,

I tested this with dap/nlua, and indeed, the leader d a items are as expected.

I was testing extras/lang/python in combination with dap and observed those operator pending mappings.

If I understand you correctly the "adapters" menu is only in "real" use when dap/nlua is included. Would it make sense to create submenu "leader d a" in dap/nlua instead of dap/core? I do not see any other file in "extras" defining "leader d a" keys.

**Comment by folke** [comment]
It's pretty much a bug in which-key. Empty groups should simply not be shown. Low prio issue tbh

**Comment by abeldekat** [comment]
I understand. Thanks for your time!
