### ISSUE TITLE
bug: disabling default keymaps and autocmds not working

### ISSUE THREAD

**Issue by Keep-Simple** [LazyVim/LazyVim#1128]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0

### Operating system/version

Macos

### Describe the bug

lua/lazyvim/config/init.lua, 

opts.defaults isn't used, autocmds and keybinding are always sourced

### Steps To Reproduce

-

### Expected Behavior

opts.defaults let me disable default settings

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
Have you read the [docs](https://www.lazyvim.org/configuration#default-settings)? These options should be configured in a spec for LazyVim.

**Comment by Keep-Simple** [comment]
they aren't respected, actual code of LazyVim ignores it

**Comment by dpetka2001** [comment]
I just put in `/lua/plugins/LazyVim.lua` the following
```lua
return {
  {
    "LazyVim/LazyVim",
    opts = {
      defaults = {
        keymaps = false,
      },
    },
  },
}
```
and the default keymaps were correctly disabled. But only the default keymaps that LazyVim sets up, not the keymaps of plugins, so keep that in mind.

**Comment by Keep-Simple** [comment]
works now, thanks!

**Comment by Keep-Simple** [comment]
found how lazynvim does conditional loading, missed it
sorry for the issue :)
