### ISSUE TITLE
bug: guifont is always set to Firacode before user options are loaded.

### ISSUE THREAD

**Issue by Mehgugs** [LazyVim/LazyVim#113]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

v0.8.2

### Operating system/version

Windows 10 Home x86_64

### Describe the bug

"Unknown font: FiraCode Nerd Font" is logged whenever I start up. I already have a nerd front that I want to use which I've set in my options but the defaults always try to set the guifont regardless. 

### Steps To Reproduce

- Dont have the default nerd font installed.
- Set a suitable guifont in your options.lua

### Expected Behavior

No missing font error if you've configured your own font.

**Comment by folke** [comment]
That guifont shouldn't be set. Removed it

**Comment by Mehgugs** [comment]
Thanks a lot!
