### ISSUE TITLE
bug: `z-=` suggestion window won't auto close after choice has been inserted

### ISSUE THREAD

**Issue by mangkoran** [LazyVim/LazyVim#1136]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

Arch Linux

### Describe the bug

`z-=` suggestion window won't auto close after choice has been inserted.

![image](https://github.com/LazyVim/LazyVim/assets/57625126/90c4749f-44f2-4de0-93a5-8ea8cdbdb1a1)

### Steps To Reproduce

1. `z-=` on top of any word
2. Select the choice and press <CR>

### Expected Behavior

`z-=` suggestion window should auto close after choice has been inserted.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```
---
Note:
Not reproable using issue template's `repro.lua` (above) as it works normally.
![image](https://github.com/LazyVim/LazyVim/assets/57625126/d7e8cf6d-7ff1-4bd6-bc49-a84c2fffcee4)

![image](https://github.com/LazyVim/LazyVim/assets/57625126/77c40861-4596-4b4c-a777-fe90a1f8b9de)

However it is reproable using https://github.com/LazyVim/starter/commit/a13d5c90769ce6177d1e27b46efd967ed52c1d68
![image](https://github.com/LazyVim/LazyVim/assets/57625126/90c4749f-44f2-4de0-93a5-8ea8cdbdb1a1)

**Comment by folke** [comment]
fixed upstream

**Comment by mangkoran** [comment]
Thank you! May I know which plugin did this?
