### ISSUE TITLE
feature: Which Font do you use exactly in LazyVim

### ISSUE THREAD

**Issue by kuki-xie** [LazyVim/LazyVim#1139]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

# Please list the exactly suggested font in the lazyVim website.
Now when i install the lazyvim, there exits a problem on the icons because the nerd-font i download.

### Describe the solution you'd like

list the exactly suggested font in the lazyVim website

### Describe alternatives you've considered

Just tell us the nerd-font you suggest to install.

**Comment by folke** [comment]
It's listed in the requirements on the website

**Comment by kuki-xie** [comment]
yeah i have noticed that but when i download nerd font such as Hack Nerd Font，3270 nerd font which version> 3.0. it has problems
 To show the icon before Find file(when I type nvim and loaded in the window)

发自我的 iPhone

在 2023年7月15日，17:09，Folke Lemaitre ***@***.***> 写道：

﻿

It's listed in the requirements on the website

**Comment by kuki-xie** [comment]
[截屏2023-07-15 17.17.01.png]
The font I use is above.
But there exits problems to show the icon before Find File
[截屏2023-07-15 17.18.55.png]

2023年7月15日 17:08，Folke Lemaitre ***@***.***> 写道：



Closed #1139<https://github.com/LazyVim/LazyVim/issues/1139> as not planned.

**Comment by folke** [comment]
Then it means your terminal is not using the Nerd Font v3

**Comment by Siddaarth** [comment]
I think it is a issue when using iTerm2, since when I launch lazy vim on my default mac terminal, I do not experience the search icon loads normally. I also saw someone on discussion with the exact issue. This is despite using Nerd Font V3.

**Comment by tjwelde** [comment]
Same issue for me using iterm2. Works in macos Terminal.
Has anyone found a solution to this?

**Comment by tjwelde** [comment]
Seems like there is a fix in a nightly build of iTerm2: https://github.com/ryanoasis/nerd-fonts/issues/1149#issuecomment-1475762974

**Comment by cerebrl** [comment]
I personally just change the config for the "dashboard" to use a glyph that renders without issue in my iTerm2: https://github.com/cerebrl/nvim/blob/main/lua/plugins/dashboard.lua. For the "magnifying glass" icon specifically, I use `F0349` from NerdFont symbols. 

![CleanShot 2023-11-11 at 10 26 50](https://github.com/LazyVim/LazyVim/assets/3070458/695ae3d1-e87f-40ea-bbad-3e1b815da148)

**Comment by tjwelde** [comment]
That's very helpful. thanks.
I changed the code from your `dashboard.lua` file to just change the icon like this:
```
return {
  {
    "nvimdev/dashboard-nvim",
    opts = function(_, options)
      options.config.center[1].icon = "󰍉 "
    end,
  },
}
```
In case someone else wants to just change the icon.
