### ISSUE TITLE
bug: Too long LSP Hint in a single line

### ISSUE THREAD

**Issue by BreezyMain** [LazyVim/LazyVim#1146]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1 Release

### Operating system/version

Archlinux Rolling

### Describe the bug

![image](https://github.com/LazyVim/LazyVim/assets/61371380/1a71e59c-260f-4e5b-87ad-8fa4298a23fd)
![image](https://github.com/LazyVim/LazyVim/assets/61371380/e2864344-72e5-45e4-8b0c-8d945adf55a0)

It seems caused by incorrect lsp configuration, or lsp hint need extra handle.

### Steps To Reproduce

1. Write any code in lazyvim
2. Check lsp hint

### Expected Behavior

LSP Hints that are too long need to be displayed in a floating window or some other suitable container.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
This works as it should.

To get the full details of a diagnostics, you can go to it with `<leader>cd`

**Comment by BreezyMain** [comment]
> 
Thank you very much and I apologize for wasting your valuable time.

**Comment by BreezyMain** [comment]
> This works as it should.
> 
> To get the full details of a diagnostics, you can go to it with `<leader>cd`

Thank you very much and I apologize for wasting your valuable time.

**Comment by folke** [comment]
You can also quickly go to the next/prev diagnostic with `]d` and `[d`. That will go to the next location and show a popup
