### ISSUE TITLE
feature: Easier way to disable groups of LazyVim default whichkey keymaps

### ISSUE THREAD

**Issue by shaun-mathew** [LazyVim/LazyVim#1155]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

I'm trying to disable the <leader><Tab> mappings provided in the default config. Currently, I'm just hiding the group in whichkey and disabling each of the default keymaps in the keymaps config file.

### Describe the solution you'd like

Ideally, something along the lines of this:

```lua
return {
   "folke/which-key.nvim",
   opts = function(_, opts)
      opts.defaults["<leader><Tab>"] = nil
   end
}
```

If nil is specified, it would disable all keymaps under that group. Currently, it just sets the group name to "+prefix", but preserves all the mappings.

### Describe alternatives you've considered

Currently, I'm doing the following.:

plugins/overrides.lua
```lua
return {
   "folke/which-key.nvim",
   opts = function(_, opts)
      opts.defaults["<leader><Tab>"] = "which_key_ignore"
   end
}
```

config/keymaps.lua
```lua
-- For each keymap under the whichkey group, I disable it using the nvim_api
vim.api.nvim_del_keymap("n", "<Leader><Tab><Tab>")
vim.api.nvim_del_keymap("n", "<Leader><Tab>[")
vim.api.nvim_del_keymap("n", "<Leader><Tab>]")
vim.api.nvim_del_keymap("n", "<Leader><Tab>d")
vim.api.nvim_del_keymap("n", "<Leader><Tab>f")
vim.api.nvim_del_keymap("n", "<Leader><Tab>l")
```

If there is a preferred way of doing this that is a bit more succinct and already supported by whichkey/lazyvim, then that's fine as well.

**Comment by dpetka2001** [comment]
For the default ones from Lazyvim only you can do as described in the [docs](https://www.lazyvim.org/configuration#default-settings). For the plugin keymaps, you would have to do it from each plugin itself.
