### ISSUE TITLE
bug: trailing search character corrupt

### ISSUE THREAD

**Issue by sdenovan** [LazyVim/LazyVim#1157]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0 (appimage)

### Operating system/version

Ubuntu 23.04

### Describe the bug

When searching, the first character following a match is shown with a different color and becomes a different character. After hitting enter to complete the search, the search matches are shown properly.

I'm using UbuntuMono Nerd Font but have also tried other monospaced fonts including JetBrains Mono Nerd Font (all the same). 

I tried changing the color scheme from the default to gruvbox but the issue remained (just a different color).

I've tried a full update of Lazy and Mason as well as a clean re-install with no changes to the base config (today).

I'm using Kitty but observed the same issue in the default Ubuntu Gnome terminal.

Note the search below for `fi` as an example:
![image](https://github.com/LazyVim/LazyVim/assets/18961389/e10ff5fe-7899-4fb0-929d-0d227959f083)

Happy to try any suggestions or help debug further. Thanks for the great project!

### Steps To Reproduce

1. Clean install
2. Search for `fi` on dashboard (though not specific to the dashboard or search term)

### Expected Behavior

Trailing character should not highlight/change.

**Comment by folke** [comment]
Those are jump labels from the `flash.nvim` plugin. In your screenshot, typing `j` would have jumped to config
