### ISSUE TITLE
feature: lazy load lsp/null-ls source by files type

### ISSUE THREAD

**Issue by tuanbass** [LazyVim/LazyVim#1161]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

I work on different projects using different programming language (js, ts, go, rust...) . For each, I configured a different sources of LSP and/or Null-ls methods. 

Each time, when I try to open a source file (.ts for example), LSP/Null-ls sources for go, rust is also loaded. 
Is there anyway to have them lazily loaded? 

### Describe the solution you'd like

Lazyload the sources on FileType event.

### Describe alternatives you've considered

N/A

**Comment by folke** [comment]
nope, since the sources contain information on when to load the lsp client.
