### ISSUE TITLE
bug: telescope <Tab> <S-Tab> weird behaviors 

### ISSUE THREAD

**Issue by hunterliao29** [LazyVim/LazyVim#117]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.2

### Operating system/version

MacOS 13.2

### Describe the bug

hitting `<Tab>` or `<S-Tab>` inside telescope windows will cause search result to "refresh", change the search scope or rearrange result list.

### Steps To Reproduce

1. open nvim in home dir
2. `<leader><leader>` in to file picker
3. press `<Tab>`

### Expected Behavior

move down/up the searching list without change search scope and rearrange results

### Repro

```Lua
clean install.
```

**Comment by folke** [comment]
Fixed! That one was tricky to find. I totally forgot `<c-i>` is the same as `<tab>`. And that was bound to find files including ignored files. Changed it to `<a-i>` instead.
