### ISSUE TITLE
bug: `require` doesn't search the whole of `lua/` folder

### ISSUE THREAD

**Issue by plaukiu** [LazyVim/LazyVim#1172]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.1

### Operating system/version

MacOS 13.4.1

### Describe the bug

```
~/.config/nvim/lua:
- config
  - autocmds.lua
  - keymaps.lua
  - lazy.lua
  - options.lua
- plugins
  -...
- func
  - movement.lua 
```

`require("func/movement")` should work. it doesn't. only relative path does.

here's the error
```
E5113: Error while calling lua chunk: /Users/<>/.config/nvim/lua/config/keymaps.lua:10: module 'func/movement' not found:
    no field package.preload['func/movement']
cache_loader: module func/movement not found
cache_loader_lib: module func/movement not found
    no file './func/movement.lua'
    no file '/opt/homebrew/share/luajit-2.1.0-beta3/func/movement.lua'
    no file '/usr/local/share/lua/5.1/func/movement.lua'
    no file '/usr/local/share/lua/5.1/func/movement/init.lua'
    no file '/opt/homebrew/share/lua/5.1/func/movement.lua'
    no file '/opt/homebrew/share/lua/5.1/func/movement/init.lua'
    no file './func/movement.so'
    no file '/usr/local/lib/lua/5.1/func/movement.so'
    no file '/opt/homebrew/lib/lua/5.1/func/movement.so'
    no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
    [C]: in function 'require'
    /Users/<>/.config/nvim/lua/config/keymaps.lua:10: in main chunk
```
It should check `~/.config/nvim/lua`, but it doesn't.

This same folder structure works fine in my config sans LazyVim.

### Steps To Reproduce

- Create folder `x` in `~/.config/nvim/lua`. 
- Add `y.lua` file to it.
- Add `local y = {}; return y`
- `require("x/y")` from any other file in `~/.config/nvim/lua`
- Observe error.

### Expected Behavior

`require 'x/y'` has to retrieve modules from any file in `~/.config/nvim/lua` folder and its subfolders.

**Comment by plaukiu** [comment]
No, in lua `"a.b"` is equivalent to `"a/b"`

It just started working. I just swapped the config with my own one a few times. Go figure.

**Comment by dpetka2001** [comment]
I had never seen that before, so I just assumed that it had to be a period between the path components. Tnx for clearing that out. Good to know.
