### ISSUE TITLE
feature: toggle format for current buffer filetype

### ISSUE THREAD

**Issue by amaanq** [LazyVim/LazyVim#1176]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Oftentimes I'm in projects that leverage a combination of multiple languages, e.g. the project might contain a combination of C, Rust, JS, Python, Bash, and I might want to disable my formatting for C and Bash given that there's several format styles out there. Normally this would be fine with a file like .clang-format or an uncrustify config in the project but oftentimes people don't typically add those for these languages.

### Describe the solution you'd like

It'd be a huge benefit to have say `<leader>ut` toggle formatting for specific filetypes (it should toggle the current buffer's ft)

### Describe alternatives you've considered

I'd like to implement it myself, but my Lua isn't the best - though I'm thinking just using a table to map ft to bools would be easy enough to check for this when formatting, and when globally toggling set all the entries to the global value as a sort of "reset", or whatever you think is best

**Comment by folke** [comment]
Check https://www.lazyvim.org/configuration/tips#disable-autoformat-for-some-buffers

You can implement this yourself by keeping track of disabled filetypes and then have an autocmd that sets the buffer local vairable

**Comment by amaanq** [comment]
That is good enough (with some path detection added), but it'd be nicer to have that in a per project level (in my own C/Bash/whatever projects my formatting style would be used)
