### ISSUE TITLE
bug: <leader>/ telescope keymap being eclipsed by <space>/ 

### ISSUE THREAD

**Issue by ubmit** [LazyVim/LazyVim#1179]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0

### Operating system/version

MacOS 13.3.1 (a) (22E772610a)

### Describe the bug

I used to use `<leader>st` to search for text within my project, but since I started working on a monorepo, I realized that this keymap wouldn't search form the `root dir` whenever I'm inside a package of the monorepo. So, [according to the docs](https://www.lazyvim.org/keymaps#telescopenvim), `<leader>/` would be my solution. However, I find out that whenever I try to use this keymap I end up triggering the comment action, which keymap is `<space>/`. Yes, my `leader` key is `Space`.

Also, `<leader><space>`, which should find files (root dir) doesn't work for me either.

### Steps To Reproduce

1. Open a monorepo project 
2. Open a file inside a package folder
3. Try to trigger search text (root dir) from that buffer

### Expected Behavior

I should be able to search for text (root dir) after using `<leader>/`

**Comment by folke** [comment]
Must be your config. I use that keymap all the time to search

**Comment by ubmit** [comment]
That's strange, because here is my entire `.config/lvim/config.lua` file: 

```
-- Read the docs: https://www.lunarvim.org/docs/configuration
-- Video Tutorials: https://www.youtube.com/watch?v=sFA9kX-Ud_c&list=PLhoH5vyxr6QqGu0i7tt_XoVK9v-KvZ3m6
-- Forum: https://www.reddit.com/r/lunarvim/
-- Discord: https://discord.com/invite/Xb9B4Ny

lvim.colorscheme = "tokyonight-night"
lvim.format_on_save.enabled = true

local formatters = require "lvim.lsp.null-ls.formatters"
formatters.setup {
  { name = "prettierd" },
}

local linters = require "lvim.lsp.null-ls.linters"
linters.setup {
  {
    name = "eslint_d",
    condition = function(utils)
      return utils.root_has_file { ".eslintrc", ".eslintrc.js", ".eslintrc.cjs", '.eslintrc.json' }
    end,
    -- #{m}: message, #{s}: source name (defaults to null-ls), #{c}: code (if available)
    diagnostics_format = '#{m} eslint(#{c})',
  },
}

table.insert(lvim.plugins, {
  "zbirenbaum/copilot-cmp",
  event = "InsertEnter",
  dependencies = { "zbirenbaum/copilot.lua" },
  config = function()
    vim.defer_fn(function()
      require("copilot").setup()     -- https://github.com/zbirenbaum/copilot.lua/blob/master/README.md#setup-and-configuration
      require("copilot_cmp").setup() -- https://github.com/zbirenbaum/copilot-cmp/blob/master/README.md#configuration
    end, 100)
  end,
})
```

As you can see, there is nothing here related to `telescope` and the mentioned keymaps. Any thoughts?

**Comment by ubmit** [comment]
I'm so sorry @folke! I'm not even using LazyVim... I'm actually using another distro. Haven't used Neovim for a long time, so that's probably why I confused. I'm sorry...
