### ISSUE TITLE
Weird Chinese characters and symbols everywhere

### ISSUE THREAD

**Issue by NightMachinery** [LazyVim/LazyVim#1180]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.1

### Operating system/version

Ubuntu 22.04.2 LTS

### Describe the bug

I have just installed neovim and lazyvim, with no personal config (just a colorscheme change). I see a bunch of Chinese characters:

<img width="1272" alt="image" src="https://github.com/LazyVim/LazyVim/assets/36224762/81eb439a-df99-4e13-a2b0-f956a412a9ad">

### Steps To Reproduce

_

### Expected Behavior

_

**Comment by folke** [comment]
you need a proper terminal and nerd font 3.0. Please check the requirements on the LazyVim webiste
