### ISSUE TITLE
bug: Not showing diagnostics in Python file unless a line is deleted

### ISSUE THREAD

**Issue by roberte777** [LazyVim/LazyVim#1183]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0

### Operating system/version

Windows 11 and MacOS

### Describe the bug

I have a base lazyvim config with the Python extras. No other changes. Whenever I write a line of code in a Python file that should produce an error, I do not get error diagnostics. I only get error diagnostics after deleting a line. 

This video should help illustrate the issue. I write sleep(), which should be an error since I didn't import it. However, I do not get any visual diagnostics until after I add a line and delete it.

https://github.com/LazyVim/LazyVim/assets/33569440/50bc9388-ebd4-4cb6-9dfc-607cabfef325

### Steps To Reproduce

1. Open a new Python file
2. write sleep() or any line that would result in diagnostic that should be shown
3. exit insert and save

### Expected Behavior

I would expect the red squiggles and ghost text to tell me I have an error.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Can't reproduce this with the python extra.

**Comment by roberte777** [comment]
@folke I've reproduced this on 3 different machines, and swapped to my own personal config with the same tools installed and not found the issue. I'm not suggesting you're incorrect, but since you're so experienced I was hoping you might be able to point me in the right direction to solve this problem :D

**Comment by folke** [comment]
no idea. I don't use python myself

**Comment by roberte777** [comment]
> no idea. I don't use python myself

I’ve also reproduced this in the docker container suggested on your website after installing pyenv and using nvm to install pyright. May I ask how you tried to reproduce? Did you use a docker container? Trying to narrow down differences to discover a cause.

**Comment by puppyapple** [comment]
same issue here

**Comment by folke** [comment]
must be a pyright issue then. Either way, this is not a LazyVim issue.

**Comment by roberte777** [comment]
> must be a pyright issue then. Either way, this is not a LazyVim issue.

Can't be a pyright issue, cannot reproduce in my own config that uses same verisons. 

@puppyapple will you let me know if you discover a cause or a fix?

**Comment by puppyapple** [comment]
@folke 
I've tried the following experiments under the same  original configs only with { import = "lazyvim.plugins.extras.lang.python" } added to lazy.nvim.
1. Macbook air M1: pyright diagnostic infomation show well
2. Ubuntu 22.04: no pyright infomation displays
3. Ubuntu 22.04 with other pluging that support pyright lsp(Coc.nvim with coc-pyright): pyright diagnostic infomation show well

BTW, I used Lunarvim before and want to move to LazyVim. And Lunarvim also uses nvim-lspconfig to manage pyright lsp for python, the diagnostic works well in my Ubuntu.

So if it is possible there are some compatibility issue in the python config on Linux? @folke

**Comment by puppyapple** [comment]
> > must be a pyright issue then. Either way, this is not a LazyVim issue.
> 
> Can't be a pyright issue, cannot reproduce in my own config that uses same verisons.
> 
> @puppyapple will you let me know if you discover a cause or a fix?

@roberte777 Unfortunately, no progress for now...

**Comment by puppyapple** [comment]
I found my situation is a little bit different @roberte777 
<img width="1597" alt="image" src="https://github.com/LazyVim/LazyVim/assets/33118185/778169aa-50ae-4042-9c47-2da20076f834">
pyright seems to report some of the diagnostic like not defined but does not do any type checking or memberaccess check.  But it give all error when using in cmdline. So maybe it is not a  pyright issue? @folke

**Comment by folke** [comment]
look, this is definitely not a LazyVim issue. It's either going to be a bug in Neovim diagnostics, Neovim's lsp, lspconfig or pyright.

There's also some work on Neovim done to support pull diagnostcis, so maybe that's somehow causing issues.

LazyVim does nothing special for diagnostics for pyright.

When I tested it, I didnt see this issue. Maybe different pyright version? No idea.

**Comment by puppyapple** [comment]
```python
local pyright_opts = {
  root_dir = function(fname)
    local util = require("lspconfig.util")
    local root_files = {
      "pyproject.toml",
      "setup.py",
      "setup.cfg",
      "requirements.txt",
      "Pipfile",
      "manage.py",
      "pyrightconfig.json",
    }
    return util.root_pattern(unpack(root_files))(fname) or util.root_pattern(".git")(fname) or util.path.dirname(fname)
  end,
  settings = {
    pyright = {
      disableLanguageServices = false,
      disableOrganizeImports = false,
    },
    python = {
      analysis = {
        autoSearchPaths = true,
        diagnosticMode = "workspace",
        useLibraryCodeForTypes = true,
        reportGeneralTypeIssues = true,
      },
    },
  },
  single_file_support = true,
}
return {
  "neovim/nvim-lspconfig",
  init = function()
    local keys = require("lazyvim.plugins.lsp.keymaps").get()
    keys[#keys + 1] = { "<leader>ca", false }
    -- change a keymap
    keys[#keys + 1] = { "<leader>cA", false }
    keys[#keys + 1] = { "gr", false }
    keys[#keys + 1] = { "gd", false }
    keys[#keys + 1] = { "<leader>cd", false }
    keys[#keys + 1] = { "<leader>cf", false }
    keys[#keys + 1] = { "<leader>cl", false }
    keys[#keys + 1] = { "<leader>cr", false }
    keys[#keys + 1] = {
      "<leader>la",
      vim.lsp.buf.code_action,
      desc = "Code Action",
      mode = { "n", "v" },
      has = "codeAction",
    }
    keys[#keys + 1] = { "<leader>lr", vim.lsp.buf.rename, desc = "Rename", has = "rename" }
  end,
  opts = {
    servers = {
      pyright = pyright_opts,
      ruff_lsp = {},
    },
    setup = {
    },
  },
  config = function(_, opts)
    require('lspconfig')["pyright"].setup({ pyright_opts })
  end
}
```
New Progress:
I add config with function that mannually setup pyright with my own opts like showed above(So I think the default config https://www.lazyvim.org/plugins/lsp here for nvim-lspconfig is overrided if I understand well). Then I got all the diagnostics from pyright. @folke

**Comment by folke** [comment]
does your project have a .vscode folder with settings?

**Comment by puppyapple** [comment]
No. For testing I created a brand  new and clean project.发自我的 iPhone在 2023年7月26日，18:41，Folke Lemaitre ***@***.***> 写道：﻿
does your project have a .vscode folder with settings?

**Comment by roberte777** [comment]
Thanks for your continued work on this @puppyapple! I admit I stopped looking because I didn’t want to make Folke mad when he’s done great things with LazyVim. However, he is correct in the sense this still seems like it’s not a LazyVim issue, should I open an issue in neoconf instead?

**Comment by roberte777** [comment]
@puppyapple I am seeing the same issue with python but also typescript files in lunarvim. They use nlsp settings but not neoconf. I wonder if there's some similarity between those two plugins that is causing the issue?

**Comment by puppyapple** [comment]
> @puppyapple I am seeing the same issue with python but also typescript files in lunarvim. They use nlsp settings but not neoconf. I wonder if there's some similarity between those two plugins that is causing the issue?

I'm not an expert of nvim plugins so I could not say what really happened here. Mayby leave this to the experts. (BTW, I used to work well with Lunarvim without issue above.)
The other thing is that I think your issue in the video is a little different from mine. Have you tried to disable the neoconf.nvim to see what will happen?

**Comment by z3z1ma** [comment]
I was having an inexplicable issue around lsp's using default python extra as well as various custom configs
I deleted the `.vscode` directory, and suddenly everything works fine
Not sure why that worked but posting here just in case. Thanks for the work on LazyVim, top notch, hope to save others from this gotcha.

**Comment by roberte777** [comment]
> I was having an inexplicable issue around lsp's using default python extra as well as various custom configs
> 
> I deleted the `.vscode` directory, and suddenly everything works fine
> 
> Not sure why that worked but posting here just in case. Thanks for the work on LazyVim, top notch, hope to save others from this gotcha.

Thanks for the tips, I'm sure this will help someone out in the future. However, I don't have a vscode folder.

**Comment by ramfattah** [comment]
I'm facing the same issue in C# file. 

Actually the whole diagnostics today has been faulty. Not sure if there has been breaking changes or something...


Any updates on this? 

To reproduce, clone the lazy vim starter template and test the UI Diagnostics.

**Comment by roberte777** [comment]
> I'm facing the same issue in C# file. 
> 
> 
> 
> Actually the whole diagnostics today has been faulty. Not sure if there has been breaking changes or something...
> 
> 
> 
> 
> 
> Any updates on this? 
> 
> 
> 
> To reproduce, clone the lazy vim starter template and test the UI Diagnostics.

No updates from me, I've just been living with it D: I'm not really sure where to start looking for the solution to this issue. I'm not even unwilling, I've been trying for a month, I just don't have the background

**Comment by ramfattah** [comment]
@roberte777, 

I switched to "[AstroVim](https://astronvim.com/)" and it's working without issues so far.
