### ISSUE TITLE
A few vim.opt options are already nvim defaults

### ISSUE THREAD

**Issue by adrian5** [LazyVim/LazyVim#119]
Some of the options in [options.lua](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua) are being set to their default values and could be omitted.

`opt.shortmess` can be appended to for brevity when it's a _superset_ of the defaults, e.g.:

```lua
opt.shortmess:append { c = true, W = true}
```

Just pointing that out, you may have your own reasons/preferences.

**Comment by folke** [comment]
Great. Feel free to submit a pr!

**Comment by adrian5** [comment]
Ok, will do!
