### ISSUE TITLE
bug: Updating packages cannot communicate with agent.

### ISSUE THREAD

**Issue by njnygaard** [LazyVim/LazyVim#1191]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.1

### Operating system/version

Arch (2023-07-22)

### Describe the bug

![image](https://github.com/LazyVim/LazyVim/assets/4606342/44acb89a-cd11-44da-baad-4e41276eb4eb)
Updating packages fails to communicate with the running agent but git operations outside nvim in the same terminal session work fine.

Any advice is appreciated. I only seem to have this issue on the update screen. During the first installation process, I had to enter a password in to pinentry several times, but it was able to get through the process. Every time I try to update, it asks for pinentry for each package.

### Steps To Reproduce

1. System configured with gpg-agent and sshcontrol to present authentication subkey for ssh.
2. `lU` in nvim to update packages.
3. all updates fail initially and present graphical pinentry for each operation.

### Expected Behavior

Ideally it should connect to the running socket like all other sessions do once pinentry is completed once.

### Repro

```Lua
-- N/A Vanilla
```

**Comment by folke** [comment]
That's really weird, since those repos are public.

No idea, but 100% certain something in your config.

**Comment by tricinel** [comment]
I've had a similar issue. I use a Yubikey. The issue was indeed in the git config. This is the bit that caused problems:
```
[url "git@github.com:"]
  insteadOf = "https://github.com/"
```

Without this, it works. Not sure why though.

Hope it helps others.
