### ISSUE TITLE
feature: consider adding 'leader keymap' to the getting started docs

### ISSUE THREAD

**Issue by notDavid** [LazyVim/LazyVim#1199]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Hi there, as a new user/noob i thought it would be useful to suggest an improvement to the docs;

After installing and reading the [keymaps](https://www.lazyvim.org/keymaps) i was confused with, and searching for, the `<leader>` key. It currently says:

> Just press any key like \<space\> and you'll see a popup with all possible keymaps starting with \<space\>.

However, at that point, i wasn't aware that `<space>` actually *is* the leader key. This is also not mentioned in the next section, [General](https://www.lazyvim.org/keymaps#general), where all the keymaps are listed.

So i took me like half an hour to eventually find it in the [Options](https://www.lazyvim.org/configuration/general#options) after clicking on **Default Options**.

### Describe the solution you'd like

Please consider adding 

**Key = `space`
Description = Leader**

as first item in the [General](https://www.lazyvim.org/keymaps#general) keymaps list.

### Describe alternatives you've considered

-

**Comment by appelgriebsch** [comment]
Please check the official documentation page for default keyboard mappings: https://www.lazyvim.org/keymaps.

**Comment by skoch13** [comment]
It is being mentioned in `Default options` [here](https://www.lazyvim.org/configuration/general#options). To my mind it will be hard(and might be not that necessary) to mention everything within the docs including the defaults provided by the maintainer.

**Comment by folke** [comment]
Just pushed an update to include this on https://www.lazyvim.org/keymaps

Will be loive in a couple of minutes
