### ISSUE TITLE
feature: code refactoring tools

### ISSUE THREAD

**Issue by leCoq42** [LazyVim/LazyVim#1211]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Are there currently tools available for code refactoring within Lazyvim? 

### Describe the solution you'd like

A plugin like integrated like: https://github.com/ThePrimeagen/refactoring.nvim

### Describe alternatives you've considered

-

**Comment by folke** [comment]
no, but as you found, you can use that plugin (which is not that great to be honest).

Most lsps provide refactoring through code actions. `<leader>ca`
