### ISSUE TITLE
bug: java.lang extention not working with neovim 0.9.1

### ISSUE THREAD

**Issue by ys-kalyakin** [LazyVim/LazyVim#1215]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

Manjaro Linux

### Describe the bug

See:
https://github.com/LazyVim/LazyVim/issues/1207

neovim 0.9.1 does not support the vim.fs.joinpath function, but this function is used in extension java.lang

"-configuration",
**vim.fs.joinpath(jdtls_cache_dir, "config"),**
"-data",
**vim.fs.joinpath(jdtls_cache_dir, "workspace"),**

### Steps To Reproduce

https://github.com/LazyVim/LazyVim/issues/1207

### Expected Behavior

java.lang extention working with neovim >= 0.8.0

**Comment by dpetka2001** [comment]
Didn't you already post an issue about this and was fixed?
