### ISSUE TITLE
bug: vat/vit yit/yat etc don't work as intended 

### ISSUE THREAD

**Issue by StitiFatah** [LazyVim/LazyVim#1217]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

Archlinux

### Describe the bug

 vat/vit  and other at/it combination  don't work like normally in neovim, if the tags are spread into multiple lines they seem to select every parent nodes and not just what's inside the tags  

### Steps To Reproduce

try the `vat` motion on a fresh lazyvim config

### Expected Behavior

Normal `it/at` behavior

### Repro

Here are two screen recording with the `vat` motion 

With stock lazyvim :  https://github.com/LazyVim/LazyVim/assets/68331131/653a4849-4a4b-469c-a12a-a86ad7677d65

With stock neovim :  https://github.com/LazyVim/LazyVim/assets/68331131/20886e4c-6501-47e2-939b-71b52730baea

**Comment by loqusion** [comment]
I use the following overrides in my `mini.ai` config, they have worked well for me in the past:

```lua
{
  custom_textobjects = {
    t = { "<(%w-)%f[^<%w][^<>]->.-</%1>", "^<.->%s*().-()%s*</[^/]->$" },
    T = { "<(%w-)%f[^<%w][^<>]->.-</%1>", "^<.->().*()</[^/]->$" },
  },
}
```

**Comment by folke** [comment]
right, report to mini.ai if you think this is a bug

**Comment by dpetka2001** [comment]
This is a known limitation of `mini.ai`, as the maintainer himself has also admitted (because `mini.ai` uses lua patterns and some false positives are expected to exist). He recommends the [answer])https://github.com/echasnovski/mini.nvim/issues/110#issuecomment-1212277863) in this thread. You could take a look and see if it works for you. The answer is for `.html` files, but you could customize it for other filetypes you work with as well I imagine.

**Comment by folke** [comment]
LazyVim already has that treesitter mapping, so instead of vit, one could do vif I think

**Comment by StitiFatah** [comment]
> This is a known limitation of `mini.ai`, as the maintainer himself has also admitted (because `mini.ai` uses lua patterns and some false positives are expected to exist). He recommends the [answer](https://github.com/echasnovski/mini.nvim/issues/110#issuecomment-1212277863) in this thread. You could take a look and see if it works for you. The answer is for `.html` files, but you could customize it for other filetypes you work with as well I imagine.

Thanks for the indications, I'm however just gonna disable the plugin since I don't use its functionalities anyway
