### ISSUE TITLE
bug: Quick undos and redos cause a neovim to crash

### ISSUE THREAD

**Issue by paudrow** [LazyVim/LazyVim#1220]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

MacOS 13.3.1

### Describe the bug

If I undo and redo quickly, Neovim crashes. This doesn't happen with unmodified Neovim. I assume it's one of the plugins. I disabled any plugins that I added so as to make sure they don't introduce this error.

This happens especially often when shifting many lines at once, for example, with
```
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv", { desc = "shift lines down" })
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv", { desc = "shift line up" })
```

### Steps To Reproduce

1. Have a big file with lots of indentation
2. Shift a lot of lines around
3. Undo and redo changes neovim crashes with a 134 exit code.

Note, this happens especially often for me in markdown files.

### Expected Behavior

I'd expect Neovim not to crash.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here

vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv", { desc = "shift lines down" })
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv", { desc = "shift line up" })

vim.api.nvim_create_autocmd("FileType", {
  -- group = augroup("wrap_spell"),
  pattern = { "markdown" },
  callback = function()
    vim.opt_local.wrap = true
    vim.opt_local.spell = true
    vim.opt_local.tabstop = 2
    vim.opt_local.softtabstop = 2
    vim.opt_local.shiftwidth = 2
    vim.opt_local.foldmethod = "indent"
  end,
})
```

**Comment by folke** [comment]
If neovim crashes, get a stacktrace and report upstream. Not a lazyvim issue.
