### ISSUE TITLE
bug: nvim-colorizer not work

### ISSUE THREAD

**Issue by tkkcc** [LazyVim/LazyVim#1224]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

archlinux

### Describe the bug

hex color on line 4 is not rendered

![image](https://github.com/LazyVim/LazyVim/assets/17373509/e8b8986b-15a9-4346-9ce2-1df12a16fd1d)

### Steps To Reproduce

1. clean install LazyVim
2. add to top of `~/.config/nvim/lua/plugin/example.lua`
```lua
if true then
  vim.opt.termguicolors = true
  local x = "#000FFF"
  return {
    { "norcalli/nvim-colorizer.lua" },
  }
end
```
3. restart nvim, type `I` to install plugin
4. restart nvim again to see if hex color is rendered.

### Expected Behavior

it works if using plain lua require to load nvim-colorizer
![image](https://github.com/LazyVim/LazyVim/assets/17373509/69ed39f0-1c82-41b3-bd9d-ab80c31ff38f)

**Comment by dpetka2001** [comment]
You just installed the plugin, you didn't set it up. Add
```lua
config = function() require("colorizer").setup() end,
```
to your spec and it should work.

**Comment by tkkcc** [comment]
Thanks. it works. I will recheck doc of lazy.nvim.
