### ISSUE TITLE
bug: When Tmux pane is resized, LazyVim jumps to the last nvim tab page

### ISSUE THREAD

**Issue by CallumHoward** [LazyVim/LazyVim#1241]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1 stable

### Operating system/version

MacOS 13.4

### Describe the bug

When in nvim with LazyVim inside Tmux and pane becomes resized, it triggers nvim to show the last nvim tab page. 
* Does not occur in nvim with no config
* Does occur in tmux with no config
* Does occur in fresh LazyVim installed with docker method
* Does occur with Bufferline.nvim disabled
* Does occur in different terminal emulators (Kitty, MacOS Terminal)

### Steps To Reproduce

1. Start new Tmux session with `tmux`
2. Run `nvim +tabe +'norm gt'`
3. Create a new Tmux horizontal split pane with `<C-b>"`

This resizes the Tmux pane that nvim is in. It can also be reproduced by resizing pane with mouse drag or other methods that incidentally resize the pane.

### Expected Behavior

Should remain on first tab page and not change to last tab page when pane is resized.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here

-- no additional config required to reproduce
```

**Comment by dpetka2001** [comment]
It's the `lazyvim_resize_splits` autocommand. If you disable it, it works like you want.

**Comment by CallumHoward** [comment]
Thanks @dpetka2001, disabling it is a sufficient workaround, however it would be nice to still have the resize functionality.

https://github.com/LazyVim/LazyVim/blob/9264c54ae96d1d56f029ad9b561326c7b991c53b/lua/lazyvim/config/autocmds.lua#L22-L27

Would it not be better to modify this to be something like:

```lua
vim.api.nvim_create_autocmd({ "VimResized" }, {
  group = augroup("resize_splits"),
  callback = function()
    local current_tab = vim.fn.tabpagenr()
    vim.cmd("tabdo wincmd =")
    vim.cmd("tabnext " .. current_tab)
  end,
})

```

**Comment by dpetka2001** [comment]
Yes, I think this looks nice. But I'm just a user like you. Don't ask me for any permission. Go submit your PR and the maintainer will decide if it's useful or not. I personally will incorporate your solution to my configuration, since I like the way it works now better. Good luck with your PR!! :smile:

**Comment by CallumHoward** [comment]
@dpetka2001 thanks, have opened it. I saw the "contributor" tag next to your comments and made an incorrect assumption 😅
