### ISSUE TITLE
bug: Auto format on save yields wrong formatting every other time

### ISSUE THREAD

**Issue by Vanluren** [LazyVim/LazyVim#1243]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.1

### Operating system/version

MacOS 13.5 (22G74)

### Describe the bug

Hey, thanks for all the hard work on this! The config works super well!

I have run into what I think is a bug. Whenever I save a `.vue` or `.ts` file which triggers the auto formatting, the code is either formatted so the lint services do not complain or in a format where eslint complains. 

### Steps To Reproduce

1. create a ts file
2. write something that would fail e 
3. save the file and let the auto formatting do it's thing 

### Expected Behavior

The auto formatting produces a valid output every time.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
there's very little info here. You could've at least added the extras you enabled.

If you have the eslint extra, then that may cause issues of you also use prettier as part of eslint. Please check the docs on the lazyvim website for the two different approaches in useing prettier
