### ISSUE TITLE
Error compiling on Windows 

### ISSUE THREAD

**Issue by CCurl** [LazyVim/LazyVim#1244]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1.20230153 (RelWithDebInfo), LuaJIT 2.1.0-beta3, installed using chocolatey

### Operating system/version

Windows 10

### Describe the bug

On my Windows 10 system, I did a clean install of neovim / lazy-vim and followed the startup instructions.

I have Visual Studio, but I also installed llvm (16.0.6) using chocolatey.

I also have lazygit, and ripgrep installed (also via chocolatey)

When I start nvim, after about 10 seconds or so, a whole slew of errors of different sorts are printed to the screen.

Where can I find the logs that would capture the errors so that I can post them here?

### Steps To Reproduce

1. Follow the startup instructions.
2. Enable the typescript, json, and mini-animate plugins in (lazy.lua).
3. Start nvim.

### Expected Behavior

No errors

### Repro

```Lua
-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
```

**Comment by folke** [comment]
It would help to see the actual errors?

**Comment by CCurl** [comment]
I have been unsuccessful finding a log wile where they are written. Hence the question in my post:

"Where can I find the logs that would capture the errors so that I can post them here?"

**Comment by folke** [comment]
there is no log. I dont even know what errors you are talking about, so how would I know what log they would be in?
a screenshot of the errors is good enough if that's easier.

**Comment by CCurl** [comment]
here are the first few ...
![image](https://github.com/LazyVim/LazyVim/assets/14334380/8b9157c5-11b9-4ab2-9989-d3f4d9daecca)

**Comment by CCurl** [comment]
More ... I have removed the folders and re-run nvim, but i still get errors

![image](https://github.com/LazyVim/LazyVim/assets/14334380/5c41737f-e65a-4e10-98c4-e7cf208fb612)

**Comment by CCurl** [comment]
It's always the tree-sitter stuff. Is it because my version on nvim is too old? Should I use something other than chocolatey to install nvim?

**Comment by folke** [comment]
Best to check for those errors in the nvim-treesitter repo.
I think for Windows, you may have to install something extra and you also have errors on internet access.

There's a link on the lazyvim website requirements to https://github.com/nvim-treesitter/nvim-treesitter#requirements

Read that for windows
