### ISSUE TITLE
bug: Installazion Errors! 

### ISSUE THREAD

**Issue by atomrq** [LazyVim/LazyVim#1246]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0

### Operating system/version

Centos7.9

### Describe the bug

Following the procedures in the repo "Installation" page, I execute "git clone https://github.com/LazyVim/starter ~/.config/nvim", "rm -fr ~/.config/.git", and start nvim

**While I got these Error Message**

Error detected while processing /share/users/jxm/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /share/users/jxm/.config/nvim/lua/config/lazy.lua:9: module 'lazy' not found:
        no field package.preload['lazy']
        no file './lazy.lua'
        no file '/__w/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/lazy.lua'
        no file '/usr/local/share/lua/5.1/lazy.lua'
        no file '/usr/local/share/lua/5.1/lazy/init.lua'
        no file '/__w/neovim/neovim/.deps/usr/share/lua/5.1/lazy.lua'
        no file '/__w/neovim/neovim/.deps/usr/share/lua/5.1/lazy/init.lua'
        no file './lazy.so'
        no file '/usr/local/lib/lua/5.1/lazy.so'
        no file '/__w/neovim/neovim/.deps/usr/lib/lua/5.1/lazy.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /share/users/jxm/.config/nvim/lua/config/lazy.lua:9: in main chunk
        [C]: in function 'require'
        /share/users/jxm/.config/nvim/init.lua:2: in main chunk

### Steps To Reproduce

nvim 0.9.0
centos-7.9

### Expected Behavior

nvim itself works well, while the LazyVim config not.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
that means your inital checkout probably failed due to network errors.

delete `~/.local/share/nvim/lazy` and try again
