### ISSUE TITLE
bug: g:python3_host_prog

### ISSUE THREAD

**Issue by zombie-bear** [LazyVim/LazyVim#1257]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

W11 22H2

### Describe the bug

Not quite a bug (i think), i have this error when i try to save a file "E486: Motif introuvable : python3_host_prog" and when i do a checkhealth it appear  :
"
- `g:python3_host_prog` is not set.  Searching for python in the environment.
- Multiple python executables found.  Set `g:python3_host_prog` to avoid surprises. 
"
i search in nvim and found that i have to add "let g:python3_host_prog = expand('C:\Users\delfe\AppData\Local\Programs\Python\Python310\python.exe')" to my init.vim? or to make this command run when i launch nvim whit lazyvim. (source:https://github.com/Shougo/deoplete.nvim/issues/932)

when i run "let g:python3_host_prog = expand('C:\Users\delfe\AppData\Local\Programs\Python\Python310\python.exe')" in command line in lazyvim, the problem disappear but the change isn't persistant after i quit nvim.

i search for vimrc, init.vim but don't i don't seems to exist, even the file that appear whit the command "vim -v" that return the path to sysinit.vim isn't valid (the file doesn't exist at that path).
i try to add the command to init.lua or creat a plugin but it doesn't work.

### Steps To Reproduce

install python3.10
install nvim
install Lazyvim

### Expected Behavior

i should be able to save file

**Comment by folke** [comment]
you're using a plugin that uses python bindings.

set it in `lua/config/optionsl.lua`

`vim.g.pythion3... `
