### ISSUE TITLE
How how do you turn off auto closing quotes parenthesis etc?

### ISSUE THREAD

**Issue by robby-robby** [LazyVim/LazyVim#1259]
There seems to be an undocumented functionality that is unconventional which is auto-closing brackets and quotes. How do you turn it off?

**Comment by dpetka2001** [comment]
I believe it's `mini.pairs`. You should disable that if you don't want the functionality.

**Comment by rockfruit** [comment]
Do any serious coders actually use this auto-smart-keys stuff?

@robby-robby edit lua/plugins/disabled.lua and add this:

`return { "echasnovski/mini.pairs", enabled = false }`

**Comment by folke** [comment]
> Do any serious coders actually use this auto-smart-keys stuff?
> 
> @robby-robby edit lua/plugins/disabled.lua and add this:
> 
> `return { "echasnovski/mini.pairs", enabled = false }`
> 
> 

Yes, obviously
