### ISSUE TITLE
Failed loading lazyvim.config.keymaps

### ISSUE THREAD

**Issue by joshmedeski** [LazyVim/LazyVim#126]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

v0.8.2

### Operating system/version

MacOS Ventura 13.1 (22C65)

### Describe the bug

New issue on startup with `v1.3.1` of LazyVim

```
Failed loading lazyvim.config.keymaps

...l/share/nvim/lazy/LazyVim/lua/lazyvim/config/keymaps.lua:9: attempt to index local 'keys' (a nil value)

# stacktrace:
  - /LazyVim/lua/lazyvim/config/keymaps.lua:9 _in_ **map**
  - /LazyVim/lua/lazyvim/config/keymaps.lua:15
  - /LazyVim/lua/lazyvim/config/init.lua:124
  - /LazyVim/lua/lazyvim/config/init.lua:123 _in_ **load**
  - /LazyVim/lua/lazyvim/config/init.lua:94 _in_ **setup**
  - /LazyVim/lua/lazyvim/config/init.lua:158 _in_ **__index**
  - gitsigns.lua:1
  - ~/.config/nvim/lua/config/lazy.lua:9
  - ~/.config/nvim/init.lua:2
```

### Steps To Reproduce

Run nvim `v1.3.1`

### Expected Behavior

No errors

**Comment by folke** [comment]
How do you trigger this? What;s in `gitsigngs.lua` on line 1? That's not part of LazyVim.

**Comment by joshmedeski** [comment]
Ah, thanks. I was trying to pull in the icons before returning my gitsigns config.

```
local icons = require("lazyvim.config").icons
return {
  "lewis6991/gitsigns.nvim",
   // ...
}
```

I guess I can't do it that way.
