### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by WernerDrasche** [LazyVim/LazyVim#1263]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

OpenBSD 7.2

### Describe the bug

Crash after about 5 seconds after opening neovim.
![crash](https://github.com/LazyVim/LazyVim/assets/79748606/46690baf-72a0-43f0-b82a-ce6d27a921db)

### Steps To Reproduce

Followed instructions to install (cleaned config, cache etc.)
Ran nvim once (plugins were installed): no crash
Starting the second time it crashes consistently after about 5 seconds.

### Expected Behavior

It  shouldn't crash.

### Repro

```Lua
-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
```

**Comment by amaanq** [comment]
gdb backtrace could be useful

**Comment by WernerDrasche** [comment]
It closes because it apparently receives an exit event inside of multiqueue_process_events().
![src](https://github.com/LazyVim/LazyVim/assets/79748606/a43680b7-f2e7-4995-b297-747e7cf8bc28)
![event](https://github.com/LazyVim/LazyVim/assets/79748606/ca875390-9893-42b9-8601-293124e36158)

**Comment by folke** [comment]
This should be reported to Neovim instead

**Comment by amaanq** [comment]
No stack can happen w/o debug syms or in odd cases with weird archs/vms in my experience, also would be good to break on catch/throws with `catch throw` and `catch catch` but yeah this belongs at neovim
