### ISSUE TITLE
feature: overwrite default keymaps

### ISSUE THREAD

**Issue by joshmedeski** [LazyVim/LazyVim#127]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

I'd like to overwrite `<leader><space>`. I prefer it for code action.

I tried adding a map in `config/keymaps.lua` but it doesn't take.

### Describe the solution you'd like

Overwrite default keymap values.

### Describe alternatives you've considered

I realize I could fork LazyVim and manage items myself, but I don't want to commit to that much maintenance right now.

**Comment by folke** [comment]
https://www.lazyvim.org/configuration/plugins#%EF%B8%8F-adding--disabling-plugin-keymaps

**Comment by joshmedeski** [comment]
I missed that in the docs. Thanks for finding it for me.

**Comment by jin-ahn** [comment]
How do I unmap defaults that are not from a plugin?
For example <leader>wd is delete window. But I what do I need to do if I don't <leader>wd to do anything? I tried removing as much as posssible but now my which-key popup is filled with "prefix" for keys I haven't set.
![image](https://user-images.githubusercontent.com/66384196/216486495-e3b0774c-808d-44a3-b5f6-3a13a3c37f6a.png)

**Comment by jin-ahn** [comment]
@alexkatz i appreciate your tip!! not an elegant solution but it works for me!

@folke what do you think about a feature that allows lazyvim pulling the default keymappings as an option instead?
