### ISSUE TITLE
bug: `smart-split` navigatng faild with lazyvim-starter but works perfect with native lazy.nvim

### ISSUE THREAD

**Issue by qizidog** [LazyVim/LazyVim#1270]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.1 Build type: Release LuaJIT 2.1.0-beta3

### Operating system/version

MacOS 12.6.6 (Apple silicon)

### Describe the bug

[`smart-split`](https://github.com/mrjones2014/smart-splits.nvim/) navigatng faild with lazyvim-starter but works perfect with native lazy.nvim. More related infomation in mrjones2014/smart-splits.nvim#118 and it seems to be caused by LazyVim.

A definitely [Minimal Configuration to Reproduce](https://github.com/qizidog/nvim) is uploaded, I would greatly appreciate it if you could help locate the problem.

@mrjones2014

### Steps To Reproduce

1. Open terminal
2. New tmux session
3. Create a vertical split (left and right) and open nvim in the left side
4. Try to navigate from left nvim to right tmux pane (should work and it does work) (both direction works nvim <-> terminal)
5. Maximize or fullscreen or resize the terminal (Alacritty) with mouse
6. Navigation from nvim -> tmux pane no longer works. (tmux pane -> nvim still works)
7. Change terminal size to original size as just opened (with default shortcut of [Rectangle](https://github.com/rxhanson/Rectangle) crtl+option+backspace) then try navigate, it works again

### Expected Behavior

Just like [christoomey/vim-tmux-navigator](https://www.github.com/christoomey/vim-tmux-navigator), navigating between windows but not wrap.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here


-- [[
A definitely Minimal Configuration to Reproduce is uploaded (https://github.com/qizidog/nvim)
-- ]]
```

**Comment by mrjones2014** [comment]
@abeldekat One detail I don't see specified here that was in the original issue in `smart-splits.nvim` -- navigation stops working after resizing a tmux pane, or resizing the overall terminal window. I am not sure if it's specific to resizing with the mouse or not. I haven't reproduced the issue on my machine yet.

**Comment by qizidog** [comment]
Hey @abeldekat, thanks for replying! 

> 1\. The title of your issue states that navigation failed. In the steps to reproduce you write: "with mouse". Is the mouse crucial? I entered fullscreen using the keyboard...

No, resize with mouse is not crucial, I can reproduce it either with mouse, with rectangle or with yabai. For me, the only key point is tmux pane is resized.


> 2\. Could you run "nvim -u minimal.lua minimal.lua" with the config provided above? Please remove the .repr folder if it exists.

Actually I have tested in two different methods in `init.lua` of [Minimal Configuration to Reproduce](https://github.com/qizidog/nvim) which load only `samrt-splits.nvim` but end with different results.

I will try `minimal.lua` later, maybe after 9 hours since it's too late for me tonight.

**Comment by qizidog** [comment]
> {
>     "mrjones2014/smart-splits.nvim",
>     opts = {
>       at_edge = "wrap",
>     },
>     config = function(_, opts)
>       -- change focus window
>       vim.keymap.set("n", "<C-h>", require("smart-splits").move_cursor_left, { desc = "Move to left window" })
>       vim.keymap.set("n", "<C-j>", require("smart-splits").move_cursor_down, { desc = "Move to down window" })
>       vim.keymap.set("n", "<C-k>", require("smart-splits").move_cursor_up, { desc = "Move to up window" })
>       vim.keymap.set("n", "<C-l>", require("smart-splits").move_cursor_right, { desc = "Move to right window" })
> 
>       -- resize window
>       vim.keymap.set("n", "<C-Left>", require("smart-splits").resize_left, { desc = "smart resize left" })
>       vim.keymap.set("n", "<C-Down>", require("smart-splits").resize_down, { desc = "smart resize down" })
>       vim.keymap.set("n", "<C-Up>", require("smart-splits").resize_up, { desc = "smart resize up" })
>       vim.keymap.set("n", "<C-Right>", require("smart-splits").resize_right, { desc = "smart resize right" })
>       require("smart-splits").setup(opts)
>     end,
>   },

I'm sosososo sorry, the `at_edge` need to be set to `stop`, but I set it with default `wrap` in my `Method 2` in `init.lua`. So I'm not sure whether the method 2 works perfect now, because with `at_edge = wrap`, it always works well even in my computer.

**Comment by qizidog** [comment]
I jumped out of my bed to test the method 2 just now. 😵‍💫 

I have corrected the mistake of `wrap` and it doesn't work in both method 1 and method 2 now.

`minimal.lua` hav been tested, it still doesn't work. 😢 

Maybe a test video will be uploaded later or tomorrow.

**Comment by abeldekat** [comment]
@mrjones2014 @qizidog 

> I have corrected the mistake of wrap and it doesn't work in both method 1 and method 2 now.

Reading the above comments, I think it is save to say that this is not a LazyVim issue, as the issue also arises with just lazy.nvim using option at_edge = stop.
Best regards!
