### ISSUE TITLE
 bug: Cannot find word list "pl.utf-8.spl" or "pl.ascii.spl"

### ISSUE THREAD

**Issue by alteriks** [LazyVim/LazyVim#1274]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.1

### Operating system/version

Linux

### Describe the bug

After enabling spelling, nvim cannot automatically download spl files
![image](https://github.com/LazyVim/LazyVim/assets/6512767/1cabd892-f974-4116-b833-25bcedce8bb5)

### Steps To Reproduce

1. Configure spelling
`lua/config/options.lua
7:opt.spelllang = { "pl", "en" }`
2. Launch nvim to get error

Temporary fix:
1. Enable netrw - comment netrwPlugin in disabled_plugins
lua/config/lazy.lua
45:        "netrwPlugin",
2. Launch vim and accept auto downloading files

### Expected Behavior

LazyVim should provide a way to download spell files.

**Comment by dpetka2001** [comment]
The `netrwPlugin` is already commented in the [starter](https://github.com/LazyVim/starter/blob/main/lua/config/lazy.lua) template. So it should work out of the box. Are you sure you didn't disable it by mistake yourself?

**Comment by abeldekat** [comment]
I can reproduce this behaviour on stock lazyvim starter. Added to options.lua:

`vim.opt.spellang` = { "pl", "en"}

After opening nvim I remain on the starter screen. Enter the command "set spell", or the keystrokes "<leader>us", and empty dialog boxes popup and the error as described occurs.

Note that when nvim is opened with a file, for example "init.lua", the dialogues are fine and the "pl" spell file is installed.

**Comment by dpetka2001** [comment]
I see, I didn't try it out in the starter screen. I always had a file open and executed `:set spell` and the dialogues appeared just fine.
