### ISSUE TITLE
Add commentstring for Typst

### ISSUE THREAD

**Issue by mangkoran** [LazyVim/LazyVim#1277]
I would like to configure commenstring for Typst file (*.typ). Below is my current configuration, but it doesn't work.

`../config/autocmds.lua`
```lua
vim.api.nvim_create_autocmd("FileType", {
  -- group = augroup("commentstring"),
  pattern = {
    "typ",
  },
  -- callback = function()
  --   vim.opt_local.commentstring = "// %s"
  -- end,
  command = "setlocal commentstring=// %s",
})
```

May I know where the problem is?

**Comment by jyuan0** [comment]
Think it should be `pattern = { "typst" }`, or whatever `set ft?` returns in a Typst file.

**Comment by dpetka2001** [comment]
The following worked for me
```lua
vim.api.nvim_create_autocmd("FileType", {
  -- group = augroup("commentstring", { clear = true }),
  pattern = {
    "typst",
  },
  -- callback = function()
  --   vim.opt_local.commentstring = "// %s"
  -- end,
  command = "setlocal commentstring=//%s",
})
```
As @jyuan0 mentioned, `pattern` should be set to either filetype as shown by `set ft?` or a regex pattern such as `*.typ` (which includes the extension of the file). Also notice that in the Ex command you execute, there shouldn't be any space between `//` and `%s`. Whereas if you used the `callback` Lua Api, there can be a `space` between the 2.

**Comment by mangkoran** [comment]
@jyuan0 @dpetka2001 Thank you very much! Both of your suggestions worked for me 😁
