### ISSUE TITLE
bug: bufferline options not being overwritten

### ISSUE THREAD

**Issue by stickperson** [LazyVim/LazyVim#128]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.0

### Operating system/version

MacOS 12.5.1

### Describe the bug

Overriding options for bufferline (and probably _all_ plugins) does not work consistently. According to the [docs](https://www.lazyvim.org/configuration/examples), settings `opts = function() ...` will override all of the default options for a plugin. When I try this with bufferline, the options are randomly ignored.

### Steps To Reproduce

1. clone lazyvim starter template
2. create a `bufferline.lua` file inside of `lua/plugins/` and add the following:

```
return {
  {
    "akinsho/bufferline.nvim",
    event = "VeryLazy",
    opts = function()
      return {
        options = {
          always_show_bufferline = true,
        },
      }
    end,
  },
}
```

### Expected Behavior

The bufferline should always be loaded. This is only the case randomly.

**Comment by folke** [comment]
It looks like the plugin was renamed from `nvim-bufferline.lua` to `bufferline.nvim`, so that's why the options did not apply.

I renamed the plugin to the new name.

**Comment by stickperson** [comment]
Good catch! Thanks.
