### ISSUE TITLE
bug:  dap-python doesn't work on windows

### ISSUE THREAD

**Issue by veiledshadow** [LazyVim/LazyVim#1284]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0

### Operating system/version

Windows 11

### Describe the bug

I try to debug Python by nvim-dap-python on windows but it seems doesn't work. 

I'm user Windows Terminal

When I When I use <leader>db to add a breakpoint and then use the shortcut <leader>dc to debug, the following strange window pops up, 

![strange_windows](https://github.com/LazyVim/LazyVim/assets/60610570/7434e744-6fd3-487d-b2ec-84bbed3e4c74),

and vim displays the following message:

![Info1](https://github.com/LazyVim/LazyVim/assets/60610570/2e64b836-8092-43ee-a5eb-ab90f67fbc11)

![Info2](https://github.com/LazyVim/LazyVim/assets/60610570/72ae4a7c-08c4-46c7-988e-c6c2c34cba12)

I followed the official website's configuration method and added the following content to the `lazy.lua` file:

```lua
    { import = "lazyvim.plugins.extras.dap.core" },
```

and my configuration for python is as follows:

```lua
return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = function(_, opts)
      if type(opts.ensure_installed) == "table" then
        vim.list_extend(opts.ensure_installed, { "ninja", "python", "rst", "toml" })
      end
    end,
  },
  {
    "neovim/nvim-lspconfig",
    opts = {
      servers = {
        pyright = {},
        ruff_lsp = {},
      },
    },
    setup = {
      ruff_lsp = function()
        require("lazyvim.util").on_attach(function(client, _)
          if client.name == "ruff_lsp" then
            -- Disable hover in favor of Pyright
            client.server_capabilities.hoverProvider = false
          end
        end)
      end,
    },
  },

  {
    "williamboman/mason.nvim",
    opts = function(_, opts)
      table.insert(opts.ensure_installed, "black")
    end,
  },

  -- null-ls
  {
    "jose-elias-alvarez/null-ls.nvim",
    dependencies = { "nvim-lua/plenary.nvim" },
    opts = function(_, opts)
      local nls = require("null-ls")
      table.insert(opts.sources, nls.builtins.diagnostics.flake8)
      table.insert(opts.sources, nls.builtins.formatting.black)
    end,
  },

  {
    "nvim-neotest/neotest",
    optional = true,
    dependencies = {
      "nvim-neotest/neotest-python",
    },
    opts = {
      adapters = {
        ["neotest-python"] = {
          -- Here you can specify the settings for the adapter, i.e.
          -- runner = "pytest",
          -- python = ".venv/bin/python",
        },
      },
    },
  },

  {

    "mfussenegger/nvim-dap-python",
    ft = { "python" },
    dependencies = {

      "mfussenegger/nvim-dap",
      -- stylua: ignore
    },

    keys = {
      {
        "<leader>dPt",
        function()
          require("dap-python").test_method()
        end,
        desc = "Debug Method",
      },
      {
        "<leader>dPc",
        function()
          require("dap-python").test_class()
        end,
        desc = "Debug Class",
      },

      config = function()
        local dap = require("dap")
        dap.configurations.python = {
          {
            type = "python",
            request = "launch",
            name = "Launch file",
            program = "${file}",
            pythonPath = function()
              return "D:\\Software\\anaconda3\\python"
            end,
          },
        }

        local dap_python = require("dap-python")
        local dap_python_path = "D:\\Software\\anaconda3\\python"
        vim.api.nvim_echo({ { "Using path for dap-python: " .. dap_python_path, "None" } }, false, {})
        dap_python.setup(dap_python_path)
      end,
    },
  },
}
```
Is this issue caused by Windows/Windows Terminal, or is it due to my incorrect configuration? Could you provide some suggestions.
```

### Steps To Reproduce

1. Download LazyVim on Windows and use Windows Terminal
2. add the following content to the `lazy.lua` file:

```lua
    { import = "lazyvim.plugins.extras.dap.core" },
```
3. add the following configuration in ```plugins.python.lua```
```lua
return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = function(_, opts)
      if type(opts.ensure_installed) == "table" then
        vim.list_extend(opts.ensure_installed, { "ninja", "python", "rst", "toml" })
      end
    end,
  },
  {
    "neovim/nvim-lspconfig",
    opts = {
      servers = {
        pyright = {},
        ruff_lsp = {},
      },
    },
    setup = {
      ruff_lsp = function()
        require("lazyvim.util").on_attach(function(client, _)
          if client.name == "ruff_lsp" then
            -- Disable hover in favor of Pyright
            client.server_capabilities.hoverProvider = false
          end
        end)
      end,
    },
  },

  {
    "williamboman/mason.nvim",
    opts = function(_, opts)
      table.insert(opts.ensure_installed, "black")
    end,
  },

  -- null-ls
  {
    "jose-elias-alvarez/null-ls.nvim",
    dependencies = { "nvim-lua/plenary.nvim" },
    opts = function(_, opts)
      local nls = require("null-ls")
      table.insert(opts.sources, nls.builtins.diagnostics.flake8)
      table.insert(opts.sources, nls.builtins.formatting.black)
    end,
  },

  {
    "nvim-neotest/neotest",
    optional = true,
    dependencies = {
      "nvim-neotest/neotest-python",
    },
    opts = {
      adapters = {
        ["neotest-python"] = {
          -- Here you can specify the settings for the adapter, i.e.
          -- runner = "pytest",
          -- python = ".venv/bin/python",
        },
      },
    },
  },

  {

    "mfussenegger/nvim-dap-python",
    ft = { "python" },
    dependencies = {

      "mfussenegger/nvim-dap",
      -- stylua: ignore
    },

    keys = {
      {
        "<leader>dPt",
        function()
          require("dap-python").test_method()
        end,
        desc = "Debug Method",
      },
      {
        "<leader>dPc",
        function()
          require("dap-python").test_class()
        end,
        desc = "Debug Class",
      },

      config = function()
        local dap = require("dap")
        dap.configurations.python = {
          {
            type = "python",
            request = "launch",
            name = "Launch file",
            program = "${file}",
            pythonPath = function()
              return "D:\\Software\\anaconda3\\python"
            end,
          },
        }

        local dap_python = require("dap-python")
        local dap_python_path = "D:\\Software\\anaconda3\\python"
        vim.api.nvim_echo({ { "Using path for dap-python: " .. dap_python_path, "None" } }, false, {})
        dap_python.setup(dap_python_path)
      end,
    },
  },
}
```
where I default to using the Python interpreter that comes with Anaconda, and its path is 

```
 "D:\\Software\\anaconda3\\python"
```

4. Create a `test.py` file 
5. use `<leader>db` to add a breakpoint and use `<leader>dc` to run, the above situation occurs.

### Expected Behavior

Python can be debugged successfully.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
Have you tried the `extras.python` that sets up `nvim-dap` and `nvim-dap-python` for you ([python](https://www.lazyvim.org/extras/lang/python))? If the problem persists after you try this, then maybe open an issue at `nvim-dap` repo to ask about how well they support Windows? Not using Windows, so don't know what else to tell you really, sorry.

**Comment by abeldekat** [comment]
In addition to the answer given by @dpetka2001:
In your mason config, you ensure black is installed. Is debugpy installed on your system?

The minimal config below should ensure debugby is also installed. 

```
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "LazyVim/LazyVim",
  { import = "lazyvim.plugins" },
  { import = "lazyvim.plugins.extras.dap.core" },
  { import = "lazyvim.plugins.extras.lang.python" },
  {
    "jose-elias-alvarez/null-ls.nvim",
    optional = true,
    opts = function(_, opts)
      if type(opts.sources) == "table" then
        local nls = require("null-ls")
        vim.list_extend(opts.sources, {
          nls.builtins.formatting.black,
        })
      end
    end,
  },
  -- Ensure Python debugger and black are installed
  {
    "williamboman/mason.nvim",
    optional = true,
    opts = function(_, opts)
      if type(opts.ensure_installed) == "table" then
        if require("lazyvim.util").has("nvim-dap") then
          vim.list_extend(opts.ensure_installed, { "debugpy" })
        end
        vim.list_extend(opts.ensure_installed, { "black" })
      end
    end,
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

You can test this with:
```
nvim -u minimal.lua <your_python_file>
```
```

**Comment by veiledshadow** [comment]
> Have you tried the `extras.python` that sets up `nvim-dap` and `nvim-dap-python` for you ([python](https://www.lazyvim.org/extras/lang/python))? If the problem persists after you try this, then maybe open an issue at `nvim-dap` repo to ask about how well they support Windows? Not using Windows, so don't know what else to tell you really, sorry.

Thank you very much. I had previously attempted to configure nvim-dap using extras.python, but the popup window still appeared and provided the same prompt. I suspect it might be due to the Windows system? Today, I transferred my configuration to  WSL2, simply replacing the Windows Python path with the Linux Python path as mentioned above, and I was able to debug smoothly. I truly don't understand why the popup window would appear on Windows. In any case, I appreciate your advice.

**Comment by veiledshadow** [comment]
> In addition to the answer given by @dpetka2001: In your mason config, you ensure black is installed. Is debugpy installed on your system?
> 
> The minimal config below should ensure debugby is also installed.
> 
> ```
> -- DO NOT change the paths and don't remove the colorscheme
> local root = vim.fn.fnamemodify("./.repro", ":p")
> 
> -- set stdpaths to use .repro
> for _, name in ipairs({ "config", "data", "state", "cache" }) do
>   vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
> end
> 
> -- bootstrap lazy
> local lazypath = root .. "/plugins/lazy.nvim"
> if not vim.loop.fs_stat(lazypath) then
>   vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
> end
> vim.opt.runtimepath:prepend(lazypath)
> 
> -- install plugins
> local plugins = {
>   "LazyVim/LazyVim",
>   { import = "lazyvim.plugins" },
>   { import = "lazyvim.plugins.extras.dap.core" },
>   { import = "lazyvim.plugins.extras.lang.python" },
>   {
>     "jose-elias-alvarez/null-ls.nvim",
>     optional = true,
>     opts = function(_, opts)
>       if type(opts.sources) == "table" then
>         local nls = require("null-ls")
>         vim.list_extend(opts.sources, {
>           nls.builtins.formatting.black,
>         })
>       end
>     end,
>   },
>   -- Ensure Python debugger and black are installed
>   {
>     "williamboman/mason.nvim",
>     optional = true,
>     opts = function(_, opts)
>       if type(opts.ensure_installed) == "table" then
>         if require("lazyvim.util").has("nvim-dap") then
>           vim.list_extend(opts.ensure_installed, { "debugpy" })
>         end
>         vim.list_extend(opts.ensure_installed, { "black" })
>       end
>     end,
>   },
> }
> require("lazy").setup(plugins, {
>   root = root .. "/plugins",
> })
> 
> vim.cmd.colorscheme("tokyonight")
> -- add anything else here
> ```
> 
> You can test this with:
> 
> ```
> nvim -u minimal.lua <your_python_file>
> ```

Thank you very much. I had previously attempted to configure `nvim-dap` using `extras.python`, but the popup window still appeared and provided the same prompt. My `debugpy` is installed and configured in another file. I have test the debug model use your provided configuration, but the popup window still appeared and provided the same prompt.   I suspect it might be due to the Windows system? I transferred my configuration to WSL2, simply replacing the Windows Python path with the Linux Python path , and I was able to debug smoothly. I truly don't understand why the popup window would appear on Windows. In any case, I appreciate your advice and  Thank you very much for providing the test code.

**Comment by dpetka2001** [comment]
You should make an issue to `nvim-dap` repo for support for Windows. Since this is not related to Lazyvim would you be kind to close the issue if you have no further requirements?

**Comment by AlbinZhu** [comment]
try
1. disable mason-dap-nvim automatic_installation 
```
 -- mason.nvim integration
{
      "jay-babu/mason-nvim-dap.nvim",
      dependencies = "mason.nvim",
      cmd = { "DapInstall", "DapUninstall" },
      opts = {
        -- Makes a best effort to setup the various debuggers with
        -- reasonable debug configurations
        automatic_installation = false,
      },
    },
  },
```

2.uninstall debugpy which installed by mason
`MasonUninstall debugpy`

3.install dedbugpy by` pip install`

4.set debugpy path for dap-python
```
{
    "mfussenegger/nvim-dap",
    optional = true,
    require("dap.ext.vscode").load_launchjs(),
    dependencies = {
      "mfussenegger/nvim-dap-python",
      -- stylua: ignore
      keys = {
        { "<leader>dPt", function() require('dap-python').test_method() end, desc = "Debug Method", ft = "python" },
        { "<leader>dPc", function() require('dap-python').test_class() end, desc = "Debug Class", ft = "python" },
      },
      config = function()
        require("dap-python").setup("pathtodebugpy\\python.exe")
      end,
    },
  },
```
5.enjoy it
