### ISSUE TITLE
feature: need an option to disable Mason and use LSP server binaries installed via system package manager

### ISSUE THREAD

**Issue by hronro** [LazyVim/LazyVim#1285]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

In NixOS, it's basically impossible to run a binary downloaded from the internet, so Mason is basically useless on NixOS.

### Describe the solution you'd like

It would be great if LazyVim could provide an option to disable the usage of Mason and use the LSP server binaries installed via the system package manager instead.

### Describe alternatives you've considered

None

**Comment by dpetka2001** [comment]
In the [docs](https://www.lazyvim.org/plugins/lsp#nvim-lspconfig) it mentions in the `lua_ls` section that you can put `mason = false` for the particular server you want and it won't be managed by Mason. Instead `lspconfig` will look for binaries in your PATH to invoke the corresponding client and attach it to the buffer.

**Comment by hronro** [comment]
@dpetka2001 Thank you, I didn't notice that.

**Comment by shanesveller** [comment]
Fellow Nix & NixOS user here - it's also possible to fully disable the mason plugins if you never intend to let Neovim/Mason manage those binaries for you, i.e. if you pull LSP binaries into your devShells for versioning reasons. The rest of the LazyVim config generally works exactly correctly without them.

**Comment by musjj** [comment]
Weird, I have fully disabled the mason plugins like this:

```lua
{                                      
  "williamboman/mason.nvim",           
  enabled = false,                     
},                                     
                                       
{                                      
  "williamboman/mason-lspconfig.nvim", 
  enabled = false                      
},                                     
```

But it still expects mason paths. I guess `mason = false` is still required?
