### ISSUE TITLE
feature: Ignore Tailwind specific directives

### ISSUE THREAD

**Issue by stefanfrede** [LazyVim/LazyVim#1295]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

At the moment you get warnings for Tailwind CSS specific [directives](https://tailwindcss.com/docs/functions-and-directives) like for example `@apply`.

```
css: Unknown at rule @apply
```

### Describe the solution you'd like

If you use Tailwind CSS those directives are ignored.

### Describe alternatives you've considered

I tried to configure it myself but I failed :disappointed:

**Comment by dpetka2001** [comment]
This is the default behavior of tailwindcss LSP server as stated in the [docs](https://github.com/tailwindlabs/tailwindcss-intellisense#tailwindcsslintinvalidapply). You should disable that if you don't want it. Something like
```lua
{
  "neovim/nvim-lspconfig",
  opts = {
    servers = {
      tailwindcss = {
        settings = {
          tailwindCSS = {
            lint = {
              invalidApply = false,
            },
          },
        },
      },
    },
  },
},
```
in the file where you configure your lspconfig setup. This is not a Lazyvim issue in my opinion.

**Comment by stefanfrede** [comment]
This did the trick:
```
{
  "neovim/nvim-lspconfig",
  opts = {
    servers = {
      tailwindcss = {
        settings = {
          tailwindCSS = {
            lint = {
              invalidApply = "ignore",
            },
          },
        },
      },
    },
  },
},
```
I close this issue as this was just a configuration issue.
