### ISSUE TITLE
bug: Neo-tree does not respect `cwd` ?

### ISSUE THREAD

**Issue by dpetka2001** [LazyVim/LazyVim#130]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0-dev commit c6ab8dfc1

### Operating system/version

Linux Mint 21.1

### Describe the bug

After first opening nvim for example from `~/` I open a file from `~/.config/nvim/lua/plugins/`.
The first time i open `Neotree (cwd)` it correctly shows the contents of `~` which is supposed to be the `cwd`.
After i open `Neotree (root dir)` it correctly shows the contents of `~/.config/nvim/lua/plugins/` which is supposed 
to be the `roor_dir` of the currently opened file.
Then i open `Neotree (cwd)` again and it continues to show the contents of `~/.config/lua/plugins/` which are the 
contents of the `roor_dir` and not the contents of `cwd` which should be `~/`.
Is this supposed to be the correct behavior? Does `lazyvim.util.get_root()` update the `cwd` to be the `root_dir` after
it is called? I would expect to keep track of `cwd` and Neotree to show the files of `cwd` when invoked with `Neotree (cwd).

### Steps To Reproduce

1. Open neovim for example from `~/`.
2. Open a file from `~/.config/nvim/lua/plugins/`
3. Invoke `Neotree (cwd)` (it shows correctly the contents of `cwd`)
4. Invoke `Neotree (root dir)` (it shows correctly the contents of `root_dir`)
5. Invoke again `Neotree (cwd)` (it shows the contents of `root_dir`)

### Expected Behavior

I would expect in step 5 when i invoke `Neotree (cwd)` to show again the files of `cwd` like it did
in step 3. 

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
It shouldn't update the CD. Will check what's wrong.

**Comment by folke** [comment]
Should be fixed now!

**Comment by jcorum11** [comment]
I have a similar issue: My company uses Angular with Nx and one of my buddies figured out a pseudo fix by putting this in plugins/neo-tree.lua
```
return {
  {
    "neovim/nvim-lspconfig",
    dependencies = {
      "jose-elias-alvarez/typescript.nvim",
      init = function()
        require("lazyvim.util").on_attach(function(_, buffer)
          -- stylua: ignore
          vim.keymap.set( "n", "<leader>co", "TypescriptOrganizeImports", { buffer = buffer, desc = "Organize Imports" })
          vim.keymap.set("n", "<leader>cR", "TypescriptRenameFile", { desc = "Rename File", buffer = buffer })
          vim.keymap.set(
            "n",
            "<leader>cu",
            "TypescriptRemoveUnused",
            { desc = "Remove Unused Variables", buffer = buffer }
          )
        end)
      end,
    },
    ---@class PluginLspOpts
    opts = {
      ---@type lspconfig.options
      servers = {
        -- typescript will be automatically installed with mason and loaded with lspconfig
        tsserver = {},
        -- angularls will be automatically installed with mason and loaded with lspconfig
        angularls = {
          root_dir = function(fname)
            return vim.loop.cwd()
          end,
        },
      },
    },
  },
}
```
Which seems to fix the issue since while navigating the root wont change. But if I close and Neo-tree with `<space>e` the cwd changes again.

**Comment by mauchchhash** [comment]
This exact same issue is happening to me too. And in my case apart from neo-tree, telescope find files is also behaving the same way. `<leader>ff` is showing the results from `cwd' and `<leader>fF` is showing from `root dir`.
I am using v0.9.1 appimage on Linux Mint 21.1

**Comment by dpetka2001** [comment]
I cannot reproduce this problem any more. Are you following the exact same steps as in the opening post? What is the path that you're opening Neovim from and what is the path of the file you're opening in Neovim?
