### ISSUE TITLE
bug: Neotree focused file jumps to bottom of explorer

### ISSUE THREAD

**Issue by ghidalgo93** [LazyVim/LazyVim#1304]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

MacOS 13.5

### Describe the bug

When there are more files that fit (vertically) in the neotree explorer, the focused file jumps 4 spaces from the bottom of the explorer. Presumably, this has to do with the`scrolloff` option, as when I change this value, the focused file's location jumps accordingly. 

### Steps To Reproduce

1. open the neotree explorer in a directory with explorer contents > number of rows.
2. center (or otherwise change position of) the focused/highlighted file
3. navigate to another buffer
4. focused file will jump `scrolloff` # of rows from the bottom

### Expected Behavior

moving to another buffer does not change or otherwise affect the neotree explorer.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by abeldekat** [comment]
Hello @ghidalgo93 

> Expected behaviour: moving to another buffer does not change or otherwise affect the neotree explorer.

You could add the following to your config:

```lua
{
  "neo-tree.nvim",
  opts = {
    filesystem = {
      follow_current_file = { enabled = false },
    },
  },
}
```

You also mention the jump to the bottom of the explorer. I tested this with a minimal config, using only lazy.nvim. I guess this is the standard neo-tree behavior when the follow_current_file setting is enabled. The jumps are there, even when scrolloff is 0. Please correct me when I am wrong...

For now, I think this is not a bug in LazyVim.
