### ISSUE TITLE
bug: dap run debuggables in rust not attaching unless selecting continue or opening ui

### ISSUE THREAD

**Issue by NotNullBool** [LazyVim/LazyVim#1305]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.1

### Operating system/version

Windows 11

### Describe the bug

```
//plugins
    { import = "lazyvim.plugins.extras.dap.core" },
    { import = "lazyvim.plugins.extras.lang.rust" },
    { import = "lazyvim.plugins.extras.util.project" },
    { import = "lazyvim.plugins.extras.coding.yanky" },

//Error
C:\Users\x9ov8\AppData\Local\nvim-data\mason\packages\codelldb/extension/adapter/codelldb exited with code 1
Couldn't connect to 127.0.0.1:${port}: ECONNREFUSED
```

When I use debug> run debuggables> test or build 
I am not receiving ui pop up and dap is not connecting to the localhost. 
However,
debug>dap ui> click the play button or debug>continue
UI works as expected allowing me to see info on variables stopping at break points

### Steps To Reproduce

1. fresh LazyVim
2. import dap.core
3. import lang.rust
4. open rust file in nvim
5. <leader>dr
6. test or build
7. see error

### Expected Behavior

From my understanding running debuggables should be the same as debug>continue without the need to manual find the executable or at the very least be popping up a window trying to find the executable. However it just shows an error then closes.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by abeldekat** [comment]
Hello @NotNullBool,


I searched using "codelldb Couldn't connect to 127.0.0.1:${port}: ECONNREFUSED" and found an issue in the repository of [rust-tools.nvim](https://github.com/simrat39/rust-tools.nvim/issues/330). I have no rust knowledge, maybe the information in that issue is helpful. 

Best regards!

**Comment by NotNullBool** [comment]
I tried that and it didn't fix the issue. I was hoping it was something to do with lazy-vim since the rest was working.

**Comment by lxgreen** [comment]
i have the same symptoms (`Couldn't connect to 127.0.0.1:${port}: ECONNREFUSED`) for typescript test debugging (jest). It worked perfectly till the last week or so, then the error started to pop up when trying to debug a test.

**Comment by GrigoreAlexandru-Arch** [comment]
After hours of trying to fiddle with the rust tools opts, I finally found out why it didn't work.
The issue is that the liblldb_path is not set up correctly for windows.
After I created rust-tools.lua in the plugins folder with the code below, the debugger started working: 

```
return {
	"simrat39/rust-tools.nvim",
	opts = function()
		local ok, mason_registry = pcall(require, "mason-registry")
		local adapter ---@type any
		if ok then
			-- rust tools configuration for debugging support
			local codelldb = mason_registry.get_package("codelldb")
			local extension_path = codelldb:get_install_path() .. "/extension/"
			local codelldb_path = extension_path .. "adapter/codelldb"
			local liblldb_path = ""

			if vim.loop.os_uname().sysname:find("Windows") then
				liblldb_path = extension_path .. "lldb\\bin\\liblldb.dll"
			elseif vim.fn.has("mac") == 1 then
				liblldb_path = extension_path .. "lldb/lib/liblldb.dylib"
			else
				liblldb_path = extension_path .. "lldb/lib/liblldb.so"
			end
			adapter = require("rust-tools.dap").get_codelldb_adapter(codelldb_path, liblldb_path)
		end
		return {
			dap = {
				adapter = adapter,
			},
			tools = {
				on_initialized = function()
					vim.cmd([[
              augroup RustLSP
                autocmd CursorHold                      *.rs silent! lua vim.lsp.buf.document_highlight()
                autocmd CursorMoved,InsertEnter         *.rs silent! lua vim.lsp.buf.clear_references()
                autocmd BufEnter,CursorHold,InsertLeave *.rs silent! lua vim.lsp.codelens.refresh()
              augroup END
            ]])
				end,
			},
		}
	end,
}

```

**Comment by NotNullBool** [comment]
That looks extremely tedious I appreciate you so much for figuring it out!

**Comment by cyberman500** [comment]
Alternatively, avoid the `get_codelldb_adapter` function which requires us to override the `liblldb_path` even though we want the default:
```lua
return {
  "simrat39/rust-tools.nvim",
  opts = function()
    local ok, mason_registry = pcall(require, "mason-registry")
    local adapter ---@type any
    if ok then
      -- rust tools configuration for debugging support
      local codelldb = mason_registry.get_package("codelldb")
      local extension_path = codelldb:get_install_path() .. "/extension/"
      local codelldb_path = extension_path .. "adapter/codelldb"

      adapter = {
        type = "server",
        port = "${port}",
        host = "127.0.0.1",
        executable = {
          command = codelldb_path,
          args = { "--port", "${port}" },
        },
      }
    end
    return {
      dap = {
        adapter = adapter,
      },
      tools = {
        on_initialized = function()
          vim.cmd([[
                augroup RustLSP
                  autocmd CursorHold                      *.rs silent! lua vim.lsp.buf.document_highlight()
                  autocmd CursorMoved,InsertEnter         *.rs silent! lua vim.lsp.buf.clear_references()
                  autocmd BufEnter,CursorHold,InsertLeave *.rs silent! lua vim.lsp.codelens.refresh()
                augroup END
              ]])
        end,
      },
    }
  end,
  config = function() end,
}
```

The default: https://github.com/vadimcn/codelldb/blob/f4b6ad6dfc20a31da922146b78cbea9543997e5d/adapter/loader/main.rs#L45-L55
