### ISSUE TITLE
bug: clangd not in configured server list when importing "lazyvim.plugins.extras.lang.clangd"

### ISSUE THREAD

**Issue by jla2000** [LazyVim/LazyVim#1309]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.0

### Operating system/version

MacOS 15.11

### Describe the bug

After importing "lazyvim.plugins.extras.lang.clangd" in the lazy.lua config file and installing all the new plugins, the clangd server is somehow not in the configured servers list and is not being attached when opening C/C++ projects.

### Steps To Reproduce

Import the "lazyvim.plugins.extras.lang.clangd" plugin
Open a C/C++ project
No lsp attached / configured :'(

### Expected Behavior

Clangd being in the configured servers list and attaching to C/C++ files.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
  spec = {
    -- add LazyVim and import its plugins
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- import any extras modules here
    { import = "lazyvim.plugins.extras.dap.core" },
    { import = "lazyvim.plugins.extras.lang.rust" },
    { import = "lazyvim.plugins.extras.lang.cmake" },
    { import = "lazyvim.plugins.extras.lang.clangd" },
    { import = "lazyvim.plugins.extras.lang.yaml" },
    { import = "lazyvim.plugins.extras.util.project" },
    -- import/override with your plugins
    { import = "plugins" },
  },
})

vim.cmd.colorscheme("tokyonight")
```

**Comment by dpetka2001** [comment]
#1308 I know you already saw the PR and also found a solution for the time being. Just mentioning it here, in case someone else stumbles upon this, because most ppl look through issues and not much so PRs.

**Comment by jla2000** [comment]
Yes, after trying out #1308 clangd works now again, I'll close this issue
