### ISSUE TITLE
bug: Go Debug (Arguments) fails

### ISSUE THREAD

**Issue by habsfanongit** [LazyVim/LazyVim#1314]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.1

### Operating system/version

mac OS 13.5 (22G74)

### Describe the bug

Hi,
When debugging Go projects, if you choose to debug (Arguments) after `<lead>dc`, the argument window disappears too fast then this message shows up `debug adapter reported a frame at line 9 column 1, but: Cursor position outside buffer. Ensure executable is up2date`

<img width="1728" alt="image" src="https://github.com/LazyVim/LazyVim/assets/21362322/87b40e14-2040-4ede-a0f8-4aa6936d0e4e">

The only config changes to Lazyvim I have came from the documentation page 
```
require("lazy").setup({
  spec = {
    -- add LazyVim and import its plugins
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- import any extras modules here
    { import = "lazyvim.plugins.extras.lang.typescript" },
    { import = "lazyvim.plugins.extras.lang.json" },
    { import = "lazyvim.plugins.extras.ui.mini-animate" },
    { import = "lazyvim.plugins.extras.dap.nlua" },
    { import = "lazyvim.plugins.extras.dap.core" },
    { import = "lazyvim.plugins.extras.lang.rust" },
    { import = "lazyvim.plugins.extras.lang.go" },
    { import = "lazyvim.plugins.extras.lang.terraform" },
    -- import/override with your plugins
    { import = "plugins" },
  },
```

### Steps To Reproduce

1. Create a Go project using go mod init projectname
2. place a debug point on any line
3. start the debugger with arguments <lead>dc and select Debug (Arguments)

### Expected Behavior

Should allow the debugger to wait for arguments to be entered 

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by abeldekat** [comment]
Hello @habsfanongit,

I searched using "go debug debug adapter reported a frame at line" and found this [issue](https://github.com/mfussenegger/nvim-dap/issues/956) in the nvim-dap repository.

I scanned the issue, the label "needs:repoduction" was added recently.
That issue could benefit from the steps you described.

Best regards!

**Comment by habsfanongit** [comment]
Hello @abeldekat ,
I just saw the issue and noticed that you added a mention to this one.
I initially thought this issue was caused by the Argument window disappearing quickly. 
This is a different issue; I can debug without a problem if I don't use arguments. 
I will try a C++ and try to reproduce the same issue you found and report it with details.
Thank you.

**Comment by folke** [comment]
This isn't really a LazyVim issue. Report it to the relevant plugins instead. Closing....
