### ISSUE TITLE
bug: copilot cmp failing

### ISSUE THREAD

**Issue by joshmedeski** [LazyVim/LazyVim#1315]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.1

### Operating system/version

macOS 13.5 (22G74)

### Describe the bug

I'm getting the following error

```
  Error  14:12:56 msg_show.lua_error Error detected while processing LspAttach Autocommands for "*":
14:12:56 msg_show Error executing lua callback: ...l/share/nvim/lazy/copilot-cmp/lua/copilot_cmp/source.lua:29: attempt to index field 'dynamic_capabilities' (a nil value)
stack traceback:
	...l/share/nvim/lazy/copilot-cmp/lua/copilot_cmp/source.lua:29: in function <...l/share/nvim/lazy/copilot-cmp/lua/copilot_cmp/source.lua:28>
	vim/shared.lua: in function 'tbl_filter'
	...l/share/nvim/lazy/copilot-cmp/lua/copilot_cmp/source.lua:28: in function 'is_available'
	...cal/share/nvim/lazy/copilot-cmp/lua/copilot_cmp/init.lua:30: in function '_on_insert_enter'
	...cal/share/nvim/lazy/copilot-cmp/lua/copilot_cmp/init.lua:43: in function <...cal/share/nvim/lazy/copilot-cmp/lua/copilot_cmp/init.lua:42>
	[C]: in function 'nvim_exec_autocmds'
	...w/Cellar/neovim/0.9.1/share/nvim/runtime/lua/vim/lsp.lua:1531: in function '_on_attach'
	...w/Cellar/neovim/0.9.1/share/nvim/runtime/lua/vim/lsp.lua:1358: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

### Steps To Reproduce

1. Upgrade Lazy packages to their latest versions
2. Open a file with LSP support

### Expected Behavior

Copilot cmp should start up and offer auto-complete options while coding.

**Comment by krishna-bala** [comment]
@joshmedeski this seems like it's related to the latest change in `copilot-cmp`. If you are not aware, you can roll back to the previous commit of `copilot-cmp` pretty easily. If you open `:Lazy log`, go to `copilot-cmp`, you will see that there was a change made a few hours ago. If you go to the previous commit (`c2cdb3c`) and press `r`, it will restore that plugin to the previous commit.

**Comment by joshmedeski** [comment]
That fixes it for now, thanks @krishna-bala

**Comment by CatDadCode** [comment]
> @joshmedeski this seems like it's related to the latest change in `copilot-cmp`. If you are not aware, you can roll back to the previous commit of `copilot-cmp` pretty easily. If you open `:Lazy log`, go to `copilot-cmp`, you will see that there was a change made a few hours ago. If you go to the previous commit (`c2cdb3c`) and press `r`, it will restore `copilot-cmp` to the commit under your cursor.

omg I love LazyVim so much. Crazy that falling back a plugin to a previous commit is that easy.

**Comment by CatDadCode** [comment]
This is fixed now :)

https://github.com/zbirenbaum/copilot-cmp/issues/84

**Comment by dpetka2001** [comment]
@CatDadCode Just a minor nitpick, it's `lazy.nvim` that offers this feature not Lazyvim. So, even if you use another distro or have your own custom configuration and use `lazy.nvim` as your package manager, then you have access to this feature. Also, since this is not a Lazyvim issue and also has been solved upstream, @joshmedeski would you be kind to close the issue if possible?

**Comment by CatDadCode** [comment]
Yes, the lazy.nvim plug-in is the plug-in manager. I'm aware thank you.

**Comment by joshmedeski** [comment]
@dpetka2001 I'm using the builtin lazyvim plugin, so I thought it was easiest to first open an issue here.

```lua
    { import = "lazyvim.plugins.extras.coding.copilot" },
```


Thanks for keeping us informed @CatDadCode and I appreciate the speediness @rgruyters with the patch 🙏
