### ISSUE TITLE
feature: simple folding/unfolding

### ISSUE THREAD

**Issue by dongwangdw** [LazyVim/LazyVim#1319]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

When to read a big code file, it is really convenient fo fold so that I can jump by functions or long segments.

### Describe the solution you'd like

I would like some simple commands which would enable folding/unfolding.

### Describe alternatives you've considered

Current default option is not good to use or customize.

**Comment by abeldekat** [comment]
Hello @dongwangdw,

Could you provide some more info regarding the solution you'd like? Most notably, I think the meaning of the word "simple" is too broad.

My first thoughts:
1. Inside LazyVim, editing code: When I press 'z' multiple folding suggestions appear.
2. I know of a plugin called [nvim-ufo](https://github.com/kevinhwang91/nvim-ufo). Would this plugin be useful to you?

Best regards!

**Comment by dpetka2001** [comment]
+1 for `nvim-ufo`. Just customize it to your needs.

**Comment by mirsella** [comment]
Alternative without another plugin is to use treesitter's as foldexpr

**Comment by sdondley** [comment]
@mirsella I'm a newb with lazy vim and treesitter. Is there a good recipe for that?

**Comment by towry** [comment]
```lua
vim.opt.foldexpr = 'v:lua.vim.treesitter.foldexpr()'
vim.opt.foldmethod = 'expr'
```

**Comment by dongwangdw** [comment]
> Hello @dongwangdw,
> 
> Could you provide some more info regarding the solution you'd like? Most notably, I think the meaning of the word "simple" is too broad.
Sorry for the ambigousness, my first impression would be some simple keyboards shortcuts. Maybe a one more prefix + some key? 
Regarding the backend, I did not search more about this.
> 
> My first thoughts:
> 
> 1. Inside LazyVim, editing code: When I press 'z' multiple folding suggestions appear.
Yeah, I did not found this option. 
But I may not use this properly. In a python file in which there are many functions, I would like fold all the functions. So
I press z and then i(toggle folding) and I also tried z and M(close all folds) but none works. Is there anything I missed.
BTW I did not find any segments in documentation. 
> 2. I know of a plugin called [nvim-ufo](https://github.com/kevinhwang91/nvim-ufo). Would this plugin be useful to you?
I found this too. But yet try it. The folding is useful I would like a easy use default folding. 
> Best regards!

**Comment by dpetka2001** [comment]
It's because by default the `foldmethod` is manual, meaning you would have to create the folds yourself in the places that you want. With those suggestions it changes the default behavior to use treesitter as the `foldexpr` to use for folding making.

**Comment by sdondley** [comment]
Thanks @mirsella, worked perfectly. If you have an idea on how to turn off folding for everything except functions, that would be fantastic.

I tried the suggestion here: https://github.com/nvim-treesitter/nvim-treesitter/issues/1564#issuecomment-931000867

I modified it for lua (or tried to at least) but I just got a bunch of errors.

**Comment by abeldekat** [comment]
Hello @dongwangdw,

Thanks for your reply. 
As mentioned by @towry and @mirsella, folding with [treesitter](https://github.com/LazyVim/LazyVim/issues/1319#issuecomment-1681644431) is also an excellent idea. 

> ... BTW I did not find any segments in documentation...

Folding is documented in neovim's help pages(`:h folding`). In LazyVim, you can use "leader s h"

> Not sure how better nvim-ufo would be than the default setting?

I can't really say, as I "revisited" the folding functionality because of your feature request.  I did observe that the plugin provides an easy way to use the `lsp` for folding, and uses `indent` as backup strategy. Try it out, I would suggest. For my personal use case, treesitter folding is also fine.

> With suggestions from @towry, then I can use the z for foldings. I guess the default setting misses this?

This is [explained](https://github.com/LazyVim/LazyVim/issues/1319#issuecomment-1681906377) by @dpetka2001. 
I don't think the default setting *misses* this though. Currently, `LazyVim` has no explicit opinion on folding. It's up to the user to add his own preferences. 

I'm interested in any the feedback your request will receive!

**Comment by sdondley** [comment]
Here's a simple but effective solution for just folding on just the functions: `vim.opt.foldnestmax = 1`

**Comment by dpetka2001** [comment]
@sdondley Can you try the following and see if it's to your liking?
```lua
autocmd("BufEnter", {
  pattern = "*",
  callback = function()
    require("vim.treesitter.query").set("lua", "folds", [[(function_definition (block) @fold)]])
  end,
  group = augroup("LazyVimFolds", { clear = true }),
  desc = "Treesitter folding only Lua functions",
})
```
You can put it in your `~/.config/nvim/lua/config/autocmds.lua`.

**Comment by GitMurf** [comment]
> Currently, `LazyVim` has no explicit opinion on folding. It's up to the user to add his own preferences.

@abeldekat would you say this perspective has changed in the last few months? Below are several commits of the default lazyzim options related to folds. Is there an "official" stance or write-up anywhere with how lazyvim now handles folds and what/how the best way to understand and tweak the preferences if a user desires? Thanks for all the hardwork from everyone!

https://github.com/LazyVim/LazyVim/commit/19926d284862b5e58f29e73b71ec532ac29c54ba
https://github.com/LazyVim/LazyVim/commit/f1ce07510d2048e33fec2b609814d68a7175d591
https://github.com/LazyVim/LazyVim/commit/e105c9daf6e973b4a294a17b4d2d1882f2188ac6
https://github.com/LazyVim/LazyVim/commit/d989ecc943b3240db0be3aa0369b96089cee4b40
https://github.com/LazyVim/LazyVim/commit/a5c9708736f6ecd3e3413ad0ca34b7b1fa3d4862

**Comment by abeldekat** [comment]
Hello @GitMurf,

Yes, that perspective has changed I think. I can't answer your question regarding the official stance or write-up though. Maybe you can ask your question in the discussions section?

Best regards!

**Comment by GitMurf** [comment]
does anyone know how we can still add our own custom / manual folds on top of treesitter? My biggest painpoint is code comment sections which I am surprised treesitter folding doesn't support ootb. I would like to be able to do `vip` to select a chunk of commented out code (paragraph) and then create a manual fold for that. Is this possible? thanks!
