### ISSUE TITLE
feature: Markdown preview capabilities

### ISSUE THREAD

**Issue by liamwh** [LazyVim/LazyVim#1326]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

I'm having difficulties getting either [markdown preview](https://github.com/iamcco/markdown-preview.nvim) or [peek.nvim](https://github.com/toppair/peek.nvim) to work on Mac or WSL2 (Ubuntu) with LazyVim.

### Describe the solution you'd like

Given markdown is used so universally, I believe it'd make sense to include it by default in LazyVim or available as an extra.

### Describe alternatives you've considered

Setting up markdown preview and peek

**Comment by dpetka2001** [comment]
You can install `peek.nvim` in your personal spec. Just take a look through the issues and PRs because there was a problem with the version of deno it could compile. It required 1.25.4 if I recall correctly. This [PR](https://github.com/toppair/peek.nvim/pull/49) provides more info.

**Comment by liaohui5** [comment]
> 

you can try [markdown-preview.nvim](https://github.com/iamcco/markdown-preview.nvim) plugin
