### ISSUE TITLE
feature: add disable auto reload config file user option

### ISSUE THREAD

**Issue by liaohui5** [LazyVim/LazyVim#1332]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

I use neovim to edit LazyVim configs, but it's always let me restart neovim

### Describe the solution you'd like

add a user option to disable this feature, like this

```lua
-- in init.lua
vim.g.disabled_auto_reload_configs = false
```

### Describe alternatives you've considered

no

**Comment by dpetka2001** [comment]
I'm not sure what exactly you want to achieve. Would you mind explaining with more detail please? You don't want to see the 
```
# Config Change Detected. Reloading...

- **changed**: `lua/plugins/coding.lua`
```
notification if I understand correctly and you want to manually restart Neovim for the changes to take effect?

**Comment by liaohui5** [comment]
> 
Thank you for your reply

You're right, I don't want to see this message, I'm used to manually restarting to reload configs

**Comment by liaohui5** [comment]
> I'm not sure what exactly you want to achieve. Would you mind explaining with more detail please? You don't want to see the
> 
> ```
> # Config Change Detected. Reloading...
> 
> - **changed**: `lua/plugins/coding.lua`
> ```
> 
> notification if I understand correctly and you want to manually restart Neovim for the changes to take effect?

Thank you for your reply

You're right, I don't want to see this message, I'm used to manually restarting to reload configs

**Comment by jyuan0** [comment]
Add a `change_detection` key with the settings you want in your lazy.nvim spec (in `config/lazy.lua`). These are the defaults:
```lua
  change_detection = {
    -- automatically check for config file changes and reload the ui
    enabled = true,
    notify = true, -- get a notification when changes are found
  },
```
https://github.com/folke/lazy.nvim#%EF%B8%8F-configuration

**Comment by liaohui5** [comment]
> Add a `change_detection` key with the settings you want in your lazy.nvim spec (in `config/lazy.lua`). These are the defaults:
> 
> ```lua
>   change_detection = {
>     -- automatically check for config file changes and reload the ui
>     enabled = true,
>     notify = true, -- get a notification when changes are found
>   },
> ```
> 
> https://github.com/folke/lazy.nvim#%EF%B8%8F-configuration

my problem is solved. Thank you very much

**Comment by dpetka2001** [comment]
Plz bare in mind that if you put `change_detection.enabled = false` then you will also lose the ability for the Lazy UI to pick up changes when you make any change in your specs (Lazy will only pick the changes to install or clean a plugin after a restart). With just `notify = false` you won't see the notification any more.

**Comment by liaohui5** [comment]
> Plz bare in mind that if you put `change_detection.enabled = false` then you will also lose the ability for the Lazy UI to pick up changes when you make any change in your specs (Lazy will only pick the changes to install or clean a plugin after a restart). With just `notify = false` you won't see the notification any more.

I remember it, now. thank you very much! 👍
