### ISSUE TITLE
bug: Background image icon not respect

### ISSUE THREAD

**Issue by naknode** [LazyVim/LazyVim#134]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.2

### Operating system/version

MacOS 13.0

### Describe the bug

I copied the Neovim from Scratch, `master` branch and now I get something like this:

![image](https://user-images.githubusercontent.com/616320/214713067-309bd6df-714d-4f67-86e7-4815fa7d25a5.png)

Using kitty. This happens in any. I am using FiraCode Nerd Fon with tmux.

### Steps To Reproduce

1. Follow instructions on https://github.com/LunarVim/Neovim-from-scratch
2. Install new neovim config
3. Go to any project
4. See the terminal as such

### Expected Behavior

It should not show the darker background around the icons.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
This is the LazyVim project. This has nothing to do with Lunarvim or Neovim from scratch

**Comment by naknode** [comment]
I meant LazyVim. Oops. Cool. :+1:

**Comment by folke** [comment]
@naknode either way, LazyVim uses the Tokyonight colorscheme, which correctly renders Lualine. Your screenshot does not look like LazyVim at all

**Comment by folke** [comment]
If you're trying to set a new colorscheme, follow the steps from the docs:

https://www.lazyvim.org/plugins/colorscheme

**Comment by naknode** [comment]
@folke You're right. This is probably on me -- thanks. And good stuff, by the way.
