### ISSUE TITLE
What's the difference of setting plugin in lazy.lua or plugin/voom.lua

### ISSUE THREAD

**Issue by dlintw** [LazyVim/LazyVim#1345]
I'm a newbie in nvim.
I want to try load 'VOom.vim when need.(I'm not sure it is possible).
I try to add a line in ~/.config/nvim/lua/config/lazy.lua as
```
...
require("lazy").setup({
  spec = {
...
 "vim-voom/VOom",
 { import = "plugins" },
  },
...
```
by check ":scriptnames", voom.vim loaded

So, I comment out the line in lazy.lua and create a new file ~/.config/nvim/lua/plugins/voom.lua as
```
return {
  { "vim-voom/VOom" },
}
```

If possible, I want to use this plugin only when I open "*.txt", "*.md" and "*.log" file.  What's the proper way to do this?

**Comment by MariaSolOs** [comment]
`LazyVim` is not the same as `lazy.nvim`. Create the issue in https://github.com/folke/lazy.nvim instead.

**Comment by abeldekat** [comment]
Hello @dlintw,

You are asking two questions, regarding `lazy.nvim`
Please ask your question in the [discussions](https://github.com/folke/lazy.nvim/discussions) forum, and close this issue.

Best regards!

**Comment by abeldekat** [comment]
Hello @dlintw,

You can use the `ft` property, described [here](https://github.com/folke/lazy.nvim#-plugin-spec).
The [examples](https://github.com/folke/lazy.nvim#examples) show its usage.

I hope this answers your question. If so, please take a moment to close this issue.

**Comment by dpetka2001** [comment]
So, this was the issue that slipped my mind :stuck_out_tongue: . On a serious note, @abeldekat , are you aware if `ft` accepts patterns like the `event` keyword? For example `event = BufEnter *.lua`. Does `ft` also accept that? Or it only accepts what `set ft?` returns as the filetype of the corresponding file?

**Comment by abeldekat** [comment]
Hi @dpetka2001,

A serious note most certainly deserves a serious answer...)
Disclaimer: I have no in-depth knowledge of that particular area of the code.

Events are the only `triggers` where `patterns` are mentioned in the [Plugin Spec](https://github.com/folke/lazy.nvim#-plugin-spec). I looked at the code in lazy.nvim's `lua/lazy/core/handler` folder. My answer would be, with some confidence: You can only specify `patterns` for `events`. The reason *might* be that `patterns` are an integral part of vim's `event` specification.

**Comment by dpetka2001** [comment]
@abeldekat I also took a look at the code and although I don't understand it fully, as I'm fairly new both to programming and Lua, I believe [this](https://github.com/folke/lazy.nvim/blob/dac844ed617dda4f9ec85eb88e9629ad2add5e05/lua/lazy/core/handler/event.lua#L19-L21) is where the differentiation between `event` and `pattern` is made. But looking at the `handler/ft.lua` code I didn't see such code and honestly understood even less. Thanks for clarifying in the best of your ability, as always you've been really helpful.

**Comment by abeldekat** [comment]
@dpetka2001,

Yes, that's the difference!

**Comment by dpetka2001** [comment]
By the way have you tried [Sourcegraph](https://sourcegraph.com/github.com/folke/lazy.nvim/-/blob/lua/lazy/core/handler/ft.lua)'s new AI assistant Cody? It's been really helpful for me I think on a basic level of understanding at least for my limited programming knowledge, although I have no credible qualifications to actually rate how correct its explanations are.

**Comment by abeldekat** [comment]
I did not try the assistant. Glad to know its helping you!
I must say though: Seeing the quality of your answers, I *really* don't think your programming knowledge is a limiting factor! You are, for example, on the top of the list of most helpful people in the discussions section. Thus, your judgement on the correctness of an answer is excellent!

Best regards!

**Comment by dpetka2001** [comment]
Thank you for your kinds words. I'm just excited to improve and expand my knowledge and that includes also programming. Just taking it step by step.

**Comment by MariaSolOs** [comment]
This is such a wholesome thread <3
