### ISSUE TITLE
bug: close tab does not clear the tab in the tab bar

### ISSUE THREAD

**Issue by simonxmh** [LazyVim/LazyVim#135]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.0

### Operating system/version

MacOS 12.6.2

### Describe the bug

When I use `<leader><tab>` I have the selections to manipulate my tabs.

Whenever I attempt to close a tab with `<leader><tab>d`. The tab with the numbering on the top right is effectively closed, but it remains visible as a selection in the tab bar on the left.

### Steps To Reproduce

1. `<leader><tab><tab>` to create a new tab
2. `<leader><tab>d` to close it
3. The tab name still shows at the top

### Expected Behavior

The tab should not show up

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by simonxmh** [comment]
I think I mis-identified the tab.

**Comment by folke** [comment]
Tabs and buffers are two different things. Tabs are closed, the empty buffer you created by creating a new tab needs to be closed separately
