### ISSUE TITLE
feature: add zz on search (n, N) as default or example

### ISSUE THREAD

**Issue by Hudison** [LazyVim/LazyVim#1350]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

I was changing some keymaps that I was already used to, in this case, having `zz` after `n` and `N` to center the cursor after a search, and I found that as a default LazyVim uses [vim-galore](https://github.com/mhinz/vim-galore#saner-behavior-of-n-and-n) suggestion for saner `n` and `N.` 

My suggestion is the add in the docs an example of adding more commands after the `n` and `N` but maintaining the **vim-galore** suggestion. 

The solution I came up with was to simply add ` . 'zz'` at the end of the command, e.g. 
```lua
map("n", "n", "'Nn'[v:searchforward]", { expr = true, desc = "Next search result" }) -- current
map("n", "n", "'Nn'[v:searchforward] . 'zz'", { expr = true, desc = "Next search result" })
```

### Describe alternatives you've considered

Add as a default QoL for LazyVim, if it makes sense for the objective of the project.

Supply more examples of appending to the default keymaps of LazyVim even though I did not find any other cases where it modifies a default keymap that makes sense (in my point of view) to append to.

### Additional context
I found that having `zz` executed after searching for something feels very good since my eyes don't go around the screen looking for some highlighted word or things like that. 
I also have this functionality on `*`, `#`, `g*` and `g#`

I understand that this is a personal opinion on a keymap QoL, but I found myself looking at the internet and doing some trying and error until I found a solution that worked well. 
I'm far away from a Vim expert but I also think that using a starter config like LazyVim is the home for a lot of beginners like myself, so I can imagine that more people will encounter these types of issues.

**Comment by abeldekat** [comment]
Hello @Hudison,

In LazyVim, extra care is required, as those mappings can interfere with the [mini.animate](https://github.com/echasnovski/mini.animate#features):

> If you have remapped any movement operation to center after it is done (like with nzvzz or <C-d>zz), you need to change those mappings. Either remove them or update to use MiniAnimate.execute_after() (see :h MiniAnimate.config.scroll)

**Comment by folke** [comment]
feel free to change this in your own config
