### ISSUE TITLE
feature:  add <leader> hotkey to toggle auto-complete

### ISSUE THREAD

**Issue by dlintw** [LazyVim/LazyVim#1362]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Sometimes, when writing a simple text. The auto-complete function just let you type in low speed. As I know, to disable it maybe 
```
 :lua require('cmp').setup.buffer { enabled = false }
```

### Describe the solution you'd like

if possible, set a toggle hotkey. if impossible, maybe a enable and disable key.

### Describe alternatives you've considered

no other idea.

**Comment by dpetka2001** [comment]
This is just a personal preference in my opinion and should be left up to the user to implement such a feature if he likes. If the maintainer decides that such a feature would be beneficial, he can of course include it in the base Lazyvim configuration. Since the maintainer will be absent until the end of month, until then you could use the following code in your `lua/config/keymaps.lua`
```lua
local Util = require("lazy.core.util")
local cmp_enabled = require("cmp.config").get().enabled
local cmp_toggle = function()
  cmp_enabled = not cmp_enabled
  if cmp_enabled then
    require("cmp").setup.buffer({ enabled = cmp_enabled })
    Util.info("cmp enabled", { title = "cmp" })
  else
    -- cmp_enabled = not cmp_enabled
    require("cmp").setup.buffer({ enabled = cmp_enabled })
    Util.warn("cmp disabled", { title = "cmp" })
  end
end

vim.keymap.set("n", "<leader>cp", cmp_toggle, { desc = "Toggle cmp" })
```
Could you check if this does what you want?

**Comment by dlintw** [comment]
Thanks your script, it works.  But it is too hard for a newbie to write out this function.  If it can provides in lazy.nvim by default will be better.  And also appear the hotkey in the "keymap" document.

**Comment by dpetka2001** [comment]
I'm a newbie myself. I know very basic Lua. I just try to read code from plugins while studying by myself. This snippet I wrote was heavily inspired by https://github.com/LazyVim/LazyVim/blob/566049aa4a26a86219dd1ad1624f9a1bf18831b6/lua/lazyvim/plugins/lsp/format.lua#L12-L24
 So if you try you can do it yourself as well. It's just a matter of what you want to do and it will definitely take some time. Again, I personally believe this is more of a personal preference as far as this keymap is concerned. If you would like, you can close this issue as this is not a Lazyvim bug but rather a user configuration request and probably belongs better in the Discussions. Or you might as well leave it open until the maintainer comes back and gives a definitive answer about your request if this is something that should be in the default Lazyvim configuration. Best regards.
