### ISSUE TITLE
bug: Cpp comment is nil, not "//"

### ISSUE THREAD

**Issue by XunHang** [LazyVim/LazyVim#1368]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

Ubuntu 20.04.4 LTS x86_64

### Describe the bug

I add a print function in mini.comment, and I type "gcc" in my c++ project, it shows "nil".
Then I use command :TSInstall cpp & :TSUpdate to make sure that they are up-to-date, but this bug still occurs.
![0998f3e0-8fa9-461f-892a-c8a0e03926e6](https://github.com/LazyVim/LazyVim/assets/17587962/9c95b006-179d-4ed7-a9f7-0c220d09ba81)

### Steps To Reproduce

1. make a cpp file;
2. type "gcc" to comment code
3. message shows "nil"

### Expected Behavior

Maybe it is a bug of ts, but I am rookie of neovim/vim, so I make issue here...

### Repro

```Lua
return{
  {
    "echasnovski/mini.comment",
    event = "VeryLazy",
    opts = {
      options = {
        custom_commentstring = function()
          local cs = require("ts_context_commentstring.internal").calculate_commentstring()
          print(cs)
          return cs or vim.bo.commentstring
        end,
      },
    },
  },
}
```

**Comment by dpetka2001** [comment]
I managed to solve this with following code in `~/.config/nvim/lua/plugins/treesitter.lua`
```lua
return {
  {
    "nvim-treesitter/nvim-treesitter",
    dependencies = {
      "JoosepAlviste/nvim-ts-context-commentstring",
    },
    opts = {
      context_commentstring = {
        enable = true,
        enable_autocmd = false,
        config = {
          cpp = "// %s",
        },
      },
    },
  },
}
```
I'm not sure if there is a more correct way, so whoever would like is welcome to come up with a more elegant solution. Could you test it out?

**Comment by XunHang** [comment]
> I managed to solve this with following code in `~/.config/nvim/lua/plugins/treesitter.lua`
> 
> ```lua
> return {
>   {
>     "nvim-treesitter/nvim-treesitter",
>     dependencies = {
>       "JoosepAlviste/nvim-ts-context-commentstring",
>     },
>     opts = {
>       context_commentstring = {
>         enable = true,
>         enable_autocmd = false,
>         config = {
>           cpp = "// %s",
>         },
>       },
>     },
>   },
> }
> ```
> 
> I'm not sure if there is a more correct way, so whoever would like is welcome to come up with a more elegant solution. Could you test it out?

It works! Tank you!
And I find a closed issue in this plugin's repo:  [How do I set commentstrings for c?](https://github.com/JoosepAlviste/nvim-ts-context-commentstring/issues/60)

maybe the best way is change the launch order to fix this bug?

**Comment by amaanq** [comment]
that's an issue w/ your config then, LazyVim's order is fine.

**Comment by XunHang** [comment]
> nvim-treesitter

I use the default mini.comment option before: [lazyvim: mini.comment](https://www.lazyvim.org/plugins/coding#minicomment)

Then I create a plugin named 'ts', and add 'requires = { "nvim-treesitter/nvim-treesitter" },', all lua code below:
``` lua
return {
  {
    "echasnovski/mini.comment",
    event = "VeryLazy",
    requires = { "nvim-treesitter/nvim-treesitter" },
    opts = {
      options = {
        custom_commentstring = function()
          local ccs = require("ts_context_commentstring.internal").calculate_commentstring()
          print(ccs)
          return ccs or vim.bo.commentstring
        end,
      },
    },
  },
}
```
After I run 'Lazy sync' and open a cpp file, 'css' is still 'nil', and plugin 'nvim-treesitter/nvim-treesitter' is not loaded.

When I type <C-space> to load nvim-ts, 'css' is still 'nil', too.

My plugin loaded status is below:

![image](https://github.com/LazyVim/LazyVim/assets/17587962/cda158ae-f0f5-4344-9335-e98db2246660)

**Comment by amaanq** [comment]
s/requires/dependencies/g

**Comment by XunHang** [comment]
By the way, I don't use 
```lua  
 { import = "lazyvim.plugins.extras.lang.clangd" },
```, 
my clangd lsp plugin get from @amaanq #1308

**Comment by XunHang** [comment]
> s/requires/dependencies/g

The Result:
![image](https://github.com/LazyVim/LazyVim/assets/17587962/687100c7-6c6a-4178-99cb-3b953a5f7865)

**Comment by XunHang** [comment]
my folder & files tree is below:
``` bash
 tree -L 2
.
├── build
│   ├── CMakeCache.txt
│   ├── CMakeFiles
│   ├── cmake_install.cmake
│   ├── compile_commands.json
│   ├── demo
│   └── Makefile
├── CMakeLists.txt
├── include
│   └── test.h
└── src
    ├── main.cpp
    └── test.cpp

```

And my CmakeLists.txt is 
``` cmake
cmake_minimum_required(VERSION 3.16.3)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON CACHE INTERNAL "")
set(CMAKE_CXX_STANDARD 17)

project(cmake_example)

include_directories(${CMAKE_CURRENT_LIST_DIR}/include)

add_executable (demo src/main.cpp src/test.cpp)

```

**Comment by folke** [comment]
I can't reproduce this with default LAzyVim. When I do gcc, it comments correctly. What am I missing?

**Comment by folke** [comment]
It's normal that nvim-ts-context-commentstring returns `nil`.
The cpp filetype in NEovim sets commentstring automatically, so that will be used instead.

**Comment by folke** [comment]
Update: if you want to set a custom commentstring, you can easily do this with:

```lua
  {
    "JoosepAlviste/nvim-ts-context-commentstring",
    opts = {
      config = {
        cpp = "// %s",
      },
    },
  },
```

There's really not need to mess with treesitter modules for this. Treesitter modules will also be deprecated at some point.
