### ISSUE TITLE
bug: can not find correct word by '/' because it is interrupted by wired quick jump key

### ISSUE THREAD

**Issue by dlintw** [LazyVim/LazyVim#1369]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.0

### Operating system/version

Rockey Linux 8.6

### Describe the bug

There is one strange function, when I search by press '/' then type 'F', then 'T', then 'P'.

I want to search "FTP",  but it works like, search 'F', then jump to 'T' position, then do 'P' command.

I don't know what's the plugin cause this issue. require to disable this function by default.

BTW, when I press '/' and 'F', it shows many words like FM, FB, FV, FX, FZ, FP,... the second char is marked as pink color.  I guess this is a funciton like quick jump to those location by press relative hint char like 'M', 'B', ...

### Steps To Reproduce

Below is what I guess to reproduce step, but I can not share what file I type FTP faile
1. generate a file which contains "ab", "ac", "ad",... "az"....
2. search 'abc' 

### Expected Behavior

Just want to disable this quick jump function, so annoy.

### Repro

```Lua
default lazynvim setup
```

**Comment by dlintw** [comment]
I tried this, seems useless by add a ~/.config/nvim/lua/plugins/disable.lua
```
return {
  { "ggandor/flit.nvim", enabled = false },
  { "ggandor/leap.nvim", enabled = false },
}
```

`:scriptnames` result
```
scriptnames   1: /usr/share/nvim/runtime/ftplugin.vim
  │ 2: /usr/share/nvim/runtime/indent.vim
  │ 3: /usr/share/nvim/sysinit.vim
  │ 4: ~/.config/nvim/init.lua
  │ 5: /usr/share/nvim/runtime/filetype.lua
  │ 6: ~/.local/share/nvim/lazy/nvim-cmp/plugin/cmp.lua
  │ 7: ~/.local/share/nvim/lazy/diffview.nvim/plugin/diffview.lua
  │ 8: ~/.local/share/nvim/lazy/VOom/plugin/voom.vim
  │ 9: ~/.local/share/nvim/lazy/cheatsheet.nvim/plugin/cheatsheet.vim
  │10: ~/.local/share/nvim/lazy/cheatsheet.nvim/ftdetect/cheatsheet.vim
  │11: ~/.local/share/nvim/lazy/ccc.nvim/plugin/ccc.lua
  │12: /usr/share/nvim/runtime/plugin/health.vim
  │13: /usr/share/nvim/runtime/plugin/man.lua
  │14: /usr/share/nvim/runtime/plugin/matchit.vim
  │15: /usr/share/nvim/runtime/pack/dist/opt/matchit/plugin/matchit.vim
  │16: /usr/share/nvim/runtime/plugin/matchparen.vim
  │17: /usr/share/nvim/runtime/plugin/netrwPlugin.vim
  │18: /usr/share/nvim/runtime/plugin/rplugin.vim
  │19: /usr/share/nvim/runtime/plugin/shada.vim
  │20: /usr/share/nvim/runtime/plugin/spellfile.vim
  │21: ~/.local/share/nvim/lazy/cmp_luasnip/after/plugin/cmp_luasnip.lua
  │22: ~/.local/share/nvim/lazy/cmp-path/after/plugin/cmp_path.lua
  │23: ~/.local/share/nvim/lazy/cmp-buffer/after/plugin/cmp_buffer.lua
  │24: ~/.local/share/nvim/lazy/cmp-nvim-lsp/after/plugin/cmp_nvim_lsp.lua
  │25: ~/.local/share/nvim/lazy/nvim-lspconfig/plugin/lspconfig.lua
  │26: /usr/share/nvim/runtime/filetype.vim
  │27: /usr/share/nvim/runtime/syntax/syntax.vim
  │28: /usr/share/nvim/runtime/syntax/synload.vim
  │29: /usr/share/nvim/runtime/autoload/provider/clipboard.vim
  │30: ~/.local/share/nvim/lazy/indent-blankline.nvim/plugin/indent_blankline.vim
  │31: ~/.local/share/nvim/lazy/vim-illuminate/plugin/illuminate.vim
  │32: ~/.local/share/nvim/lazy/nvim-treesitter/plugin/nvim-treesitter.lua
  │33: ~/.local/share/nvim/lazy/todo-comments.nvim/plugin/todo.vim
  │34: /usr/share/nvim/runtime/ftplugin/sh.vim
  │35: /usr/share/nvim/runtime/indent/sh.vim
  │36: /usr/share/nvim/runtime/syntax/sh.vim
  │37: ~/.local/share/nvim/lazy/plenary.nvim/plugin/plenary.vim
  │38: ~/.local/share/nvim/lazy/which-key.nvim/plugin/which-key.vim
  │39: ~/.local/share/nvim/lazy/nvim-web-devicons/plugin/nvim-web-devicons.vim
~

```

**Comment by dpetka2001** [comment]
@dlintw Without meaning to be disrespectful towards you, most of the issues you're opening are easily solved by reading the docs. In Lazyvim `flash` is the current default instead of `leap/flit`. If you take a look at `flash`'s default [configuration](https://github.com/folke/flash.nvim#%EF%B8%8F-configuration), you will find how to disable the feature that annoys you. But here is what you can do. Create a file `~/.config/nvim/lua/plugins/flash.lua` with
```lua
return {
  {
    "folke/flash.nvim",
    opts = {
      modes = { search = { enabled = false, }, },
    },
  },
}
```
I would suggest next time you have a problem with user configuration that conflicts with how you're used to things being done to open a Discussion instead of creating another Issue. I would suggest that you close this issue as well, but that's up to you in the end. Best regards.
