### ISSUE TITLE
bug: UI Diagnostics causes error in C# file when re-enabled.

### ISSUE THREAD

**Issue by ramfattah** [LazyVim/LazyVim#1374]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have searched the existing issues of LazyVim
- [ ] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.1

### Operating system/version

macOS 13.4 M1

### Describe the bug

After enabling "Toggle Diagnostics" back using the following key shortcuts:
* `space` + `u` + `d`

I get the following error:
`
E5108: Error executing lua: ...r/neovim/0.9.1/share/nvim/runtime/lua/vim/diagnostic.lua:1031: Invalid 'line': out of range
stack traceback:
	[C]: in function 'nvim_buf_set_extmark'
	...r/neovim/0.9.1/share/nvim/runtime/lua/vim/diagnostic.lua:1031: in function 'show'
	...r/neovim/0.9.1/share/nvim/runtime/lua/vim/diagnostic.lua:1223: in function 'show'
	...r/neovim/0.9.1/share/nvim/runtime/lua/vim/diagnostic.lua:1179: in function 'show'
	...r/neovim/0.9.1/share/nvim/runtime/lua/vim/diagnostic.lua:1173: in function 'show'
	...r/neovim/0.9.1/share/nvim/runtime/lua/vim/diagnostic.lua:1595: in function 'enable'
	....local/share/nvim/lazy/LazyVim/lua/lazyvim/util/init.lua:207: in function <....local/share/nvim/lazy/LazyVim/lua/lazyvim/util/init.lua:204>
`

This is a fresh clone of nvim from Installation page:
https://www.lazyvim.org/installation

### Steps To Reproduce

1. Clone the starter template from [instructions here](https://www.lazyvim.org/installation)
2. Open a C# file with `nvim`
3. Disable UI Diagnostics (`space` + `u` + `d`)
4. Enable UI Diagnostics back (`space` + `u` + `d`)
5. Notice the error

```shell
E5108: Error executing lua: ...r/neovim/0.9.1/share/nvim/runtime/lua/vim/diagnostic.lua:1031: Invalid 'line': out of range
stack traceback:
	[C]: in function 'nvim_buf_set_extmark'
	...r/neovim/0.9.1/share/nvim/runtime/lua/vim/diagnostic.lua:1031: in function 'show'
	...r/neovim/0.9.1/share/nvim/runtime/lua/vim/diagnostic.lua:1223: in function 'show'
	...r/neovim/0.9.1/share/nvim/runtime/lua/vim/diagnostic.lua:1179: in function 'show'
	...r/neovim/0.9.1/share/nvim/runtime/lua/vim/diagnostic.lua:1173: in function 'show'
	...r/neovim/0.9.1/share/nvim/runtime/lua/vim/diagnostic.lua:1595: in function 'enable'
	....local/share/nvim/lazy/LazyVim/lua/lazyvim/util/init.lua:207: in function <....local/share/nvim/lazy/LazyVim/lua/lazyvim/util/init.lua:204>
```

![Screenshot 2023-08-24 at 4 15 03 PM](https://github.com/LazyVim/LazyVim/assets/38049078/3c036054-8461-4ae3-a224-77b9decec0d6)

### Expected Behavior

To toggle UI Diagnostic back and forth without seeing errors.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by abeldekat** [comment]
Hello @ramfattah,

I don't think this is a bug in LazyVim. 
The toggle only calls `vim.diagnostic.enable()` or `vim.diagnostic.disable()`

I cannot reproduce the issue using the provided steps. There are no diagnostics...)
Which tools need to be installed?

The error happens in neovim's diagnostic.lua:
You could search the issues of neovim's repository for `Invalid 'line': out of range`

Best regards!

**Comment by dpetka2001** [comment]
I also couldn't reproduce this on a fresh starter template. Like @abeldekat mentioned, maybe it would be better to make an issue at Neovim's repo. 
@ramfattah What happens if instead of the keybinding you use `vim.diagnostic.disable()` and then `vim.diagnostic.enable()` (I expect you get the same error)? The keybinding only executes these 2 functions, which have nothing to do with Lazyvim, but rather Neovim itself.

**Comment by ramfattah** [comment]
Thanks for the suggestions Team!! 

@dpetka2001, surprisingly the UI Diagnostics is working now, not sure what was the issue there intially.
