### ISSUE TITLE
feature: extend root file extensions dynamically as configuration parameter 

### ISSUE THREAD

**Issue by franroa** [LazyVim/LazyVim#1375]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

I am using projects which are completely managed as symlinks by an owner project (this is common  with dotfiles). In this case, there are projects where I have no .git or .lua files, since the whole git is managed by the owner project.

### Describe the solution you'd like

The idea would be to add in the config/lazy an option to define an array of extensions or whole file names which are added here https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/util/init.lua#L5 instead of setting them statically.

### Describe alternatives you've considered

Alternative would be to use a plugin for this, but I don't like this option, having a plugin  just for getting the root. For me this would be the cleanest option.

In porject.nvim you can define your root files, but for that you need to activate the plugin and combine with other plugins like neo-tree, which is already done by LazyVim

**Comment by franroa** [comment]
I have just  realized that fE keymap find the root defined in project.nvim. In any case, it would be nice not to have to activate the plugin

**Comment by folke** [comment]
You can do:

```lua
require("lazyvim.util").root_patterns = ...
```
