### ISSUE TITLE
First line is getting deleted while loading workspace or by using cmd mode

### ISSUE THREAD

**Issue by 1Mike1** [LazyVim/LazyVim#1383]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Ubuntu 20.04

### Describe the bug

After installation whenever i am trying to save the file it always delete the very first line, similarly when i opening project it is loading the workspace and while doing this it is again deleting the first line.

I tried reinstalling, also did the clean setup but no luck.
[nvim_issue.webm](https://github.com/LazyVim/LazyVim/assets/45176462/32ba3681-9671-478f-9919-d0d044e42346)

Please refer the attach video for the reference.

### Steps To Reproduce

1. Do a fresh installation.
2. Try to add any plugin or update any plugin details in config (lazy.lua)
3. Try open a project where it will load workspace

### Expected Behavior

It should not delete anything from the file until user decides to delete any word, line or paragraph.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
I cannot reproduce this with fresh starter template. Also you don't add your plugins specs in `/lua/config/lazy.lua`, but rather create a file in `/lua/plugins/` directory and put your spec in the file.

**Comment by 1Mike1** [comment]
I tried by creating a new spec file but still issue persist. May i know the neovim version which you are using now ?

**Comment by dpetka2001** [comment]
I build Neovim from source and currently I'm on commit `5d8ab32`.

**Comment by 1Mike1** [comment]
Awesome , Thanks for the details 😊

**Comment by amaanq** [comment]
I noticed this on my mac but not linux desktop fwiw

**Comment by dpetka2001** [comment]
Could it be terminal related on mac? Were you able to reproduce with different terminals on mac? Just throwing out ideas.

**Comment by 1Mike1** [comment]
I tried with bash and zsh but no luck. I reinstalled my neovim and again did the fresh installation but still facing the same issue.

**Comment by abeldekat** [comment]
This seems to be a neovim-dev problem:

- [nvim_buf_set_lines](https://github.com/neovim/neovim/pull/24889)
- [broken plugins](https://github.com/neovim/neovim/issues/24897)

**Comment by amaanq** [comment]
Yeah you're right, thanks - bisecting does reveal 008154954791001efcc46c28146e21403f3a698b as the bad commit

Neovim on my Linux machine was just a couple commits behind that, hence why I didn't notice :sweat_smile:

**Comment by 1Mike1** [comment]
Cool we finally got the root cause hope this will fixed soon.

**Comment by amaanq** [comment]
Just build neovim@5bb1795 for now

**Comment by aidan2129** [comment]
@amaanq Hello, What is build neovim@5bb17958? is it a commit ref? Can't seem to find it.

**Comment by dpetka2001** [comment]
It's only meant for if you're building Neovim from source. Otherwise you'll have to wait for a fix in the latest nightly release.

**Comment by folke** [comment]
This has been fixed in nightly a couple of days ago. Only Telescope still has issues for some reason.
