### ISSUE TITLE
bug:  debug python occur modulenotfounderror

### ISSUE THREAD

**Issue by mikewang68** [LazyVim/LazyVim#1386]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.91

### Operating system/version

manjaro

### Describe the bug

from pymongo import MongoClient
from matplotlib import pyplot as plt

### Steps To Reproduce

when debug python program ,  dap occur " Thread stopped due to exception of type ModuleNotFoundError" , and then stop running

### Expected Behavior

working normal

### Repro

```Lua
require("lazy").setup({
  spec = {
    -- add LazyVim and import its plugins
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- import any extras modules here
    { import = "lazyvim.plugins.extras.lang.typescript" },
    { import = "lazyvim.plugins.extras.lang.json" },
    { import = "lazyvim.plugins.extras.ui.mini-animate" },
    { import = "lazyvim.plugins.extras.lang.python" },
    { import = "lazyvim.plugins.extras.lang.rust" },
    { import = "lazyvim.plugins.extras.lang.java" },
    { import = "lazyvim.plugins.extras.lang.go" },
    { import = "lazyvim.plugins.extras.dap.core" },
    { import = "lazyvim.plugins.extras.dap.nlua" },
    { import = "lazyvim.plugins.extras.lang.clangd" },
    -- import/override with your plugins
    { import = "plugins" },
  },
```

**Comment by mikewang68** [comment]
i am sure pymongo and matplotlib installed , and  running in shell is nomarlly , use python3 test.py

**Comment by haininhhoang94** [comment]
hello there, I encounter the same problem and have solve it by:
`return {
  {
    "linux-cultist/venv-selector.nvim",
    cmd = "VenvSelect",
    opts = {
      name = {
        "venv",
        ".venv",
        "env",
        ".env",
      },
      dap_enabled = true,
    },
    keys = { { "<leader>cv", "<cmd>:VenvSelect<cr>", desc = "Select VirtualEnv" } },
  },
}
`
Basically, venv-selector need dap_enabled=true to fix this. I will create a pull request for this!

**Comment by mikewang68** [comment]
okay ，i am try it ,thanks

**Comment by folke** [comment]
I merged a PR to set `dap_enabled` by default. will make a new release later
