### ISSUE TITLE
question: [mode 'terminal'] how to disable <C-h> but keep original behavior

### ISSUE THREAD

**Issue by genmzy** [LazyVim/LazyVim#1387]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

wsl2-Ubuntu-20.04

### Describe the bug

- Most of shell use \<C-h\> and \<BS\> for "BackSpace", I'm used to using \<C-h\> to do "BackSpace"
- LazyVim use \<C-h\> to goto left window
- I have tried ` vim.keymap.set("t", "<C-h>", "<nop>", { noremap = true })` to disable "\<C-h\>", but that will also disable "BackSpace" behavior of shell
- I don't want to use ` vim.keymap.set("t", "<C-h>", "<BS>", { noremap = true })` because \<C-h\> is just one of all keymaps that I want to change back  
How can I fix it?

### Steps To Reproduce

It does not need to reproduce

### Expected Behavior

Find a way to configure that and keep original Terminal "BackSpace" behavior in LazyVim starter

**Comment by dpetka2001** [comment]
Could you try `vim.keymap.del("t", "<C-h>")`?

**Comment by genmzy** [comment]
> Could you try `vim.keymap.del("t", "<C-h>")`?

Oh, thank you, problem solved, close this
