### ISSUE TITLE
bug: The import statements are ordered when enabling the prettier formatter

### ISSUE THREAD

**Issue by GiancarlosIO** [LazyVim/LazyVim#1396]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

Macos 12.5.1

### Describe the bug

Hi there!
This is my first time using neovim and lazyvim, and I'm trying to use it as a replacement for vscode. After installing lazy.vim I found that all my import statements are being ordered on save-file if I have the prettier formatted enabled 😢 

https://github.com/LazyVim/LazyVim/assets/17274950/8f0479a1-0ea5-4e66-87f7-1eddfb3efc55

This only happens with lazy vim. I have tested my code and prettier config in vscode and in the command line (`prettier --write..` ) and it work as expected. Maybe the lazyvim prettier plugin has a default configuration that is overridden my prettier.config.js? 🤔 

### Steps To Reproduce

1. Install lazy vim: https://www.lazyvim.org/installation
2. Enable prettier: https://www.lazyvim.org/extras/formatting/prettier
3. Go to a ts file and save the file. You will see how the imports are sorted 😞 

### Expected Behavior

Prettier should not sort/order my imports 😢 

### Repro

I'm using the default lazy-vim configuration. I have not edited or added new plugins except the one for prettier.

````Lua
-- lua/config/lazy.lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- bootstrap lazy.nvim
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

require("lazy").setup({
  spec = {
    -- add LazyVim and import its plugins
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- import any extras modules here
    -- { import = "lazyvim.plugins.extras.lang.typescript" },
    { import = "lazyvim.plugins.extras.lang.json" },
    { import = "lazyvim.plugins.extras.ui.mini-animate" },




    -- I have enabled/modified only this.
    { import = "lazyvim.plugins.extras.formatting.prettier" },




    -- { import = "lazyvim.plugins.extras.linting.eslint" },
    -- import/override with your plugins
    { import = "plugins" },
  },
  defaults = {
    -- By default, only LazyVim plugins will be lazy-loaded. Your custom plugins will load during startup.
    -- If you know what you're doing, you can set this to `true` to have all your custom plugins lazy-loaded by default.
    lazy = false,
    -- It's recommended to leave version=false for now, since a lot the plugin that support versioning,
    -- have outdated releases, which may break your Neovim install.
    version = false, -- always use the latest git commit
    -- version = "*", -- try installing the latest stable version for plugins that support semver
  },
  install = { colorscheme = { "tokyonight", "habamax" } },
  checker = { enabled = true }, -- automatically check for plugin updates
  performance = {
    rtp = {
      -- disable some rtp plugins
      disabled_plugins = {
        "gzip",
        -- "matchit",
        -- "matchparen",
        -- "netrwPlugin",
        "tarPlugin",
        "tohtml",
        "tutor",
        "zipPlugin",
      },
    },
  },
})
````

**Comment by dpetka2001** [comment]
I cannot reproduce this with starter template and enabling only `prettier` extra. I tried in a vanilla `.js` file. Default Lazyvim doesn't configure prettier in any way. If you look at the [code](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/extras/formatting/prettier.lua) it just downloads it with `mason` and enables formatting via `null-ls`. Nothing else. Are you sure you didn't install any kind of prettier-sort-imports plugin and have some extended rules in your `.prettierrc`? Also you should take a look at this #542. It's being mentioned that `prettier.config.js` might have problems with `prettierd` and it's suggested that you use a `.prettierrc` for your configuration instead.

**Comment by GiancarlosIO** [comment]
@dpetka2001 I have tried moving my config to `.prettierrc` but it give me the same results, prettier ordering my imports 😢 . I have also checked my package.json files and I have not found any prettier plugin related to imports.[
Do you know if there is a way to enable logs for that prettier nvim?

something like the `output` section in vscode:

````bash
["INFO" - 7:50:44 PM] Using ignore file (if present) at /Users/*****/Documents/******/frontend-apps/.prettierignore
["INFO" - 7:50:44 PM] File Info:
{
  "ignored": false,
  "inferredParser": "yaml"
}
["INFO" - 7:50:44 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 7:50:44 PM] Prettier Options:
{
  "filepath": "/Users/*******/Documents/*******/frontend-apps/apps/my-app/.prettierrc",
  "parser": "yaml",
  "useTabs": false,
  "tabWidth": 2,
  "endOfLine": "lf",
  "singleQuote": true,
  "printWidth": 80,
  "bracketSameLine": false,
  "trailingComma": "all",
  "arrowParens": "avoid"
}
["INFO" - 7:50:44 PM] Formatting completed in 15ms.
````

**Comment by dpetka2001** [comment]
I know there is `null-ls` log in the `~/.cache/nvim/` directory but by default I think it logs only errors and warnings. Maybe if you enable [debug](https://github.com/jose-elias-alvarez/null-ls.nvim#how-do-i-enable-debug-mode-and-get-debug-output) mode you will get some messages that can help you.

**Comment by folke** [comment]
LazyVim does not configure any prettier options

**Comment by GiancarlosIO** [comment]
I'll move the issue to the prettierd repo. Thanks
