### ISSUE TITLE
bug: line numbers disappear

### ISSUE THREAD

**Issue by haskelcurry** [LazyVim/LazyVim#1412]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.3

### Operating system/version

MacOS 13.5.1

### Describe the bug

Line numbers sometimes disappear, covered up by a colored line. I couldn't figure out neither the plugin that does this nor the reason. Sometimes it takes all of the lines in the file (like for JSON files), sometimes only a portion (see the picture).
<img width="28" alt="screenshot" src="https://github.com/LazyVim/LazyVim/assets/8557753/ef3084e8-7ab4-4397-94de-c3642cf70335">

### Steps To Reproduce

1. Open any JSON file (some of them are shown ok, I can't figure out the exact reasons)
2. Observe the line numbers pane

### Expected Behavior

Line numbers should never be covered / hidden.

**Comment by abeldekat** [comment]
Hello @haskelcurry,

I can't reproduce this behaviour using an unmodified lazyvim starter, opening lazy-lock.json.

**Comment by haskelcurry** [comment]
I've just tried that with package-lock.json and it was working too... I guess it's not for all JSONs, but I can't figure out the exact causes.

**Comment by abeldekat** [comment]
@haskelcurry,

Can you reproduce the issue using an unmodified [lazyvim starter](https://github.com/LazyVim/starter)?

**Comment by haskelcurry** [comment]
@abeldekat yes you are right, it works ok with starter! Could you be so kind to give me a hint on how can I figure out what plugin does this?

**Comment by haskelcurry** [comment]
@abeldekat Again you're right, I've set `signcolumn=number` to preserve the space...  
When I remove it, everything works fine again.  
Is there a way to use `signcolumn=number` with LazyVim?

**Comment by abeldekat** [comment]
@haskelcurry,

Great! I think those vertical lines are rendered by the [`gitsigns`](https://github.com/lewis6991/gitsigns.nvim) plugin, indicating you changed some code.

As this isn't a bug in LazyVim, could you ask the question regarding `signcolumn` in the [discussions](https://github.com/LazyVim/LazyVim/discussions) section?

Best regards!

**Comment by haskelcurry** [comment]
@abeldekat Thank you sir, we can close this issue as not a bug.
