### ISSUE TITLE
bug: Windows flashback

### ISSUE THREAD

**Issue by lingllqs** [LazyVim/LazyVim#1419]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev

### Operating system/version

archlinux kernel 6.4.3

### Describe the bug

When I use the plugin ‘voldikss/vim-translator’, the popup window flickers out

### Steps To Reproduce

1. install plugin voldikss/vim-translator’
             return {
              "voldikss/vim-translator",
              config = function()
                vim.cmd([[
                    let g:translator_default_engines = ['google']
                    nmap <silent> mm <Plug>TranslateW
                    vmap <silent> mm <Plug>TranslateWV
                    ]])
              end,
            }
2. select a word
3. input command TranslateW or press mm in normal mode

### Expected Behavior

The pop-up window continues to display

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by lingllqs** [comment]
I deleted lazyvim and reinstalled it, then installed this plugin and still have the problem

**Comment by dpetka2001** [comment]
Make sure to also delete the 
> -- required
mv ~/.config/nvim{,.bak}
-- optional but recommended
mv ~/.local/share/nvim{,.bak}
mv ~/.local/state/nvim{,.bak}
mv ~/.cache/nvim{,.bak}

like mentioned in the [docs](https://www.lazyvim.org/installation). I tried with a fresh starter Lazyvim template and didn't have any problem.

**Comment by dpetka2001** [comment]
![2023-09-05_17-39](https://github.com/LazyVim/LazyVim/assets/12776461/58d222f8-b1c2-4a2a-b4da-d51abbefe6d2)

It's been like this for 5 minutes now without any flashback.

**Comment by lingllqs** [comment]
Yeah, I deleted everything, including the cache

**Comment by dpetka2001** [comment]
Maybe it has to do with your terminal or Neovim version. I use kitty and latest Neovim built from source. Not able to reproduce.

**Comment by lingllqs** [comment]
thankyou very much
It is indeed a problem with nvim version
It works in  version 0.9
