### ISSUE TITLE
feature: Document choice of "find_files" or "git_files" based on `.git`

### ISSUE THREAD

**Issue by maxmahlke** [LazyVim/LazyVim#1425]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

I was trying to set `telescope` picker defaults for `<leader><space>`: `Find Files (root dir)` according to the docs.
The picker settings in

```
return {
  "nvim-telescope/telescope.nvim",
  opts = {
    pickers = {
      find_files = {
        ...
      }
    }
  }
```

were sometimes taking effect, sometimes not.

### Describe the solution you'd like

This comment showed me the solution:

https://github.com/LazyVim/LazyVim/blob/a72a84972d85e5bbc6b9d60a0983b37efef21b8a/lua/lazyvim/util/init.lua#L93

The fact that the keybind description says "Find Files" is fitting but unfortunately misleading because it seems like this function just calls the `find_files` picker. The fact that both `find_files` and `git_files` are used in this function chould be documented, e.g. here:

https://www.lazyvim.org/keymaps

For every function that calls `Util.telescope("files")` under the hood, it could say:

`<leader><space>` - Find Files (root dir) - uses either `find_files` or `git_files` picker

### Describe alternatives you've considered

I looked if I could contribute to the website directly but didn't find where the page source is hosted.

**Comment by dpetka2001** [comment]
You could make a PR at the website's [repo](https://github.com/LazyVim/lazyvim.github.io).

**Comment by maxmahlke** [comment]
Thanks @dpetka2001, I looked for the repo under folke's profile.

 It looks like that the keymap docs are built automatically from the `desc` keys of the `map` command, so my suggestion
of extending the documentation doesn't work (would make the description shown in 'which-key` too verbose).
