### ISSUE TITLE
bug: format doesn't work with lang.yaml

### ISSUE THREAD

**Issue by linsui** [LazyVim/LazyVim#1435]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

NixOS

### Describe the bug

I enabled extras.lang.yaml but it seems the formatter doesn't work. I thought https://github.com/redhat-developer/yaml-language-server/issues/486 is related.

### Steps To Reproduce

Enable extras.lang.yaml and try to format a yaml file.

### Expected Behavior

The formatter works.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
You need to enable the yaml extra. That also enables formatting https://www.lazyvim.org/extras/lang/yaml

**Comment by folke** [comment]
I used this as a test:

```yaml
aa:      123
```

**Comment by linsui** [comment]
> You need to enable the yaml extra.

I enabled this. I only added

```lua
{ import = "lazyvim.plugins.extras.lang.yaml" },
```

to lazy.lua to enable the yaml support. Then I open the test yaml file and save it with `:w`. Nothing happens. It seems I should be able to format the file with `<leader>cf` but the kepmap is not displayed in which-key and it doesn't work, either.

> If it still woudln't work, you can enable the formatter debugging by setting an lspconfig option format_notify = true

I'm not sure where I should add this. I try to add it in the yamlls block but it doesn't make any difference.

**Comment by folke** [comment]
Have you tried updating yamlls through mason?

What does :LspInfo show?

**Comment by linsui** [comment]
yamlls is installed via mason.

```
 Language client log: /home/l/.local/state/nvim/lsp.log
 Detected filetype:   yaml
 
 1 client(s) attached to this buffer: 
 
 Client: yamlls (id: 1, bufnr: [11])
 	filetypes:       yaml, yaml.docker-compose
 	autostart:       true
 	root directory:  /home/l/.dotfiles
 	cmd:             /home/l/.local/share/nvim/mason/bin/yaml-language-server --stdio
 
 Configured servers list: lua_ls, yamlls, jsonls
```

**Comment by folke** [comment]
No idea then. All I can say is that it works with a default LazyVim install using that extra

**Comment by linsui** [comment]
I'm testing it on a fresh LazyVim install with only the extra yaml change. I'm confused...

**Comment by folke** [comment]
Can you show me your lazy config? You need to add the extra after importing LazyVim and before importing your own plugins

**Comment by linsui** [comment]
I only changed the lazy.lua to enable the yaml support:

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- bootstrap lazy.nvim
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable",
    lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

require("lazy").setup({
  spec = {
    -- add LazyVim and import its plugins
    { "LazyVim/LazyVim",                          import = "lazyvim.plugins" },
    -- import any extras modules here
    -- { import = "lazyvim.plugins.extras.lang.typescript" },
    -- { import = "lazyvim.plugins.extras.lang.json" },
    -- { import = "lazyvim.plugins.extras.ui.mini-animate" },
    -- import/override with your plugins
    { import = "lazyvim.plugins.extras.lang.yaml" },
    { import = "plugins" },
  },
  defaults = {
    -- By default, only LazyVim plugins will be lazy-loaded. Your custom plugins will load during startup.
    -- If you know what you're doing, you can set this to `true` to have all your custom plugins lazy-loaded by default.
    lazy = false,
    -- It's recommended to leave version=false for now, since a lot the plugin that support versioning,
    -- have outdated releases, which may break your Neovim install.
    version = false, -- always use the latest git commit
    -- version = "*", -- try installing the latest stable version for plugins that support semver
  },
  install = { colorscheme = { "tokyonight", "habamax" } },
  checker = { enabled = true }, -- automatically check for plugin updates
  performance = {
    rtp = {
      -- disable some rtp plugins
      disabled_plugins = {
        "gzip",
        -- "matchit",
        -- "matchparen",
        -- "netrwPlugin",
        "tarPlugin",
        "tohtml",
        "tutor",
        "zipPlugin",
      },
    },
  },
})
```

**Comment by folke** [comment]
What's your Neovim version? You need at least the latest stable for format to work, since yamlls advertises formatting with dynamic capabilities

**Comment by linsui** [comment]
It's 0.9.1. Only the yaml format doesn't work...

**Comment by folke** [comment]
that's it then. you need 0.9.2 . That version supports dynamic registration

**Comment by linsui** [comment]
Ah, when I opened this issue I was using 0.9.1 but it's 0.9.2 now.

**Comment by folke** [comment]
Apparently this only worked on nightly.

I just added a work-around for Neovim < 0.10. Will make a new release later

**Comment by linsui** [comment]
It works now, thanks!
