### ISSUE TITLE
go extra (gopls): duplicate configuration for directoryFilters

### ISSUE THREAD

**Issue by lazywei** [LazyVim/LazyVim#1440]
Not sure why but it seems this line https://github.com/LazyVim/LazyVim/blame/a72a84972d85e5bbc6b9d60a0983b37efef21b8a/lua/lazyvim/plugins/extras/lang/go.lua#L54 is causing the following error message for Golang lsp:

```
LSP Message (gopls): Invalid settings: parsing setting "directoryFilters": duplicate configuration for directoryFilters
```

I did some search in the whole LazyVim and my whole pluggins directory and this is the only place that sets `directoryFilters` so not sure where the "duplication" comes from.

Commenting out this line makes the error messages go away.

Enabled extra:
```
    { import = "lazyvim.plugins.extras.lang.go" },

```

Screenshot:
![image](https://github.com/LazyVim/LazyVim/assets/2840571/38210c08-6685-4252-b938-dae160a7ca9a)

**Comment by dpetka2001** [comment]
Do you happen to have a `.vscode/settings.json` file in your project that might have settings from VsCode?
