### ISSUE TITLE
bug: <home> key don't work

### ISSUE THREAD

**Issue by lbgws2** [LazyVim/LazyVim#1467]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9

### Operating system/version

ubuntu 22.04

### Describe the bug

When I use n/i mode, the<home>key does not work, but there is no problem using vim

### Steps To Reproduce

I used the default configuration

### Expected Behavior

Move to the beginning of the line

**Comment by dpetka2001** [comment]
I cannot reproduce. For me it works correctly both in n/i modes. I'm using Neovim nightly, don't know if that's a factor to consider. Maybe it's some kind of setting of the terminal you use.

**Comment by lbgws2** [comment]
which path should i search for the default keymap setting??

**Comment by folke** [comment]
for sure a terminal setting
