### ISSUE TITLE
bug: lsp_disable seems to only enable language servers

### ISSUE THREAD

**Issue by tmcw** [LazyVim/LazyVim#1469]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.2

### Operating system/version

macOS 13.5.2 (22G91)

### Describe the bug

If I have a file structure like

```
package.json
directory/
   deno.json
   file.ts
```

I'd _hope_ that `file.ts` gets the Deno language server and not the TypeScript language server. Getting both tends to muck things up.

However, I get both servers running at the same time. This especially hits when the you're using Deno's built-in support for package.json.

What it appears to be as a root cause is that there's this code that tries to only enable one at a time:

https://github.com/LazyVim/LazyVim/blob/a72a84972d85e5bbc6b9d60a0983b37efef21b8a/lua/lazyvim/plugins/lsp/init.lua#L197C1-L202

But the method that it triggers, `lsp_disable` is only capable of turning language servers on, not off:

https://github.com/LazyVim/LazyVim/blob/a72a84972d85e5bbc6b9d60a0983b37efef21b8a/lua/lazyvim/util/init.lua#L263

### Steps To Reproduce

1. Have a file structure with both deno.json and package.json files
2. Open a TypeScript or JavaScript file

### Expected Behavior

Only Deno or TypeScript should be booted up.

### Repro

```Lua
-- Reproducible with lazy starter with no changes
```

**Comment by folke** [comment]
It will correctly disable one of the two. The problem in your case is that you have two root dirs.

The easiest way to fix this is by creating an empty file `.neoconf.json` in the actual root dir.

There's other ways to fix this, but that's the easiest
