### ISSUE TITLE
bug: Trouble to install nvim-orgmode

### ISSUE THREAD

**Issue by juridiener** [LazyVim/LazyVim#1471]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-37+gccc0980f8

### Operating system/version

Mac

### Describe the bug

Does not open the agende or the capturing mode.

### Steps To Reproduce

In LazyVim
Installed nvim-orgmode.
Press <leader>oa   ==> nothing happens
Press <leader>oc  ==> nothing happens

Add under plugins/nvim-org.lua:
```
return {
  "nvim-orgmode/orgmode",
  dependencies = {
    { "nvim-treesitter/nvim-treesitter", lazy = true },
  },
  event = "VeryLazy",
  config = function()
    -- Load treesitter grammar for org
    require("orgmode").setup_ts_grammar()

    -- Setup treesitter
    -- Commented out because got following warning:
    -- Missing required fields in type `TSConfig`: `modules`, `sync_install`, `ignore_install`, `auto_install` [missing-fields]
    -- require("nvim-treesitter.configs").setup({
    --   highlight = {
    --     enable = true,
    --     additional_vim_regex_highlighting = { "org" },
    --   },
    --   ensure_installed = { "org" },
    -- })

    -- Setup orgmode
    require("orgmode").setup({
      org_agenda_files = "~/Documents/org-files/**/*",
      org_default_notes_file = "~/Documents/org-files/refile.org",
    })
  end,
}
```

### Expected Behavior

Open Agende or Capture Mode.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
It works for me with the recommended configuration from the [repo](https://github.com/nvim-orgmode/orgmode#installation). Also this is a personal user configuration, so I believe it's more appropriate for the `Discussions` section and not an issue of Lazyvim.

**Comment by juridiener** [comment]
> It works for me with the recommended configuration from the [repo](https://github.com/nvim-orgmode/orgmode#installation). Also this is a personal user configuration, so I believe it's more appropriate for the `Discussions` section and not an issue of Lazyvim.

Ok thanks. Do you know how can i troubleshoot this problem? And why i get the warning message : Missing required fields in type `TSConfig`: `modules`, `sync_install`, `ignore_install`, `auto_install` [missing-fields]

**Comment by dpetka2001** [comment]
You can disregard these messages. They come from Lua LSP. Alternatively, you could also just extend the default Lazyvim Treesitter configuration to include these options for Treesitter. I didn't do anything else except from copy/pasting the instructions for `lazy.nvim`. Then I just pressed `<leader>oa` and the agenda menu opened.

**Comment by juridiener** [comment]
> You can disregard these messages. They come from Lua LSP. Alternatively, you could also just extend the default Lazyvim Treesitter configuration to include these options for Treesitter. I didn't do anything else except from copy/pasting the instructions for `lazy.nvim`. Then I just pressed `<leader>oa` and the agenda menu opened.

Okay that's really interesting. But this should work with a minimal.lua config right? if other plugins causing this problem. Can You maybe me provide a minimal.lua config so i can test it? I tried to put the configurations in this repro.lua file under plugins with {...} but i think maybe i did something wrong.

**Comment by dpetka2001** [comment]
```
1. mkdir ~/.config/newstarter && cd ~/.config/newstarter
2. git clone https://github.com/LazyVim/starter .
3. rm -rf .git*
4. `NVIM_APPNAME=newstarter nvim` and wait for installation of plugins to finish
5. Quit Neovim and start again with: `NVIM_APPNAME=newstarter nvim lua/plugins/orgmode.lua`
6. Paste the contents of the installation steps for `lazy.nvim` mentioned [here](https://github.com/nvim-orgmode/orgmode#installation) in the file that you opened. 
7. Quit and restart Neovim again with the aforementioned command and press `<leader>oa` and you should see the agenda menu opening in a popup menu.
```
I didn't test anything else, since I don't use the plugin and don't know how it works.
