### ISSUE TITLE
bug: :set linebreak not working

### ISSUE THREAD

**Issue by firubat** [LazyVim/LazyVim#1475]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.2 Build type: Release LuaJIT 2.1.1692716794

### Operating system/version

linux mint 21.2

### Describe the bug

`:set linebreak` not working.

### Steps To Reproduce

1. Install lazyvim as explained in docs
2. Open nvim  
3. Create new file. Insert text longer than window size
4. Enter `:set linebreak`

### Expected Behavior

Lines should get wrapped to fit window size.

**Comment by dpetka2001** [comment]
Do you have `wrap` enabled as well?

**Comment by firubat** [comment]
Don't know what that is, so don't know 🤷
 It didn't require anything else without Lazyvim.

**Comment by firubat** [comment]
Oh OK, thanks alot!
I'll read more thoroughly.
Why does lazyvim disable it?

**Comment by firubat** [comment]
Sure, was just wondering if it's preference or that it interferes with something.
