### ISSUE TITLE
Remap default localleader

### ISSUE THREAD

**Issue by juridiener** [LazyVim/LazyVim#1477]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-37+gccc0980f8

### Operating system/version

Mac

### Describe the bug

When i set in options.lua a different binding it does not work.
vim.g.maplocalleader = ","

### Steps To Reproduce

1. Set the binding in options.lua  
vim.g.maplocalleader = ","

I noticed the error when I installed neorg. 
And in a norg file when I pressed the following key combination ,nn to create a new file
Then I had this error message:
E486: Pattern not found: some text

### Expected Behavior

To override the localleader

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
What does `echo maplocalleader` show?

**Comment by juridiener** [comment]
> What does `echo maplocalleader` show?

Where i should put this? I tried it in the comman mode and got nothing

**Comment by dpetka2001** [comment]
If you press `:echo maplocalleader` it should echo the value of current `maplocalleader`. Notice the `:` at the start, so that you enter command mode.

**Comment by juridiener** [comment]
https://github.com/LazyVim/LazyVim/assets/92093874/b6fe6ce7-97f7-4baf-98d3-a14b593dcda9

**Comment by dpetka2001** [comment]
![2023-09-22_17-34](https://github.com/LazyVim/LazyVim/assets/12776461/1c073447-3297-4b32-b751-f7df11a3305f)
This is what I get when setting in `~/.config/nvim/lua/config/options.lua` the option `vim.g.maplocalleader = ","`.

**Comment by dpetka2001** [comment]
I tested this on default Lazyvim starter template. So, maybe there's something wrong with your configuration? Can you try testing with a new Lazyvim starter template, so that you only have default settings?

**Comment by juridiener** [comment]
Is it Maybe helpful when i provide my config? https://github.com/juridiener/dotfiles-config/tree/main/LazyVim
To see if you get the same result.

**Comment by dpetka2001** [comment]
You seem to be changing here https://github.com/juridiener/dotfiles-config/blob/1665df7d0db5e12d5e780f5c3a915a34efb0e803/LazyVim/lua/plugins/neorg.lua#L26 the `neorg_leader` which by default is mapped to `LocalLeader`. Maybe that's the issue?

**Comment by dpetka2001** [comment]
If I comment out that line in your configuration for `neorg`, for me changing `vim.g.maplocalleader = ","` and then pressing `,nn` in a norg file it pops up a menu for `New Note`. You might also want to change the default `vim.opt.timeoutlen = 300` to a little higher value (I set it to 1000), because otherwise you have to press `,nn` real quickly for the keybind to take effect. I just increased the value, so that I can have a bit more room between pressing `,` and then `nn`.

**Comment by juridiener** [comment]
> You seem to be changing here https://github.com/juridiener/dotfiles-config/blob/1665df7d0db5e12d5e780f5c3a915a34efb0e803/LazyVim/lua/plugins/neorg.lua#L26 the `neorg_leader` which by default is mapped to `LocalLeader`. Maybe that's the issue?

No I just edit this so i can work with it, I did not had this before in my code when i created the issue. 
But why when i did echo maplocalleader i got nothing? 
What do you get when trying echo?

**Comment by dpetka2001** [comment]
`echo` shows me the picture that I showed you in my previous post. That's after changing `maplocalleader = ","`, because in the default Lazyvim I get `\`, which is the Lazyvim default `maplocalleader`.

**Comment by folke** [comment]
setting `maplocalleader` in your options.lua is the way to change this and **does** work as intended

**Comment by juridiener** [comment]
Okay thank you for helping me. I think the timeoutlen option was the issue.

**Comment by dpetka2001** [comment]
@juridiener Another thing I noticed is that the keymaps from `neorg` don't correctly register under `which-key` without invoking the `which-key` menu yourself already before. So, if you just press `<leader>` to invoke the `which-key` menu, then you can hit `Esc` to close it and then press `,` (your `maplocalleader`) it will show the mappings for your `maplocalleader` as well and you will be able to see the `neorg` keymaps. Not all of them have descriptions, but you can understand visually what you're doing.

**Comment by teial** [comment]
I have the same issue as @dpetka2001 - I need to first invoke leader to make local leader work. If I just open norg file and press my local leader key it will have no effect.

**Comment by dpetka2001** [comment]
@teial Try putting in `~/.config/nvim/lua/config/keymaps.lua` the following
```lua
vim.keymap.set("n", "<localleader>", '<cmd>lua require("which-key").show("\\\\")<cr>')
```
and test to see how it's working for you.

**Comment by teial** [comment]
It worked! Thank you!

**Comment by signal-intrusion** [comment]
I'm having major problems just remapping `<leader>` to `","`. I've tried just about everything I can think of. What's the simplest way to make `,` my leader?

**Comment by tallamjr** [comment]
> I'm having major problems just remapping `<leader>` to `","`. I've tried just about everything I can think of. What's the simplest way to make `,` my leader?

@signal-intrusion I have found adding `vim.g.mapleader = ","` to your `$HOME/config/.config/nvim/lua/config/options.lua` does the trick. Hope that helps.

**Comment by oleynikandrey** [comment]
> [@teial](https://github.com/teial) Try putting in `~/.config/nvim/lua/config/keymaps.lua` the following
> 
> vim.keymap.set("n", "<localleader>", '<cmd>lua require("which-key").show("\\\\")<cr>')
> and test to see how it's working for you.

I have the same problem with the `grug-far`: local leader not working before hitting the leader key. Setting the local leader as you suggested helps, but I got the following warning when I hit the local leader in other files:

```
Recursion detected.
Are you manually loading which-key in a keymap?
Use `opts.triggers` instead.
Please check the docs.
```

Could you please give advice on how to fix it?

**Comment by dpetka2001** [comment]
@oleynikandrey Try 
```lua
return {
  {
    "MagicDuck/grug-far.nvim",
    keys = {
      { "<localleader>", '<cmd>lua require("which-key").show("\\\\")<cr>', ft = "grug-far" },
    },
  },
}
```
and remove the other keymap that you have. If you want to have this for multiple filetypes and not having to define it in each plugin spec, then your best bet would be to define it in an autocmd that triggers on `FileType` event and define the filetypes that you want this mapping set.

**Comment by oleynikandrey** [comment]
@dpetka2001, thank you for the solution.

Since `grug-far` is the default plugin, shouldn't it work without any configuration changes? I tried the clean starter LazyVim config, and the local leader doesn't function unless I press the leader key first.

**Comment by dpetka2001** [comment]
That's a problem with how which-key operates. Not Lazyvim related.

**Comment by antoniorodr** [comment]
> [@oleynikandrey](https://github.com/oleynikandrey) Try
> 
> return {
>   {
>     "MagicDuck/grug-far.nvim",
>     keys = {
>       { "<localleader>", '<cmd>lua require("which-key").show("\\\\")<cr>', ft = "grug-far" },
>     },
>   },
> }
> and remove the other keymap that you have. If you want to have this for multiple filetypes and not having to define it in each plugin spec, then your best bet would be to define it in an autocmd that triggers on `FileType` event and define the filetypes that you want this mapping set.

Hi @dpetka2001 !

Thanks for this. It's possible to make this to work globally?

I did it too with `octo.nvim`, but if I need to do it with every plugins which is using `localleader` it will be a nightmare...

EDIT: Nevermind, I see you posted it already.
