### ISSUE TITLE
How to reproduce the autocomplete function arguments

### ISSUE THREAD

**Issue by Good1Cheese** [LazyVim/LazyVim#1490]
When autocompleted in LazyVim, function arguments autocomplete too. I have tried to paste into my configuration all things related to cmp and LSP, but it doesn't help.
**Lua_ls "Replace"** option also doesn't work.

How can I achieve this?

**Comment by dpetka2001** [comment]
Is this really a Lazyvim issue?? `Discussions` seem like more appropriate to me I believe.

**Comment by Good1Cheese** [comment]
You are right
