### ISSUE TITLE
bug: Golang - removing all references to an import does not remove it from the import list on save.

### ISSUE THREAD

**Issue by jeffdupont** [LazyVim/LazyVim#1499]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.1

### Operating system/version

MacOS 13.5.2

### Describe the bug

When typing on a .go file, if I add code for packages that are not imported, it seems to add them to the import list as expected. However, if I remove all references to the same package, the import list is not modified and errors that the package is "imported and not used". 

### Steps To Reproduce

1. Open a *.go file
2. Add reference to a new package and see it appends the package correctly to the import list
3. Remove all references to the package
4. Save file and see that the import remains and displays package issue that it is "imported and not used"

### Expected Behavior

The on save format would correctly remove unused packages

### Repro

```Lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- bootstrap lazy.nvim
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

require("lazy").setup({
  spec = {
    -- add LazyVim and import its plugins
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- import any extras modules here
    { import = "lazyvim.plugins.extras.lang.typescript" },
    { import = "lazyvim.plugins.extras.lang.json" },
    { import = "lazyvim.plugins.extras.ui.mini-animate" },
    { import = "lazyvim.plugins.extras.lang.go" },
    { import = "lazyvim.plugins.extras.test.core" },
    { import = "lazyvim.plugins.extras.dap.core" },
    { import = "lazyvim.plugins.extras.formatting.prettier" },
    { import = "lazyvim.plugins.extras.vscode" },
    { import = "lazyvim.plugins.extras.ui.edgy" },
    -- import/override with your plugins
    { import = "plugins" },
  },
  defaults = {
    -- By default, only LazyVim plugins will be lazy-loaded. Your custom plugins will load during startup.
    -- If you know what you're doing, you can set this to `true` to have all your custom plugins lazy-loaded by default.
    lazy = false,
    -- It's recommended to leave version=false for now, since a lot the plugin that support versioning,
    -- have outdated releases, which may break your Neovim install.
    version = false, -- always use the latest git commit
    -- version = "*", -- try installing the latest stable version for plugins that support semver
  },
  install = { colorscheme = { "tokyonight", "habamax" } },
  checker = { enabled = true }, -- automatically check for plugin updates
  performance = {
    rtp = {
      -- disable some rtp plugins
      disabled_plugins = {
        "gzip",
        -- "matchit",
        -- "matchparen",
        -- "netrwPlugin",
        "tarPlugin",
        "tohtml",
        "tutor",
        "zipPlugin",
      },
    },
  },
})


-- lua/plugins/go.lua
return {
  {
    "neovim/nvim-lspconfig",
    opts = function(_, opts)
      opts.servers.gopls.settings.gopls.semanticTokens = false
    end,
  },
}
```

**Comment by dpetka2001** [comment]
Lazyvim uses `vim.lsp.buf.format` for formatting on save. That's entirely on the LSP server. For your particular case, I'd guess that `goimports_reviser` is the one responsible for importing the necessary packages. If you look at official [docs](https://pkg.go.dev/github.com/incu6us/goimports-reviser), it mentions it also accepts an option `-rm-unused` to remove unused imports. You should pass that as extra argument in null-ls when setting up `goimports-reviser`. You should take a look at null-ls official [docs](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTIN_CONFIG.md#arguments) for how to achieve that. This is not a Lazyvim problem, but a user configuration issue.

**Comment by jeffdupont** [comment]
Yes and no, if developers are following the setup on the lazy website then
that should be considered to be included in that documentation. Especially
those coming over from vscode and just starting out. I'm not a beginner,
but I still had difficulty figuring out where and why this was happening
and I did look through the plugins I thought was responsible. The autocmd
from the gopls site did end up working for me... but if it was really just
as simple as adding that option, then I'd much rather have that.

**Comment by dpetka2001** [comment]
You can't expect the Lazyvim website to include all official documentation of every plugin it uses, right? Even the `extras` Lazyvim provides, have some kind of personal bias from the people that actually make the PRs depending on what features they use on their own. That's why there are improvements made on PRs by other people to include other common features. So, feel free to submit a PR with how to make this work and the maintainer will make the final decision. I don't use Go myself and don't use at all the Go extra.

**Comment by jeffdupont** [comment]
You're right I wouldn't, but when the extras section attempts to make it
simple and easy to turn Go on, it probably should be part of those
settings.

**Comment by dpetka2001** [comment]
And that's why I said that PRs can get improved. Rust, Python and even Java have gone through transformations to include more things than the original PR. So, make a PR yourself, so that the Go extra gets improved :smile:
