### ISSUE TITLE
feature: Make included autocommands revertable/optional

### ISSUE THREAD

**Issue by TamasBarta** [LazyVim/LazyVim#150]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Whenever I resize the window, it switches to the last tab, so I cannot continue working, I have to switch back. I had the same issue with LunarVim, and it was tracked down, that the issue causing it was this autocommand: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua#L16 (the link shows its occurrence in LazyVim)

At the moment I found no solution to disable individual autocommands in LazyVim, because they are not in groups, and the Neovim API I found to remove autocommands take an integer, which my understanding is coming from registering the autocommand, that's not in my code, but in LazyVim's.

### Describe the solution you'd like

In LunarVim I could control individual autocommands, as they were in groups, and groups can be removed by name. If the autocommands were in groups, I could nullify the ones I don't like from LazyVim.

### Describe alternatives you've considered

I was thinking about ways to prevent setting the autocommands altogether, but that just looks unnecessary work, and as far as I can tell it doesn't align with the philosophy of the plugin either, but you tell me.

### Additional context

I even checked the sources, but the lua files tell me there's no conditionality anywhere near loading the autocommands (or the options, but those are easy to change afterwards).

**Comment by TamasBarta** [comment]
I forked "LazyVim/LazyVim" to experiment, and I found that if I wrap "VimResized" in a group, and try to delete a group, I cannot do that, the group is not found.

I thought maybe my autocmds.lua is loaded earlier than LazyVim's, but https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/init.lua#L123 suggests otherwise.

After some amount of research I found that iteration over tables is not deterministic (my source: https://stackoverflow.com/questions/66329522/what-makes-lua-tables-key-order-be-undeterministic sorry, I'm a Lua noob).

Running the plugin's and the user's configs in non-deterministic order itself is I believe a bug, but even if you accounted for that in the original design, this improvement would probably need that to change, if this idea is accepted.

**Comment by TamasBarta** [comment]
I got it all working in my fork. Have a look at my proposal in #151. It also fixes the indeterministic config load (that I could reproduce with the current foreach solution).

**Comment by folke** [comment]
I'll have a look at the PR later today.

That part about `ipairs` not being deterministic though is wrong. `pairs` is not deterministic, but `ipairs` will **ALWAYS** be in the correct order.

**Comment by TamasBarta** [comment]
I see, maybe I was clumsy when I tried to verify it (during testing, it looked like it needed the inner function refactor too to make the order right). Thanks for the info!

**Comment by TamasBarta** [comment]
I removed the refactor, and left only the augroup stuff in the PR in a new commit.

**Comment by folke** [comment]
Fixed in https://github.com/LazyVim/LazyVim/commit/f57031db7ce12ddf21c6a51a22a9370237a729b6
