### ISSUE TITLE
bug: vim-tmux-navigator shortcuts stopped working

### ISSUE THREAD

**Issue by ejazahm3d** [LazyVim/LazyVim#1502]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

MacOS Sonoma

### Describe the bug

The latest version of LazyVim broke vim-tmux-navigator. 
It was working fine and still is until version 6.3.0

### Steps To Reproduce

1. Install latest LazyVim
2. Install vim-tmux-navigator
3. Use it. It should switch to other windows using its shortcut

### Expected Behavior

It should switch to other window when I press the shortcut for it.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
    "christoomey/vim-tmux-navigator",

}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
It works fine for me even with the latest release. This is the [commit](https://github.com/dpetka2001/dotfiles/commit/9cd061381cf15e7444add6b4ab6e5064de04c41f) with the changes I made to incorporate it to LazyVim.

**Comment by ejazahm3d** [comment]
@dpetka2001 Thanks. But previously it has been working for me until 6.4.0 without manually adding keymaps. For now I reverted to previous version.

**Comment by dpetka2001** [comment]
You can add `event = "BufReadPre"` to your `vim-tmux-navigator` spec, so that keys load properly.

**Comment by folke** [comment]
It probably only used to work when opening a file directly from the cmdline, but not when opening just Neovim.

Keymaps in LazyVim are loaded on the VeryLazy event.

As @dpetka2001 suggested, you need to either set the correct mappings in your `keymaps.lua`, or load the plugin after that.
