### ISSUE TITLE
Categorized keybindings by default or optional

### ISSUE THREAD

**Issue by rathod-sahaab** [LazyVim/LazyVim#1507]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

LazyVim default keybindings are hard to remember 

### Describe the solution you'd like

The default keybindings or some boolean option than can let us enable categorised/tree like key bindings.

I believe it more inline with philosophy of vim keybindings idea `ciw, caw, diw, daB` as well as `which-key` plugin and new users of LazyVim will find it easier to learn these keybindings rather than current defaults.

```
Ex: In my old config
- l : LSP prefix
    - r : rename
    - f : format
    - d : +diagnostics
        - n: next
        - p: prev
        - e: expand
    - c : +code
        - a: actions
- g: git signs actions 
- t: Telescope operations

... and so on
```

You get the gist

  

### Describe alternatives you've considered

Override everything in my own config.

1. That seems like redundant work
2. It would be just fragmenting the community, for a feature which I believe can benefit all.

**Comment by folke** [comment]
Not sure what you mean, since LAzyVim key bindings are already categorized
