### ISSUE TITLE
bug: indent-blankline: migration version 2 -> version 3

### ISSUE THREAD

**Issue by msMatix** [LazyVim/LazyVim#1509]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.2

### Operating system/version

windows/10

### Describe the bug

After opening a project like Python or cpp the following error message is printed when opening the first source file:

```
You are trying to call the setup function of indent-blankline version 2, but you have version 3 installed.
Take a look at the readme for instructions on how to migrate, or revert back to version 2.
```

In the corresponding repository a migration from v2.0 to v3.0 has to be done. With Version 2.0 everything works as expected.

### Steps To Reproduce

1. Just Update the package:  "lukas-reineke/indent-blankline.nvim"

### Expected Behavior

No error message output

**Comment by folke** [comment]
Fixed by https://github.com/LazyVim/LazyVim/commit/db86635e3276451f795da4f8af64eff94391fe48
