### ISSUE TITLE
feature: Consider replacing s and S flash key mappings as they override basic keys

### ISSUE THREAD

**Issue by dsirov** [LazyVim/LazyVim#1511]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Current flash (and previous leap) key mappings override the basic `s` and `S` keys in normal mode:

Key | Description | Mode
-- | -- | --
s | Flash | n, x, o
S | Flash Treesitter | n, o, x
. . . | . . . | . . .

While one can argue that basic vim's `s` is not used quite often,  IMHO `S` is very useful (I use it all the time).
Anyway, some people may be used to using the basic keys...

Keep up the awesome job you are doing!

### Describe the solution you'd like

Please consider changing the default mapping using the `<leader>`

### Describe alternatives you've considered

-

**Comment by folke** [comment]
Feel free to disable the mappings in your own config for flash.

See https://www.lazyvim.org/configuration/keymaps

**Comment by dsirov** [comment]
Of course, I have done that.  ;)
However, I believe these are too basic of commands being overridden...

**Comment by berarma** [comment]
I also didn't expect LazyVim to replace basic commands with some unrelated functionality.
