### ISSUE TITLE
feature: deprecate mini.indentscope in favor of indent-blankline.nvim

### ISSUE THREAD

**Issue by OneOfOne** [LazyVim/LazyVim#1524]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

IBL supports indent scopes, although requires a bit of a hack.

This way it's one less plugin to depend on.

### Describe the solution you'd like

```lua
	{
		'lukas-reineke/indent-blankline.nvim',
		opts = {
			scope = {
				enabled = true,
				highlight = 'Function',
				include = {
					node_type = { ['*'] = { '*' } },
				},
			},
		},
	},
```

### Describe alternatives you've considered

n/a

**Comment by folke** [comment]
I added indentscope for its animations.

Feel free to remove it in your personal config
