### ISSUE TITLE
bug: Update failed in windows10 wsl2

### ISSUE THREAD

**Issue by lipppchen** [LazyVim/LazyVim#1525]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

widnows10

### Describe the bug

I have to computer. One Mac, One windows. Both install lazyvim, they use same network, same proxy, the Mac is works fine, update quickly. But the windows, mostly update plugins failed. The system remind me "fetch failed process was killed because it reached the timeout" 

### Steps To Reproduce

while(1)
{
   open nvim
   l
   U
   waiting ...........
   failed.
}

### Expected Behavior

Hope soneone can help me fix it   :(

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by lipppchen** [comment]
Sorry for the grammatical errors, hopefully it won't be too much of a reading problem for you guys

**Comment by dpetka2001** [comment]
I don't think this is a problem of Lazyvim. It might be Windows Firewall or even WSL itself (as I've read several google stuff about ppl with similar networking errors). One thing I might suggest is making sure that even on Windows you have installed git version >=2.19.0 as described in the `lazy.nvim` docs. Another thing you might want to try is setting `concurrency = 0` on windows in case the firewall limits the amount of outgoing connections from a particular process. Other than that, I really think you just will have to google for similar Windows problems and maybe you will find something that will help you. I don't use Windows, except for gaming, so I don't really know what else to suggest.

**Comment by folke** [comment]
set concurrency to something like 5

**Comment by chavesdaniel** [comment]
how I set the concurrency to 5 ?
