### ISSUE TITLE
bug: E5108: Error executing lua: .../nvim/lazy/venv-selector.nvim/lua/venv-selector/venv.lua:294: module 'dap-python' not found:

### ISSUE THREAD

**Issue by rghvdberg** [LazyVim/LazyVim#1528]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-742+g12ccea596

### Operating system/version

Ubuntu 22.04.3 LTS

### Describe the bug

crash when selecting virtual env , venv isn't enabled it seems

ftr, I dunno how to make that minimal Repro thingy below because I've only enabled the Python lang as instructed in https://www.lazyvim.org/extras/lang/python

Here's the error messag
==== output ====
12:15:01 msg_show.echo E5108: Error executing lua: .../nvim/lazy/venv-selector.nvim/lua/venv-selector/venv.lua:294: module 'dap-python' not found:
	no field package.preload['dap-python']
cache_loader: module dap-python not found
cache_loader_lib: module dap-python not found
	no file './dap-python.lua'
	no file '/__w/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/dap-python.lua'
	no file '/usr/local/share/lua/5.1/dap-python.lua'
	no file '/usr/local/share/lua/5.1/dap-python/init.lua'
	no file '/__w/neovim/neovim/.deps/usr/share/lua/5.1/dap-python.lua'
	no file '/__w/neovim/neovim/.deps/usr/share/lua/5.1/dap-python/init.lua'
	no file './dap-python.so'
	no file '/usr/local/lib/lua/5.1/dap-python.so'
	no file '/__w/neovim/neovim/.deps/usr/lib/lua/5.1/dap-python.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	.../nvim/lazy/venv-selector.nvim/lua/venv-selector/venv.lua:294: in function 'setup_dap_venv'
	.../nvim/lazy/venv-selector.nvim/lua/venv-selector/venv.lua:93: in function 'set_venv_and_system_paths'
	.../nvim/lazy/venv-selector.nvim/lua/venv-selector/venv.lua:217: in function 'activate_venv'
	...azy/venv-selector.nvim/lua/venv-selector/mytelescope.lua:159: in function 'key_func'
	...hare/nvim/lazy/telescope.nvim/lua/telescope/mappings.lua:257: in function <...hare/nvim/lazy/telescope.nvim/lua/telescope/mappings.lua:256>

### Steps To Reproduce

1. fresh install of LazyVim
2. add   `{ import = "lazyvim.plugins.extras.lang.python" },` to `lua/config/lazy.lua`
3. restart LazyVim
4. use VenvSelect to open a virtual environment

### Expected Behavior

not crash :-)

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by rghvdberg** [comment]
changing optional=true to false in https://github.com/LazyVim/LazyVim/blob/6f9adbd4fba4132bd4f12404bd2b90c4a28ff136/lua/lazyvim/plugins/extras/lang/python.lua#L47C5-L47C21 and https://github.com/LazyVim/LazyVim/blob/6f9adbd4fba4132bd4f12404bd2b90c4a28ff136/lua/lazyvim/plugins/extras/lang/python.lua#L31 fixes the crash

**Comment by dpetka2001** [comment]
You should also install [dap-core](https://www.lazyvim.org/extras/dap/core)

**Comment by folke** [comment]
Yeah, but it shouldnt give errors without dap. I think it's due to that dap_enabled in the venv config. That probably should conditionally be set only when dap is installed.


I don't work with python often. 
Can anyone give me the simple steps to trigger that error? Like what command do I use etc?

**Comment by dpetka2001** [comment]
I tried with a new Lazyvim starter template only adding the import for Python extra and am not able to reproduce the error. It just opens venv-selector without any error. I could see in the venv-selector [code](https://github.com/linux-cultist/venv-selector.nvim/blob/14d6e866070f759e9014a8053954f835294f56f9/lua/venv-selector/venv.lua#L92-L94) that it requires `nvim-dap-python` when that option is set, but I don't get any errors. I also don't have any DAP extras installed, but it seems that it's not affecting venv-selector in my case.

**Comment by rghvdberg** [comment]
I'm sorry, I've should have been more specific.
The crash happens **after** selecting a a virtual env.

**Comment by rghvdberg** [comment]
Here's a screen recording

[Schermopname van 30-09-23 15:02:47.webm](https://github.com/LazyVim/LazyVim/assets/10710663/cdf146dd-f744-43ff-a8c8-81a18ee5e98d)

**Comment by rghvdberg** [comment]
> I don't work with python often. Can anyone give me the simple steps to trigger that error? Like what command do I use etc?

```bash
mkdir lazypython
cd lazypython
python3 -m venv venv
nvim
```
 - press `<leader> cv`
- search for the venv
- select, press enter

**Comment by dpetka2001** [comment]
I see what you mean. I can confirm this also happens to me after selecting the virtual environment (I was only opening the venv-selector UI before without selecting anything under the assumption that the error occurred when you open the UI). Are you going to debug in python? If yes, you might want to install [dap-core](https://www.lazyvim.org/extras/dap/core), which will also solve your current problem. Otherwise, that option would need to be conditional based on if `nvim-dap` and `nvim-dap-python` are installed.

**Comment by rghvdberg** [comment]
Confirmed that enabling `dap-core` fixes the crash
I somehow was under the assumption that enabling lang.python would also take care of a complete python-dap environment.

**Comment by gwenwindflower** [comment]
thanks for this everybody, been driving me nuts all week but haven't had time to dig in 🙏🏻
