### ISSUE TITLE
feature: extras.go disable gofumpt

### ISSUE THREAD

**Issue by OneOfOne** [LazyVim/LazyVim#1533]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

gopls already handles gofumpt, having gofumpt enabled in none-ls/conform.nvim does nothing except adding overhead and sometimes none-ls will get confused and leave extra temp files.

### Describe the solution you'd like

Remove gofumpt from none-ls/conform's settings in extras.go.

### Describe alternatives you've considered

Override none-ls's sources in my personal config to disable it.

**Comment by folke** [comment]
I don't use go myself. If gopls does indeed already cover that, then feel free to submit a PR.
