### ISSUE TITLE
disable catppuccin failed

### ISSUE THREAD

**Issue by bruce-the-terrible** [LazyVim/LazyVim#1534]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev

### Operating system/version

22.04.1-Ubuntu

### Describe the bug

-- ~/.config/nvim/lua/plugins/disabled.lua 
_return {
  { "folke/tokyonight.nvim", enabled = false }, -- this line works, tokyonight not be download anymore
  { "catppuccin/nvim", enabled = false },          -- this line report no bug,but still download catppuccin
  { "catppuccin/catppuccin", enabled = false }, -- this line report bug ,and still download catppuccin
}_

### Steps To Reproduce

create ~/.config/nvim/lua/plugins/disabled.lua  like above
rm -rf ~/.local/shared/nvim
run nvim again

tokyonight not loaded
but catppuccin still download

### Expected Behavior

catppuccin disappeare like tokyonight

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Should be just `catppuccin`. That plugin is a bit different since it has a custom name. The normal name would be `nvim` which is not great.
