### ISSUE TITLE
bug: Clangd Offset Encoding

### ISSUE THREAD

**Issue by msMatix** [LazyVim/LazyVim#1540]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.2

### Operating system/version

Linux - Manjaro

### Describe the bug

As soon as I use the linter Sonarlint, I get the message that the offset encoding does not fit. I have the fix in the docs:
```
{
  "neovim/nvim-lspconfig",
  opts = {
    setup = {
      clangd = function(_, opts)
        opts.capabilities.offsetEncoding = { "utf-16" }
      end,
    },
  },
}
```

and unfortunately this one does not work. To make sure that it is also due to the encoding, I wrapped clangd. After that the whole thing works. 
For wrapping I proceeded like this:
1. shell script: 
```
#!/usr/bin/env sh
clangd_ --offset-encoding=utf-16 $@
```
2. `mv $MASON_DIR/bin/clangd $MASON_DIR/bin/clangd_`

Then restart nvim and the warning disappears. So I think that in the clangd - extras in the cmd-attribute the following bold line is missing:
```
cmd = {
        "clangd",
        "--background-index",
        "--clang-tidy",
        **"-offset-encoding=utf-16",**
        "--header-insertion=iwyu",
        "--completion-style=detailed",
        "--function-arg-placeholders",
        "--fallback-style=llvm",
      },
```

### Steps To Reproduce

1. Add clangd to LazyVim (see extras)
2. Add Sonarlint 
 ```
 --Sonarlint
  {
    "https://gitlab.com/schrieveslaach/sonarlint.nvim.git",
    lazy = true,
    ft = { "typescript", "javascript", "cpp", "python" },
    config = function()
      require("sonarlint").setup({
        server = {
          cmd = {
            vim.fn.expand("$MASON/bin/sonarlint-language-server"),
            "-stdio",
            "-analyzers",
            vim.fn.expand("$MASON/share/sonarlint-analyzers/sonarpython.jar"),
            vim.fn.expand("$MASON/share/sonarlint-analyzers/sonarcfamily.jar"),
            vim.fn.expand("$MASON/share/sonarlint-analyzers/sonarcjs.jar"),
          },
        },
        filetypes = {
          "typescript",
          "cpp", 
          "python",
        },
      })
    end,
  },
```
3. Open a *.cpp file and the warning should be visible

### Expected Behavior

No Warning due to encoding is set to utf-16

**Comment by folke** [comment]
Can't reproduce when I add:

```lua
{
  "neovim/nvim-lspconfig",
  opts = {
    setup = {
      clangd = function(_, opts)
        opts.capabilities.offsetEncoding = { "utf-16" }
      end,
    },
  },
}
```

**Comment by Dimfred** [comment]
I could reproduce it. It seems like the `clangd` args are not correctly forwarded. Afaik there should be way more args shown with `LspInfo`, but for me `clangd` just start without any args.

**Comment by msMatix** [comment]
@folke: Is the warning present if you don't do the customization from the docs?

**Comment by dpetka2001** [comment]
```
1. mkdir ~/.config/new_lazy && cd ~/.config/new_lazy
2. git clone https://github.com/LazyVim/starter .
3. NVIM_APPNAME=new_lazy nvim
4. Wait for the plugins to install and restart Neovim with command in step 3
5. Add to `~/.config/new_lazy/lua/config/lazy.lua` the line `{ import = "lazyvim.plugins.extras.lang.clangd" },` and restart Neovim with command in step 3
6. Create a file `~/.config/new_lazy/lua/plugins/sonar.lua` with contents in your initial post and after you save the file press `<leader>l` to open Lazy UI and install `sonarlint` plugin
7. Restart Neovim with command in step 3 and open a `.cpp` file
```
I don't get any errors when following these steps to create a new Lazyvim starter template configuration. If I missed something in the steps I provided, plz feel free to tell me if I should have done anything additional. Also the `cmd` in `LspInfo` shows 
```
	cmd:             /home/jrn23/.local/share/new_lazy/mason/bin/clangd --background-index --clang-tidy --header-insertion=iwyu --completion-style=detailed --function-arg-placeholders --fallback-style=llvm
```
which are the arguments that are passed from the Lazyvim clangd extra. But I also don't get any diagnostics from `sonarlint`. Unfortunately, I don't use it, so I don't know how it's supposed to work.
To remove the remnants of the Lazyvim installation from the steps above, just do
```
rm -rf ~/.config/new_lazy
rm -rf  ~/.local/share/new_lazy
rm -rf ~/.local/state/new_lazy
rm -rf ~/.cache/new_lazy
```

**Comment by msMatix** [comment]
ah thank you.
That was very helpful as it helped me find the error in my configuration. 
I accidentally overwrote the lsps again at one point and caused the whole thing. 

Thank you again for your support!
