### ISSUE TITLE
bug: can't disable or override some keymaps

### ISSUE THREAD

**Issue by pzzxqj** [LazyVim/LazyVim#1555]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.2

### Operating system/version

openSUSE Tumbleweed

### Describe the bug

I'm trying to disable the `s` map to flash and override remap `<C-/>` to mini comment line.
```lua
  {
    "echasnovski/mini.comment",
    opts = {
      mappings = {
        comment_line = "<C-/>",
      },
    },
  },
  {
    "folke/flash.nvim",
    keys = {
      { "s", false },
    },
  },

```
But there is no change

### Steps To Reproduce

1. open `./lua/plugins/example.lua
2. write
	 ```lua	
	return {
	  {
	    "echasnovski/mini.comment",
	    opts = {
	      mappings = {
	        -- comment = "<C-/>",
	        comment_line = "<C-/>",
	      },
	    },
	  },
	  {
	    "folke/flash.nvim",
	    keys = {
	      { "s", false },
	    },
	  },
	}

4. reload nvim


### Expected Behavior

disable and override

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  -- add any other plugins here
  {
    "echasnovski/mini.comment",
    opts = {
      mappings = {
        -- comment = "<C-/>",
        comment_line = "<C-/>",
      },
    },
  },
  {
    "folke/flash.nvim",
    keys = {
      { "s", false },
    },
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
you need to specifcy the exact `mode` in order to correctly disable a keymap.

Also worth mentioning that most terminals don't correctly map `C-/`, and sometimes you need to use `C-_` for that key instead.

Next time, please post a new discussion instead of posting an issue.

**Comment by pzzxqj** [comment]
1. I also have tried `{ "s", false, mode = { "n", "x" } }`,  it's not work.
2. I use foot terminal, I've use `<C-/>` map and ti works well without lazyvim.

**Comment by folke** [comment]
You're missing `o`: `{ "n", "x", "o" }`

Not sure about `mini.comment`. We're just using the default options.

Just try it with `<C-_>` anyway. The keymap you type, would still be `<C-/>`

**Comment by pzzxqj** [comment]
First, thank your reply. Now I can disable the `s` key.

I've tried it with `<C-_>` , but it still doesn't work. Pressing  `ctrl+/` will open the terminal. `verbose map <C-_>`  only shows that which_key_ignore.

**Comment by pzzxqj** [comment]
Hi, you can try the posted repro, but comment the following line. it works well.
```lua
{ "LazyVim/LazyVim", import = "lazyvim.plugins" },
```

**Comment by folke** [comment]
I know what's happening here. This is a special case. You can fix it with:

```lua
{
    "echasnovski/mini.comment",
    opts = {
      mappings = {
        comment_line = "<C-/>",
      },
    },
    config = function(_, opts)
      vim.schedule(function()
        require("mini.comment").setup(opts)
      end)
    end,
  }
```

**Comment by dpetka2001** [comment]
@folke I'd be interested in understanding what's happening here. If you could provide more info on why `mini.comment`'s setup has to be deferred, I'd really appreciate it. Could it be maybe because of the change for the default Lazyvim keymaps to be loaded on `VeryLazy` event and thus overwriting the plugins' ones that are also loaded on `VeryLazy` event?

**Comment by folke** [comment]
no, that was already the case.

in `lazyvim.config.keymaps`, the `map` function overrides the default to check if no plugin has created the same keymap. If so, we dont add the keymap and keep the one from the plugin.

`mini.comment` creates their own keymaps, so that check would fail and the default LAzyVim `<C-/>` would have been added instead.

That schedule is a simple trick to make sure the mini.comment keymap is created after regular keymaps are loaded.

**Comment by dpetka2001** [comment]
So the same situation is not only applicable to `mini.comment`, but to whatever plugin that creates its own internal mappings and the setup would have to be deferred as well, right?

**Comment by folke** [comment]
Normally it doesn't have to be deferred. It is a work-around when it the plugin is using the same keymaps as defined in `lazyvim.config.keymaps`

**Comment by dpetka2001** [comment]
Yes, only in that case. I understand. Tnx a lot.

**Comment by pzzxqj** [comment]
Thanks, everything works as expected.

**Comment by goetzc** [comment]
This should also work, which is what I'm using:

```lua
vim.keymap.set("n", "<C-_>", "gcc", { remap = true, silent = true, desc = "Comment line" })
vim.keymap.set("x", "<C-_>", "gc", { remap = true, silent = true, desc = "Comment selection" })
```
