### ISSUE TITLE
bug: staticcheck is not supported at go1.18.10

### ISSUE THREAD

**Issue by Songggggr** [LazyVim/LazyVim#1556]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0

### Operating system/version

14.0.0

### Describe the bug

Prompt when opening a .go file
![image](https://github.com/LazyVim/LazyVim/assets/131334123/22cd7101-c6f1-45ea-a043-22adb4165515)

### Steps To Reproduce

1. rtx install go@1.18.10
2. install new lazyvim
3. open go file

### Expected Behavior

not open error message

**Comment by folke** [comment]
As the error says, you need a more recent version of go for gopls
