### ISSUE TITLE
bug: telescope example in documentation doesn't work

### ISSUE THREAD

**Issue by aoodham** [LazyVim/LazyVim#1566]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.2

### Operating system/version

Ubuntu 22.04

### Describe the bug

Adding a file called `telescope.lua` to my local `plugins` folder, as per the `example.lua` file, provides a new keymapping which works on initial boot, but subsequently fails.

```lua
-- telescope.lua
return {
  "nvim-telescope/telescope.nvim",
  keys = {
      -- add a keymap to browse plugin files
      -- stylua: ignore
      {
        "<leader>fp",
        function() require("telescope.builtin").find_files({ cwd = require("lazy.core.config").options.root }) end,
        desc = "Find Plugin File",
      },
  },
  -- change some options
  opts = {
    defaults = {
      layout_strategy = "horizontal",
      layout_config = { prompt_position = "top" },
      sorting_strategy = "ascending",
      winblend = 0,
    },
  },
  -- add telescope-fzf-native
  {
    "telescope.nvim",
    dependencies = {
      "nvim-telescope/telescope-fzf-native.nvim",
      build = "make",
      config = function()
        require("telescope").load_extension("fzf")
      end,
    },
  },
}
```
When I first fire up neovim, the new keybinding works as expected, albeit the "p" character is added into search box. If I change the keybinding, whatever character follows the `<leader>f` is similarly added into the search box.

After this, however, the keybinding is no longer recognised and doing `<leader>fp` resutlts in the same behaviour as `fp`.

I suspect the keybinding being lost and the final character being pre-entered into the search box are related, but I cannot workout why this is happening.

### Steps To Reproduce

1. Add custom telescope.lua file to local `plugins` folder.
2. Open vim, use keymap `<leader>fp` to trigger new keymap. It works, but note that `p` is entered into the search box for you
3. Open any random file, and re-try to use  the keymap - it is no longer recognised. 
4. `nmap <leader>fp` points to the generic which-key entry for "+file/find"

### Expected Behavior

When using the new keymap it always works and is not overriden. Bonus characters aren't entered into the search box.

**Comment by folke** [comment]
Your spec is wrong. Toplevel spec is telescope and under that you add another for telescope native. Fix your spec and next time, please use discussions for user questions

**Comment by folke** [comment]
Should be something like this:

```lua
return {
  {
    "telescope.nvim",
    dependencies = {
      {
        "nvim-telescope/telescope-fzf-native.nvim",
        build = "make",
        config = function()
          require("telescope").load_extension("fzf")
        end,
      },
    },
    keys = {
      {
        "<leader>fp",
        function()
          require("telescope.builtin").find_files({
            cwd = require("lazy.core.config").options.root,
          })
        end,
        desc = "Find Plugin File",
      },
    },
    opts = {
      defaults = {
        layout_strategy = "horizontal",
        layout_config = { prompt_position = "top" },
        sorting_strategy = "ascending",
        winblend = 0,
      },
    },
  },
}
```

**Comment by aoodham** [comment]
I'm sorry - but this is literally copied and pasted from the example file: 

https://github.com/LazyVim/starter/blob/main/lua/plugins/example.lua#L53-L85

and was not working - hence my assumption it was a bug.

**Comment by aoodham** [comment]
Upon closer inspection ti appears that a pair of brackets were indeed lost during the copy and paste - the example from the example file does work if they are included.
