### ISSUE TITLE
bug: status column icons look off with v8.4.0

### ISSUE THREAD

**Issue by fredrikaverpil** [LazyVim/LazyVim#1571]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.2

### Operating system/version

macOS Sonoma 14.0

### Describe the bug

Following [v8.4.0](https://github.com/LazyVim/LazyVim/releases/tag/v8.4.0), the status column icons look off. I don't think I've got anything special here in my config that affects this behavior.

v8.3.0:

![image](https://github.com/LazyVim/LazyVim/assets/994357/6ca1d22b-68c7-453d-9abe-9ecd2ce90047)

v8.4.0:

![image](https://github.com/LazyVim/LazyVim/assets/994357/11584ace-eac2-4941-a878-7520cdb27bba)

Do you see this on your end too?

### Steps To Reproduce

Downgrade to v8.3.0 and compare.

### Expected Behavior

I didn't expect the icons to become this small. They also overlap the line number even if it doesn't show well in my screenshot above (looks worse for other icons).

**Comment by fredrikaverpil** [comment]
Some more examples:

![image](https://github.com/LazyVim/LazyVim/assets/994357/cffa3ae6-fdbf-456e-b3f6-4ee98caef69a)

![image](https://github.com/LazyVim/LazyVim/assets/994357/f0d8c585-ee9e-475b-b4b8-49dcfe76551d)

**Comment by dpetka2001** [comment]
For me the icon gets smaller only when the cursor is on the line with the icon and only for line numbers that are greater then double digits. Also I did not observe any overlapping. Do you maybe have a plugin `statuscol.nvim`? I also disabled that, but I don't know how much of an impact it had. Screenshots following:
![2023-10-03_18-30](https://github.com/LazyVim/LazyVim/assets/12776461/fe346235-5cc3-4da4-b8b7-7c964d5b1df4)
![2023-10-03_18-29_2](https://github.com/LazyVim/LazyVim/assets/12776461/af00a7a2-c965-476a-af40-76dbbb749cb4)
![2023-10-03_18-29_1](https://github.com/LazyVim/LazyVim/assets/12776461/c9a5e16e-6e58-4230-b3bd-08d97c38a626)
![2023-10-03_18-29](https://github.com/LazyVim/LazyVim/assets/12776461/d9604d1e-dbd8-4712-9c27-21727780c071)

**Comment by folke** [comment]
I know what's causing this. Will fix...

**Comment by folke** [comment]
The problem is that some unicode characters render differently whether there's a space following or not
