### ISSUE TITLE
bug: sometimes Tab in insert mode still jumps me around my document 

### ISSUE THREAD

**Issue by stevenhay** [LazyVim/LazyVim#1577]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1017+g0c86828a

### Operating system/version

macOS 13.4 (22F66)

### Describe the bug

While I'm editing some Go files (I'm not sure if it's localised to Go files or not, it's the only thing I edit in), sometimes while I'm in insert mode pressing Tab will randomly jump my cursor around my document.  Pressing it multiple times will continue to jump around in my document. 

It's potentially an issue where I press Tab so fast after "i" or "o" that it registers the Tab before insert mode is activated. Is there anyway I can simply disable Tab movement?

I'm using the default LazyVim installation with the following new keybinds:
```lua
map("n", "<leader>gw", require("telescope").extensions.git_worktree.git_worktrees, { desc = "Open Worktree" })
map("n", "<leader>gW", require("telescope").extensions.git_worktree.create_git_worktree, { desc = "Create Worktree" })

map("n", "<leader>fm", "<CMD>Telescope harpoon marks<CR>", { desc = "Find Harpoon Marks" })
map("n", "<leader>ha", require("harpoon.mark").add_file, { desc = "Add File to Harpoon" })
map("n", "<leader>ht", require("harpoon.ui").toggle_quick_menu, { desc = "Toggle Harpoon UI" })
```

and this spec:
```lua
spec = {
    -- add LazyVim and import its plugins
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- import any extras modules here
    { import = "lazyvim.plugins.extras.lang.go" },
    { import = "lazyvim.plugins.extras.lang.java" },
    { import = "lazyvim.plugins.extras.lang.json" },
    { import = "lazyvim.plugins.extras.lang.yaml" },
    { import = "lazyvim.plugins.extras.lang.docker" },
    { import = "lazyvim.plugins.extras.dap.core" },
    { import = "lazyvim.plugins.extras.test.core" },
    { import = "lazyvim.plugins.extras.util.project" },
    { import = "plugins" },
  },
```

everything else is unchanged.

### Steps To Reproduce

I'm not sure how to reproduce this, sometimes it happens rarely and othertimes it happens very frequent and I end up jumping around my document and typing random stuff somewhere else.

### Expected Behavior

Tab should indent, not jump me to somewhere completely random in my document :(

**Comment by amaanq** [comment]
I get this occasionally too

**Comment by dpetka2001** [comment]
From what I could see `<Tab>` was only configured for `Luasnip`. So you should just disable the `keys` handlers that enable the mapping. See [here](https://www.lazyvim.org/configuration/plugins#%EF%B8%8F-adding--disabling-plugin-keymaps) how to disable plugins' keymaps.

**Comment by folke** [comment]
Set `history = false` for luasnip. See here https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#config-options

That will probably solve the issue you're having.
