### ISSUE TITLE
bug: randomly auto indent will break and stop working until buffer is re-opened

### ISSUE THREAD

**Issue by stevenhay** [LazyVim/LazyVim#1579]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1017+g0c86828a

### Operating system/version

macOS 13.4 (22F66)

### Describe the bug

Randomly while I've been developing in Go the auto indenting will fail until I've reopened the document or quit and restarted Neovim. For example in the following code:
```go
func (c *Client) do(r *Request) (*http.Response, error) {
	attempt := 1
	for {
		if r.Body != nil {
			if _, err := r.body.Seek(0, 0); err != nil {
				c.HTTPClient.CloseIdleConnections()
				return nil, fmt.Errorf("failed to seek body: %v", err)
			}
		}

		resp, err := c.HTTPClient.Do(r.Request)

		shouldRetry, shouldRetryErr := c.ShouldRetry(r.Context(), resp, err)
		if !shouldRetry {
			if shouldRetryErr != nil {
				err = shouldRetryErr
			}
			return resp, err
		}

		if err == nil { // MOUSE HERE
// ENDS HERE
                     // SHOULD BE HERE
		}

		if attempt == c.MaxRetries {
			break
		}
	}
    return nil, nil
}
```

Pressing enter while at the end of the line (MOUSE HERE) fails to correctly automatically indent within the block. Pressing `cc`, `o`, etc. also doesn't work here. Closing the buffer and reopening it fixes it.

### Steps To Reproduce

It happens randomly so I have no steps to reproduce

### Expected Behavior

Auto indent should not randomly stop indenting :(

**Comment by folke** [comment]
LazyVim is just a config for Neovim. We don't do anything special regarding indenting.

This is really not the place to submit issues like this. Probably best to check the Neovim and gopls repos.

**Comment by folke** [comment]
One thing you may try is disabling treesitter indent.

```lua
{
  "nvim-treesitter/nvim-treesitter",
  opts = {
    indent = { enable = true },
  },
}
```

You can also disable it for just some filetypes. Check the nvim-treesitter docs to see how.
