### ISSUE TITLE
bug: dashboard isn't closed if file was opened from the quickfix list

### ISSUE THREAD

**Issue by fpohtmeh-github** [LazyVim/LazyVim#1580]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.2

### Operating system/version

OS Name	Microsoft Windows 10 Pro N Version 10.0.19045 Build 19045

### Describe the bug

The dashboard isn't closed if I send a list of files to the quickfix list from the telescope and open the file from the quickfix list.

### Steps To Reproduce

1. Open LazyVim
2. Find files in the telescope
3. Send the filtered list to the quickfix list (Ctrl+Q)
4. Open any file from the quickfix list
5. The buffer is opened in the split, closing of the dashboard quits Neovim

### Expected Behavior

The dashboard is closed, there is no splitting
Alternatively, closing the dashboard doesn't quit Neovim

### Repro

```Lua
// clean LazyVim installation
```

**Comment by folke** [comment]
That's not really a LazyVim issue is it?

If it bothers you, report an issue upstream (probably alpha.nvim repo).
