### ISSUE TITLE
bug: Freeze when opening any projects e.g. java, lua, react with neovim with latest update LazyVim

### ISSUE THREAD

**Issue by Delice0** [LazyVim/LazyVim#1584]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.2 Build type: Release LuaJIT 2.1.0-beta3

### Operating system/version

MacOs 13.6

### Describe the bug

After updating LazyVim plugin using :Lazy command, neovim suddenly started freezing right away when opening any project. I basically have to quit neovim. I can't use it at all for coding anymore.

### Steps To Reproduce

1. Open a lua/java/react project with latest LazyVim + Lazy plugin

### Expected Behavior

I expect it NOT to freeze when opening a project

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
I don't have this issue, but it might be related to the new settings for `vim.opt.foldexpr`

Can you add `vim.opt.foldexpr = "0"` to your `lua/config/options.lua` file and check if that fixes it?

If so, would be great if you could report an issue to Neovim and link it here.

**Comment by folke** [comment]
What do you mean exactly with opening a project?

**Comment by folke** [comment]
Closing in favor of https://github.com/LazyVim/LazyVim/issues/1584
