### ISSUE TITLE
bug: Tailwind LSP plugin (plugins/extras/lang) ignores provided/custom 'filetypes'

### ISSUE THREAD

**Issue by lahickey** [LazyVim/LazyVim#1590]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.2

### Operating system/version

ArchLinux

### Describe the bug

If a custom 'filetypes' table is provided for tailwind: e.g.
```
  {
    "neovim/nvim-lspconfig",
    ---@class PluginLspOpts
    opts = {
      ---@type lspconfig.options
      servers = {
        tailwindcss = {
          filetypes = { "templ" },
        },
      },
    },
  },
```
then the 'filetypes' is ignored. It appears to be because the included setup function ...

```
     setup = {
        tailwindcss = function(_, opts)
          local tw = require("lspconfig.server_configurations.tailwindcss")
          --- @param ft string
          opts.filetypes = vim.tbl_filter(function(ft)
            return not vim.tbl_contains(opts.filetypes_exclude or {}, ft)
          end, tw.default_config.filetypes)
        end,
      },
```
... overwrites the 'filetypes' table with a filtered version of the default filetypes from the lspconfig - in order to filter out 'filetypes_exclude'

Perhaps a setup function along these lines would be a solution:
```
      setup = {
        tailwindcss = function(_, opts)
          local tw = require("lspconfig.server_configurations.tailwindcss")
          opts.filetypes = vim.list_extend(opts.filetypes or {}, tw.default_config.filetypes)
          --- @param ft string
          opts.filetypes = vim.tbl_filter(function(ft)
            return not vim.tbl_contains(opts.filetypes_exclude or {}, ft)
          end, opts.filetypes)
        end,
      },
```

### Steps To Reproduce

Add the builtin tailwind lsp config and then extend it to have custom 'filetype' table. Notice that this never makes its way through to the LSP config

### Expected Behavior

Any added 'filetypes' are appended or prepended to the default list

**Comment by folke** [comment]
I just fixed this and added a `filetypes_include` option to achieve what you want. Check the diff for more info

**Comment by lahickey** [comment]
Yep, that appears to do the trick - thanks!
