### ISSUE TITLE
bug: ]c, [C not available in diff mode

### ISSUE THREAD

**Issue by imroc** [LazyVim/LazyVim#1610]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.2 

### Operating system/version

MacOS 13.5.1

### Describe the bug

I noticed that the keymap `]c` and `[c` is used by `nvim-treesitter-textobjects`:  https://github.com/LazyVim/LazyVim/blob/fb110e76d86096fd0ad5585537cb7915b6d3cf8d/lua/lazyvim/plugins/treesitter.lua#L69

Which is confict with diff-mode, and recent commit just simply remove keymap `[c` and `]c`:
https://github.com/LazyVim/LazyVim/commit/86de423ef029abd085531e18b197a5f90e201d98

So we still can't use `]c` and `[c` to jump to next change and previous change.

### Steps To Reproduce

see desc.

### Expected Behavior

see desc.

**Comment by imroc** [comment]
cc @folke

**Comment by imroc** [comment]
Currently, I use this to avoid bug(`c`-->`l`):

```lua
return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = function(_, opts)
      opts.textobjects.move.goto_next_start["]c"] = nil
      opts.textobjects.move.goto_next_start["]l"] = "@class.outer"
      opts.textobjects.move.goto_previous_start["[c"] = nil
      opts.textobjects.move.goto_previous_start["[l"] = "@class.outer"

      opts.textobjects.move.goto_next_end["]C"] = nil
      opts.textobjects.move.goto_next_end["]L"] = "@class.outer"
      opts.textobjects.move.goto_previous_end["[C"] = nil
      opts.textobjects.move.goto_previous_end["[L"] = "@class.outer"
    end,
  },
}
```

**Comment by folke** [comment]
Have you tried with the latest release of LazyVim?

When Neovim starts in diff mode, the treesitter mappings should not be set.

Or are you starting diff mode differently?

**Comment by imroc** [comment]
Yes I tried the `9.3.0` today
![image](https://github.com/LazyVim/LazyVim/assets/7448852/5550c813-eb2c-4f91-a6cc-6c2387f682ba)

 And I use [diffview.nvim](https://github.com/sindrets/diffview.nvim) to start diff mode.

**Comment by folke** [comment]
ok, cool. Will work on a better fix for this

**Comment by imroc** [comment]
Nice fix!

**Comment by dpetka2001** [comment]
It works perfectly fine for me. It must be something on your end. Screencast following where `test.lua` is exactly the same as `init.lua` with some changes for testing purposes

https://github.com/user-attachments/assets/c57e3e95-9257-4d1e-ae52-aa4109c9adbf
