### ISSUE TITLE
feature: Refresh lsp settings from .vscode/settings.json in a monorepo

### ISSUE THREAD

**Issue by GuillaumeLagrange** [LazyVim/LazyVim#1611]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

I work on a rust monorepo (one cargo workspace) which is quite large. By default, rust-analyzer runs cargo check on all packages of the cargo workspace, which is not ideal. We use local `.vscode/settings.json` to override the check command to only check for the current package (`cargo check -p package_name`)

When I open a file in `service_a`, the rust-analyzer check command is correct: `cargo check -p service_a`.
If I then open a file from a different service (`service_b`), the overridden cargo check command remains the one for the first service, and I do not get diagnostics.

It remains so until I relaunch neovim and open a service_b file first.

This is not ideal, since rust-analyzer takes ages to launch in a large monorepo.

### Describe the solution you'd like

I would love for a way to manually refresh the settings, basically neoconf to look for the settings file associated with the current buffer, and send it to the lsp server.

If the process is not too heavy, it could even be fired on buffer enter to switch seamlessly between files, but I can live with a manual refresh since the main frustration comes from having to restart rust-analyzer OR have multiple nvim (and rust-analyzer) opened at the same time if I want to work across services)

### Describe alternatives you've considered

I could also look into a solution to manually send the cargo check command, but I would love to make use of vs code settings files written by colleagues, and neoconf is awesome so if we can improve it even further that would be awesome.

### Additional context

The issue can be reproduced with basic LazyVim configuration, with the rust lang plugin enabled.

Here is the [minimal repro repo](https://github.com/GuillaumeLagrange/neoconf-repro) with its structure detailed below: 

```
├── Cargo.lock
├── Cargo.toml
├── service_a
│   ├── Cargo.toml
│   ├── src
│   │   └── main.rs
│   └── .vscode
│       └── settings.json  // cargo check -p service_a
└── service_b
    ├── Cargo.toml
    ├── src
    │   └── main.rs
    └── .vscode
        └── settings.json  // cargo check -p service_b

```

Have a great day

**Comment by folke** [comment]
You can trigger a reload with:

`require("neoconf.plugins").fire("on_update", fname)`

fname should be the full filename of the `.vscode/settings.json` file
