### ISSUE TITLE
Can't init on windows, I had removed the nvim-data folder

### ISSUE THREAD

**Issue by Mikanku** [LazyVim/LazyVim#1614]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.2 Build type: RelWithDebInfo LuaJIT 2.1.1694082368

### Operating system/version

Windows 11

### Describe the bug

I follow the doc on https://www.lazyvim.org/installation, but I find the issue that 
.../Local/nvim-data/lazy/lazy.nvim/lua/lazy/core/plugin.lua:80: table index is nil
here is the description
![2023-10-07_21-10-03](https://github.com/LazyVim/LazyVim/assets/111589535/b7bbb29a-f46c-4f3b-a965-41a3a6e0fa5f)

### Steps To Reproduce

1. remove all my neovim folder for newly install
2. follow the docs to install
4. try on debian newly install
5. debian is all right, but windows error

### Expected Behavior

like the behavior on Debian
![image](https://github.com/LazyVim/LazyVim/assets/111589535/33d3ea7b-1053-477d-a4de-36d990e68b7f)

### Repro

```Lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- bootstrap lazy.nvim
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

require("lazy").setup({
  spec = {
    -- add LazyVim and import its plugins
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- import any extras modules here
    -- { import = "lazyvim.plugins.extras.lang.typescript" },
    -- { import = "lazyvim.plugins.extras.lang.json" },
    -- { import = "lazyvim.plugins.extras.ui.mini-animate" },
    -- import/override with your plugins
    { import = "plugins" },
  },
  defaults = {
    -- By default, only LazyVim plugins will be lazy-loaded. Your custom plugins will load during startup.
    -- If you know what you're doing, you can set this to `true` to have all your custom plugins lazy-loaded by default.
    lazy = false,
    -- It's recommended to leave version=false for now, since a lot the plugin that support versioning,
    -- have outdated releases, which may break your Neovim install.
    version = false, -- always use the latest git commit
    -- version = "*", -- try installing the latest stable version for plugins that support semver
  },
  install = { colorscheme = { "tokyonight", "habamax" } },
  checker = { enabled = true }, -- automatically check for plugin updates
  performance = {
    rtp = {
      -- disable some rtp plugins
      disabled_plugins = {
        "gzip",
        -- "matchit",
        -- "matchparen",
        -- "netrwPlugin",
        "tarPlugin",
        "tohtml",
        "tutor",
        "zipPlugin",
      },
    },
  },
})
```

**Comment by folke** [comment]
You are using a very old lazy.nvim version. Remove all the cache/state/share directories as mentioned on the website.

**Comment by Mikanku** [comment]
It seems to be a path problem with the plugin, an error occurs when using import, and importing can be normal without import

**Comment by folke** [comment]
what?

**Comment by Mikanku** [comment]
when i use import { }, it's error

**Comment by folke** [comment]
Again, what do you mean? Where do you use import? And what?

**Comment by Mikanku** [comment]
I can be sure I'm using the new version, when i use import

spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
}
it's get a error

**Comment by folke** [comment]
As I said, you **ARE** using an old verison of lazy.
remove `AppData/Local/nvim-data/lazy`.

**Comment by Mikanku** [comment]
![image](https://github.com/LazyVim/LazyVim/assets/111589535/ad40539f-146b-4fde-9ae2-401c65979f90)
Is it a problem with slashes and backslashes? I've deleted nvim-data many times

**Comment by folke** [comment]
Just rebooted in Windows myself to double-check, but all works as expected.
As I mentioned before, those lines don't match the latest lazy.nvim version so that is still the problem.
Try deleting your lazy-lock.json file as well just to be sure.

**Comment by Mikanku** [comment]
This doesn't solve my problem, but thank you for the answer
