### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by shahidkhan142** [LazyVim/LazyVim#1626]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

 v0.9.2

### Operating system/version

Macos 13.2.1

### Describe the bug

1.  cannot update the init.lua file 
<img width="1193" alt="Screenshot 2023-10-08 at 1 17 01 PM" src="https://github.com/LazyVim/LazyVim/assets/127819741/68ae54b1-b49e-403a-8c67-356e095fd0ae">

### Steps To Reproduce

Try update the init.lua file when pressing leader +U 

### Expected Behavior

Should update the init.lua file when pressing leader +U 

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
Try removing `~/.local/share/nvim/lazy/` directory and try updating again. Also the key to update is `Shift-u`, not `<leader>U`.
