### ISSUE TITLE
bug: Custom linespace not working

### ISSUE THREAD

**Issue by Delice0** [LazyVim/LazyVim#1637]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

latest

### Operating system/version

latest

### Describe the bug

I tried to change the linespace inside options.lua, but nothing happens regardless of what value i use.

vim.opt.linespace = 10 -- example

### Steps To Reproduce

add vim.opt.linespace = 10 inside options.lua

### Expected Behavior

i expect the linespace to be 10

**Comment by folke** [comment]
LazyVim does nothing special with this. This only works in a GUI and the GUI must support it.
Not a LazyVim issue
