### ISSUE TITLE
bug: Commit `fb70170` breaks LazyVim when Edgy is not installed

### ISSUE THREAD

**Issue by minusfive** [LazyVim/LazyVim#1649]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

9.8.0

### Operating system/version

MacOS 13.6

### Describe the bug

With latest release, if `edgy` is disabled/removed LazyVim won't open any files. Pretty sure this happens after `fb70170`, right?

![Screenshot 2023-10-10 at 4 00 31 AM](https://github.com/LazyVim/LazyVim/assets/33695/5b7bfbe4-a6d0-47e7-bd2b-dc15efd90e77)

### Steps To Reproduce

1. `nvim`
2. `<leader><Space>`
3. pick a file
4. 💥 

### Expected Behavior

Shouldn't explode :P

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by minusfive** [comment]
Additional info: This only seems to happen if the edgy extra is added but disabled through plugin config. Removing the extra line fixed it.

**Comment by folke** [comment]
That's normal, since the edgy extra also configures some other plugins.
Just disable the extra instead.
