### ISSUE TITLE
bug: LaTeX is slow and `texlab` always timeouts on save

### ISSUE THREAD

**Issue by MartinRJDagleish** [LazyVim/LazyVim#1650]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.2

### Operating system/version

Manjaro Linux x86_64 Kernel: 5.15.133-1-MANJARO

### Describe the bug

Hey, 
I am really enjoying the feature-rich LazyVim distro. It helped me kickstart my journey away from VS Code to fully using NVim. 
My only problem right now is with using LazyVim with LaTeX. 

I am sry, if this is wrongly posted here, but I was not sure if it is purely the fault of `texlab` LSP or the combination in LazyVim. 

As I especially switched to NeoVim for speed, I was kind of suprised that after getting to about 200 lines in a 
document, it feels a bit slow and slugish. Especially the snippets would not work as fast, which caused a lot of misstyping. 

Everytime I saved the document, `texlab` timeouts. Also while scolling in a document, `texlab` seems to be at about 100% CPU usage for one core, sometimes also while being more or less idle at a point. 

Summed up: 
1. Snippets do not work as "instantaneous" as expected. 
2. `texlab` always timeouts on save

Not sure if [this](https://www.reddit.com/r/neovim/comments/12gu3jd/neovim_lagging_when_writing_latex/) is relevant or not. 

### Steps To Reproduce

1. Use the recommended `extras/lang/lang.tex` provided in the documentation 
2. Get document of about 200 lines of code 
3. High CPU usage and very slow responsiveness

### Expected Behavior

- No timeout on save 
- Faster response, less sluggishness

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")

-- the recommended { import = "lazyvim.plugins.extras.lang.tex" },
-- in lua/config/lazy.lua
```

**Comment by folke** [comment]
Nope, not normal and I don't have this issue.
texlab is an lsp server, nothing LazyVim (or Neovim) can do about that.

**Comment by Zhaoyilunnn** [comment]
Hi @MartinRJDagleish I am facing the same issue, did you manage to solve this problem?

**Comment by MartinRJDagleish** [comment]
@Zhaoyilunnn Yes I kind of solved the problem. 

`texlab` needs to have a way to detect the current `root` of your project, which was somehow broken. (see: https://github.com/neovim/nvim-lspconfig/issues/3262) for more infomation.

After I made sure that I had a `.latexmkrc` for example in my root of the project, it was a lot better and it pretty much resolved the issue.

**Comment by Zhaoyilunnn** [comment]
Hi @MartinRJDagleish, thanks a lot for your suggestions, I tried to create a `.latexmkrc` file and still experience "LSP timeout" when saving files. As I am working on a git project, so that I have the ".git" directory, I think `texlab` has already correctly detected the root of my project, as can be confirmed in `:LspInfo`.  I'll try to debug more but thanks for your suggestions.
