### ISSUE TITLE
bug: cannot update mason.nvim

### ISSUE THREAD

**Issue by Memnoc** [LazyVim/LazyVim#1652]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.2

### Operating system/version

Arch Linux

### Describe the bug

 I always sync LazyVim when I start working <leader> L - <leader> S but all of a sudden Mason is not updating with the following error:
 
 ```
error: Your local changes to the following files would be overwritten by checkout:
        	.github/workflows/tests.yml
        	CHANGELOG.md
        Please commit your changes or stash them before you switch branches.
        Aborting

```
I am actually not sure this is dependent on LazyVim but I am reporting just in case since I have not purposely, at least, changed anything in my config to cause this issues to begin with.

Three commits were pushed to mason.nvim in the past 10 hours or so, those are the ones causing the issue it seems.

### Steps To Reproduce

1. Open LazyVim
2. <leader> L then <leader> S
3. error as reported updating Mason  - all other plugins seems fine

### Expected Behavior

Update all packages with no issues

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
Cannot reproduce. Just updated `mason` without any problems. You could try to delete the folder `~/.local/share/nvim/lazy/` and let Lazy reinstall everything. Maybe you changed something in that directory yourself (which you really shouldn't)?

**Comment by folke** [comment]
I just pushed a new release of lazy.nvim that includes a new feature that checks git status of plugins and shows how to fix it if you have changed files.
