### ISSUE TITLE
bug: edgy.nvim/lua/edgy/view.lua:115: Vim:E444: Cannot close last window

### ISSUE THREAD

**Issue by NeckBeardPrince** [LazyVim/LazyVim#1664]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.4

### Operating system/version

14.1 Beta (23B5067a)

### Describe the bug

I'm unable to exit the window if I open neovim into a directory tree.

I've provided a video, as it's a lot easier to understand than my ramblings. I'm not sure why the playback is so fast, i didn't go that fast.
https://share.cleanshot.com/JC6JpyBL

```lua
Error detected while processing WinClosed Autocommands for "*":
Error executing lua callback: vim/_editor.lua:0: WinClosed Autocommands for "*"..script nvim_exec2() called at WinClosed Autocommands for "*":0: Vim(sbuffer):E85: There is no listed buffer
stack traceback:
        [C]: in function 'nvim_exec2'
        vim/_editor.lua: in function 'cmd'
        ...ner/.local/share/nvim/lazy/edgy.nvim/lua/edgy/editor.lua:71: in function <...ner/.local/share/nvim/lazy/edgy.nvim/lua/edgy/editor.lua:34>
```

![CleanShot 2023-10-11 at 12 28 59](https://github.com/LazyVim/LazyVim/assets/6558867/bf74c2d5-2e76-41bc-bb0b-5e4d47ea574c)

Line 34 in edgy/editor.lua

```lua
-- Ensures that there is always a main window
-- when a edgebar is visible
function M.check_main()
  local wins = M.list_wins()
```

### Steps To Reproduce

1. Open nvim into a directory
2. `:q` or `:q!`
3. You live there now

### Expected Behavior

I wanna go home

### Repro

```Lua
Does not happen
```

**Comment by folke** [comment]
Fixed by https://github.com/folke/edgy.nvim/commit/e75283cde36056e756f535740085d4a721786721

**Comment by NeckBeardPrince** [comment]
> Fixed by [folke/edgy.nvim@e75283c](https://github.com/folke/edgy.nvim/commit/e75283cde36056e756f535740085d4a721786721)

New issue after updating. I'll make a new issue.

**Comment by folke** [comment]
ok, please do it in the edgy repo
