### ISSUE TITLE
bug: Invalid option (not found) smoothscroll

### ISSUE THREAD

**Issue by juridiener** [LazyVim/LazyVim#1669]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-37+gccc0980f8

### Operating system/version

Mac

### Describe the bug

After Updating LazyVim i got this error.
Failed loading lazyvim.config.options
vim/_meta/.lua:0:  Invalid option (not found) smoothscroll

### Steps To Reproduce

Updated LazyVim 
Open Nvim

### Expected Behavior

No errors
<img width="590" alt="Screenshot 2023-10-09 at 09 33 10" src="https://github.com/LazyVim/LazyVim/assets/92093874/2bfdf634-fb4c-4d00-aea1-c61bd162675b">

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
That's because you are using an old nightly.
Only stable versions as of 0.9 and latest nightly are supported.

I'm not going to support outdated nightlies.
