### ISSUE TITLE
bug: whichkey does not show the `a` command after hitting <leader>d

### ISSUE THREAD

**Issue by fredrikaverpil** [LazyVim/LazyVim#1671]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

9.9.1

### Describe the bug

As mentioned in #1629

The `<leader>da` keymap does not show in whichkey when hitting `<leader>d`, which I guess it should be doing...?

![image](https://github.com/LazyVim/LazyVim/assets/994357/4d48f7bd-c7de-4873-bf62-1826f2080aad)

I know you are busy with v10.0.0, so I figured I'd open this so we don't forget it 😄 

### Steps To Reproduce

1. hit `<leader>d`, look at the whichkey commands showing up

### Expected Behavior

The `a` command should show up.

**Comment by folke** [comment]
Has also been fixed in https://github.com/LazyVim/LazyVim/pull/1655
