### ISSUE TITLE
bug: go/delve debugger unexpectedly asks for args

### ISSUE THREAD

**Issue by fredrikaverpil** [LazyVim/LazyVim#1672]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

9.9.1

### Describe the bug

Args are being asked for even if I don't pick the option that says `Debug (Arguments)` in the debug window for Go/delve.

https://github.com/LazyVim/LazyVim/assets/994357/4648dcfb-1beb-4413-93bb-2d1f799b1c9b

I know you are busy with 10.0.0 so I just opened this here so not to forget about it 😄 

### Steps To Reproduce

1. Hit `<leader>da`
2. Pick "Debug"

### Expected Behavior

No arguments popup window should show.

**Comment by folke** [comment]
Has been fixed in https://github.com/LazyVim/LazyVim/pull/1655
