### ISSUE TITLE
bug: Aerial not showing in lualine

### ISSUE THREAD

**Issue by theoribeiro** [LazyVim/LazyVim#1682]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9

### Operating system/version

MacOS 14.0

### Describe the bug

I just enabled aerial as an extra and disabled navic but it is not showing the symbols in Lualine. I tried configuring lualine explicitly as aerial's documentation but it still doesn't work. 
Opening Aerial's window works and symbols show up correctly, the problem is just with Lualine.

Is that happening to everyone or is it something specific about my config? 

### Steps To Reproduce

1. Enable aerial as an extra
2. Restart nvim
3. Aerial doesn't show up in lualine

### Expected Behavior

Aerial would show up in Lualine. 

```

**Comment by folke** [comment]
Should work out of the box by just enabling the aerial extra (not alpha).

I did add a kind filter though, to prevent showing useless symbols.

You can disable that by setting `opts.filter_kind= false` for aerial.

**Comment by theoribeiro** [comment]
Sorry, that was a typo, I meant aerial, I'll edit the original PR. 

Even by disabling the filter it still doesn't show up in Lualine. Any ideas on how I could debug to investigate?

**Comment by folke** [comment]
You probably changed lualine yourself?
Try commenting out all your personal lualine config and see if that works.

If so, you know your config is the issue.

**Comment by theoribeiro** [comment]
Already did. 
Printing `vim.inspect(require('lualine').get_config())` I get the following configuration that shows that aerial should be showing. A little odd, isn't it?

```
{
  extensions = { "neo-tree", "lazy" },
  inactive_sections = {
    lualine_a = {},
    lualine_b = {},
    lualine_c = { "filename" },
    lualine_x = { "location" },
    lualine_y = {},
    lualine_z = {}
  },
  inactive_winbar = {},
  options = {
    always_divide_middle = true,
    component_separators = {
      left = "",
      right = ""
    },
    disabled_filetypes = {
      statusline = { "dashboard", "alpha", "starter" },
      winbar = {}
    },
    globalstatus = true,
    icons_enabled = true,
    ignore_focus = {},
    refresh = {
      statusline = 1000,
      tabline = 1000,
      winbar = 1000
    },
    section_separators = {
      left = "",
      right = ""
    },
    theme = "auto"
  },
  sections = {
    lualine_a = { "mode" },
    lualine_b = { "branch" },
    lualine_c = { { "diagnostics",
        symbols = {
          error = " ",
          hint = " ",
          info = " ",
          warn = " "
        }
      }, { "filetype",
        icon_only = true,
        padding = {
          left = 1,
          right = 0
        },
        separator = ""
      }, { <function 1> }, { "aerial",
        colored = true,
        dense = false,
        dense_sep = ".",
        depth = 5,
        sep = " "
      } },
    lualine_x = { { <function 2>,
        color = {
          fg = "#b988b0"
        },
        cond = <function 3>
      }, { <function 4>,
        color = {
          fg = "#81a1c1"
        },
        cond = <function 5>
      }, { <function 6>,
        color = {
          fg = "#ebcb8b"
        },
        cond = <function 7>
      }, { <function 8>,
        color = {
          fg = "#de878f"
        },
        cond = <function 9>
      }, { "diff",
        symbols = {
          added = " ",
          modified = " ",
          removed = " "
        }
      } },
    lualine_y = { { "progress",
        padding = {
          left = 1,
          right = 0
        },
        separator = " "
      }, { "location",
        padding = {
          left = 0,
          right = 1
        }
      } },
    lualine_z = { <function 10> }
  },
  tabline = {},
  winbar = {}
}

```

**Comment by folke** [comment]
Can you see what `:= require("lazyvim.util").root.pretty_path()` shows?
I've noticed that lualine component errors are silently ignored.

**Comment by folke** [comment]
OR even better, do you see the path of the buffer in lulaine?

**Comment by theoribeiro** [comment]
Yep, path is fine! pretty_path shows the right root path. In fact, Aerial is working perfectly and showing all the symbols.
![image](https://github.com/LazyVim/LazyVim/assets/41117224/27a2c12a-48f2-4432-9e9f-30deff46ba18)

**Comment by folke** [comment]
That is really odd.

Did you enable the extra with `LazyExtras`? If not, make sure you only import it after LazyVim and before your personal config.

Try commenting everythig related to lualine and aerial in your personal config to see if that fixes it.

**Comment by theoribeiro** [comment]
Found the culprit! Had to disable all of my plugins one by one to find out that whenever `jackMort/ChatGPT.nvim` is on, Aerial disappears from lualine. 

Now... wth does that happen? lol

**Comment by folke** [comment]
That is indeed very weird :)

**Comment by folke** [comment]
Closing

**Comment by theoribeiro** [comment]
Thanks for helping diagnose it @folke ! 
And kudos again for such a great project!!!
