### ISSUE TITLE
bug: When generating default linting configs(nvim-lint) nil is not checked

### ISSUE THREAD

**Issue by aarondill** [LazyVim/LazyVim#1685]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

N/A

### Operating system/version

N/A

### Describe the bug

https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/linting.lua#L29-L33 looks like 
```lua
local lint = require("lint")
      for name, linter in pairs(opts.linters) do
        if type(linter) == "table" and type(lint.linters) == "table" then
          lint.linters[name] = vim.tbl_deep_extend("force", lint.linters[name], linter)
        end
      end
```
This should have an additional check for `lint.linters[name]` to keep the vim.tbl_deep_extend from throwing.

Additionally, there is currently a bug (https://github.com/mfussenegger/nvim-lint/issues/408) where a string (error stack trace) is returned when the linter doesn't exist. Until this is fixed, I suggest checking explicitly that `type(lint.linters[name]) == 'table'`

Furthermore, functions are allowed, so this check is doubly suggested.

### Steps To Reproduce

Create a custom linter
Errors!

### Expected Behavior

No error. Just don't merge config with (non-existent) default config

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  { --- Note: alex must be in PATH!
    "mfussenegger/nvim-lint",
    opts = function(_, opts)
      opts = opts or {}
      opts.formatters = opts.formatters or {}
      opts.linters_by_ft = opts.linters_by_ft or {}
      opts.linters_by_ft.markdown = opts.linters_by_ft.markdown or {}
      table.insert(opts.linters_by_ft.markdown, "alex")

      opts.linters.alex = {
        command = "alex",
        args = { "--stdin", "--quiet" },
        stdin = true,
        cmd = "linter_cmd",
        append_fname = true, -- Automatically append the file name to `args` if `stdin = false` (default: true)
        stream = "stderr", ---@type ('stdout' | 'stderr' | 'both')
        ignore_exitcode = true, -- set this to true if the linter exits with a code != 0 and that's considered normal.
           }
    end,
  },

  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by aarondill** [comment]
I suspect there's a typo and this (after my changes) should look like:
```lua
local lint = require("lint")
  for name, linter in pairs(opts.linters) do
    if type(linter) == "table" and type(lint.linters) == "table" then
      lint.linters[name] = vim.tbl_deep_extend("force", opts.linters[name], linter) -- Note: opts!
    end
end
```

**Comment by folke** [comment]
My bad. Fixed now. That check on ` type(lint.linters)` should have been ` type(lint.linters[name])`

**Comment by folke** [comment]
@aarondill nope, that part is correct. We are merging the options set on the plugin in the default linter config.

**Comment by aarondill** [comment]
You're right. My bad, I didn't notice the `linter` second argument was from `opts.linters`
