### ISSUE TITLE
bug: Linters aren't set from user config if they don't already exist on the linter object. (Nvim-lint)

### ISSUE THREAD

**Issue by aarondill** [LazyVim/LazyVim#1687]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

N/A

### Operating system/version

N/A

### Describe the bug

Linters aren't set from user config if they don't already exist on the linter object.

### Steps To Reproduce

Create a custom linter.
: lua = require('lint').linters
Notice no linters.

### Expected Behavior

```
      for name, linter in pairs(opts.linters) do
        if type(linter) == "table" and type(lint.linters[name]) == "table" then
          lint.linters[name] = vim.tbl_deep_extend("force", lint.linters[name], linter)
        else -- Note the else in case this is a *new* linter. Also handles the case of type(linter) == 'function'.
          lint.linters[name] = linter
        end
      end
```

### Repro

```Lua
Omitted. See #1685
```

**Comment by folke** [comment]
Right, should be fixed properly now! :)

**Comment by aarondill** [comment]
Yep :smile:
Thanks for the quick responses!
