### ISSUE TITLE
bug: Persistence not saving session on VimLeavePre

### ISSUE THREAD

**Issue by LeviticusNelson** [LazyVim/LazyVim#1688]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev-1337+g2c9f22e7e-Homebrew

### Operating system/version

MacOS 14.1 Beta (23B5067a)

### Describe the bug

I have updated to the newest version of LazyVim and no new sessions are being saved upon exiting neovim.

### Steps To Reproduce

1. Update to LazyVim v10
2. Open project with multiple buffers.
3. Exit neovim
4. Attempt to restore session from dashboard or by `<leader>qs`

### Expected Behavior

Expected to have session properly restored.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Can't reproduce. I use session all the time and they always work.

There's also nothing changed at all related to sessions/persistence.

**Comment by LeviticusNelson** [comment]
Hmm, yeah they always work for me too until now, maybe it's something to do with the latest version of neovim?

**Comment by folke** [comment]
Edit: I think I know what's causing this.
Probably showing the news or LazyExtras and restarting before opening an actual file.
In that case your sesson would have been reset.

Can you open neovim, open some files and then restart and load session?

**Comment by LeviticusNelson** [comment]
It looks like restoring last session works but not session

**Comment by LeviticusNelson** [comment]
When I open up a file directly from command line (ex: `vim .wezter.lua`) it properly saves and restores session. When I open up a file from the dashboard it does not save that session at all.

**Comment by LeviticusNelson** [comment]
Maybe the persistence autocmd is not created when opening a file from dashboard?

**Comment by LeviticusNelson** [comment]
The main issue that I am seeing is the ability to restore sessions from a parent directory. Ex: opening `~/.config/nvim/` session from `~/`

**Comment by folke** [comment]
The issue was really caused by displaying the LazyVim news on the dashboard. That cleared the session.
I just fixed this in persistence https://github.com/folke/persistence.nvim/commit/e9afeaf3a7bb645ca73980cd13048c48c292500c

**Comment by alesbrelih** [comment]
Hi. First thanks a lot of LazyVim.. It's really awesome.

I'm staring to get the same problem as mentioned above though.

I'm attaching video that shows what's going on. When I reopen neovim and restore session it didn't remember that I switched file. Not sure if its problem with persistance plugin or the v10 of LazyVim.


https://github.com/LazyVim/LazyVim/assets/10506436/6f99e30f-d7c7-4fc1-89cb-9a8ea825588e

If you need to do something to help debug it, let me know I will be happy to.

**Comment by folke** [comment]
Are you using projects.nvim or any other plugin that changes the cwd?

**Comment by folke** [comment]
I just changed the impl of persistence so that the used cwd is the one when the session started instead of when the session ended.
https://github.com/folke/persistence.nvim/commit/0361df7775f5b4ed51a6d7fe159438573b7f07a6

Let me know if that fixes your issue

**Comment by alesbrelih** [comment]
Just wanted to write that I've used git bisect to see which commit broke restore functionality for me. And I got this:

``` sh
[~/.local/share/nvim/lazy/LazyVim]$ git bisect bad
1bcf6b9a282bc839d4fde92a94b800185ad58118 is the first bad commit
commit 1bcf6b9a282bc839d4fde92a94b800185ad58118
Author: Folke Lemaitre <folke.lemaitre@gmail.com>
Date:   Thu Oct 12 21:47:31 2023 +0200

    feat(extras): LazyExtras can now manage user extras `lua/plugins/extras`. Fixes #1681

 NEWS.md                       |   3 ++
 lua/lazyvim/plugins/xtras.lua |  10 ++--
 lua/lazyvim/util/extras.lua   | 106 +++++++++++++++++++++++++++---------------
```

BUT! Your question made me realize that once LazyExtra was introduced I've installed the `util.project` extra to test it out a bit.

Once I've removed it it is working again! :+1:

Thank you!

**Comment by folke** [comment]
great!

**Comment by alesbrelih** [comment]
> I just changed the impl of persistence so that the used cwd is the one when the session started instead of when the session ended. [folke/persistence.nvim@0361df7](https://github.com/folke/persistence.nvim/commit/0361df7775f5b4ed51a6d7fe159438573b7f07a6)
> 
> Let me know if that fixes your issue

I've reinstalled `util.project` with your fix and it seems to be working now!

Thanks a lot!

You are awesome for doing all this work for community <3
