### ISSUE TITLE
bug: Treesitter and LSP not loaded when editing new file

### ISSUE THREAD

**Issue by leonasdev** [LazyVim/LazyVim#169]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.1

### Operating system/version

Ubuntu 22.04

### Describe the bug

When you edit a new file (e.g. `nvim newfile.lua`), treesitter and LSP will not be loaded, and I think it's because `treesitter` and `lsp-config` are lazy-load with `BufReadPre` or `BufReadPost`.

In [Neovim docs](https://neovim.io/doc/user/autocmd.html#autocmd-events), it says `BufReadPre	BufReadPost	starting to edit an existing file`.

Shouldn't editing a new file behave the same as editing an existing file?

The same situation also exists with these plugins: `gitsigns`, `indent-blankline`, `mini.indentscope`, `null-ls`, `persistence`, `todo-comments`, `vim-illuminate`

### Steps To Reproduce

1. `nvim newfile.lua`

### Expected Behavior

Editing a new file behaves the same as editing an existing file.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
If you edit the `nvim-lspconfig` for event `BufNewFile` it should work. I just tried it and it works
as expected. As an example:
```lua
  {
    "neovim/nvim-lspconfig",
    event = { "BufReadPre", "BufNewFile" },
  },
```
should do the work. Just put the above in a spec under your `plugins` directory.

**Comment by leonasdev** [comment]
> If you edit the `nvim-lspconfig` for event `BufNewFile` it should work. I just tried it and it works as expected. As an example:
> 
> ```lua
>   {
>     "neovim/nvim-lspconfig",
>     event = { "BufReadPre", "BufNewFile" },
>   },
> ```
> 
> should do the work. Just put the above in a spec under your `plugins` directory.

yeah, that should work. or just `BufEnter`.

**Comment by dpetka2001** [comment]
You should also configure the same for `null-ls` to have formatting support in new files as well.

**Comment by leonasdev** [comment]
> You should also configure the same for `null-ls` to have formatting support in new files as well.

yeah I think all my metions before should be concerned.

**Comment by dpetka2001** [comment]
I just tried `BufEnter` but although it recognizes the server that should be attached, it doesn't actually attach
it. `BufNewFile` attaches the server as expected. 
As for your concerns I don't know if this should be the default behavior or not, that would up to the developer
to decide. And making these changes to get the support that you need is really trivial, so it shouldn't be much of
a problem.

**Comment by leonasdev** [comment]
> And making these changes to get the support that you need is really trivial, so it shouldn't be much of
> a problem.
Yeah, it’s up to maintainers, however I would never say that editing a new file with fully feature support is "just my personal use case".

**Comment by folke** [comment]
When I edit a new file as you describe, then treesitter does attach. Am I missing something here?

Lsp servers only attach after you saved the file and then reload it `:e`. That's a limitation on the Neovim lsp implementation I believe.

What difference does the `BufNewFile` bring for you?

**Comment by dpetka2001** [comment]
I didn't know about this LSP limitation. Good to know. This renders `BufNewFile` needless indeed. Thanks for
your help. Although it didn't bother me personally as I usually used NeoTree to create and open new files
and it always attached LSP (though that must be because it inherently does what you said when creating and
opening the file).

**Comment by xulongwu4** [comment]
In my experience, adding the `BufNewFile` event does help when I open a non-existing file. For example, if I do `nvim abc.py` where `abc.py` was not in my filesystem, the LSP won't attach until I reload it if I don't use the `BufNewFile` event. If I use the `BufNewFile` event, the LSP will attach automatically and I don't have to reload it. I guess opening a non-existing file will not trigger the `BufReadPost` event.

**Comment by leonasdev** [comment]
> When I edit a new file as you describe, then treesitter does attach. Am I missing something here?

yes...treesitter does attach, think I have accidentally opened a file that does not have the ts parser when I'm testing.

> Lsp servers only attach after you saved the file and then reload it `:e`. That's a limitation on the Neovim lsp implementation I believe.
> 
> What difference does the `BufNewFile` make for you?

When I'm testing this, using `BufNewFile` event to lazy-load lspconfig, it truly does attach the lsp server when editing an non-existing file.

`BufEnter` and `BufReadPre` both do not attach to lsp server just like @dpetka2001 said.


https://user-images.githubusercontent.com/39915562/217132977-58739f73-17ab-4a7b-8cf0-4426329778d4.mp4

**Comment by folke** [comment]
Damn, I always thought that was a limitation of lspconfig, so thank you for this!

Just updated all events to include `BufNewFile`.

Everything now indeed seems to work for new files as well!

**Comment by leonasdev** [comment]
> Everything now indeed seems to work for new files as well!

Glad you fix it!👍👍
