### ISSUE TITLE
bug: leader changed to `\` and OS clipboard not handled

### ISSUE THREAD

**Issue by Martin1887** [LazyVim/LazyVim#1695]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.2

### Operating system/version

Fedora 38

### Describe the bug

It seems that some options are not read after the update to LazyVim 10. Concretely, `mapleader` is set as the default value (`\`) and `clipboard` too (empty instead of `unnamedplus`), not handling OS clipboard. 

### Steps To Reproduce

1. Open Neovim.
2. ` ` is not the `leader` key.
3. OS clipboard is not pasted with `p`.

### Expected Behavior

` ` is the `leader` key as in the previous versions and `clipboard` is set to `unnamedplus` to handle OS clipboard.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
That means LazyVim never initialized. Is there somthing special about your setup?
What's in your `lua/config/lazy.lua` file?
Did you overwrite the `lazyvim.plugins` module by accident? By creating a file `lua/lazyvim/plugins.lua` or `lua/lazyvim/plugins/init.lua`.

Either way, closing, since this must be something you did wrong in your config.

**Comment by Martin1887** [comment]
I'm using the starter template with additional plugins, and it works in LazyVim < 10 (including 9.9.1).

**Comment by folke** [comment]
ok, I'll check with your config

**Comment by folke** [comment]
Can you link your config? Since the starter does work

**Comment by Martin1887** [comment]
Then I will play a bit more with it in some hours. My current configuration is customizing `none-ls` and therefore it produces a conflict when upgrading. I replaced it yesterday with conform.nvim and nvim-lint but it is not committed yet.

If the starter works maybe the problem is upgrading with none-ls active and a clean installation with the new config should also work. I will check this today and update the issue then.

Thanks!

**Comment by Martin1887** [comment]
I have tried in a clean install and it keeps happening.

I have created a branch with the updated config in 
https://github.com/Martin1887/dotenv/tree/LazyVim10/nvim

Thanks!

**Comment by Martin1887** [comment]
What a silly error! It worked in previous versions but fixing the typo has fixed the problem, so the issue does not actually exist.

Thanks!
