### ISSUE TITLE
bug: after installing prettier extra, `gqq` in a markdown file does not work, causes conform to error

### ISSUE THREAD

**Issue by birtles** [LazyVim/LazyVim#1697]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.1

### Operating system/version

Ubuntu 22.04.3 LTS (WSL)

### Describe the bug

Attempting to wrap lines in a markdown file using `gqq` no longer works after enabling the `prettier` extra. Instead I get a notification `Formatter failed. See :ConformInfo for details`.

The log in `~/.local/state/nvim/conform.log` simply shows:

```
18:04:24[ERROR] Formatter 'prettierd' error: 
```

(i.e. an empty error)

Note that prior to LazyVim 10 I was working around issues with `gq` sometimes not working by unsetting `formatexpr` when `null-ls` had no fomatting generator as per [this comment](https://github.com/jose-elias-alvarez/null-ls.nvim/issues/1131#issuecomment-1457584752).

Please forgive me if this is an issue with `conform.nvim` (I searched the repo there but thought I'd start here).

### Steps To Reproduce

1. Possibly install `prettierd` (e.g. `npm install -g @fsouza/prettierd` or `yarn global add @fsouza/prettierd`. I think LazyVim does this via the `prettier` extra, however?)
2. `mkdir lazyvim-bug-repro`
3. `cd lazyvim-bug-repro`
4. `git clone https://github.com/LazyVim/starter .config/nvim`
5. `XDG_CONFIG_HOME=.config nvim`
6. `:LazyExtras`
7. Enable the prettier extra
8. Restart NeoVim opening a file called `test.md`: `XDG_CONFIG_HOME=.config nvim test.md`
9. Insert "This sentence is long--nearly 100 characters in length--but we want to wrap it to 80 characters"
10. Return to normal mode
11. `:set tw=80`
12. Type `gqq`

### Expected Behavior

The line is wrapped to 80 characters.

### Repro

`init.lua`

```lua
-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
```

`lazyvim.json`

```json
{
  "extras": [
    "lazyvim.plugins.extras.formatting.prettier"
  ],
  "news": {
    "NEWS.md": "2123"
  },
  "version": 2
}
```

**Comment by folke** [comment]
Something you should report in the conform repo indeed.
