### ISSUE TITLE
bug: error when disabling dashboard with newest lazyvim version

### ISSUE THREAD

**Issue by Delice0** [LazyVim/LazyVim#1706]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

latest

### Operating system/version

mac latest

### Describe the bug

I had dashboard disabled before newest lazyvim version and now i found out that it was enabled but from another repo. I disabled it again:

  { "nvimdev/dashboard-nvim", enabled = false },

and now i get an error everytime i open nvim:

```
   Error  22:52:27 notify.error lazy.nvim Two plugins with the same name and different url:
{
  new = { "nvimdev/dashboard-nvim",
    _ = {
      dep = false,
      fid = 95,
      module = "plugins.disabled-plugins"
    },
    dir = "/Users/me/.local/share/nvim/lazy/dashboard-nvim",
    enabled = false,
    name = "dashboard-nvim",
    url = "https://github.com/nvimdev/dashboard-nvim.git"
  },
  old = { "glepnir/dashboard-nvim",
    _ = {
      dep = false,
      fid = 52,
      module = "lazyvim.plugins.ui"
    },
    dir = "/Users/me/.local/share/nvim/lazy/dashboard-nvim",
    event = "VimEnter",
    name = "dashboard-nvim",
    opts = <function 1>,
    url = "https://github.com/glepnir/dashboard-nvim.git"
  }
}
```

I couldn't find any "dashboard" inside my local lazy dir.

What do I do?

### Steps To Reproduce

disable nvim/dashboard-nvim

### Expected Behavior

expect no errors when disabling dashboard

**Comment by dpetka2001** [comment]
They're the same plugin and the problem is that `Lazy` cannot assign the same name to a plugin with 2 different urls. You could just delete the line from your config entirely for the error to go away, since it's already included to default Lazyvim and manage it from Lazy. I guess @folke could also just change the url of the plugin or just add to `renames` the old and new url, so that `Lazy` doesn't complain.

**Comment by Delice0** [comment]
I don't want any dashboard, so I need to disable it without any errors popping up, so I guess the "delete the code and the error goes away" isn't really an option for me.

**Comment by dpetka2001** [comment]
Change your `{ "nvimdev/dashboard-nvim", enabled = false },` to `{ "glepnir/dashboard-nvim", enabled = false },`

**Comment by folke** [comment]
fyi, I added the rename to LazyVim, so this should no longer cause similar issues for others

**Comment by Delice0** [comment]
> fyi, I added the rename to LazyVim, so this should no longer cause similar issues for others

When I add 'url' field to target another repo (my own e.g.) for a plugin, i get the same kind of error like the one I described here.

Here's a minimal config:

```
return {
  "hrsh7th/nvim-cmp",
  url = "https://github.com/Delice0/nvim-cmp.git", -- use local version from GITHUB
}
```

What to do in this situation? I want to use my local version of nvim-cmp from my own github repo.

**Comment by dpetka2001** [comment]
The same answer that I gave you in my previous post applies here. There can't be the same plugin module with 2 different urls. Since nvim-cmp is already installed by default in Lazyvim, it's already parsed by `lazy.nvim` with its default url. I don't know if this would work, but you could either disable the default one and then in your own specify a different `name`, so that Lazy doesn't complain, or you could clone your git repo to your local and state in your spec that nvim-cmp should be defined as dev (look at `lazy.nvim`'s `dev` property). You should read the [lazy.nvim docs](https://github.com/folke/lazy.nvim) more thoroughly to understand how it works.

**Comment by Delice0** [comment]
Disabling hrsh7th/nvim-cmp doesn't make a change. I already tried that

**Comment by Delice0** [comment]
Why can't i have the same name but different url? I can't see the problem in that. It provides a lot of  flexibility imo

**Comment by folke** [comment]
Use the `dir` or `dev` option instead.

**Comment by Delice0** [comment]
> Use the `dir` or `dev` option instead.

That doesn't really solve the issue because according to the documentation:

```
 -- local plugins can also be configure with the dev option.
  -- This will use {config.dev.path}/noice.nvim/ instead of fetching it from Github
  -- With the dev option, you can easily switch between the local and installed version of a plugin
```

I have a forked repository of nvim-cmp that I want to use for both my personal and workstation. I don't want to clone the repository in both places, instead, I should "just" be able to fetch from my local forked repository instead of the original one with lazy throwing that error.

Is this possible or no?

**Comment by folke** [comment]
nope, not possible. I do this as well like that using the dev option and cloning it locally.

**Comment by Delice0** [comment]
It's not like it's not working for me. I can clone it locally and set the dev option and it's fine, but then I would have to clone the forked repository to my workstation too which I see as unnecessary if what I suggested was possible.

Any plan on adding this feature, then?

**Comment by folke** [comment]
I just changed it to a warning, which means in practice you will only see that warning when running `:checkhealth`

https://github.com/folke/lazy.nvim/commit/0c53d4673ff02c57a192558325b394cfd9adde0f
