### ISSUE TITLE
bug: unable to install stylua in docker image 

### ISSUE THREAD

**Issue by HakonHarnes** [LazyVim/LazyVim#1716]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

Docker: alpine:edge - Host: Arch Linux (kernel 6.5.6)

### Describe the bug

Some LSPs won't install with Mason due to a "The current platform is unsupported." when using Docker. This occurs for both `stylua` and `tailwind-css-language-server`.

### Steps To Reproduce

Run the docker commands as per the [docs](https://www.lazyvim.org/installation):

```sh
docker run -w /root -it --rm alpine:edge sh -uelic '
  apk add git lazygit neovim ripgrep alpine-sdk --update
  git clone https://github.com/LazyVim/starter ~/.config/nvim
  cd ~/.config/nvim
  nvim
'
```

Let it install the dependencies and run: 

```
:MasonLog
```

Error: 

```
Installation failed for Package(name=stylua) error="The current platform is unsupported."
```

### Expected Behavior

stylua and other formatters/LSPs should install successfully.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
What does this have to do with Lazyvim? See similar issue at Maso [repo](https://github.com/williamboman/mason.nvim/discussions/1406).

**Comment by HakonHarnes** [comment]
> What does this have to do with Lazyvim? See similar issue at Mason [repo](https://github.com/williamboman/mason.nvim/discussions/1406).

It's related to the LazyVim docs. Perhaps the alpine Docker image should be replaced with a different image?

**Comment by dpetka2001** [comment]
No it doesn't because Lazyvim installs correctly and the packages from Mason are not able to install because of "unsupported architecture". If Lazyvim installs correctly, do you really expect every other plugin that might not be supported by the Docker architecture to be taken into account in the Lazyvim docs? The author of Mason gave an answer in the issue I attached in my previous post. Nothing that can be done from Lazyvim's side. Just try another image to see if it works.
