### ISSUE TITLE
bug: nvim-lint events table are not working properly

### ISSUE THREAD

**Issue by connorvict** [LazyVim/LazyVim#1719]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.2 

### Operating system/version

Arch Linux 20230723.0.166908

### Describe the bug

According to the Lazynvim docs, this should work
![image](https://github.com/LazyVim/LazyVim/assets/45220802/4160e2f9-777b-469b-b0c2-2d6df16a38c7)

but the linters only trigger on BufWritePost and BufReadPost which I believe is default behavior. I tried several different events including InsertLeave, InsertEnter, and InsertChange, but they don't trigger the linters.  Could be something I am doing wrong, but I don't know what that would be. Any ideas?

### Steps To Reproduce

1. Create a new file in plugins directory
2. Add the following and ensure linters are installed:
![image](https://github.com/LazyVim/LazyVim/assets/45220802/5c1af79a-a92f-4c97-a67a-901e10b5bdd5)
3. Leaving Insert mode does not trigger linters, only save and open file do.

### Expected Behavior

Adding events such as InsertLeave should invoke the linters when the event fires.

**Comment by folke** [comment]
Not sure what you want to achieve, but that `events` should be under `opts`.
It's quite clear in the docs https://www.lazyvim.org/plugins/linting

Please, use discussions next time for user questions

**Comment by folke** [comment]
Every lazy spec has a top-level `event` entry. For nvim-lint that's `LazyFile`, which translates to `{ "BufReadPost", "BufNewFile", "BufWritePre" }`.

Those are the lazy-loading events meaning the plugin load as soon as one of those events trigger
