### ISSUE TITLE
bug: can not overwrite mini.surround keybinds

### ISSUE THREAD

**Issue by pprotas** [LazyVim/LazyVim#172]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.0-dev-2057+g8376486e8-dirty

### Operating system/version

MacOS 13.2

### Describe the bug

You can not overwrite the keybinds for surround objects with `mini.surround`. Here is an example config:

```lua
return {
  {
    "echasnovski/mini.surround",
    opts = {
      mappings = {
        add = "sa",
        delete = "sd",
        find = "sf",
        find_left = "sF",
        highlight = "sh",
        replace = "sr",
        update_n_lines = "sn",
      },
    },
  },
}
```

This doesn't work, see how the keybinds look like in Telescope:

![image](https://user-images.githubusercontent.com/30273418/216764768-760715a9-2952-476b-9f9c-be2bd92de2d7.png)

I tried replicating [the full spec from the docs](https://www.lazyvim.org/plugins/coding#minisurround), but now I have duplicate keybinds:

```lua
return {
  {
    "echasnovski/mini.surround",
    keys = function(plugin, keys)
      local opts = require("lazy.core.plugin").values(plugin, "opts", false)
      local mappings = {
        { opts.mappings.add, desc = "Add surrounding", mode = { "n", "v" } },
        { opts.mappings.delete, desc = "Delete surrounding" },
        { opts.mappings.find, desc = "Find right surrounding" },
        { opts.mappings.find_left, desc = "Find left surrounding" },
        { opts.mappings.highlight, desc = "Highlight surrounding" },
        { opts.mappings.replace, desc = "Replace surrounding" },
        { opts.mappings.update_n_lines, desc = "Update `MiniSurround.config.n_lines`" },
      }
      return vim.list_extend(mappings, keys)
    end,
    opts = {
      mappings = {
        add = "sa",
        delete = "sd",
        find = "sf",
        find_left = "sF",
        highlight = "sh",
        replace = "sr",
        update_n_lines = "sn",
      },
    },
  },
}
```

![image](https://user-images.githubusercontent.com/30273418/216764898-307d16b7-7c7d-431d-b832-723a4bc07eae.png)

Flit and Leap are both **disabled**.

### Steps To Reproduce

1. Use one of the example configs above
2. Notice that the shortcuts aren't as configured or there are duplicate shortcuts

### Expected Behavior

I can use `s` instead of `gz` for surrounding

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
`s` is the default key for Neovim to delete characters and enter into `insert` mode to enter new characters for
the deleted ones. I don't think this is specifically a LazyVim behavior. You should probably try to use a `<leader>`
key in your keymappings or some other key that doesn't conflict with the default Neovim mappings.

**Comment by pprotas** [comment]
These are the default keybinds for `mini.surround`. Just because vim uses `s` by default shouldn't mean that I can't re-map it.

**Comment by alezunino** [comment]
I redefined mini.surround keymaps using this:

  -- disable leap to avoid conflict with mini.aling and mini.jump
  {
    "ggandor/leap.nvim",
    enabled = false,
  },

  {
    "echasnovski/mini.surround",
    event = "BufRead",
    keys = function(_, keys)
      local mappings = {
        { "sa", desc = "Add surrounding", mode = { "n", "v" } },
        { "sd", desc = "Delete surrounding" },
        { "sf", desc = "Find right surrounding" },
        { "sF", desc = "Find left surrounding" },
        { "sh", desc = "Highlight surrounding" },
        { "sr", desc = "Replace surrounding" },
      }
      return vim.list_extend(mappings, keys)
    end,
    config = function(_, _)
      require("mini.surround").setup({})
    end,
  },

**Comment by dpetka2001** [comment]
```lua
{
    "echasnovski/mini.surround",
    keys = function(plugin, keys)
      -- Populate the keys based on the user's options
      local opts = require("lazy.core.plugin").values(plugin, "opts", false)
      local mappings = {
        { opts.mappings.add, desc = "Add surrounding", mode = { "n", "v" } },
        { opts.mappings.delete, desc = "Delete surrounding" },
        { opts.mappings.find, desc = "Find right surrounding" },
        { opts.mappings.find_left, desc = "Find left surrounding" },
        { opts.mappings.highlight, desc = "Highlight surrounding" },
        { opts.mappings.replace, desc = "Replace surrounding" },
        { opts.mappings.update_n_lines, desc = "Update `MiniSurround.config.n_lines`" },
      }
      return vim.list_extend(mappings, keys)
    end,
    opts = {
      mappings = {
        add = "gza", -- Add surrounding in Normal and Visual modes
        delete = "gzd", -- Delete surrounding
        find = "gzf", -- Find surrounding (to the right)
        find_left = "gzF", -- Find surrounding (to the left)
        highlight = "gzh", -- Highlight surrounding
        replace = "gzr", -- Replace surrounding
        update_n_lines = "gzn", -- Update `n_lines`
      },
    },
    config = function(_, opts)
      -- use gz mappings instead of s to prevent conflict with leap
      require("mini.surround").setup(opts)
    end,
  },
```
If you use this config and just replace the mappings with for example `<leader>ma>` as you wrote in 
your previous post it will work. Just tried it. Of course you would have to add a corresponding `which-key`
keymap for `<leader>m` so that it could show in the `which-key` pop-up menu.

**Comment by pprotas** [comment]
@dpetka2001 This works but I already mentioned this in my original post. This results in duplicate keybindings, so it is not a good solution.

@alezunino's solution works! Thanks

**Comment by dpetka2001** [comment]
@pprotas It doesn't result in duplicate keybindings for me. I only have the `<leader>m` keybindings which replaced
the original ones. 

I don't see how this could be considered a bug. You have to customize the configuration to apply for your 
preferences. Not everyone likes the default keybindings, but there are others that don't mind. Since you are given
the possibility to tinker the default configuration according to your preferences, how is this a bug?

**Comment by pprotas** [comment]
Interesting, I have duplicate keybinds with the configuration you provided:
![image](https://user-images.githubusercontent.com/30273418/216773676-4cd8bedf-ec7e-4e3c-971d-9bb02db6c37b.png)

Just because there is a workaround doesn't mean that it isn't a bug, right? Maybe our definitions of bug differ! In any case, I'll let the maintainers decide on that

**Comment by dpetka2001** [comment]
Yes you are correct!! I must have done something wrong in my previous test with the config provided. Just tested 
again and I get duplicate entries as well. Sorry for what I stated in my previous comment.

**Comment by dpetka2001** [comment]
Yes, that is because we use `vim.list_extend`, which appends the new values to the already constructed list and we 
get dupplicate keybindings. If you use instead `vim.tbl_deep_extend` you shouldn't get any more duplicates. This applies 
to the other more elegant solution as well. I tried it and it seems to work.

**Comment by pprotas** [comment]
Hmm I am back to sew some chaos in this thread... I was too hasty in saying that @alezunino's solution worked. It does add the mappings to my WhichKey, but the keys don't actually don't do anything.

I am now using @dpetka2001's solution with `return vim.tbl_deep_extend("keep", mappings, keys)`, that seems to fix both of my problems. So no more duplicate keybinds and the keys are correctly remapped.

**Comment by alezunino** [comment]
My solution does work. I use it on several computers. Besides, I am addicted to "sa" "se" and "sd" keys 😜. Just copy the code I posted before, including: event = "BufRead"

**Comment by dpetka2001** [comment]
Could you plz elaborate on what `event = "BufRead"` does exactly. I tried your solution as well and indeed it works.
But then when i went to remap the keys to `<leader>ma>` your keys would still show up in `Telescope search keymaps`.
When I commented out `event = "BufRead"`, then they stopped showing. Just LazyVim keep some kind of state for the 
buffer and it still shows your keymaps when `event = "BufRead"` is not commented? Really curious why this is happening.

**Comment by pprotas** [comment]
I made a PR to fix the bug, see https://github.com/LazyVim/LazyVim/pull/177.

**Comment by alezunino** [comment]
> Could you plz elaborate on what `event = "BufRead"` does exactly. I tried your solution as well and indeed it works. But then when i went to remap the keys to `<leader>ma>` your keys would still show up in `Telescope search keymaps`. When I commented out `event = "BufRead"`, then they stopped showing. Just LazyVim keep some kind of state for the buffer and it still shows your keymaps when `event = "BufRead"` is not commented? Really curious why this is happening.

The "BufRead" event is triggered when starting to edit a new buffer. On the other hand, the original config of mini.surround will load it "VeryLazy"ly, which is AFAIK after than BufRead. In other words, BufRead in my config seems to take precedence over the one defined in LazyVim. Not 100% sure about this...

Anyway, in my code the keybindings defined by mini.surround are not modified (meaning that sa, sd, etc... are defined in mini). To modify the keys you should use something like this: 
`
{
    "echasnovski/mini.surround",
    event = "BufRead",
    -- keys = function(_, _) end,
    keys = function(_, keys)
      local mappings = {
        { "<leader>ma", desc = "Add surrounding", mode = { "n", "v" } },
        { "<leader>md", desc = "Delete surrounding" },
        { "<leader>mf", desc = "Find right surrounding" },
        { "<leader>mF", desc = "Find left surrounding" },
        { "<leader>mh", desc = "Highlight surrounding" },
        { "<leader>mr", desc = "Replace surrounding" },
      }
      return vim.list_extend(mappings, keys)
    end,
    opts = {
      mappings = {
        add = "<leader>ma", -- Add surrounding in Normal and Visual modes
        delete = "<leader>md", -- Delete surrounding
        find = "<leader>mf", -- Find surrounding (to the right)
        find_left = "<leader>mF", -- Find surrounding (to the left)
        highlight = "<leader>mh", -- Highlight surrounding
        replace = "<leader>mr", -- Replace surrounding
        update_n_lines = "<leader>mn", -- Update `n_lines`
      },
    },
    config = function(_, opts)
      require("mini.surround").setup(opts)
    end,
  }
`

the difference here is that we are passing the "opts" parameter to mini, where "opts" contain the keys.

**Comment by folke** [comment]
This should now be fixed. You can just change the opts and the keys will be updated as expected.
