### ISSUE TITLE
feature: A way to disable welcome message?

### ISSUE THREAD

**Issue by curtbushko** [LazyVim/LazyVim#1723]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

I know this is brand new (like 2 hours old), but is there a way to disable the Welcome to LazyVim message?

### Describe the solution you'd like

A toggle in the config.

### Describe alternatives you've considered

N/A

**Comment by folke** [comment]
It should only be shown after a clean install. Are you seeing it more than that?

**Comment by curtbushko** [comment]
I see it on every run of neovim. I am using nix to configure my neovim install and I would guess that the state is not allowed to be written somewhere?

I put up a PR for the toggle: https://github.com/LazyVim/LazyVim/pull/1724

**Comment by folke** [comment]
It's the file `~/.config/nvim/lazyvim.json`. That contains installed extras and some state information on what news you have seen. This file should be part of your configuration.

Putting the news state in `config` instead of `stdpath.state` is on purpose, since it's not dependent on the machine where LazyVim is running on, but on the user's dotfiles.

When the file doesn't contain a state for news, it means a new user that never used LazyVim before.

I assume your nvim config dir is not writable?

Easiest way to fix showing that welcome message, is to make sure there's a `lazyvim.json` file containing:

```json
{
  "news": {
    "NEWS.md":0
  }
}
```

Things like `:LazyExtras` obviously won't work in a setup where that file is not writeable

**Comment by curtbushko** [comment]
Thank you for circling back!  (love you work)

> I assume your nvim config dir is not writable?

That is correct. Nix has the directory locked down.

There is probably a way to do it the nix way. I will report back when I figure it out.

**Comment by curtbushko** [comment]
"0" threw an error but the setting below worked:

```{
"extras": [

],
"news": {
"NEWS.md": "2123"
},
"version": 2
}```

**Comment by danilo-alm** [comment]
I'm having this same problem, but I'm on Arch. The file is readable and writable. NEWS.md is already "2123" (it was by default); changing it to 0 or "0" still triggers the welcome message on the next run AND the value gets changed back to "2123".

**Comment by Julien76** [comment]
I am getting the same issue on Nix. The lazy.json is readonly. Manually (forcing) setting the new.md value has no effect and the pop up shows at every launch.

**Comment by Julien76** [comment]
I see in `lazyvim/config/init.lua` the following option:
`` 
news = {
    -- When enabled, NEWS.md will be shown when changed.
    -- This only contains big new features and breaking changes.
    lazyvim = false,
    -- Same but for Neovim's news.txt
    neovim = false,
  },
``

how to set the news.lazyvim to false in an existing config? 

Manually overriding the value in `.local/share/nvim/lazy/LazyVim/lua/config/init.lua` works to get rid of the message but that is not a permanent solution.

**Comment by dpetka2001** [comment]
You should set it in your `~/.config/nvim/lua/config/lazy.lua` file.

**Comment by Julien76** [comment]
@dpetka2001 
I already tried with the following but it has no effect:
```lua
require("lazy").setup({
  spec = {
    -- add LazyVim and import its plugins
    { url="https://gitlab.com/Julien76/LazyVim.git", import = "lazyvim.plugins" },
    -- { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- import any extras modules here
    { import = "lazyvim.plugins.extras.lang.typescript" },
    { import = "lazyvim.plugins.extras.lang.json" },
    -- { import = "lazyvim.plugins.extras.editor.flash" },
    { import = "lazyvim.plugins.extras.ui.mini-animate" },
    { import = "lazyvim.plugins.extras.dap.core" },
    { import = "lazyvim.plugins.extras.dap.nlua" },
    { import = "lazyvim.plugins.extras.test.core" },
    { import = "lazyvim.plugins.extras.util.project" },
    { import = "lazyvim.plugins.extras.coding.copilot" },
    -- { import = "lazyvim.plugins.extras.coding.yanky" },
    -- import/override with your plugins
    { import = "plugins" },
    { import = "plugins.lang" },
  },
  defaults = {
    -- By default, only LazyVim plugins will be lazy-loaded. Your custom plugins will load during startup.
    -- If you know what you're doing, you can set this to `true` to have all your custom plugins lazy-loaded by default.
    lazy = false,
    -- It's recommended to leave version=false for now, since a lot the plugin that support versioning,
    -- have outdated releases, which may break your Neovim install.
    version = false, -- always use the latest git commit
    -- version = "*", -- try installing the latest stable version for plugins that support semver
  },
  news = {
    -- When enabled, NEWS.md will be shown when changed.
    -- This only contains big new features and breaking changes.
    lazyvim = false,
    -- Same but for Neovim's news.txt
    neovim = false,
  },
  install = { colorscheme = { "tokyonight", "habamax" } },
  checker = { enabled = true }, -- automatically check for plugin updates
  performance = {
    rtp = {
      -- disable some rtp plugins
      disabled_plugins = {
        "gzip",
        -- "matchit",
        -- "matchparen",
        -- "netrwPlugin",
        "tarPlugin",
        "tohtml",
        "tutor",
        "zipPlugin",
      },
    },
  },
})
```
``

**Comment by dpetka2001** [comment]
I'm sorry. I was wrong. You should set it in the LazyVim spec. So, create a file in `~/.config/nvim/lua/plugins/core.lua` with contents
```lua
return {
	{
	  "LazyVim/LazyVim",
	  opts = {
	    news = { lazyvim = false },
	  },
	},
}
```

**Comment by Julien76** [comment]
@dpetka2001 , works great thank you so much :smiley:
