### ISSUE TITLE
bug: text highlighted while navigation through code

### ISSUE THREAD

**Issue by Traap** [LazyVim/LazyVim#1725]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev-9f32deb

### Operating system/version

6.5.7-arch1-1

### Describe the bug

I am not sure if this is a bug or a feature.  A barebones LazyVim installation consisting of:

local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
-- Bootstrap lazy.nvim
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", lazypath
  })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

require("lazy").setup({
	-- Setup lazy
	spec = {
		{ "LazyVim/LazyVim", import = "lazyvim.plugins" },
		{ import = "lazyvim.plugins.extras.editor.leap" },
	},

	defaults = { lazy = false, version = false },

	install = { colorscheme = { "tokyonight", "habamax" } },

	checker = { enabled = true },

	performance = {
		rtp = {
			disabled_plugins = {
				"gzip",
				"netrwPlugin",
				"tarPlugin",-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here

				"tohtml",
				"tutor",
				"zipPlugin",
			},
		},
	},
})

Produces undesirable side-effects or feature change.
 
![ArcoLinux_2023-10-14_12-48-54](https://github.com/LazyVim/LazyVim/assets/1930415/7ad2c683-eb79-43fd-b03f-6a0c8c5ac75d)

Notice relative line numbers 719, 154, 142, 86 and highlighted.  How does is this disabled?

### Steps To Reproduce

Edit any source file with nested lua configuration.

### Expected Behavior

I do not expect LazyVim  plugins to adjust text representation without being configured to do so.

**Comment by amaanq** [comment]
that's context info, you can remove it by disabling nvim-treesitter-context

**Comment by dpetka2001** [comment]
It's been made toggleable with the latest release using the keymap `<leader>ut`.

**Comment by Traap** [comment]
Thanks.

**Comment by folke** [comment]
That's a new addition indeed. You can disable it in your own config.
