### ISSUE TITLE
LSP windows don't have border

### ISSUE THREAD

**Issue by lpanebr** [LazyVim/LazyVim#173]
I'm loving lazyvim!

The only thing do fat that's bugging me is I don't know how to make LSP windows like hover, diagnostic etc to have a border.

Any idea?
Thanks!

**Comment by krolyxon** [comment]
you can do something like this, (i am not a lazyvim user but i do use cmp, and i see lazyvim hasnt configured borders so i am just suggesting this)

```lua
local function border(hl_name)
    return {
        { "╭", hl_name },
        { "─", hl_name },
        { "╮", hl_name },
        { "│", hl_name },
        { "╯", hl_name },
        { "─", hl_name },
        { "╰", hl_name },
        { "│", hl_name },
    }
end

require("cmp").setup {
window = {
        completion = {
            border = border "CmpBorder",
        },
        documentation = {
            border = border "CmpDocBorder",
        },
    },
}
```

**Comment by folke** [comment]
That's not a bug, since I personally prefer not having borders :)

But as you found out yourself, it's pretty easy to add borders to your config.

**Comment by loichyan** [comment]
You can add [this file](https://github.com/loichyan/dotfiles/blob/main/config/nvim/lua/plugins/_border.lua) to your local config directory, it adds rounded border to borderless plugins.

**Comment by lpanebr** [comment]
>
> This file is great. Exactly what I needed.
>
Thank you!Message ID: ***@***.***>
>

**Comment by robertsarkozi** [comment]
I've added that code snippet above to lazy.lua, options.lua and I see it is applied, if I print the cmp.window.completion and .documentation values, but for the K (show documentation) command it doesn't draw borders. For code completion, borders are drawn.

In which file do I add it to make it work?

Thanks

**Comment by loichyan** [comment]
> You can add [this file](https://github.com/loichyan/dotfiles/blob/lazyvim/config/nvim/lua/plugins/_border.lua) to your local config directory, it adds rounded border to borderless plugins.

Sorry for the broken link :( I have replaced it with [a permalink](https://github.com/loichyan/dotfiles/blob/lazyvim/config/nvim/lua/plugins/_border.lua).

> In which file do I add it to make it work?

@robertsarkozi You can enable the `lsp_doc_border` preset of `noice.nvim` to configure a rounded border:

```lua
  {
    "noice.nvim",
    opts = {
      presets = { lsp_doc_border = true },
    },
  }
```

If your `noice.nvim` is disabled, you can follow [this guide](https://github.com/neovim/nvim-lspconfig/wiki/UI-Customization#borders) to add a border to the native UI:

```lua
local orig_util_open_floating_preview = vim.lsp.util.open_floating_preview
function vim.lsp.util.open_floating_preview(contents, syntax, opts, ...)
  opts = opts or {}
  opts.border = opts.border or "rounded"
  return orig_util_open_floating_preview(contents, syntax, opts, ...)
end
```

**Comment by robertsarkozi** [comment]
Works by adding a border.lua file and setting that content in the permalink. Thanks!
