### ISSUE TITLE
Version / Hash calculation of the NEWS.md file differs on Windows and Linux systems

### ISSUE THREAD

**Issue by folstein** [LazyVim/LazyVim#1730]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.4

### Operating system/version

Windows 11

### Describe the bug

When sharing a config with a Windows and Linux system via git the versioning information in the lazyvim.json for the NEWS.md file is different on the two systems. This appears to be because a hash is calculated on the local file and it will be different because of different line endings. When I push a config change from one system to the other I am shown the news popup even though nothing has changed because the hashes are different.

### Steps To Reproduce

1. Make a change to the LazyExtras on one system.
2. Save the changes and push to a remote repo.
3. Pull the changes on a different system.
4. Launch nvim.

### Expected Behavior

The news pop should only be shown when the contents of the NEWS.md file changes.

**Comment by folke** [comment]
You'll just have to live with it or disable news.
The hash is the file size of the `NEWS.md` file.
Do you have `auto_crlf` set or something?
Either way, won't fix. Not worth further looking into this.
