### ISSUE TITLE
bug: checkout failed

### ISSUE THREAD

**Issue by SuperCB** [LazyVim/LazyVim#1732]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.2

### Operating system/version

ubuntu 20.0

### Describe the bug

![image](https://github.com/LazyVim/LazyVim/assets/82354186/59cf9fd0-cdcc-4657-b7a9-22fc41ee192c)

### Steps To Reproduce

When I upgraded LazyVim to the latest version, I encountered a situation where I deleted all the content in the. local/share/nvim file and reinstalled nvim

### Expected Behavior

there should no warning

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
I don't see how this can happen with the current code-base.
Might have been that you had an older version of either lazy or LazyVim and only upgraded one of the two.

Closing, since at this time this simply can never happen
