### ISSUE TITLE
bug: nvim-lint permits functions as linter config, but LazyVim doesn't

### ISSUE THREAD

**Issue by aarondill** [LazyVim/LazyVim#1734]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

N/A

### Operating system/version

N/A

### Describe the bug

Here we check for the linter and it's properties, but if the linter is a function instead of a table, then this will fail and it won't be included.

https://github.com/LazyVim/LazyVim/blob/7c60431c58a050cf4badced0609f3179bd284137/lua/lazyvim/plugins/linting.lua#L78

Here in the nvim-lint readme it says: (https://github.com/mfussenegger/nvim-lint/blob/master/README.md?plain=1#L180-L182)
```markdown
Instead of declaring the linter as a table, you can also declare it as a
function which returns the linter table in case you want to dynamically
generate some of the properties.
```

### Steps To Reproduce

Declare a linter as a function. Try using this linter. It won't be included when using LazyVim's linting keybinds. Only if try_lint is manually called (therefore defaulting to nvim-lint's handling)

### Expected Behavior

Permit all configurations permitted by nvim-lint.

### Repro

```Lua
Sorry, I don't have a repro. Let me know if you really want one and I'll generate it when I get the chance.
```

**Comment by aarondill** [comment]
Here's the check in the source for nvim-lint as to whether linter is a function (oddly only in M.try_lint, not in M.lint, seems like a possible bug in nvim-lint?)

https://github.com/mfussenegger/nvim-lint/blob/6d596b87862909370f4d1e6535cc9fad80c89fe6/lua/lint.lua#L142C5-L144

**Comment by folke** [comment]
That code you link to will not fail when the linter is a function. See the `not` before the `condition` check

**Comment by folke** [comment]
So if the linter is a function, this will return true, since `type(linter)` is `function`:

```lua
linter and not (type(linter) == "table" and ...)
```

**Comment by aarondill** [comment]
You are right. Sorry for wasting your time. Hope you have a good night (or whatever time it is where you are).
