### ISSUE TITLE
bug: LazyVim can't create/access lazy-lock.json under NixOS

### ISSUE THREAD

**Issue by carlouws** [LazyVim/LazyVim#174]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.0-dev-8376486

### Operating system/version

NixOS 23.05.20230120.5ed4819 (Stoat)

### Describe the bug

A lockfile can't be created when using Home-Manager within NixOS to install and manage neovim and its config files. NixOS keeps the config files in the nix store `/nix/store` which is read-only and symlinks it to the appropriate location in my home folder `~/.config/nvim`. Since `/nix/store` is read-only, whenever LazyVim tries to create the lockfile I get this error: 

> Error executing vim.schedule lua callback: ...local/share/nvim/lazy/lazy.nvim/lua/lazy/manage/lock.lua:12: /home/carlouws/.config/nvim/lazy-lock.json: Read-only file system
stack traceback:
	[C]: in function 'assert'
	...local/share/nvim/lazy/lazy.nvim/lua/lazy/manage/lock.lua:12: in function 'update'
	...local/share/nvim/lazy/lazy.nvim/lua/lazy/manage/init.lua:111: in function <...local/share/nvim/lazy/lazy.nvim/lua/lazy/manage/init.lua:110>

### Steps To Reproduce

1. Add neovim to home-manager
2. Create `./nvim` folder with your configuration within your home-manager files
3.  Point to neovim config files from home-manager. `xdg.configFile."nvim".source = ./nvim`
4. Open LazyVim and try to install or update plugins 

### Expected Behavior

The `lazy-lock.json` gets created and managed by LazyVim.

**Comment by luxus** [comment]
why u want home-manager setup neovim if you use lazyvim?

**Comment by folke** [comment]
`config.lockfile`

**Comment by Nikola-Milovic** [comment]
I am sorry, but what is the solution in this case? I don't quite get it
