### ISSUE TITLE
bug: Neo tree stop working because of the path separator

### ISSUE THREAD

**Issue by beadinsea** [LazyVim/LazyVim#1749]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

Windows 10

### Describe the bug

On windows 10, the file list is empty when opening neo-tree window with "&lt;leader&gt;e". And the files show when open neo-tree window with "&lt;leader&gt;E".
Maybe it's because the new version of "Util.root.get()" or "Util.root()" returns the path with forward slash separator. And "&lt;leader&gt;E" works because the path separator is backslash returned by "vim.loop.cwd()"

### Steps To Reproduce

On windows 10, open a file in a git repo with neovim, and open an neo-tree window with "&lt;leader&gt;e" shortcut.

### Expected Behavior

To see all the files in the git repo when open the neo-tree file window.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by Olaison** [comment]
I have the same exact issue, also on windows 10 and nvim 0.9.4

**Comment by folke** [comment]
Fixed. Will make a new release later

**Comment by beadinsea** [comment]
Thank very much! Your response is incredibly quick.
LazyVim is amazing!!!
