### ISSUE TITLE
bug: slow rendering/scrolling on sshfs-mounted directory due to lualine's root_dir()

### ISSUE THREAD

**Issue by lkhphuc** [LazyVim/LazyVim#1753]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1361+g0892c1cd9-Homebrew

### Operating system/version

MacOS

### Describe the bug

Kind of a niche, but nvim scrolling is very slow and laggy when run inside a sshfs-mounted directory.

I found a similar issue in Lualine's https://github.com/nvim-lualine/lualine.nvim/issues/715 and disabling lualine does indeed resolve the slowness issue.
In the original issue, the cause was due to the 'branch' component. However, now using the lualine's branch component does not slow anything down for me.

I've found that the culprit is the new LazyVim's root_dir component. More specifically, the `Util.root.get()` function.
Replacing it with a simple cwd component make everything snappy again inside sshfs:
```lua
      opts.sections.lualine_c[1] = {
         function() return " " .. vim.fn.fnamemodify(vim.fn.getcwd(), ":t") end,
         color = { gui = "italic", fg = fg("Special").fg },
         padding = 0,
       }
```

### Steps To Reproduce

1. Mount sshfs folder
2. Cd inside and start nvim
3. Scroll

### Expected Behavior

Scrolling and getting root directory shouldn't be slow even inside sshfs directory.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by neuromaancer** [comment]
I am having the same experience, but I was thinking probably is a network issue, thank you for pointing this out!

**Comment by folke** [comment]
Turns out it was running multiple times per second.
It's all cached now, so will only be re-calculated when a new LSP attaches, or on buffer writes

**Comment by lkhphuc** [comment]
Thank @folke for your fast response.
Unfortunately testing on main's latest commit, it is still laggy inside sshfs when I enable the root_dir component. 
@neuromaancer can you confirm on your case?

**Comment by folke** [comment]
Are you sure you are using the dev version? So with version=false for LazyVim? Didn't make a new release yet

**Comment by neuromaancer** [comment]
I think version 10.4.0 is not released yet.

**Comment by lkhphuc** [comment]
Hmm, nevermind. 
I've tried again on main branch and it's snappy now. Thanks again.

**Comment by neuromaancer** [comment]
Just tested it! Blazing fast now!
