### ISSUE TITLE
bug: LazyExtras cannot disable user extra plugins

### ISSUE THREAD

**Issue by konosubakonoakua** [LazyVim/LazyVim#1754]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10

### Operating system/version

ubuntu 22

### Describe the bug

bug: LazyExtras cannot disable user extra plugins in user config folder `lua/plugins/extras`.
we can see the status of enabled and disabled plugins in LazyExtra TUI, but disabled plugins are not really disabled, they have been loaded as shown in lazy.nvim TUI.

json config & user extras plugins:
[![rQP5W.png](https://i.imgs.ovh/2023/10/16/rQP5W.png)](https://imgloc.com/image/rQP5W)

lazyextra tui:
[![rQCbJ.png](https://i.imgs.ovh/2023/10/16/rQCbJ.png)](https://imgloc.com/image/rQCbJ)

lazy.nvim tui:
[![rQLXv.png](https://i.imgs.ovh/2023/10/16/rQLXv.png)](https://imgloc.com/image/rQLXv)

### Steps To Reproduce

1. add user extras plugins
2. disable them
3. check whether they are loaded actually

### Expected Behavior

user extra plugins remain not loaded or disabled if they are disabled by LazyExtra TUI

**Comment by dpetka2001** [comment]
You still have `{ import = "plugins.extras" },` in your `lua/config/lazy.lua` file. Comment out that line and let `LazyExtras` manage them.
