### ISSUE TITLE
bug: formatting.lua sets formatexpr unconditionally

### ISSUE THREAD

**Issue by agriffis** [LazyVim/LazyVim#1759]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev+1344-g712adacdf

### Operating system/version

Fedora 38

### Describe the bug

Since lazyvim switched to conform, `formatexpr` is set in a way that is hard to override:

https://github.com/LazyVim/LazyVim/blob/fef0b3f7564e64f92df129cd86bc904afc19b976/lua/lazyvim/plugins/formatting.lua#L53

I've tried setting it in `config/options.lua` back to the default `vim.opt.formatexpr = ''` (so that `gq` wraps text rather than calling conform) but the plugin overrides. I also tried various hacks such as

```
  {
    'stevearc/conform.nvim',
    opts = function()
      vim.opt.formatexpr = '' -- LazyVim conform plugin sets this, but we don't want it
    end,
  },
```

but that only works on the second invocation of `gq`, and it's obviously hacky besides.

Seems like this should be an optional setting, but I'm not sure if you'd rather do it in the opts for that plugin, or a different way. Thoughts?

### Steps To Reproduce

1. Load a text file
2. `gql` doesn't wrap lines
3. `:set formatexpr=''`
4. Now `gql` wraps lines

### Expected Behavior

I want `gq` to work the normal vim way, instead of calling `conform`

### Repro

```Lua
Actually struggling with the minimal repro. Will update when I have that working
```

**Comment by agriffis** [comment]
Here's the workaround I'm using for the moment:

```
  {
    'stevearc/conform.nvim',
    init = function()
      Formatting[1].init() -- call the original init func
      vim.opt.formatexpr = '' -- reset formatexpr
    end,
  },
```

**Comment by folke** [comment]
You can now override it in `options.lua`

**Comment by agriffis** [comment]
Thank you!
