### ISSUE TITLE
docs: Copilot extra documentation is missing nvim-cmp config 

### ISSUE THREAD

**Issue by SFToro** [LazyVim/LazyVim#1769]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.2

### Operating system/version

Mint 21.2

### Describe the bug

I was checking the copilot extra config because I have my own config of lualine, and importing the extra "breaks" it.

In the [docs](https://www.lazyvim.org/extras/coding/copilot) full spec says  "zbirenbaum/copilot.lua" and "zbirenbaum/copilot-cmp" should be configured. 

Checking the source code of the extra, it is "nvim-cmp" which should be configured, with "zbirenbaum/copilot-cmp" as dependency:

```lua
{
    "nvim-cmp",
    dependencies = {
      {
        "zbirenbaum/copilot-cmp",
        dependencies = "copilot.lua",
        opts = {},
        config = function(_, opts)
          local copilot_cmp = require("copilot_cmp")
          copilot_cmp.setup(opts)
          -- attach cmp source whenever copilot attaches
          -- fixes lazy-loading issues with the copilot cmp source
          require("lazyvim.util").lsp.on_attach(function(client)
            if client.name == "copilot" then
              copilot_cmp._on_insert_enter({})
            end
          end)
        end,
      },
    },
    ---@param opts cmp.ConfigSchema
    opts = function(_, opts)
      table.insert(opts.sources, 1, {
        name = "copilot",
        group_index = 1,
        priority = 100,
      })
    end,
  },
}
```

### Steps To Reproduce

1. Copy the full spec in the docs
2. Copilot does not show suggestions in nvim-cmp

### Expected Behavior

To copy  the full spec of the docs and get copilot working
```lua
return {
{
  "zbirenbaum/copilot.lua",
  cmd = "Copilot",
  build = ":Copilot auth",
  opts = {
    suggestion = { enabled = false },
    panel = { enabled = false },
    filetypes = {
      markdown = true,
      help = true,
    },
  },
},
{
  "zbirenbaum/copilot-cmp",
  dependencies = "copilot.lua",
  opts = {},
  config = function(_, opts)
    local copilot_cmp = require("copilot_cmp")
    copilot_cmp.setup(opts)
    -- attach cmp source whenever copilot attaches
    -- fixes lazy-loading issues with the copilot cmp source
    require("lazyvim.util").lsp.on_attach(function(client)
      if client.name == "copilot" then
        copilot_cmp._on_insert_enter({})
      end
    end)
  end,
}
}

**Comment by folke** [comment]
You should never copy the full spec. There's a big warning on top that literally says that is just shows the options as a reference.

Either way, I will check why nvim-cmp is not included in the doc for the extra. Those docs are auto generated, so there's probably a bug in there.

I'll also add a link to the full source on GitHub for every extra.

**Comment by folke** [comment]
I fixed the doc-gen in the meantime, and the new docs are live!
