### ISSUE TITLE
bug: show nvim-lspconfig.opts.autoformat is deprecated. Please use vim.g.autoformat instead for neovim 0.9.4

### ISSUE THREAD

**Issue by marsjane** [LazyVim/LazyVim#1781]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

MacOS 14.0

### Describe the bug

after upgrade neovim to 0.9.4 and update all lazyvim & plugin, each time I open a file it will show
```
  nvim-lspconfig.opts.autoformat is deprecated. Please use vim.g.autoformat instead
   # stacktrace:
   	 - /LazyVim/lua/lazyvim/util/plugin.lua:91 in ****
   	 - vim/_editor.lua:0
```

### Steps To Reproduce

update neovim use brew to 0.9.4
use macos 14.0 (not sure about this), think should not be related
open a file

### Expected Behavior

show message
```
  nvim-lspconfig.opts.autoformat is deprecated. Please use vim.g.autoformat instead
   # stacktrace:
   	 - /LazyVim/lua/lazyvim/util/plugin.lua:91 in ****
   	 - vim/_editor.lua:0
```

**Comment by folke** [comment]
It literally tells you what option is deprecated and how to fix it.
https://www.lazyvim.org/configuration/general#options

**Comment by marsjane** [comment]
but I checked the `~/.local/share/nvim/lazy/LazyVim/lua/lazyvim/config/options.lua` it do use the `vim.g.autoformat = true`
and there is no any setting in my own config/options.lua, just
```
-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here
local opt = vim.opt

opt.relativenumber = false
opt.wrap = true

-- set filetype
vim.api.nvim_create_autocmd({"BufRead","BufNewFile"}, {
  pattern = {"*.ft"},
  command = "set filetype=ruby",
})
```
 a bit confused, any suggestions?

**Comment by marsjane** [comment]
oh sorry I found the reason, I used this config in the plugins 
```
cat plugins/lspconfig.lua                                                                                                                                                                                                   23s 15:50:10
return {
  {
    "neovim/nvim-lspconfig",
    opts = {
      autoformat = false,
    },
  },
}
```

**Comment by Emile-Durkheim** [comment]
Having the same issue. There is no string by the name of "autoformat" in any of the options.lua, lazy.lua or plugin.lua. Setting vim.g.autoformat = true in options.lua also doesn't fix the issue.

**Comment by dpetka2001** [comment]
You have somewhere in your personal configuration something like
```lua
{
  "neovim/nvim-lspconfig",
  opts = {
    autoformat = something,
  },
}
```
You have to search throughout your configuration where such a code snippet exists and remove it.
