### ISSUE TITLE
bug: nvim-ts-autotag does not work for xml or html files.

### ISSUE THREAD

**Issue by 231tr0n** [LazyVim/LazyVim#1795]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

Archlinux

### Describe the bug

Auto closing tags does not work in any html or xml files by default which was supposed to be the default behaviour. Can you please help me figure out how to get auto closing tags working.

### Steps To Reproduce

I just installed the latest starter config of lazyvim and since it is version 10 and above, auto tag closing should be enabled by default. But I was not able to see this feature of auto tag closing work. I also tried creating a custom plugin config under the lua/plugin directory with the config mentioned but still could not get it work.

### Expected Behavior

Auto tag closing should work by default

**Comment by dpetka2001** [comment]
Strange, I just tested with a fresh starter template and opened an `.html` file and when I typed `<div>` it closed automatically with `</div>`. I also renamed `<div>` to `<span>` and the closing `</div>` got renamed to closing `</span>` automatically. Did you make any changes to the default configuration? Also you shouldn't copy the default config to `lua/plugins`. You should only do so, when you want to change the default behavior of a plugin with the necessary `opts`.

**Comment by folke** [comment]
You need to have the respective treesitter parsers installed for ts-autotag to work
