### ISSUE TITLE
bug: Icon size inconsistency

### ISSUE THREAD

**Issue by a1401358759** [LazyVim/LazyVim#1803]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1f551e0

### Operating system/version

archlinux 6.5.5-arch1-1 x86_64 GNU/Linux

### Describe the bug

![image](https://github.com/LazyVim/LazyVim/assets/15830146/cafe3045-0398-4b3e-a891-c866b144aba6)

### Steps To Reproduce

see desc

### Expected Behavior

see desc

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
Do you have nerdfonts installed?

**Comment by folke** [comment]
You're missing proper fonts indeed

**Comment by a1401358759** [comment]
![image](https://github.com/LazyVim/LazyVim/assets/15830146/56da646c-ffbf-496c-8f6f-95881ce87ffe)

Sorry, maybe I didn't describe my problem clearly, what I meant to say was that the icons are not the same size，I use jetbrains mono font, they are good on NvChad and AstroNvim!

**Comment by a1401358759** [comment]
![image](https://github.com/LazyVim/LazyVim/assets/15830146/62d6dd1d-126c-4b9c-ba9a-766a8a531b8a)

**Comment by folke** [comment]
Still font/terminal issue. I don't have that problem
