### ISSUE TITLE
bug: Conform formatting sporadic errors

### ISSUE THREAD

**Issue by Balssh** [LazyVim/LazyVim#1806]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

Arch

### Describe the bug

Sometimes when I try to format a file Conform would throw and error:
![image](https://github.com/LazyVim/LazyVim/assets/82440615/343e22b8-1b36-4397-b737-991f7d668828)
I've seen this happen both on my personal laptop (Arch) and work laptop (WSL Ubuntu). I double checked and LSP seems to be attached. Anyone else having problem with formatting?

### Steps To Reproduce

Try to format a file, only happens sporadically.

### Expected Behavior

Execute format correctly.

### Repro

```Lua
Default formatting settings of LazyVim
```

**Comment by dpetka2001** [comment]
I have also experienced this, but it really happens sporadically. Not able to reproduce in a constant way.

**Comment by folke** [comment]
I've seen this as well. It think it's related to lazy.nvim. 
I don't see how that error can happen, and it rarely happens. Super weird.

Will keep investigating.

**Comment by folke** [comment]
I made some changed to the way we pass formatting options, and that possibly fixes it.

If you'd see the error again, let me know!
