### ISSUE TITLE
feature: put a simple sample in ~/.nvim/lua/config/keymaps.lua

### ISSUE THREAD

**Issue by dlintw** [LazyVim/LazyVim#1812]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

It is hard to figure out how to add new hot key.

### Describe the solution you'd like

append some lines like this
```
-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set:  https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
local map = vim.keymap.set
map("n", "<Leader>ch", ":ClangdSwitchSourceHeader<CR>", { noremap = true, desc=" swtich between source and header file"})  -- equal to https://vimawesome.com/plugin/a-vim
-- Add any additional keymaps here, ref: help vim.keymap.set and  folke/which-key.nvim plugin
```

### Describe alternatives you've considered

As a beginner, I guess simple quick jump description is much easier than read all plugins document.

**Comment by ogios** [comment]
there's a documentation for keymap.lua, and you can also check it in [here](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua)

**Comment by dlintw** [comment]
In my opinion, for those people who used vim, In vim, only one line can assign a key or remove a key.
So, just require a simple line example for add key. and a simple line example to delete default key.
Instead of read the complex default setup. In fact,  In this case, it is not a suggest way to copy & paste the default setup and modify it.

**Comment by dlintw** [comment]
> edit: [this](https://github.com/ogios/nvim-config/blob/lazyvim/lua/config/keymaps.lua) is how i setup my keymap

Why use so complex settings? Any benefit?  In fact, I can not easy understand what's your config doing.  After read 'pair' document of lua. I understood.  But, I still prefer to use 6 lines of delete key instead of declare an array , use code to iterate the array to delete key.  Like what I did in Vim configuration.

**Comment by dpetka2001** [comment]
In [keymaps docs](https://www.lazyvim.org/configuration/general#keymaps) under default keymaps, you can find all Lazyvim's default keymaps. It even has a warning about not using the `map` function that Lazyvim uses internally, but use `vim.keymap.set` instead. And in [keymaps](https://www.lazyvim.org/configuration/keymaps#global-keymaps) it tells you that to delete the default Lazyvim keymaps you should use `vim.keymap.del`. It's up to the user to read how to use these 2 functions to add and delete keymaps.
