### ISSUE TITLE
bug: icons are not the same size

### ISSUE THREAD

**Issue by a1401358759** [LazyVim/LazyVim#1814]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1f551e0

### Operating system/version

archlinux 6.5.5-arch1-1 x86_64 GNU/Linux

### Describe the bug

![image](https://github.com/LazyVim/LazyVim/assets/15830146/edc85295-cea1-406c-8175-11f822abc165)

Sorry, maybe I didn't describe my problem clearly, what I meant to say was that the icons are not the same size，I use jetbrains mono font, they are good on NvChad and AstroNvim!

![image](https://github.com/LazyVim/LazyVim/assets/15830146/6f658d90-18dd-4a53-906a-8c30ca05bd6c)

### Steps To Reproduce

see description

### Expected Behavior

see description

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
That;s your terminal. I don't have that issue.
