### ISSUE TITLE
bug: adding `desc =` to a user extras causes error

### ISSUE THREAD

**Issue by Jomik** [LazyVim/LazyVim#1818]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1290 5db076c7c-Homebrew

### Operating system/version

macOS 13.1

### Describe the bug

   Error  13:04:32 notify.error lazy.nvim Failed to load `plugins.extras.util.neovim-project`

...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/plugin.lua:67: attempt to call method 'find' (a nil value)

# stacktrace:
  - ~/.config/nvim/lua/config/lazy.lua:9
  - ~/.config/nvim/init.lua:2

### Steps To Reproduce

1. Create extras with a description
```lua
---@type LazyPluginSpec[]
return {
  desc = "Neovim project plugin simplifies project management",
  {
    "coffebar/neovim-project",
    opts = {
      projects = { -- define project roots
        "~/projects/*",
        "~/.config/*",
      },
    },
    init = function()
      -- enable saving the state of plugins in the session
      vim.opt.sessionoptions:append("globals") -- save global variables that start with an uppercase letter and contain at least one lowercase letter.
    end,
    dependencies = {
      { "nvim-lua/plenary.nvim" },
      { "nvim-telescope/telescope.nvim" },
      { "Shatur/neovim-session-manager" },
    },
    lazy = false,
    priority = 100,
  },
}
```
3. Enable it
4. Reload neovim

### Expected Behavior

It should work.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
That's a hidden feature, but lazy can be too picky in parsing specs.

To fix it, return just a spec with desc instead of a list of specs.

If you'd have more than one spec in the return list, it would have worked the way you did it.
