### ISSUE TITLE
bug: Duplicate inline diagnostics with default python extras settings

### ISSUE THREAD

**Issue by j-woolfe** [LazyVim/LazyVim#1819]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

EndeavourOS Linux x86_64

### Describe the bug

When using the Python lang extras, both Ruff-lsp and pyright errors appear in the inline diagnostics.

![image](https://github.com/LazyVim/LazyVim/assets/43143052/8b8e00d1-5290-4b6e-9c7c-609d8abdba58)

### Steps To Reproduce

1. Install python language features with `:LazyExtras`

### Expected Behavior

Displaying both of these diagnostic sources seems unnecessary as a default.

I see in the default settings that hover uses pyright over ruff so maybe something similar could be used here?

**Comment by j-woolfe** [comment]
Fair enough, I'll have a look into it. Thanks for the quick response :)

**Comment by ibeex** [comment]
@j-woolfe did you manage to fix this I tried with comment options but can't get both suppressed!?

**Comment by horta** [comment]
This solved for me: https://github.com/astral-sh/ruff-lsp/issues/384#issuecomment-1941556771

My full config:


```
  {
    "neovim/nvim-lspconfig",
    opts = {
      servers = {
        pyright = {
          settings = {
            pyright = {
              disableOrganizeImports = true, -- Using Ruff
            },
            python = {
              analysis = {
                ignore = { '*' }, -- Using Ruff
                typeCheckingMode = 'off', -- Using mypy
              },
            },
          },
        },
        ruff_lsp = {
          keys = {
            {
              "<leader>co",
              function()
                vim.lsp.buf.code_action({
                  apply = true,
                  context = {
                    only = { "source.organizeImports" },
                    diagnostics = {},
                  },
                })
              end,
              desc = "Organize Imports",
            },
          },
        },
      },
      setup = {
        ruff_lsp = function()
          require("lazyvim.util").lsp.on_attach(function(client, _)
            if client.name == "ruff_lsp" then
              -- Disable hover in favor of Pyright
              client.server_capabilities.hoverProvider = false
            end
          end)
        end,
      },
    },
  },
```
