### ISSUE TITLE
feature: Make TypeScript keymaps customizable

### ISSUE THREAD

**Issue by LandonSchropp** [LazyVim/LazyVim#182]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Currently, the TypeScript keymaps are [hardcoded](https://github.com/LazyVim/LazyVim/blob/65fb26fe9726eede3f3c2f0067b87f91cf302940/lua/lazyvim/plugins/extras/lang/typescript.lua#L27-L28) in `plugins.extra.lang.typescript`.

### Describe the solution you'd like

It would be great if this config could use `keys` so these keymaps were easily customizable.

### Describe alternatives you've considered

I've considered overriding the config myself, but it doesn't seem worth it.

### Additional context

Thanks for all the great plugins!

**Comment by folke** [comment]
Would be best to just override the whole function. Just copy the tsserver function part and customize the keymaps to your liking.

IT's only 9 lines of code. Not worth it to make that configurable in another way

**Comment by folke** [comment]
you can't use `keys` in this case, since those keymaps are buffer-local and only for buffers where tsserver is attached. I dont think it's needed to make them configurable. But if you want you can as I mentioned

**Comment by LandonSchropp** [comment]
Gotcha, thanks.
