### ISSUE TITLE
bug: telecope-fzf-native fails to build and causes telescope errors

### ISSUE THREAD

**Issue by kylelaker** [LazyVim/LazyVim#1820]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev-1385+gf4b896198f

### Operating system/version

Arch Linux

### Describe the bug

When LazyVim is doing the initial plugin setup, `telescope-fzf-native` fails with the error:

```
    ● telescope-fzf-native.nvim 0.07ms ✔ build
        make: *** No targets specified and no makefile found.  Stop.
```

(Notably, `LuaSnip` reports a similar error for `install_jsregexp`)

Then, using any `Telescope` commands results in the following errors:

```
Error executing lua callback: ...lugins/telescope.nvim/lua/telescope/_extensions/init.lua:10: 'fzf' extension doesn't exist or isn't installed: ....repro/plugins/telescope-fzf-native.nvim/lua/fzf_lib.lua:11: /home/kyle/Documents/lazy-repro/.repro/plugins/telescope-fzf-native.nvim/lua/../build/libfzf.so: cannot open shared object file: No such file or directory
stack traceback:
	[C]: in function 'error'
	...lugins/telescope.nvim/lua/telescope/_extensions/init.lua:10: in function 'load_extension'
	...lugins/telescope.nvim/lua/telescope/_extensions/init.lua:62: in function 'load_extension'
	...ro/.repro/plugins/LazyVim/lua/lazyvim/plugins/editor.lua:124: in function 'fn'
	...y-repro/.repro/plugins/LazyVim/lua/lazyvim/util/init.lua:138: in function <...y-repro/.repro/plugins/LazyVim/lua/lazyvim/util/init.lua:136>
	[C]: in function 'nvim_exec_autocmds'
	...-repro/.repro/plugins/lazy.nvim/lua/lazy/core/loader.lua:347: in function <...-repro/.repro/plugins/lazy.nvim/lua/lazy/core/loader.lua:346>
```

If I go into the `telescope-fzf-native.nvim` folder and run `make` then the errors go away.

### Steps To Reproduce

1. Use the repro file below
2. Wait for LazyVim to finish the initial plugin setup, note the `telescope-fzf-native` error
3. Try to run a Telescope command (such as `:Telescope find_files`), note that any attempt to tab complete also results in the errors appearing

### Expected Behavior

The plugin should successfully build (I do have `make` and other tools installed, tree sitter can build its parsers happily). If it does not successfully build, telescope should still work.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  -- add any other plugins here
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by kylelaker** [comment]
Investigating this more, my shell is `zsh`. If I specifically set `vim.env.SHELL` to `/usr/bin/bash` in the repro before the plugin install, then this doesn't happen (and both `telescope-fzf-native.nvim` and `LuaSnip` build successfully).

**Comment by ggteixeira** [comment]
@kylelaker,

**Comment by kylelaker** [comment]
> Hey @kylelaker, how did you fix that zsh/bash issue? I'm facing the same problem on my machine :/

My issue, it turns out, is a bug in ZSH itself. I am using `systemd-homed` with a `btrfs` subvolume for my home directory. In ZSH 5.9 and older this has a bug.

Adding `vim.env.SHELL = "/bin/bash"` to `lua/config/lazy.lua` before the call to `require("lazy").setup()` fixed it for me (at least until the next version of ZSH comes out).

**Comment by ggteixeira** [comment]
Thank you, @kylelaker. I've found out that my error was due to some missing packges like `gcc`.

**Comment by XantreGodlike** [comment]
I had the same issue, all requirements was satisfied, only thing that helped - is to delete `nvim-data`
```bash
rm $env:LOCALAPPDATA\nvim-data -r
```
