### ISSUE TITLE
How do you fix this?

### ISSUE THREAD

**Issue by dpetka2001** [LazyVim/LazyVim#1822]
How do you fix this?

![CleanShot 2023-10-20 at 12 02 37@2x](https://github.com/LazyVim/LazyVim/assets/1625373/46086683-294f-44aa-ada5-199130cd2447)

In the screenshot you can see the symbols of markdown headlines not rendering properly

_Originally posted by @kapral18 in https://github.com/LazyVim/LazyVim/discussions/1816_

**Comment by rghvdberg** [comment]
You need to define the highlights for headlines.

Checkout docs for headlines.nvim and https://neovim.io/doc/user/syntax.html#%3Ahighlight

**Comment by dpetka2001** [comment]
This is done in the extra itself [here](https://github.com/LazyVim/LazyVim/blob/fa3170d422f3c661d0411472c96f92e5324dc281/lua/lazyvim/plugins/extras/lang/markdown.lua#L71-L73)
