### ISSUE TITLE
bug: Rust setup may be incomplete

### ISSUE THREAD

**Issue by Balssh** [LazyVim/LazyVim#1829]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

Arch

### Describe the bug

I installed the Rust and DAP core extras from LazyVim but seems like K hovering doesn't work unless I'm on a crate with the cursor (for example K on `println` doesn't do anything). Also when trying to run dap inside Rust project it just throws an error:
![image](https://github.com/LazyVim/LazyVim/assets/82440615/7ddc0237-feb7-4703-aaea-dc395ffcb98e)
I have installed lldb in my system.
Does this happen to anyone else? I couldn't find something related to these 2 problems and I wonder if it's from LazyVim setup or from rust-tools.

### Steps To Reproduce

Install the extras.lang.rust extras.dap.cor packages in lazyvim
Try to hover things/run dap.

### Expected Behavior

Hovering on function to open something like lsp hover.
Being able to debug rust files.

**Comment by lazymaniac** [comment]
It works fine for me. Do you have codelldb installed by Mason? Rust config is looking for codelldb in Mason directory. What :checkhealth shows?

**Comment by folke** [comment]
Closing since we now use rustaceanvim
