### ISSUE TITLE
bug: Using everything out of the box, Rust DAP immediately quits.

### ISSUE THREAD

**Issue by KitchenTable99** [LazyVim/LazyVim#1835]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0

### Operating system/version

MacOS 14.0

### Describe the bug

The Rust DAP does not run. Even if I use a completely blank install of LazyVim and only enable the DAP core and Rust lang extras, running something will immediately terminate the process.

It's worth noting that installing the Python lang extra and the DAP core extra allows the Python DAP to work just fine.

### Steps To Reproduce

1. Grab fresh installation of LazyVim
2. Enable DAP Core in the lazy.nvim file (haven't tried using the Extras manager, but I imagine that would also lead to the bug)
3. Enable the Rust lang extra in the same way
4. Open any Rust program (a default `cargo new foo` would be fine)
5. Place a breakpoint anywhere
6. Run the DAP using <leader>dr and selecting the first option

### Expected Behavior

You will receive a Notify alert stating: "Compiling a debug build for debugging. This might take some time..." Then the DAP will briefly flicker on screen before quitting. I've attached a screenshot of the UI after I bring it back up.
<img width="1440" alt="Screenshot 2023-10-21 at 10 33 34 PM" src="https://github.com/LazyVim/LazyVim/assets/67441762/e941d038-b22f-44d5-a760-12661cc12d1c">

**Comment by ogios** [comment]
sorry to ask a non related question, what is it at the bottom line? seems like multiple tabs, is it a nvim plugin or terminal?

**Comment by KitchenTable99** [comment]
The bottom line is from tmux

**Comment by KitchenTable99** [comment]
Additionally, nvim-dap generates no log messages (though it will create the log file) when running for Rust. The Python logs show up just fine.

**Comment by ratbag98** [comment]
Using lazy as a package manager, but otherwise my own config, I get the same results.

**Comment by borneygit** [comment]
I'm having the same problem.

**Comment by keaz** [comment]
Does anyone find a solution for this?

**Comment by keaz** [comment]
for now, delete the `~/.local/share/nvim/mason/packages/codelldb/extension/lldb/bin/debugserver`

**Comment by bmikaili** [comment]
I have the same issue but with Java

**Comment by folke** [comment]
Closing since we now use rustaceanvim

**Comment by squeaktoy** [comment]
Even with rustaceanvim, this continues to be a problem

**Comment by twilwa** [comment]
Seconded, DAP immediately crashes in Rust files.
