### ISSUE TITLE
bug: util.dot extra doesn't seem to do anything

### ISSUE THREAD

**Issue by dotfrag** [LazyVim/LazyVim#1838]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.4

### Operating system/version

Linux

### Describe the bug

Enabling the extra `util.dot` and restarting seems to have no effect on setting the filetype for config files.

### Steps To Reproduce

1. Enable util.dot extra
2. Close nvim
3. `nvim ~/.config/waybar/config` or `nvim ~/.config/kitty/kitty.conf`
4. Filetype is unset (empty).

### Expected Behavior

I expect the filetype to be set for these files, as they are defined in `lua/lazyvim/plugins/extras/util/dot.lua`:

```lua
...
      vim.filetype.add({
        extension = { rasi = "rasi" },
        pattern = {
          [".*/waybar/config"] = "jsonc",
          [".*/mako/config"] = "dosini",
          [".*/kitty/*.conf"] = "bash",
        },
      })
...
```

Unless I'm misunderstanding what the config does..

**Comment by dpetka2001** [comment]
I only have `kitty` to test with this extra, but when I enabled it, it correctly changed the filetype of `kitty.conf` to `bash`.

**Comment by dotfrag** [comment]
Does it matter where you open the file from or if it is a symlink?

**Comment by dpetka2001** [comment]
Only tested with regural file in `~/.config/kitty/kitty.conf`.

**Comment by dotfrag** [comment]
Can you test if this is working for you?

```shell
cd /tmp
mkdir kitty
touch kitty/kitty.conf
nvim kitty/kitty.conf
```

and `:set ft?`

**Comment by dpetka2001** [comment]
Yes, it's still set to `bash`.

**Comment by dotfrag** [comment]
It's not working here, no idea how to debug it more. Thank you for checking anyway.

**Comment by dpetka2001** [comment]
![2023-10-22_13-10](https://github.com/LazyVim/LazyVim/assets/12776461/b81ffbc7-9473-4da5-aebb-0d8704b733b7)

**Comment by dpetka2001** [comment]
Unfortunately, I don't have any idea what's wrong with your system. But it for sure doesn't seem to be Lazyvim related. Something else must be going on on your end.

**Comment by folke** [comment]
Probably your Neovim version. Try with nightly

**Comment by madjxatw** [comment]
@dotfrag, I encountered the same issue when I enabled `dot` yesterday. The difference between what you posted and that from @dpetka2001 is that you attempted to open a file using nvim from the shell command line while @dpetka2001 opened a file from inside an already started (fully configured) nvim instance. I suspect that nvim has not got all the setups done for remapping the filetype when you do `nvim <some-file>` to open a file.

**Comment by dotfrag** [comment]
Sorry I haven't noticed the messages.

> Probably your Neovim version. Try with nightly

@folke tried on a few machines, both with stable and nightly, same behaviour.

@madjxatw you are right, if I open nvim, then open a random file, then finally `:e ~/.config/kitty/kitty.conf`, the `dot` extra appears to work.  That's probably related to plugin loading.

It also works when you `nvim ~/.config/kitty/kitty.conf`, then `:e<cr>`.
