### ISSUE TITLE
feature: Change default behaviour of html tag indentation when pressing enter using using nvim-ts-autotag

### ISSUE THREAD

**Issue by 231tr0n** [LazyVim/LazyVim#1840]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Currently lazyvim is closing tags properly but the issue is that if I hit enter after tag completition it becomes something like this:-
```
<html>|</html>
```
Hit enter then it becomes
```
<html>
|</html>
```
To make it become something like below i have to add additional config as suggested by @dpetka2001 in discussion https://github.com/LazyVim/LazyVim/discussions/1832 to my plugins config
```
<html>
  |
</html>
```

```lua
return {
    "hrsh7th/nvim-cmp",
    dependencies = {
      { "windwp/nvim-autopairs", opts = {} },
    },
    opts = function()
      local cmp = require("cmp")
      local cmp_autopairs = require("nvim-autopairs.completion.cmp")

      -- Insert parentheses after selecting method/function
      cmp.event:on("confirm_done", cmp_autopairs.on_confirm_done())
    end,
  }
```

### Describe the solution you'd like

Can this config which I have to additionally add be included in lazyvim by default. Because the default behaviour of tags when enter is pressed makes it tought cause i have to go back to normal mode and press O again.

### Describe alternatives you've considered

None

**Comment by dpetka2001** [comment]
As I mentioned in the discussion thread, I believe it would be more appropriate to open an issue either at `nvim-cmp`'s or `nvim-ts-autotag`'s repo to take care of this. It really isn't a Lazyvim issue I believe.
