### ISSUE TITLE
bug: treesitter foldexpr causes massive slowdown in toggleterm w/ large history

### ISSUE THREAD

**Issue by amaanq** [LazyVim/LazyVim#1846]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev-1397+g40574b424-dirty

### Operating system/version

Arch Linux 6.5.8-zen1-1-zen

### Describe the bug

When using toggleterm (or maybe any term?) which has a lot of scrollback history, the treesitter foldexpr causes slowness. Disabling it/changing it back completely gets rid of the slowness -  It seems to be because it always tries to create/load a parser every time the terminal is opened, which it shouldn't. I was able to confirm this using perfanno.nvim (amazing plugin, recommend checking it out for debugging slowness..), but I'm unsure about what the fix should be (early return based on buftype upstream if it's a terminal or nofile? or use a wrapper to check in LazyVim?), so sorry if it was a mistake to report it here :^)

### Steps To Reproduce

1. Use toggleterm.nvim
2. Open a terminal
3. Make sure your terminal can scrollback thousands of lines - otherwise a low number makes this useless, mine is set to 500,000 in kitty
4. Populate your terminal with ~2-10k lines depending on your machine, you can do this by running `awk -v v=2000 'BEGIN{for(i=1;i<=v;i++)print "whatever "i}'` a few times
5. Toggle the terminal so it closes (but doesn't quit), then open it again. Opening should hang, and take a few seconds. 
6. PerfAnno profiling info when recording the terminal opening:

![image](https://github.com/LazyVim/LazyVim/assets/29718261/ea450abb-4882-48e9-aad6-d92897d30fd2)

### Expected Behavior

No lag when the terminal contains thousands of lines of history/scrollback

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  {
    "akinsho/toggleterm.nvim",
    init = function()
      vim.keymap.set("t", "<ESC>", "<C-\\><C-n>", { noremap = true, silent = true })
    end,
    opts = {},
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here

vim.opt.foldmethod = "expr"
vim.opt.foldexpr = "v:lua.vim.treesitter.foldexpr()"
```

**Comment by folke** [comment]
That's indeed a pretty bad experience.

I just added a wrapper that checks if a given buffer has treesitter at most once per tick.
After each even loop tick, the cache is cleared. (needed since new queries may have been added to the rtp).

Additionally, I also return `"0"` for `buftype ~= ""`.

**Comment by amaanq** [comment]
Thank you!!
