### ISSUE TITLE
bug: dashboard - remove unnecessary brackets from keys 

### ISSUE THREAD

**Issue by msMatix** [LazyVim/LazyVim#1860]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.2

### Operating system/version

Linux - Manjaro

### Describe the bug

When using the extra plugin: `extra.util.project` you forgot to remove the brackets around the keys in the dashboard. 

### Steps To Reproduce

1. Enable extras.util.project
2. restart nvim
3. brackets around the key for the project are visible

### Expected Behavior

Brackets should not be visible similar to the other key commands

**Comment by dpetka2001** [comment]
This has been fixed. Update Lazyvim.

**Comment by msMatix** [comment]
I am already using the newest version of LazyVim: 10.5.0

**Comment by dpetka2001** [comment]
I'm guessing it's not in the latest release yet. But it has been merged into `main`, so if you follow Lazyvim dev branch you should be able to see the change.
