### ISSUE TITLE
bug: Strange behaviour of search in case input some characters

### ISSUE THREAD

**Issue by pkropachev** [LazyVim/LazyVim#1862]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4 Release

### Operating system/version

Ubuntu 20.04

### Describe the bug

I faced with strange behaviour of search in case input sequence of characters.
I have C++ file. I start search by input `/` character. Then I input word `test` or `show` - all is ok. But during attempt input `create` word, nvim exists from search mode after input `r` letter. The same problem in case attemp to input `aa` - search is closed after input second `a` character.
In my case problem is reproduced with default LazyVim configuration. Not sure that problem is related with LazyVim, perhaps it's related with some plugin.

### Steps To Reproduce

1. Open some file with code in nvim.
2. Try to search something by input `create`, `search`, `aa` words.

### Expected Behavior

Search works independ input characters.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by pkropachev** [comment]
Yes, both suggestions are worked for me. Thanks!

**Comment by gravis** [comment]
I have the same issue, and https://github.com/LazyVim/LazyVim/issues/1862#issuecomment-1775594272 fixed it :+1:
