### ISSUE TITLE
bug: can not disable mason install  automatically

### ISSUE THREAD

**Issue by pzzxqj** [LazyVim/LazyVim#1865]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

openSUSE Tumbleweed

### Describe the bug

Can not disable mason install lua_ls  automatically by configure nvim-lspconfig.

### Steps To Reproduce

use `repro.lua` and nvim -u repro.lua

### Expected Behavior

Don't install automatically.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	"folke/tokyonight.nvim",
	-- "LazyVim/LazyVim",
	{ "LazyVim/LazyVim", import = "lazyvim.plugins" },
	{
		"neovim/nvim-lspconfig",
		servers = {
			lua_ls = {
				mason = false,
			},
		},
	},
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
servers-> opts.servers.

Please use github discussions for user questions. you can assume that things like that obviously work in LazyVim given the user base
