### ISSUE TITLE
feature: allow to disable highlight on yank

### ISSUE THREAD

**Issue by rudenkornk** [LazyVim/LazyVim#1875]
### Did you check the docs?

- [x] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Currently LazyVim [has non-switchable highlight on yank](https://github.com/LazyVim/LazyVim/blob/09eafc60eff2ba7d7b78c1717d07ce26b762a8a8/lua/lazyvim/config/autocmds.lua#L14), which is painfully slow and annoying on my WSL2 setup.

### Describe the solution you'd like

Disable autocmd completely, use [standard settings in the yanky plugin](https://github.com/gbprod/yanky.nvim/blob/c1211c6c6d983a72c74dde44df8575a64d50562f/README.md?plain=1#L90) itself.

### Describe alternatives you've considered

I tried to disable it with `vim.api.nvim_del_augroup_by_name("highlight_yank")`, but that did not work.  
I get error `/home/rudenkornk/.config/nvim/lua/config/autocmds.lua:10: Vim:E367: No such group: "highlight_yank"`

**Comment by folke** [comment]
Please use discussions next time for user questions.

https://github.com/LazyVim/LazyVim/blob/09eafc60eff2ba7d7b78c1717d07ce26b762a8a8/lua/lazyvim/config/autocmds.lua#L4

The group is `lazyvim_highlight_yank`

I'm also pretty sure it's not the highligtting that is causing the slow-down, but executing the actual clipboard program by Neovim

**Comment by rudenkornk** [comment]
Wow, thanks!
