### ISSUE TITLE
bug: Cannot disable Lazyvim keymaps

### ISSUE THREAD

**Issue by krisgry** [LazyVim/LazyVim#1886]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

nneovim-0.10.0~ubuntu1+git202308301604-bec13cfca-9b397864c

### Operating system/version

Ubuntu 22.04

### Describe the bug

Disabling some of the default Lazyvim keymaps (defined in `lua/lazyvim/config/keymaps.lua`) seemingly has no effect.

Here is my `~/.config/nvim/lua/plugins/lazyvim.lua`

```
return {
  {
    "LazyVim/LazyVim",
    keys = {
      { "<leader>ww", vim.NIL },
      { "<leader>wd", vim.NIL },
      { "<leader>w-", vim.NIL },
      { "<leader>w|", vim.NIL },
      { "<leader>-", vim.NIL },
      { "<leader>|", vim.NIL },
    },
    import = "lazyvim.plugins.core",
    opts = {
      defaults = {
        autocmds = true,
        keymaps = true,
      },
    },
}
}
```
I've also tried with `false` instead of `vim.NIL` (according to [lazyvim docs](https://www.lazyvim.org/configuration/plugins#%EF%B8%8F-adding--disabling-plugin-keymaps), and I've seen #63 

My current workaround is to disable all the keymaps (opts.defaults.keymaps = false), and then copy the ones I like into my config, but that is fragile.

Thanks for the efforts you are making btw! :smi

### Steps To Reproduce

Attempted a `repro.lua` init file, see below. But I'm not very fluent in lua, so I did not know how to "include" my `lua/plugins/lazyvim.lua`. Instead I added the relevant key map settings directly to the repro.lua file.

Steps:

1. `nvim -u repro.lua`
2. Press <leader>w
3. The disabled mappings (ww,wd,w-.w|) show up on the screen, and are fully functional

### Expected Behavior

After setting the keys to `false`/`vim.NIL` the mapping should be disabled, they should not show up in which-key, and they should be possible to override by other plugins.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

require("lazy").setup({
  spec = {
    -- add LazyVim and import its plugins
    "folke/tokyonight.nvim",
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- import any extras modules here
    {"LazyVim/LazyVim",
      keys = {
        { "<leader>ww", vim.NIL, mode = {"n"}},
        { "<leader>wd", false },
        { "<leader>w-", vim.NIL },
        { "<leader>w|", vim.NIL },
        { "<leader>-", vim.NIL },
        { "<leader>|", vim.NIL },
      },
    },
  },
})

vim.cmd.colorscheme("tokyonight")
```

**Comment by dpetka2001** [comment]
> Disabling some of the default Lazyvim keymaps (defined in lua/lazyvim/config/keymaps.lua) seemingly has no effect.

You would have to disable those in your `~/.config/nvim/lua/config/keymaps.lua`.

**Comment by folke** [comment]
Those keymaps are not defined ont he LazyVim plugin.
https://www.lazyvim.org/configuration/keymaps

**Comment by krisgry** [comment]
Thanks for the quick replies! 
So how can I overwrite an existing keymap? One of my plugins maps `<leader>ww`, but this is seemingly overwritten by the lazyvim keymaps. I've tried:

- adding `vim.keymap.del('n','<leader>ww')` to my lua/config/keymaps.lua. This disables both keymaps.
- adding `keys = {{ "<leader>ww",  "<cmd> WikiIndex <cr>", desc = "Wiki home" }},` to the `lua/plugins/wiki.lua` file (where I load the plugin). This has no effect, but if I change to "wa" instead of "ww" it works.
- adding `vim.keymap.del('n','<leader>ww')` to the `init` of the plugin file (wiki.lua), and subsequently `vim.keymap.set(...)`. This complains that there is "no such mapping". When removing the `del` part, the set-part seemingly has no effect (<leader>ww still maps to the lazyvim default)
- by adding vim.keymap.set(...) to  lua/config/keymaps.lua the behaviour is as intended (I can set the keymap to whatever I want), but this seems like a hack (defining the keymap independent of whether the plugin is installed/loaded or not). 

Is there a better way? 

Thanks!, and please forgive my lua confusion.

**Comment by dpetka2001** [comment]
The following worked for me
```lua
return {
  {
    "lervag/wiki.vim",
    keys = {
      { "<leader>ww", "<cmd>WikiIndex<cr>" },
    },
  },
}
```

**Comment by krisgry** [comment]
Thanks, good to know that your snippet should work!

There seems to be something wrong/fragile with my init-function for wiki.vim (commenting out some seemingly unrelated stuff made it work), so I'll keep digging.
