### ISSUE TITLE
feature: `prepend_args` support for "nvim-lint"

### ISSUE THREAD

**Issue by UtkarshVerma** [LazyVim/LazyVim#1887]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

If I want to specify extra args for linters, there's no provision for doing that. For `conform.nvim`, we have `prepend_args` and LazyVim merges the passed opts with the defaults.

### Describe the solution you'd like

As it is with formatters, support for this would be great. For example, since `nvim-lint` does not have a `prepend_args` key, we could reserve this key just for LazyVim where the `config()` function extends the default linter with the passed args.

This would result in a clean config on the user side like this:
```lua
  {
    "nvim-lint",
    opts = {
      linters_by_ft = {
        sh = { "shellcheck" },
      },
      linters = {
        shellcheck = {
          prepend_args = {
            "-x",
          },
        },
      },
    },
  },
```

### Describe alternatives you've considered

https://github.com/mfussenegger/nvim-lint/issues/397 discusses this, but when I assigned a function for shellcheck doing the same list extension, it did not work as the function overrides the default linter table.

### Additional context

For now, in my config I have the following if condition to implement this feature.

```lua
      local lint = require("lint")
      for name, linter in pairs(opts.linters) do
        if type(linter) == "table" and type(lint.linters[name]) == "table" then
          lint.linters[name] = vim.tbl_deep_extend("force", lint.linters[name], linter)

          if type(linter.prepend_args) == "table" then
            vim.list_extend(lint.linters[name].args, linter.prepend_args)
          end
        else
          lint.linters[name] = linter
        end
      end
      lint.linters_by_ft = opts.linters_by_ft
```

**Comment by folke** [comment]
Added!
