### ISSUE TITLE
bug: VenvSelector won't work with Poetry on MacOS

### ISSUE THREAD

**Issue by isinyaaa** [LazyVim/LazyVim#1889]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

14.0

### Describe the bug

I'm using [`extras/lang/python.lua`](https://github.com/LazyVim/LazyVim/blob/7831fc94ca5989baf766c0bb6ad36a70838c3d5a/lua/lazyvim/plugins/extras/lang/python.lua) and when I try to use `<leader>cv` it can't find any `venv`s except if they are defined in `cwd`.

<img width="801" alt="image" src="https://github.com/LazyVim/LazyVim/assets/39812919/f6b96265-f220-4dfe-93cc-a649d6e5ff67">

### Steps To Reproduce

1. `mkdir test && cd test`
2. `poetry init -n`
3. `poetry add attrs` (any dependency will do)
4. `poetry install`
5. Open nvim and try to `:VenvSelect` (or `<leader>cv`)

### Expected Behavior

On Linux I get a complete list of `venv`s:

<img width="828" alt="image" src="https://github.com/LazyVim/LazyVim/assets/39812919/88de53bf-038f-4dab-b890-35f38d88f5f5">

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
  { import = "lazyvim.plugins.extras.lang.python" },  -- I'm not sure why that won't work but that's the idea.
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Not really a LAzyVim issue is it. Check the venv plugin's docs or report it there
