### ISSUE TITLE
bug: attempt to index a boolean value

### ISSUE THREAD

**Issue by svartkanin** [LazyVim/LazyVim#1895]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

Archlinux

### Describe the bug

```
Error executing Lua callback: ...ocal/share/nvim/lazy/LazyVim/lua/lazyvim/util/extras.lua:81: attempt to index a boolean value
stack traceback:
	...ocal/share/nvim/lazy/LazyVim/lua/lazyvim/util/extras.lua:81: in function 'get_extra'
	...ocal/share/nvim/lazy/LazyVim/lua/lazyvim/util/extras.lua:47: in function 'fn'
	.../.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/util.lua:203: in function 'fn'
	.../.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/util.lua:190: in function 'ls'
	.../.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/util.lua:199: in function 'walk'
	.../.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/util.lua:201: in function 'fn'
	.../.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/util.lua:190: in function 'ls'
	.../.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/util.lua:199: in function 'walk'
	...ocal/share/nvim/lazy/LazyVim/lua/lazyvim/util/extras.lua:44: in function 'get'
	...ocal/share/nvim/lazy/LazyVim/lua/lazyvim/util/extras.lua:155: in function 'update'
	...ocal/share/nvim/lazy/LazyVim/lua/lazyvim/util/extras.lua:103: in function 'show'
	...ocal/share/nvim/lazy/LazyVim/lua/lazyvim/config/init.lua:186: in function <...ocal/share/nvim/lazy/LazyVim/lua/lazyvim/config/init.lua:185>
```

### Steps To Reproduce

1. Installed Lazyvim
2. Run the initial installation
3. Opened Mason
4. Installed Python LSP
5. Restarted Lazyvim
6. Exectued `:LazyExtras`

### Expected Behavior

Executing `:LazyExtras` does not result in an error

**Comment by dpetka2001** [comment]
Is Lazyvim updated to the latest version? Or maybe something went wrong during the installation from git? Could you try remove `~/.local/share/nvim/lazy/LazyVim` directory and let Neovim install it again?

**Comment by folke** [comment]
That's because you have a plugin file under `lua/plugins/extras/foo.lua` that is not a spec

**Comment by svartkanin** [comment]
> That's because you have a plugin file under lua/plugins/extras/foo.lua that is not a spec
That was the problem thanks
