### ISSUE TITLE
feature: Toggle quickfix/location list instead of just opening

### ISSUE THREAD

**Issue by Cretezy** [LazyVim/LazyVim#190]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

It's nice to have a way to close to quickfix list when in another buffer. LazyVim could toggle the quickfix/location list instead of simply opening it.

Related mapping:
https://github.com/LazyVim/LazyVim/blob/3a28ce7919b05b4bcec2fdc461eac099d0905835/lua/lazyvim/config/keymaps.lua#L96-L97

### Describe the solution you'd like

Maybe something like:

```lua
function toggle_qf()
  local qf_exists = false
  for _, win in pairs(vim.fn.getwininfo()) do
    if win["quickfix"] == 1 then
      qf_exists = true
    end
  end

  if qf_exists == true then
    vim.cmd "cclose"
    return
  end
  if not vim.tbl_isempty(vim.fn.getqflist()) then
    vim.cmd "copen"
  end
end
```

### Describe alternatives you've considered

Can bind it myself.

**Comment by folke** [comment]
I don't think this is really needed. You can also close the qf list etc with `q` already
