### ISSUE TITLE
feature: lombok support by default on jdtls

### ISSUE THREAD

**Issue by jeusdi** [LazyVim/LazyVim#1907]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

lombok libreries are ignored since lombok.jar is not able on jdtls by default.

### Describe the solution you'd like

Add lombok by default.
See, [here for example](https://github.com/dragove/nvim/blob/8727d6991a2985231a177969e6c70d369f11c8b3/lua/plugins/jdtls.lua#L53).

### Describe alternatives you've considered

Add custom plugin.

**Comment by guillaumeLamanda** [comment]
I posted [here](https://github.com/LazyVim/LazyVim/discussions/275#discussioncomment-7457295) a way to add lombok to the Java extra. 😁
