### ISSUE TITLE
Release unused `<c-k>` `<c-b>` `<c-f>` keymaps in `insert mode`

### ISSUE THREAD

**Issue by ueaner** [LazyVim/LazyVim#191]
I'm not sure what events generate floating windows in insert mode.

https://github.com/LazyVim/LazyVim/blob/2ff213126ceb7c85619a084f9bde4c92199248f3/lua/lazyvim/plugins/ui.lua#L206-L207

Seeing `<c-k>` triggers `Signature Help`.

https://github.com/LazyVim/LazyVim/blob/2ff213126ceb7c85619a084f9bde4c92199248f3/lua/lazyvim/plugins/lsp/keymaps.lua#L21

It should be rare to move to a function in insert mode to view its `Signature Help`, and the `Signature Help` is often not large and does not need to scroll.

So I think in insert mode, we should release `<c-k>` `<c-b>` `<c-f>` these keys to do other things.

What do you think of my humble opinion?

**Comment by folke** [comment]
Those mappings were added for a reason. I'm not just going to remove them.

**Comment by ejuarezg** [comment]
I just came across this issue in my personal config and was wondering how one would create an override to free up the key for other plugins?

**Comment by folke** [comment]
Didnt test, but something like the below should work

```lua

local keys = require("lazyvim.plugins.lsp.keymaps").get()

keys[#keys+1] = {"<c-k>", false}
```

**Comment by ejuarezg** [comment]
Thank you! Didn't work at first, but it did after adding `mode = {i}`
