### ISSUE TITLE
bug: Telescope Trouble keybindings don't work

### ISSUE THREAD

**Issue by skoch13** [LazyVim/LazyVim#1910]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

MacOS 14.1

### Describe the bug

Telescope has predefined [trouble keybindings](https://github.com/LazyVim/LazyVim/blob/e5babf289c5ccd91bcd068bfc623335eb76cbc1f/lua/lazyvim/plugins/editor.lua#L228C19-L228C19), which used to work but now they don't. Instead, pressing, for example, `<c-t>` opens up the selected file.

### Steps To Reproduce

1. `<leader> s + w`
2. Press `<c-t>` to send everything to Trouble

### Expected Behavior

Search results are open in Trouble

### Repro

```Lua
Nothing's changed from default settings here.
```

**Comment by dpetka2001** [comment]
It works for me like it should. `<c-t>` sends the results to Trouble. Maybe something to do with your terminal keymaps conflict?

**Comment by skoch13** [comment]
@dpetka2001 thank you for looking into it. By some reason telescope provides the following keymaps 
![Screenshot 2023-10-31 at 12 25 33](https://github.com/LazyVim/LazyVim/assets/29177689/eb750d69-97c3-4e8a-96dd-a72662b042d9)

I'll investigate it further.

**Comment by dpetka2001** [comment]
Maybe you changed the keybinding yourself in your personal Telescope spec?

**Comment by skoch13** [comment]
I found that turning off my telescope changes fixes the issue, however I only disabled some of keybindings. I presume the pickers customization is to blame.

**Comment by dpetka2001** [comment]
Since this is not a Lazyvim issue, maybe close it and open a new one in the Discussions for further help?

**Comment by skoch13** [comment]
You are right, thank you.

**Comment by skoch13** [comment]
You are right, thank you.

**Comment by skoch13** [comment]
I was changing telescope's opts wrong. The working solution would be the following:

```
config = function(_, opts)
  local updates = {...}
      require("telescope").setup(vim.tbl_deep_extend("keep", updates, opts))
     end,
```
