### ISSUE TITLE
bug: The workspace is automatically replaced with the parent directory

### ISSUE THREAD

**Issue by ClzSkywalker** [LazyVim/LazyVim#1912]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.4

### Operating system/version

docker in windows, the base image is ubuntu：https://hub.docker.com/repository/docker/1045683477/lazyvim/general

### Describe the bug

For example, I am/MNT/d/project/flutter/input nvim hw_flutter working directory, enter the neovim I found working directory into the/MNT/d/project

![bug](https://github.com/LazyVim/LazyVim/assets/44250611/aed96c1e-b7de-4174-b40a-989c0c6cc8ef)

### Steps To Reproduce

1. git clone https://github.com/LazyVim/starter ~/.config/nvim
2. Find a directory with multiple levels
3. input nvim

### Expected Behavior

The working directory should be the current directory

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
The keymap for current working directory is `<leader>E`. Do you use that or do you use `<leader>e`? Or change the `vim.g.root_spec` to only `cwd` if you don't prefer this kind of behavior.

**Comment by ClzSkywalker** [comment]
> The keymap for current working directory is `<leader>E`. Do you use that or do you use `<leader>e`? Or change the `vim.g.root_spec` to only `cwd` if you don't prefer this kind of behavior.

use <leader>e

I in ~ / config/nvim lua/config/options. The lua files to increase the vim. G.r oot_spec = 'CWD', but it's no use.

This problem is not all directories are like this, most directories use nvim is normal, only a few directories will occur this situation, I temporarily can not distinguish between normal directories and abnormal directories what is the difference

**Comment by dpetka2001** [comment]
This is caused because of the LSP `root_dir` detection that Lazyvim offers. Use `<leader>E` instead of `<leader>e` if you want the files in the current working directory or in your `/lua/config/options.lua` put `vim.g.root_spec = { "cwd" }`.

**Comment by ClzSkywalker** [comment]
> This is caused because of the LSP `root_dir` detection that Lazyvim offers. Use `<leader>E` instead of `<leader>e` if you want the files in the current working directory or in your `/lua/config/options.lua` put `vim.g.root_spec = { "cwd" }` to disable this kind of behavior permanently.

My friend, you are my hero, I spent a lot of time to solve this problem, thanks to your code, I used vim.g.oot_spec = {"cwd"} has been able to work properly. I used to think the telescope plugin was the cause of the problem.
