### ISSUE TITLE
bug: Some troubles with selects

### ISSUE THREAD

**Issue by kobzar** [LazyVim/LazyVim#1913]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

OSx, Linux

### Describe the bug

Something went wrong after last updates
When i try to select some standard or custom select - its do wrong
For example 
<img width="339" alt="image" src="https://github.com/LazyVim/LazyVim/assets/1912842/15f29d52-ab73-4ae7-ab43-b61524bc280d">

The next one i try to select word inside brackets "data", so i try several variants
```viw```
or use plugin multiedit
[    "mg979/vim-visual-multi",
](https://github.com/mg979/vim-visual-multi)
In both variants the selecting is wrong
<img width="341" alt="image" src="https://github.com/LazyVim/LazyVim/assets/1912842/61251078-2a33-4459-8519-345be71d97b6">

When i try to select function/method name i've got this 
<img width="634" alt="image" src="https://github.com/LazyVim/LazyVim/assets/1912842/526a036b-d162-4315-9e2e-9a063799fa27">

This is very hard to work now. And i dont change any of my plugins settings.

In the same time, Flash and mini.surround plugins work correctly

### Steps To Reproduce

*

### Expected Behavior

*

### Repro

```Lua
*
```

**Comment by dpetka2001** [comment]
I just tried with a new fresh starter template and it works correctly. Could you also try with a new starter template? If it works correctly (like in my case), then I guess it would have something to do with your own config.
