### ISSUE TITLE
question:  How should I modify the settings of this markdown

### ISSUE THREAD

**Issue by oldqin97** [LazyVim/LazyVim#1914]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.0

### Operating system/version

Macos 12.4

### Describe the bug

<img width="615" alt="image" src="https://github.com/LazyVim/LazyVim/assets/48620148/2c51bf19-f137-42af-9ce7-6ce3dfa89fbb">
<img width="516" alt="image" src="https://github.com/LazyVim/LazyVim/assets/48620148/14d05b5d-32cb-4044-8203-ce5d15632578">

In a markdown file, when I place the cursor over the text, I can see the editing format. How should I set it to make these characters display their original appearance? For example, **test** is currently displayed like this, and I want it to appear like this without having to hover over it.

### Steps To Reproduce

null

### Expected Behavior

<img width="165" alt="image" src="https://github.com/LazyVim/LazyVim/assets/48620148/b256f2d2-5d65-4e9f-85b9-c04087492162">

**Comment by dpetka2001** [comment]
Try with `:set cole=0`. If this does what you want, you can set it in your `/lua/config/options.lua` with `vim.opt.conceallevel = 0`.

**Comment by oldqin97** [comment]
> 尝试使用`:set cole=0`. 如果这符合您的要求，您可以将其设置在您的`/lua/config/options.lua`with中`vim.opt.conceallevel = 0`。

Thank you very much, I set this up and it solved the problem
