### ISSUE TITLE
bug: file dropped on nvim-qt on Windows OS won’t open

### ISSUE THREAD

**Issue by Noneangel** [LazyVim/LazyVim#192]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.8.3

### Operating system/version

Windows 10 and Windows 11

### Describe the bug

Dropping a file from the Windows (os) explorer to `nvim-qt.exe` (the gui bundled with nvim from [the official github](https://github.com/neovim/neovim/releases/tag/stable)) does nothing (it doesn't open the file dropped on the gui).
I can reproduce these two computers running Windows 10 and 11.

In both cases, I erased `nvim` and `nvim-data` before doing a fresh install of LasyVim.

Opening a file using drag and drop work in an instance of the gui loaded with `nvim-qt.exe -- -u none`.

This is specific with `nvim-qt.exe`. I cannot reproduce the bug with `neovide`.

`nvim-qt.exe -v`:
![image](https://user-images.githubusercontent.com/1888627/217103627-9bcf70a3-1aee-43d9-bb51-4f148b5b336c.png)

### Steps To Reproduce

1. Follow installation instruction from https://www.lazyvim.org/installation (including the step `Move-Item $env:LOCALAPPDATA\nvim-data $env:LOCALAPPDATA\nvim-data.bak`
2. launch `nvim-qt.exe`
3. drag a file from the explorer to `nvim-qt.exe`

### Expected Behavior

The file dropped on the gui should be opened by `nvim-qt.exe`.

**Comment by folke** [comment]
Can you make sure your `lua/config/lazy.lua` file does not disable `netrwPlugin`?
So that line should be commented

**Comment by folke** [comment]
It's caused by lazy.nvim. See possible fixes here https://github.com/folke/lazy.nvim/issues/403

https://github.com/equalsraf/neovim-qt#why-are-the-gui-commands-missing
