### ISSUE TITLE
bug: can not over set default keymap

### ISSUE THREAD

**Issue by j2wyatt** [LazyVim/LazyVim#1929]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

macos 13.2

### Describe the bug

`vim.keymap.set("n", "f", "<C-f>", { remap = true })`
this command not work

### Steps To Reproduce

1. write config init.lua
2. this words：`vim.keymap.set("n", "f", "<C-f>", { remap = true })`
3. not working

### Expected Behavior

real work

### Repro

```Lua
-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")

vim.keymap.set("n", "s", "<cmd>w<cr><esc>", { desc = "Save file" })
vim.keymap.set("n", "f", "<C-f>", { remap = true })
vim.keymap.set("n", "e", "<C-u>", { remap = true })
vim.keymap.set("n", "<f3>", "<leader>fc", { remap = true })
vim.keymap.set("n", ".", "<leader>e", { remap = true })
vim.o.guifont = "Monaco Nerd Font:h18"
```

**Comment by liaohui5** [comment]
@j2wyatt 如果你想要修改快捷键, [请看文档](https://www.lazyvim.org/configuration/keymaps)
因为你使用 vim.keymap.set 这个API, 给的参数不对, neovim 的API没有 `remap` 这个选项, 
你可以在neovim中 `:help vim.keymap.set` 可以查看文档,

这个选项是 lazyvim 提供的, 换句话说: 你必须按照 lazyvim 的配置文件, 使用 `keys` 选项才可以使用这个 `remap` 这个选项,
所以你这样执行是不行的 `vim.keymap.set("n", "f", "<C-f>", { remap = true })`

[这是我的配置](https://github.com/liaohui5/dotfiles/tree/main/nvim), 你可以参考下, 希望更可以帮到你

**Comment by dpetka2001** [comment]
The following `vim.keymap.set("n", "f", "<C-f>", { remap = true })` worked fine for me if you put it in `/lua/config/keymaps.lua`.

**Comment by j2wyatt** [comment]
> The following `vim.keymap.set("n", "f", "<C-f>", { remap = true })` worked fine for me if you put it in `/lua/config/keymaps.lua`.

Thank you very much. Although I have already guessed in my heart, I just don’t want to admit that init.lua and keymaps.lua may be different, [crying]

**Comment by j2wyatt** [comment]
> The following `vim.keymap.set("n", "f", "<C-f>", { remap = true })` worked fine for me if you put it in `/lua/config/keymaps.lua`.

Also I would really like to know more about this feature, do you know where I can find it?

**Comment by j2wyatt** [comment]
Sorry, I was referring to why `init.lua` and `keymaps.lua` have different effects. Where can I see such documents?

**Comment by dpetka2001** [comment]
My guess is that it has something to do with the way Lazyvim loads the different files in `/lua/config/`. In Lazyvim `f` is used by `flash.nvim`. But if you put it in your `init.lua` it will get overwritten by the plugin's configuration, which is loaded after the `init.lua` is loaded. So, if you put the keymap in `/lua/config/keymaps.lua` it is ensured that it takes precedence over plugin's configuration. I don't really know any good docs to point you except from reading the code itself in `/lua/config/lazy.lua`.

**Comment by dpetka2001** [comment]
Also do you mind closing the issue since it's been resolved?

**Comment by j2wyatt** [comment]
thanks
