### ISSUE TITLE
bug: Cannot delete terminal keymap

### ISSUE THREAD

**Issue by JoshStern** [LazyVim/LazyVim#1936]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.2

### Operating system/version

Ubuntu 22.04.1 - Linux 6.2.0-33-generic 

### Describe the bug

I'd like to clear the default behavior for toggling the floating terminal. I tried following the instructions in the docs: 

> Default LazyVim keymaps can be deleted with vim.keymap.del

But after deleting the mapping it still toggles the floating terminal. After loading nvim with the `.del(...)` command `:nmap` and `:WhichKey` both don't have `<C-/>` but the keymap continues to toggle the terminal. I also tried setting it to another command and it still toggles the floating terminal.

### Steps To Reproduce

1. Clone the starter repo to your config:
   ```sh
   git clone https://github.com/LazyVim/starter ~/.config/nvim
   ```
2. Edit `lua/config/keymaps.lua` to include the following:
   ```lua
   vim.keymap.del("n", "<C-/>")
   -- optionally you can set it to something else here
   ```
3. Reload neovim and enter the `C-/` keymap.

### Expected Behavior

The toggle terminal keymap to be removed or replaced.

### Repro

The initial repro script doesn't seem to load the default keymaps, I did not edit it.
```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

Also LazyVim has been fantastic - thank you for the work on this! I'm happy to contribute a fix but will need some direction.

**Comment by jyuan0** [comment]
It **might** have to do with how your terminal is interpreting `C-/`. You can try also adding `vim.keymap.del("n", "<c-_>")` to see if that does the trick. LazyVim maps both keystrokes to `lazyterm`.

**Comment by folke** [comment]
@jyuan0 is correct

**Comment by JoshStern** [comment]
That did it, thank you for the quick response! I saw the binding and should have tried clearing it as well, sorry about that.
