### ISSUE TITLE
bug: Unable to create 

### ISSUE THREAD

**Issue by j-barnak** [LazyVim/LazyVim#194]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.8.3

### Operating system/version

Linux Mint 21

### Describe the bug

I'm unable to add  LSP configs to `nvim-lspconfig` according to [nvim-lspconfig](https://www.lazyvim.org/plugins/lsp#nvim-lspconfig). I specifically want to add the following arguments to `clangd`

```
"--query-driver",
"/home/jared/Projects/CPP/NakOS/Toolchain/opt/cross/bin/i686-elf-g++"
```

I get the following error

Failed to load `plugins.lsp-conf`

```
vim/_init_packages.lua:0: /home/jared/.config/nvim/lua/plugins/lsp-conf.lua:4: '}' expected (to close '{' at line 3) near '='

# stacktrace:
  - vim/_init_packages.lua:0
  - ~/.config/nvim/lua/config/lazy.lua:9
  - ~/.config/nvim/init.lua:3
```

### Steps To Reproduce

1. Go to `~/.config/nvim/lua/plugins`
2. Create a file `~/.config/nvim/lua/plugins/lsp-conf.lua`

`~/.config/nvim/lua/plugins/lsp-conf.lua` contains

```
opts = {
  servers = {
    clangd = {
      clangd.arguments = {
        "--query-driver",
        "/home/jared/Projects/CPP/NakOS/Toolchain/opt/cross/bin/i686-elf-g++",
      }
    }
  }
}
```

### Expected Behavior

Apply the `--query-driver` argument to `.clangd`/

**Comment by surmish** [comment]
I think a compile_flags.txt in one of your parent dirs for your project will do the trick.
E.g I have a symlink to the following file in the project dir:

```
cat ~/.clang_compilation_dir/compile_flags.txt
-xc++
-fPIC
-fPIE
-query-driver
-std=c++17
-I/home/jared/Projects/CPP/NakOS/Toolchain/opt/cross/bin/i686-elf-g++
```

**Comment by TamasBarta** [comment]
@j-barnak this is a syntax error, so the fault is definitely in your config. I don't know the specific plugin, but to me, it looks like you don't need `clangd.arguments`, but only `arguments` on line 4. At least that resolves the syntax error :)

**Comment by j-barnak** [comment]
I was able to fix this by doing

```
-- bootstrap lazy.nvim, LazyVim and your plugins

require("config.lazy")

local lspconfig = require("lspconfig")
local project_root = "/home/jared/Projects/CPP/NakOS"

if vim.fn.getcwd() == project_root then
    lspconfig.clangd.setup({
        cmd = {
            "clangd",
            "--background-index",
            "--query-driver",
            "/home/jared/Projects/CPP/NakOS/Toolchain/opt/cross/bin/i686-elf-g++",
        },
        filetypes = { "c", "cpp", "objc", "objcpp" },
    })
end
```

Is there a way I could add

```
local lspconfig = require("lspconfig")
local project_root = "/home/jared/Projects/CPP/NakOS"

if vim.fn.getcwd() == project_root then
    lspconfig.clangd.setup({
        cmd = {
            "clangd",
            "--background-index",
            "--query-driver",
            "/home/jared/Projects/CPP/NakOS/Toolchain/opt/cross/bin/i686-elf-g++",
        },
        filetypes = { "c", "cpp", "objc", "objcpp" },
    })
end
``` 

to a file in `~/.congig/nvim/lua/config/`?

**Comment by folke** [comment]
The error very clearly shows you have a syntax error in your config. 
I would advise you to read some Neovim and general Lua guides to have a better understanding of the language. That'll help you with understanding how to configure LazyVim.
