### ISSUE TITLE
bug: Today I update LazyVim and while sync, plugin nvim-spectre it failed. 

### ISSUE THREAD

**Issue by mkubasz** [LazyVim/LazyVim#1940]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.4 Build type: Release LuaJIT 2.1.1697887905

### Operating system/version

macos - 14.1 Sonoma

### Describe the bug

Today I update LazyVim and while sync plugin nvim-spectre it failed. Same I tried with fresh installation.

I created issue ticked on the nvim-spectre repo https://github.com/nvim-pack/nvim-spectre/issues

### Steps To Reproduce

1. Clone lazyvim
2. Open vim to install packages

https://drive.google.com/file/d/1mWrAoL3qLVrf53CVEuSK08636_cxjrrE/view?usp=sharing

### Expected Behavior

Should don't fail with neovim-spectre.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
I highly doubt this is a Lazyvim issue. This is a problem with spectre and your OS.

**Comment by mkubasz** [comment]
> I highly doubt this is a Lazyvim issue. This is a problem with spectre and your OS.

Yes, only add here note as bug, to notice that is problem with that. I will close if it is unrelated.

**Comment by mkubasz** [comment]
Current workaround is on the repo of neovim-spectre. https://github.com/nvim-pack/nvim-spectre/issues/182#issuecomment-1792220582
