### ISSUE TITLE
feature: add a option in lazyvim to set all plugins border

### ISSUE THREAD

**Issue by leisurelicht** [LazyVim/LazyVim#1942]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

when I try to change float window border to rounded. I need to go through and modify the option for each individual plugin. If border is set within keymap,  such as diagnostic. I have to copy diagnostic_goto function and remap it only for add a border option.

```lua
local diagnostic_goto = function(next, severity)
  local go = next and vim.diagnostic.goto_next or vim.diagnostic.goto_prev
  severity = severity and vim.diagnostic.severity[severity] or nil
  return function()
    go({ severity = severity, float = { border = "rounded" } })
  end
end

map.set("n", "]d", diagnostic_goto(true), { desc = "Next Diagnostic" })
map.set("n", "[d", diagnostic_goto(false), { desc = "Prev Diagnostic" })
map.set("n", "]e", diagnostic_goto(true, "ERROR"), { desc = "Next Error" })
map.set("n", "[e", diagnostic_goto(false, "ERROR"), { desc = "Prev Error" })
map.set("n", "]w", diagnostic_goto(true, "WARN"), { desc = "Next Warning" })
map.set("n", "[w", diagnostic_goto(false, "WARN"), { desc = "Prev Warning" })
```

### Describe the solution you'd like

Can we add a global option 'border' to LazyVim to control the 'border' parameter for all plugins. like colorscheme.

```
    {
      "LazyVim/LazyVim",
      import = "lazyvim.plugins",
      opts = {
        colorscheme = "catppuccin-frappe",
        border = "rounded",
      },
    }
```

### Describe alternatives you've considered

I can config it myself, but I believe having a unified configuration option would be more user-friendly.

**Comment by dpetka2001** [comment]
Do you want to have diagnostics with rounded borders? If so, you can try
```lua
return {
  {
    "neovim/nvim-lspconfig",
    opts = {
      diagnostics = {
        float = {
          border = "rounded",
        },
      },
    },
  },
}
```

**Comment by leisurelicht** [comment]
> ```lua
> opts = {
>       diagnostics = {
>         float = {
>           border = "rounded",
>         },
>       },
>     },
> ```

thanks you。It is worked and solved most of my issues。for the rest，I feel I can configure them myself。

**Comment by dpetka2001** [comment]
Lazyvim also uses `noice` which has a preset for LSP borders. Test it out to see if that's also something that you'd like. You can configure it like this
```lua
return {
  "folke/noice.nvim",
  opts = {
    presets = {
      lsp_doc_border = true,
    },
  },
}
```
I don't know what other borders you'd like. For the floating terminal you could also see #1915.

**Comment by leisurelicht** [comment]
> Lazyvim also uses `noice` which has a preset for LSP borders. Test it out to see if that's also something that you'd like. You can configure it like this
> 
> ```lua
> return {
>   "folke/noice.nvim",
>   opts = {
>     presets = {
>       lsp_doc_border = true,
>     },
>   },
> }
> ```
> 
> I don't know what other borders you'd like. For the floating terminal you could also see #1915.
> 
> Edit: and for the autocompletion menu you can see this [post](https://github.com/LazyVim/LazyVim/discussions/419#discussioncomment-5802918).

thank you。I already set border in which-key，cmp，noice，term and git plugins myself。It is not too hard. I believe that‘s all I need to set in lazyvim。

**Comment by towry** [comment]
I believe there eventually will be an option like `vim.g.lazyvim_ui_border`
