### ISSUE TITLE
feature: keep stock neovim start screen

### ISSUE THREAD

**Issue by melsiir** [LazyVim/LazyVim#1946]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

for me i think the stock nvim start screen is the most fancy start screen  i l've seen and i would like to make my main start screen i understand that  there are mix of plugins and sittings make disappear  and i wonder if someone can work it around

### Describe the solution you'd like

i want neovim stock startup screen  to be my main start screen

### Describe alternatives you've considered

i've set lualine separator to none and aliased vi to vi +intro
this will make neovim start with the stock start screen but the problem is that the intro appear even if i opening file and thats annoying i want it to appear only if i open neovim with no file

### Additional context

![SwXg7](https://github.com/LazyVim/LazyVim/assets/73516767/326d9c71-ca0f-493e-9625-1db96387a522)

**Comment by dpetka2001** [comment]
Take a look at this post in `lazy.nvim` repo, that should help you do what you want. There's some tinkering involved to achieve what you'd like. Try it out.

**Comment by abeldekat** [comment]
For stock `LazyVim`, I have an example in my [starter repo](https://github.com/abeldekat/starter/tree/default_startscreen). See file `plugins.test.lua`.

**Comment by abeldekat** [comment]
Thanks @dpetka2001!

**Comment by melsiir** [comment]
thanks it worked @dpetka2001 @abeldekat
