### ISSUE TITLE
bug: custom keymap for LSP format no longer works

### ISSUE THREAD

**Issue by PetarMetodiev** [LazyVim/LazyVim#1948]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.2

### Operating system/version

macOS Ventura 13.6

### Describe the bug

Previously(using LazyVim v8) I was able to set a custom keymap for formatting like so:
```lua
{
    "neovim/nvim-lspconfig",
    init = function()
      local keys = require("lazyvim.plugins.lsp.keymaps").get()
      -- ...other working keymaps
      keys[#keys + 1] = {
        "gf",
        vim.lsp.buf.format,
        noremap = true,
        silent = true,
        desc = "Format document",
        has = "formatting", -- tried removing this, but had no luck
      }
      -- ... other working keymaps
}
```

Yesterday I updated to version 10 and this keymap no longer works. The default mapping of `<leader>cf` works as expected, typing `:lua vim.lsp.buf.format()` formats as expected, typing `:lua require('conform').format()` formats as expected. 

But when I press `g` I no longer see "Format document" next to `f` but instead see "Go to file under cursor".

I found [this](https://github.com/LazyVim/LazyVim/blob/68ff818a5bb7549f90b05e412b76fe448f605ffb/lua/lazyvim/config/keymaps.lua#L90C33-L92C26) piece of code which sets the default keymap for formatting. Tried it in my config like so:

```lua
{
    "neovim/nvim-lspconfig",
    init = function()
      local keys = require("lazyvim.plugins.lsp.keymaps").get()
      local Util = require("lazyvim.util")

      keys[#keys + 1] = {
        "gf",
        function()
          Util.format({ force = true })
        end,
        noremap = true,
        silent = true,
        desc = "Format document",
        has = "formatting",
      }
}
```
... but it didn't help.

I have other mappings in this block and they seem to work as expected. I event have a keymap for formatting visual selection and it is working as expected:
```lua
      keys[#keys + 1] = {
        "gf",
        vim.lsp.buf.format,
        noremap = true,
        silent = true,
        desc = "Format range",
        mode = "v",
        has = "rangeFormatting",
      }
```

I looked through the docs and the only thing I found was that now conform is used for formatting, but could not find anything related to my issue.

[Link](https://github.com/PetarMetodiev/.dotfiles/tree/master/vim/lazyvim) to my config.

### Steps To Reproduce

1. Change the format keymap like so:
```lua
{
    "neovim/nvim-lspconfig",
    init = function()
      local keys = require("lazyvim.plugins.lsp.keymaps").get()
      keys[#keys + 1] = {
        "gf",
        vim.lsp.buf.format,
        noremap = true,
        silent = true,
        desc = "Format document",
        has = "formatting",
      }
}
```
2. Press `gf`.
3. The document does not get formatted.

### Expected Behavior

Pressing `gf` should format the document.

**Comment by dpetka2001** [comment]
The format key was removed from the LSP keys section and moved to `keymaps.lua`. So, if you do in your `/lua/config/keymaps.lua` something like this
```lua
local Util = require("lazyvim.util")
vim.keymap.set({ "n", "v" }, "gf", function()
  Util.format({ force = true })
end, { desc = "Format" })
```
I believe it should work.

**Comment by PetarMetodiev** [comment]
Thanks for the suggestion. Tried it, but it doesn't work. On the upside when I press `g` whichkey properly shows the description. Still formatting doesn't seem to work.

**Comment by dpetka2001** [comment]
Strange, it works for me with `conform` in a Lua file. 

![test](https://github.com/LazyVim/LazyVim/assets/12776461/609a8f10-e406-49d0-b33c-9f8b22d3da6d)

Maybe it has to do with which formatter you're using?

**Comment by PetarMetodiev** [comment]
I am not sure this is the case. Indeed when you try to fix only indentations, `gf` is working as expected. But when it comes to more complex cases nothing happens. This is reproducible in `tsx` and `lua` files, both with default formatters. Here is a demo:

https://github.com/LazyVim/LazyVim/assets/6378306/431d9260-4e3d-4c06-b88a-b4ce221e71f9

**Comment by dpetka2001** [comment]
![test](https://github.com/LazyVim/LazyVim/assets/12776461/a1b56261-924b-4ebd-b88c-efd1def791bb)

I tried to emulate what you did in your demo, but sadly could not reproduce.

**Comment by PetarMetodiev** [comment]
Ok, that is strange. Any idea what could _possibly_ be the culprit? I have not touched anything related to formatters.
![image](https://github.com/LazyVim/LazyVim/assets/6378306/8b58b8c9-dc44-49f2-b831-d134cfe6bf05)
![image](https://github.com/LazyVim/LazyVim/assets/6378306/f5caae1d-bf5c-4320-9b39-e307e86c8dee)

**Comment by dpetka2001** [comment]
Unfortunately, I'm not very familiar with the Lazyvim format process myself. I just tried this on a new Lazyvim starter template. Maybe you could test with a fresh starter template if it works correctly to check if it has something to do with your configuration or not in the end?

**Comment by PetarMetodiev** [comment]
Ok, found the root cause. I am just stupid 🤦‍♂️
The problem was that I hadn't removed the old mapping from nvim-lspconfig options and it was causing trouble. Thank you very much for the help and sorry if I wasted your time.
Here is a cute cat for apology:
![image](https://github.com/LazyVim/LazyVim/assets/6378306/9e534dba-d7dc-469a-a1ae-6a1ee262d1b3)

**Comment by dpetka2001** [comment]
No wasted time at all. Glad you were able to make it work in the end :)
