### ISSUE TITLE
bug: which-key not working for <leader>gh, shows +prefix instead of +hunks

### ISSUE THREAD

**Issue by Syphdias** [LazyVim/LazyVim#1955]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.4

### Operating system/version

Arch Linux (Kernel 6.5.9-arch2-1)

### Describe the bug

Which-Key does not correctly display `<space>gh` hint as `+hunks` and instead displays a generic `+prefix`.

I believe that this line on [main](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/editor.lua#L316) ([specific commit](https://github.com/LazyVim/LazyVim/blob/39861698235c03d30096b3fb315ce38eeaef95e2/lua/lazyvim/plugins/editor.lua#L316) for reference stability) is not working:
```lua
["<leader>gh"] = { name = "+hunks" },
```

This happens for normal and visual mode. Steps to reproduce only go over normal mode.

### Steps To Reproduce

1. Open neovim with defaults from LazyVim/LazyVim lazyvim.plugins
2. press `<space>g`
![image](https://github.com/LazyVim/LazyVim/assets/16988672/7ee11f6a-5eed-43cb-b909-9181b0981464)

### Expected Behavior

display `+hunk` instead of `+prefix`

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
  {
    "LazyVim/LazyVim",
    import = "lazyvim.plugins",
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by abeldekat** [comment]
See [Custom registered mappings don't have the correct name](https://github.com/folke/which-key.nvim/issues/482)

**Comment by Syphdias** [comment]
Thank you, @abeldekat!
For testing purposes I used `{ dir = "path/to/local/which-key.nvim", opts = …}`, reverted the commit https://github.com/folke/which-key.nvim/commit/8503c0d725420b37ac31e44753657cde91435597 you mentioned and it shows `+hunks`.

Obviously not a real solution, especially since the group is not empty but is being filled by `lewis6991/gitsigns.nvim`. I tried to disable lazyloading for gitsigns without luck and also to set the priority for which-key to -1000 and 1000 without luck.

**Comment by rubiin** [comment]
This bug seems to be in v1.5.0+ only of which key.

**Comment by folke** [comment]
I'm closing this, since this is a which-key issue.

**Comment by rofrol** [comment]
> bug seems to be in v1.5.0+ only. Tested with v1.4.0 and it’s working as expected.

Maybe LazyVim should stay on older version?

**Comment by folke** [comment]
This is not really that big of an issue and I prefer the latest version of which-key. You can of course pin a certain version in your own config.

I'll look into the which-key issue at some point, but it's a fairly low prio issue tbh

**Comment by rubiin** [comment]
> > bug seems to be in v1.5.0+ only. Tested with v1.4.0 and it’s working as expected.
> 
> Maybe LazyVim should stay on older version?

Like he said you can pin the version to <1.5.0. I am doing that as well

**Comment by dpetka2001** [comment]
There's a workaround for this. See my [comment here](https://github.com/LazyVim/LazyVim/discussions/2887#discussioncomment-8962181), which also mentions one issue at `which-key` repo from which I initially saw the idea from another user. This way you don't have to pin the version to <1.5.0.
