### ISSUE TITLE
feature: floating diagnostics (instead of in-line)

### ISSUE THREAD

**Issue by squishram** [LazyVim/LazyVim#1964]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

In short, I find in-line diagnostics in general to be a bad linting solution:
1. it creates a lot of visual noise
2. you often can't read the whole message

### Describe the solution you'd like

The option to press e.g. `gl` on a line to see all of its diagnostics in a float that disappears when you navigate away/ with any action/ keypress. The diagnostic symbols in the left gutter will inform me of when there is one to look at.

The absolute *dreamiest* solution would be if there were a simple LazyVim toggle I could put in `~/.config/nvim/lua/config/lazy.lua` or likewise to activate this behaviour, but that's just config sugar. Happy to jam in whatever solution is currently most in line with the LazyVim philosophy in the meantime!

### Describe alternatives you've considered

I understand that diagnostics can be turned off with `<leader>ud`, and up to now I've been simply keeping them off until I want to check if they are there. But the fact that they tend to run off-screen, coupled with `<leader>ud` removing all the gutter diagnostic indicators has started to "bug" me.

### Additional context

Just want to say thanks! I apologise if you've addressed this request before, but I can't find it in the documentation. I'm no code wizard (just a scientist) so the work you've put into this starter config has been an absolute game-changer for me, particularly as far as LSP-related tooling goes. Cheers to you!

**Comment by dpetka2001** [comment]
The keymap `<leader>cd` does exactly what you want I believe if I'm not misunderstanding you.

**Comment by squishram** [comment]
Duh. I feel like such a dingus, thanks. If there's an easy way to turn off the virtual text as well, I can close this and hang my head in private shame.

**Comment by dpetka2001** [comment]
Create a file `/lua/plugins/lsp.lua` with the following contents
```lua
return {
	{
		"neovim/nvim-lspconfig",
		opts = {
			diagnostics = {
				virtual_text = false,
			},
		},
	},
}
```
Test it out to see if it works.
