### ISSUE TITLE
bug: subcapture nesting too deep

### ISSUE THREAD

**Issue by fegyi001** [LazyVim/LazyVim#1969]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev-fcfc87c

### Operating system/version

MacOS 14.0

### Describe the bug

I'm inside my complex typescript (angular) project, and sometimes this strange error becomes visible whenever I save a file:

<img width="1367" alt="image" src="https://github.com/LazyVim/LazyVim/assets/4125222/3c86913d-4525-47d6-9bbb-916bbc5c7c2e">

I cannot figure out what went wrong, and I did not find any help while googling `subcapture nesting too deep`

Is it a neovim, a lazyvim or an lsp issue, or what is it? :)

### Steps To Reproduce

1. open a project
2. edit a file
3. save file

My neovim config is here: https://github.com/fegyi001/nvim

**Comment by fegyi001** [comment]
Hi @abeldekat,

Thanks for the reply. I created an issue in the neovim lsp bug section. 
The error comes also when there is only one file opened.
When I enter `:LazyFormatInfo` the same error appears.
I don't know whether it happens on stable versions or not, I only have 0.10.x

**Comment by folke** [comment]
You should really report this in the Neovim repo. Not a LazyVim issue.

I personally disable that lsp feature with:

```lua
  {
    "neovim/nvim-lspconfig",
    opts = {
      inlay_hints = { enabled = true },
      capabilities = {
        workspace = {
          didChangeWatchedFiles = {
            dynamicRegistration = false,
          },
        },
      },
...
```
