### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by alexlitinsky** [LazyVim/LazyVim#197]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.0 commit db1b0ee3b30f

### Operating system/version

MacOS 11.5

### Describe the bug

I'm running a transparent setup on my system, and when I switch in and out of buffers, the buffer I'm on is transparent, but the other buffers aren't (except for NeoTree). This occurs when I'm on the NeoTree tab which is transparent while the actual file isn't. This also occurs when I have split tabs, and the tab that I'm not on isn't transparent. 

### Steps To Reproduce

I added the following commands to the init.lua file:

vim.cmd("hi NonText ctermbg=NONE")
vim.cmd("hi Normal guibg=NONE ctermbg=NONE")
vim.cmd("hi NeoTreeNormal guibg=NONE ctermbg=NONE")
vim.cmd("hi NeoTreeNormalNC guibg=NONE ctermbg=NONE")
vim.cmd("hi NeoTreeTabInactive guibg=NONE ctermbg=NONE")
vim.cmd("hi NeoTreeTabActive guibg=NONE ctermbg=NONE")

vim.cmd("hi Normal guibg=none ctermbg=none")
vim.cmd("hi LineNr guibg=none ctermbg=none")
vim.cmd("hi Folded guibg=none ctermbg=none")
vim.cmd("hi NonText guibg=none ctermbg=none")
vim.cmd("hi SpecialKey guibg=none ctermbg=none")
vim.cmd("hi VertSplit guibg=none ctermbg=none")
vim.cmd("hi SignColumn guibg=none ctermbg=none")
vim.cmd("hi EndOfBuffer guibg=none ctermbg=none")
vim.cmd("hi StartOfBuffer guibg=none ctermbg=none")

### Expected Behavior

When I'm on the buffer it's transparent, but if I move out of it, it becomes the normal background of the color scheme. 

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
`NormalNC`
