### ISSUE TITLE
feature: allow default keymaps customization

### ISSUE THREAD

**Issue by imroc** [LazyVim/LazyVim#1970]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Currently, the only customization for default keymaps is to disable all default keymaps:
```lua
      opts = {
        defaults = {
          keymaps = false,
        },
      }
```
And I just need a little customization:
1. Disable default `C-h/j/k/l` to avoid confliction with [tmux.nvim](https://github.com/aserowy/tmux.nvim), cuz I use nvim in tmux, I want to jump nvim window and tmux pane smoothly with keymap `C-h/j/k/l`.
```lua
-- map("n", "<C-h>", "<C-w>h", { desc = "Go to left window", remap = true })
-- map("n", "<C-j>", "<C-w>j", { desc = "Go to lower window", remap = true })
-- map("n", "<C-k>", "<C-w>k", { desc = "Go to upper window", remap = true })
-- map("n", "<C-l>", "<C-w>l", { desc = "Go to right window", remap = true })
```
2. Disable default `C-s` to avoid conflict with tmux, cuz I use `C-s` as tmux prefix key.
```lua
-- map({ "i", "x", "n", "s" }, "<C-s>", "<cmd>w<cr><esc>", { desc = "Save file" })
```

To achieve my needs, I have to disable all default keymaps, and copy `keymaps.lua` and remove those default keymaps that I have to disable. And LazyVim is currently under active development, if I upgrade LazyVim, I have to check the latest `keymaps.lua` and compare with my own `keymaps.lua`, find new difference and patch to my own `keymaps.lua`, This is a bit too troublesome.

### Describe the solution you'd like

And some options to customize default keymaps, 

```lua
      opts = {
        defaults = {
          keymaps = {
            window_jump = false,
            save_file = false,
          },
        },
      }
```

### Describe alternatives you've considered

none

**Comment by imroc** [comment]
> You don't have to disable all default keymaps. Just change or delete what you want in your own `keymaps.lua`. They will get merged with the defaults in the end.

How to delete? Do you mean execute `vim.keymap.del` in my own `keymaps.lua`?

**Comment by imroc** [comment]
I tried `vim.keymap.del` keys `<C-h/j/k/l>`, the same keys in plugin `tmux.nvim` will not work.

**Comment by abeldekat** [comment]
> Currently, the only customization for default keymaps is to disable all default keymaps

I would argue that the statement above is not correct.

The `tmux` plugin, when `navigation.enable_default_keybindings = true`, creates the keybindings which will be overwritten by `LazyVim`'s keybindings in `lazyvim.config.keymaps.lua`.

Overriding a generic keybinding with a plugin keybinding is a special case.
You have to create the keybindings yourself. This could be done in your own `config.keymaps.lua`.
However, this file is intended for generic keybindings. Introducing plugins here is not recommended.

`LazyVim` will not override keybindings defined in the spec with `keys = `.

I recommend the following spec:

```lua
  {
    "aserowy/tmux.nvim",
    keys = {
      {"<c-h>", function() require("tmux").move_left() end, desc = "tmux move left"},
      {"<c-j>", function() require("tmux").move_bottom() end, desc = "tmux move bottom"},
      {"<c-k>", function() require("tmux").move_top() end, desc = "tmux move top"},
      {"<c-l>", function() require("tmux").move_right() end, desc = "tmux move right"},
    },
    opts = {
      navigation = {
        -- enables default keybindings (C-hjkl) for normal mode
        enable_default_keybindings = false
      }
    },
  }
```

I do the same in my [config](https://github.com/abeldekat/nvim/blob/692deadd1c0e8dcadae971728d4d7efda97a0ea4/lua/plugins/editor.lua#L300), using these `ctrl keys` for `harpoon`.

In general, I only use vim.keymap.del if I want the keymap removed instead of redefined. For example, `<S-h> <S-l>` to restore `Neovim`'s top and bottom navigation.
The `<C-s>` keymapping can be removed in your own `config.keymaps.lua`:

```lua
for _, mode in pairs({ "i", "v", "n" }) do
  vim.keymap.del(mode, "<C-s>")
end
```

Best regards!

**Comment by dpetka2001** [comment]
For `vim-tmux-navigator` i have the following in my `keymaps.lua`
```lua
if os.getenv("TMUX") then
  map("n", "<C-h>", "<cmd>TmuxNavigateLeft<cr>")
  map("n", "<C-j>", "<cmd>TmuxNavigateDown<cr>")
  map("n", "<C-k>", "<cmd>TmuxNavigateUp<cr>")
  map("n", "<C-l>", "<cmd>TmuxNavigateRight<cr>")
end
```
I'd guess you could do something similar for `tmux.nvim` or go the `keys` route like @abeldekat suggested.

**Comment by imroc** [comment]
@abeldekat  Thanks a lot! It works, now I use this configuration (`tmux.lua`):
```lua
return {
  {
    "aserowy/tmux.nvim",
    keys = {
      {
        "<c-h>",
        function()
          require("tmux").move_left()
        end,
        desc = "tmux move left",
      },
      {
        "<c-j>",
        function()
          require("tmux").move_bottom()
        end,
        desc = "tmux move bottom",
      },
      {
        "<c-k>",
        function()
          require("tmux").move_top()
        end,
        desc = "tmux move top",
      },
      {
        "<c-l>",
        function()
          require("tmux").move_right()
        end,
        desc = "tmux move right",
      },
    },
    opts = {
      navigation = {
        enable_default_keybindings = false,
      },
    },
  },
}
```

And my `keymaps.lua`:

```lua
vim.keymap.del({ "i", "x", "n", "s" }, "<C-s>")
```

**Comment by abeldekat** [comment]
You're welcome!

**Comment by doodleEsc** [comment]
> > Currently, the only customization for default keymaps is to disable all default keymaps
> 
> I would argue that the statement above is not correct.
> 
> The `tmux` plugin, when `navigation.enable_default_keybindings = true`, creates the keybindings which will be overwritten by `LazyVim`'s keybindings in `lazyvim.config.keymaps.lua`.
> 
> Overriding a generic keybinding with a plugin keybinding is a special case. You have to create the keybindings yourself. This can be done in your own `config.keymaps.lua`. However, that file is intended for generic keybindings. Introducing plugins here is not recommended.
> 
> `LazyVim` will not override keybindings defined in the spec with `keys = `.
> 
> I recommend the following spec:
> 
>   {
>     "aserowy/tmux.nvim",
>     keys = {
>       {"<c-h>", function() require("tmux").move_left() end, desc = "tmux move left"},
>       {"<c-j>", function() require("tmux").move_bottom() end, desc = "tmux move bottom"},
>       {"<c-k>", function() require("tmux").move_top() end, desc = "tmux move top"},
>       {"<c-l>", function() require("tmux").move_right() end, desc = "tmux move right"},
>     },
>     opts = {
>       navigation = {
>         -- enables default keybindings (C-hjkl) for normal mode
>         enable_default_keybindings = false
>       }
>     },
>   }
> I do the same in my [config](https://github.com/abeldekat/nvim/blob/692deadd1c0e8dcadae971728d4d7efda97a0ea4/lua/plugins/editor.lua#L300), using these `ctrl keys` for `harpoon`.
> 
> In general, I only use `vim.keymap.del` if I want the keybinding removed instead of redefined. For example, `<S-h> <S-l>` to restore `Neovim`'s top and bottom navigation. The `<C-s>` keymapping can be removed in your own `config.keymaps.lua`:
> 
> for _, mode in pairs({ "i", "v", "n" }) do
>   vim.keymap.del(mode, "<C-s>")
> end
> Best regards!

Thank you!
