### ISSUE TITLE
bug: When enabling lang.clangd from LazyVim Extras, `nvim-cmp/lua/cmp/view.lua` outputs an error

### ISSUE THREAD

**Issue by funasoul** [LazyVim/LazyVim#1973]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

macOS 12.7.1

### Describe the bug

When enabling lang.clangd from LazyVim Extras, `nvim-cmp/lua/cmp/view.lua` outputs an error:
`   Error  23:13:36 notify.error ...ers/foo/.local/share/nvim/lazy/nvim-cmp/lua/cmp/view.lua:102: invalid order function for sorting`
As far as I remember, this error did not occur until a few weeks ago.

### Steps To Reproduce

1. launch nvim, and then `:LazyExtras`
2. enable `lang.clangd` and then restart nvim
3. open new file `foo.c` and then type `#include`
4. The error message will appear in noice.

### Expected Behavior

Previously, completion candidates were displayed, and no errors were shown.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
  {
    "LazyVim/LazyVim",
    import = "lazyvim.plugins",
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
Just tried with a fresh starter template and do not encounter the problem you mention. When i type `#include` the `nvim-cmp` menu opens to offer suggestions.

**Comment by funasoul** [comment]
@dpetka2001 Thank you for getting back to me so quickly.
Here, I attached my screencast, which only uses the above `repro.lua` and enables `lang.clangd`.

https://github.com/LazyVim/LazyVim/assets/1589676/017d7a72-c40b-40bd-ab65-ad88e8ac5870

Please let me know if you find any problem with my procedure.

**Comment by dpetka2001** [comment]
What version of Neovim are you using? I followed the exact steps in your demo and am not able to reproduce.

**Comment by funasoul** [comment]
I'm using 0.9.4.

**Comment by dpetka2001** [comment]
What is the directory `private`? Can you show output of `nvim --version`?

**Comment by funasoul** [comment]
The `private` directory is where the `/tmp` directory is created in macOS.
Here is the out put of `nvim --version`
```
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/local/share/nvim"

Run :checkhealth for more info
```

**Comment by dpetka2001** [comment]
My version is built with LuaJit 2.1.1692716794. I don't know if that matters. How did you install Neovim? Would you mind installing Neovim via [bob](https://github.com/MordechaiHadad/bob) and try to see if you have same issue?

**Comment by dpetka2001** [comment]
Also what do you see in line 102 of `private/tmp/c/.repro/plugins/nvim-cmp/lua/cmp/view.lua`?

**Comment by funasoul** [comment]
Thanks. I'll try `bob` later today.
line 102 of `/private/tmp/c/.repro/plugins/nvim-cmp/lua/cmp/view.lua` is as follows.
```
    -- sort.
    local comparetors = config.get().sorting.comparators
    table.sort(entries, function(e1, e2)                     <== line 102
      for _, fn in ipairs(comparetors) do
        local diff = fn(e1, e2)
        if diff ~= nil then
          return diff
        end
      end
    end)
    local max_item_count = config.get().performance.max_view_entries or 200
    entries = vim.list_slice(entries, 1, max_item_count)
```

**Comment by dpetka2001** [comment]
I don't know what to tell you because I'm also not very knowledgeable about Lua. My guess would be it has something to do with the version of LuaJit your Neovim is built with. Of course I might be entirely wrong. Please check with Neovim from `bob` in case that might solve your issue.

**Comment by funasoul** [comment]
@dpetka2001 Thank you for your help.
Today, MacPorts updated LuaJIT to version 2.1.1699491927, so I updated LuaJIT, and the above problem is solved.
The above problem did not occur with `nvim` installed using `bob` as you had advised.
Now that the problem is solved with the following version of `nvim` (MacPorts), so I will close this issue.

```
% nvim --version
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1699491927

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/local/share/nvim"

Run :checkhealth for more info
```
