### ISSUE TITLE
Termux ,,, lua server platform not supported 

### ISSUE THREAD

**Issue by Gul7333** [LazyVim/LazyVim#1982]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

Android 

### Describe the bug

I have lunar vim in termux, there lua server is installed with Mason ....
But on lazyvim it is saying
Current platform is not supported
....
Also typescript server is working...
But when i 
Const fs = require("fs")
Then I type "fs" and "dot" for suggestions but no suggestions come on module fs...
But other suggestions appear...
Screenshot is attached below
Remember 
I am not professional,,,, 

### Steps To Reproduce

Just install lua lua language server in mason on termux
Android 10
Tecno Pova LD7
![Screenshot_20231109-180453](https://github.com/LazyVim/LazyVim/assets/106809902/a8228153-66cb-4ed3-9e26-d80b3ef1f6c0)

### Expected Behavior

It should work with termux as we write code on the go with Mobile

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
I doubt this is a problem with Lazyvim. And I'm not sure how mason would work in Android with LunarVim and not LazyVim. Essentially it downloads the same package for the cpu architecture available on your phone. The error means that your cpu architecture isn't supported by `lua_ls` server (or at least there aren't prebuilt binary packages available to download and install with mason).

**Comment by Gul7333** [comment]
Ok... sorry for lunar vim ... Lunar vim also has same problem so I think it's lua problem.....👇👇👇
And can you help me in lsp suggestions
As when I code for example 
Const fs = require('fs')
Here suggestions appear
But when I write fs and dot ,,,,fs module suggestions ie(readFile() etc) should appear but they don't.....
In js file
I have typescript server
Suggestions are working but not for imported module

**Comment by dpetka2001** [comment]
Unfortunately I'm not familiar with typescript server and don't know much about it. If you would be kind to close this issue, since it's not a LazyVim problem, and ask in the Discussions section if you want anything additional regarding user configuration.

**Comment by Gul7333** [comment]
I would want you to make lazy vim stable on termux.... If you can....
As some err occur....

Closing issue

**Comment by dpetka2001** [comment]
If it's something related to Lazyvim then please create an issue. But if it's not Lazyvim related, then I doubt anything can be done from Lazyvim side(like `lua_ls` not being able to install because of unsupported platform). Either way I'm just a user like you. The maintainer is absent until November 21 (see pinned issue). I'm sure that if the problem you have is Lazyvim related, the maintainer will do his best to accommodate it.
