### ISSUE TITLE
How to continue scrolling down after using K

### ISSUE THREAD

**Issue by brumbyhhh** [LazyVim/LazyVim#1987]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

debian12

### Describe the bug

https://github.com/LazyVim/LazyVim/assets/93305122/8193523c-09fe-459e-99cf-b4ae344160c1
After using K, how to continue reading? For example, I want to know what the 37th function is. I tried ctrl + n or using the arrow keys but they don't let me scroll down to view.

### Steps To Reproduce

1. using K

### Expected Behavior

For example, it allows me to see more functions

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
`<C-f>` or `<C-b` to scroll or you can press `K` again and that will put your cursor in the flowting window and you'll be able to use normal vim motions.

**Comment by abeldekat** [comment]
Before creating a new bug, this is what is shown:

> Before reporting an issue, make sure to read the [documentation](https://github.com/folke/LazyVim) and search [existing issues](https://github.com/folke/LazyVim/issues). Usage questions such as "How do I...?" belong in [Discussions](https://github.com/folke/LazyVim/discussions) and will be closed.
Did you check docs and existing issues?
...etc

Why did you create this bug report, after confirming all the check boxes?

**Comment by dpetka2001** [comment]
I don't believe this is possible, since this hover menu is just a pop up window by noice which show you the docs. There's no LSP attached to it, since `ft = noice`.

**Comment by andresatierf** [comment]
Could there be a way to attach the LSP to this window? I think this is something really useful to be able to do and if it could be done in LazyVim by default, it would be awesome

**Comment by dpetka2001** [comment]
No idea. You could try issuing `:LspStart name_of_lsp_server` that you want and see if that works. You could create an issue with `enhancement` label, so that the maintainer can take it into consideration and see if it can be done or not. I'm not that adept with Lua myself.
