### ISSUE TITLE
Mini.Indentscope disabled by Alpha config while opening file directly

### ISSUE THREAD

**Issue by Shinzu** [LazyVim/LazyVim#199]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0-dev

### Operating system/version

Ubuntu 18.04

### Describe the bug

In https://github.com/LazyVim/LazyVim/blob/edd0fbb6a10f1a6fbcf12de92c20f430ea1bbc89/lua/lazyvim/plugins/ui.lua#L248 miniindentscope seems to be disabled "globally" when open a file directly with `nvim <filename>`. While open a over the alpha dashboard mini.indentscope is enabled correctly.

related issue in mini https://github.com/echasnovski/mini.nvim/issues/220

### Steps To Reproduce

1. open file directly via `nvim <filename>`
2. indentscope is disabled
3. open file over alpha
4. indentscope is working

### Expected Behavior

indentscope is working also while opening file directly

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by loiccoyle** [comment]
I can reproduce, removing the line at 
https://github.com/LazyVim/LazyVim/blob/edd0fbb6a10f1a6fbcf12de92c20f430ea1bbc89/lua/lazyvim/plugins/ui.lua#L248

fixes the issue, what was the reason for it in the first place?

**Comment by folke** [comment]
@loiccoyle that is to disable miniindentscope on the alpha dashboard. I'll change it in another way

**Comment by folke** [comment]
It actually is already taken care of, so that can just be deleted :)

Will push a new release in a bit

**Comment by loiccoyle** [comment]
> @loiccoyle that is to disable miniindentscope on the alpha dashboard. I'll change it in another way

Yeah I thought but unless there is some quirk with my setup, nothing changes on the alpha dashboard with or without it. There is no visible indentscope highlighting either way.

**Comment by folke** [comment]
Yep, exactly. The code below already took care of that. I probably added that in the alpha config block before I added the autocmd.

https://github.com/LazyVim/LazyVim/blob/320f5c6de78a8671393ef221bccc9dce8265d3e5/lua/lazyvim/plugins/ui.lua#L173-L178
