### ISSUE TITLE
bug: Conflict when using edgy.nvim and symbols-outline.nvim together

### ISSUE THREAD

**Issue by plokid** [LazyVim/LazyVim#1996]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.4

### Operating system/version

archlinux

### Describe the bug

When I try to use edgy.nvim and symbols-outline.nvim plugins together in lazyvim, I get the following error message: "The `edgy.nvim` extra must be **imported** before the `symbols-outline.nvim` extra to work properly." I'm not sure how to fix this issue. Can someone help me?

### Steps To Reproduce

1. Enable both edgy.nvim and symbols-outline.nvim plugins in lazyvim.
2. Open a code file.

### Expected Behavior

Both plugins should work together without any issues.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
How do you import the extras? From `LazyExtras` or in your `/lua/config/lazy.lua` file? The error tells you that `edgy` must be imported first, so you should do that.
