### ISSUE TITLE
bug: Creating a new line (lowercase and capital O) 

### ISSUE THREAD

**Issue by raveltan** [LazyVim/LazyVim#1998]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

MacOS 14.1.1

### Describe the bug

Using the key o and O on a flutter (dart) project causes a huge delay, the configuration used is the default configuration without any additional settings. (around 3 seconds)

### Steps To Reproduce

1. Install lazyvim as usual.
2. Install the flutter-tools.nvim
3. open a flutter project 
4. open a dart file
5. press o or O
6. it will take 3 or more second to response

### Expected Behavior

The command should be instant.

### Repro

```Lua
I am unable to setup a reproduceable example, but with the default settings, the key o and O has a huge delay
```

**Comment by dpetka2001** [comment]
I'm on Linux Mint 21.1 and followed these steps:
1. I installed `flutter` using the manual method from the [docs](https://docs.flutter.dev/get-started/install/linux#method-2-manual-installation)
2. Installed `flutter-tools.nvim` in a fresh Lazyvim starter template.
3. Navigated to the directory I exctracted the flutter git repo from installation step 1 and opened a random `.dart` file. 
4. Checked with `LspInfo` that `dartls` is attached to the buffer (it is attached successfully) and then pressed on a random line both `o` and `O` and could not reproduce the delay you observed. Both `o` and `O` created a new line below/above respectively instantly.

**Comment by raveltan** [comment]
Thanks for the response, I had checked my configuration again, and doing a completely clean install from scratch (including deleting all the caches directory). and the problem disappear. I assume that it might be related to the previous neovim distribution that I am using (and I only clean the config folder of neovim without clearing the cache for the initial installation). But anyway, Thank you for looking into the issue @dpetka2001, appreciate it!

**Comment by dpetka2001** [comment]
If you don't want to delete your default Neovim configuration every time, you should look into `NVIM_APPNAME` starting with Neovim 0.9+ onwards. It helps you keep multiple configurations in parallel and activate whichever you want. I have one only for testing purposes without messing my default Neovim config.

**Comment by raveltan** [comment]
Thanks, I will check it out!

**Comment by DerPesky** [comment]
I'm having this issue too, but only with dart files. Spikes CPU usage from 0.1% to 8.3% (maxes out a single core). What plugins are interacting with that? I had a similar issue in the past with freezing on copying due to "unnamedplus" before.

**Comment by amaanq** [comment]
It's a known issue with the dart parser, I would just disable indents for dart in your nvim-treesitter config
