### ISSUE TITLE
bug: `get_root` returning package directory not root directory in monorepos

### ISSUE THREAD

**Issue by briandipalma** [LazyVim/LazyVim#200]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.8.3

### Operating system/version

Linux

### Describe the bug

The `Find Files (root dir)` telescope search is rooted at the package directory when launched with a buffer open that has a file from a package loaded. So for example if I have a TypeScript package file open in a window and I launch a `root dir` search my search is limited to that package directory only and not the git repo I'm working in. This is due to the logic in `get_root` preferring `client.config.root_dir` over the `.git` root pattern.

```lua
-- returns the root directory based on:
-- * lsp workspace folders
-- * lsp root_dir
-- * root pattern of filename of the current buffer
-- * root pattern of cwd
---@return string
function M.get_root()
```

I honestly don't know what to suggest here...I feel a `root dir` is the root of the repo. I never set `client.config.root_dir` and it's set due to the presence of the `package.json` file by the language server (this issue goes away if I delete that file)?

If the `client.config.root_dir` check was dropped to the last option I think that would be reasonable as workspace folders would still be ahead of the `.git` root pattern search but I realize that's a breaking change.

This change might cause issues for people with git submodules but that's a weird layout in that you have a submodule inside a package...

### Steps To Reproduce

1. Create some nested directories with package.json files in them.
2. Open a TS file in the most deeply nested directory.
3. Try a `root dir` search.

### Expected Behavior

I'd expect my search to be rooted at the git repo directory.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by JoachimR** [comment]
@briandipalma thanks for raising this and also giving the answer. Just to clarify, you mean from the basic setup I should use `<leaver>fF` instead of `<leader>ff` to search in my mono repo?

from editor.lua:
```lua
      { "<leader>ff", Util.telescope("files"), desc = "Find Files (root dir)" },
      { "<leader>fF", Util.telescope("files", { cwd = false }), desc = "Find Files (cwd)" },
```

**Comment by briandipalma** [comment]
Yes correct, it's definitively something that makes me think a bit more about my searches as in some cases searching within a package is what I want to do and in some cases I want a monorepo search. For my personal ergonomics I'd prefer if monorepo search was the default but it's a minor issue so I leave the default keymaps as they are.
