### ISSUE TITLE
bug: error when triggering LSP code action

### ISSUE THREAD

**Issue by tiberiuichim** [LazyVim/LazyVim#2004]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1418+g15983cf2c

### Operating system/version

Ubuntu 22.04

### Describe the bug

I get this error when I trigger a code action:

```
    1    Error  10:32:25 msg_show.lua_error Error executing vim.schedule lua callback: ...azy/lazy/dressing.nvim/lua/dressing/select/telescope.lua:29: attempt to index field 'ctx' (a nil value)       
   21 stack traceback:                                                                                                                                                                                   
    1 │ ...azy/lazy/dressing.nvim/lua/dressing/select/telescope.lua:29: in function <...azy/lazy/dressing.nvim/lua/dressing/select/telescope.lua:8>                                                      
    2 │ ...azy/lazy/dressing.nvim/lua/dressing/select/telescope.lua:137: in function 'select'                                                                                                            
    3 │ ...vim-lazy/lazy/dressing.nvim/lua/dressing/select/init.lua:70: in function ''                                                                                                                   
    4 │ vim/_editor.lua: in function <vim/_editor.lua:0> 
```

### Steps To Reproduce

In all the code that I'm trying this, I get the error. To reproduce, in a source code, type `<leader>ca`

### Expected Behavior

No crash, valid input from LSP for the available code actions.

### Repro

Note: I'm not able to reproduce this problem with the default minimal setup, as it doesn't seem to enable LSP and LazyExtra or the Mason commands are not available.

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by abeldekat** [comment]
Update dressing.nvim

https://github.com/stevearc/dressing.nvim/issues/126

**Comment by tiberiuichim** [comment]
Many thanks!

**Comment by abeldekat** [comment]
You're welcome!

**Comment by ditadi** [comment]
@tiberiuichim @abeldekat hey guys, 

I updated lazyvim by the Lazy dashboard, but I still have this issue.

I checked the lazy-lock.json and the commit on Dressing is the last one. (fe30713)
Is it necessary to do another update?

**Comment by tiberiuichim** [comment]
@ditadi An hour after I reported that updating Dressing fixed my problem, I had it happen again. Based on the comments from linked dressing issues, I realized that I need to update and recompile Neovim to solve this, which is what I did and I didn't have problems again.
