### ISSUE TITLE
Does anyone know the plugin name's that pops up the documentation box when you hit Shift + K?

### ISSUE THREAD

**Issue by mendesbarreto** [LazyVim/LazyVim#2010]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

Hey all,

Quick question: Does anyone know the plugin that pops up the documentation box when you hit Shift + K? I'm looking to tweak the background colour to a darker shade; it's a bit tricky to distinguish it from the code background right now, and it's bugging me. Thanks!

![Screenshot 2023-11-13 at 10 18 15 PM](https://github.com/LazyVim/LazyVim/assets/2684784/83b615c4-549f-4d40-84b9-bcb26e6df665)

**Comment by abeldekat** [comment]
> Before reporting an issue, make sure to read the [documentation](https://github.com/folke/LazyVim) and search [existing issues](https://github.com/folke/LazyVim/issues). Usage questions such as "How do I...?" belong in [Discussions](https://github.com/folke/LazyVim/discussions) and will be closed.
Did you check docs and existing issues?
... etc ...

You checked all the boxes before creating this bug report. Still, you registered a **bug** to ask your question here. Is there a specific reason for doing so?

Best regards!

**Comment by dpetka2001** [comment]
Questions about user configurations are meant to be in the `Discussions` section like @abeldekat mentioned. Kindly close this and open a Discussion instead.

**Comment by mendesbarreto** [comment]
Thank you for the head up

**Comment by dpetka2001** [comment]
Regarding your question, in LazyVim `noice` is the plugin that decorates the LSP hover docs. You could try something like
```lua
  {
    "folke/noice.nvim",
    opts = {
      presets = {
        lsp_doc_border = true,
      },
    },
  },
```
to have borders around the LSP hover docs to make it more distinguishable from the background actual code.
