### ISSUE TITLE
bug: formatting in C# files do not work

### ISSUE THREAD

**Issue by rpisarew** [LazyVim/LazyVim#2016]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.4 Build type: Release LuaJIT 2.1.1699524327

### Operating system/version

MacOS Ventura 13.6

### Describe the bug

When I try to format a C# file, I get a lag for like half a second and then I get the message: Formatter 'csharpier' timeout.

When I execute the formatter on the command line (dotnet csharpier ..) it works without any issues.

### Steps To Reproduce

1. Open a C# file
2. try to format

### Expected Behavior

File should be formatted

### Repro

```Lua
no changes stock from starter repo
```

**Comment by dpetka2001** [comment]
Did you install the `omnisharp` from `LazyExtras`?

**Comment by rpisarew** [comment]
Yes, my LSP is working for C#.

![grafik](https://github.com/LazyVim/LazyVim/assets/3972970/3b0722a7-ac1a-4b2e-a042-c644e3536fd9)

**Comment by dpetka2001** [comment]
I meant if you enabled the whole `lang.omnisharp` extra from `LazyExtras`. Just to clarify.

**Comment by rpisarew** [comment]
Yes, it's enabled:

![grafik](https://github.com/LazyVim/LazyVim/assets/3972970/bca054c5-41d5-4556-a419-6ac9bae92cf1)

**Comment by dpetka2001** [comment]
I don't know anything about C#, I just tried to confirm if the formatter worked or not. I installed `dotnet` for my distro (Linux Mint) and also enabled the extra `lang.omnisharp` and then created a project with `dotnet new console -n test` and the formatter works as it should (although I do observe about half a second delay for it to format, but I guess that's something related to `csharpier` itself). What is the output of `LazyFormatInfo` and `ConformInfo`?

**Comment by dpetka2001** [comment]
Plz show output of `LazyFormatInfo` and `ConformInfo`. For me both show that `csharpier` is enabled for the buffer. Maybe something is wrong with your formatter?

**Comment by rpisarew** [comment]
LazyFormatInfo:
![grafik](https://github.com/LazyVim/LazyVim/assets/3972970/1eb8c752-541a-47a1-a6ec-6dcb63958b0b)

ConformInfo:
![grafik](https://github.com/LazyVim/LazyVim/assets/3972970/17b6c454-1fa4-471b-a361-b6609f66004e)

Tested on a new C# console project.

**Comment by dpetka2001** [comment]
The output of the commands is the same for me as well. Unfortunately, I can't reproduce this. It works fine for me. Sorry I can't be of more help.

**Comment by rpisarew** [comment]
No worries, thanks for your time :)

**Comment by abeldekat** [comment]
Does `:Mason` offer an update for csharpier?
Perhaps your commandline version differs from the version Mason installed.

**Comment by rpisarew** [comment]
@abeldekat No, everything is up to date.

**Comment by 2giosangmitom** [comment]
Which version of dotnet-sdk are you using?

**Comment by rpisarew** [comment]
This are my installed SDKs (arm64):
![grafik](https://github.com/LazyVim/LazyVim/assets/3972970/ac6569f7-4569-482e-a0fd-21a874250e07)

My projects for my work are using dotnet 6.

**Comment by 2giosangmitom** [comment]
> This are my installed SDKs (arm64): ![grafik](https://user-images.githubusercontent.com/3972970/283077586-ac6569f7-4569-482e-a0fd-21a874250e07.png)
> 
> My projects for my work are using dotnet 6.

I just tested again with dotnet-6.0. `ConformInfo`:
![image](https://github.com/LazyVim/LazyVim/assets/87252943/933fc0d2-991d-4049-8bfe-9fd4bd06b652)


I tried reinstalling `csharpier` from `Mason` and it worked.

**Comment by rpisarew** [comment]
> > This are my installed SDKs (arm64): ![grafik](https://user-images.githubusercontent.com/3972970/283077586-ac6569f7-4569-482e-a0fd-21a874250e07.png)
> > My projects for my work are using dotnet 6.
> 
> I just tested again with dotnet-6.0. `ConformInfo`: ![image](https://user-images.githubusercontent.com/87252943/283082143-933fc0d2-991d-4049-8bfe-9fd4bd06b652.png)
> 
> I tried reinstalling `csharpier` from `Mason` and it worked.

I had the same issue and reinstall helped me too, but I still get the timeout message in VIM but in the terminal it works.

**Comment by dpetka2001** [comment]
Do `:echo stdpath("data")`.

**Comment by abeldekat** [comment]
> In which directory Mason installs the binaries?
> ....
> $home/.config/local/share/nvim

That's a strange location given that your `conform.log` is in `/Users/yourname/.local/state/nvim/conform.log`. 
I would expect the directory to be `/Users/yourname/.local/share/nvim/mason/bin`

In [this](https://github.com/LazyVim/LazyVim/issues/2016#issuecomment-1812170780) comment you write:

> I had the same issue and reinstall helped me too, but I still get the timeout message in VIM but in the terminal it works.

Am I correct to understand that the formatting now works in `Neovim`, but you still get the timeout message?

Would you be able to try using [stock lazyvim starter](https://github.com/LazyVim/starter), only adding the minimum required plugins, like `lang.omnisharp`?

**Comment by livghit** [comment]
Maybe try csharpier instead of omnisharp ?

**Comment by rpisarew** [comment]
> > In which directory Mason installs the binaries?
> > ....
> > $home/.config/local/share/nvim
> 
> That's a strange location given that your `conform.log` is in `/Users/yourname/.local/state/nvim/conform.log`. I would expect the directory to be `/Users/yourname/.local/share/nvim/mason/bin`
> 
> In [this](https://github.com/LazyVim/LazyVim/issues/2016#issuecomment-1812170780) comment you write:

Weird I didn't noted that, but I tried it again and the path was right this time:
![grafik](https://github.com/LazyVim/LazyVim/assets/3972970/eda34c30-29a0-4a99-ae84-0779a24a1910)

> 
> > I had the same issue and reinstall helped me too, but I still get the timeout message in VIM but in the terminal it works.
> 
> Am I correct to understand that the formatting now works in `Neovim`, but you still get the timeout message?

No, in that case there were an error when I executed csharpier in the terminal (a lib was missing), but after reinstall it started to work in the terminal, but not in VIM.

> Would you be able to try using [stock lazyvim starter](https://github.com/LazyVim/starter), only adding the minimum required plugins, like `lang.omnisharp`?

I will try that.

**Comment by rpisarew** [comment]
> Maybe try csharpier instead of omnisharp ?

I try it with csharpier..

**Comment by dpetka2001** [comment]
So you have 2 versions of `csharpier` installed? One local which you installed yourself and one installed by Mason via the extra `lang.omnisharp`?

**Comment by rpisarew** [comment]
> So you have 2 versions of `csharpier` installed? One local which you installed yourself and one installed by Mason via the extra `lang.omnisharp`?

That's right. I used `dotnet tool install -g csharpier` to install it for my system globally.

**Comment by dpetka2001** [comment]
What does `:!which csharpier` say?

**Comment by rpisarew** [comment]
> What does `:!which csharpier` say?

```
:!which csharpier
shell returned 1
```

**Comment by rpisarew** [comment]
I found a solution.
The issue was that `conform` does not properly pipe the buffer to `stdin`, because of that I was receiving the timeout message (default: 500ms).

I think there is a issue in `comform`, I will try to open a issue there.

My current workaround is to use the file path instead of the pipe:
```
  {
    "stevearc/conform.nvim",
    opts = {
      formatters_by_ft = {
        cs = { "csharpier" },
      },
      formatters = {
        csharpier = {
          command = "dotnet-csharpier",
          args = { "--write-stdout", "$FILENAME" },
        },
      },
    },
  },
```
