### ISSUE TITLE
bug: LazyVim not working with th official Github Copilot plugin.

### ISSUE THREAD

**Issue by itzcodex24** [LazyVim/LazyVim#2018]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

MacOS 13.4.1

### Describe the bug

I have tried installing the Github Copilot successfully which works.
```
return {
  "github/copilot.vim",
}
```

When I run the `Copilot status` command, I receive the following error: `:Copilot <Tab> map has been disabled or is claimed by another plugin`

I am able to suppress this error by adding the following line to the `init.lua` file within my custom config

```
vim.g.copilot_assume_mapped = true
```

I can now view suggestions in line with the code that I am writing which is what I want. The only problem is that now, I cannot accept the suggestion by pressing Tab **WHILST** in INSERT mode.

The reason why I don't want to use the Copilot extra provided by LazyVim is because of the reason that I cannot seem to configure it to show suggestions in line with the code rather than in the dialog box and accept it using the Tab key.

### Steps To Reproduce

1. Install Github Copilot plugin
2. Run `Copilot auth`
3. Run `Copilot status` - Note this should show the error described above
4. Add the line to suppress this error in the `init.lua` file in config
5. Write some code to view suggestions in real time **IN LINE**.
6. Notice that pressing Tab only creates an indent and does not accept the solution.

### Expected Behavior

When pressing Tab, we should expect the suggested code to be accepted and written into the current file.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
`<Tab>` is used by Lualine for navigation through its nodes. You can disable it if you don't like it. I don't think this is a LazyVim issue, rather a user configuration issue and more appropriate to the Discussions section.

**Comment by itzcodex24** [comment]
I have not touched any of the default configuration since installing LazyVim just yesterday and after installing the Github Copilot plugin I noticed this functionality not working.

**Comment by itzcodex24** [comment]
In addition, I cannot see any keymaps which consist of only the `<Tab>` key on the LazyVim documentation under Keymaps

**Comment by dpetka2001** [comment]
Github Copilot itself tells you that the keymap is claimed by another plugin. That plugin is `Luasnip` in LazyVim. I misspoke when I said `Lualine` in my previous comment. So, LazyVim already has `<Tab>` mapped to another plugin. You can either disable that mapping or choose a new keymap for Copilot, whichever you like. You cannot see the keymap in documentation under Keymaps, because in that doc only the general keymaps are mentioned. The plugins' keymaps are mentioned inside each plugin. See here for [Luasnip](https://www.lazyvim.org/plugins/coding#luasnip) and press `Full spec`. Still not a LazyVim issue, rather a user configuration issue, which is more appropriate in the Discussion section.

**Comment by Jomik** [comment]
Why not use [the copilot extra](https://www.lazyvim.org/extras/coding/copilot)?

**Comment by abeldekat** [comment]
> The reason why I don't want to use the Copilot extra provided by LazyVim is because of the reason that I cannot seem to configure it to show suggestions in line with the code rather than in the dialog box and accept it using the Tab key.

I agree with @dpetka2001. You want to know how to configure the plugin to use the `tab` key.

> Before reporting an issue, make sure to read the [documentation](https://github.com/folke/LazyVim) and search [existing issues](https://github.com/folke/LazyVim/issues). 
>
> Usage questions such as "How do I...?" belong in [Discussions](https://github.com/folke/LazyVim/discussions) and will be closed.

Kindly close this issue and ask your question in the discussion section.

**Comment by itzcodex24** [comment]
Thank you, will check over the documentation and open a discussion if necessary.

**Comment by khongtrunght** [comment]
@itzcodex24 Do you have any solution to this problem? I have trouble similar to you.
