### ISSUE TITLE
bug: Next Occurence Keymap Appears to be Broken

### ISSUE THREAD

**Issue by cerbervs** [LazyVim/LazyVim#2019]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

Arch 6.6.1-arch1-1

### Describe the bug

After performing plugin updates this morning, all of which seemed unrelated to the "n"/"N" search motions, next occurence broke. When using the "n" key for moving to the next occurence of a search term the cursor moves forward by one character instead of going to the next occurence. Previous occurence "N" works just fine. There were no breaking when updating plugins, listed by Lazy, that should have affected the way the "n" key functions and nothing else in my config has changed.

### Steps To Reproduce

1. Open nvim
2. Search with either / or ?
3. Press "n"

### Expected Behavior

Move to next occurence of search term

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  "folke/zen-mode.nvim",
  "mg979/vim-visual-multi",
  "nelsyeung/twig.vim",
  "rest-nvim/rest.nvim",
  "nvimtools/none-ls.nvim",
  "NeogitOrg/neogit",
  "iamcco/markdown-preview.nvim",
  "tpope/vim-dadbod",
  "davidmh/cspell.nvim",
  "norcalli/nvim-colorizer.lua"
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
I cannot reproduce this with fresh Lazyvim starter template. Can you try with new Lazyvim starter template? If you can't observe the same behavior with the new Lazyvim starter template, then it's probably some problem with your configuration.

**Comment by cerbervs** [comment]
Sure thing, I'll give it a go now.

**Comment by cerbervs** [comment]
@dpetka2001 It was my config. Closing the issue. Thanks!
