### ISSUE TITLE
bug: Search abruptly ends and Neovim returns to normal mode

### ISSUE THREAD

**Issue by SamiKalliomaki** [LazyVim/LazyVim#2055]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.4

### Operating system/version

Docker

### Describe the bug

Search abruptly ends and the cursor jumps to a "random" location returning to normal mode. Sequences that trigger the issue seem to depend on the file contents?

### Steps To Reproduce

1. Start a default LazyVim Neovim instance e.g.
```
docker run -w /root -it --rm alpine:edge sh -uelic '
  apk add git lazygit neovim ripgrep alpine-sdk --update
  git clone https://github.com/LazyVim/starter ~/.config/nvim
  cd ~/.config/nvim
  nvim
'
```

2. Create a new file and type content `asdasdasd`
3. Return to normal mode
4. Type `/asdd` (No enter)
5. Observe cursor jumps to the nearest letter `a` and Neovim returns to normal mode.

For the file `asdasdasd`, for example `/asf` also triggers the issue but `/asr` does not.

### Expected Behavior

Similar to any other search that is not found in the file, the search remains active.

### Repro

```Lua
Default starter config
```

**Comment by SamiKalliomaki** [comment]
The issue does not reproduce in a config without LazyVim e.g.
```
docker run -w /root -it --rm alpine:edge sh -uelic '
  apk add git lazygit neovim ripgrep alpine-sdk --update
  nvim
'
```

**Comment by dpetka2001** [comment]
It's probably `flash.nvim`. Pls see #1410 for how to fix it. Also since this seems to be a user configuration issue, I believe it's more appropriate for the Discussions section.

**Comment by SamiKalliomaki** [comment]
Thank you, that seems to be the plugin causing the unexpected behavior.
