### ISSUE TITLE
bug: Unable to override or disable telescope.builtin.lsp_references keymap 

### ISSUE THREAD

**Issue by averche** [LazyVim/LazyVim#2056]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.4

### Operating system/version

MacOS 13.5.2

### Describe the bug

Following the [docs example](https://www.lazyvim.org/configuration/plugins#%EF%B8%8F-adding--disabling-plugin-keymaps), I created the following telescope config:

~/.config/nvim/lua/plugins/telescope.lua:

```lua
return {
  "nvim-telescope/telescope.nvim",
  keys = {
    {
      "gr", -- changing this to "<leader>gr" fixes the issue (the new keymap works)!
      function()
        require("telescope.builtin").lsp_references({
          show_line = false,
        })
      end,
      desc = "References",
    },
  },
}
```

However, the `gr` keymap still results in the old behaviour.

Similarly:

```lua
return {
  "nvim-telescope/telescope.nvim",
  keys = {
    { "gr", false }, -- does not disable the keymap
  },
}
```

If I switch the keymap to something else, e.g. `<leader>gr`, the new keymap works correctly along with the old `gr` keymap (with old behavior).

### Steps To Reproduce

1. Create the configuration file above
2. `nvim main.go`
3. Use `gr` keymap on a variable.
4. Notice that the default LSP references screen is brought up (it does not respect `show_line = false` setting).

### Expected Behavior

I expect the `gr` keymap to invoke the new (modified) `lsp_references` implementation.

**Comment by dpetka2001** [comment]
This is not a bug. Did you read the [docs](https://www.lazyvim.org/plugins/lsp#%EF%B8%8F-customizing-lsp-keymaps) about how to change LSP keymaps? It's not the same way as changing a plugin's keymap, but similar.

**Comment by averche** [comment]
Thanks @dpetka2001, this worked!
