### ISSUE TITLE
bug: Error opening typescript files in a project

### ISSUE THREAD

**Issue by NguyenHoangHieu22GIT2** [LazyVim/LazyVim#2061]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.(I forgot the number, 0 maybe) dev

### Operating system/version

Linux ( Pop Os)

### Describe the bug

All I did was clone lazyvim, let them install, do some LspInstall and TSInstall. Then it's pretty much done for my configs.

I go straight to develop my typescript project (Nest.JS) and this error keeps popping up in each file :

```
E5108: Error executing lua ...u/.local/share/nvim/lazy/LazyVim/lua/lazyvim/util/ui.lua:16: attempt to index local 'ret' (a nil value)
stack traceback:
	...u/.local/share/nvim/lazy/LazyVim/lua/lazyvim/util/ui.lua:16: in function <...u/.local/share/nvim/lazy/LazyVim/lua/lazyvim/util/ui.lua:13>
	vim/shared.lua: in function 'tbl_map'
	...u/.local/share/nvim/lazy/LazyVim/lua/lazyvim/util/ui.lua:13: in function 'get_signs'
	...u/.local/share/nvim/lazy/LazyVim/lua/lazyvim/util/ui.lua:98: in function <...u/.local/share/nvim/lazy/LazyVim/lua/lazyvim/util/ui.lua:87>
```

It's kinda annoying since it's popping in every file. Even though it doesn't break any functionality, looking at the message pissing me off. I have used lazyvim with windows and everything was fine. but in Pop Os, it's pretty painful :(

### Steps To Reproduce

1. Clone Lazyvim starter pack
2. Open neovim and install Lsp and TS
3. Open up A project ( Nest.JS ) and encounter the error.

### Expected Behavior

I want the error message to go away. or be more precise, I want the error getting fixed.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
Probably duplicate of #2039

**Comment by NguyenHoangHieu22GIT2** [comment]
> Probably duplicate of #2039

What really ? Let me, I tried to find in issues tab but not successful, maybe because I don't know the error's name. Let me check it, if it's a duplicate, I am sorry

**Comment by NguyenHoangHieu22GIT2** [comment]
Welp it is fixed. Thank you for guiding me :)
