### ISSUE TITLE
feature: `Go to definition` inside lsp hover

### ISSUE THREAD

**Issue by andresatierf** [LazyVim/LazyVim#2073]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

It's not possible to `Go to definition` inside the lsp hover window. Discussed in #1987

### Describe the solution you'd like

Being able to press the keymap `Go to definition` and it working

### Describe alternatives you've considered

can't think of one

**Comment by folke** [comment]
That's not possible
