### ISSUE TITLE
feature: debugging

### ISSUE THREAD

**Issue by AmitGolden** [LazyVim/LazyVim#208]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Setting up debugging by hand could take a long time, and requires a lot of knowledge in how dap works.
Having this already set up would be a major time saver

### Describe the solution you'd like

Including nvim-dap, nvim-dap-ui, and setting them up for popular languages, also adding keybindings for it.
Also including unit test debugging would be cool

### Describe alternatives you've considered

Setting it up myself, which took a long time, resulting in a not very good end result

**Comment by dpetka2001** [comment]
There is already an open [PR](https://github.com/LazyVim/LazyVim/pull/24) in which the maintainer has expressed that he would
rather not include such tools in LazyVim by default. I've no idea if his stance has changed since, but in this PR you can find great examples of how you can configure dap yourself.

**Comment by Jomik** [comment]
I think it makes sense to set up and configure `nvim-dap` with friends (`nvim-dap-mason`) and some sane keybindings, etc.
Then leave it to the user to enable various debug adapters, similar to how the typescript extras hook into treesitter and mason.

**Comment by SamPosh** [comment]
Like kickstarter nvim config ,it is better to add basic debug support as @Jomik mentioned

**Comment by folke** [comment]
I just pushed a bunch of updates that properly integrates dap.

See the docs here https://www.lazyvim.org/plugins/extras/dap.core

Example for the Neovim lua adapter:

![image](https://user-images.githubusercontent.com/292349/232338656-d8f5dfb7-8c1d-4c49-964b-9999e5efd227.png)

**Comment by catdadcode** [comment]
> See the docs here https://www.lazyvim.org/plugins/extras/dap.core

[Fixed link](https://www.lazyvim.org/extras/dap/core)
