### ISSUE TITLE
bug: `Telescope notify` gives out some wierd error

### ISSUE THREAD

**Issue by rjshrjndrn** [LazyVim/LazyVim#2086]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.4
![image](https://github.com/LazyVim/LazyVim/assets/2563385/47749e62-ebf7-42f9-a0a7-18b6f201c4da)

### Operating system/version

arch

### Describe the bug

Open nvim
`:w` which will throw error in nvim-notify.
open `:Telescope notify` and you'll get another error of index out of bound

![image](https://github.com/LazyVim/LazyVim/assets/2563385/891d257e-ea96-4013-92d7-70e93f121d75)

### Steps To Reproduce

Open nvim
`:w` which will throw error in nvim-notify.
open `:Telescope notify` and you'll get another error of index out of bound

### Expected Behavior

No random error

**Comment by dpetka2001** [comment]
The error `No file name` occurs when you try to write to a newly created buffer without specifying the name that you want to save it or when you do `:w` when the dashboard is still open. I don't get any error when opening `Telescope notify`. More info with a reproducible example would be great.

**Comment by abeldekat** [comment]
Please also test with an unmodified lazyvim starter:

```lua
cd ~/.config
git clone https://github.com/lazyvim/starter.git lazytest
cd lazytest
NVIM_APPNAME=lazytest nvim init.lua
```

Reboot after installation. If the problem is related to your config, I expect no errors.

**Comment by abeldekat** [comment]
Glad to hear that you found the cause of the issue.
If you think that your config is correct you could file an issue in the `nvim-notify` repro.

Could you close this issue?

Best regards!

**Comment by rjshrjndrn** [comment]
Thank you @abeldekat for your guidance.
Sure @dpetka2001 I'll raise the issue in nui.

**Comment by dpetka2001** [comment]
@rjshrjndrn actually this happens only if you have `render = "wrapped-compact"`. So it might be a `nvim-notify` issue after all. If you comment that line in your configuration no error occurs. I'm really not sure which of the 2 plugins is at fault here.

**Comment by abeldekat** [comment]
When this is only happening when render = "wrapped-compact" I think this is an nvim-notify issue.

**Comment by rjshrjndrn** [comment]
Yup, @dpetka2001 thank you for that astute observation. I'll raise the issue in nvim-notify, all will pivot from there.

**Comment by abeldekat** [comment]
@dpetka2001, interesting!
So, the problem does not occur when notice is disabled?

**Comment by dpetka2001** [comment]
But `max_width = 25` throws the same error. It seems that `noice` must be taking into account the Telescope's previewer size into consideration somehow? Don't know. Just a guess.

**Comment by rjshrjndrn** [comment]
wow, it's just amazing to listen to 2 experts discussing the possibilities. 
Sorry, but it really interesting, even though most of the things are just independent Lego blocks for me. 
@dpetka2001 I took the width calculation from https://www.lazyvim.org/plugins/ui#nvim-notify. I just reduced the multiplication factor from .75 to .3.

**Comment by abeldekat** [comment]
I don't think its telescope because telescope only uses plenary.

**Comment by dpetka2001** [comment]
Under no circumstances can i be considered an expert. I have very basic programming knowledge. Just experienced with my LazyVim configuration and like to dig into things.
That aside it seems that I misunderstood then. I thought `max_width` was the maximum number of columns at which the wrapping would take effect, but it's actually the size of the window that will pop up. Upon more consideration, I would go with creating an issue at `nvim-notify` for starters, since the error occurs when `render = "wrapped-compact`. The maintainer should be able to guide you if it's actually a problem of `nvim-notify` or `nui.nvim` or `noice.nvim`. All I do is trying to guess based on observing the behavior I see happening.
