### ISSUE TITLE
bug: ERROR Failed to run healthcheck for "provider" plugin. Exception:     6   Vim:E15: Invalid expression: "\m[^\-.a-zA-Z_/]'' ? shellescape(v:val) : v:val"

### ISSUE THREAD

**Issue by wxzvim** [LazyVim/LazyVim#2087]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev

### Operating system/version

wsl

### Describe the bug

into command mode,execute checkhealth: export follow errror
![image](https://github.com/LazyVim/LazyVim/assets/110797126/3733d7c0-de44-475b-b813-d59500e38ac8)

### Steps To Reproduce

into command mode
:checkhealth
![image](https://github.com/LazyVim/LazyVim/assets/110797126/7eb44b10-6db9-40a0-8050-14265b517011)

### Expected Behavior

![image](https://github.com/LazyVim/LazyVim/assets/110797126/b714f991-ceb3-4e0f-ab17-d08cef843d58)

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
I fail to see how this is a LazyVim problem. There's something wrong with the npm neovim package. You can either create an issue at Neovim repo itself or in the npm package repo to get this resolved.

**Comment by abeldekat** [comment]
Hello @wxzvim, 

As @dpetka2001 said, this error is not related to LazyVim.
Could you close this issue?
