### ISSUE TITLE
feature: Disable nvim-cmp in plain-text files

### ISSUE THREAD

**Issue by averche** [LazyVim/LazyVim#209]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

I find `nvim-cmp` auto completion quite useful in code but a bit intrusive when just writing a plain-text or a markdown file.

### Describe the solution you'd like

Ideally, I would prefer to have `nvim-cmp` plugin conditionally loaded when opening code files and disabled otherwise. 

### Describe alternatives you've considered

A good alternative would be an easy way to toggle `nvim-cmp` while in neovim (perhaps from `<leader>l` menu or with a simple `: command`. I'm able to run the following and it works, but it's a lot to remember:

```vim
:lua require('cmp').setup.buffer { enabled = false }
```

### Additional context

Please excuse me if I'm missing something obvious, I'm new to LazyVim :)

**Comment by folke** [comment]
I'm not going to add anything special for this in LazyVim. You can create your own mapings to toggle cmp. Check their docs for what you need

**Comment by averche** [comment]
I was not expecting anything special, rather a more sensible default, but I understand your position.

Thanks for developing LazyVim 👍

**Comment by droctothorpe** [comment]
I found this issue in nvim-cmp but I'm not sure how to integrate it with lazyvim. Any suggestions would be greatly appreciated. Thank you!

https://github.com/hrsh7th/nvim-cmp/issues/1522
