### ISSUE TITLE
bug: Unable to get rust_analyzer to work

### ISSUE THREAD

**Issue by kingedward35** [LazyVim/LazyVim#210]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0-dev-771+g18fb669b9

### Operating system/version

Macos 12.4

### Describe the bug

I have recently installed LazyVim and I am trying to use it for some rust development. However the rust_analyzer doesn't display any lsp information in the editor. I know I have it installed and it runs and indexing when I open a rust file, but even when I intentionally type errors in a file, I don't get any of the diagnostics information to display. I have this working in other neovim configurations on my system, but can't seem to get it to work using LazyVim. I was wondering if there was some configuration options that I might be missing to get things to work properly. Thanks.

### Steps To Reproduce

Installed LazyVim starter.
Installed the rust_analyzer via Mason.
Opened up a rust project with toml and cargo files.
Type `printf("Hello World!");` in a `main.rs` file and function.
No diagnostic information.

### Expected Behavior

Should see diagnostic information from rust_analyzer.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
There's nothing different with LazyVim, so this is **not** a bug.

Please debug yourself before posting issues here.

This could help: https://github.com/LazyVim/LazyVim/pull/24
