### ISSUE TITLE
feature: Dashboard should have a section for display some news about Neovim.

### ISSUE THREAD

**Issue by Parables** [LazyVim/LazyVim#2108]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

I just read about [the passing of Bram Moolenaar:](https://github.com/neovim/neovim/releases/tag/v0.9.2).

It would be nice if there could be an section on the LazyVim's Dashboard, that shows news about Vim and Neovim; it could be about new releases, breaking changes and important prompts/notifications like `:help Bram` and `:help Uganda` should be all included on the Dashboard...  

### Describe the solution you'd like

See some of the default Vim/Nvim dashboard contents like :help Bram and :help Uganda on LazyVim's Dashboard.

### Describe alternatives you've considered

None at the moment

**Comment by dpetka2001** [comment]
There's a shortcut `<leader>L` about `LazyLog` that shows the latest changes in LazyVim. The rest is mostly personal preference and a user can add them to his personal config. Personally, I wouldn't want to see something like that on my Dashboard. I prefer to only have essential actions that get me started.
