### ISSUE TITLE
feature: Biome formatter

### ISSUE THREAD

**Issue by liamwh** [LazyVim/LazyVim#2116]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

[Biome](https://biomejs.dev/formatter/#use-the-formatter-with-the-cli) won the [prettier in Rust contest](https://prettier.io/blog/2023/11/27/20k-bounty-was-claimed), with >95% compatibility with Prettier. Is it an idea to directly support Biome in conform somehow?

### Describe the solution you'd like

An extra or something to use Biome over Prettier / Prettierd.

### Describe alternatives you've considered

N/A

**Comment by madflow** [comment]
You can already use "Biome"s LSP in Neovim: https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/biome.lua . If you jst want Biomes formatting - maybe [turning off](https://biomejs.dev/reference/configuration/#linterenabled) the linter will suffice.

**Comment by jsonMartin** [comment]
I also think it would be great to add an out of the box configuration setup for Biome within LazyVim, as it's quickly replacing prettier. Biome's plugin works well in VSCode and I need Neovim's behavior to match for cross-compatibility in the same projects.

It took some light digging to figure out to get Biome to work within LazyVim, but fortunately it's not too complicated. Inside my `~/.config/nvim/lua/plugins/plugins.lua` file, I ensured `biome` is installed in `mason`, and disabled `conform` plugin for formatting (since Biome also handles that). 

```lua
return {
  -- Use Biome instead of prettier / eslint
  {
    "stevearc/conform.nvim",
    enable = false,
  },
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "biome",
      },
    },
  },
}
```

Seems to work for me so far with this now, I tested in `js`, `tsx`, and `python` files and they both lint and format successfully 😃

**Comment by kyrisu** [comment]
You don't need to disable conform as it supports biome.
The following config works:

```lua
return {
  {
    "stevearc/conform.nvim",
    optional = true,
    opts = {
      -- for language support
      -- @see https://biomejs.dev/internals/language-support/
      formatters_by_ft = {
        ["javascript"] = { "biome" },
        ["javascriptreact"] = { "biome" },
        ["typescript"] = { "biome" },
        ["typescriptreact"] = { "biome" },
        ["json"] = { "biome" },
        ["jsonc"] = { "biome" },
        -- ["vue"] = { "biome" },
        -- ["css"] = { "biome" },
        -- ["scss"] = { "biome" },
        -- ["less"] = { "biome" },
        -- ["html"] = { "biome" },
      },
    },
  },
}
```

References:
- [biome supported languages](https://biomejs.dev/internals/language-support/)
- [conform supported formatters](https://github.com/stevearc/conform.nvim?tab=readme-ov-file#formatters)

**Comment by binhtran432k** [comment]
> You don't need to disable conform as it supports biome. The following config works:
> 
> ```lua
> return {
>   {
>     "stevearc/conform.nvim",
>     optional = true,
>     opts = {
>       -- for language support
>       -- @see https://biomejs.dev/internals/language-support/
>       formatters_by_ft = {
>         ["javascript"] = { "biome" },
>         ["javascriptreact"] = { "biome" },
>         ["typescript"] = { "biome" },
>         ["typescriptreact"] = { "biome" },
>         ["json"] = { "biome" },
>         ["jsonc"] = { "biome" },
>         -- ["vue"] = { "biome" },
>         -- ["css"] = { "biome" },
>         -- ["scss"] = { "biome" },
>         -- ["less"] = { "biome" },
>         -- ["html"] = { "biome" },
>       },
>     },
>   },
> }
> ```
> 
> References:
> 
> * [biome supported languages](https://biomejs.dev/internals/language-support/)
> * [conform supported formatters](https://github.com/stevearc/conform.nvim?tab=readme-ov-file#formatters)

Hi @kyrisu, it dos not work well when you must use prettier in work, this is better when there is some custom prettier configuration in your project.
```lua
local function biome_lsp_or_prettier(bufnr)
  -- local has_biome_lsp = vim.lsp.get_clients({
  --   bufnr = bufnr,
  --   name = "biome",
  -- })[1]
  -- if has_biome_lsp then
  --   return {}
  -- end
  local has_prettier = vim.fs.find({
    -- https://prettier.io/docs/en/configuration.html
    ".prettierrc",
    ".prettierrc.json",
    ".prettierrc.yml",
    ".prettierrc.yaml",
    ".prettierrc.json5",
    ".prettierrc.js",
    ".prettierrc.cjs",
    ".prettierrc.toml",
    "prettier.config.js",
    "prettier.config.cjs",
  }, { upward = true })[1]
  if has_prettier then
    return { "prettier" }
  end
  return { "biome" }
end

return {
  {
    "stevearc/conform.nvim",
    ---@class ConformOpts
    opts = {
      formatters_by_ft = {
        javascript = biome_lsp_or_prettier,
        typescript = biome_lsp_or_prettier,
        javascriptreact = biome_lsp_or_prettier,
        typescriptreact = biome_lsp_or_prettier,
        json = { "biome" },
        jsonc = { "biome" },
      },
    },
  },
}
```

**Comment by jsonMartin** [comment]
> You don't need to disable conform as it supports biome. The following config works:
> 
> ```lua
> return {
>   {
>     "stevearc/conform.nvim",
>     optional = true,
>     opts = {
>       -- for language support
>       -- @see https://biomejs.dev/internals/language-support/
>       formatters_by_ft = {
>         ["javascript"] = { "biome" },
>         ["javascriptreact"] = { "biome" },
>         ["typescript"] = { "biome" },
>         ["typescriptreact"] = { "biome" },
>         ["json"] = { "biome" },
>         ["jsonc"] = { "biome" },
>         -- ["vue"] = { "biome" },
>         -- ["css"] = { "biome" },
>         -- ["scss"] = { "biome" },
>         -- ["less"] = { "biome" },
>         -- ["html"] = { "biome" },
>       },
>     },
>   },
> }
> ```
> 
> References:
> 
> * [biome supported languages](https://biomejs.dev/internals/language-support/)
> * [conform supported formatters](https://github.com/stevearc/conform.nvim?tab=readme-ov-file#formatters)

Yeah, I also ended up re-enabling Conform with Biome, as I had some weird behavior and inconsistent formatting without it. It seems to work well now, I now have a very similar configuration to the one you posted where the formatter for every file is overridden with Biome.

**Comment by jsonMartin** [comment]
> > You don't need to disable conform as it supports biome. The following config works:
> > ```lua
> > return {
> >   {
> >     "stevearc/conform.nvim",
> >     optional = true,
> >     opts = {
> >       -- for language support
> >       -- @see https://biomejs.dev/internals/language-support/
> >       formatters_by_ft = {
> >         ["javascript"] = { "biome" },
> >         ["javascriptreact"] = { "biome" },
> >         ["typescript"] = { "biome" },
> >         ["typescriptreact"] = { "biome" },
> >         ["json"] = { "biome" },
> >         ["jsonc"] = { "biome" },
> >         -- ["vue"] = { "biome" },
> >         -- ["css"] = { "biome" },
> >         -- ["scss"] = { "biome" },
> >         -- ["less"] = { "biome" },
> >         -- ["html"] = { "biome" },
> >       },
> >     },
> >   },
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > References:
> > 
> > * [biome supported languages](https://biomejs.dev/internals/language-support/)
> > * [conform supported formatters](https://github.com/stevearc/conform.nvim?tab=readme-ov-file#formatters)
> 
> Hi @kyrisu, it does not work well when you must use prettier in work, this is better when there is some custom prettier configuration in your project.
> 
> ```lua
> local function biome_lsp_or_prettier(bufnr)
>   local has_biome_lsp = vim.lsp.get_clients({
>     bufnr = bufnr,
>     name = "biome",
>   })[1]
>   if has_biome_lsp then
>     return {}
>   end
>   local has_prettier = vim.fs.find({
>     -- https://prettier.io/docs/en/configuration.html
>     ".prettierrc",
>     ".prettierrc.json",
>     ".prettierrc.yml",
>     ".prettierrc.yaml",
>     ".prettierrc.json5",
>     ".prettierrc.js",
>     ".prettierrc.cjs",
>     ".prettierrc.toml",
>     "prettier.config.js",
>     "prettier.config.cjs",
>   }, { upward = true })[1]
>   if has_prettier then
>     return { "prettier" }
>   end
>   return { "biome" }
> end
> 
> return {
>   {
>     "stevearc/conform.nvim",
>     ---@class ConformOpts
>     opts = {
>       formatters_by_ft = {
>         javascript = biome_lsp_or_prettier,
>         typescript = biome_lsp_or_prettier,
>         javascriptreact = biome_lsp_or_prettier,
>         typescriptreact = biome_lsp_or_prettier,
>         json = { "biome" },
>         jsonc = { "biome" },
>       },
>     },
>   },
> }
> ```

Thank you for posting this solution @binhtran432k ! After integrating a similar change into my `plugins.lua` file now I can work on Biome and Prettier projects without needing to change the global config each time (previously I'd just open the prettier projects in VSCode since it was too much effort to constantly juggle global configs). It would be great if there was an easier way to do this out of the box, but this is a great solution for now!

**Comment by shanesveller** [comment]
> The 2nd line `local has_biome_lsp = vim.lsp.get_clients({` is causing the error, because that function name is no longer available; instead now it is called `get_active_clients`.

@jsonMartin FYI these names are factors of which version of Neovim you're running with, and aren't influenced by updating LazyVim or other plugins. The function names involved are indeed [a deprecation in upcoming Neovim 0.10](https://neovim.io/doc/user/news.html#news-deprecations), but `get_clients` is the newer non-deprecated syntax for >= 0.10. Perhaps the original snippet's author is using nightlies, which is perfectly fine.

**Comment by jsonMartin** [comment]
> > The 2nd line `local has_biome_lsp = vim.lsp.get_clients({` is causing the error, because that function name is no longer available; instead now it is called `get_active_clients`.
> 
> 
> 
> @jsonMartin FYI these names are factors of which version of Neovim you're running with, and aren't influenced by updating LazyVim or other plugins. The function names involved are indeed [a deprecation in upcoming Neovim 0.10](https://neovim.io/doc/user/news.html#news-deprecations), but `get_clients` is the newer non-deprecated syntax for >= 0.10. Perhaps the original snippet's author is using nightlies, which is perfectly fine.

Gotcha. Thanks for the clarification

**Comment by folke** [comment]
You can just install biomels with mason. No extra configuration needed.

**Comment by technophile-04** [comment]
> You can just install biomels with mason. No extra configuration needed.

Just tried doing this, but for some reason my lsp is not showing all inlay errors. Some are shown in editor itself but when I do `biome check .` it shows more error in CLI but they are not shown in editor :(

**Comment by andribiz** [comment]
I've been using Biome on my project. It's working fast and great, except for one thing: organizing imports. Coming from Prettier & eslint, where imports are organized on format.

is it possible automatically organize import biomels on format  rather than call it manually  ?

i read in [biome documentation](https://biomejs.dev/analyzer/import-sorting/) that it is possible with vscode  using custom action on save setting.

**Comment by maxpetretta** [comment]
@jsonMartin thank you for the snippet. i find this is still required for biome projects when you have the prettier extra installed

**Comment by andrew-t-james-core** [comment]
I tried disabling pretter from extras along with eslint and continue to have issues with formatting on save. I am getting what looks like a double formatting (only on bracket spacing). 

I did use the snippet called out in thread as well as attempted without it (as it mentioned biome should just work). 
```lua
local function biome_lsp_or_prettier(bufnr)
  local has_biome_lsp = vim.lsp.get_clients({
    bufnr = bufnr,
    name = "biome",
  })[1]
  if has_biome_lsp then
    return {}
  end
  local has_prettier = vim.fs.find({
    -- https://prettier.io/docs/en/configuration.html
    ".prettierrc",
    ".prettierrc.json",
    ".prettierrc.yml",
    ".prettierrc.yaml",
    ".prettierrc.json5",
    ".prettierrc.js",
    ".prettierrc.cjs",
    ".prettierrc.toml",
    "prettier.config.js",
    "prettier.config.cjs",
  }, { upward = true })[1]
  if has_prettier then
    return { "prettier" }
  end
  return { "biome" }
end

return {
  -- Use Biome instead of prettier / eslint
  {
    "stevearc/conform.nvim",
    opts = {
      formatters_by_ft = {
        ["javascript"] = biome_lsp_or_prettier,
        ["javascriptreact"] = biome_lsp_or_prettier,
        ["typescript"] = biome_lsp_or_prettier,
        ["typescriptreact"] = biome_lsp_or_prettier,
        ["vue"] = { "biome" },
        ["css"] = { "biome" },
        ["scss"] = { "biome" },
        ["less"] = { "biome" },
        ["html"] = { "biome" },
        ["json"] = { "biome" },
        ["jsonc"] = { "biome" },
        ["yaml"] = { "biome" },
        ["markdown"] = { "biome" },
        ["markdown.mdx"] = { "biome" },
        ["graphql"] = { "biome" },
        ["handlebars"] = { "biome" },
      },
    },
    -- formatters = {
    --   biome = {
    --     -- Ensure Biome uses the config file
    --     args = { "format", "--config-path", "biome.json", "--stdin-file-path", "$FILENAME" },
    --   },
    -- },
  },
}



```
https://github.com/user-attachments/assets/78030a24-68b3-4062-94d8-c051e8754649

**Comment by jericopulvera** [comment]
> Leaving this incase any one else faces this challenge when prettier is added via lazy extras this worked for my issue
> 
> -- /nvim/plugins/conform.lua
> 
> local formatters = { "biome", "prettierd", "prettier" }
> 
> local function find_config(bufnr, config_files)
>   return vim.fs.find(config_files, {
>     upward = true,
>     stop = vim.fs.dirname(vim.api.nvim_buf_get_name(bufnr)),
>     path = vim.fs.dirname(vim.api.nvim_buf_get_name(bufnr)),
>   })[1]
> end
> 
> local function biome_or_prettier(bufnr)
>   local has_biome_config = find_config(bufnr, { "biome.json", "biome.jsonc" })
>   if has_biome_config then
>     return { "biome", stop_after_first = true }
>   end
> 
>   local has_prettier_config = find_config(bufnr, {
>     ".prettierrc",
>     ".prettierrc.json",
>     ".prettierrc.yml",
>     ".prettierrc.yaml",
>     ".prettierrc.json5",
>     ".prettierrc.js",
>     ".prettierrc.cjs",
>     ".prettierrc.toml",
>     "prettier.config.js",
>     "prettier.config.cjs",
>   })
>   if has_prettier_config then
>     return { "prettier", stop_after_first = true }
>   end
> 
>   -- Default to Prettier if no config is found
>   return { "prettier", stop_after_first = true }
> end
> 
> local filetypes_with_dynamic_formatter = {
>   "javascript",
>   "javascriptreact",
>   "typescript",
>   "typescriptreact",
>   "vue",
>   "css",
>   "scss",
>   "less",
>   "html",
>   "json",
>   "jsonc",
>   "yaml",
>   "markdown",
>   "markdown.mdx",
>   "graphql",
>   "handlebars",
> }
> 
> return {
>   {
>     "stevearc/conform.nvim",
>     opts = {
>       formatters_by_ft = (function()
>         local result = {}
>         for _, ft in ipairs(filetypes_with_dynamic_formatter) do
>           result[ft] = biome_or_prettier
>         end
>         return result
>       end)(),
>     },
>   },
> }

Unused local `formatters` also biome organize imports does not trigger on save am I missing something?

**Comment by andrew-t-james-core** [comment]
@jericopulvera I couldn't get organize imports to work with this setup. 

```lua
-- conform.lua
local format_utils = require("utils.format")

return {
  "stevearc/conform.nvim",
  opts = function(_, opts)
    opts.formatters_by_ft = (function()
      local result = {}
      for _, ft in ipairs(format_utils.filetypes_with_dynamic_formatter) do
        result[ft] = format_utils.biome_or_prettier
      end
      return result
    end)()

    opts.format_on_save = function(bufnr)
      -- Disable with a global or buffer-local variable
      if vim.g.disable_autoformat or vim.b[bufnr].disable_autoformat then
        return
      end

      local formatter = format_utils.biome_or_prettier(bufnr)
      if formatter[1] == "biome" then
        return { timeout_ms = 500, lsp_fallback = true, async = false }
      end
      return false
    end

    -- Add Biome formatter
    -- opts.formatters = opts.formatters or {}
    opts.formatters.biome = {
      command = "biome",
      args = { "check", "--write", "$FILENAME" }, --  ← this was the magic that fixed organizing imports 
      stdin = false,
    }

    return opts
  end,
}

```

and in my utils 
```lua
local M = {}

M.find_config = function(bufnr, config_files)
  return vim.fs.find(config_files, {
    upward = true,
    stop = vim.fs.dirname(vim.api.nvim_buf_get_name(bufnr)),
    path = vim.fs.dirname(vim.api.nvim_buf_get_name(bufnr)),
  })[1]
end

M.biome_or_prettier = function(bufnr)
  local has_biome_config = M.find_config(bufnr, { "biome.json", "biome.jsonc" })

  if has_biome_config then
    return { "biome", stop_after_first = true }
  end

  local has_prettier_config = M.find_config(bufnr, {
    ".prettierrc",
    ".prettierrc.json",
    ".prettierrc.yml",
    ".prettierrc.yaml",
    ".prettierrc.json5",
    ".prettierrc.js",
    ".prettierrc.cjs",
    ".prettierrc.toml",
    "prettier.config.js",
    "prettier.config.cjs",
  })

  if has_prettier_config then
    return { "prettier", stop_after_first = true }
  end

  -- Default to Prettier if no config is found
  return { "prettier", stop_after_first = true }
end

M.format_file = function(bufnr)
  local file = vim.api.nvim_buf_get_name(bufnr)
  local formatter = M.biome_or_prettier(bufnr)

  if formatter[1] == "biome" then
    -- Run Biome
    local result = vim.fn.system("biome check --write " .. vim.fn.shellescape(file))
    if vim.v.shell_error == 0 then
      vim.cmd("edit!")
    else
      vim.api.nvim_err_writeln("Biome error: " .. result)
    end
  end
  -- Add Prettier logic here if needed
end

M.filetypes_with_dynamic_formatter = {
  "javascript",
  "javascriptreact",
  "typescript",
  "typescriptreact",
  "vue",
  "css",
  "scss",
  "less",
  "html",
  "json",
  "jsonc",
  "yaml",
  "markdown",
  "markdown.mdx",
  "graphql",
  "handlebars",
}

return M

```

**Comment by ekenigs** [comment]
@andrew-t-james-core I get this error using your config. Do you know what could be wrong?<img width="505" alt="Image" src="https://github.com/user-attachments/assets/3beba21b-4f38-4cbd-8a1c-86561aae8231" />

**Comment by ukcw** [comment]
> I was getting this warning as well. [@ekenigs](https://github.com/ekenigs) I also recently switch to [this](https://github.com/stevearc/conform.nvim/issues/585#issuecomment-2504734402) configuration in my conform.lua file and it works as expected. This [PR](https://github.com/stevearc/conform.nvim/pull/599) also exists just hasn't been merged.

Thanks a lot mate, your replies here have been very helpful.
