### ISSUE TITLE
bug: vim-cmp not select first item as default selection.

### ISSUE THREAD

**Issue by chen-gz** [LazyVim/LazyVim#2129]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.4

### Operating system/version

macOS 14.1.2 (23B92)

### Describe the bug

I use everything as default. When I typing the code, the auto complement does not select first item in the list. it skip some items.
![Screenshot 2023-12-04 at 11 44 48 AM](https://github.com/LazyVim/LazyVim/assets/18215354/7652015c-e431-4ab7-895b-47dbe15b3c54)
I try to update nvim-cmp settings by add following content to `Lua/plugins/nvim-cmp.lua`
Also tried with different options. But no lucky. Appreciate for any help.
return {
  {
    "nvim-cmp",
    dependencies = {
      {
        "zbirenbaum/copilot-cmp",
        dependencies = "copilot.lua",
        opts = {},
        config = function(_, opts)
          local copilot_cmp = require("copilot_cmp")
          copilot_cmp.setup(opts)
          -- attach cmp source whenever copilot attaches
          -- fixes lazy-loading issues with the copilot cmp source
          -- require("lazyvim.util").lsp.on_attach(function(client)
          --   -- if client.name == "copilot" then
          --   --   copilot_cmp._on_insert_enter({})
          --   -- end
          -- end)
        end,
      },
    },
    ---@param opts cmp.ConfigSchema
    opts = function(_, opts)
      table.insert(opts.sources, 1, {
        name = "copilot",
        -- group_index = 1,
        priority = 1,
      })
    end,
  },
}

### Steps To Reproduce

1. clone the default settings.
2. enable copilot and update all plugin to latest.
3. typing code and wait for auto complete.

### Expected Behavior

The first item is select as default

### Repro

```Lua
-- I am using configuration from "https://github.com/LazyVim/starter"
-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
```

**Comment by folke** [comment]
That;s not a LAzyVim issue.

That's your LSP telling cmp to preselect a certain completion item.

Check the cmp docs if you dont want this behavior
