### ISSUE TITLE
bug: diagnostic and dap signs are not displayed in `statuscolumn` anymore

### ISSUE THREAD

**Issue by mikaoelitiana** [LazyVim/LazyVim#2147]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev-1513+g98bb1d66b-Homebre

### Operating system/version

14.1.2

### Describe the bug

DAP signs like the breakpoint indicator or diagnostic icons are not displayed in the status column anymore. 

### Steps To Reproduce

1. Open a file
2. Add a breakpoint on a line using `<space>db`

### Expected Behavior

A sign should be displayed on the status column 

https://github.com/LazyVim/LazyVim/assets/674667/0de30e55-32b3-4a6e-8c2c-d075360f33f5

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
Try to update your Neovim to latest nightly and see if they appear. There was an update on Neovim about signs about 3-4 weeks ago and consequently LazyVim also made some changes to accommodate those changes upstream. With a fresh LazyVim starter template and latest Neovim nightly I can see the icons appearing just fine. You'll only notice that the DAP sign will be right on top of the diagnostic sign when you set a breakpoint.

**Comment by bncpr** [comment]
> Try to update your Neovim to latest nightly and see if they appear. There was an update on Neovim about signs about 3-4 weeks ago and consequently LazyVim also made some changes to accommodate those changes upstream. With a fresh LazyVim starter template and latest Neovim nightly I can see the icons appearing just fine. You'll only notice that the DAP sign will be right on top of the diagnostic sign when you set a breakpoint.

Had the same issue and this solved it

**Comment by folke** [comment]
Will work correctly on stable or a recent nightly
