### ISSUE TITLE
bug: vscode extra - no highlight on search and replace (:s command)

### ISSUE THREAD

**Issue by dorudumitru-hh** [LazyVim/LazyVim#2149]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.2

### Operating system/version

Linux (RedHat 8)

### Describe the bug

When using vscode extra, if you open vscode, select some code and use :s, there is no highlight for matched words.

### Steps To Reproduce

1. Install lazyvim.plugins.extras.vscode
2. Open vscode
3. Select some code and use :s

![Screenshot from 2023-12-07 11-48-42](https://github.com/LazyVim/LazyVim/assets/40240395/598429c6-71c1-4382-be2f-fd008c6c5a52)

### Expected Behavior

All matched words should be highlighted

![Screenshot from 2023-12-07 11-51-02](https://github.com/LazyVim/LazyVim/assets/40240395/f03d9b56-1431-484e-b79b-da795868f837)

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dorudumitru-hh** [comment]
Update. I just changed the OS (Fedora 39) and I'm facing the same issue here as well.

**Comment by folke** [comment]
That's not a LazyVim issue.
See also https://github.com/vscode-neovim/vscode-neovim/issues/1833

**Comment by dorudumitru-hh** [comment]
I don't think the two issues are related. If i use a minimal init.lua the highlight works. But tnx anyway.

![image](https://github.com/LazyVim/LazyVim/assets/40240395/3ae02dfb-6b18-401a-9eba-0e698b566abb)
