### ISSUE TITLE
feature: Change the default terminal in Windows from cmd to Windows Powershell

### ISSUE THREAD

**Issue by bijuli74** [LazyVim/LazyVim#2151]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Is there a way to change the default terminal which is opened via <C-/> to powershell instead of cmd in windows? I could not figure it out. Powershell is imo better than cmd as it allows the use of some common bash commands like `ls` etc.

### Describe the solution you'd like

Just how can I change my default terminal in nvim config or provide a way to do so.

### Describe alternatives you've considered

else just need to open another tab and then cd into the working directory, which is inconvenient. Coming from vscode it will be great to have a terminal window open in the present working directory. Also can I move the terminal window page to bottom like in VScode.

**Comment by dpetka2001** [comment]
LazyVim does not have control over this. It just opens a floating terminal with whatever your default `shell` is. You should change on Windows what your default shell is. As far as I know the terminal can only be a floating window. You might want to check [toggleterm](https://github.com/akinsho/toggleterm.nvim) which gives you more freedom where the terminal should be positioned. This is not a LazyVim issue.

**Comment by dpetka2001** [comment]
There's also the option `shell` in Neovim which by default on Windows is set to `cmd.exe`. Maybe you could try changing this to represent the value of path of where Powershell resides on your Windows system.

**Comment by TheRealNOIG** [comment]
Here is my config that changes the shell to PowerShell



```lua
-- Check if 'pwsh' is executable and set the shell accordingly
if vim.fn.executable('pwsh') == 1 then
    vim.o.shell = 'pwsh'
else
    vim.o.shell = 'powershell'
end

-- Setting shell command flags
vim.o.shellcmdflag = '-NoLogo -ExecutionPolicy RemoteSigned -Command [Console]::InputEncoding=[Console]::OutputEncoding=[System.Text.UTF8Encoding]::new();$PSDefaultParameterValues[\'Out-File:Encoding\']=\'utf8\';'

-- Setting shell redirection
vim.o.shellredir = '2>&1 | %{ "$_" } | Out-File %s; exit $LastExitCode'

-- Setting shell pipe
vim.o.shellpipe = '2>&1 | %{ "$_" } | Tee-Object %s; exit $LastExitCode'

-- Setting shell quote options
vim.o.shellquote = ''
vim.o.shellxquote = ''
```
