### ISSUE TITLE
bug: Debugging TypeScript Files Not Working with LazyVim Extra TypeScript and DAP Core Configurations

### ISSUE THREAD

**Issue by Demianeen** [LazyVim/LazyVim#2156]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.4

### Operating system/version

MacOS 14.1.2 (23B92)

### Describe the bug

I am experiencing an issue with LazyVim where the debugger disconnects when attempting to debug TypeScript files containing TypeScript-specific code (like types definitions). This occurs when using the configurations provided by the `extras.lang.typescript` and `extras.dap`.core packages in LazyVim.

https://github.com/LazyVim/LazyVim/assets/51330172/b9e8b7c3-6826-4936-a31a-175f8d62b983

### Steps To Reproduce

1. Init lazy vim
2. Add 		{ import = "lazyvim.plugins.extras.dap.core" } and     { import = 'lazyvim.plugins.extras.lang.typescript' },
3. Open ts file with and add some types
4. Run debugger

### Expected Behavior

Typescript debug works

**Comment by dpetka2001** [comment]
Maybe you should ask at [nvim-dap](https://github.com/mfussenegger/nvim-dap). This doesn't seem to be LazyVim related. If you press `<leader>dr` for Dap Repl, it shows an error about `Unexpected token ':'` at the place where you define the Typescript type. I don't know why that is. Also there is a command `DapShowLog` that might contain further hints as to why this happens when you create the ticket.

**Comment by Demianeen** [comment]
So, the issue is that pwa-node uses node by default, I just needed to add:
runtimeExecutable = 'tsx', -- or ts-node, from what I understand it should be installed globally

Thanks to https://www.reddit.com/r/neovim/comments/17hms38/typescript_debugging_via_nvimdap/

So, now I have two configurations:
```json
{
  {
    type = 'pwa-node',
    request = 'launch',
    name = 'Launch JS file',
    program = '${file}',
    cwd = '${workspaceFolder}',
  },
  {
    type = 'pwa-node',
    request = 'launch',
    name = 'Launch TS file',
    cwd = '${workspaceFolder}',
    runtimeExecutable = 'tsx',
    args = { '${file}' },
    sourceMaps = true,
    protocol = 'inspector',
    skipFiles = { '<node_internals>/**', 'node_modules/**' },
    resolveSourceMapLocations = {
      '${workspaceFolder}/**',
      '!**/node_modules/**',
    },
  },
}
```

Works like magic

**Comment by dpetka2001** [comment]
Great @Demianeen!! I didn't know about this. Thanks for letting us know as well :smile:

**Comment by phortonssf** [comment]
> So, the issue is that pwa-node uses node by default, I just needed to add: runtimeExecutable = 'tsx', -- or ts-node, from what I understand it should be installed globally
> 
> Thanks to https://www.reddit.com/r/neovim/comments/17hms38/typescript_debugging_via_nvimdap/
> 
> So, now I have two configurations:
> 
> ```lua
> {
>   {
>     type = 'pwa-node',
>     request = 'launch',
>     name = 'Launch JS file',
>     program = '${file}',
>     cwd = '${workspaceFolder}',
>   },
>   {
>     type = 'pwa-node',
>     request = 'launch',
>     name = 'Launch TS file',
>     cwd = '${workspaceFolder}',
>     runtimeExecutable = 'tsx',
>     args = { '${file}' },
>     sourceMaps = true,
>     protocol = 'inspector',
>     skipFiles = { '<node_internals>/**', 'node_modules/**' },
>     resolveSourceMapLocations = {
>       '${workspaceFolder}/**',
>       '!**/node_modules/**',
>     },
>   },
> }
> ```
> 
> Works like magic

Where did you add this, what file?

**Comment by Demianeen** [comment]
@phortonssf, I added it in nvim dap setup file. I use lazyvim, with it I have the following configuration:
```lua
return {
  'mfussenegger/nvim-dap',
  opts = function()
    local languages =
      { 'typescript', 'javascript', 'typescriptreact', 'javascriptreact' }

    local dap = require('dap')

    dap.adapters['pwa-node'] = {
      type = 'server',
      host = 'localhost',
      port = '${port}',
      executable = {
        command = 'js-debug-adapter',
        args = { '${port}' },
      },
    }

    dap.adapters['pwa-chrome'] = {
      type = 'server',
      host = 'localhost',
      port = '${port}',
      executable = {
        command = 'js-debug-adapter',
        args = { '${port}' },
      },
    }

    require('dap.ext.vscode').load_launchjs(nil, {
      ['pwa-node'] = languages,
      ['node'] = languages,
      ['chrome'] = languages,
      ['pwa-chrome'] = languages,
    })

    for _, language in ipairs(languages) do
      vim.list_extend(dap.configurations[language], {
        -- {
        --   type = 'pwa-node',
        --   request = 'launch',
        --   name = 'Launch JS file',
        --   program = '${file}',
        --   cwd = '${workspaceFolder}',
        -- },
        {
          type = 'pwa-node',
          request = 'launch',
          name = 'Launch file',
          cwd = '${workspaceFolder}',
          -- NOTE: you would need to have tsx installed globally
          runtimeExecutable = 'tsx',
          args = { '${file}' },
          sourceMaps = true,
          protocol = 'inspector',
          skipFiles = { '<node_internals>/**', 'node_modules/**' },
          resolveSourceMapLocations = {
            '${workspaceFolder}/**',
            '!**/node_modules/**',
          },
        },
        {
          type = 'pwa-node',
          request = 'attach',
          name = 'Attach to process',
          processId = require('dap.utils').pick_process,
          cwd = '${workspaceFolder}',
        },
        {
          type = 'pwa-chrome',
          request = 'launch',
          name = 'Start Chrome on port',
          url = function()
            local port = vim.fn.input({
              prompt = 'Port ',
              completion = 'file',
            })
            return 'http://localhost:3000' .. port
          end,
          webRoot = '${workspaceFolder}',
          userDataDir = '${workspaceFolder}/.vscode/vscode-chrome-debug-userdatadir',
        },
      })
    end
  end,
}

```
