### ISSUE TITLE
feature: support images

### ISSUE THREAD

**Issue by liamwh** [LazyVim/LazyVim#2157]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Would like to be able to open a png in a buffer

### Describe the solution you'd like

https://github.com/3rd/image.nvim setup with a plugin

### Describe alternatives you've considered

N/A

**Comment by Bacbia3696** [comment]
Hi @liamwh , the features you request is implemented by 3rd/images.nvim.
You read the document to install dependencies.

I used Kitty, if you use other terminal, you might need to change the config a bit.
setup plugins, you can check my config for references: https://github.com/Bacbia3696/lazy_nvim/blob/main/lua/plugins/images.lua
![Uploading image.png…]()

**Comment by neuromaancer** [comment]
I believe this is very hard to implement in a general distro, as `3rd/image.nvim` is kind of hard to realize if you don't use kitty or linux.

**Comment by folke** [comment]
there's plugins out there that support this
