### ISSUE TITLE
feature: support git worktrees for root directory identification 

### ISSUE THREAD

**Issue by jokajak** [LazyVim/LazyVim#216]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

I'm using git worktrees with bare repositories and struggling with the identification of the root directory for a project.

The issue I'm having is that the logic implemented in https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/util/init.lua#L39 checks if `.git` is a directory but for worktrees it's a file with contents `/path/to/bare/git/repo.git/worktrees/<worktree name>`

Therefore I have to use `cwd` based keymaps and commands for my actions which isn't as ergonomic as the project based keymaps.

### Describe the solution you'd like

Update https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/util/init.lua#L39 to allow the `.git` path to be a file or directory.

### Describe alternatives you've considered

Living with the poor ergonomics or trying to fix it myself.

### Additional context

I'm using https://github.com/jokajak/git-worktree.nvim to let me switch between worktrees and I've configured it to set the current root for neo-tree but it would be nice if the project root aligned with the worktree automagically.

Thanks for the great framework!

**Comment by folke** [comment]
`.git` as a file will already be used for root detection. 

`get_root` will first check lsp root dirs if they are available. If those are incorrect, you'll have to fix that first.

**Comment by briandipalma** [comment]
I use worktrees and everything is working fine for me, the issue is using bare repositories I think. Could you not just use normal repositories?

**Comment by jokajak** [comment]
Thank you @folke , you are right that my lsp root detection is broken.
