### ISSUE TITLE
bug: Auto-indent not working for html files

### ISSUE THREAD

**Issue by imli700** [LazyVim/LazyVim#2161]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

Fedora 39

### Describe the bug

Auto indentation doesn't work in HTML files. I'm a new LazyVim user so I don't know if this was caused by an update but I noticed it today and can't figure out what's causing this. I haven't changed any treesitter options and it happens only for HTML. Other file types auto indent as expected.

Say I have typed this:
![image](https://github.com/LazyVim/LazyVim/assets/76049491/8d25f74e-9141-41c7-884c-c767b5d0761c)

When I press ENTER, I want stuff to indent like so:
![image](https://github.com/LazyVim/LazyVim/assets/76049491/347bed38-c942-40c0-9310-7719e6d3aaaf)

However, it doesn't indent at all:
![image](https://github.com/LazyVim/LazyVim/assets/76049491/1435d34b-8851-4a57-8cd7-44977bb21477)

### Steps To Reproduce

1. Open any HTML file
2. Type in an opening and closing tag
3. Press ENTER key

### Expected Behavior

The tags auto indent

**Comment by dpetka2001** [comment]
Look into [nvim-autopairs](https://github.com/windwp/nvim-autopairs) to get this kind of behavior. LazyVim uses `mini.pairs` by default, which doesn't seem to provide the desired behavior. Maybe you could create an issue at the plugin's repo to provide such behavior if possible. Or perhaps it's a combination of `nvim-cmp` with `mini.pairs`, not sure.

**Comment by imli700** [comment]
Dude I'm an idiot. I installed `nvim-autopairs` earlier to help with some character pairing. Turns out that and `mini.pairs` were someone in conflict. Everything works after I disabled `mini.pairs`

**Comment by alex-k03** [comment]
Do you have emmet_language_server installed on mason per chance? Uninstalling it seems to fix this issue for me, or installing autopairs. I'm not sure why that is exactly, I didn't think LSPs can dictate formatting, so I'd appreciate if someone could shed some light on how this works or how to fix it.

**Comment by imli700** [comment]
> Do you have emmet_language_server installed on mason per chance?

No, I don't.

> I didn't think LSPs can dictate formatting, so I'd appreciate if someone could shed some light on how this works or how to fix it.

Idk man I'm a newbie myself
