### ISSUE TITLE
feature: Responsive Telescope layouts

### ISSUE THREAD

**Issue by JonatasAmaral** [LazyVim/LazyVim#2173]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

When using LazyVim in a vertical screen, `:Telescope live_grep` (`<leader>/`), that has horizontal layout, gets without the preview

### Describe the solution you'd like

It would be nice if LazyVim could check if has move height than width, and if so, exec `:Telescope ... layout_strategy=vertical` for `<leader>/`|`<leader>sg`|all Ts commands with preview

https://github.com/LazyVim/LazyVim/blob/5987570b5213c9a8b756fd8a169f8e92c05f5bfa/lua/lazyvim/plugins/editor.lua#L53

### Describe alternatives you've considered

I've created a `plugins/telescope.lua` to overwrite some keys, but that' too much to overwrite i suppose.
Also, it may be a beneficial thing for every one.

### Additional context
Here's how i've done on my side

```lua
-- gives "esponsiveness" to Telescope's commands with previews
-- by open in vertical layout for vertical screens

local function isVertical()
  local width = vim.api.nvim_get_option("columns")
  local height = vim.api.nvim_get_option("lines")

  print("echo 'screen is " .. width .. "x" .. height .. "'")

  return height > width / 2 -- lines are wider than columns in px
end

local function responsiveGrep()
  local direction = isVertical() and "vertical" or "horizontal"
  require("telescope.builtin").live_grep({ layout_strategy = direction })
end
local function responsiveFindFiles()
  local direction = isVertical() and "vertical" or "horizontal"
  require("telescope.builtin").files({ layout_strategy = direction })
end

return {
  "nvim-telescope/telescope.nvim",
  keys = {
    -- { "<leader>/", vim.NIL },
    { "<leader>/", responsiveGrep, desc = "Find in Files (Grep)" },
    { "<leader>sg", responsiveGrep, desc = "Grep (root dir)" },
    { "<leader><space>", responsiveFindFiles, desc = "Find Files (root dir)" },
    { "<leader>ff", responsiveFindFiles, desc = "Find Files (root dir)" },
  },
}
```

_No response_

**Comment by dpetka2001** [comment]
You should look into `:h telescope.layout.flex`. No need to change this for every keymap (since `flex` will be used for every picker if you define it) or use custom functions to recognize if it should be horizontal or vertical.

**Comment by JonatasAmaral** [comment]
Sorry the delay

I experimented with flex, it's cool how it swaps on resize/scale.
It gets almost there, but i doesn't feel "flexible" enough

You set the `flip_columns` and `flip_lines` to swap it from vert to horizontal.
With that fixed value for example:
- my laptop's screen get horizontal, makes sense
- but my side (vert) monitor does too
- i fine tune the number, but then if i split my vert screen, it keep a vertical layout
- fine tune the `flip_lines`, then don't match my main screen on split
...

I really expect layout strategy to depend on aspect-ratio instead on size
oppose to... well, size, either of the panel, preview of cutoff

So, flex would be perfect if `flip_*` could receive a function that evaluates it's value
gonna open a request there

But for now, the way above feels to me a better "generalist" option.
Maybe i'll give a try to make [my own strategy](https://github.com/nvim-telescope/telescope.nvim/blob/6213322ab56eb27356fdc09a5078e41e3ea7f3bc/lua/telescope/pickers/layout_strategies.lua#L43C1-L45C14).



And finally, i do think that setting better defaults is indeed LazyVim related.
So for myself, it's kind of solved with the (non optimal) config above, but that's a opportunity for a small improvement of the project as a whole, even if only setting "flex" the default strategy

**Comment by dpetka2001** [comment]
I see what you mean. You have 2 different monitors. I only have one horizontal and couldn't test the different behavior of `flex` in a vertical monitor. I only experimented with flex in the horizontal monitor and tried to resize my terminal and observed the behavior I mentioned.
On that aspect, yes, it seems that if `flip_*` values could take a function would make more sense. 
As far as the Lazyvim defaults are concerned, I guess in retrospect, I agree with your suggestion above (since I believed that `flex` would take care of your problem under my false assumptions).
