### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by szechp** [LazyVim/LazyVim#2177]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

MacOs 13.3.1

### Describe the bug

i have this set:

```
vim.api.nvim_set_keymap('n', '', ':move .-2', { noremap = true, silent = true, desc = "Move line/block up" })
vim.api.nvim_set_keymap('n', '', ':move .+1', { noremap = true, silent = true, desc = "Move line/block down" })
vim.api.nvim_set_keymap('x', '', ":move '<-2gv-gv", { noremap = true, silent = true, desc = "Move line/block up" })
vim.api.nvim_set_keymap('x', '', ":move '>+1gv-gv", { noremap = true, silent = true, desc = "Move line/block down" })
```

still, alt + left/right resizes my current buffer. i couldn't find what plugin overwrites this. also there is no mention of alt + left/right rebinding to this. binding alt + up/down works, no issues.

### Steps To Reproduce

put above mentioned keymaps in you keymaps.lua

### Expected Behavior

i expect the keymaps i set.

**Comment by dpetka2001** [comment]
You haven't set anything in the `lhs` section. It's just empty string.
