### ISSUE TITLE
bug: HTML Indentation issue - <!DOCTYPE html> and <html> tags cause indentation errors

### ISSUE THREAD

**Issue by alex-k03** [LazyVim/LazyVim#2182]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

MacOS 14.1.1

### Describe the bug

When editing empty HTML files, indentation works fine:
![Screenshot 2023-12-12 at 22 20 38](https://github.com/LazyVim/LazyVim/assets/39222273/e23a7e9e-6122-44c4-977c-d1a060293bf3)
Hit Enter:
![Screenshot 2023-12-12 at 22 21 32](https://github.com/LazyVim/LazyVim/assets/39222273/c610f0d5-9760-4a8d-bddc-647ed5a4f3aa)
However, when you have <!DOCTYPE> and <HTML> tags present:
![Screenshot 2023-12-12 at 22 22 22](https://github.com/LazyVim/LazyVim/assets/39222273/aa30adf3-5803-4ad2-b6ec-6e76bb8d6c2f)
Hit Enter:
![Screenshot 2023-12-12 at 22 22 38](https://github.com/LazyVim/LazyVim/assets/39222273/df72e6cd-1201-452a-ae50-b11c7fe3c386)
It indents incorrectly.

### Steps To Reproduce

1. Create and open a new .html file in lazyvim
2. Replicate the structure of the file in the description
3. Create a new <div> or <section> and see how it indents.

### Expected Behavior

Tags to indent correctly

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
This doesn't happen with default Lazyvim starter template. It must be some of your plugins.

**Comment by alex-k03** [comment]
The only plugin I have that interferes with this is autopairs, but all it does is create a newline between the div tags and indents it. Without it the second div tag is still indented too far. I'll double check by installing a fresh lazyvim config.

**Comment by dpetka2001** [comment]
https://github.com/LazyVim/LazyVim/assets/12776461/f1c18dc1-4009-4f79-9e44-efcd8830465e

This is what I get with fresh Lazyvim starter template without any plugins.

**Comment by alex-k03** [comment]
That's because the body is indented one space inside the HTML tags - I've never done that personally but looking online I can see this is quite common, so I guess it's just a style issue. Anyway I suppose this is some plugin doing this that is beyond the distro's control, so I'll close this issue.

**Comment by alex-k03** [comment]
@dpetka2001 When you save the file, does autoformat leave everything inside the HTML tags indented? For me it unindents it, which messes up indentation again. Not sure if this is default behaviour or if it's a plugin. I'm not really sure what decides how the autoformat formats the file, so could you tell me how to fix this issue?

**Comment by alex-k03** [comment]
It seems to me that the html lsp, the only one seemingly available, is responsible for deindenting everything inside the <HTML> tags when I save the file. This conflicts with the way indentation works when I edit the file, which I suppose treesitter is responsible for? I can't find an easy way to configure either of these plugins to indent the same way, so it seems to me that the default config is pretty much unusable for HTML. If I'm not missing anything I'm considering reopening this issue or creating a new one that lays out the problem more clearly.

**Comment by dpetka2001** [comment]
Yes, the `html-lsp` also de-indents for me when it's the default formatter. But I use `prettierd` for html (configured via conform and it takes precedence over the LSP server) which doesn't do that. The default config doesn't use anything for programming in HTML. The user has to configure the LSP and formatting on his own. I suggest you use either `prettier` or `prettierd` for formatting.
