### ISSUE TITLE
bug: nvim-dap keymaps are not available automatically

### ISSUE THREAD

**Issue by s1n7ax** [LazyVim/LazyVim#2186]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.4 Build type: Release LuaJIT 2.1.1692716794

### Operating system/version

Ubuntu

### Describe the bug

I'm trying to add instructions to install [nvim-java](https://github.com/nvim-java/nvim-java) on Lazyvim. According to [this doc](https://www.lazyvim.org/extras/dap/core#nvim-dap), you have added bunch of keymaps to dap. However, these keymaps are not present even though the plugin is loaded.

I'm using the latest Lazyvim template, without any change but the nvim-java installation.

### Steps To Reproduce

1. Install lazyvim using the template
2. Create a file for nvim-java spec `~/.config/nvim/lua/plugins/java/init.lua`
3. Add following plugin spec

```lua
return {
  "nvim-java/nvim-java",
  dependencies = {
    "nvim-java/lua-async-await",
    "nvim-java/nvim-java-core",
    "nvim-java/nvim-java-test",
    "nvim-java/nvim-java-dap",
    "MunifTanjim/nui.nvim",
    "neovim/nvim-lspconfig",
    "mfussenegger/nvim-dap",

    {
      "williamboman/mason.nvim",
      opts = {
        registries = {
          "github:nvim-java/mason-registry",
          "github:mason-org/mason-registry",
        },
      },
    },
    {
      "williamboman/mason-lspconfig.nvim",
      opts = {
        handlers = {
          ["jdtls"] = function()
            require("java").setup()
          end,
        },
      },
    },
  },
  opts = {},
}
```

4. Open a java file
5. Press `<leader>` and which key should show keymaps for debugging

### Expected Behavior

Expected following keys to be loaded when the plugin is loaded

![image](https://github.com/LazyVim/LazyVim/assets/18459807/49caad4d-de4a-44a8-bcdb-b92a3749c168)

https://github.com/LazyVim/LazyVim/assets/18459807/571096e0-382b-4a4c-9fc3-4f87b11ecc49

**Comment by dpetka2001** [comment]
You have to enable this [Extra](https://www.lazyvim.org/extras/dap/core) for these keybindings to be available. What does `:LazyExtras` show you? If you don't enable the Extra the keybindings won't be available. All the Extras are optional and have to be enabled by users according to their needs.

**Comment by s1n7ax** [comment]
@dpetka2001 I see. I needed dap.core extra. Thanks
