### ISSUE TITLE
bug: Lua debugger disconnects on debug starts

### ISSUE THREAD

**Issue by Demianeen** [LazyVim/LazyVim#2188]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.4

### Operating system/version

MacOS 14.1.2 (23B92)

### Describe the bug

I did try to setup lua Nvim debugger using dap.core and dap.nlua extras, but when try to attach a debugger to nvim instance I get:
DAP Couldn't connect to 127.0.0.1:8086: ECONNREFUSED

### Steps To Reproduce

1. Setup lazyvim:
```lua
local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  -- bootstrap lazy.nvim
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable",
    lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

require('lazy').setup({
  spec = {
    {
      'LazyVim/LazyVim',
      import = 'lazyvim.plugins',
    },
    { import = 'lazyvim.plugins.extras.dap.core' },
    { import = 'lazyvim.plugins.extras.dap.nlua' },
  },
})
```
2. Reenter neovim
3. Toggle breakpoint
4. Run Attach to neovim instance configuration

https://github.com/LazyVim/LazyVim/assets/51330172/babc122f-66ad-44dd-90e8-40c2fe3c84d4

### Expected Behavior

Debugger will run

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
spec = {
    {
      'LazyVim/LazyVim',
      import = 'lazyvim.plugins',
    },
    { import = 'lazyvim.plugins.extras.dap.core' },
    { import = 'lazyvim.plugins.extras.dap.nlua' },
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
```

**Comment by dpetka2001** [comment]
You should read the Lua adapter's [docs](https://github.com/jbyuki/one-small-step-for-vimkind/blob/94b06d81209627d0098c4c5a14714e42a792bf0b/doc/osv.txt#L44-L69) for how to debug.

**Comment by Demianeen** [comment]
Yep, you are 100% right. Solved it. At least, next time somebody will be able to google the issue)
