### ISSUE TITLE
bug: HTML Formatter and LSP Indentation Inconsistency

### ISSUE THREAD

**Issue by alex-k03** [LazyVim/LazyVim#2200]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

MacOS 14.1.1

### Describe the bug

In a fresh LazyVim install, with html-lsp installed, the indentation does not work correctly. As you're writing code the autoindentation wants everything inside the <html> tags to be indented by one tab, else everything you write inside those tags will autoindent with an extra tab. The html-lsp formatter on the other does not the content of the <html> tags to be indented, and unindents it automatically when you save. Consequentially, every time you save your buffer and edit it again, indentation does not work properly. Here is a video to demonstrate:

https://github.com/LazyVim/LazyVim/assets/39222273/4b85e4c1-8666-409d-b9fa-0d389161c2ce

Note that both formatters in LazyExtras format the same way as the LSP - so I can't seem to find an easy fix to this problem. As it stands LazyVim seems to be incapable of saving and editing HTML documents.

### Steps To Reproduce

1. Install html-lsp on a fresh install of LazyVIm
2. Create a HTML file with a HTML boilerplate
3. Save the file
4. Add a <div> in the <body> and see how it indents

### Expected Behavior

Indentation to either indent based off the indentation of the first parent block so that it always indents correctly, or at least for the indentation rules of the formatter to match the indentation rules whilst editing.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
I answered you in the closed topic, where you referenced me, first. But the same answer goes here. It's a problem with how `html` LSP formats. If you don't want that behavior, then use another formatter like `prettier/prettierd`. If you enable the LazyExtra in formatting for `prettier` you shouldn't have this problem.

**Comment by alex-k03** [comment]
Thank you for the help. You're right - prettier does seem to format without unindenting anything - however it doesn't take tabstop/shiftwidth into account so if your tab isn't set to two spaces it still doesn't indent correctly. I'm not sure how to fix this. Still, it seems awfully difficult to edit HTML files in LazyVim, and it would be better if formatters and LSPs were preconfigured consistently.

**Comment by dpetka2001** [comment]
LazyVim has no saying in how the LSP server formats the buffer. That's internal to the LSP server. Also about the `shiftwidth` problem this is because `prettier` by default has `tabWidth =2` (see official [docs](https://prettier.io/docs/en/options#tab-width)). You should change that setting in your `.prettierrc` at the root of your project and set it to whatever value you like. Consistent preconfiguration is a rather personal opinion from my experience. For example, in a seminar I did about basic `html/css` stuff, we used the default value of prettier's `tabWidth`. So, a user should change that in his `.prettierrc` in his own project according to his own preferences.

**Comment by alex-k03** [comment]
Ah I see, it's quite inconvenient that html-lsp can't be configured. What's strange is that while the html-lsp is based on vscode's lsp for HTML, this behaviour doesn't happen in vscode - rather it keeps indentation the same for <HTML> tags regardless of whether you choose to indent them. Is it possible to configure prettier to use the current tabWidth from vim.opts, or to configure it on the fly? I often switch between different repos which have different indentation, since many of them are not mine I don't want to change the tab width when I make contributions. Hence I use a function I have :ToggleIndentation that switches between tab width of 2 and 4. Would it be possible for this to set prettier's tab width too?

**Comment by alex-k03** [comment]
Strangely I can't find anyone talking about this in the discussions or issues - whether it's fixable or not it affects the user experience quite significantly in my opinion - makes me feel like I'm missing an obvious solution.

**Comment by dpetka2001** [comment]
Well each project should have its own `.prettierrc` file for prettier's configuration. If you use prettier, then  it should respect the configuration defined in that file regardless of the project.

**Comment by alex-k03** [comment]
This seems like a very convoluted solution to the problem - quickly editing existing HTML documents should require this much work and configuration. Maybe there's some kind of autocommand that can be added to BufWrite (:w) to fix indentation?

**Comment by dpetka2001** [comment]
Well alternatively, you can disable auto-formatting (either via `<leader>uf` or setting `vim.g.autoformat = false` in your `options.lua` file for permanent setting) and then when you open a file you can `:set sw=4` (or any other desired value) and manually indent with `gg=G`.  This seems more convoluted to me, since I believe that a user should conform with each project's formatting tools that they use (most use prettier or something else). If the projects you contribute don't use any formatting tool, then the above solution seems the most logical to me. Unfortunately, I can't think of anything else.

**Comment by alex-k03** [comment]
Fair enough, I've decided to just use a global config for prettier in my root dir, maybe later I will create a function to change the config on my fly.

**Comment by alex-k03** [comment]
Thank you for the help

**Comment by dpetka2001** [comment]
Plz bare in mind, that I'm just a normal user like yourself and not affiliated with this project. These are all things, I tried to think a better way for you to solve the problem. There could definitely be a better way to do this, it's just that I myself don't know very much about Neovim's internals and LSP servers, so I fail to think of anything else. So, maybe someone else can come up with a better solution than what I've suggested.

**Comment by alex-k03** [comment]
I understand, I'm certainly newer to the nvim world myself, I've been using it for about a week now. For anyone interested, here's the very non elegant solution to the problem I came up with:
1. Format using prettier from LazyExtras
2. Create a .prettierrc in your root directory, this applies globally unless you have a project-specific config
3. For adjusting indentation on the fly, create two functions - SetIndentation(indent) and ChangePrettierTab(value):
```lua
function SetIndentation(indent)
  ChangePrettierTab(indent)
  vim.opt.tabstop = indent
  vim.opt.shiftwidth = indent
  vim.opt.softtabstop = indent
  vim.opt.expandtab = true
end

vim.cmd("command! -nargs=1 SetIndentation lua SetIndentation(<args>)")

function ChangePrettierTab(value)
  local prettierConfigPath = os.getenv("HOME") .. "/.prettierrc"

  -- Read the existing config
  local file = io.open(prettierConfigPath, "r")
  if not file then
    print("Error: Unable to open file.")
    return
  end
  local content = file:read("*a")
  file:close()

  -- Replace the tabWidth value
  local updatedContent = content:gsub('"tabWidth":%s*%d+', '"tabWidth": ' .. value)

  -- Write the updated config back
  file = io.open(prettierConfigPath, "w")
  if not file then
    print("Error: Unable to open file for writing.")
    return
  end
  file:write(updatedContent)
  file:close()
end
```
Now you can use :SetIndentation x to set how many spaces both your editor and prettier formatter will indent with.
Bear in mind that this is a horrible solution as it doesn't use any libraries to read the .prettierrc file, but for a config that has a single value of tabWidth it works.
