### ISSUE TITLE
bug: rust analyzer not suggesting imports

### ISSUE THREAD

**Issue by chrontax** [LazyVim/LazyVim#2201]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.4 Build type: Release LuaJIT 2.1.0-beta3

### Operating system/version

6.1.67-gentoo-dist

### Describe the bug

when writing rust with the rust extra enabled I don't get any import suggestions

### Steps To Reproduce

1. nvim src/main.rs
2. start typing "use std::"
3. no suggestions appear

### Expected Behavior

suggestions of what I can take from the library (collections, etc.)

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
        vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
        vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
        "folke/tokyonight.nvim",
        "folke/LazyVim",
        {
                "neovim/nvim-lspconfig",
                config = function()
                        require("lspconfig").rust_analyzer.setup({})
                end,
        },
        {
                "hrsh7th/nvim-cmp",
                config = function()
                        local cmp = require("cmp")
                        cmp.setup({
                                sources = cmp.config.sources({ { name = "nvim_lsp" } }, { { name = "buffer" } }),
                        })
                end,
        },
        "hrsh7th/cmp-nvim-lsp",
        -- add any other plugins here
}
require("lazy").setup(plugins, {
        root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
I can't reproduce this. This is a picture of auto-completion with fresh LazyVim starter template, without any customization and only enabling the Rust LazyExtra.
![2023-12-17_12-21](https://github.com/LazyVim/LazyVim/assets/12776461/b46ccf85-cdc2-4014-8d3a-4d6738287c73)

Is the `rust-analyzer` LSP attached to your buffer? What does `:LspInfo` show?

**Comment by chrontax** [comment]
![image](https://github.com/LazyVim/LazyVim/assets/93487917/b9a9037a-9f0a-4599-9d00-61f2cc152199)

**Comment by dpetka2001** [comment]
Can you reproduce this in a fresh LazyVim starter template to avoid any conflict from your own configuration? The other thing my mind would go to is that maybe there's something wrong with your Rust installation. Do you have latest Rust installed (`rustup update` to update to latest version).

**Comment by chrontax** [comment]
I'm running rust version 1.74 installed with emerge and this still happens with a fresh starter

**Comment by chrontax** [comment]
found it! for some reason gentoos rust doesn't play nice with nvim, but after installing via rustup everything works as it should
