### ISSUE TITLE
feature: 

### ISSUE THREAD

**Issue by 07Rafael08** [LazyVim/LazyVim#2204]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

How do I solve the problem? 

![image0](https://github.com/LazyVim/LazyVim/assets/137735832/012cc778-9aac-4eb2-a6f1-46044c78485a)

### Describe the solution you'd like

.

### Describe alternatives you've considered

.

### Additional context

.

**Comment by dpetka2001** [comment]
I believe you're missing a C compiler in your OS. This is not an issue with LazyVim, rather a configuration issue with the OS you use. 

Also it'd really help a lot if you put a more elaborate effort from your side when creating issues. You can't expect those who will try to help you to make guesses about your problem. There's a reason the issue template comes with some sections that you should complete.

**Comment by abeldekat** [comment]
@07Rafael08,

Kindly close this issue
