### ISSUE TITLE
bug: Can't override default which-key folder

### ISSUE THREAD

**Issue by nwaywood** [LazyVim/LazyVim#2210]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.4

### Operating system/version

MacOS 13.4

### Describe the bug

When I try to set a [keybinding](https://github.com/nwaywood/dotfiles/blob/master/config/nvim/lua/plugins/telescope.lua#L14) to override a [default which-key folder](https://github.com/LazyVim/LazyVim/blob/879e29504d43e9f178d967ecc34d482f902e5a91/lua/lazyvim/plugins/editor.lua#L314) the keybinding works but it doesn't show up in which-key UI.

### Steps To Reproduce

1. Disable all default `<leader>f*` bindings (e.g. [here](https://github.com/nwaywood/dotfiles/blob/master/config/nvim/lua/plugins/neo-tree.lua#L4-L5), [here](https://github.com/nwaywood/dotfiles/blob/master/config/nvim/lua/plugins/telescope.lua#L8-L13) and [here](https://github.com/nwaywood/dotfiles/blob/master/config/nvim/lua/config/keymaps.lua#L10-L12)) so that the `<leader>f` "folder" doesn't contain any keymappings anymore
2. Define a base level `<leader>f` keymapping `{ "<leader>f", Util.telescope("files"), desc = "Find Files" }` (e.g. [here](https://github.com/nwaywood/dotfiles/blob/master/config/nvim/lua/plugins/telescope.lua#L14)) to replace the `"+file/find"` which-key folder

### Expected Behavior

The new keybinding `{ "<leader>f", Util.telescope("files"), desc = "Find Files" }` should show up in the which-key UI. 

However, instead, the keybinding works as expected but it's not visible in the which-key UI.

My guess as to why this is happening is a bug with the logic for overriding default which-key folders.

I tried [disabling the folder definition](https://github.com/nwaywood/dotfiles/blob/master/config/nvim/lua/plugins/which-key.lua) so that my new `<leader>f` binding shows up in the UI properly but it didn't work.

Note: If I set the binding to `<leader>r` instead of `<leader>f`, a binding that doesn't clash with a default which-key folder, then it correctly shows up in the which-key UI

**Comment by abeldekat** [comment]
Hello @nwaywood,

I found the problem in your which-key config:

```lua

return {
  "folke/which-key.nvim",
  opts = {
    defaults = {
      ["<leader>f"] = nil,
    },
  },
}
```

This fragment will be merged with the opts configured by `LazyVim`. Unfortunately, when merging, any key having a `nil` value will be discarded.

In this case, you have to explicitly override with `nil`:

```lua
return {
  "folke/which-key.nvim",
  opts = function(_, opts)
    opts.defaults["<leader>f"] = nil
  end,
}
```

**Comment by nwaywood** [comment]
Ah yes that fixed the issue! Thank you @abeldekat 

And thanks for the explanation, the docs didn't mention that `nil` values are ignored

<img width="752" alt="image" src="https://github.com/LazyVim/LazyVim/assets/3773641/1a2d8d91-3ce7-4d84-a6f4-c4edbc11df19">

**Comment by abeldekat** [comment]
Your welcome!
Indeed, I also can't find this situation in the docs. 
A similar problem in the discussions: [Can't override default keymaps](https://github.com/LazyVim/LazyVim/discussions/1427#discussioncomment-6947911)

I think it's inherent to the language:

```lua

local test = {
  good = "bye",
  hello = nil, -- "world"
}

vim.print(test)
```

The output:

```lua
{
  good = "bye"
}
```

**Comment by dpetka2001** [comment]
@abeldekat I was poking around `lazy.nvim`'s [merge](https://github.com/folke/lazy.nvim/blob/96584866b9c5e998cbae300594d0ccfd0c464627/lua/lazy/core/util.lua#L390-L416) function and it seems that you can pass to a value `vim.NIL` and it will be cleared. You don't have to explicitly overwrite it.

**Comment by abeldekat** [comment]
@dpetka2001,

Thanks!

I did not know about `:h vim.NIL`:

```
vim.NIL                                                              *vim.NIL*
    Special value representing NIL in |RPC| and |v:null| in Vimscript
    conversion, and similar cases. Lua `nil` cannot be used as part of a Lua
    table representing a Dictionary or Array, because it is treated as
    missing: `{"foo", nil}` is the same as `{"foo"}`.
```


So, the following which-key fragment will also fix the problem:

```lua
return {
  "folke/which-key.nvim",
  opts = {
    defaults = {
      ["<leader>f"] = vim.NIL, -- nil,
    },
  },
}
```

**Comment by dpetka2001** [comment]
Yep, i tried it and it works.
