### ISSUE TITLE
bug: `lang.markdown` is broken?

### ISSUE THREAD

**Issue by marcelohdez** [LazyVim/LazyVim#2214]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

Fedora 39 (Asahi Remix)

### Describe the bug

Hello, after installing markdown-preview.nvim through the extras import in lazy.lua, the `:MarkdownPreview*` commands are available in Markdown files, _but_ they do not work... After running `:MarkdownPreview` and then looking at `:messages` I get the following:
```
node:internal/modules/cjs/loader:1147
  throw err;
  ^
Error: Cannot find module 'tslib'
Require stack:
- /home/mhdez/.local/share/nvim/lazy/markdown-preview.nvim/app/lib/app/index.js
- /home/mhdez/.local/share/nvim/lazy/markdown-preview.nvim/app/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/home/mhdez/.local/share/nvim/lazy/markdown-preview.nvim/app/lib/app/index.js:3:17)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/mhdez/.local/share/nvim/lazy/markdown-preview.nvim/app/lib/app/index.js',
    '/home/mhdez/.local/share/nvim/lazy/markdown-preview.nvim/app/index.js'
  ]
}
Node.js v20.10.0
```
I have Node and Yarn installed (installed `yarn` just to troubleshoot this), so after running `yarn install && yarn upgrade` in the plugin directory the plugin starts working, but Lazy now cannot update it as a yarn.lock file was created.

### Steps To Reproduce

1. Add MarkdownPreview through the `lazy.setup` table in `lazy.lua` (`{ import = "lazyvim.plugins.extras.lang.markdown" },`)
2. Restart Neovim
3. Open a Markdown file
4. See that `<leader>cp` is visible in Which-Key and all `:MarkdownPreview*` commands are available
5. Run `:MarkdownPreview`
6. Nothing happens...
7. Quit Neovim
8. `cd` into `~/.local/share/nvim/lazy/markdown-preview.nvim` and run `yarn install && yarn upgrade`
9. Open another Markdown file in Neovim
10. See that `:MarkdownPreview` now successfully opens file in a browser
11. `:Lazy` now considers plugin broken as there exists a yarn.lock file

### Expected Behavior

For `:MarkdownPreview` to work out-of-the-box from LazyVim's extra schema.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  { import = "lazyvim.plugins.extras.lang.markdown" },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by marcelohdez** [comment]
In the description I put my OS as Fedora 39 Asahi Remix, but I just tried on my regular Fedora 39 desktop (both where built up from the Minimal install, in case that matters) and the same issue persists with the same fix (running yarn in plugin directory manually).

**Comment by dpetka2001** [comment]
I tried to reproduce and couldn't. Commands are working fine for me with just enabling the Markdown LazyExtra. 
My guess is it might be some kind of regression with your Node version. I use version 20.10.0 and didn't encounter any problems.

**Comment by marcelohdez** [comment]
@dpetka2001 What OS are you using?

**Comment by dpetka2001** [comment]
Linux mint 21.1 (derivative of Ubuntu 22.04 i believe?)

**Comment by Bacbia3696** [comment]
I got the same issue on my machine, so I remove the plugin `markdown-preview.nvim` and reinstall it so that I run the build script again. Then the preview command work as expected

**Comment by Redoxahmii** [comment]
Same issue on EndeavourOS
