### ISSUE TITLE
feature: add a short description on how to change the default settings

### ISSUE THREAD

**Issue by hesxenon** [LazyVim/LazyVim#2216]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Kinda, I had some trouble figuring out how to change the default kind_filters after noticing that the typescript lsp apparently did not report variables. 

I only made the connection after seeing how the default aerial config referred to something like `Config.kind_filter`, then seeing that `kind_filter` property defined in the [default settings](https://www.lazyvim.org/configuration#default-settings) and noticing the "LazyVim/LazyVim" entry in the example.lua. 

(Also, I'm still wondering why the example.lua file isn't sourced when the docs state "every lua file in the plugins folder will be loaded". But I'm guessing "example" is a reserved name?)

### Describe the solution you'd like

Simply expanding the default settings section a bit by mentioning something like

---

If you want to change any of these settings, just create a lua file in the plugins folder (other than example.lua) with the following content:
```lua
return {
  {
    "LazyVim/LazyVim",
    opts = {
      -- your overrides
    }
  }
}
```

### Describe alternatives you've considered

Extending the plugins doc or linking to e.g. [this issue](https://github.com/LazyVim/LazyVim/discussions/740)

**Comment by hesxenon** [comment]
ofc if you're ok with the proposed text I'd be willing to make a PR, but I'm kinda afraid that I've missed something in my 10 minutes looking for a solution^^

**Comment by dpetka2001** [comment]
The `example.lua` doesn't load because of the following at the top of the file
```lua
if true then return {} end
```
It basically returns an empty table right at the top and the rest of the file isn't taken into consideration
for loading the spec into `lazy.nvim`.

**Comment by dpetka2001** [comment]
I took another look at the docs and [here](https://www.lazyvim.org/configuration#icons--colorscheme) you can see that there is an example about changing the default settings and right below all the default LazyVim settings are mentioned (including the `kind_filter`), so I don't understand what exactly was confusing about the docs.

**Comment by hesxenon** [comment]
you linked to a section explicitly called "Icons & Colorscheme"... while I see now that this is how you change default settings I simply skipped this section because I didn't know that at the time. So maybe just change that heading to "Changing default settings"?

**Comment by dpetka2001** [comment]
I can see how this might be confusing, but still right below is the section for `Default Settings`, which is what a user would look for. Anyway, I'm just a user like you, so keep this open until the maintainer responds. Changing that heading to something more clarifying would definitely be a better solution.

**Comment by rubiin** [comment]
Sorry to bump but was wondering how to extend the default configs as well. In my case , I wanted to add file_ignore_patterns to telescope plugin while keeping everything else to default @dpetka2001

**Comment by dpetka2001** [comment]
@rubiin You could do something like 
```lua
return {
  {
    "nvim-telescope/telescope.nvim",
    opts = {
      defaults = {
        file_ignore_patterns = {
          -- put whatever patterns
          -- you want here
        },
      },
    },
  },
}
```
Also pls read the docs on the website. They have examples of how you can structure your plugin's configuration.

**Comment by dpetka2001** [comment]
I don't know if that setting is applied to telescope file browser as well. It's a different plugin and extension to telescope. Best to ask over at the plugin's repo about that. I tried with Telescope's `find_files` picker and it works as expected.

**Comment by dpetka2001** [comment]
@rubiin I actuall installed telescope-file-browser and tested it and it seems to respect that option. It doesn't show any pdf files for me. I don't know what you have in your config.

**Comment by rubiin** [comment]
oh yeah it works. Thanks for the help man, cheers  . I have been taking reference from your lua files as I am still a beginner when it comes to lua

**Comment by dpetka2001** [comment]
Glad you got it working. Enjoy your Neovim journey :smile:

**Comment by hesxenon** [comment]
yes, since I just started my lazyvim config from scratch again I stumbled across the original issues again as well. I just put the following in my `plugins/custom.lua` now:

```lua
  {
    "LazyVim/LazyVim",
    opts = {
      kind_filter = {
        default = false,
      },
    },
  },
```

the kind filter is a nice idea but a bit too restrictive imho - especially because for some reason it simply excluded the top level definitions in a module for me.
