### ISSUE TITLE
bug: Every time I type '.', ';', or ',' characters, "gu" gets appended to the end. 

### ISSUE THREAD

**Issue by guzman109** [LazyVim/LazyVim#2224]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

Ubuntu 23.10

### Describe the bug

This happens when I type when searching for files and insert mode but not in the command line or the terminal plugins. Only inside Lazyvim and I've tried with another text editor (nano) and this does happen.

### Steps To Reproduce

nvim
`f` to search for file
type either `;`, `.`, or `,`

### Expected Behavior

no "gu" string appended at the end of the punctuation.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
I don't understand what you're doing exactly. Can you give more details? `f` is not searching for files. `f` is searching for the next character to the right (see `:h f`).

**Comment by guzman109** [comment]
Sorry about that. I meant when you first start neovim and press f to trigger telescope to find files.

**Comment by dpetka2001** [comment]
`f` is for searching characters to the right. `<leader>ff` is for Telescope find_files. What exactly happens in Telescope when you search for files?

**Comment by guzman109** [comment]
same thing. "gu" gets appended to the end of those characters.

**Comment by dpetka2001** [comment]
What does `verbose imap .` show?

**Comment by guzman109** [comment]
```
i  .           * .<M-g>u
	Last set from Lua
```

**Comment by dpetka2001** [comment]
Please try the following
```
1. `mkdir ~/.config/lazytest`
2. `git clone https://github.com/LazyVim/starter ~/.config/lazytest`
3. `NVIM_APPNAME=lazytest nvim` and wait for the installation to complete
4. Restart Neovim with the command provided in step 3
```
Do you experience the same issue? 
After you finish testing you can remove the following folders to remove the previous instance
```
rm -rf ~/.config/lazytest
rm -rf ~/.local/share/lazytest
rm -rf ~/.local/state/lazytest
rm -rf ~/.cache/lazytest
```

**Comment by guzman109** [comment]
Nope, I everything works as expected.

**Comment by dpetka2001** [comment]
Then it is something in your configuration that causes this behavior you're observing.

With the commands above you created a fresh LazyVim starter template with default settings and 
no customization and there is no problem at all.

Since this is not a LazyVim problem, kindly close this issue and try to debug your own configuration to figure
out what's causing this. I would probably start with checking your keybindings or some plugin. I can't provide 
you any more help with debugging your own configuration.

**Comment by guzman109** [comment]
Okay, I'll check it out. Thank you so much for your help!
