### ISSUE TITLE
bug: Can't install nvim-notify 

### ISSUE THREAD

**Issue by sollymay** [LazyVim/LazyVim#2225]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.2

### Operating system/version

macOS Sonoma 14.1.2

### Describe the bug

Seems like nvim-notify repo changed to using ssh and for some reason lazy can no longer clone the repo. I have tried many different steps in order to fix this issue, however it only happens with nvim-notify

<img width="1164" alt="Screenshot 2023-12-19 at 5 10 16 PM" src="https://github.com/LazyVim/LazyVim/assets/6496698/f23268d1-b431-4ec1-ac93-fbe9b259c886">

### Steps To Reproduce

1. Download a brand new copy of lazyvim
2. Let all plugins/libraries to install
3. Once all libraries are installed, you will see nvim-notify is not installed.
(Issue might be stemming from nvim-notify repo moving away from https and using ssh for its repo now)

### Expected Behavior

All libraries should be installed 

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  "Mofiqul/dracula.nvim",

  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("dracula")
-- add anything else here
```

**Comment by dpetka2001** [comment]
Cannot reproduce. Just installed a fresh LazyVim starter and `nvim-notify` finished installing correctly along with the rest of the plugins.

**Comment by sollymay** [comment]
never mind! Just realized what the issue was. I had additional configuration for nvim-notify and for some reason it was trying to install the incorrect repo? Anyways. Problem solved 😄
