### ISSUE TITLE
Open plugins show not managed by LazyExtras

### ISSUE THREAD

**Issue by imkratos** [LazyVim/LazyVim#2229]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

MacOS 14.1.2

### Describe the bug

<img width="1334" alt="image" src="https://github.com/LazyVim/LazyVim/assets/3302461/455324dd-319e-4591-8f72-3127e0c8fce9">

### Steps To Reproduce

 I config plugins in ~/.config/nvm/lua/config/lazy.lua , but show this 

<img width="1315" alt="image" src="https://github.com/LazyVim/LazyVim/assets/3302461/88a9696a-5997-416a-abcd-a13164f498b1">

### Expected Behavior

I don't know

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
That's normal. If you configure the Extras in `lua/config/lazy.lua`, then in `LazyExtras` it will show exactly what you see.
They are not managed by `LazyExtras`, instead they are manually configured in your `config/lazy.lua` file.
