### ISSUE TITLE
bug: Cannot pass `--dialect` arg to sqlfluff through conform

### ISSUE THREAD

**Issue by JakeTompkins** [LazyVim/LazyVim#2231]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0-dev

### Operating system/version

Arch Linux

### Describe the bug

I've added sqlfluff to conform and nvim-lint for sql files. The format command is run successfully, but sqlfluff errors out because the dialect is not specified. I've tried adding the argument in the conform plugin config, but because `preprend_args` places arguments before the filename, and sqlfluff expects `--dialect` to appear after the filename, the argumnet is not recognized as causes sqlfluff to error out.

### Steps To Reproduce

1. Add `plugins/conform.lua` with the following contents:
```
return {
  "stevearc/conform.nvim",
  opts = {
    formatters = {
      sqlfluff = {
        prepend_args = { "--dialect=postgres" },
      },
    },
    formatters_by_ft = {
      sql = { "sqlfluff" },
    },
  },
}
```
2. Open an sql file
3. Save the sql file
4. run `:ConformInfo` to see the error

### Expected Behavior

Save on format should successfully run `sqlfluff format...` and write the fixed code to the buffer.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
I believe you need
```lua
      formatters = {
        args = { "fix", "--force", "--dialect=postgres", "-" },
      },
```
to override the default args.

**Comment by JakeTompkins** [comment]
> I believe you need
> 
> ```lua
>       formatters = {
>         args = { "fix", "--force", "--dialect=postgres", "-" },
>       },
> ```
> 
> to override the default args.

Ok, I did try to overwrite the args, but had difficulty getting the correct output to write to the file. I wound up replacing the buffer with the error message output by sqlfluff which is obviously not what I wanted. I can give this a whirl though, thank you.
