### ISSUE TITLE
feature: add `cappyzawa/telescope-terraform.nvim` and `ANGkeith/telescope-terraform-doc.nvim` to `lazyvim.plugins.extras.lang.terraform`

### ISSUE THREAD

**Issue by pbnj** [LazyVim/LazyVim#2234]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

`cappyzawa/telescope-terraform.nvim` provides information about terraform modules, resources, & data through Telescope.

`ANGkeith/telescope-terraform-doc.nvim` provides terraform documentation information through Telescope

### Describe the solution you'd like

Enabling `lazyvim.plugins.extras.lang.terraform` should automatically setup these telescope extensions 

### Describe alternatives you've considered

Overriding telescope plugin to manually setup additional extensions.

**Comment by dpetka2001** [comment]
You don't have to overwrite the telescope plugin, you can just extend it. Also, most contributions come through PRs, so feel free to make one that extends the current terraform extra. Otherwise, you'll have to wait for someone who uses the plugins to make the PR.

**Comment by pbnj** [comment]
@dpetka2001 - Thank you. I am working on a PR as we speak 😄
