### ISSUE TITLE
bug: Fresh new install on Fedora 39 errors on `indent-blankline`

### ISSUE THREAD

**Issue by droopy4096** [LazyVim/LazyVim#2236]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

Fedora 39

### Describe the bug

After fresh new setup I receive errors:

```
Error executing lua callback: vim/keymap.lua:0: rhs: expected string|function, got nil
stack traceback:
	[C]: in function 'error'
	vim/shared.lua: in function 'validate'
	vim/keymap.lua: in function 'set'
	...re/nvim/lazy/LazyVim/lua/lazyvim/plugins/lsp/keymaps.lua:118: in function 'on_attach'
	...share/nvim/lazy/LazyVim/lua/lazyvim/plugins/lsp/init.lua:101: in function 'on_attach'
	....local/share/nvim/lazy/LazyVim/lua/lazyvim/util/init.lua:13: in function <....local/share/nvim/lazy/LazyVim/lua/lazyvim/util/init.lua:10>
	[C]: in function 'nvim_exec_autocmds'
	/usr/share/nvim/runtime/lua/vim/lsp.lua:1530: in function '_on_attach'
	/usr/share/nvim/runtime/lua/vim/lsp.lua:1357: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

```
You are trying to call the setup function of indent-blankline version 2, but you have version 3 installed.
Take a look at the GitHub wiki for instructions on how to migrate, or revert back to version 2.
```

### Steps To Reproduce

1. Install lazyVim
   ```shell
   mv ~/.config/nvim{,.bak}
   
   # optional but recommended
   mv ~/.local/share/nvim{,.bak}
   mv ~/.local/state/nvim{,.bak} 
   mv ~/.cache/nvim{,.bak}
   git clone https://github.com/LazyVim/starter ~/.config/nvim
   ```
2. open nvim configuration directory:
   ```shell
   nvim ~/.config/nvim
   ```
3. Open `README.md` - received
    ```
    You are trying to call the setup function of indent-blankline version 2, but you have version 3 installed.
    Take a look at the GitHub wiki for instructions on how to migrate, or revert back to version 2.
    ```
4. Open `init.lua`  - get `Error executing lua callback: vim/keymap.lua:0: rhs: expected string|function, got nil...` error

### Expected Behavior

No errors opening files

### Repro

```Lua
require("config.lazy")
```

**Comment by dpetka2001** [comment]
The error clearly states what is wrong. Newer version of `indent-blankline` had breaking changes and you must be using old syntax in your configuration. It even tells you to read the Github Wiki at the plugin's repo for how to migrate.

This isn't a LazyVim problem.

**Comment by droopy4096** [comment]
I have *no* pre-existing configuration. This is *stock* LazyVim

**Comment by droopy4096** [comment]
after purge of `~/.local/share/nvim/lazy` the problem still persists

**Comment by dpetka2001** [comment]
The problem is in your `~/.config/nvim/lua/plugins/`. Some file in there that configures `indent-blankline`, uses the syntax of version 2, which creates conflicts because LazyVim installs version 3 when you fresh install it.

**Comment by abeldekat** [comment]
I think your LazyVim may be out-of-date. The latest version is `10.8.2`.

> ...re/nvim/lazy/LazyVim/lua/lazyvim/plugins/lsp/keymaps.lua:118: in function 'on_attach'

File [keymaps.lua](https://github.com/LazyVim/LazyVim/blob/879e29504d43e9f178d967ecc34d482f902e5a91/lua/lazyvim/plugins/lsp/keymaps.lua#L102) does not have a line *118*

Could you run steps 3 and 4 using the code below?

```lua
1. `mkdir ~/.config/lazytest`
2. `git clone https://github.com/LazyVim/starter ~/.config/lazytest`
3. `NVIM_APPNAME=lazytest nvim` and wait for the installation to complete
4. Restart Neovim with the command provided in step 3
```

Cleanup:

```lua
rm -rf ~/.config/lazytest
rm -rf ~/.local/share/lazytest
rm -rf ~/.local/state/lazytest
rm -rf ~/.cache/lazytest
```

**Comment by dpetka2001** [comment]
I think this must be a different problem with the keymaps file and LazyVim out of date. 

The error about `indent-blankline` is specifically for using old syntax in the newer v3.* installation of the plugin or calling the plugin with the old setup method (which indicates something's amiss in the user configuration). Either way starting with a new LazyVim installation and gradually adding his old user configuration would be the best way moving forward in my opinion.

Still this doesn't really seem to be a LazyVim bug. I've tested with a fresh LazyVim starter template and no problems exist with default configuration. So something must be happening in the OP's personal configuration regarding `indent-blankline`.
