### ISSUE TITLE
bug: Leap, taking over basic keybindings, isn't a good fit as a default

### ISSUE THREAD

**Issue by epage** [LazyVim/LazyVim#224]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

 v0.8.3

### Operating system/version

Linux

### Describe the bug

`x` doesn't work in visual mode

This is because leap.nvim takes over that key binding.  LazyVim/lazyvim.github.io#3 exists for making this slightly more discoverable.  For someone explicitly opting in, this can make sense to change defaults but for a monolithic configuration, I feel like norms should be followed or be very explicit when broken.

Maybe this is the frustration surfacing but I find [leap condescending in its discussion on this](https://github.com/ggandor/leap.nvim#faq) (which again, wasn't very searchable, I had to go into "raw" mode of the file and search for backtick-x-backtick).

### Steps To Reproduce

1. Select a range of text
2. Hit `x`
3. See a message about nothing to be done

### Expected Behavior

Text is deleted

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
I actually agree with you on this. Just pushed a change to disable those leap mappings (x and X)

https://github.com/LazyVim/LazyVim/commit/42d2411bfa1d6fcc5edc20ee6dbc0dff0f0fba6e
