### ISSUE TITLE
feature: Improve support for Helm templates

### ISSUE THREAD

**Issue by tcpkump** [LazyVim/LazyVim#2251]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

When editing a [Helm](https://helm.sh/) template with `extras.lang.yaml` enabled, there are many issues due to `yamlls` running even though the files should be identified as `helm` (or `gotmpl`). This is because even though the templates have a `.yaml` file extension, they are actually go templates for generating yaml.

![image](https://github.com/LazyVim/LazyVim/assets/20349484/32632a9a-76a4-4b30-8ba3-7d8b433d0b95)

### Describe the solution you'd like

Minimally, some configuration to prevent `yamlls` from attaching to these files is an okay solution.

Ideally, some form of support for `helm-ls` for these "yaml" files would be great, with some syntax highlighting (I apologize if I don't fully understand and these things are unrelated).

### Describe alternatives you've considered

I found [this](https://github.com/mrjosh/helm-ls#neovim-using-nvim-lspconfig) documentation which works, but had to be done manually.

**Comment by abeldekat** [comment]
Hi @tcpkump,

> Minimally, some configuration to prevent yamlls from attaching to these files is an okay solution.

This discussion addresses a similar requirement:
https://github.com/LazyVim/LazyVim/discussions/1389

**Comment by alesbrelih** [comment]
I'm using towolf/vim-helm + https://github.com/mrjosh/helm-ls and it works quite nice for Helm. Helm-ls got a lot of improvements

**Comment by pbnj-dragon** [comment]
@abeldekat - would LazyVim be open to a PR that adds `extras.lang.helm` to accomplish the following?

- Installs `towolf/vim-helm` for Helm filetype detection and syntax
- Installs `mrjosh/helm-ls`
- Configures LSP as you suggested in https://github.com/LazyVim/LazyVim/discussions/1389

**Comment by abeldekat** [comment]
Hello @pbnj-dragon,

That's up to Folke. 

I do think that you are free to open a PR. That's the way many users started contributing.

A **personal** opinion: The languages in `extras` also need to be maintained. As a consequence, it makes sense to only add languages that are broadly used, or languages that are popular amongst LazyVim's user base. I don't use Helm myself.

Best of luck!

**Comment by pbnj-dragon** [comment]
> As a consequence, it makes sense to only add languages that are broadly used, or languages that are popular amongst LazyVim's user base.

LazyVim has a diverse user base, including infrastructure engineers who work extensively with Terraform, Docker, Helm, and Kubernetes on a daily basis.

I am happy to volunteer as a maintainer/reviewer of Terraform, Helm, and Docker extras.

**Comment by abeldekat** [comment]
I would encourage you to submit the PR.

In case the PR is not accepted for some reason, you can always publish your work in the "show and tell" section of the discussions for others to benefit from.
