### ISSUE TITLE
bug: lang.java how to use lombok?

### ISSUE THREAD

**Issue by imkratos** [LazyVim/LazyVim#2259]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9

### Operating system/version

MacOS 14.1.2 

### Describe the bug

import lang.java  lombok can not working.

### Steps To Reproduce

import plugs     { import = "lazyvim.plugins.extras.lang.java" },

### Expected Behavior

hope lombok is working 

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by abeldekat** [comment]
Hello @imkratos,

When you open a new bug report, this is shown:

```md
Before reporting an issue, make sure to read the [documentation](https://github.com/folke/LazyVim) 
and search [existing issues](https://github.com/folke/LazyVim/issues). 

Usage questions such as "How do I...?" belong in [Discussions](https://github.com/folke/LazyVim/discussions) 
and will be closed.

Did you check docs and existing issues?

Make sure you checked all of the below before submitting an issue
I have read all the LazyVim docs *
I have searched the existing issues of LazyVim *
I have searched the existing issues of plugins related to this issue *
```

Please ask your question in [discussions](https://github.com/folke/LazyVim/discussions) and close this issue.

**Comment by imkratos** [comment]
> Hello @imkratos,
> 
> When you open a new bug report, this is shown:
> 
> ```
> Before reporting an issue, make sure to read the [documentation](https://github.com/folke/LazyVim) 
> and search [existing issues](https://github.com/folke/LazyVim/issues). 
> 
> Usage questions such as "How do I...?" belong in [Discussions](https://github.com/folke/LazyVim/discussions) 
> and will be closed.
> 
> Did you check docs and existing issues?
> 
> Make sure you checked all of the below before submitting an issue
> I have read all the LazyVim docs *
> I have searched the existing issues of LazyVim *
> I have searched the existing issues of plugins related to this issue *
> ```
> 
> Please ask your question in [discussions](https://github.com/folke/LazyVim/discussions) and close this issue.

ok,thank bro
