### ISSUE TITLE
bug: Buffer Splits / Neo-tree flickers different color on load

### ISSUE THREAD

**Issue by BrendanRomanDev** [LazyVim/LazyVim#2262]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

MacOS 13.4.1 (Ventura)

### Describe the bug

No matter what theme I use (even default, tokyonight with proper transparency) there is a 'shadow' that renders before the file explorer opens, and just before it closes. It happens on _every_ theme, Transparent or not. 

This issue is pronounced when using transparent themes. For examaple, I switched to theme [solarized-osaka](https://github.com/craftzdog/solarized-osaka.nvim), and also tried [fynnfluegge/monet](https://github.com/fynnfluegge/monet.nvim). This issue happens on transparent Tokyonight as well. 

_latest stable nvim version: v0.9.4
_Running Wezterm (though the problem also happens in kitty)._
_Note -- these black boxes are not .gif artifiacts, it's what I'm seeing with many themes including tokyo night transparent_
![LazyVim Buffer Issue](https://github.com/LazyVim/LazyVim/assets/63918015/c7c7cbcc-104f-440e-9a39-ed5543145701)

**What I've tried:**
- Using 'nvim-tree' instead of neotree.
- Trying kitty emulator instead of Wezterm.
- Trying multiple themes, messing with highlight groups and varying theme configs for neo-tree. Still happens (though subtly) on default themes.
- Tried adding autocmd to set `Normal` / `NormalNC` colors to `NONE` on `BufEnter`.

Could this be a highlight group issue? I just set up my LazyVim config 2 or 3 days ago. I've read through the docs and googled _extensively_ but can't find anyone else sharing this problem. If nothing else, suggestions are super welcome.

### Steps To Reproduce

1. New LazyVim Distro
2. Follow documentation guidelines to configure TokyoNight transparent theme.
3. Use <Leader>e to open Neo-tree explorer.

### Expected Behavior

You would expect neo-tree and split buffers to open with transparency, however a black flicker occurs in the buffer before it appears.

### Repro

```Lua
-- /plugins/colorscheme.lua

return {
  "folke/tokyonight.nvim",
  opts = {
    transparent = true,
    styles = {
      sidebars = "transparent",
      floats = "transparent",
    },
  },
}

```

```Lua
--- /config/lazy.lua

local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- bootstrap lazy.nvim
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable",
    lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

require("lazy").setup({
  spec = {
    -- add LazyVim and import its plugins
    {
      "LazyVim/LazyVim",
      import = "lazyvim.plugins",
      opts = { colorscheme = "tokyonight" },
    },
    -- import any extras modules here
    { import = "lazyvim.plugins.extras.linting.eslint" },
    { import = "lazyvim.plugins.extras.formatting.prettier" },
    { import = "lazyvim.plugins.extras.lang.typescript" },
    { import = "lazyvim.plugins.extras.lang.json" },
    { import = "lazyvim.plugins.extras.ui.mini-animate" },
    { import = "lazyvim.plugins.extras.util.mini-hipatterns" },
    { import = "lazyvim.plugins.extras.editor.aerial" },
    -- { import = "lazyvim.plugins.extras.lang.tailwind" },
    -- import/override with your plugins
    { import = "plugins" },
  },
  defaults = {
    -- By default, only LazyVim plugins will be lazy-loaded. Your custom plugins will load during startup.
    -- If you know what you're doing, you can set this to `true` to have all your custom plugins lazy-loaded by default.
    lazy = false,
    -- It's recommended to leave version=false for now, since a lot the plugin that support versioning,
    -- have outdated releases, which may break your Neovim install.
    version = false, -- always use the latest git commit
    -- version = "*", -- try installing the latest stable version for plugins that support semver
  },
  install = { colorscheme = { "tokyonight", "habamax" } },
  checker = { enabled = true }, -- automatically check for plugin updates
  performance = {
    rtp = {
      -- disable some rtp plugins
      disabled_plugins = {
        "gzip",
        -- "matchit",
        -- "matchparen",
        -- "netrwPlugin",
        "tarPlugin",
        "tohtml",
        "tutor",
        "zipPlugin",
      },
    },
  },
})

```

**Comment by dpetka2001** [comment]
I was able to reproduce the problem with `mini.animate` enabled. I was able to temporarily disable it with the following
configuration
```lua
return {
  {
    "echasnovski/mini.animate",
    opts = {
      open = {
        enable = false,
      },
      close = {
        enable = false,
      },
    },
  },
}
```
But this is just a fix in my opinion. There is also a relevant [issue](https://github.com/echasnovski/mini.nvim/issues/357) about the same problem you're facing. According to the maintainer it seems to be an upstream issue with Neovim and float windows. 

Either way not a LazyVim issue, so kindly close this issue.

**Comment by BrendanRomanDev** [comment]
> I was able to reproduce the problem with `mini.animate` enabled. I was able to temporarily disable it with the following configuration
> 
> ```lua
> return {
>   {
>     "echasnovski/mini.animate",
>     opts = {
>       open = {
>         enable = false,
>       },
>       close = {
>         enable = false,
>       },
>     },
>   },
> }
> ```
> 
> But this is just a fix in my opinion. There is also a relevant [issue](https://github.com/echasnovski/mini.nvim/issues/357) about the same problem you're facing. According to the maintainer it seems to be an upstream issue with Neovim and float windows.
> 
> Either way not a LazyVim issue, so kindly close this issue.

This has been driving me insane for 2 days. My bad for not seeing the other issue you linked.

**Thank you SO MUCH <3**
