### ISSUE TITLE
bug:  opening lazvvim through tmux is changing the theme

### ISSUE THREAD

**Issue by luanlouzada** [LazyVim/LazyVim#2264]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

ubuntu 22.04

### Describe the bug

well I use terminator on linux with zsh and tmux.

Previously, I had neovim with my own settings, opening it through tmux and there was no such problem.

tmux has 256 colors, I already checked.

Strangely, when I open lazyvim through tmux it seems that the theme becomes gruvbox, I have no idea why, I use tokyonight.

I spent about 3 hours researching and trying everything possible, everything I mentioned is default and the latest version

### Steps To Reproduce

Configure LazyVim: Ensure LazyVim is set to use the Tokyo Night theme.
Open Tmux: Start a Tmux session in a Terminator terminal using Zsh.
Open LazyVim in Tmux: Within the Tmux session, open LazyVim. Observe that the theme automatically changes to Gruvbox.

### Expected Behavior

When opening LazyVim inside Tmux, the configured theme (Tokyo Night) should be retained.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
Make sure you have the following in your `tmux.conf`
```conf
# Enable RGB colour if running in xterm(1)
set-option -sa terminal-overrides ",xterm*:Tc:sitm=\E[3m"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colors - needs tmux-3.0

# Change the default $TERM to tmux-256color
set -g default-terminal "screen-256color"
```

**Comment by luanlouzada** [comment]
I've already done that, I've changed everything in tmux that you can imagine, isn't it...
nor the terminal (terminator), I tried with others too.

I install pure nvim and open tmux and then open neovim the theme continues, it's something in Lazyvim I have no idea why, for some reason it stays with the gruvbox colors, I never changed the theme, lazyvim is default

I know it's difficult to check why this happens without a log or reproducing the problem, I was hoping that some developer would have some idea why.

Before opening this issue I tried for hours to solve it, the problem is in lazyvim, which I don't know...

**Comment by dpetka2001** [comment]
Can you try with kitty or wezterm?

**Comment by luanlouzada** [comment]
[](https://imgur.com/a/UAxad7u) 

I just tried with wez


without tmux:
[](https://imgur.com/a/wbkCget)

**Comment by dpetka2001** [comment]
Unfortunately, I can't reproduce it. I can only reproduce it if I don't have the above lines in `tmux.conf`. If I have them, then colorscheme stays the same for me.

**Comment by luanlouzada** [comment]
"Resolved! I reinstalled tmux for the second time and used version 3.3a instead of a package manager like apt-get, I used appimage.

It ended up being the same, but when I entered your commands

Enable RGB colour if running in xterm(1)
set-option -sa terminal-overrides ",xterm*:Tc:sitm=\E[3m"
set -as terminal-overrides ',:Smulx=\E[4::%p1%dm' # undercurl support
set -as terminal-overrides ',:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m' # underscore colors - needs tmux-3.0

I had entered them before, but it hadn't worked, and the reason I reinstalled and used an appimage was that I read in the comments that tmux 3.0 was needed. I started wondering if mine was outdated? Many things from the package manager are...
It worked!

Thank you! I couldn't find this answer in my searches."
