### ISSUE TITLE
treesitter jsonc certificate error

### ISSUE THREAD

**Issue by verajosemanuel** [LazyVim/LazyVim#2296]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.2

### Operating system/version

Windows 10

### Describe the bug

Everytime I open LazyVim I get this error:
```
Cloning into 'tree-sitter-jsonc'...
fatal: unable to access 'https://gitlab.com/WhyNotHugo/tree-sitter-jsonc.git/': SSL certificate problem: unable to get local issuer certificate
```

Several days in a row as we are hoping a temporary issue in GitLab but status seems to be ok. So, we guess if there's a workaround, maybe installing by hand.

### Steps To Reproduce

1. install Lazyvim
2. Open Lazyvim
3. get error

### Expected Behavior

no error is shown.

### Repro

```Lua
no changes to init.lua
```

**Comment by dpetka2001** [comment]
Sounds like a problem with `git` really rather than LazyVim. Check out this [thread](https://stackoverflow.com/questions/53210531/ssl-certificate-problem-unable-to-get-local-issuer-certificate-in-git).

**Comment by verajosemanuel** [comment]
could it be installed manually as seems that I can donwload the repository from the website?

**Comment by dpetka2001** [comment]
No idea. Don't really use Windows myself. You should try the solutions on that thread, it also has a link to another one, that has other suggestions. For example try `git config --global http.sslbackend schannel` and see what happens.

**Comment by verajosemanuel** [comment]
this did the trick. Lazyvim gets unresponsive for almost 8 seconds and then is usable. Not cool but fine.
