### ISSUE TITLE
bug: can't completely hide the tabline

### ISSUE THREAD

**Issue by vdegenne** [LazyVim/LazyVim#2298]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

fedora 39

### Describe the bug

I tried to hide the tabline at the top but it keeps coming back when I open a file from nvim tree on the left.

### Steps To Reproduce

1. fresh install lazyvim (as explained in the doc)
2. add `vim.cmd [[ set showtabline=0 ]]` in `config/options.lua`
3. open a vim session
4. open at least 2 buffers

the top tab line appears

### Expected Behavior

expected the tabline to never show

**Comment by dpetka2001** [comment]
That's because it gets overwritten by a plugin after you set it in your `options.lua` (probably either `bufferline.nvim` or `neo-tree`). If you don't like to see tabline at all, it would be best to just remove `bufferline.nvim`.

**Comment by dpetka2001** [comment]
Just add `enabled = false` in your code snippet above. Yes, it should be created in the `/lua/plugins/` directory. Filename can be whatever makes sense to you.

**Comment by dpetka2001** [comment]
@vdegenne would you also be kind to close this issue if it's resolved? Thank you.

**Comment by vdegenne** [comment]
Thanks for your kind help

**Comment by dpetka2001** [comment]
Pls also close this issue @vdegenne.

**Comment by vdegenne** [comment]
Sorry I thought I did
