### ISSUE TITLE
feature: show all available keymaps from inside lazyvim

### ISSUE THREAD

**Issue by verajosemanuel** [LazyVim/LazyVim#2299]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

I am always searching for documentation regarding the keymappings.  This is a very time consuming task.
There is some other Neovim distributions that solved this issue the very same mechanism as when searching for a file: opening a list and fuzzy searching as the user types after calling it with a specific keymap. (I assume they are using Telescope)
is there anything similar in lazyvim?

### Describe the solution you'd like

Here below the LunarVim version pressing Leader key and L k
![image](https://github.com/LazyVim/LazyVim/assets/15836677/27dc047c-16c8-4d21-acb8-5d0bbf66c127)

That could be a very nice addition to avoid searching repeatedly for keybindings.

### Describe alternatives you've considered

text file with all the keymappings from the documentation here https://www.lazyvim.org/keymaps, but very cumbersome to have it always opened and change to it for search

**Comment by dpetka2001** [comment]
In LazyVim you can use `<leader>sk` for doing the same.

**Comment by abeldekat** [comment]
Hello @verajosemanuel,

> is there anything similar in lazyvim?

That's a question, not a feature. Please ask questions in the [discussions](https://github.com/LazyVim/LazyVim/discussions) section.

Kindly close this issue.

**Comment by verajosemanuel** [comment]
thanks, that is what i was searching for in documentation to no avail.
