### ISSUE TITLE
feature: use mason-null-ls.nvim

### ISSUE THREAD

**Issue by joshmedeski** [LazyVim/LazyVim#23]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Null-ls can be automatically setup from mason using this package: https://github.com/jay-babu/mason-null-ls.nvim

### Describe the solution you'd like

Be able to have anything supported and installed on mason automatically setup up on null-ls.

### Describe alternatives you've considered

This could be done by hand, but I think this package already does a good job.

The other alternative is to just source everything manually in the config file.

**Comment by amaanq** [comment]
Ideally this template is meant to be extended with your own config, you can simply add that yourself like I have in mine. 

Add this block wherever you load plugins with lazy:
```lua
{
		"jayp0521/mason-null-ls.nvim",
		dependencies = {
			"williamboman/mason.nvim",
			"jose-elias-alvarez/null-ls.nvim",
		},
		after = "mason.nvim",
		config = function()
			require("mason-null-ls").setup({
				automatic_installation = true,
			})
		end,
	},
```

I'm not sure if this is *necessary* or a huge QoL improvement to have in the template, but it'd be nice nonetheless

**Comment by joshmedeski** [comment]
That's a fair point. Let's see if @folke think it's a good idea to include in LazyVim directly. 

mason-lspconfig.nvim is already built-in so this seems like a reasonable addition.

**Comment by folke** [comment]
I agree with @amaanq. 

I personally don't use mason-null-ls since a lot of the tools I use for null-ls are already installed on my system. I also made it easy to have certain tools always installed with mason itself, so I'd rather keep it like that.
