### ISSUE TITLE
bug: Openning LazyGit with <leader>gg gives me an error

### ISSUE THREAD

**Issue by SneaKy178** [LazyVim/LazyVim#2302]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

MacOS Sonoma 14.2.1

### Describe the bug

Whenever I type <leader>gg to open LazyGit, it immediately shows an error and nothing will happen

![CleanShot 2024-01-03 at 22 13 00](https://github.com/LazyVim/LazyVim/assets/30359036/f063e209-2914-4a10-8ec9-8a1bc0601d92)

### Steps To Reproduce

1. just typing leader gg

**Comment by bharatm29** [comment]
is lazygit installed on your system?

**Comment by SneaKy178** [comment]
It was installed, or so I thought. I reinstalled it and it works now. Thanks

**Comment by abeldekat** [comment]
Kindly close this issue.

**Comment by appelgriebsch** [comment]
Maybe we should add a check if `lazygit` is installed and only offer it if it is available on the system?

**Comment by abeldekat** [comment]
Hello @appelgriebsch,

This is already included in `:checkhealth`

> ...
> LazyVim ~
> - OK Using Neovim >= 0.9.0
> - OK `git` is installed
> - OK `rg` is installed
> - OK `fd` is installed
> - OK `lazygit` is installed
> ...

My personal opinion: 
As it is very important to be able to execute and interpret `:checkhealth` when problems exists, I don't think we should add the check you proposed. 
Users should be aware of the installation [requirements](https://www.lazyvim.org/#%EF%B8%8F-requirements).
