### ISSUE TITLE
archived: symbols-outline

### ISSUE THREAD

**Issue by nikolovlazar** [LazyVim/LazyVim#2303]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

I noticed that [symbols-outline](https://github.com/simrat39/symbols-outline.nvim) got archived yesterday due to the maintainer not having time to work on it anymore. What should we do about this?

**Comment by nikolovlazar** [comment]
@dpetka2001 oh you're right! Thanks!

**Comment by futile** [comment]
> `neo-tree` has support for document symbols and `aerial` also. Please use discussions for these kinds of questions as they don't pertain to a LazyVim problem.

Well there is a LazyVim extra that uses the now-archived symbols-outline: https://www.lazyvim.org/extras/editor/symbols-outline.

So I would think it is relevant to LazyVim itself?
