### ISSUE TITLE
bug(floating-terminal): refocus puts you into normal mode

### ISSUE THREAD

**Issue by codymikol** [LazyVim/LazyVim#2313]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

Ubuntu 22.04.3

### Describe the bug

Not sure if this is expected behavior, but I found that refocusing your terminal window puts you into normal mode when using the floating terminal. This can be disorienting as you are then unable to input any further commands and must know that insert mode must be activated before you can continue using the terminal.

### Steps To Reproduce

Open the floating terminal `ctrl + /`
Focus another window
Focus your terminal again
You will now be in Normal Mode

### Expected Behavior

Open the floating terminal `ctrl + /`
Focus another window
Focus your terminal again
You will continue to be in insert mode

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by codymikol** [comment]
I totally understand if this is a behavior of nvim itself and cannot be changed, but figured if we could do something about it, its definitely worth thinking about.

Before I realized exactly what was happening, my workflow was to

`esc`
`esc`
`q`
`ctrl + /`

To regain control of the terminal error.

This was totally me not understanding that I could just press `i` to regain control, but I suspect new users will experience the same friction.

Thanks for all your hard work on LazyVim!

**Comment by dpetka2001** [comment]
This is not the case for me. Every time I focus the terminal buffer it's in insert mode. That's the default behavior. Do you have some kind of customization in your configuration?

**Comment by codymikol** [comment]
I am using this configuration

https://github.com/codymikol/nvim @ https://github.com/codymikol/nvim

I tried removing all customization except for my minimal changes to the lazy.lua file at that sha and am still experiencing the same issue.

**Comment by codymikol** [comment]
I am using this configuration

https://github.com/codymikol/nvim @ https://github.com/codymikol/nvim

I tried removing all customization except for my minimal changes to the lazy.lua file at that sha and am still experiencing the same issue.

**Comment by dpetka2001** [comment]
Are you able to reproduce with the code below
```bash
1. `mkdir ~/.config/lazytest`
2. `git clone https://github.com/LazyVim/starter ~/.config/lazytest`
3. `NVIM_APPNAME=lazytest nvim` and wait for the installation to complete
4. Restart Neovim with the command provided in step 3
```
Cleanup
```bash
rm -rf ~/.config/lazytest
rm -rf ~/.local/share/lazytest
rm -rf ~/.local/state/lazytest
rm -rf ~/.cache/lazytest
```

**Comment by dpetka2001** [comment]
A screencast of how it behaves with default LazyVim starter template.

https://github.com/LazyVim/LazyVim/assets/12776461/d0ae5650-6b80-49fa-99b8-59a58539b192

**Comment by codymikol** [comment]
Yes, I can reproduce the problem as shown

[Screencast from 01-05-2024 11:16:08 AM.webm](https://github.com/LazyVim/LazyVim/assets/13606342/638cf057-4aaf-4aca-bd5d-0869d8d5f4b1)

**Comment by dpetka2001** [comment]
What do you use to unfocus? I didn't see your cursor focusing another window. In my screencast you can see my cursor going to the window behind and then when it comes back to the terminal it goes straight into insert mode. How do you unfocus? Do you press `<esc>`? If yes, that's normal behavior.

**Comment by dpetka2001** [comment]
Yeah, my understanding is that's normal behavior. Even if you don't "unfocus" the way you mean it, clicking with the mouse anywhere inside Neovim while the terminal is open, will take you to Normal mode (that is even happening with stock Neovim terminal). There is no way for Neovim to understand the focus of the terminal emulator window I believe (of course I might be wrong since I know very little portion of Neovim's behavior). Neovim only understands focus in terms of buffers inside Neovim itself, as far as I understand it. 

Anyway, I doubt this is a LazyVim bug, as it also happens with default Neovim terminal. To observe the default Neovim behavior, open Neovim with `nvim --clean` and then type `:terminal` to open the stock Neovim terminal. Same thing happens.

If you agree that this is not a LazyVim bug, kindly close this issue.

**Comment by codymikol** [comment]
I agree that this is not a LazyVim bug, thank you for all your hard work!

**Comment by dpetka2001** [comment]
I'm just a user like you that tries to help others. I haven't put any hard work into this project. Others have contributed way more.

**Comment by dpetka2001** [comment]
Also just FYI if you read `:h terminal-input`, there's this quote
> Mouse input has the following behavior:
> - If another window is clicked, terminal focus will be lost and nvim will jump
  to the clicked window

That seems to be the case in the scenario you described I believe.
