### ISSUE TITLE
feature: Switch Rust support to `Rustacion`

### ISSUE THREAD

**Issue by yeoffrey** [LazyVim/LazyVim#2314]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

[Rust-Tools](https://github.com/simrat39/rust-tools.nvim) is no longer actively maintained as of January 3rd. They recomend switching to [Rustacean](https://github.com/mrcjkb/rustaceanvim), which is actively supported.

### Describe the solution you'd like

I believe we should switch over to Rustacean

### Describe alternatives you've considered

We could also fork Rust-tools, but Rustacean seems better supported

**Comment by dpetka2001** [comment]
There's already an open issue #2113 and a pending PR #2198. Please do a search before creating a new issue.

Kindly close this, since it's duplicate.
