### ISSUE TITLE
bug: I don't  want to use the keymap in lsp, which is [ctrl K]. I can't find where to modify it.

### ISSUE THREAD

**Issue by lipppchen** [LazyVim/LazyVim#2317]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

mac os 14.2.1

### Describe the bug

I need to know where to find the lsp key mapping. I want to modify some quick keys.

### Steps To Reproduce

I search in the internet but i can't find where.

### Expected Behavior

pls some good gus told me where i can find it. 

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
[Here](https://www.lazyvim.org/plugins/lsp#%EF%B8%8F-customizing-lsp-keymaps) you can find how you can customize LSP keymaps. 

However this isn't bug or anything, rather a user configuration question and more suited for the `Discussions`. Kindly close this issue @lipppchen .
