### ISSUE TITLE
bug: can't override clipboard to unamed 

### ISSUE THREAD

**Issue by Parthvsquare** [LazyVim/LazyVim#2327]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.0

### Operating system/version

macos 14.2.1

### Describe the bug

```
-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here
-- local opt = vim.opt
-- opt.clipboard = "unnamed" -- Sync with system clipboar
local opt = vim.opt

-- opt.autowrite = true -- Enable auto write
opt.clipboard = "unnamed"
```

added following to config/options.lua but yanking still saves to my clipboard

### Steps To Reproduce

add unnamed to options.lua
try yanking

### Expected Behavior

should not save to system clipboard

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
Cannot reproduce. With `unnamed` yanking doesn't save to clipboard.

**Comment by cerebrl** [comment]
If you don't want any syncing, use `opt.clipboard = ""`. [The use of `unnamed` varies a bit depending on OS, but `unnamed` and `unnamedplus` roughly result in similar results](https://stackoverflow.com/questions/30691466/what-is-difference-between-vims-clipboard-unnamed-and-unnamedplus-settings). Here are the official nvim doc on this setting: https://neovim.io/doc/user/options.html#'clipboard'. I use macOS, and the empty string does NOT sync with the system clipboard.

Here's a link to my nvim config: https://github.com/cerebrl/nvim/blob/main/lua/config/options.lua#L8.

**Comment by dpetka2001** [comment]
@cerebrl Didn't know about the difference between different OSes (and didn't actually ever search for it). Your link to stackoverflow is very useful. Tnx :)

**Comment by Parthvsquare** [comment]
> If you don't want any syncing, use `opt.clipboard = ""`. [The use of `unnamed` varies a bit depending on OS, but `unnamed` and `unnamedplus` roughly result in similar results](https://stackoverflow.com/questions/30691466/what-is-difference-between-vims-clipboard-unnamed-and-unnamedplus-settings). Here are the official nvim doc on this setting: https://neovim.io/doc/user/options.html#'clipboard'. I use macOS, and the empty string does NOT sync with the system clipboard.
> 
> Here's a link to my nvim config: https://github.com/cerebrl/nvim/blob/main/lua/config/options.lua#L8.

this work :) dunno how
