### ISSUE TITLE
bug: mason.nvim duplicated in the docs

### ISSUE THREAD

**Issue by planetsLightningArrester** [LazyVim/LazyVim#2342]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

Windows 11

### Describe the bug

I've been learning LazyVim configuration through its docs and I think `mason.nvim` is duplicated in the `Plugins > LSP` section.

https://www.lazyvim.org/plugins/lsp

<img width="801" alt="image" src="https://github.com/LazyVim/LazyVim/assets/52364115/9adc6c87-d482-449a-966a-086946c53838">

### Steps To Reproduce

1. Access https://www.lazyvim.org/plugins/lsp
2. Scroll until the end of the page

### Expected Behavior

I believe only the last mason.nvim of the page has the correct default setting.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by planetsLightningArrester** [comment]
Same for dressing.nvim: https://www.lazyvim.org/plugins/ui#dressingnvim-1

**Comment by folke** [comment]
That's already reported in the lazyvim.github.io repo. closing
