### ISSUE TITLE
LazyExtras: clippy doesn't show warnings

### ISSUE THREAD

**Issue by kul-sudo** [LazyVim/LazyVim#2345]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

Windows/Fedora/PopOS

### Describe the bug

As we all know, if you want to quickly set up the config for a specific language (in this case Rust), you can just add this:
```lua
{ import = "lazyvim.plugins.extras.lang.rust" }
```

Rust is obviously expected to analyse the code using clippy whenever you save it, and this is exactly what is meant to be done: https://www.lazyvim.org/extras/lang/rust. However, it just doesn't work. It does inform me if there's an undeclared variable used somewhere in the code or if there's any kind of mistake in the code, it does even show this:
![image](https://github.com/folke/lazy.nvim/assets/95244851/1d4a6026-edb5-43cc-94a8-54a73e9c368f)
but it doesn't show any warnings in the code.

What I've noticed is this:
1. It happens on Windows, on PopOS, and on Fedora. I think that's enough to assume that the error doesn't come from the OS.
2. Even if I use the very basic template (`git clone https://github.com/LazyVim/starter ~/.config/nvim`), the issue persists.
3. It does work in VSCode.
4. Because it works in VSCode, it does obviously show me the clippy issue in the terminal if I run "cargo clippy" manually.

### Steps To Reproduce

1. `git clone https://github.com/LazyVim/starter ~/.config/nvim`
2. Use
```lua
{ import = "lazyvim.plugins.extras.lang.rust" }
```
3. You won't be informed if there's a clippy issue.

### Expected Behavior

It is indeed expected to inform me if something's wrong after the analysis with clippy.

### Repro

Basic config (`git clone https://github.com/LazyVim/starter ~/.config/nvim`)
+

```lua
{ import = "lazyvim.plugins.extras.lang.rust" }
```

**Comment by dpetka2001** [comment]
@kul-sudo This seems to be related with #2141. Unfortunately, `rust-tools` has become archived and no longer being worked on. Until the maintainer comes back and merges #2113 this won't be resolved. My suggestion would be to close this issue and make whatever additional comments you want in #2141. No need to have multiple issues related to the same problem. Just a suggestion from a fellow user like you.

**Comment by kul-sudo** [comment]
> @kul-sudo This seems to be related with #2141. Unfortunately, `rust-tools` has become archived and no longer being worked on. Until the maintainer comes back and merges #2113 this won't be resolved. My suggestion would be to close this issue and make whatever additional comments you want in #2141. No need to have multiple issues related to the same problem. Just a suggestion from a fellow user like you.
> 
> Edit: you could also try #2113 locally and see if the issue persists. If, by any possibility it does, you could ask the author of that PR (which will be the successor to `rust-tools` extra) to look into it, so that the PR doesn't lack anything when it will get merged.

OK, I'll just wait until that PR is merged. Thank you.

**Comment by kul-sudo** [comment]
> @kul-sudo This seems to be related with #2141. Unfortunately, `rust-tools` has become archived and no longer being worked on. Until the maintainer comes back and merges #2113 this won't be resolved. My suggestion would be to close this issue and make whatever additional comments you want in #2141. No need to have multiple issues related to the same problem. Just a suggestion from a fellow user like you.
> 
> Edit: you could also try #2113 locally and see if the issue persists. If, by any possibility it does, you could ask the author of that PR (which will be the successor to `rust-tools` extra) to look into it, so that the PR doesn't lack anything when it will get merged.

You won't believe it, but I think I've found the solution: I just do `cargo clean`, and it starts working. Closing the issue.
