### ISSUE TITLE
bug: All Japanese letters are underlined in `markdown` (and `ENOENT: no such file or directory`)

### ISSUE THREAD

**Issue by spring-haru** [LazyVim/LazyVim#2349]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5 Release

### Operating system/version

macOS 14.2.1 (M1)

### Describe the bug

(1) As the attached image shows, all Japanese letters in the last five lines are underlined in the default colorscheme `tokyonight` like URLs and words such as `Neovim`, `Lua` and `LazyVim` (in the last five lines). It occurred in `LazyVim` before making any change to it, though the attached image uses `vim.o.conceallevel = 0`. Initially I thought it is due to `treesitter`. But I also tried `kickstart.nvim` with no change to it after uninstalling `LazyVim`, and encountered NO such problem.

(2) Once `lang.markdown` is enabled in `LazyVim Extra`, the same problem persists and the following error pops up.
```
Error running markdownlint: ENOENT: no such file or directory
```

<img width="725" alt="スクリーンショット 2024-01-13 13 55 07" src="https://github.com/LazyVim/LazyVim/assets/2603953/8a2da35e-07d0-4ac5-ad44-6051525f4723">

[README-test.md](https://github.com/LazyVim/LazyVim/files/13926860/README-test.md)

### Steps To Reproduce

Open the attached file `README-test.md`

### Expected Behavior

No underline for Japanese letters.

### Repro

```Lua
-- Original init.lua is used
```

**Comment by dpetka2001** [comment]
The Japanese letters are underlined because there's no Japanese word dictionary installed and by showing them as underlined it indicates that they are not recognized by the spell checker which is enabled in `markdown` files (see `:h spell` for more info if you'd like). If you don't like this behavior, you can disable it with the shortcut `<leader>us` that toggles spelling on/off.

Not a LazyVim bug, so kindly close this issue.

**Comment by hyogoa2c** [comment]
@spring-haru 
this works fine with me in `options.lua`

```lua: options.lua
local opt = vim.opt

opt.spelllang = { "en", "cjk" }
```
ref:[Spell - Neovim docs](https://neovim.io/doc/user/spell.html#spell-cjk)

**Comment by spring-haru** [comment]
@hyogoa2c Thanks! I switched to kickstart.nvim, but I will certainly try your tip.
