### ISSUE TITLE
bug: Telescope has shortcut to scroll preview right, but not left

### ISSUE THREAD

**Issue by ericukk** [LazyVim/LazyVim#2362]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

docker installation from documentation

### Operating system/version

Linux/docker

### Describe the bug

Telescope preview has default shortcut to scroll right, but not left.

From the telescope project, C-f and C-k are scroll left and right respectively.
LazyVim tries to have a consistent shortcut set with C-f/C-b for scrolling up/down, but accidentally overrides C-f. 

This is just a minor bug that can be easily fixed with custom config, but I don't think this is expected.

### Steps To Reproduce

1. `<leader>ff`

### Expected Behavior

Expect to have both preview scroll left and right, not just scroll right.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
Actually this is not a bug. LazyVim first implemented those keybindings [here](https://github.com/LazyVim/LazyVim/commit/151bf12a9f9591bd324a359374e6c4a5fb65bbbc) and Telescope added the horizontal preview scrolling [here](https://github.com/nvim-telescope/telescope.nvim/blame/da8b3d485975a8727bea127518b65c980521ae22/lua/telescope/mappings.lua#L151-L152). So, when LazyVim added these keymaps, they didn't even exist at Telescope yet. 

It's just that nobody really bothered using them even after the change in Telescope repo, so no one noticed this before. Still you can easilly override this behavior in your personal configuration if you'd like.
