### ISSUE TITLE
bug: Dashboard Find File Icon Doesn't Exist in Nerd Font Icon Cheat Sheet

### ISSUE THREAD

**Issue by tompark58981** [LazyVim/LazyVim#2364]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

MacOS Sonoma 14.0

### Describe the bug

<img width="595" alt="Screenshot 2024-01-17 at 1 02 49 AM" src="https://github.com/LazyVim/LazyVim/assets/92641483/e4b45f87-f469-4743-ae15-e2ac1ee63fbe">

Find file icon is broken and it won't show up in nerd font icon cheat sheet (copied from ui.lua file in lazyvim git repository).

Could you change the icon to the following?:
Icon: 󰱽
Class: nf-md-file_search_outline
UTF: \udb83\udc7d

### Steps To Reproduce

1. Run nvim command on terminal to open dashboard
2. Find File icon is missing even with patched nerd fonts and proper terminal

### Expected Behavior

Proper icon should show up and icon should be in nerd font cheatsheet

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
LazyVim uses the `f002` hex code for the search icon and it does exist in the Nerd Font cheat sheet. For some reason it's not being rendered in iTerm2. But it's being correctly rendered in kitty, wezterm and Terminator that I've tested. I don't know what the problem is with iTerm2, but like @cerebrl suggested you should take a look at the issue he suggested to fix that.

**Comment by cerebrl** [comment]
I believe iTerm 2 reserves a few of the icons' hex values internally that Nerd Icons use, so they don't work when used in apps running in iTerm, like LazyVim.

**Comment by dpetka2001** [comment]
I agree with that, but if the hex code is being used by Nerd Fonts, then it's not really a LazyVim bug, is it?

**Comment by cerebrl** [comment]
No, this is not a LazyVim bug. It's a design decision of iTerm that I believe they will fix at sometime in the future.

**Comment by tompark58981** [comment]
Sorry should have looked into the issues more thoroughly. Thanks for the comments :)
