### ISSUE TITLE
bug: function signature documentation overlap with cursor line

### ISSUE THREAD

**Issue by xzbdmw** [LazyVim/LazyVim#2371]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

macos 14.1

### Describe the bug

see screenshot

https://github.com/LazyVim/LazyVim/assets/97848247/cabac1cf-dac7-48c1-be15-d0a817559dce

### Steps To Reproduce

default setting

### Expected Behavior

signature above or below current line

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
Create a file `~/.config/nvim/lua/plugins/noice.lua` (or put it somewhere else) with the following contents
```lua
  {
    "folke/noice.nvim",
    opts = {
      lsp = {
        signature = {
          opts = {
            size = {
              max_height = 15,
            },
          },
        },
      },
    },
  },
```
Try to experiment with the value of `max_height`, so that it doesn't cause any overlap based on the size of your monitor. On my laptop this value seems to work good enough (default was 20 and caused overlap for me as well).

**Comment by xzbdmw** [comment]
maybe set default to disable? find many places to disable document don't think about it is in noice

**Comment by xzbdmw** [comment]
> Create a file `~/.config/nvim/lua/plugins/noice.lua` (or put it somewhere else) with the following contents
> 
> ```lua
>   {
>     "folke/noice.nvim",
>     opts = {
>       lsp = {
>         signature = {
>           opts = {
>             size = {
>               max_height = 15,
>             },
>           },
>         },
>       },
>     },
>   },
> ```
> 
> Try to experiment with the value of `max_height`, so that it doesn't cause any overlap based on the size of your monitor. On my laptop this value seems to work good enough (default was 20 and caused overlap for me as well).

I see the documentation of noice and don't find the configuration in doc, am I missing something?
copy from https://github.com/folke/noice.nvim/blob/main/doc/noice.nvim.txt
```signature = {
          enabled = true,
          auto_open = {
            enabled = true,
            trigger = true, -- Automatically show signature help when typing a trigger character from the LSP
            luasnip = true, -- Will open signature help when jumping to Luasnip insert nodes
            throttle = 50, -- Debounce lsp signature help request by 50ms
          },
          view = nil, -- when nil, use defaults from documentation
          ---@type NoiceViewOptions
          opts = {}, -- merged with defaults from documentation
        },
        documentation = {
          view = "hover",
          ---@type NoiceViewOptions
          opts = {
            lang = "markdown",
            replace = true,
            render = "plain",
            format = { "{message}" },
            win_options = { concealcursor = "n", conceallevel = 3 },
          },
          ```

**Comment by xzbdmw** [comment]
Thank you very much, I naively thought all doc in in that txt file.
