### ISSUE TITLE
bug: leap custom keybinding resets after first usage

### ISSUE THREAD

**Issue by cd-a** [LazyVim/LazyVim#2379]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

macOS 14.2.1

### Describe the bug

to enable bidirectional search in leap, you have to set a keybinding, but it gets overridden after using it once, then it reverts to the normal leap keybinding

This has been mentioned in https://github.com/ggandor/leap.nvim/issues/191 a while back, but it seems to be a lazy vim issue. I used leap before without lazyvim with this binding and had no issues whatsoever.

### Steps To Reproduce

1. add leap extra
2. add special keybinding in keymaps.lua
```lua
vim.keymap.set("n", "s", function()
  require("leap").leap({ target_windows = { vim.api.nvim_get_current_win() } })
end)
```
3. use s once to do bidirectional jump, it works
4. use s again, but now the keymap was reset to the normal one-directional jump

### Expected Behavior

The keymap persists

**Comment by dpetka2001** [comment]
Try the following
```lua
-- ~/.config/nvim/lua/plugins/leap.lua
  {
    "ggandor/leap.nvim",
    config = function(_, opts)
      local leap = require("leap")
      for k, v in pairs(opts) do
        leap.opts[k] = v
      end
      leap.add_default_mappings(true)
      vim.keymap.del({ "x", "o" }, "x")
      vim.keymap.del({ "x", "o" }, "X")
      vim.keymap.set("n", "s", function()
        require("leap").leap({ target_windows = { vim.api.nvim_get_current_win() } })
      end)
    end,
  },
```

**Comment by cd-a** [comment]
Thanks a lot for the quick reply, works great!

**Comment by ggandor** [comment]
If you don't need most of the default mappings anyway, then I think it's clearer to write:
```lua
vim.keymap.set('n', 's', function ()
  require('leap').leap({ target_windows = { vim.api.nvim_get_current_win() } })
end)
vim.keymap.set('n', 'gs', '<Plug>(leap-from-window)')  -- or S maybe
vim.keymap.set({'x', 'o'}, 's', '<Plug>(leap-forward)')
vim.keymap.set({'x', 'o'}, 'S', '<Plug>(leap-backward)')
```

**Comment by dpetka2001** [comment]
Yeah probably depends on the needs of a person. I just copied the default config Lazyvim had and added the keymap at the end. The reason it was only functioning the first time was because the config function added the defaults again and overwrote the one the user had set.
