### ISSUE TITLE
feature: consider using heirline?

### ISSUE THREAD

**Issue by gacallea** [LazyVim/LazyVim#2394]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

heirline could help reduce the number of dependencies with lualine, bufferline, and more.

### Describe the solution you'd like

heirline is a modern and elegant plugin to define statusline, winbar, tabline, statuscolumn and possibly more

### Describe alternatives you've considered

currently using what LazyVim provides.

### Additional context

I first was introduced to heriline when I tried AstroNvim. I must say it's impressive. https://github.com/rebelot/heirline.nvim

**Comment by SnakeHit** [comment]
+1

**Comment by kobzar** [comment]
-
For simple users configure or change heirline look like Space boat control pannel.

**Comment by folke** [comment]
I'm good with lualine
