### ISSUE TITLE
bug: Markdown syntax highlighting stopped working

### ISSUE THREAD

**Issue by leehpham** [LazyVim/LazyVim#2398]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

MacOS 13.6.3

### Describe the bug

Markdown syntax highlighting stopped working.

One thing I noticed is that when I opened a single Markdown file with `nvim foo.md`, the syntax highlighting seemed to work as expected but after a quick second, all the highlights disappeared.

Screenshot:
![Screenshot 2024-01-21 at 8 32 07 PM](https://github.com/LazyVim/LazyVim/assets/16496282/8b867263-ac32-4f08-8246-76547e2c7cf3)

I have tried re-installing `markdown` and `markdown-inline` for `nvim-treesitter` but this didn't fix the issue.

### Steps To Reproduce

1. Open a Markdown file with nvim using `nvim foo.md`.

### Expected Behavior

Markdown syntax highlighting should work.

**Comment by folke** [comment]
due to changes in treesitter. update nvim-treesitter and tokyoight
