### ISSUE TITLE
bug: checkhealth for telescope seems to stop working

### ISSUE THREAD

**Issue by thisguychris** [LazyVim/LazyVim#2406]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev-2008+g4ee656e4f

### Operating system/version

Ubuntu 22.04.1 LTS

### Describe the bug

I am getting

`- ERROR No healthcheck found for "telescope" plugin.`

When I run `:checkhealth telescope`

### Steps To Reproduce

1. Install LazyVim
2. run :checkhealth telescope

### Expected Behavior

should run telescope's checkheatlh

**Note:**
_minimal repro does work though_

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",

  {
    "nvim-telescope/telescope.nvim",
    tag = "0.1.5",
    dependencies = { "nvim-lua/plenary.nvim" },
  },

}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
`checkhealth` can only run for loaded plugins.
So you need to open telescope first and then run checkhealth.

To run checkhealth for all plugins:

- first load all plugins: `:Lazy load all`
- run checkhealth: `:checkhealth`

**Comment by folke** [comment]
fyi: I just added a new `:LazyHealth` command to LAzyVim that loads all plugins before running `:checkhealth`

**Comment by thisguychris** [comment]
Thanks @folke You rock! 🤘
