### ISSUE TITLE
bug: Some or all vim options can't be overriden in options.lua

### ISSUE THREAD

**Issue by davidnorth** [LazyVim/LazyVim#2423]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Debian

### Describe the bug

The docs state that the default options are loaded "before your own" which I understand to mean that anything I place in options.lua will override anything already set. However the following doesn't take effect for me. 

`vim.opt.formatoptions:remove({ "c", "r", "o" })`

echo &formatoptions shows:  rjcroql

Note that the above command when entered manually does work, i.e. 
`lua vim.opt.formatoptions:remove({ "c", "r", "o" })`

Other settings in my options.lua do work but I believe none of these override a lazyvim default.

### Steps To Reproduce

1. Add my formatoptions line to options.lua
2. Restart nvim
3. echo &formatoptions to check if the setting was applied

### Expected Behavior

My formatoptions would not include c, r & o

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by davidnorth** [comment]
Closing because I believe a plugin is responsibel for this. I am able to override tabstop for example.

**Comment by davidnorth** [comment]
Its a duplicate of https://github.com/LazyVim/LazyVim/issues/80#issuecomment-1478662212
Needs to go in an autocommand. Not sure why this is necessary for this option in particular.

**Comment by dpetka2001** [comment]
@davidnorth 

For future reference, if you open Neovim with `nvim -V1` and then when you open a buffer, you press `:verbose set formatoptions?` for example, it will show you the last place the option was set. This way you can find who the culprit is for other options that you might want to change and can't. Setting a `FileType` autocommand is usually the best way to bypass trouble like this.
