### ISSUE TITLE
feature: Add support for lsp zero

### ISSUE THREAD

**Issue by rubiin** [LazyVim/LazyVim#2428]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Collection of functions that will help you setup Neovim's LSP client, so you can get IDE-like features with minimum effort.

### Describe the solution you'd like

An extra or something to use lsp zero.

### Describe alternatives you've considered

N/A

**Comment by kobzar** [comment]
Try to use :LazyExtras for this 
For example 
https://www.lazyvim.org/extras/lang/python
(in left side you can see other langs presets)

**Comment by folke** [comment]
LazyVim pretty much already does everything lsp zero does.

You can use mason to install an lsp and it will work out of the box

**Comment by thobiasn** [comment]
> LazyVim pretty much already does everything lsp zero does.
> 
> You can use mason to install an lsp and it will work out of the box

Not on NixOS which is how I found this thread. 
https://nix.dev/guides/faq#how-to-run-non-nix-executables
