### ISSUE TITLE
bug: Use error in WSL

### ISSUE THREAD

**Issue by j2501987804** [LazyVim/LazyVim#2434]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Arch wsl

### Describe the bug

![图片](https://github.com/LazyVim/LazyVim/assets/41771911/e7932320-1ec9-45c5-bfe5-1a656547bd09)
I use WSL2 Archlinux. I don't know why this is the case for specific reasons. Is there any idea to help solve it? This depends on Lazyvim that has nothing to do with Lazyvim

### Steps To Reproduce

rm -rf ~/.config/nvim
rm -rf ~/.local/share/nvim
git clone https://github.com/LazyVim/starter ~/.config/nvim

### Expected Behavior

![图片](https://github.com/LazyVim/LazyVim/assets/41771911/fbe9abfd-1463-41c1-853d-24b2eb09bb04)

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by abeldekat** [comment]
This [issue](https://github.com/folke/lazy.nvim/issues/1025#issuecomment-1719989652) in lazy.nvim *might* be related.

There is also a [PR](https://github.com/folke/lazy.nvim/pull/1055)

**Comment by folke** [comment]
Probably fixed by https://github.com/folke/lazy.nvim/commit/d2a4ce22dc02aa08c176cd7692b5b0ed74e4722b
