### ISSUE TITLE
feature: Setting color of the column cursor

### ISSUE THREAD

**Issue by raguay** [LazyVim/LazyVim#2435]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

I want to use the line cursor and the column cursor together. I can turn it on in LazyVim, but I can't get the color to set. I'm using:

```lua
vim.cmd([[highlight ColorColumn ctermbg="#5144528" guibg="#5144528"]])
```

but it doesn't seem to do anything. Any ideals?

I can manually run the command in the Ex mode, but not in a Lua script.

### Describe the solution you'd like

I would like a way to set the column cursor colors based on the current theme, but I can't get it to work.

### Describe alternatives you've considered

I've tried all these variations as well:

```lua
      vim.o["CursorColumn"] = "#544158"
      vim.api.nvim_set_option_value("CursorColumn", "#544158", {})
      vim.api.nvim_set_hl(0, "ColorColumn", { ctermbg = 0, bg = "#544158", force = true })
      vim.cmd([[highlight cursorcolumn ctermbg='#544158' guibg='#544158']])
      vim.api.nvim_command([[highlight cursorcolumn ctermbg='#544158' guibg='#544158']])
      vim.cmd.highlight({ "cursorcolumn", "guibg='#544158'", "ctermbg='#544158'" })
 ```

**Comment by dpetka2001** [comment]
My guess is that you're setting these highlights in `options.lua` and they're getting overwritten when your colorscheme loads. It would be best to set these highlights in the plugin spec of the colorscheme you use.

**Comment by raguay** [comment]
I'm setting it in the setup for the Dracula theme that I use. But, I
haven't used options.lua. I'll look into that and see if it works. Thanks.

Richard

**Comment by dpetka2001** [comment]
Do you mean this [dracula](https://github.com/Mofiqul/dracula.nvim)?

**Comment by dpetka2001** [comment]
Try the following
```lua
  {
    "Mofiqul/dracula.nvim",
    opts = {
      overrides = {
        CursorColumn = { bg = "#544158" },
      },
    },
  },
```
It should do what you want.

**Comment by raguay** [comment]
Thanks. That works great for me.
