### ISSUE TITLE
feature: Toggle/disable Markdown lint

### ISSUE THREAD

**Issue by j-steinbach** [LazyVim/LazyVim#2437]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

I just want to focus on writing Markdown files the way I want without having a linter get in my way. But every time I sit down and take some quick notes everything gets wriggly underlined and and I don't know how to remove that. Half of my screen is stuff like `[MD027] no-multiple-space-blockquote`

### Describe the solution you'd like

Be able to toggle/disable (Markdown) lint, and some way to set it off by default. It says 'optional' in the Markdown extras, but it comes enabled by default.

### Describe alternatives you've considered

- Disable the linting via a rules-files. I do this for my big notes folder, but I need to now add a secondary file whenever I just want to write some notes. This is also terrible when collaborating.
- Disable the [Markdown Extras](https://www.lazyvim.org/extras/lang/markdown) completely.
- Disable the linter somehow, but I don't understand how it comes together.

This worked for some time, but when I then enable [none-ls](https://www.lazyvim.org/extras/lsp/none-ls) the lint is there again..

```lua
{
  "mfussenegger/nvim-lint",
  optional = true,
  opts = {
    linters_by_ft = {
      --markdown = { "markdownlint" },
      markdown = { },
    },
  },
}
```

**Comment by dpetka2001** [comment]
Doesn't `<leader>ud` work for you for toggling on/off diagnostics?

**Comment by j-steinbach** [comment]
Wow, it does! I didn't know that the linting was under 'diagnostics'. 

Do you also know how to disable these diagnostics by default for Markdown?

**Comment by dpetka2001** [comment]
I personally don't know how to disable diagnostics for a specific source. But you could put in your `~/.config/nvim/lua/config/options.lua` the following `vim.diagnostic.disable()` to disable all diagnostics by default and then use the keymap I mentioned before to toggle them `on/off`.

**Comment by j-steinbach** [comment]
Adding `vim.diagnostic.disable()` behaves weirdly. Toggling `<leader>ud` the first time still says 'disabling diagnostic', so to enable the diagnostics it needs to be enabled a second time. 

(For some reason I also produce swap files every time I edit the buffer and need to clean them manually. Not sure if this is related)

---

I agree that this is not a bug (never was), but I am not fully convinced this is not a feature request. I'll still close it, as I got some direction and maybe can do it myself, but for me the core issue of _not being able to disable Markdown lint by default_ still stands.

**Comment by dpetka2001** [comment]
> Adding vim.diagnostic.disable() behaves weirdly. Toggling <leader>ud the first time still says 'disabling diagnostic', so to enable the diagnostics it needs to be enabled a second time.

Regarding this behavior, there is #2438 waiting to be merged. 

Regarding this was not a bug issue, you're totally right. I didn't read carefully this was a feature request. Apologies for that.

**Comment by j-steinbach** [comment]
Good to know.

I created this abomination to serve my use-case. So far it seems to do what I want, so I don't think we need to reopen this. Thank you very much for your help :)

```lua

local Util = require("lazyvim.util")
-- Disable Lint for Markdown files
local disableLint = vim.api.nvim_create_augroup('disableLint', { clear = true })
vim.api.nvim_create_autocmd({"BufEnter"}, {
  pattern = {"*.md"},
  group = disableLint,
  callback = function(ev)
    Util.toggle.diagnostics()
  end,
  desc = "Disable Markdown lint by default"
})
```

**Comment by dpetka2001** [comment]
You could also do the following
```lua
return {
  {
    "mfussenegger/nvim-lint",
    opts = {
      linters_by_ft = {
        markdown = {},
      },
    },
  },
}
```
That would disable `markdownlint` for Markdown files and you could run `:lua require("lint").try_lint("markdownlint")` to manually invoke it. But if you manually invoke it, that would mean the diagnostics would show in the buffer until you toggle them off again.

**Comment by j-steinbach** [comment]
I tried that before, but when I enable the [none-ls](https://www.lazyvim.org/extras/lsp/none-ls) Extra, the linting returns.

I assume because the Markdown linting is enabled in multiple plugins (`nvim-lint`, `null-ls` and `none-ls`). 

For example this code can also be found in the [Markdown Extra](https://www.lazyvim.org/extras/lang/markdown).

```lua
opts = function(_, opts)
  local nls = require("null-ls")
  opts.sources = vim.list_extend(opts.sources or {}, {
    nls.builtins.diagnostics.markdownlint,
  })
end
```

**Comment by dpetka2001** [comment]
Oh you also have `none-ls` enabled. I see. I don't use that anymore, since `nvim-lint` and `conform` have been the base plugins for some time and I also transitioned my configuration to use them. In that case, instead of disabling `markdownlint` in several places, maybe the auto-command would serve you better.

**Comment by j-steinbach** [comment]
That is good to know that 'none-ls' is not needed. It is very difficult to keep track of all the plugins, especially when they supersede each other and don't have a good description.

I think it should be made more clear that some of the Extras are not needed by default, as the Lazy base config already uses something 'better'.

**Comment by dpetka2001** [comment]
All the Extras are not needed by default. That's why they're called Extras. They are there to provide additional functionality that a user might want. `none-ls` Extra specifically is there, so that users that were using `none-ls` before Lazyvim transitioned to `conform` and `nvim-lint` could still keep their existing `none-ls` configuration if they didn't want to make the transition, since they could achieve almost the same functionality with both configurations. That is also the reason why they are not enabled by default, unless a user specifically enables them. It's up to the user to decide what he wants to do.

**Comment by j-steinbach** [comment]
Fair point. But I believe that to make an informed decision the user needs to have enough information. For example everything you are telling me right now is something I did not know before. So I naively enabled the `none-ls` package, as I thought it would somehow improve my installation.

Adding something along the lines of `The _none-ls_ Extra does not provide extra functionality, but is an alternative to _conform_ and _nvim-lint_, which LazyVim is using by default.` would have helped me make a better decision.

Compare this also to e.g. the language Extras, which add extra functionality that is not there by default. For example I might not write _Rust_ by default, but enabling the Extra also won't hurt me.
