### ISSUE TITLE
bug: deleting default keymaps in lua/config/keymap.lua does not always work

### ISSUE THREAD

**Issue by dnebauer** [LazyVim/LazyVim#2439]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.5

### Operating system/version

Debian 6.5.13-1 (2023-11-29) 

### Describe the bug

According to [https://www.lazyvim.org/configuration/keymaps](https://www.lazyvim.org/configuration/keymaps), "Global keymaps are keymaps that are always active. You can configure them in your "lua/config/keymaps.lua" file. Default LazyVim keymaps can be deleted with `vim.keymap.del`."

I tried this method for deleting the default normal mode mappings for the "todo-comment.nvim" plugin: `<Leader>st`, `<Leader>sT`, `<Leader>xt`, and `<Leader>xT`. My experience afterwards was that the mappings were deleted in only 2 out of 10 nvim starts.

Without any idea of LazyVim's and lazy.vim's architecture I can only speculate on what is happening. I suspect competing processes and so added a `vim.cmd.sleep(5)` command before the mapping deletion commands. After this the mappings were deleted in 7 out of 10 nvim starts. Given such limited testing this improvement may or may not be significant.

Is there anything I can do to ensure default LazyVim mappings are deleted every time?

### Steps To Reproduce

1. Add command `vim.keymap.del("n", "<Leader>st")` to "lua/config/keymaps.lua"
2. After each nvim start check for the mapping with `:map <Leader>st`

### Expected Behavior

Based on the LazyVim documentation at [https://www.lazyvim.org/configuration/keymaps](https://www.lazyvim.org/configuration/keymaps) referred to above, I expected the mappings to be deleted in every nvim start, but instead the deletion is successful in only a fraction of starts.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
The mappings you're referring to are Plugin keymaps and you should disable them the way for [disabling plugin keymaps](https://www.lazyvim.org/configuration/plugins#%EF%B8%8F-adding--disabling-plugin-keymaps). The global mappings the docs are referring to are the ones that don't belong to a plugin spec and are defined in [lazyvim/config/keymaps.lua](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua) (keymaps for moving between windows, altering the size of windows, moving lines up/down etc).

So, in general, if you would like to disable a keymap, you should search this repo (for example search for `<leader>st`) and it will give you the place the keymap is defined. Then you can see if it's defined in [lazyvim/config/keymaps.lua](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua) or in a plugin spec inside the `keys` section and proceed accordingly.

**Comment by dnebauer** [comment]
Thank you for taking the time to write such a clear explanation. I see where I went wrong and have been able to disable the mappings. Hope this helps future newbies who take the same wrong turn I did...
