### ISSUE TITLE
feature: Add py-requirements.nvim

### ISSUE THREAD

**Issue by rneithon** [LazyVim/LazyVim#2445]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

No i have problem. but LazyVim will be more useful if add this plugin.

### Describe the solution you'd like

Add [py-requirements.nvim](https://github.com/MeanderingProgrammer/py-requirements.nvim)

### Describe alternatives you've considered

It is like a Python version of Crates.nvim, which will make it easier to write requirements.txt

**Comment by rneithon** [comment]
If you think this idea is good, I'll try to make a PR myself.

**Comment by kobzar** [comment]
For my opinion this plugind user must use by their choice. 
Not all of them use python.
From another side, the good practics is use Poetry.
Poetry is not only pkg selector, this is powerfull project manager for python.
For this time this plugin is to raw. How to update selected pkg to last version, all pkg? e.t.c
So, its look nice but dont needed as default in LazyVim.

**Comment by folke** [comment]
You can just add this to yourpersonal config. No need for an extra
