### ISSUE TITLE
bug:  alpha-nvim can't enable

### ISSUE THREAD

**Issue by Matrix-Zhang** [LazyVim/LazyVim#2456]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.5

### Operating system/version

macos 14.3

### Describe the bug

<img width="1214" alt="image" src="https://github.com/LazyVim/LazyVim/assets/1751829/50028c59-eb70-45e7-b2f1-ff023611d645">

### Steps To Reproduce

enable alpha-nvim

### Expected Behavior

no errors

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
Not able to reproduce. Do you maybe have other dashboards enabled at the same time as well?

**Comment by Matrix-Zhang** [comment]
> Not able to reproduce. Do you maybe have other dashboards enabled at the same time as well?

no, there is don't have any other dashboard

**Comment by dpetka2001** [comment]
Can you try the following
```bash
1. `mkdir ~/.config/lazytest`
2. `git clone https://github.com/LazyVim/starter ~/.config/lazytest`
3. `NVIM_APPNAME=lazytest nvim` and wait for the installation to complete
4. Restart Neovim with the command provided in step 3
```
Do you observe the same behavior with the above commands?
For cleanup do
```bash
rm -rf ~/.config/lazytest
rm -rf ~/.local/share/lazytest
rm -rf ~/.local/state/lazytest
rm -rf ~/.cache/lazytest
```

**Comment by Matrix-Zhang** [comment]
> Can you try the following
> 
> ```shell
> 1. `mkdir ~/.config/lazytest`
> 2. `git clone https://github.com/LazyVim/starter ~/.config/lazytest`
> 3. `NVIM_APPNAME=lazytest nvim` and wait for the installation to complete
> 4. Restart Neovim with the command provided in step 3
> ```
> 
> Do you observe the same behavior with the above commands? For cleanup do
> 
> ```shell
> rm -rf ~/.config/lazytest
> rm -rf ~/.local/share/lazytest
> rm -rf ~/.local/state/lazytest
> rm -rf ~/.cache/lazytest
> ```

yes. I can reduce the same problem.

**Comment by dpetka2001** [comment]
How are you enabling `alpha.nvim`? Do you have a link to your dotfiles available on Github?

**Comment by Matrix-Zhang** [comment]
> How are you enabling `alpha.nvim`? Do you have a link to your dotfiles available on Github?

yes, I enabled it, which dotfile you need?

**Comment by kobzar** [comment]
Just show your alpha.vim plugin file like 
../plugins/file_name.lua
it must contains something like this one

```lua
return {
    'goolord/alpha-nvim',
    dependencies = {
        'nvim-tree/nvim-web-devicons',
        'nvim-lua/plenary.nvim'
    },
    config = function ()
        require'alpha'.setup(require'alpha.themes.theta'.config)
    end
}
```

**Comment by dpetka2001** [comment]
@Matrix-Zhang I want a link to your nvim configuration on github. If you don't have them on Github, plz upload them. You're not exactly giving any reproducible information. 
> yes, I enabled it

How are you enabling it?

**Comment by dpetka2001** [comment]
Also, could you try deleting the directory `~/.local/share/nvim/lazy/` and open Neovim again? It will re-install all plugins from scratch, but maybe something went wrong during the clone procedure of the specific plugin.

**Comment by Matrix-Zhang** [comment]
> ~/.local/share/nvim/lazy/

:LazyExtras enable it, and also <leader + l> Install it

**Comment by dpetka2001** [comment]
Please try deleting `~/.local/share/nvim/lazy/` directory and restart Neovim.

**Comment by Matrix-Zhang** [comment]
> Please try deleting `~/.local/share/nvim/lazy/` directory and restart Neovim.

it worked
