### ISSUE TITLE
vim.opt isn't available `E480: No match: opt`

### ISSUE THREAD

**Issue by dr-kernel** [LazyVim/LazyVim#2468]
vim.opt isn't available for me.  I get the error: `vim.opt.colorcolumn = "90" E480: No match: opt`
I added it to my `../lua/config/options.lua`
same msg when i type it in as a command . 

NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1692716794

**Comment by dpetka2001** [comment]
`vim.opt` should be available for Neovim versions after 0.5. If you have any problem with this, something must be wrong with your Neovim installation. Please make an issue in upstream Neovim repo itself, as this is not a LazyVim bug and out of scope.

**Comment by kobzar** [comment]
This is absolutly rigth variable.
vim.opt.colorcolumn = "90"

Show your options.lua file

**Comment by dr-kernel** [comment]
```lua
vim.opt.colorcolumn = "90"
``` 
that's the only thing in it.

**Comment by kobzar** [comment]
Show your os version and nvim -v
output. 
how are you install neovim?

**Comment by dr-kernel** [comment]
So this works:
```lua
 local opt = vim.opt
opt.colorcolumn = "80"
```
Curious why i couldn't access it directly for the one command?  I would have also expected it to work from a `:` command. 
Perhaps some Lua thing i'm not aware of (very much n00b at lua).
