### ISSUE TITLE
bug: Cant disable Catppuccin color theme

### ISSUE THREAD

**Issue by kobzar** [LazyVim/LazyVim#2470]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

MacOs/Linux

### Describe the bug

I am use MAterial color theme.
So, i try to disable another(default colot themes)
this is my disable conf
```lua
-- disabled.lua
return {
  {
    -- Disable tokyonight theme
    "folke/tokyonight.nvim",
    enabled = false,
  },
  -- Disable catppuccin theme
  { "ellisonleao/gruvbox.nvim", enabled = false },
  { "catppuccin/nvim", enabled = false },
  { "echasnovski/mini.indentscope", enabled = false },
}
```

And all plugins from this list is disabled except the catppuccin.

### Steps To Reproduce

Just try to disable catppuccin color theme

### Expected Behavior

*

**Comment by le-nhat** [comment]
https://github.com/LazyVim/LazyVim/discussions/1774#discussioncomment-7307641

**Comment by kobzar** [comment]
Oh. Sorry. This is it. And thanks for the quick support.
