### ISSUE TITLE
use lua_ls instead of sumneko_lua since sumneko_lua is deprecated

### ISSUE THREAD

**Issue by LovesAsuna** [LazyVim/LazyVim#248]
https://github.com/neovim/nvim-lspconfig/commit/6669f2d8ebc38cfb9e639145569f94be5556d916

**Comment by radvil2** [comment]
up

**Comment by folke** [comment]
I'm aware of this, but I'm waiting for the these PRs/issues:

- [ ] https://github.com/williamboman/mason-lspconfig.nvim/pull/148
- [ ] https://github.com/folke/neodev.nvim/pull/124
- [ ] https://github.com/folke/neoconf.nvim/pull/12

**Comment by folke** [comment]
I've just patched mason in LazyVim, so that should work again
