### ISSUE TITLE
issue: How to send commands to the integrated terminal 

### ISSUE THREAD

**Issue by luisra51** [LazyVim/LazyVim#2480]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.4

### Operating system/version

MacOS 14.2.1 

### Describe the bug

I'm trying to create a keyboard shortcut that executes a command in the terminal that comes with lazyvim by default
```
vim.keymap.set("n", "<leader>glci", function()
	Util.terminal({ "ls -la ./example" }, { cwd = Util.root(), esc_esc = false, ctrl_hjkl = false })
end, { desc = "ls example" })
```

error
![image](https://github.com/LazyVim/LazyVim/assets/7151700/a10b61f3-83bb-438a-a0cb-4ca9a8e9319a)

If i use only comand without args work, example: ls (alone), 

### Steps To Reproduce

1. add the code ⬇️  in `lua/config/keymaps.lua`
```
vim.keymap.set("n", "<leader>glci", function()
	Util.terminal({ "ls -la ./example" }, { cwd = Util.root(), esc_esc = false, ctrl_hjkl = false })
end, { desc = "ls example" })
```
2. open lazyvim and press <leader>glci

### Expected Behavior

The expected one is to create a keymap that executes commands within the lazyvim terminal with the arguments you need

**Comment by le-nhat** [comment]
You can try:
```
vim.keymap.set("n", "<leader>glci", function()
	require("lazy.util").float_cmd({ "ls -la ./example" })
end, { desc = "ls example" })
```
[float_term](https://github.com/folke/lazy.nvim/blob/aedcd79811d491b60d0a6577a9c1701063c2a609/lua/lazy/util.lua#L107) and [float_cmd](https://github.com/folke/lazy.nvim/blob/aedcd79811d491b60d0a6577a9c1701063c2a609/lua/lazy/util.lua#L135)

**Comment by dpetka2001** [comment]
```lua
vim.keymap.set("n", "<leader>glcc", function()
  require("lazy.util").float_cmd({ "ls", "-al" })
end, { desc = "float_cmd" })
```
Try this. `float_term` is for opening executable apps in term I believe (like lazygit for example).

**Comment by le-nhat** [comment]
if you want add location, try this
```
vim.keymap.set("n", "<leader>glci", function()
  require("lazy.util").float_cmd({ "ls", "-la" }, { cwd = vim.fn.expand("./example") })
end, { desc = "ls example" })
```

**Comment by luisra51** [comment]
> ```lua
> vim.keymap.set("n", "<leader>glcc", function()
>   require("lazy.util").float_cmd({ "ls", "-al" })
> end, { desc = "float_cmd" })
> ```
> 
> Try this. `float_term` is for opening executable apps in term I believe (like lazygit for example).

Thanks, it is working, with simple commands like ls -la, I used this as an example, but when using commands like k9s (cli k8s) and glab (cli gitlab) the terminal freezes

**Comment by dpetka2001** [comment]
I don't know what these commands do. Are they supposed to be interactive? Because when you execute `:term cmd` it runs in a non-interactive shell. If you'd like any kind of interaction, you should simply just open a terminal and type your commands. That's just how the Neovim terminal works. Nothing to do with LazyVim I believe, since LazyVim also uses Neovim terminal under the hood.

**Comment by luisra51** [comment]
Yes, they are interactive commands, and the idea of creating a floating terminal with an interactive command occurred to me when I saw how lazygit is executed from lazyvim

**Comment by dpetka2001** [comment]
That is just the app taking care of the interactivity. See `:h :terminal`

> Run {cmd} in a non-interactive 'shell' in a new
			|terminal-emulator| buffer. Without {cmd}, start an
			interactive 'shell'.

If you want that your best bet is to start the terminal yourself and interact with the commands you want (to the best of my knowledge).
