### ISSUE TITLE
bug: plugins/coding nvim-cmp mapping scroll_docs <c-b>/<c-f> don't work

### ISSUE THREAD

**Issue by rltyty** [LazyVim/LazyVim#2482]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

macOS 12.7.2

### Describe the bug

Environment: Kitty+Tmux+Python venv

I'm working on a python project, I can use `<c-n>` , `<c-p>` to select next and prev items in nvim-cmp pop-up menu, but cannot scroll the menu by 4 items. 

I tried to disable `noice` plugin which seems to also bind `<c-b>/<c-f>`,  it didn't work.
I tried to modify the below mapping to some other keys (e..g `<c-k>/<c-j>`) in the default installed `~/.local/share/nvim/lazy/LazyVim/lua/lazyvim/plugins/coding.lua`, and `:verbose imap <c-k>` shows

```
i  <C-K>       * <Lua 858: ~/.local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/keymap.lua:127>                                                                                          
                 cmp.utils.keymap.set_map                                                                                                                                           
        Last set from Lua  
```

but it still didn't work.

https://github.com/LazyVim/LazyVim/blob/7c5a458761fe7002c6603d602e8d130b9a62dd68/lua/lazyvim/plugins/coding.lua#L60-L61

I don't do much custom configuration under `~/.config/nvim`.  How should I investigate on this problem next?

Thanks in advance.

### Steps To Reproduce

Almost default LazyVim configuration with simple lsp custom settings

```lua
return {
  -- lsp
  {
    "neovim/nvim-lspconfig",
    config = function()
      require("lspconfig").lua_ls.setup({
        settings = {
          Lua = {
            diagnostics = {
              -- suppress the "Global vim is undefined" warning
              globals = { "vim" },
            },
          },
        },
      })
      require("lspconfig").pyright.setup({})
    end,
  },
}
```

### Expected Behavior

scrolling back and forth in nvim-cmp pop-up menu work properly

**Comment by dpetka2001** [comment]
Can you try the following
```bash
1. `mkdir ~/.config/lazytest`
2. `git clone https://github.com/LazyVim/starter ~/.config/lazytest`
3. `NVIM_APPNAME=lazytest nvim` and wait for the installation to complete
4. Restart Neovim with the command provided in step 3
```
and without making any changes, test if you observe the same behavior.
For cleanup afterwards, do:
```bash
rm -rf ~/.config/lazytest
rm -rf ~/.local/share/lazytest
rm -rf ~/.local/state/lazytest
rm -rf ~/.cache/lazytest
```

**Comment by rltyty** [comment]
@dpetka2001 Thanks for the reply.

I did the 4 steps as you said. With this fresh new starter template nvim, the problem is still there.

**Reproduce step:**
1. open an empty py file in a new Kitty window.
`NVIM_APPNAME=lazytest nvim a.py
`
2. type `import test.` and cmp pop-up menu shows.
3. Selecting next or previous one menu item with `<c-n>` or `<c-p>` works as expected, while scrolling through docs with `<c-f>` or `<c-b>` doesn't.

`:telescope keymaps` shows

<img width="650" alt="Screen Shot 2024-02-02 at 13 02 41" src="https://github.com/LazyVim/LazyVim/assets/98961340/1e0da94b-b2f5-4758-9470-55bdb10132fa">

`:verbose imap <c-f>` shows

<img width="763" alt="Screen Shot 2024-02-02 at 13 05 02" src="https://github.com/LazyVim/LazyVim/assets/98961340/ff7e0d87-7ab7-41ba-bfab-30b3c6b79ced">


In checkhealth log, there are 3 warnings:

```
lazy.nvim ~
- OK Git installed
- OK no existing packages found by other package managers
- OK packer_compiled.lua not found
- WARNING {telescope-fzf-native.nvim}: overriding <config>
- WARNING {flash.nvim}: unknown key <vscode>
```

```
WhichKey: checking conflicting keymaps ~
- WARNING conflicting keymap exists for mode **"n"**, lhs: **"gc"**
- rhs: ` `
- 
```

**Comment by dpetka2001** [comment]
You seem to be misunderstanding what `<c-f>/<c-b>` do. They scroll not in the auto-completion popup menu is open to select items. They scroll when the `nvim-cmp` docs menu is open. So, you don't scroll items with these keys. You scroll the documentation that opens for a specific item.

**Comment by dpetka2001** [comment]
![2024-02-02_12-58](https://github.com/LazyVim/LazyVim/assets/12776461/462ef1fc-a78b-42ad-bc19-1b4dd36300f7)
Here you can see the docs menu opened for the specific item. If you use `<c-f>/<c-b>` it will scroll the opened docs for the selected item.

**Comment by rltyty** [comment]
@dpetka2001 oh oh, you mean the scroll_dos keys is to scroll in :help nvim-cmp-lsp?

**Comment by dpetka2001** [comment]
See my previous post.

**Comment by dpetka2001** [comment]
Kindly close the issue if that was your problem.

**Comment by rltyty** [comment]
> ![2024-02-02_12-58](https://private-user-images.githubusercontent.com/12776461/301821922-462ef1fc-a78b-42ad-bc19-1b4dd36300f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NzE5MjQsIm5iZiI6MTcwNjg3MTYyNCwicGF0aCI6Ii8xMjc3NjQ2MS8zMDE4MjE5MjItNDYyZWYxZmMtYTc4Yi00MmFkLWJjMTktMWI0ZGQzNjMwMGY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDExMDAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlMzJiOTgwOTAxNzE2NWY0Y2FiMzFmODRjMGNiMTIwMGE0MWMzMmNjZGQ0Y2Q4MzQxYTBmNzBiMzAzNmZhNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iKClOT1cBNaoXD4b8TCuhtUjyFGajVLRCyRKxa1thcQ) Here you can see the docs menu opened for the specific item. If you use `<c-f>/<c-b>` it will scroll the opened docs for the selected item.

Oh, I got it, you mean scrolling in the function document?

**Comment by rltyty** [comment]
Thanks a lot for the explanation, @dpetka2001. Sorry for my misunderstanding.

**Comment by dpetka2001** [comment]
No problem, glad to help :smile:
