### ISSUE TITLE
issue: How to add toggleterm to lazyvim setup 

### ISSUE THREAD

**Issue by rohan-kapse** [LazyVim/LazyVim#2485]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

Windows 11 

### Describe the bug

Hello, I have just shifted to lazyvim and messing up with configs to learn. The one such plugin I want is toggleterm to be added to my lazyvim, I just dont know to do it. Please can someone guide me step by step as to where to do what. (which file to make changes and so on in detail). Thank You ! 

### Steps To Reproduce

1. To configure the lazyvim setup.

### Expected Behavior

Want to setup toggleterm in lazyvim.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by rohan-kapse** [comment]
@le-nhat Thanks, but whats the key for opening it horizontally and splitting sessions,

**Comment by kobzar** [comment]
@rohan-kapse 
Just read answers
https://github.com/dpetka2001/dotfiles/blob/main/dot_config/nvim/lua/plugins/toggleterm.lua

**Comment by rohan-kapse** [comment]
@kobzar Solved, it works !

**Comment by rohan-kapse** [comment]
@kobzar Solved, it works ! 😅
