### ISSUE TITLE
bug: treesitter/highlighter: Error executing lua:    ..... im-win64/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid

### ISSUE THREAD

**Issue by networkpankaj** [LazyVim/LazyVim#2486]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.95

### Operating system/version

windows

### Describe the bug

lua failed to grow stack to 4003

### Steps To Reproduce

lua failed to grow stack to 4004

### Expected Behavior

Lua failed

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by kobzar** [comment]
Could you attach full log?

**Comment by Mephistophillis** [comment]
After the update I encountered a similar error. :TSUpdate command helped me

**Comment by networkpankaj** [comment]
Ohhk i got it , can i ask you something

**Comment by networkpankaj** [comment]
Bro can you give me suggestion how i connect girhub

**Comment by SymphonySimper** [comment]
> After the update I encountered a similar error. :TSUpdate command helped me

Sadly, this did not work for me. Any other solution/ workaround?

**Comment by SymphonySimper** [comment]
My issue was because of a bug with the latest update on nvim-treesitter-context. So they fixed it.
