### ISSUE TITLE
feature: disable individual capabilities per server

### ISSUE THREAD

**Issue by pprotas** [LazyVim/LazyVim#249]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

This seems like a common problem when it comes to `nvim-lsp`. Some LSP servers configure capabilities that conflict with each other, and not every LSP server allows configuration to disable the conflicting capabilities. For example, the `tsserver` LSP configures formatting by default, and there is no easy way to disable it. This creates conflicts with formatters like `prettier`, since now 2 formatters are used at the same time. The neovim docs recommend using the `filter` function to [disable specific formatters](https://neovim.io/doc/user/lsp.html#vim.lsp.buf.format()), which is not a great solution in my opinion.

I think the greater problem here is the fact that there is no way to enable/disable capabilities per server. Another example is where the `eslint-lsp` formatting capability is actually disabled by default, and the user needs to overwrite the `require("lazyvim.util").on_attach` function manually to enable it. 

[Here](https://github.com/LazyVim/LazyVim/discussions/100) is another example of a user wanting to disable the `jsonls` formatter in favor of `null-ls`.

### Describe the solution you'd like

I propose a way to disable/enable capabilities per server:

```lua
return {
  {
    "neovim/nvim-lspconfig",
    opts = {
      format = {
        async = true,
      },
      setup = {
        tsserver = {
          capabilities = {
            formatting = false,
          },
          -- Other configuration
        },
        eslint = {
          capabilities = {
            formatting = true,
          },
          -- Other configuration
        },
        solargraph = {
          capabilities = {
            diagnostics = false,
          },
          -- Other configuration
        },
      },
    },
  },
}
```

LazyVim should handle the enabling/disabling of capabilities in the back-end. If no option is specified, it should keep its current, default behavior. For example, the `eslint` format capabilities is `false` by default, while the `tsserver` format capability is true.

### Describe alternatives you've considered

[Formatting filter](https://neovim.io/doc/user/lsp.html#vim.lsp.buf.format()), this only works for the formatting capability and is not a clean solution. [Here](https://github.com/jose-elias-alvarez/null-ls.nvim/wiki/Avoiding-LSP-formatting-conflicts) are the `null-ls` docs that describe something similar.

Another option is disabling the capability by overwriting the `on_attach` function:

```lua
return {
  {
    "neovim/nvim-lspconfig",
    opts = {
      format = {
        async = true,
      },
      setup = {
        tsserver = function(_, opts)
          require("lazyvim.util").on_attach(function(client, buffer)
            if client.name == "tsserver" then
              -- stylua: ignore
              vim.keymap.set("n", "<leader>co", "<cmd>TypescriptOrganizeImports<CR>", { buffer = buffer, desc = "Organize Imports" })
              -- stylua: ignore
              vim.keymap.set("n", "<leader>cR", "<cmd>TypescriptRenameFile<CR>", { desc = "Rename File", buffer = buffer })

              client.server_capabilities.documentFormattingProvider = false
            end
            if client.name == "eslint" then
              client.server_capabilities.documentFormattingProvider = true
            end
          end)
          require("typescript").setup({ server = opts })
          return true
        end,
      },
    },
  },
}
```

Which, again, is not great since now I have `eslint` configuration under `tsserver`.

### Additional context

https://neovim.discourse.group/t/help-needed-to-stop-two-competing-servers-formatting-javascript/1422

https://www.reddit.com/r/neovim/comments/qxj389/tsserver_and_eslint_format_conflict/

**Comment by pprotas** [comment]
If you want, I can work on this and submit a PR!

**Comment by folke** [comment]
This is already possible

```lua
  {
    "neovim/nvim-lspconfig",
    opts = {
      setup = {
        clangd = function(_, opts)
          opts.capabilities.offsetEncoding = { "utf-16" }
        end,
      },
    },
  }
```

**Comment by pprotas** [comment]
Ah whoops 😅! That is news to me. Is there documentation for this?

**Comment by folke** [comment]
It's probably a bit hidden, but it's in the lspconfig opts section https://www.lazyvim.org/plugins/lsp#nvim-lspconfig

**Comment by pprotas** [comment]
In your example, `clang` provides a `capabilities` option: https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#clangd

But not every LSP has this option, for example `tsserver`: https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#tsserver

And `eslint`: https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#eslint

So this will not work for every server. I just tried it with this config:

```lua
return {
  {
    "neovim/nvim-lspconfig",
    opts = {
      format = {
        async = true,
      },
      setup = {
        tsserver = function(_, opts)
          opts.capabilities.documentFormattingProvider = false
        end,
        eslint = function(_, opts)
          opts.capabilities.documentFormattingProvider = true
        end,
      },
    },
  },
}
```

And the `tsserver` formatting is still being called, see my `:LspLog`:
```
# tsserver still registers documentFormattingProvider
[INFO][2023-02-12 11:12:59] .../lua/vim/lsp.lua:1341	"LSP[tsserver]"	"server_capabilities"	{  server_capabilities = {    callHierarchyProvider = true,    codeActionProvider = {      codeActionKinds = { "source.fixAll.ts", "source.removeUnused.ts", "source.addMissingImports.ts", "source.organizeImports.ts", "quickfix", "refactor" }    },    completionProvider = {      resolveProvider = true,      triggerCharacters = { ".", '"', "'", "/", "@", "<" }    },    definitionProvider = true,    documentFormattingProvider = true,    documentHighlightProvider = true,    documentRangeFormattingProvider = true,    documentSymbolProvider = true,    executeCommandProvider = {      commands = { "_typescript.applyWorkspaceEdit", "_typescript.applyCodeAction", "_typescript.applyRefactoring", "_typescript.configurePlugin", "_typescript.organizeImports", "_typescript.applyRenameFile", "_typescript.goToSourceDefinition" }    },    foldingRangeProvider = true,    hoverProvider = true,    implementationProvider = true,    inlayHintProvider = true,    referencesProvider = true,    renameProvider = {      prepareProvider = true    },    selectionRangeProvider = true,    semanticTokensProvider = {      full = true,      legend = {        tokenModifiers = { "declaration", "static", "async", "readonly", "defaultLibrary", "local" },        tokenTypes = { "class", "enum", "interface", "namespace", "typeParameter", "type", "parameter", "variable", "enumMember", "property", "function", "member" }      },      range = true    },    signatureHelpProvider = {      retriggerCharacters = { ")" },      triggerCharacters = { "(", ",", "<" }    },    textDocumentSync = {      change = 2,      openClose = true,      save = {        includeText = false      },      willSave = false,      willSaveWaitUntil = false    },    typeDefinitionProvider = true,    workspaceSymbolProvider = true  }}

# Format command still triggers tsserver, while eslint is not being triggered
[DEBUG][2023-02-12 11:13:08] .../lua/vim/lsp.lua:1388	"LSP[tsserver]"	"client.request"	5	"textDocument/formatting"	{  options = {    insertSpaces = true,    tabSize = 2  },  textDocument = {    uri = "file:///<myfile>.tsx"  }}	<function 1>	3
[DEBUG][2023-02-12 11:13:08] .../vim/lsp/rpc.lua:284	"rpc.send"	{  id = 3,  jsonrpc = "2.0",  method = "textDocument/formatting",  params = {    options = {      insertSpaces = true,      tabSize = 2    },    textDocument = {      uri = "file:///<myfile>.tsx"    }  }}
```

**Comment by folke** [comment]
Every server **does** have capabilities. Just do a `vim.pretty_print` of the opts. Not every server sets capabilities in lspconfig, but that is not relevant.

What you see in the log are the `server_capabilities`. This just means that tsserver is capable of doing formatting.

What you are defining in the setup are `client_capabilities`. This tells tsserver that the client does not support formatting.

capabilities are part of the spec. It seems that tsserver does not honor the client capabilities completely. There are also tsserver settings to disable formatting, but they are also ignore when a client requests formatting anyway.

I just pushed a change specifically for formatting that wont format if the client capability has been disabled to work-around this.
