### ISSUE TITLE
bug: Bug Report - Unwanted Notification in LazyVim Plugin Manager

### ISSUE THREAD

**Issue by GUNGODD** [LazyVim/LazyVim#2493]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

WINDOWS 11 / WSL 

### Describe the bug

The LazyVim plugin manager currently displays a notification suggesting that users may need to run Codeium auth because no API keys are found. However, this notification persists even for users who haven't subscribed to Codeium's premium plans and,  do not have access to free API keys. This behavior is misleading, unnecessary, and  frustrating for users, including myself.

### Steps To Reproduce

1. Install LazyVim plugin manager.
2. Open Neovim.
3. Observe the notification: "No API keys found: maybe you need to run Codeium auth."

### Expected Behavior

![Screenshot 2024-02-03 213010](https://github.com/LazyVim/LazyVim/assets/104669514/b5d06681-6f55-43ab-b617-f21f10f2c76d)

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
Why don't you just disable the plugin since you don't plan to authorize in order to use it? `Codeium` is not enabled by default. It's just an extra that the users themselves enable (those who want to use it with credentials).

Also this is not a LazyVim bug. That notification comes straight from the plugin `Codeium` itself, so if you don't like this behavior, just create an issue at the plugin's repo. LazyVim doesn't deal with codebases that come from plugins. Kindly close this issue.

**Comment by GUNGODD** [comment]
thank mate for your response .. !!
