### ISSUE TITLE
bug:    Failed     ◍ fsautocomplete       ▶ # [3/3] spawn: dotnet failed with exit code - and signal -. dotnet is not executable  

### ISSUE THREAD

**Issue by jscodinity** [LazyVim/LazyVim#2499]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

windows 10

### Describe the bug

when i install fsautocomplete it show me this error

### Steps To Reproduce

it show me this error

### Expected Behavior

help me 

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
From your error it seems that you don't have [dotnet-sdk](https://dotnet.microsoft.com/download) installed. You should install that. 

Kindly close this issue, since it's not a LazyVim bug, rather a user configuration issue with your OS.
