### ISSUE TITLE
feature: Option to remove stylua from mason and install it with system package manager

### ISSUE THREAD

**Issue by sabinpuiu** [LazyVim/LazyVim#2503]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

NixOS cannot run dynamically linked executables intended for generic linux environments out of the box.

### Describe the solution you'd like

It would be great if i could somehow remove things from mason opts.ensure_installed, so i can install them myself via the system package manager.

### Describe alternatives you've considered

Disabling mason entirely, which i dont really wanna do since everything else works for me except stylua.

**Comment by dpetka2001** [comment]
Can't you just do
```lua
-- ~/.config/nvim/lua/plugins/mason.lua
return {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {},
    },
  },
}
```
This will empty out the `opts.ensure_installed` that LazyVim provides and you can uninstall what you want from the `Mason` UI. They shouldn't be installed again. You can also populate `opts.ensure_installed` with whatever you'd like to get installed by default in your configuration.
