### ISSUE TITLE
bug: xsel open too many files.

### ISSUE THREAD

**Issue by XunHang** [LazyVim/LazyVim#2511]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

Ubuntu 20.04.4 LTS x86_64

### Describe the bug

When I start the nvim, the files it opens slowly grow over time.
When the file exceeds 1024, the neo-tree plug-in will report an error, nvim will freeze to the point of being unusable, and the clipboard will not work.

I use this `ulimit` to check the limit of files and it is 1024.
```shell
>>> ulimit -a | grep file
-f: file size (blocks)              unlimited
-c: core file size (blocks)         0
-n: file descriptors                1024
-x: file locks                      unlimited
```

Then I open a file and use `ps` to know all pids of nvim.
```shell
>>> ps -A | grep nvim
 431194 ?        00:02:48 nvim
3154958 pts/4    00:00:01 nvim
3154961 ?        00:00:00 nvim
3154968 ?        00:04:56 nvim
```
Finally, I use `watch` to know the files number opened.
```shell
>>>  watch -n 1 "lsof -p 3154958,3154961,3154968,431194 |wc -l"
```

Then I see the number gradually rises. When it is greater than 1024 for a while, the following error will appear.

![image](https://github.com/LazyVim/LazyVim/assets/17587962/ee4a43ae-8460-45e6-985b-be2b8896b730)

![image](https://github.com/LazyVim/LazyVim/assets/17587962/e375219a-41f8-4cc3-8dd5-7b8eacdab22c)

### Steps To Reproduce

1. use nvim to open a small project or a file;
2. Go to other applications or workspaces and do whatever you want, and just wait for a while (sometimes it may take up to half an hour)
3. go back and use neo-tree or telescope, ERROR will be shown.

### Expected Behavior

Nvim with lazyvim can be used for long periods of time without crashing。

### Repro

```Lua
I do not know how to save repro.lua. (TAT)
```

**Comment by dpetka2001** [comment]
The error comes from neo-tree. Why don't you create an issue at the repo? If it affects xclip, maybe it has also something to do with Neovim upstream (although it could be just a side effect), not sure about that. Either way doesn't seem like a LazyVim specific bug.

**Comment by XunHang** [comment]
Sorry, I start use vim through LazyVim, I will close this issue and move it to Neo-Tree.
Thank you.
