### ISSUE TITLE
bug: searching fs automatically exits search mode

### ISSUE THREAD

**Issue by blurskye** [LazyVim/LazyVim#2514]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.4 Build type: Release LuaJIT 2.1.1702233742

### Operating system/version

arch linux

### Describe the bug

/fs automatically exits search mode, cant search anything that has "fs" at the begining

with the minimum init.lua, repro.lua, it doesnt happen, i downgraded to 0.9.4 just to check, and yes the issue is persistant

### Steps To Reproduce

type `/fs` in normal mode

### Expected Behavior

to continue to stay in search mode until i press return/enter,

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
That is a feature that `flash.nvim` provides for labels in the search mode. There are 2 options:
1. Disable the feature entirely
```lua
return {
	{
  		"folke/flash.nvim",
  		opts = {
    		modes = {
      			search = {
        			enabled = false,
      			},
    		},
  		},
	},
}
```
2. Press `<C-s>` while in search mode to temporarily toggle off this feature in case you want to use it another time.
