### ISSUE TITLE
feature: provide a mechanism to remove pre-configured whichkey groups

### ISSUE THREAD

**Issue by gunslingerfry** [LazyVim/LazyVim#2518]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Feel free to close this because it is a rather silly use case. 

I love a lot about LazyVim but I've already got very well established keymaps for single keys. In particular <leader>f for fuzzy searching files and <leader>b for listing buffers. Unfortunately, when WhichKey shows up the first time it seems to somehow eat my bindings and does not list the <leader>f or <leader>b because they've been set aside for groups.

### Describe the solution you'd like

Provide some sort of overriding mechanism for whichkey groups in order to better customize.

### Describe alternatives you've considered

Obviously, I could just get used to a different keymap. I don't waaant to though.

**Comment by dpetka2001** [comment]
This looks similar to #2193. So that's your answer there. 

If you would like to simply just hide the label from `which-key` menu, you could do `["<leader>f] = which_key_ignore`. That doesn't mean that the keymaps are deleted. The top-level key will just not be visible on the menu. If you'd like to remove all the keys, there's no other way than manually deleting them.

If you'd like to change all the `<leader>f` keys to something else, you can use the plugin that is mentioned in the other issue.

**Comment by gunslingerfry** [comment]
So I've already changed all the <leader>f keys one by one. It was a pain, yes, but it's possible so that's not my issue. The problem is that once which key shows everything goes real weird.

So I guess there is two asks/problems:
1. My request is to disable or override the groups so that normal bindings show in which-key
2. There is a bug when you use noremap on a binding that is assigned to a group.

`vim.keymap.set("n", "<leader>f", require("telescope.builtin").find_files, { desc = "find files in working directory", noremap=true })` << binding breaks

`vim.keymap.set("n", "<leader>f", require("telescope.builtin").find_files, { desc = "find files in working directory" })` << binding is fine, but still doesn't work if you wait for timeoutlen and which-key to load.

Interestingly, I've found that you could utilize this to have fast and slow bindings. I didn't disable the maps for `<leader>b{key}` but added my own. If I do the mapping within timeoutlen it uses my binding. If I let timeoutlen expire it pulls up whichkey and uses the group.

**Comment by dpetka2001** [comment]
This is specific to `which-key`, so I'd suggest creating an issue at the repo, since LazyVim has nothing to do with that.

**Comment by gunslingerfry** [comment]
Sorry for the multiple edits. Yes and no. The problem is not with how which-key is generally used. It's only a problem because of the LazyVim which-key defaults. It's hardly a use case for which-key itself to handle someone creating an empty group on a particular mapping and then also creating a mapping on top. The answer would be to not create the empty group. I can't stop the creation of the empty group through the specs that LazyVim provides.

It's sorta related to the empty group thing and it sounds like what @folke was saying about it eating the leader key but in this case the mapping is _gone entirely_,

**Comment by dpetka2001** [comment]
Again, this is very similar to #2193 (providing a mechanism to remove pre-configured groups) and the maintainer already gave an answer there. My guess is your request falls under the same assumptions as in that issue. I'm just a regular user without a say in the project, so maybe the maintainer has a different opinion on this. 

Either way, what I can suggest you is to either use `which_key_ignore` to hide the specific key you want from the `which-key` top-level menu (but that won't delete the keymaps and they will still be available) or delete all the keymaps you want and change the `which-key` defaults to whatever you like.

**Comment by gunslingerfry** [comment]
Yeah I think disabling which-key or, perhaps, just mapping the which-key leader key to something else will solve my problem. I think it is a more serious issue that the mappings are changing/disappearing due to which-key though.

**Comment by dpetka2001** [comment]
That is an issue directed to the which-key repo though, since its codebase is responsible for how to interact with groups. Lazyvim just uses it to define groups and map keys.

**Comment by gunslingerfry** [comment]
Alright I'll create an issue there.
