### ISSUE TITLE
bug: Cannot install lsp servers with Mason

### ISSUE THREAD

**Issue by madflow** [LazyVim/LazyVim#252]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.3

### Operating system/version

MacOS Ventura, arm64

### Describe the bug

When I try to set lsp serves like described here:

https://github.com/LazyVim/starter/blob/main/lua/plugins/example.lua

I always get:

```
Failed to run `config` for mason.nvim

...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:68: Cannot find package "denols".

# stacktrace:
  - /mason.nvim/lua/mason-registry/init.lua:68 _in_ **get_package**
  - /LazyVim/lua/lazyvim/plugins/lsp/init.lua:169 _in_ **config**
  - /telescope.nvim/lua/telescope/actions/set.lua:168 _in_ **run_replace_or_original**
  - /telescope.nvim/lua/telescope/actions/mt.lua:65 _in_ **run_replace_or_original**
  - /telescope.nvim/lua/telescope/actions/mt.lua:65 _in_ **run_replace_or_original**
  - /telescope.nvim/lua/telescope/actions/mt.lua:65 _in_ **key_func**
  - /telescope.nvim/lua/telescope/mappings.lua:350 _in_ **execute_keymap**
  - lua:1
 ```

### Steps To Reproduce

* I cloned https://www.lazyvim.org/installation
* Started nvim
* Updated Lazyvim and plugins
* created a new file `plugins/lsp.lua`

```
return {

  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "denols",
      },
    },
  },
}
```

### Expected Behavior

The Deno Language Server should be installed.

### Repro

```Lua
see above
```

**Comment by folke** [comment]
![image](https://user-images.githubusercontent.com/292349/218307072-ba73b253-8c2b-43cd-b988-821ad87b8a0c.png)

**Comment by appelgriebsch** [comment]
I guess the package is just named `deno` in mason.nvim: https://github.com/williamboman/mason.nvim/blob/main/lua/mason-registry/deno/init.lua#L9

**Comment by folke** [comment]
it is, but it's better to use `denols` in the lspconfig section. No need to specify it under `ensure_installed` for mason

**Comment by madflow** [comment]
I understand that this is not a bug, but more likely a documentation or experience "how things work" issue. I just read https://github.com/LazyVim/starter/blob/1a2b26d37c1601b53d7ef0641fd790ffe3b1c395/lua/plugins/example.lua#L203 and did that .

So in order to add servers and have them managed by Mason I will have just have to add them the lspconfig section?

**Comment by folke** [comment]
What you are referncing is an example to add `tools` to LazyVim.

The example above clearly shows how to add an lsp server
https://github.com/LazyVim/starter/blob/1a2b26d37c1601b53d7ef0641fd790ffe3b1c395/lua/plugins/example.lua#L87

The LSP docs also mention this https://www.lazyvim.org/plugins/lsp#nvim-lspconfig

No more docs needed
