### ISSUE TITLE
feature: shall we add functionaliy of removing trailing spaces when to copy by default?

### ISSUE THREAD

**Issue by 4t8dd** [LazyVim/LazyVim#2525]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

I use the starter config. But whenever I copy, I got a lot of trailing spaces.

### Describe the solution you'd like

This seems configurable. Why not add it to the default config? I think it is useful for most users.

### Describe alternatives you've considered

N/A

**Comment by folke** [comment]
NEovim supports .editorconfig.
You can configure that to remove trailing whitespace
