### ISSUE TITLE
bug: how to modify terminal

### ISSUE THREAD

**Issue by Abrillant-Lee** [LazyVim/LazyVim#2545]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.5

### Operating system/version

win11 

### Describe the bug

The dafault terminal is cmd , but cmd is very inconvenient to use. How to change it to powershell so that the powerhshell terminal is opened using <leader -ft>

### Steps To Reproduce

now use <learder-ft>to open cmd

### Expected Behavior

use <learder-ft> to open powershell instead of cmd

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
@Abrillant-Lee When you create a bug issue, the template also includes the following which you agree
>  Usage questions such as "How do I...?" belong in [Discussions](https://github.com/folke/LazyVim/discussions) and will be closed.

If you would be kind to close this issue and move to the Discussions that would be greatly appreciated. You might also want to take a look at this Reddit [thread](https://www.reddit.com/r/neovim/comments/vpnhrl/how_do_i_make_neovim_use_powershell_for_external/) which seems to describe what you should do in Windows.

**Comment by Abrillant-Lee** [comment]
ok，i close this issue and move to the discussions
