### ISSUE TITLE
bug: documentHighlightProvider not working with Python files

### ISSUE THREAD

**Issue by amaanq** [LazyVim/LazyVim#255]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0-dev-941+g2b1c07a1d Build type: RelWithDebInfo LuaJIT 2.1.0-beta3

### Operating system/version

Arch Linux 6.1.6

### Describe the bug

This isn't really related to LazyVim, but I would think you (Folke) would be best at answering this and I'd get a faster response here than the core neovim repo (dunno where else this would go)

When using jedi_language_server or pyright for Python files, the textDocument/highlighting feature isn't applied and as such the LSP doesn't add highlighting to my buffer. I added 2 debug points, the first being in plugins/lsp/init.lua inside the call to (lazyvim.util).on_attach():
```lua
if client.name == "jedi_language_server" or client.name == "pyright" or client.name == "lua_ls" then
    dd("client.name: ", client.name, " client.server_capabilities: ", client.server_capabilities)
```
this shows that jedi_language_server, pyright, and lua_ls has documentHighlightProvider. 

The second debug point is a few lines after in the setup function declaration. I add 
```lua
if server == "jedi_language_server" or server == "pyright" or server == "lua_ls" then
    dd("server =", server, "server_opts = ", server_opts)
end
```

In that debug notif, none of them have documentHighlight mentioned anywhere, but lua_ls does indeed add highlights and this can be checked with your <leader>ui bind in your dotfiles under any section highlighted differently from tree-sitter (and rust, other languages work fine too)

However, it seems like python and only python files don't apply this. I'd be very appreciative if you could help figure out why that is. I hope this explained the problem clear enough!

Thanks,
Amaan

### Steps To Reproduce

1. Use pyright or jedi_language_server
2. Add debug points (optional)
3. Open python file, notice treesitter highlights work fine but LSP highlights aren't added

### Expected Behavior

LSP highlights are added if the server supports it.

### Repro

Use LazyVim with pyright/jedi_language_server and open a python file.

**Comment by folke** [comment]
This is not a NEovim support forum.

However, check `:h vim.lsp.buf.document_highlight()`

**Comment by folke** [comment]
Nevermind, we have illuminate. That lsp server probably does not support document highlights

**Comment by folke** [comment]
It works for me with pyright. Maybe the colorscheme you are using does not support the highlight group?

**Comment by amaanq** [comment]
> Nevermind, we have illuminate. That lsp server probably does not support document highlights

Yeah, but pyright and jedi_ls do. Do you get additional highlights beyond treesitter for python files? (iirc you use pyright and we both use tokyonight_moon, I can upload a screenshot shortly)

**Comment by folke** [comment]
![image](https://user-images.githubusercontent.com/292349/218329148-2a63916d-524a-4895-a4fb-0f96f028c2b8.png)

**Comment by folke** [comment]
Maybe you mis-understand what document highlights are?

It just highlights references to the variable under the cursor. See my srceenshot.

**Comment by folke** [comment]
The extra highlighting is called semantic tokens, that's a completely different capability.

It doesn't seem that pyright supports semantic tokens. At least not parameter highlighting

![image](https://user-images.githubusercontent.com/292349/218329299-16f0f66b-57ab-4a5d-ba9b-0b02615335d4.png)

**Comment by amaanq** [comment]
> The extra syntax highlighting is called semantic tokens, that's a completely different capability.
> 
> It doesn't seem that pyright supports semantic tokens. At least not parameter highlighting
> 
> ![image](https://user-images.githubusercontent.com/292349/218329299-16f0f66b-57ab-4a5d-ba9b-0b02615335d4.png)
> 

Yeah, I initially thought this might be a pyright limitation, (which it is), so I tried jedi_language_server which (I think? now I have to double check) support semantic tokens. When using that as well I didn't have the parameter and other highlights I was expecting. I then thought that the extra highlighting was textDocumentHighlight, and after conforming pyright does indeed support that I then filed the issue. Now after the clarification on your end, this could just be a limitation of python language servers after all. 

I'd appreciate if you could try jedi_language_server, but from what I can tell now behavior is normal then, sorry to trouble you and thanks for clarifying what the extra highlighting is actually called :)
