### ISSUE TITLE
bug: notifications lost border and text

### ISSUE THREAD

**Issue by rishubn** [LazyVim/LazyVim#2558]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

nvim v0.10.0-dev

### Operating system/version

Ubuntu 22.04

### Describe the bug

The notification are broken

![image](https://github.com/LazyVim/LazyVim/assets/6591138/220320ce-118d-4e0e-9f21-69a61d5c29ac)

### Steps To Reproduce

Not sure why or how to reproduce this, but it occurs on startup

### Expected Behavior

Notifications work as expected

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
@rishubn 

This is a bug with `nvim-notify` plugin and there is currently a [PR](https://github.com/rcarriga/nvim-notify/pull/253) waiting to be merged to fix this issue.

If you would be kind to close this issue, since it's not a LazyVim bug, that would be greatly appreciated.

**Comment by rishubn** [comment]
Ah, I didn't realize, thanks!
