### ISSUE TITLE
bug: Rust extra not working properly.

### ISSUE THREAD

**Issue by Redoxahmii** [LazyVim/LazyVim#2576]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

Arch Linux

### Describe the bug

I tried it even on a clean install of LazyVim.
A simple Rust .rs file after enabling it in LazyExtras gives an underline under statements like `println` 
This issue sometimes just resolves automatically but most of the time the issue presists.

![Screenshot from 2024-02-20 01-29-02](https://github.com/LazyVim/LazyVim/assets/13983258/f6726ffc-75a4-4222-ae5a-b18777d56b06)

One thing i would like to mention is that this issue does not show in the diagnostics and the code runs correctly as it is correct code.

### Steps To Reproduce

1.Clean install lazyvim.
2. Enable lang.rust from LazyExtras
3. Write a simple .rs file with statement println or the other print functions.

### Expected Behavior

Should not be marking or underlining them for no reason.

### Repro

```Lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- bootstrap lazy.nvim
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

require("lazy").setup({
  spec = {
    -- add LazyVim and import its plugins
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- import any extras modules here
    -- { import = "lazyvim.plugins.extras.lang.typescript" },
    -- { import = "lazyvim.plugins.extras.lang.json" },
    -- { import = "lazyvim.plugins.extras.ui.mini-animate" },
    -- import/override with your plugins
    { import = "plugins" },
  },
  defaults = {
    -- By default, only LazyVim plugins will be lazy-loaded. Your custom plugins will load during startup.
    -- If you know what you're doing, you can set this to `true` to have all your custom plugins lazy-loaded by default.
    lazy = false,
    -- It's recommended to leave version=false for now, since a lot the plugin that support versioning,
    -- have outdated releases, which may break your Neovim install.
    version = false, -- always use the latest git commit
    -- version = "*", -- try installing the latest stable version for plugins that support semver
  },
  install = { colorscheme = { "tokyonight", "habamax" } },
  checker = { enabled = true }, -- automatically check for plugin updates
  performance = {
    rtp = {
      -- disable some rtp plugins
      disabled_plugins = {
        "gzip",
        -- "matchit",
        -- "matchparen",
        -- "netrwPlugin",
        "tarPlugin",
        "tohtml",
        "tutor",
        "zipPlugin",
      },
    },
  },
})
if vim.g.neovide then
  vim.o.guifont = "JetBrainsMono Nerd Font"
  vim.g.neovide_scale_factor = 0.8
  vim.g.neovide_transparency = 0.8
end
```

**Comment by igorgue** [comment]
As a workaround, I'm pretty sure there's a PR that fixes this where I copied this config but I couldn't find it, here's a fix:

https://github.com/igorgue/dotnvim/blob/main/lua/plugins/extras/lang/rust.lua

This replaces rust-tools with rustecean.nvim, works on my LazyVim install.

**Comment by Redoxahmii** [comment]
> As a workaround, I'm pretty sure there's a PR that fixes this where I copied this config but I couldn't find it, here's a fix:
> 
> https://github.com/igorgue/dotnvim/blob/main/lua/plugins/extras/lang/rust.lua
> 
> This replaces rust-tools with rustecean.nvim, works on my LazyVim install.

I researched the issue a little bit more and this occurs only with a few colorschemes like  tokyonight  and solarized-osaka but works fine if i use catppuccin.
I am on Arch and the other solution that i found for this was to use rustup instead of simple rust and install the stable toolchain for working.
Still the removal of rust-tools with rustecean.nvim is still a good decision instead of using an archived plugin.
Thanks for this suggestion @igorgue  hopefully this PR gets merged soon.

**Comment by folke** [comment]
The PR with rustecean has been merged. closing for now
