### ISSUE TITLE
feature: Add --force-with-lease option on branch push.

### ISSUE THREAD

**Issue by patrick-motard** [LazyVim/LazyVim#2579]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

When pushing a branch, if the local branch history deviates from the remote, which is common after a rebase, a popup is shown asking the user if they would like to push with the --force flag. This is potentially harmful, as you may not have changes locally that others have added to the remote. By force pushing, there is a high risk of blindly overwriting others changes. 99 times out of 100, I am force pushing after a rebase. I do _not_ intend to overwrite others commits that I may not have.

### Describe the solution you'd like

In the case described above, I would like two things:

- The pop-up shows the user multiple push options. `--force-with-lease` and `--force`.
- The default action suggested to the user in the list of options is `--force-with-lease`, a flag on `git push` that fails the push if there are commits on the remote not present on local. [Reference](https://git-scm.com/docs/git-push#Documentation/git-push.txt---force-with-leaseltrefnamegtltexpectgt).

### Describe alternatives you've considered

Not sure i would suggest an alternative here, but it's a required field in this ticket form. An alternative would be that push no longer has a pop up if it fails to push to local and remote differing. Instead there would be a menu option for push, force push, and force push safe (`git push --force-with-lease`). 
I wouldn't suggest this over the other option as it puts more options in front of the user than they need most of the time, but it feels like it still aligns with the general approach of the lazygit ui.

**Comment by dpetka2001** [comment]
LazyVim doesn't do any `lazygit` configuration. Maybe you would like to redirect your feature request to the `lazygit` repo instead? It doesn't have to do anything with LazyVim this kind of request in this repo.

**Comment by patrick-motard** [comment]
Whoops! Completely created this ticket in the wrong tab. Sorry! I'll move this over to lazygit.
Thanks @dpetka2001
