### ISSUE TITLE
feature: linter-specific running rules

### ISSUE THREAD

**Issue by tomhampshire** [LazyVim/LazyVim#2589]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Using nvim-lint, some linters (e.g. mypy, pylint) are very slow, and cannot be run using the nvim-lint plugin as it has a negative impact on developer experience; however, it is useful to have linting messages from these whilst coding.

### Describe the solution you'd like

With null-ls, it was possible to specify _when_ linters were run (e.g. onsave only, on exit insert mode, etc). 
Currently, LazyVim has the option to define the event when nvim-lint is run, but this is on a global-basis.
```lua
  -- Event to trigger linters
  events = { "BufWritePost", "BufReadPost", "InsertLeave" },
```
it would be useful to have some (slower) linters run on `BufWritePost`/`BufReadPost`, and some (faster) linters run on `InsertLeave` _only_

### Describe alternatives you've considered

I've had to remove slow linters entirely.

**Comment by tomhampshire** [comment]
Cross post with: https://github.com/mfussenegger/nvim-lint/issues/540

**Comment by dpetka2001** [comment]
A solution about this was provided in the post from `nvim-lint` issue. Maybe this should be closed?
