### ISSUE TITLE
bug: opts not getting merged

### ISSUE THREAD

**Issue by cwrau** [LazyVim/LazyVim#2590]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

Arch Linux

### Describe the bug

https://www.lazyvim.org/configuration/plugins#%EF%B8%8F-customizing-plugin-specs states that providing a table to the `opts` field would merge that with the default `opts`, but the following `conform.lua` doesn't work;

```lua
---@type LazyPlugin[]
local plugins = {
  {
    "stevearc/conform.nvim",
    ---@type ConformOpts
    opts = {
      formatters = {
        sh = {
          prepend_args = function (_)
            return { "-i", "2", "-ci" }
          end
        },
        beautysh = {
          prepend_args = function (_)
            return { "-i", "2", "--force-function-style", "fnpar" }
          end
        }
      },
      formatters_by_ft = {
        helm = {},
        yaml = { "yamlfmt" },
        ["*"] = { "trim_whitespace", "trim_newlines", "codespell" }
      }
    }
  },
}

return plugins
```

While this one using a function works;

```lua
---@type LazyPlugin[]
local plugins = {
  {
    "stevearc/conform.nvim",
    ---@param opts ConformOpts
    opts = function(_, opts)
      opts.formatters.sh = {
        prepend_args = function(_)
          return { "-i", "2", "-ci" }
        end,
      }
      opts.formatters.beautysh = {
        prepend_args = function(_)
          return { "-i", "2", "--force-function-style", "fnpar" }
        end,
      }
      opts.formatters_by_ft = {
        helm = {},
        yaml = { "yamlfmt" },
        ["*"] = { "trim_whitespace", "trim_newlines", "codespell" },
      }
    end,
  },
}

return plugins
```

I can verify this, because formatting a shell file replaces all indentation-spaces with tabs although the config says it should be spaces.

### Steps To Reproduce

1. Use the above provided `conform.lua`
2. Format a shellscript indented with spaces
3. See that they are now tabs

### Expected Behavior

Either the `opts` field should be correctly merged, the docs updated that this indeed does not work or the docs should be made more precise on how to do this correctly 😅

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```
---

I guess adding the `conform.lua` into this repro should work? I can't get any key mappings working with this config 😅.

`:nmap temp :echo('your leader is "<Leader>"')<Esc>| execute 'normal temp'| nunmap temp` says my leader is `<space>`, but typing ` cf` doesn't do anything

**Comment by dpetka2001** [comment]
Shouldn't it be `opts.formatters.shfmt` instead?

**Comment by cwrau** [comment]
> Shouldn't it be `opts.formatters.shfmt` instead?

I dunno, why?

It works when using the function, so I guess it's ok?

**Comment by dpetka2001** [comment]
Because `formatters` is a table where the keys are the names of the formatters and not the filetypes. Anyways, this seems to work for me
```lua
return {
  {
    "stevearc/conform.nvim",
    opts = {
      formatters = {
        shfmt = {
          prepend_args = { "-i", "2", "-ci" },
        },
        beautysh = {
          prepend_args = { "-i", "2", "--force-function-style", "fnpar" },
        },
      },
      formatters_by_ft = {
        helm = {},
        yaml = { "yamlfmt" },
        ["*"] = { "trim_whitespace", "trim_newlines", "codespell" },
      },
    },
  },
}
```
So, I guess the `opts` are getting merged properly.

**Comment by cwrau** [comment]
> Because `formatters` is a table where the keys are the names of the formatters and not the filetypes. Anyways, this seems to work for me
> 
> ```lua
> return {
>   {
>     "stevearc/conform.nvim",
>     opts = {
>       formatters = {
>         shfmt = {
>           prepend_args = { "-i", "2", "-ci" },
>         },
>         beautysh = {
>           prepend_args = { "-i", "2", "--force-function-style", "fnpar" },
>         },
>       },
>       formatters_by_ft = {
>         helm = {},
>         yaml = { "yamlfmt" },
>         ["*"] = { "trim_whitespace", "trim_newlines", "codespell" },
>       },
>     },
>   },
> }
> ```
> 
> So, I guess the `opts` are getting merged properly.

Ok..., then why does it work when I use the function variant? 😅

But you are right, using the `shfmt` entry does merge it correctly

**Comment by dpetka2001** [comment]
Could you kindly close this issue if your problem is resolved? Thanks in advance.

**Comment by cwrau** [comment]
> Could you kindly close this issue if your problem is resolved? Thanks in advance.

Sooo, should I open another bug-issue? With the title `Using the function for "opts" weirdly sets different things that don't work when using a table for "opts"`? 😅

**Comment by dpetka2001** [comment]
What do you mean? I don't understand. You yourself said that using `shfmt` instead of `sh` correctly merges the `opts`.

**Comment by cwrau** [comment]
> What do you mean? I don't understand. You yourself said that using `shfmt` instead of `sh` correctly merges the `opts`. And we already established that `formatters` table takes formatters as the keys and not filetypes.

Yesss, I understand, but why does it work when I use a function instead of a table for `opts`? Either something is going wrong when doing that or something is not working when using a table.

I mean, if `sh` isn't supposed to work but it does work when using a function something weird is going on there.
And if `sh` is supposed to, or at least _could_, work but doesn't work when using a table something else weird is going on there. 😅

If you want I can close this one and open a new one, I just wanted to reduce noise 😅

**Comment by dpetka2001** [comment]
But it does work with a table. Have you tried my example? I tried my example and the shell file is formatted with spaces instead of tabs. My example is with `opts` as a table.

**Comment by cwrau** [comment]
> But it does work with a table. Have you tried my example? I tried my example and the shell file is formatted with spaces instead of tabs. My example is with `opts` as a table.

Yesss, I tried it, it worked, but that's not what I'm talking about!

I'm talking about, and questioning, why it works when using a function?!

> I mean, if `sh` isn't supposed to work [in a table] but it does work when using a function something weird is going on there.
> And if `sh` is supposed to, or at least could, work [in a function] but doesn't work when using a table something else weird is going on there. 😅

And if the current behaviour, different things working when using either table or function, then this should be documented.

Because if I try something in a function and it works and I convert it to a table and it doesn't, it just confuses people, or at least me

**Comment by dpetka2001** [comment]
Formatting in LazyVim will first try to use `conform.nvim` and if that's not available then fall back to LSP formatting. Maybe that's what you observed? Because I tried your exact example and it doesn't format the file even though `opts` is a function (in my case I don't have any LSP server installed for sh files, thus nothing is attached). What does `:LspInfo` show?

**Comment by cwrau** [comment]
> Formatting in LazyVim will first try to use `conform.nvim` and if that's not available then fall back to LSP formatting. Maybe that's what you observed? Because I tried your exact example and it doesn't format the file even though `opts` is a function (in my case I don't have any LSP server installed for sh files, thus nothing is attached). What does `:LspInfo` show?

Mh, interesting, but my `:LspInfo` is empty;

```
Detected filetype:   sh             
                                    
0 client(s) attached to this buffer:
```

> Also, :ConformInfo only shows the global formatters with your example.

Aha, didn't know about that, I guess using a function doesn't merge then? 🤔

**Comment by dpetka2001** [comment]
You can't do that with `opts` as a function, because the entry `shfmt` doesn't exist in the table `formatters` and cannot be created when `opts` is a function. You can only access existing entries when using `opts` as a function or you could use `opts` as a function that returns a new table that will override the defaults. That's how Lua works.
