### ISSUE TITLE
bug: Command Autocomplete Is Not Working

### ISSUE THREAD

**Issue by josephcrawfordSRH** [LazyVim/LazyVim#2591]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

MacOS 14.2.1

### Describe the bug

I am not seeing any auto completions in the command input.

### Steps To Reproduce

1. Installed LazyVim
2. Executed Command
3. Never saw auto complete

### Expected Behavior

I would expect that there would be some command auto completion so that I could see what commands were available.
![Screenshot 2024-02-22 at 11 22 17 AM](https://github.com/LazyVim/LazyVim/assets/100154037/95bb9ddc-cde1-48b7-af0b-e467528b7a01)
![Screenshot 2024-02-22 at 11 22 06 AM](https://github.com/LazyVim/LazyVim/assets/100154037/159dc51d-5481-4d05-9213-4df156d8f072)

When I use the repro.lua below and launch nvim into the base setup I also get no auto complete as seen below.

![Screenshot 2024-02-22 at 11 25 19 AM](https://github.com/LazyVim/LazyVim/assets/100154037/c1712e67-c2d1-4e3d-80c7-323174d4ebc8)
![Screenshot 2024-02-22 at 11 25 35 AM](https://github.com/LazyVim/LazyVim/assets/100154037/6d2db38a-55b9-41ba-a812-405f27dd32db)

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
You have to press `<Tab>` to see the available options for completion in the command line.

**Comment by josephcrawfordSRH** [comment]
oh well jeez, apologies I didn't see that in the docs anywhere, assumed it would be automatic.  Thank you!
