### ISSUE TITLE
feature: hot reload config

### ISSUE THREAD

**Issue by Delice0** [LazyVim/LazyVim#2612]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

When applying new changes, I always have to restart the neovim instance in order to see the actual changes. This can be annoying and time consuming when you often make changes.

### Describe the solution you'd like

I want some kind of functionality that hot reloads all neovim instance whenever I make a new change to my configs.

### Describe alternatives you've considered

n/a

**Comment by folke** [comment]
I'm not planning to support this in LazyVim.

However, there is some preliminary support for this part of lazy.nvim. Check the repo's issues to learn more

**Comment by Delice0** [comment]
> I'm not planning to support this in LazyVim.
> 
> 
> 
> However, there is some preliminary support for this part of lazy.nvim. Check the repo's issues to learn more

Why not?
