### ISSUE TITLE
feature: 

### ISSUE THREAD

**Issue by Emojiproblem** [LazyVim/LazyVim#2625]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

I am disgusted with the terrorist emoji. Why would you include this??? 🥷🏻

### Describe the solution you'd like

Remove this emoji

### Describe alternatives you've considered

I don’t know how to get rid of it, but it’s incredibly offensive

**Comment by dpetka2001** [comment]
@mkubasz You don't know that ninjas are terrorists? Even a fresh new Github account created today to just make this post knows this. Omg...

**Comment by mkubasz** [comment]
@dpetka2001 Everyday I learn something new :)

**Comment by folke** [comment]
It's a ninja indeed and as fas as I know, this emoj is NOT being used at all in LazyVim
