### ISSUE TITLE
bug: Lua LSP taking 50x more RAM than in Vscode right from boot

### ISSUE THREAD

**Issue by StitiFatah** [LazyVim/LazyVim#2627]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Archlinux

### Describe the bug

The lua language server takes 800+ MiB of RAM at boot and quickly build up to 1+ GiB, while in Vscode it's only taking 15MiB when opening the same file. 

Here are the screenshots from btop, you can see that the processes have been started recently : 

![2024-02-28-194933_sway-screenshot](https://github.com/LazyVim/LazyVim/assets/68331131/6529bdf3-0bee-41e6-ae4f-47ea399429d6)
![2024-02-28-193206_sway-screenshot](https://github.com/LazyVim/LazyVim/assets/68331131/1984642d-9703-4eda-bd84-179d8201cfae)

On a side note I noticed the same with tailwind's lsp. 

### Steps To Reproduce

1. Fresh Lazyvim install 
2. open `~/.config/nvim/lua/plugins/example.lua` 
3. Observe RAM consumption of `~/.local/share/nvim/mason/packages/lua-language-server/libexec/bin/lua-language-server` quickly build up to 1GB

### Expected Behavior

Closer RAM consumption than in Vscode or at least reasonable numbers

### Repro

default

**Comment by sdondley** [comment]
The paths to the l-l-s binaries are different. To get a more accurate picture of what's going on, seems like it would be better to symlink mason's binary to vscode or vice versa so they are using the same binary.

**Comment by StitiFatah** [comment]
> The paths to the l-l-s binaries are different. To get a more accurate picture of what's going on, seems like it would be better to symlink mason's binary to vscode or vice versa so they are using the same binary.

Thanks for the reply, the binaries seem to be same according to `diff`, I've created a symlink to vscode's `lua-language-server` located in `~/.vscode-oss/extensions/sumneko.lua-3.7.4-linux-x64/server/bin` and the behavior is the same as expected

**Comment by dpetka2001** [comment]
In your `~/.config/nvim/.neoconf.json` file change under `neodev.library.plugins` from `true` to `false`. The default behavior is to scan through all the plugins you have installed, so that `lua_ls` provides you with auto-completion, types etc from all the plugins. That only happens in your `~/.config/nvim/` folder. If you don't want the aforementioned behavior, just disable it. The rest depends on how `lua_ls` LSP is configured on Vscode vs Neovim.

**Comment by StitiFatah** [comment]
> In your `~/.config/nvim/.neoconf.json` file change under `neodev.library.plugins` from `true` to `false`. The default behavior is to scan through all the plugins you have installed, so that `lua_ls` provides you with auto-completion, types etc from all the plugins. That only happens in your `~/.config/nvim/` folder. If you don't want the aforementioned behavior, just disable it. The rest depends on how `lua_ls` LSP is configured on Vscode vs Neovim.

You're right, it doesn't happen outside the nvim folder. Thanks, I'm closing the issue.
