### ISSUE TITLE
bug: debug icons not operative

### ISSUE THREAD

**Issue by rdataforge** [LazyVim/LazyVim#2634]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.95

### Operating system/version

ubuntu WSL

### Describe the bug

fresh clean installation from starter template, activated DAP core extras for python, debugging works ok but icons are not operative. Clicking on them does nothing.
Tested on Windows Terminal and WezTerm

### Steps To Reproduce

1. install neovim
2. install lazyvim starter template
3. activate DAP extras and mason for Python
4. open a python file for debug and DAP-UI
5. press on icons
6. nothing happened
7. initiate debugging with keypress (leader d c)
8. press on icons
9. nothing happened

### Expected Behavior

expected is the dap-ui icons to work. 

### Repro

```Lua
no changes to starter template
```

**Comment by folke** [comment]
I dont think the icons are supposed to be clickable. I never use the mouse though.
