### ISSUE TITLE
feature:  Create New File with a name to get LSP working 

### ISSUE THREAD

**Issue by TyronSamaroo** [LazyVim/LazyVim#2636]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

`<leader> fn` Makes a new file but this feels lacking since I will not have any autocomplete feature if I want to create a new python file.  I know I can do `:w filename` but why have `<leader> fn`to quickly create a new file and not name it to get LSP working?

### Describe the solution you'd like

Have `<leader> fn `ask for file name

### Describe alternatives you've considered

N/A

**Comment by folke** [comment]
Just do `:e foo.py` instead?

**Comment by TyronSamaroo** [comment]
But why have the option in lazyvim to just create a new file with leader fn?

**Comment by folke** [comment]
I use that for example to quickly edit something I copy pasted from a web form.

* leader fn
* :setf yaml
* do my thing
* copy and paste it in the webform
