### ISSUE TITLE
bug:  Error laoding sessions because win width cannot be smaller than winminwidth

### ISSUE THREAD

**Issue by Martin1887** [LazyVim/LazyVim#2648]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Linux

### Describe the bug

Loading sessions often fail with a message specifying that win width cannot be smaller than `winminwidth` (at least with persisted.nvim and focus.nvim).

See https://github.com/nvim-focus/focus.nvim/issues/138.

It is fixed setting `vim.go.winminwidth = 0` in `options.lua`. Why `winminwidth` is set to 5 in LazyVim?

Thanks!

### Steps To Reproduce

1. Open editor with some buffers.
2. Save session.
3. Quit Neovim.
4. Open Neovim.
5. Load session.

### Expected Behavior

Session is correctly loaded, but it is not, with a error message 592: 'winwidth' cannot be smaller than 'winminwidth'.

See https://github.com/nvim-focus/focus.nvim/issues/138.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  "nvim-focus/focus.nvim",
  "olimorris/persisted.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
Can you try with the following configuration
```lua
  {
    "nvim-focus/focus.nvim",
    event = "BufReadPre",
    opts = {},
  },
  {
    "olimorris/persisted.nvim",
    opts = {},
  },
```
and test the behavior? Make sure to delete your session files beforehand.

**Comment by Martin1887** [comment]
The problem persists doing that. Setting `vim.go.winminwidth=0` in `options.lua` works like a charm however.

Thanks.

**Comment by Martin1887** [comment]
I deleted the session file corresponding to that project in my full LazyVim configuration, but I think the result should be the same. I could try in the isolated configuration in a new clean environment in some days.

**Comment by folke** [comment]
winminwidth is set to 5 since smaller makes no sense.
focus.nvim requires 0, so you should set it in your config.
This is not a LazyVim issue.
