### ISSUE TITLE
feature: add a default binding for codelens

### ISSUE THREAD

**Issue by OneOfOne** [LazyVim/LazyVim#2656]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

No default bindings for codelens.

### Describe the solution you'd like

`nmap('<leader>cc', vim.lsp.codelens.run, 'run codelens')`

### Describe alternatives you've considered

running it by hand.

**Comment by dpetka2001** [comment]
Why running it by hand and not make a custom keymap in your `/lua/config/keymaps.lua`?

**Comment by dpetka2001** [comment]
I didn't question your suggestion for the keymap to be incorporated into LazyVim. It's just that in the `Alternatives you've considered` you put `running it by hand`, so I was under the assumption that you just run the command manually. That's all.

**Comment by OneOfOne** [comment]
@folke for me, at least in rust, codelens don't show at all anymore until I hit `<leader>cC` (I set codelens = true in my config), where before the change, they always showed up.

**Comment by dpetka2001** [comment]
Did you enable the option in `nvim-lspconfig`? By default it's set to `false`.

**Comment by dpetka2001** [comment]
I set this 
```lua
  {
    "neovim/nvim-lspconfig",
    opts = {
      codelens = {
        enabled = true,
      },
    },
  },
```
and this is how it looks in a testing Rust project

![2024-03-08_20-01](https://github.com/LazyVim/LazyVim/assets/12776461/b81d87e1-fe9a-490b-9597-eda17d350aa9)

**Comment by OneOfOne** [comment]
there was a typo and it didn't error, thanks.
