### ISSUE TITLE
bug: Weird question mark icon in markdown files

### ISSUE THREAD

**Issue by apicgg** [LazyVim/LazyVim#2658]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

MacOS 14.3.1

### Describe the bug

After following the installation guide as per the [https://www.lazyvim.org/installation](https://www.lazyvim.org/installation), every existing markdown (`.md`) files in any projects are having question marks. See the second line in the below screen shot. Nerd Font is also being used.

![image](https://github.com/LazyVim/LazyVim/assets/78271602/af7a8c60-81d2-4f8c-9b79-26e2065df7ff)

### Steps To Reproduce

1. Install `neovim` and it's dependencies as per the documentation. e.g. `brew install neovim ripgrep fd`.
2. Open `neovim` with `nvim`.
3. Open `lazy.lua` and add `markdown` language support. 

![image](https://github.com/LazyVim/LazyVim/assets/78271602/9a6c4fbc-7049-40ea-9739-6d6133a03363)

4. Open any markdown file and see the issue. e.g. Open `README.md` from the `~/.config/nvim`.

### Expected Behavior

The question mark icon should not get displayed.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
It's a problem with your font. See this [comment](https://github.com/lukas-reineke/headlines.nvim/issues/41#issuecomment-1556334775) in a similar post in the `headlines.nvim` repo.

**Comment by apicgg** [comment]
> It's a problem with your font. See this [comment](https://github.com/lukas-reineke/headlines.nvim/issues/41#issuecomment-1556334775) in a similar post in the `headlines.nvim` repo.

Tried with FiraCodeNF. Same issue. Let me know if you have any other suggestions. Thanks.

![image](https://github.com/LazyVim/LazyVim/assets/78271602/2b7f399d-4f05-401d-94e6-445978bc6bbc)

**Comment by dpetka2001** [comment]
Try another font and make sure your terminal uses it or use the workaround mentioned in the comment that I linked in my previous post. It has nothing to do with LazyVim. Those icons you're seeing come from the plugin `headlines.nvim`, because your fonts don't support the default character that the plugin uses.
