### ISSUE TITLE
No specs found for module lazyvim.plugins.extras.editor.symbols-outline

### ISSUE THREAD

**Issue by xchray** [LazyVim/LazyVim#2663]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

WIN11

### Describe the bug

after 2024-03-07 update 10.11.0. I got this error:
No specs found for module lazyvim.plugins.extras.editor.symbols-outline.  

### Steps To Reproduce

update to 10.11. 

### Expected Behavior

no error message

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by Ian2020** [comment]
For anyone else finding this symbols-outline has been removed from extras recently so you may need to update your config: https://github.com/LazyVim/LazyVim/pull/2535
