### ISSUE TITLE
Missing ruatacean feature in changelog?

### ISSUE THREAD

**Issue by 1313** [LazyVim/LazyVim#2665]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

10.11.0

### Operating system/version

All

### Describe the bug

No mentioning of switching from rust-tools to rustacean

### Steps To Reproduce

Read changelog

### Expected Behavior

Could not find anything about rustacean va rust-tools in changelog 

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
You're right. The commit message was not valid (missing `:`), so the changelog generator did not pick it up.

https://github.com/LazyVim/LazyVim/pull/2198

Just made a dummy commit to have it in the changelog.
