### ISSUE TITLE
bug: The `edgy.nvim` extra must be **imported** before the `outline.nvim` extra to work properly.

### ISSUE THREAD

**Issue by davepgreene** [LazyVim/LazyVim#2666]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev-2488+g5d4e1693c

### Operating system/version

Windows 11

### Describe the bug

Currently extras are ordered in the `lazyvim.json` file such that the `ui.edgy` extra can never be ordered before the `editor.outline` extra. My guess is that `lazyvim.plugins.extras.ui.edgy` needs to be added to the [prios table](https://github.com/LazyVim/LazyVim/blob/5cabc2ff5b52405c0d41f1a06329567e84d15d3b/lua/lazyvim/plugins/xtras.lua#L4-L9) with a sufficient priority to order it above `editor.outline`.

### Steps To Reproduce

1. Add `ui.edgy` and `editor.outline` in Edgy Extras.
2. See the following warning: `LazyVim The `edgy.nvim` extra must be **imported** before the `outline.nvim` extra to work properly.`

### Expected Behavior

If `ui.edgy` is imported via lazyvim extras it should always be ordered before `editor.outline` if that ordering is required.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup({
  spec = {
    -- add LazyVim and import its plugins
    { "LazyVim/LazyVim", import = "lazyvim.plugins", version = "*" },
  }
}, plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```
Now open neovim, wait for lazy.nvim to bootstrap and install plugins, go to Extras, enable `ui.edgy` and `editor.outline`, then restart neovim.

This is the resulting `lazyvim.json` file.
```
{
  "extras": [
    "lazyvim.plugins.extras.editor.outline",
    "lazyvim.plugins.extras.ui.edgy"
  ],
  "news": {
    "NEWS.md": "2123"
  },
  "version": 2
}
```
```

**Comment by davepgreene** [comment]
Wow you're fast! Thanks @folke 😄

**Comment by xchray** [comment]
Sorry I don't understand how to correct this issue. I unloaded UI.EDGE, and reloaded and no matter what to do, I still have this one. It is now warning not error. Below is warning msg and all my extras

![image](https://github.com/LazyVim/LazyVim/assets/81406963/1cf414f1-e321-4abb-9dd9-d0be9b701a80)

![image](https://github.com/LazyVim/LazyVim/assets/81406963/c4deef6f-0b4e-4f45-97a0-557561e2b7fc)

**Comment by thingsiplay** [comment]
> Sorry I don't understand how to correct this issue.

I had this issue today too too. With a recent update there was an autofix included and it fixed this issue without me doing anything. So this should be fixed I think.
