### ISSUE TITLE
bug: Impossible to set maplocalleader without warning

### ISSUE THREAD

**Issue by aarondill** [LazyVim/LazyVim#2668]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev-2281+g0e9a33572

### Operating system/version

Arch Linux

### Describe the bug

After the [commit adding a warning when maplocalleader changes](https://github.com/folke/lazy.nvim/commit/0694651fd37c3645e1683b4f392d4e38e7d2991b) it's now impossible to set maplocalleader to a value other than "\\" without a warning.

`lua/lazyvim/config/options.lua` sets maplocalleader, before it gets loaded by lazy. This means that even the following code gets a warning:
```lua
vim.g.maplocalleader=" " -- this is overridden
require("config.lazy") -- maplocalleader gets reset *and* stored here
vim.g.maplocalleader=" " -- this is warned about
```

### Steps To Reproduce

1. Set maplocalleader before calling lazy, this will be lost, even though it's suggested
2. call `require "config.lazy"`
3. Set maplocalleader to create new mappings (this is warned about!)

### Expected Behavior

No warning if mapleader or maplocalleader are set before calling lazy.

Since these values start as `nil`, `lazyvim/config/options.lua` could be replaced with
```lua
vim.g.mapleader = vim.g.mapleader or " "
vim.g.maplocalleader = vim.g.maplocalleader or "\\"
```
therefore setting them only if the user hasn't already set them.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}

vim.g.maplocalleader=" " -- this gets overwritten

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.g.maplocalleader=" " -- warning here (I just want to use space!)

vim.cmd.colorscheme("tokyonight")
```

**Comment by folke** [comment]
That suggestion is for using lazy.nvim

LAzyVim loads lazy.nvim internally.

The correct way to set your leader and localleader is in your local options.lua

**Comment by aarondill** [comment]
I first found this by having the setting in my local options.lua.

I had 
```lua
vim.g.mapleader = “ “
vim.g.maplocalleader = “”
```
as the first lines of options.lua and get the warning message popup

**Comment by aarondill** [comment]
actually, it was the header of `keymaps.lua`. is options loaded separately from the other config files?

**Comment by folke** [comment]
yes, you are supposed to set this in your options.lua

See the docs https://www.lazyvim.org/configuration/general#options

Click on default options

**Comment by folke** [comment]
keymaps are lazy loaded (most of the time)
