### ISSUE TITLE
Keep popping up notification to remove symbols-outline

### ISSUE THREAD

**Issue by ivanlee1999** [LazyVim/LazyVim#2675]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

10.12.0

### Operating system/version

Macos

### Describe the bug

After updating lazyvim, it will keep poping this notifcation after each time lazyvim launches. Even though I checked the lazy plugin and symbols-outline is already gone.

<img width="599" alt="image" src="https://github.com/LazyVim/LazyVim/assets/73640368/ea4b8066-ea2f-4862-bce8-6e9f4a8154e2">

<img width="1984" alt="image" src="https://github.com/LazyVim/LazyVim/assets/73640368/5e69223d-cb32-46c1-b12b-16a287ac15ff">

### Steps To Reproduce

update lazyvim. then launch it

### Expected Behavior

no such notification

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by thingsiplay** [comment]
Same here, I am unable to understand what to do. I get following warning:

> ```
>  The `symbols-outline` has been replaced by `outline`.
>  Please remove the extra to hide this warning.
>  
>  # stacktrace:
>    - .config/nvim/lua/config/lazy.lua:9
>    - .config/nvim/init.lua:2
> ```

I can't find any extra to remove. The only related one is `outline` itself and removing it would not change the warning too.
