### ISSUE TITLE
bug: packloadall doesn't run on startup

### ISSUE THREAD

**Issue by bitmage** [LazyVim/LazyVim#2689]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

Manjaro 23.1

### Summary

I am wondering if something that LazyVim is doing is causing `packloadall` not to run on startup, and therefore short circuiting a direct install of packages in the `$packpath/pack/*/start/*` directories.

### Background

I wanted to install the `tpope/vim-surround` package outside of LazyVim using neovim's default package manager because I was having trouble getting it to run via Lazy.

For unknown reasons, I found that on my computer `packpath/runtimepath` is set to `/usr/share/nvim/runtime/` and not `~/.local/share/nvim` as is documented in the neovim docs and many other place.  I found the location by typing `:set packpath?`.

When I cloned the `vim-surround` repo into `/usr/share/nvim/runtime/pack/plugins/start` it still wasn't loading automatically on startup.  Running `:packloadall` manually did the trick.  Setting `:packloadall` within my `init.vim` created the load on startup behavior that I was desiring.

However, in the NeoVim documentation for `packloadall` it says:

```
This is normally done automatically during startup,
after loading your |vimrc| file.  With this command it
can be done earlier.
```

So I am wondering why it doesn't appear to be happening during startup.  Is LazyVim changing this behavior?  Are there any other reasons why it might be getting disabled?

### Steps To Reproduce

1. Install neovim.
2. Install the [LazyVim starter](https://www.lazyvim.org/installation) template.
3. Clone the tpope/vim-surround plugin into the appropriate directory.
```bash
$ cd /usr/share/nvim/runtime/pack
$ mkdir -p plugins/start
$ cd plugins/start
$ git clone https://github.com/tpope/vim-surround
```
4. Start vim.  Select some text in visual mode and type `s"`.  Observe no response.
5. Run ":packloadall".
6. Select some text in visual mode and type `s"`.  Observe that the text is surrounded in quotes.

### Expected Behavior

Expect `:packloadall` to occur on startup of NeoVim.

Expect default vim packages to work side by side with LazyVim, for any scenarios where I want to eliminate a layer of complexity.

### Repro

```Lua
I deleted my `.config/nvim` and installed the base starter.
```

**Comment by folke** [comment]
lazy.nvim does not support packloadall since lazy takes over the whole startup process of NEovim.

If you still want to use it, you can, but any issues because of this are not supported

**Comment by bitmage** [comment]
So am I correct in understanding that LazyVim disables packloadall?

I wouldn't expect LazyVim to provide "support" for a NeoVim feature, but if you're disabling it...

1. Documenting that more prominently would be helpful.
2. Are there any negative consequences of combining the two methods that you're aware of?

**Comment by bitmage** [comment]
Hello?

**Comment by dpetka2001** [comment]
It is documented in the `lazy.nvim` [README](https://github.com/folke/lazy.nvim#%EF%B8%8F-startup-sequence). 
> lazy.nvim does NOT use Neovim packages and even disables plugin loading completely (vim.go.loadplugins = false)

This happens for every distro that uses `lazy.nvim` as its package manager (NvChad, AstroNvim, LunarVim, kickstart etc). It's not specific to LazyVim. It's `lazy.nvim` the package manager that doesn't support it, nothing to do with the distro.

I can't answer as to if there are any negative sequences, as I don't understand that deeply myself as a simple user.

**Comment by bitmage** [comment]
Oh great!  I missed that section of the readme.  That answers my question perfectly, thank you.
