### ISSUE TITLE
feature: mini.files extra keymaps

### ISSUE THREAD

**Issue by dusty-phillips** [LazyVim/LazyVim#2692]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

I prefer mini.files to neotree and have disabled neotree. Two actions I would like to invoke on my filesystem are not possible in the default mini.files extra: splitting windows and changing CWD.

### Describe the solution you'd like

Mini.files provides documentation for mapping splits and setting cwd here:

https://github.com/echasnovski/mini.nvim/blob/e578f353d0b1d9f21a9640458d8e506c0c9acf5e/doc/mini-files.txt#L429

I would like LazyVim-sensible keybindings for these actions. Ideally, it would be possible to configure the keybindings without overriding `config()`.

### Describe alternatives you've considered

I can, of course, extend the existing LazyVim config to include these mini.files keymaps, but I felt they would be useful for other users as well.

**Comment by dusty-phillips** [comment]
For reference, here is the config that I used to override the default one provided by lazvim (as far as I can tell, there's no way to say "call the default config" from inside the config call so I have to completely overwrite it?:

```
  config = function(_, opts)
    require("mini.files").setup(opts)

    local show_dotfiles = true
    local filter_show = function(fs_entry)
      return true
    end
    local filter_hide = function(fs_entry)
      return not vim.startswith(fs_entry.name, ".")
    end

    local toggle_dotfiles = function()
      show_dotfiles = not show_dotfiles
      local new_filter = show_dotfiles and filter_show or filter_hide
      require("mini.files").refresh({ content = { filter = new_filter } })
    end

    local map_split = function(buf_id, lhs, direction)
      local rhs = function()
        -- Make new window and set it as target
        local new_target_window
        local cur_target_window = require("mini.files").get_target_window()
        if cur_target_window ~= nil then
          vim.api.nvim_win_call(cur_target_window, function()
            vim.cmd(direction .. " split")
            new_target_window = vim.api.nvim_get_current_win()
          end)

          require("mini.files").set_target_window(new_target_window)
          require("mini.files").go_in({ close_on_file = true })
        end
      end

      local desc = "Split " .. direction
      vim.keymap.set("n", lhs, rhs, { buffer = buf_id, desc = desc })
    end

    local files_set_cwd = function()
      local cur_entry_path = MiniFiles.get_fs_entry().path
      local cur_directory = vim.fs.dirname(cur_entry_path)
      if cur_directory ~= nil then
        vim.fn.chdir(cur_directory)
      end
    end

    vim.api.nvim_create_autocmd("User", {
      pattern = "MiniFilesBufferCreate",
      callback = function(args)
        local buf_id = args.data.buf_id
        vim.keymap.set("n", "g.", toggle_dotfiles, { buffer = buf_id, desc = "Toggle dotfiles" })
      end,
    })

    vim.api.nvim_create_autocmd("User", {
      pattern = "MiniFilesBufferCreate",
      callback = function(args)
        local buf_id = args.data.buf_id
        -- Tweak keys to your liking
        map_split(buf_id, "gs", "belowright horizontal")
        map_split(buf_id, "gv", "belowright vertical")
      end,
    })

    vim.api.nvim_create_autocmd("User", {
      pattern = "MiniFilesBufferCreate",
      callback = function(args)
        vim.keymap.set("n", "gc", files_set_cwd, { buffer = args.data.buf_id, desc = "Set cwd" })
      end,
    })

    vim.api.nvim_create_autocmd("User", {
      pattern = "MiniFilesActionRename",
      callback = function(event)
        require("lazyvim.util").lsp.on_rename(event.data.from, event.data.to)
      end,
    })
  end,
```

Some notes:
* I added a desc to the existing `g.` keybinding so it has a description in the menu. This is a no-brainer so I'll put up a PR for it.
* I modified the mini.files-provided examples a bit because it was giving me some lua warnings. Mostly added some `if` clauses to ensure that something is actually there.
* The `gv` keybinding collides with LazyVim. It seem to work in the mini.files buffer, but if you use `g` and look a the menu it has the "wrong" description.
* The `gc` keybinding also collides with LazyVim, but seems to work in the mini.files buffer. It has the right description, but if you press `g`, wait for the menu, then press `c`, it will *both* change the cwd *and* show up a`c` menu that you have to escape.
* There's no way to customize the keybindings without overriding the config. Maybe it could have some extra mappings in opts?

**Comment by dusty-phillips** [comment]
Created the linked PR to implement all of the above, though I'm cautious about the keybindings.

**Comment by imroc** [comment]
FYI, I have a tricky way to add extra keybindings without overwriting the lazy's config function.

Here is my config example:

```lua
return {
  "echasnovski/mini.files",
  keys = {
    { "<leader>a", "<leader>fm", desc = "[P]Open mini.files (Directory of Current File)", remap = true },
    { "<leader>A", "<leader>fM", desc = "[P]Open mini.files (cwd)", remap = true },
  },
  init = function()
    vim.api.nvim_create_autocmd("User", {
      pattern = "MiniFilesBufferCreate",
      callback = function(args)
        local buf_id = args.data.buf_id
        vim.keymap.set("n", "<leader>a", function()
          require("mini.files").close()
        end, { buffer = buf_id, desc = "[P]Toggle mini.files" })
      end,
    })
  end,
  opts = {
    windows = {
      preview = false,
    },
    mappings = {
      go_in_plus = "<CR>",
      go_in_horizontal_plus = "-",
      go_in_vertical_plus = "\\",
    },
  },
}
```
The main idea is to use lazy's `init` function to create autocmd to add extra keybindings, in above example, I can use `<leader>a` to toggle `mini.files`, just like `<leader>e` to toggle neotree.

And of course you can add autocmd in `autocmds.lua`, but I don't think it's elegant, cuz in this way, the configuration related to mini.files is not centralized, which is not conducive to configuration maintenance.
