### ISSUE TITLE
bug: Lazy's formatexpr does not allow for textwidth to take effect

### ISSUE THREAD

**Issue by LonelyMusicDisc** [LazyVim/LazyVim#2694]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Fedora 39

### Describe the bug

When trying to hard wrap—for example the whole file with `ggqG`—with a textwidth higher than 0, nothing happens. This is due to `'lazyvim.util'.format.formatexpr()` and I know this because `set formatoptions+=t` makes it work again.

### Steps To Reproduce

1. `$ vi test.md`
2. insert mode `all work and no play makes jack a dull boy all work and no play makes jack a dull boy all work and no play makes jack a dull boy`
3. cmd `set formatexpr=v:lua.require'lazyvim.util'.format.formatexpr()`
4. cmd `set tw=40`
4. normal `Vgq`

### Expected Behavior

This text:
```
all work and no play makes jack a dull boy all work and no play makes jack a dull boy all work and no play makes jack a dull boy
```

Would turn into:
```
all work and no play makes jack a dull
boy all work and no play makes jack a
dull boy all work and no play makes jack
a dull boy 
```

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
You can use `gw` instead of `gq`, which doesn't take into consideration the `formatexpr`. Lazyvim's `formatexpr` is set to `conform`'s `formatexpr` when `conform` is available, so it may have to do with how `conform` evaluates its `formatexpr`. No idea about conform's internals from my part though.

**Comment by LonelyMusicDisc** [comment]
https://github.com/stevearc/conform.nvim/issues/55#issuecomment-1837153257 this issue is closed so it seems nothing can be done on LazyVim's side, and the mentioned issue is closed which I'm guessing means using `gw` is the best option. Thank you!
