### ISSUE TITLE
docs: mini.surround's keymap does not match with the document

### ISSUE THREAD

**Issue by abiriadev** [LazyVim/LazyVim#2698]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Linux 6.7.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 03 Mar 2024 00:30:36 +0000 x86_64 GNU/Linux

### Describe the bug

First of all, I love Lazyvim! Thanks for maintaining this great project! I started using it yesterday, I found the weird issue on the document while configuring `mini.surround`.

[The document page](https://www.lazyvim.org/keymaps#minisurround) shows every keymap starting with `gs-`, which are different from the actual keymaps.

![image](https://github.com/NilsIrl/dockerc/assets/72962900/3cf53895-50af-4e19-85fe-f13e616b4c6d)

Below is the source of the document.

https://github.com/LazyVim/lazyvim.github.io/blob/b458d2220d9a2f337db5efb89d2ea1cd9f8c9fe1/docs/keymaps.md?plain=1#L161-L171

### Steps To Reproduce

1. Go to the current [document page](https://www.lazyvim.org/keymaps#minisurround).

### Expected Behavior

The default keymaps for `mini.surround` should start with `gz-`. You can see the result from the telescope.

![image](https://github.com/NilsIrl/dockerc/assets/72962900/48657bc6-7f6e-4983-b47e-5a0745bbbfb6)

Is this just a typo, or am I missing something? I want to make sure that before sending a PR for this.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
That's because you enabled leap. Leap's keybindings clash with mini.surround, so when using leap, we use gz instead.

https://www.lazyvim.org/extras/editor/leap#minisurround

**Comment by genmzy** [comment]
Plugin mini.surround `gs` also conflicts with extras.lang.java "Go Super". Should add to docs.
