### ISSUE TITLE
bug: Cannot map <Tab> behavior in nvim_cmp settings

### ISSUE THREAD

**Issue by dupeiran001** [LazyVim/LazyVim#2701]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2551+g8797429a7 Build type: RelWithDebInfo LuaJIT 2.1.1707061634 Run "nvim -V1 -v" for more info

### Operating system/version

MacOS 14.3

### Describe the bug

setting `<Tab>` mappings in nvim_cmp make no sense, like this:
```lua
return {
  "hrsh7th/nvim-cmp",
  version = false, -- last release is way too old
  opts = function(_, opts)
    local cmp = require("cmp")
    opts.mapping = vim.tbl_extend("force", opts.mapping, {
      ["<Tab>"] = cmp.mapping.select_next_item({ behavior = cmp.SelectBehavior.Select }),
    })
  end,
}
```

using `imap`, the `<tab>` is taken over by the keys setting in the lazy config:
```
i  <Tab>       * <Lua 133: ~/.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/keys.lua:112>
```

and trying to unset keys in the config like this:
```lua
keys = {
{"<Tab>", false}
}
```

I found lazy vim has its default binding: 
```
i  <Tab>       * <Lua 91: ~/.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/keys.lua:112>
```
and I don't know how to override it in only nvim_cmp drop down menu.

### Steps To Reproduce

1. override the default nvim_cmp config with this: 
```{
  "hrsh7th/nvim-cmp",
  opts = function(_, opts)
    local cmp = require("cmp")
    opts.mapping = vim.tbl_extend("force", opts.mapping, {
      ["<Tab>"] = cmp.mapping.select_next_item({ behavior = cmp.SelectBehavior.Select }),
    })
  end,
}
```
3. in the nvim_cmp drop down menu, press <Tab>
4. its just behaves like normal <Tab>

### Expected Behavior

As in config, <Tab> should be able to go to the next completion item in the menu.

### Repro

```Lua
-- I'm not not sure how to setup LazyVim distribution in this minimal config
-- I'm not able to reproduce in this minimal config

-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
Disable `<Tab>` from Luasnip. It's the one that uses it. See the [docs](https://www.lazyvim.org/plugins/coding#luasnip) and in the code as well [here](https://github.com/LazyVim/LazyVim/blob/78e6405f90eeb76fdf8f1a51f9b8a81d2647a698/lua/lazyvim/plugins/coding.lua#L71-L114).

**Comment by dupeiran001** [comment]
having disabled it like this:
```lua
return {
  "L3MON4D3/LuaSnip",
  keys = {
    { "<Tab>", false },
  },
}
```
but it seems not working.

its still set by 
```
i  <Tab>       * <Lua 266: ~/.local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/keymap.lua:127>
                 cmp.utils.keymap.set_map
```

**Comment by dpetka2001** [comment]
No, that's a different message. It's set by `nvim-cmp` this time. Here's what's working for me
```lua
return {
  {
    "hrsh7th/nvim-cmp",
    opts = function(_, opts)
      local cmp = require("cmp")
      opts.mapping = vim.tbl_extend("force", opts.mapping, {
        ["<Tab>"] = cmp.mapping.select_next_item({ behavior = cmp.SelectBehavior.Select }),
        ["<S-Tab>"] = cmp.mapping.select_prev_item({ behavior = cmp.SelectBehavior.Select }),
      })
    end,
  },
  {
    "L3MON4D3/LuaSnip",
    keys = function()
      return {}
    end,
  },
}
```

**Comment by dupeiran001** [comment]
thanks, it works
