### ISSUE TITLE
feature: show round line in float window

### ISSUE THREAD

**Issue by WikiLiu** [LazyVim/LazyVim#2708]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Why not add round line in float plane? Its so difficult to distinguish background special in smaller back color-diff. I saw many discuss about to add round in lsp-config, lsp-hover, and cmp-plane etc. Its complicating for me.
Will it seriously affect the appearance with round line?

### Describe the solution you'd like

as on

### Describe alternatives you've considered

as on

**Comment by WikiLiu** [comment]
> ### Did you check the docs?
> * [x]  I have read all the LazyVim docs
> 
> ### Is your feature request related to a problem? Please describe.
> Why not add round line in float plane? Its so difficult to distinguish background special in smaller back color-diff. I saw many discuss about to add round in lsp-config, lsp-hover, and cmp-plane etc. Its complicating for me. Will it seriously affect the appearance with round line?
> 
> ### Describe the solution you'd like
> as on
> 
> ### Describe alternatives you've considered
> as on
> 
> ### Additional context
> _No response_

ui.border

**Comment by dpetka2001** [comment]
In your `~/.config/nvim/lua/config/lazy.lua` you can add 
```lua
  ui = {
    border = "rounded",
  },
```
and then if you create a file `~/.config/nvim/lua/plugins/round.lua` with following contents
```lua
return {
  {
    "hrsh7th/nvim-cmp",
    opts = function(_, opts)
      local cmp = require("cmp")
      opts.window = {
        completion = cmp.config.window.bordered(),
        documentation = cmp.config.window.bordered(),
      }
    end,
  },
  {
    "williamboman/mason.nvim",
    opts = {
      ui = {
        border = "rounded",
      },
    },
  },
}
```
I believe it should take care of most of what you're trying to achieve.

**Comment by dpetka2001** [comment]
```lua
return {
  {
    "hrsh7th/nvim-cmp",
    opts = function(_, opts)
      local cmp = require("cmp")
      opts.window = {
        completion = cmp.config.window.bordered(),
        documentation = cmp.config.window.bordered(),
      }
    end,
  },
  {
    "williamboman/mason.nvim",
    opts = {
      ui = {
        border = "rounded",
      },
    },
  },
  {
    "folke/noice.nvim",
    opts = {
      presets = {
        lsp_doc_border = true,
      },
    },
  },
  {
    "neovim/nvim-lspconfig",
    opts = {
      diagnostics = {
        float = {
          border = "rounded",
        },
      },
    },
  },
}
```
Hope this covers your case.

**Comment by WikiLiu** [comment]
> ```lua
> return {
>   {
>     "hrsh7th/nvim-cmp",
>     opts = function(_, opts)
>       local cmp = require("cmp")
>       opts.window = {
>         completion = cmp.config.window.bordered(),
>         documentation = cmp.config.window.bordered(),
>       }
>     end,
>   },
>   {
>     "williamboman/mason.nvim",
>     opts = {
>       ui = {
>         border = "rounded",
>       },
>     },
>   },
>   {
>     "folke/noice.nvim",
>     opts = {
>       presets = {
>         lsp_doc_border = true,
>       },
>     },
>   },
>   {
>     "neovim/nvim-lspconfig",
>     opts = {
>       diagnostics = {
>         float = {
>           border = "rounded",
>         },
>       },
>     },
>   },
> }
> ```
> 
> Hope this covers your case.

Perfect，youre my Idol

**Comment by zaynOm** [comment]
This works perfectly, the only issue I have is the LSP completion popup does not have the same colorscheme instead it has a black bg

**Comment by WikiLiu** [comment]
> This works perfectly, the only issue I have is the LSP completion popup does not have the same colorscheme instead it has a black bg

don`t know exact appearance, maybe paste the screen?

**Comment by zaynOm** [comment]
I shared a screenshot with the solution you can take a look, [here](https://github.com/LazyVim/LazyVim/discussions/2092#discussioncomment-9786373)
