### ISSUE TITLE
feature: Include bg.nvim by default

### ISSUE THREAD

**Issue by 00sapo** [LazyVim/LazyVim#2710]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Neovim sets the background of its region, but the remaining surrounding pixels are not colored by neovim. They are still managed by the terminal emulator. This causes ugly borders in any terminal.

### Describe the solution you'd like

There is a plugin that needs no configuration and works like a charm: https://github.com/typicode/bg.nvim

### Describe alternatives you've considered

Add an extra layer, maybe, but the plugin should create no conflicts, so no reason to separate it from the default config...

**Comment by MarvinJWendt** [comment]
Once you see the border, you can't unsee it 😆 
I would also like to have this added to the defaults.

It recommends `{ "typicode/bg.nvim", lazy = false }`, but for me `{ "typicode/bg.nvim" }` works just as fine.

**Comment by yusufaktepe** [comment]
This is not suitable for the Kitty terminal, as it would make the background transparent. (See: [link](https://github.com/dracula/vim/issues/284#issuecomment-1086532742))

**Comment by 00sapo** [comment]
Yes, ot actually also has issues with my konsole setup. But it's worth to keep an eye on it or similar plugins

**Comment by folke** [comment]
I don't think this is something that should be a LAzyVim default.
You can always add it to your own config.
