### ISSUE TITLE
feature: Move lukas-reineke/headlines.nvim in its own extra

### ISSUE THREAD

**Issue by jordandelbar** [LazyVim/LazyVim#2717]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

headlines.nvim creates small icons in markdown files and makes them really buggy to edit. 

### Describe the solution you'd like

I would suggest to put headlines.nvim in its own dedicated extra because it is a nice to have functionality that hampers productivity (at least for me, but I am sure I am not the only one).

### Describe alternatives you've considered

Deactivate markdown.lang extra and add the different packages manually in the plugin folder.

**Comment by dpetka2001** [comment]
What small icons are you referring to?

**Comment by jordandelbar** [comment]
Those:
![image](https://github.com/LazyVim/LazyVim/assets/35341015/6e6fd858-0b3e-4a5f-8d91-a82d0441a543)

When you try to delete a # the user experience is far from great and sometimes it bugs out and you cannot delete the icons (the rendering freezes I guess).
![image](https://github.com/LazyVim/LazyVim/assets/35341015/f07cfa8e-7394-4660-b773-20bfdb2b1318)

These are also mentioned at the end of the README file of the repository:
https://github.com/lukas-reineke/headlines.nvim

**Comment by dpetka2001** [comment]
You just disable the headline highlights and you won't notice this
```lua
  {
    "lukas-reineke/headlines.nvim",
    opts = {
      markdown = {
        headline_highlights = false,
      },
    },
  },
```
It's because of the different background that the headline highlights and the colorscheme have. And if you don't like it at all you can just disable the plugin in your personal configuration, whilst still using the Markdown Extra. Just `enabled = false` to the above snippet. It's easier than disabling the Extra and adding all the rest manually (which of course you can still do if you like it more this way).

**Comment by dusty-phillips** [comment]
Looks like this is a recent regression that may be fixed someday. https://github.com/lukas-reineke/headlines.nvim/issues/66

**Comment by jordandelbar** [comment]
@dpetka2001 Indeed, I forgot I could do that. Thanks

**Comment by folke** [comment]
@dusty-phillips yeah, figured something must have changed. The current behavior is pretty annoying.

I just fixed it on the LazyVim side, by simply disabling headlines.nvim while in insert mode.

https://github.com/LazyVim/LazyVim/commit/0ba731a87977e98f2420e2c6d2c4cabbcedaff60

**Comment by folke** [comment]
I just made another update that disables the new bullets in headlines.nvim.

I'm sure some people like them, but I find them to be a bit too intrusive as a default.
