### ISSUE TITLE
bug: Please help me，I want to configure rust debug dap.croe

### ISSUE THREAD

**Issue by ThisGoLive** [LazyVim/LazyVim#2718]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

archlinux

### Describe the bug

 I open the Trust Cargo project. Tip:  Invalid config dap.configuration.program: expected string got function
 Execute leader d a, Top: the selected configuartion references adapter 'lldb', but dap.adapters.lldb is undefined

### Steps To Reproduce

refer to Describe the bug。
launch.json , I use vscode launch.json
![2024-03-12_21-45](https://github.com/LazyVim/LazyVim/assets/37787710/7586eb80-8275-4e69-8bff-bf6dd6b2733c)
![2024-03-12_21-46](https://github.com/LazyVim/LazyVim/assets/37787710/825ba55c-212e-49ea-8dc7-6df99333d6f5)

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "lldb",
      "request": "launch",
      "name": "Debug executable 'demo_cargo'",
      "cargo": {
        "args": [
          "build",
          "--bin=demo_cargo",
          "--package=demo_cargo"
        ],
        "filter": {
          "name": "demo_cargo",
          "kind": "bin"
        }
      },
      "args": [],
      "cwd": "${workspaceFolder}"
    },
    {
      "type": "lldb",
      "request": "launch",
      "name": "Debug unit tests in executable 'demo_cargo'",
      "cargo": {
        "args": [
          "test",
          "--no-run",
          "--bin=demo_cargo",
          "--package=demo_cargo"
        ],
        "filter": {
          "name": "demo_cargo",
          "kind": "bin"
        }
      },
      "args": [],
      "cwd": "${workspaceFolder}"
    }
  ]
}

```
I have checked the relevant dap. core configuration,  I am a beginner for Neovim users。But I don't know how to configure it 

https://github.com/LazyVim/LazyVim/discussions/894
https://stackoverflow.com/questions/77932510/cant-configure-to-make-the-nvim-dap-working-for-rust-development

### Expected Behavior

Can run debug normally, just like vscode

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
LazyVim doesn't configure `nvim-dap` to provide support for `launch.json` files. You should add it to your personal configuration if you want something like this. Read the `nvim-dap` [docs](https://github.com/mfussenegger/nvim-dap/blob/780fd4dd06b0744b235a520d71660c45279d9447/doc/dap.txt#L316-L380) for how to do it.

**Comment by ThisGoLive** [comment]
> LazyVim doesn't configure `nvim-dap` to provide support for `launch.json` files. You should add it to your personal configuration if you want something like this. Read the `nvim-dap` [docs](https://github.com/mfussenegger/nvim-dap/blob/780fd4dd06b0744b235a520d71660c45279d9447/doc/dap.txt#L316-L380) for how to do it.

Thank you very much for your reply. I found what I wanted from it. Then I realized that there was already an integrated project in place 😂

https://github.com/mrcjkb/rustaceanvim
