### ISSUE TITLE
bug: Nvim sometimes freezes when lazyterm is in background as if throttling

### ISSUE THREAD

**Issue by life00** [LazyVim/LazyVim#2719]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

Fedora Linux Asahi Remix 39 aarch64

### Describe the bug

When I run some moderately intensive build process using lazyterm and then hide the window with `:q` there is a high chance that my whole neovim session may freeze for some time and occasionally unfreezes until build is complete. This issue is not reproducible with light tasks (e.g. `sleep 100`) or if I do not hide lazyterm. My main guess is that when lazyterm is in the background it has some different process characteristics and the running build process may throttle neovim itself, while this does not occur in foreground.

### Steps To Reproduce

It is rather difficult to reproduce sometimes, but it seems that it is possible to reproduce it in the pretty much default lazyvim setup. I might have found a tendency that when I enable more intensive parts of my config the probability of neovim being frozen is higher. This makes me more confident that it is related to throttling.

Here are the steps that might help you to reproduce it:

1. have some lazyvim setup
2. have some code for an intensive build process
3. run the build process from lazyterm and hide lazyterm

This may or may not work because if its throttling then it may be system dependent.

### Expected Behavior

Process with any intensity should not result in neovim being throttled when lazyterm is hidden.

### Additional Information

I already submitted an exact same issue to toggleterm.nvim https://github.com/akinsho/toggleterm.nvim/issues/552 because the behavior is completely reproducible for both terminal plugins and it seems lazyterm is more susceptible to this issue. The dev from toggleterm.nvim said that this is too difficult of an issue and is kind of unrelated to that plugin which is fair enough, but now I am here.

I understand that lazyterm is basically a wrapper for default neovim terminal, however the default terminal cannot be hidden, so I guess this is introduced by lazyvim?

**Comment by folke** [comment]
Lazyterm uses Neovim's built-in terminal, so you should report this in the Neovim repo instead.
