### ISSUE TITLE
bug: Keymaps for Telescope find files root and find files cwd are switched

### ISSUE THREAD

**Issue by Aietes** [LazyVim/LazyVim#2725]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0-dev-2560+gf879a6545

### Operating system/version

MacOS 14.4

### Describe the bug

Keymaps for Telescope find files root and find files cwd are switched

### Steps To Reproduce

Keymap leader-ff is labeled as 'Find Files (root dir)' triggers find files cwd, and leader-fF vice-versa.

### Expected Behavior

Keymaps trigger telescope action like labelled.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
No, they're not switched. What Lazyvim refers as the root is actually the LSP `root_dir` and `cwd` is the directory where you invoke Neovim. You can change the behavior of how Lazyvim behaves with `vim.g.root_spec`.

**Comment by Aietes** [comment]
Thank you for the explanation! Is it common knowledge that root_dir refers to the LSP root? For me personally the labeling of the keymap is not intuitive...

**Comment by thesobercoder** [comment]
@dpetka2001 Thanks for saving me from hours of frustrations.
