### ISSUE TITLE
bug: I can not override <C-k> in inside config/keymaps.lua

### ISSUE THREAD

**Issue by radvil** [LazyVim/LazyVim#273]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v.0.9

### Operating system/version

Linux

### Describe the bug

I try to override <C-K> behavior, but it seems not working. I set it inside the config/keymaps.lua. Did I do it wrong way ??

### Steps To Reproduce

1. Install starter pack or LazyVim
2. set keymap on lua/config/keymaps.lua

### Expected Behavior

This should do it, I think I miss something

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}

vim.g.mapleader = " "

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
vim.keymap.set("n", "<C-K", "<Cmd>TmuxNavigateTop<CR>", {noremap=true,silent=true)
```

**Comment by folke** [comment]
What does `:verbose nmap <c-k>` say?

You need to set it in `lua/config/keymaps.lua`
