### ISSUE TITLE
bug: 'Util' (a nil value)

### ISSUE THREAD

**Issue by Mike-18awq** [LazyVim/LazyVim#2731]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Arch Linux

### Describe the bug

When attempting to execute the configuration for the nvim-jdtls plugin, an error occurs resulting in a failure to execute. The error message indicates an attempt to index the global variable 'Util', which is a nil value in the current context. This occurs at line 50 of the nvim-jdtls.lua file.

![4-JavaError](https://github.com/LazyVim/LazyVim/assets/137745753/c80b1b18-6e6a-43e8-808f-bdf09bd7203d)

### Steps To Reproduce

1. Install neovim - LazyVim
2. Active Lazy extras util.*
3. add config examples from [LazyVim](https://www.lazyvim.org/extras/lang/java#nvim-jdtls)

### Expected Behavior

The nvim-jdtls configuration executes successfully without any errors.

### Repro

```Lua


Failed to run `config` for nvim-jdtls

~/.config/nvim/lua/plugins/nvim-jdtls.lua:50: attempt to index global 'Util' (a nil value)

# stacktrace:
  - lua/plugins/nvim-jdtls.lua:50 _in_ **config**
  - lua/config/lazy.lua:9
  - init.lua:2

```

**Comment by dpetka2001** [comment]
This error comes from your own configuration
> Failed to run `config` for nvim-jdtls
~/.config/nvim/lua/plugins/nvim-jdtls.lua:50: attempt to index global 'Util' (a nil value)

You're doing something in that file and use `Util` without having it required probably.
