### ISSUE TITLE
bug:  lazygit commit history on current file

### ISSUE THREAD

**Issue by msMatix** [LazyVim/LazyVim#2735]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Windows

### Describe the bug

I wanted to try out the new function ```<leader>gf``` on my windows computer. Unfortunately, lazygit only opens normally. So I would do ```<leader>gg```. When I press ```<c-s>``` in lazygit the desired field appears. 

### Steps To Reproduce

1. Open Project File
2. <leader>gf
3. default window of lazygit opens

### Expected Behavior

Lazygit commit history on current file should be opened.

**Comment by msMatix** [comment]
Ah I found the problem. The issue seems to be the neovim version. Was a nightly build used here? The `vim.fn.system` does not work as expected with my Version (0.9.5). Therefore, the following adjustment:

```map("n", "<leader>gf", function()
  local git_path = vim.api.nvim_buf_get_name(0)
  Util.terminal({ "lazygit", "-f", vim.trim(git_path) }, { esc_esc = false, ctrl_hjkl = false })
end, { desc = "Lazygit current file history" })```

Does it make sense to create a PR? 

Matix

**Comment by dpetka2001** [comment]
Maybe it's just a WSL thing? I just tried it on Linux with Neovim 0.9.5 and it works as expected. `vim.fn.system` behaves differently on WSL? Not insinuating anything about the PR. Just trying to understand the underlying reason. 

@folke Would you happen to have more insight?

**Comment by msMatix** [comment]
Ah, very good! Thank you, @dpetka2001, for looking into that again. I use a pure Windows computer at work and no WSL. So I would have tried the whole thing again at home on my Manjaro system. But if that works. Let @folke decide.  I have a workaround for the Windows pc.

**Comment by dpetka2001** [comment]
As I said before, I'm not insinuating anything about the PR. Maintainer already gave his OK. 

Just trying to understand the reason why it's happening and if it's a Windows thing. That's all.

**Comment by dpetka2001** [comment]
Help of `vim.fn.system` quotes the following
>When {input} is given and is a valid buffer id, the content of 
the buffer is written to the file line by line, each line      
terminated by NL (and NUL where the text has NL).        
Result is a String, filtered to avoid platform-specific quirks: 
 `<CR><NL>` is replaced with `<NL>`                                
      

Maybe it's the different termination that is used on Windows that's causing this?

**Comment by msMatix** [comment]
Might be. Any idea how to check this?
I definitely will check my solution on my Manjaro system. The advantage of my solution would definitely be that you could then save yourself a function call. Have you tried mine to see if it would even work on linux?

**Comment by dpetka2001** [comment]
Just got home and tried your solution. Can verify it works both on Neovim stable and nightly on Linux.

**Comment by msMatix** [comment]
Yeah I also tried it. Due to it is less code and works on both systems I decided to make the pr.
Unfortunately I did not find a reason why the other one did not work.
