### ISSUE TITLE
bug: LSP for Rust `extras.lang.rust` does not work even with LazyVim starter on Windows 11 Powershell

### ISSUE THREAD

**Issue by gabrielkryss** [LazyVim/LazyVim#2746]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev-2597+gd326e0486

### Operating system/version

Windows 11

### Describe the bug

My Lsp for rust (rust-analyzer) wasn't working on the LazyVim starter. I made sure that most of my `:LazyHealth` was relatively green with the right compilers. My Neovin nightly version (installed using scoop) but it is >=0.10. It seems like from the error logs below there is something to do with `man.lua` for the Shift+K behavior. Another observation is that the rust-analyzer may not support the tool chain  'stable-x86_64-pc-windows-msvc' from the LSP Logs shown below. 

Any help on this would be appreciated, the LSP for `extras.lang.rust` used to work fine but not sure what happened that it is not working now. I even tried with a new sLazyVim starter to make sure nothing else was the case, and I tried looking around and similar issues with the rust-analyzer community and cannot find a similar issue, but if anyone does let me know. I also tried with Golang and the LSP and inlay hints work fine.

### Steps To Reproduce

1. clone LazyVim starter
2. go to extras and enable lang.rust
3. open a rust project
4. Warning about rust analyzer exiting
![image](https://github.com/LazyVim/LazyVim/assets/20222391/1e71e96d-f602-4433-97cd-2e9e45e7fe10)
5. Tried doing Shift+K on println!() and see this error
![image](https://github.com/LazyVim/LazyVim/assets/20222391/486a0f81-0439-4790-8499-15896cba4115)
6. Tried <leader>uh to toggle inlay hints and see these errors
![image](https://github.com/LazyVim/LazyVim/assets/20222391/1e9ba893-c81b-4fb2-b10e-f9cc86f04d96)
7. `:LspInfo` is not recognized even restarting LSP with`:LspRestart`
![image](https://github.com/LazyVim/LazyVim/assets/20222391/753dc945-ec58-4042-8989-c876be83d6f9)
8. `:LspLog`
```
4-03-15 16:58:58] LSP logging initiated
[ERROR][2024-03-15 16:58:58] .../vim/lsp/rpc.lua:789	"rpc"	"C:\\Users\\<name>\\AppData\\Local\\nvim-data\\mason\\bin\\taplo.CMD"	"stderr"	' INFO taplo: registered request handler method="initialize"\n INFO taplo: registered request handler method="textDocument/foldingRange"\n INFO taplo: registered request handler method="textDocument/documentSymbol"\n INFO taplo: registered request handler method="textDocument/formatting"\n INFO taplo: registered request handler method="textDocument/completion"\n INFO taplo: registered request handler method="textDocument/hover"\n INFO taplo: registered request handler method="textDocument/documentLink"\n INFO taplo: registered notification handler method="textDocument/didChange"\n INFO taplo: registered request handler method="textDocument/prepareRename"\n INFO taplo: registered notification handler method="workspace/didChangeWorkspaceFolders"\n INFO taplo: registered request handler method="taplo/listSchemas"\n INFO taplo: registered request handler method="taplo/associatedSchema"\n INFO taplo: registered notification handler method="initialized"\n INFO taplo: registered request handler method="textDocument/semanticTokens/full"\n INFO taplo: registered notification handler method="textDocument/didClose"\n INFO taplo: registered notification handler method="workspace/didChangeConfiguration"\n INFO taplo: registered request handler method="taplo/convertToJson"\n INFO taplo: registered request handler method="taplo/convertToToml"\n INFO taplo: registered request handler method="textDocument/rename"\n INFO taplo: registered notification handler method="textDocument/didOpen"\n INFO taplo: registered notification handler method="taplo/associateSchema"\n INFO taplo: registered notification handler method="textDocument/didSave"\n INFO taplo: LSP server listening transport="stdio"\n'
[ERROR][2024-03-15 16:59:05] .../vim/lsp/rpc.lua:789	"rpc"	"rust-analyzer"	"stderr"	"error: 'rust-analyzer.exe' is not installed for the toolchain 'stable-x86_64-pc-windows-msvc'\n"
[ERROR][2024-03-15 17:03:12] .../vim/lsp/rpc.lua:789	"rpc"	"C:\\Users\\<name>\\AppData\\Local\\nvim-data\\mason\\bin\\taplo.CMD"	"stderr"	" INFO taplo: received shutdown request id=Number(3) method=shutdown\n"
[START][2024-03-15 17:09:03] LSP logging initiated
[ERROR][2024-03-15 17:09:03] .../vim/lsp/rpc.lua:789	"rpc"	"rust-analyzer"	"stderr"	"error: 'rust-analyzer.exe' is not installed for the toolchain 'stable-x86_64-pc-windows-msvc'\n"
[START][2024-03-15 17:23:54] LSP logging initiated
[ERROR][2024-03-15 17:23:54] .../vim/lsp/rpc.lua:789	"rpc"	"rust-analyzer"	"stderr"	"error: 'rust-analyzer.exe' is not installed for the toolchain 'stable-x86_64-pc-windows-msvc'\n"
[START][2024-03-15 17:27:08] LSP logging initiated
[ERROR][2024-03-15 17:27:08] .../vim/lsp/rpc.lua:789	"rpc"	"rust-analyzer"	"stderr"	"error: 'rust-analyzer.exe' is not installed for the toolchain 'stable-x86_64-pc-windows-msvc'\n"
```

### Expected Behavior

LSP for rust should be working on a rust project as intended from the LazyVim starter, after enabling `extras.lang.rust`

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by gabrielkryss** [comment]
So seems like I fixed the issue by running
```
rustup add component rust-analyzer
```
I guess Mason doesn't do it for me as I thought it would because before I didn't have to do it and when I installed go the other day it seemed like installing `gopls` from Mason was good enough and I didn't have to install gopls with go cli. I guess just weird inconsistent behavior I guess. `LspInfo` still doesn't work consistent;y though but it sometimes will pop up after a restart maybe.

**Comment by FlippingBinary** [comment]
Executing `rustup component add rust-analyzer` did the trick for me on Windows 10. Thank you. I already had it installed, but the versions probably got mismatched or something.

**Comment by FabioCastroMorffi** [comment]
2 years later and still the same issue. Did the trick for me too.

**Comment by dpetka2001** [comment]
2 years later and if you'd made an effort to read `rustaceanvim`'s [docs](https://github.com/mrcjkb/rustaceanvim/blob/8717297ab2fcfac2e79fdd6044477f9d62329621/doc/mason.txt#L4-L8), you'd see that its design is to deliberately not detect `rust-analyzer` provided by Mason. 

The plugin author's suggestion is for the user to manually install it himself (see [his comment here](https://github.com/LazyVim/LazyVim/pull/2198#issuecomment-1999475044)). He also gives an example in the docs linked above for users who want rust-analyzer by Mason itself, but this is left up to users who explicitly want this. So, LazyVim just follows the plugin's intended behavior. You can still do whatever you want in your personal configuration if you prefer rust-analyzer via Mason.

**Comment by FabioCastroMorffi** [comment]
Pointless comment from my part. Thank you for the correction.
