### ISSUE TITLE
LSP is conflicting with colorschemes

### ISSUE THREAD

**Issue by rickalex21** [LazyVim/LazyVim#2747]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2507+g3df1211eb

### Operating system/version

Linux void 6.7.9_1 1 SMP PREEMPT_DYNAMIC Fri Mar  8 01:01:43 UTC 2024 x86_64 GNU/Linux

### Describe the bug

When `neovim/nvim-lspconfig` is enabled the colorscheme group will not be applied. The group
`Identifier` will remain the color I want until the lsp starts. This has been discussed [here](https://github.com/NvChad/NvChad/issues/1907). The temp fix for now is to use this as mentioned in that issue.

```lua
vim.highlight.priorities.semantic_tokens = 95 -- Or any number lower than 100, treesitter's priority level
```

### Steps To Reproduce

1. Clone a fresh install of LazyVim
2. Create file plugins/myplugins.lua

```lua
return {
  {
    "marko-cerovac/material.nvim",
    -- Comments are a bit darker than I would like
    config = function()
      require("material").setup({
        -- high_visibility = {
        -- lighter = false, -- Enable higher contrast text for lighter style
        -- darker = false, -- Enable higher contrast text for darker style
        -- },
        custom_highlights = {
          CursorLine = { bg = "#262626" }, -- 262626 looks good in comments.
          -- Identifier = { fg = "#de5d68" }, -- 262626 looks good in comments.
          Identifier = { fg = "#ffffff" }, -- 262626 looks good in comments.
        },
      })
    end,
  },

  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "material-darker",
    },
  },
}
```

### Expected Behavior

I expect my colorscheme options to be used for the group `Identifier` but they revert.
Here is a video of the issue.

https://github.com/LazyVim/LazyVim/assets/76216665/aba80ac0-1f8f-428a-afd4-890afe109d06

### Repro

```Lua
See Steps To Reproduce above.
```

**Comment by dpetka2001** [comment]
Isn't that a problem with Neovim itself? What does it have to do with LazyVim?

**Comment by rickalex21** [comment]
I'm not sure if that's a problem with Neovim itself? I'm not familar with thier code base.
Do I need to open up an issue with them?

**Comment by dpetka2001** [comment]
`vim.highlight.priorities` is being set directly from Neovim. LSP semantics have higher priority than treesitter. Instead of changing the value of `Identifier` i believe you should change the value of the LSP highlight that takes over to achieve what you want.
