### ISSUE TITLE
util.lualine.pretty_path enhancement

### ISSUE THREAD

**Issue by Old-Farmer** [LazyVim/LazyVim#2752]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Now, util.lualine.pretty_path only do some highlight when a buffer is modified. For someone who are not really sensitive to color it is not very good. Hope some other elements show when a buffer has been changed.

### Describe the solution you'd like

like add [+] when a buffer is modified

### Describe alternatives you've considered

none

**Comment by lkhphuc** [comment]
On the topic, does any find the default truncation of path to no more than 3 directories a little bit excessive?
Though I don't think dynamic truncation is possible with lualine at the moment.

**Comment by dpetka2001** [comment]
Not excessive for me, but that's purely personal preference from my part. 

You could still just copy the `pretty_path` function and make it look like you want. 

Or we could add a `trunc_level` variable and check if it's, for example, 0, then don't do any truncating. We could also do the truncating based on the `trunc_level`. For example, if `trunc_level = 5`, then we could just `unpack` the `parts` table based on the `trunc_level`. 

But again that begs the question of how a user would like to see it. Would he want to see the first 2 parts of the path, then the ellipses character and the last 3 parts at the end. Or would it be a 1 and 4 split? Or a 3 and 2 split? 

This complicates the logic unnecessarily I believe and should be better left to the user to implement a similar function in their personal configuration and use that function in their lualine component to make it look exactly how they like.
