### ISSUE TITLE
issue: Custom Python formatting for tabstop shiftwidth and autoindent

### ISSUE THREAD

**Issue by devhaocui** [LazyVim/LazyVim#2753]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

14.4 (23E214)

### Describe the bug

apologies if I am new to neovim/lazyvim/vim, but I cannot for the life of me find people with similar issues.
lazyvim works completely fine on it's own and indents and tabstops at 2 with .cpp files
But when using .py files the indent is set to 4 and I've spend a lot of hours trying to locate the issue.
Is there some kind of custom files that is causing this or options to modify the indentation?

### Steps To Reproduce

1. fresh install of lazyvim
2. create a .py file
3. try creating a function and see the indentation

### Expected Behavior

when creating a function in python it requires : instead of {} like it would in cpp. I expected the indentation to be the same as it would in .cpp files

**Comment by dpetka2001** [comment]
Neovim ships runtime ftplugin files that set settings for some languages. That's what you're observing here. You can type `:verbose set tabstop?` to see where it was last set and you will see it was set in a runtime ftplugin Neovim file (in default LazyVim at least if you haven't made any changes). You can create a file in `~/.config/nvim/after/ftplugin/python.lua` and set your local options for the python language. If you want for other languages you just replace `python.lua` with the name of the filetype of the language you want.

**Comment by devhaocui** [comment]
> Neovim ships runtime ftplugin files that set settings for some languages. That's what you're observing here. You can type `:verbose set tabstop?` to see where it was last set and you will see it was set in a runtime ftplugin Neovim file (in default LazyVim at least if you haven't made any changes). You can create a file in `~/.config/nvim/after/ftplugin/python.lua` and set your local options for the python language. If you want for other languages you just replace `python.lua` with the name of the filetype of the language you want.

yup, upon further looking up online I've finally found the solution and they recommended similar to what you said about ~/.config/nvim/after/ftplugin/python.lua and look for the exact line where it says tabstop=4 and changed that. It worked!!! thank you as well.

**Comment by devhaocui** [comment]
I now have an new issue, the settings @delatorrejuanchi recommended worked fine. But .py files when saving it using :wa or :w it will indent back to 4 spaces rather than 2 again. Any fixes for that?

**Comment by dpetka2001** [comment]
That is entirely up to the formatter you use and how you configure it.

**Comment by devhaocui** [comment]
I am currently using LazyVim and I think they use conform.nvim but I am not seeing any tabstop or shiftwidth options to configure.

**Comment by dpetka2001** [comment]
For Python you probably use `black` formatter, so you should read its docs for how to configure it.

**Comment by dpetka2001** [comment]
It seems that `black` formatter doesn't support specifying the indent level and there have also been tickets created at their repo but were disregarded as `won't be supported`. So, your best bet is to disable `black` formatter or disable LazyVim auto-formatting with `<leader>uf` or use some other formatter for Python which allows the user to specify the level of indent.. Not a LazyVim bug in my opinion, rather a formatter/user configuration issue.

**Comment by devhaocui** [comment]
this fixed the issue for me.
https://vi.stackexchange.com/questions/42597/how-to-disable-autoformating-on-save-on-lazyvim

**Comment by delatorrejuanchi** [comment]
I'm not sure what settings I've recommended. But for what it's worth, I don't think your solution should be to disable lsp autoformat.

You shouldn't expect that all languages have similar formatting rules. In fact, python recommends [4 spaces for tabs instead of two](https://peps.python.org/pep-0008/#indentation).

If it's truly your preference, go ahead and configure things the way you'd like. If you did this because you found that it didn't quite look the same as your C++ code, you're looking at it the wrong way!
