### ISSUE TITLE
bug: Changing init.lua breaks cache function

### ISSUE THREAD

**Issue by melas0nos** [LazyVim/LazyVim#276]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0-dev-794+gbcdbf7753

### Operating system/version

Windows Version10.0.19044 Build 19044

### Describe the bug

I got Lazy VIm using the "LazyVim Starter"

I tried for some time to figure out where one is supposed to make their own changes. I initially put in init.lua this next code to be able to use copy/paste in Windows WSL2, but it wouldnt work so I put in the .local/share/nvim/lazy/lazy.nvim/lua/lazy/init.lua:

```
vim.cmd([[
set clipboard=unnamedplus
]])
```
then I put in autocmds.lua 

I also added "set wrap" and a few other basic settings.
This is likely user error, so I would like to know where one is supposed to make changes because folowing the documentation for me did not work.

***

LazyVim was working fine for some time and I was able to Update and Sync without error, then yesterday it started giving this error when updating:

"Your local changes to the following files would be overwritten by checkout: init.lua"

So I made backups of the files I made slight changes to, then reverted them all to the current state unchanged. However when opening now I am getting this error:

```
Error detected while processing /home/melas/.config/nvim/init.lua:
E5113: Error while calling lua chunk: ...melas/.local/share/nvim/lazy/lazy.nvim/lua/lazy/init.lua:44: attempt to
call field 'enable' (a nil value)
stack traceback:
        ...melas/.local/share/nvim/lazy/lazy.nvim/lua/lazy/init.lua:44: in function 'setup'
        /home/melas/.config/nvim/lua/config/lazy.lua:9: in main chunk
        [C]: in function 'require'
        /home/melas/.config/nvim/init.lua:2: in main chunk
```

I apologize for my lack of knowledge here. This is the first neovim config that has just worked out of the box for me and I really like it. If I should just start over from scratch and use the LazyVim STarter again after deleted all the files I can do that, but perhaps you can tell me where I am supposed to make configuration changes like the set clipboard that need to be loaded every time the plugin loads, not lazy?

Thank you!

### Steps To Reproduce

Install via LazyVim Starter
make changes to add your own configurations to init.lua or others like options and autocmds
Updateing LazyVim (worked for a long time but just started giving error even though I have not changed anything for a long time)

### Expected Behavior

To continue updating normally

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
Have you read the [docs](https://www.lazyvim.org/)? You don't put your changes neither in `init.lua` or `.local/share/nvim/lazy`. You have to put it in the files `lua/config/{options,autocmds,keymaps}.lua` inside your `nvim` directory.

**Comment by melas0nos** [comment]
Yes but it does not make sense to me sorry. It says  Options is the only one that runs every time you open lazyvim if I understand correctly, because it loads BEFORE lazy.nvim, correct? So this is where I should put a change that I want to run every startup and not lazy?: 
```
vim.cmd([[
set clipboard=unnamedplus
]])
```

**Comment by melas0nos** [comment]
I just deleted and started completely over. I just must not understand how the "laziness" works. I will try putting the set clipboard function in the options.lua file only. Closing as a layer 8 issue. Sorry to waste your time, and have a nice day.

**Comment by folke** [comment]
@melas0nos ` clipboard=unnamedplus` is already the default with **LazyVim**, so you actually do not need to set that again.

You should indeed never make any changes to files under `~/.local/share/nvim/lazy`. Those are the plugins that are managed by lazy. They should not be manually changed.

You probably got confused by reading somewhere about `init.lua`?

Every time you see that mentioned, people are talking about the file `~/.config/nvim/init.lua`.

That is the entry point that loads your Neovim config. In the case of `LazyVim`, that's where the file `lua/config/lazy.lua` will be required and will load all your plugins.

You are free to make changes to that file however. Typically after the `require` that sets up yourplugins.

I hope this helps!
