### ISSUE TITLE
bug: New warning from extra on `nvim-dap-ui` saying `nvim-nio` to be installed

### ISSUE THREAD

**Issue by jsatk** [LazyVim/LazyVim#2764]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

macOS 14.4

### Describe the bug

On start up I see the following message after running the LazyVim Update.

```
  lazy.nvim                                                                                                                                         11:57:29 
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Failed to run config for nvim-dap-ui

...on/.local/share/nvim/lazy/nvim-dap-ui/lua/dapui/init.lua:36: nvim-dap-ui requires nvim-nio to be installed. Install from https://github.com/nvim-neotest/nv

# stacktrace:
  - /LazyVim/lua/lazyvim/plugins/extras/dap/core.lua:31 in config
  - ~/.config/nvim/lua/plugins/metals.lua:7 in config
  - /telescope.nvim/lua/telescope/_extensions/init.lua:8 in load_extension
  - /telescope.nvim/lua/telescope/_extensions/init.lua:17 in __index
  - ~/.config/nvim/lua/config/keymaps.lua:22
  - /LazyVim/lua/lazyvim/config/init.lua:233
  - /LazyVim/lua/lazyvim/config/init.lua:232 in _load
  - /LazyVim/lua/lazyvim/config/init.lua:241 in load
  - /LazyVim/lua/lazyvim/config/init.lua:179
```

### Steps To Reproduce

Simply run the latest set of updates via `:Lazy` and include the extra `nvim-dap-ui` and re-open neovim.

### Expected Behavior

No error.

**Comment by dpetka2001** [comment]
There's already #2763 waiting to be merged.

**Comment by dpetka2001** [comment]
You can just add the dependency in your personal configuration until it gets merged, so that you don't get the error.

**Comment by roeybenarieh** [comment]
I have the same issue, hopefully get merged soon :-)

**Comment by Aietes** [comment]
As @dpetka2001 says, simply add the dependency to any file in the `lua/plugins` folder:

```lua
return {
  {
    "nvim-neotest/neotest",
    dependencies = { "nvim-neotest/nvim-nio" }
  }
}
```

**Comment by GrassedgeT** [comment]
same fault, it works!

**Comment by GrassedgeT** [comment]
> As @dpetka2001 says, simply add the dependency to any file in the `lua/plugins` folder:如前所述，只需将依赖项添加到文件夹中的任何文件： `lua/plugins`
> 
> ```lua
> return {
>   {
>     "nvim-neotest/neotest",
>     dependencies = { "nvim-neotest/nvim-nio" }
>   }
> }
> ```

same fault, it works!
