### ISSUE TITLE
bug: CMake Tools making DAP load in any file

### ISSUE THREAD

**Issue by uthmanmoh** [LazyVim/LazyVim#2767]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2501+gdbf6be296-Homebrew Build type: Release LuaJIT 2.1.1703358377

### Operating system/version

MacOS 14.4

### Describe the bug

When I add the `cmake` extra by adding `{ import = "lazyvim.plugins.extras.lang.cmake" }` and I also have the `dap` extra enabled, it is making `nvim-dap` load as soon as I enter any file, even though `nvim-dap` shouldn't work in the file.

<img width="1142" alt="image" src="https://github.com/LazyVim/LazyVim/assets/83053931/215f1413-9e3a-46ed-9555-97181746a6c4">

When I remove this `cmake` extra, `nvim-dap` doesn't load on any file entry, and only loads when a keymap for dap is pressed.

I don't understand exactly where `nvim-dap` is being loaded from, but it seems like it's coming from `Civitasv/cmake-tools.nvim` based on this in Lazy Profile
<img width="904" alt="image" src="https://github.com/LazyVim/LazyVim/assets/83053931/b15020db-172a-4868-adea-4ef0e47ad355">

Just in case I am mistaken and something else is causing this problem instead, here is my entire nvim config: https://github.com/uthmanmoh/nvim

### Steps To Reproduce

1. Add `dap` and `cmake` extras
2. Open any file in neovim with this config
3. Notice that all the `nvim-dap` plugins are enabled in `:Lazy`

### Expected Behavior

I expect `nvim-dap` and all related plugins (like `nvim-dap-go`, etc) to only load when they need to be used, such as when a key is pressed

**Comment by uthmanmoh** [comment]
On a separate note, how come `nvim-dap-go` and `nvim-dap-python` are being loaded in files that aren't go or python, even when `nvim-dap` is loaded? Should these plugins ([nvim-dap-go ref](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/extras/lang/go.lua#L134-L137)) have a `ft` to them?

**Comment by dpetka2001** [comment]
It seems that `cmake-tools` have inherently debug configuration and that's why they load `nvim-dap` as well. Create an issue at their repo to see if the maintainer is willing to make that behavior configurable by the user. Don't think anything can be done from LazyVim side.

**Comment by uthmanmoh** [comment]
Can we make the plugin load in `cmake` projects only or something? Making the plugin load when entering any file doesn't seem like a good idea anyways since it only applies to cmake projects

**Comment by uthmanmoh** [comment]
The fact that it takes 110ms to load when the plugin isn't needed at all in most files seems like a bug in the cmake extra to me. 110ms is a considerable amount of slowdown for neovim.

In my opinion if LazyVim can make this plugin load only when necessary it will be a good performance improvement for all users of LazyVim (or at least the ones with the extra enabled)

If anyone has a good suggestion on a condition to make this plugin load that will encompass all needs of cmake I'd be willing to make a PR to add that
