### ISSUE TITLE
bug: using the tab button makes the cursor jump around like crazy

### ISSUE THREAD

**Issue by amanafro** [LazyVim/LazyVim#2772]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

Opensuse (Linux)  / tumbleweed 20240314 x86_64

### Describe the bug

every time I'm in insert mode and i want to indent the cursor just jumps around. i can use the space bar but it wouldn't be consistent and accurate. it just is frustrating to deal with.  

### Steps To Reproduce

1. get to a empty line
2. go into insert mode
3. hit the tab button 
4. the cursor jumps around like crazy 

### Expected Behavior

when i hit the tab button i want it to indent into the line

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
I can't reproduce. But the only place that `<Tab>` is being used at the moment is the Luasnip plugin. You could just overwrite the keymap yourself and use something else and that way `<Tab>` will only be used for indenting always, so I guess it shouldn't cause you any more problems in your case.

**Comment by bchopson** [comment]
https://github.com/L3MON4D3/LuaSnip/issues/953

**Comment by folke** [comment]
I've personally moved away from using luasnip and I use the native snippets in Neovim 0.10.0.

There's an extra to enable it.
