### ISSUE TITLE
bug: I can not known this bug

### ISSUE THREAD

**Issue by iafshinafshin** [LazyVim/LazyVim#2774]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Arch linux 6.8

### Describe the bug

I have this bug : 
Error detected while processing /home/afshin/.config/nvim/
init.lua:
E5113: Error while calling lua chunk: vim/keymap.lua:0: invalid key: description
stack traceback:
        [C]: in function 'nvim_set_keymap'
        vim/keymap.lua: in function 'set'
        ...share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/keys.lua:189: in function '_set'
        ...share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/keys.lua:177: in function '_del'
        ...share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/init.lua:132: in function 'del'
        ...share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/init.lua:43: in function 'disable'
        ...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:336: in function '_load'
        ...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:191: in function 'load'
        ...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:123: in function 'startup'
        ...fshin/.local/share/nvim/lazy/lazy.nvim/lua/lazy/init.lua:110: in function 'setup'
        /home/afshin/.config/nvim/lua/config/lazy.lua:14: in main chunk
        [C]: in function 'require'
        .../.config/nvim/init.lua:10: in main chunk

### Steps To Reproduce

Null

### Expected Behavior

Null

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
Somewhere in your `keys` section you have set `description` to something. This is not a valid term in `lazy.nvim`. It should be `desc` instead.

**Comment by iafshinafshin** [comment]
Hey, I fixed them
