### ISSUE TITLE
bug: Parentheses added when importing react functional component

### ISSUE THREAD

**Issue by alivault** [LazyVim/LazyVim#2780]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

macOS 14.3.1

### Describe the bug

If I have the following React component:

```jsx
export function Example() {
  return <h1>Example</h1>;
}
```

When I type `<Example` and hit enter, I get `<Example()`. The auto-completion recognizes the imported value as a function, but adds parentheses after it. I think the default should be not to call the function when importing.

This seems to have been [solved in LunarVim](https://github.com/LunarVim/LunarVim/issues/2082#issue-1080215114) by the way. I think LazyVim should do the same so that when we import react functional components we don't get `<Example()`

### Steps To Reproduce

1. Create a react component like this:
```jsx
export function Example() {
  return <h1>Example</h1>;
}
```
2. Import the component using auto import by typing `<Example` and hit enter
3. Observe the parentheses added at the end `<Example()`

### Expected Behavior

Parentheses should not be added when importing a function.

**Comment by dpetka2001** [comment]
Are you using `nvim-autopairs`?

**Comment by alivault** [comment]
No nvim-autopairs, just the included mini.pairs

**Comment by dpetka2001** [comment]
I disabled the `mini.pairs` but this still happens. Do you observe the same behavior with `mini.pairs` disabled? This leads me to believe the problem originates from some kind of interaction between `nvim-cmp` and the `tsserver`. Your best bet would be to create an issue at `nvim-cmp` repo. The issue that you mentioned in Lunarvim was using `nvim-autopairs` in combination with `nvim-cmp` and they just removed `nvim-autopairs`. But LazyVim doesn't use `nvim-autopairs`. So whatever completion you get is a combination of `nvim-cmp` and `tsserver` itself.

**Comment by alivault** [comment]
Yes it still happens with mini.pairs disabled. I'll open an issue at the nvim-cmp repo, thanks.

**Comment by dpetka2001** [comment]
@alivault 

Ok, I experimented a bit further and also created a config without LazyVim and that problem you're observing doesn't come up there. So, I looked into how LazyVim sets up Typescript and I believe I found the culprit. Try the following
```lua
-- ~/.config/nvim/lua/plugins/lsp.lua
return {
  {
    "neovim/nvim-lspconfig",
    opts = function(_, opts)
      opts.servers.tsserver.settings.completions.completeFunctionCalls = false
    end,
  },
}
```
Typescript LSP server is configured to `true` with the above value. Now, I don't do Typescript myself and am not familiar with the above value, but setting that value to `false` seems to produce the completion that you expect.

**Comment by alivault** [comment]
@dpetka2001 
That is exactly what was causing the issue, thank you! I do think false should be the default. That way we can import react components without the added parentheses, which is not what is expected when typing `<Example`

**Comment by dpetka2001** [comment]
Like I said I don't do Typescript myself. It's a default chosen by the maintainer. No idea what the default should be. 

Maybe pinging @folke will give you a better understanding of why it was chosen as default.

**Comment by alivault** [comment]
@folke I encountered this bug where functional components are getting completed with parentheses like `<Example()`. @dpetka2001 has found the solution above. I think the complete function calls setting in tsserver should be false by default to prevent this bug.

**Comment by folke** [comment]
This is a bug in tsserver, so report it there.
Disabling that option, would disable function handling **anywhere**, which is not desirable

**Comment by arn4v** [comment]
@alivault Did you figure out how to fix this?

**Comment by alivault** [comment]
@arn4v dpetka2001 provided a solution above. I wrote up a post explaining the fix here: https://www.aliabbas.dev/articles/troubleshooting-neovim-fixing-unwanted-parentheses-in-react-imports

**Comment by ThomasCode92** [comment]
@alivault - The link to your blog post seems to be broken. Can you please share how you fixed this?

**Comment by alivault** [comment]
@ThomasCode92 
dpetka2001 provided the solution [here](https://github.com/LazyVim/LazyVim/issues/2780#issuecomment-2010488293). 
Although if you update LazyVim to the latest version, this issue seems to be gone and there is no need for this fix anymore.
