### ISSUE TITLE
bug: OSC52 not working as expected

### ISSUE THREAD

**Issue by tby321** [LazyVim/LazyVim#2782]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2657+g9765efb40

### Operating system/version

Linux 4.19.91

### Describe the bug

After commit [fix(options): dont set clipboard in an SSH session, so that OSC52 can be enabled (when supported)](https://github.com/LazyVim/LazyVim/commit/1c9f4160a22dbdca2db36169460fcf28641607e7)
I cannot yank from neovim over ssh on neovim nightly 9765efb40f57b543d9fea610fb0d0f05b8387454
Before this commit, all works as expected.

### Steps To Reproduce

1. Log in to the machine via ssh
2. Attach to existing tmux session
3. Open random file
4. yy

### Expected Behavior

yank lines to system clipboard using OSC52

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
There was a change in nightly for which this new approach was needed, so update your nightly.

Basically Neovim now automatically enables OSC52 as long as vim.opt.clipboard is not set

**Comment by folke** [comment]
You could also copy that previous autocmd to your autocmds if that works with your nightly
