### ISSUE TITLE
bug: lazyvim.util.telescope always sets show_untracked to true in a git repo, preveting recurse_submodules from working with it

### ISSUE THREAD

**Issue by Berteun** [LazyVim/LazyVim#2788]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2507+g3df1211eb

### Operating system/version

openSUSE Leap 15.5

### Describe the bug

LazyVim's Util.telescope always sets 'show_untracked' to true when executing git_files, passing 'recurse_submodules' is therefore not possible, as both cannot be set at the same time.

If `recurse_submodules` is passed explicitly, `show_untracked` should not be forced. Otherwise passing it explicitly should allow one to disable show_untracked without it being forcibly enabled.

Offending line [in `lazy/LazyVim/lua/lazyvim/util/telescope.lua` ](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/util/telescope.lua#L32).

### Steps To Reproduce

1. Add a keybinding for telescope to your `lua/plugins/telescope.lua` file like this:
```
local Util = require("lazyvim.util")

return {
    "nvim-telescope/telescope.nvim",
        keys = {
                { "<leader>fa", Util.telescope("files", { recurse_submodules=true, show_untracked=false }), desc = "Find All Files (root dir)" },
        },
}
```
2. In normal mode press <leader>fa, while in a git repository and observe the error: `[telescope.builtin.git_files]: Git does not support both --others and --recurse-submodules` ; even though show_tracked=false is explicitly passed, it's overwritten by the plugin.

### Expected Behavior

I would expect this to work and execute `Telescope git_files recurse_submodules=True` .

**Comment by dpetka2001** [comment]
Just make a new keymap yourself and don't use `util.telescope`?

**Comment by Berteun** [comment]
Sure, but the nice thing about util.telescope files is that it looks whether it is in a git repo or not, so then it basically becomes a copy paste of that function, whereas to me it seems more logically to only set the show_tracked if the user doesn't specify it.

**Comment by dpetka2001** [comment]
Can you try the following
```lua
local Util = require("lazyvim.util")
return {
  {
    "dpetka2001/LazyVim",
    branch = "fix/util-telescope",
  },
  {
    "nvim-telescope/telescope.nvim",
    keys = {
      {
        "<leader>fa",
        Util.telescope("files", { recurse_submodules = true, show_untracked = false }),
        -- Util.telescope("files", {}),
        desc = "Find All Files (root dir)",
      },
    },
  },
}
```
and see if it works for you? If yes, I'll submit a PR. It doesn't throw an error for me any more, but I don't use submodules and can't test it further if anything else is amiss.

**Comment by Berteun** [comment]
Yes that works -- thank you.
