### ISSUE TITLE
bug: Background is set to light by default eventhough I have set my colorscheme to `tokyonight-moon`

### ISSUE THREAD

**Issue by martisj** [LazyVim/LazyVim#279]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.3

### Operating system/version

macos 13.2

### Describe the bug

I have a `~/.config/nvim/lua/plugins/colorscheme.lua` file with the following contents:
```lua
return {
  -- { "Mofiqul/vscode.nvim" },
  { "folke/tokyonight.nvim", lazy = true, opts = { style = "moon" } },

  -- Configure LazyVim to load colorscheme
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "tokyonight",
    },
  },
}
```

I expect the background to be dark.

### Steps To Reproduce

1. Copy the plugin config to `~/.config/nvim/lua/plugins/colorscheme.lua`
2. Restart nvim

### Expected Behavior

Background should be dark and colorscheme should be `tokyonight-moon`

**Comment by folke** [comment]
That's not how it works. You can set `colorscheme = "tokyonight-moon"` explicitly, or set `vim.go.background = "dark"` in your `lua/config/options.lua`

**Comment by martisj** [comment]
Aha! Thanks! that is indeed the case

**Comment by jackplus-xyz** [comment]
Hi,

Is it possible to set two different color schemes based on the background color?

**Comment by folke** [comment]
background detection will be too late and this will not (always) work. Neovim's background detection is async, so you'd have to listen to option changes, or set the colorscheme later. Do know that a lot of plugins don't properly listen to colorscheme changes and if you load the colorscheme after those plugins, the plugin colors may be off.

**Comment by jackplus-xyz** [comment]
Thanks!
