### ISSUE TITLE
bug: typescript extra doesn't configure nvim-dap correctly

### ISSUE THREAD

**Issue by mesmere** [LazyVim/LazyVim#2800]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

refs/heads/main

### Operating system/version

N/A

### Describe the bug

You can see in [the code](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/extras/lang/typescript.lua#L72) or [the documentation](https://www.lazyvim.org/extras/lang/typescript#nvim-dap-optional) that dap setup is performed in the `opts` function:

```lua
,
opts = function()
  local dap = require("dap")
  -- etc etc
```

When `opts` is defined and `config` is not defined **- as is the case for the LazyVim typescript extra -** lazy.nvim provides a default `config` implementation that looks roughly like:

```lua
config = function(_, opts)
  require("dap").setup(opts)
end
```

Unfortunately, dap has no `setup` function, so loading the plugin will fail if lazy tries to run the default `config` function.

### Steps To Reproduce

Enable the typescript extra with the nvim-dap plugin. Reload plugins and see that nvim-dap fails to load, showing a stack trace with `attempt to call field 'setup' (a nil value)`.

### Expected Behavior

Plugins load with no errors dumped to :messages

**Comment by dpetka2001** [comment]
Did you enable the `dap.core` Extra?
