### ISSUE TITLE
bug: getting error after update "attempt to index field 'uv' (a nil value)"

### ISSUE THREAD

**Issue by manhhn01** [LazyVim/LazyVim#2803]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

MacOS 14.3.1

### Describe the bug

After update LazyVim i getting this error
![image](https://github.com/LazyVim/LazyVim/assets/34568913/11a09a0b-0166-4fab-ab81-3f412d46b5b4)
Tried removing old config and install again but it didn't work

### Steps To Reproduce

git clone https://github.com/LazyVim/starter ~/.config/nvim

### Expected Behavior

Can use lazyvim with neovim v0.9.5

**Comment by soOwasTaken** [comment]
same issue here

**Comment by pkropachev** [comment]
I faced with the same problem. Then during attempt edit text in any files the following notification appears:

![image](https://github.com/LazyVim/LazyVim/assets/34160907/cef32f9b-50fc-405f-95c4-436245b5328a)

**Comment by folke** [comment]
You need to also update lazy.nvim
