### ISSUE TITLE
Rustaceanvim is not producing diagnostics

### ISSUE THREAD

**Issue by mlp1802** [LazyVim/LazyVim#2808]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

Ubuntu

### Describe the bug

It only show diagnostics for gibberish, more subtle errors are ignored.
Before latest lazy vim update (I think) everything was working fine.

![dia](https://github.com/LazyVim/LazyVim/assets/4717892/87d28978-821c-44c9-a03b-d01244e3a493)

### Steps To Reproduce

I'm not sure

### Expected Behavior

It should show diagnostics in telescope and using virtual text 

### Repro

```Lua
Rustaceanvim config

local common = require("config.common")
return {
  "mrcjkb/rustaceanvim",
  enabled = true,
  version = "^4", -- Recommended
  ft = { "rust" },
  opts = {
    server = {
      on_attach = function(_, bufnr)
        vim.keymap.set("n", "<M-3>", common.workspace_diagnostics, { noremap = true, silent = true })
        vim.keymap.set("n", "<M-w>", common.document_diagnostics, { noremap = true, silent = true })
        vim.keymap.set("n", "<M-w>", common.document_diagnostics, { noremap = true, silent = true })
        vim.keymap.set("n", "<leader>cR", function()
          vim.cmd.RustLsp("codeAction")
        end, { desc = "Code Action", buffer = bufnr })
        vim.keymap.set("n", "<leader>dr", function()
          vim.cmd.RustLsp("debuggables")
        end, { desc = "Rust debuggables", buffer = bufnr })
      end,
      default_settings = {
        -- rust-analyzer language server configuration
        ["rust-analyzer"] = {
          cargo = {
            allFeatures = true,
            loadOutDirsFromCheck = true,
            runBuildScripts = true,
          },
          -- Add clippy lints for Rust.
          checkOnSave = {
            allFeatures = true,
            command = "check",
            extraArgs = { "--no-deps" },
          },
          procMacro = {
            enable = true,
            ignored = {
              ["async-trait"] = { "async_trait" },
              ["napi-derive"] = { "napi" },
              ["async-recursion"] = { "async_recursion" },
            },
          },
        },
      },
    },
  },
  config = function(_, opts)
    vim.g.rustaceanvim = vim.tbl_deep_extend("keep", vim.g.rustaceanvim or {}, opts or {})
  end,
}

Lsp config
```lua
return {
  "neovim/nvim-lspconfig",
  enabled = true,
  opts = {
    diagnostics = {
      signs = {
        text = {
          [vim.diagnostic.severity.ERROR] = require("lazyvim.config").icons.diagnostics.Error,
          [vim.diagnostic.severity.WARN] = require("lazyvim.config").icons.diagnostics.Warn,
          [vim.diagnostic.severity.HINT] = require("lazyvim.config").icons.diagnostics.Hint,
          [vim.diagnostic.severity.INFO] = require("lazyvim.config").icons.diagnostics.Info,
        },
      },
    },
    servers = {
      rust_analyzer = {
        --   settings = {
        --     ["rust-analyzer"] = {
        --       cargo = {
        --         allFeatures = true,
        --         loadOutDirsFromCheck = true,
        --         runBuildScripts = true,
        --       },
        --       -- Add clippy lints for Rust.
        --       checkOnSave = {
        --         allFeatures = true,
        --         command = "check",
        --         arguments = {},
        --         extraArgs = {},
        --       },
        --       procMacro = {
        --         enable = true,
        --         ignored = {
        --           ["async-trait"] = { "async_trait" },
        --           ["napi-derive"] = { "napi" },
        --           ["async-recursion"] = { "async_recursion" },
        --         },
        --       },
        --     },
        --   },
      },
      taplo = {
        keys = {
          {
            "K",
            function()
              if vim.fn.expand("%:t") == "Cargo.toml" and require("crates").popup_available() then
                require("crates").show_popup()
              else
                vim.lsp.buf.hover()
              end
            end,
            desc = "Show Crate Documentation",
          },
        },
      },
    },
    setup = {
      rust_analyzer = function()
        return true
      end,
    },
  },

  init = function()
    local keys = require("lazyvim.plugins.lsp.keymaps").get()
    --change a keymap
    --keys[#keys + 1] = { "K", "<cmd>echo 'hello'<cr>" }
    -- disable a keymap
    --keys[#keys + 1] = { "K", false }
    -- add a keymap
    keys[#keys + 1] = { "gD", SimpleGoToDefinition, desc = "Goto defition in new split" }
    keys[#keys + 1] = {
      "gd",
      function()
        vim.lsp.buf.definition({ reuse_win = false })
      end,
      desc = "Goto definition hm",
    }
  end,
}
```
```

**Comment by mlp1802** [comment]
Should not that everything else, refactoring, goto definition etc, works perfectly

**Comment by dpetka2001** [comment]
Install rust and rust-analyzer via `rustup` from the official docs. Per `rustaceanvim`'s author and maintainer the plugin doesn't automatically pick up `rust-analyzer` from Mason. So, you should install it yourself. Following picture with a test with your code

![2024-03-22_18-21](https://github.com/LazyVim/LazyVim/assets/12776461/52906b2c-c2ad-4d25-b94a-3f00f522aaab)

This is with LazyVim's default settings for `rustaceanvim`.

**Comment by mlp1802** [comment]
Already did this in the project root:
```
 rustup component add rust-analyzer
``` 
Andrust analyzer was already installed. How could refactoring etc work without rust analyzer? the only thing that doesnt work is diagnostics

**Comment by dpetka2001** [comment]
Can you try with default LazyVim settings to see if there are diagnostics like in the picture i attached in my previous comment? Maybe it has something to do with your configuration on your end?

**Comment by mlp1802** [comment]
OK but what is default settings? I already have only plugins related to lsp and telescope running, and all those are with the default settings as specified on the website. Did delete lazy vim and reinstalled it as well.

**Comment by dpetka2001** [comment]
Try the following
```bash
1. `mkdir ~/.config/lazytest`
2. `git clone https://github.com/LazyVim/starter ~/.config/lazytest`
3. `NVIM_APPNAME=lazytest nvim` and wait for the installation to complete
4. Restart Neovim with the command provided in step 3 and ONLY enable the Rust LazyExtra (to enable it press `x` for LazyExtras from dashboard and then find `lang.rust` and press `x` to enable it)
5. Restart Neovim with command from step 3 and open your Rust file
```
This should give you a fresh LazyVim starter installation. Do you observe the same behavior with above steps?

For cleanup do
```bash
rm -rf ~/.config/lazytest
rm -rf ~/.local/share/lazytest
rm -rf ~/.local/state/lazytest
rm -rf ~/.cache/lazytest
```

**Comment by mlp1802** [comment]
Ok I'll try that tomorrow, that seems like the way to do it. Thanks.

**Comment by mlp1802** [comment]
I did it in a slightly different way, just renaming my old nvim config file. Then cloned the repo. Same result, works but no diagnostics. It shows warnings (before I filtered by severity error) but no errors, only the most simple errors. Underlines errors with red though, but no message. Think it could be something with the rust installations or something.

**Comment by dpetka2001** [comment]
Please do try the way I suggested. That way you get a fresh new LazyVim installation without any remnants from your old config.

**Comment by dpetka2001** [comment]
How did you install Rust? Via a package manager or via the method mentioned in the official [docs](https://www.rust-lang.org/tools/install)?

**Comment by mlp1802** [comment]
I dont know really, it's been years since I installed it. I use rustup to update it once in a while. Version for the project is rustc 1.79.0-nightly (0ad927c0c 2024-03-21)

**Comment by dpetka2001** [comment]
`rust-analyzer --version` and `rustc --version`, do they show the same build version? I remember a similar issue with another user, who was using Gentoo and had installed Rust via `emerge` and then uninstalled it and installed via the method in the official docs (that I linked in my previous post) and his problems went away. Might be worth to explore this route if you don't mind. Also from inside Neovim if you press `:!which rust-analyzer` it should show the path of `rust-analyzer` installed via `rustup` and not the path from Mason.

**Comment by mlp1802** [comment]
rust-analyzer version (from command line) rust-analyzer 1.79.0-nightly (0ad927c 2024-03-21)
Rust analyzer version used by vim (!rust-analyzer  --version) 0.3.1885-standalone (b6d1887bc 2024-03-17)



!which rust-analyzer: 
~/.local/share/nvim/mason/bin/rust-analyzer
which rust-analyzer:
~/.cargo/bin/rust-analyzer
So that could be the problem!
It uses the mason one and not the newest one on command line. Can that be changed?
Can I simply just disable mason?

**Comment by mlp1802** [comment]
Ok disabled mason and it uses the "real" one, lets see what happens..

**Comment by mlp1802** [comment]
Ok that didn't make a difference at all damn.

**Comment by dpetka2001** [comment]
Put in a file in `/lua/plugins/` directory the following contents
```lua
return {
  {
    "neovim/nvim-lspconfig",
    opts = {
      servers = {
        rust_analyzer = {
          mason = false,
        },
      },
    },
  },
}
```
And then from Mason UI uninstall `rust-analyzer` and restart Neovim with Rust extra enabled.

**Comment by mlp1802** [comment]
I disabled mason and updated the servers {} section but it's the same problem..

**Comment by dpetka2001** [comment]
Does Mason show if `rust-analyzer` is installed or not?

**Comment by mlp1802** [comment]
How can I make it show me? I see rustanalyzer starting up in lower right corner..and it should work because everything else works, like refactoring, goto definition, auto completion, signatures.

**Comment by dpetka2001** [comment]
Just press `<leader>cm` or write `:Mason` so that its UI pops up. Then you will see what tools are installed.

**Comment by mlp1802** [comment]
OK but didn't you want to to disable it? I know for a fact the rust analyzer runs, or nothing would work at all?

**Comment by dpetka2001** [comment]
I didn't say to disable Mason. In my previous code snippet I provided, you're just making sure that Mason will not install `rust-analyzer`, so that `rust-analyzer` from `~/.cargo/bin` will be picked up instead.

**Comment by mlp1802** [comment]
![mason](https://github.com/LazyVim/LazyVim/assets/4717892/47bcd56c-9bbf-4d7e-97cc-a7e5d2652632)
I enabled it again and ran the Mason command

**Comment by dpetka2001** [comment]
Did you add the code snippet I mentioned in my previous [post](https://github.com/LazyVim/LazyVim/issues/2808#issuecomment-2016475599)? Make sure you do that and then in the Mason UI go with your cursor on top of `rust-analyzer` and press `X` (capital x) to uninstall `rust-analyzer` installed by Mason.

**Comment by mlp1802** [comment]
Ok I enabled Mason again, and when its enabled, Mason kicks in and uses its own mason rust analyzer, not the one from cargo. But with a disabled mason, the one from .cargo runs.

**Comment by mlp1802** [comment]
Yes I added your code snippet.

**Comment by mlp1802** [comment]
Mason dont seem to care about your codesnippet though

**Comment by dpetka2001** [comment]
Uninstall `rust-analyzer` from Mason by pressing `X`.

**Comment by mlp1802** [comment]
OK it says "E21: Cannot make changes, 'modifiable' is off" when I try to delete language server (masons)

**Comment by dpetka2001** [comment]
Press `Shift-x`, not just `x`.

**Comment by mlp1802** [comment]
OK now mason is enabled, and rust analyzer deleted, and now it uses the one from .cargo (I ran !which)
No difference though

**Comment by mlp1802** [comment]
Could it be because I use nightly rust?

**Comment by dpetka2001** [comment]
Not sure. I use stable. It seems to be something related with your Rust installation in my opinion. If you do `:!rustc --version` and `:!rust-analyzer --version` from Neovim, does it show the same version for both?

**Comment by mlp1802** [comment]
Yes they are same versions. Could try to downgrade but afraid entire project will crash, but it's probably my last hope. Btw it works on emacs, dianogstics and all, so idk..it's just one of those things.

**Comment by mlp1802** [comment]
cargo cleaned many times and cargo cache -a as well. It's s a mystery

**Comment by dpetka2001** [comment]
Does `:!which rustc` also point to the one in `~/.cargo/bin`?

**Comment by mlp1802** [comment]
yea..and !which cargo also

**Comment by mlp1802** [comment]
Should note that everything worked perfectly until I decided to update plugins..I'm not sure but I think this update brought rustaceanvim with it..

**Comment by dpetka2001** [comment]
It's not a problem with `rustaceanvim` because it works correctly on my end. I would suggest you also try what I suggested in this [post](https://github.com/LazyVim/LazyVim/issues/2808#issuecomment-2015606318).

**Comment by mlp1802** [comment]
I see. I assume you mean 
export NVIM_APPNAME=lazytest ?
then "vim"?
I tried both version but it just starts up with the default config

**Comment by mlp1802** [comment]
Ah wait didnt clone first to lazytest, I bet that is it

**Comment by dpetka2001** [comment]
No don't export anything. Just follow the steps.

**Comment by mlp1802** [comment]
No matter what I does it just starts up with the config in nvim dir. And I just checked google, this is the way to do it. Very strange

**Comment by mlp1802** [comment]
OK can start it with lazy test now, just used "vim" instead of nvim. I had an alias to that, wonder how that makes a difference.

**Comment by dpetka2001** [comment]
You're doing some step wrong. That works 100% and I've done it multiple times when I want to test something with default Lazyvim configuration. I've also suggested it to other ppl who had issues here and everyone was able to make it work. You're missing something.

**Comment by dpetka2001** [comment]
What does `:echo stdpath("config")` show?

**Comment by mlp1802** [comment]
~/.config/nvim
the lazytest now works, and this is the result:
![Screenshot from 2024-03-23 14-35-56](https://github.com/LazyVim/LazyVim/assets/4717892/b50e3115-a245-47ad-b047-c529942aafdc)
![Screenshot from 2024-03-23 14-36-03](https://github.com/LazyVim/LazyVim/assets/4717892/b1aeda4d-bc85-4207-8934-37bd0330f226)

**Comment by dpetka2001** [comment]
It uses mason rust-analyzer maybe? Try to add previous snippet in `~/.config/lazytest/lua/plugins` and uninstall rust-analyzer from Mason like you did before.

**Comment by dpetka2001** [comment]
Wait. What does `:echo stdpath("config")` show?

**Comment by mlp1802** [comment]
It shows "~/.config/lazytest"

**Comment by dpetka2001** [comment]
Ok because previously you wrote it showed `~/.config/nvim` and that was wrong.

**Comment by dpetka2001** [comment]
Did you add the code and uninstalled rust-analyzer from Mason?

**Comment by mlp1802** [comment]
Yes just did, same result

**Comment by dpetka2001** [comment]
Can you try in a new `cargo init` test project?

**Comment by mlp1802** [comment]
OK sec

**Comment by mlp1802** [comment]
![Screenshot from 2024-03-23 15-20-42](https://github.com/LazyVim/LazyVim/assets/4717892/70426c13-f226-4f6c-bd33-bee440f3806c)

**Comment by mlp1802** [comment]
Im using the "lazytest" config of course

**Comment by dpetka2001** [comment]
I can't think of anything else than maybe your Rust installation.

**Comment by dpetka2001** [comment]
I reaaly don't think this is a Lazyvim problem since i also tried the Rust Lazyextra and attached a picture that shows diagnostics like it should.

**Comment by mlp1802** [comment]
Yes that's my conclusion also. But I have no clue at all as to what can be wrong. Could downgrade but who knows then what might happen.

**Comment by mlp1802** [comment]
I'm experimenting with different toolchains now, and will post the result here. Thanks for your help so far, really appreciate it.

**Comment by dpetka2001** [comment]
Really hope you find a solution to this. I don't do Rust myself, so can't help with toolchain related stuff. I was just trying to see if it was a problem with your configuration or LazyVim.

**Comment by mlp1802** [comment]
Yeah I'll leave it be for a sec, am on a tight deadline and boss wouldnt care to hear that I spent all this time on an EDITOR lol (they dont understand editor wars). So probably have to fire up rust rover or something similar dreadful. I truly fear it.

**Comment by OneOfOne** [comment]
Can we reopen this @folke? i'm running into this problem as well.

**Comment by OneOfOne** [comment]
Ok I fixed it, not sure why it happened or how it happened, steps to fix for me:

1. rm -rf ~/.rustup
2. rustup install stable
3. rustup component add rust-analyzer
4. profit

Not i have mason disabled, so it's using my system's rust analyzer.

**Comment by dpetka2001** [comment]
Yes, that's how it should be. `rustaceanvim` doesn't pick up `rust-analyzer` by Mason, so you have to install the component in your toolchain. If you want to keep Mason enabled (to install other things) then you could do in your personal configuration
```lua
return {
  {
    "neovim/nvim-lspconfig",
    opts = {
      servers = {
        rust_analyzer = {
          mason = false,
        },
      },
    },
  },
}
```
The maintainer of `rustaceanvim` has made a [comment regarding Mason](https://github.com/LazyVim/LazyVim/pull/2198#issuecomment-1999475044) among other things mentioned in that comment. The last paragraph of the comment I linked mentions Mason.

**Comment by mlp1802** [comment]
Trying my luck again..right now I dont understand why do we need the nvim-lsp-config  rust section, even if empty, when we use ructaceanvim?
