### ISSUE TITLE
bug: Can not override default keymap for <S-k> or K

### ISSUE THREAD

**Issue by radvil** [LazyVim/LazyVim#281]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0 (Nightly)

### Operating system/version

Linux

### Describe the bug

I was setting this is in my ~/.config/nvim/lua/config/keymaps.lua

```lua
  vim.keymap.set("n", "K", "5k", { desc = "Jump 5 row to top" })
```
But is seems like it's not replacing it. I tried to get hint by this command `verbose nmap K`, I saw this message 
```
n K     /usr/share/nvim/runtime/lua/vim/lsp/buf.lua:40
Last set from Lua n K *5k
Last set from Lua
```
something like that. Also my `vim.keymap.set("i", "<C-i>", "<Space><Esc>i", { desc="Add one space after cursor" })` seems like it doesnt work anymore, unlike my previous config before I migrate it to LazyVim.

PLEASE HELP ME, What did I do wrong ??

### Steps To Reproduce

1. Set keymaps based on above description, located in `$HOME/.config/nvim/lua/config/keymaps.lua`
2. Press "K"
3. That's it, it doesnt work as expected

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/36059968/219397726-1494d7a6-333f-476f-a010-b756b43e9c78.gif)

### Expected Behavior

This should have worked, What am I missing please tell me

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Please use the discussions next time, since this is just a user question.

`K` is an LSP keymap. See [here](https://www.lazyvim.org/plugins/lsp#%EF%B8%8F-customizing-lsp-keymaps) on how to disable it.

About that other, keymap, it just seems wrong to me. LazyVim also doesn't add any keymaps for `<c-i>`

**Comment by radvil** [comment]
I am sorry, I will use discussion next time. I am so new to this github thing

**Comment by radvil** [comment]
Thanks for the reference
