### ISSUE TITLE
bug: Some file types are not displaying icons for neo-tree, but the icons work fine in nvim edit

### ISSUE THREAD

**Issue by tsmith165** [LazyVim/LazyVim#2812]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev-2662+gcfc9fcc

### Operating system/version

Ubuntu 22.04

### Describe the bug

.js / .log / .txt / .svg files are not showing their icons in the neo-tree, but the icons are able to be loaded in the vim editor itself. Is there any special config I need to be making for these file types? I'm not seeing any docs on this. I have DevIcons font installed (tried Jetbrains mono nerd font and Hacker nerd font as well, but didnt see any effect).

Screenshot of nvim not loading the icons:
![image](https://github.com/LazyVim/LazyVim/assets/16846767/bdd7aa24-5bf6-4658-b20e-1764ac728e42)

### Steps To Reproduce

1. Install Ubuntu 22.04
2. Run LazyVim Automated Installer at: https://github.com/tsmith165/lazyvim-ubuntu-installer
3. Open nvim and view neo-tree

### Expected Behavior

.js / .log / .txt / .svg icons loaded in neo-tree

### Repro

```Lua
require("config.lazy")
require("config.neo-tree")
vim.opt.guifont = 'DevIcons:h12'
```

**Comment by lhiamgeek** [comment]
nerd font needed

**Comment by dpetka2001** [comment]
This is a problem with the font you're using and your terminal configuration. Not LazyVim related.

![2024-03-23_12-53](https://github.com/LazyVim/LazyVim/assets/12776461/d84884db-3d65-4a17-a8a9-ab7fe9c6eb57)
