### ISSUE TITLE
bug: Cannot uninstall flash.nvim

### ISSUE THREAD

**Issue by uforek** [LazyVim/LazyVim#2813]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

MacOS 14.4

### Describe the bug

Cannot remove flash.nvim after repeated attempts to remove via the 'Lazy' gui.

### Steps To Reproduce

1. From the 'Lazy' gui, highlight flash.nvim
2. Press 'x' to delete plugin
3. Plugin appears under 'Not Installed'
4. Restart vim, plugin re-installs.

### Expected Behavior

Removal of flash.nvim

**Comment by lhiamgeek** [comment]
you should first disable it then remove, cause it's built in lazyvim

**Comment by lhiamgeek** [comment]
you need to disable it using lazy.nvim config, check [this](https://github.com/folke/lazy.nvim) out
