### ISSUE TITLE
bug: LazyVim always show fzf-native to be cleaned even loaded OK

### ISSUE THREAD

**Issue by xchray** [LazyVim/LazyVim#2815]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

WIN11

### Describe the bug

Since I am using LazyVim on corporate laptop, installing MS make is not an option.  For telescope-fzf-native, I am using a prebuild binary from airtonix/telescope-fzf-native.nvim. I am using url option to re-direct to that repo.  Everything seems to be all right, However, after installation, LazyVim always show fzf under Clean operation. 

![image](https://github.com/LazyVim/LazyVim/assets/81406963/469f0447-2ff1-46ff-b313-d268e9f46ad2)

### Steps To Reproduce

I am using follow config: 
```lua 
  {
    -- "nvim-telescope/telescope-fzf-native.nvim",
    "airtonix/telescope-fzf-native.nvim",
    url = "https://github.com/airtonix/telescope-fzf-native.nvim",
    build = function()
      require("telescope-fzf-native").download_library({
        platform = "windows", -- windows | ubuntu | macos
        arch = "x64", -- x64 | arm
        compiler = "cc", -- windows: cc, unix: gcc | clang
        version = "0.0.2", -- the release name found on our github releases page, defaults to "dev"
      })
    end,
  },
  {
    "telescope.nvim",
    dependencies = {
      "telescope-fzf-native.nvim",
      config = function()
        require("telescope").load_extension("fzf")
      end,
    },
  },
```

### Expected Behavior

Not sure why it is considered to be CLEANed. 

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
That's becasue you don't have make or cmake installed.
You're using a PR, that downloads binaries, so that's not yet part of fzf-native.

You can add enabled=true to your fzf spec to fix it.

Also, do be aware that fzf-native is included in LazyVim by default.
