### ISSUE TITLE
bug: Vue parser crashes neovim on insert

### ISSUE THREAD

**Issue by devpaps** [LazyVim/LazyVim#2819]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev+2671-gdc110cba3

### Operating system/version

Fedora v39

### Describe the bug

When i open up a `.vue` file and hit either `i` or `o` to start edit the file neovim crashes. I'm using the `Nuxt version 2.15.8` but it dosen't matter if i try the newest version of Nuxt. I have not changed anything in Lazyvim, it's totally default.

### Steps To Reproduce

1. Open up a vue file
2. Press `i` or `o` and start typing, i can sometimes add 1-2 characters before neovim closes down completely

### Expected Behavior

Can edit `.vue` files with Lazyvim.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	"folke/tokyonight.nvim",
	"folke/LazyVim",
	{
		-- Highlight, edit, and navigate code
		"nvim-treesitter/nvim-treesitter",
		build = ":TSUpdate",
		event = { "VeryLazy" },
		config = function()
			local config = require("nvim-treesitter.configs")
			config.setup({
				ensure_installed = {
					"bash",
					"c",
					"vue",
					"diff",
					"html",
					"javascript",
					"jsdoc",
					"json",
					"jsonc",
					"lua",
					"luadoc",
					"luap",
					"markdown",
					"markdown_inline",
					"python",
					"query",
					"regex",
					"toml",
					"tsx",
					"typescript",
					"vim",
					"vimdoc",
					"yaml",
				},
				auto_install = true,
				highlight = {
					enable = true,
				},
				indent = {
					enable = true,
				},
				autotag = {
					enable = true,
				},
			})
		end,
	},

	-- add any other plugins here
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here

```

**Comment by folke** [comment]
Whenever Neovim crashes, it's a Neovim bug.

Check the neovim docs on how to get a stacktrace and report it upstream.
