### ISSUE TITLE
bug: high memory usage when operating with buffer

### ISSUE THREAD

**Issue by rakshasha-medhi** [LazyVim/LazyVim#2823]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.4

### Operating system/version

Windows 10

### Describe the bug

Any operation regarding Buffer would make a jump in memory usage from 50MB to 600MB and keep climbing to almost 2GB before I ran out of memory (I got 8GB laptop memory).

Happened multiple times throughout the day. I don't think it's the LSP coz the latest one happened when I'm editing notes.txt

### Steps To Reproduce

1. Open a document (txt file would suffice).
2. Open the buffer explorer
3. It would take 10-15 seconds to load.
4. From there memory usage start creeping up from initially < 50MB to 600MB and then till I ran out of memory around 2GB usage.

The text document I'm editing was 10 lines long.
*Upon further monitoring, before nvim process starts to creep up, Git for Windows appeared for several seconds. Then the git process disappeared and from there neovim.exe start eating the memory.

### Expected Behavior

I expect the buffer explorer to open instantly and memory usage to keep steady between 50-100MB (my normal usage prior to opening the buffer explorer).

I'm on a LazyVim fresh install with Gruvbox theme as the only modification made.

### Repro

*forgot to mention, I have reinstalled LazyVim 3x and the same issue keeps appearing.

**Comment by rakshasha-medhi** [comment]
A screenshot of the Task Manager. 
the memory usage will go through 2GB+ and then I ran out of memory. Note the Git for Windows processes. Memory usage back to normal post force-closed nvim.exe

![image](https://github.com/LazyVim/LazyVim/assets/94270125/3b76b825-990a-4146-a8e0-6ae903c8c0ab)

**Comment by folke** [comment]
What do you mean with the Buffers Explorer?

I can't reproduce this at all. Nobody ever reported something similar, so I'm pretty sure something's messed up with your setup.
