### ISSUE TITLE
bug: LazyGit not working in Windows after latest update (change its color depending on the current colorscheme)

### ISSUE THREAD

**Issue by aaarafat** [LazyVim/LazyVim#2836]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

Windows

### Describe the bug

LazyGit stopped working after the latest update which change it's colors based on the selected colorscheme on windows 
It works fine on linux though

### Steps To Reproduce

Open lazygit inside neovim shows this for a split-second then closes automatically
![image](https://github.com/LazyVim/LazyVim/assets/44725090/5f1c471e-0084-4915-b166-d7eaad510c41)

### Expected Behavior

Lazygit  to work as usual

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
What does `:=vim.env.LG_CONFIG_FILE` show?

**Comment by aaarafat** [comment]
![image](https://github.com/LazyVim/LazyVim/assets/44725090/ffcbbb12-3106-47df-aa12-898d5fdc3e68)
I'm using git bash on windows terminal. However I tried it on CMD and it's working fine. This suggests the issue is with git bash itself.

**Comment by folke** [comment]
I just added some additional error handling, so lazygit should at least start now.

Can you test the latest main branch?

You may have to update your specs to use the dev version.

See here: https://www.lazyvim.org/configuration/lazy.nvim

Let me know what error you get (if any)

**Comment by aaarafat** [comment]
@folke working on the latest main branch 👍
