### ISSUE TITLE
bug: lazygit dimmed background even after exit 

### ISSUE THREAD

**Issue by lkhphuc** [LazyVim/LazyVim#2842]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.5 & nightly

### Operating system/version

MacOS 14.4.1

### Describe the bug

The entire neovim is dimmed after open lazygit floating window, but is not restored and stay dimmed even after quit. Also my incline.nvim window (top right buffer name) is also hidden.
<img width="721" alt="Screenshot 2024-03-27 at 10 06 06" src="https://github.com/LazyVim/LazyVim/assets/12573521/f8131218-25eb-4ab4-bc2f-fd69afef28b6">

<img width="724" alt="Screenshot 2024-03-27 at 10 06 43" src="https://github.com/LazyVim/LazyVim/assets/12573521/9b006568-c779-4bd8-a0e8-011f54565a66">

This only happens with lazygit, not with LazyVim's terminal, i.e 
`map("n", "<C-.>", function() LazyVim.terminal.open(nil, { ft = "", border = "rounded" }) end, {})` 
my own mapping still works fine.

### Steps To Reproduce

1. `<leader>gg`
2. `q`

### Expected Behavior

Color get back to normal

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
      {
      "LazyVim/LazyVim",
      import = "lazyvim.plugins",

    },

}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by lkhphuc** [comment]
Toggle via my own config above `map("n", "<C-.>", function() LazyVim.terminal.open(nil, { ft = "", border = "rounded" }) end, {})` restore original color.
It seems the autocmd `q` just run `<cmd>close<CR>` so it does not toggle the background thing.

**Comment by folke** [comment]
I did fix some issues related to this yesterday (and today), so can you update both lazy.nvim and LazyVim first?

When the problem persists, can you tell me the exact steps, or keymaps that trigger the issue?

lazygit works fine for me...

**Comment by lkhphuc** [comment]
Sorry I must have made a mistake earlier since I couldn't reproduce with my repro.lua above.
Turn out I have an old autocommand that close terminal with exit code 0 and somehow it interfere with the new update.
Thanks you.
