### ISSUE TITLE
bug: Popup windows seem to have dark dimming around them when in transparency mode

### ISSUE THREAD

**Issue by blueberryfudge** [LazyVim/LazyVim#2847]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.5 commit latest

### Operating system/version

MacOS Sonoma 14.4

### Describe the bug

`<leader>l` opens Lazy package manager dimming background window. Same when triggering `<leader>gg` for lazygit.
This was not the case before the update, Lazy package manager opened without dimming in transparent mode, cannot figure out what's wrong.

### Steps To Reproduce

iterm2, latest version:
profile is set to use transparency at 30%.

Theme:

```
return {
  {
    "folke/tokyonight.nvim",
    lazy = false,
    priority = 1000,
    opts = {
      transparent = true,
      styles = {
        floats = "transparent",
        sidebars = "transparent",
      },
      on_colors = function(colors)
        -- colors.fg_gutter = "#5f626d"
        colors.border = "#5f626d"
        -- colors.blue = "#0cf7b8"
        colors.bg_statusline = ""
        --colors.bg_float = ""
        -- colors.cyan = "#0cf7b8"
      end,
      on_highlights = function(hl)
        hl.LineNr = { fg = "#717582" }
        hl.CursorLineNr = { fg = "#0cf7b8" }
        hl.Comment = { fg = "#717582" }
        hl.CursorLine = { bg = "" }
        --hl.Pmenu = { bg = "NONE" }
        --hl.PmenuSel = { bg = "NONE", fg = "NONE" }
      end,
    },
  },
}
```
No other visual settings are re-configured.

Preview Lazy package manager popup window:
<img width="2537" alt="Screenshot 2024-03-27 at 11 54 53" src="https://github.com/LazyVim/LazyVim/assets/160427878/adf5579c-a247-4ffe-ae37-661a0c593231">

Preview lazygit popup window:

<img width="2552" alt="Screenshot 2024-03-27 at 12 03 02" src="https://github.com/LazyVim/LazyVim/assets/160427878/069b9805-82b1-4dff-b052-b183aeb55b53">

### Expected Behavior

Cannot reproduce it other than showcasing how the window used to pop-up other than launching Telescope, which works great.

Preview:
<img width="2552" alt="Screenshot 2024-03-27 at 11 59 40" src="https://github.com/LazyVim/LazyVim/assets/160427878/5b17ec8e-3d3a-4f60-abcf-026cdc4e07d7">

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
You should set in your `/lua/config/lazy.lua`
```lua
  ui = {
    backdrop = 100,
  },
```

**Comment by blueberryfudge** [comment]
Thank you very much @dpetka2001 - worked like magic. Have a lovely day!
