### ISSUE TITLE
feature: ssh key passphrase prompt

### ISSUE THREAD

**Issue by tjstebbing** [LazyVim/LazyVim#2856]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

When I load LazyVim and it tries to fetch plugins from github, it doesn't prompt for a password to unlock my ssh key.

### Describe the solution you'd like

If LazyVim cannot update / clone whatever because the appropriate ssh key is not cached by the ssh_agent, it should prompt the user to unlock their ssh key 

### Describe alternatives you've considered

Currently if I want LazyVim to check for plugin updates on start, I have to ssh github.com manually to unlock my ssh key and cache it in the ssh_agent so that when I THEN start nvim, Lazy can check for udpates.

**Comment by amaanq** [comment]
Lazyvim should not handle this, you might be interested in [Funtoo Keychain](https://www.funtoo.org/Funtoo:Keychain) though
