### ISSUE TITLE
bug: cmp_luasnip is conflicting with gopls

### ISSUE THREAD

**Issue by Skylli202** [LazyVim/LazyVim#2857]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Win11 - WSL  2.0.14.0 - Fedora image

### Describe the bug

Hi,

I love your neovim "distribution". Thanks for awesome work. But I had to disable a few plugins. I used the method explained in the documentation [example](https://www.lazyvim.org/configuration/examples).

```lua
-- disable trouble
{ "folke/trouble.nvim", enabled = false },
```
> Please find here my [lua/plugins/disabled.lua](https://github.com/Skylli202/LazyVim/blob/main/lua/plugins/disabled.lua)

I recently re-enabled them (https://github.com/Skylli202/LazyVim/commit/6955999a05d8fabdb5553b472869024bb0bc2902) and instantly noticed that my LSP suggestion for Go were off. Here is a before and an after.

_Before:_
<img width="400" alt="WindowsTerminal_jm7z0EOihf" src="https://github.com/LazyVim/LazyVim/assets/38432216/be921241-5d6f-406b-990b-c97fc95747c9">

_After:_
<img width="434" alt="WindowsTerminal_BNFLGUx6Sv" src="https://github.com/LazyVim/LazyVim/assets/38432216/ced32210-9fef-4227-b8cb-3f31ac8e742b">

See, not at all the same suggestion. On the _before_ accepting those suggestion does the import and all those nice things LSP does for us. On the _after_, nothing works, just... snippet.

Please find below the `:LspInfo`.
_Before_:
<img width="1010" alt="WindowsTerminal_SRtzcQNBsz" src="https://github.com/LazyVim/LazyVim/assets/38432216/46fb7729-6f66-40fe-8f53-431d9cbf3da6">

_After_:
<img width="1053" alt="WindowsTerminal_VTMYTTSD1h" src="https://github.com/LazyVim/LazyVim/assets/38432216/43a76953-6a4c-47b1-9d41-83c2411dcad0">

### Steps To Reproduce

1. `git clone https://github.com/LazyVim/starter ~/.config/nvim.LazyVim`
2. `cd`
3. `mkdir foo`
4. `cd foo`
5. `go mod init foo`
6. `touch main.go`
7. `NVIM_APPNAME=nvim.LazyVim nvim .`
8. `:LazyExtras`
9. Enable `lang.go`
10. `:q`
7. `NVIM_APPNAME=nvim.LazyVim nvim .` 
12. start editing `main.go`
```go
package main

func main() {

}
```
13. Start typing `fmt.Println` the completion should be just like my _after_. Only snippet.
14. Disable `cmp_luasnip`, create `disable.lua` at `~/.config/nvim.LazyVim/lua/plugins/disable.lua` and put the following:
```lua
return {
	{ "saadparwaiz1/cmp_luasnip", enabled = false }
}
```
15. Reopen `main.go`
16. Proceed to start typing `fmt.Println` and see the Lsp kicks in!

### Expected Behavior

I prefer Lsp over snippet. I feel like snippet is just like those LLM that hallucinate. Maybe having both is the correct/expected behavior?

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
Can't reproduce. Please try a fresh LazyVim starter template. Screencast following

[Screencast 2024-03-28 11:28:20.webm](https://github.com/LazyVim/LazyVim/assets/12776461/9d428c43-32cf-4484-af5c-a95ab288d2b6)

**Comment by Skylli202** [comment]
Hmmm weird, indeed.
I literally did the reproduce steps on my ends with a fresh starter template (step 1).

I'll try again, but on your reproduction. It is weird that you do not have any snippet enabled, or do you and I did not see them?

**Comment by dpetka2001** [comment]
I had only default LazyVim settings that come with the default installation. Didn't change anything. Just enabled the Go LazyExtra. You can see everything I did in the video. I didn't do anything more or less.

**Comment by Skylli202** [comment]
Yeah, I can tell, just like me when I did it alongside writing the step to reproduce.

**Comment by dpetka2001** [comment]
I'm getting both snippets and auto-completion from LSP 

![2024-03-28_19-41](https://github.com/LazyVim/LazyVim/assets/12776461/5c60679a-e696-4934-ab23-327473815232)

![2024-03-28_19-41_1](https://github.com/LazyVim/LazyVim/assets/12776461/3560c551-8607-43bf-b560-f668e8304e8f)

**Comment by Skylli202** [comment]
I did reproduce the issue.

Here is a video in the same style as yours.

https://github.com/LazyVim/LazyVim/assets/38432216/2a68f8ae-9300-4a87-814b-ce92cbc43efd

**Comment by Skylli202** [comment]
Ok so, I carefully compared your video and mine. And I came across something really strange. It appears that the issue is reproducible if you `git clone` the starter using SSH, but not if you use HTTP.


https://github.com/LazyVim/LazyVim/assets/38432216/426efb68-38c6-490f-961c-a71a7b3c1e32

**Comment by dpetka2001** [comment]
Never heard of this before. However, this does confirm that it's not a LazyVim bug. Maybe if you clone via ssh, there's a chance not all files from LazyVim repo are downloaded? No idea. But this is definitely out of LazyVim's control.
