### ISSUE TITLE
bug: Lazygit using wrong colorscheme

### ISSUE THREAD

**Issue by SooOverpowered** [LazyVim/LazyVim#2867]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

MacOS 14.4.1

### Describe the bug

Lazygit inside nvim ignores the colorscheme defined in `.config/lazygit/config.yml`
![image](https://github.com/LazyVim/LazyVim/assets/49089778/c4db6d6a-2fa4-43fd-a484-edf4f9a97875)

### Steps To Reproduce

1. Define a custom colorscheme for lazygit inside the config path (in my case I use catpuccin mocha theme)
2. Confirm theme working inside terminal
3. Launch Neovim and open Lazygit inside
4. Lazygit has the wrong colorscheme

### Expected Behavior

Lazygit inside neovim should have the same colorscheme as outside of neovim

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  "catppuccin/nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("catppuccin-mocha")
-- add anything else here
```

**Comment by dpetka2001** [comment]
Lazygit inside LazyVim now has the same colorscheme as the one used by LazyVim. See [here](https://github.com/LazyVim/LazyVim/blob/cfbd3582736286433ee5532e1ea3a8d05a1e2649/lua/lazyvim/config/options.lua#L15-L20). You can disable this behavior by setting `vim.g.lazygit_config = false`.

**Comment by SooOverpowered** [comment]
@dpetka2001 thanks, I got it working now

**Comment by adrien-barret** [comment]
@SooOverpowered  where did you put the config line? tried into lua/config/options.lua but doesn't seem to load correctly
