### ISSUE TITLE
bug: changing neo-tree config

### ISSUE THREAD

**Issue by rwijtvliet** [LazyVim/LazyVim#2889]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.2

### Operating system/version

ubuntu

### Describe the bug

Not sure if this is the correct location for this issue, but here it goes.

I am trying to redo my neovim setup, taking lazyvim as the starting point. Now, I use htns for navigation (dvorak) so I want to disable/remap any plugin shortcuts that use those keys.

To that end, I added a `neo-tree.lua` file in the `plugins` folder, with the following contents:

```
return {
  "nvim-neo-tree/neo-tree.nvim",
  opts = {
    window = {
      mappings = {
        ["<A-h>"] = "prev_source",
        ["<A-s>"] = "next_source",
        ["l"] = false,
        ["s"] = "child_or_open",
        ["n"] = "",
        ["t"] = false,
        ["<"] = false,
        [">"] = false,
        ["_"] = "open_tabnew",
        ["|"] = "open_vsplit",
        ["\\"] = "open_split",
      },
    },
    filesystem = { filtered_items = { visible = true } },
  },
}
```

This does indeed work; e.g., `t` now moves up and does not do the default action (open in new tab).

(I tried using the `keys` key, as described [here](http://www.lazyvim.org/configuration/plugins#%EF%B8%8F-adding--disabling-plugin-keymaps), but apparently neotree does not use that convention.)

**However**, the help no longer works. Pressing `?` gives an error message. ("Error executing lua" in `~/.local/share/nvim/lazy/...`).

Any ideas on why this is? 

### Steps To Reproduce

1. fresh lazyvim install
2. add file in `.../lua/plugins/` folder with contents above
3. restart neovim
4. control-e to  go to neotree window
5. press question mark to see keymap info

### Expected Behavior

the popup window with the keymaps for the neotree context is shown.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by jyuan0** [comment]
I don't know if this will fix the help popup, but the [neo-tree docs](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/16d1b194376bf1fc2acd89ccb3c29ba8315bfcea/doc/neo-tree.txt#L467) say you should map to `"none"` or `"noop"` to remove a default mapping.

**Comment by rwijtvliet** [comment]
Ah, thanks for that! Unfortunately, that didn't fix it...

```
E5108: Error executing lua: ...ud/.local/share/nvim/lazy/nui.nvim/lua/nui/line/init.lua:22: attempt to index local 'block' (a nil value)
stack traceback:
	...ud/.local/share/nvim/lazy/nui.nvim/lua/nui/line/init.lua:22: in function 'append'
	.../lazy/neo-tree.nvim/lua/neo-tree/sources/common/help.lua:62: in function 'show'
	...y/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:882: in function <...y/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:879>
```

But do let me know if I should ask neo-tree devs directly

**Comment by dpetka2001** [comment]
```lua
return {
  "nvim-neo-tree/neo-tree.nvim",
  opts = {
    window = {
      mappings = {
        ["<A-h>"] = "prev_source",
        ["<A-s>"] = "next_source",
        ["l"] = false,
        ["s"] = "",
        ["n"] = "",
        ["t"] = false,
        ["<"] = false,
        [">"] = false,
        ["_"] = "open_tabnew",
        ["|"] = "open_vsplit",
        ["\\"] = "open_split",
      },
    },
    filesystem = { filtered_items = { visible = true } },
  },
}
```
This works for me. I removed `child_or_open` because it wasn't a valid command. Also, this is not a LazyVim bug, but a user configuration issue, since the default settings work out of the box. It would be better if you create a Discussion in the future for similar problems.

**Comment by rwijtvliet** [comment]
Ok, many thanks for looking into this. I'll create a discussion next time!
