### ISSUE TITLE
bug: dot file type detection not work when opening directly

### ISSUE THREAD

**Issue by MoetaYuko** [LazyVim/LazyVim#2891]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.5

### Operating system/version

Arch

### Describe the bug

With the `lazyvim.plugins.extras.util.dot` extra, dotfile types aren't detected as specified via `vim.filetype.add` when opening the file directly. However, it works if launching nvim first and then using `:e` to open the file. I guess the lazy loading trigger needs to be tweaked.

### Steps To Reproduce

This doesn't work:
1. `nvim ~/.config/hypr/hyprland.conf`
2. `set ft` returns `filetype=conf`

This works:
1. `nvim`
2. `:e  ~/.config/hypr/hyprland.conf`
3. `set ft` returns `filetype=hyprlang`

### Expected Behavior

`set ft` returns `filetype=hyprlang` in the first case above.

**Comment by dotfrag** [comment]
Relates to https://github.com/LazyVim/LazyVim/issues/1838.

**Comment by MoetaYuko** [comment]
> Relates to #1838.

Indeed. Besides, `:filetype detect` after directly opening the file switches to the expected ft.

**Comment by dpetka2001** [comment]
I've switched `nvim-treesitter` to 
```lua
    event = function()
      return { "BufReadPost", "BufNewFile" }
    end,
```
 in my personal config to overcome this problem. I believe Treesitter is one of the few plugins that doesn't play well with `LazyFile` in my opinion. Maybe there's a better solution than this, but I don't understand that well what is going on in the `load` function of `util.plugin`.

**Comment by dotfrag** [comment]
That worked, thanks @dpetka2001! I'll keep an eye out in case someone knows a better solution.

**Comment by dpetka2001** [comment]
If the part about `vim.filetype.add` gets moved before the start of the `return`'ed specs, it will still work without having to change the `event` for `nvim-treesitter`. Still, not sure if that's the best solution. Hopefully, maintainer can shed some light on what the more correct approach should be.
