### ISSUE TITLE
bug: Could not find which plugin provides the functionality.

### ISSUE THREAD

**Issue by arafune** [LazyVim/LazyVim#2892]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

MacOS 14.4.1

### Describe the bug

Exactly speaking, I know this is not a bug, but I feel this is a sort of a lack in the documentation problem.
<img width="1393" alt="スクリーンショット 2024-03-31 17 18 17" src="https://github.com/LazyVim/LazyVim/assets/6754804/464d5c0b-e221-45b9-bd14-181d175cf33b">

When I described the class/function with long lines, as in the attached file, the top part indicates which class/function corresponds to the current cursor.  I would simply like to turn this feature off, but I don't know which plugin provides this functionality. Could you let me know how to do?

### Steps To Reproduce

Just edit the class with long lines in the python file.

### Expected Behavior

Enable on/off.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
The plugin is `nvim-treesitter/nvim-treesitter-context`. There is a keymap `<leader>ut` to toggle it on/off during your Neovim session or just disable the plugin permanently if you don't want such behavior.
