### ISSUE TITLE
feature: allow disabling Trouble V3 Error messages

### ISSUE THREAD

**Issue by TxHawks** [LazyVim/LazyVim#2895]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

I want to use the Trouble v3 extra, but still prefer Outline for Trouble's document symbols (mostly for the out of the box support for JSX tags).

Functionally it all seems to work just fine, but I get an error message because of this:

https://github.com/LazyVim/LazyVim/blob/97480dc5d2dbb717b45a351e0b04835f138a9094/lua/lazyvim/plugins/extras/editor/trouble-v3.lua#L3-L13

### Describe the solution you'd like

Warning _every_ time seems a bit intrusive, and I think there should be an option to disable the warning.

### Describe alternatives you've considered

Showing the warning just once or once in a while would also be okay, though I think an option to explicitly disable it is better.

**Comment by dpetka2001** [comment]
You can use
```lua
  {
    "noice.nvim",
    opts = function(_, opts)
      table.insert(opts.routes, {
        filter = {
          event = "notify",
          find = "Trouble v3",
        },
        opts = { skip = true },
      })
    end,
  },
```
in your personal configuration to skip these messages. However, I'm not sure if there's a conflict between `Trouble v3` and `Outline`, so if you want to use both of them together you do that at your own risk.

**Comment by TxHawks** [comment]
Yeah, that's what I did, but I still think it's pretty intrusive and unintuitive and should be behind an option.

If there is some conflict between them, I didn't run into it yet.

Thanks for helping anyway

**Comment by Ian2020** [comment]
I saw this error message even with troublev3 disabled, when I was trying to add editor.aerial.
