### ISSUE TITLE
Snippet's icons are not shown correctly

### ISSUE THREAD

**Issue by michael-burakov** [LazyVim/LazyVim#2898]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

Arch Linux

### Describe the bug

Firstly, I must point out that I'm very new to nvim and lua. I have recently started with LazyVim as it looks awesome. Great job!

Watched recommended Youtube video and went through manuals on [http://www.lazyvim.org/](LazyVim). So I setup and configured everything as I wanted but one little detail. For some reason I cannot get icon shown correctly **only** in front of _Snippet_ in pop-up window of `vnim-cmp` plugin. The text for _Snippet_ look overshadowed as well, not sure if this is related. All other icons seem to be shown correctly.

![lazyvim-snippet-icons](https://github.com/LazyVim/LazyVim/assets/78799798/c491834f-f005-49b4-b9ec-801f03ed97e5)

In the screenshot above, it looks like `bashls` language server is loaded correctly. And it looks like the snippet comes from it. However, it looks like the icon could not be loaded.

My terminal is Alacritty 0.13.2 (bb8ea18e) where I've configured JetBrainsMono Nerd Font (v3.1.1).

### Steps To Reproduce

1. Get started template from github.
2. Enable "Dot Files" in `:LazyExtras`
3. Create a new bash script and type `if` to get if-related snippets.

### Expected Behavior

I've looked through a lot of pages, and I believe I've seen a correct icon for snippets somewhere. I don't remember in what context exactly and I couldn't find a solution for my problem anyway there.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
This is default behavior. The icon is what LazyVim actually sets for snippets and the text looks overshadowed because the highlight group `CmpItemKindSnippet` is linked by the colorscheme to `Conceal` by default.

**Comment by michael-burakov** [comment]
Ok, thank you for the fast response.
