### ISSUE TITLE
feature: To toggle the termial and run the background task like in Zellij

### ISSUE THREAD

**Issue by Notnobcoder** [LazyVim/LazyVim#2899]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

"When opening the terminal with <leader> ft, it would be convenient if we could toggle it to run background applications such as React projects. I currently use Zellij for this purpose, and having this feature integrated would greatly enhance the user experience."

### Describe the solution you'd like

"Having a floating window feature like in Zellij would be excellent."

### Describe alternatives you've considered

"like a floating terminal in vs code"

**Comment by dpetka2001** [comment]
Doesn't `<C-/>` do what you want? It opens a floating terminal. And you can use the same keymap for showing/hiding the terminal.

**Comment by Notnobcoder** [comment]
It's not functioning on my Arch Linux machine at the moment.

**Comment by dpetka2001** [comment]
Try pressing `<C-_>`.

**Comment by Notnobcoder** [comment]
Not working Actually, it's minimizing the font size in the terminal.

**Comment by Notnobcoder** [comment]
I've seen the issue #193 as well. It seems to be referencing the installation of a custom plugin. I've also attempted the commands provided in the issue, but unfortunately, the problem persists.

**Comment by dpetka2001** [comment]
This is something related to your terminal emulator. What terminal are you using? Are you inside tmux? Type the following in `insert` mode inside Neovim `<C-v><C-/>`. What characters are printed out?

**Comment by Notnobcoder** [comment]
No just using kitty .

**Comment by dpetka2001** [comment]
> Type the following in insert mode inside Neovim <C-v><C-/>. What characters are printed out?

You didn't answer this.

**Comment by Notnobcoder** [comment]
okay so its working.

**Comment by surmish** [comment]
> okay so its working.

Can you close this?
