### ISSUE TITLE
bug: when in insert mode and i press tab i got this error in below screenshot

### ISSUE THREAD

**Issue by bkash775** [LazyVim/LazyVim#2911]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.4

### Operating system/version

Windows 11

### Describe the bug

![image](https://github.com/LazyVim/LazyVim/assets/35194241/f738bb13-9c0b-40b7-ab81-b36f4cf8299d)

In my windows 11 when i try to code using nvim i have lazyvim plugin, so when try to type something and if i press tab it doesnot let me give tab space but instead throw and error message popup as in the screen shot.

### Steps To Reproduce

idk what steps to reproduce but i thing u might have got it.

### Expected Behavior

can u please let me know what is the issue on my lazyvim in windows 11.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
You have enabled the native snippets Extra in Neovim 0.9.4, but native snippets are only available in 0.10+ if I'm not mistaken.
