### ISSUE TITLE
feature: use vtsls instead of tsserver in the typescript extra

### ISSUE THREAD

**Issue by OneOfOne** [LazyVim/LazyVim#2918]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

This a wrapper around the official VSCode extension.

### Describe the solution you'd like

replacing tsserver with vtsls is a drop-in replacement, no configuration is needed.

### Describe alternatives you've considered

n/a

**Comment by dpetka2001** [comment]
Related #2858

**Comment by rubiin** [comment]
how about typescript-tools. I think this is more performant when there as more files

**Comment by folke** [comment]
Closed by https://github.com/LazyVim/LazyVim/commit/fba06ce9f522b91be8a342f9c028948c2733132d

**Comment by jcfrancisco** [comment]
Just adding one data point: for my large TypeScript codebase, this change made the plugin's performance worse for me. After making changes, it would take a much longer time (seconds to minutes) for the changes to be processed by the TS server.

I ended up reverting to the [last version of the extra](https://github.com/LazyVim/LazyVim/blob/54d7cea30567577bf926765e9282d7736e951941/lua/lazyvim/plugins/extras/lang/typescript.lua) prior to the switch.
