### ISSUE TITLE
bug: vim-illuminate autocmd causes an error in Rust files when :e is called (to refresh the buffer)

### ISSUE THREAD

**Issue by amaanq** [LazyVim/LazyVim#292]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0-dev-975+gd34c64e34

### Operating system/version

Arch Linux 6.2.0-rc8

### Describe the bug

Error executing lua callback: /usr/local/share/nvim/runtime/filetype.lua:21: Error executing lua: /usr/local/share/nvim/runtime/filetype.lua:22: BufReadPost Autocommands for "*"..FileType Autocommands for "*"..function <SNR>1_LoadFTPlugin, line 2: Vim(nunmap):E31: No such mapping
stack traceback:
	[C]: in function 'nvim_cmd'
	/usr/local/share/nvim/runtime/filetype.lua:22: in function </usr/local/share/nvim/runtime/filetype.lua:21>
	[C]: in function 'nvim_buf_call'
	/usr/local/share/nvim/runtime/filetype.lua:21: in function </usr/local/share/nvim/runtime/filetype.lua:10>
stack traceback:
	[C]: in function 'nvim_buf_call'
	/usr/local/share/nvim/runtime/filetype.lua:21: in function </usr/local/share/nvim/runtime/filetype.lua:10>
	
Commenting out <https://github.com/LazyVim/LazyVim/blob/ba7942b80bba69592bb1b14b91bff6d356d9151e/lua/lazyvim/plugins/editor.lua#L264-L270> removes this bug.

### Steps To Reproduce

1. Use LazyVim
2. Might need rust-analyzer LSP, could happen without it but I haven't checked
3. Open a Rust file in a Rust project and run :e

### Expected Behavior

No error, and highlighting doesn't go away (error happens before anything can redraw I guess, like treesitter)

### Repro

Mentioned in steps

**Comment by amaanq** [comment]
I assumed the linked commit had fixed it, but I can confirm it is still present with the exact same error output

**Comment by folke** [comment]
It is fixed. I just didn't create a new release yet. If you want to follow HEAD changes for LazyVim and/or lazy.nvim, see https://www.lazyvim.org/configuration/lazy.nvim
