### ISSUE TITLE
bug: Lazyrc warning is thrown even though it is the last spec loaded in config.lazy

### ISSUE THREAD

**Issue by vinicius507** [LazyVim/LazyVim#2938]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.4

### Operating system/version

Linux desktop 6.1.82 #1-NixOS SMP PREEMPT_DYNAMIC Fri Mar 15 18:27:50 UTC 2024 x86_64 GNU/Linux

### Describe the bug

When using a `.lazy.lua` file, I always get the following warning:

```
WARN The `lazyrc` extra must be the last plugin spec added to **lazy.nvim**. 

Add `{ import = 'lazyvim.plugins.extras.lazyrc' }` to file `config.lazy`. 
Do not use the `LazyExtras` command. 
```

Even though I have it as the last plugin spec added to lazy.nvim.

### Steps To Reproduce

1. Use the following `config.lazy`:
```lua
-- lua/config/lazy.lua

local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"

if not (vim.uv or vim.loop).fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end

vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

require("lazy").setup({
	spec = {
		{ "LazyVim/LazyVim", import = "lazyvim.plugins" },
		{ import = "lazyvim.plugins.extras.coding.copilot" },
		{ import = "lazyvim.plugins.extras.dap.core" },
		{ import = "lazyvim.plugins.extras.editor.harpoon2" },
		{ import = "lazyvim.plugins.extras.editor.navic" },
		{ import = "lazyvim.plugins.extras.lang.docker" },
		{ import = "lazyvim.plugins.extras.lang.json" },
		{ import = "lazyvim.plugins.extras.lang.markdown" },
		{ import = "lazyvim.plugins.extras.lang.yaml" },
		{ import = "lazyvim.plugins.extras.vscode" },
		{ import = "plugins" },
		-- LazyRc must be the last import
		{ import = "lazyvim.plugins.extras.lazyrc" },
	},
	lazy_nvim = {
		performance = {
			rtp = {
				reset = false,
				disabled_plugins = {
					"gzip",
					"matchit",
					"matchparen",
					"netrwPlugin",
					"tarPlugin",
					"tohtml",
					"tutor",
					"zipPlugin",
				},
			},
			reset_packpath = false,
		},
	},
})
```

2. And the following `.lazy.lua`:

```lua
vim.filetype.add({
	extension = {
		mdx = "markdown",
	},
})

return {
	{ import = "lazyvim.plugins.extras.lang.tailwind" },
	{ import = "lazyvim.plugins.extras.lang.typescript" },
	{ import = "lazyvim.plugins.extras.formatting.prettier" },
	{ import = "lazyvim.plugins.extras.linting.eslint" },
}
```

### Expected Behavior

No warning at all

**Comment by dpetka2001** [comment]
That's because you import other extras in `.lazy.lua`, thus `lazyrc` spec is not the last one any more. It's perfectly normal behavior.

**Comment by dpetka2001** [comment]
The problem is that every spec gets assigned an id by `lazy.nvim` depending on the order it gets loaded/imported. The check is if the lazyrc id is the last one in `lazy.nvim`. If it's not, then you get the warning. This is just to avoid that the spec you specify in Lazyrc gets overwritten by other specs. If you're confident nothing gets overwritten, then you can simply ignore the warning. But the warning you get is not a bug, rather expected behavior.

**Comment by vinicius507** [comment]
> The thing is that every spec gets assigned an id by `lazy.nvim` depending on the order it gets loaded/imported. The check is if the lazyrc id is the last one in `lazy.nvim`. If it's not, then you get the warning. This is just to avoid that the spec you specify in Lazyrc doesn't get overwritten by other specs. If you're confident nothing gets overwritten, then you can simply ignore the warning. But the warning you get is not a bug, rather expected behavior.

Good to know, thanks a ton 🙏
