### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by Sarctiann** [LazyVim/LazyVim#2939]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

 macOS 14.4.1

### Describe the bug

The keymaps to show ignored or hidden files are harcoded to `<a-...>` *(alt) key* which is not transparent for Mac users
![image](https://github.com/LazyVim/LazyVim/assets/49457785/81625c9a-52d9-44ab-815a-ca0d1ab231bb)

### Steps To Reproduce

1. got to a directory with hidden and ignored files
2. search for a file (<leader>ff or <leader>fF or <leader><leader>)
3. try to find a hidden or a ignored file by pressing [option]-i or[option]-h

### Expected Behavior

hidden and/or ignored files should be shown

This can be fixed by changing `<a-` with `<M-`

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
There are other keys throughout LazyVim as you can see [here](https://github.com/search?q=repo%3ALazyVim%2FLazyVim%20%3Ca-&type=code) that use `<A->` instead of `<M->`. Do they work correctly on Mac. I don't have Mac, so I can't test. I'm preparing a PR to change these keymaps to `<M->` instead. Could you verify please, so I know if I should change all instances or only the internal Telescope mappings?

**Comment by Sarctiann** [comment]
<A-> works well, since in my terminal emulators (warp and alacritty) I have "the left key option as goal" configured, a fairly standard option in all Mac terminals.

But it seems <a-> (lower) doesn't behave the same way, I guess the best solution would be to use <A-> (upper) for every case

**Comment by dpetka2001** [comment]
Could you please try the following in a file in your `~/.config/nvim/lua/plugins/` directory?
```lua
return {
	  {
    "dpetka2001/LazyVim",
    branch = "fix/option-keys-mac",
  },
}
```
And then open Lazy UI and update LazyVim. Then restart and verify if the keymaps work as you expect.

**Comment by Sarctiann** [comment]
Sorry for the delay.

Did you merge the fix?
I commented out the tweak that I made for those telescope keymaps, and restarted neovim (to be able to reproduce the issue) but it's just working as expected

**Comment by dpetka2001** [comment]
I'm just a simple user like you. Only the maintainer is able to merge PRs. I haven't even made the PR yet. I asked you to test the branch from the forked LazyVim repo that I have in order to test the keymaps. Is that not needed any more? Everything works as expected at your end?

**Comment by Sarctiann** [comment]
right now, is working... IDK if there is some cache out there... but I'm currently not able to restart all my tmux sessions since I'm working on three different projects :|

For now, I will leave the config as it is from the factory. Then if I have the same behavior I will use your branch, and let you now if that solves the issue. Thank you!

**Comment by folke** [comment]
`<A` should work perfectly fine on mac with the option key. Whatever wasnt working for you before, is not due to this.

**Comment by Sarctiann** [comment]
> `<A` should work perfectly fine on mac with the option key. Whatever wasnt working for you before, is not due to this.

Yes, although the problem is related to the `<a-` (lower) thought

**Comment by Sarctiann** [comment]
I just discovered that after kill all my tmux sessions and restarting alacritty. I'm able to reproduce the issue.

the missing file that I'm trying to find is hidden (because starts with `.`) and is ignored by git. So inside the Telescope's picker, I wrote the name ".env.local" but I only got the file ".env.local-example" (that is hidden, but is not ignored by git)
Then I press Option+i but nothing happens

So I added this configuration:

```lua
return {
  "nvim-telescope/telescope.nvim",
  opts = function()
    local actions = require("telescope.actions")

    local open_with_trouble = function(...)
      return require("trouble.providers.telescope").open_with_trouble(...)
    end
    local open_selected_with_trouble = function(...)
      return require("trouble.providers.telescope").open_selected_with_trouble(...)
    end
    local find_files_no_ignore = function()
      local action_state = require("telescope.actions.state")
      local line = action_state.get_current_line()
      LazyVim.telescope("find_files", { no_ignore = true, default_text = line })()
    end
    local find_files_with_hidden = function()
      local action_state = require("telescope.actions.state")
      local line = action_state.get_current_line()
      LazyVim.telescope("find_files", { hidden = true, default_text = line })()
    end

    return {
      defaults = {
        prompt_prefix = " ",
        selection_caret = " ",
        -- open files in the first window that is an actual file.
        -- use the current window if no other window is available.
        get_selection_window = function()
          local wins = vim.api.nvim_list_wins()
          table.insert(wins, 1, vim.api.nvim_get_current_win())
          for _, win in ipairs(wins) do
            local buf = vim.api.nvim_win_get_buf(win)
            if vim.bo[buf].buftype == "" then
              return win
            end
          end
          return 0
        end,
        mappings = {
          i = {
            ["<c-t>"] = open_with_trouble,
            ["<M-t>"] = open_selected_with_trouble,
            ["<M-i>"] = find_files_no_ignore,
            ["<M-h>"] = find_files_with_hidden,
            ["<C-Down>"] = actions.cycle_history_next,
            ["<C-Up>"] = actions.cycle_history_prev,
            ["<C-f>"] = actions.preview_scrolling_down,
            ["<C-b>"] = actions.preview_scrolling_up,
          },
          n = {
            ["q"] = actions.close,
          },
        },
        -- configure to use ripgrep
        vimgrep_arguments = {
          "rg",
          "-u",
          "--follow", -- Follow symbolic links
          "--hidden", -- Search for hidden files
          "--no-heading", -- Don't group matches by each file
          "--with-filename", -- Print the file path with the matched lines
          "--line-number", -- Show line numbers
          "--column", -- Show column numbers
          "--smart-case", -- Smart case search

          -- Exclude some patterns from search
          "--glob=!**/.git/*",
          "--glob=!**/.idea/*",
          "--glob=!**/.vscode/*",
          "--glob=!**/build/*",
          "--glob=!**/dist/*",
          "--glob=!**/yarn.lock",
          "--glob=!**/package-lock.json",
        },
      },
      pickers = {
        find_files = {
          hidden = true,
          -- needed to exclude some files & dirs from general search
          -- when not included or specified in .gitignore
          find_command = {
            "rg",
            "-u",
            "--files",
            "--hidden",
            "--glob=!**/.git/*",
            "--glob=!**/.idea/*",
            "--glob=!**/.vscode/*",
            "--glob=!**/build/*",
            "--glob=!**/dist/*",
            "--glob=!**/yarn.lock",
            "--glob=!**/package-lock.json",
          },
        },
      },
    }
  end,
}
```

(This is not default)
```lua
 mappings = {
          i = {
            ["<c-t>"] = open_with_trouble,
            ["<M-t>"] = open_selected_with_trouble,
            ["<M-i>"] = find_files_no_ignore,
            ["<M-h>"] = find_files_with_hidden,
            ["<C-Down>"] = actions.cycle_history_next,
            ["<C-Up>"] = actions.cycle_history_prev,
            ["<C-f>"] = actions.preview_scrolling_down,
            ["<C-b>"] = actions.preview_scrolling_up,
          },
          n = {
            ["q"] = actions.close,
          },
        },
        -- configure to use ripgrep
        vimgrep_arguments = {
          "rg",
          "-u",
          "--follow", -- Follow symbolic links
          "--hidden", -- Search for hidden files
          "--no-heading", -- Don't group matches by each file
          "--with-filename", -- Print the file path with the matched lines
          "--line-number", -- Show line numbers
          "--column", -- Show column numbers
          "--smart-case", -- Smart case search

          -- Exclude some patterns from search
          "--glob=!**/.git/*",
          "--glob=!**/.idea/*",
          "--glob=!**/.vscode/*",
          "--glob=!**/build/*",
          "--glob=!**/dist/*",
          "--glob=!**/yarn.lock",
          "--glob=!**/package-lock.json",
        },
      },
      pickers = {
        find_files = {
          hidden = true,
          -- needed to exclude some files & dirs from general search
          -- when not included or specified in .gitignore
          find_command = {
            "rg",
            "-u",
            "--files",
            "--hidden",
            "--glob=!**/.git/*",
            "--glob=!**/.idea/*",
            "--glob=!**/.vscode/*",
            "--glob=!**/build/*",
            "--glob=!**/dist/*",
            "--glob=!**/yarn.lock",
            "--glob=!**/package-lock.json",
          },
        },
      },
```

And after restart tmux and alacritty... I can do the same as before, but when I press Option+i Now I see both files ".env.local" and ".env.local-example"

**Comment by dpetka2001** [comment]
My branch only changed the keys from `<a-i>` to `<M-i>`. If that doesn't fix your issue then it's probably an issue with your configuration. You should test with a LazyVim default installation instead of your personal configuration and compare the behavior.

**Comment by Sarctiann** [comment]
I tested the 3 ways.
My configuration is working!

But this may related to the other arguments that I added
```lua
vimgrep_arguments = {
    "rg",
    "-u",
    "--follow", -- Follow symbolic links
    "--hidden", -- Search for hidden files
    "--no-heading", -- Don't group matches by each file
    "--with-filename", -- Print the file path with the matched lines
    "--line-number", -- Show line numbers
    "--column", -- Show column numbers
    "--smart-case", -- Smart case search

    -- Exclude some patterns from search
    "--glob=!**/.git/*",
    "--glob=!**/.idea/*",
    "--glob=!**/.vscode/*",
    "--glob=!**/build/*",
    "--glob=!**/dist/*",
    "--glob=!**/yarn.lock",
    "--glob=!**/package-lock.json",
  },
},
pickers = {
  find_files = {
    hidden = true,
    -- needed to exclude some files & dirs from general search
    -- when not included or specified in .gitignore
    find_command = {
      "rg",
      "-u",
      "--files",
      "--hidden",
      "--glob=!**/.git/*",
      "--glob=!**/.idea/*",
      "--glob=!**/.vscode/*",
      "--glob=!**/build/*",
      "--glob=!**/dist/*",
      "--glob=!**/yarn.lock",
      "--glob=!**/package-lock.json",
    },
  },
},
```

**Comment by Sarctiann** [comment]
for the third time,
* I already tried the default settings (it doesn't work)
* I already tried your fork version (it doesn't work)
* and I went back to my settings (it works)

I also think that the problem is not the keymap but it was solved by the arguments that I passed to `vimgrep_arguments` and `pickers`

**Comment by folke** [comment]
the telescope pickers honor your gitignore, so not seeing that file is to be expected.

**Comment by Sarctiann** [comment]
> the telescope pickers honor your gitignore, so not seeing that file is to be expected.

I understand your point, but I disagree, since this is a configuration file, that contains secrets so is ignored to not be tracked by git, but sometimes (more often than I would like) I have to modify it. It will be useful to be able to search for it, the same way I look for every other file.

But I guess we are getting into a "personal opinion land"
I will use my config.

A possible solution could be to provide a more exposed configuration for the Telescope so users can decide on that kind of detail.

Anyway, in some way it does, since I was able to write this config, so thank you for your time, Lazyvim is awesome.

**Comment by folke** [comment]
> I understand your point, but I disagree

This is not about having an opinion over some behavior.
I was just stating that this is how ripgrep works by default.
If you don't like the defaults, change it to your liking like you have done.
