### ISSUE TITLE
bug:  the default keybinding for "s"  and "S"  was always "substitute"  This seems to be remapped somehow

### ISSUE THREAD

**Issue by cool-clay** [LazyVim/LazyVim#2941]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5 LuaJIT 2.1.1692716794

### Operating system/version

mx linux 23 

### Describe the bug

I don't know if this is a bug,  but to me, a common keybinding that doesn't work the way it should is a bug.
That s does some unexpected behavior.   Maybe some plugin.
And looking through the configs.. I don't see any remapping of the key.

### Steps To Reproduce

1. fresh install of neovim from the website by downloading the tar file
2. Fresh install of Lazy from the quick setup, all default config.
3. Edit a file normally using nvim and press s or S.

### Expected Behavior

"s" should do a substitute character and go into insert mode  "3s" should do 3 characters
"S" should delete the line and go to insert mode.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
This comes from plugin `flash.nvim`. You can read the docs for how to change the keys to something else or you can disable the plugin if you don't want this behavior.

**Comment by dpetka2001** [comment]
@cool-clay To change the colorscheme to something else you should do what is described in the [docs](https://www.lazyvim.org/configuration#icons--colorscheme).

**Comment by aprilmay** [comment]
> This comes from plugin `flash.nvim`. You can read the docs for how to change the keys to something else or you can disable the plugin if you don't want this behavior.

Many thanks for the pointer.
IMHO LazyVim's basic config should not include plugins that remaps the basic vim behavior.
