### ISSUE TITLE
bug: ES6 shorthand function definitions are ignored in symbols search

### ISSUE THREAD

**Issue by joms** [LazyVim/LazyVim#2947]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

macOS 14.4.1

### Describe the bug

When defining functions in JavaScript/TypeScript using the ES6 shorthand syntax, they are not shown in "Goto symbol" using `<leader>ss`.

However, when using the traditional syntax `function foo() {}` it is listed in this view.

I have checked the behavior in Astrovim, and there it behaves as expected. However, I have not been able to figure out how to achieve the same in the LazyVim configuration.

### Steps To Reproduce

// myfile.js
```
const foo = () => {}
```

`<leader>ss`

### Expected Behavior

When opening "Goto symbol" with `<leader>ss` function foo should be listed.

**Comment by dpetka2001** [comment]
You can try changing the default Telescope keymap in a file in `~/.config/nvim/lua/plugins/` directory
```lua
-- ~/.config/nvim/lua/plugins/tele.lua
return {  
  {
    "nvim-telescope/telescope.nvim",
	keys = {
	  {
        "<leader>ss",
        function()
          require("telescope.builtin").lsp_document_symbols({})
        end,
        desc = "Goto Symbol",
      },
	},
  },
}
```

**Comment by joms** [comment]
That did work, however now all constants in the code is listed. I think the idea was that this should not be the case.

I tried this code in the [Tree-sitter playground](https://tree-sitter.github.io/tree-sitter/playground):

```
const foo = () => {};

function foobar() {}
```

A notable difference is that foobar is a `function_declaration`, but foo is a `lexical_declaration` that has a value of `arrow_function`. I would assume that there's a filter somewhere that filters out variable definitions, but does not look into whether the variable is an arrow function or something else.

**Comment by dpetka2001** [comment]
Yes, there's some filtering done based on the [default symbols here](https://github.com/LazyVim/LazyVim/blob/97480dc5d2dbb717b45a351e0b04835f138a9094/lua/lazyvim/config/init.lua#L97-L112). You could create the keymap with extending this list-like table. So, something like
```lua
    {
        "<leader>ss",
        function()
          require("telescope.builtin").lsp_document_symbols({
            symbols = vim.list_extend(require("lazyvim.config").get_kind_filter(), { "your_type_here" })
          })
        end,
        desc = "Goto Symbol",
     },
```

**Comment by dpetka2001** [comment]
Does AstroNvim not show all constants? Does it show only the arrow function? As far as I can see in `Telescope lsp_document_symbols` it recognizes the arrow function as a `Constant` LSP symbol.

**Comment by joms** [comment]
> Does AstroNvim not show all constants? Does it show only the arrow function? 

<img width="1027" alt="image" src="https://github.com/LazyVim/LazyVim/assets/537060/d2f5d31a-ca0e-4fa2-86e0-e1dfa4f10e28">

Ah shoot, good point! Didn't realize they show everything. I guess what I'm looking for then is a way to filter out `Constant`s that doesn't have a value of `arrow_function`.

**Comment by dpetka2001** [comment]
I'm not aware how you can filter from `Constant` only the arrow functions to be shown. But this is definitely not a bug. I also just tried AstroNvim and it does show all Constants.

**Comment by joms** [comment]
Right, thanks for the help!

**Comment by dpetka2001** [comment]
@joms If you do happen to find a way to do this, please make a comment here providing the way to do it. 

I myself would be interested in knowing how to do this if possible at all.

**Comment by joms** [comment]
Absolutely. I feel like it would be something that's useful to get into typescript extras too.

**Comment by gugahoi** [comment]
Any chance you've been able to find a solution to this?

**Comment by joms** [comment]
> Any chance you've been able to find a solution to this?

I have not :( The closest I got was just to show everything without filtering for functions. But that didn't really solve the issue.
