### ISSUE TITLE
feature: nvim-neoclip

### ISSUE THREAD

**Issue by Martin1887** [LazyVim/LazyVim#2948]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Not a LazyVim problem but a general Neovim use case problem :smile: . Basically losing the yanked contents after yanking other ones because people usually don't record every yank in a different register except they are sure they will need them.

### Describe the solution you'd like

https://github.com/AckslD/nvim-neoclip.lua seems a great approach to solve this, I think adding it by default in LazyVim and LazyVim tips would help many users.

### Describe alternatives you've considered

I have not searched other alternatives, but nvim-neoclip seems a really good one.

**Comment by dpetka2001** [comment]
LazyVim already has `yanky` in the Extras, which I believe provides a key for history with the yanked contents. See the [docs](https://www.lazyvim.org/extras/coding/yanky).

**Comment by Martin1887** [comment]
Well, that's true, but I find yanky less intuitive. In addition, neovim-neoclip also supports macros history.

**Comment by Martin1887** [comment]
My mappings in nvim-neoclip in case they are inspiring for this issue:
```lua
map(
  "n",
  "<leader>yy",
  "<cmd>Telescope neoclip<cr>",
  { desc = "Telescope neoclip (yank history)", silent = true, noremap = true }
)
map(
  "n",
  "<leader>m",
  "<cmd>Telescope macroscope<cr>",
  { desc = "Telescope macroscope (neoclip macros history)", silent = true, noremap = true }
)
map(
  "n",
  "<leader>yo",
  "<cmd>:lua require('neoclip').start()<cr>",
  { desc = "Telescope neoclip On", silent = true, noremap = true }
)
map(
  "n",
  "<leader>yf",
  "<cmd>:lua require('neoclip').stop()<cr>",
  { desc = "Telescope neoclip oFF", silent = true, noremap = true }
)
map(
  "n",
  "<leader>yt",
  "<cmd>:lua require('neoclip').toggle()<cr>",
  { desc = "Telescope neoclip Toggle", silent = true, noremap = true }
)
map(
  "n",
  "<leader>yc",
  "<cmd>:lua require('neoclip').clear_history()<cr>",
  { desc = "Telescope neoclip Clear history", silent = true, noremap = true }
)

```

**Comment by dpetka2001** [comment]
I suggest you make a PR and make your case to the maintainer why this should be preferred over yanky (or even as a separate Extra, so that both can exist). He's the one who has the final say after all.

Good luck :smile:

**Comment by folke** [comment]
yep, feel free to create an extra. thanks
