### ISSUE TITLE
bug: cannot switch off tsserver if no package.json

### ISSUE THREAD

**Issue by iykekings** [LazyVim/LazyVim#295]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

v0.8.3

### Operating system/version

MacOS 13.1

### Describe the bug

I'm not sure if this is a bug, but it is the only other issue template alongside feature request.
I have this config in `lua/plugins/typescript_lsp.lua` 
Configuration lifted from Deno docs [here](https://deno.land/manual@v1.30.3/getting_started/setup_your_environment#neovim-06-using-the-built-in-language-server)
```lua
return {
  "neovim/nvim-lspconfig",
  dependencies = { "jose-elias-alvarez/typescript.nvim" },
  ---@class PluginLspOpts
  opts = {
    ---@type lspconfig.options
    servers = {
      tsserver = { root_dir = require("lspconfig").util.root_pattern("package.json"), single_file_support = false },
      denols = { root_dir = require("lspconfig").util.root_pattern("deno.json", "deno.jsonc") },
    },
    ---@type table<string, fun(server:string, opts:_.lspconfig.options):boolean?>
    -- setup = {
    --   tsserver = function(_, opts)
    --     require("typescript").setup({
    --       server = opts,
    --       root_dir = lspconfig.util.root_pattern("package.json"),
    --       single_file_support = false,
    --     })
    --     return true
    --   end,
    -- },
  },
}
```

But I noticed that on a directory with just `deno.json` that tsserver is still activated when I do `space` `cl`
I also tried this same thing with the file in `lua/config/` and also with the part commented out uncommented, but the same experience.

I'm new to vim/LazyVim, so I might be doing sth totally wrong.

### Steps To Reproduce

1. Create a deno project - say just a single ts file with url import 
2. Have both deno lsp and typescript language server installed
3. And check for lsp state in the current directory with <leader> `cl`, both denols and tserver will be activated

### Expected Behavior

 Expected result is that only denols should be on.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
require("config.lazy")
```

**Comment by folke** [comment]
This is an issue with neoconf.

To resolve it, you could disable `folke/neoconf.nvim` for now.

Closing this, and tracking the issue at https://github.com/LazyVim/LazyVim/issues/295

**Comment by iykekings** [comment]
If I disable `folke/neoconf.nvim`, every command under `<leader>c` is off except `m` for mason.

**Comment by folke** [comment]
That's because you have no LSP attached. Check with `:LspInfo`.

**Comment by iykekings** [comment]
Great, this works, but `tsserver` is still turned on by `single_file mode`, even though the `single_file_support` is set to false

**Comment by folke** [comment]
No idea. You'll have to consult the lspconfig docs

**Comment by iykekings** [comment]
Thank you for your help
