### ISSUE TITLE
feature: Which font does lazyvim use,nerd is a font family?

### ISSUE THREAD

**Issue by ArchGu** [LazyVim/LazyVim#2950]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Which font does lazyvim use,nerd is a font family?

### Describe the solution you'd like

I do not want to install all the fonts in nerd fonts family.

### Describe alternatives you've considered

i do not know.

**Comment by dpetka2001** [comment]
LazyVim does not use any nerd font. It's up to the user to decide which Nerd font to install to show the icons. And you also have to configure your terminal to use the font that you installed.

**Comment by ArchGu** [comment]
> LazyVim does not use any nerd font. It's up to the user to decide which Nerd font to install to show the icons. And you also have to configure your terminal to use the font that you installed.

Thanks,maybe i read the wrong third-party installation instructions.

**Comment by dpetka2001** [comment]
It's mentioned in the requirements that you need a Nerd font to show the prettified icons, but Lazyvim doesn't use a specific Nerd font. The user can install whatever he chooses. Pls keep in mind that there are differences even between Nerd fonts and some may not show all the icons, but some will (this is just what i've read from other people experience).
