### ISSUE TITLE
bug: `Failed to setup handlers for mini.surround` with empty `mappings` entry

### ISSUE THREAD

**Issue by echasnovski** [LazyVim/LazyVim#296]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.3

### Operating system/version

EndeavourOS Linux x86_64 (6.1.11-arch1-1)

### Describe the bug

When using empty string as `mappings` entry in 'mini.surround', this error is shown:

```
Failed to setup handlers for mini.surround

vim/keymap.lua:0: Invalid (empty) LHS

# stacktrace:
  - vim/keymap.lua:0 _in_ **set**
```

Any `mappings` entry in any 'mini.nvim' module (except 'mini.pairs') can be an empty string with meaning to not create that particular mapping. Relevant modules for LazyVim are 'mini.ai', 'mini.comment', 'mini.indentscope', 'mini.surround'.

### Steps To Reproduce

1. Configure 'mini.surround' using, for example, this setup:
```lua
return {
  "echasnovski/mini.surround",
  opts = {
    mappings = {
      add = "ys",
      delete = "ds",
      find = "yf",
      find_left = "yF",
      highlight = "vs",
      replace = "cs",
      update_n_lines = "",
    },
    search_method = "cover_or_next",
  },
  config = function(_, opts)
    require("mini.surround").setup(opts)
  end,
}
```
2. Open Neovim.

### Expected Behavior

Empty string in `mappings` entry doesn't result into error.

**Comment by folke** [comment]
Fixed!

**Comment by echasnovski** [comment]
Nice!
I've thought that 'mini.ai' is also affected (as it also uses `mappings` to configure `a`/`i` and their `next`/`last` variants), but it seems LazyVim doesn't account for those. Only 'mini.surround' it is then.
