### ISSUE TITLE
bug: Compilation errors from treesitter

### ISSUE THREAD

**Issue by eagle-tex** [LazyVim/LazyVim#2961]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Ubuntu 20.04

### Describe the bug

Each time I launch LazyVim, I get a bunch of compilation errors related to treesitter.
Some say it can't compile certain languages (javascript, html, lua, etc)
I can't capture all the notifications as there are quite a few.

Here is one of them

> [nvim-treesitter] [21/23, failed: 21] Compiling...
nvim-treesitter[tsx]: Error during compilation
In file included from src/tree_sitter/parser.h:9,
                 from src/parser.c:1:
/usr/lib/gcc/x86_64-linux-gnu/9/include/stdint.h:9:16: fatal error: stdint.h: No such file or directory
    9 | # include_next <stdint.h>
      |                ^~~~~~~~~~
compilation terminated.
In file included from ./src/tree_sitter/parser.h:9,
                 from src/../../common/scanner.h:1,
                 from src/scanner.c:1:
/usr/lib/gcc/x86_64-linux-gnu/9/include/stdint.h:9:16: fatal error: stdint.h: No such file or directory
    9 | # include_next <stdint.h>
      |                ^~~~~~~~~~
compilation terminated.
In file included from src/tree_sitter/parser.h:9,
                 from src/parser.c:1:
/usr/lib/gcc/x86_64-linux-gnu/9/include/stdint.h:9:16: fatal error: stdint.h: No such file or directory
    9 | # include_next <stdint.h>
      |                ^~~~~~~~~~
compilation terminated.
In file included from ./src/tree_sitter/parser.h:9,
                 from src/../../common/scanner.h:1,
                 from src/scanner.c:1:
/usr/lib/gcc/x86_64-linux-gnu/9/include/stdint.h:9:16: fatal error: stdint.h: No such file or directory
    9 | # include_next <stdint.h>
      |                ^~~~~~~~~~
compilation terminated.

When I run `:checkhealth nvim-treesitter`, this is the result:

==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.7 (b268e412ad4848380166af153300464e5a1cf83f) (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v20.10.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "5.15.0-101-generic",
  sysname = "Linux",
  version = "#111~20.04.1-Ubuntu SMP Mon Mar 11 15:44:43 UTC 2024"
} ~

Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ x
  - query               ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              x . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

The following errors have been detected: ~
- ERROR lua(injections): ...Uu63/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid structure at position 3272 for language lua
  lua(injections) is concatenated from the following files:
  | [ERROR]:"/home/gildas/.local/share/LazyVim/lazy/nvim-treesitter/queries/lua/injections.scm", failed to load: ...Uu63/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid structure at position 3272 for language lua
- ERROR vimdoc(highlights): ...Uu63/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 749 for language vimdoc
  vimdoc(highlights) is concatenated from the following files:
  | [ERROR]:"/home/gildas/.local/share/LazyVim/lazy/nvim-treesitter/queries/vimdoc/highlights.scm", failed to load: ...Uu63/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 749 for language vimdoc

Is there something I'm missing?
I didn't have these errors a few weeks ago when I launched LazyVim and I haven't touched its configuration in a while.

### Steps To Reproduce

1. Fresh install of LazyVim
2. Launch LazyVim
3. 

### Expected Behavior

Not to have any of the errors.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
These errors are not related to LazyVim. Few things you should check
- Update plugins from Lazy UI
- Run `TSUpdate` to update all treesitter parsers. 
- Check nvim-treesitter's [requirements](https://github.com/nvim-treesitter/nvim-treesitter?tab=readme-ov-file#requirements) and [troubleshooting](https://github.com/nvim-treesitter/nvim-treesitter?tab=readme-ov-file#troubleshooting)

If you still can't get it working, I suggest opening an issue either at Neovim or nvim-treesitter's repo.
