### ISSUE TITLE
ansible-lint command failed

### ISSUE THREAD

**Issue by sandikata** [LazyVim/LazyVim#2967]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.5

### Operating system/version

Gentoo 2.15

### Describe the bug

When i am using ansible lsp (nvim-ansible) every time it throws ansible-lint command error 

### Steps To Reproduce

1. LazyExtras
2. Select Ansible
3. Try to open any playbook

### Expected Behavior

Should not complain about ansible-lint execution.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
Do you have `ansible-lint` installed? What is the error you get?

**Comment by sandikata** [comment]
Yeah, ansible-lint is installed, the error is somehow related to the PATH variable, but it's a confusing one.

ansible-lint
WARNING: PATH altered to include /usr/lib/python-exec/python3.11 :: This is usually a sign of broken local setup, which can cause unexpected behaviors.

As it appears only on ansible-lint execution.

PS: is it possible any .ansible-lint configuration per project to reflect?

**Comment by dpetka2001** [comment]
No idea, I don't do Ansible. What does `:!which ansible-lint` show from inside Neovim?

**Comment by sandikata** [comment]
Actually, it is .ansible-lint issue, if this file is empty then ansible-lint fails on project level.
