### ISSUE TITLE
bug: change keymap from <leader>bd to <leader>c is slow

### ISSUE THREAD

**Issue by gxt-kt** [LazyVim/LazyVim#2977]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5 

### Operating system/version

archlinux

### Describe the bug

I have changed keymap from <leader>bd to <leader>c by `keymap("n", "<leader>c", "<cmd>lua require('mini.bufremove').delete(0)<cr>", opts)
`
Though the keymap is effective, but the reaction is very slow when i use try to close current buffer.
And <leader>bd close is very fast.

And i try to change the source keymap code of lazyvim `editor.lua` file, but <leader>c is still slow.

### Steps To Reproduce

 changed keymap from <leader>bd to <leader>c 

### Expected Behavior

use <leader>c can close buffer fast like <leader>bd

**Comment by dpetka2001** [comment]
This is normal behavior because there are many keymaps that include [`<leader>c`](https://github.com/search?q=repo%3ALazyVim%2FLazyVim%20%3Cleader%3Ec&type=code), so it's waiting for `timeoutlen` seconds to see if some other key will follow after `<leader>c`.

**Comment by gxt-kt** [comment]
So is there some other resolution to solve this problem. Actually i can remap all `<leader>c*` key to others, only use `<leader>c` to close current buffer.
Maybe i can delete all `<leader>c` and only map this one?

**Comment by dpetka2001** [comment]
Not without remapping all `<leader>c*` keys. Or you could just add one more letter in your keymap to not have any delay (for example `<leader>cx`).

**Comment by dpetka2001** [comment]
You can also try this [plugin](https://github.com/abeldekat/lazyvim-menu-addon) to change the top-level key of your choosing to something else and then be able to use that key according to your own preferences. However, this plugin is archived and can't guarantee that something won't break in the future. But you can try it and see if it fits your needs.

**Comment by gxt-kt** [comment]
Thanks for your reply, i also find a discussion about remap the top-level leader key. https://github.com/LazyVim/LazyVim/discussions/90
I think I will continue using the default keymap `<leader>bd`.
