### ISSUE TITLE
bug: Visual Bug when on top of the file

### ISSUE THREAD

**Issue by hoidOS** [LazyVim/LazyVim#2979]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-66220d1

### Operating system/version

MacOS 14.4.1

### Describe the bug

When I press 'k' to move up on the first line, the line disappears and reappears, and in the signs column, '<<<' appears. Sometimes, the lualine completely bugs out, and I see multiple cursors. I've tried deactivating multiple plugins, but the issue still persists. Interestingly, the bug doesn't appear with a somewhat clean Neovim config and just Lazy as the package manager. Any ideas or suggestions? Thanks!
![CleanShot 2024-04-13 at 23 06 48](https://github.com/LazyVim/LazyVim/assets/72317378/c272389d-dc56-4399-ae20-7d6637b47ca1)

### Steps To Reproduce

1. Open file
2. Press k on top of the file
3. first line bugs out | disappears | <<< in the signs column

### Expected Behavior

Nothing happens when pressing k on the first line

**Comment by hoidOS** [comment]
It turns out the problem was the scrolloff setting set to 999. Lowering it to 10 resolves the problem, although typically, I use it to keep the line centered. Could this option be conflicting with a plugin?

**Comment by dpetka2001** [comment]
Not able to reproduce with default LazyVim installation. Please test with default LazyVim installation (not your personal configuration) and report if the behavior is present with `vim.opt.scrolloff = 999`.

**Comment by hoidOS** [comment]
So i tested it and yes only `vim.opt.scrolloff = 999` works, but the combination `vim.opt.wrap = true` and `vim.opt.scrolloff = 999` is the problem.

**Comment by dpetka2001** [comment]
With these 2 settings, I still can't reproduce in default LazyVim installation. Did you try default LazyVim installation or your personal configuration? Test the following
```bash
1. `mkdir ~/.config/lazytest`
2. `git clone https://github.com/LazyVim/starter ~/.config/lazytest`
3. `NVIM_APPNAME=lazytest nvim` and wait for the installation to complete
4. Restart Neovim with the command provided in step 3
5. Set in `~/.config/lazytest/lua/config/options.lua` the 2 settings `vim.opt.scrolloff = 999` and `vim.opt.wrap = true`
6. Restart Neovim with command provided in step 3 and observe behavior
```
For cleanup
```bash
rm -rf ~/.config/lazytest
rm -rf ~/.local/share/lazytest
rm -rf ~/.local/state/lazytest
rm -rf ~/.cache/lazytest
```

**Comment by hoidOS** [comment]
Yes i did it like that for testing. Completely clean install only those two options.

![CleanShot 2024-04-14 at 11 23 50](https://github.com/LazyVim/LazyVim/assets/72317378/07d03eb2-3cdf-43ae-82af-a834ea5f1a23)

**Comment by dpetka2001** [comment]
Yes, I can reproduce. After some fiddling I think `vim.opt.smoothscroll` is the culprit. This doesn't happen with Neovim stable, only with nightly where this option is enabled. Try setting `vim.opt.smoothscroll = false`.

**Comment by hoidOS** [comment]
Yes it works with `smoothscroll` off. 
Thank you very much for your help!
