### ISSUE TITLE
Error executing vim.schedule lua callback

### ISSUE THREAD

**Issue by SimonCrA** [LazyVim/LazyVim#2991]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

ubuntu 22.04

### Describe the bug

When opening a .md file. A notification pop up with this message. And it keeps appearing everytime I type down

![image](https://github.com/LazyVim/LazyVim/assets/46234570/2e5d9d46-9040-451e-9412-dc14d45bec1e)

### Steps To Reproduce

1. open and .md file
2. type something in insert mode and wait for the notification to pop up.
3. it stops when you are in normal mode

### Expected Behavior

It should not appear the notification.

### Repro

```Lua
-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
```

**Comment by dpetka2001** [comment]
Do you have `nvim-treesitter` parser for `markdown` installed?

**Comment by SimonCrA** [comment]
I have `nvim-treesitter` installed, I'm not sure if it is checking md files too.

these are the plugins are being loaded 
![image](https://github.com/LazyVim/LazyVim/assets/46234570/ba63c836-db54-45f3-b258-12731a88ee78)

**Comment by dpetka2001** [comment]
Do a `:TSInstallInfo` and see in `:messages` if the parser for `markdown` is installed.

**Comment by dpetka2001** [comment]
Also it doesn't show in your first screenshot, but what does the error actually show? 
```
invalid node type at position xxx for language ???
```
Does it tell you for which language the error occurs?

**Comment by SimonCrA** [comment]
It actually is installed: markdown and markdown_inline

![image](https://github.com/LazyVim/LazyVim/assets/46234570/ad0223bc-1e64-4239-b9c0-4601134acb0d)

**Comment by dpetka2001** [comment]
Can you also answer my previous comment if possible?

**Comment by SimonCrA** [comment]
yes, about the error. this is what it says:

![image](https://github.com/LazyVim/LazyVim/assets/46234570/fefcae0e-2615-492b-977b-500f8940894d)

**Comment by dpetka2001** [comment]
Do you have parser for `latex` installed? It's not installed by default.

**Comment by SimonCrA** [comment]
that was the problem, Thank you. I installed the vimtex plugin and the error is not showing anymore

**Comment by SimonCrA** [comment]
should it be installed with markdown plugin since is a direct dependency?

**Comment by dpetka2001** [comment]
Not every markdown file has latex included. That's why there's an explicit Extra for Tex [here](https://www.lazyvim.org/extras/lang/tex).

**Comment by SimonCrA** [comment]
Okay, I understand. Thanks for your quick response. I will close the issue then.
