### ISSUE TITLE
bug: crash when using telescope

### ISSUE THREAD

**Issue by francois-pasquier** [LazyVim/LazyVim#30]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0-dev-647+g1df2db0bc-dirty

### Operating system/version

MacOS 12.6

### Describe the bug

When using Telescope with this keymap: `{ "<leader>/", util.telescope("live_grep"), desc = "Find in Files (Grep)" }`

In a fairly large project, typing/removing a few letters seems to crash neovim.
I have only between 16 and 60 results when it crashes.

Is there any way to pinpoint the issue as neovim just closes without any message?

I checked on the Telescope repo, some open issues are about crashes but they all seem to get errors shown inside of neovim.

My config is straight from the starter, no change at all.

### Steps To Reproduce

1. Open a large project
2. <leader>/
3. type/remove a few letters e.g: `abcde` (speed doesn't seem to matter)
4. I am back to my terminal without any message.

### Expected Behavior

no crash

### Repro

```Lua
Same as starter
```

**Comment by folke** [comment]
Are you using nightly? Nightly is currently unstable due to the TUI rework.

**Comment by folke** [comment]
See also https://github.com/folke/noice.nvim/issues/298

**Comment by folke** [comment]
I just updated Noice to show a warning when running on nightly with the TUI rework

**Comment by francois-pasquier** [comment]
That was the issue, thank you
