### ISSUE TITLE
feature: Install LazyVIm in a isolated environment. No Internet.

### ISSUE THREAD

**Issue by sojjan1337** [LazyVim/LazyVim#3000]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Struggling to getting it to work in a good way without Internet access.

### Describe the solution you'd like

Install LazyVim with LSP and default plugins support in a offline environment.
A default font included, and that autocompletion works from start, and standard plugins like treesitter is available.
Just unpack a .tar file then use a good IDE :)

lsp should work with python,terraform,ansible,yaml,bash.
That would be great.

### Describe alternatives you've considered

Manually copying it to remote server, but doesn't work that well.

**Comment by dpetka2001** [comment]
I don't believe this falls under LazyVim's scope. It's something that the user should do himself. Just backup the corresponding directories mentioned in the [installation docs](https://www.lazyvim.org/installation) and copy them over to where you want. I haven't done this, so I can't say it will work 100%, but it's up to the user to try and find out.

**Comment by sojjan1337** [comment]
Thanks for a quick response. I have tried but it's a hassle.

**Comment by smprather** [comment]
Bummer that offline isn't supported. I have copied all of the dirs to offline environment, but LazyVim is trying to download some stuff plugin stuff anyway. It gets stuck there until timeout. For the sake of Google, what are the options needed to prevent LV (and Mason, etc) from trying to access internet and getting hung?

**Comment by nerdbugg** [comment]
@dpetka2001 Hello, is there some way to install plugins in config and generate files usable in offline setup in quite mode? And then we can write a github action script to automate generating the files for offline setup. 
Although some plugins use absolute file path like mason, the function should be much useful for offline user. And we could work based on it and solve them using script case by case.
I'm not familar with the LazyVim initialize and internal code, if there are some document or suggestion will be nice.

**Comment by dpetka2001** [comment]
I've never tried this, so am not familiar with such a process. Unfortunately, I can't be of much help on this matter. Probably the maintainer has a better grasp on how to achieve something like this, but he's currently on vacation and you would have to wait for his input after he comes back.

**Comment by smprather** [comment]
The best I have come up with so far is a set of scripts I use to create git clones of the plugins I use in my online environment. I tar all of those up and transfer to my offline environment. Extract. I tell LazyVim to change the repo URL from https://github.com/foo/bar to file:///where/i/extract/in/offline/foo/bar.

It would be really nice if I could get similar functionality in Mason. But there are just so many online-needy things related to NeoVim (npm, treesitter, lazyvim, mason, pip, lua rocks, and on and on and on), that I am worried fully functional offline NeoVim is something that will never be supported unless someone comes along with major time and energy to drive the effort. And even then, I'm skeptical.

My personal goal is to be able to create a NeoVim environment online, get it working really nice, snapshot, toss it into offline. If I want updates, go back to online, do updates, repeat. Don't believe anybody that says "just copy the so and so dirs over...". Pure Lua stuff, sure. But nope. There are just too many external deps and native-code builds. To make matters worse, my offline is Redhat 8, the currently "chosen" platform for chip development. a) I don't have an online Redhat 8 available (making one is on my todo list), b) Redhat 8  (GLIBC 2.28) is quickly becoming incompatible with the rest of the linux ecosystem.

I first ran into Dependency Hell 30 years ago when I was admin'ing a grad-student unix lab at LSU, and trying to compile Elm. Some things never change.

**Comment by nerdbugg** [comment]
In my company, we use old glibc too (centos). But a seperate gcc-12 toolchain is installed on host with no-default path. And we can use `pathelf` to set loader and rpath to use new libc. Maybe you can try with it.

And tools write in go and rust is easy to build in static-linked mode, and they are friendly for offline use.

**Comment by smprather** [comment]
> In my company, we use old glibc too (centos). But a seperate gcc-12 toolchain is installed on host with no-default path. And we can use `pathelf` to set loader and rpath to use new libc. Maybe you can try with it.
> 
> And tools write in go and rust is easy to build in static-linked mode, and they are friendly for offline use.

Amazing! I can't change anything in the system dirs, but I'm thinking I can get this working in user space. Unfortunately, I am all too familiar with patchelf and RPATH 😺/😿. Thanks for the great idea. I was thinking that GLIBC version was at the fundamental foundation (kernal tied?) of any linux and there was no way around it.
