### ISSUE TITLE
feature: add johmsalas/text-case.nvim plugin

### ISSUE THREAD

**Issue by burnettk** [LazyVim/LazyVim#3002]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like

I wouldn't mind being able to convert "HeyMan" to "hey_man" or "heyMan" more easily.

### Describe alternatives you've considered

There are likely native solutions to these problems that are likely rough around the edges.

### Additional context

It's this thing: https://github.com/johmsalas/text-case.nvim. I hate adding plugins to lazyvim. Just wanted to see if this one had ever been considered. It's nice. But absolutely feel free to close this without adding. Thanks for the awesome software.

**Comment by folke** [comment]
shouldnt be a core plugin. thanks
