### ISSUE TITLE
bug: Unhelpful error when trying to install a plugging that does not exist

### ISSUE THREAD

**Issue by BraianPita** [LazyVim/LazyVim#3005]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Debian Bookworm

### Describe the bug

When I try to install a package from a github repository that does not exits, it throws an error completely unrelated to the problem:

```text
        Cloning into '/home/user/.local/share/nvim/lazy/gruvbox.nvim'...
        fatal: No credential store has been selected.

        Set the GCM_CREDENTIAL_STORE environment variable or the credential.credentialStore Git configuration setting to one of the following options:

          secretservice : freedesktop.org Secret Service (requires graphical interface)
          gpg           : GNU `pass` compatible credential storage (requires GPG and `pass`)
          cache         : Git's in-memory credential cache
          plaintext     : store credentials in plain-text files (UNSECURE)

        See https://aka.ms/gcm/credstores for more information.

        fatal: could not read Username for 'https://github.com': terminal prompts disabled

```

### Steps To Reproduce

Install a package that does not exist on github
Run Lazy and use the Install (I) command

### Expected Behavior

Instead of showing an unrelated error talking about missing github credentials, it should check if its a 404, and return a helpful message that explains that the repository for the plugin is missing.

### Repro

```Lua
-- inside init.lua

  { -- You can easily change to a different colorscheme.
    -- Change the name of the colorscheme plugin below, and then
    -- change the command in the config to whatever the name of that colorscheme is
    --
    -- If you want to see what colorschemes are already installed, you can use `:Telescope colorscheme`
    'mispelled/gruvbox.nvim',
    lazy = false, -- make sure we load this during startup if it is your main colorscheme
    priority = 1000, -- make sure to load this before all the other start plugins
    config = function()
      -- Load the colorscheme here
      vim.cmd.colorscheme 'gruvbox'
      vim.o.background = 'dark'

      -- You can configure highlights by doing something like
      vim.cmd.hi 'Comment gui=none'
    end,
  },
```

**Comment by dpetka2001** [comment]
This error comes directly from git. Just do a `git clone https://github.com/mispelled/gruvbox.nvim.git` and observe behavior. This has nothing to do with LazyVim.

**Comment by dpetka2001** [comment]
Nope that is not the work of LazyVim. It's the package manager that uses git and returns the error that git provides.

**Comment by BraianPita** [comment]
> Instead of showing an unrelated error talking about missing github credentials, it should check if its a 404, and return a helpful message that explains that the repository for the plugin is missing.

You are indeed correct, I got confused on which repo this was and thought this was the Lazy package manager repository. Apologies 😅
