### ISSUE TITLE
bug: LspInfo command gives E464: ambiguous use of user-defined command

### ISSUE THREAD

**Issue by gegenschall** [LazyVim/LazyVim#3006]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev-2898+g4c31a1b80-dirty

### Operating system/version

macOS 14.4

### Describe the bug

I am trying to debug an issue around LSP and conform (ESLint/Prettier/tsserver both seem to be competing to format the buffer) and was trying to open `:LspInfo`. The command works fine in a `.lua` file but fails in a JavaScript/TypeScript buffer with the error `E464: Ambiguous use of user-defined command`.

I've since disabled all LazyVim extras, removed all plugin configuration, updating to latest, used the clean functionality of lazy but to no avail.
I inspected `:command` but can only see one occurrence of `LspInfo` (assuming there should be multiple with the above error message?)

What does work is adding this to my config and then using that command:
```
vim.api.nvim_create_user_command("LspInfoTmp", function()
  require("lspconfig.ui.lspinfo")()
end)
```

### Steps To Reproduce

1. Open any JS/TS file
2. Type `:LspInfo<CR>`

### Expected Behavior

LspInfo is shown.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
Can't reproduce if I type the whole command. Only when I type `:LspIn` and press `<Tab>` and press `<CR>` I get the error, but this is due to the command not being completed until the end, because there is also the command `LspInstall`. You should either type the command as a whole or press `<Tab>` until the command appears as a whole in the command line.

**Comment by folke** [comment]
exactly as @dpetka2001 says
