### ISSUE TITLE
Preselect option of nvim-cmp is ignored

### ISSUE THREAD

**Issue by danieltd** [LazyVim/LazyVim#301]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.8.3

### Operating system/version

Void Linux (up to date as of Feb 10)

### Describe the bug

nvim-cmp `preselect` option is not respected in LazyVim config. I have created a lua script at `~/cfg/nvim/lua/plugins/plug_nvimcmp.lua` with the line `opts.preselect = cmp.PreselectMode.None`, but autocomplete menus still select the first item by default (when it should not select any). Here is my full config for that lua file:

```
-- Use <tab> for completion and snippets (supertab-like behavior)
-- This config for setting up supertab behavior came from LazyVim site:
-- https://www.lazyvim.org/configuration/recipes#supertab
return {
  {
    "L3MON4D3/LuaSnip",
    keys = function()
      return {}
    end,
  },

  {
    "hrsh7th/nvim-cmp",
    dependencies = {
      "hrsh7th/cmp-emoji",
    },
    ---@param opts cmp.ConfigSchema
    opts = function(_, opts)
      local has_words_before = function()
        unpack = unpack or table.unpack
        local line, col = unpack(vim.api.nvim_win_get_cursor(0))
        return col ~= 0 and vim.api.nvim_buf_get_lines(0, line - 1, line, true)[1]:sub(col, col):match("%s") == nil
      end

      local luasnip = require("luasnip")
      local cmp = require("cmp")

      opts.preselect = cmp.PreselectMode.None

      opts.mapping = vim.tbl_extend("force", opts.mapping, {
        ["<Tab>"] = cmp.mapping(function(fallback)
          if cmp.visible() then
            cmp.select_next_item()
          -- You could replace the expand_or_jumpable() calls with expand_or_locally_jumpable()
          -- they way you will only jump inside the snippet region
          elseif luasnip.expand_or_jumpable() then
            luasnip.expand_or_jump()
          elseif has_words_before() then
            cmp.complete()
          else
            fallback()
          end
        end, { "i", "s" }),
        ["<S-Tab>"] = cmp.mapping(function(fallback)
          if cmp.visible() then
            cmp.select_prev_item()
          elseif luasnip.jumpable(-1) then
            luasnip.jump(-1)
          else
            fallback()
          end
        end, { "i", "s" }),
        ["<CR>"] = function(fallback)
          -- Disable ENTER key from selecting autocompletion.
          -- I don't know if this is the right way to do it, but it works.
          fallback()
        end,
        ["<C-Space>"] = cmp.mapping.confirm({
          -- TODO remove this C-Space block after TAB completion works how I
          -- want
          -- behavior = cmp.ConfirmBehavior.Replace,
          select = false,
        }),
      })
    end,
  },
}
```

### Steps To Reproduce

1. Install neovim
2. Install LazyVim starter config
3. Add the above nvim-cmp configuration to the config path mentioned above
4. Restart neovim
5. Start typing something that nvim-cmp has autocomplete suggestions for
6. A pop-up menu will display as you type, with the first item already preselected (when no item should be selected without first pressing TAB).

### Expected Behavior

As I type, the nvim-cmp completion menu should look like this:
![image](https://user-images.githubusercontent.com/2867646/219878000-d0edd84b-4355-4336-924e-bc93b4949c1f.png)
(Nothing is preselected.)

It should not look like it does now:
![image](https://user-images.githubusercontent.com/2867646/219878035-7af7bc78-328f-4b8d-b029-13f62a737da4.png)
(The first item is already preselected/highlighted on its own, without me first pressing any completion keys.)

**Comment by dpetka2001** [comment]
Try this
```lua
......  -- your previous config here
      opts.preselect = cmp.PreselectMode.None
      opts.completion = {
        completeopt = "noselect",
      }
......  -- your config continues here
```
I found it in one of the `nvim-cmp` issues. You must also set `completeopt` for some reason after `preselect`.

**Comment by danieltd** [comment]
@dpetka2001 That did the trick! Thank you so much.

LazyVim might consider adding this to their documentation, especially on [the page for supertab configuration](https://www.lazyvim.org/configuration/recipes#supertab).
