### ISSUE TITLE
bug: Unable to mix Deno and non-Deno files in the same workspace

### ISSUE THREAD

**Issue by eriklindebratt** [LazyVim/LazyVim#3019]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5, latest stable release from Homebrew

### Operating system/version

macOS 14.4.1

### Describe the bug

The Deno LSP has the setting `deno.enablePaths` so that one can choose to only run Deno in _parts of a workspace_. In a TypeScript workspace where just a _part_ of the files should use Deno – with a `package.json` file but _no `deno.json`_ – these lines completely disables the Deno LSP:

https://github.com/LazyVim/LazyVim/blob/bb36f71b77d8e15788a5b62c82a1c9ec7b209e49/lua/lazyvim/plugins/lsp/init.lua#L218-L224

The only way around it as I have found it is to add [this](https://www.lazyvim.org/plugins/lsp#nvim-lspconfig) to my own LazyVim config but with the lines above removed/commented out, something I'd ideally like to avoid.

### Steps To Reproduce

1. Make sure you have the `denols` and `tsserver` LSPs installed.
2. Clone [my example repo](https://github.com/eriklindebratt/denols-and-tsserver).
3. Run `pnpm install` in the root directory.
4. Open `deno-scripts/my-deno-script.ts` in Neovim and check the output of `:LspInfo`. `denols` will be listed but as _not attached to buffer_.

(In my example repo I haven't explicitly added `deno.enablePaths` to any Neovim/LazyVim config but as I understanded it, Neoconf should pick it up from `.vscode/settings.json`. And running `:Neoconf lsp` in the workspace shows `deno.enablePaths` being applied from `.vscode/settings.json`.)

### Expected Behavior

1. Even without a `deno.json` file, the `denols` LSP should still remain enabled if `"deno.enablePaths": ["some/path"]` is set and it matches the current buffer.

2. Paths matching `deno.enablePaths` should disable the `tsserver` LSP.

Using VS Code and their TypeScript/Deno LSP extensions, both of these expected behaviors work.

**Comment by dpetka2001** [comment]
Maybe you could add an additional check in `is_deno` with `LazyVim.opts("nvim-lspconfig").servers.denols.settings.deno.enablePaths` to see if that option is enabled in the user's `nvim-lspconfig` configuration. If you could try that out and see if it's working for you, then maybe you could submit a PR that rectifies this behavior.

**Comment by eriklindebratt** [comment]
@dpetka2001 Thanks for the suggestion! Inspecting `LazyVim.opts("nvim-lspconfig").servers`, `denols` doesn't appear to be defined. I thought the config resolved from Neoconf would populate that?

**Comment by dpetka2001** [comment]
Yes, apparently it doesn't. `LazyVim.opts` only shows the options for the corresponding spec. Since, it's not defined in `nvim-lspconfig` spec it won't find it. I'm sorry, but I don't know how you can check it against Neoconf importing the `.vscode.settings.json`. Hopefully the maintainer will get back to you with a better solution.

**Comment by eriklindebratt** [comment]
Fixed in https://github.com/LazyVim/LazyVim/pull/3446.
