### ISSUE TITLE
feature: use blame.nvim instead of telescope blame 

### ISSUE THREAD

**Issue by DrummyFloyd** [LazyVim/LazyVim#3027]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

.

### Describe the solution you'd like

https://github.com/FabijanZulj/blame.nvim
not a blame to one line but full file like git command 

### Describe alternatives you've considered

.

**Comment by folke** [comment]
Feel free to add this to your own config. Not something that should be part of the core plugins.
