### ISSUE TITLE
bug: "Fix clangd offset encoding" doesn't work, still "utf-8" in C/C++ buffer

### ISSUE THREAD

**Issue by olatheander** [LazyVim/LazyVim#3028]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Arch Linux Kernel 6.8.7

### Describe the bug

I have wrestled quite a bit with the `warning: multiple different client offset_encodings detected for buffer, this is not supported yet` for `clang` and it seems like the fix suggested in [Fix clangd offset encoding](https://www.lazyvim.org/configuration/recipes#fix-clangd-offset-encoding) doesn't work.

I've added a bit of custom code to the fix to print the `opts` argument:
```
  {
    "neovim/nvim-lspconfig",
    opts = {
      setup = {
        clangd = function(_, opts)
          local function dump(o)
            local s = ""
            for a, b in ipairs(o) do
              s = s .. "(" .. a .. ", " .. b .. ")"
            end
            return s
          end
          print("clangd setup", dump(opts.capabilities.offsetEncoding))
          opts.capabilities.offsetEncoding = { "utf-16" }
          print("clangd setup", dump(opts.capabilities.offsetEncoding))
        end,
      },
    }
  }
```
which prints:
```
clangd setup (1, utf-16)
clangd setup (1, utf-16)
```
i.e. before and after and all looks good.

However, I also added a function and bound it to a key that basically mimic the Neovim code that issue the warning ([util.lua](https://github.com/neovim/neovim/blob/f42ab1dc4848eceab12c7180c2b9049da29a9ba6/runtime/lua/vim/lsp/util.lua#L2070-L2091)) but prints out the `offset_encoding` for all the clients and bound it to a which-key:
```
function PrintBufferDetails()
  print("Buffer details:")
  for _, buf in ipairs(vim.api.nvim_list_bufs()) do
    local offset_encoding
    local clients = vim.lsp.get_active_clients()
    for _, client in ipairs(clients) do
      if client ~= nil then
        local this_offset_encoding = client.offset_encoding
        if not offset_encoding then
          offset_encoding = this_offset_encoding
          print("Buffer ID: " .. buf .. " | Offset Encoding: " .. offset_encoding .. " | Client: " .. client.name)
        elseif offset_encoding ~= this_offset_encoding then
          print(
            "warning: multiple different client offset_encodings detected for buffer, this is not supported yet: "
              .. offset_encoding
              .. " | "
              .. this_offset_encoding
              .. " | Client: "
              .. client.name
          )
        end
      end
    end
  end
end

return {
  {
    "folke/which-key.nvim",
    opts = {
      defaults = {
        ["<leader>"] = {
          e = { "<cmd>lua PrintBufferDetails()<cr>", "PrintBufferDetails" },
        },
      },
    },
  },
}
```
Opening a `.c` file and then issue this command I get:
```
Buffer details:
Buffer ID: 2 | Offset Encoding: utf-8 | Client: clangd
Buffer ID: 3 | Offset Encoding: utf-8 | Client: clangd
Buffer ID: 4 | Offset Encoding: utf-8 | Client: clangd
Buffer ID: 6 | Offset Encoding: utf-8 | Client: clangd
Buffer ID: 7 | Offset Encoding: utf-8 | Client: clangd
```
Thus, for some reason the encoding is `utf-8` and not the expected `utf-16`.

If I then go into insert mode to edit the conflict with CoPilot kicks in and I see in messages (after re-issuing the command via the key binding):
```
Buffer details:
Buffer ID: 2 | Offset Encoding: utf-8 | Client: clangd
warning: multiple different client offset_encodings detected for buffer, this is not supported yet: utf-8 | utf-16 | Client: copilot
Buffer ID: 3 | Offset Encoding: utf-8 | Client: clangd
warning: multiple different client offset_encodings detected for buffer, this is not supported yet: utf-8 | utf-16 | Client: copilot
Buffer ID: 4 | Offset Encoding: utf-8 | Client: clangd
warning: multiple different client offset_encodings detected for buffer, this is not supported yet: utf-8 | utf-16 | Client: copilot
...
..
```

### Steps To Reproduce

1. Enable the `lazyvim.plugins.extras.coding.copilot` and `lazyvim.plugins.extras.lang.clangd` in `lazy.lua`:
1. Apply the [Fix clangd offset encoding](https://www.lazyvim.org/configuration/recipes#fix-clangd-offset-encoding) fix.
1. Apply the custom function and keybinding to which-key.
1. Open a `.c/.cpp` file and issue the command (`<leader>e`).
1.  Go into insert-mode to provoke the warning `multiple different client offset_encodings detected for buffer, this is not supported yet` is issued. 
1. Re-issue the command to get the new printout.

### Expected Behavior

`utf-16` to be configured for Clangd.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
require("lazy").setup({
  spec = {
    -- add LazyVim and import its plugins
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- import any extras modules here
    { import = "lazyvim.plugins.extras.coding.copilot" },
    { import = "lazyvim.plugins.extras.lang.clangd" },
    -- import/override with your plugins
    { import = "plugins" },
  },
  },
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
I believe you don't need to apply the fix if you use the LazyExtra clangd. It's already included.

**Comment by olatheander** [comment]
I may add that the only working solution I've found so far is the rather hackish [solution](https://github.com/neovim/nvim-lspconfig/issues/2184#issuecomment-1511154286) of tweaking LspConfig's `clangd.lua` file directly to remove the `utf-8` entry but then I run into other problems when trying to update with Lazy (of if it's Mason complaning) that discovers that the file been tampered with and display an error.

**Comment by dpetka2001** [comment]
I don't use copilot but i tried with your function keybinding and it shows utf-16 to me when i open a c file.

**Comment by olatheander** [comment]
@dpetka2001 hmm, really interesting. For clangd I presume?

The thing is that it seems like CoPilot is just causing the conflict to appear so it's not necessary for the problem. If I only open a `.c` file without going into insert mode, CoPilot is not yet activate. I.e. `LspInfo` gives:
```
 1 client(s) attached to this buffer: 
 
 Client: clangd (id: 1, bufnr: [7])
 	filetypes:       c, cpp, objc, objcpp, cuda, proto
 	autostart:       true
 	root directory:  /home/olathe/Git/Karpathy/llm.c
 	cmd:             /home/olathe/.local/share/nvim/mason/bin/clangd
 
 Configured servers list: marksman, jsonls, yamlls, eslint, texlab, tsserver, lua_ls, clangd
```
and then triggering my function gives:
```
Buffer details:
Buffer ID: 2 | Offset Encoding: utf-8 | Client: clangd
Buffer ID: 3 | Offset Encoding: utf-8 | Client: clangd
Buffer ID: 4 | Offset Encoding: utf-8 | Client: clangd
Buffer ID: 7 | Offset Encoding: utf-8 | Client: clangd
```
I take it you have `utf-16` given the same scenario? Very peculiar.

**Comment by olatheander** [comment]
Thanks, I try and start over with a totally clean LazyVim config and see what happens.

**Comment by dpetka2001** [comment]
Related screencast

[Screencast 2024-04-21 18:05:25.webm](https://github.com/LazyVim/LazyVim/assets/12776461/257bbb14-b914-43b6-bcc9-2f0f26c18e7e)

**Comment by dpetka2001** [comment]
Please keep in mind this is a new installation with LazyVim default settings. I also tried it with my personal configuration and didn't encounter any problems. I just showed the one with LazyVim default settings, as I wanted to ensure that the default LazyVim installation encountered the problem or not.

**Comment by olatheander** [comment]
Thanks, noticed the command `LazyVim.opts("nvim-lspconfig").servers.clangd` but that doesn't work for me. Getting an error:
```
E5107: Error loading lua [string ":lua"]:1: '=' expected near '<eof>'
```
but maybe I'm doing something wrong.

**Comment by dpetka2001** [comment]
The actual command as I typed it is `:=LazyVim.opts("nvim-lspconfig").servers.clangd`, but noice doesn't show it all as I typed it.

**Comment by olatheander** [comment]
@dpetka2001 Thanks, now the command worked. But peculiar enough I get:
```
{
  capabilities = {
    offsetEncoding = { "utf-16" }
  },
  cmd = { "/home/<user>/.local/share/nvim/mason/bin/clangd", "--background-index", "--clang-tidy", "--header-insertion=iwyu", "--completion-style=detailed", "--function-arg-placeholders", "--fallback-style=llvm" },
  init_options = {
    clangdFileStatus = true,
    completeUnimported = true,
    usePlaceholders = true
  },
  keys = { { "<leader>cR", "<cmd>ClangdSwitchSourceHeader<cr>",
      desc = "Switch Source/Header (C/C++)",
      mode = "n"
    } },
  root_dir = <function 1>
}
```
i.e. `offsetEncoding = { "utf-16" }` :thinking:.

**Comment by dpetka2001** [comment]
Yes, that's what I get as well. Why is it peculiar? It's the default value in the clangd LazyExtra. This command returns the values of clangd as it is configured in `nvim-lspconfig`.

**Comment by olatheander** [comment]
It's peculiar since I get `utf-16` with that command but still have the conflict and `utf-8` with my `PrintBufferDetails` command. Why isn't it consistent?

**Comment by dpetka2001** [comment]
Did you try with a default LazyVim installation? Enable only clangd and copilot extras with no other changes.

**Comment by olatheander** [comment]
Will do that now and gradually move over my config to see if I can circle in what's causing this.

**Comment by olatheander** [comment]
OK, a clean installation behave as expected with `utf-16`. Will rebuild now and see if I can find the culprit.

**Comment by dpetka2001** [comment]
If the default LazyVim installation from your testing doesn't reproduce this problem, then we can safely assume it's not a LazyVim bug and the issue can be closed?

**Comment by olatheander** [comment]
Yep, the issue can be closed but in case someone stumble over a similar issue, the problem turned out to be the `kevinhwang91/nvim-ufo` plugin's configuration. A section of the plug-in's `config` do:
```
...
..
      -- Tell the server the capability of foldingRange,
      -- Neovim hasn't added foldingRange to default capabilities, users must add it manually
      local capabilities = vim.lsp.protocol.make_client_capabilities()
      capabilities.textDocument.foldingRange = {
        dynamicRegistration = false,
        lineFoldingOnly = true,
      }
      local language_servers = require("lspconfig").util.available_servers() -- or list servers manually like {'gopls', 'clangd'}
...
..
```
Have to investigate why that cause the `utf-8` to be enforced (probably being the default) but a simple fix was to add `capabilities.offsetEncoding = { "utf-16" }`:
```
      -- Tell the server the capability of foldingRange,
      -- Neovim hasn't added foldingRange to default capabilities, users must add it manually
      local capabilities = vim.lsp.protocol.make_client_capabilities()
      capabilities.textDocument.foldingRange = {
        dynamicRegistration = false,
        lineFoldingOnly = true,
      }
      capabilities.offsetEncoding = { "utf-16" }
      local language_servers = require("lspconfig").util.available_servers() -- or list servers manually like {'gopls', 'clangd'}
```

**Comment by dpetka2001** [comment]
Maybe you would like to mention that in the plugin's repo, so corresponding documentation could be added in order to avoid this problem.

**Comment by dpetka2001** [comment]
It seems that `vim.lsp.protocol.make_client_capabilities` returns a new object with the default capabilities of LSP servers. 

I don't use `nvim-ufo` any more, but this is how I had it configured when I used it (see [here in my dots](https://github.com/dpetka2001/dotfiles/blob/2d65a389abb6d39115e7b5f21f553912ead21edb/dot_config/nvim/lua/plugins/folding.lua#L31-L44)). This way it doesn't override the LSP server capabilities, but rather extend them to also include the necessary part about `foldingRange`. 

If you took a similar approach, I believe you wouldn't have any problems. And this way you don't mess with `offsetEncoding` and just leave it up to each LSP server's capabilities to use whatever it's configured to use. Because your solution changes `offsetEncoding` for all available LSP servers.

**Comment by olatheander** [comment]
Thanks, I write something in the UFO's repo.

**Comment by olatheander** [comment]
I improved on the fix for nvim-ufo a bit so that the `offsetEncoding` doesn't affect all servers. A bit further down in ufo's officially recommended config the language servers are looped so I simply added an if-statement for the encoding for clangd:
```
      local capabilities = vim.lsp.protocol.make_client_capabilities()
      capabilities.textDocument.foldingRange = {
        dynamicRegistration = false,
        lineFoldingOnly = true,
      }
      local language_servers = require("lspconfig").util.available_servers() -- or list servers manually like {'gopls', 'clangd'}
      for _, ls in ipairs(language_servers) do
        if ls == "clangd" then
          capabilities.offsetEncoding = { "utf-16" }
        end
        require("lspconfig")[ls].setup({
          capabilities = capabilities,
          -- you can add other fields for setting up lsp server in this table
        })
...
..
```
