### ISSUE TITLE
Bufferline not anymore working in LazyVim

### ISSUE THREAD

**Issue by juridiener** [LazyVim/LazyVim#3041]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1335+g840e1864c

### Operating system/version

MacOS

### Describe the bug

After updating the plugins in Lazy with U
I get now following error and can not use bufferline properly anymore: 

E5108: Error executing lua ...share/LazyVim/lazy/bufferline.nvim/lua/bufferline/ui.lua:119: attempt to call field 'is_list' (a nil value)
stack traceback:
	...share/LazyVim/lazy/bufferline.nvim/lua/bufferline/ui.lua:119: in function 'get_component_size'
	...share/LazyVim/lazy/bufferline.nvim/lua/bufferline/ui.lua:480: in function <...share/LazyVim/lazy/bufferline.nvim/lua/bufferline/ui.lua:461>
	vim/shared.lua: in function 'get_components'
	...al/share/LazyVim/lazy/bufferline.nvim/lua/bufferline.lua:56: in function <...al/share/LazyVim/lazy/bufferline.nvim/lua/bufferline.lua:54>
	[C]: in function 'ui_attach'
	...ocal/share/LazyVim/lazy/noice.nvim/lua/noice/ui/init.lua:74: in function 'enable'
	.../.local/share/LazyVim/lazy/noice.nvim/lua/noice/init.lua:61: in function 'enable'
	.../.local/share/LazyVim/lazy/noice.nvim/lua/noice/init.lua:23: in function <.../.local/share/LazyVim/lazy/noice.nvim/lua/noice/init.lua:19>
	[C]: in function 'xpcall'
	...al/share/LazyVim/lazy/noice.nvim/lua/noice/util/call.lua:149: in function 'try'
	.../.local/share/LazyVim

### Steps To Reproduce

open a directory with nvim .

### Expected Behavior

No errors when openning LazyVim

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
Update your Neovim.

**Comment by juridiener** [comment]
Thanks. I close the issue.

**Comment by VipinDevelops** [comment]
Hey @dpetka2001, I am experiencing the same problem on my Ubuntu machine. As you suggested, I tried updating my nvim to the version: NVIM v0.10.0-dev, However, I am still encountering this issue.

**Comment by dpetka2001** [comment]
What does `nvim --version` show?

**Comment by VipinDevelops** [comment]
> What does `nvim --version` show?

@dpetka2001  
``` ➜ nvim --version
NVIM v0.10.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info

```

**Comment by VipinDevelops** [comment]
``` ➜ nvim -V1 -v 
NVIM v0.10.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -ffile-prefix-map=/build/neovim-ee5fnR/neovim-0.10.0~ubuntu1+git202401242104-b280d57db-862fdbd52=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -fdebug-prefix-map=/build/neovim-ee5fnR/neovim-0.10.0~ubuntu1+git202401242104-b280d57db-862fdbd52=/usr/src/neovim-0.10.0~ubuntu1+git202401242104-b280d57db-862fdbd52-c148bd039~ubuntu23.04.1 -O2 -g -Og -g -flto=auto -fno-fat-lto-objects -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fsigned-char -fstack-protector-strong -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=auto  -DUNIT_TESTING -DHAVE_UNIBILIUM -D_GNU_SOURCE -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_TS_HAS_SET_MAX_START_DEPTH -I/usr/include/luajit-2.1 -I/build/neovim-ee5fnR/neovim-0.10.0~ubuntu1+git202401242104-b280d57db-862fdbd52/.deps/usr/include -I/build/neovim-ee5fnR/neovim-0.10.0~ubuntu1+git202401242104-b280d57db-862fdbd52/build/src/nvim/auto -I/build/neovim-ee5fnR/neovim-0.10.0~ubuntu1+git202401242104-b280d57db-862fdbd52/build/include -I/build/neovim-ee5fnR/neovim-0.10.0~ubuntu1+git202401242104-b280d57db-862fdbd52/build/cmake.config -I/build/neovim-ee5fnR/neovim-0.10.0~ubuntu1+git202401242104-b280d57db-862fdbd52/src -I/usr/include 

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by dpetka2001** [comment]
You're on an old version from 24/01/2024. That's why you get the error. I don't know how you installed or update Neovim, but I use [bob](https://github.com/MordechaiHadad/bob) and you can easily switch between stable and nightly (and even HEAD) version easily.

**Comment by VipinDevelops** [comment]
Hey @dpetka2001  Thanks a lot for helping me out I was using standard `apt-get install neovim` to update it so removed that and installed following [this docs](https://github.com/neovim/neovim/blob/master/INSTALL.md)

**Comment by dpetka2001** [comment]
You can choose whatever you want to install Neovim. My personal favorite is `bob` as I mentioned in my previous comment because I can easily switch between versions with just doing `bob use nightly` or `bob use stable`.

**Comment by JosueIsOffline** [comment]
What is the latest version?

**Comment by dpetka2001** [comment]
You can find the latest [nightly here](https://github.com/neovim/neovim/releases/tag/nightly) and it gets updated every 1-2 days.

**Comment by juridiener** [comment]
One question, how you guys are updating neovim? Is there a good solution? I had to remove neovim and then install it again. Not quit the best solution in my opinion.
