### ISSUE TITLE
feature: When a prompt is triggered while typing, the prompt panel appears transparent. Is it possible to add an option to prevent it from becoming transparent?

### ISSUE THREAD

**Issue by czfadmin** [LazyVim/LazyVim#3063]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

When a prompt is triggered while typing, the prompt panel appears transparent. Is it possible to add an option to prevent it from becoming transparent?
At the same time, it is also transparent on the file explorer.

### Describe the solution you'd like

Add an option to prevent it from becoming transparent

### Describe alternatives you've considered

The prompt becomes transparent when typing on the keyboard
![image](https://github.com/LazyVim/LazyVim/assets/13393959/e437a07c-e1c3-4713-b5d3-c378fd6fba07)

**Comment by folke** [comment]
Check `:h 'pumblend'`. You can configure it to your liking in `options.lua`

**Comment by czfadmin** [comment]
@folke thank you for your help
