### ISSUE TITLE
bug: mason.nvim stopped working

### ISSUE THREAD

**Issue by esau-morais** [LazyVim/LazyVim#3065]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0-dev

### Operating system/version

Ubunutu 22

### Describe the bug

when trying to use :Mason, it returns 

```bash
  Registry installation failed with the following error:
    GitHubRegistrySource(repo=mason-org/mason-registry) failed to install: Failed to fetch latest registry version from GitHub API.
```

![image](https://github.com/LazyVim/LazyVim/assets/55207584/54fd64b6-e5bc-4b47-b7ca-265cf1657234)

### Steps To Reproduce

1. Type `:Mason`
2. See error

### Expected Behavior

Mason should work properly

**Comment by dpetka2001** [comment]
Update Neovim

**Comment by esau-morais** [comment]
it is already up to date based on the unstable version

**Comment by esau-morais** [comment]
this was due to the neovim unstable version, i installed the stable version and it's all good now

https://github.com/williamboman/mason.nvim/discussions/1113#discussioncomment-9227149 helped me

**Comment by dpetka2001** [comment]
The latest nightly that got released today fixed the issue.

**Comment by esau-morais** [comment]
> The latest nightly that got released today fixed the issue.

thank you, it worked as well
