### ISSUE TITLE
bug: Got unexpected error while installing LazyVim on WSL

### ISSUE THREAD

**Issue by BennisonDevadoss** [LazyVim/LazyVim#3072]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

WSL ubuntu 22

### Describe the bug

I am new to LazyVim and Lua, While setting up the Lazzy Vim on my WSL I got the exception. It seems this issue is related to Lua, but I am not sure.

Here I have attached the exception snapshot for reference.
![image](https://github.com/LazyVim/LazyVim/assets/89965371/d9b962c8-b384-48b0-a892-cad9a36e255a)
![image](https://github.com/LazyVim/LazyVim/assets/89965371/bc4fc7f5-e4cd-4dcf-924e-d7c50fc3c6fb)

Could anyone help me to resolve this problem?

### Steps To Reproduce

Need to follow the installation step.

1. mv ~/.config/nvim{,.bak}
2. mv ~/.local/share/nvim{,.bak}
3. mv ~/.local/state/nvim{,.bak}
4. mv ~/.cache/nvim{,.bak}
5. git clone https://github.com/LazyVim/starter ~/.config/nvim
6. rm -rf ~/.config/nvim/.git
7. nvim

### Expected Behavior

Should run without error, as expected.

**Comment by dpetka2001** [comment]
This seems to be similar to https://github.com/folke/lazy.nvim/pull/1055. It's not a LazyVim bug. Try to set in your git config `autocrlf = false`.

**Comment by BennisonDevadoss** [comment]
@dpetka2001. Even I tried LazyVim installation after change some git configs to `git config --global core.autocrlf true`. I got the same problem.

**Comment by dpetka2001** [comment]
`autocrlf` should be set to `false` not `true`. This is not a LazyVim bug. This is a problem with Neovim itself. Just don't set this git global to true. Or set it to `false` temporarily to download and install LazyVim and then set it back to `true` again. But whenever you want to install or update plugins it should be set to `false`. The issue that I linked has detailed information about this problem.

**Comment by BennisonDevadoss** [comment]
@dpetka2001 , Thanks for your help, now I have installed it successfully.
