### ISSUE TITLE
feature: Add YAML schema selection functionality to YAML extra

### ISSUE THREAD

**Issue by liamwh** [LazyVim/LazyVim#3075]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Sometimes the incorrect YAML schema is automatically selected, which causes errors to show which aren't correct.

### Describe the solution you'd like

In this scenario, it would be great to have the functionality to select the YAML schema manually. It would also be nice to add some information to the statusbar showing which schema is currently being used.

Perhaps something like: https://github.com/someone-stole-my-name/yaml-companion.nvim.git

### Describe alternatives you've considered

Looked if there was a way to do it with the current plugins for the YAML lazy extra but did not determine a solution on my own

**Comment by dpetka2001** [comment]
Related #2907

**Comment by folke** [comment]
https://github.com/LazyVim/LazyVim/pull/2907#issuecomment-2150180952
