### ISSUE TITLE
 Has the keymap `<leader>uh` been removed? How do I get the Inlay Hints feature?

### ISSUE THREAD

**Issue by WindChim1** [LazyVim/LazyVim#3079]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

macos

### Describe the bug

 After updating my lazyVim locally, I noticed that the Inlay Hints feature is missing, and although the official documentation has a mapping to enable it, it doesn't work!
 
<img width="666" alt="image" src="https://github.com/LazyVim/LazyVim/assets/133325208/ff5b1902-f151-4b42-b6f8-c7bd2491424c">

### Steps To Reproduce

1. update LazyVIm
2. use mapping  `<leader>uh`

### Expected Behavior

Inlay Hints function works fine

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
In the [docs](https://www.lazyvim.org/plugins/lsp#nvim-lspconfig) it says 
> -- Enable this to enable the builtin LSP inlay hints on Neovim >= 0.10.0
  -- Be aware that you also will need to properly configure your LSP server to
  -- provide the inlay hints.
  inlay_hints = {
    enabled = false,
  },

You use Neovim 0.9.4, but inlay hints are natively available on Neovim >=0.10.0
