### ISSUE TITLE
feature: Automatically reload config when change in any files is detected

### ISSUE THREAD

**Issue by Rizhiy** [LazyVim/LazyVim#308]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Whenever I make a change to my configuration, I have to restart my whole neovim to see if it works right.

### Describe the solution you'd like

If a file inside `nvim` directory is changed, `lazyvim` should reload configuration.

### Describe alternatives you've considered

I tried to make a keybinding to reload config manually, but couldn't manage to get it to work.
With vimscript I could just do `:source $MYVIMRC<CR>`, but with lua there appears to be some caching going on, so it is not as simple. Therefore, I think it would be a good addition to put it as autocommand.

**Comment by folke** [comment]
This is already tracked in the lazy.nvim repo

**Comment by Rizhiy** [comment]
@folke Then it is not working

**Comment by folke** [comment]
I didn't say it was implemented yet. It's tracked in https://github.com/folke/lazy.nvim/issues/445

**Comment by Rizhiy** [comment]
Ok, I thought you meant that changes are already tracked.

**Comment by kuvaldini** [comment]
@folke @Rizhiy 
3 yrs later, yep config files are **tracked** and changes reported in notification, and **never applied**.
