### ISSUE TITLE
bug: new fresh install on windows hangs at Treesitter compilation step with zig

### ISSUE THREAD

**Issue by seccentral** [LazyVim/LazyVim#3086]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.5 commit

### Operating system/version

Microsoft Windows [Version 10.0.22631.3447] (11 23H2)

### Describe the bug

I'm new to nvim so i did a lot of testing and distro experimenting. Settled on lazyvim but nuked my conf often to just start from scratch and learn or just redo everything because I messed it up completely. 
So I know for a fact that this used to work just fine and is a recent problem (1 week or so at most)

Here's how nvim looks like with all compile tasks just taking space : 
![image](https://github.com/LazyVim/LazyVim/assets/3766320/3fc9022a-fc01-4df4-b269-a6086ef93eb2)

here's the details on one of them : 
zig c++ -o parser.so src/parser.c -lc -Isrc -shared -Os
Current directory: "C:\Users\User\AppData\Local\nvim-data\tree-sitter-json\" (this is just one, others are obviously stuck within their own respective workding directories, so this is not a "tree-sitter-json" problem, that just happens to be the current thing.

### Steps To Reproduce

Install nvim, install zig, add it to path, git clone lazygit, launch nvim, observe the intial setup: 
- notice that for as long as the toast notification in the upper right corner stays active, the amount of zig compile taks in the background run. The moment that notification dissapears (or because it dissapears, who knows) nothing else happens and the list of processes just show a bunch of zigs sitting idly. They never complete the initial build

This also happens on concurrent updates which trigger multiple zig recompiles. 
This is also workaround(ed) by closing nvim, starting it again and repeating that for as many times as it takes since each run manages to finish compiling one or two tasks. (6-7 runs is enough on my machine) 

### Expected Behavior

The compile step should run through all taks successfuly and display a completion notification starting with 1/n up to n/n and there should be no zig processes idling in the background 

### Repro
just start fresh , clone lazyvim and launch nvim.

**Comment by dpetka2001** [comment]
This is a problem with the compiler you use in your OS and treesitter and should be best reported in `nvim-treesitter` repo. I have LazyVim installed on Windows and installed clang via chocolatey (as described in treesitter [docs](https://github.com/nvim-treesitter/nvim-treesitter/wiki/Windows-support#llvm-clang) and all the parsers compiled successfully. Not a LazyVim bug.

**Comment by seccentral** [comment]
i see, so i should repost this to treesitter's git. thanks

**Comment by seccentral** [comment]
this is just too "cute" https://github.com/nvim-treesitter/nvim-treesitter/issues/6545#issuecomment-2088422366 but hey, i tried

**Comment by dpetka2001** [comment]
I have LazyVim installed on Windows with clang as compiler and the parsers get installed correctly. Maybe try with clang instead of zig. Again, this is not a LazyVim bug.
