### ISSUE TITLE
bug: neo-tree does not make directory current working directory when I click . on that directory

### ISSUE THREAD

**Issue by monoira** [LazyVim/LazyVim#3088]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

EndeavourOS Linux x86_64

### Describe the bug

in other distributions like Astronvim and NvChad, when you press . on a directory when neo-tree is open, you automatically enter & cd into that directory and that directory becomes current working directory.

this is not case with LazyVim. this seems to be more of a LazyVim issue? because I deleted
 ~/.config/nvim && rm -rf ~/.local/share/nvim/ && rm -rf ~/.cache/nvim
 
and tried fresh install but it still doesn't cd into that directory upon . press.
 
 this is my lua/plugins/neo-tree.lua:
 
```lua
return {
  "nvim-neo-tree/neo-tree.nvim",

  opts = {
    sources = { "filesystem", "buffers", "git_status", "document_symbols" },
    open_files_do_not_replace_types = {
      "terminal",
      "Trouble",
      "trouble",
      "qf",
      "Outline",
    },
    filesystem = {
      bind_to_cwd = true,
      follow_current_file = { enabled = true },
      use_libuv_file_watcher = true,

      filtered_items = {
        visible = true,
        show_hidden_count = true,
        hide_dotfiles = false,
        hide_gitignored = false,
        hide_by_name = {
          ".git",
          ".DS_Store",
          "thumbs.db",
        },
        never_show = {},
      },
    },
    window = {
      mappings = {
        ["<space>"] = "none",
        ["Y"] = {
          function(state)
            local node = state.tree:get_node()
            local path = node:get_id()
            vim.fn.setreg("+", path, "c")
          end,
          desc = "Copy Path to Clipboard",
        },
        ["O"] = {
          function(state)
            require("lazy.util").open(
              state.tree:get_node().path,
              { system = true }
            )
          end,
          desc = "Open with System Application",
        },
      },
    },
    default_component_configs = {
      indent = {
        with_expanders = true, -- if nil and file nesting is enabled, will enable expanders
        expander_collapsed = "",
        expander_expanded = "",
        expander_highlight = "NeoTreeExpander",
      },
    },
  },
}
```
I have tried playing with neo-tree's set_root, using it without dedicated file, but ultimately I am beginner and I can only do so much.

I have project.nvim and vim.g.root_spec set right but sometimes I want to cd into empty directory with . and with there being no pattern items, I have to do that manually, which is painful :(

Here is my whole neovim config github: https://github.com/monoira/neovim_repo

### Steps To Reproduce

- install LazyVim
- press . on directory or file in opened neo-tree
- current working directory that you can print out with :pwd doesn't change and on neo-tree close & open, my current working directory is where I was before pressed . on directory or file.

### Expected Behavior

I expected :pwd to change when I press . on directory or a file

**Comment by dpetka2001** [comment]
LazyVim has in neo-tree spec the option `opts.filesystem.bind_to_cwd = false`. You should change that to `true` in your personal configuration to achieve what you want.

**Comment by monoira** [comment]
I changed that and it still doesn't work. I tried disabling project.nvim and commenting out vim.g.root_spec too but . thing still doesn't work.

 here is my current neo-tree.lua:
 
 
 return {
  "nvim-neo-tree/neo-tree.nvim",
  branch = "v3.x",
  cmd = "Neotree",
  keys = {
    {
      "<leader>fe",
      function()
        require("neo-tree.command").execute({
          toggle = true,
          dir = LazyVim.root(),
        })
      end,
      desc = "Explorer NeoTree (Root Dir)",
    },
    {
      "<leader>fE",
      function()
        require("neo-tree.command").execute({
          toggle = true,
          dir = vim.uv.cwd(),
        })
      end,
      desc = "Explorer NeoTree (cwd)",
    },
    {
      "<leader>e",
      "<leader>fe",
      desc = "Explorer NeoTree (Root Dir)",
      remap = true,
    },
    {
      "<leader>E",
      "<leader>fE",
      desc = "Explorer NeoTree (cwd)",
      remap = true,
    },
    {
      "<leader>ge",
      function()
        require("neo-tree.command").execute({
          source = "git_status",
          toggle = true,
        })
      end,
      desc = "Git Explorer",
    },
    {
      "<leader>be",
      function()
        require("neo-tree.command").execute({

          source = "buffers",

          toggle = true,
        })
      end,

      desc = "Buffer Explorer",
    },
  },

  deactivate = function()
    vim.cmd([[Neotree close]])
  end,

  init = function()
    if vim.fn.argc(-1) == 1 then
      local stat = vim.uv.fs_stat(vim.fn.argv(0))

      if stat and stat.type == "directory" then
        require("neo-tree")
      end
    end
  end,

  opts = {

    sources = { "filesystem", "buffers", "git_status", "document_symbols" },

    open_files_do_not_replace_types = {

      "terminal",

      "Trouble",

      "trouble",

      "qf",

      "Outline",
    },

    filesystem = {

      filtered_items = {

        visible = true,

        show_hidden_count = true,

        hide_dotfiles = false,

        hide_gitignored = false,

        hide_by_name = {

          ".git",

          ".DS_Store",

          "thumbs.db",
        },

        never_show = {},
      },

      bind_to_cwd = true,

      follow_current_file = { enabled = true },

      use_libuv_file_watcher = true,
    },

    window = {

      mappings = {

        ["<space>"] = "none",

        ["Y"] = {

          function(state)
            local node = state.tree:get_node()

            local path = node:get_id()

            vim.fn.setreg("+", path, "c")
          end,

          desc = "Copy Path to Clipboard",
        },

        ["O"] = {

          function(state)
            require("lazy.util").open(state.tree:get_node().path, { system = true }
)
          end,

          desc = "Open with System Application",
        },
      },
    },

    default_component_configs = {

      indent = {

        with_expanders = true, -- if nil and file nesting is enabled, will enable expanders

        expander_collapsed = "",

        expander_expanded = "",

        expander_highlight = "NeoTreeExpander",
      },
    },
  },

  config = function(_, opts)
    local function on_move(data)
      LazyVim.lsp.on_rename(data.source, data.destination)
    end

    local events = require("neo-tree.events")

    opts.event_handlers = opts.event_handlers or {}

    vim.list_extend(opts.event_handlers, {

      { event = events.FILE_MOVED, handler = on_move },

      { event = events.FILE_RENAMED, handler = on_move },
    })

    require("neo-tree").setup(opts)

    vim.api.nvim_create_autocmd("TermClose", {

      pattern = "*lazygit",

      callback = function()
        if package.loaded["neo-tree.sources.git_status"] then
          require("neo-tree.sources.git_status").refresh()
        end
      end,
    })
  end,
}

**Comment by dpetka2001** [comment]
After you change directory with `.` (set_root) you should use `<leader>E` which is for `cwd` instead of `<leader>e` which is for root_dir.
