### ISSUE TITLE
NeoTree & Telescope open in wrong CWD

### ISSUE THREAD

**Issue by juridiener** [LazyVim/LazyVim#3090]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2982+gea1c9f60e

### Operating system/version

MacoS

### Describe the bug

Hello, if i open a spesific directory it falls back always to the root kinda. So i opened in my terminal nvim joomla. The first time the file browser shows the right directory, then i press leader e or E to close and reopen, then it shows me everything above too  and in telescope i got not the find files picker but instead the git files. I don't know if I'm doing something wrong or is this the normal behavoir?? 
<img width="446" alt="Screenshot 2024-05-02 at 10 50 17" src="https://github.com/LazyVim/LazyVim/assets/92093874/72508914-2efd-4d13-bbde-7b896568bb60">
<img width="1591" alt="Screenshot 2024-05-02 at 10 50 50" src="https://github.com/LazyVim/LazyVim/assets/92093874/f3eec954-2fa6-4f0a-84c6-1fd312e4feac">

### Steps To Reproduce

Open a spesific directory with nvim folder,
press leader e twice
press leader ff

### Expected Behavior

Open neo-tree only in that folder as cwd
set that folder as cwd for telescope

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
You should use `<leader>E` and `<leader>fF` which are the corresponding keymaps for opening in `cwd` instead of `root_dir`.

**Comment by juridiener** [comment]
I just tried it but it still behaves the same way

**Comment by dpetka2001** [comment]
Yes in `options.lua` file.

**Comment by juridiener** [comment]
Ok i tried it out, but it still behaves the same...

**Comment by dpetka2001** [comment]
I don't understand what you're saying. It behaves correctly for me. Can you explain what exactly you're doing?

**Comment by jinwood** [comment]
I have (had) this problem and added @dpetka2001 's fix which has worked for me. Thanks

**Comment by juridiener** [comment]
Like in the video. If i open on the first time neovim, it shows me the right folder if i close and reopen it shows me all the folders... 

https://github.com/LazyVim/LazyVim/assets/92093874/b2af30f7-ebc8-49ba-b193-fbb1b486dccf

**Comment by dpetka2001** [comment]
Just make a new keymap for neo-tree that executes `Neotree toggle`.

**Comment by juridiener** [comment]
Ok this worked if i do Neotree toggle. And what about telescope, how do I get it to only search the folder and subfolders I'm in?

**Comment by dpetka2001** [comment]
The current working directory `cwd` is the one that you invoke Neovim. Not the file/directory argument that you pass to Neovim. So, if you want to search from a specific directory downwards, you should invoke Neovim in the specific directory that you want.

**Comment by dpetka2001** [comment]
Do the following test if you'd like. `nvim --clean joomla/` and then inside Neovim (which will open as vanilla Neovim without plugins and configuration) do `:pwd`. You'll see that it the directory from where you invoked Neovim. This is default Neovim behavior.
