### ISSUE TITLE
LazyVim Profile, maybe something is wrong?

### ISSUE THREAD

**Issue by juridiener** [LazyVim/LazyVim#3093]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2982+gea1c9f60e

### Operating system/version

MacOS

### Describe the bug

I saw on reddit a post, where some people showing there profiles. 
This is mine:
    LazyStart 16.79ms
    LazyDone  486.56ms (+469.77ms)
    UIEnter   526.77ms (+40.21ms)
    
   I mean is this normal or is it way to much? 

### Steps To Reproduce

Press: leder l 
Press: P

### Expected Behavior

Maybe less time.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
This is totally dependent on your hardware. Also, this kind of questions are more appropriate for the Discussions section and not bug issues.

**Comment by juridiener** [comment]
Sorry i move this question, thanks for repliying.
