### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by samerickson** [LazyVim/LazyVim#3099]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev-2854+g49983387f

### Operating system/version

Windows 11

### Describe the bug

Given I have launched neovim from the terminal, and are viewing a file. When  I attempt to close the file using `ZZ` then UI remains visible until I press another key (can be any key).

Interestingly, the UI also hangs using `<leader>qq` until I press another key.

I checked with `nvim --clean` and the UI does not hang in that case.

Additionally, I tried this with windows terminal and wezterm and the issue persists on both terminals.

### Steps To Reproduce

1. Launch neovim with lazyVim installed from the terminal
2. Press `ZZ` or `<leader>qq`
3. See neovim not close (until you press another key)

### Expected Behavior

I expect lazyVim to quit right away without needing an additional button press.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by samerickson** [comment]
I can work on finding the minimal reproduction, so far I know that it exists in the base installation outlined here: https://www.lazyvim.org/installation

**Comment by folke** [comment]
This must be something in your installation. Closing LazyVim obviously works for thousands of people. Closing...

**Comment by samerickson** [comment]
Okay, I tried this on a few of my machines, and the issue was only present on the Windows one. Leading me to believe that this is only an issue for Windows users. Except nuking my config folder and the `nvim-data` caused the issue to disappear. So I tried just deleting my configuration files and I finally got the following error:

![image](https://github.com/LazyVim/LazyVim/assets/9330283/f6c9eaa1-6648-4d71-bba3-e2df9425bea0)

This appears to be a long-standing issue with `neovim` itself. https://github.com/neovim/neovim/issues/8587 and sure enough I had all 26 shada files in my `shada` folder: 

![image](https://github.com/LazyVim/LazyVim/assets/9330283/81cc5926-93bf-41ae-a822-180001660e98)

Deleting one of them would cause the issue to go away (I need to do some more reading on what shada files are but it looks like you can either delete these files when this issue shows up or disable shada files entirely: https://vi.stackexchange.com/questions/9570/how-do-i-shadont)

The one annoying bit is something in the LazyVim configuration files that prevents me from seeing that error for some reason. To look into this I tried manually creating all the `shada` files as empty text files and the initial issue shows back up. So now I just need to figure out what is hiding the error. I agree this issue should be closed I can log the hidden error message is whatever project makes sense when I have time to track it down.

**Comment by axelhj** [comment]
I see the same issue, also on Windows 11. I don't run LazyVim but I assume you removed it by deleting nvim-data & config-folders. I get the 26 tmp-files and the prompt on quit. I guess the only information that might give is that it is not specific to LazyVim but potentially specific to Windows.

**Comment by folke** [comment]
IT is a Windows thing. I actually noticed it yesterday and made some changes to Noice, so that you could actally see that error. Not straightforward, since that's during exit
