### ISSUE TITLE
feature: Toggle ruby blocks

### ISSUE THREAD

**Issue by deniciocode** [LazyVim/LazyVim#3112]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

When programming in `ruby` we as developers needs to swap from `{ }` to `do-end` block and wise versa. There is a [plugin written in `vimscript`](https://github.com/jgdavey/vim-blockle).
This plugin uses `<Leader>b` as mapping which overwrites the `<Leader>b` namespace for the buffer. 

### Describe the solution you'd like

It would be great to toggle the following example:
```ruby
it "shows the example" do
  expect do 
    execute #here is the cursor
  end.to be_true
end
```

to the following 
```ruby
it "shows the example" do
  expect { execute #here is the cursor }.to be_true
end
```

### Describe alternatives you've considered

My alternative was the usage of [vim-blockle](https://github.com/jgdavey/vim-blockle) before I switched to `LazyVim`. But installing the plugin removes the buffer namespace.

**Comment by dpetka2001** [comment]
You can use the global variable `vim.g.blockle_mapping = something` to change the mapping maybe? I quickly skimmed through the docs and found [this part of code](https://github.com/jgdavey/vim-blockle/blob/71532ed05c84ca0a0cee95d2cba68a3cf1e182b7/plugin/blockle.vim#L215-L217) (though I don't know any Vimscript, just searched for familiar Lua syntax). 

I don't believe such a plugin (unmaintained and archived) should be a core plugin, rather better be left to the user to incorporate it to his personal config. But I'm just a regular user like you and the maintainer has the final say.
