### ISSUE TITLE
bug: stdin pipe opens menu instead of buffer 

### ISSUE THREAD

**Issue by turekaj** [LazyVim/LazyVim#3124]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

V0.9.1

### Operating system/version

Ubuntu 22.04

### Describe the bug

echo “hello world” > hello_world.txt 
cat hello_world.txt | nvim -

The above works fine with vanilla Neovim. With LazyVim, the Lazy main menu that is provided when you don’t pass in a file path is shown. Instead, treat stdin as a file. 

### Steps To Reproduce

```
echo “hello world” > hello_world.txt 
cat hello_world.txt | nvim -
```

### Expected Behavior

Same behavior as vanilla vi, vim, or neovim. Display stdin in a new buffer. 

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
Will be fixed once #3107 gets merged.
