### ISSUE TITLE
bug: can't rename html tags in javascriptreact ( jsx ) and typescriptreact ( tsx ) files.

### ISSUE THREAD

**Issue by monoira** [LazyVim/LazyVim#3127]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

EndeavourOS Linux x86_64

### Describe the bug

so for example let's take this tsx code:

```javascript
import CharactersSection from "../components/CharactersSection";
import IncrementButton from "../components/IncrementButton";

function HomePage() {
  const defaultMoney = 10;
  const startMoney = defaultMoney ?? 0;

  console.log(startMoney);

  return (
    <main>
      <div>123</div>
      <CharactersSection />

      <IncrementButton incrementAmount={5} currency="USD">
        increment btn
      </IncrementButton>
    </main>
  );
}
export default HomePage;
```

I can't rename main or div.
I CAN rename IncrementButton and HomePage component names. idk why.

I am getting this error from Notify every time I try to rename html tag:

Error on prepareRename: Request textDocument/prepareRename failed with message: You cannot rename elements that are defined in a 'node_modules' folder.

I am just modifying normal html codes like <p> so idk why this is telling me anything about node_modules.

when I remove node_modules directory completely and try to rename html tag in tsx/jsx, then I get this error:

Error on prepareRename: Request textDocument/prepareRename failed with message: You cannot rename this element.

### Steps To Reproduce

use lazyvim with all html, css, typescript support.
everything else works. renaming html tags in jsx & tsx files is only thing that does not work for me.

### Expected Behavior

I would hope for html tag to get renamed normally like how everything else works fine.

**Comment by dpetka2001** [comment]
The rename comes directly from the LSP server you use. If it doesn't rename correctly you should create an issue at the appropriate server repo. LazyVim doesn't handle how the rename is done.
