### ISSUE TITLE
feature: Other development languages simple development configuration suggestions

### ISSUE THREAD

**Issue by TomYule** [LazyVim/LazyVim#3130]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

This tool is excellent, but I want to use it to develop Java and I hope it can support Maven. I'm not sure how to configure it. I also hope it can include configurations for languages like Python, Java, Go, ......, and provide the best configurations directly

### Describe the solution you'd like

This tool is excellent, but I want to use it to develop Java and I hope it can support Maven. I'm not sure how to configure it. I also hope it can include configurations for languages like Python, Java, Go, ......, and provide the best configurations directly

### Describe alternatives you've considered

This tool is excellent, but I want to use it to develop Java and I hope it can support Maven. I'm not sure how to configure it. I also hope it can include configurations for languages like Python, Java, Go, ......, and provide the best configurations directly

**Comment by dpetka2001** [comment]
Please take a look at the [docs](https://www.lazyvim.org/extras). There is support for several languages.
