### ISSUE TITLE
bug: Cannot delete default lazyvim keymaps

### ISSUE THREAD

**Issue by marsjane** [LazyVim/LazyVim#3132]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.5

### Operating system/version

Macos 14.4.1

### Describe the bug

I try use the vim.keymap.del method as requested to delete default key but it seems not working as expected

### Steps To Reproduce

1. write delete config:
```
>cat lua/config/delkeymap.lua
vim.keymap.del("n", "<S-l>")
vim.keymap.del("n", "<S-h>")
```
2. Try this keymap, it still working.

### Expected Behavior

These two keymap for buffer switching should not work as it should be deleted by above setting

**Comment by dpetka2001** [comment]
You should put those commands in `/lua/config/keymaps.lua` as mentioned in the [docs](https://www.lazyvim.org/configuration/keymaps#global-keymaps).

**Comment by marsjane** [comment]
Thanks! It works, sorry I didn't read the doc carefully, here is another question can you help?
I use below config to instead default <C-h><C-l><C-j><C-k>
```
keymap.set("n", "wh", "<C-w>h")
keymap.set("n", "wk", "<C-w>k")
keymap.set("n", "wj", "<C-w>j")
keymap.set("n", "wl", "<C-w>l")
```
It works just as expected in normal opened file views, but in neo-tree, when I open the tree, and open one file, `wh` can help me move the focus from right to the left(the tree), but `wl` cannot let me move focus back to the right windows. So it seems that `w` is use in neo-tree. I checked the doc, it seems `["w"] = "open_with_window_picker",` for neovim, I tried this:
```
return {
  "nvim-neo-tree/neo-tree.nvim",
  keys = {
    { "w", mode = { "n", "x", "o", "i" }, false },
  }
}
```
but it doesn't work as expect, the `w` seems still works as the `open_with_window_picker` in neotree. Can you give me some advice? Much thanks!

**Comment by marsjane** [comment]
Thanks, it works!
