### ISSUE TITLE
bug: nvim-treesitter-context Unable to load context query for haskell:

### ISSUE THREAD

**Issue by NamelessDev0000** [LazyVim/LazyVim#3140]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.5

### Operating system/version

Archlinux Rolling

### Describe the bug

Every time when I firstly open a haskell file with lazyvim, nvim-notify will inform me that something wrong with nvim-treesitter-context

### Steps To Reproduce

1. Install haskell tree-sitter parser
2. simply open a haskell file

### Expected Behavior

![图片](https://github.com/LazyVim/LazyVim/assets/61371380/7bd08fdc-4123-4374-9c6c-6d64999a1efe)

**Comment by dpetka2001** [comment]
LazyVim does not have any control over the treesitter parsers. Please create an issue at the appropriate repo. Either [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) or the plugin [treesitter-context](https://github.com/nvim-treesitter/nvim-treesitter-context).
