### ISSUE TITLE
bug: native_snippets doesn't change config for lang.haskell to not use luasnip

### ISSUE THREAD

**Issue by Ben10164** [LazyVim/LazyVim#3141]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0 commit 8c7a8be27437d8f2d640daf1c2598d4c18933e04

### Operating system/version

MacOS 14.4.1

### Describe the bug

When using `extras.coding.native_snippets` and `extras.lang.haskell`, opening a file that activates the Haskell language server results in an error saying:
```
Failed to run `config` for haskell-snippets.nvim

...y/haskell-snippets.nvim/lua/haskell-snippets/pragmas.lua:148: module 'luasnip' not found:
	no field package.preload['luasnip']
cache_loader: module luasnip not found
cache_loader_lib: module luasnip not found
	no file './luasnip.lua'
	no file '/Users/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1/luasnip.lua'
	no file '/usr/local/share/lua/5.1/luasnip.lua'
	no file '/usr/local/share/lua/5.1/luasnip/init.lua'
	no file '/Users/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/luasnip.lua'
	no file '/Users/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/luasnip/init.lua'
	no file './luasnip.so'
	no file '/usr/local/lib/lua/5.1/luasnip.so'
	no file '/Users/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/luasnip.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'

# stacktrace:
  - /haskell-snippets.nvim/lua/haskell-snippets/pragmas.lua:148
  - /haskell-snippets.nvim/lua/haskell-snippets/init.lua:25
  - /LazyVim/lua/lazyvim/plugins/extras/lang/haskell.lua:68 _in_ **config**
  - ~/.local/share/bob/nightly/nvim-macos-arm64/share/nvim/runtime/filetype.lua:36
  - ~/.local/share/bob/nightly/nvim-macos-arm64/share/nvim/runtime/filetype.lua:35
  - vim/_editor.lua:0
  - /telescope.nvim/lua/telescope/actions/set.lua:200 _in_ **run_replace_or_original**
  - /telescope.nvim/lua/telescope/actions/mt.lua:65 _in_ **run_replace_or_original**
  - /telescope.nvim/lua/telescope/actions/mt.lua:65 _in_ **run_replace_or_original**
  - /telescope.nvim/lua/telescope/actions/mt.lua:65 _in_ **key_func**
  - /telescope.nvim/lua/telescope/mappings.lua:290
```

### Steps To Reproduce

1. Turn on `extras.lang.haskell` and `extras.coding.native_snippets`.
2. Open any cabal project (either a `.hs` or `.cabal`.
3. Notice error

### Expected Behavior

No error for missing `luasnip`, as `native_snippets` should replace all functionality of `luasnip`. There are no errors when using `extras.lang.python` or `extras.lang.rust`.

### Repro

```Lua
-- sorry, this isnt very minimal, but i was having issues getting the lsp-server
-- to work in a minimal config. I hope this doesnt cause any issues.
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "LazyVim/LazyVim",
    import = "lazyvim.plugins",
  }, -- Sorry its not minimal
  -- add any other plugins here
  {
    import = "lazyvim.plugins.extras.coding.native_snippets",
  },
  {
    import = "lazyvim.plugins.extras.lang.haskell",
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
`haskell-snippets.nvim` has a [requirement of luasnip](https://github.com/mrcjkb/haskell-snippets.nvim?tab=readme-ov-file#required). Maybe ask the maintainer of the plugin to provide support for native snippets also? This has nothing to do with LazyVim. Otherwise, just disable the plugin `haskell-snippets` in your personal configuration.

**Comment by Ben10164** [comment]
> `haskell-snippets.nvim` has a [requirement of luasnip](https://github.com/mrcjkb/haskell-snippets.nvim?tab=readme-ov-file#required). Maybe ask the maintainer of the plugin to provide support for native snippets also? This has nothing to do with LazyVim. Otherwise, just disable the plugin `haskell-snippets` in your personal configuration.

My bad, I thought it was an issue with the config for the `lang.haskell`. Sorry! I'll close the issue
