### ISSUE TITLE
bug: omnisharp is broken and lsp.log is growing to 13GB+

### ISSUE THREAD

**Issue by iryan2** [LazyVim/LazyVim#3154]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

macOS 14.4.1

### Describe the bug

My `~/.local/state/nvim/lsp.log` is rapidly filling up with garbage. I think, for every keystroke, the following is being added to that file (this was actually much longer but I ran into the character limit in this GH issue template):

<details>
<summary>click to expand</summary>

```
[START][2024-05-14 08:35:52] LSP logging initiated
[ERROR][2024-05-14 08:35:52] ...lsp/handlers.lua:535	"OmniSharp.Script.ScriptContextProvider: Failed to resolve compilation dependencies - System.NullReferenceException: Object reference not set to an instance of an object.\n   at Dotnet.Script.DependencyModel.Context.DotnetRestorer.<Restore>g__CreateConfigFileArgument|4_1(<>c__DisplayClass4_0&)\n   at Dotnet.Script.DependencyModel.Context.DotnetRestorer.Restore(ProjectFileInfo projectFileInfo, String[] packageSources)\n   at Dotnet.Script.DependencyModel.Context.ProfiledRestorer.Restore(ProjectFileInfo projectFileInfo, String[] packageSources)\n   at Dotnet.Script.DependencyModel.Compilation.CompilationDependencyResolver.GetDependencies(String targetDirectory, IEnumerable`1 scriptFiles, Boolean enableScriptNugetReferences, String defaultTargetFramework)\n   at OmniSharp.Script.ScriptContextProvider.CreateScriptContext(ScriptOptions scriptOptions, String[] allCsxFiles, Boolean editorConfigEnabled) in /Users/runner/work/1/s/src/OmniSharp.Script/ScriptContextProvider.cs:line 89 | "
[WARN][2024-05-14 08:35:52] ...lsp/handlers.lua:537	"OmniSharp.Extensions.LanguageServer.Server.LspServerOutputFilter: Tried to send request or notification before initialization was completed and will be sent later OutgoingNotification { Method = o#/backgrounddiagnosticstatus, Params = {\n  \"Status\": 0,\n  \"NumberProjects\": 1,\n  \"NumberFilesTotal\": 1,\n  \"NumberFilesRemaining\": 0\n}, TraceParent = , TraceState =  } | @Request='OutgoingNotification { Method = o#/backgrounddiagnosticstatus, Params = {\n  \"Status\": 0,\n  \"NumberProjects\": 1,\n  \"NumberFilesTotal\": 1,\n  \"NumberFilesRemaining\": 0\n}, TraceParent = , TraceState =  }'"
[WARN][2024-05-14 08:35:52] ...lsp/handlers.lua:537	"OmniSharp.Extensions.LanguageServer.Server.LspServerOutputFilter: Tried to send request or notification before initialization was completed and will be sent later OutgoingNotification { Method = o#/backgrounddiagnosticstatus, Params = {\n  \"Status\": 0,\n  \"NumberProjects\": 1,\n  \"NumberFilesTotal\": 1,\n  \"NumberFilesRemaining\": 0\n}, TraceParent = , TraceState =  } | @Request='OutgoingNotification { Method = o#/backgrounddiagnosticstatus, Params = {\n  \"Status\": 0,\n  \"NumberProjects\": 1,\n  \"NumberFilesTotal\": 1,\n  \"NumberFilesRemaining\": 0\n}, TraceParent = , TraceState =  }'"
[WARN][2024-05-14 08:35:52] ...lsp/handlers.lua:537	"OmniSharp.Extensions.LanguageServer.Server.LspServerOutputFilter: Tried to send request or notification before initialization was completed and will be sent later OutgoingNotification { Method = o#/backgrounddiagnosticstatus, Params = {\n  \"Status\": 0,\n  \"NumberProjects\": 1,\n  \"NumberFilesTotal\": 1,\n  \"NumberFilesRemaining\": 0\n}, TraceParent = , TraceState =  } | @Request='OutgoingNotification { Method = o#/backgrounddiagnosticstatus, Params = {\n  \"Status\": 0,\n  \"NumberProjects\": 1,\n  \"NumberFilesTotal\": 1,\n  \"NumberFilesRemaining\": 0\n}, TraceParent = , TraceState =  }'"
[WARN][2024-05-14 08:35:52] ...lsp/handlers.lua:537	"OmniSharp.Extensions.LanguageServer.Server.LspServerOutputFilter: Tried to send request or notification before initialization was completed and will be sent later OutgoingNotification { Method = o#/backgrounddiagnosticstatus, Params = {\n  \"Status\": 0,\n  \"NumberProjects\": 1,\n  \"NumberFilesTotal\": 1,\n  \"NumberFilesRemaining\": 0\n}, TraceParent = , TraceState =  } | @Request='OutgoingNotification { Method = o#/backgrounddiagnosticstatus, Params = {\n  \"Status\": 0,\n  \"NumberProjects\": 1,\n  \"NumberFilesTotal\": 1,\n  \"NumberFilesRemaining\": 0\n}, TraceParent = , TraceState =  }'"
[WARN][2024-05-14 08:35:52] ...lsp/handlers.lua:537	"OmniSharp.Extensions.LanguageServer.Server.LspServerOutputFilter: Tried to send request or notification before initialization was completed and will be sent later OutgoingNotification { Method = o#/backgrounddiagnosticstatus, Params = {\n  \"Status\": 0,\n  \"NumberProjects\": 1,\n  \"NumberFilesTotal\": 1,\n  \"NumberFilesRemaining\": 0\n}, TraceParent = , TraceState =  } | @Request='OutgoingNotification { Method = o#/backgrounddiagnosticstatus, Params = {\n  \"Status\": 0,\n  \"NumberProjects\": 1,\n  \"NumberFilesTotal\": 1,\n  \"NumberFilesRemaining\": 0\n}, TraceParent = , TraceState =  }'"
[WARN][2024-05-14 08:35:52] ...lsp/handlers.lua:537	"OmniSharp.Extensions.LanguageServer.Server.LspServerOutputFilter: Tried to send request or notification before initialization was completed and will be sent later OutgoingNotification { Method = o#/projectdiagnosticstatus, Params = {\n  \"Type\": \"background\",\n  \"Status\": 0,\n  \"ProjectFilePath\": \"(100%)\"\n}, TraceParent = , TraceState =  } | @Request='OutgoingNotification { Method = o#/projectdiagnosticstatus, Params = {\n  \"Type\": \"background\",\n  \"Status\": 0,\n  \"ProjectFilePath\": \"(100%)\"\n}, TraceParent = , TraceState =  }'"
[WARN][2024-05-14 08:35:52] ...lsp/handlers.lua:537	"OmniSharp.Extensions.LanguageServer.Server.LspServerOutputFilter: Tried to send request or notification before initialization was completed and will be sent later OutgoingNotification { Method = o#/projectdiagnosticstatus, Params = {\n  \"Type\": \"background\",\n  \"Status\": 0,\n  \"ProjectFilePath\": \"(100%)\"\n}, TraceParent = , TraceState =  } | @Request='OutgoingNotification { Method = o#/projectdiagnosticstatus, Params = {\n  \"Type\": \"background\",\n  \"Status\": 0,\n  \"ProjectFilePath\": \"(100%)\"\n}, TraceParent = , TraceState =  }'"
[WARN][2024-05-14 08:35:52] ...lsp/handlers.lua:537	"OmniSharp.Extensions.LanguageServer.Server.LspServerOutputFilter: Tried to send request or notification before initialization was completed and will be sent later OutgoingNotification { Method = o#/projectdiagnosticstatus, Params = {\n  \"Type\": \"background\",\n  \"Status\": 0,\n  \"ProjectFilePath\": \"(100%)\"\n}, TraceParent = , TraceState =  } | @Request='OutgoingNotification { Method = o#/projectdiagnosticstatus, Params = {\n  \"Type\": \"background\",\n  \"Status\": 0,\n  \"ProjectFilePath\": \"(100%)\"\n}, TraceParent = , TraceState =  }'"
[WARN][2024-05-14 08:35:52] ...lsp/handlers.lua:537
```

</details>

I suspect the first line might be a separate, but possibly related issue. I have submitted a bug report for `nvim-treesitter` [here](https://github.com/nvim-treesitter/nvim-treesitter-context/issues/440).

Yesterday it had grown to 13GB, with relatively minor interaction with `.cs` files.

I apologize for not providing a working repro below. I have provided my attempt at cobbling together a repro by copying the config, but on opening nvim with it I get

```
Failed to run `config` for nvim-lspconfig

...cripts/.repro/plugins/lazy.nvim/lua/lazy/core/loader.lua:373: attempt to call field 'setup' (a table value)

# stacktrace:
  - repro.lua:66
```

### Steps To Reproduce

1. Enable omnisharp via `:LazyExtras`
2. Open any `.cs` file
3. Notice that LSP actions like GoToDefinition, ShowReferences etc don't work properly
4. If you do this enough you'll start getting noice warnings about large logs
5. Open `~/.local/state/nvim/lsp.log` and see wall of the same log

### Expected Behavior

I'd like to be able to jump to definition, jump to type definition and show references with Omnisharp. Also it'd be good if the `lsp.log` file didn't grow into the gigabytes.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  {
  "williamboman/mason.nvim",
  opts = function(_, opts)
    if type(opts.ensure_installed) == "table" then
      vim.list_extend(opts.ensure_installed, { "netcoredbg", "csharpier" })
    end
  end,
},
{ "Hoffs/omnisharp-extended-lsp.nvim", lazy = true },
{
  "nvim-treesitter/nvim-treesitter",
  opts = function(_, opts)
    if type(opts.ensure_installed) == "table" then
      vim.list_extend(opts.ensure_installed, { "c_sharp" })
    end
  end,
},
{
  "neovim/nvim-lspconfig",
  opts = {
    servers = {
      omnisharp = {
        handlers = {
          ["textDocument/definition"] = function(...)
            return require("omnisharp_extended").handler(...)
          end,
        },
        keys = {
          {
            "gd",
            function()
              require("omnisharp_extended").telescope_lsp_definitions()
            end,
            desc = "Goto Definition",
          },
        },
        enable_roslyn_analyzers = true,
        organize_imports_on_format = true,
        enable_import_completion = true,
      },
    },
  },
}
  -- add any other plugins here
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
Lazyvim doesn't have control over LSP servers. Kindly create an issue either at the corresponding server github repo or at Neovim repo itself. The problem seems to be with the LSP handlers, that are changed to use the extended `Hoffs/omnisharp-extended-lsp.nvim` handlers, so it might also be a problem with the plugin itself. All these questions are better made at the appropriate place. I would suggest you to start by inquiring at the plugin's repo first and then work your way from there.

**Comment by iryan2** [comment]
Thanks for the pointer, I've raised an [issue on the `Hoffs/omnisharp-extended-lsp.nvim` repo](https://github.com/Hoffs/omnisharp-extended-lsp.nvim/issues/34).

**Comment by iryan2** [comment]
> Lazyvim doesn't have control over LSP servers. 

I see where you're coming from, but LazyVim must have some control over the configuration of LSP servers, as I'm supposed to be able to enable c_sharp support by turning on the Omnisharp option in `:LazyExtras`, right?

I raised the issue here because from my perspective as a LazyVim user, I have simply turned on a feature and it doesn't work, even on an empty project (i.e. `dotnet new console`, open `Program.cs`, omnisharp doesn't work and the log file gets filled up with the same kind of stuff as in my original post).

Is there a guide somewhere for configuring LazyVim for c_sharp? So far I haven't been able to find anyone that can conclusively tell me whether there's more I need to do other than turning on the feature via `:LazyExtras`. @dpetka2001 Do you happen to know the answer? Alternatively, do you know of anyone that is using Omnisharp with LazyVim, who might be willing to share their dotfiles?

Hoffs responded that his plugin doesn't handle any of this stuff either:
> This plugin does not perform any installation or configuration, it only builds on top of LSP.
He pointed me toward the [nvim-lspconfig docs](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#omnisharp). I installed `omnisharp-roslyn` as per the instructions and added the following to my LazyVim config (`nvim/lua/plugins/omnisharp.lua`):
```
return {
  require("lspconfig").omnisharp.setup({
    cmd = { "dotnet", "/Users/work/Desktop/omnisharp-linux-arm64-net6.0/OmniSharp.dll" },
  }),
}
```

And that actually works for a basic project! By "works", I mean, I can put my cursor on `Console`, press `gd` and I'm taken to the definition 🎉 However, it doesn't work for the repo that I work on for my day job, and I now also get an error when opening any file that causes LSP be initialised:
```
Error detected while processing User Autocommands for "LazyFile":
Setup require("neoconf").setup() should be run BEFORE setting up any lsp server with lspconfig
```

Naively adding `require("neoconf").setup()` to the line above `require("lspconfig").omnisharp.setup({` in my `omnisharp.lua` file doesn't get rid of the error. Also, the `lsp.log` file keeps getting filled with garbage - just while I've been writing this message it's gone from 0 to 750,000 lines (or 1.1GB).

I completely understand that these issues are almost certainly caused by something other than LazyVim itself. However, I'm coming at this as a LazyVim user, and for better or worse the LazyVim project is obfuscating the configuration of the things that are causing it - I don't know where to look! So I'm asking this community for help - can anyone please let me know what's required to work with C# in LazyVim? Is it supposed to be as easy as turning on Omnisharp via `:LazyExtras`? Based on my experience, the answer appears to be "no, there's more to it than that", but there doesn't seem to be any mention of that in the LazyVim docs, or elsewhere.
