### ISSUE TITLE
bug: lazyvim.plugins.extras.linting.eslint stopped working

### ISSUE THREAD

**Issue by leehpham** [LazyVim/LazyVim#3161]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

MacOS 14.4.1

### Describe the bug

After recent update, it seemed extras.linting.eslint stopped working.

### Steps To Reproduce

1. Open a TS project
2. Navigate to a TS source file
3. Intentionally let a typescript-eslint rule fail.

### Expected Behavior

The eslint diagnostic error should appear inline (on the line of the failed rule).

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by omelette-watin** [comment]
having the same bug here !
eslint client is still listed in `LspInfo` and no errors are produced in `LspLog`.

i have this warning tho : 
```
The language server eslint triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless
```

**Comment by dpetka2001** [comment]
This is due to recent changes in Eslint. See also #3129. Either downgrade eslint to 4.8.0 or use Neovim nightly where this doesn't seem to happen.

**Comment by leehpham** [comment]
Thanks @omelette-watin @dpetka2001 , seems an eslint-lsp's issue. Guess we could patiently wait this out.

**Comment by dpetka2001** [comment]
@leehpham You can temporarily downgrade to 4.8.0 by using the command `:MasonInstall eslint-lsp@4.8.0`. Later you can upgrade again when they fix the issue.
