### ISSUE TITLE
bug: disabling an extra does not work as expected

### ISSUE THREAD

**Issue by htulipe** [LazyVim/LazyVim#3166]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Windows 11 WSL 2

### Describe the bug

Hello

When disabling the typescript extra (`lazyvim.plugins.extras.lang.typescript`), even after restarting nvim, I still have features from the extra when editing a ts file.

I don't know if I have the full set of features but at least I have code completion, code formatting (though I don't know who does it since I didnot configured any formatter) and disagnostics.

Thanks

### Steps To Reproduce

On a fresh LazyVim install:
- open a typescript file, notice there is no language feature such as diagnostics (which makes sense)
- enable typescript extra via :LazyExtras command
- :q then restart nvim
- notice there are now language features (still makes sense)
- disable typescript extra via :LazyExtras command
- :q then restart nvim
- Notice that all language feature are still there

### Expected Behavior

When disabling typescript extra I would expect to be in the same spot as I was before enabling it

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
That's not how it works. The user has to uninstall the LSP servers from Mason UI and the treesitter parsers himself.

**Comment by stevenroose** [comment]
> disable typescript extra via :LazyExtras command

how does disabling an extra even work? is it documented?

**Comment by dpetka2001** [comment]
When you open the LazyExtras UI with `:LazyExtras` or pressing `x` from Dashboard, you can see at the top of the UI that it mentions
> Enable/disable extras with the <x> key

So, just press `x` on the Extra that you want to toggle it on/off.
