### ISSUE TITLE
bug: Escape key doesn't exit the window instantly (probably some dublicating default remap shadowing the escape key?)

### ISSUE THREAD

**Issue by qbnil** [LazyVim/LazyVim#3171]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Linux Arch

### Describe the bug

There is a delay when i press escape key to exit the window: for example the fzf-lua window. I need to press the escape key to exit that window, but it hangs for about 1.5 seconds.  I already applied these settings to my tmux config: set -sg escape-time 0 
set -g status-interval 0 (but still there is a bit of a delay before the window exits). Probably there is any way i can completely disable all the default keybinds. I tried setting it like this but it seems to not fix the issue: 
![image](https://github.com/LazyVim/LazyVim/assets/130576530/e6ac3f09-3c7d-4616-a2eb-1ccc4db2ba84)

### Steps To Reproduce

-

### Expected Behavior

Faster escape timings

**Comment by dpetka2001** [comment]
In your `~/.config/nvim/lua/config/keymaps.lua` put the following
```lua
vim.keymap.del("t", "<esc><esc>)
vim.keymap.set("t", "<esc>", "<C-\\><C-n>")
```
It should behave like you want.

**Comment by qbnil** [comment]
Thx bud, appreciate that
