### ISSUE TITLE
bug: The tick icon is cut off + (problem request - default indent spaces on save)

### ISSUE THREAD

**Issue by qbnil** [LazyVim/LazyVim#3172]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Linux Arch

### Describe the bug

![image](https://github.com/LazyVim/LazyVim/assets/130576530/94a9ba07-7f5a-47bb-ad5b-26ca37e7f393)
Does it have something to do with the font?... Also i'd really like to know how to change the default two indents on save, i'd like to change it to 4

### Steps To Reproduce

-

### Expected Behavior

-

**Comment by dpetka2001** [comment]
This has to do with the font size and the line spacing which both are dependent on your terminal emulator's settings.

The indents on save depend on the formatter being used to format the buffer. For example, for Lua, you would have to edit the `stylua.toml` file and change `indent_width = 4`.

**Comment by qbnil** [comment]
the indent_width worked clearly, i totally forgot about that one. That means that for everything else i'd need to set up a formatter to format code on save right? And i also wanted to know how to remove the dash signs indicating the spaces

**Comment by dpetka2001** [comment]
`:h 'listchars'` for more info, but as far as I know LazyVim doesn't configure anything by default, so maybe you have something in your personal configuration?
