### ISSUE TITLE
bug: mini.identscope animation on neo-tree if neo-tree is opened before buffer

### ISSUE THREAD

**Issue by georgeguimaraes** [LazyVim/LazyVim#318]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0-dev-1011+g350747461-dirty

### Operating system/version

macOS v12.6.3

### Describe the bug

When you open neo-tree before opening a file, and then open a file, lazy then loads mini.indentscope.

What happens is that now your neo-tree window has the mini.indentscope animation enabled, which shouldn't happen.

### Steps To Reproduce

1. `nvim .` to open neovim with neo-tree already opened
2. open any file
3. return focus to the neo-tree window
4. now you can see the animation from mini.identscope (see screenshot)

![CleanShot 2023-02-21 at 12 27 31](https://user-images.githubusercontent.com/2929/220388375-0bf7f510-a636-43a5-b3e9-29cf47dd0d75.png)

### Expected Behavior

I'd expect to identscope to not be attached to the neo-tree window.

I managed to solve this by copying this into my `lua/config/autocms.lua`:

```
      vim.api.nvim_create_autocmd("FileType", {
        pattern = { "help", "alpha", "dashboard", "neo-tree", "Trouble", "lazy", "mason" },
        callback = function()
          vim.b.miniindentscope_disable = true
        end
````

This way I think it ensures mini.identscope is disabled in neo-tree even before mini.identscope is loaded by lazy.vim.

**Comment by dpetka2001** [comment]
I didn't manage to reproduce following the steps you provided. I followed steps 1-3 and in step 4 I can't see any animation in neo-tree. The autocmd you put in your `lua/config/autocmds.lua` is already part of [`mini.identscope`](https://www.lazyvim.org/plugins/ui#miniindentscope) default configuration, so I don't if it makes any difference.

**Comment by georgeguimaraes** [comment]
@dpetka2001 when browsing through nested files in neo-tree can you try hitting `$` to move the cursor to the end of line? 
That's the difference in my setup. I was noticing it because I also use my mouse to click the files in the list (which will also trigger the animation from mini.identscope).

![CleanShot 2023-02-23 at 18 33 59](https://user-images.githubusercontent.com/2929/221035592-50872a0c-caed-40b6-989a-40df95dcf16a.png)
![CleanShot 2023-02-23 at 18 33 53](https://user-images.githubusercontent.com/2929/221035599-a0eb164d-0ceb-4a9f-98c7-5a3b3059ecaa.png)

**Comment by dpetka2001** [comment]
Yes, I see what you mean and I can confirm this is the case. I just never used `$` to go to the end of the line or the mouse. Just up and down to go to the file i wanted to open. Indeed the autocmd in your own config solves this issue.
