### ISSUE TITLE
feature: update superTab recipes from doc

### ISSUE THREAD

**Issue by DrummyFloyd** [LazyVim/LazyVim#3183]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

with the Breaking change the SuperTab Recipe is not uptodate i think due to LuaSnip deprecation
https://www.lazyvim.org/configuration/recipes#supertab

### Describe the solution you'd like

.

### Describe alternatives you've considered

.

### Additional context

.

**Comment by dpetka2001** [comment]
Just change the Luasnip code from the recipe to the corresponding [keymaps](https://github.com/LazyVim/LazyVim/blob/07923f3701af23504bb09bf6cc11c4fb0a1894e7/lua/lazyvim/plugins/coding.lua#L115-L155) used for the native snippets?

**Comment by bruno-ortiz** [comment]
I used to have this "SuperTab" configuration for copilot. But since the update it stopped working.
```lua
-- config/keymaps.lua
vim.keymap.set("i", "<Tab>", function()
  print("Loading keymaps")
  if require("copilot.suggestion").is_visible() then
    require("copilot.suggestion").accept()
  else
    local key = vim.api.nvim_replace_termcodes("<Tab>", true, false, true)
    vim.api.nvim_feedkeys(key, "n", false)
  end
end, {
  silent = true,
})```
Is this somehow related to this issue or should I open a new one?

**Comment by dpetka2001** [comment]
Since LazyVim's defaults work, I believe this is mostly a user configuration issue.

**Comment by catdadcode** [comment]
I implemented this. Just as @dpetka2001 said I only had to swap out the luasnip bits for the native snippet functions. Here's the diff from the old supertab recipe to the new 😊: https://github.com/catdadcode/.dotfiles/commit/2e4935b809197c0e9ae6cd6bfe980fcd9f6b3aaa

**Comment by catdadcode** [comment]
I have also gone ahead and created a PR to update the recipe 😊

https://github.com/LazyVim/lazyvim.github.io/pull/90

**Comment by DrummyFloyd** [comment]
> I have also gone ahead and created a PR to update the recipe 😊
> 
> [LazyVim/lazyvim.github.io#90](https://github.com/LazyVim/lazyvim.github.io/pull/90)

thank you for the MR 

i'm trying this atm 

and i noticed somethings strange 

some snippets are not working, dunno if it's related 

for instance 

=> `py` file with snippet `asi`

```lua
stack traceback:
	[C]: in function 'assert'
	...ux64/share/nvim/runtime/lua/vim/lsp/_snippet_grammar.lua:177: in function 'parse'
	...10.0/nvim-linux64/share/nvim/runtime/lua/vim/snippet.lua:408: in function 'expand'
	...l/share/nvim/lazy/LazyVim/lua/lazyvim/plugins/coding.lua:109: in function 'expand'
	...jmonnet/.local/share/nvim/lazy/nvim-cmp/lua/cmp/core.lua:488: in function <...HOME/.local/share/nvim/lazy/nvim-cmp/lua/cmp/core.lua:434>
	...ocal/share/nvim/lazy/nvim-cmp/lua/cmp/utils/feedkeys.lua:47: in function 'run'
	[string ":lua"]:1: in main chunk
```

or `yaml` file can't have `k-ingress` (kubernetes snippet) working anymore

it's related to LazyVim stuff or something else ?

**Comment by catdadcode** [comment]
> EDIT: with previous SUPER-TAB config and extras-luasnip it work like a charms

Well yeah, that would be restoring pre-native snippets behavior so it should work exactly the same as before. The real question is whether or not those snippets work for you *with* native snippets and *without* the supertab config. If not then it's just a problem with those snippets and native snippets, not the supertab setup.

**Comment by DrummyFloyd** [comment]
> > EDIT: with previous SUPER-TAB config and extras-luasnip it work like a charms
> 
> Well yeah, that would be restoring pre-native snippets behavior so it should work exactly the same as before. The real question is whether or not those snippets work for you _with_ native snippets and _without_ the supertab config. If not then it's just a problem with those snippets and native snippets, not the supertab setup.

with and without superTab those snippets do not work => so not related to the initail idea of the issue ofc =) 

thanks for your time ! (time to investigate where the problem come from ))

**Comment by catdadcode** [comment]
@DrummyFloyd No prob, happy to help. I know it's not strictly related to this but if you find the issue let me know :)

**Comment by folke** [comment]
Fixed by https://github.com/LazyVim/lazyvim.github.io/pull/90
