### ISSUE TITLE
bug: Symbols Outline not listed in Extras

### ISSUE THREAD

**Issue by rogeriofrsouza** [LazyVim/LazyVim#3184]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.5

### Operating system/version

Linux Mint 21.3 x86_64

### Describe the bug

I just updated my LazyVim to the last Breaking Change version and added the Symbols Outline extra as shown in https://www.lazyvim.org/extras/editor/symbols-outline
However, there's an error being raised when I launch Neovim now:
![error-lazyvim](https://github.com/LazyVim/LazyVim/assets/77423511/706dc832-bcee-41fc-8f30-e7fb72b43c49)

Also, seems like this Extra is not present when running `:LazyExtras` command:
![image](https://github.com/LazyVim/LazyVim/assets/77423511/df7b52b0-8eee-4910-90c3-8e7f7daa96be)

Here is a snippet of my lazy.lua
```lua
require("lazy").setup({
  spec = {
    -- add LazyVim and import its plugins
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- import any extras modules here
    { import = "lazyvim.plugins.extras.lang.typescript" },
    { import = "lazyvim.plugins.extras.lang.json" },
    { import = "lazyvim.plugins.extras.dap.core" },
    { import = "lazyvim.plugins.extras.editor.symbols-outline" },
    -- import/override with your plugins
    { import = "plugins" },
  },
```

### Steps To Reproduce

1. Install the latest version of LazyVim v11.0.1
2. Add Symbols Outline extra in your lazy.lua
3. Save and rerun Neovim

### Expected Behavior

Don't raise the error and load the plugin.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
  { import = "lazyvim.plugins.extras.editor.symbols-outline" },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
That repo is archived. There's a fork (and corresponding extra called `editor.outline`)

**Comment by rogeriofrsouza** [comment]
Ok, thanks for replying.
It is still shown in the `Extras -> editor` section of the website, is this planned?

https://www.lazyvim.org/extras/editor/symbols-outline

**Comment by folke** [comment]
nope, just removed it. Thanks!
