### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by metal3d** [LazyVim/LazyVim#3192]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

Ubuntu (WSL)

### Describe the bug

An error occurs when I launch neovim

```
Failed to run `config` for indent-blankline.nvim

.../share/nvim/lazy/indent-blankline.nvim/lua/ibl/utils.lua:428: attempt to call field 'iter' (a nil value)

# stacktrace:
  - /indent-blankline.nvim/lua/ibl/utils.lua:428 _in_ **tbl_join**
  - /indent-blankline.nvim/lua/ibl/config.lua:253 _in_ **merge_configs**
  - /indent-blankline.nvim/lua/ibl/config.lua:276 _in_ **set_config**
  - /indent-blankline.nvim/lua/ibl/init.lua:57 _in_ **setup**
```

Edit: I removed all my plugins to be sure:

```
Failed to run `config` for indent-blankline.nvim

.../share/nvim/lazy/indent-blankline.nvim/lua/ibl/utils.lua:428: attempt to call field 'iter' (a nil value)

# stacktrace:
  - /indent-blankline.nvim/lua/ibl/utils.lua:428 _in_ **tbl_join**
  - /indent-blankline.nvim/lua/ibl/config.lua:253 _in_ **merge_configs**
  - /indent-blankline.nvim/lua/ibl/config.lua:276 _in_ **set_config**
  - /indent-blankline.nvim/lua/ibl/init.lua:57 _in_ **setup**
  - vim/_editor.lua:0
  - /neo-tree.nvim/lua/neo-tree/utils/init.lua:732 _in_ **open_file**
  - /neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:729 _in_ **open**
  - /neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:751 _in_ **open_with_cmd**
  - /neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:760 _in_ **open**
  - /neo-tree.nvim/lua/neo-tree/sources/filesystem/commands.lua:184
```

### Steps To Reproduce

1. Install the starter
2. Launch neovim, make the lazyvim update
3. relaunch and open a file

I tried several times, and I also retry with a blank installation. The error occurs whatever I do.

It does **not** happen using the repro.lua file.

### Expected Behavior

The error should not appear :)

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
That's not a LAzyVim issue is it? Report it in the correct plugin repo

**Comment by metal3d** [comment]
There is no plugin in my configuration, see the "edit" section please

**Comment by metal3d** [comment]
(sorry for the title, I removed it by error)

**Comment by folke** [comment]
What do you mean? indent-blankline is included in LAzyVim. That plugin is giving the error.
As I said submit an issue in that repo. 
You can't expect me to be responsible for all issues for any plugin included with LazyVim....

**Comment by metal3d** [comment]
The plugins directory is empty (there is the example.lua file only)
I didn't installed extras.

It's a blank installation using the LazyVim/starter repository

I don't have any other explanation... LazyVim worked for weeks, and yesterday the error appears. So I removed everything, reinstalled LazyVim with starter, and the problem is still here.

**Comment by folke** [comment]
Like I said, indent-blankline IS PART OF the core LazyVim plugins.
They just made an update that is not backward compativle with 0.9.5.
I'm pretty sure that was by accident. They'll fix it.

**Comment by folke** [comment]
See here https://github.com/lukas-reineke/indent-blankline.nvim/commit/98f85638a669fd7f42f59a7283676391ab9b9ca3

**Comment by metal3d** [comment]
Ha ! Sorry, I didn't understand what you meant. All apologies.

**Comment by ENEmyr** [comment]
As mentioned in the above comment, the problem arises from the incompatibility of the Neovim version. So, waiting for a while should fix the issue. However, if you want to fix it temporarily, you can add the following line to your custom plugins to downgrade the version of the problem plugin.
 
`  { "lukas-reineke/indent-blankline.nvim", event="LazyFile", opts = { scope = { enabled = false } }, version = "=3.5.4" } `

**Comment by akcharlie24** [comment]
@ENEmyr can you pleasea also mention the temporary fix for the tree-sitter issue ??

**Comment by dpetka2001** [comment]
The field `iter` is available in Neovim 0.10. So, if you update Neovim to stable 0.10 I believe it should be ok. I use stable 0.10 and don't see this error.

**Comment by akcharlie24** [comment]
I am using the 0.11 version but it somehow stopped breaking now after fixing the indent-blankspace thing. Thanks for the help.

**Comment by folke** [comment]
I've already fixed this in LAzyVim, so you can safely use the latest IBL version
