### ISSUE TITLE
bug: Slow file navigation in LazyGit in LazyVim

### ISSUE THREAD

**Issue by emnnipal** [LazyVim/LazyVim#3194]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0

### Operating system/version

MacOS 14.4.1

### Describe the bug

Using LazyGit in LazyVim is lagging when navigating files. This issue occurred after updating to neovim 0.10.0 and LazyVim v11.0.1.

### Steps To Reproduce

1. Open Neovim with a project that has unstaged/staged files (even with just 4 file changes).
2. Go to the second section of LazyGit where you see the changed files.
3. Navigate the files using j and k.
4. The lag is more apparent if you hold j or k to navigate.

### Expected Behavior

There should be no lag. Using lazygit outside of lazyvim is smooth.

**Comment by folke** [comment]
Can't reproduce. Neovim 0.10 does include a new featre related to buffering screen updates for the terminal.
You may look into that and try disabling it to see if that helps.

**Comment by dpetka2001** [comment]
Also can't reproduce, here's a screencast of how it looks for me

[Screencast 2024-05-17 13:59:38.webm](https://github.com/LazyVim/LazyVim/assets/12776461/52b8bde1-74e6-4d27-8f4c-a431504be24c)

**Comment by emnnipal** [comment]
Thank you for the answers and suggested solution. 
Yes, turning off termsync does help resolve the issue for me. Thank you.

**Comment by emnnipal** [comment]
Just a heads up, I'm still experiencing the same issue despite turning off the termsync option, particularly in **monorepos**. 
For now, I've resorted to using lazygit outside of neovim. It seems that the problem arose after updating to neovim 0.10.

**Comment by Dronakurl** [comment]
Have you found a solution yet? I experience a small lag even for neovim 0.9.5. I tried nightly, stable and also different terminal emulators. It's strange and also happens when using gitui in the terminal.

**Comment by wirtsi** [comment]
> Just a heads up, I'm still experiencing the same issue despite turning off the termsync option, particularly in **monorepos**. For now, I've resorted to using lazygit outside of neovim. It seems that the problem arose after updating to neovim 0.10.

Can confirm, also in multi-language repos (like python backend and typescript frontend), lazygit takes a second to react to a keystroke

**Comment by wirtsi** [comment]
Just FYI, I figured this has to to with the kitty terminal I am using. For the fun of it I switched to neovide, there the issue is not present
