### ISSUE TITLE
feature: Allow disabling "No information available" when lsp has no definitions.

### ISSUE THREAD

**Issue by zolrath** [LazyVim/LazyVim#32]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

When multiple LSPs are active for a single buffer, they will all attempt to get information when you trigger a hover. This leads to a single popup of the information you're looking for, with multiple "No information available" popups simultaneously appearing on the top right of the screen.

### Describe the solution you'd like

Ideally,  if any of the LSPs found a result you will only see the result popup, and **no** "No information available" messages.

Similarly, if none of the LSPs find a result, you could see a **single** "No information available" popup.

From what I've gathered its effectively an all or nothing operation, and having zero "No information available" is preferable to a bunch of them, erroneously.

### Describe alternatives you've considered

In my old config I had this to globally replace the floating preview for hover.
It would make the hover rounded to better separate it from the buffer, and return early if there were no results.

For some reason this does **nothing** when set in my LazyVim installation.

```lua
vim.lsp.handlers["textDocument/hover"] = function(_, result, ctx, config)
  config = config or {}
  config.focus_id = ctx.method
  config.border = "rounded"
  if not (result and result.contents) then
    return
  end
  local markdown_lines = vim.lsp.util.convert_input_to_markdown_lines(result.contents)
  markdown_lines = vim.lsp.util.trim_empty_lines(markdown_lines)
  if vim.tbl_isempty(markdown_lines) then
    return
  end
  return vim.lsp.util.open_floating_preview(markdown_lines, "markdown", config)
end
```

**Comment by folke** [comment]
Lsp hover is powered by Noice, to get better rendering with markdown etc. You can disable that with the relevant noice options (see the noice readme), or disable noice altogether.

Or make sure that your code above runs after noice took over hover
