### ISSUE TITLE
bug: cache_loader: module luasnip not found

### ISSUE THREAD

**Issue by rofrol** [LazyVim/LazyVim#3208]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0

### Operating system/version

MacOS 14.4.1

### Describe the bug

My config https://github.com/rofrol/LazyVim--starter/

After upgrading to neovim 0.10 and `Lazy update` I see this error:

```
Failed to run config for nvim-cmp
/Users/roman.frolow/.config/nvim/lua/plugins/cmp.lua:16: module 'luasnip' not found:
  no field package-preload'luasnip'
cache_loader: module luasnip not found
cache_loader_lib: module luasnip not found
  no file '"/luasnip.lua'
  no file '/opt/homebrew/share/luajit-2.1/luasnip.lua'
  no file '/usr/local/share/lua/5.1/luasnip.lua'
  no file '/usr/local/share/lua/5.1/luasnip/init.lua'
  no file '/opt/homebrew/share/lua/5.1/luasnip.lua'
  no file '/opt/homebrew/share/lua/5.1/luasnip/init.lua'
  no file './luasnip.so'
  no file '/usr/local/lib/lua/5.1/luasnip.so'
  no file '/opt/homebrew/lib/lua/5.1/luasnip.so'
  no file '/usr/local/lib/lua/5.1/loadall.so'

# stacktrace:
  - ~/.config/nvim/lua/plugins/cmp.lua:16 in values
```

### Steps To Reproduce

1. Upgrade to neovim 0.10.
2. `Lazy update`

### Expected Behavior

No error

### Repro

Sorry, haven't narrow it done yet.

**Comment by dpetka2001** [comment]
Do you have `Luasnip` Extra enabled? `Luasnip` has been moved to LazyExtras and the default is `native snippets`. Try to enable `Luasnip` from LazyExtras.

**Comment by rofrol** [comment]
nvim-cmp uses luasnip.
but I don't know if I need it. I try to use defaults.
How can I use use native snippets?

**Comment by dpetka2001** [comment]
You are using luasnip [here in your dotfiles](https://github.com/rofrol/LazyVim--starter/blob/3cb56ab6c4e7ad7dfafd2e64858d076cd23457a0/lua/plugins/cmp.lua#L16-L43). Remove those lines to not get the error.

**Comment by rofrol** [comment]
@dpetka2001 Thanks. I completely forgot that I have added it.
