### ISSUE TITLE
bug: Bad autoindent on cpp files

### ISSUE THREAD

**Issue by PabloPicose** [LazyVim/LazyVim#3210]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Linux Min

### Describe the bug

First of all I'm new on LazyVim ecosystem but not in neovim (I don't have a lot experience either).
When I enter on a new line using <CR> (enter) or with 'o' key in normal mode, the indentation expected are the same as the cpp file, but allways a 2 space is placed instead of my current configuration using .clang-format on the root of my proyect.
In LUA lang, as it uses by default 2 spaces, it works, and if I change my clang-format configuration to 2 it works too, but this is not the expected behavior of a editor.
Using a custom empty neovim app without LazyVim it works correctly
I have to mention that using neovim 0.9.5 with the last supported version of LazyVim this does not work too.

![Peek 2024-05-18 00-58](https://github.com/LazyVim/LazyVim/assets/40830013/9e2ed9ed-7f79-45c0-9c64-46a745bf0053)

If I format the document, the document is formatted as my .clang-format ( I'm using 4 spaces of indentation)
![Peek 2024-05-18 01-02](https://github.com/LazyVim/LazyVim/assets/40830013/19596170-721f-41ab-ae23-4ccd2d4fbac4)

I don't imagine what happens here but in some other editors the indentation used in the document is 'automatic'

### Steps To Reproduce

1. Open a .cpp file with clang-format configured to 4 (or whatever indent different from 2)
2. Type whatever you like
3. The indentation is not respected

### Expected Behavior

If I configure the indentation to 4, 6 or 20 (joke) the editor should respect the jump-line indent in the next line

**Comment by dpetka2001** [comment]
The indentation in Neovim depends on `shiftwidth` and `tabstop`. `clang-format` only takes effect when formatting the buffer. See [here](https://github.com/dpetka2001/dotfiles/blob/main/dot_config%2Fnvim%2Fafter%2Fftplugin%2Fc.lua) and do the same options. Create a file `~/.config/nvim/after/ftplugin/cpp.lua` and put the options there. This is not a bug but it's how Neovim by default does things. The first 2 options set up the indentation, the rest put them if you want or not. See `:h name_of_option` for more info about what each option does.

**Comment by PabloPicose** [comment]
> The indentation in Neovim depends on `shiftwidth` and `tabstop`. `clang-format` only takes effect when formatting the buffer. See [here](https://github.com/dpetka2001/dotfiles/blob/main/dot_config%2Fnvim%2Fafter%2Fftplugin%2Fc.lua) and do the same options. Create a file `~/.config/nvim/after/ftplugin/cpp.lua` and put the options there. This is not a bug but it's how Neovim by default does things. The first 2 options set up the indentation, the rest put them if you want or not. See `:h name_of_option` for more info about what each option does.

Doing this the bad behavior continues, and I put an additional 'print' to see if this file is being loaded but it's not, maybe its about a plugin, but I do not enable more than the clang. 
![Peek 2024-05-18 01-30](https://github.com/LazyVim/LazyVim/assets/40830013/eeadc07b-57e2-4079-8bf2-d571e1d4d3f5)

**Comment by dpetka2001** [comment]
You put the file in wrong directory `nvim/lua/config/after/ftplugin`. That's wrong. Please read carefully what i write.

**Comment by PabloPicose** [comment]
> You put the file in wrong directory `nvim/lua/config/after/ftplugin`. That's wrong. Please read carefully what i write.

After correctly relocate the 'after' path and clean the nvim .cache path it works. THANKS!
Could you provide some info about why this is required using LazyVim config and not for a default nvim configuration? What's the reason? Thanks again :)
