### ISSUE TITLE
bug: the color of modified file in neo-tree is not orange

### ISSUE THREAD

**Issue by ShIRannx** [LazyVim/LazyVim#3219]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0 stable

### Operating system/version

macos 12.5.1

### Describe the bug

<img width="614" alt="image" src="https://github.com/LazyVim/LazyVim/assets/72802064/bad200b0-b5bd-40db-aa6c-5facdf061fc0">

I don't know which version started working like the picture above. Only new files are displayed in orange, not modified files, but it used to show both. I know it's not an issue with LazyVim, but I don't know where to find or solve this issue. Any help would be greatly appreciated. Thank you!

### Steps To Reproduce

simply clone the lazyvim starter then launch nvim. go to a git folder and try to modify a file.

### Expected Behavior

<img width="239" alt="image" src="https://github.com/LazyVim/LazyVim/assets/72802064/bb8a82ad-3409-43dc-b9be-afba246dc405">

like demonstration pic in neo-tree.nvim 

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  "nvim-neo-tree/neo-tree.nvim"
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
`neo-tree` has 2 highlight groups for modified files. `NeoTreeGitModified`, which by default is orange and highlights modified files when in a git repo, and `NeotreeModified`, which is used to highlight the symbol `[+]` for the modified file not the filename itself. So, I guess this is normal behavior.

**Comment by folke** [comment]
I just added some extra neotree colors to tokyonight
