### ISSUE TITLE
ci and cil not working as expected anymore

### ISSUE THREAD

**Issue by vdegenne** [LazyVim/LazyVim#3222]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

Fedora 39

### Describe the bug

I used to press `cil` and then the surrounding character to edit its content (the `l` was used to go backward). However this behavior doesn't work anymore, and I haven't changed anything in my configurations.

Another thing that is broken from the recent update is the use of `ci` in certain contexts, see the following (`*` is the caret position):

```js
function a() {
  c*onst {} = getVars();
}
```
From there if I press `ci {` the whole function block is deleted and enters insert mode when I expect to go inside the `{}` near the caret on the same line.

It makes coding painful again.

### Steps To Reproduce

(details in description)

### Expected Behavior

(details in description)

**Comment by dpetka2001** [comment]
This functionality is provided by `mini.ai` plugin, which was moved to `LazyExtras` in recent updates. You have to enable it yourself to have the same functionality again. 

Not a LazyVim bug. When you update LazyVim (especially throughout major version updates) there is a `NEWS` window popping up, mentioning the latest changes. It would be good practice to read through it, so you are aware of the changes.

**Comment by folke** [comment]
`mini.ai` has been added back as a core plugin. It's also in the NEWS

**Comment by dpetka2001** [comment]
Yes!! I always have it enabled :)

**Comment by vdegenne** [comment]
I'll try to be more careful of the changes next time, Thanks for the help!
