### ISSUE TITLE
bug: New plugins not being added

### ISSUE THREAD

**Issue by nikolovlazar** [LazyVim/LazyVim#3224]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0

### Operating system/version

MacOS 14.4.1

### Describe the bug

Ever since updating to the latest neovim and LazyVim, adding new Lua files in `lua/plugins` don't have any effect. I've tried adding oil.nvim like so:
```lua
return {
  {
    "stevearc/oil.nvim",
    opts = {},
    -- Optional dependencies
    dependencies = { "nvim-tree/nvim-web-devicons" },
  },
}
```
but Lazy doesn't pick it up and it doesn't get installed. I also tried overriding mini.move's keys, but it doesn't seem to have an effect.

### Steps To Reproduce

1. Upgrade Neovim to 0.10.0
2. Update LazyVim to latest (https://github.com/LazyVim/LazyVim/commit/90809599810a46fb7b7e6e9eb8c2591f317aeacd)
3. Add new plugin files in `lua/plugins`
4. Reload neovim - nothing happens

### Expected Behavior

Adding and modifying Lua files in `lua/plugins` should be reflected in Neovim's behavior.

**Comment by nikolovlazar** [comment]
**Update:** It seems that older existing Lua plugin files are being executed, but not new ones. I've added a `print` statement in an older Lua plugin file and the message did appear. I also deleted an older Lua file of a plugin I don't use anymore and now I'm getting an error `Failed to load 'plugins.games'` (`games.lua` was the deleted file). This looks like a caching issue?

**Comment by dpetka2001** [comment]
Delete `~/.local/share/nvim/lazy` and restart Neovim.

**Comment by nikolovlazar** [comment]
> Delete `~/.local/share/nvim/lazy` and restart Neovim.

I did this, but it didn't change anything.

**Comment by nikolovlazar** [comment]
The whole error:
```
 | lazy.nvim:  | lazy.nvim:  | lazy.nvim: Failed to load `plugins.games`

...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/plugin.lua:415: module 'plugins.games' not found:
	no field package.preload['plugins.games']
cache_loader: module plugins.games not found
cache_loader_lib: module plugins.games not found
	no file './plugins/games.lua'
	no file '/opt/homebrew/share/luajit-2.1/plugins/games.lua'
	no file '/usr/local/share/lua/5.1/plugins/games.lua'
	no file '/usr/local/share/lua/5.1/plugins/games/init.lua'
	no file '/opt/homebrew/share/lua/5.1/plugins/games.lua'
	no file '/opt/homebrew/share/lua/5.1/plugins/games/init.lua'
	no file './plugins/games.so'
	no file '/usr/local/lib/lua/5.1/plugins/games.so'
	no file '/opt/homebrew/lib/lua/5.1/plugins/games.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './plugins.so'
	no file '/usr/local/lib/lua/5.1/plugins.so'
	no file '/opt/homebrew/lib/lua/5.1/plugins.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'

# stacktrace:
  - ~/.config/nvim/lua/config/lazy.lua:9
  - ~/.config/nvim/init.lua:2
```

**Comment by dpetka2001** [comment]
There's something wrong with your LazyVim installation. Please follow the [installation instructions](https://www.lazyvim.org/installation).

**Comment by nikolovlazar** [comment]
Yeah I've had `plugins.games` for some time, but deleting it causes this error. I expected for the plugins in `games.lua` to be marked for cleaning, but it still tries to access the old file. Is this a cache issue of some sorts?

**Comment by dpetka2001** [comment]
You have somewhere in your configuration something like `require("plugins.games")` and that must be causing the error.

**Comment by nikolovlazar** [comment]
Nope, there's no mention of `"games"` at all in all of my config.

**Comment by dpetka2001** [comment]
Plz try the following
```bash
1. `mkdir ~/.config/lazytest`
2. `git clone https://github.com/LazyVim/starter ~/.config/lazytest`
3. `NVIM_APPNAME=lazytest nvim` and wait for the installation to complete
4. Restart Neovim with the command provided in step 3
```
Try to add 
```lua
return {
  {
    "stevearc/oil.nvim",
    opts = {},
    -- Optional dependencies
    dependencies = { "nvim-tree/nvim-web-devicons" },
  },
}
```
in `~/.config/nvim/lua/plugins/oil.lua` and restart Neovim with command provided in previous step 3.

For cleanup 
```bash
rm -rf ~/.config/lazytest
rm -rf ~/.local/share/lazytest
rm -rf ~/.local/state/lazytest
rm -rf ~/.cache/lazytest
```

**Comment by dpetka2001** [comment]
I just cloned your dotfiles and I don't get any error. I deleted `games.lua` and `lazy.nvim` uninstalled `ThePrimeagen/vim-be-good` correctly. I even created a file `~/.config/nvim/lua/plugins/oil.lua` with the code snippet above for `oil.nvim` and Lazy also installed that correctly. 

I can't help you debug your own configuration on your end, but all these tests show that it's something on your end and not a LazyVim bug as this issue suggests.

If you're unable to correctly diagnose the problem on your end, then I would suggest to start fresh as per the [installation docs](https://www.lazyvim.org/installation) by deleting all the directories that are mentioned and keep a backup of your `~/.config/nvim` directory and then slowly integrate your old configuration back.

**Comment by nikolovlazar** [comment]
There seems to be something cached that still points to the existing plugins. I deleted all the folders you suggested above, but there must be something else.

**Comment by dpetka2001** [comment]
You have to figure that on your own. As I said, I cloned your dotfiles and tested your configuration from Github and I got no error. Again, this is not a LazyVim bug.

**Comment by dpetka2001** [comment]
Are your dotfiles stored in a way that create symlinks in `~/.config/nvim`?

**Comment by nikolovlazar** [comment]
🤦‍♂️ I use `stow` and the symlink was still present in the `~/.config/nvim/lua/plugins` folder. That was it... Thanks @dpetka2001.
