### ISSUE TITLE
bug: vim.schedule error when opening a TeX file

### ISSUE THREAD

**Issue by EraPartner** [LazyVim/LazyVim#3231]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0 Build type: Release

### Operating system/version

MacOS 14.5

### Describe the bug

When opening a tex file right now, I get an error saying, regardless of whether the TeX extra is enabled or not: 

`Error executing vim.schedule lua callback: .../neovim/0.10.0/share/nvim/runtime/lua/vim/lsp/client.lua:786: Invalid 'data': Cannot convert given Lua table
stack traceback:
        [C]: in function 'nvim_exec_autocmds'
        .../neovim/0.10.0/share/nvim/runtime/lua/vim/lsp/client.lua:786: in function <.../neovim/0.10.0/share/nvim/runtime/lua/vim/lsp/client.lua:785>`

I tried fixing it by going to that file but I don't know this framework. 

### Steps To Reproduce

1. create a test.tex file with some template TeX code
2. open this with lazyVim
3. observe error

### Expected Behavior

No error

**Comment by folke** [comment]
I'm going to need some more info here, since it works fine for me

**Comment by folke** [comment]
You don't need to configure anything if you enable the xtra.
`Optional` just means that that part of the extra will be enabled if the plugin for which it is optional for is present.

**Comment by folke** [comment]
Just enable the extra and remove all your text config. 
Closing
