### ISSUE TITLE
Can't get LazyVim installed under windows

### ISSUE THREAD

**Issue by bergtholdt** [LazyVim/LazyVim#324]
I tried the instructions from the [install page](https://www.lazyvim.org/installation) under the windows tab. But when I start nvim I just get this error:

```
Error detected while processing C:\Users\martin\AppData\Local\nvim\init.lua:
E5113: Error while calling lua chunk: C:\Users\martin\AppData\Local\nvim/lua/config/lazy.lua:9: module 'lazy' not
found:
        no field package.preload['lazy']
        no file '.\lazy.lua'
        no file 'C:\tools\neovim\nvim-win64\bin\lua\lazy.lua'
        no file 'C:\tools\neovim\nvim-win64\bin\lua\lazy\init.lua'
        no file '.\lazy.dll'
        no file 'C:\tools\neovim\nvim-win64\bin\lazy.dll'
        no file 'C:\tools\neovim\nvim-win64\bin\loadall.dll'
stack traceback:
        [C]: in function 'require'
        C:\Users\martin\AppData\Local\nvim/lua/config/lazy.lua:9: in main chunk
        [C]: in function 'require'
        C:\Users\martin\AppData\Local\nvim\init.lua:2: in main chunk
Press ENTER or type command to continue
```

I usually don't work under windows, however I need to and any help would be appreciated.

Running nvim without the LazyVim/starter worked.

Apparently lazy.nvim did get cloned into

```
C:\Users\martin\AppData\Local\nvim-data\lazy
```

**Comment by dpetka2001** [comment]
Try to remove the `C:\Users\martin\AppData\Local\nvim-data\lazy` folder and run nvim again in case the `git clone` didn't finish successfully. It will try to reinstall lazy again.

**Comment by folke** [comment]
I just booted up my Windows install and it all went fine.
It might indeed have been an issue where the initial clone didnt finish sucessfully

**Comment by bergtholdt** [comment]
Just tried it. It worked. Thanks alot!
