### ISSUE TITLE
bug: tab navigation breaks after Lsp initlization

### ISSUE THREAD

**Issue by ZilDeus** [LazyVim/LazyVim#3242]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.5 Build type: Release LuaJIT 2.1.1713773202

### Operating system/version

windows 11 Arch Wsl2

### Describe the bug

this error started happening after the last update
![image](https://github.com/LazyVim/LazyVim/assets/131702027/724e0c70-caba-4d16-8e26-96ce068a7766)

after this error i just can't `<leader>l` and `<leader>h` , `<leader>bd` works though.
sorry if this issue doesn't follow the standard format, i just would like this to be fixed, cause it's essential to my workflow. 

### Steps To Reproduce

- start neovim
- press `<leader>e` to open file explorer
- select any file
- wait for the Lsp to start
- open any other file
- it gives me this error

### Expected Behavior

.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
See #3239. It's a problem with bufferline itself. Kindly create an issue at the plugin's repo if one is not yet present.

**Comment by folke** [comment]
IT seems that bufferline just pushed a fix for this

**Comment by ZilDeus** [comment]
thanks, and sorry.

**Comment by ZilDeus** [comment]
that did it ! , thank you.

**Comment by folke** [comment]
I just pushed an update to LazyVim that pins bufferline to the last working commit on 0.9.x.
You'll have to run `:Lazy` and  update to downgrade to the older version
