### ISSUE TITLE
bug: Uninstalling a(ny) plugin will reinstall the plugin on next load.

### ISSUE THREAD

**Issue by Jestar342** [LazyVim/LazyVim#3245]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.11.0-dev-17+g48c2ad5d2d

### Operating system/version

Win10 WSL2 ArchLinux.

### Describe the bug

Uninstallaing packages (with 'x' in :Lazy) will mark them as 'Not installed':

![image](https://github.com/LazyVim/LazyVim/assets/457158/f6e72c8f-163d-4043-8efa-81a9105a2d11)

but on next nvim startup, they are reinstalled:

![image](https://github.com/LazyVim/LazyVim/assets/457158/4be62a66-5b52-43ff-857d-b4aefac317dd)

### Steps To Reproduce

1. Uninstall any plugin via :Lazy 
2. Restart Neovim
3. Plugins reinstall themselves.

### Expected Behavior

Uninstalling should remove them permanently.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
That's not how you uninstall plugins. You have to remove the spec from your configuration if you installed it yourself or disable the LazyExtra if you installed via LazyExtras or disable the plugins as per the [docs](https://www.lazyvim.org/configuration/plugins#-disabling-plugins) if it's a core LazyVim plugin.
