### ISSUE TITLE
bug: Gitui broke after neovim 0.10.0 update

### ISSUE THREAD

**Issue by tmlnv** [LazyVim/LazyVim#3253]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

MacOS 14.3.1

### Describe the bug

Gitui plugin stops working after the update to LazyVim 11.3.2 and neovim 0.10.0.  
It simply flashes for a second after being called and dissapears.
GitUI was installed via LazyExtras.

### Steps To Reproduce

1. <leader>g - git
2. g - GitUI (RootDir)

### Expected Behavior

GitUI is open.

**Comment by dpetka2001** [comment]
Cannot reproduce. Screecast following

[Screencast 2024-05-20 21:35:06.webm](https://github.com/LazyVim/LazyVim/assets/12776461/ac784a51-b259-4b9e-a97e-73cffe604dc9)

**Comment by folke** [comment]
Same here, works as expected

**Comment by tmlnv** [comment]
@dpetka2001 @folke , tagging u in case u did not see the screencast.
Moreover, I've tried this on a fresh new instalation after removing 
~/.config/nvim
~/.local/share/nvim
~/.local/state/nvim
~/.cache/nvim
but still got the same issue. Here is the additional error message.
<img width="1408" alt="gitui_err_msg" src="https://github.com/LazyVim/LazyVim/assets/108088921/72df19d7-aa10-4ebe-ac3f-3daa80c3ec8b">

**Comment by dpetka2001** [comment]
I saw the screencast but cannot reproduce. I've tested on 2 computers (not Apple) with separate LazyVim configurations and none of them had that problem. From the error it seems that it can't find the executable. Are you sure it's installed by Mason? Check `MasonLog` to see if there any errors when installing the plugin.

**Comment by tmlnv** [comment]
MasonLog says `Installation succeeded for Package(name=gitui)`.
Could you please give any suggestions regarding what else can I clean? Maybe something related to gitui itself could be cached somewhere?
I've also tested on another Mac and inside Docker and could not reproduce the issue myself so it is definitely related to the local installation.

**Comment by dpetka2001** [comment]
Are the 2 macs the same architecture (Intel Mac or Apple Silicon)?

**Comment by tmlnv** [comment]
Intel both

**Comment by dpetka2001** [comment]
I'm out of ideas. Usually removing the 4 directories you mentioned lets LazyVim start fresh installation. Try to uninstall `gitui` yourself from Mason and then install it again manually? Can't help further, since i don't own a Mac to test and haven't been able to repro on 2 different computers.

**Comment by tmlnv** [comment]
Np, thx for advice

**Comment by dpetka2001** [comment]
Can you check if the file is present in the Mason install directory?

**Comment by EdricChan03** [comment]
I've encountered the issue (on an Intel Mac as well), and it seems that the `gitui` executable that Mason installs is actually an Apple Silicon executable (according to [Apparency](https://www.mothersruin.com/software/Apparency/))...

<img width="810" alt="Screenshot of Mason-installed gitui executable in Apparency" src="https://github.com/LazyVim/LazyVim/assets/20047125/41f80254-4a91-498a-ba01-0dcb4c8f8c1f">

And here's the global version I have installed from Homebrew for comparison:

<img width="810" alt="Screenshot of Homebrew-installed gitui executable in Apparency" src="https://github.com/LazyVim/LazyVim/assets/20047125/460c8924-2ba0-480a-849f-53293bc7289e">

**Comment by EdricChan03** [comment]
From what I can tell:

* The GitHub Actions macOS runner was moved to arm64 by default
  * So recent versions of `gitui` were built only for Apple Silicon, until [v0.26.3-rc-1](https://github.com/extrawurst/gitui/releases/tag/v0.26.3-rc.1)
  * And the resulting installed executable would be Apple Silicon-only
* There's currently a pending PR to bump to v0.26.3 for the Mason registry https://github.com/mason-org/mason-registry/pull/5950
