### ISSUE TITLE
bug:  intelephense or php actor doesnt attach to a buffer 

### ISSUE THREAD

**Issue by muneebusmani** [LazyVim/LazyVim#3258]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4 (in wsl ubuntu), 0.9.5 (in windows)

### Operating system/version

win 10 latest updated

### Describe the bug

whenever i install php lsp , it doesnt get attached to a buffer after restarting nvim, although i tried manually configuring the lsp server but i also messed up so i just left it as it is, mason is installing lsp and the lsp is getting preconfigured configuration thanks to lazyvim but when i type :LspInfo , it says 0 clients attached to a buffer, it happens to 2 lsps for the same language

### Steps To Reproduce

1. Install phpactor/intelephense.
2. Restart nvim
3. open a php file, you will notice that the completions dont pop up
4. type :LspInfo , you will notice 0 clients attached to this buffer

### Expected Behavior

it should work

### Repro

```Lua
i only have catppuccin and vim-tmux-navigator configured as a plugin so there is not point pasting the lazy.lua here because it is untouched
```

**Comment by dpetka2001** [comment]
Both of them need the pattern `root_pattern("composer.json", ".git")` to attach correctly. Make sure you have either of those files at the root of your project.

**Comment by muneebusmani** [comment]
> Both of them need the pattern `root_pattern("composer.json", ".git")` to attach correctly. Make sure you have either of those files at the root of your project.

Yeah i thought of that and it worked, thanks dude, but this should be fixed because not every project has .git or composer.json, because sometimes there are core php projects too

**Comment by dpetka2001** [comment]
This has nothing to do with LazyVim. This is how the LSP server is configured from [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/blob/0b8165cf95806bc4bb8f745bb0c92021b2ed4b98/lua/lspconfig/server_configurations/intelephense.lua#L7-L13). You should create an issue at the repo if you want this behavior changed, so that they also add `single_file_support` for the LSP server that you want.
