### ISSUE TITLE
bug: snippets broken in Svelte after latest update

### ISSUE THREAD

**Issue by couscousdude** [LazyVim/LazyVim#3266]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

MacOS 14.2.1

### Describe the bug

Typing anything in `.svelte` files will lead to the errors shown below, presumably related to completion plugins. No completions are shown, even when LSP is active.

![image](https://github.com/LazyVim/LazyVim/assets/38934577/c6c01937-5521-49de-8e43-58a811d69e97)

```
   Error  09:24:41 msg_show.lua_error Error executing vim.schedule lua callback: ...local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/snippet.lua:409: snippet parsing failed.
stack traceback:
	[C]: in function 'error'
	...local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/snippet.lua:409: in function 'parse'
	...ouwenw/.local/share/nvim/lazy/nvim-cmp/lua/cmp/entry.lua:130: in function 'callback'
	.../.local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/cache.lua:38: in function 'get_word'
	...ouwenw/.local/share/nvim/lazy/nvim-cmp/lua/cmp/entry.lua:81: in function 'callback'
	.../.local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/cache.lua:38: in function 'get_offset'
	...uwenw/.local/share/nvim/lazy/nvim-cmp/lua/cmp/source.lua:353: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
   Error  09:24:41 notify.error ...local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/snippet.lua:409: snippet parsing failed.
```

Error still occurs whether with clean configuration or with LSP and Treesitter set up.

### Steps To Reproduce

1. Install LazyVim
2. Open `+page.svelte`, `+error.svelte`, etc
3. Enter insert mode and type anything

### Expected Behavior

Should produce no errors and show completions as normal.

**Comment by dusty-phillips** [comment]
> This is actually a bug in cmp: [hrsh7th/nvim-cmp#1877](https://github.com/hrsh7th/nvim-cmp/issues/1877)
> 
> But, I actually have snippet parsing code in LazyVim as well. I just replaced cmp's snippet parser with the LazyVim one if the cmp one fails.

This is the second time in a week I've tracked down an issue only to find that @folke fixed it five minutes ago. ❤️❤️❤️

**Comment by folke** [comment]
That module exists in the latest version of CMP. Are you pinning CMP somehow?

**Comment by mikededo** [comment]
No, I'm not. I even went to the local cloned repository for CMP and updated to the latest commit (in which I was already). Yet the error still persisted. I will try a clean install.

**Comment by mikededo** [comment]
Even after a clean install (basically removing all the plugins and the cache), the error persists. The only way I have managed to make it work is by overwriting the `config` from `nvim-cmp`.

Here's the current config, maybe you can guess what's wrong with it, it there's any:

<details>
<summary>Local nvim-cmp config</summary>

```lua
return {
  {
    'hrsh7th/nvim-cmp',
    dependencies = {
      'hrsh7th/cmp-emoji',
      'zbirenbaum/copilot-cmp',
    },
    opts = function(_, opts)
      local lspkind = require('lspkind')
      local has_words_before = function()
        unpack = unpack or table.unpack
        local line, col = unpack(vim.api.nvim_win_get_cursor(0))
        return col ~= 0
          and vim.api
              .nvim_buf_get_lines(0, line - 1, line, true)[1]
              :sub(col, col)
              :match('%s')
            == nil
      end

      local cmp = require('cmp')

      opts.mapping = vim.tbl_extend('force', opts.mapping, {
        ['<C-j>'] = cmp.mapping(function(fallback)
          if cmp.visible() then
            cmp.select_next_item()
          elseif has_words_before() then
            cmp.complete()
          else
            fallback()
          end
        end, { 'i', 's' }),
        ['<C-k>'] = cmp.mapping(function(fallback)
          if cmp.visible() then
            cmp.select_prev_item()
          else
            fallback()
          end
        end, { 'i', 's' }),
      })
      opts.formatting = {
        fields = { 'kind', 'abbr', 'menu' },
        formatting = {
          format = lspkind.cmp_format({
            mode = 'symbol',
            max_width = 50,
            symbol_map = { Copilot = '' },
          }),
        },
        format = function(entry, vim_item)
          local kind = lspkind.cmp_format({
            mode = 'symbol_text',
            maxwidth = 50,
          })(entry, vim_item)

          local strings = vim.split(kind.kind, '%s', { trimempty = true })
          kind.kind = ' ' .. strings[1] .. ' '
          kind.menu = '    (' .. strings[2] .. ')'

          return kind
        end,
      }
    end,
    ---@param opts cmp.ConfigSchema | {auto_brackets?: string[]}
    config = function(_, opts)
      -- Override the default config as the snippets are not working.
      -- See => https://github.com/LazyVim/LazyVim/issues/3266
      -- See => https://github.com/hrsh7th/nvim-cmp/issues/1877
      for _, source in ipairs(opts.sources) do
        source.group_index = source.group_index or 1
      end

      local cmp = require('cmp')
      cmp.setup(opts)
      cmp.event:on('confirm_done', function(event)
        if vim.tbl_contains(opts.auto_brackets or {}, vim.bo.filetype) then
          LazyVim.cmp.auto_brackets(event.entry)
        end
      end)
      cmp.event:on('menu_opened', function(event)
        LazyVim.cmp.add_missing_snippet_docs(event.window)
      end)
    end,
  },
}
```
</details>

**Comment by dpetka2001** [comment]
You're overwriting the default config function of nvim-cmp and the changes made in LazyVim aren't taken into consideration. Add [these lines](https://github.com/LazyVim/LazyVim/blob/2bae438570aa96904836e56d8dad7f33eb3204ee/lua/lazyvim/plugins/coding.lua#L75-L82) to your config as well. In fact I don't see you making any changes to the config function yourself, so you don't need to even have it in your personal configuration.

**Comment by dpetka2001** [comment]
My bad I should have read more carefully. This was your workaround to overcome the issue. Maybe wait on the maintainer's reply then. Another thing i saw was that your defining `formatting` twice in the `opts`. Maybe that's not needed (unless i'm mistaken)??
```lua
formatting = {
          format = lspkind.cmp_format({
            mode = 'symbol',
            max_width = 50,
            symbol_map = { Copilot = '' },
          }),
        },
```

**Comment by dpetka2001** [comment]
@mikededo Can you try commenting out [these lines](https://github.com/mikededo/.dotfiles/blob/4652b8bd21070c37e8809bb78d1d612660f80ac9/nvim/.config/nvim/lua/plugins/tailwindcss.lua#L19-L33) in your personal configuration assuming that they're still like this (because that was from 3 months ago).

**Comment by mikededo** [comment]
Hmm, that solves the issue. I also removed the extra formatting I had and removed the `config` overwrite...

Any clue on what that was?

**Comment by dpetka2001** [comment]
That is just wrong way to define a spec. Inside another spec (for example `nvim-colorizer`) you can only define another spec inside the `dependencies`. In your case you were defining the `nvim-cmp` inside the `nvim-colorizer` spec and that was being evaluated during the parsing phase of `lazy.nvim` I believe (not 100% sure really)?? Also bare in mind that what is inside the `dependencies` will load first. But to me it seems like a problem with how you're defining the spec.
