### ISSUE TITLE
bug: which-key hunks prefix does not work

### ISSUE THREAD

**Issue by dotfrag** [LazyVim/LazyVim#3267]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0

### Operating system/version

Linux

### Describe the bug

This:

https://github.com/LazyVim/LazyVim/blob/8c94842b4a613995bf4c0c79febcd74c310439d0/lua/lazyvim/plugins/editor.lua#L356

Does not work:

![2024-05-21T19:34:07,387856034+03:00](https://github.com/LazyVim/LazyVim/assets/17456867/9932e595-d126-41b3-b386-6a6e9d7d1942)

I discovered it while trying to remap `gitsigns` keys in my config:

```lua
  {
    "folke/which-key.nvim",
    opts = {
      defaults = {
        ["<leader>h"] = { name = "+hunks" },
      },
    },
  },
```

^ this doesn't work either.

I am not 100% sure why, but I suspect it's because Gitsigns loads after which-key. When which-key loads first, it doesn't see any keymaps `<leader>gh*`, and doesn't register an "empty" prefix.

For refence, I've tested this in the default starter config.

That's all the info I have and I don't know how to fix it, sorry.

### Steps To Reproduce

1. Use starter config
2. Press `<leader>g`
3. `h` shows as `+prefix` instead of `+hunks`

### Expected Behavior

Expected to show `+hunks` instead of `+prefix`.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
This is a problem with `which-key.nvim` itself and there's a workaround mentioned in this [comment](https://github.com/LazyVim/LazyVim/discussions/2887#discussioncomment-8962181) (it also includes the initial comment at `which-key` repo from which I got the idea).

**Comment by dotfrag** [comment]
Ahhh now I see. This makes perfect sense then:

https://github.com/nvim-lua/kickstart.nvim/blob/5aeddfdd5d0308506ec63b0e4f8de33e2a39355f/init.lua#L283-L291

I can create a PR for this.

**Comment by dpetka2001** [comment]
You would have to create it at `which-key`'s repo if you want. This is not the place for this.

**Comment by dotfrag** [comment]
Okay, no problem. I am going to add the placeholder in my config.

**Comment by dpetka2001** [comment]
@dotfrag I'm just a regular user like you, so the opinion I expressed was only my personal one. Go ahead and do the PR if you like and the maintainer will make the decision for it.
