### ISSUE TITLE
bug: (minor UI issue) nvim-navic background colour different from lualine background

### ISSUE THREAD

**Issue by kiyoon** [LazyVim/LazyVim#328]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0

### Operating system/version

Ubuntu 22.04

### Describe the bug

![image](https://user-images.githubusercontent.com/12980409/220959976-29cdab14-99b2-4205-b27c-62fef347e09e.png)

Super minor. You need to look closely. You can see that the nvim-navic colour doesn't align with the lualine colour.  
Not talking about the line below (it's my tmux statusline so ignore that please)

### Steps To Reproduce

N/A

### Expected Behavior

N/A

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by kiyoon** [comment]
@dpetka2001 Sorry I had no idea. But I think if it's a highlight group you can configure it manually right? Then I think preconfiguration could improve that. Or maybe colorscheme (tokyonight) has to be improved

**Comment by dpetka2001** [comment]
But not anyone uses the same colorscheme. That's why i think this doesn't fall under general configuration of Lazyvim, but personal configuration of the user.

**Comment by kiyoon** [comment]
@dpetka2001 I didn't configure anything. I just downloaded the starter and I could see it by default. Also if it's highlight group issue, then if you fix it on the lualine configuration of LazyVim, whatever colourscheme you yse it should be fixed for anything.

**Comment by annaleighsmith** [comment]
I have seen the same issue (using nord) but i'm sure there's some way to configure it and fix it, just haven't found it yet. @kiyoon

**Comment by dpetka2001** [comment]
So I have found a temporary solution. You would have to tamper the `tokyonight` colorscheme. The file you would have to change is `~/.local/share/nvim/lazy/tokyonight.nvim/lua/tokyonight/theme.lua`. Inside that file you would have to change all `Navic*` values from line 548 up to line 576 to have `bg = "#1e2030"`. For other colorschemes there would have to be either appropriate support from the colorscheme for `nvim-navic` or someone should set up in the `attach` function, where navic is being required, the highlight groups as mentioned in the `nvim-navic` README to the have the corresponding background as their colorscheme uses for `lualine`. I'm not sure if this is deliberate in tokyonight, as maybe the maintainer thought it would be more visibly correct to differentiate the `navic` component from the other components. But if you want it so much to change, feel free to make a PR in tokyonight repo for the change to become the default. There might be some other way from Lazyvim, but I wasn't able to find it except from setting the highlight groups when setting up navic.

**Comment by dpetka2001** [comment]
@kiyoon Actually just set `bg = c.bg_dark` instead of the value above. This way it will update according to which flavor of `tokyonight` you use. I use `moon` which is also the default for Lazyvim (I think?) and put the arithmetic value explicitly.

**Comment by dpetka2001** [comment]
```lua
  {
    "folke/tokyonight.nvim",
    opts = {
      style = "moon",
      on_highlights = function(hl, c)
        hl.NavicIconsFile = { bg = c.bg_dark, fg = "#ffffff" }
        hl.NavicIconsModule = { bg = c.bg_dark, fg = "#ffffff" }
        hl.NavicIconsNamespace = { bg = c.bg_dark, fg = "#ffffff" }
        hl.NavicIconsPackage = { bg = c.bg_dark, fg = "#ffffff" }
        hl.NavicIconsClass = { bg = c.bg_dark, fg = "#ffffff" }
        hl.NavicIconsMethod = { bg = c.bg_dark, fg = "#ffffff" }
        hl.NavicIconsProperty = { bg = c.bg_dark, fg = "#ffffff" }
        hl.NavicIconsField = { bg = c.bg_dark, fg = "#ffffff" }
        hl.NavicIconsConstructor = { bg = c.bg_dark, fg = "#ffffff" }
        hl.NavicIconsEnum = { bg = c.bg_dark, fg = "#ffffff" }
        hl.NavicIconsInterface = { bg = c.bg_dark, fg = "#ffffff" }
        hl.NavicIconsFunction = { bg = c.bg_dark, fg = "#ffffff" }
        hl.NavicIconsVariable = { bg = c.bg_dark, fg = "#ffffff" }
        hl.NavicIconsConstant = { bg = c.bg_dark, fg = "#ffffff" }
        hl.NavicIconsString = { bg = c.bg_dark, fg = "#ffffff" }
        hl.NavicIconsNumber = { bg = c.bg_dark, fg = "#ffffff" }
        hl.NavicIconsBoolean = { bg = c.bg_dark, fg = "#ffffff" }
        hl.NavicIconsArray = { bg = c.bg_dark, fg = "#ffffff" }
        hl.NavicIconsObject = { bg = c.bg_dark, fg = "#ffffff" }
        hl.NavicIconsKey = { bg = c.bg_dark, fg = "#ffffff" }
        hl.NavicIconsNull = { bg = c.bg_dark, fg = "#ffffff" }
        hl.NavicIconsEnumMember = { bg = c.bg_dark, fg = "#ffffff" }
        hl.NavicIconsStruct = { bg = c.bg_dark, fg = "#ffffff" }
        hl.NavicIconsEvent = { bg = c.bg_dark, fg = "#ffffff" }
        hl.NavicIconsOperator = { bg = c.bg_dark, fg = "#ffffff" }
        hl.NavicIconsTypeParameter = { bg = c.bg_dark, fg = "#ffffff" }
        hl.NavicText = { bg = c.bg_dark, fg = "#ffffff" }
        hl.NavicSeparator = { bg = c.bg_dark, fg = "#ffffff" }
      end,
    },
  },
```
should do it for tokyonight.

**Comment by kiyoon** [comment]
@dpetka2001 Thanks for looking into this. I will try out after weekends. I think maybe if you do `hilink` linking Navic* to lualine hlgroup it will be a non colourscheme specific solution

**Comment by dpetka2001** [comment]
So if you create an autocmd with the following
```lua
autocmd("Colorscheme", {
  pattern = "*",
  callback = function()
    vim.cmd([[
      hi link NavicText lualine_c_normal
      hi link NavicIconsFile lualine_c_normal
      hi link NavicIconsModule lualine_c_normal
      hi link NavicIconsNamespace lualine_c_normal
      hi link NavicIconsPackage lualine_c_normal
      hi link NavicIconsClass lualine_c_normal
      hi link NavicIconsMethod lualine_c_normal
      hi link NavicIconsProperty lualine_c_normal
      hi link NavicIconsField lualine_c_normal
      hi link NavicIconsConstructor lualine_c_normal
      hi link NavicIconsEnum lualine_c_normal
      hi link NavicIconsInterface lualine_c_normal
      hi link NavicIconsFunction lualine_c_normal
      hi link NavicIconsVariable lualine_c_normal
      hi link NavicIconsConstant lualine_c_normal
      hi link NavicIconsString lualine_c_normal
      hi link NavicIconsNumber lualine_c_normal
      hi link NavicIconsBoolean lualine_c_normal
      hi link NavicIconsArray lualine_c_normal
      hi link NavicIconsObject lualine_c_normal
      hi link NavicIconsKey lualine_c_normal
      hi link NavicIconsNull lualine_c_normal
      hi link NavicIconsEnumMember lualine_c_normal
      hi link NavicIconsStruct lualine_c_normal
      hi link NavicIconsEvent lualine_c_normal
      hi link NavicIconsOperator lualine_c_normal
      hi link NavicIconsTypeParameter lualine_c_normal
      hi link NavicText lualine_c_normal
      hi link NavicSeparator lualine_c_normal
    ]])
  end,
  group = "mygroup",
  desc = "Set highlight groups for navic",
})
```
it should work for every colorscheme (I tried it with rose-pine and kanagawa). For some reason tokyonight doesn't seem to take it into account. So I ended up keeping the tokyonight configuration in the previous post as well.

**Comment by moxuze** [comment]
> So if you create an autocmd with the following
> 
> ```lua
> autocmd({ "Colorscheme", "BufReadPre", "BufNewFile" }, {
>   pattern = "*",
>   callback = function()
>     vim.cmd([[
>       hi link NavicText lualine_c_normal
>       hi link NavicIconsFile lualine_c_normal
>       hi link NavicIconsModule lualine_c_normal
>       hi link NavicIconsNamespace lualine_c_normal
>       hi link NavicIconsPackage lualine_c_normal
>       hi link NavicIconsClass lualine_c_normal
>       hi link NavicIconsMethod lualine_c_normal
>       hi link NavicIconsProperty lualine_c_normal
>       hi link NavicIconsField lualine_c_normal
>       hi link NavicIconsConstructor lualine_c_normal
>       hi link NavicIconsEnum lualine_c_normal
>       hi link NavicIconsInterface lualine_c_normal
>       hi link NavicIconsFunction lualine_c_normal
>       hi link NavicIconsVariable lualine_c_normal
>       hi link NavicIconsConstant lualine_c_normal
>       hi link NavicIconsString lualine_c_normal
>       hi link NavicIconsNumber lualine_c_normal
>       hi link NavicIconsBoolean lualine_c_normal
>       hi link NavicIconsArray lualine_c_normal
>       hi link NavicIconsObject lualine_c_normal
>       hi link NavicIconsKey lualine_c_normal
>       hi link NavicIconsNull lualine_c_normal
>       hi link NavicIconsEnumMember lualine_c_normal
>       hi link NavicIconsStruct lualine_c_normal
>       hi link NavicIconsEvent lualine_c_normal
>       hi link NavicIconsOperator lualine_c_normal
>       hi link NavicIconsTypeParameter lualine_c_normal
>       hi link NavicText lualine_c_normal
>       hi link NavicSeparator lualine_c_normal
>     ]])
>   end,
>   group = "mygroup",
>   desc = "Set highlight groups for navic",
> })
> ```
> 
> it should work for every colorscheme (I tried it with rose-pine and kanagawa). For some reason tokyonight doesn't seem to take it into account. So I ended up keeping the tokyonight configuration in the previous post as well. To solve this problem without having to keep the tokyonight configuration maybe the maintainer has a better answer as to how to achieve the desired result.

Thanks for your method, but it doesn't work when activating other modes, lualine will change highlights into something like `lualine_c_insert` dynamically. I guess you want to setup like:
```lua
  {
    "SmiteshP/nvim-navic",
    opts = {
      highlight = false,
    },
  },
```
Unfortunately all colors will be cleared in this way.

**Comment by dpetka2001** [comment]
Well yes, you would have to do the same for the other modes as well. It's just repetetive code and didn't test it further. That's why most colorschemes that support `lualine` make same or different colors for different modes. As i said the easiest way would be for the colorscheme to support `navic` inherently and then you can just change the settings in your colorscheme. The code in the previous post was just an attempt to a solution agnostic to a colorscheme, but I don't know how practical this is.

**Comment by folke** [comment]
The way it currently looks in TokyoNight, is on purpose. As @dpetka2001 mentioned, you can change the colors to somehting else if you like

**Comment by kiyoon** [comment]
@dpetka2001 I tried your solution but it made all icons lose colour.
@folke I didn't know it was intentional.
Thanks everyone for looking into this :)

**Comment by dpetka2001** [comment]
@kiyoon Please try this
```lua
        hl.NavicIconsFile = { bg = c.bg_dark, fg = c.fg }
        hl.NavicIconsModule = { bg = c.bg_dark, fg = c.yellow }
        hl.NavicIconsNamespace = { bg = c.bg_dark, fg = c.fg }
        hl.NavicIconsPackage = { bg = c.bg_dark, fg = c.fg }
        hl.NavicIconsClass = { bg = c.bg_dark, fg = c.orange }
        hl.NavicIconsMethod = { bg = c.bg_dark, fg = c.blue }
        hl.NavicIconsProperty = { bg = c.bg_dark, fg = c.green1 }
        hl.NavicIconsField = { bg = c.bg_dark, fg = c.green1 }
        hl.NavicIconsConstructor = { bg = c.bg_dark, fg = c.orange }
        hl.NavicIconsEnum = { bg = c.bg_dark, fg = c.orange }
        hl.NavicIconsInterface = { bg = c.bg_dark, fg = c.orange }
        hl.NavicIconsFunction = { bg = c.bg_dark, fg = c.blue }
        hl.NavicIconsVariable = { bg = c.bg_dark, fg = c.magenta }
        hl.NavicIconsConstant = { bg = c.bg_dark, fg = c.magenta }
        hl.NavicIconsString = { bg = c.bg_dark, fg = c.green }
        hl.NavicIconsNumber = { bg = c.bg_dark, fg = c.orange }
        hl.NavicIconsBoolean = { bg = c.bg_dark, fg = c.orange }
        hl.NavicIconsArray = { bg = c.bg_dark, fg = c.orange }
        hl.NavicIconsObject = { bg = c.bg_dark, fg = c.orange }
        hl.NavicIconsKey = { bg = c.bg_dark, fg = c.purple }
        hl.NavicIconsNull = { bg = c.bg_dark, fg = c.purple }
        hl.NavicIconsEnumMember = { bg = c.bg_dark, fg = c.orange }
        hl.NavicIconsStruct = { bg = c.bg_dark, fg = c.green1 }
        hl.NavicIconsEvent = { bg = c.bg_dark, fg = c.orange }
        hl.NavicIconsOperator = { bg = c.bg_dark, fg = c.orange }
        hl.NavicIconsTypeParameter = { bg = c.bg_dark, fg = c.fg }
        hl.NavicText = { bg = c.bg_dark, fg = c.green1 }
        hl.NavicSeparator = { bg = c.bg_dark, fg = c.fg }
```
I shouldn't have overriden the default fg_colors.

**Comment by kiyoon** [comment]
@dpetka2001 Thanks a lot! You're amazing :)
I changed the `hl.NavicText = { bg = c.bg_dark, fg = c.green1 }` to `fg = c.fg` because the texts were in green and it used to be white. But now I see how it works and I really appreciate the solution!

**Comment by dpetka2001** [comment]
Yes, I changed that as well. It must have been some wrong copy/paste from my part.
