### ISSUE TITLE
bug: eslint is sometimes extremely slow

### ISSUE THREAD

**Issue by omelette-watin** [LazyVim/LazyVim#3281]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Macos Sonoma

### Describe the bug

Eslint lsp is sometimes extremely slow (sometime format appears letter by letter) and often timeout with a `WARN [Lsp][Eslint] timeout` especially when using `prettier-plugin-tailwindcss`.
It didn't happen before all the releases and the bump of eslint-lsp from 4.8 to 4.10.

I also noticed this warning in LspLog
`The language server eslint triggers a registerCapability handler for workspace/didChangeWorkspaceFolders despite dynamicRegistration set to false. Report upstream, this warning is harmless`

### Steps To Reproduce

1. Install lazyvim
2. add eslint extras
3. open a large typescript project with at least prettier-plugin-tailwindcss

### Expected Behavior

Eslint formatting shouldnt be that slow

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
What does this have to do with LazyVim? Report that at `eslint`'s repo. I've seen other issues that people had with eslint-lsp 4.10 and most of them downgraded to 4.8.
