### ISSUE TITLE
bug: Auto Jump Includes Declaration

### ISSUE THREAD

**Issue by rkk1995** [LazyVim/LazyVim#3282]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

dev

### Operating system/version

Ubuntu 22.04

### Describe the bug

It seems `auto_jump` doesn't work as intended (or IMO as it should). I added a feature to the Trouble v2 here - https://github.com/folke/trouble.nvim/pull/312 to ignore the declaration when one does `TroubleToggle references` or similar LSP related functions.

I think `auto_jump`  should ignore the declaration. 

### Steps To Reproduce

1. Open any file where LSP is enabled.
2. Have a function defined and call it once elsewhere.
3. Go to the function and run `:Trouble lsp_references`.

The Trouble window will have the declaration AND the call site.  

### Expected Behavior

With auto_jump = true, it should just jump to the call site.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
That's not really a LazyVim issue is it?
I'd also highly suggest using Trouble v3.
Closing.

**Comment by rkk1995** [comment]
Ah whoops, meant to put it in Trouble. Was trying to add the ignore declaration logic into Trouble v3 (exists in v2). I’ll create it there.
