### ISSUE TITLE
bug: extra trouble-v3 has keys conflict with extra outline

### ISSUE THREAD

**Issue by ylchen07** [LazyVim/LazyVim#3286]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

MacOS 14.5

### Describe the bug

I have enabled the extra outline and trouble-v3 at the same time, 
They use the exact same `<leader>cs` key to trigger

Configure file
[outline.lua](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/extras/editor/outline.lua)
[trouble-v3](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/extras/editor/trouble-v3.lua)

### Steps To Reproduce

1. Add below two line of config in the `lazy.lua`
```lua
    { import = "lazyvim.plugins.extras.editor.outline" },
    { import = "lazyvim.plugins.extras.editor.trouble-v3" },

```

2. Restart lazyvim
3. Open a new `yaml` file or `markdown` file
4. Use `<leader>cs` try to display the outline, but trouble setting override the outline setting

### Expected Behavior

Purpose to use `<leader>co` for outline display to avoid the conflict.

**Comment by folke** [comment]
That's on purpose. You should only enable one of them since they provide similar functionality
