### ISSUE TITLE
bug: format on save in markdown files changes raw links like https://link.to/sth into <https://link.to/sth>

### ISSUE THREAD

**Issue by rofrol** [LazyVim/LazyVim#3295]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

MacOS 14.5

### Describe the bug

 format on save in markdown files changes raw links like `https://link.to/sth` into `<https://link.to/sth>`
 
 Sorry, I do not know which plugin does this. conform.nvim?

### Steps To Reproduce

1. Have code like `https://link.to/sth`.
2. Save.

### Expected Behavior

Link stays `https://link.to/sth`.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
You can check with :LazyFormatInfo

Closing since this is not a Lazyvim bug

**Comment by rofrol** [comment]
For other that got hit by this bug:

To disable formatting for markdown files, I've added this to `nvim/lua/config/options.lua`:

```lua
-- disable autoformat for markdown files
vim.api.nvim_create_autocmd({ "FileType" }, {
  pattern = { "markdown" },
  callback = function()
    vim.g.autoformat = false
  end,
})
```

- https://vi.stackexchange.com/questions/42597/how-to-disable-autoformating-on-save-on-lazyvim/43698#43698
- https://www.reddit.com/r/neovim/comments/1766fl1/lazyvim_1000_has_been_released/

**Comment by dpetka2001** [comment]
You better disable it locally for buffers of Markdown only instead of globally with `vim.b.autoformat = false`.

**Comment by rofrol** [comment]
So to disable this, you need to add file `.markdownlint.jsonc` to your project root with content:

```jsonc
{
  // Default state for all rules
  "default": true,
  // Path to configuration file to extend
  "extends": null,
  // MD034/no-bare-urls : Bare URL used : https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md034.md
  "MD034": true,
}
```

**Comment by rofrol** [comment]
Another option is with conform.nvim to change default:

`["markdown"] = { { "prettierd", "prettier" }, "markdownlint", "markdown-toc" }` to omit "markdownlint".

```lua
  {
    "stevearc/conform.nvim",
    optional = true,
    opts = {
      formatters_by_ft = {
        ["markdown"] = { { "prettierd", "prettier" }, "markdown-toc" }
    },
  },
```
