### ISSUE TITLE
bug: Opening nv then hitting <leader>qs very fast results in the opened buffer not having any highlights/colors?

### ISSUE THREAD

**Issue by amaanq** [LazyVim/LazyVim#33]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.0-dev-588+g99cf11128

### Operating system/version

Arch Linux 6.1.4-zen2-1

### Describe the bug

Open a project you've edited before with this spec, restore session with <leader>qs as *fast* as you can, you'll see sometimes the opened buffer will be all white text, which can be fixed with :e. I have no idea how to go about debugging this, nor is this really an issue as it's rare I restore a session that fast to begin wtih.

### Steps To Reproduce

1. Open neovim
2. <leader>qs or require("persistence").load() (impossible to be fast enough without a bind)
3. voila

### Expected Behavior

Syntax highlighting is ok

### Repro

Used your dots for nvim to check if it was just mine, that also has an issue, so not sure if it's from the dots or LazyVim.

**Comment by folke** [comment]
I can't reproduce this. Very weird. The Alpha dashboard has a shortcut to load your session with the `s` key. But even when doing it very fast, everything still loads as it should be.

Are you running nightly? That's a bit unstable now, so maybe that's causing issues. I've also just pushed a change related to notify, which may have fixed this somehow maybe? No idea, but I don't have this on my machine

**Comment by amaanq** [comment]
I wasn't using nightly, but cleaning every package with lazy then reinstalling seems to fixed it, dunno what happened but seems ok now, sorry about that :)
