### ISSUE TITLE
bug: Hello, I want to modify the icon of diagnostics, but I configured the following icon options. Why does this not make the icon modification take effect successfully?

### ISSUE THREAD

**Issue by czfadmin** [LazyVim/LazyVim#3309]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10

### Operating system/version

window 11

### Describe the bug

Hello, I want to modify the icon of diagnostics, but I configured the following icon options. Why does this not make the icon modification take effect successfully?

![image](https://github.com/LazyVim/LazyVim/assets/13393959/9fda82a0-e424-4e61-8d79-c786e7da900a)
![image](https://github.com/LazyVim/LazyVim/assets/13393959/bb1608b8-ffba-48fc-baa1-9b15a67d0be0)
![image](https://github.com/LazyVim/LazyVim/assets/13393959/f4d63e58-07fc-4153-adf6-b151cf49ff76)

After modification, nvim has been restarted.

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"

if not (vim.uv or vim.loop).fs_stat(lazypath) then
  -- bootstrap lazy.nvim
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

require("lazy").setup({
  spec = {
    -- add LazyVim and import its plugins
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- import any extras modules here
    -- { import = "lazyvim.plugins.extras.lang.typescript" },
    -- { import = "lazyvim.plugins.extras.lang.json" },
    -- { import = "lazyvim.plugins.extras.ui.mini-animate" },
    -- import/override with your plugins
    { import = "plugins" },
  },
  defaults = {
    -- By default, only LazyVim plugins will be lazy-loaded. Your custom plugins will load during startup.
    -- If you know what you're doing, you can set this to `true` to have all your custom plugins lazy-loaded by default.
    lazy = false,
    -- It's recommended to leave version=false for now, since a lot the plugin that support versioning,
    -- have outdated releases, which may break your Neovim install.
    version = false, -- always use the latest git commit
    -- version = "*", -- try installing the latest stable version for plugins that support semver
  },
  install = { colorscheme = { "sonokai" } },
  checker = { enabled = true }, -- automatically check for plugin updates
  performance = {
    rtp = {
      -- disable some rtp plugins
      disabled_plugins = {
        "gzip",
        -- "matchit",
        -- "matchparen",
        -- "netrwPlugin",
        "tarPlugin",
        "tohtml",
        "tutor",
        "zipPlugin",
      },
    },
  },
  icons = {
    diagnostics = {
      Error = "  ",
      Warn = "  ",
      Hint = "  ",
      Info = "  ",
    },
  },
})


```

### Steps To Reproduce

1. Add custom icon configuration in config
2. Restart nvim

### Expected Behavior

gutter icon modified successfully

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Those icons are an option for the LazyVim plugin. It's all in the docs.
https://www.lazyvim.org/configuration#icons--colorscheme

**Comment by czfadmin** [comment]
Thank you very much. I misread this configuration. I'll try it later. This project is great.

**Comment by czfadmin** [comment]
@folke Why do I have this effect when I configure it this way?

![image](https://github.com/LazyVim/LazyVim/assets/13393959/4c725515-211d-4813-b689-652dd7857a00)

This is my configuration:
```lua
-- Configure LazyVim to load gruvbox
return {
  "LazyVim/LazyVim",
  opts = {
    colorscheme = "sonokai",
    icons = {
      diagnostics = {
        Error = "",
        Warn = "",
        Hint = "",
        Info = "",
      },
    },
  },
}
```

**Comment by dpetka2001** [comment]
Because this way has been deprecated for the LSP diagnostic icons. You should change them in 
```lua
{
  "neovim/nvim-lspconfig",
  opts = {
      diagnostics = {
        signs = {
          text = {
            [vim.diagnostic.severity.ERROR] = your_sign_1,
            [vim.diagnostic.severity.WARN] = your_sign_2,
            [vim.diagnostic.severity.HINT] = your_sign_3,
            [vim.diagnostic.severity.INFO] = your_sign_4,
          },
        },
      },
  },
}
```

**Comment by dpetka2001** [comment]
Actually it should happen with the changing the icons in LazyVim spec, but I believe that `nvim-lspconfig` `opts` are getting parsed during parsing phase, thus `LazyVim.config.icons.diagnostics` is getting required at that moment and gets the icon from the default config instead of what the user has specified in his personal configuration. 

If we make `opts` a function, then `LazyVim.config.icons.diagnostics` get evaluated when `nvim-lspconfig` gets loaded and it takes correctly into consideration whatever icon the user has changed in his personal configuration for LazyVim spec.

**Comment by czfadmin** [comment]
> 因为这种方式已不再适用于LSP诊断图标。您应该在代码中进行更改。
> 
> ```lua
> {
>   "neovim/nvim-lspconfig",
>   opts = {
>       diagnostics = {
>         signs = {
>           text = {
>             [vim.diagnostic.severity.ERROR] = your_sign_1,
>             [vim.diagnostic.severity.WARN] = your_sign_2,
>             [vim.diagnostic.severity.HINT] = your_sign_3,
>             [vim.diagnostic.severity.INFO] = your_sign_4,
>           },
>         },
>       },
>   },
> }
> ```

@dpetka2001. Thank you. It is indeed possible to modify the diagnostic icon. I feel that adding this feature is very good. Because as a user of lazyvim, many people want to beautify the lazyvim theme they use.
