### ISSUE TITLE
bug: remap ; to :. ; does not trigger popup command window

### ISSUE THREAD

**Issue by dontdieych** [LazyVim/LazyVim#3316]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0

### Operating system/version

Arch Linux

### Describe the bug

remap ; to : ; does not trigger popup command window

Even it does not shows command popup, input command after ; works. e.g. ;q

### Steps To Reproduce

cat ~/.config/lazyvim/lua/config/keymaps.lua

local map = LazyVim.safe_keymap_set

map({ "i", "x", "n", "s" }, "<C-s>", "<cmd>w<cr><esc>", { desc = "Save File" })
map({ "v", "n" }, ";", ":", { desc = "Excute command" }

### Expected Behavior

; key trigger command input popup window.

**Comment by dpetka2001** [comment]
Why don't you try `vim.keymap.set("n", ";", ":", {remap = true})`? Also in your `keymaps.lua` you're not supposed to use `LazyVim.safe_keymap_set`, but `vim.keymap.set` instead as mentioned [here](https://github.com/LazyVim/LazyVim/blob/0f6ff53ce336082869314db11e9dfa487cf83292/lua/lazyvim/config/keymaps.lua#L3-L4).

**Comment by dontdieych** [comment]
Thanks. It solved.
