### ISSUE TITLE
bug: freeze on neovim v0.10.0 on Fedora with extra go dap and other extras

### ISSUE THREAD

**Issue by longwuyuan** [LazyVim/LazyVim#3321]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

% nvim --version NVIM v0.10.0 Build type: RelWithDebInfo LuaJIT 2.1.1707061634 Run "nvim -V1 -v" for more info

### Operating system/version

Fedora40

### Describe the bug

Neovim freezes and the cursor blinks at a unbeleivably extreme high speed (as if there was some reconciling or similar background event occurring). 

Please advise where to look for logs of background activity or should I strace the nvim process etc.

Extremely sorry for any mistake here as I am a longtime sysadmin but baffled on how to debug the freeze.

Problem started after bumping to neovim v0.10.x. It was not freezing or having any problems while I was on neovim v0.9.5

### Steps To Reproduce

1. Create a Fedora40 host
2. Update and upgrade dnf
3. Install Neovim to ensure the version is neovim v0.10.0
5. Install Lazyvim exactly as documented
```
git clone https://github.com/LazyVim/starter ~/.config/nvim
```
6. Enable extras as seen in screenshot below
```
"extras": [                                                                                                                                                                     
   3   │ │ "lazyvim.plugins.extras.coding.luasnip",                                                                                                                                      
   4   │ │ "lazyvim.plugins.extras.coding.mini-surround",                                                                                                                                
   5   │ │ "lazyvim.plugins.extras.coding.yanky",                                                                                                                                        
   6   │ │ "lazyvim.plugins.extras.dap.core",                                                                                                                                            
   7   │ │ "lazyvim.plugins.extras.dap.nlua",                                                                                                                                            
   8   │ │ "lazyvim.plugins.extras.formatting.black",                                                                                                                                    
   9   │ │ "lazyvim.plugins.extras.lang.docker",                                                                                                                                         
  10   │ │ "lazyvim.plugins.extras.lang.go",                                                                                                                                             
  11   │ │ "lazyvim.plugins.extras.lang.helm",                                                                                                                                           
  12   │ │ "lazyvim.plugins.extras.lang.json",                                                                                                                                           
  13   │ │ "lazyvim.plugins.extras.lang.markdown",                                                                                                                                       
  14   │ │ "lazyvim.plugins.extras.lang.python",                                                                                                                                         
  15   │ │ "lazyvim.plugins.extras.lang.terraform",                                                                                                                                      
  16   │ │ "lazyvim.plugins.extras.lang.toml",                                                                                                                                           
  17   │ │ "lazyvim.plugins.extras.lang.yaml",                                                                                                                                           
  18   │ │ "lazyvim.plugins.extras.test.core"                                                                                                                                            
  19   │ ],                                                                                                                                                                              
  20   │ "news": {                                                                                                                                                                       
  21   │ │ "NEWS.md": "4964"                                                                                                                                                             
  22   │ },                                                                                                                                                                              
  23   │ "version": 4                                                                                                                                                                    
  24   }                                
```
![image](https://github.com/LazyVim/LazyVim/assets/5085914/b24b3089-d376-4757-aa9a-b3eb7327a3d5)
8. Create 2 plugin files. One each for 2 of the recipes from docs, as seen in screenshot below
![image](https://github.com/LazyVim/LazyVim/assets/5085914/e0f8e69a-e30f-474c-8f44-4f86558e8f8a)
9. Now stop and restart nvim
10. Open this go file  https://github.com/inancgumus/learngo/blob/master/13-loops/10-word-finder-labeled-switch/main.go  or any file
11. Observe the cursor blinks extremely extremely fast in neovim occasionaly while typing and when it does, neovim freezes

### Expected Behavior

Able to see the logs of neovim background activiry during freeze and cursor blinking at extreme extreme super high speed

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
I'm sorry to say this, but this is not a minimal repro. Please try with default LazyVim installation. Does this behavior occur? Then start enabling the Extras one by one until you figure out what is causing this behavior. You can't expect others to go through all this configuration and debug it.

**Comment by longwuyuan** [comment]
Understood. Fair and appropriate. I assumed someone may know. For example the new feature of inlay.hints kicked in automatically and I started seeing hints after the upgrade of neovim to v0.10.0 from v0.9.5 .

I had to now start using the menu option <space>><u><h> to suppress the hints.

Thanks

**Comment by dpetka2001** [comment]
Yes inlay hints are enabled by default on Neovim 0.10+. To disable them you can create a file `~/.config/nvim/lua/plugins/lsp.lua` with following contents
```lua
return {
  {
    "neovim/nvim-lspconfig",
    opts = {
      inlay_hints = {
        enabled = false,
      },
      -- document_highlight = {
      --   enabled = false,
      -- },
    },
  },
}
```
The commented section doesn't have to do anything with inlay hints, but maybe you could try uncommenting it to see if you don't observe the behavior you mentioned any more. If you still see the same behavior after uncommenting it, you should try to figure out which Extra causes it by enabling them one by one.

**Comment by folke** [comment]
I actually tried with your steps, but I'm not able to reproduce this.

Can you do `:Noice disable` and see whether the issue is gone after that?

I also see that you use luasnip, but you're using the supertab recipe for Neovim's builtin snippets.

Additionally, the recipe for fzf-native is no longer needed, since that's now included by default in LazyVim (I just removed it from the docs)

**Comment by longwuyuan** [comment]
@dpetka2001 thank you very much. I tried it and seems to work. Gratitude.

@folke thanks tons for the not just this but everything else you have done. I am trying to disable/history/log Noice, but the freeze is not allowing me to even complete typing `:Noice disable`.  I will keep trying

**Comment by dpetka2001** [comment]
Just try to disable `noice` in the plugin spec. So setting in a file 
```lua
{
  "folke/noice.nvim",
  enabled = false,
}
```
And then restart Neovim. `noice` shouldn't be installed and enabled any more.

**Comment by longwuyuan** [comment]
@dpetka2001 @folke now, after setting inlay.hints to `false` and  stopping/restarting neovim, I think that super-fasting blinking cursor & freeze have not occurred for at least 2-3 minutes.

I will also disable `Noice` as you suggested now.

**Comment by dpetka2001** [comment]
Now with Noice disabled can you re-enable inlay hints to see if that's what causes the issue?

**Comment by longwuyuan** [comment]
Ah, I think there is a lot of improvement. I have waited 120 seconds or more after disabling `Noice` + re-enabling `inlay.hints`, but the lightening-fast-blinking and freeze has not occurred. I am super grateful & thankful for the world of blessings from you. :pray:

**Comment by longwuyuan** [comment]
I had seen a message earlier on a different issue about the update to LazyVim. And I habitually press `l` and `s` to sync lazy so I assumed I was on latest.

But the last time I stopped and restarted neovim, I saw a brief message flash that lazy was upgraded to version 5. I guess that was very very significant.

**Comment by dpetka2001** [comment]
So if you re-enable Noice then the issue starts occuring again? Noice was the culprit? LazyVim default installation comes with Noice pre-installed. Do you observe the same behavior with default LazyVim installation?

**Comment by longwuyuan** [comment]
I will re-enable `Noice` now by removing that file that disables it. And update asap.

**Comment by longwuyuan** [comment]
Before I could  re-enable `Noice`, I was  alt-tabbing between firefox & terminal, and I the lightening-fast-blinking-cursor started happening again.

Also, I can reproduce the flashing-fast-cursor-blinking almost every-time I switch between firefox & terminal (terminal where neovim has a file opened).  But now the blinking cursor makes cursor movement extreme-snail-pace slow but not a complete locked-up-freeze like before.

I will restart neovim and check again (still with `Noice` disabled first and after enabling it next)

**Comment by dpetka2001** [comment]
What terminal are you using? Can you try a different one?

**Comment by longwuyuan** [comment]
ok. Its just the default gnome-terminal that ships with Fedora. I will try alacritty.

But now, with ;
- disabled Noice
- inlay.hints NOT disabled
- restart neovim
- gnome-terminal
- switched back & forth between firefox/terminal
- neovim v0.10.0

I also pushed my nvim dir here https://github.com/longwuyuan/nvim-config

**Comment by longwuyuan** [comment]
With above state, there is a brief blinking but no crippling freeze

**Comment by dpetka2001** [comment]
Do you by any chance use tmux?

**Comment by longwuyuan** [comment]
Apologies for  dumb question but where can I tail the logs of live neovim background activity  (short of doing a strace)

**Comment by longwuyuan** [comment]
oh yes, all this on a tmux window

**Comment by dpetka2001** [comment]
Do you observe the same behavior outside of tmux?

**Comment by longwuyuan** [comment]
if tmux and refresh after switching from firefox is causing this, I will live with it as the freeze is not crippling. But neovim v0.9.5 with tmux with same config (without the new inlay.hints enabled that shipped with nvim0.10), there was never blinking or freeze. So I guess just need to avoid tmux and use a supported terminal emulator !

**Comment by longwuyuan** [comment]
checking behaviour outside tmux now

**Comment by longwuyuan** [comment]
ok, confirmed that blinking is almost nil without tmux. But blinking is rampant after a switch from firefox. Although, there is negligible freeze experience while blinking is in progress (in tmux). After the blinking stops in 5-8 seconds, its not disrupting use of Neovim.

**Comment by dpetka2001** [comment]
Can you try with kitty terminal and tmux?

**Comment by longwuyuan** [comment]
ok trying with kitty terminal & tmux

**Comment by longwuyuan** [comment]
also, I spoke too soon.

Even though a slight switch back from firefox looked workable, the freezes do occur during a continued use of neovim in terminal tmux. I was typing for roughly 3 minutes and now freezes are frequent enough to disrupt work.

will update status with kitty-terminal+tmux

**Comment by longwuyuan** [comment]
No blinking or freeze/lockup with ;
- kitty-terminal
- tmux
- `Noice` disabled
- hints enabled

**Comment by folke** [comment]
When do you exerience the blinking? Is it only during search, or when the cmdline is active?

**Comment by dpetka2001** [comment]
Can you re-enable Noice with kitty+tmux and see if it still occurs or not?

**Comment by longwuyuan** [comment]
- blinking is guranteed on each switch from firefox to a go file in neovim v0.10.0 in gnome-terminal in a tmux window. But core issue now is lockup accompanied with blinking on alt-tabbling back from firefox first.

- More critically problem now is this. After the initial focus back from firefox to neovim, the blinking stops after 5-8 seconds and I can resume typing in neovim after 8 seconds or 10 seonds. But after resuming and withing 30 seconds neovim just locks up and freezes and no key/mouse stroke/button works. And it stays lockedup for at least for 10 seconds nad often more. So every 30 seonds, there is a lockup of 10 seconds.

**Comment by longwuyuan** [comment]
ok, re-enabling Noice in kitty and testing.

**Comment by longwuyuan** [comment]
NO blinking or freezing with ;
- kitty terminal-emulator
- tmux
- Neovim 0.10.0 opened a go file
- `Noice` enabled
- `hints` enabled
- Multiple back&forth between firefox & kitty

**Comment by folke** [comment]
The problem might be yanky and it's synching to the clipboard.
Can you disable yanky and try again?
I've seen similar issues on Gnome. (not using gnome myself though)

**Comment by folke** [comment]
See also https://github.com/gbprod/yanky.nvim/issues/37

**Comment by folke** [comment]
Maybe my fix for yanky no longer works

**Comment by longwuyuan** [comment]
ok thanks tons. Removing yanky and testing on gnome-terminal now

**Comment by longwuyuan** [comment]
You were right. Problem almost certainly seems related to yanky.

NO blinking & NO Freeze now with ;
- gnome-terminal-emulator
- tmux
- Noice enabled
- Hints enabled

There are no words to express gratitude for all the good software and all the help the world receives from you. More power to you.

**Comment by folke** [comment]
ok, great. Then it's probably best to submit an issue to yanky and reference the issue I mentioned

**Comment by folke** [comment]
Either way, I'd still suggest you to use wezterm or kitty. Better terminals than Gnome's terminal.

**Comment by dpetka2001** [comment]
What clipboard tool are you using for Neovim? Can you run `:checkhealth vim.provider` and see what it says about Clipboard?

**Comment by longwuyuan** [comment]
Thank you so very much.
- I will try to switch termnal emulator. Was blocked because easy menu for configuring a nerd font in gnome-terminal. 
- I will submit a issue at Yanky and reference the issue you mentioned. It all makes sense now

**Comment by longwuyuan** [comment]
wl-copy

I did not change any defaults so it seems to have picked up wl-copy as clipboard
![image](https://github.com/LazyVim/LazyVim/assets/5085914/8a927ece-4a05-4a26-b698-b07037814402)

**Comment by folke** [comment]
The problem is that launching wl-copy from Gnome, creates a new window. That triggers FocusLost in NEovim and right after, FocusGained.

Just submitted a fix for yanky https://github.com/gbprod/yanky.nvim/pull/183

**Comment by longwuyuan** [comment]
> The problem is that launching wl-copy from Gnome, creates a new window. That triggers FocusLost in NEovim and right after, FocusGained.
> 
> Just submitted a fix for yanky [gbprod/yanky.nvim#183](https://github.com/gbprod/yanky.nvim/pull/183)

I don't know how to thank you. I use bits authored by you almost all the time I am on a keyboard so much much gratitude and more power to you.
