### ISSUE TITLE
bug: lazygit.lua assumes non-windows path separator

### ISSUE THREAD

**Issue by curbol** [LazyVim/LazyVim#3327]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Windows 11

### Describe the bug

in [lazygit.lua](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/util/lazygit.lua), it creates some file paths that don't work on Windows because of the path separator.

```lua
M.theme_path = vim.fn.stdpath("cache") .. "/lazygit-theme.yml"
```

```lua
vim.env.LG_CONFIG_FILE = M.config_dir .. "/config.yml" .. "," .. M.theme_path
```

This file should be looking for the system path separator like in other areas

```lua
if package.config:sub(1, 1) == "\\" then
  -- windows specific logic
end
```

Maybe a global utility can be added like this:

```lua
local function get_path_separator()
  return package.config:sub(1, 1)
end

local function join_paths(...)
  local separator = get_path_separator()
  return table.concat({...}, separator)
end

local path1 = "home"
local path2 = "user"
local path3 = "documents"
local full_path = join_paths(path1, path2, path3)
```

### Steps To Reproduce

1. Install default LazyVim on Windows
2. Try to open lazygit with <leader>gg
3. Observe error message mentioning "The system cannot find the file specified" referencing `...\lazygit/config.yml`

Other info:
I'm running LazyVim in `zsh` shell with `wezterm` terminal. I got `zsh` working on windows using a guide like this: https://dev.to/equiman/zsh-on-windows-without-wsl-4ah9. I mention this in case `zsh` running in windows adds to the path separator issue.

### Expected Behavior

LazyGit (<leader>gg) should work on windows the same as MacOS and Linux.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Windows supports linux and mixed-style paths as well.
I just tried and for me it all worked correctly, so I assume zsh on Windows is the issue here.
I just pushed a change to use linux style paths in those two places.

**Comment by curbol** [comment]
Thanks for looking into this. I later found that the issue was that the config was missing on my machine. I'm not sure how that happened, maybe from when I uninstalled and reinstalled lazygit. Manually creating the `...lazygit/config.yml` file fixed the issue. So it wasn't the path separators. Sorry for the false-issue.
