### ISSUE TITLE
feature: use `vim.fs.root` introduced by `nvim-0.10` instead of `util/root.lua` ?

### ISSUE THREAD

**Issue by konosubakonoakua** [LazyVim/LazyVim#3329]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

nop

### Describe the solution you'd like

Since nvim 0.10 provides a new method `vim.fs.root`, is `util/root` still needed?

### Describe alternatives you've considered

use `vim.fs.root` instead

**Comment by konosubakonoakua** [comment]
https://neovim.io/doc/user/lua.html#vim.fs.root()

**Comment by dpetka2001** [comment]
This only seems to provide the ability to find the root directory based on the markers provided into the function. This looks to me more equivalent to `util.root.detectors.patterns` specifically. 

It doesn't account for the LSP servers `root_dir`. To use `vim.fs.root` for discovering LSP servers `root_dir`, we would have to specify every possible marker as a pattern for the `root_dir` of every LSP server (and that would also make it hardcoded and what if users wanted to change the LSP server's `root_dir` pattern in their personal configuration in `nvim-lspconfig` spec?). 

`util.root.detectors.lsp` gets the `root_dir` directly from the LSP client.

So, personally I fail to see how this can replace the whole `util.root`.
