### ISSUE TITLE
feature: Copilot Chat is missing visual mode behaviours

### ISSUE THREAD

**Issue by dusty-phillips** [LazyVim/LazyVim#3334]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Excited to see copilot chat as an extra as I use it extensively, but it's missing some functionality:

* If you select some text in your code and invoke copilot chat (with e.g. `:'<,'>CopilotChat<CR>`) copilot chat can remember your selection. After you've finished the interactive session, it is configured with the keybinding `<C-y>` to confirm that you want to replace the code that was previously selected with whatever CopilotChat most recently came up with. It's the most seamless flow I've found for working with this new fangled AI fad.
* I'm pretty sure the "Prompt Actions" menu only makes sense in the context of visual mode as well, or at least, it *also* makes sense in visual mode.
* CopilotChat pops up in awkward locations when you invoke it, so I think it's a prime candidate for edgy integration.

### Describe the solution you'd like

For the keybinding issue, I propose:
```lua
     keys = {
       {
         "<Leader>aa",
         ":'<,'>CopilotChat<CR>",
         mode = { "v" },
         desc = "Copilot Chat Selection",
       },
```

and also adding `mode = {"n", "v"}` to the prompt-actions menu.

For the optional edgy configuration, my (non-extra) configuration was like this:

```lua
   {
     "folke/edgy.nvim",
     event = "VeryLazy",
     opts = {
       exit_when_last = false,
       animate = {
         enabled = false,
       },
       wo = {
         winbar = true,
         winfixwidth = true,
         winfixheight = false,
         winhighlight = "WinBar:EdgyWinBar,Normal:EdgyNormal",
         spell = false,
         signcolumn = "no",
       },
       right = {
         {
           ft = "copilot-chat",
           title = "Copilot",
           size = { width = 0.18 },
         },
       },
     },
   }
```

### Describe alternatives you've considered

* Not sure we want to reuse the `aa` keybinding for this because when there's a visual selection and chat is already open, it's not a "toggle" action, it's a "focus with the selection" action. `ac` might be better?
* I could just disable the extra and keep my old configuration or extend the extra with the above configuration, but I thought it was worth sharing.

**Comment by folke** [comment]
Thank you for the suggestions!

What I changed:
* added mode `v` to the keymaps
* added an edgy integration

To change the active selection, you can just go back to the source buffer, make a new selection and then go back to copilot-chat. So there's no need to call `open` with the new selection.

I've also opened a PR to highlight the active selection when in the chat window:

https://github.com/CopilotC-Nvim/CopilotChat.nvim/pull/332

**Comment by folke** [comment]
Just made another update that enhances the chat view

![image](https://github.com/LazyVim/LazyVim/assets/292349/889eba35-9cd7-4edf-833d-20074ed6f915)

**Comment by dusty-phillips** [comment]
Seems to be working well! 🙏🏻
