### ISSUE TITLE
feature: set global variables in local config file

### ISSUE THREAD

**Issue by bryanniwa** [LazyVim/LazyVim#3337]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Lazyrc supported setting global variables in the config files. This provided an easy way to disable automatic formatting for a specific project. The new built-in lazy.nvim feature only seems to allow plugin specs and is therefore not a direct replacement.

### Describe the solution you'd like

I would like to be able to set global variables in the local config files.

### Describe alternatives you've considered

I saw the note in the LazyVim docs that mention using an autocommand to disable autoformatting which would work for my use-case although there's still the lack of feature parity.

**Comment by folke** [comment]
You can still change any globals like so:

```lua
vim.g.autoformat = false

-- return empty spec
return {}
```

**Comment by bryanniwa** [comment]
ah my bad. sorry about that. thanks for the quick response

**Comment by ravisumit33** [comment]
@folke Is there way to change `vim.g.autoformat` only for a particular project locall?

**Comment by dpetka2001** [comment]
Just create a `.lazy.lua` file at the root of your project with the contents of what Folke said in his previous reply.

**Comment by ravisumit33** [comment]
> Just create a `.lazy.lua` file at the root of your project with the contents of what Folke said in his previous reply.

Thanks, it worked. Wasn't able to find this in the documentation.
