### ISSUE TITLE
bug: lsp hover shows "no information available" twice

### ISSUE THREAD

**Issue by kapral18** [LazyVim/LazyVim#3342]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0 Build type: Release LuaJIT 2.1.1713773202 Run "nvim -V1 -v" for more info

### Operating system/version

MacOS 14.5

### Describe the bug

calling `vim.lsp.buf.hover()` produces "no available information" popup twice while lsp hover is actually successfully happening

https://github.com/LazyVim/LazyVim/assets/1625373/be61f3bf-c0d9-4ae2-bf43-094e036dff72

### Steps To Reproduce

1. Use lazyvim-starter
2. Switch off all plugins and extras
3. Go to any js or ts file and call `vim.lsp.buf.hover()` on any reference

### Expected Behavior

doesn't show no information popup when there is lsp data on hover present, or if shown at least show once not twice

### Repro

```Lua
vim.lsp.buf.hover() doesn't event work with this repro
```

**Comment by dpetka2001** [comment]
You must have multiple LSP servers attached to the buffer and not everyone has information about the symbol under the cursor. I noticed this when I had pyright and jedi and had disabled `HoverProvider` from pyright in favor of jedi. You can enable an option in `noice.nvim` to not show these messages. `opts.lsp.hover.silent = true`

For more info read noice's docs.

**Comment by kapral18** [comment]
> You must have multiple LSP servers attached to the buffer and not everyone has information about the symbol under the cursor. I noticed this when I had pyright and jedi and had disabled `HoverProvider` from pyright in favor of jedi. You can enable an option in `noice.nvim` to not show these messages. `opts.lsp.hover.silent = true`
> 
> For more info read noice's docs.

in the video I have disabled noice.nvim completely. For ts/js eslint/tailwind/css_modules + typescript-tools are present. 

But the thing is when I remove all plugins and disable all lazyextras I have exact same problem. Which means it's not my configuration but a lazyvim preset behavior

**Comment by dpetka2001** [comment]
I think it's because of `nvim-notify`. Try disabling it and see if you observe same behavior.

**Comment by kapral18** [comment]
without nvim-notify it prints twice to messages stack

![image](https://github.com/LazyVim/LazyVim/assets/1625373/2845e82e-f8ff-42c3-b3c7-4c977649aef6)

and if I disable all plugins and extras and disable nvim-notify I see nothing at all on hover

but switching off nvim-notify is not an optimal solution here because nvim-notify is needed. Any js/ts buffer has at any given moment at least 3 lsp clients working at the same time to complete missing parts of each  other, eslint  + tsserver + cssls, so I am surprised that this is a an actual problem

**Comment by dpetka2001** [comment]
Are you able to reproduce this with default LazyVim installation?

**Comment by dpetka2001** [comment]
This is default behavior for Neovim `vim.lsp.buf.hover()`. See [here](https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp/buf.lua#L33) where it is defined. It calls `request`, which is the function just above, which returns `vim.lsp.buf_request()`. That in turn is defined [here](https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp.lua#L862) and you can see from the comments that 
> --- Sends an async request for all active clients attached to the
--- buffer.

Since it sends the request to all active clients in the buffer, the ones that don't have information for the symbol under the cursor send back `Information not available`. If there are more than one server which doesn't have information available you will see more than one notification. 

So, not a LazyVim bug it seems.

**Comment by folke** [comment]
Noice does the same as the default lsp handler

**Comment by kapral18** [comment]
@dpetka2001 thanks for checking

This resolves the issue for me for good

https://github.com/neovim/neovim/issues/20457#issuecomment-1266782345

do you think this can be added to lazyvim as well?

**Comment by dpetka2001** [comment]
This is what noice does (overwriting the LSP buffer handler) and you can use the option I mentioned earlier to silence those notifications. If you don't use noice, then you have to do something similar in your personal configuration on your own.

**Comment by gugahoi** [comment]
This is still happening on a new installation of LazyVim. What's the recommended way to disable these notifications?

**Comment by dpetka2001** [comment]
Try configuring `noice.nvim` like following
```lua
return {
  {
    "folke/noice.nvim",
    opts = {
      lsp = {
        hover = { silent = true },
      },
    },
  }.
}
```
