### ISSUE TITLE
bug: friendly snippet (json) not expanding

### ISSUE THREAD

**Issue by lomaharshana** [LazyVim/LazyVim#3347]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Linux

### Describe the bug

vim-snippet error "Failed to parse snippet" on trying to expand 'property~' in python. Looks like nvim-snippet doesn't support  friendly-snippets of json format, and Luasnip has been removed. This used to work earlier, but stopped working after I refreshed the installation.

### Steps To Reproduce

1. Open new buffer
2. in insert mode type property
3. Select the property~ snippet and press enter
4. vim-snippet parse error.

### Expected Behavior

Should expand the snippet property

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
You can use the luasnip extra. vim.snippet indeed does not yet support all snippets
