### ISSUE TITLE
bug: `gco` and `gcO` emit a notification of `V`

### ISSUE THREAD

**Issue by stefanlogue** [LazyVim/LazyVim#3352]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0 release

### Operating system/version

MacOS 14.3

### Describe the bug

When performing `gco` or `gcO` in my `tmux.conf` file, a `noice` notification popped up with the content of `V`. This also happens in `.lua` files, assuming it happens in more.

### Steps To Reproduce

1. Have a line of text in any file
2. press `gco`/`gcO`

### Expected Behavior

A comment line is inserted in the correct place without the notification

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
I don't see that happening, so must be something in your config.

**Comment by folke** [comment]
Probably casued by this https://github.com/garymjr/nvim-snippets/issues/29#issuecomment-2135725993
