### ISSUE TITLE
bug: folding doesn't always work

### ISSUE THREAD

**Issue by OneOfOne** [LazyVim/LazyVim#3354]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.11.0-dev-6+g06135cc21

### Operating system/version

Arch Linux

### Describe the bug

Note that this also happens on nvim v0.9 and v0.10.

Trying to use folding (`za`) inside a go function returns `E490: no fold found`, setting foldmethod to indent works.

### Steps To Reproduce

create a simple go file:

```go
package main

import "fmt"

func main() {
	var x string
	fmt.Println(x)
}
```

Press `za` somewhere in the func body to fold.

### Expected Behavior

Fold the function.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
vim.opt.foldmethod = "expr"
vim.opt.foldexpr = "v:lua.require('lazyvim.util').ui.foldexpr()"
vim.opt.foldtext = "v:lua.require('config.utils').foldLines()"
```

**Comment by folke** [comment]
Then use indents? This is not a lazyvim issue. Probably something related to nvim-treesitter folds for golang
