### ISSUE TITLE
prev/next sometimes jumps to the wrong location

### ISSUE THREAD

**Issue by folke** [LazyVim/LazyVim#3359]
### Discussed in https://github.com/LazyVim/LazyVim/discussions/3349

<div type='discussions-op-text'>

<sup>Originally posted by **dusty-phillips** May 28, 2024</sup>
I have the trouble-v3 extra enabled, so I'm not 100% sure if this is a bug report against trouble or against the lazyvim configuration of trouble-v3. Since @folke owns both, I just flipped a coin as to which project to post in.

A flow I like to adopt is:

* use space-/ to search for some text in telescope
* hit ctrl-t to open the search results in trouble
* navigate between search results using ]q and [q

In my current (latest lazyvim with all plugins synced recently) setup, the last bullet point isn't work because trouble automatically moves the "selected" element to the list. So when I hit `]q`, it selects the next element as expected. But it moves it to the top of the list, so when I hit `]q` again, it simply alternates between the top-two elements instead of navigating down the list.

Workaround for now is to not use trouble, so I hit `ctrl-q` from the telescope window to put the items in quickfix instead of trouble.</div>

**Comment by folke** [comment]
@dusty-phillips @dpetka2001 this should be fixed now. Would be great if you can confirm!

**Comment by dusty-phillips** [comment]
Also working for me. ❤️

**Comment by folke** [comment]
Great!!
