### ISSUE TITLE
feature: Have LspInfo bordered based on value set for LazyVim's `ui.border` value

### ISSUE THREAD

**Issue by UtkarshVerma** [LazyVim/LazyVim#336]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

There's no problem. Just a minor UI change.

### Describe the solution you'd like

We can have the border of `LspInfo` window set to whatever value is set for `ui.border` in LazyVim's setup options for more consistency.

```lua
require('lspconfig.ui.windows').default_options.border = <LazyVim's border>
```

### Describe alternatives you've considered

Alternative would be for the user to configure it themselves.

**Comment by folke** [comment]
I'd rather keep this separate. The border you're refering to is a setting for lazy.nvim. Not for LazyVim.
