### ISSUE TITLE
bug: Cursor blinks wildly, with random inputs and long freezes on a clean install

### ISSUE THREAD

**Issue by rbpatt2019** [LazyVim/LazyVim#3361]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0 release

### Operating system/version

MacOS 14.5

### Describe the bug

After a clean install of Lazy Vim, any attempts to enter insert mode and type are met with a rapidly blinking mouse cursor, apparently random inputs (it will occasionally randomly select something from autocomplete and hit enter), and severe freezes when trying to issue `:q!` to close the file. 
After some sleuthing, I believe this is related to the neovim v0.10.0 update. Everything runs smoothly, as far as I can tell, on neovim v0.9.5, and breaks on v0.10.0. The only possibly related I can find is [this one](https://github.com/neovim/neovim/issues/28992) where there's an apparent regression of some mouse settings; however, testing the proposed solution (run `set mouse=`) in neovim v0.10.0 does not solve the problem.
It does seem specific to Lazy vim, as if I run nvim without Lazy Vim, all is as expected.

### Steps To Reproduce

1. Update to neovim v0.10.0
2. Perform a clean install of Lazy Vim. Make no further modifications.
3. Open a new file with nvim
4. Watch for rapidly blinking cursors and long freezes when interacting with command mode

### Expected Behavior

Lazy Vim should operate normally on the most recent version of neovim.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
Did you update `noice.nvim` to latest version of today?

**Comment by folke** [comment]
Are you sure you're on stable 0.10?
If you're on nightly, then you need to update it to the one from today, otherwise you'll have issues with noice.

Either way, can't reproduce with your steps. no blinking at all

**Comment by rbpatt2019** [comment]
@folke - I'm pretty sure it's the stable 0.10.0. I use Macports, and they are normally pretty good about getting their versions correct.
@dpetka2001 - I just went through and update everything, and it seems to have resolved! Possibly noice then. 

Thank you both for the quick insights and brilliant product 👍
