### ISSUE TITLE
bug: double use of key mapping 

### ISSUE THREAD

**Issue by msMatix** [LazyVim/LazyVim#3363]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Windows 10

### Describe the bug

For the clangd-extension the key-binding: `<leader>cR` is already used. This one was added `{ "<leader>cR", LazyVim.lsp.rename_file, desc = "Rename File", mode ={"n"}, has = "workspace/didRenameFiles"},` so is there a way to change that binding?

### Steps To Reproduce

Just Compare extension clangd and the keymappings.lua file

### Expected Behavior

Change of key-binding

**Comment by msMatix** [comment]
Thanks!

**Comment by folke** [comment]
Thank you for reporting!
