### ISSUE TITLE
bug: New vtsls server don't attach on astro files

### ISSUE THREAD

**Issue by jorgejhms** [LazyVim/LazyVim#3364]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

MacOs 14.4.1

### Describe the bug

New vtsls server don't get attach on Astro files

<img width="1470" alt="Captura de pantalla 2024-05-29 a la(s) 10 15 19 p  m" src="https://github.com/LazyVim/LazyVim/assets/5061624/a52c0388-835e-4fc8-867a-dc1ff95bf3a9">

### Steps To Reproduce

1. Load an Astro project.
2. Open .astro files
3. Check LspInfo

### Expected Behavior

Vstls should attach to .astro files to get autocompletition and correct types information.

**Comment by folke** [comment]
vtsls nor tsserver are supposed to attach to astro buffers?

You need astro language server?

**Comment by jorgejhms** [comment]
tsserver was attaching to Astro buffers as Astro include [typescript support)[https://docs.astro.build/en/guides/typescript/] for typing props and such . I recently updated to astro server and it's mostly working, but I found a another issue (was thinking to create a separate bug later). Importing Astro types definition into a .ts files is working on tsserver, while vtsserver gives me an error. Here the screenshots (personal config vs lazyvim)
<img width="1470" alt="Captura de pantalla 2024-05-31 a la(s) 11 12 25 a  m" src="https://github.com/LazyVim/LazyVim/assets/5061624/a6a191a3-c26e-4d40-9a32-3782c4758980">
<img width="1470" alt="Captura de pantalla 2024-05-31 a la(s) 11 12 39 a  m" src="https://github.com/LazyVim/LazyVim/assets/5061624/c36eac9d-b24f-469e-bea3-43f9bf6b0c9b">

**Comment by folke** [comment]
Yes, I still need to change that so that vtsls also includes the astro-ts plugin.
Although, a better way is actualy to include the plugin in your tsconfig.json file locally

**Comment by folke** [comment]
fyi: https://github.com/withastro/language-tools/tree/main/packages/ts-plugin

**Comment by folke** [comment]
https://github.com/mason-org/mason-registry/pull/5924

**Comment by folke** [comment]
This has now been fully implemented
