### ISSUE TITLE
bug: vtsls missing workspace symbols

### ISSUE THREAD

**Issue by jamgam** [LazyVim/LazyVim#3373]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.11.0-dev

### Operating system/version

Windows 11, WSL Ubuntu 22.04

### Describe the bug

Missing symbols using LSP Dynamic Workspace Symbols (Telescope) search when using `vtsls` from LazyVim Extras Typescript. Was able to get expected behavior by disabling LazyVim Extras Typescript and setting my own `lspconfig` for `tsserver`.  

### Steps To Reproduce

1. Open ts file in ts project with nvim. (small repro repo: https://github.com/jamgam/tslsp-test)
2. `<leader>sS` or run `:lua require("telescope.builtin").lsp_dynamic_workspace_symbols()`.
3. Observe that most symbols are missing.

### Expected Behavior

I should see all symbols in my workspace like when using tsserver.

**Comment by folke** [comment]
not really a LazyVim issue is it?
File an issue at the vtsls repo, if this is really broken.

**Comment by jamgam** [comment]
Makes sense. Wanted to bring it up since a recent lazyvim release changed the typescript lsp to `vtsls`.
