### ISSUE TITLE
bug: Neovim not closing with Neotree bind_to_cwd in git repos

### ISSUE THREAD

**Issue by Kayzels** [LazyVim/LazyVim#3382]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0 Release

### Operating system/version

Windows 10 22H2

### Describe the bug

After changing the cwd using Neotree in a git repo, Neovim won't close. It gets stuck.

This only happens after pressing `.` in Neotree to change the directory, with the `bind_to_cwd` enabled, in a folder that is a git repo.

I have this set because I prefer to see the shorter file paths when paths are saved, rather than the long ones relative to the home directory. I understand this is different from the default setting for LazyVim, but it only seems to occur when using LazyVim - using a clean install without LazyVim doesn't lead to this.

### Steps To Reproduce

1. Create a git repo in some folder.
2. Add a file to the git repo.
3. Navigate to the folder using Neotree
4. Press `.` in Neotree for the folder, to set that folder as the cwd
5. Open another file in that directory
6. Try to close Neovim, entering `:qa`

### Expected Behavior

Neovim should close and allow the terminal it's open in to be able to be reused.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  {
    "nvim-neo-tree/neo-tree.nvim",
    opts = {
      filesystem = {
        bind_to_cwd = true, -- Lazy sets it to false by default
      },
    },
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
```

**Comment by folke** [comment]
Can't reproduce with your repro. Make sure all your plugins are up to date and you're using a stable Neovim release, or a recent nightly,

**Comment by dpetka2001** [comment]
Can't reproduce. Screencast following

[Screencast 2024-05-30 19:46:53.webm](https://github.com/LazyVim/LazyVim/assets/12776461/46f39f8e-2bd2-4bb4-ad2a-875d646c0d14)

**Comment by Kayzels** [comment]
Possibly it's caused by Windows? I'm on the latest public release for Neovim, 0.10.0. This used to work until recently, so not sure what could have caused the change.


https://github.com/LazyVim/LazyVim/assets/72696811/50d9ee99-a3b0-4b03-893d-b9404d794980

**Comment by Kayzels** [comment]
Is there any way I can debug this, to figure out what's preventing it from closing?
