### ISSUE TITLE
bug: reading useFlatConfig 

### ISSUE THREAD

**Issue by DrummyFloyd** [LazyVim/LazyVim#3383]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10 (stable)

### Operating system/version

ArchLinux (btw)

### Describe the bug

on tsx file (node version 20.11.1)

   Error  06:21:25 PM notify.error eslint: -32603: Request textDocument/diagnostic failed with message: Cannot read properties of undefined (reading 'useFlatConfig')

### Steps To Reproduce

open tsx file 

### Expected Behavior

no error message

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
    vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
    "folke/tokyonight.nvim",
    "folke/LazyVim",
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    { import = "lazyvim.plugins.extras.lang.tailwind" },
    { import = "lazyvim.plugins.extras.lang.typescript" },
    { import = "lazyvim.plugins.extras.linting.eslint" },
    -- add any other plugins here
}
require("lazy").setup(plugins, {
    root = root .. "/plugins",
})

vim.cmd.colorscheme "tokyonight"
-- add anything else here
```

**Comment by dpetka2001** [comment]
Have you read #2732 and #3129? Seems like some kind of regression with latest version of `eslint`.

**Comment by DrummyFloyd** [comment]
no , did search in discussion tbh , but thank will close the issue tho', if it's related to `eslint` thank you =)

**Comment by Nakahiru** [comment]
Yes, I was looking into it but for the moment, I still don't understand 😬 I'm still investing if there is a workaround or a specific settings 🤷🏻‍♂️

**Comment by mokevnin** [comment]
I think this is the reason https://github.com/neovim/nvim-lspconfig/commit/aa7fe109bde42d8ab1dc9a5cdcdae32c7799c65

Using stable versions `version = "*"` helped me

**Comment by pkropachev** [comment]
@mokevnin, could you please explain details? How have you solved it?

**Comment by mokevnin** [comment]
Yes, uncomment this line https://github.com/LazyVim/starter/blob/main/lua/config/lazy.lua#L28

**Comment by higherorderfunctor** [comment]
Can also just set the offending config to nil.

```lua
return {
  "neovim/nvim-lspconfig",
  opts = {
    servers = {
      eslint = {
        settings = {
          useFlatConfig = true, -- set if using flat config
          experimental = {
            useFlatConfig = nil, -- option not in the latest eslint-lsp
          },
        },
      },
    },
    setup = {
      eslint = function()
        require("lazyvim.util").lsp.on_attach(function(client)
          if client.name == "eslint" then
            client.server_capabilities.documentFormattingProvider = true
          else -- NOTE: disables vtsls for formatting
            -- elseif client.name == "tsserver" then
            client.server_capabilities.documentFormattingProvider = false
          end
        end)
      end,
    },
  },
}
```

**Comment by kesor** [comment]
This was caused by this PR yesterday https://github.com/neovim/nvim-lspconfig/pull/3183

**Comment by damianveltkamp** [comment]
They just reverted the breaking change, just update your nvim-lspconfig and it should be working again: [3184](https://github.com/neovim/nvim-lspconfig/pull/3184)

**Comment by KadaGuetouache** [comment]
> Sure! uncomment this line https://github.com/LazyVim/starter/blob/main/lua/config/lazy.lua#L28

I'm using astronvim where I could this file and change that line?

**Comment by folke** [comment]
@KadaGuetouache just update lspconfig. That change was not needed at all. The option is not even deprecated yet.

**Comment by stephen776** [comment]
I am running into this now. Not having much luck with the above suggestions. What is the current recommended fix? I have some project using flat config and some on the old style.

**Comment by tommitah-heeros** [comment]
Have the issue too with eslint-lsp 4.10.0. Going to try downgrading it though.

**Comment by salvaft** [comment]
The only thing that worked for me was to downgrade `eslint_lsp`

Versions ="*" did not help
