### ISSUE TITLE
bug: Eslint throwing an error after the recent update.

### ISSUE THREAD

**Issue by Redoxahmii** [LazyVim/LazyVim#3384]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10

### Operating system/version

Arch Linux

### Describe the bug

Eslint throws error whenever i open any file and it started recently after i upgraded LazyVim to latest.

`
eslint: -32603: Request textDocument/diagnostic failed with message: Cannot read properties of undefined (reading 'useFlatConfig') 
 ) 
`
This is the error it is throwing.
Maybe it has some issues working with `vtsls` after changing the lsp server from `tsserver` for Typescript extra.
The error could be completely unrelated to this but this is just a guess.
EDIT: This error is being thrown on every change to the file if i do any changes in the buffer it shows this message so it has literally made it impossible to do anything.

![t_2024_05_30_23_16](https://github.com/LazyVim/LazyVim/assets/13983258/19b34907-9867-4c35-9df9-f19ac10eb112)

### Steps To Reproduce

1. Open a file

### Expected Behavior

Should not throw an error.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by pkropachev** [comment]
Duplicate of #3383.

**Comment by Redoxahmii** [comment]
Thank you for the quick response.
Is there any chances of fixes or should i just use `version = "*"` for the time ?

**Comment by dpetka2001** [comment]
@Redoxahmii There's an answer in #3383 and also 2 other linked issues, which dealt with `eslint` regression in the past (which you might also wanna read through). Either way this is not a LazyVim bug.

**Comment by Redoxahmii** [comment]
I have changed the `version = "*"` for the time being. Using this breaks one plugin for me but that is manageable for use right now.
Thank you for the information @dpetka2001.

**Comment by dpetka2001** [comment]
@Redoxahmii You could just do
```lua
return {
  {
    "neovim/nvim-lspconfig",
    version = "*",
    opts = {
      -- rest of your options go here
    },
  },
}
```
This way you just pin `nvim-lspconfig` to the latest stable version without it affecting any of the rest of the plugins.

**Comment by Redoxahmii** [comment]
@dpetka2001 Thank you this resolves the issue.

**Comment by ikotun-dev** [comment]
`eslint: -32603: Request textDocument/diagnostic failed with message: Could not find config file.
`
I'm getting this error and I've tried everything mentioned here. I would appreciate any suggestions on how to fix it.

**Comment by otakutyrant** [comment]
I met this error too and `version = "*"` fixed it. What is this bug? Why does `version = "*"` work?

**Comment by sweetcuptea** [comment]
> `eslint: -32603: Request textDocument/diagnostic failed with message: Could not find config file. ` I'm getting this error and I've tried everything mentioned here. I would appreciate any suggestions on how to fix it.

I had the same issue. Is it fixed?

**Comment by dpetka2001** [comment]
Nothing to fix in Lazyvim because it wasn't a Lazyvim bug. Check the links mentioned here which forward to other related issues.
