### ISSUE TITLE
feature: lazy extra for Laravel blade and php

### ISSUE THREAD

**Issue by muneebusmani** [LazyVim/LazyVim#3386]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

yeah it is , basically i've had a hard time configuring lazyvim for laravel Blade and php files, after doing so many things i could only get to the point to just make php run good , but cant really do any blade in it because it has multiple things going on, someone created a pr some time ago but then that guy deleted the repo so now there's nothing for that present, i have some sort of things setup for laravel projects only upto these things:
Treesitter Highlight for blade (custom parser)
Lsp can recognize the namespaces etc when i call some method or function from those, lsps also do auto imports and give code actions so there is nothing else to do other than fixing blade files i copied someone's setup for laravel so that's why i've got these many things working on , without that there isnt even a ts highlighting for blade files officially, this is my current configuration for laravel:
https://github.com/muneebusmani/nvim

### Describe the solution you'd like

it also has scripting in its directives
it has php code integrated like in angular
it has html and css

### Describe alternatives you've considered

there is no alternative for that i have to stick to vscode whenever i do a laravel project

**Comment by dpetka2001** [comment]
All the Extras are contributions from people who dabble in the specific language domain. If you want an Extra for this, feel free to submit a PR. Otherwise, you'll have to wait and hope for someone else to do it.

**Comment by muneebusmani** [comment]
i have 90% of the stuff an extra would provide but still cant figure out a way to make it blade files work, any ideas?

**Comment by dpetka2001** [comment]
No idea. I have 0 experience with PHP and blade.

**Comment by muneebusmani** [comment]
i just figured out even vscode doesnt have accurate intellisense blade files because there is no official lsp for that, which means that the snippets i am getting in neovim are the same as vscode, i would like to open a pr to the extra for php + laravel because i have 100% of the things an extra would provide

**Comment by ronald2wing** [comment]
Add Pint too

**Comment by muneebusmani** [comment]
> Add Pint too
Bruh adding pint isn't that hard, just copy the php.lua from lazyvim repo and replace phpcsfixer with pint, btw with my experience, I can guarantee you that currently Laravel development isn't that great on neovim, the Laravel team is developing Laravel lsp, currently pint is only a formatter, there is no official linter for Laravel, if they make a linter too, then the Laravel development would be possible in neovim, until then, use phpstorm if you create full stack apps in Laravel, or vscode if you only create backend in laravel

**Comment by ronald2wing** [comment]
> > Add Pint too
> > Bruh adding pint isn't that hard, just copy the php.lua from lazyvim repo and replace phpcsfixer with pint, btw with my experience, I can guarantee you that currently Laravel development isn't that great on neovim, the Laravel team is developing Laravel lsp, currently pint is only a formatter, there is no official linter for Laravel, if they make a linter too, then the Laravel development would be possible in neovim, until then, use phpstorm if you create full stack apps in Laravel, or vscode if you only create backend in laravel

If we are creating a Laravel extra, adding Pint will be necessary. I don't want to corrupt my configs with many Laravel changes. It also needs to add blade-formatter and rustywind to Mason. 
You don't need PHPStorm when adalessa/laravel.nvim already helps a lot with Laravel development. This would be helpful to add in Extra as well.

**Comment by ronald2wing** [comment]
Here is a laravel extra with blade and other Laravel features https://github.com/LazyVim/LazyVim/pull/6830
