### ISSUE TITLE
feature: Standardize all WhichKey shortcut names to have their first character capitalized.

### ISSUE THREAD

**Issue by leisurelicht** [LazyVim/LazyVim#3392]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Currently, the capitalization of WhichKey shortcut names is inconsistent, making them look less visually appealing. 
<img width="586" alt="image" src="https://github.com/LazyVim/LazyVim/assets/8042345/f75caa0c-b8cc-442b-8410-f62e05ab5e23">

### Describe the solution you'd like

It would look better if they were all standardized with the first character capitalized.
Additionally, adding some icons in front of folder name would enhance their visual appeal, like this.
<img width="918" alt="image" src="https://github.com/LazyVim/LazyVim/assets/8042345/92bee0ac-07f1-4b84-9877-6423f58b554c">

### Describe alternatives you've considered

I know I can map it myself. However, I think it would be better if the styles were standardized from the start. This would help somebody avoid a lot of unnecessary configuration.

### Additional context

If you don't mind, I can create a pr to help address this.

**Comment by folke** [comment]
which key groups are lower-case. keymaps are capitalized. It **IS** consistent

**Comment by folke** [comment]
good point! Will change it
