### ISSUE TITLE
bug: bad argument #1 to 'get_line_col' (string expected, got nil)

### ISSUE THREAD

**Issue by francoisrob** [LazyVim/LazyVim#3394]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.11.0-dev-130+gefa45832e

### Operating system/version

Ubuntu 22.04 lts

### Describe the bug

Lazy version: 12.1.0
![image](https://github.com/LazyVim/LazyVim/assets/67432234/1b838fe7-20d9-43ca-8387-416f5172b9f5)
Extremely verbose output in notify of the above. 1 or 2 notifications of the same message at a time
![image](https://github.com/LazyVim/LazyVim/assets/67432234/70e9eea5-5001-475d-b890-173a31393e78)
^output of Notifications

### Steps To Reproduce

1. In a file (ts file in my case), escape from insert to normal mode after making changes floods my screen with these notifs

### Expected Behavior

No big red notifications after file changes

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by francoisrob** [comment]
I've tried replacing typescript-tools with the lazyvim typescript extra but still get the same errors

**Comment by YgorCastor** [comment]
Same issue here, with several file types. 

Neovim 0.10.0

**Comment by folke** [comment]
Please update trouble. should be fixed
