### ISSUE TITLE
bug: `<leader>m` not working with `neo-tree` opened

### ISSUE THREAD

**Issue by konosubakonoakua** [LazyVim/LazyVim#3396]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10

### Operating system/version

ubuntu 22

### Describe the bug

`<leader>m` not working with `neo-tree` opened, open other windows are restored

### Steps To Reproduce

1. open neo-tree
2. open another two win
3. <leader>m at any of the other two win

### Expected Behavior

`<leader>m` should restore `neo-tree` window width too.

**Comment by konosubakonoakua** [comment]
`zen-mode.nvim` works well.

**Comment by dpetka2001** [comment]
This is default Neovim behavior. Open Neotree and press `<C-w>|` to maximize width. Then do `<C-w>=` to equalize the size of the windows. You'll see nothing happens. LazyVim just implements the default Neovim window resize options to make a keymap that toggles window maximize on/off. If default Neovim doesn't support it, neither will LazyVim.
