### ISSUE TITLE
bug: Overriding Copilot-Chat edgy config does not work 

### ISSUE THREAD

**Issue by kevintraver** [LazyVim/LazyVim#3409]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

MacOS 14.4.1

### Describe the bug

Nothing happens when trying to override the edgy settings for CopilotChat.

### Steps To Reproduce

`.config/nvim/lua/plugins/copilot-chat.lua`

```lua
{
  "folke/edgy.nvim",
  optional = true,
  opts = function(_, opts)
    opts.right = opts.right or {}
    table.insert(opts.right, {
      ft = "copilot-chat",
      title = "Copilot Chat",
      size = { width = 0.4 },
    })
  end,
}
```

### Expected Behavior

Custom override settings should take precedent.

**Comment by kevintraver** [comment]
It appears it has to do with the load order in [xtras.lua].(https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/xtras.lua)

It works if `lazyvim.plugins.extras.coding.copilot-chat` loads before `lazyvim.plugins.extras.ui.edgy`

**Comment by folke** [comment]
edgy extra should load first and will be loaded first when you use `:LazyExtras`.
If that;s not how you do it, then you need to make sure you do the imports properly.

To override it in your own config, you need to alter the list, not add a new entry since and entry for copilot chat already exists.

**Comment by folke** [comment]
Next time, please use discussions for user questions

**Comment by kevintraver** [comment]
Ok, thanks for the explnation!
