### ISSUE TITLE
feature: lazydocker

### ISSUE THREAD

**Issue by DKulan** [LazyVim/LazyVim#3417]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

I love that lazygit is included but would also like to see lazydocker as well which was made by the same developer:
https://github.com/jesseduffield/lazydocker

### Describe the solution you'd like

lazydocker as an option in the lazyextras.

### Describe alternatives you've considered

Installing and managing the plugin myself.

**Comment by dpetka2001** [comment]
`lazydocker` doesn't exist as a tool in Mason to install. Just like `lazygit` the user would have to install the plugin himself. LazyVim doesn't install `lazygit`, it just makes a keymap for if `lazygit` is found in the user's system. So, just install `lazydocker` in your OS and then just do a mapping like 
```lua
if vim.fn.executable("lazydocker") == 1 then
  vim.keymap.set("n", "<leader>gd", function()
    LazyVim.terminal("lazydocker", { esc_esc = false, ctrl_hjkl = false })
  end,
    {desc = "Lazydocker"})
end
```
and I believe it should work.
