### ISSUE TITLE
feature: Have option to add keymap prefixes in which-key opts

### ISSUE THREAD

**Issue by UtkarshVerma** [LazyVim/LazyVim#342]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Currently, `which-key` keymaps are hardcoded in the `config` function and if a user wants to add a new keymap prefix, e.g. `<leader>d` for `+debug`, they have to redefine the entire config function.

### Describe the solution you'd like

The keymaps variable inside `config` function could be moved to opts, allowing users to add stuff to it.

### Describe alternatives you've considered

Alternatively, users can override the entire `config` function.

Here is the current implementation:
```lua
    config = function(_, opts)
      local wk = require("which-key")
      wk.setup(opts)
      local keymaps = {
        mode = { "n", "v" },
        ["g"] = { name = "+goto" },
        ["gz"] = { name = "+surround" },
        ["]"] = { name = "+next" },
        ["["] = { name = "+prev" },
        ["<leader><tab>"] = { name = "+tabs" },
        ["<leader>b"] = { name = "+buffer" },
        ["<leader>c"] = { name = "+code" },
        ["<leader>d"] = { name = "+debug" },
        ["<leader>f"] = { name = "+file/find" },
        ["<leader>g"] = { name = "+git" },
        ["<leader>gh"] = { name = "+hunks" },
        ["<leader>q"] = { name = "+quit/session" },
        ["<leader>s"] = { name = "+search" },
        ["<leader>u"] = { name = "+ui" },
        ["<leader>w"] = { name = "+windows" },
        ["<leader>x"] = { name = "+diagnostics/quickfix" },
      }
      -- if Util.has("noice.nvim") then
      --   keymaps["<leader>sn"] = { name = "+noice" }
      -- end
      wk.register(keymaps)
    end,
```

**Comment by dpetka2001** [comment]
```lua
return {
  -- Modify which-key keys
  {
    "folke/which-key.nvim",
    opts = function()
      require("which-key").register({
        ["<leader>xl"] = {
          name = "+LSP (Telescope)",
        },
        ["<leader>un"] = {
          name = "+Notifications",
        },
        ["<leader>ut"] = {
          name = "+Treesitter",
        },
        ["zd"] = { "Delete fold under cursor" },
        ["zD"] = { "Delete folds recursively under cursor" },
        ["zE"] = { "Eliminate all folds in window" },
        ["<leader>cw"] = {
          name = "+LSP Workspace",
        },
        ["<leader>t"] = {
          name = "+Terminal",
        },
      })
    end,
  },
}
```
I did it as shown and didn't have to recreate the whole config. Just add what you want and it will be merged with default `which-key` mappings.

**Comment by folke** [comment]
As @dpetka2001 mentions, you can add this in opts, or just call which-key register anywhere else in your config with additional stuff.

**Comment by dpetka2001** [comment]
When you return a function in `config` i think it overrides the default values completely and returns new values. Your way is like setting up the plugin from scratch. You should prefer `opts` if you care about merging your changes with the default values of a plugin (I think).

**Comment by UtkarshVerma** [comment]
Thanks, that is a good solution to the problem I faced.
