### ISSUE TITLE
bug: `recommended` not working after removing specs for some plugins

### ISSUE THREAD

**Issue by madjxatw** [LazyVim/LazyVim#3420]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0

### Operating system/version

Fedora 38

### Describe the bug

After removing specs for some plugins in a lua module that returns a table containing `recommended` keyword,  during the startup of Neovim, an error is reported as:

>...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/plugin.lua:67: attempt to call method 'find' (a nil value)

### Steps To Reproduce

1. Enable `dot`
2. Edit `plugins/extras/util/dot.lua`, comment out the specs for `nvim-lspconfig` and `mason.nvim` (Check the **Repro** section to see my `dot.lua`)
3. Restart Neovim.

### Expected Behavior

It should work without error raised, but only losing some features. In my case, I only need treesitter highlighting but not all lsp features.

### Repro

```Lua
My `plugins/extras/util/dot.lua` (This is the only file modified, and everything worked well before the modification):


---@type string
local xdg_config = vim.env.XDG_CONFIG_HOME or vim.env.HOME .. "/.config"

---@param path string
local function have(path)
  return vim.uv.fs_stat(xdg_config .. "/" .. path) ~= nil
end

return {
  recommended = true,
  desc = "Language support for dotfiles",

  -- add some stuff to treesitter
  {
    "nvim-treesitter/nvim-treesitter",
    opts = function(_, opts)
      local function add(lang)
        if type(opts.ensure_installed) == "table" then
          table.insert(opts.ensure_installed, lang)
        end
      end

      vim.filetype.add({
        extension = { rasi = "rasi", rofi = "rasi", wofi = "rasi" },
        filename = {
          ["vifmrc"] = "vim",
        },
        pattern = {
          [".*/waybar/config"] = "jsonc",
          [".*/mako/config"] = "dosini",
          [".*/kitty/.+%.conf"] = "bash",
          [".*/hypr/.+%.conf"] = "hyprlang",
          ["%.env%.[%w_.-]+"] = "sh",
        },
      })

      add("git_config")

      if have("hypr") then
        add("hyprlang")
      end

      if have("fish") then
        add("fish")
      end

      if have("rofi") or have("wofi") then
        add("rasi")
      end
    end,
  },
  --[==[
  {
    "neovim/nvim-lspconfig",
    opts = {
      servers = {
        bashls = {},
      },
    },
  },
  {
    "williamboman/mason.nvim",
    opts = function(_, opts)
      opts.ensure_installed = opts.ensure_installed or {}
      vim.list_extend(opts.ensure_installed, { "shellcheck" })
    end,
  },
  --]==]
}
```

**Comment by dpetka2001** [comment]
You shouldn't customize the source paths of the plugins you want. Just put your customizations in `/lua/plugins/` directory.

**Comment by folke** [comment]
That error can only happen if you just keep the treesitter spec in there.
Either way, recommended and desc are not support by lazy.nvim. That's a LazyVim thing. You shouldn't use that in your own specs.
