### ISSUE TITLE
bug: Failed to run config for nvim-snippets

### ISSUE THREAD

**Issue by rogeriofrsouza** [LazyVim/LazyVim#3426]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.5

### Operating system/version

Linux Mint 21.3 x86_64

### Describe the bug

Today after updating LazyVim and all my plugins, I noticed this new error.
It occurs when I open Telescope Find Files.

![Screenshot from 2024-06-02 11-51-22](https://github.com/LazyVim/LazyVim/assets/77423511/633a29ac-a8d4-447a-9027-b3c7b6b3ac79)

As I'm using Neovim 0.9.5, I included the LuaSnip Extra but it's still throwing the error 😞 

It's specified in [nvim-snippets Requirements section](https://github.com/garymjr/nvim-snippets?tab=readme-ov-file#requirements) that a neovim >= 0.10 is needed. Thus, a version check should be added in LazyVim before running this plugin?

I couldn't reproduce the error with the Repro provided below. I made a fresh LazyVim installation following the [Installation section](https://www.lazyvim.org/installation) on the website.

### Steps To Reproduce

1. Install LazyVim
2. Run nvim command
3. On dashboard press f (Find File)

### Expected Behavior

Don't show this error.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
  "nvim-telescope/telescope.nvim",
  "nvim-lua/plenary.nvim",
  "garymjr/nvim-snippets",
  "L3MON4D3/LuaSnip",
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
  spec = {
    { import = "lazyvim.plugins.extras.lang.luasnip" },
  },
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Oversight. Fixed!
