### ISSUE TITLE
bug: cmp menu doesn't appear when typing punctuation characetrs

### ISSUE THREAD

**Issue by REmerald** [LazyVim/LazyVim#3438]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.11.0-dev-158+g05435a915

### Operating system/version

Arch Linux (Garuda Linux)

### Describe the bug

When typing special characters such as `#`, `/` or `@`, the nvim-cmp menu doesn't appear unless I type an alphabetical character afterwards.
This is problematic because I can't insert snippets with prefixes consisting entirely of these characters, e.g. `#`, `##`, `/`, `//`, `/**` in `friendly-snippets` `python.json`, `c.json` and `cdoc.json` respectively.
The bug was discovered in https://github.com/rafamadriz/friendly-snippets/pull/454#issuecomment-2140739466.

### Steps To Reproduce

1. Type `#`.
2. No menu.
3. Type `e`.
4. Menu appears.
5. Backspace `e`.
6. Menu disappears.

### Expected Behavior

Menu should always appear if punctuational character (i.e. ASCII printable character which is not a space or alphanumeric) is typed.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
  "hrsh7th/nvim-cmp",
  {
    "garymjr/nvim-snippets",
    opts = { friendly_snippets = true, },
  },
  "rafamadriz/friendly-snippets",
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
require("cmp").setup({
  sources = {
    { name = "snippets" },
    { name = "nvim_lsp" },
    { name = "path" },
    { name = "buffer" },
  },
})
```

**Comment by dpetka2001** [comment]
This is either a problem with `nvim-cmp` or native `vim.snippet` engine which doesn't support all kind of snippets except what the LSP specification defines. I don't think this is LazyVim related. Try changing to Luasnip and see if the Luasnip cmp source and snippet engine can handle this.
