### ISSUE TITLE
feature: Ask for users permission before removing or adding new plugins over lazyvim update

### ISSUE THREAD

**Issue by beastr45** [LazyVim/LazyVim#3442]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

In new versions of lazyvim often there are many breaking changes that impact heavily on the users workflow or cause breakage with custom plugin configurations. 

### Describe the solution you'd like

The user should be prompted to decide on the plugins they want to keep avoiding breakage in workflow. The user should be able to easily roll back automatic updates to lazyvim. 

### Describe alternatives you've considered

Im shure there is a way to specify version to lock lazyvim into a usable state I will revise documentation and do this.

**Comment by folke** [comment]
What about users reading the actual changelog they see in lazy before updating??

No, I'm not going to do the effort to maintain different versions.

If there's a breaking change, then I typically mention that in the news file, which you see when you start LAzyVim.
It also contains the necessary steps to install/revert to a situation that was close to before the change.

LazyVim is an opensource project, not a company.

And you can indeed use Lazy's lockfile to restore if you don't like changes.
