### ISSUE TITLE
bug: default indent adds wrong indentline in nested functions

### ISSUE THREAD

**Issue by MystikReasons** [LazyVim/LazyVim#3447]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Windows 10

### Describe the bug

The bug shows itself in functions that are relatively big (more than 100 lines) and if it has many nestings.
In the middle of scrolling it adds a new indentline which absolutely does not make sense.
I've tested the same file in VSCode and there it is working as expected.

This is how it should look:
![grafik](https://github.com/LazyVim/LazyVim/assets/18333048/4fbd8dd8-4148-4c6b-b918-27cc6feb6972)

After scrolling past line 88 this happens:
![grafik](https://github.com/LazyVim/LazyVim/assets/18333048/2f7d1d26-bd1d-4c02-bfe9-7971b196693c)

Please find attached my test file (I needed to zip it since I can't upload .php files).
[test.zip](https://github.com/user-attachments/files/15550738/test.zip)

### Steps To Reproduce

1. Load latest vanilla version of Lazyvim
2. Load my test.php file (just some garbage but a long function, 120 lines of code with many nestings).
3. Scroll down
4. If you scroll past line 88, a new indentline should appear and if you scroll up again, it disappears

### Expected Behavior

The additional indent line should not show up at all.

**Comment by folke** [comment]
Why is this a LazyVim bug?

**Comment by MystikReasons** [comment]
You are correct, it also happens with vanilla Neovim and only indent-blankline. I will post my bug report there

**Comment by folke** [comment]
There's nothing I can do about that.

**Comment by dpetka2001** [comment]
Why don't you use a `vim.opt_local.shiftwidth = whatever_value_you_want` in `~/.config/nvim/after/ftplugin/php.lua`? Maybe that will help?
