### ISSUE TITLE
bug: `gitsigns.nvim` makes Neovim randomly freeze when scrolling/switching buffers

### ISSUE THREAD

**Issue by pidgeon777** [LazyVim/LazyVim#3448]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0

### Operating system/version

Windows 11 Version 23H2

### Describe the bug

Occasionally, while scrolling or switching between buffers, Neovim unexpectedly becomes unresponsive. When this happens, I am forced to manually terminate the `nvim.exe` process.

This behavior started manifesting approximately two weeks ago.

### Steps To Reproduce

1. Open several tabs.
2. Rapidly alternate between them in no particular order.
3. Swiftly scroll through the open buffers.

At a certain point, Neovim will become unresponsive, freezing itself.

On some occasions, Neovim might freeze immediately upon restoring a session, seemingly at random.

### Expected Behavior

No freezes should occur.

### Repro

I can't reproduce it with the basic `repro` config:

```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

Instead, I'm able to reproduce it using `LazyVim`.

But, if I disable `gitsigns.nvim` in `LazyVim` using this plugin spec:

```lua
return {
  {
    "lewis6991/gitsigns.nvim",
    enabled = false,
  },
}
```

then everything works fine, with no freezes.

**Comment by pidgeon777** [comment]
Maybe it could be related to this?:

https://github.com/LazyVim/LazyVim/discussions/3407

https://github.com/lewis6991/gitsigns.nvim/issues/1027

**Comment by folke** [comment]
Why do you post this here??
