### ISSUE TITLE
bug: Not managed by LazyExtras

### ISSUE THREAD

**Issue by alivault** [LazyVim/LazyVim#3450]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

MacOS 14.4.1 

### Describe the bug

I am getting these message about Luasnip and mini-comment not being managed by LazyExtras:
<img width="868" alt="image" src="https://github.com/LazyVim/LazyVim/assets/48610822/6b0d4980-dfa7-4cbb-90fd-bc464cb545c7">
Yet my config has no mention of luasnip or mini-comment:
<img width="1025" alt="image" src="https://github.com/LazyVim/LazyVim/assets/48610822/961c80f0-44d6-4dd0-8180-278249a1531f">
I also tried removing everything in my plugins folder to see if that fixed the message, but I still get the "not managed by LazyExtras" message.

### Steps To Reproduce

1. Open LazyExtras
2. Observe the "not managed by LazyExtras" message next to Luasnip and mini-comment

### Expected Behavior

Need to manage Luasnip and mini-comment in LazyExtras

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
You probably `import` those Extras in your `/lua/config/lazy.lua` file. Remove those imports from that file and then enable them via the `LazyExtras` UI.

**Comment by dpetka2001** [comment]
Ohh. It's because of your Neovim version. You're on 0.9.5 and that's why those are enabled by default.

**Comment by alivault** [comment]
That was it! Updgrading nvim to the latest version solved it. Thanks

**Comment by wcheek** [comment]
I'm seeing this issue as well, but I'm running `v0.10.0`.
![image](https://github.com/LazyVim/LazyVim/assets/66931618/a4d84d32-9b19-4504-9ed5-d4933cc60de1)
Yet no mention of `telescope` in my config.

**Comment by dpetka2001** [comment]
That's normal. Telescope was moved to Extras recently and is being imported during the parsing phase. That's why you see this.
