### ISSUE TITLE
bug: python semshi autocommand error when semshi plugin is not installed

### ISSUE THREAD

**Issue by kimusan** [LazyVim/LazyVim#3456]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.11 dev

### Operating system/version

Ubuntu 24.04

### Describe the bug

With latest update of Lazy vim I suddenly start seeing this error when exiting (even without opening any file):

```
Error detected while processing VimLeave Autocommands for "*"..function remote#define#AutocmdBootstrap[7]..VimLeave Autocommands for "*"..function remote#define#request:
line    2:
Error invoking '/home/kschulz/.local/share/nvim/lazy/semshi/rplugin/python3/semshi:autocmd:VimLeave:*' on channel 19 (python3-rplugin-host):
no request handler registered for "/home/kschulz/.local/share/nvim/lazy/semshi/rplugin/python3/semshi:autocmd:VimLeave:*"⏎

```

I do not have the Semshi "extra" enabled 

### Steps To Reproduce

Open lazyVim, Close Lazyvim

### Expected Behavior

No error on exit

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
You probably enabled it at some point, or not. 
Either way you do have the semshi remote plugin. Just delete it

**Comment by kimusan** [comment]
How can that happen? I have never used it or done anything to install it.

**Comment by folke** [comment]
I have no idea.

I did make a change in noice recently to make sure you can actually see errors triggered during vim exit. Previously you wouldn't see the error and neovim might have just seem to hang, waiting for input

**Comment by kimusan** [comment]
The plugin is not listed in the LazyVim plugin list and not enabled in extras. I ended up enabling it in extras restarting nvim and then disable it again. That seemed to fix the problem. However, when I actually cleaned it via LazyVim, the error returned. 

I am not sure what I am supposed to remove in order to "delete" it, as it is not getting in via my own configurations:
![image](https://github.com/LazyVim/LazyVim/assets/1150049/b5999cd2-00f6-487a-bf00-d4deff0b56b7)
and the files in ~/.local/share/nvim/ that contains "semshi" are all handled by lazyvim git repo .... except for rplugin.vim (It is auto generated by neovim as far as I can tell). 
I ended up removing the lines related to semshi from rplugin.vim and that seem to finally have removed the problem. I have absolutely no idea as to why this file contains info about semshi and when to got added.

**Comment by folke** [comment]
You probably enabled it at some point.
I think I'll just remove that extra alltogether. Not at all that useful and rplugin is not that great either

**Comment by rabbit19981023** [comment]
I'm facing same problem after latest lazyvim updated. (I have enabled semshi before)

I finally got it solved by running `:UpdateRemotePlugins`.

**Comment by franklinjpt** [comment]
I have the same error, I uninstalled from everywhere but I got the same error and semshi is no more in extras
![image](https://github.com/LazyVim/LazyVim/assets/61480925/429f0632-096f-45af-8714-e7a71acce597)

**Comment by rabbit19981023** [comment]
> I have the same error, I uninstalled from everywhere but I got the same error and semshi is no more in extras ![image](https://private-user-images.githubusercontent.com/61480925/340428153-429f0632-096f-45af-8714-e7a71acce597.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2NzUyMjcsIm5iZiI6MTcxODY3NDkyNywicGF0aCI6Ii82MTQ4MDkyNS8zNDA0MjgxNTMtNDI5ZjA2MzItMDk2Zi00NWFmLTg3MTQtZTdhNzFhY2NlNTk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDAxNDIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3M2I1OTM5ZDk0MzIxZGIyNzkwNDZmZGU3ODhjMjA2MDA4Y2JiYmRkOWQzMDk4ZWIwZmZlMDhhNWIzNmM4ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xOeOQxXzU-6_IBUzQccKSCR0ukDSu6HXmij8yid_laQ)

@franklinjpt I faced same problem, after running `:UpdateRemotePlugins` command, the bug was fixed.

**Comment by franklinjpt** [comment]
> > I have the same error, I uninstalled from everywhere but I got the same error and semshi is no more in extras ![image](https://private-user-images.githubusercontent.com/61480925/340428153-429f0632-096f-45af-8714-e7a71acce597.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2NzUyMjcsIm5iZiI6MTcxODY3NDkyNywicGF0aCI6Ii82MTQ4MDkyNS8zNDA0MjgxNTMtNDI5ZjA2MzItMDk2Zi00NWFmLTg3MTQtZTdhNzFhY2NlNTk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDAxNDIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3M2I1OTM5ZDk0MzIxZGIyNzkwNDZmZGU3ODhjMjA2MDA4Y2JiYmRkOWQzMDk4ZWIwZmZlMDhhNWIzNmM4ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xOeOQxXzU-6_IBUzQccKSCR0ukDSu6HXmij8yid_laQ)
> 
> 
> 
> @franklinjpt I faced same problem, after running `:UpdateRemotePlugins` command, the bug was fixed.

Thank you so much, it works
