### ISSUE TITLE
Autocompletion Icons

### ISSUE THREAD

**Issue by skinner12** [LazyVim/LazyVim#346]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.3

### Operating system/version

Arch

### Describe the bug

Hello,
I've installed fresh version on LazyVim but I can't see icons when auto completion's windows is open.

I notice that the video linked in README has the same problem: [check here](https://www.youtube.com/watch?v=N93cTbtLCIM&t=416s) 

### Steps To Reproduce

Clone repo and run nvim

### Expected Behavior

When open window for auto completion we have to see icons for function, snippets etc...

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
You need a proper Nerd Font installed to see the icons.

Funily enough, @elijahmanor is actually working on a new video to address this problem :)

**Comment by skinner12** [comment]
Hi @elijahmanor, 
The problem was from my side as wrote you and @folke. I'm using Arch/Alacritty with an old huge nerd font's package that was moved from AUR  into smaller ones community packages. For some reason I have to install new packages and replace old one. Now all works as should. 

My next step is to override icons with lspkind as in my previous config, but here is not the right place where talk about it. 

Regards

**Comment by elijahmanor** [comment]
Ah yes, probably what you were encountering was just an older nerd font that didn't support all of the icons/symbols that you wanted/needed. Another approach is to not use a patched font with nerd symbols, but use a normal font with a symbol font fallback to fill in the gaps. 

Alacritty doesn't have the feature built-in, but iTerm, Kitty, and WezTerm do. 

However, as a workaround, you could update your `fonts.conf` and provide the fallback there. 

Here is an example https://github.com/polyzen/dotfiles/blob/156d4d0f2e96156fff4ed15bb74a942459bc1f89/workstation/.config/fontconfig/fonts.conf 

On Arch you can download the [ttf-nerd-fonts-symbols package](https://archlinux.org/packages/community/any/ttf-nerd-fonts-symbols/).

**Comment by skinner12** [comment]
My solution is the latter one you wrote: I downloaded new packages and, magically, I saw icons.

Thanks for explaining well.

Regards
Il 28 feb 2023, 21:07 +0100, Elijah Manor ***@***.***>, ha scritto:
