### ISSUE TITLE
After updating LazyVim I now get an error after saving a file

### ISSUE THREAD

**Issue by juridiener** [LazyVim/LazyVim#3489]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2982+gea1c9f60e

### Operating system/version

MacOS

### Describe the bug

After saving a file i get this error: Error detected while processing BufWritePre Autocommands for "*":

### Steps To Reproduce

Update LazyVim
Open file
Save file

### Expected Behavior

No errors after saving file

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end


-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
All works correctly with a default LAzyVim installation. And also with my personal install.

**Comment by juridiener** [comment]
Ok. It worked before too. Only now after i did the Update of the plugins and LazyVim i get this error. How can I find out what is causing this issue?

**Comment by juridiener** [comment]
So it's only happening in js files in php for example it works

**Comment by folke** [comment]
What is the exact error you get?

**Comment by juridiener** [comment]
Error detected while processing BufWritePre Autocommands for "*"
After I save the file.

**Comment by folke** [comment]
And `:ConformInfo`?

**Comment by juridiener** [comment]
Error executing Lua callback: ...cal/share/LazyVim/lazy/conform.nvim/lua/conform/util.lua:53: attempt to call field 'root' (a nil value)
stack traceback:
	...cal/share/LazyVim/lazy/conform.nvim/lua/conform/util.lua:53: in function 'cwd'
	...cal/share/LazyVim/lazy/conform.nvim/lua/conform/init.lua:633: in function 'get_formatter_info'
	...l/share/LazyVim/lazy/conform.nvim/lua/conform/health.lua:144: in function 'append_formatters'
	...l/share/LazyVim/lazy/conform.nvim/lua/conform/health.lua:163: in function 'show_window'
	...cal/share/LazyVim/lazy/conform.nvim/lua/conform/init.lua:165: in function <...cal/share/LazyVim/lazy/conform.nvim/lua/conform/init.lua:164>

**Comment by folke** [comment]
Did you change conform settings?

**Comment by juridiener** [comment]
Not unaware. I just did an update with leader l and then U

**Comment by juridiener** [comment]
I can show you my repo if it helps you

**Comment by juridiener** [comment]
{
  format = {
    async = false,
    lsp_fallback = true,
    quiet = false,
    timeout_ms = 3000
  },
  formatters = {
    injected = {
      options = {
        ignore_errors = true
      }
    },
    prettier = {
      condition = <function 1>
    }
  },
  formatters_by_ft = {
    css = { "prettier" },
    fish = { "fish_indent" },
    graphql = { "prettier" },
    handlebars = { "prettier" },
    html = { "prettier" },
    javascript = { "prettier" },
    javascriptreact = { "prettier" },
    json = { "prettier" },
    jsonc = { "prettier" },
    less = { "prettier" },
    lua = { "stylua" },
    markdown = { "prettier" },
    ["markdown.mdx"] = { "prettier" },
    scss = { "prettier" },
    sh = { "shfmt" },
    svelte = { "prettier" },
    typescript = { "prettier" },
    typescriptreact = { "prettier" },
    vue = { "prettier" },
    yaml = { "prettier" }
  }
}

**Comment by folke** [comment]
https://github.com/stevearc/conform.nvim/blob/069e971295a34a810484b7b2ef54b3c735214181/lua/conform/util.lua#L52

You're using an outdated nightly.

Either upgrade to NEovim stable, or use a recent Nightly

**Comment by juridiener** [comment]
Ok i will try this. thanks folke for your time and help.

**Comment by joshuawootonn** [comment]
I am seeing a similar error @juridiener. I am not sure it happened right when I updated though. 

This seems to be related: https://github.com/neovim/neovim/issues/26520
