### ISSUE TITLE
bug: Starter wont close immediately on pressing q

### ISSUE THREAD

**Issue by jpx40** [LazyVim/LazyVim#3492]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

immediately

### Operating system/version

Linux arch 6.9.3-arch1-1  x86_64 GNU/Linux

### Describe the bug

Hey, the nvim Starter won't close immediately when i press q only when i press another button after it, it shows a blank screen, shift + q (Q) on the other hand works.

### Steps To Reproduce

1. open nvim with out file so starter opens
2. pressing q (small q)  (shift + q works)

### Expected Behavior

nvim closes immediately on pressing q in starter

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Please update noice, and restart. You will probably see an error message.
Or before quitting, do `:Noice disable` and then quit.

You'll likelysee an error about shada corruption. Nothing I can do about that. 
It's a recent thing in NEovim

**Comment by folke** [comment]
`:h shada`
