### ISSUE TITLE
feature: add folke/zen-mode to extras

### ISSUE THREAD

**Issue by idelice** [LazyVim/LazyVim#3500]
### Did you check the docs?

- [X] I have read all the LazyVim docs
- [X] This is not a request for a new or existing extra (see above)

### Is your feature request related to a problem? Please describe.

No problem - just a nice-to-have feature.

### Describe the solution you'd like

folke/zen-mode

### Describe alternatives you've considered

n/a

**Comment by dpetka2001** [comment]
>  IMPORTANT: ideas or requests related to extras, should go in the [Extra Requests](https://github.com/LazyVim/LazyVim/discussions/categories/extra-requests) discussion forum.
This is not a request for a new or existing extra (see above)

**Comment by folke** [comment]
you can just add that to your own config. not worth to add as an extra

```lua
  {
    "folke/zen-mode.nvim",
    cmd = "ZenMode",
    opts = {},
    keys = { { "<leader>z", "<cmd>ZenMode<cr>", desc = "Zen Mode" } },
  }
```
