### ISSUE TITLE
bug: black block in lualine

### ISSUE THREAD

**Issue by panboo-leo** [LazyVim/LazyVim#3502]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0 Build type: Release LuaJIT 2.1.1716656478

### Operating system/version

MacOS 14.4

### Describe the bug
use neotree

![image](https://github.com/LazyVim/LazyVim/assets/57588266/07d15001-61e0-4b52-b72f-104f51abb3dd)

no neotree
![image](https://github.com/LazyVim/LazyVim/assets/57588266/846be7d5-f51f-4f5c-8ee5-c78c515246de)

### Steps To Reproduce

when using neotree 

### Expected Behavior

black block 

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
That screenshot is not tokyonight. It works find with TN, so either your colorscheme should be fixed, or your terminal is doing weird things
