### ISSUE TITLE
bug: keymap sequence issue

### ISSUE THREAD

**Issue by kapral18** [LazyVim/LazyVim#3508]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0 Build type: Release LuaJIT 2.1.1716656478 Run "nvim -V1 -v" for more info

### Operating system/version

MacOS 14.5

### Describe the bug

After recent updates something happened to sequences of keymaps. Like if I hit `<leader>t` fast nothing shows up anymore, while previously I would see the which-key popup. Only if I hit `<leader>` and wait then it shows up. Also I noticed that sometimes the second sequence gets lost, like `<leader>db` and then rightaway `<leader>td` leads to no debugger spawning.

### Steps To Reproduce

1. `<leader>db`
2. `<leader>td`

### Expected Behavior

Should start debugging

**Comment by kapral18** [comment]
also `<leader>tt` is not happening if I type it too fast sometimes

**Comment by dpetka2001** [comment]
Just reduce the value of `vim.opt.timeoutlen` to whatever you prefer.

**Comment by folke** [comment]
Just fixed this in which-key: https://github.com/folke/which-key.nvim/commit/ccf027625df6c4e22febfdd786c5e1f7521c2ccb

In case you don't know yet, you can now specify which-key groups with `<nop>` or empty mappings.

```lua
vim.keymap.set("n", "<leader>d", "", {desc = "+debug"})
```

Can also be used to set buffer-local which-key groups.

**Comment by dpetka2001** [comment]
@folke does this also work for group names that are empty because the keymaps are not created yet, like what happens with gitsigns hunks? So, in which-key I'd usually do `["<leader>gh"] = { name = "+hunks", ["🚫"] = "which_key_ignore" },`. Can I do the same in `vim.keymap.set`?

**Comment by folke** [comment]
yep, ideed. You can use vim.keymap.set, or lazy's keys with an empty rhs ""

**Comment by dpetka2001** [comment]
@folke One minor discrepancy I noticed with the new approach is the following.

When you use `vim.keymap.set`, then `which-key` correctly shows the group name grouped with the rest of the group names. 
![2024-06-07_01-18](https://github.com/LazyVim/LazyVim/assets/12776461/acb7a6a7-7e9e-46d4-ac13-4493ff4110e6)

But when you use the Lazy keys, the group name is shown grouped with the commands and with different highlight
![2024-06-07_01-25](https://github.com/LazyVim/LazyVim/assets/12776461/5e4cf792-31bf-4f72-b783-ff437318a8f5)

**Comment by folke** [comment]
Are you sure you're using the latest lazy.nvim? I had to fix something there to make this work properly

**Comment by dpetka2001** [comment]
Just updated. Can confirm this doesn't happen any more. Had updated yesterday morning, but not again throughout the day. Just LazyVim throughout the day. Sorry about that and thank you for pointing me to the right direction.
