### ISSUE TITLE
feature: Format eslint ?

### ISSUE THREAD

**Issue by naknode** [LazyVim/LazyVim#351]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

In my `autocmds.lua`, I have:

```lua
-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here

vim.cmd[[colorscheme nord]]

vim.api.nvim_create_autocmd("BufWritePost", {
  callback = function()
      vim.lsp.buf.format() 
  end
})
```

And when I go where my project that needs linting -- it does not format. In VS Code, it does, so I know it works. What am I doing wrong?

Or rather, do I need to be using `nvm-lsp` instead of a vim command?

### Describe the solution you'd like

Use either Neovim LSP or the vim api to format the code via eslint standards

### Describe alternatives you've considered

Used vim api

### Additional context

Neovim 0.8.2 on a MacBook Pro 2021 M1

**Comment by dpetka2001** [comment]
Is the lsp-server you use attached to your buffer? What does `LspInfo` show?

**Comment by folke** [comment]
LazyVim already provides auto-formatting, so there's not need for that autocmd. It will even cause issues.

To get eslint formatting, you can either enable the eslint lsp, or use eslint, eslint_d with null-ls
