### ISSUE TITLE
bug: duplicate lsp symbol navigation for lualine

### ISSUE THREAD

**Issue by leisurelicht** [LazyVim/LazyVim#3511]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0

### Operating system/version

Apple M1 Pro 14.5 (23F79)

### Describe the bug

It seems that the core plugin `trouble` will add LSP symbol navigation by default, and if you add another extra navigation plugin like `navic`, there will be duplicate LSP symbol navigation in lualine.

<img width="1027" alt="image" src="https://github.com/LazyVim/LazyVim/assets/8042345/24eeea33-902b-4958-8212-ef6057ba6dd6">

### Steps To Reproduce

1. import `LazyVim` and  ` lazyvim.plugins.extras.editor.navic ` and install.
2. install lsp server
3. start neovim

### Expected Behavior

I think we should disable the default symbol navigation in extra symbol navigation plugins like navic or aerial.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  { import = "lazyvim.plugins.extras.editor.navic" },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
Yes, and that's not a bug. You should learn some Lua to customize your configuration to your needs. You need to remove the corresponding Lua component that you don't want. Both of the plugins `trouble` and `navic` provide their own Lualine component.

**Comment by leisurelicht** [comment]
> Yes, and that's not a bug. You should learn some Lua to customize your configuration to your needs. You need to remove the corresponding Lualine component that you don't want. Both of the plugins `trouble` and `navic` provide their own Lualine component.
> 
> PS: Just remembered that there's an option that you can set in your `/lua/config/options.lua` to disable trouble Lualine component as you can see [here](https://github.com/LazyVim/LazyVim/blob/e1c54ac638bf63b12586926c5b3a550a29a71d94/lua/lazyvim/config/options.lua#L38) when you have other Extras with similar functionality enabled.

OK，at first, I really didn't notice that there has an `trouble` option, that's my fault.

But did you really think this should require manual settings by the user? not automatically?

When I enable `navic` by `lazy Extras`，that means I want to use it，right? And  `Lazy Extras` was created for let user can quickly enable/disable a new extra without modifying the configuration file, right?

So If I have to modify the configuration file anyway, then why do I still need to use `Lazy Extras` to manage the extra plugin? why don't I just import `navic` directly in the configuration file?

**Comment by dpetka2001** [comment]
@leisurelicht I sincerely apologize because I jumped the gun. I regret what I said and that's why I submitted the PR to take into consideration what you suggested, that the user shouldn't be seeing 2 Lualine components for symbols.

**Comment by leisurelicht** [comment]
@dpetka2001 OK, maybe I also got a bit worked up.

I have seen your pr。 No offense intended。I don't think it's a best solution.  Just like I said above, when user enable `navic` or `aerial` by `Lazy extras`, they still need to modify configuration file and set `vim.g.trouble_lualine`. If user forget to set `vim.g.trouble_lualine = false` after enable `navic` or `aerial` by `Lazy Extras`. they will never show。Users might not even realize that the current content displayed in `lualine` does not come from the extra plugins they added。This may go against the original intention of `LazyExtra`. 

So I thought the best way is if user enable `navic` or `aerial`,  disable the `trouble` `lualine` component. Not first check the`troubel_lualine`, if it's true, then doesn't load extra `lualine` component. 

Since I still use configuration file to manage extra except language plugins. `trouble_lualine` has been enough to solve my problem. So it just a suggestion. 

Finally, thank you for the effort you've made to this project.

**Comment by folke** [comment]
The way it works right now is how it should work. Enabling outline or aerial should **NOT** replace the default symbols in lualine. Only if the user disables the trouble lualine it should do that.

> PS. I know how to write configurations in Lua, so I suggest you mind your own business and try to learn how to accept different opinions.

And I really won't allow this type of language in the LazyVim community. You have been warned.

**Comment by dpetka2001** [comment]
@folke It was my fault to begin with. I wasn't in the right frame of mind when I first replied to OP (it had nothing to do with the OP, it was just personal factors). I should have waited and given a proper response at a later time. 

@leisurelicht is not at fault here. He just responded based on my wrong behavior of my first reply. If you want to give someone a warning please give it to me. I will gladly accept it and strive to do better in the future. I'm really sorry you have to deal with such situations when you give your best effort to keep so many users happy with all of your work. Again, I apologize both to you and @leisurelicht.

**Comment by leisurelicht** [comment]
@dpetka2001 Never mind, It is just a suggestion。

@folke Seriously？ Fine，好きにしよう。
