### ISSUE TITLE
bug:Prettier not working again. 

### ISSUE THREAD

**Issue by Redoxahmii** [LazyVim/LazyVim#3525]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10

### Operating system/version

Arch Linux

### Describe the bug

Prettier does not seem to be formatting my files anymore.
I am not that well aware if this is related to prettier or something else so i have attached a video showing that it is not working anymore if that is any help.
Happened after the recent update.
I have `nvim-lspconfig` using `version = "*"` but even changing it does not seem to be making any difference.

https://github.com/LazyVim/LazyVim/assets/13983258/18312fbe-c1d4-4a98-9cc5-e9dd7c4cab64

### Steps To Reproduce

1. Open a file and make some changes and save and no formatting happens.

### Expected Behavior

Should format.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
What does `:ConformInfo` say?

**Comment by dpetka2001** [comment]
There's a fix for prettier in latest HEAD and will be available in next stable release. If you want to follow latest HEAD see instructions in the [docs](https://www.lazyvim.org/configuration/lazy.nvim).

**Comment by ohnix** [comment]
Glad someone posted this. I'm having the same issue as of yesterday, even on vanilla LazyVim

Mine says Condition failed, or Command not found.

**Comment by Redoxahmii** [comment]
I never really ever had any issues with LazyVim before but recently all i've had is issues.
Changing one thing breaks the next and the circle is continuing.

**Comment by dpetka2001** [comment]
Update to latest LazyVim release that just got out and see if problem persists.

**Comment by Redoxahmii** [comment]
![t_2024_06_07_11_50](https://github.com/LazyVim/LazyVim/assets/13983258/2d1f5a79-e591-46a5-8fe2-de4c6ad2962c)

Still same unfortunately.

**Comment by dpetka2001** [comment]
Do you have a prettier configuration file? If not, then put in your `/lua/config/options.lua` the following option `vim.g.lazyvim_prettier_needs_config = false`.

**Comment by Redoxahmii** [comment]
i do not have a prettier configuration file in the repo.
Adding this option has made it work properly.
Previously prettier worked as is without needing this option. 
Is there some changes in how prettier is being initialized now ?

**Comment by dpetka2001** [comment]
Yes prettier is now configured by default to require a configuration file to be able to format. You use that option I mentioned if you want the old behavior back.

**Comment by Redoxahmii** [comment]
Thank you for the quick response.

**Comment by folke** [comment]
I just changed the implementation of when prettier will be used on favor of the LSP:
- when the prettier extra is enabled, it will be enabled for all supported prettier filetypes
- when additionally, astro/svelte is enabled, it will enable prettier when the correct prettier plugin is available

This way, it would all work out of the box, including for svelte/astro and will fallback to LSP automatically when the svelte/astro plugin is not available. (instead of conform throwing errors)

**Comment by Redoxahmii** [comment]
I mostly don't have an explicit file for configuration for prettier and it used to run by default but this makes more sense for you to handle the other plugins as well.
The goal for me for enabling prettier was so it could run by default and detect when and if some repository provides an explicit file for prettier configuration.
Setting the option to false reverts it back to that behavior for me so happy days.

**Comment by folke** [comment]
You didnt read my changed well I guess :)
You no longer need to set that option. prettier will work by default for supported filetypes.
Will make a new release in a bit

**Comment by Redoxahmii** [comment]
> You didnt read my changed well I guess :) You no longer need to set that option. prettier will work by default for supported filetypes. Will make a new release in a bit

Sorry i thought you meant by supported filetypes were the different formats that prettier configuration files come in and i checked for an update and nothing had yet landed so i assumed i was correct.
My bad :slightly_smiling_face: 
Thank you for your work brother!

**Comment by folke** [comment]
new release is now available

**Comment by stephen776** [comment]
This seems to still be an issue. My prettiers format on save just stopped working today. I do have a `prettier.config.js` in my project but formatting does not occur on save. 

Prettier on save working fine on same project in VSCode. Same results with my various other projects.

**Comment by folke** [comment]
Nothing changed on our end, so this is clearly a bug caused by https://github.com/stevearc/conform.nvim/pull/456
Please report an issue there

**Comment by Redoxahmii** [comment]
Seems to be working fine for me but i did notice conform deprecating something that could be the culprit.

**Comment by folke** [comment]
They changed an option, but the change was backward compatible

**Comment by dpetka2001** [comment]
https://github.com/stevearc/conform.nvim/blob/9228b2ff4efd58b6e081defec643bf887ebadff6/lua/conform/init.lua#L692-L700

It will only use LSP formatting as fallback if there are no `formatters_by_ft` defined for the specific `ft` of the buffer. I don't know how it used to work (as I've only checked the recent changes), but if you don't like the current behavior, you can either change `lsp_format = "prefer"` or request at conform's repo that the old `fallback` behavior be reinstated (again I haven't looked into how old code worked, so maybe it worked the same as now or maybe not).

**Comment by folke** [comment]
Fallback should be used if no other formatyer was used

**Comment by dpetka2001** [comment]
@folke This [line](https://github.com/stevearc/conform.nvim/blame/0d12c3781384d63909431297ed1a0f383008bb8f/lua/conform/init.lua#L699) was introduced in the latest update and now it checks if there's no filetype formatter as well.

**Comment by dpetka2001** [comment]
Submitted a PR https://github.com/stevearc/conform.nvim/pull/462 to revert to old `fallback` behavior. Not sure if this change was intended or not.
