### ISSUE TITLE
bug: The plugin `lazyvim.plugins.extras.lang.sql` doesn't work for new implementations

### ISSUE THREAD

**Issue by zafhiel** [LazyVim/LazyVim#3529]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

archlinux

### Describe the bug

I am interested in using the plugin and all its features as described at https://www.lazyvim.org/extras/lang/sql.

When I try to install `lazyvim.plugins.extras.lang.sql` 

* Using `:LazyExtras`, it doesn't appear in the list. 

* Adding it to the extras section in the `lazyvim.json` file or creating a new lua file in the plugins folder gives me the following error:

  `No specs found for module lazyvim.plugins.extras.lang.sql`

### Steps To Reproduce

1. Used a fresh or existing instance of Arch Linux.
2. Tried to install the `lazyvim.plugins.extras.lang.sql` plugin in several ways, but none of them worked.

### Expected Behavior

It should be included in the `:LazyExtras` list, or it should be possible to install and use this functionality.

**Comment by dpetka2001** [comment]
Have you updated LazyVim to latest version? Because I can see it just fine.

**Comment by zafhiel** [comment]
> Have you updated LazyVim to latest version? Because I can see it just fine.

@dpetka2001  It looks like this is only for new implementations or where it has never been installed before.

**Comment by dpetka2001** [comment]
Just remove it from `lazyvim.json` if you see an entry about it and also remove it from your `lazy.lua` where you import it. After updating to latest LazyVim version you should be able to see it in LazyExtras and install it.

**Comment by zafhiel** [comment]
Great news! A bug has been fixed in the latest version of LazyVim, 12.9.0, which was released just an hour ago.
