### ISSUE TITLE
bug: angular treesitter not enabled for telescope previews

### ISSUE THREAD

**Issue by mishasbtr** [LazyVim/LazyVim#3542]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.11.0-dev-197+gf3632e14e3

### Operating system/version

Linux

### Describe the bug

When previewing angular html files with telescope, treesitter highlighting is not enabled in the previews.

This is related to a recent addition of angular and enabling treesitter for html files:
https://github.com/LazyVim/LazyVim/pull/3488
Currently highlighting is enabled by attaching to `BufRead` event, but this seems to not be triggered when previewing the files through telescope.
I would really appreciate if someone knows a way to attach enabling angular treesitter to telescope search/preview events.

### Steps To Reproduce

1. Open an angular project
2. Search with telescope for `*html` file
3. Go through the previews
4. Observe the highlighting

### Expected Behavior

Treesitter uses angular for highlighting, not html.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by mishasbtr** [comment]
Sorry if creating an issue is not the best way to open a discussion about this problem, I'm starting get acquainted with LazyVim repository and would appreciate if someone points to a more suitable place to have this discussion.
Feel free to close the issue if this is not an approproate place for this question.

**Comment by folke** [comment]
This should indeed not be reported as an issue.
Telescope uses it's own detection to quickly render the doc.
Won't work properly indeed
