### ISSUE TITLE
bug: snippet result is displayed twice with LuaSnip extra

### ISSUE THREAD

**Issue by quangd42** [LazyVim/LazyVim#3547]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

MacOS 14.5

### Describe the bug

I got issue with vim.snippet not being able to parse snippets from friendly snippets in Golang. It seems like the recommendations in similar issues is to enable the LuaSnip extra. 

After I did that, I get two (almost) identical snippet results for the same keys. I'm suspecting that because friendly snippet is loaded twice, once by nvim-snippet and once by LuaSnip.

Please see attached recording in Golang.
![Screen Recording 2024-06-08 at 21 55 13](https://github.com/LazyVim/LazyVim/assets/113684938/10e3abf5-408b-42b3-a6da-05de927cf8a9)

### Steps To Reproduce

Please see the description. Let me know if you need more information please.

### Expected Behavior

Only one snippet result should be shown at a time to give space for lsp suggestions.

**Comment by WayenVan** [comment]
I want to reopen this issue because it happened when switching to blink.cmp in 14.x.

**Comment by dpetka2001** [comment]
@WayenVan probably related to [this](https://github.com/Saghen/blink.cmp/commit/12ffc10c6283ac148a89d72b5540d819fc80e2ff). It has been fixed on blink main branch, but you have to wait for the next blink release.
