### ISSUE TITLE
feature: add mason-tool-installer for auto updating packages

### ISSUE THREAD

**Issue by dotfrag** [LazyVim/LazyVim#3553]
### Did you check the docs?

- [X] I have read all the LazyVim docs
- [X] This is not a request for a new or existing extra (see above)

### Is your feature request related to a problem? Please describe.

Not really a problem, but I like to keep mason packages up to date.

### Describe the solution you'd like

Use [mason-tool-installer](https://github.com/WhoIsSethDaniel/mason-tool-installer.nvim) to keep mason packages up-to-date automatically.

### Describe alternatives you've considered

N/A

### Additional context

I have tried setting it up myself but I failed. First, I am not sure where the best place to put it in LazyVim's config is to create a PR, and second, I haven't gotten very far:

```lua
return {
  "williamboman/mason.nvim",
  dependencies = {
    "WhoIsSethDaniel/mason-tool-installer.nvim",
    opts = function(_, opts)
      local ensure_installed = LazyVim.opts("mason.nvim").ensure_installed
      -- for k, _ in pairs(LazyVim.opts("nvim-lspconfig").servers) do
      --   ensure_installed[#ensure_installed + 1] = k
      -- end

      opts.ensure_installed = ensure_installed
      opts.auto_update = true
      opts.integrations = {
        ["mason-lspconfig"] = LazyVim.has("mason-lspconfig.nvim"),
        ["mason-null-ls"] = LazyVim.has("none-ls.nvim"),
        ["mason-nvim-dap"] = LazyVim.has("nvim-dap"),
      }
      vim.print(opts)
    end,
  },
}
```

The above works, but it doesn't detect all packages. As you can see from the commented out part, I tried retrieving all package names from lspconfig but the names don't match 1:1 and you get errors like:

```text
   Error  11:25:59 AM notify.error lazy.nvim Failed to run `config` for mason.nvim

...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:80: Cannot find package "jsonls".

# stacktrace:
  - /mason.nvim/lua/mason-registry/init.lua:80 _in_ **get_package**
  - /LazyVim/lua/lazyvim/plugins/lsp/init.lua:287 _in_ **callback**
  - /mason.nvim/lua/mason-core/async/init.lua:87 _in_ **step**
  - /mason.nvim/lua/mason-core/async/init.lua:96 _in_ **run**
  - /mason.nvim/lua/mason-registry/init.lua:202 _in_ **refresh**
  - /LazyVim/lua/lazyvim/plugins/lsp/init.lua:285 _in_ **config**
```

The integrations option is supposed to help with this, but either I'm doing it wrong or it's not fully working.

**Comment by dotfrag** [comment]
I was skeptical to make this request, as a working implentation might require refactoring LazyVim's code.. so feel free to close it if it's a hassle.

**Comment by folke** [comment]
Why would you need this?
LazyVim already automatically installs required mason tools

**Comment by dotfrag** [comment]
It's not for installing, but for automatically updating the packages after they are installed.

**Comment by folke** [comment]
you don't need that for auto-updating.
you can easily implement that yourself in way less code than the code needed to add the plugin.

**Comment by dotfrag** [comment]
Okay, I'll give it a shot, thanks for checking!
