### ISSUE TITLE
bug: Attempt to index field 'foldupdate_range' (a nil value)

### ISSUE THREAD

**Issue by kapral18** [LazyVim/LazyVim#3569]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

MacOS 14.5

### Describe the bug

When lsp adding missing imports in TS files I occasionally get these

![image](https://github.com/LazyVim/LazyVim/assets/1625373/968e1817-05b3-4d70-a382-51c3d547caa2)

Trying to understand if this is a lazyvim error or neovim error

### Steps To Reproduce

Open TS file try removing and re-adding imports via lsp organize imports

### Expected Behavior

No error

**Comment by folke** [comment]
Looks like a Neovim bug

**Comment by tomtomjhj** [comment]
the error message says that the error happened when processing bufwritepre, which means that nvim was saving the file (and trigger auto formating). were you actually saving the file when this happened? can you reproduce this by doing some edits in insert mode and concurrently trigger auto formatting without leaving insert mode?

**Comment by kapral18** [comment]
@tomtomjhj 

yes I do use mostly ctrl-c instead of esc as much as possible. Do you think it can affect this?

This happens randomly. For example this happens when I try to exit fzf-lua window when I am checking for lsp references and kill it with ctrl-c. But I noticed it mostly happens with list of new references that I haven't visited yet.

Or this happens when I try to complete the auto imports from normal mode with tsserver or typescript-tools add imports functionality with lsp code actions. And again happens with new imports mostly.

@tomtomjhj can you tell me how to trigger autoformatting without leaving insert mode?

**Comment by tomtomjhj** [comment]
> yes I do use mostly ctrl-c instead of esc as much as possible. Do you think it can affect this?

yes this seems to be the root cause. leaving insert mode eith ctrl-c doesn't trigger insertleave autocmd, and this confuses treesitter fold stuff. i missed this point when i made changes to it.

the fix is simple: just add a nil check. i was initially hesitant to do this because it didnt seem necessary, but it turns out it's indeed necessary. i'll make pr soon.

**Comment by s1n7ax** [comment]
Can confirm this is happening in 0.11 as well. This occurs in Typescript, Lua, Java files.

Almost 70% time this occurs when I organize imports in Typescript files or use `vim.lsp.buf.code_action()` to import something. And then sometimes when I use treesitter.

**Comment by tomtomjhj** [comment]
@s1n7ax do you use ctrl-c to exit insert mode?

**Comment by kapral18** [comment]
this was definitely a ctrl-c issue in my case

**Comment by s1n7ax** [comment]
@tomtomjhj Yes but how is that related to error occurring when `vim.lsp.buf.code_action()` is used? Anyway, just added a remap for `<c-c>` to `<esc>`

**Comment by tomtomjhj** [comment]
Here's the scenario that I guess you were running into. 
1. In insert mode, do some edits that update the syntax tree.
1. Leave insert mode with ctrl-c.
1. Make edits in normal mode that update the syntax tree. This happens to be the change made by code_action.
1. Enter insert mode, and leave insert mode with ESC, without making changes.
1. nil error

I have fixed this and explained why this happens in https://github.com/neovim/neovim/pull/29581

**Comment by s1n7ax** [comment]
@tomtomjhj Ah. Cool. So far no errors with `nmap <c-c> <esc>`.

**Comment by s1n7ax** [comment]
`nmap <c-c> <esc>` don't fix the issue. Hopefully PR will be merged soon

![screenshot 24-07-07 11:13:51](https://github.com/LazyVim/LazyVim/assets/18459807/01ec7e08-d1c7-4080-bb73-6997b8e67209)

**Comment by tomtomjhj** [comment]
`inoremap <c-c> <esc>`

**Comment by s1n7ax** [comment]
@tomtomjhj of course dafuq was I thinking XD

**Comment by dennypenta** [comment]
had the same issue with custom `InsertLeave` autocommand.
fixed with validating the existing changes:
```vim.api.nvim_create_autocmd({ "InsertLeave" }, {
  pattern = { "*" },
  callback = function()
    if vim.bo.modified then
      vim.cmd("silent! write")
    end
  end,
})```
