### ISSUE TITLE
bug: codelldb does not find localhost because it resolves to ipv6 address

### ISSUE THREAD

**Issue by vandalt** [LazyVim/LazyVim#3577]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.11.0-dev-210+gd9af8c2431

### Operating system/version

Arch Linux

### Describe the bug

I added the [clangd](https://www.lazyvim.org/extras/lang/clangd) extra and the debugger did not work. DAP gave the error `Couldn't connect to localhost:${port}: ECONNREFUSED`, but the dap logs in `~/.cache/nvim/dap.log` looked fine.

After digging a bit more, I realized that changing `host = "localhost"` to `host = "127.0.0.1"` in the `codelldb` adapter definition fixed the issue. The only other place where I found a reference to this is [this comment](https://github.com/mfussenegger/nvim-dap/issues/1031#issuecomment-2134247046) on an `nvim-dap` issue. The problem comes from the fact that `localhost` resolves to the IPv6 address on some system, but `codelldb` (or DAP?) only works with IPv4, if I understand correctly.

It is not clear to me if the "bug" comes from my networking setup (in which case I guess this is more a feature request than a bug report), `nvim-dap` or `codelldb`. One thing I did notice is that by default, `nvim-dap` sets `host` to `"127.0.0.1"` (according to `:h dap.txt`), so what caused the issue for me was that the adapter definition in LazyVim sets `host` to `"localhost"`.

I was wondering if setting the `host = "127.0.0.1"` was a potential fix on the LazyVim side? Otherwise I guess it would be good to document the potential issue somewhere (here or on the `nvim-dap` repo). In any case I'm happy to send a docs or code PR if it can help.

In the meantime, a simple fix was to add this to my config, in case it can help others:

```lua
  {
    "mfussenegger/nvim-dap",
    optional = true,
    opts = function()
      local dap = require("dap")
      if dap.adapters["codelldb"] then
        dap.adapters.codelldb["host"] = "127.0.0.1"
      end
    end,
  }
```

Thank you!

### Steps To Reproduce

1. Add the `clangd` extra to to LazyVim
2. Build a `cpp` file with `clangd++ -glldb <filename>`
3. Open file and launch debug session

### Expected Behavior

The expected behavior would be for debugging to start normally.

### Repro

```Lua
-- NOTE: Sorry I edited the `require("lazy")` part directly because I was not sure how else to add the plugins I needed to repro.

-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

require("lazy").setup({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    { import = "lazyvim.plugins.extras.lang.clangd" },
    { import = "lazyvim.plugins.extras.dap.core" },
    -- NOTE: Uncomment block below to fix
    -- {
    --   "mfussenegger/nvim-dap",
    --   optional = true,
    --   opts = function()
    --     local dap = require("dap")
    --     if dap.adapters["codelldb"] then
    --       dap.adapters.codelldb["host"] = "127.0.0.1"
    --     end
    --   end,
    -- },

  },
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
Just for reference for future users that might end up here, because another user commented in the commit that fixed this issue that had problems with this change, this should be better changed on the OS level. Probably (depending on the OS) in `/etc/hosts` try to see if there's a corresponding entry that resolves `localhost` to a IPv6 entry and try to comment that out.
