### ISSUE TITLE
bug: Searching Workspace symbols dont work with fzf-lua extra

### ISSUE THREAD

**Issue by smit2909** [LazyVim/LazyVim#3587]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10

### Operating system/version

MacOS Sonoma

### Describe the bug

<img width="1157" alt="image" src="https://github.com/LazyVim/LazyVim/assets/79797111/6bba8d8d-67c1-4c3d-804d-123e8f8bd347">

Searching workspace symbols throws this error. I think fzf lua library has function with name 
[lsp_live_workspace_symbols](https://github.com/ibhagwan/fzf-lua?tab=readme-ov-file#lspdiagnostics)

### Steps To Reproduce

In any project, I am using go, try to search for workspace symbols using <leader>sS

### Expected Behavior

Should be able to search workspace symbols

### Repro

**Comment by baronyoung** [comment]
I just got this error searching for a symbol in a .svelte file:

`[Fzf-lua] LSP: server does not support workspace/symbol`

I know this isn't correct as I've been doing it for years.  I'll open a new issue.

**Comment by folke** [comment]
these are issues with another plugin, so please **do not** open issues for this in LazyVim

**Comment by baronyoung** [comment]
It wasn't intentional.  I was just on the wrong github page.  My apologies.
