### ISSUE TITLE
bug: weird tab behaviour 

### ISSUE THREAD

**Issue by Axel-ex** [LazyVim/LazyVim#359]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0

### Operating system/version

linux mint 21

### Describe the bug

I am fairly new to neovim. I set in my config.lua the following options to obtain the format I want:

vim.o.expandtab = true -- Pressing the TAB key will insert spaces instead of a TAB character
vim.o.softtabstop = 4 -- Number of spaces inserted instead of a TAB character
vim.o.shiftwidth = 4 -- Number of spaces inserted when indenting
vim.o.tabstop = 4 -- A TAB character looks like 4 spaces
vim.o.smarttab = true

However when insert a tab, the number of space inserted is not calculated from the end of the word. 

### Steps To Reproduce

1. set the above options
2. create a .c file and try to insert a tab after the keywords "char" "int" or "struct"
3. depending on the number of letter of the word, the number of space inserted when tab pressed is different.

### Expected Behavior

4 spaces consistently inserted everytime tab is pressed.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Sorry, but this is clearly not a bug. Check the Neovim docs or ask this in the Github discussions instead.
