### ISSUE TITLE
bug: yanky plugin error

### ISSUE THREAD

**Issue by flavono123** [LazyVim/LazyVim#3599]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

macOS 14.5

### Describe the bug

when just a yanky extra added, the error comes its spec is not a table, but a boolean:

```sh
# :LazyHealth

lazy: require("lazy.health").check()

lazy.nvim ~
- OK Git installed
- OK no existing packages found by other package managers
- OK packer_compiled.lua not found
- ERROR Issues were reported when loading your specs:
- ERROR Invalid spec module: `plugins.yanky`
- ERROR Expected a `table` of specs, but a `boolean` was returned instead
```

### Steps To Reproduce

1. add a yank extra like:

```lua
require("lazy").setup({
  spec = {
    ...
    { import = "lazyvim.plugins.extras.coding.yanky" },
...
```

2. open the nvim, got error

fyi. [my config](https://github.com/flavono123/dotfiles/tree/master/neovim/.config/nvim) except this one, install yanky extra

### Expected Behavior

no errors

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugicns, {
  root = root .. "/plugins",
  spec = {
    { import = "lazyvim.plugins.extras.coding.yanky" }, -- this is not loaded
  },
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
You have a file `~/.config/nvim/lua/plugins/yanky.lua`
That file is not a correct lazy spec.

Please ask this types of questions in discussions next time

**Comment by flavono123** [comment]
i see my fault
thank you @folke
