### ISSUE TITLE
bug: Venv-selector extra does not work without Telescope.nvim

### ISSUE THREAD

**Issue by akthe-at** [LazyVim/LazyVim#3612]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Windows 10

### Describe the bug

This is ultimately an upstream issue (I am going to try and make a PR for them tonight if I can) because linuxcultist/venv-selector has telescope hard coded as a picker. Therefore, it doesn't seem like it can be easily extended to fzf-lua at the moment like how you have been gobbling up all the other needed picker refactors over the last 24-48 hours.  In the mean time, we could throw telescope as a dependency for anyone that has that extra installed otherwise it will bomb and error out.

### Steps To Reproduce

1. Install Python Extra
2. Open Python project or dir that has a virtual env in it.
3. Try to activate the venv with <leader>cv and behold error.

### Expected Behavior

A picker should pop up that lets you select the desired venv.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
I'd rather have a proper solution in place instead of just adding telescope.

venv-selector should ideally implement a fallback using `vim.ui.select`.
In case fzf-lua is installed, that would then be used as the ui.

**Comment by akthe-at** [comment]
> I'd rather have a proper solution in place instead of just adding telescope.
> 
> venv-selector should ideally implement a fallback using `vim.ui.select`.
> In case fzf-lua is installed, that would then be used as the ui.

No problem! I thought you might feel that way and I do appreciate the input for how to do it. I look forward to trying to doing something that can contribute to both projects.

**Comment by folke** [comment]
Closing, since venv-selector will now only be installed if telescope is available
