### ISSUE TITLE
bug: Formatter introduces syntax errors 

### ISSUE THREAD

**Issue by bartheerman** [LazyVim/LazyVim#3624]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0 

### Operating system/version

macos 14.5

### Describe the bug

   ```python
logger.info(f"Existing interfaceId for name {l3_interface['name']} is {interface_id}")
```
is formatted into
```python
logger.info(f"Existing interfaceId for name {
            l3_interface['name']} is {interface_id}")
```
A line break between `{` and `}` is not allowed and introduces a SyntaxError exception.

### Steps To Reproduce

1. Create a new python file with the line 
   `logger.info(f"Existing interfaceId for name {l3_interface['name']} is {interface_id}")`
2. Ensure prettier is installed (and used before black)
3. Format the code 

### Expected Behavior

The formatter cannot introduce SyntaxError. Black does a better job.
If prettier breaks code, it should not be used.

**Comment by dpetka2001** [comment]
`prettier` is not used for formatting Python files. I have `python`, `prettier` and `black` Extras all enabled and `LazyFormatInfo` and `ConformInfo` show that `black` is being used for formatting. Are you sure you're not doing anything wrong on your end?

**Comment by bartheerman** [comment]
have you even tried to reproduce?

**Comment by folke** [comment]
@bartheerman as @dpetka2001 says, prettier is **NOT** a formatter for python.
You probably added this to conform yourself, which obviously won't work

**Comment by bartheerman** [comment]
I enabled the formatting.prettier extra. And prettier.black is disabled. What is actually used when the formatting.prettier extra is enabled is unknown to me. Therefor I name it prettier. As black is used in formatting.black. 
But it is ok. I just disable the formatting.prettier to resolve the issue. 
So I did not add anything nor do I have a need to conform myself. But still, it was broken.

**Comment by dpetka2001** [comment]
You should name it whatever `:LazyFormatInfo` and `ConformInfo` shows. You haven't said what these commands show for you. For me it was showing `black` and `ruff_lsp` as fallback.

**Comment by bartheerman** [comment]
Formatters for this buffer:
LSP: pylsp, ruff_lsp
