### ISSUE TITLE
bug: Small nerd font icons in alpha

### ISSUE THREAD

**Issue by madjxatw** [LazyVim/LazyVim#365]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.3

### Operating system/version

Fedora 37

### Describe the bug

The new nerd font icons replacing the obsolete ones look too small. My term is kitty and the font is JetBrains Mono + `symbol_map` to Symbols Nerd Font Mono.

![alpha-icons](https://user-images.githubusercontent.com/6035833/222437210-2c78e940-42bc-4fe3-b8c2-6f473b658e31.png)

### Steps To Reproduce

Pull the latest version of LazyVim and launch nvim.

### Expected Behavior

All icons picked should look consistent in size.

**Comment by folke** [comment]
![image](https://user-images.githubusercontent.com/292349/222439497-0501add4-eb01-4939-858d-5d529fc0c99f.png)

Replaced the session icon, but couldn't find a larger sleep symbol

**Comment by madjxatw** [comment]
So sad that nf-mdi-sleep icon is obsolete. I actually had no issue with it even for CJK fonts.

**Comment by folke** [comment]
Yeah, me neither, but I assume it will be removed at some point...
