### ISSUE TITLE
bug: codelldb adapter path incorrect after removal of mason-nvim-dap.nvim dependency

### ISSUE THREAD

**Issue by Pagliacii** [LazyVim/LazyVim#3663]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.11.0-dev-236+g5def8714a

### Operating system/version

Windows 11

### Describe the bug

PR #3493 removed [mason-nvim-dap.nvim](https://github.com/jay-babu/mason-nvim-dap.nvim) from the dependencies of [nvim-dap.nvim](https://github.com/mfussenegger/nvim-dap). This change has resulted in an issue with the `codelldb` adapter, `dap.adapters.codelldb` is unable to use the correct path for `codelldb`.

### Steps To Reproduce

See the description above.

### Expected Behavior

The codelldb adapter should use the correct path, allowing proper debugging functionality.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Where are you seeing this issue? What extra? How can I trigger it?

**Comment by folke** [comment]
I possibly fixed this on main

**Comment by Pagliacii** [comment]
I've verified that your commit resolves the issue.

```diff
+    require("mason-nvim-dap")
```

The problem was reproducible using the following `launch.json` configuration and could be triggered by executing `require("dap").continue()` with any C++ file:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch C++ Program",
      "type": "codelldb",
      "request": "launch",
      "program": "${workspaceFolder}/build/${fileBasenameNoExtension}.exe",
      "args": "${input:programArgs}",
      "stopAtEntry": false,
      "cwd": "${workspaceFolder}",
      "environment": [],
      "externalConsole": false,
      "preLaunchTask": "build",
      "initCommands": [
        "log enable lldb default api"
      ]
    }
  ],
  "inputs": [
    {
      "id": "programArgs",
      "type": "promptString",
      "description": "Enter program arguments (separated by spaces):"
    }
  ]
}
```

**Comment by folke** [comment]
ok, great that it's solved. Thank you for reporting!
