### ISSUE TITLE
feature: Document how to override autocommands

### ISSUE THREAD

**Issue by danrasmuson** [LazyVim/LazyVim#3692]
### Did you check the docs?

- [X] I have read all the LazyVim docs
- [X] This is not a request for a new or existing extra (see above)

### Is your feature request related to a problem? Please describe.

By default lazyvim turns on `wrap = true` for markdown files

```lua
vim.api.nvim_create_autocmd("FileType", {
  group = augroup("wrap_spell"),
  pattern = { "*.txt", "*.tex", "*.typ", "gitcommit", "markdown" },
  callback = function()
    vim.opt_local.wrap = true
    vim.opt_local.spell = true
  end,
})
```
[source](https://github.com/LazyVim/LazyVim/blob/0422dd278a1b4e5bdbbc5b145eb161177d3ce810/lua/lazyvim/config/autocmds.lua#L87)

I was trying to set `vim.o.wrap = false` In my options file `/nvim/lua/config/options.lua` when I disable wrap it gets overriden by this autocmd by the 

```lua
vim.o.wrap = false
```

### Describe the solution you'd like

I would like to view in the LazyDocumentation how to disable autocommands

### Describe alternatives you've considered

I've tryied getting this working with something like `vim.api.nvim_clear_autocmds({ group = "wrap_spell" })` but haven't found the right command yet

**Comment by dpetka2001** [comment]
You have to put that in `/lua/config/autocmds.lua` not `options.lua`. 

Also the group name is `lazyvim_wrap_spell`, because if you see [here](https://github.com/LazyVim/LazyVim/blob/0422dd278a1b4e5bdbbc5b145eb161177d3ce810/lua/lazyvim/config/autocmds.lua#L3-L5) that's how the group name is getting created, by prepending `lazyvim_` to whatever is in the `augroup("whatever_name")`.

**Comment by danrasmuson** [comment]
> You have to put that in `/lua/config/autocmds.lua` not `options.lua`. I mean the `vim.api.nvim_clear_autocmds({ group = "wrap_spell" })` that you mentioned.
> 
> Also the group name is `lazyvim_wrap_spell`, because if you see [here](https://github.com/LazyVim/LazyVim/blob/0422dd278a1b4e5bdbbc5b145eb161177d3ce810/lua/lazyvim/config/autocmds.lua#L3-L5) that's how the group name is getting created, by prepending `lazyvim_` to whatever is in the `augroup("whatever_name")`.

Thanks! I can confirm putting `vim.api.nvim_clear_autocmds({ group = "lazyvim_wrap_spell" })` in my `autocmds.lua` fixed this for me
