### ISSUE TITLE
bug:  Hover get exited when scrolling to the end 

### ISSUE THREAD

**Issue by DrummyFloyd** [LazyVim/LazyVim#3693]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Arch

### Describe the bug

When i hover with `<s-K>` and when i scroll with `<C-f>` or `<C-b>` once i get near the end, i'm ejected  out of the hover, so i can't scroll anymore , i have to Hover again

seems to be related to `mini.animate` plugins extras

### Steps To Reproduce

1. hover whatever function
2. <c-f> till the end
3. cannot use <c-b> until hover exited

### Expected Behavior

shoud not  be out of hover

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
    vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
    "folke/tokyonight.nvim",
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    { import = "lazyvim.plugins.extras.ui.mini-animate" },
    {},
    -- add any other plugins here
}
require("lazy").setup(plugins, {
    root = root .. "/plugins",
})

vim.cmd.colorscheme "tokyonight"
-- add anything else here
```

**Comment by folke** [comment]
I don't really understand what you mean. Can you please be a bit clearer?
What does hover till the end mean?

> When i hover with and when i scroll with or once i get near the end, i'm ejected out of the hover,

What does that mean?

**Comment by DrummyFloyd** [comment]
> I don't really understand what you mean. Can you please be a bit clearer?
> What does hover till the end mean?
> 
> > When i hover with and when i scroll with or once i get near the end, i'm ejected out of the hover,
> 
> What does that mean?

Was not clear (I hope) because of `<command>`  not being encapsulated into quote ><

**Comment by folke** [comment]
Fixed by https://github.com/folke/noice.nvim/commit/e292a011d5cf331f35e4d0ffdd6bd6e644a1fcef
