### ISSUE TITLE
bug: after latest update, there is error in edgy

### ISSUE THREAD

**Issue by ibeex** [LazyVim/LazyVim#3697]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0

### Operating system/version

Linux Ubuntu 22.04

### Describe the bug

Failed to run `config` for edgy.nvim

vim/shared.lua:0: t: expected table, got nil

# stacktrace:
  - vim/shared.lua:0 _in_ **validate**
  - vim/shared.lua:0 _in_ **list_contains**
  - /LazyVim/lua/lazyvim/plugins/extras/ui/edgy.lua:103 _in_ **values**

### Steps To Reproduce

Start Neovim

I don't have any custom config for edgy

### Expected Behavior

no error

**Comment by ibeex** [comment]
@dpetka2001 yes, everything is updated.

**Comment by dpetka2001** [comment]
What does `nvim --version` show?

**Comment by kuba-gaj** [comment]
I have the same problem, also on latest. Maybe it's conflict with another package from `extra`? I have a lot of them enabled :)

**Comment by kuba-gaj** [comment]
```
NVIM v0.11.0-dev-226+g721551210
Build type: RelWithDebInfo
LuaJIT 2.1.1716656478
Run "nvim -V1 -v" for more info
```

**Comment by dpetka2001** [comment]
I just tried with default LazyVim installation and enabled only the `edgy` Extra, nothing else. And I could not reproduce it. Can you try with default LazyVim installation? If you can't repro with default LazyVim installation, then you should disable all the Extras and enable them again one by one to find out the conflicting one. I don't know which Extras you have installed.

**Comment by dpetka2001** [comment]
@ibeex What does `nvim --version` show?

**Comment by ibeex** [comment]
@dpetka2001 
```
❯ nvim --version
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info

**Comment by ibeex** [comment]
@dpetka2001 with clean install there is no error... here is my config for xtra
```
  "extras": [
    "lazyvim.plugins.extras.coding.copilot",
    "lazyvim.plugins.extras.coding.copilot-chat",
    "lazyvim.plugins.extras.coding.mini-surround",
    "lazyvim.plugins.extras.editor.harpoon2",
    "lazyvim.plugins.extras.editor.mini-files",
    "lazyvim.plugins.extras.editor.refactoring",
    "lazyvim.plugins.extras.formatting.black",
    "lazyvim.plugins.extras.formatting.prettier",
    "lazyvim.plugins.extras.lang.clangd",
    "lazyvim.plugins.extras.lang.markdown",
    "lazyvim.plugins.extras.lang.python",
    "lazyvim.plugins.extras.lang.terraform",
    "lazyvim.plugins.extras.lang.toml",
    "lazyvim.plugins.extras.lang.yaml",
    "lazyvim.plugins.extras.ui.edgy",
    "lazyvim.plugins.extras.util.dot"
  ],
```

**Comment by dpetka2001** [comment]
If there's no error, then it's either something in your personal configuration or there might be some other Extra that conflicts. Try enabling them one by one to see which one causes the conflict.

**Comment by kuba-gaj** [comment]
same, no errors on clean, will try to find an extra as I don't configure edgy in any of my plugins

**Comment by dpetka2001** [comment]
Maybe it's `copilot-chat`? Can you try without that?

**Comment by ibeex** [comment]
I get it since https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/extras/ui/edgy.lua#L103 disabling 
```
return {
  { "nvim-neo-tree/neo-tree.nvim", enabled = false },
}
````
since I am using mini.files reproduce this ...

**Comment by kuba-gaj** [comment]
can also confirm, disabling `neo-tree` causes the problem on fresh config

**Comment by dpetka2001** [comment]
Feel free to create a PR so that maintainer can look at it.
