### ISSUE TITLE
feature:  Add full-featured setup guides for different languages, such as lint

### ISSUE THREAD

**Issue by 5huanghuai** [LazyVim/LazyVim#3699]
### Did you check the docs?

- [X] I have read all the LazyVim docs
- [X] This is not a request for a new or existing extra (see above)

### Is your feature request related to a problem? Please describe.

Configure different languages ​​in lint, and uniformly manage and install format, lsp, lint, and dap through mason

### Describe the solution you'd like

No solution yet

### Describe alternatives you've considered

Set lsp, format, lint, dap, etc. for a language in a separate lua folder. Different plugins read lua files to obtain corresponding configurations. mason reads the lua file and installs all the necessary content

**Comment by dpetka2001** [comment]
Isn't that what LazyExtras already do?
