### ISSUE TITLE
bug: breaking change in conform.nvim

### ISSUE THREAD

**Issue by eslam-allam** [LazyVim/LazyVim#3706]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.11.0-dev+7-g878dcf198

### Operating system/version

Fedora Linux 39 (Workstation Edition)

### Describe the bug

latest version of conform renamed lsp_fallback = true to lsp_format = "fallback". Now certain files nolonger format. Calling require'conform'.format directly still works.

### Steps To Reproduce

- update conform to 9228b2ff4efd58b6e081defec643bf887ebadff6
- try to format a golang file (I`m not sure why but others like templ format just fine)

### Expected Behavior

the file should be formatted

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by eslam-allam** [comment]
I believe all that needs to be done here is to update the default opts from 
```lua 
format = {
      timeout_ms = 3000,
      async = false, -- not recommended to change
      quiet = false, -- not recommended to change
      lsp_fallback = true, -- not recommended to change
    },
```

to

```lua
format = {
      timeout_ms = 3000,
      async = false, -- not recommended to change
      quiet = false, -- not recommended to change
      lsp_format = "fallback", -- not recommended to change
    },
```

**Comment by eslam-allam** [comment]
my description seems to be inaccurate. will open again after investigating abit

**Comment by dpetka2001** [comment]
I believe it should be `lsp_format = "fallback"`.
