### ISSUE TITLE
bug: there are 2 suggested supertab configurations in website

### ISSUE THREAD

**Issue by longwuyuan** [LazyVim/LazyVim#3713]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

% nvim -v NVIM v0.10.0 Build type: Release LuaJIT 2.1.1713484068 Run "nvim -V1 -v" for more info

### Operating system/version

Linux Ubuntu LTS

### Describe the bug

Hi,

There are 2 code snippets for configuring supertab. One is in the ./lua/plugins/example.lua and the other is under the recipes section of the website https://www.lazyvim.org/configuration/recipes. Which one to use as they are slightly different

![image](https://github.com/LazyVim/LazyVim/assets/5085914/dd88fcab-f28a-4f91-9ab5-22efc6f3d5da)

### Steps To Reproduce

copy both code-snippets in separate files and diff them

### Expected Behavior

Only one suggested code-snippet is availabel for configuring supertab

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Removed the example

**Comment by longwuyuan** [comment]
Thank you very much @folke . All of your work is a blessing . Gratitude :pray:
