### ISSUE TITLE
bug: nvim-metals does not load when Scala extras is enabled

### ISSUE THREAD

**Issue by VersBinarii** [LazyVim/LazyVim#3717]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0 Build type: Release LuaJIT 2.1.1713773202 Run "nvim -V1 -v" for more info

### Operating system/version

MacOs Sonoma 14.0

### Describe the bug

It seems that one of the last updates has broken Scala extras as it is not loading the nvim-metals when enabled.
The file is correctly recognized:
![image](https://github.com/LazyVim/LazyVim/assets/2277121/67f075c7-5000-4a90-89ea-c5b8ae732be2)
The scale extras is enabled:
![image](https://github.com/LazyVim/LazyVim/assets/2277121/1981b5f7-4f4b-4460-bbbb-418826e7429b)
But it seems that the metals plugin is not loaded:![image](https://github.com/LazyVim/LazyVim/assets/2277121/6fe1ef59-3403-44bb-8caa-f2ecc0315cb2)

### Steps To Reproduce

Enable LazyExtra scala support

### Expected Behavior

Metal commands should be available and LSP server should start

**Comment by dpetka2001** [comment]
I don't see the LSP server `metals` in the image that you showed. Didn't it get installed by Mason? Does Mason show if `metals` is installed?

**Comment by VersBinarii** [comment]
No, metals does not seem to be installed. This setup worked fine till few weeks ago. I just didn't touch scala for last ~2  weeks
![image](https://github.com/LazyVim/LazyVim/assets/2277121/c3b7b762-1903-4a1c-830b-f623a11e8b67)

**Comment by gpwns3717** [comment]
Did this situation occur when you opened a "new" scala file?
In nvim-metals, only existing scala files are initialized.([see here](https://github.com/scalameta/nvim-metals/blob/1b87e6bfa4174b5fbaee9ca7ec79d8eae8df7f18/lua/metals/setup.lua#L71))

**Comment by VersBinarii** [comment]
metals is not present in the 'Available' list. Typing MasonInstall metals returns: 'metals is not a valid package'.

It happens on new and existing projects unfortunately

**Comment by dpetka2001** [comment]
It seems it got removed. You have to install `metals` server another way then. Read the official docs for how to install it on your system.

**Comment by dpetka2001** [comment]
Oh it seems that the plugin installs the `metals` server for you. Please defer to @gpwns3717 comment instead.

**Comment by gpwns3717** [comment]
Yes, by default mason doesn't provide metals, nvim-metals installs it automatically, so I don't think it's a mason issue.

I'd need a more detailed reproduce to figure out the cause.

**Comment by VersBinarii** [comment]
Yes, i dont think its a mason issue either. The issue seems to be that the nvim-metals seems not initialized. I showed the screen that shows that the `:Metals` command that should be provided by nvim-metals is not available which to me suggest issue with nvim-metals intialization. When i configured nvim-metals manually in plugin folder the nvim-metals was correctly initlaized.

**Comment by VersBinarii** [comment]
@gpwns3717  i looked at the code you linked. I misunderstood initially but i definitely test it on actual, existing .scala files.

**Comment by VersBinarii** [comment]
Just wondering if this [change](https://github.com/LazyVim/LazyVim/commit/c1f5fcf9c7ed2659c9d5ac41b3bb8a93e0a3c6a0) couldn't have anything to do with it?

**Comment by gpwns3717** [comment]
I think the problem with adding Commands is a problem with nvim-metals.
Commands are added [here](https://github.com/scalameta/nvim-metals/blob/1b87e6bfa4174b5fbaee9ca7ec79d8eae8df7f18/lua/metals/setup.lua#L78) during the initialization process, but due to the issues mentioned above, the command addition process is skipped.

And even if I tested it after reverting to the previous version, the new file was not initialized.
Could you please check if it works properly after reverting? I couldn't find the problem in my environment.

**Comment by VersBinarii** [comment]
Hmmm, rolling back to one commit before that change initilizes nvim-metals for me:
![image](https://github.com/LazyVim/LazyVim/assets/2277121/bf9ea099-24da-4f2a-af27-7cbf641a9b74)
Although with some errors:
```
stack traceback:
	[C]: in function 'error'
	vim/shared.lua: in function 'validate'
	vim/shared.lua: in function 'tbl_contains'
	...share/nvim/lazy/LazyVim/lua/lazyvim/plugins/lsp/init.lua:151: in function <...share/nvim/lazy/LazyVim/lua/lazyvim/plugins/lsp/init.lua:147>
	[C]: in function 'nvim_exec_autocmds'
	.../.local/share/nvim/lazy/LazyVim/lua/lazyvim/util/lsp.lua:79: in function <.../.local/share/nvim/lazy/LazyVim/lua/lazyvim/util/lsp.lua:61>
	[C]: in function 'nvim_exec_autocmds'
	...im-macos-arm64/share/nvim/runtime/lua/vim/lsp/client.lua:946: in function '_on_attach'
	...im-macos-arm64/share/nvim/runtime/lua/vim/lsp/client.lua:615: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by gpwns3717** [comment]
Hmm... even if I test that commit, it behaves the same as the current commit. And no error occurs.

It seems to me like it's not a problem in LazyVim, but a conflict somewhere else.

**Comment by VersBinarii** [comment]
Ok, so your comment about conflict made me realize that i had this small bit of extra config in my plugins directory:
```
 {
   "neovim/nvim-lspconfig",
   ---@class PluginLspOpts
   opts = function(_, opts)
     opts.codelens = { enabled = false }
     opts.inlay_hints = { enabled = true }
     opts.capabilities = vim.lsp.protocol.make_client_capabilities()
     opts.capabilities.textDocument.completion.completionItem.snippetSupport = false
   end,
},
```
After commenting it out the nvim-metal now loads correctly

**Comment by dpetka2001** [comment]
Why do you have this line `opts.capabilities = vim.lsp.protocol.make_client_capabilities()`? This overrides the default capabilities and returns a new object. Maybe that's the cause of the conflict?

**Comment by gpwns3717** [comment]
@dpetka2001 I agree with your comment.

@VersBinarii Can you change it below and test it out?
lazy.nvim will automatically merge the opts table.

```lua
  {
    "neovim/nvim-lspconfig",
    ---@class PluginLspOpts
    opts = {
      codelens = {
        enabled = false,
      },
      inlay_hints = {
        enabled = true,
      },
      capabilities = {
        textDocument = {
          completion = {
            completionItem = {
              snippetSupport = false,
            },
          },
        },
      },
    },
  },
```

**Comment by dpetka2001** [comment]
I was just about to make the same comment :smile:

**Comment by dpetka2001** [comment]
Also `inlay_hints.enabled = true` is not needed since it's already the default.

**Comment by dpetka2001** [comment]
When you're using an `opts` function, the values you change for keys completely override the default values. It would be advisable to use `vim.tbl_deep_extend("force", default_key, { custom_key = custom_value })` instead. Just something to keep in mind.

**Comment by VersBinarii** [comment]
Yes, it does appear that i was being a dum dum. 
@gpwns3717 your change dos fixes everything for me, thank you.
@dpetka2001 thanks for the pointers, i only dabble a little bit with lua so some of the stuff  confused me a bit.

Thanks for the help
