### ISSUE TITLE
bug: nvim-treesitter error on read-only file system

### ISSUE THREAD

**Issue by linsui** [LazyVim/LazyVim#3718]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

NixOS

### Describe the bug

I install the treesitter parsers from nixpkgs into a read-only path. I disabled auto_install and ensure_installed for nvim-treesitter and it worked well. But after a recent update it complains that the parser dir is read-only on neovim start.

### Steps To Reproduce

Install nvim-treesitter to a read-only path.

### Expected Behavior

If I don't need to install parsers via nvim-treesitter it shouldn't error out.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by linsui** [comment]
According to nvim-treesitter dev, this plugin is only used to install parsers. But it seems I can't disable it directly.

**Comment by dpetka2001** [comment]
Can't you just make sure that `ensure_installed` is an empty list, so nothing gets installed by default?

**Comment by dpetka2001** [comment]
See #3702

**Comment by linsui** [comment]
> Can't you just make sure that ensure_installed is an empty list, so nothing gets installed by default?

This is what I do. It worked. But recently it doesn't work anymore.

**Comment by dpetka2001** [comment]
How are you defining it to be empty? Can you show your code?

**Comment by linsui** [comment]
> See https://github.com/LazyVim/LazyVim/discussions/3702

Wow, this works, thanks!
