### ISSUE TITLE
bug: which-key set `il`/`al`/`in`/`an` even if they are disabled or remapped in `mini.ai`

### ISSUE THREAD

**Issue by jimzk** [LazyVim/LazyVim#3720]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0

### Operating system/version

MacOs 14.5

### Describe the bug

When I disable `il`/`al`/`in`/`an` in `mini.ai`, the which-key still registers them, which will pop up cheatsheet table and cause them to be unusable if I remap them to other text objects.

![image](https://github.com/LazyVim/LazyVim/assets/10106636/b6d62aae-9c21-4106-8f3f-0b35845720a6)

### Steps To Reproduce

Disable next/last text-object mapping in mini.ai

```lua
return {
  "echasnovski/mini.ai",
  opts = {
    mappings = {
      around_next = "",
      inside_next = "",
      around_last = "",
      inside_last = "",
    },
  },
}

```

### Expected Behavior

Do not register `il`/`al`/`in`/`an` if I disable them in mini.ai.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Sorry, won't fix...
