### ISSUE TITLE
bug: relative number not working

### ISSUE THREAD

**Issue by ha5h6r000wn** [LazyVim/LazyVim#3721]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.11.0-dev-274+g1a1c76604-Homebrew

### Operating system/version

MacOS 14.5

### Describe the bug

<img width="1657" alt="image" src="https://github.com/LazyVim/LazyVim/assets/170237072/adfce3e1-00f6-4993-b48c-38136aeebf61">

By pressing SPACE-uL, it only shows current line number while the "relative numbers" can't be seen anywhere. It used to work fine but don't know somehow it ends up like this.  

### Steps To Reproduce

SPACE-uL

### Expected Behavior

shows relative numbers

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
Try out #3719 locally
