### ISSUE TITLE
bug: formatting is not working if lang.go and formatting.prettier are installed on relevant files

### ISSUE THREAD

**Issue by leaf541** [LazyVim/LazyVim#3729]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0

### Operating system/version

MacOS 14.5

### Describe the bug

I have installed extras lang.go and formatting.prettier alongside lsp.null-ls. Inside TS file it's not formatted on save with installed prettier extra. Also GO file is not formatting if I have lang.go extra installed. 

### Steps To Reproduce

1. Start neovim with repro.lua
2. open .ts file that can be prettified
3. edit it and save
4. Formatting is not working

--- 
1. Same steps with .go files to test it

### Expected Behavior

When there are formatting issues and you save a file it should be formatted.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  { import = "lazyvim.plugins.extras.lsp.none-ls" },
  { import = "lazyvim.plugins.extras.lang.typescript" },
  { import = "lazyvim.plugins.extras.lang.go" },
  { import = "lazyvim.plugins.extras.formatting.prettier" },
  { import = "lazyvim.plugins.extras.linting.eslint" },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
This is due to a recent change in `conform.nvim` and is not a LazyVim bug. I submitted a PR https://github.com/stevearc/conform.nvim/pull/462 to revert to old `fallback` behavior. Not sure if this change was intentional or not.

**Comment by leaf541** [comment]
Okay, thank you for sharing. Should I close a issue then?

**Comment by dpetka2001** [comment]
If you would be kind since it's not a LazyVim bug.
