### ISSUE TITLE
bug(haskell): LazyVim.root does not detect lsp root dir

### ISSUE THREAD

**Issue by grddavies** [LazyVim/LazyVim#3732]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Ubuntu 22.04.4

### Describe the bug

In a git repo containing multiple Haskell projects, and with `haskell-tools.nvim` configured via the LazyVim extra, `LazyVim.root.get()` returns the git project root, rather than the `haskell-tools.nvim` lsp client `root_directory`. 

This causes the file tree and the terminal to open at the wrong directory.

I have looked at the how `haskell-tools.nvim` is configured as an LSP client [here](https://github.com/mrcjkb/haskell-tools.nvim/blob/master/lua/haskell-tools/lsp/init.lua#L132), and it does not set `workspace_folders`. It _does_ set `root_dir`, although this is ignored by `LazyVim.root.detectors.lsp`.

According to the LSP Protocol [here](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initialize) `rootPath` is a deprecated argument to the `initialize` request. But while it isn't marked as deprecated as an option in `vim.lsp.start()`, I think LazyVim should be able to find the project root using either the `root_dir` or the `workspace_folders` that the client was initialised with.

I'm happy to open an issue in `haskell-tools.nvim` if that is not launching the client correctly.

### Steps To Reproduce

1. Create the following file structure:
```
├── .git/
├── bar
│  └── bar.cabal
└── foo
   ├── foo.cabal
   └── foo.hs
```

2. Ensure the `lang.haskell` LazyVim extra is enabled and open `foo.hs`

3. run `:lua vim.print(LazyVim.root.get())` and see that the returned directory is above `foo/`

4. Run `LspInfo` to verify that `haskell-tools.nvim` has a root directory of `/path/to/foo`

### Expected Behavior

Correct LSP root calculated

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  -- add any other plugins here
  { import = "lazyvim.plugins.extras.lang.haskell" },

}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
[Here in your dotfiles](https://github.com/grddavies/dotfiles/blob/8d9ddebebc8febca823f13477fe64bef5c91ff21/home/dot_config/nvim/lua/plugins/extras/user/lang/haskell.lua#L11-L18) you're setting up `hls` with `nvim-lspconfig`. At the end of the function you should `return true`, so that `hls` doesn't get set up by `nvim-lspconfig` but rather by `haskell-tools` instead. Maybe that's what's causing the conflict in the LSP root dir you're observing?

**Comment by folke** [comment]
LazyVim uses both root_dir and workspace_folders, so there's something else going on in your config

**Comment by grddavies** [comment]
The bug can be reproduced using the folder structure described above, and teh minimal repro using only LazyVim and the lang.haskell extra.

**Comment by grddavies** [comment]
Thanks!
