### ISSUE TITLE
question: fonts don't seem to display 

### ISSUE THREAD

**Issue by jason-shen** [LazyVim/LazyVim#374]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.80

### Operating system/version

MacOS 11.5

### Describe the bug

this is not really a bug its more of a question, i have googled but couldn't find anything. 

i do have jetbrains nerd front install, but some icon's just don't show, is there any other font i need for this?

<img width="807" alt="CleanShot 2023-03-04 at 05 33 24@2x" src="https://user-images.githubusercontent.com/1794291/222775765-b50907f8-7826-46b1-8997-ce01752344d0.png">

### Steps To Reproduce

1. see the image

### Expected Behavior

icons don't display

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
you need a nerd font as is mentioned in the requirements of the docs.

Please use Github discussions for these types of questions next time.

**Comment by jason-shen** [comment]
i do have installed nerd font as mention, sure will use github disussions cheers

**Comment by folke** [comment]
Maybe your terminal does not support nerd fonts?
