### ISSUE TITLE
bug: cannot use <c-cr> when a suggestion is showing

### ISSUE THREAD

**Issue by BSFishy** [LazyVim/LazyVim#3743]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Pop!_OS 22.04

### Describe the bug

Whenever I start typing something and get the suggestions menu, I expect to be able to press Ctrl + Enter to make a new line instead of select a suggestion. I can't seem to do that. If I'm not mistaken, this was working a little while ago, but I can't remember when.

I did some testing of my own, but I'm not familiar enough with any of this stuff to be confident. However, from what I could tell, `nvim-cmp` doesn't differentiate between `<CR>` and `<C-CR>`, meaning that the mappings won't work as intended:

https://github.com/LazyVim/LazyVim/blob/dde4a9dcdf49719c67642d09847dbaf7f9c7a156/lua/lazyvim/plugins/coding.lua#L37-L43

### Steps To Reproduce

1. Follow steps to install the LazyVim starter
2. Open a file
3. Start typing something to get the suggestion menu
4. Press Ctrl + Enter

### Expected Behavior

I expect to be able to press Ctrl + Enter to insert a new line instead of select a suggestion.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")

-- I didn't change anything here, works as is
```

**Comment by dpetka2001** [comment]
This is not a LazyVim bug but a problem with how your terminal emulator interprets the key sequence. Enter `insert` mode and press `<C-v><C-cr>` and see what characters are printed out.

**Comment by BSFishy** [comment]
Okay isolating it to the terminal emulator was the solution! I feel like this was on my mind a little while ago when I first started noticing it but I forgot about it recently. Adding the keybind from this comment fixed the issue: https://github.com/wez/wezterm/issues/2692#issuecomment-1300525115

Thanks for helping me find that!
