### ISSUE TITLE
bug: no specs found for module prisma

### ISSUE THREAD

**Issue by banjo** [LazyVim/LazyVim#3770]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

MacOS 14.2.1

### Describe the bug

Trying to install Prisma by adding the extras line for it:

```
{ import = "lazyvim.plugins.extras.lang.prisma" }
```

However, I just get this error message: 

```
No specs found for module lazyvim.plugins.extras.lang.prisma
```

### Steps To Reproduce

1. Add prisma import
2. Restart nvim

### Expected Behavior

It should install appropriate Prisma packages

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  { import = "lazyvim.plugins.extras.lang.prisma" }
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
Are you sure LazyVim is updated to latest version?

**Comment by banjo** [comment]
An update did solve the issue. Sorry about that and thanks.
