### ISSUE TITLE
bug: vim.ui.open might not work in all environments

### ISSUE THREAD

**Issue by abhidahal** [LazyVim/LazyVim#3776]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Arch Linux : 6.9.5-arch1-1

### Describe the bug

`vim.ui.open` function is not universally supported across all systems or all versions of Neovim. This function is part of the new Lua API in Neovim and it might not be available if the user is running an older version of Neovim.

### Steps To Reproduce

1. `<leader>gB`
2. E5108: Error executing lua: ...cal/share/nvim/lazy/LazyVim/lua/lazyvim/util/lazygit.lua:179: attempt to call field 'open' (a nil value)

### Expected Behavior

To open the GitHub repo in the browser instead of the current error.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by abhidahal** [comment]
Previously, the `open` function in `lazygit.lua` was using `vim.ui.open` to
open URLs, which might not work in all environments. I changed
the function to use `os.execute` with `xdg-open`, `gnome-open`, or `kde-open`,
which should make it more compatible with different systems.

```diff
- 179 : vim.ui.open(remote.url)
+ 179 :  os.execute( string.format('xdg-open "%s" || gnome-open "%s" || kde-open "%s" &', remote.url, remote.url, remote.url))
```

**Comment by dpetka2001** [comment]
This is not a bug but a conscious choice made by the maintainer. See also another [comment](https://github.com/LazyVim/LazyVim/pull/2758#issuecomment-2014698137) of his in another PR. The only thing that could be done is show an error like `vim.ui.open not found on your Neovim`, so that it's less confusing.

**Comment by dpetka2001** [comment]
@abhidahal I submitted a PR for the latter approach using `lazy.util.open` in Neovim <=0.10. 

Hopefully the maintainer accepts it.
