### ISSUE TITLE
bug: (kotlin extra) Parser failed. <...> Expected value but found invalid token at character 1

### ISSUE THREAD

**Issue by againstpetra** [LazyVim/LazyVim#3779]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

macOS 14.5

### Describe the bug

Install kotlin extra. Open an android project. See this error:

```
Parser failed. Error message:
~/.local/share/nvim/lazy/nvim-lint/lua/lint/linters/ktlint.lua:8: Expected value but found invalid token at character 1
```

same thing happens with the minimal reporo lua

### Steps To Reproduce

1. Install kotlin extra
2. Open android project
3. See the above error

### Expected Behavior

It should just lint the kotlin and report the errors.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
Probably an issue with `nvim-lint` itself? Maybe open an issue at the plugin's repo? Seems similar to https://github.com/mfussenegger/nvim-lint/issues/242.

**Comment by againstpetra** [comment]
thanks, will update this issue depending on how my issue there goes.
