### ISSUE TITLE
bug: Can't identify the selected text due to document highlights

### ISSUE THREAD

**Issue by s1n7ax** [LazyVim/LazyVim#3785]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.11.0-dev+0e3e1e6

### Operating system/version

NixOs

### Describe the bug

Right now I'm using `rose-pine` color scheme. When I move my cursor to string, it highlights the entire string like below.

![image](https://github.com/LazyVim/LazyVim/assets/18459807/a284cfc8-1360-47d8-9ead-7ca3657e07a5)

However, when I select only the text `oil.nvim` from that entire text, there is no way to distinguish the selected text from the `document_highlight` because both are using the same highlight.

![image](https://github.com/LazyVim/LazyVim/assets/18459807/16b9bd33-2755-4461-aba3-67dd1d7e7ab3)

Apparently in lazyvim, on cursor hold, `vim.lsp.buf.document_highlight()` is called

![image](https://github.com/LazyVim/LazyVim/assets/18459807/ea625656-57df-4c20-891c-2eec0fb017d2)

When I comment that line, I can identify the text selected as expected.

![image](https://github.com/LazyVim/LazyVim/assets/18459807/d5b5ca7e-92bb-4e15-9abd-097e8497b57e)

### Steps To Reproduce

-

### Expected Behavior

Use two different highlight colors? one for document highlight and one for selection?

### Repro

```Lua
-
```

**Comment by dpetka2001** [comment]
This is really dependent on your colorscheme. With default Tokyonight colorscheme this is how it looks like

![2024-06-23_21-10](https://github.com/LazyVim/LazyVim/assets/12776461/1e92afc0-43ce-416e-8180-9a0563508144)

You can see that the LSP document highlight is a greyish color while `nvim-dap` visual selection is blue.

**Comment by s1n7ax** [comment]
@dpetka2001 I see. Is there a way to change the highlight for any color scheme?

I would like to have something like below

```lua
vim.api.nvim_set_hl(0, 'Visual', { fg = '#000000', bg = '#db4b4b' })
```

But not quite sure how to load that after colorscheme is loaded to override the existing highlight.

**Comment by dpetka2001** [comment]
You should read the docs of the colorscheme you're interested in to see if they provide a way to do that. Tokyonight provides a way to do that, for example I do
```lua
  {
    "tokyonight.nvim",
    style = "moon",
    opts = {
      on_colors = function(colors)
        colors.gitSigns["change"] = "#FF8000"
        colors.gitSigns["add"] = "#006C00"
      end,
    },
  },
```
to change these specific colors to what I want. I'm not sure what ways `rose-pine` provides. Another way would be to define your custom highlight in an autocmd probably on `BufReadPost/BufNewFile` events. But I don't know if the autocmd might have some other side effects.
