### ISSUE TITLE
bug: Can't send telescope git status to trouble

### ISSUE THREAD

**Issue by niba** [LazyVim/LazyVim#3787]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

MacOs 14.3

### Describe the bug

When you try to send a git status data to trouble then you get an error: "Filename is required"
As a workaround you can send it to quickfix first

I don't know if this is a trouble bug or lazyvim bug. I'm reporting it here

### Steps To Reproduce

1. Open telescope with git status data. Default <leader>gs
2. Try to send it to trouble using ctrl-t

### Expected Behavior

Trouble should open and consume list of files.

**Comment by folke** [comment]
That's an issue with trouble. Please report it there instead.
I can't transfer the issue since lazyvim is an org
