### ISSUE TITLE
bug:  clangd has no reaction to clang-tidy

### ISSUE THREAD

**Issue by SCXM729** [LazyVim/LazyVim#3791]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

archlinux

### Describe the bug

can't get information from clagd-tidy

### Steps To Reproduce

I install lazyvim online, and just add two line configuration without any other change
![image](https://github.com/LazyVim/LazyVim/assets/148051331/79c5706b-026d-4b82-ad4c-42756031d2f3)
 
but there no any prompt here from clang-tidy
![image](https://github.com/LazyVim/LazyVim/assets/148051331/7d94fc54-7b86-428f-be8a-4e205f2ba402)
the lspinfo
![image](https://github.com/LazyVim/LazyVim/assets/148051331/16556815-ef52-4d64-b387-12a6ecc091bd)
the lsplog
![image](https://github.com/LazyVim/LazyVim/assets/148051331/a4211cca-0a80-4f7f-893b-958f7a17ea6f)

### Expected Behavior

![image](https://github.com/LazyVim/LazyVim/assets/148051331/f9092a57-fb0c-408a-a701-72206b7b5872)

**Comment by folke** [comment]
This is not a bug, but a configuration issue. Clangs is connected, so that's working as it should. No idea what clang tidy is or how to set it up with the LSP. Ask on GitHub discussions if you want, but not here
