### ISSUE TITLE
feature: option to use `vim.g.terminal_color_0` as the background color in floating terminals

### ISSUE THREAD

**Issue by Martin1887** [LazyVim/LazyVim#3793]
### Did you check the docs?

- [X] I have read all the LazyVim docs
- [X] This is not a request for a new or existing extra (see above)

### Is your feature request related to a problem? Please describe.

In dark backgrounds, usually the floating background color is brighter than the background, and it is good for the most of floating windows. However, for terminals using a darker background (even pure black) is better for more contrast.

### Describe the solution you'd like

An option to use `vim.g.terminal_color_0` in floating terminals instead of the floating background color.

### Describe alternatives you've considered

I have not found any alternatives.

**Comment by dpetka2001** [comment]
I believe the floating terminal use the highlight group `NormalFloat`, so you can change that to whatever you want.

**Comment by Martin1887** [comment]
But the thing is `NormalFloat` is good to be a bit brighter for most of floating windows except floating terminal.

It also would differentiate floating terminals of other floating windows.

**Comment by folke** [comment]
create an autocmd on buftype, and then set winhl to the custom group you want
