### ISSUE TITLE
bug: undo a change then go to neotree to change file with file picker will always show select window

### ISSUE THREAD

**Issue by nadeemkhedr** [LazyVim/LazyVim#3795]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Macos 14.5

### Info

Issue is related neo-tree and the plugin that shows info in the bottom right (not sure which one) when undoing we get some info like `One line less before #3; 1 second ago` 

Neo-tree has an option to open the selected file with a file picker (by default bound to `w`) (option called `open_with_window_picker`)

If you have one pane, open when selecting a file with `w` opens it in that pane without showing the select file ui

---

### What is the issue:

When you have some text visible in the bottom right, and open neo-tree and select a file you will see a file picker 

![2024-06-24_13-58-33](https://github.com/LazyVim/LazyVim/assets/180256/c23c97cc-6953-4967-9300-eb545d4e746a)

### Steps To Reproduce

1. Go to any file
2. add a new line then undo
3. you will see in the bottom right `One line less before #3; 1 second ago`
4. While that is visible, open `neo-tree` and click `w` on any file
5. You will see select window picker

### Expected Behavior

If you only have one pane, you shouldn't see select window picker

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by nadeemkhedr** [comment]
I wasn't sure what the plugin on the bottom right is called? Question is should this fix be part of lazyvim because its already using the two plugins together?

**Comment by dpetka2001** [comment]
LazyVim doesn't use `nvim-window-picker`. That is something that you added yourself. So, configure it properly. The maintainer of that plugin also made a question here in LazyVim recently, so maybe he's using LazyVim himself (I'm just guessing). Ask the maintainer directly at the plugin's repo.

**Comment by nadeemkhedr** [comment]
You are actually right, mb. I thought it was bundled with `neo-tree`. Quick question do you know what the plugin that adds text in the bottom right called?

**Comment by dpetka2001** [comment]
It's probably [noice.nvim](https://github.com/folke/noice.nvim/).
