### ISSUE TITLE
bug: No longer displays line numbers when opening a file directly

### ISSUE THREAD

**Issue by zolrath** [LazyVim/LazyVim#38]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.8.2

### Operating system/version

MacOS 11.5

### Describe the bug

The latest version of LazyVim no longer displays the line numbers to the left of the buffer when opening a file directly from the terminal.

### Steps To Reproduce

1. Go to a directory in the terminal
2. `vim filename` directly 
3. There are no line numbers on the left

### Expected Behavior

Line numbers would be on the left, just like they are if you open vim and then open a file from within vim.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Yep, I'm aware of this. It's because of a recent change I did. Will fix this!
