### ISSUE TITLE
bug: (javascript/typescript) auto format does not use my .eslintrc

### ISSUE THREAD

**Issue by fegyi001** [LazyVim/LazyVim#380]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.0-dev-1001+gcbd4480f9

### Operating system/version

MacOS 13.2.1

### Describe the bug

(Foreword: I'm quite beginner with neovim/lazyvim etc, just switched to lazyvim from nvchad.)

While eslint errors are shown correctly, on save lazyvim does not seem to use eslint rules (e.g. delete extra lines, remove whitespaces when needed etc). So my file is fine, no eslint errors, hit save, and reformatted somehow, and now shows eslint errors. 

An example: this is a file BEFORE saving:
<img width="780" alt="image" src="https://user-images.githubusercontent.com/4125222/222900199-683ff33b-8dfe-4e9b-99a1-e51fdd093ae8.png">

And when I save this is how it looks like after auto formatting:
<img width="706" alt="image" src="https://user-images.githubusercontent.com/4125222/222900219-cc435a7b-36c7-47d8-8223-0954e873c185.png">

It has a prettier-related problem which is fine, I have prettier rules in my .eslintrc conf file.
lazyvim recognizes the problem just fine:
<img width="599" alt="image" src="https://user-images.githubusercontent.com/4125222/222900270-a0de0a61-9312-42b8-babd-f7680c59d5ae.png">

How could I tell lazyvim to use my eslintrc config file when saving a typescript/javascript file?

### Steps To Reproduce

1. Edit file, make sure no eslint errors are present
2. Save file
3. On save, lazyvim reformats file, but does not use my .eslintrc file

### Expected Behavior

lazyvim should be able to use existing eslint config files when possible.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Add the following:

```lua
       {
    "neovim/nvim-lspconfig",
    opts = {
      servers = { eslint = {} },
      setup = {
        eslint = function()
          require("lazyvim.util").on_attach(function(client)
            if client.name == "eslint" then
              client.server_capabilities.documentFormattingProvider = true
            elseif client.name == "tsserver" then
              client.server_capabilities.documentFormattingProvider = false
            end
          end)
        end,
      },
    },
  },
```

**Comment by madtrick** [comment]
Hi @folke, is this still the way to disable the formatting done by `tsserver`.

I digged through the issues/commits and found that in response to this other issue https://github.com/LazyVim/LazyVim/issues/249#issuecomment-1426998926 you [pushed some changes](https://github.com/LazyVim/LazyVim/commit/fab6150da919a094614752f95f5fe4e7f55832f8) to disable formatting if the client had it disable. 

That code is gone since https://github.com/LazyVim/LazyVim/commit/f1a8f24a361d0de198f6b1458168652a6835c932 (or even earlier) so I'm wondering if now we should be using another way to fix this interference between the two format attempts.
