### ISSUE TITLE
bug: problem with installation

### ISSUE THREAD

**Issue by alec-c4** [LazyVim/LazyVim#3800]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0 LuaJIT 2.1.1716656478

### Operating system/version

macOS 14.5 (23F79)

### Describe the bug

I've used AstroNvim before and decided to move to LazyVim. I've removed all configs as described below, but got following problem

<img width="1259" alt="SCR-20240625-blje" src="https://github.com/LazyVim/LazyVim/assets/25312/9f8bb738-fa9f-43c8-9788-9747eff65a94">

### Steps To Reproduce

1. cleanup after previous installation `rm -rf ~/.local/share/nvim ~/.local/state/nvim ~/.cache/nvim`
2. remove previous installation `rm -rf ~/.config/nvim/ `
3. install LazyVim `git clone https://github.com/LazyVim/starter ~/.config/nvim`

<img width="1265" alt="SCR-20240625-bmgh-5" src="https://github.com/LazyVim/LazyVim/assets/25312/12a433f7-153e-4b3f-a2d7-636a034710af">

### Expected Behavior

Installed LazyVim

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Fixed by https://github.com/folke/lazy.nvim/commit/62a47b921fbffb3c1c8088a731029ae234f98851
Thank you for reporting!
