### ISSUE TITLE
bug: [Elixir] Credo linter is not working on fresh lazyvim installation

### ISSUE THREAD

**Issue by markevich** [LazyVim/LazyVim#3808]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0 Build type: Release

### Operating system/version

MacOS 14.1.1 (23B81)

### Describe the bug

Hi!

I installed LazyVim via instructions. Then, I installed Elixir Lang via LazyExtras. No additional plugins/customizations were enabled.

Everything works(syntax highlighting, elixir language server, autocompletion, etc) except `credo` linting.

Running `mix credo` in the terminal produces the following output:
<img width="1586" alt="image" src="https://github.com/LazyVim/LazyVim/assets/1043784/4101f82e-ab52-45bf-8c5e-a716232e865d">

Opening that file while working in NEOVIM shows no credo warning/error.
<img width="1704" alt="image" src="https://github.com/LazyVim/LazyVim/assets/1043784/8d7fea0d-cf72-490c-842a-1a8cf4d49456">

Elixir 1.16.2 (compiled with Erlang/OTP 26)

Credo is installed via mix package manager.
`{:credo, "~> 1.7", only: [:dev, :test], runtime: false}`

### Steps To Reproduce

1. Install the latest LazyVim version from the documentation.
2. Install `lang.elixir` using `LazyExtras`
3. Open up an elixir project with installed `credo`
4. Made some code issues that will be treated as warnings by `credo`

### Expected Behavior

Credo warnings are displayed in elixir project.

**Comment by markevich** [comment]
According to documentation from https://www.lazyvim.org/extras/lang/elixir there should be an function `executable("credo")` 

<img width="894" alt="image" src="https://github.com/LazyVim/LazyVim/assets/1043784/2efc5416-e944-443f-b493-3a9aba023e88">

Running that function in the editor returns 0

<img width="1223" alt="image" src="https://github.com/LazyVim/LazyVim/assets/1043784/4a7ee58c-8eed-481c-a339-bb322284bd30">

**Comment by dpetka2001** [comment]
Does `:!which credo` also return nothing? If that's so, then I believe it's a problem with your `$PATH` because you don't use Mason to install the linter. 

`nvim-lint` takes an argument `cmd` to define/overwrite the command being used. Read the docs of `nvim-lint` and use `cmd` to define the full path of wherever you installed `credo` on your own.

**Comment by markevich** [comment]
@dpetka2001 Yep, `:!which credo` returns 
<img width="552" alt="image" src="https://github.com/LazyVim/LazyVim/assets/1043784/3fb78be3-fc8b-4455-abfb-05b082fc31ca">

Hmm, but `credo` is not a binary. It's only possible to run it via `mix credo` command within an elixir mix project directory.

**Comment by markevich** [comment]
@dpetka2001 mix binary exists
<img width="645" alt="image" src="https://github.com/LazyVim/LazyVim/assets/1043784/ab63110f-72b1-4013-8ccb-bb0e827937e0">

**Comment by dpetka2001** [comment]
Can you try removing those lines
```lua
      if vim.fn.executable("credo") == 0 then
        return
      end
```
and see if it works correctly?

**Comment by dpetka2001** [comment]
Or rather change `credo` to `mix` instead.

**Comment by markevich** [comment]
Yep, i added following plugins entry:
<img width="613" alt="image" src="https://github.com/LazyVim/LazyVim/assets/1043784/f7af9b1b-4057-4bba-a41c-1bd72ccaa2fd">

And credo is working.
<img width="890" alt="image" src="https://github.com/LazyVim/LazyVim/assets/1043784/0eb09803-4197-4fe3-91e7-efe102a757eb">

**Comment by dpetka2001** [comment]
Could you please make a PR for fixing this?

**Comment by markevich** [comment]
Sure, will do it today. Thanks for the assist!

**Comment by markevich** [comment]
@dpetka2001 looking at the old discussions, it looks like if we change that executable check to "mix", elixir devs will start to receive an old error 
`I'm getting ** (Mix) The task "credo" could not be found now on any Elixir file 🤔` in projects where credo is not installed
https://github.com/LazyVim/LazyVim/pull/1546#issuecomment-1749869212 

Is there a way to do the check more efficiently? Like checking the exit status of a command?

Project with credo(exit status 0)
```
mix credo -v
1.7.7-ref.main.667fe8b+uncommittedchanges
```

Project without credo(exit status 1)
```
mix credo -v
** (Mix) The task "credo" could not be found
```

**Comment by dpetka2001** [comment]
You could try running the command with `vim.fn.system({"mix", "credo", "-v"})` and then check against `vim.v.shell_error`. If it's `0` then no error happened, otherwise an error happened.

**Comment by dpetka2001** [comment]
But this will run externally the command every time and I don't really know how much lag (if any) this would introduce potentially. I don't know of another way to do that as I'm not familiar with Elixir at all. Maybe you should ask for feedback from the maintainer as he's far more knowledgeable.

**Comment by dpetka2001** [comment]
So on the LazyVim website it has an example for `solene`
```lua
linters = {
    -- -- Example of using selene only when a selene.toml file is present
    -- selene = {
    --   -- `condition` is another LazyVim extension that allows you to
    --   -- dynamically enable/disable linters based on the context.
    --   condition = function(ctx)
    --     return vim.fs.find({ "selene.toml" }, { path = ctx.filename, upward = true })[1]
    --   end,
    -- },
  },
```
Maybe you could do something similar with `credo` using the `condition` to search for a file specific to a `credo` project? Just throwing out ideas.

**Comment by markevich** [comment]
@dpetka2001 Thanks for the suggestions!. That change doesn't have any visible performance impacts, but my project is quite small.
I asked for feedback from the maintainer in the pull request itself.

**Comment by dpetka2001** [comment]
The person you asked for feedback is not the maintainer of LazyVim. Folke is the maintainer. Also, have you tried with the `condition` like I suggested in my previous comment? Does it work with `condition` or not?

**Comment by markevich** [comment]
@dpetka2001 Yes, I tried the condition, and it works great for `nvim-lint`.

<img width="953" alt="image" src="https://github.com/LazyVim/LazyVim/assets/1043784/638a998d-8f89-4887-9aeb-fc1faa063793">

Right now I'm trying to find a similar `condition` function for `none-ls.nvim`

**Comment by markevich** [comment]
Hmm, `none-ls` is not working even if comment out any early returns from it.

<img width="1128" alt="image" src="https://github.com/LazyVim/LazyVim/assets/1043784/a403c00d-3006-44c0-a30e-f076a4fbb953">

**Comment by dpetka2001** [comment]
`none-ls` has the following about [condition in the docs](https://github.com/nvimtools/none-ls.nvim/blob/main/doc/BUILTIN_CONFIG.md#condition). Maybe you would like to try that out?

**Comment by markevich** [comment]
Yes, I tried right now. There were no syntax errors in Lua, but linting is not working anyway.

<img width="707" alt="image" src="https://github.com/LazyVim/LazyVim/assets/1043784/0897683d-d707-4a49-909b-a07993d45aba">

**Comment by dpetka2001** [comment]
Try to change that directly in `~/.local/share/nvim/lazy/LazyVim/lua/lazyvim/plugins/extras/lang/elixir.lua` and see if it works. After your testing revert all the changes you made in that file.

**Comment by markevich** [comment]
Changed plugin config directly in lazyvim plugin

<img width="688" alt="image" src="https://github.com/LazyVim/LazyVim/assets/1043784/d1b24596-0e31-4446-83bf-393cca79e396">
Linter is still not working.

I also tried fresh installation again, with only `none-ls` changes in the repo itself(I removed `executable("credo") == 0` check).

I'm not sure that the plugin works. Maybe it was broken by some upstream `none-ls` updates? 
As far as I understand, as a lazyvim user, I should pick `nvim-lint` OR `none-ls` linter for credo, it doesn't make sense to enable them both. `nvim-lint` works just fine for a new installation.

I would appreciate your advice about the possible next step for the PR:
- I can include only tested `nvim-lint` changes and create a new issue about not working `none-ls`.
- I can include `nvim-lint` changes and remove `none-ls` config entry from the elixir plugin.
- I can commit both changes, but `none-ls` will be untested.

**Comment by dpetka2001** [comment]
To use `none-ls` you have to enable the Extra first. Have you enabled it via LazyExtras?

**Comment by markevich** [comment]
I did not enable it 😞 . That was not obvious for me, sorry.

After enabling it and using config without `.credo.exs` file checks I got doubled linting errors. At least it works 🥹 
<img width="1258" alt="image" src="https://github.com/LazyVim/LazyVim/assets/1043784/0b818561-b1d5-483f-95d6-3b7192545b3b">


Then i put back the file checks.

- `nvim-lint` works
- `none-ls` doesn't work. Config: 
<img width="699" alt="image" src="https://github.com/LazyVim/LazyVim/assets/1043784/c7b44aa5-0f2d-412c-bf9f-1a46685e331e">

Is there a way to debug that a function was called. Can i print anything inside a function and then read it from some kind of logs?

**Comment by markevich** [comment]
Well, i forgot to add `return`. 🤦 
It looks like everything is working as expected now.

**Comment by dpetka2001** [comment]
So, both of them work as they should? And there's also no prob for an Elixir project without credo? Glad you got it working :smile:

**Comment by markevich** [comment]
@dpetka2001 yep. Both of them work. And nvim does not freak out if I delete credo from the project.

Thanks a lot for your patience and help!

PR is updated as well.
