### ISSUE TITLE
select a language server

### ISSUE THREAD

**Issue by RazaGR** [LazyVim/LazyVim#381]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.8.4-dev-2+gb1ae775de

### Operating system/version

MacOS 13.2

### Describe the bug

after the last update (1.16.0 commit 1f7be0b) I keep getting this popup 
![Screenshot 2023-03-04 at 1 43 12 PM](https://user-images.githubusercontent.com/30994076/222902145-1cc74b61-cf0d-4db9-a944-5f2967b5f4c9.png)

### Steps To Reproduce

open any Lua file, edit and save, upon saving hat popup shows up

### Expected Behavior

shouldn't show that popup

**Comment by folke** [comment]
I didn't make any updates to formatting, and it doesn't show that dialog for me.
Are you sure you didn't add a formatting autocmd yourself? Lazyvim uses null-ls for formatting when it is available and otherwise it uses the lsp server.

**Comment by RazaGR** [comment]
ah right, again my bad... I had ` vim.cmd([[autocmd BufWritePre * lua vim.lsp.buf.formatting_sync()]])`

Thanks again
