### ISSUE TITLE
bug: Wrong text for 'Explorer NeoTree (Root Dir/cwd) ...

### ISSUE THREAD

**Issue by heilingbrunner** [LazyVim/LazyVim#3820]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10

### Operating system/version

Windows 11

### Describe the bug

Only wrong text in the descriptions. Change 'Root Dir' and 'cwd'.

Check in file `lua/lazyvim/plugins/editor.lua`, lines 23 and 24.

```lua
      { "<leader>e", "<leader>fe", desc = "Explorer NeoTree (Root Dir)", remap = true },
      { "<leader>E", "<leader>fE", desc = "Explorer NeoTree (cwd)", remap = true },
```

should be

```lua
      { "<leader>e", "<leader>fe", desc = "Explorer NeoTree (cwd)", remap = true },
      { "<leader>E", "<leader>fE", desc = "Explorer NeoTree (Root Dir)", remap = true },
```

### Steps To Reproduce

1. Open lazyvim
2. Press `<space>`
3. Read key mapping description 

### Expected Behavior

Show corrext text

**Comment by dpetka2001** [comment]
No, the current text is correct. LazyVim uses a combination of LSP server `root_dir`, `cwd` and `.git` pattern to return the `root`. There are cases where the LSP server `root_dir` will coincide with `cwd`.
