### ISSUE TITLE
Remove LSP keeps being attempted to be started

### ISSUE THREAD

**Issue by DevonPeroutky** [LazyVim/LazyVim#3822]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

MacOS 13.4

### Describe the bug

I installed the `pyright` and `ruff-lsp` language servers for python. However, I then decided to use pyright and uninstalled `ruff-lsp` using Mason. However, I continually get the error message any time I open a python file.

```
...lar/neovim/0.10.0/share/nvim/runtime/lua/vim/lsp/rpc.lua:800: Spawning language server with cmd: `{ "ruff-lsp" }` failed. The language server is either not installed, missing from PATH, or not executable.
```

This is despite the fact that ruff-lsp is not enabled.
<img width="1792" alt="Screenshot 2024-06-26 at 3 45 10 PM" src="https://github.com/LazyVim/LazyVim/assets/36947377/9b0d44f0-3b6f-4b0f-8f36-aa57d6143f31">

I've looked everywhere. Including on Mason docs and on nvim-lspconfig docs and I can not find where the configuration is that keeps trying to start `ruff-lsp` for python files, despite it being uninstalled/removed. I have no LSP specific configuration.

Sorry if this is a dumb question, I'm new to the neovim configuration

### Steps To Reproduce

1. Install a fresh LazyVim setup
2. Install pyright and ruff-lsp via Mason GUI
3. Uninstall ruff-lsp via Mason GUI
4. Open up a python file?

### Expected Behavior

`ruff-lsp` is not attempted to be started.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
I just tried a fresh LazyVim installation and I can't reproduce. I've installed pyright and ruff-lsp via Mason and then uninstalled only ruff-lsp and I didn't observe any error when opening a Python file. Did you enable the Python Extra maybe? Do you have a link to your dotfiles available on Github?

**Comment by dpetka2001** [comment]
Also did you maybe have a previous Neovim installation before trying LazyVim? If yes, did you remove `~/.local/share/nvim`, `~/.local/state/nvim` and `~/.cache/nvim` directories before installing LazyVim to avoid any potential conflict between your previous installation and LazyVim installation?

**Comment by DevonPeroutky** [comment]
Hey @dpetka2001, I do have the Python Extras enabled I believe (shown below). I have pushed up my [current configuration here](https://github.com/DevonPeroutky/dotfiles) for you.
<img width="1792" alt="Screenshot 2024-06-26 at 4 36 57 PM" src="https://github.com/LazyVim/LazyVim/assets/36947377/22d1f38d-8c92-48da-80fe-06be1dfc5d40">

I didn't have a pre-existing Neovim or LazyVim installation.

**Comment by DevonPeroutky** [comment]
As a beginner, I think I'm a little lost on the Lazyvim <> Mason <> Neovim-lspconfig interaction and where the configuration lives. I was able to find some configuration via greping through `~/.local/share/nvim` for `ruff-lsp`, but modifying things there didn't resolve anything (and probably made things worse, so I reinstalled those packages).

**Comment by dpetka2001** [comment]
I think it's because of [these lines](https://github.com/DevonPeroutky/dotfiles/blob/b5d77643b0b757f024f47437600c019a09b74201/lua/plugins/mason-lsp.lua#L6-L8) in your config. `mason = false` specifies that the LSP server won't be installed via Mason, but it still expects to find a LSP server installed by you. You should add `enabled = false` if you want to disable `ruff_lsp` because the Python Extra will pull it in automatically.

**Comment by DevonPeroutky** [comment]
@dpetka2001 That worked! Thank you so much for looking into this.

If I'm understanding you correctly. The Python Extras by default enabled the `ruff-lsp`? And because I had `mason = false` (in an attempted to disable it), mason wouldn't install the lsp, despite it being expected/enabled?

Is there any documentation on the Python Extras? Where could I have looked to see what it enables and configures?

**Comment by dpetka2001** [comment]
Correct. You can see [here on the website](https://www.lazyvim.org/extras/lang/python) about the default Lazyvim configuration for Python. Plugins that are `optional` will only be enabled if you explicitly enable the corresponding Extras (for example nvim-dap and neotest).

**Comment by dpetka2001** [comment]
Also just for reference, you should never make any changes in your `~/.local/share/nvim` directory because you will probably cause problems when you're trying to update some plugin you changed.

**Comment by DevonPeroutky** [comment]
> Also just for reference, you should never make any changes in your `~/.local/share/nvim` directory because you will probably cause problems when you're trying to update some plugin you changed.

Yeah, I was just desperately poking to trying and figure out the configuration. But thanks again for resolving this so quickly!
