### ISSUE TITLE
feature: `checkhealth` for plugin config override

### ISSUE THREAD

**Issue by vlaw** [LazyVim/LazyVim#3823]
### Did you check the docs?

- [X] I have read all the LazyVim docs
- [X] This is not a request for a new or existing extra (see above)

### Is your feature request related to a problem? Please describe.

There are cases, such as below, that can be somewhat tedious, particularly when upgrading LazyVim:

1. `inc-rename.nvim` was already included in my configuration before LazyVim incorporated it in version 12.x.
2. I have overridden some configurations of `mini.indentscope`, which LazyVim relocated to extras in version 11.x.

It would be nice to get a warning triggered in `checkhealth` or through some other method that I am not aware of.

### Describe the solution you'd like

I suggest adding a property such as `override` to LazySpec, allowing users to explicitly indicate whether the configuration is intended to override LazyVim's preconfigured plugins.

1. When `override` is set to `true`, LazyVim will issue a warning if it removes any plugins that the user intends to override, potentially missing LazyVim's upstream configuration.
2. When `override` is set to `false`, LazyVim will issue a warning if it adds new plugins that the user may have already included, potentially causing a conflict.

### Describe alternatives you've considered

None

**Comment by dpetka2001** [comment]
When you update LazyVim, you get a pop-up window with the latest changes made. That includes breaking changes as well (such as `mini.indentscope` being moved to Extras) or just regular changes (`inc-rename` has been added to Extras). It's up to the user to correctly process the information. I don't think any additional warnings are necessary.
