### ISSUE TITLE
Setting recurse_submodules = true for git_files picker breaks <leader>ff 

### ISSUE THREAD

**Issue by mux** [LazyVim/LazyVim#3831]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0 (release)

### Operating system/version

Ubuntu 20.04

### Describe the bug

I use the following configuration in .config/nvim/lua/plugins/telescope.lua so that the git_files picker also looks for files in submodules. 

```
return {
  {
    "nvim-telescope/telescope.nvim",

    opts = {
      pickers = {
        find_files = { follow = true },
        git_files = { show_untracked = false, recurse_submodules = true },
      },
    },
  },
}
```
However, that breaks the \<leader\>ff picker when in a git repository, because it gets this error message from `git ls-files`:

```
[telescope.builtin.git_files]: Git does not support both --others and --recurse-submodules
```

This seems to indicate that the LazyVim picker that automatically selects find_files or git_files when in a git repository is somehow passing both options, which is surprising because the show_untracked option for telescope git_files is supposed to be false by default (show_untracked will map to use --others on the git command line).

As you can see above, I also tried to explicitly set the `show_untracked` option to false, but that does not fix the issue. Using `:Telescope find_files` works perfectly, and so does `:Telescope git_files`, so it seems to be coming from the automatic picker of LazyVim.

### Steps To Reproduce

1. Add the telescope.lua plugin configuation file as above
2. Run vim in a git repository
3. Attempt to use \<leader\>ff

### Expected Behavior

It should work just as `:Telescope find_files`.

**Comment by dpetka2001** [comment]
[LazyVim.pick](https://github.com/LazyVim/LazyVim/blob/44ed11c4f8867cdc887fdcba6a22938125a403ee/lua/lazyvim/util/pick.lua#L81-L84) automatically sets `show_untracked` to `true` if you don't pass explicit option via the keymap. So, either make a keymap for `LazyVim.pick("auto", { show_untracked = false })` or use `Telescope git_files` if you don't want that behavior.

**Comment by mux** [comment]
I see. Wouldn't it make more sense for LazyVim.pick to follow the options configured by the user for git_files though?

**Comment by dpetka2001** [comment]
Better wait for maintainer's input regarding that, since I'm just a simple user.

**Comment by mux** [comment]
Makes sense. I feel the situation is quite inconsistent right now, because LazyVim.pick will honor the user setting the recurse_submodules option to true, but won't do so for the show_untracked option.

**Comment by dpetka2001** [comment]
Can you try the following 
```lua
-- ~/.config/nvim/lua/plugins/core.lua
return {
  {
    "dpetka2001/LazyVim",
    branch = "fix/telescope-show_untracked",
  },
}
```
Then open Lazy UI, press `C` to check for updates and `U` to apply updates. Then restart Neovim and see if you observe the same behavior. If it is to your liking I can submit a PR.

**Comment by mux** [comment]
I just tried this and it did not fix the issue somehow? Something weird is going on because I added this to my telescope.lua configuration, and it also did not help:
```
keys = {
  { "<leader>ff", LazyVim.pick("auto", { show_untracked = false }), desc = "Find Files (Root Dir)" },
  { "<leader>fF", LazyVim.pick("auto", { root = false, show_untracked = false }), desc = "Find Files (cwd)" },
},
```

**Comment by dpetka2001** [comment]
Strange for me it didn't show any error with this change, whereas with your initial telescope config it showed the error that you mentioned. Do you get the same error or something different?

**Comment by mux** [comment]
Yeah something is off here. I get the exact same error. I have been double-checking to make sure I didn't do anything dumb but everything looks right. Updating with the fix plugin in core.lua worked for sure, I got a bunch of notifications because of file changes, and yet I have the exact same behavior as before. I am also curious to know if overriding the keymaps like I showed in my last message works for you? The reason this doesn't work might be the same reason why pulling in your plugin does not.

**Comment by mux** [comment]
Ah, I believe I understand what is happening. I had removed show_untracked = false from my telescope configuration because it shouldn't technically be required since Telescope's default is false. So, I do not know LUA well, or its definition of truthiness and comparisons, but I assume that a nil value doesn't compare to equal with false, so `opts.show_untracked ~= false` would end up evaluating to true. I wonder if that is why the LazyVim picker also sets show_untracked to true; that would be the case if the opts dict is actually coming from the telescope configuration, but I am just widly guessing here, I need to check the code.

**Comment by mux** [comment]
Following up on the above, trying a LUA expression evaluator online, I see that `nil ~= false` indeed evaluates to true. I am assuming that `opts.show_untracked` would be nil if the option is not set.

**Comment by dpetka2001** [comment]
Does it work correctly if you put back `show_untracked = false` in your Telescope spec?

**Comment by mux** [comment]
Yes it does. I just don't think that should be needed.

**Comment by dpetka2001** [comment]
It should because the default behavior of LazyVim is to set it to `true`. And in my fix I only check if the user has explicitly set in his Telescope spec `show_untracked = false`, otherwise if he hasn't I leave the default LazyVim value untouched.

**Comment by mux** [comment]
Yeah, that does makes sens if you are trying to preserve the current behavior of LazyVim. I am simply coming at this from another angle though, and saying that LazyVim should honor the Telescope defaults and the user overrides. I guess we will have to see what the maintainer thinks about it.

**Comment by mux** [comment]
In other words, I personally feel that the most sensible fix would be to simply remove this line:
```
      opts.show_untracked = opts.show_untracked ~= false
```

But then again, I do not know the motivation for this behavior in the first place.

**Comment by dpetka2001** [comment]
Yeah it's not my place to make decisions. I just tried to work around the problem for setting the value in the user configuration and LazyVim to respect that value and at the same time also respect the default LazyVim value if the user hasn't defined anything in his personal configuration.

**Comment by mux** [comment]
Yeah, and thank you for that! By the way, did you get around to trying the keymaps override like I posted earlier? I am confused as to why this isn't working.

**Comment by dpetka2001** [comment]
> and saying that LazyVim should honor the Telescope defaults and the user overrides

Most Neovim distros are quite biased depending on each maintainer's experience and personal preferences. LazyVim already has a lot of default options changed regarding other plugins as well. So, in my personal opinion, I don't agree with it having to respect the plugins' default options. It only has to respect the user's personal configuration settings and overrides. But that's just me and I don't expect everyone to agree with that take.

Regarding the keymaps, no I didn't try that. It's getting really late here, so I'm just gonna call it a night for today. Hopefully, the maintainer will shed more light to clear any questions you might have regarding LazyVim defaults.

**Comment by folke** [comment]
Leader ff automatically uses git files or find files. It works as it should. Closing.

**Comment by dpetka2001** [comment]
@mux I tried the following configuration with default LazyVim configuration and it seems to work (I don't get any error when I press `<leader>ff`)
```lua
  {
    "nvim-telescope/telescope.nvim",
    opts = {
      pickers = {
        find_files = { follow = true },
        git_files = { show_untracked = false, recurse_submodules = true },
      },
    },
    keys = {
      { "<leader>ff", LazyVim.pick("auto", { show_untracked = false }) },
    },
  },
```
Although I believe that setting `show_untracked = false` in `telescope.pickers.git_files` is kind of redundant since you already define it in the keymap itself.

**Comment by dpetka2001** [comment]
@folke Should I withdraw the PR I made, since the keymap works correctly? The PR is just for taking into account the option set in Telescope's spec in user configuration without the user having to define a different keymap or change the default ones. I don't know what the correct approach should be, should a user prefer such a behavior with `show_untracked = false, recurse_submodules = true` in Telescope spec.

**Comment by mux** [comment]
@folke Thank you for getting back to us. I understand that `<leader>ff` is supposed to automtically use git_files or find_files depending on the circumstances and that is just fine. The problem I am describing here is that a perfectly legitimate git_files configuration by the user (setting `recurse_submodules` to true) leads to `<leader>ff` not working anymore. This leads to two questions:
1. Why would LazyVim honor the `recurse_submodules` setting and yet ignore `show_untracked`, forcing it to true and making ` <leader>ff` impossible to use unless by remapping it completely? This is arguably a bug and the patch from @dpetka2001 fixes this.
2. Why is LazyVim forcing `show_untracked` to true in the first place when telescope defaults to false? I personally feel that it would make more sense to use the same defaults as telescope, although that is clearly debatable.

Even if LazyVim wants to continue forcing `show_untracked` to true for some reason, it should probably avoid getting in a situation where the picker just doesn't work anymore, by not setting `show_untracked` to true when `recurse_submodules` is.

@dpetka2001 You are correct - the keymap setting actually fixes `<leader>ff`, what I was observing is that selecting `Find File` in the menu after starting nvim without parameters shows the same problem and error message. I have no idea why would `Find File` in the menu would behave differently from `<leader>ff` but that is apparently the case.

**Comment by dpetka2001** [comment]
@mux Yes on the dashboard menu it wouldn't work. That's because when we define a keymap we only pass the options we specify to that keymap alone. All other keymaps would behave with LazyVim defaults and that's what you observe I believe. If my PR gets accepted, I believe the user won't have to change all possible keymaps. He will just have to define in the Telescope spec `show_untracked = false` to override the default LazyVim behavior and that's all.

Hopefully the maintainer will accept my PR or maybe he will come up with an even better solution than mine, since my knowledge is quite limited if I may say so.
