### ISSUE TITLE
Can't use skim with fzf-lua

### ISSUE THREAD

**Issue by guzman109** [LazyVim/LazyVim#3838]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

latest

### Operating system/version

Liniux

### Describe the bug

Can't use skim with fzf-lua unless I enter `lua require"fzf-lua".setup({"skim",winopts={preview={default="bat"}}})`

### Steps To Reproduce

  {
    "ibhagwan/fzf-lua",
    require("fzf-lua").setup({ "skim", winopts = { preview = { default = "bat" } } }),
     defaults = require("fzf-lua.profiles.skim"),
     winopts = {
       preview = {
         default = "bat",
       },
     },
  },

### Expected Behavior

fzf-lua to work with skim

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
That is not a correct lazy spec

**Comment by guzman109** [comment]
@folke 
My apologies, I tried to follow the configuration with is the Lazyvim website. Could you help me to have it work then?
I changed it to this.
```
{
    "ibhagwan/fzf-lua",
    opts = {
      defaults = require("fzf-lua.profiles.skim"),
      winopts = {
        preview = {
          default = "bat",
        },
      },
    },
  },

```
Pop up shows this time but closes immediately with this error
`fzf error 2: error: Found argument '--no-scrollbar' which wasn't expected, or isn't valid in this context`

**Comment by dpetka2001** [comment]
Try to add 
```lua
fzf_opts = {
  ["--no-scrollbar"] = false,
},
```

**Comment by guzman109** [comment]
@dpetka2001 

Thank you, I was able to figure it out and that's exactly what I ended updoing.

```(lua)
  {
    "ibhagwan/fzf-lua",
    opts = {
      defaults = require("fzf-lua.profiles.skim"),
      winopts = {
        preview = {
          default = "bat",
          scrollbar = "false",
        },
      },
      fzf_opts = {
        ["--no-scrollbar"] = false,
      },
      actions = {
        ["default"] = actions.file_edit,
      },
    },
  },
```
