### ISSUE TITLE
bug: vim.g.bigfile_size not loaded before use since 12.20.0

### ISSUE THREAD

**Issue by relf108** [LazyVim/LazyVim#3840]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.11.0-dev-313+gfc9b70826-Homebrew Build type: Release LuaJIT 2.1.1716656478

### Operating system/version

MacOS 14.5 (23F79) and Nixos 24.05

### Describe the bug

Since the "bigfile" type was added in release 12.20.0, when opening a file and determining filetype the following error is thrown due to `lua/lazyvim/config/autocmds.lua` being loaded before `lua/lazyvim/config/options.lua`. 

```
Error executing lua callback: .../share/nvim/lazy/LazyVim/lua/lazyvim/config/autocmds.lua:125: attempt to compare nil with number
stack traceback:
	.../share/nvim/lazy/LazyVim/lua/lazyvim/config/autocmds.lua:125: in function <.../share/nvim/lazy/LazyVim/lua/lazyvim/config/autocmds.lua:121>
	vim/filetype.lua: in function ''
	vim/filetype.lua: in function 'match'
	...llar/neovim/HEAD-fc9b708/share/nvim/runtime/filetype.lua:14: in function <...llar/neovim/HEAD-fc9b708/share/nvim/runtime/filetype.lua:10>
```
The "nil" value in this case being `vim.g.bigfile_size` from `options.lua`. I've created a quick and dirty fix locally but didn't feel confident enough in my understanding of your caching code to raise a PR with a proper solution (sorry!) 

My fix is as follows and hopefully a better lua programmer than me can suggest something that will work in the long term.
add to top of `autocmds.lua`
```lua
if vim.g.bigfile_size == nil then
  vim.g.bigfile_size = 1024 * 1024 * 1.5 -- 1.5 MB
end
```

### Steps To Reproduce

1. Update to V12.20.0
2. Attempt to determine a filetype of lua file (`:e`) 

### Expected Behavior

`:set filetype` returns "filetype=lua" and no nil comparison error is thrown.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
Could you give a link to your dotfiles on Github?

**Comment by folke** [comment]
`options.lua` should always load before `autocmds`, so no idea how you get that error

**Comment by dpetka2001** [comment]
I asked a link to OP's github dotfiles, because all I could find was [this](https://github.com/relf108/nvimrc), which doesn't seem to be a LazyVim configuration. It seems more like OP tried to incorporate LazyVim into his own configuration. But maybe I'm wrong and the OP just doesn't have his dotfiles available on Github.

**Comment by folke** [comment]
Yes, look like it.
What's up with all these people posting issues that have some frankenstein LazyVim setup. Pretty annoying...
