### ISSUE TITLE
bug: No a editor command: VenvSelect

### ISSUE THREAD

**Issue by Guan9Wu** [LazyVim/LazyVim#3841]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Archlinux x64

### Describe the bug

Choose python environment by command `:VenvSelect` in a python file, but it can't works. I check the installed plugins, there is `venv-selector.nvim` plugin be installed, but it isn't loaded. The detail as following screenshots:
![Screenshot_2024-06-28-16-11-08](https://github.com/LazyVim/LazyVim/assets/38772075/638a4785-750a-4b0a-9f4e-179932c394fa)
![Screenshot_2024-06-28-16-11-28](https://github.com/LazyVim/LazyVim/assets/38772075/c32c0ecc-4c71-4f87-acbc-a952f75c84fd)

### Steps To Reproduce

1. nvim test.py, then key some python codes.
2. `:VenvSelect

### Expected Behavior

I can select my python virtual environment.

### Repro

```Lua
Just use default Lazyvim's configurations.
```

**Comment by dpetka2001** [comment]
`venv-selector.nvim` is at the bottom disabled. You're probably using the `fzf` Extra. `venv-selector` currently doesn't support fzf-lua at the moment and it's only enabled when Telescope is also enabled. So, if you want `venv-selector` then use Telescope instead of fzf-lua. There's an open issue at venv-selector to support more pickers other than Telescope and it seems that something is at works, but until they implement something on their side you can only use it with Telescope together and not fzf-lua.

**Comment by Guan9Wu** [comment]
Yeah, thanks for your reply.



Sent&nbsp;from&nbsp;my&nbsp;iPhone


------------------ Original ------------------
From: Iordanis Petkakis ***@***.***&gt;
Date: Fri, Jun 28, 2024 4:35 PM
To: LazyVim/LazyVim ***@***.***&gt;
Cc: Guang ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [LazyVim/LazyVim] bug: No a editor command: VenvSelect (Issue#3841)





 
venv-selector.nvim is at the bottom disabled. You're probably using the fzf Extra. venv-selector currently doesn't support fzf-lua at the moment and it's only enabled when Telescope is also enabled. So, if you want venv-selector then use Telescope instead of fzf-lua. There's an open issue at venv-selector to support more pickers other than Telescope and it seems that something is at works, but until they implement something on their side you can only use it with Telescope together and not fzf-lua.
