### ISSUE TITLE
bug: Markdown auto-format ignores .editorconfig

### ISSUE THREAD

**Issue by awilkins** [LazyVim/LazyVim#3845]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0 (Ubuntu snap rev 2823)

### Operating system/version

Ubuntu 20.04

### Describe the bug

Editorconfig indent setting is ignored by the (new?) autoformatting on save in `lang.markdown`.

Works OK for the Markdown lib used by the markdown preview, but this is not universal - many Markdown libs [don't cope well with 2-space indents](https://docs.newrelic.com/docs/style-guide/structure/styleguide-markup-indentation/#two-space)

e.g. Slack : Nope, Discord : OK

for
```markdown
- [ ] Thing
  - Review new submission
    - Double Nested
```

![image](https://github.com/LazyVim/LazyVim/assets/368399/81907161-0d60-421c-bb2d-e1949abd2269)

And for GH flavoured :

- [ ] Thing
  - Review new submission
    - Double Nested

.. whereas four-spaces works properly in everything I've tried.

### Steps To Reproduce

1. Enable `lang.markdown`
1. Create an `.editorconfig` with a section
```toml
[*.md]
indent_size = 4
```
3. `nvim test.md`
1. Add text
    - Note that the tabstop is set properly - tab adds 4 spaces
```
- Nested List
    - Four spaces!
        - Four more!
```
5. `<esc> :w`
6. File is reformatted to
```
- Nested List
  - Four spaces!
    - Four more!
```

### Expected Behavior

Auto-format respects editorconfig indent level

**Comment by dpetka2001** [comment]
This has to do with formatter `markdownlint` that `conform.nvim` uses. Does the formatter even support `.editorconfig` itself? It doesn't seem like it. See https://github.com/DavidAnson/markdownlint-cli2/issues/179, https://github.com/DavidAnson/markdownlint/issues/1114 and https://github.com/DavidAnson/markdownlint/issues/303. If you want such a feature make your case in the appropriate formatter's repo, but from what I've seen from a quick skim through the repo, the maintainer himself has declined such a feature stating that such configuration can be achieved via `markdownlint.yml` itself. 

I don't believe this has anything to do with LazyVim itself.
