### ISSUE TITLE
bug: lazyvim.util.foldexpr() cause unexpected wakeup of treesitter

### ISSUE THREAD

**Issue by zhyzky** [LazyVim/LazyVim#3849]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

ubuntu 22.04

### Describe the bug

When visit a file that enabled tresitter, like test.cpp, execute following commang
1. `set ft=xxd`
2. `%!xxd`
Then the lazyvim.util.foldexpr will be invoked, inside which there is a line
`local ok = pcall(vim.treesitter.get_parser, buf)`
that would cause an error like "no parser for "xxd""

Just wonder why not set foldexpr to nvim_treesitter#foldexpr()?

### Steps To Reproduce

1. visit a file, say hello.cpp
2. execute command `set ft=xxd`
3. execute `%!xxd`

### Expected Behavior

No error msg popup

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- that's end
```

**Comment by folke** [comment]
If you'd read that whole function, you'd see this is actually a **huge** performance improvement over the default implementation when no parser exists for the filetype.

The default Neovim impl will run `local parser = vim.F.npcall(ts.get_parser, bufnr)` for **every** line, even when no parser is available.

The **LazyVim** fix, will do that at most once per tick per file, not potentially 100s of times per tick per file.

**Comment by zhyzky** [comment]
> If you'd read that whole function, you'd see this is actually a **huge** performance improvement over the default implementation when no parser exists for the filetype.
> 
> The default Neovim impl will run `local parser = vim.F.npcall(ts.get_parser, bufnr)` for **every** line, even when no parser is available.
> 
> The **LazyVim** fix, will do that at most once per tick per file, not potentially 100s of times per tick per file.

What concerns is the error msg invoked by `vim.treesitter.get_parser`
from nvim-treesitter, there's a function
```
function M.has_parser(lang)
  lang = lang or M.get_buf_lang(api.nvim_get_current_buf())

  if not lang or #lang == 0 then
    return false
  end
  -- HACK: nvim internal API
  if vim._ts_has_language(lang) then
    return true
  end
  return #parser_files[lang] > 0
end
```
where
 `vim._ts_has_language(lang)` 
seems not raise the error for no parser found

**Comment by folke** [comment]
I don't really get how that `pcall` could raise an error.

The regular `foldexpr` does the same thing

![image](https://github.com/LazyVim/LazyVim/assets/292349/2a1d09fc-4ed9-49ec-9743-6c55fd21f36f)

**Comment by zhyzky** [comment]
Neither do i. Seems not using `pcall` still invoke the error.

**Comment by dpetka2001** [comment]
I just tried with `vim.opt.foldexpr = ""` (which disables the LazyVim `foldexpr`) and followed the steps above. The error still happens and it seems to come from Neovim builtin treesitter itself
```
   Error  11:29:15 AM msg_show.lua_error Error executing vim.schedule lua callback: ...nux64/share/nvim/runtime/lua/vim/treesitter/language.lua:107: no parser for 'xxd' language, see :help treesitter-parsers
stack traceback:
	[C]: in function 'error'
	...nux64/share/nvim/runtime/lua/vim/treesitter/language.lua:107: in function 'add'
	...4/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:111: in function 'new'
	...y/nvim-linux64/share/nvim/runtime/lua/vim/treesitter.lua:41: in function '_create_parser'
	...y/nvim-linux64/share/nvim/runtime/lua/vim/treesitter.lua:108: in function 'get_parser'
	...-linux64/share/nvim/runtime/lua/vim/treesitter/_fold.lua:117: in function 'compute_folds_levels'
	...-linux64/share/nvim/runtime/lua/vim/treesitter/_fold.lua:376: in function 'fn'
	...-linux64/share/nvim/runtime/lua/vim/treesitter/_fold.lua:289: in function <...-linux64/share/nvim/runtime/lua/vim/treesitter/_fold.lua:285>
```
So, this doesn't seem to have anything to do with LazyVim's `foldexpr` itself.

**Comment by folke** [comment]
exactly
