### ISSUE TITLE
bug: lazygit Failed to get **lazygit** config directory

### ISSUE THREAD

**Issue by gj86** [LazyVim/LazyVim#3851]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.11.0-dev+315-g46187117c

### Operating system/version

Fedora 40

### Describe the bug

After updating `lazy.nvim` the following error occur on launching `lazygit` with keymap `<leader>gg`

```lua
lazygit Failed to get **lazygit** config directory.
Will not apply **lazygit** config.

# Error:
~/.repro/plugins/lazy.nvim/lua/lazy/async.lua:157: In coroutine without async context
```

### Steps To Reproduce

1. Update everything to latest version.
2. Start `LazyVim`
3. Navigate to any git project dir and open any file.
4. Try to start `LazyGit` with the default keymap provided in `LazyVim`

### Expected Behavior

LazyGit should start without any error.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  {
    'LazyVim/LazyVim',
    import = 'lazyvim.plugins',
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Fixed by https://github.com/folke/lazy.nvim/commit/3513227a9a41c8e6366e1719f4cefbe891ca73d2
