### ISSUE TITLE
Rust suggestions look aesthetically bad, unreadable

### ISSUE THREAD

**Issue by osenvosem** [LazyVim/LazyVim#3855]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0

### Operating system/version

MacOS 13.6

### Describe the bug

Completion info for the Rust language look wrong compared to other languages. This happens in both cases: with the Rust Extra and without it, with rust-analyzer only. Completion window is too large and Info window is skewed. Typescript and Lua for example are ok.

<img width="1791" alt="Screenshot 2024-06-29 at 14 49 18" src="https://github.com/LazyVim/LazyVim/assets/6762673/19c726bd-a45e-4ef7-95a3-4d876b913377">

### Steps To Reproduce

Install rust-analyzer and try completion for `random` for instance.

### Expected Behavior

Readable, good aesthetics. LunarVim for reference
<img width="1249" alt="Screenshot 2024-06-29 at 15 38 41" src="https://github.com/LazyVim/LazyVim/assets/6762673/87da9749-f18b-41d3-a35d-1aaabf99d9e7">

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Feel free to provide a PR with a more sane cmp width setting.
