### ISSUE TITLE
feature: option for the location of lazyvim.json

### ISSUE THREAD

**Issue by Aylur** [LazyVim/LazyVim#3856]
### Did you check the docs?

- [X] I have read all the LazyVim docs
- [X] This is not a request for a new or existing extra (see above)

### Is your feature request related to a problem? Please describe.

When the config is managed by home-manager (nix) the directory is read-only which makes it impossible to make use of `LazyExtras` command, since it can't write to lazyvim.json. Another issue is the news message will always popup #1723

### Describe the solution you'd like

The most simple solution imo is to let us configure the location of `lazyvim.json` in `lazy.lua`, so we could move it to `~/.local/state` or `~/.cache` to make it writeable.
Otherwise we need weird workarounds that goes against nix and defeats its purpose.

### Describe alternatives you've considered

not using nix

### Additional context

I want to make use of `:LazyExtras` because I want an extra to be enabled on one of my machines while not the other, but I want to keep using the same config on all of my machines without declaring extra config in nix or lua

**Comment by folke** [comment]
The new docs are still building, but here's the docs for setting a custom path for `lazyvim.json`:

**LazyVim** stores some configuration like the enabled **extras** in the `lazyvim.json` file.

This can be configured with `vim.g.lazyvim_json`, but you need to do this **before**
loading `lazy.nvim`, so **not** in your `options.lua`.

```lua title="lua/init.lua"
-- lua/init.lua
vim.g.lazyvim_json = vim.fn.stdpath("config") .. "/lazyvim.json"
```
