### ISSUE TITLE
bug: vtsls => enableProjectDiagnostics (tsserver experimental) keeps redirecting to a json file in project dir

### ISSUE THREAD

**Issue by AbhinavRobinson** [LazyVim/LazyVim#3857]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

MacOS 15.0

### Describe the bug

When I set enableProjectDiagnostics = true, opening my project and going to TS file automatically opens a JSON file in the project dir without any inputs.

### Steps To Reproduce

1. Default Lazyvim setup + typescript
2. Add this plugin customization
```lua
return {
  "neovim/nvim-lspconfig",
  opts = {
    servers = {
      vtsls = {
        settings = {
          typescript = {
            tsserver = {
              experimental = {
                enableProjectDiagnostics = true,
              },
            },
          },
        },
      },
    },
  },
}
```
3. Go to a TS project with a JSON file in the dir as well.

### Expected Behavior

Have project wide diagnostics enabled, but no files randomly opening.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
How is this a LazyVim issue? Closing
