### ISSUE TITLE
Document core plugins

### ISSUE THREAD

**Issue by EvanCarroll** [LazyVim/LazyVim#3859]
### Did you check the docs?

- [X] I have read all the LazyVim docs
- [X] This is not a request for a new or existing extra (see above)

### Is your feature request related to a problem? Please describe.

I installed Lazy.nvim, and I couldn't figure out anything it came with or what it was doing, I had to look into lazy-lock.json to learn what it was.

The docs say only this,

> 📦 Comes with a wealth of plugins pre-configured and ready to use

That makes it very hard for people using it to investigate what kind of value it offers. It may offer them a ton of value, and they'd never know unless they audited it like I did.

### Describe the solution you'd like

Just a table of everything in lazy-lock.json (core plugins) with a brief summary of what they do. It would be really nice if they were catagorized too. For example **language-specific**, **functionality improvements**, **foundational** (like plenary)

### Describe alternatives you've considered

just a doc request

**Comment by dpetka2001** [comment]
I'm sure I can see a small concise description about quite a few plugins (not all, but some are self-explanatory). If the user requires more information, he should read the plugin's github README to see what it's all about. The LazyVim website is not meant to be a consolidation of plugins' docs in my personal opinion as a simple user like you.

Of course, I don't make any decisions and the maintainer is the one you're making your case with. I'm just expressing my personal opinion.

**Comment by folke** [comment]
Therer's a whole website with all the info about every plugin included linking to every plugin's readme.

I'm sorry, but this is more than enough.

Just read.
