### ISSUE TITLE
feature: Integrate YankAssassin plugin

### ISSUE THREAD

**Issue by zim0369** [LazyVim/LazyVim#386]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Yanking multiple lines in vim takes you to that line which is mostly inconvenient.

### Describe the solution you'd like

[Yank Assassin](https://github.com/svban/YankAssassin.vim) preserves cursor position & since we have post yank highlighting so the user knows what's exactly copied.

### Describe alternatives you've considered

-

### Additional context

-

**Comment by folke** [comment]
I don't think this should be a default LazyVim plugin, but you can of course easily add it to your own config
