### ISSUE TITLE
bug: treesitter context doesn't work with prisma file

### ISSUE THREAD

**Issue by shyamayadav154** [LazyVim/LazyVim#3864]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10

### Operating system/version

MacOS 14.3.1

### Describe the bug

prisma file doesn't show model context at top even when lsp and tresitter, tresitter context and prima lsp is installed using LazyExtra

### Steps To Reproduce

1. Install the default lazy
2. install the prisma lsp, tressiter and tresitter context from LazyExtra
3. go to any prisma schema file check if prisma model stickes to the top

### Expected Behavior

prisma model name should stickes to the top when scrolled and the model name is not in screen but cursor is inside the model curly bracket

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
feature request for nvim-treesitter-context?

**Comment by shyamayadav154** [comment]
treesitter-context already supports prisma,I think I didn't report the bug correctly the issue is that prisma model name doesn't stick to the top, earlier it used to stick at the top in lazyvim if treesitter-context and prisma lsp is installed now it doesn't stick at the top
