### ISSUE TITLE
bug: AngularLS crashes with `ngtypecheck not found` after saving

### ISSUE THREAD

**Issue by l3d00m** [LazyVim/LazyVim#3879]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0 LuaJIT 2.1.1713484068

### Operating system/version

Windows Version 10.0.19045 Build 19045

### Describe the bug

The angular language server in nvim crashes after saving any `.component.ts` file. It crashes with `Program does not contain "PROJECT_PATH/apps/org/src/app/app.component.ngtypecheck.ts"`

See also https://github.com/angular/vscode-ng-language-service/issues/2043 (maintainers suggested that it was the wrong repo bc it's not reproducible in VSCode)

### Steps To Reproduce

1. Setup a clean new angular v18 project using `npm install -g @angular/cli` followed by `ng new my-app` with the default settings (just press enter).
2. Start nvim with the config below (stock + [angular LSP extra](https://www.lazyvim.org/extras/lang/angular) enabled)
3. Open `app.component.ts `. 
4. Save the file a few times.
5. After a few saves (at most 3 for me), the LSP crashes with `Client angularls quit with exit code 1 and signal 0. Check log for errors: C:\Users\myuser\AppData\Local\nvim-data/lsp.log` and in the log it says  `Program does not contain "c:/Users/myuser/IdeaProjects/projects/my-app/org/apps/org/src/app/app.component.ngtypecheck.ts"`

### Expected Behavior

Angular LS should not crash

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  { import = "lazyvim.plugins.extras.lang.angular" },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
How is this a LazyVim bug?

**Comment by l3d00m** [comment]
Sorry! I'm still new to this whole ecosystem. Could you point me to a direction on where to file the bug? The angularls maintainers also said they are not responsible since it doesn't occur in with the VSCode integration, which the language server is intended for.
