### ISSUE TITLE
bug:  <leader>gB (git browse) doesn't handle correctly azure devops remotes

### ISSUE THREAD

**Issue by med8bra** [LazyVim/LazyVim#3886]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10

### Operating system/version

NixOS

### Describe the bug

Git repository url isn't computed correctly for azure devops git remote when using the builtin keymap `<leader>gB`.

I checked [vim-fugitive](https://github.com/tpope/vim-fugitive), and they seem to offload this task to other plugins to implement the logic needed for the mapping (git remote url to repo website url). Example [fugitive-azure-devops.vim](https://github.com/cedarbaum/fugitive-azure-devops.vim)

Also I checked [neogit](https://github.com/NeogitOrg/neogit), and they have a simpler solution using templates; they use this for open pull request, but it can be used also for browse branch.
https://github.com/NeogitOrg/neogit/blob/66b29453df7050543a51986620f8961a79a13fcc/lua/neogit/config.lua#L323-L327
```lua
    git_services = {
      ["github.com"] = "https://github.com/${owner}/${repository}/compare/${branch_name}?expand=1",
      ["bitbucket.org"] = "https://bitbucket.org/${owner}/${repository}/pull-requests/new?source=${branch_name}&t=1",
      ["gitlab.com"] = "https://gitlab.com/${owner}/${repository}/merge_requests/new?merge_request[source_branch]=${branch_name}",
      ["azure.com"] = "https://dev.azure.com/${owner}/_git/${repository}/pullrequestcreate?sourceRef=${branch_name}&targetRef=${target}",
```

### Steps To Reproduce

On an azure devops git repo, in normal mode click `<leader>gB` leads to 404 page on your browser

### Expected Behavior

The correct repo url should be computed depending on the git remote provider

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by med8bra** [comment]
I would love to contribute with a fix for this one, and I would go with neogit's approach.

**Comment by folke** [comment]
Feel free to create a PR!

**Comment by dotfrag** [comment]
@med8bra, if you do decide to create a fix, could you please make this customisable to the user? I use several hosted services that I would like to add custom urls to. Thanks either way!

**Comment by folke** [comment]
@dotfrag can you give some exmaples of remote -> url mappings for those providers?
I can then add them to the tests.

The new impl should be pretty generic, but we can always add custom patterns when needed

**Comment by dotfrag** [comment]
> @dotfrag can you give some exmaples of remote -> url mappings for those providers? I can then add them to the tests.
> 
> The new impl should be pretty generic, but we can always add custom patterns when needed

With the refactoring, I believe the case is well covered.

https://about.gitea.com/ and https://forgejo.org/ (fork for gitea, so same url scheme)

example:

`gitea.example.com` -> `https://gitea.albourne.com/owner/repo(.git)`

I'm guessing now that there are no host mappings, we can't resolve DNS aliases in a controlled network, right? i.e. if `gitea` resolved to `gitea.example.com`, then a repo's remote would be `gitea:owner/repo.git`. Just wondering, not a big deal! I could clone the repos with the full url and it would work.

**Comment by dotfrag** [comment]
> @dotfrag can you give some exmaples of remote -> url mappings for those providers? I can then add them to the tests.
> 
> The new impl should be pretty generic, but we can always add custom patterns when needed

With the refactoring, I believe the case is well covered.

https://about.gitea.com/ and https://forgejo.org/ (fork for gitea, so same url scheme)

example:

`gitea.example.com` -> `https://gitea.example.com/owner/repo(.git)`

I'm guessing now that there are no host mappings, we can't resolve DNS aliases in a controlled network, right? i.e. if `gitea` resolved to `gitea.example.com`, then a repo's remote would be `gitea:owner/repo.git`. Just wondering, not a big deal! I could clone the repos with the full url and it would work.

PS. same goes for gitlab hosted.

**Comment by folke** [comment]
Should probably also work? url would be `https://gitea/owner/repo`

**Comment by dotfrag** [comment]
I'm guessing it will, consider it working. If it doesn't I'll post back when I get the chance to test it.

**Comment by dotfrag** [comment]
@folke 

Repo with remote `gitea:owner/repo` doesn't work, I had good luck with:

```lua
{ "^(gitea):(.*)", "https://%1/%2" },
```

or more generic

```lua
{ "^(%w+):(.*)", "https://%1/%2" },
```

**Comment by folke** [comment]
You can use `./scripts/tests`

**Comment by dotfrag** [comment]
That was too easy :)

I haven't been able to get all tests to pass, I believe my ssh config is also getting in the way. It's masking the user.

This passes, but I don't like the pattern:

```lua
  { "^(g%w+):(.*)"  , "https://%1/%2" },
```

```lua
....
  ["https://gitea.example.com/owner/repo"] = "https://gitea.example.com/owner/repo",
  ["https://gitlab.example.com/owner/repo"]  = "https://gitlab.example.com/owner/repo",
  ["gitea:owner/repo"] = "https://gitea/owner/repo",
  ["gitlab:owner/repo"] = "https://gitlab/owner/repo",
```
