### ISSUE TITLE
Double rust_analyzer clients attached to buffer

### ISSUE THREAD

**Issue by amrro** [LazyVim/LazyVim#3887]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

MacOs 14.5

### Describe the bug

Out of the box two rust_analyzer clients attached to the buffer.

```
Language client log: /Users/amrro/.local/state/nvim/lsp.log
 Detected filetype:   rust
 
 2 client(s) attached to this buffer: 
 
 Client: rust-analyzer (id: 1, bufnr: [2, 174])
 	filetypes:       rust
 	autostart:       false
 	root directory:  /Users/amrro/rust_project
 	cmd:             rust-analyzer --log-file /var/folders/j3/4zkpzbtx2k9cyj841vhxjynw0000gn/T/nvim.amrro/YHCvud/0-rust-analyzer.log
 
 Client: rust_analyzer (id: 2, bufnr: [2, 174])
 	filetypes:       rust
 	autostart:       true
 	root directory:  /Users/amrro/rust_project
 	cmd:             /Users/amrro/.local/share/nvim/mason/bin/rust-analyzer
 ```

From the rustaceanvim's docs: 
> This plugin supports automatically detecting mason.nvim codelldb installations,
but not rust-analyzer.
The main reason for this choice is that it mason.nvim installations of rust-analyzer
will most likely have been built with a different toolchain than your project,
leading to inconsistencies and possibly subtle bugs.

and rustaceanvim's [docs](https://github.com/mrcjkb/rustaceanvim/blob/af4de6a35d128ce71c75a9a7846bf089aea76f50/doc/mason.txt#L40-L53) suggests to add the following config to LazyVim: 
```lua
  {
    'neovim/nvim-lspconfig',
    opts = {
      setup = {
        rust_analyzer = function()
          return true 
        end,
      },
    },
  }
```
 

### Steps To Reproduce

1. Open any rust based project. 
2. Open any rust file.
3. Get `:LspInfo` or `<leader>cl`.

### Expected Behavior

To have a single rust_analyzer client running and configured from the rustaceanvim plugin

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
Lazyvim doesn't install `rust-analyzer` via Mason. You must have done so yourself. Uninstall `rust-analyzer` from Mason.

**Comment by amrro** [comment]
Removing rust_analyzer from mason and installing it through: `rustup component add rust-analyzer` fixed it.
Thanks!
