### ISSUE TITLE
bug: telescope lsp keys are not overwritable

### ISSUE THREAD

**Issue by kapral18** [LazyVim/LazyVim#3889]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

MacOs 14.5

### Describe the bug

According to https://www.lazyvim.org/plugins/lsp#%EF%B8%8F-customizing-lsp-keymaps
I can remap lsp keys using lazyvim api to get lsp keymaps

I am trying to setup glance.nvim for my lsp keymaps

```lua
  {
    "dnlhc/glance.nvim",
    opts = function()
      local keys = require("lazyvim.plugins.lsp.keymaps").get()

      keys[#keys + 1] = { "gd", false }
      keys[#keys + 1] = { "gr", false }
      keys[#keys + 1] = { "gy", false }
      keys[#keys + 1] = { "gI", false }

      return {
        border = {
          enable = true,
        },
        use_trouble_qf = true,
      }
    end,
    cmd = { "Glance" },
    keys = {
      { "gd", "<CMD>Glance definitions<CR>", desc = "Goto Definition" },
      { "gr", "<CMD>Glance references<CR>", desc = "References" },
      { "gy", "<CMD>Glance type_definitions<CR>", desc = "Goto t[y]pe definitions" },
      { "gI", "<CMD>Glance implementations<CR>", desc = "Goto implementations" },
    },
  },
```

But this gets overwritten by telescope extras that is by default enabled

https://github.com/LazyVim/LazyVim/blob/00f53315b59fd35ef05ea74e66423944a2012974/lua/lazyvim/plugins/extras/editor/telescope.lua#L267

So I am stuck

### Steps To Reproduce

-

### Expected Behavior

Should allow overwriting lsp keys from builtin extras

**Comment by dpetka2001** [comment]
The docs say to put those commands in `nvim-lspconfig` spec. Not `glance.nvim` spec. There's a difference.

**Comment by folke** [comment]
You indeed need to disable those keymaps in the lspconfig spec.
Your custom plugins are parsed after all LazyVim specs, so the telescope one should not override your specs.

**Comment by kapral18** [comment]
my bad, thanks
