### ISSUE TITLE
bug: nvim-cmp doesn't show auto import source modules anymore

### ISSUE THREAD

**Issue by flupke** [LazyVim/LazyVim#3893]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0

### Operating system/version

Manjaro

### Describe the bug

I don't see the source module in nvim-cmp auto imports anymore:
![image](https://github.com/LazyVim/LazyVim/assets/188962/f56ee7a9-7948-4cfa-a069-74297bb37e9e)

### Steps To Reproduce

1. Open a rust file in a project with dependencies (`Result` is often aliased)
2. Type `Result` and wait for auto import suggestions
3. You don't see the source module like before

### Expected Behavior

We should see the source module:
![image](https://github.com/LazyVim/LazyVim/assets/188962/7e1de888-3047-4c30-9043-b0a2f1e0a282)

**Comment by folke** [comment]
You're running an old version of LazyVim...

**Comment by folke** [comment]
Just made a new release https://github.com/LazyVim/LazyVim/pull/3872

**Comment by flupke** [comment]
> You're running an old version of LazyVim...

How should I upgrade? (running U in lazyvim menu shows `LazyVim` as up-to-date)

**Comment by flupke** [comment]
Thanks, working now, is there something I missed about updating LazyVim?
