### ISSUE TITLE
bug: Unable to close the lazy interface when opening neo-tree.

### ISSUE THREAD

**Issue by wanlufun** [LazyVim/LazyVim#3898]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0

### Operating system/version

Rocky Linux 9.4 

### Describe the bug

When using LazyVim, if I open the lazy interface with the shortcut <leader>l and then try to open neo-tree with another shortcut, I am unable to close the lazy interface.

### Steps To Reproduce

1. Execute the nvim command to open the dashboard.
2. Enter l to open the lazy interface.
3. Then use <leader>e to open neo-tree.
4. At this point, you are unable to close the lazy interface except by completely exiting nvim.

### Expected Behavior

I want to close the lazy interface without exiting nvim.

It is possible to close it using `:bd <buf-id>`, but this method is not very user-friendly. I would like to know if it is possible to automatically close it when calling neo-tree.

**Comment by dpetka2001** [comment]
That's because the Lazy UI has lost focus when you open Neo-tree. Just `<c-w>w` until your cursor is back on Lazy UI and press `q` to close it. I don't understand how this is a bug.

**Comment by wanlufun** [comment]
> That's because the Lazy UI has lost focus when you open Neo-tree. Just `<c-w>w` until your cursor is back on Lazy UI and press `q` to close it. I don't understand how this is a bug.

Oh, yes, that was my question. Thank you for your help, I will close this issue.
