### ISSUE TITLE
feature: A way to disable auto-select in `nvim-cmp`

### ISSUE THREAD

**Issue by cifkao** [LazyVim/LazyVim#3912]
### Did you check the docs?

- [X] I have read all the LazyVim docs
- [X] This is not a request for a new or existing extra (see above)

### Is your feature request related to a problem? Please describe.

The auto-completion behavior hard-wired into LazyVim is that the first option is always auto-selected:
https://github.com/LazyVim/LazyVim/blob/c848cfddef6f4417b133382cae6fda49e8df990c/lua/lazyvim/plugins/coding.lua#L26

I was looking for a more "non-invasive" behavior where I have to explicitly select an option. This took me quite long to figure out because all solutions that came up online suggested setting `vim.opt.completeopt` or `nvim-cmp`'s `preselect` option or using `cmp.mapping.confirm({ select = false })`, neither of which seems to solve the issue on its own.

### Describe the solution you'd like

It would be great to make `auto_select` a LazyVim option that can be changed in the user config instead of having it hardcoded.

Additionally, I would disable the ghost-text feature when `auto_select` is false.

### Describe alternatives you've considered

It seems that something like this results in the behavior I was looking for:
```lua
  {
    "hrsh7th/nvim-cmp",
    ---@param opts cmp.ConfigSchema
    opts = function(_, opts)
      opts.preselect = cmp.PreselectMode.None
      opts.completion = { completeopt = "menu,menuone,preview,noinsert,noselect" }
      opts.experimental.ghost_text = false

      opts.mapping = vim.tbl_extend("force", opts.mapping, {
        ["<CR>"] = cmp.mapping.confirm({ select = false }),
      })
    end
  }
```
This could be added as a recipe in the docs.

**Comment by cifkao** [comment]
#301 is related.

**Comment by folke** [comment]
That's up to the user to change.

**Comment by cifkao** [comment]
@folke That's fair but it's non-trivial as it requires setting a combination of options. Why not add it as a recipe as also suggested [here](https://github.com/LazyVim/LazyVim/issues/301#issuecomment-1436042975)?

**Comment by yacoob** [comment]
I second the addition of an easy toggle; can't express how many combinations I've tried, as a person unfamiliar with neovim ecosystem to get this going :[

In other words: yes, user can toggle it. The toggle has an unusual shape, and the advice about flipping it suggests many ways of flipping it, most of them not working :D

**Comment by smarquez1** [comment]
Thanks everyone. Just created a PR to add this as a recipe based on [this comment](https://github.com/LazyVim/LazyVim/issues/301#issuecomment-1435725970).

https://github.com/LazyVim/lazyvim.github.io/pull/109
