### ISSUE TITLE
feature: split non-essential stuff from lazyvim.json

### ISSUE THREAD

**Issue by moetayuko** [LazyVim/LazyVim#3936]
### Did you check the docs?

- [X] I have read all the LazyVim docs
- [X] This is not a request for a new or existing extra (see above)

### Is your feature request related to a problem? Please describe.

I use git to manage and sync my dotfiles. The `news` and `version` are automatically updated on start so they vary on different machines. As a result, I have to manually git reset to avoid conflict before pulling neovim config.

### Describe the solution you'd like

Storing manual settings (e.g. `extras`) and automatically generated metadata (e.g. `news` and `version`) in different files so I can gitignore the latter.

### Describe alternatives you've considered

n/a

**Comment by folke** [comment]
no
