### ISSUE TITLE
bug: keys aren't mereged

### ISSUE THREAD

**Issue by TxHawks** [LazyVim/LazyVim#394]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0-dev-3761+ga0292b4e5-dirty

### Operating system/version

MacOS 13.2.1

### Describe the bug

When setting a `keys` list on a default plugin, the keys won't get merged but rather override the defined keys.

### Steps To Reproduce

1. Create `lua/plugins/telescope.lua`, which contains the following:
   ```lua
   return  {{
     "telescope.nvim",
     keys = {
       { "<leader>/", false },
       { "gd", false },
       { "gr", false },
       { "gt", false },
       { "gI", false },
     }
   }}
   ```
2. Reopen neovim. All Telescope keymaps are gone.

### Expected Behavior

My understanding of the docs is that `keys` should be merged, not overridden, so I'd expect the Telescope keymaps (e.g., `<Leader>Space`), which weren't disabled to still be active.

**Comment by folke** [comment]
Something really odd is going on here. Even without that keys prop all keys are gone. I'm looking into it.

**Comment by folke** [comment]
There was indeed a bug in lazy.nvim. Just fixed it
https://github.com/folke/lazy.nvim/commit/355312eb514b58b79e93753d46b2612a21949aa4

Will create a new release of lazy and LazyVim in a bit.

Thank you for reporting!!

**Comment by TxHawks** [comment]
Thanks for solving it so quickly!

**Comment by TxHawks** [comment]
Okay, so the original issue is resolved, but I'm having another one. What I want to do is use [DNLHC/glance.nvim](/DNLHC/glance.nvim) instead of Telescope to view definitions, references, etc.

Since `gd`, etc. open Telescope, I initially thought the keymappings are defined there, but after looking at [plugins/lsp/keymaps.lua](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/lsp/keymaps.lua#L15-L19) I realized that it's actually part of [neovim/nvim-lspconfig](neovim/nvim-lspconfig)'s config and tried to override it there, but to no effect. The keymappings don't change.

This is the spec file:
```lua
return {
  {
    "neovim/nvim-lspconfig",
    keys = {
      { "gd", false },
      { "gr", false },
      { "gt", false },
      { "gI", false },
    },
  },

  {
    "DNLHC/glance.nvim",
    keys = {
      { "gr", "<cmd>Glance references<cr>", desc = "Glance References" },
      { "<Leader>cr", "<cmd>Glance references<cr>", desc = "Glance References" },
      { "gd", "<cmd>Glance definitions<cr>", desc = "Glance Definitions" },
      { "<Leader>cD", "<cmd>Glance definitions<cr>", desc = "Glance Definitions" },
      { "gt", "<cmd>Glance type_definitions<cr>", desc = "Glance Type Definitions" },
      { "<Leader>ct", "<cmd>Glance type_definitions<cr>", desc = "Glance Type Definitions" },
      { "<Leader>ci", "<cmd>Glance implementations<cr>", desc = "Glance Implementations" },
      { "gI", "<cmd>Glance implementations<cr>", desc = "Glance Implementations" },
    },
    -- I tried with and without this
    -- dependencies = {
    --   "neovim/nvim-lspconfig",
    -- },
  },
}
```

Am I misunderstanding something?

**Comment by folke** [comment]
https://www.lazyvim.org/plugins/lsp#%EF%B8%8F-customizing-lsp-keymaps

**Comment by TxHawks** [comment]
Thanks! Don't know how I missed that
