### ISSUE TITLE
bug: can't disable "folke/trouble.nvim".

### ISSUE THREAD

**Issue by matta** [LazyVim/LazyVim#3944]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0 Build type: Release LuaJIT 2.1.1716656478

### Operating system/version

Debian Buster

### Describe the bug

Disabling trouble causes some parts of LazyVim to throw errors.

In places, LazyVim assume that `vim.g.trouble_lualine = true` implies that trouble is available and enabled. Since `vim.g.trouble_lualine` defaults `true`, disabling trouble causes issues.

```text
Failed to run `config` for lualine.nvim

...local/share/nvim/lazy/LazyVim/lua/lazyvim/plugins/ui.lua:202: module 'trouble' not found:
^Ino field package.preload['trouble']
cache_loader: module trouble not found
cache_loader_lib: module trouble not found
^Ino file './trouble.lua'
^Ino file '/home/linuxbrew/.linuxbrew/share/luajit-2.1/trouble.lua'
^Ino file '/usr/local/share/lua/5.1/trouble.lua'
^Ino file '/usr/local/share/lua/5.1/trouble/init.lua'
^Ino file '/home/linuxbrew/.linuxbrew/share/lua/5.1/trouble.lua'
^Ino file '/home/linuxbrew/.linuxbrew/share/lua/5.1/trouble/init.lua'
^Ino file './trouble.so'
^Ino file '/usr/local/lib/lua/5.1/trouble.so'
^Ino file '/home/linuxbrew/.linuxbrew/lib/lua/5.1/trouble.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'

# stacktrace:
  - /LazyVim/lua/lazyvim/plugins/ui.lua:202 _in_ **values**
```

### Steps To Reproduce

Put this anywhere in your lazy config:

```lua
{ "folke/trouble.nvim", enabled = false },
```

### Expected Behavior

No trouble (pun intended)

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	"folke/tokyonight.nvim",
	{ "LazyVim/LazyVim", import = "lazyvim.plugins" },
	{ "folke/trouble.nvim", enabled = false },
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
```

**Comment by folke** [comment]
Then just set `vim.g.trouble_lualine = false`??

**Comment by matta** [comment]
> Then just set `vim.g.trouble_lualine = false`??

That is a workaround, yes.

I filed the bug because https://www.lazyvim.org/configuration/plugins#-disabling-plugins suggests that "enabled = false" should be enough. It is just a small paper cut, though.

**Comment by folke** [comment]
allright, fixed it anyway...
