### ISSUE TITLE
bug: black formatting via null-ls crashes neovim

### ISSUE THREAD

**Issue by fredrikaverpil** [LazyVim/LazyVim#395]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.3

### Operating system/version

macOS 13.2.1

### Describe the bug

Hi 👋  and thanks for the amazing LazyVim!

I am hitting a neovim crash whenever I rename a function (causes some files to be changed) followed by a `:wqa`. Screenshot:

<img width="1493" alt="Screenshot 2023-03-07 at 23 11 54" src="https://user-images.githubusercontent.com/994357/223565307-15e21635-7871-4aa6-9886-e6af1a5b6cd9.png">

I have narrowed it down to `null-ls` and the `black` formatter. It seems the formatting and file-saving is clashing here. Do you have any idea what I can try to avoid this crash?

Related discussion: https://github.com/LazyVim/LazyVim/discussions/257#discussioncomment-5027701

### Steps To Reproduce

```lua
-- config/plugins/null_ls.lua
return {

  {
    "jose-elias-alvarez/null-ls.nvim",
    event = { "BufReadPre", "BufNewFile" },
    dependencies = { "mason.nvim" },
    opts = function()
      local nls = require("null-ls")
      return {
        sources = {
          nls.builtins.formatting.black,
        },
      }
    end,
  },

}
```

Then I ...

1. Open neovim in a small Python project and make sure the `black` executable is on my `$PATH` (in my case I have an activated Python virtual environment with `black` installed).
2. Hit `<Leader>cr` and rename a function (which in my case causes two files to be changed).
3. Hit `:wqa` to save all files and quit.

- At step 3 I consistently see a neovim crash.
- The crash does _not_ happen if you just change one file and then hit `:wqa`.
- If I comment out `nls.builtins.formatting.black,` from the null-ls config, the crash does not happen.

### Expected Behavior

Well, I was expecting the files were formatted and then saved without a crash. 😄

**Comment by folke** [comment]
That's not a LAzyVim issue as you probably aready know. Get a stack trace (see the neovim wiki) and report there.

But those issues might also have been fixed on Nightly already, so make to check that first before submitting a NEovim issue
