### ISSUE TITLE
bug: Pairs inside mini.pairs closeopen don't close inner pair

### ISSUE THREAD

**Issue by Kayzels** [LazyVim/LazyVim#3954]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0 Release

### Operating system/version

Windows 10 22H2

### Describe the bug

When you type a "closeopen" pair, like `"` or `'", with MiniPairs enabled, when you try to type a pair inside that pair, the inner pair won't close. This happens in multiple file types.

The output ends up being (with | being the cursor)
```
"This string should have a closing bracket: (|"
```
instead of the expected
```
"This string should have a closing bracket: (|)"
```

This happens for all pairs designated closeopen, including custom ones added. No changes to the default config for LazyVim are required to lead to this.

### Steps To Reproduce

1. Run the `repro.lua` file with `nvim -u repro.lua`
2. Open some file, and enter a closeopen pair, such as `"`.
3. Enter some text inside the closeopen pair, and attempt to open a new pair inside it, such as `()`.

### Expected Behavior

Instead of only adding the opening part of the pair, both parts of the pair should be added. So, it should add `(|)` with the cursor inside the pair. At the moment, it only adds `(|`.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
```

**Comment by folke** [comment]
that's on purpose

**Comment by dpetka2001** [comment]
You can do the following to override this behavior
```lua
  {
    "echasnovski/mini.pairs",
    opts = function(_, opts)
      opts.skip_next = false
      opts.skip_ts = false
    end,
  },
```
Test it to see if it does what you want.
