### ISSUE TITLE
bug: `<C-Space>` for incremental treesitter selection does not work

### ISSUE THREAD

**Issue by andresatierf** [LazyVim/LazyVim#3959]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Windows 11 10.0.22631.0

### Describe the bug

using `<c-space>` to select text with treesitter does not work
https://github.com/LazyVim/LazyVim/blob/8a340511774b93c6dd75368960ebbb44aa58df5c/lua/lazyvim/plugins/treesitter.lua#L22

### Steps To Reproduce

1. fresh nvim install (using starter)
2. open config
3. use `<c-space>` to select text

### Expected Behavior

`<c-space>` should select treesitter nodes incrementally

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
Enter `insert` mode and press `<C-v><C-space>`. What characters are printed out?

**Comment by andresatierf** [comment]
nothing

**Comment by dpetka2001** [comment]
It should print something out. I believe it's a problem with how your terminal interprets the key sequence. Try with `wezterm` if you're on windows.

**Comment by andresatierf** [comment]
I'm using western on windows

**Comment by dpetka2001** [comment]
It's still a problem with Wezterm on Windows. Try to do what is mentioned [here](https://github.com/wez/wezterm/issues/4055#issuecomment-1694542317). Also try to search through Wezterm github repo for other similar issues. Not a LazyVim bug.

**Comment by andresatierf** [comment]
You were correct. The link you provided fixed the issue. Thanks
