### ISSUE TITLE
question: how to toggle terminal?

### ISSUE THREAD

**Issue by redxtech** [LazyVim/LazyVim#396]
**note:** if this isn't the right place to ask this sort of question, please let me know, i'll move it to wherever would be best

hey! i've just gotten started using lazyvim and so far i'm loving it!

one issue that I am coming upon, however, is the toggleable terminal. for whatever reason, i'm not able to toggle the terminal away once i've opened it!

using the same keybind in the terminal `<leader>ft` just opens up another one, leaving me with exiting the terminal being the only option, whether it's by `exit` or `ctrl+d`.

if i'm missing something that, that would be optimal, as i'd like to figure it out.

alternatively, if you could just share which function i would have to call in order to hide the current terminal without exiting so i can bind it to another key, that would be great as well!

relevant details: `NVIM v0.8.3`

once again thanks for the work on this project, it has saved me a massive amount of time during my re-working of my neovim  configuration!

**Comment by Kristmh** [comment]
Have you seen this  #193 ?

**Comment by folke** [comment]
You can't for now. Better to use a plugin like toggleterm for this purpose

**Comment by redxtech** [comment]
> You can't for now. Better to use a plugin like toggleterm for this purpose

I have already switched my config to use toggleterm, which I am already familiar with, having used it in my old config.

Looks like it was the right choice!

Thanks!
