### ISSUE TITLE
bug: Autocommand group lazyvim_wrap_spell is not triggering for expected file types

### ISSUE THREAD

**Issue by Mike-Pilmer** [LazyVim/LazyVim#3973]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Fedora 40 - i3 spin

### Describe the bug

The autocommand in LazyVim/lua/lazyvim/config/autocmds.lua with group name lazyvim_wrap_spell is intended to trigger for text file types with a current pattern of 
`pattern = { "*.txt", "*.tex", "*.typ", "gitcommit", "markdown" }`

However, it is not actually setting the local wrap or spell variable to true in files of type *.txt, *.tex, or *.typ.  

This is fixed if the pattern is changed to 
` pattern = { "text", "plaintex", "typst", "gitcommit", "markdown" }`

### Steps To Reproduce

1. Create new text file with nvim test.txt
2.  Enter command  :setlocal spell?       This returns nospell.
4. Enter command  :setlocal wrap?        This returns nowrap.

### Expected Behavior

Since the file type is 'text', I expected that the autocommand would set the local option for spell and wrap to true, but instead they remain set to false.  

The autocommand does work as expected for markdown files. 

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
feel free to create a PR

**Comment by Mike-Pilmer** [comment]
No problem.  PR completed.
