### ISSUE TITLE
bug: Cannot resume LazyVim after waking computer from sleep.

### ISSUE THREAD

**Issue by guzman109** [LazyVim/LazyVim#3981]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10

### Operating system/version

Kubuntu 24.04

### Describe the bug

Whenever my computer sleeps after inactivity or when I close my laptop lid, I cannot resume any opened nvim windows I have opened. I'm using latest kitty terminal and I'm able to open tabs and interact with the shell, but just not any opened nvim tabs before the computer went inactive.

Not sure if this is a LazyVim bug or not and I am using all the mini.nvim LazyExtras. I cannot reproduce with the `repro.lua` method below. Here is my config https://github.com/guzman109/.dotfiles/tree/main/.config/nvim/lua

### Steps To Reproduce

1. Open LazyVim
2. Open a buffer inside LazyVim
3. Close laptop or put computer to sleep
4. Wake computer and try to interact with opened nvim window.

### Expected Behavior

Resume neovim session

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
I cannot reproduce this neither with my personal configuration or LazyVim default installation. And since you also can't reproduce it with `repro.lua`, it makes this highly unlikely to be a LazyVim bug.

**Comment by guzman109** [comment]
Hi @dpetka2001, it started once I enabled the `.mini` LazyExtras. Do you think it is a problem with those then? I'm not sure how I can share all the LazyExtras I enabled.

**Comment by guzman109** [comment]
Found them, https://github.com/guzman109/.dotfiles/blob/main/.config/nvim/lazyvim.json

**Comment by dpetka2001** [comment]
No idea. From `mini` Extras, I only use `mini-surround`, `mini-identscope` and `mini-hipatterns`. With those enabled I don't have the problem you observe. But I can't speak for the rest of the Extras as I don't use them. You should debug your own config by disabling all the Extras and enabling them one by one until you find the culprit. Nobody else can debug your configuration except you.

**Comment by folke** [comment]
When it happens, can you check the CPU usage of the Neovim process?

**Comment by guzman109** [comment]
@folke Does not seem to use alot, in total it is 207MB

![image](https://github.com/LazyVim/LazyVim/assets/42706936/b8e86528-22f6-44ec-99b4-b9deef3d677b)

**Comment by guzman109** [comment]
@dpetka2001 @folke  I disabled all of my added plugins and configs and used only the LazyExtras that I have installed. Looks like the problem may lie there? I will try disable each Extra plugin to see if any of those is causing the freeze.

**Comment by guzman109** [comment]
@dpetka2001 @folke 

Seems the culprit is yanky.nvim. I do not know if this is bug is related (https://github.com/gbprod/yanky.nvim/issues/123) or not and I don't know how to test this plugin only without LazyVim.

**Comment by folke** [comment]
For sure that one indeed.
I'm on hyprland which doesnt have that issue with wl-copy
