### ISSUE TITLE
bug: php-cs-fixer unavailable: Formatter config missing or incomplete (PHP)

### ISSUE THREAD

**Issue by dca-b** [LazyVim/LazyVim#3985]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0

### Operating system/version

Ubuntu 24.04

### Describe the bug

Formatters for this buffer:                                                                                                                                                                                                       │  
  │php-cs-fixer unavailable: Formatter config missing or incomplete

### Steps To Reproduce

LazyExtras: lang.php (x)

:ConformInfo
:checkhealth

### Expected Behavior

Can't format current buffer (.php) file.

**Comment by dpetka2001** [comment]
@dca-b  It would be great if you could test the linked PR locally to see if it works for you, because I don't do PHP and can't test it appropriately.
