### ISSUE TITLE
bug: settings for outline.nvim cause symbol search crash

### ISSUE THREAD

**Issue by Verisana** [LazyVim/LazyVim#4003]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Ubuntu 22.04.4 LTS

### Describe the bug

Before I open `outline.nvim` tab with LazyVim settings, if I hit `<leader>ss`, everything is working. After I open and settings for `outline.nvim` there are two issues:
1/ I don't see functions connected to classes (Rust)
2/ And if I hit `<leader>ss`, this error message is showed:

```
Error executing vim.schedule lua callback: vim/shared.lua:0: bad argument #1 to '?' (string expected, got boolean)
stack traceback:
	[builtin#81]: at 0x64743f732e00
	vim/shared.lua: in function 'tbl_map'
	...l/share/nvim/lazy/telescope.nvim/lua/telescope/utils.lua:143: in function 'filter_symbols'
	...nvim/lazy/telescope.nvim/lua/telescope/builtin/__lsp.lua:325: in function 'handler'
	/usr/share/nvim/runtime/lua/vim/lsp/client.lua:685: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

In order to temporary fix it, I just override all LazyVim related settings on this plugin and it works again:
```
return {
  {
    "hedyhli/outline.nvim",
    keys = { { "<leader>o", "<cmd>Outline<CR>", desc = "Toggle Outline" } },
    opts = function()
      local defaults = require("outline.config").defaults
      return defaults
    end,
  },
}
```

### Steps To Reproduce

1/ Enable Rust extra
2/ Open file
3/ Open side outline.nvim
4/ Hit <leader>ss and should show an error

### Expected Behavior

Expect outline to show all functions in class and `<leader>ss` key to work with symbol search

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by Verisana** [comment]
Hello @folke ,
Thank you very much for your prompt actions :pray: 

I just tried new version and problem with crashing when `<leader>ss` is hit fixed, but `outline.nvim` still doesn't show functions under the classes. Here are the images to showcase the situation:
![image](https://github.com/user-attachments/assets/58dbd1af-3bc3-4dd5-9ece-12029c86def7)

vs default settings for `outline.nvim`:
![image](https://github.com/user-attachments/assets/416f2f60-d718-475d-950c-bc126b00d151)

Should I open a new ticket? What additional information I can provide to help to fix the issue?

**Comment by dpetka2001** [comment]
That's not a bug. That's a configuration setting in LazyVim. You can search through closed issues about how to change `kind_filter` ([this comment](https://github.com/LazyVim/LazyVim/issues/2216#issuecomment-2091460516) mentions a way to do it) if you don't like the default setting.
