### ISSUE TITLE
bug: weird keymap error

### ISSUE THREAD

**Issue by huwqchn** [LazyVim/LazyVim#4020]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.11.0

### Operating system/version

archlinux

### Describe the bug

In lazyvim's keymaps.lua, adding `vim.keymap.set({ "n", "v", "o" }, "l", "o")` causes an error `current buffer is not in diff mode` when pressing `x` in normal mode. This keymap works fine in regular nvim.

### Steps To Reproduce

1. git clone https://github.com/LazyVim/starter.git ~/.config/nvim
2. echo 'vim.keymap.set({ "n", "x", "o" }, "l", "o")' >> ~/.config/nvim/lua/config/keymaps.lua
3. open a file in nvim and press 'x'

### Expected Behavior

the 'x' key can work normally

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
Can't reproduce at all.

**Comment by dpetka2001** [comment]
Update your plugins. I was able to reproduce it with old (today morning) `which-key` version. But commit `877ce16` seems to fix this and does not happen anymore.

**Comment by huwqchn** [comment]
> Update your plugins. I was able to reproduce it with old (today morning) `which-key` version. But commit `877ce16` seems to fix this and does not happen anymore.

Thanks, it works
