### ISSUE TITLE
bug: telescope require `fd` when find files

### ISSUE THREAD

**Issue by manhhn01** [LazyVim/LazyVim#4031]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0 Build type: Release LuaJIT 2.1.1713773202

### Operating system/version

MacOS 14.3.1

### Describe the bug

When find_files, telescope is looking for fd
Other pickers work as normal
![image](https://github.com/user-attachments/assets/2dbc258b-8cf0-4462-998a-7dbb0b4c8d3f)

### Steps To Reproduce

1. Open LazyVim
2. `:Telescope find_files` or `<leader>ff`

### Expected Behavior

to find files without fd installed

**Comment by folke** [comment]
That's correct
