### ISSUE TITLE
bug: Mason package path not found for debugpy

### ISSUE THREAD

**Issue by kapral18** [LazyVim/LazyVim#4039]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0 Build type: Release LuaJIT 2.1.1720049189 Run "nvim -V1 -v" for more info

### Operating system/version

MacOS 14.5

### Describe the bug

![image](https://github.com/user-attachments/assets/e71024ab-e9cf-417c-a9ed-7fdc45ba0c07)

Appears every time I open nvim on any file, unrelated to python. 

### Steps To Reproduce

1. Clone lazyvim-starter
2. Add python extras
3. Open nvim

### Expected Behavior

mason package should be added as part of python extras config

**Comment by dpetka2001** [comment]
Did you add a breakpoint and the package didn't get installed?

**Comment by kapral18** [comment]
@dpetka2001  well the package is not mentioned in python extras config in the place, so there is nowhere for me to put the breakpoint there. You nvim-dap-python requires debugpy https://github.com/mfussenegger/nvim-dap-python?tab=readme-ov-file#debugpy. `debugpy` is available through mason, but is not mentioned in extras config, if I understand it correctly it needs to be added within nvim-dap-python -> dependencies -> mason-> ensure_installed -> debugpy

**Comment by folke** [comment]
That should be installed automatically when you use nvim-dap-python

**Comment by dpetka2001** [comment]
If you press `<leader>db` to put a breakpoint in any file, that should trigger `nvim-dap` loading and its dependencies and `debugpy` should be installed automatically. I just tried it several times with default LazyVim installation. Maybe you're overriding something in your personal config and that messes up with the installation?

**Comment by kapral18** [comment]
I do have dap.core and it's not happening. I tried to nuke all my config state with `rm -rf cache,share,state` I get the warning above rightaway with clean install. This is my python override config https://github.com/kapral18/dotfiles/blob/0adf19ad6d9708673e9ec1318e4b0f98158e6f6d/home/dot_config/exact_nvim/exact_lua/exact_plugins/python.lua, so there is nothing related to nvim-dap-python here.

**Comment by dpetka2001** [comment]
The problem is not with your python configuration. It's with your `dap` configuration. 

[Here](https://github.com/kapral18/dotfiles/blob/0adf19ad6d9708673e9ec1318e4b0f98158e6f6d/home/dot_config/exact_nvim/exact_lua/exact_plugins/dap.lua#L14-L19) you're overriding the default LazyVim nvim-dap `config` function and that's why it's not working for you. See how the default LazyVim [nvim-dap config function](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/extras/dap/core.lua) is and make proper adjustments.

Not a LazyVim bug.

**Comment by kapral18** [comment]
@dpetka2001 thanks for spotting

**Comment by VishalSubramanyam** [comment]
I have this issue even though I'm not overriding the config function in my setup, only setting opts to a function

**Comment by dpetka2001** [comment]
Try it with a default LazyVim installation and enable only the Python and dap-core Extra. If it works (which will work) it's a problem somewhere in your personal configuration. Disable the changes you made in your personal configuration and enable them piece by piece until you find out what messes up your config.

**Comment by amr390** [comment]
In case it helps.
To me the problem was with this plugin 
https://github.com/linux-cultist/venv-selector.nvim
I used the regexp branch with the default config in the readme and the problem dissapeared.

**Comment by ngfuong** [comment]
> In case it helps. To me the problem was with this plugin https://github.com/linux-cultist/venv-selector.nvim I used the regexp branch with the default config in the readme and the problem dissapeared.

I was having the same bug with venv-selector plugin. I removed the plugin and the bug was eliminated.
