### ISSUE TITLE
bug: extras/lang/typescript

### ISSUE THREAD

**Issue by suciptoid** [LazyVim/LazyVim#405]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.0-dev-1184+g0ecb4d725-dirty

### Operating system/version

MacOS 13

### Describe the bug

Hi, thank you for this awesome nvim preconfigured setup.

I have some issue about typescript plugin spect provided by LazyVim.

I'm using builtin spec, imported from:
```lua
 { import = "lazyvim.plugins.extras.lang.typescript" }
```

1. When using command `<space> c o` (organize import), it's show "Not an editor command: TypescriptOrganizeImports". But when i'm remap manuali and call `require("typescript").actions.organizeImports()` it's work.
2. Some completion not shown in jsx props like (className, onClick), but on custom component it show the autocompletion. I read some issue on `typescript.nvim` repo https://github.com/jose-elias-alvarez/typescript.nvim/issues/34, and i think lazyvim spec already set capabilities correctly.

### Steps To Reproduce

1. Use lazyvim starter
2. enable `{ import = "lazyvim.plugins.extras.lang.typescript" }`
3. open typescript-react project
4. create component, some props not shown as completion (className,onClick,...)

### Expected Behavior

props shown as completion

### Repro

```Lua
https://github.com/suciptoid/nvim
```

**Comment by folke** [comment]
It works with a standard LazyVim install. It also doesn't make sense that the command is not available since you do have the mapping.

**Comment by folke** [comment]
Does typescript.nvim work for tsx out of the box?

It all works fine for me for a regular typescript project

**Comment by suciptoid** [comment]
Sorry, apparently caused by my ufo configuration in here:
https://github.com/suciptoid/nvim/blob/861ecfaf18c13ea36c8d076b66d27358785cc0c5/lua/plugins/ufo.lua#L20-L31

After try to standart lazyvim everything is ok, and than comeback with my configuration with all my plugin disabled, everything is ok. thank you for your help 👍
