### ISSUE TITLE
bug: lsp keymaps calling functions rather than passing function

### ISSUE THREAD

**Issue by tombell** [LazyVim/LazyVim#4051]
### Describe the bug

I was just browisng the source, and looking at the LSP keymaps, and I noticed [the defaults](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/lsp/keymaps.lua#L17-L20) are calling the `vim.lsp.buf.*` functions, rather than passing the function, and I believe this breaks the keymaps

**Comment by folke** [comment]
Good catch! 

Those are normally not used, but better to fix that anyway indeed :)

Done
