### ISSUE TITLE
bug: Mason plugin doesn't install mason-registry

### ISSUE THREAD

**Issue by vprashar2929** [LazyVim/LazyVim#4055]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0

### Operating system/version

MacOS 14.5

### Describe the bug

When LazyVim is installed and the Mason plugin is checked, no languages/linters/LSP etc appear in the list. It seems that the mason-registry is uninstalled. Additionally, when the :checkhealth command is executed, it gets stuck and displays the following error. 

Attaching some screenshot for reference:

<img width="1144" alt="Screenshot 2024-07-15 at 10 25 59 PM" src="https://github.com/user-attachments/assets/176497b4-0256-473b-9595-23c610e94285">

<img width="1144" alt="Screenshot 2024-07-15 at 10 26 53 PM" src="https://github.com/user-attachments/assets/8df95e67-8093-4601-901f-d591c23059f8">

<img width="1360" alt="Screenshot 2024-07-15 at 10 28 02 PM" src="https://github.com/user-attachments/assets/5d01a801-07a0-4605-a6c2-1f2791423520">

### Steps To Reproduce

1. Install neovim with above defined version.
2. Follow the installation steps mentioned here: https://www.lazyvim.org/installation
3. Check the Mason plugin to see if the list of langauges/linters/formatters etc are available

### Expected Behavior

Once LazyVim is installed and Mason plugin checked it should have installed the registries which entail shows the list of linters/languages etc available for installing.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by vprashar2929** [comment]
It used to work earlier not sure why it doesn't work now.
Verified the same issue on Fedora 40

**Comment by dpetka2001** [comment]
Can't reproduce. Following screencast with LazyVim default installation.

[Screencast 2024-07-15 20:16:33.webm](https://github.com/user-attachments/assets/e91f962f-eb3c-4aa7-9cb0-0d24ad06a179)

My guess would be you either have an incompatible architecture or some trouble with Github possibly (maybe behind some proxy??). Try to install LazyVim from start and if the problem persists you should probably create an issue at Mason github repo.

**Comment by vprashar2929** [comment]
I checked on arm and amd64 architecture. Getting same issue. Probably I will raise the same at Mason repo
