### ISSUE TITLE
bug: Error with nvim-cmp

### ISSUE THREAD

**Issue by link1183** [LazyVim/LazyVim#4056]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Arch Linux

### Describe the bug

On a raw installation of LazyVim, when using the completion list with <c-p> or <c-n>, you get the following error (copied from the :messages buffer)

E5108: Error executing lua: .../nvim/lazy/nvim-cmp/lua/cmp/view/custom_entries_view.lua:328: attempt to perform arithmetic on local 'cursor' (a nil value)
stack traceback:
	.../nvim/lazy/nvim-cmp/lua/cmp/view/custom_entries_view.lua:328: in function 'select_next_item'
	...gunthe1/.local/share/nvim/lazy/nvim-cmp/lua/cmp/view.lua:224: in function 'select_next_item'
	...gunthe1/.local/share/nvim/lazy/nvim-cmp/lua/cmp/init.lua:146: in function 'select_next_item'
	...ocal/share/nvim/lazy/nvim-cmp/lua/cmp/config/mapping.lua:48: in function 'on_keymap'
	...gunthe1/.local/share/nvim/lazy/nvim-cmp/lua/cmp/core.lua:145: in function 'callback'
	....local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/keymap.lua:133: in function <....local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/keymap.lua:127>

### Steps To Reproduce

1. Follow the installation process at http://www.lazyvim.org/installation
2. Open any code file (in my case, a main.rs file)
3. Type something to get a completion list (in my case, 'prin')
4. Press <c-p> or <c-n>

### Expected Behavior

The cursor should go up or down in the completion list

**Comment by nutrienrafaelinacio** [comment]
I'm getting this same error on macos, any solution

**Comment by sjclayton** [comment]
@link1183 and @nutrienrafaelinacio 

Looks like it's likely an issue with this --> [https://github.com/hrsh7th/nvim-cmp/pull/1986](https://github.com/hrsh7th/nvim-cmp/pull/1986)

**Comment by folke** [comment]
exactly, not a LazyVim issue.
Please don't just post any issue you have here.

There's a reason I added this:

- [x] I have searched the existing issues of plugins related to this issue
