### ISSUE TITLE
bug: prettierd not installing when using prettier extras

### ISSUE THREAD

**Issue by briandipalma** [LazyVim/LazyVim#406]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.8.3

### Operating system/version

Linux

### Describe the bug

I saw you added extras for ESLint and Prettier so I uninstalled them and moved my configuration to using them, [commit here](https://github.com/briandipalma/ansible/commit/24cd888eaf86d36c7e454f545dd05006819a7ed6).

I restart and open a few JS/TS files and the ESLint LSP installs fine and works/fixes a few issues. Prettierd though doesn't install...that's not what I would expect given:

> **opts**: your custom opts will be merged with the default opts

Is it maybe the case that I need to order my plugin imports in a certain fashion or that the merging only happens for top level map values or the merging only happens once?

I've also noticed the dependency string for mason is just `"mason.nvim"` in some places, is that correct?

### Steps To Reproduce

.

### Expected Behavior

I'd expect `prettierd` to be installed.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
https://github.com/briandipalma/ansible/blob/main/roles/common/files/nvim/lua/plugins/mason.lua

Either you should include `prettierd` there, or use a function as in the commit I referenced to correctly extend the list

**Comment by briandipalma** [comment]
OK, the thing I don't understand then is how do all the various `opts` for `"neovim/nvim-lspconfig"` work? They are all `opts` tables and not functions that merge into an `opts` table.

**Comment by PetarMetodiev** [comment]
Hey, I am also having the same issue - fresh install of LazyVim following the docs and added these lines:
```
    { import = "lazyvim.plugins.extras.linting.eslint" },
    { import = "lazyvim.plugins.extras.formatting.prettier" },
```
Everything besides prettierd gets automatically installed. Manually installing prettierd through mason doesn't seem to help - it still does not get picked up by null ls. Does this mean I have to follow the steps [here](https://www.lazyvim.org/plugins/extras/formatting.prettier)? If so - what is the point of the prettier extra?

Sorry for hijacking the thread, seemed similar to my issue.

**Comment by folke** [comment]
same as what I mentioned before. You're overriding  ensure_installed etc in your own config

**Comment by PetarMetodiev** [comment]
I am not sure how about this - I did a quick grep in my config and didn't find any LSP related `ensure_installed` overrides. The only place I have it is here:
```lua
{
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "bash",
        "css",
        "scss",
        "html",
        "javascript",
        "jsdoc",
        "json",
        "json5",
        "lua",
        "tsx",
        "typescript",
        "vim",
      },
    -- ...other ts options
    },
  }
```
There are some examples in the `example.lua` file but from what I can gather it is not being loaded.

**Comment by briandipalma** [comment]
I'd try with a clean set of config without any of your changes and only vanilla LazyVim. See if that works.

**Comment by PetarMetodiev** [comment]
Ok, so here are the results with a clean config and only modifying `lazy.lua` to have these lines:
```lua
    { import = "lazyvim.plugins.extras.linting.eslint" },
    { import = "lazyvim.plugins.extras.formatting.prettier" },
```
Looking at `:Mason` I see that all required LSPs are installed, including prettierd:
![image](https://github.com/LazyVim/LazyVim/assets/6378306/5368f74d-7f20-4abd-bb1d-ee8c855ac8a9)
Looking at `:LspInfo` I see this:
![image](https://github.com/LazyVim/LazyVim/assets/6378306/b0daec96-8d77-4f7c-afae-6188efe17c3e)
`null-ls` doesn't seem to start automatically _and_ is running in single file mode. I tried manually uninstalling and then installing prettier through mason but that didn't help. When I press `<leader>cf` (the default keymap for formatting) I see a message in the lower left corner of the editor which shows prettier but the code does not get formatted:

https://github.com/LazyVim/LazyVim/assets/6378306/0dada26d-1dd0-4438-a0f0-24569b745ec4

**Comment by folke** [comment]
Prettierd is not an lsp.

Null-ls will always be shown as not starting automatically and in single file mode, that's all normal.

**Comment by PetarMetodiev** [comment]
Ah, I see. Thank you both for the help and thank you folke for making LazyVim - it is awesome!
