### ISSUE TITLE
bug: Ctrl-n and Ctrl-p to go through suggestions not working anymore.

### ISSUE THREAD

**Issue by Redoxahmii** [LazyVim/LazyVim#4063]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10

### Operating system/version

Arch Linux

### Describe the bug

**EDIT: This is happening on lsp suggestions as well the error is same. i thought this was only for `cmp-cmdline` but the behavior is same for any suggestions you try to go through using `ctrl+n` or `ctrl+p`** 

```
E5108: Error executing lua: .../nvim/lazy/nvim-cmp/lua/cmp/view/custom_entries_view.lua:365: attempt to perfor 
 rm arithmetic on local 'cursor' (a nil value) 
 stack traceback: 
 .../nvim/lazy/nvim-cmp/lua/cmp/view/custom_entries_view.lua:365: in function 'select_prev_item' 
 ...e/redox/.local/share/nvim/lazy/nvim-cmp/lua/cmp/view.lua:230: in function 'select_prev_item' 
 ...e/redox/.local/share/nvim/lazy/nvim-cmp/lua/cmp/init.lua:168: in function 'select_prev_item' 
 ...ocal/share/nvim/lazy/nvim-cmp/lua/cmp/config/mapping.lua:120: in function 'on_keymap' 
 ...e/redox/.local/share/nvim/lazy/nvim-cmp/lua/cmp/core.lua:145: in function 'callback' 
 ....local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/keymap.lua:133: in function <....local/share/nvim/lazy/nvim- 
 -cmp/lua/cmp/utils/keymap.lua:127> 
```

### Steps To Reproduce

1. setup `cmd-cmdline` using config provided.
2. try moving the selected item.

### Expected Behavior

This just broke i have been using this config since quite some time and reading from the repo of `cmp-cmdline` nothing seems to be changed.
This is the config i have:
```lua
{
  "hrsh7th/nvim-cmp",
  event = { "InsertEnter", "CmdLineEnter" },
  dependencies = {
    "hrsh7th/cmp-cmdline",
    "hrsh7th/cmp-emoji",
  },
  opts = function(_, opts)
    table.insert(opts.sources, { name = "emoji" })
    local cmp = require("cmp")
    -- `:` cmdline setup.
    cmp.setup.cmdline(":", {
      mapping = cmp.mapping.preset.cmdline(),
      sources = cmp.config.sources({
        { name = "path" },
      }, {
        {
          name = "cmdline",
          option = {
            ignore_cmds = { "Man", "!" },
          },
        },
      }),
    })
    cmp.setup({
      sources = {
        name = "nvim_lsp",
        max_item_count = 10,
      },
    })
  end,
}
```
Thank you for your time.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by fabio-pardo** [comment]
Can confirm this is also happening to me.

**Comment by DrummyFloyd** [comment]
it's related to `nvim-cmp` not `LazyVim`
wait a couple of hour and it will be fix =) 

https://github.com/hrsh7th/nvim-cmp/issues/1992

**Comment by michael-duren** [comment]
Wow good response time on this, literally just ran into it
