### ISSUE TITLE
bug: cursor abnormal

### ISSUE THREAD

**Issue by TheEros** [LazyVim/LazyVim#4065]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10

### Operating system/version

windows11 wsl2 arch

### Describe the bug

After typing a method, the cursor loads from the beginning to the method position

### Steps To Reproduce

typing a method

### Expected Behavior

After typing a method, the cursor is at the position of the method

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by TheEros** [comment]
![动画](https://github.com/user-attachments/assets/3face375-6bb4-42da-a126-ffd97cb0c5de)

**Comment by folke** [comment]
https://github.com/hrsh7th/nvim-cmp/pull/1993
