### ISSUE TITLE
feature: Expose a function to "process" a `toggle` to the users

### ISSUE THREAD

**Issue by farzadmf** [LazyVim/LazyVim#4081]
### Did you check the docs?

- [X] I have read all the LazyVim docs
- [X] This is not a request for a new or existing extra (see above)

### Is your feature request related to a problem? Please describe.

I have my own "wrappers" around `LazyVim`'s `toggle` functions. There was a recent change, refactoring the `toggle` module, changing the members from being functions to being modules/tables.

I was wondering if you're open to expose, what I call, the "process" functionality used in [toggle.map](https://github.com/LazyVim/LazyVim/blob/a1335e59e15ef55ee43dd30120da948bc0f293c3/lua/lazyvim/util/toggle.lua#L25)

### Describe the solution you'd like

I was thinking maybe something like this in `toggle.lua`:

```lua
---@param toggle lazyvim.Toggle
function M.process(toggle)
  local state = not toggle.get()
  toggle.set(state)
  if state then
    LazyVim.info("Enabled " .. toggle.name, { title = toggle.name })
  else
    LazyVim.warn("Disabled " .. toggle.name, { title = toggle.name })
  end
end

---@param lhs string
---@param toggle lazyvim.Toggle
function M.map(lhs, toggle)
  LazyVim.safe_keymap_set("n", lhs, function()
    M.process(toggle)
  end, { desc = "Toggle " .. toggle.name })
  M.wk(lhs, toggle)
end
```

### Describe alternatives you've considered

There's no alternative since the function is defined "inside", and there's no way to have access to that function.

### Additional context

I can definitely create a PR if you're good with this change

**Comment by sjclayton** [comment]
@farzadmf 

I am interested in something along these lines as well, as I have a helper function currently for toggling things that have no way to return a state, and instead rely on ex mode commands to disable and enable things... and was wondering if this could somehow be made to work in the style of the new toggle.map function.

**Comment by farzadmf** [comment]
Yeah, in my wrappers, I was using things like `LazyVim.toggle.diagnostics`, etc. basically delgating the toggling to those functions.

I mean I still can copy/paste the code from LazyVim to my config to do the toggling, but I personaly think this change helps avoiding the copy/paste

**Comment by folke** [comment]
You can now just call them like before, so `LazyVim.toggle.diagnostics()`

**Comment by farzadmf** [comment]
Thank you @folke ; I was hoping to also re-use the notifications from LazyVim toggles.

And since I'm using [hydra.nvim](https://github.com/nvimtools/hydra.nvim) to set up my toggles as wrappers around LazyVim ones (I'm passing `LazyVim.toggle.diagnostics` for example in its `heads`), I'm still getting the error from Hydra:
```lua
.../lazy/hydra.nvim/lua/hydra/init.lua:85: rhs: expected string|function, got table
```

Maybe it doesn't like `setmetatable`?

**Comment by folke** [comment]
Then that's a hydra issue. You could just wrap it in a real function.
Not going to fix hydra bugs.

I just pushed a change so that notifs are also shown

**Comment by farzadmf** [comment]
> Not going to fix hydra bugs.

Makes sense

> I just pushed a change so that notifs are also shown

Great, question: is there any way to tell `lazy.nvim` to ignore the releases and just take the very latest commit? (for `LazyVim` for example)

**Comment by folke** [comment]
https://www.lazyvim.org/configuration/lazy.nvim

**Comment by farzadmf** [comment]
I think I tried playing with `version = '*'` and `version = false` before, but none of them was picking up the latest commit

My setup is like this (added `version = false`):
```lua
require('lazy').setup({
  change_detection = {
    enabled = true,
    notify = false,
  },
  checker = {
    enabled = true,
    notify = false,
  },
  defaults = {
    lazy = true,
  },
  performance = {
    rtp = {
      disabled_plugins = {
        'gzip',
        -- "matchit",
        -- "matchparen",
        -- "netrwPlugin",
        'tarPlugin',
        'tohtml',
        'tutor',
        'zipPlugin',
      },
    },
  },
  spec = {
    { 'folke/lazy.nvim', version = false },
    { 'LazyVim/LazyVim', import = 'lazyvim.plugins', version = false },
    -- ... my other plugins ...  
  }
})
```

But still when I open `lazy.nvim`, it shows:
```
    ● LazyVim 10.82ms  start
        dir     /Users/farzadmf/.local/share/nvim/nvim_lzv/data/nvim/lazy/LazyVim
        url     https://github.com/LazyVim/LazyVim
        version 12.31.0
        tag     v12.31.0
        branch  main
        commit  d263cf5
        readme  README.md
        help    |LazyVim.txt|
```

Where the commit is still for the release, and not the latest in `main`

**Comment by folke** [comment]
Indeed, you need add that **after** this line `{ 'LazyVim/LazyVim', import = 'lazyvim.plugins', version = false },`,
or in a separate file as @dpetka2001 suggests.

**Comment by farzadmf** [comment]
> you need add that **after** this line

Sorry, what are you referring to when saying "that"? Not sure what I need to add.

**Comment by folke** [comment]
sigh, just follow the docs and it will work https://www.lazyvim.org/configuration/lazy.nvim

**Comment by farzadmf** [comment]
Sorry to bother you with stupid questions; it's probably something in my config; I need to go and check

**Comment by folke** [comment]
This:
```lua
spec = {
    { 'folke/lazy.nvim', version = false },
    { 'LazyVim/LazyVim', import = 'lazyvim.plugins', version = false },
    -- ... my other plugins ...  
  }
```

**Won't work indeed, like myself and @dpetka2001 were saying**.

If you follow literally what's in the docs. The docs I've pointed to twice, it will work.

**Comment by dpetka2001** [comment]
@farzadmf Just create a file `~/.config/nvim/lua/plugins/core.lua` with contents
```lua
return {
  { "folke/lazy.nvim", version = false },
  { "LazyVim/LazyVim", version = false },
}
```
and it should work.

**Comment by farzadmf** [comment]
Thank you @dpetka2001 ; now I understand what "that" is 🙂

So, basically the "additional" specs needs to come after `reuqire('lazy').setup({ ... })` if I understand it correctly.

> If you follow literally what's in the docs. The docs I've pointed to twice, it will work.

@folke I appreciate it, and that's why I said "stupid questions" because seems like I made a complete fool of myself.

Anyway, it _might_ be worth mentioning this in the docs in case someone gets confused like me (or possibly I'm the only dumb person reading the docs, so that's fine 🙂)

But personally I think it would be worth emphasizing the additional file `plugins/<whatever>.lua` is the key there, but again, merely a suggestion, and smarter people would figure that out by themselves.

**Comment by folke** [comment]
It literally says so?

![image](https://github.com/user-attachments/assets/96d213a1-2cd7-48ac-97df-1f647b8e579e)
