### ISSUE TITLE
bug: fzf version < 0.36.0 make fzf.lua crash

### ISSUE THREAD

**Issue by jaydebor** [LazyVim/LazyVim#4110]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.11.0-dev

### Operating system/version

ubuntu 22.04

### Describe the bug

fzf version < [0.36.0](https://github.com/junegunn/fzf/releases/tag/0.36.0) doesn't implement the --no-scrollbar, making the plugin crash

### Steps To Reproduce

1 using fzf version < 0.36.0
2 open nvim
3 hit <space>+/

### Expected Behavior

it should not crash?

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
update fzf?

**Comment by jaydebor** [comment]
i have to make a whole system upgrade to use fzf  from ubuntu package manager. I can, so that's not a problem for me, but user in a more secured environnement may not be able to.

**Comment by folke** [comment]
Open a question in the fzf-lua repo.
Maybe there's a better way to hide the scrollbar in the results

**Comment by dpetka2001** [comment]
You could also change `fzf_opts` in your personal configuration to not include `--no-scrollbar`. Something like this should work I believe
```lua
{
  "ibhagwan/fzf-lua",
  opts = function(_, opts)
    opts.fzf_opts = {}
  end,
}
```

**Comment by jaydebor** [comment]
i'm not sure it's a fzf-lua problem, the bug comes from this line in the fzf.lua file
https://github.com/LazyVim/LazyVim/blob/783949810855556dd12ed2685e62fb37a4c9504d/lua/lazyvim/plugins/extras/editor/fzf.lua#L104

**Comment by jaydebor** [comment]
> You could also change `fzf_opts` in your personal configuration to not include `--no-scrollbar`. Something like this should work I believe
> 
> ```lua
> {
>   "ibhagwan/fzf-lua",
>   opts = function(_, opts)
>     opts.fzf_opts = {}
>   end,
> }
> ```

can't test it anymore, but that could be a workaround, thanks

**Comment by folke** [comment]
> i'm not sure it's a fzf-lua problem, the bug comes from this line in the fzf.lua file
> 
> https://github.com/LazyVim/LazyVim/blob/783949810855556dd12ed2685e62fb37a4c9504d/lua/lazyvim/plugins/extras/editor/fzf.lua#L104

I'm aware, but fzf-lua has some support for enabling/disabling fzf flags depending on the version, so there might be a better way to set this.

**Comment by jaydebor** [comment]
ok, i'll try!
