### ISSUE TITLE
bug: cant use venv-selector.nvim when fzf extra plugin is imported

### ISSUE THREAD

**Issue by roeybenarieh** [LazyVim/LazyVim#4113]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Ubuntu 22.04.4 LTS

### Describe the bug

when I configure LazyVim to use both the `fzf` and `python` extras, the `venv-selector.nvim` plugin becomes disabled.
I traced it to this `venv-selector.nvim` configuration:
```lua
enabled = function()
  return LazyVim.has("telescope.nvim")
end
```
This is very unintuitive, is it possible to add a tiny disclaimer on the Lazyvim website that warns about this?

### Steps To Reproduce

1. copy repro.lua provided below
2. run `nvim -u repro.lua`
3. try to use `:VenvSelect` command

### Expected Behavior

Expected both `fzf` Lazyvim extra and `venv-selector` plugins to work

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
	spec = {
		{ "LazyVim/LazyVim", import = "lazyvim.plugins" },
		-- add any other plugins here
		{ import = "lazyvim.plugins.extras.editor.fzf" },
		{ import = "lazyvim.plugins.extras.lang.python" },
	},
})
```

**Comment by folke** [comment]
That's not a bug. venv-selector is disabled when you don't use telescope.

Related: https://github.com/linux-cultist/venv-selector.nvim/issues/142#issuecomment-2211751123

**Comment by esteban-gs** [comment]
> That's not a bug. venv-selector is disabled when you don't use telescope.
> 
> Related: [linux-cultist/venv-selector.nvim#142 (comment)](https://github.com/linux-cultist/venv-selector.nvim/issues/142#issuecomment-2211751123)

@folke , it looks like venv selector now supports fzf-lua: https://github.com/linux-cultist/venv-selector.nvim?tab=readme-ov-file#%EF%B8%8F-features
