### ISSUE TITLE
bug:  "starter" lazyvim config throwing inlay_hint.lua errors

### ISSUE THREAD

**Issue by jwiede** [LazyVim/LazyVim#4117]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2509+g633bf61d3

### Operating system/version

Debian 6.6.15-2rodete2 (2024-03-19) x86_64 GNU/Linux

### Describe the bug

After cloning lazyvim starter into .config/nvim, upon launching usual chugging of tree-sitter compiles eventually yields lazy starter page (but with the error shown in picture).  This is across multiple clean installs.
![Screenshot from 2024-07-20 00-45-40](https://github.com/user-attachments/assets/40f7d7ab-b278-413a-9fb8-4f0ca6dcbfcf)

### Steps To Reproduce

1.  Issued following shell commands:

$git clone https://github.com/LazyVim/starter ~/.config/nvim

$ rm -rf ~/.config/nvim/.git

$ nvim

(note:  no further user input needed past here except occasional spacebar or ENTER in response to tree-sitter init prompts)

2.  Sit through usual updating and churning of default components and settings.

3. Eventually processing ends at LazyVim "starter screen", only with error message overlay as per picture.

### Expected Behavior

Resolve to LazyVim default "starter screen" WITHOUT error overlay.

### Repro

```lua
-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")

-- NOTE: Yes, completely default, no changes.
```

**Comment by jwiede** [comment]
BTW, though I saw various mentions of historical inlay_hints.lua issues, I did not see anything where inlay errors were being displayed from a completely virgin installation at first launch.

**Comment by dpetka2001** [comment]
You have an old nightly build 0.10-dev. Switch to 0.10 stable or a recent 0.11-dev nightly.
