### ISSUE TITLE
bug: Grug buffer grow without bounds

### ISSUE THREAD

**Issue by mehalter** [LazyVim/LazyVim#4145]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0 (github release)

### Operating system/version

Arch Linux

### Describe the bug

When using grug-far the number of buffers grow without bounds inside the vim session. This is because there is some bug in `grug-far` or neovim where if the buffers are unlisted they just continuously get created. Until this gets resolved upstream this buffer type should be left as listed. This really messes up the dynamic title generation in `grug-far` as well.

Reference, I was looking to upstream to `grug-far` to unlist the buffers by default and all of their unit tests fail after the first one, so I investigated: https://github.com/MagicDuck/grug-far.nvim/pull/139

### Steps To Reproduce

1. `nvim -u repro.lua`, start the session
2. `<Leader>sr`, open grug
3. `hello, world`, start typing anything (notice that the buffer title, `GRUG FAR - 1` changes to `GRUG FAR - 2`
4. `:ls!`, observe the buffer list

### Expected Behavior

There should not be a huge collection of unlisted buffers.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
ty for the fix!
