### ISSUE TITLE
bug: Cannot Disable `inlay_hints` Despite Setting `enabled = false

### ISSUE THREAD

**Issue by Alan-TheGentleman** [LazyVim/LazyVim#4146]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

WSL 2

### Describe the bug

I am encountering an issue where I am unable to disable `inlay_hints` in my project. Despite setting `enabled = false`, the inlay hints continue to appear, they seem to load with "vtsls". Here are the details:

1. I have configured `inlay_hints` with `enabled = false` in my settings.
2. The inlay hints still show up in my files.
3. Using `Leader + u + h` seems to work temporarily to disable it, but I have to do it for every single file, which is not practical.

**Steps to Reproduce:**
1. Set `inlay_hints` with `enabled = false` in the settings.
2. Open any file and observe that inlay hints are still present.
3. Use `Leader + u + h` to disable inlay hints, then open another file and notice that the hints reappear.

**Expected Behavior:**
When `enabled = false` is set for `inlay_hints`, the inlay hints should not appear in any file without needing to disable them manually each time.

**Actual Behavior:**
Inlay hints are still visible in files despite setting `enabled = false`.

**Additional Information:**
Is there an additional setting or step I am missing to ensure that `inlay_hints` are permanently disabled? Any help or guidance would be greatly appreciated.

This are my dots: https://github.com/Gentleman-Programming/Gentleman.Dots/blob/main/GentlemanNvim/nvim/lua/plugins/overrides.lua

Thank you for your attention to this matter.

### Steps To Reproduce

1. Set `inlay_hints` with `enabled = false` in the settings.
2. Open any file and observe that inlay hints are still present.
3. Use `Leader + u + h` to disable inlay hints, then open another file and notice that the hints reappear.

### Expected Behavior

When `enabled = false` is set for `inlay_hints`, the inlay hints should not appear in any file without needing to disable them manually each time.

**Comment by folke** [comment]
Check line 3 of that file

**Comment by Alan-TheGentleman** [comment]
I'm so so sorry about that, added that line of code for testing proposes and forgot to remove it... so embarrassed. 
Thanks a lot !!!
