### ISSUE TITLE
bug: util.chezmoi conflicts with keybinds in the dashboard

### ISSUE THREAD

**Issue by hrzlgnm** [LazyVim/LazyVim#4155]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0

### Operating system/version

Linux - Ubuntu 22.04

### Describe the bug

After installing the extra `util.chezmoi`, after starting nvim and pressing `c` to jump to the config, one is greeted with a Chezmoi files telescope dialog.

### Steps To Reproduce

1. enable the extra `util.chezmoi`
2. try jump to config from `dashboard`

### Expected Behavior

Pressing `c` jumps to config.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
    { import = "lazyvim.plugins.extras.util.chezmoi" },
  },
})
```

**Comment by hrzlgnm** [comment]
Perhaps the `c` is indeed intended if one manages the local config using `chezmoi`, but comes sort of surprising.

**Comment by folke** [comment]
That is intentional
