### ISSUE TITLE
bug:  module 'telescope' not found

### ISSUE THREAD

**Issue by omarluq** [LazyVim/LazyVim#4165]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0

### Operating system/version

MacOs Sonoma 14.5

### Describe the bug

Running telescope commands or telescope dependent commands is failing due to missing telescope module
e.g.
```bash
  $ NoiceTelescope
  $  NoiceTelescope Error executing Lua callback: ...local/share/nvim/lazy/noice.nvim/lua/noice/util/lazy.lua:6: module 'telescope' not found:
	  no field package.preload['telescope']
```

```bash
  $ Telescope commands
  $ E492: Not an editor command: Telescope commands
```

### Steps To Reproduce

Run telescope command in nvim cmd palette 

### Expected Behavior

Telescope commands should be available as editor commands

**Comment by dotfrag** [comment]
I cannot replicate this using repro.lua or starter.

**Comment by folke** [comment]
Did you enable the fzf extra?
If so then that would disable telescope
