### ISSUE TITLE
feature: add include list to inlay_hints option

### ISSUE THREAD

**Issue by derethil** [LazyVim/LazyVim#4166]
### Did you check the docs?

- [X] I have read all the LazyVim docs
- [X] This is not a request for a new or existing extra (see above)

### Is your feature request related to a problem? Please describe.

I like the syntax LazyVim provides for enabling inlay hints and excluding certain languages e.g., this example from the docs:

```
 inlay_hints = {
   enabled = true
   exclude = { "vue" }, -- filetypes for which you don't want to enable inlay 
 },
```

However, in my case, I prefer having inlay hints only for specific languages and it'd be nice if I could implement this with similar syntax.

### Describe the solution you'd like

Add a corresponding `include` option to `inlay_hints` that would be used when `enabled = false`, e.g.:

```
 inlay_hints = {
   enabled = false
   include = { "vue" }, -- filetypes for which you do want to enable inlay 
 },
```

### Describe alternatives you've considered

This syntax isn't strictly necessary as I can configure the option manually but given the `exclude` option exists I think it makes sense to include this as well.

**Comment by folke** [comment]
Just enable it in a filetype autocmd?

**Comment by dotfrag** [comment]
I hacked an unreadable if block:

```lua
if
  vim.api.nvim_buf_is_valid(buffer)
    and vim.bo[buffer].buftype == ""
    and opts.inlay_hints.include
    and vim.tbl_contains(opts.inlay_hints.include, vim.bo[buffer].filetype)
  or (
    not opts.inlay_hints.include and not vim.tbl_contains(opts.inlay_hints.exclude, vim.bo[buffer].filetype)
  )
then
  vim.lsp.inlay_hint.enable(true, { bufnr = buffer })
end
```

But Folke's recommendation sounds better, maybe something like:

```lua

autocmd("FileType", {
  group = augroup("enable_inlay_hints"),
  pattern = {
    "javascript",
    "typescript",
  },
  callback = function(event)
    vim.lsp.inlay_hint.enable(true, { bufnr = event.buf })
  end,
})
```

**Comment by derethil** [comment]
I have it working just fine with an autocommand already, just thought I'd suggest the nicer syntax. I thought since the exclude option is a thing it makes sense but whatever, doesn't matter too much
