### ISSUE TITLE
bug: LazyExtras lang.ruby go to definition duplicate shows duplicates after saving file

### ISSUE THREAD

**Issue by Joseph-D-Bradshaw** [LazyVim/LazyVim#4170]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.11.0-dev-491+gb4b4cf46a

### Operating system/version

MacOS 14.5

### Describe the bug

When using `gd` (Go-to definition) in the default setup of Ruby LSP via LazyExtras, then the definition results seem to get an extra definition each time the file is saved and formatted.

Happy to help track it down, I am not 100% sure it is a LazyVim bug. I tested this with VSCode and don't get the same issues for go-to definition; but know little about how it is implemented there.

### Example clip
https://github.com/user-attachments/assets/4384e18b-908c-44a2-b77e-4004750906c4

### Steps To Reproduce

Steps to produce minimal Ruby example
```
mkdir reproduce
cd reproduce
bundle init
bundle install

echo "class Test
  def initialize; end

  def foo
    puts 'Hi'
  end
end
test = Test.new
test.foo
" > test.rb
```

Start via:
`nvim -u repro.lua test.rb`

Once Neovim has opened and finished bootstrapping:
1. Go to the method `foo` and enter `gd` to go to the definition.
2. Save the file with `:w`.
3. Close Neovim and repeat step 1. Each time you will get a new definition in the list.

### Expected Behavior

No duplicate definitions in result list of go-to definition.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
	spec = {
		{ "LazyVim/LazyVim", import = "lazyvim.plugins" },
		{ import = "lazyvim.plugins.extras.lang.ruby" },
	},
})
```

**Comment by folke** [comment]
not a lazyvim bug.
