### ISSUE TITLE
feature: RSS Feed for  https://www.lazyvim.org/news

### ISSUE THREAD

**Issue by Audiosutras** [LazyVim/LazyVim#4172]
### Did you check the docs?

- [X] I have read all the LazyVim docs
- [X] This is not a request for a new or existing extra (see above)

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

I would like the the [changelog](https://www.lazyvim.org/news) page on the lazyvim website to be available as an rss/atom feed. 

### Describe alternatives you've considered

I see that updates are available via twitter however I do not use twitter and prefer to use news feed aggregators. The main alternative is twitter.

**Comment by folke** [comment]
Sorry, but no

**Comment by cristianodabc** [comment]
Hi @Audiosutras, you can probably try generating one using rss.app or similar.
