### ISSUE TITLE
bug: After opening python files directly, `K` still triggers `vim.lsp.buf.hover()` even though disabled in lsp keymap setting

### ISSUE THREAD

**Issue by aik2mlj** [LazyVim/LazyVim#4176]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.1

### Operating system/version

Garuda Linux (arch-based)

### Describe the bug

I disabled `K` keymap in `lua/plugins/lsp.lua` according to the [doc](https://www.lazyvim.org/plugins/lsp#%EF%B8%8F-customizing-lsp-keymaps):
```lua
{
  "neovim/nvim-lspconfig",
  opts = function()
    local keys = require("lazyvim.plugins.lsp.keymaps").get()
    -- disable a keymap
    keys[#keys + 1] = { "K", false }
  end,
},
```

which proves effective most of the time. However, after opening a python file with `nvim filename.py`, `K` is still bound to `vim.lsp.buf.hover()`, which can be seen when searching keymap:
![image](https://github.com/user-attachments/assets/286116a3-2405-4d79-a4da-7e8a31de03e3)

Curiously, opening other file types (tried lua/rust/markdown, all with lsp enabled) doesn't yield this issue. Opening a python file with `nvim` first and selecting the file from neo-tree doesn't produce this bug as well. I suspect that there are some special settings for opening a python file directly, which add the additional `vim.lsp.buf.hover()` thing to `K`. Another evidence for this conjecture is that if uncomment my custom lsp keymap setting, the `K` key by default has a description "Hover", as set in the default [config](https://github.com/LazyVim/LazyVim/blob/bcbab77f0c5851e6d73f275f2d27c3baa4f6aa68/lua/lazyvim/plugins/lsp/keymaps.lua#L22):
![image](https://github.com/user-attachments/assets/08ee6e5e-d5be-4527-bf54-01104de16437)

### Steps To Reproduce

1. Enable the python extra package
2. add the following lines to `lua/plugin/lsp.lua`:
```lua
return {
  {
    "neovim/nvim-lspconfig",
    opts = function()
      local keys = require("lazyvim.plugins.lsp.keymaps").get()
      -- disable a keymap
      keys[#keys + 1] = { "K", false }
    end,
  },
}
```
3. Open a python file directly with `nvim filename.py`
4. `K` is still bounded to `vim.lsp.buf.hover()`, as can be seen in `<leader>sk`.

### Expected Behavior

`K` should escape the default setting.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    { import = "lazyvim.plugins.extras.lang.python" },
  },
})
```

**Comment by dpetka2001** [comment]
Since Neovim 0.10 `:h lsp-defaults`
> - |K| is mapped to |vim.lsp.buf.hover()| unless |'keywordprg'| is customized or
  a custom keymap for `K` exists.
