### ISSUE TITLE
bug: flatten.nvim doesn't work with lazygit

### ISSUE THREAD

**Issue by linsui** [LazyVim/LazyVim#4197]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0

### Operating system/version

NixOS

### Describe the bug

Recently I dropped my lazygit config based on toggleterm.nvim and switched to the lazygit config in lazyvim. But this broken flatten.nvim. When I open a file from lazygit it's opened in a new tab.

### Steps To Reproduce

Add https://github.com/willothy/flatten.nvim
Open a file from lazygit

### Expected Behavior

It's opened in the current tab.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
This happens because LazyVim sets `editPreset: "nvim-remote"` in the config file it uses and by default that opens the file in a new tab. 

To get around that you can install [nvim-remote](https://github.com/mhinz/neovim-remote) and then in your lazygit `config.yml` you can set 
```yml
os:
  edit: "nvr --remote-send '<C-\\><C-N><cmd>q<CR><cmd>lua vim.cmd(\"e \" .. {{filename}})<CR>'"
```

So, this is not actually a bug because LazyVim sets Lazygit by default to have the behavior you observe.

**Comment by linsui** [comment]
Why is neovim-remote required here? Won't this also affect lazygit out of neovim? If I set lazygit to just use neovim, the behavior is more buggy. It opens the file but lazygit window is not hidden. However the cursor is on the buffer behind the lazygit window. I'm not sure what happens here. I thought it's easier to just disable the lazygit config. But I can't only disable the edit behavior. I have to also disable the theme. Even if I disable lazygit config, the window is still kept on the top. How can I disable this behavior?

**Comment by dpetka2001** [comment]
You could try to overwrite `LazyVim.lazygit.update_config` function with your own by putting at the end of your `~/.config/nvim/init.lua` something like the following
```lua
---@diagnostic disable-next-line: duplicate-set-field
LazyVim.lazygit.update_config = function()
  ---@type table<string, string[]>
  local theme = {}

  for k, v in pairs(LazyVim.lazygit.theme) do
    if type(k) == "number" then
      local color = LazyVim.lazygit.get_color(v)
      -- LazyGit uses color 241 a lot, so also set it to a nice color
      -- pcall, since some terminals don't like this
      pcall(LazyVim.lazygit.set_ansi_color, k, color[1])
    else
      theme[k] = LazyVim.lazygit.get_color(v)
    end
  end

  local config = [[
os:
  editPreset: "nvim-remote"
  edit: "nvr --remote-send '<C-\\><C-N><cmd>q<CR><cmd>lua vim.cmd(\"e \" .. {{filename}})<CR>'"
gui:
  nerdFontsVersion: 3
  theme:
]]

  ---@type string[]
  local lines = {}
  for k, v in pairs(theme) do
    lines[#lines + 1] = ("   %s:"):format(k)
    for _, c in ipairs(v) do
      lines[#lines + 1] = ("     - %q"):format(c)
    end
  end
  config = config .. table.concat(lines, "\n")
  require("lazy.util").write_file(LazyVim.lazygit.theme_path, config)
  LazyVim.lazygit.dirty = false
end
```
You still need `neovim-remote`, but this will not affect your Lazygit default `config.yml` if you run Lazygit outside of Neovim. It will only affect Lazygit when you run it inside LazyVim with `<leader>gg`. But you will have to keep track of the above function in case something changes in future updates and make adjustments accordingly if you encounter any breakages in the future.

I don't know how recommended is the above solution, but I've seen quite a few configs that take inspiration from LazyVim and re-implement some LazyVim modules in their personal configuration to fit their needs. But you will be responsible for its maintenance.

**Comment by linsui** [comment]
Wow, thanks! But this is too much to maintain. And I need to fix the toggleterm issue for other usage anyway. It turns out that I just need to map esc to esc... So I finally go back to my toggleterm based lazygit setup. :)
