### ISSUE TITLE
bug: Not able to toggle diagnostics (clangd LazyVim extra)

### ISSUE THREAD

**Issue by VishalSubramanyam** [LazyVim/LazyVim#4203]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Ubuntu 24.04

### Describe the bug

We can see the following error message when we try to toggle diagnostic messages with clangd on a cpp file, and toggling fails:
```
E5108: Error executing lua: /usr/share/nvim/runtime/lua/vim/diagnostic.lua:1574: bufnr: expected number, got boolean                                                                                         
stack traceback:                                                                                                                                                                                             
   [C]: in function 'error'                                                                                                                                                                                 
   vim/shared.lua:764: in function 'validate'                                                                                                                                                               
   /usr/share/nvim/runtime/lua/vim/diagnostic.lua:1574: in function 'set'                                                                                                                                   
   ...ocal/share/nvim/lazy/LazyVim/lua/lazyvim/util/toggle.lua:16: in function 't'                                                                                                                          
   ...ocal/share/nvim/lazy/LazyVim/lua/lazyvim/util/toggle.lua:33: in function <...ocal/share/nvim/lazy/LazyVim/lua/lazyvim/util/toggle.lua:32>
```
This problem probably originates with an upstream plugin.
Other people who seem to have the same error with their LSPs:
[When I open the Go file in NVIM, an error message appears](https://stackoverflow.com/questions/78514165/when-i-open-the-go-file-in-nvim-an-error-message-appears)
[nvim 0.10.0 dev breaks inlay hints reactivation function](https://github.com/mrcjkb/rustaceanvim/discussions/368)

### Steps To Reproduce

1. Install clangd LazyVim Extra
2. Open a C++ source file that would produce some diagnostic message from clangd
3. Try to toggle the inline diagnostic messages (default keymap: <leader> ud)

### Expected Behavior

Diagnostic messages actually get toggled on and off

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    { import = "lazyvim.plugins.extras.lang.clangd" },
  },
})
```

**Comment by dpetka2001** [comment]
Your best bet is to update to Neovim 0.10 to not have this problem. The current implementation of toggling diagnostics is not compatible with 0.9.5

**Comment by dpetka2001** [comment]
unstale
