### ISSUE TITLE
bug: Duplicate Hover When Pressing ‘K’ Twice for Running Rust Main Method

### ISSUE THREAD

**Issue by Zoket** [LazyVim/LazyVim#4208]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.1

### Operating system/version

MacOS Sonoma 14.5

### Describe the bug

I am accustomed to running the Rust main method by pressing ‘K’ twice. The first press of ‘K’ opens the LSP hover, and the second press focuses on the hover and runs it. However, now when I press ‘K’, two hovers appear. 
<img width="324" alt="截屏2024-07-27 22 29 15" src="https://github.com/user-attachments/assets/3a156cec-5fcb-405c-909f-39c945b479e6">
Notice the left border of the hover; there are two hovers with different sizes.
When I press ‘K’ the second time, it focuses on the lower hover, and the upper hover disappears.I cannot select ‘Run’ as a result.
<img width="300" alt="截屏2024-07-27 22 29 49" src="https://github.com/user-attachments/assets/6abdab8c-f8f8-471e-9811-112e76eb39d5">
The contents of these two hovers are identical when I hover over a method:
<img width="1160" alt="截屏2024-07-27 22 30 23" src="https://github.com/user-attachments/assets/d767710d-a2b0-42e0-b6e7-3d181f16c714">
<img width="986" alt="截屏2024-07-27 22 30 54" src="https://github.com/user-attachments/assets/3ef09873-ab83-4e06-a91b-b53a1e2a8636">
If I trigger the hover using ":RustLsp hover actions" instead of the shortcut key, only one hover appears. 

### Steps To Reproduce

1. install LazyVim by offical website doc.
2. open nvim and enable "lang.rust" in Lazy Extras.
3. open a .rs file and press 'K'.

### Expected Behavior

1. it should be one hover when K pressed.
2. use double K to run main method quickly.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
What does `:LspInfo` show?

**Comment by Zoket** [comment]
> What does `:LspInfo` show?

Here it is:
<img width="1073" alt="截屏2024-07-28 09 36 29" src="https://github.com/user-attachments/assets/548dcfc5-6de4-485f-8ec0-c0dd400ad9b4">
Looks like I have two rust analyzer with different name.
but i try to uninstall rust analyzer in mason,neither lsp running then.
<img width="571" alt="截屏2024-07-28 09 31 54" src="https://github.com/user-attachments/assets/1fd1b49b-be56-4639-976c-f7157a509447">

**Comment by Zoket** [comment]
I checked rustaceanvim readme:[https://github.com/mrcjkb/rustaceanvim?tab=readme-ov-file#zap-quick-setup](url)

> Do not call the [nvim-lspconfig.rust_analyzer](https://github.com/neovim/nvim-lspconfig) setup or set up the LSP client for rust-analyzer manually, as doing so may cause conflicts.

But on lazyvim rust extras doc i found some nvim-lspconfig config about vim.lsp.buf.hover().
Is this the reason for the conflict?

**Comment by dpetka2001** [comment]
You have a borked Rust setup. Uninstall rust-analyzer from Mason and Rust from your system as a whole. Then install Rust as per the official [docs](https://www.rust-lang.org/tools/install) and also [rust-analyzer via rustup](https://rust-analyzer.github.io/manual.html#rustup). This isn't a LazyVim bug.

**Comment by Zoket** [comment]
> You have a borked Rust setup. Uninstall rust-analyzer from Mason and Rust from your system as a whole. Then install Rust as per the official [docs](https://www.rust-lang.org/tools/install) and also [rust-analyzer via rustup](https://rust-analyzer.github.io/manual.html#rustup). This isn't a LazyVim bug.

Thank you for your recommendation.
I uninstall rust-analyzer from mason and reinstall it by use `rustup component add rus-analyzer`then everything works fine.
Then I found a [mason issue](https://github.com/williamboman/mason.nvim/issues/1737) with same question shows this is a bug about mason.nvim.
