### ISSUE TITLE
bug: gitui extra does nothing if mason is disabled

### ISSUE THREAD

**Issue by Martin1887** [LazyVim/LazyVim#4212]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10

### Operating system/version

NixOS 24.05

### Describe the bug

Lazygit mappings appear instead of gitui ones and gitui commands are not available if mason is disabled.

### Steps To Reproduce

1. `<space>gg`

Lazygit is tried to be opened instead, with an error if it is not installed.

### Expected Behavior

gitui is opened.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
That's not how `gitui` is set up in LazyVim. It's set up as an Extra that gets installed via the `mason` spec. So, you can't really say that this is a bug. It's just not configured like this. Just don't use it if you don't have Mason enabled.

If you have the binary locally installed, just change the mappings to use `gitui` instead.

**Comment by Martin1887** [comment]
I think that mappings should be set although Mason is disabled to use it locally.

**Comment by dpetka2001** [comment]
You do that in your personal config. No need for duplicate mappings. Not every single derivation of user configs can be taken into account. That's why the personal user configuration exists for users to change things according to their preferences.
