### ISSUE TITLE
bug: escape character '\' not working correctly for search

### ISSUE THREAD

**Issue by baronyoung** [LazyVim/LazyVim#4216]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.1 Release

### Operating system/version

Ubuntu 24.04

### Describe the bug

Escape character '\' isn't working properly for / searches

### Steps To Reproduce

1.  Start a search with '/'
2. Search for a pattern that includes parenthesis, e.g. init(), by typing : 
`/init\(\)`
4. It seems to ignore the escaped characters and doesn't include the parenthesis in the pattern. Neither does searching for 'init()' without escape characters, so I'm left wondering how to search for this at all

### Expected Behavior

For search to work as it always has in vim/neovim.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
Set 
```lua
  {
    "echasnovski/mini.pairs",
    opts = {
      modes = { command = false },
    },
  },
```
in your personal configuration to be able to search with parentheses. By default it's set to `true` in LazyVim.

**Comment by baronyoung** [comment]
I created a file in ~/.config/nvim/lua/plugins with the following contents:
`return {
  "echasnovski/mini.pairs",
  opts = {
    modes = { command = false },
  },
}
`
But it didn't help.  I'm new to LazyVim - is this not where I should place this?

**Comment by dpetka2001** [comment]
Yes, you should just create a file in `~/.config/nvim/lua/plugins/pairs.lua` with contents
```lua
return {
  {
    "echasnovski/mini.pairs",
    opts = {
      modes = { command = false },
    },
  },
}
```
Just to be clear you don't need to escape the parenthesis character. If you want to search for `init()` you just type in search `init()`.

**Comment by baronyoung** [comment]
> Yes, you should just create a file in `~/.config/nvim/lua/plugins/pairs.lua` with contents
> 
> ```lua
> return {
>   {
>     "echasnovski/mini.pairs",
>     opts = {
>       modes = { command = false },
>     },
>   },
> }
> ```
> 
> Just to be clear you don't need to escape the parenthesis character. If you want to search for `init()` you just type in search `init()`.

Oh ok got it.  Yeah that was it.  I'm good now.  Thanks very much.  Now to reprogram 30+ years of muscle memory of using escape characters. :)
