### ISSUE TITLE
bug: warning when using grug-far

### ISSUE THREAD

**Issue by dinhlongviolin1** [LazyVim/LazyVim#4218]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Ubuntu 24.04

### Describe the bug

I am using grug-far to find and replace inside LazyVim. I am new to all of this so I am not sure what is going on. Thanks to any one that would help me look at the issue. I have run checkhealth and everything is ticked as ok.

```
Error executing lua callback: ...share/nvim/lazy/grug-far.nvim/lua/grug-far/farBuffer. lua:259: attempt to call field 'iter' (a nil value)
stack traceback:
•.. share/nvim/lazy/grug-far.nvim/lua/grug-far/farBuffer. lua:259: in function<... share/nvim/lazy/grug-far.nvim/lua/grug-far/farBuffer. lua:25
```

### Steps To Reproduce

Press <leader>sr

### Expected Behavior

A warning will show up

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
This is a problem with your Neovim version that doesn't support the method `iter`. Kindly create an issue at `grug-far`'s repo as this isn't something that can be solved here. It should be corrected in the plugin itself.

**Comment by dinhlongviolin1** [comment]
Thank you very much! That is very helpful. I will do just that.
