### ISSUE TITLE
bug: No :Copilot setup command to sign in to copilot-chat

### ISSUE THREAD

**Issue by s1n7ax** [LazyVim/LazyVim#4221]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.11.0-nightly+0dfcf3f

### Operating system/version

NixOS

### Describe the bug

I tried to run copilot chat using the extra. I have not logged into the account but I see the following error message.

```
No GitHub token found, please use `:Copilot setup` to set it up from copilot.vim or copilot.lua
```

```json
{
  "extras": [
    "lazyvim.plugins.extras.lang.docker",
    "lazyvim.plugins.extras.lang.rust",
    "lazyvim.plugins.extras.lang.tailwind",
    "lazyvim.plugins.extras.lang.typescript",
    "lazyvim.plugins.extras.lang.sql",
    "lazyvim.plugins.extras.lang.yaml",
    "lazyvim.plugins.extras.coding.copilot-chat"
  ],
  "news": {
    "NEWS.md": "6520"
  },
  "version": 6
}
```

![image](https://github.com/user-attachments/assets/bbf57baf-749c-4599-98ee-b27f3e37460f)

But the `Copilot setup` does not exist without the copilot.vim. So I guess you could consider adding copilot.vim as a dependency to the extra module.

### Steps To Reproduce

-

### Expected Behavior

-

**Comment by dpetka2001** [comment]
You also need to enable the `Copilot` extra itself? Since that's the one that has the `copilot.lua` plugin?

**Comment by s1n7ax** [comment]
.

**Comment by dpetka2001** [comment]
Did you enable the Copilot Extra? That will enable you to use the `Copilot` commands.

**Comment by folke** [comment]
you indeed also need the copilot extra
