### ISSUE TITLE
bug: Error when opening grug-far

### ISSUE THREAD

**Issue by turfaa** [LazyVim/LazyVim#4224]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

MacOS 14.5

### Describe the bug

Every time I want to open grug-far using `<Leader>sr`, edgy produces a bunch of errors.

First, the errors are "Buffer with this name already exists". Then the errors become "Failed to rename buffer".

![CleanShot 2024-07-30 at 11 56 28](https://github.com/user-attachments/assets/902310c5-3cba-4836-b00f-09a2b7e9cb5b)

### Steps To Reproduce

1. Open nvim
2. Type `<Leader>sr`
3. Voila!

### Expected Behavior

Open grug-far

### Repro
Sorry I don't understand about this part.

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
Are your plugins up to date? Because I can't reproduce it on my side.

**Comment by turfaa** [comment]
Yes, I have updated the plugins:
![CleanShot 2024-07-30 at 13 26 19](https://github.com/user-attachments/assets/72e012df-673e-4edf-97c4-2e3b25741776)

**Comment by dpetka2001** [comment]
Have you tried reproducing with default LazyVim installation? Here is a screencast where I install LazyVim from scratch and I'm not able to reproduce.

**Comment by turfaa** [comment]
Yup tried it, re-enabled the same plugins as before, and the error is now gone. Not sure why. Thank you! I'm closing this issue.

**Comment by dpetka2001** [comment]
If you can't reproduce it with default LazyVim installation, then most likely it's something in your personal config that's causing the issue. Either way, since you got it working now all good. 

Just for future reference, do try to test potential problems you encounter with a default LazyVim installation. If all works ok with it, then you should probably looking at your personal configuration to see what causes the problem.
