### ISSUE TITLE
bug: custom omnisharp lsp handler not properly loaded

### ISSUE THREAD

**Issue by MikaelElkiaer** [LazyVim/LazyVim#423]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.0-dev-1166+g06aed7c17

### Operating system/version

EndeavourOS Linux x86_64

### Describe the bug

I am trying to set up omnisharp and omnisharp_extended in LazyVim, which I have had successfully set up before using LazyVim.

I have added in `servers`: https://github.com/MikaelElkiaer/nvim-config/blob/5c3a829ea68c376c60fb0ca88fbaac3e5eb8c895/lua/plugins/lsp.lua#L16-L24

and `setup`: https://github.com/MikaelElkiaer/nvim-config/blob/master/lua/plugins/lsp.lua#L43-L64

When first opening a C# project, LspInfo looks like this:
![2023-03-13-071835_405x161_scrot](https://user-images.githubusercontent.com/2102306/224622573-36d222aa-19bc-4f71-90d5-96a12b4e0e27.png)

But then when something (not sure what) has finished loading, the config seems to be reloaded without the handler:
![2023-03-13-071852_371x143_scrot](https://user-images.githubusercontent.com/2102306/224622675-54e4d979-f360-47c8-a2ed-11d62e63893d.png)

I have also tried moving the
```
handlers = {
  ["textDocument/definition"] = require('omnisharp_extended').handler,
}
```
bit to the `on_attach` below - does not work.
I also tried switching to csharp_ls and csharpls_extended  - same issue.

### Steps To Reproduce

1a. Use my config: https://github.com/MikaelElkiaer/nvim-config
1b. Add omnisharp to `server` and `setup` sections of lsp opts, as in the two links above
2. Open a C# workspace
3. Wait for omnisharp to finish loading the workspace
4. Use go-to-definition

### Expected Behavior

Had expected the lspconfig for omnisharp to keep the custom lsp handlers.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	"folke/tokyonight.nvim",
	{ "LazyVim/LazyVim", import = "lazyvim.plugins" },
	-- add any other plugins here
	{
		"neovim/nvim-lspconfig",
		dependencies = {
			"Hoffs/omnisharp-extended-lsp.nvim",
		},
		opts = {
			ensure_installed = {
				"omnisharp",
			},
			servers = {
				omnisharp = {},
			},
			setup = {
				omnisharp = function(_, opts)
					opts.handlers = {
						["textDocument/definition"] = require("omnisharp_extended").handler,
					}
          require("lazyvim.util").on_attach(function(client, _)
            -- INFO https://github.com/OmniSharp/omnisharp-roslyn/issues/2483
            if client.name == "omnisharp" then
              client.server_capabilities.semanticTokensProvider.legend = {
                tokenModifiers = { "static" },
                tokenTypes = { "comment", "excluded", "identifier", "keyword", "keyword", "number", "operator",
                  "operator", "preprocessor", "string", "whitespace", "text", "static", "preprocessor", "punctuation",
                  "string", "string", "class", "delegate", "enum", "interface", "module", "struct", "typeParameter",
                  "field", "enumMember", "constant", "local", "parameter", "method", "method", "property", "event",
                  "namespace", "label", "xml", "xml", "xml", "xml", "xml", "xml", "xml", "xml", "xml", "xml", "xml",
                  "xml", "xml", "xml", "xml", "xml", "xml", "xml", "xml", "xml", "xml", "regexp", "regexp", "regexp",
                  "regexp", "regexp", "regexp", "regexp", "regexp", "regexp" }
              }
            end
          end)
					return false
				end,
			},
		},
	},
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
I looked into this and it's actually just LspInfo that only shows the handlers when the lsp server is not connected yet.
Once connected it shows a different view for some reason. A bit odd.

Check the relevant code here https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/ui/lspinfo.lua

**Comment by MikaelElkiaer** [comment]
Thanks for clarifying that.

Unfortunately, this means that there is another reason that my custom definition handler is not working. :disappointed:

**Comment by folke** [comment]
It worked in my tests. At least the extended definition was called instead of the regular one. Not sure if their output was correct though
