### ISSUE TITLE
bug: lazyvim.json migration breaking the existing extra module name

### ISSUE THREAD

**Issue by s1n7ax** [LazyVim/LazyVim#4236]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.11.0-nightly+4b852bc

### Operating system/version

NixOS

### Describe the bug

I have this starter config of LazyVim with nvim-java pre-configured. There I have added [dap-core](https://github.com/nvim-java/starter-lazyvim/blob/1d80ba430c6d2414f0e6fa7e6931d22eabd4c279/lazyvim.json#L3) extra. When neovim is opened for the first time, it shows a notification saying it's migrating the json and after the migration, extra module name has repeated twice.

https://github.com/nvim-java/starter-lazyvim

https://github.com/user-attachments/assets/83d25324-7b79-4aae-8728-6775df0658a3

### Steps To Reproduce

-

### Expected Behavior

-

### Repro

```lua
-
```

**Comment by dpetka2001** [comment]
It seems that if you set any kind of `version` in your `lazyvim.json` there's no issue. Conversely, if you change [this line](https://github.com/LazyVim/LazyVim/blob/12818a6cb499456f4903c5d8e68af43753ebc869/lua/lazyvim/util/json.lua#L66) to be like [this one](https://github.com/LazyVim/LazyVim/blob/12818a6cb499456f4903c5d8e68af43753ebc869/lua/lazyvim/util/json.lua#L71) the problem doesn't occur even if you don't have a `version` in your `lazyvim.json`. 

Not sure what the correct approach should be, so let's wait for Folke to weigh in on this after he comes back. In the meantime if you just append to your `lazyvim.json` any kind of `version = value` you will not meet this problem.

**Comment by s1n7ax** [comment]
.

**Comment by folke** [comment]
That's to be expected, since your initial lazyvim.json is not valid. Won't fix
