### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by thepenguinthatwants** [LazyVim/LazyVim#4245]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.1

### Operating system/version

ARCH

### Describe the bug

Everytime I open neovim it gives this alert

Error detected while processing BufReadPost Autocommands for "*":
Error executing lua callback: .../share/nvim/lazy/LazyVim/lua/lazyvim/config/autocmds.lua:129: attempt to compare nil with number
stack traceback:
        .../share/nvim/lazy/LazyVim/lua/lazyvim/config/autocmds.lua:129: in function <.../share/nvim/lazy/LazyVim/lua/lazyvim/config/autocmds.lua:125>
        vim/filetype.lua: in function ''
        vim/filetype.lua: in function 'match'
        /usr/share/nvim/runtime/filetype.lua:14: in function </usr/share/nvim/runtime/filetype.lua:10>

### Steps To Reproduce

I just open neovim  and it gives this error.

### Expected Behavior

It should not have such.

I noticed that if I remove this from my settings I won't get the error.

require("lazy").setup("core.plugins.auto")

But the idea was to have modularized way that every single plugin had own file that defines settings etc. I removed all the plugins leaving only one it still gives such error.

### Repro

```lua
Is there bug with this command? I tried to open it with this command but it automatically loads all of my neovim plugins that I haven't set here.

In my default configs which have these set, maybe it somehow affect the minimal repro.lua file?

local lazypath = vim.fn.stdpath 'data' .. '/lazy/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system {
		'git',
		'clone',
		'--filter=blob:none',
		'https://github.com/folke/lazy.nvim.git',
		'--branch=stable', -- latest stable release
		lazypath,
	}
end

-- Remap space as leader key
-- Must be before lazy
vim.keymap.set({ "n", "v" }, "<Space>", "<Nop>", { silent = true })
vim.g.mapleader = " "
vim.g.maplocalleader = ' '

local lazypath = vim.fn.stdpath 'data' .. '/lazy/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system {
		'git',
		'clone',
		'--filter=blob:none',
		'https://github.com/folke/lazy.nvim.git',
		'--branch=stable', -- latest stable release
		lazypath,
	}
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup("core.plugins.auto")
```

**Comment by thepenguinthatwants** [comment]
Adding a value
vim.g.bigfile_size = vim.g.bigfile_size or 1024 * 1024 -- Default to 1MB to ~/.local/share/nvim/lazy/LazyVim/lua/lazyvim/config/autocmds.lua 

Somehow fixes it.

**Comment by dpetka2001** [comment]
You're not using Lazyvim. But you've tried to incorporate Lazyvim to your config. That's the problem. Use the Lazyvim starter template and build from there and you'll see you won't have this error.
