### ISSUE TITLE
bug: Omnisharp doesn't fully work with editor.fzf enabled

### ISSUE THREAD

**Issue by Sheol27** [LazyVim/LazyVim#4258]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.1

### Operating system/version

MacOs

### Describe the bug

If editor.fzf is enabled, OmniSharp Go To Definitions doesn't work, this is the error:

Error executing lua: ...lazy/omnisharp-extended-lsp.nvim/lua/generic_command.lua:66: Telescope is not available, this function only works with Telescope.│

### Steps To Reproduce

Enable editor.fzf, open a C# project and try to do a Go To Definition

### Expected Behavior

I expect everything to work

**Comment by dpetka2001** [comment]
Try to change these [lines](https://github.com/LazyVim/LazyVim/blob/12818a6cb499456f4903c5d8e68af43753ebc869/lua/lazyvim/plugins/extras/lang/omnisharp.lua#L55-L57) to 
```lua
LazyVim.has("telescope.nvim") and function()
  require("omnisharp_extended").telescope_lsp_definitions()
end or function()
  require("omnisharp_extended").lsp_definitions()
end,
```
and see if it works correctly. I don't do csharp myself, so can't properly test it out.

**Comment by Sheol27** [comment]
It worked! Thank you so much !

**Comment by dpetka2001** [comment]
If it worked, would you be kind to submit a PR that fixes this? Like i said i don't do csharp and can't test this thoroughly, so this was just a guess from my part.

**Comment by dpetka2001** [comment]
Not stale.
