### ISSUE TITLE
bug: key repetition failed

### ISSUE THREAD

**Issue by ArnaudD-FR** [LazyVim/LazyVim#4267]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.1

### Operating system/version

Ubuntu 24.04

### Describe the bug

Using LazyVim prevent key repetition. For example:

 - Keeping `x` key to delete characters delete only one character.
 - Keeping `d` key to delete multiple lines delete only one line.

### Steps To Reproduce

Use the repro script or the default LazyVim configuration

```bash
# Remove any LazyVim previous files:
rm -rf ~/.local/{share,state}/nvim/ ~/.cache/nvim ~/.config/nvim

# Install LazyVim starter configuration
git clone https://github.com/LazyVim/starter ~/.config/nvim

# Start neovim
nvim
```

Once in neovim keep pressing `x` or `d` repetition will fail

### Expected Behavior

Key press repetition should continue for ever

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
Maybe you have some kind of conflict with your terminal mappings. On kitty with a default LazyVim installation this is how it behaves.

[Screencast 2024-08-06 21:02:32.webm](https://github.com/user-attachments/assets/024035a1-5ee8-4939-a58c-a12f588ed3a0)

So, I really don't think it's a LazyVim bug.

**Comment by ArnaudD-FR** [comment]
I thought about this and I'm using terminator. But my concern is without LazyVim it is OK, with LazyVim it failed...

So LazyVim or a basic plugin change something.

**Comment by dpetka2001** [comment]
I just showed you a screencast where this doesn't happen. I installed LazyVim from scratch on Kitty terminal and then pressed both `x` and `d` without letting go the of the key and the keymap correctly repeated itself. So, it's highly likely it's something on your end.

**Comment by ArnaudD-FR** [comment]
I watch your screencast and it works out of the box. But it does not explain me what can be wrong on my setup and why it worked on neovim without LazyVim.

I didn't had this issue before coming back from vacation and upgrading my setup...

For your information I just tried using:
 - gnome terminal or terminator
 - zsh or bash

Each time the same issue.

So I believe something changed on LazyVim or on basic plugin.

I already tried to revert LazyVim to a old version and same issue but plugins out of the box are still downloaded at the latest version.

Is it possible from LazyVim local clone to disable all plugins and enable them one by one to get the culprit component? Can you guide on those steps as I'm not sure to do the right things?

**Comment by dpetka2001** [comment]
I would suggest that you try with a default LazyVim installation or the `repro.lua`. I don't know what's wrong with your setup. I just know that I can't reproduce this with default LazyVim installation. For a default LazyVim installation just do the following
```bash
1. mkdir ~/.config/lazytest
2. git clone https://github.com/LazyVim/starter ~/.config/lazytest
3. NVIM_APPNAME=lazytest nvim and wait for the installation to complete
4. While Lazy UI is still open press `C` to check and `U` to make sure everything is updated
5. Restart Neovim with command from step 3
```
For cleanup 
```bash
rm -rf ~/.config/lazytest
rm -rf ~/.local/share/lazytest
rm -rf ~/.local/state/lazytest
rm -rf ~/.cache/lazytest
```

**Comment by ArnaudD-FR** [comment]
After investigation my issue is related to clipboard.

In LazyVim/lua/lazyvim/config/init.lua:185 when I comment the following lines everything is working well:
```lua
      -- if lazy_clipboard ~= nil then
      --   vim.opt.clipboard = lazy_clipboard
      -- end
```

Effectively key like `u` was repeating correctly.

And you don't have this issue because clipboard is disabled when using ssh from LazyVim/lua/lazyvim/config/options.lua:58 :
```lua
-- only set clipboard if not in ssh, to make sure the OSC 52
-- integration works automatically. Requires Neovim >= 0.10.0
opt.clipboard = vim.env.SSH_TTY and "" or "unnamedplus" -- Sync with system clipboard
```

I tested using a `ssh localhost` and I don't have this issue.

I don't understand why the `unamedplus` clipboard introduce so much latency making neovim bugs.

**Comment by dpetka2001** [comment]
I didn't use a ssh connection. `clipboard` was set to `unnamedplus` for me. So, it's still something on your end. Try to change the Neovim clipboard provider tool to something else. I use `xsel` and don't have this problem. It's something specific to your system.

**Comment by ArnaudD-FR** [comment]
Thanks @dpetka2001 !  This issue is definitely not related to LazyVim so I close it
