### ISSUE TITLE
bug: Error detected while processing TextChanged

### ISSUE THREAD

**Issue by idelice** [LazyVim/LazyVim#4271]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

macos 14.3

### Describe the bug

I get this error thrown at me sporadically:

```
   Error  19:38:07 msg_show.lua_error Error detected while processing TextChanged Autocommands for "<buffer=33>":
19:38:07 msg_show Error executing lua callback: ...lar/neovim/0.10.0/share/nvim/runtime/lua/vim/snippet.lua:376: attempt to index field '_session' (a nil value)
stack traceback:
	...lar/neovim/0.10.0/share/nvim/runtime/lua/vim/snippet.lua:376: in function <...lar/neovim/0.10.0/share/nvim/runtime/lua/vim/snippet.lua:374>
```

It often happens when my nvim instance is not in view and i get back to it and enter edit mode.

### Steps To Reproduce

n/a

### Expected Behavior

I expect no errors being thrown.

**Comment by dpetka2001** [comment]
LazyVim doesn't set any `TextChanged` autocmds. This autocmd comes from Neovim core. `_session` seems to be an internal table in `vim.snippet`, which keeps track if you're inside a snippet session or not. 

I believe this has nothing to do with LazyVim itself and should be reported in Neovim upstream.

**Comment by maxkemzi** [comment]
I'm also encountering this error.

**Neovim version (nvim -v)**
0.10.0

**Operating system/version**
Debian 12

Error start to appear with each action in a certain buffer. After restarting neovim the errors disappear.

**Comment by maxkemzi** [comment]
This seems to be a neovim issue. I found the following issue that accurately describes my situation: https://github.com/neovim/neovim/issues/29525.

**Comment by maxkemzi** [comment]
The neovim 0.10.1 update seems to have solved the problem. Let us know if the 0.10.1 update solved the problem for you as well.
