### ISSUE TITLE
bug: enable spell ft=text etc

### ISSUE THREAD

**Issue by osamuaoki** [LazyVim/LazyVim#4274]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.1-dev-101+g18a9ae169

### Operating system/version

Linux, Debian 12 (stable)

## Issues

* Spell check not active for files with *.txt extension as opened
* Spell check not active for ft=text
* Spell check not active for files with *.adoc extension as opened

## Related issue

This seems to be related to recently fixed issues:

* https://github.com/LazyVim/LazyVim/issues/3973
* https://github.com/LazyVim/LazyVim/issues/3975

It looks like we may need additional fixes.  This issue is related to initialization and autocmd.

## test case and issues

I created a simple file `test.txt` as:

```
tyypo
```

Opening it with nvim with freshly installed lazyvim w/o any customization behaves as follows:

Open `test.txt` with nvim (with unset NVIM_APPNAME):

* as opened: no red underline (BAD)
* `:set ft?` yields `filetype:text`.
* `:=vim.o.spell` is true
* `:set ft=markdown` yields red underline to indicate typo.
* `:set ft=text`     erases red underline. (BAD)
* `:set ft=markdown` yields red underline to indicate typo.
* `:set ft=text`     erases red underline. (BAD)
* `:set ft=asciidoc` yields red underline to indicate typo.

I expected redunder line for `ft=text`.

## reference case 1

I tried the same after renaming the file to `test.md`

Open `test.md` with nvim (with unset NVIM_APPNAME):

* as opened: red underline (GOOD)
* `:set ft?` yields `filetype:markdown`.
* `:=vim.o.spell` is true
* `:set ft=text`     erases red underline. (BAD)
* `:set ft=asciidoc` yields red underline to indicate typo. (GOOD)
* `:set ft=text`     erases red underline. (BAD)
* `:set ft=markdown` yields red underline to indicate typo. (GOOD)

## reference case 2

I tried the same but renaming file to `test.adoc`

Open with nvim (with unset NVIM_APPNAME):

* as opened: no red underline (BAD)
* `:set ft?` yields `filetype:asciidoc`.
* `:=vim.o.spell` is false
* `:set ft=asciidoc` no red underline (BAD)
* `:=vim.o.spell` is false
* `:set ft=text`     no red underline.(BAD)
* `:=vim.o.spell` is true (OK but why?)
* `:set ft=asciidoc` yields red underline to indicate typo. (GOOD)
* `:set ft=text`     erase red underline. (BAD)

## Desired behavior

* Spell check active for files with *.txt extension as opened
* Spell check active for ft=text
* Spell check active for files with *.adoc extension as opened

## note on related fixes etc.

I looked for spell value change in LazyVim and found:
`~/.local/share/nvim/lazy/LazyVim/lua/lazyvim/config/autocmds.lua`:

```
-- wrap and check for spell in text filetypes
vim.api.nvim_create_autocmd("FileType", {
  group = augroup("wrap_spell"),
  pattern = { "text", "plaintex", "typst", "gitcommit", "markdown" },
  callback = function()
    vim.opt_local.wrap = true
    vim.opt_local.spell = true
  end,
})
```

The recent commits modified this part:

927031a ("fix(autocmds): fixed pattern for autocommand to autoenable wrap and spell in text files (#3975)", 2024-07-10)

Reading bug reports i see the following recent fixes

* https://github.com/LazyVim/LazyVim/issues/3973
* https://github.com/LazyVim/LazyVim/issues/3975

I also checked LazyVim and there are 2 locations spell value is changed:
```
 $ rg "vim.*spell"
lua/lazyvim/config/autocmds.lua
98:    vim.opt_local.spell = true

lua/lazyvim/util/news.lua
79:  vim.opt_local.spell = false
```

I suspect that this may be some kind of issue related to delayed loading.

## workaround

For activating spell for *.adoc files, I cando it by adding modeline specifying `ft=asciidoc`.

### Repro

```lua
I used plain lazyvim startup as described at
https://www.lazyvim.org/installation
as the test system.
```

**Comment by dpetka2001** [comment]
It seems this only happens when you open Neovim with a file argument and only on the first buffer opened. If you do `nvim test.txt test2.txt` then the file `test2.txt` will correctly show the typos. Only `test.txt` doesn't show anything. Weird, let's hope Folke will have more insight as to why this happens.

**Comment by osamuaoki** [comment]
Very interesting and strange.

Further on this point:

I do suffer problem with opening a single `test.adoc` (ft=asciidoc) when opened by zero-customized LazyVim.  For this case, multiple adoc files doesn't fix situation.

But when I use somewhat customized LazyVim, I don't suffer problem at all even with a single file.

**Comment by dpetka2001** [comment]
That's because this filetype is not present in the autocmd that sets `spell` and `wrap` for specific filetypes. That's a user configuration issue. You could submit a PR that adds this filetype to the corresponding autocmd if you like, but it has nothing to do with the problem at hand regarding `*.txt` files.

**Comment by dpetka2001** [comment]
Ok, I think I found what's causing this behavior. 

It's this [option](https://github.com/LazyVim/LazyVim/blob/12818a6cb499456f4903c5d8e68af43753ebc869/lua/lazyvim/config/options.lua#L99). If you comment out this option then it behaves correctly even on the first buffer. 

From reading `:h 'spo'`, it seems that `noplainbuffer` only spellchecks when syntax is enabled. My guess is that somehow when invoking Neovim with file arguments the first file doesn't get syntax enabled in time for that option to take effect?? 

Just to be sure that this is not LazyVim related, I also tried without LazyVim with the following minimal repro
```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
-- local lazypath = vim.fn.expand("~/projects/plugins/lazy.nvim/")
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

vim.opt.spelloptions:append("noplainbuffer")

-- install plugins
local plugins = {
	{ "folke/tokyonight.nvim" },
	-- add any other plugins here
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
	dev = {
		path = "~/projects/plugins/",
	},
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here

local function augroup(name)
	return vim.api.nvim_create_augroup("lazyvim_" .. name, { clear = true })
end
vim.api.nvim_create_autocmd("FileType", {
	group = augroup("wrap_spell"),
	pattern = { "text", "plaintex", "typst", "gitcommit", "markdown" },
	callback = function()
		vim.opt_local.wrap = true
		vim.opt_local.spell = true
	end,
})
```
and it has the same behavior with that option set when you open a `.txt` file. It does not happen with a Markdown file.

**Comment by osamuaoki** [comment]
Interesting.  Setting `:set syntax=markdown`, or `:set syntax=rst` on `test.txt` enables spell check.

I know `lua/lazyvim/config/autocmds.lua` doesn't list `asciidoc`.  But opening `test.txt` and setting `:set ft=asciidoc` magically enable spell check.

**Comment by osamuaoki** [comment]
Oops.

**Comment by osamuaoki** [comment]
Sorry.  that was accident.  This should be open.  

Certainly, `opt.spelloptions:append("noplainbuffer")` seems to be involved.

I think understanding around `asciidoc` issue is important.  That was meant to be data points.

I was aware that only limited filetypes are listed in autocmd.  Please note not only asciidoc but also rst is missing there.  

I don't know if simply adding these are the right fix for asciidoc.

I also realize setting filetype seems to set syntax.

Your post reminded me to check few things:
* opening `text.txt` doesn't activate spell check (I suppose due to "noplainbuffer")
* opening `text.md` activates spell check (*md sets ft=syntax=markdown)
* opening `text.rst` activates spell check (rst is not in the list for autocmd.  So why?)
* `:set ft=asciidoc` on `text.txt` sets `syntax=asciidoc` and spell check active (?)
* `:set ft=asciidoc` on `text.adoc` sets `syntax=asciidoc` and spell check active (?)
* `:set ft=rst` on `text.txt` sets `syntax=rst` and spell check active (?)
* `:set ft=markdown` on `text.txt` sets `syntax=markdown` and spell check active

**Comment by osamuaoki** [comment]
For program, spo=noplainbuffer is a very reasonable choice to silence spell checking on variables etc. inside of code.

For now, I decided to work around this issue by adding one keymap:
```
-- Change spelloptions
map("n", "<leader>uo", function()
  if vim.bo.spelloptions == "" then
    vim.bo.spelloptions = "camel"
  elseif vim.bo.spelloptions == "camel" then
    vim.bo.spelloptions = "noplainbuffer"
  else
    -- default
    vim.bo.spelloptions = ""
  end
  vim.notify(("spelloptions = %s †"):format(vim.bo.spelloptions))
  wk_update_desc("<leader>uo", function()
    return ("spelloptions = %s †"):format(vim.bo.spelloptions)
  end)
end, { desc = ("spelloptions = %s †"):format(vim.bo.spelloptions) })
wk_update_desc("<leader>uo", function()
  return ("spelloptions = %s †"):format(vim.bo.spelloptions)
end)
```

I should make above with a bit more elegant function like `LazyVim.toggle.wrap() {}` but for now I use repeated call to a brute logic code `wk_update_desc`: 

```
local wk_update_desc = function(lhs, desc_fn)
  local ok, wk = pcall(require, "which-key")
  if ok then
    wk.add({
      {
        lhs,
        desc = desc_fn,
        icon = "",
      },
    })
  end
end
```

**Comment by dpetka2001** [comment]
I believe we should add `vim.bo[event.buf].spelloptions = ""` [here](https://github.com/LazyVim/LazyVim/blob/12818a6cb499456f4903c5d8e68af43753ebc869/lua/lazyvim/util/plugin.lua#L89), since if there won't be a Treesitter parser available it makes sense to have `spelloptions` empty?? 

Again, I believe Folke will know what is the better approach concerning this matter.

**Comment by LorenzoBettini** [comment]
I think that opening a file directly is a frequent operation, so the behavior described here (which I also experienced without understand what was going on before getting to this issue) should be somehow taken into consideration :)

**Comment by folke** [comment]
ok, so what should be changed?
Remove that option?

**Comment by dpetka2001** [comment]
Either that or in the old `lazyfile` i had added the option there right after setting `vim.bo[buf].syntax = ft` when there's no treesitter parser available and it seemed to work. Should be the same for `snacks.quickfile` no? I tested it and it seems to be working with `snacks.quickfile` as well when you set that option to empty string.

**Comment by folke** [comment]
should not be added to quickfile, since not all snack users want that option.
removing from `options.lua` is fine for me if that solves it

**Comment by dpetka2001** [comment]
Yes, removing it also works. I just created a `test.txt` with contents `tyyypo` and tested with and without that option and it seems to work. Please see also for yourself. Just do `nvim test.txt` with and without that option.

**Comment by folke** [comment]
just pushed an update

**Comment by LorenzoBettini** [comment]
Is it fixed in v13? I still see the bad behavior after updating

**Comment by dpetka2001** [comment]
It will be on [13.1.0](https://github.com/LazyVim/LazyVim/pull/4733), but a new release hasn't been made yet. You might want to follow latest HEAD if you'd like as described in the [docs](https://www.lazyvim.org/configuration/lazy.nvim).

**Comment by LorenzoBettini** [comment]
No problem, I can wait :)
I just wanted to be sure I didn't miss anything.

**Comment by LorenzoBettini** [comment]
> It will be on [13.1.0](https://github.com/LazyVim/LazyVim/pull/4733), but a new release hasn't been made yet. You might want to follow latest HEAD if you'd like as described in the [docs](https://www.lazyvim.org/configuration/lazy.nvim).

Thanks! It's fixed now :)
