### ISSUE TITLE
bug: terminal is broken when running in vscode

### ISSUE THREAD

**Issue by moetayuko** [LazyVim/LazyVim#4280]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.1

### Operating system/version

Arch

### Describe the bug

lazyvim comes with some shortcuts to toggle terminal
https://github.com/LazyVim/LazyVim/blob/12818a6cb499456f4903c5d8e68af43753ebc869/lua/lazyvim/config/keymaps.lua#L160-L165

when running in vscode through VSCode Neovim, pressing these keys will open the terminal in a non-interactable text buffer

### Steps To Reproduce

1. enable the vscode extra of LazyVim
2. install VSCode Neovim extension in vscode
3. toggle terminal through the shortcuts

### Expected Behavior

use vscode's builtin terminal feature

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
You can set in your `keymaps.lua` the following
```lua
if vim.g.vscode then
  vim.keymap.set("n", "<c-/>", [[<cmd>call VSCodeNotify('workbench.action.terminal.toggleTerminal')<cr>]])
end
```
LazyVim main configuration is for using in Neovim in a terminal. There's not much in the vscode Extra, so users have to additionally customize things. I also tried the default `lazyterm` and it does open in a separate window, but you can interact with it. I run `ls -al` and it listed the contents of the directory for example. Never the less the default built-in VsCode terminal does seem better, but you have to configure that yourself.

In my personal opinion, this is not a bug, but a user configuration issue.

**Comment by moetayuko** [comment]
yea I know I can override the keymap in my config, but IMO it *should* be handled by LazyVim.

**Comment by dpetka2001** [comment]
Like I said LazyVim doesn't do much configuration for VsCode. It's mainly to be used in Neovim in terminal. The rest of VsCode configuration should be up to the user.

**Comment by moetayuko** [comment]
> Like I said LazyVim doesn't do much configuration for VsCode. It's mainly to be used in Neovim in terminal. The rest of VsCode configuration should be up to the user.

This is almost true, but considering that the vscode extra disables most LazyVim features and leaves a few for use in vscode environment, these enabled ones *should* work out of the box rather than leaving for the users to handle compatibility.

**Comment by dpetka2001** [comment]
The `lazyterm` **does work** out of the box. I've tried it and it works fine (though I just did some basic testing, so not 100% sure if I missed something). Still, I believe the built-in VsCode terminal is better for VsCode. But, that's up to the user to configure it. 

Either way the maintainer has the final say, so wait for his input. You could also just submit a PR for the VsCode Extra that changes the keymap and the maintainer will either accept it or not. It is that simple.

**Comment by folke** [comment]
Feel free to make a PR to add that specific keymap
