### ISSUE TITLE
bug: some terminal shortcuts not working

### ISSUE THREAD

**Issue by vdegenne** [LazyVim/LazyVim#4289]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Fedora 39

### Describe the bug

I'm used to shortcuts like **ctrl+l** (clear terminal) or **ctrl+k** (delete all characters after current caret position) in Linux terminals.
When using **ctrl+/** inside LazyVim to open a modal terminal window, these shortcuts won't work and will cause the modal window to lose focus.

### Steps To Reproduce

1. Open a new LazyVim session (`vim`)
2. Open a terminal window (shortcut: ctrl+/)
3. Write something
4. Use ctrl+a to place the caret at the start of the line (notice this chord works)
5. Use ctrl+k supposedly clearing the line *but fails*

### Expected Behavior

Expect some of these keychords to work out of the box.

**Comment by dpetka2001** [comment]
This is not a bug. These keymaps are [being used here](https://github.com/LazyVim/LazyVim/blob/12818a6cb499456f4903c5d8e68af43753ebc869/lua/lazyvim/config/keymaps.lua#L171-L172) and since you don't like this behavior, you can change them in your personal configuration to whatever you want.

**Comment by vdegenne** [comment]
@dpetka2001 Thanks for your answer. I'm not sure what these keymaps are for, unless I am wrong Ctrl+/ only accounts for opening a terminal window in a centered popup window, and it's not possible to open several popup windows like that. Using ctrl+l or ctrl+k cause the caret to go back to the buffer behind this popup which has no use.

Are these keymaps obsolete?

**Comment by dpetka2001** [comment]
If you're using `edgy`, then you can open different terminals side by side and switch between them with the keys being mentioned. Again you can change this behavior in your personal configuration. Just delete those keys if you don't like them. But it's not a bug. It's been like this by design to have conformity when changing windows in normal and terminal mode.

**Comment by vdegenne** [comment]
Ok it makes sense, thanks for sharing your knowledge. I'm used to tmux but I should consider practicing opening terminals directly inside vim windows, that looks handy, thanks for the eye opener.

Before closing this thread, I know it's not good practice to comment keymaps in the LazyVim config file directly, what should I write inside the user-level keymaps config file to dismiss a global keymap like that?

**Comment by dpetka2001** [comment]
Try in `~/.config/nvim/lua/config/keymaps.lua` to delete them I guess? So, something like
```lua
vim.keymap.del("t", "<c-l>")
```

**Comment by vdegenne** [comment]
Thanks so much, that works 🔥❤️
