### ISSUE TITLE
bug: vue style commentstring is wrong

### ISSUE THREAD

**Issue by tkkcc** [LazyVim/LazyVim#4292]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.1

### Operating system/version

archlinux

### Describe the bug

comment in vue style use wrong commentstring
```vue
<style scoped>
<!-- .logo { -->
<!--   height: 6em; -->
<!--   padding: 1.5em; -->
<!--   will-change: filter; -->
<!--   transition: filter 300ms; -->
<!-- } -->
</style>

```

### Steps To Reproduce
1. `npm create vite@latest test -- --template vue-ts`
2. use fresh LazyVim, enable lang.vue, open `test/src/App.vue`, comment in style 

### Expected Behavior
inside
```vue
<style scoped>
/* .logo { */
/*   height: 6em; */
/*   padding: 1.5em; */
/*   will-change: filter; */
/*   transition: filter 300ms; */
/* } */
</style>

```
outside:
```vue
<!-- <style scoped> -->
<!-- .logo { -->
<!--   height: 6em; -->
<!--   padding: 1.5em; -->
<!--   will-change: filter; -->
<!--   transition: filter 300ms; -->
<!-- } -->
<!-- </style> -->
```

### attempt
i tried this, but outside not work
```lua
    {
      "folke/ts-comments.nvim",
      opts = {
        lang = {
          vue = {
            "<!-- %s -->",
            style_element = "/* %s */",
          },
        },
      },
    },

```

**Comment by dpetka2001** [comment]
Try 
```lua
        vue = {
          "<!-- %s -->",
          style_element = "<!-- %s -->",
          raw_text = "/* %s */",
        },
```

**Comment by tkkcc** [comment]
@dpetka2001 no change

**Comment by tkkcc** [comment]
nice! didn't notice it's raw_text inside.

**Comment by dpetka2001** [comment]
You should just press `<leader>uI` (capital `i`) for `InspectTree` and then go throughout the different nodes and see how Treesitter recognizes them. For me the above seems to be working

[Screencast 2024-08-11 18:23:16.webm](https://github.com/user-attachments/assets/928c7e94-02e5-444a-8458-5dbf89dce912)

**Comment by iamxiaojianzheng** [comment]
@dpetka2001  Wonder why the same configuration didn't work for me.

I annotated the css code with gcc, and the end result is as follows.

```css
<!-- .deploy-table-body { -->
<!--   width: 80%; -->
<!--   margin-left: 10%; -->
<!--   margin-top: 30px; -->
<!---->
<!-- } -->
```

**Comment by dpetka2001** [comment]
Do you have the css treesitter parser installed?

**Comment by iamxiaojianzheng** [comment]
> Do you have the css treesitter parser installed? 

Yes

However, it doesn't seem to work in vue.

**Comment by dpetka2001** [comment]
I didn't use `gcc` for every line. I just visually selected the whole text as also shown in the video and pressed `gc`. Not sure if this makes any difference. I don't do any web dev however and am not sure why this could be. Better wait for maintainer's input when he returns.
