### ISSUE TITLE
bug: Error after disabling neo-tree.

### ISSUE THREAD

**Issue by kenbankspeng** [LazyVim/LazyVim#4293]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

Release v0.10.1 

### Operating system/version

MacOS 14.5 (Sonoma)

### Describe the bug

After disabling neo-tree, I get: 

Failed (1)
  - neo-tree.nvim, enabled = false - clone failed
        Cloning into '.../nvim/.repro/data/nvim/lazy/neo-tree.nvim, enabled = false'...
        fatal: unable to access 'https://github.com/vim-neo-tree/neo-tree.nvim, enabled = false.git/': URL rejected: Malformed input to a URL function

### Steps To Reproduce

plugins\disable.lua
```
return {
  'vim-neo-tree/neo-tree.nvim, enabled = false',
}
```

### Expected Behavior

No error occurs

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    { 'vim-neo-tree/neo-tree.nvim, enabled = false' }
  },
})
```

**Comment by dpetka2001** [comment]
It should be `nvim-neo-tree/neo-tree.nvim` and not `vim-neo-tree/neo-tree.nvim` that you typed.

**Comment by kenbankspeng** [comment]
Thak you. That's the last time I'm ever askig my assistat to do aythig!
