### ISSUE TITLE
feature: Prompting for name when using some code actions

### ISSUE THREAD

**Issue by vdegenne** [LazyVim/LazyVim#4294]
### Did you check the docs?

- [X] I have read all the LazyVim docs
- [X] This is not a request for a new or existing extra (see above)

### Is your feature request related to a problem? Please describe.

Here's a screencast when extracting a selection to a constant, you can see the constant is automatically named `newLocal`, it'd be great to have a popup that prompts for the name we'd like to use, similar to `<leader> <c> <r>` which is used in the video as well to showcase a workaround but is an extra step which I think can be combined in one.

https://github.com/user-attachments/assets/0a8cc9d6-a392-4de6-bdf5-8ab46b13bbe9

### Describe the solution you'd like

A popup appears when extracting a selection to a local constant or function that prompts for a name.

### Describe alternatives you've considered

Reaching the object that was created and using `<leader> <c> <r>` to rename it manually.

**Comment by folke** [comment]
That's up to the LSP server.
