### ISSUE TITLE
bug: Press space is quitting neovim

### ISSUE THREAD

**Issue by annacruz** [LazyVim/LazyVim#4298]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.1

### Operating system/version

MacOS 14.5

### Describe the bug

Everytime that I open lazyvim when I'm in the command mode and press space it's going back to the terminal.

### Steps To Reproduce

1. Just open neovim

### Expected Behavior

Space open the lazyvim options, and works as <Leader>

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
Can you show a video?

**Comment by dpetka2001** [comment]
Also, since you mentioned it happens in the command mode what does `:verbose cmap <space>` show? I can't reproduce this with default LazyVim installation.

**Comment by annacruz** [comment]
Here it's the video https://asciinema.org/a/LFm3WM4PBbKTeDuq67NanQcEJ

About the result of the command it returns 'no association found'

**Comment by annacruz** [comment]
Recording of the `:verbose cmap <space>` result:  https://asciinema.org/a/jlpDlB2hLIxvsICverhcLEk2f

**Comment by dpetka2001** [comment]
Can you try the following? 
```shell
1. mkdir ~/.config/lazytest
2. git clone https://github.com/LazyVim/starter ~/.config/lazytest
3. NVIM_APPNAME=lazytest nvim and wait for the installation to complete
4. While Lazy UI is still open press `C` to check and `U` to make sure everything is updated
5. Restart Neovim with command from step 3
```
Do you observe the same behavior?
For cleanup do
```shell
rm -rf ~/.config/lazytest
rm -rf ~/.local/share/lazytest
rm -rf ~/.local/state/lazytest
rm -rf ~/.cache/lazytest
```

**Comment by annacruz** [comment]
No the behaviour doesn't happen. The strange thing is that I use the same configuration in another machine and it works like a charm.

**Comment by annacruz** [comment]
https://github.com/annacruz/nvim is the configuration that I'm using.

**Comment by dpetka2001** [comment]
What you've just tried is a default Lazyvim installation with no user configuration present. That means there's something in your personal configuration causing this and it's not a Lazyvim bug. I don't know what is causing this, but you should try disabling some things until you find the culprit.

**Comment by annacruz** [comment]
Yeah... I'll try to make the configuration manually one piece by one, it's the best. Thanks for your support!

**Comment by dpetka2001** [comment]
I would suggest you to backup your current configuration and then start from scratch enabling one piece of your current configuration in the new configuration at a time. Essentially the [installation steps mentioned on the website](https://www.lazyvim.org/installation).

**Comment by BlueDrink9** [comment]
Quitting without a map on space tells me it is possibly a crash rather than a quit. To check if it is a quit vs a crash, if you run `nvim && echo exited ok`, press space, and "exited ok" prints to the terminal, that says nvim exited normally. If you run `nvim || echo crashed` and do the same, the print to terminal will say nvim crashed.

If it's a crash, might need to reinstall neovim. Also make sure treesitter parsers are up to date (`:TSUpdate`), I've had crashes from that in the past.

**Comment by annacruz** [comment]
Just as an info it's crashing, I'm trying to check the reasons of the crash before close the issue

**Comment by annacruz** [comment]
Reinstalled everything including putting again the configuration solve the issue. Might had passed some trash. Thanks for help me debugging.
