### ISSUE TITLE
bug: invalid node type at position for language vim

### ISSUE THREAD

**Issue by sullrich84** [LazyVim/LazyVim#430]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

v0.8.3

### Operating system/version

MacOS 12.6.1

### Describe the bug

I'm using the latest version of `lazy-git`. Whenever I interact with the `cmd` dialog and error notification pops up. Running `checkhealth` gave me this results:

```
## Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - help                ✓ . . . ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - luap                ✓ . . . .
  - markdown            ✓ . ✓ . ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 x ✓ ✓ . ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

## The following errors have been detected:
  - ERROR: vim(highlights): ...im/0.8.3/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 2765 for language vim
    vim(highlights) is concatenated from the following files:
    | [ERROR]:"/Users/sebastianullrich/.local/share/nvim/lazy/nvim-treesitter/queries/vim/highlights.scm", failed to load: ...im/0.8.3/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 2765 for language vim
```

### Steps To Reproduce

1. Using latest `lazy-vim`

### Expected Behavior

`healthcheck` should not promt any errors.

**Comment by folke** [comment]
This is clearly not a LAzyVim issue. Check the docs at https://github.com/nvim-treesitter/nvim-treesitter

**Comment by nianiam** [comment]
Specifically this: https://github.com/nvim-treesitter/nvim-treesitter#i-get-query-error-invalid-node-type-at-position
