### ISSUE TITLE
bug: rename markdown.nvim to render-markdown.nvim

### ISSUE THREAD

**Issue by s1n7ax** [LazyVim/LazyVim#4306]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

-

### Operating system/version

-

### Describe the bug

markdown.nvim is now renamed to render-markdown.nvim. This is being used in markdown extra.

I wanted to disable it and using the new name does not disable the plugin. I have to use previous name. Similarly I have to note that anyone who has disabled this will be enabled if the name changes in lazyvim

### Steps To Reproduce

-

### Expected Behavior

-

### Repro

```lua
-
```

**Comment by dpetka2001** [comment]
There's already #4259 about this.
