### ISSUE TITLE
bug:  Astrojs not working in Lazyvim

### ISSUE THREAD

**Issue by sohanemon** [LazyVim/LazyVim#4317]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.1

### Operating system/version

Archlinux 6.10.4-arch2-1

### Describe the bug

Astro.js not working in my Lazyvim. No lsp, no syntax highlighting, no autocomplete.

![image](https://github.com/user-attachments/assets/c5c90068-de51-49a4-9b22-1c8ef1c1d388)

### Steps To Reproduce

if I run `:e` in my astro file it returns these errors.

```lua
Error executing lua callback: /usr/share/nvim/runtime/filetype.lua:35: Error executing lua: /usr/share/nvim/runtime/filetype.lua:36: BufReadPost Autocommands for "*"..FileType Autocommands for "*"..function <SNR>1_LoadFTPlugin[20]..script /usr/share/nvim/runtime/ftplugin/astro.vim[163]..function <SNR>36_CollectPathsFromConfig, line 11: Vim(let):E474: Trailing comma: }
stack traceback:
	[C]: in function 'nvim_cmd'
	/usr/share/nvim/runtime/filetype.lua:36: in function </usr/share/nvim/runtime/filetype.lua:35>
	[C]: in function 'nvim_buf_call'
	/usr/share/nvim/runtime/filetype.lua:35: in function </usr/share/nvim/runtime/filetype.lua:10>

``` 

and

```lua
Error detected while processing BufReadPost Autocommands for "*":
``` 

### Expected Behavior

It should be like this. But here is only syntax highlighting. It happens when I run `:TSInstall astro`.

![image](https://github.com/user-attachments/assets/5a020d26-5a8d-4090-8881-1903f6baecc2)

### Repro

```lua
I have added astro from LazyExtras.
```

**Comment by sohanemon** [comment]
thank you for your reply. Here i does the same but see the issue still there.


https://github.com/user-attachments/assets/b2a27162-87eb-4dec-b71b-179717beac03

**Comment by dpetka2001** [comment]
It's something on your end. You only deleted `~/.config/nvim` directory and not the `data`, `state` and `cache` directories. Try the following, so you can have a clean LazyVim installation without messing with your personal configuration
```shell
1. mkdir ~/.config/lazytest
2. git clone https://github.com/LazyVim/starter ~/.config/lazytest
3. NVIM_APPNAME=lazytest nvim and wait for the installation to complete
4. While Lazy UI is still open press `C` to check and `U` to make sure everything is updated
5. Restart Neovim with command from step 3
```
Enable the `lang.astro` Extra and also install the `css` treesitter parser (which you didn't do in your previous screencast).

For cleanup
```shell
rm -rf ~/.config/lazytest
rm -rf ~/.local/share/lazytest
rm -rf ~/.local/state/lazytest
rm -rf ~/.cache/lazytest
```

**Comment by sohanemon** [comment]
when I create a new Astro project, it just works like a charm. Even with my previous config. sorry for my mistake and thank you so much for your time. Now I have to figure out the issue with my project. haha
