### ISSUE TITLE
bug: Both denols and vtsls LSPs running in monorepo

### ISSUE THREAD

**Issue by nounder** [LazyVim/LazyVim#4319]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0

### Operating system/version

MacOS 15.0

### Describe the bug

In TypeScript mono repo setup, two typescript LSPs are running at the same time.

Root directory for `vtsls` and `denols` are different. `vtsls` points to expected directory (ie. when package.json and tsconfig.json is found). `denols` points to a git repo even though there are no `deno.json` anywhere in sight.

Related code that handles those two LSPs:

https://github.com/LazyVim/LazyVim/blob/12818a6cb499456f4903c5d8e68af43753ebc869/lua/lazyvim/plugins/lsp/init.lua#L248-L257

### Steps To Reproduce

```
mkdir monorepo
cd monorepo
git init
mkdir pkg
echo '{}' > pkg/tsconfig.json
cd pkg
nvim
```

While in nvim, run `C-c -l` and see both `denols` and `vtsls` running and causing conflicting formatting and auto complete.

### Expected Behavior

`denols` has the same working directory as `vtsls` so LazyVim's code to handle those conflicting LSPs will work properly for monorepos:

https://github.com/LazyVim/LazyVim/blob/12818a6cb499456f4903c5d8e68af43753ebc869/lua/lazyvim/plugins/lsp/init.lua#L248-L257

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by gtarsia** [comment]
I would appreciate any workaround for this.

**Comment by josephcrawfordSRH** [comment]
@nounder @gtarsia there is a work around for this, I had to do it myself.  The trick is to configure your LSP accordingly.  You have to set your root_dir for the lsp you wish to have enabled with a rule that will match.  This is not a bug.

For my example below I have it enable denols when a deno.jsonc or deno.json file is in the root path for the project and vtsls when there is a package.json file in the root directory.

here is my lsp.lua plugin file.

```lua
local nvim_lsp = require("lspconfig")

return {
  {
    "neovim/nvim-lspconfig",
    ---@class PluginLspOpts
    opts = {
      --      autoformat = false,
      servers = {
        intelephense = {
          filetypes = { "php", "blade" },
          settings = {
            intelephense = {
              filetypes = { "php", "blade" },
              files = {
                associations = { "*.php", "*.blade.php" }, -- Associating .blade.php files as well
                maxSize = 5000000,
              },
            },
          },
        },
        denols = {
          filetypes = { "typescript", "typescriptreact" },
          root_dir = function(...)
            return nvim_lsp.util.root_pattern("deno.jsonc", "deno.json")(...)
          end,
          settings = {
            deno = {
              enable = true,
              lint = true,
              unstable = true,
            },
          },
        },
        vtsls = {
          root_dir = nvim_lsp.util.root_pattern("package.json"),
        },
        tsserver = {
          root_dir = nvim_lsp.util.root_pattern("package.json"),
          keys = {
            {
              "<leader>co",
              function()
                vim.lsp.buf.code_action({
                  apply = true,
                  context = {
                    only = { "source.organizeImports" },
                    diagnostics = {},
                  },
                })
              end,
              desc = "Organize Imports",
            },
            {
              "<leader>cR",
              function()
                vim.lsp.buf.code_action({
                  apply = true,
                  context = {
                    only = { "source.removeUnused" },
                    diagnostics = {},
                  },
                })
              end,
              desc = "Remove Unused Imports",
            },
          },
          ---@diagnostic disable-next-line: missing-fields
          settings = {
            completions = {
              completeFunctionCalls = true,
            },
          },
        },
      },
    },
  },
}

```

**Comment by josephcrawfordSRH** [comment]
@nounder @gtarsia I found that even in a multirepo I was getting both lsps fighting over the formatting, etc.  I had to add this to my own lsp.lua config file under `servers`

```lua
local nvim_lsp = require("lspconfig")

return {
  {
    "neovim/nvim-lspconfig",
    opts = {
      servers = {
        denols = {
          filetypes = { "typescript", "typescriptreact" },
          root_dir = function(...)
            return nvim_lsp.util.root_pattern("deno.jsonc", "deno.json")(...)
          end,
        },
        vtsls = {
          root_dir = nvim_lsp.util.root_pattern("package.json"),
        },
      },
    },
  },
}
```
Once I did this everything is working properly.
