### ISSUE TITLE
bug: cmdline cursor flickering

### ISSUE THREAD

**Issue by dinhlongviolin1** [LazyVim/LazyVim#4325]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.1

### Operating system/version

Macos 14.6.1

### Describe the bug

Whenever I use the cmdline, the cursor flickers between the cmdline and the background tab.

Current setup is using wezterm + neovim. The issue also persisted on MacOS Terminal and iTerm2.

![Example](https://github.com/user-attachments/assets/9954a3b0-f555-4112-abc8-a39f49144ace)

### Steps To Reproduce

1. Use the cmdline by pressing `:`

### Expected Behavior

There should be no flickering

### Repro

- Using lazy-starter with no additional config 
- My personal config https://github.com/dinhlongviolin1/nvim-lazy

**Comment by dpetka2001** [comment]
I believe this is due to `noice.nvim` and you should report it there. You can try to disable `noice.nvim` to see if the problem still occurs to make sure the culprit is `noice.nvim`.

**Comment by dinhlongviolin1** [comment]
Yes you are right, it is because of the `noice.nvim` plugin

My fault for not finding duplicated issue #4287. I will close my issue in favor of that one. 

Will keep using noice.nvim for the moment as it looks very nice. Hopefully the bug will be fixed soon.
