### ISSUE TITLE
feature: Add `ignore_lsp` option to `lazyvim.util.root`

### ISSUE THREAD

**Issue by murar8** [LazyVim/LazyVim#4330]
### Did you check the docs?

- [X] I have read all the LazyVim docs
- [X] This is not a request for a new or existing extra (see above)

### Is your feature request related to a problem? Please describe.

Hi, first of all thanks for the great project. I have a small issue with root dir detection: When no other LSPs are enabled, the lsp detector will load the root dir from copilot LSP which is always set to the home folder.

### Describe the solution you'd like

Provide a `ignore_lsp` configuration option similarly to https://github.com/ahmedkhalf/project.nvim?tab=readme-ov-file#%EF%B8%8F-configuration

### Describe alternatives you've considered

Since project.nvim already provides the same functionality maybe you could leverage that instead of using a custom implementation? Just an idea.

**Comment by dpetka2001** [comment]
Would be great if you could test the linked PR. In your `options.lua` file you should put `vim.g.root_lsp_ignore = { "lsp_server_name_of_your_choice" }`.

**Comment by murar8** [comment]
Wow, that was fast! Sorry for the delay, I just tested your branch and it seems to work perfectly. One small change I would suggest is always including `copilot` in the ignore array since there is no way anyone could find that useful.

**Comment by dpetka2001** [comment]
I will let the maintainer decide for that, since that is a preference that might or might not be acceptable by everyone. Either way users could just set it themselves, so it will create less friction in case someone does expect it to not be blacklisted.

**Comment by murar8** [comment]
Not stale.
