### ISSUE TITLE
bug: `astro-language-server` must install by `mason.nvim` if I want Lazyvim don't warn for me

### ISSUE THREAD

**Issue by Buer-Nahida** [LazyVim/LazyVim#4339]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.1 Build type: Release LuaJIT 2.1.1713773202 Run "nvim -V1 -v" for more info

### Operating system/version

NixOS 24.11.20240809.5e0ca22 (Vicuna) x86_64

### Describe the bug

I'm using nixos, so I disabled the `mason.nvim` plugin, and use system package to install LSP, DAP, Linter and Formatter, it works normal.

When I enabled `lang.astro`, and install `pkgs.astro-language-server` package, LazyVim warn me as soon as I start neovim:
![warning](https://github.com/user-attachments/assets/571a2a94-229a-40fa-9743-30165877b780)
So, I put it in my nvim config.
```lua
    {
      "neovim/nvim-lspconfig",
      opts = function(_, opts)
        for i, v in
          ipairs(opts.servers.vtsls.settings.vtsls.tsserver.globalPlugins)
        do
          if v.name == "@astrojs/ts-plugin" then
            opts.servers.vtsls.settings.vtsls.tsserver.globalPlugins[i].location =
              vim.env.HOME .. "node_modules/@astro/ts-plugin"
          end
        end
      end,
    },
```
And execute:
```bash
npm i @astro/ts-plugin
```

After that, astro-language-server works, but LazyVim also warn me as soon as I start neovim.

### Steps To Reproduce

1. Disable `mason.nvim` plugin
2. Enable `lang.astro` lazyvim extra
3. Install `astro-language-server` package provide by system package manager
4. Start neovim

### Expected Behavior

LazyVim will not warn for it to me, because I already installed `astro-language-server` package by system package manager.
![图片](https://github.com/user-attachments/assets/21b9dead-5d91-4129-93e4-0a60bb46a985)

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    { "williamboman/mason.nvim", enabled = false },
    { import = "lazyvim.plugins.extras.lang.astro" },
    {
      "neovim/nvim-lspconfig",
      opts = function(_, opts)
        for i, v in
          ipairs(opts.servers.vtsls.settings.vtsls.tsserver.globalPlugins)
        do
          if v.name == "@astrojs/ts-plugin" then
            opts.servers.vtsls.settings.vtsls.tsserver.globalPlugins[i].location =
              --[[ path of the @astro/ts-plugin ]]
          end
        end
      end,
    },
  },
})
```

**Comment by Buer-Nahida** [comment]
I read the source code of `lang.astro`, and looks like under code triggered this bug:

https://github.com/LazyVim/LazyVim/blob/12818a6cb499456f4903c5d8e68af43753ebc869/lua/lazyvim/plugins/extras/lang/astro.lua#L40

`LazyVim.get_pkg_path` not found `astro-language-server` mason package, so it warn me.

**Comment by Buer-Nahida** [comment]
> I believe this could be worked around with the following addition我相信这可以通过以下添加来解决
> 
> ```lua
> if opts.warn and not vim.loop.fs_stat(ret) and not require("lazy.core.config").headless() and LazyVim.has("mason.nvim") then
>     M.warn(
>       ("Mason package path not found for **%s**:\n- `%s`\nYou may need to force update the package."):format(pkg, path)
>     )
>   end
> ```
> 
> in  在
> 
> https://github.com/LazyVim/LazyVim/blob/12818a6cb499456f4903c5d8e68af43753ebc869/lua/lazyvim/util/init.lua#L250-L263
> 
> So, just add `and LazyVim.has("mason.nvim")` in line 257.
> 因此，只需在第 257 行添加`and LazyVim.has("mason.nvim")`即可。
> 
> Could you verify and maybe create a PR if this solves your problem?如果这能解决您的问题，您能否验证并创建一个 PR？

It's a good idea. but if I enabled `mason.nvim`, the warning will back again (why I renabled `mason.nvim` plugin? because `vtsls` have not package on nix, so I use mason to install it)

**Comment by Buer-Nahida** [comment]
I think we can make it to check binary file first, if exist then use binary else use mason package?

**Comment by dpetka2001** [comment]
Then I believe easiest way would be to introduce a new global variable into `opts.warn`. So, something like 
```lua
opts.warn = vim.g.get_pkg_warn == nil and (opts.warn == nil and true or opts.warn) or vim.g.get_pkg_warn
```
So that users can disable that warning in their own `options.lua`. Otherwise, how would you check for binary path? There may be quite a few different ways to install binaries and maybe not all of them use the same path. 

This is something specific to NixOs and honestly the best way for NixOs users would be to copy/paste the Extras they want into `~/.config/nvim/lua/plugins/extras` directory and enable their custom Extras with the necessary changes required via `LazyExtras` UI.

**Comment by Buer-Nahida** [comment]
I found a way to solve this problem, now I'm creating a pull request.

**Comment by Buer-Nahida** [comment]
You can do that to fix vtsls tsserver not found `@astro/ts-plugin` node package, but you also get a warning:

```lua
return {
      "neovim/nvim-lspconfig",
      opts = function(_, opts)
        for i, v in
          ipairs(opts.servers.vtsls.settings.vtsls.tsserver.globalPlugins)
        do
          if v.name == "@astrojs/ts-plugin" then
            opts.servers.vtsls.settings.vtsls.tsserver.globalPlugins[i].location =
              vim.env.HOME .. "node_modules/@astro/ts-plugin"
          end
        end
      end,
    }
```

**Comment by dpetka2001** [comment]
Did you read my previous comment? If you add a `vim.g.get_pkg_warn` in line 254,then all the user has to do is set that variable to `false` in his `options.lua` file and the warning wouldn't show any more. Have you tried it?

**Comment by Buer-Nahida** [comment]
I tryed and I think it's equivalent to simply turning off all warnings, then other mason package not found the user will use more time to find why someting don't work.

**Comment by dpetka2001** [comment]
Yes, you have a point there.
