### ISSUE TITLE
bug: macro with mini-surround does not work in LazyVIM

### ISSUE THREAD

**Issue by skrobul** [LazyVim/LazyVim#4348]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.11.0-nightly+4e8efe0

### Operating system/version

Linux Nixos 24.05

### Describe the bug

I have run into a problem when trying to record a macro that utilizes the mini-surround plugin.

Input text looks like this:

```
section =
  "some-key" = "very.long.path.with.a.module:Class"
  some-key = very.long.path.with.a.module:Class
  some-key = very.long.path.with.a.module:Class
```

the goal is to add missing quotes on the last two lines so that it looks the same as the first one.
So, I have recorded the following macro `gsaiW"2WgsaiW"` while having cursor positioned on 3rd line of the input text.
When trying to play the macro, the resulting line is:

`  aW"2WgsagsaiW"asome-key = very.long.path.with.a.module:Class`

### Steps To Reproduce

1. Copy the input text from above
2. Position your cursor on a first "some-key" line without the quotes
3. Start recording the macro: `qq` in normal mode
4.  Type `gsaiW"2WgsaiW"`, then press `q` to finish the recording.
5. Position cursor on the next line and try to play the macro `@q`

### Expected Behavior

The expected behavior is for the line to be changed into
`"some-key" = "very.long.path.with.a.module:Class"`

I have verified that this does not happen with a `mini-surround` installed on a clean setup without LazyVim.
I suspected that it might be conflict with `flash.nvim` and that macro somehow triggers the `s`, but disabling the `flash.nvim` did not make any difference.

For now my workaround is to switch to nvim-surround which does not have that problem.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
Can you try disabling `which-key` and see if the behavior still occurs?

**Comment by skrobul** [comment]
> Can you try disabling which-key and see if the behavior still occurs?

behavior changes (this time part of the macro is inserted in the line above instead of the cursor line):

![image](https://github.com/user-attachments/assets/2cf51116-61e2-4b16-8538-bc2af18f0331)

**Comment by dpetka2001** [comment]
Yes, there is actually an open issue at `which-key` github repo for macros actually registering duplicate text objects or something like that. Since this is not a LazyVim bug and cannot be solved here, I'd suggest to close this issue and search for an active issue at `which-key` github repo that is similar to your problem and make a comment there with your findings. 

Also instead of disabling `which-key` as a whole and you still want to keep using it, you can just disable the `registers` functionality it uses by setting `opts.plugins.registers = false`.

**Comment by skrobul** [comment]
Thank you, really appreciate quick help on this
