### ISSUE TITLE
bug: Telescope code action picker drops visual selection

### ISSUE THREAD

**Issue by avario-cpu** [LazyVim/LazyVim#4350]
https://github.com/user-attachments/assets/aced8fb5-4067-4899-8044-8bf5a1e07625

### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.1

### Operating system/version

Windows

### Describe the bug

When the telescope picker for code actions shows up, previous selection with v-mode drops. This make method extracting impossible: for example, when [using rope with pylsp](https://github.com/python-rope/pylsp-rope) , we get a bad range error, since at the moment of executing the action, nothing is selected.

As a workaround I'm trying to get the default ui to show up with some different keybind but I can't figure it out...

### Steps To Reproduce

1. Select text with V mode
2. <Leader>ca

### Expected Behavior

Visual selection remains while telescope picker opens

### Repro

```lua
Default lazy starter clone afaik...
Only changes made are the config of the lsp itself which shouldn't concern the picker window ?
```

**Comment by dpetka2001** [comment]
LazyVim doesn't do anything with Telescope except use its pickers. Report that in Telescope.

**Comment by avario-cpu** [comment]
Gotcha, I was wondering about that.

**Comment by dpetka2001** [comment]
And actually it might not even be a problem with Telescope. When Telescope is enabled then `dressing.nvim` is used for `vim.ui.select`, which is what the pop up with code actions is. You can see this [here](https://github.com/LazyVim/LazyVim/blob/12818a6cb499456f4903c5d8e68af43753ebc869/lua/lazyvim/plugins/extras/editor/telescope.lua#L257-L276). So, maybe it has to do with `dressing.nvim` instead? Just a guess.

**Comment by avario-cpu** [comment]
> And actually it might not even be a problem with Telescope. When Telescope is enabled then `dressing.nvim` is used for `vim.ui.select`, which is what the pop up with code actions is. You can see this [here](https://github.com/LazyVim/LazyVim/blob/12818a6cb499456f4903c5d8e68af43753ebc869/lua/lazyvim/plugins/extras/editor/telescope.lua#L257-L276). So, maybe it has to do with `dressing.nvim` instead? Just a guess.

[Yes it is](https://github.com/stevearc/dressing.nvim/issues/74)

thanks a lot for hte pointer though because I wouldn't have figured out the link so soon.
