### ISSUE TITLE
bug: Lazyvim not working without /usr/share/nvim folder

### ISSUE THREAD

**Issue by Subas-mohanty** [LazyVim/LazyVim#4371]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

ubuntu 24.04

### Describe the bug

- After cloning the repo, when running nvim command it shows, can't open file /usr/share/nvim/syntax/syntax.vim .
- Because there is no folder in /usr/share as nvim
- And when installing neovim using the following command it doesn't create the folder for me
command 
```
sudo apt install neovim
```

### Steps To Reproduce

In ubuntu : 
1. sudo apt install neovim
2. git clone https://github.com/LazyVim/starter ~/.config/nvim
3. nvim

### Expected Behavior

It should open lazyvim 

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
This has to do with how you installed Neovim  and nothing with LazyVim. There should not be any files under `/usr/share/nvim` folder. The plugins `lazy.nvim` is installing should be under `~/.local/share/nvim/lazy/` directory. 

Try to uninstall any instance of Neovim from your system and use [bob](https://github.com/MordechaiHadad/bob) to install Neovim instead.

**Comment by Subas-mohanty** [comment]
I am new to vim so I didn' t know that. I thought it is a lazyvim issue. After doing some research able to solve the problem. so closing this issue
