### ISSUE TITLE
how to blend lualine winbar with colorscheme?

### ISSUE THREAD

**Issue by ShabirK21** [LazyVim/LazyVim#438]
![Screenshot_2023-03-16-12-23-14](https://user-images.githubusercontent.com/67749458/225375089-57a45033-d908-4b75-87c4-e0d93ab070de.png)

I want the filetype and name to blend in with the colorscheme like the in-file location does, i've moved it from the statusline to the winbar

**Comment by dpetka2001** [comment]
You should check [this issue](https://github.com/LazyVim/LazyVim/issues/328)

**Comment by ShabirK21** [comment]
Thanks, I'll try out your solution
