### ISSUE TITLE
bug: add to docs wrap does not work unless vim.opt.textwidth is set 

### ISSUE THREAD

**Issue by richtong** [LazyVim/LazyVim#4380]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10

### Operating system/version

MacOS 14.6.1

### Describe the bug

This took me a noob a day to figure out, but if you set \uw or you are editing one of the files, like a git commit, markdown or text file, the wrap will not work

This is because vim.opt.textwidth must also be set or the wrap does nothing.

Not a bug per se, but you might to add some documentation to the either https://www.lazyvim.org/configuration/general#options

because the defaults show that `vim.opt.local.wrap` and `vim.op_local.spell` are set
but this is not enough, you need to add some default wrap (maybe 88 characters like
Black for Python), or maybe 128 characters because what the heck it won't seem broken

I'm happy to issue a PR for this is you like as either:

1. A documentation change in https://www.lazyvim.org/keymaps where you have <leader>uw
2. Change the default options.lua to add a vim.opt.textwidth equal to something reasonable like 88 is good for markdown and text documents I think, but could be wider.

### Steps To Reproduce

1. Start Lazyvim
2. \uw to turn wrapping on or go to a Markdown files
3. :setlocal wrap? is on
4. :setlocal textwidth? returns 0 which means don't wrap

### Expected Behavior

If you turn on \uw or it is turned on for text, markdown, git commits, it should reasonably wrap or it should be documented that wrapping won't work.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
`wrap` is only for wrapping the lines if the lines are too long and overflow the width of the window. Only then they will get wrapped.

 > This option changes how text is displayed.  It doesn't change the text in the buffer, see 'textwidth' for that.
	When on, lines longer than the width of the window will wrap and displaying continues on the next line.

So, it correctly wraps the lines if for example you split your window into vertical.

`textwidth` is for determining when you're in `insert` mode and typing when the line will break and go to the next line. This is not configured in LazyVim, because it's mostly a user preference and should be done in the user personal configuration.

The 2 of them are different and do different things. Also, I don't think any additional documentation is necessary on LazyVim docs, since all this is described in Neovim `:help` (see `:h 'wrap'` and `:h 'textwidth'`). Users should get accustomed to reading Neovim documentation. That's the reason it exists.

**Comment by richtong** [comment]
Got it sorry in all the years of using vi then vim and now Neovim, I had forgotten the difference between them since ':se tw=88 wrap' is buried in all my .rc files. 

And became since vim.opt.wrap exists I thought there was a wrapper around somewhere soft and hard wrap. It's hard to know sometimes which of the layers of docs to look at between lazyvim, the many plugin configs and core Neovim. 

Anyway I'll close the issue and just note it a big blog post on my own site where I'll find it again in two years when I forget all this. 

Great project by the way. I bit the bullet and threw away an 8 year old carefully crafted .vimrc for something that's basically lazyvim with three changes in options.lua. Thanks!!!!
