### ISSUE TITLE
bug: LazyVim constantly loses track of expandtab config

### ISSUE THREAD

**Issue by stevenroose** [LazyVim/LazyVim#4388]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.5 (relelase)

### Operating system/version

nixos latest

### Describe the bug

I have a `.editorconfig` that indicates tabs should be used for indentation. I have no other indentation-related configurations. When freshly opening LazyVim, it works as expected. But constantly, as i have a vim session open for a long time (hours to days), somehow the expandtab setting changes and I start to unknowingly introduce spaces into my files.

I think it might have to do with (using LSP) visiting a file outside of my code repository, but I can't reproduce.

### Steps To Reproduce

can't

### Expected Behavior

Tab key should always follow .editorconfig.

**Comment by dpetka2001** [comment]
The issue linked points to a plugin. Why use the plugin when Neovim itself supports `editorconfig` natively? Try without the plugin or report the issue at the plugin repo. What does it have to do with LazyVim?

**Comment by stevenroose** [comment]
I don't use the plugin, I used the plugin when I made that issue in 2020 and neovim didn't have native support.

That's why I reported this issue here now, because the issue persists, even with native support.

**Comment by dpetka2001** [comment]
The editorconfig implementation comes straight from Neovim and has nothing to do with Lazyvim. Lazyvim doesn't have any kind of configuration regarding editorconfig. So, you're reporting this to the wrong repo.

**Comment by Syakhisk** [comment]
Do you restore session using the `s` key on the LazyVim start screen?
I had this issue as well earlier and found the culprit.
The default session autosave feature doesn't include options (including expandtab, shiftwidth, etc), so restoring the session might override your `.editorconfig`

**Comment by stevenroose** [comment]
I [make an issue there](https://github.com/neovim/neovim/issues/30334), I can close this one.
