### ISSUE TITLE
bug: lang.python Extra fails to provide LSP features when root is not a git repo

### ISSUE THREAD

**Issue by zymotek** [LazyVim/LazyVim#4389]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.1 | Build type: Release | LuaJIT 2.1.1713484068

### Operating system/version

Linux 6.2.14-300.fsync.fc37.x86_64

### Describe the bug

Python LSP features do not work in Python file(s) in an otherwise empty directory.

This is in current LazyVim (`v12.38.2`, `3dbace9`), with `lang.python` enabled, and otherwise default LazyVim/starter config.

If you `git init` (or even just `mkdir .git`) inside the directory and try again, all features work as expected. 

If you `rm -rf ./.git`, it stops working.

This issue was not present in an older setup (LazyVim `v10.8.2`, NVIM `v0.9.1`).

## Additional context / observations / attempts:
- Single lua file in directory: No LSP issues. Other languages not attempted.
- `vim.g.lazyvim_python_lsp = "basedpyright"` in `config/options.lua`
    - Same behavior. Slightly different error messages.
- `vim.g.root_spec = { "cwd" }` in `config/options.lua`
    - Same behavior.

`:LazyRoot` when `.git` present:
```
- [x] `/path/to/foobar` **(lsp)**
- [ ] `/path/to/foobar` **(.git, lua)**
- [ ] `/path/to/foobar` **(cwd)**

vim.g.root_spec = { "lsp", { ".git", "lua" }, "cwd" }
```

`:LazyRoot` when `.git` NOT present:
```
- [x] `/path/to/foobar` **(cwd)**

vim.g.root_spec = { "lsp", { ".git", "lua" }, "cwd" }
```

`:LspInfo` when `.git` present:
```
Client: pyright [...]
root directory:  /path/to/foobar
```

`:LspInfo` when `.git` NOT present:
```
Client: pyright [...]
root directory:  Running in single file mode.
```

Message spam in `~/.local/state/nvim/lsp.log` when not working (no errors when working):
```
[ERROR][time] ...lsp/handlers.lua:623    'File or directory "/<default workspace root>" does not exist.'
```

### Steps To Reproduce

1. Clone current LazyVim starter
2. Enable `lang.python` Extra (via `:LazyExtras` or in `config/lazy.lua`)
3. `cd` to an empty `/path/to/foobar`
4. `nvim foobar.py` (or `nvim .`) and write some Python code
5. Attempt to use LSP features, such as:
    1. `K` (noice: "No information available")
    2. `[[` and `]]` (does nothing)
    3. `<leader>cr` (noice: "Nothing to rename")
    4. `<leader>cs` (noice: "No results for symbols")
    5. Code completion (only text and snippets)

### Expected Behavior

Basic Python LSP features should work when editing any Python file.

Additional files adjacent to the Python file should not be required. Changes to LazyVim config (apart from enabling `lang.python`) should not be required.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    { import = "lazyvim.plugins.extras.lang.python" },
  },
})
```

**Comment by zymotek** [comment]
Alternatively, placing a `pyrightconfig.json` with following contents, adjacent to the Python file(s), also fixes it:

```
{
    "executionEnvironments": [
        {"root": "."}
    ]
}
```

Removing this file breaks it again.

Similarly, if you merely `touch pyproject.toml`, everything works as expected.

But the LSP should work without any of those things. And `:LazyRoot` does show the correct root when they are absent.

**Comment by dpetka2001** [comment]
This seems to be a regression in pyright and subsequently basedpyright as well. Install the previous version of Pyright with `:MasonInstall pyright@1.1.377` and you'll see it will behave correctly. Create an issue at the corresponding github repo as this can't be resolved here.

**Comment by zymotek** [comment]
Thanks for the quick response!

I'd previously skimmed over the related basedpyright issue in this repo, but had prematurely dismissed it as unrelated. You're right, that seems to have the same root cause.

Still, `:LazyRoot` does identify the correct root in all cases. Is there no way LazyVim could **tell** (based)pyright to use that as it's workspace root, instead of allowing it to fall back onto its (currently broken) default behavior?

Would it not be reasonable to say that the editor should decide what the workspace root ought to be, rather than letting the LSP server figure it out on its own?

**Comment by dpetka2001** [comment]
`lsp` from `vim.g.root_spec` just returns the `root_dir` or workspace folder the LSP client responds back. Corresponding code is [here](https://github.com/LazyVim/LazyVim/blob/3dbace941ee935c89c73fd774267043d12f57fe2/lua/lazyvim/util/root.lua#L32-L44). There's no magic being done here. LazyVim only returns what `pyright` or `basedpyright` determines to be the `root_dir`. And also `vim.g.root_spec` is just used to determine the `LazyRoot` from what the client responds. The problem here is that the LSP features of both servers don't seem to be working in `single_file` mode in the latest version. That's not something that can be fixed here.

**Comment by zymotek** [comment]
I see, makes sense. Feel free to close if issue is no longer useful.

And thanks again for the `:MasonInstall pyright@1.1.377` solution; that seems to be the way to go until they fix it.
