### ISSUE TITLE
bug: duplicate errors and warnings

### ISSUE THREAD

**Issue by joshmedeski** [LazyVim/LazyVim#439]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

v0.8.3

### Operating system/version

macOS Ventura 13.2.1

### Describe the bug

I am seeing the same errors and warnings multiple times from the LSP. Do you know why this might be happneing?

<img width="842" alt="Screenshot 2023-03-15 at 3 39 51 PM" src="https://user-images.githubusercontent.com/2036594/225436868-d46b64d0-59ec-4742-adc4-01f13ef3cf8e.png">

I have tsserver and eslint running on this example.

### Steps To Reproduce

1. Create an typescript project with eslint
2. Break on of the eslint rules

### Expected Behavior

I expect to see the provided error message once.

**Comment by folke** [comment]
You're not using the standard diagnostics it seems, so file a bug there or read their docs

**Comment by joshmedeski** [comment]
What do you mean by "standard diagnostics"? Like the LSP directly?

**Comment by folke** [comment]
you are using lsp lines or something like that

**Comment by folke** [comment]
Open trouble to see the source of the diagnostics if they really are duplicates. Tht or its the diagnostics rendering thing you use

**Comment by joshmedeski** [comment]
Yes, I'm using lsp_lines, but I get the same duplicate diagnostic errors when using the built-in lspconfig configuration.

<img width="791" alt="Screenshot 2023-03-15 at 3 48 25 PM" src="https://user-images.githubusercontent.com/2036594/225438944-4cf6c4c6-7e7e-4849-a920-88a9ad538461.png">

I'm nut not sure how to debug where each diagnostic message is coming from.

**Comment by folke** [comment]
As I said, open `:Trouble` and check the source of the dignostics

**Comment by joshmedeski** [comment]
Thanks, that did help clarify things. It's something to do with eslint, every eslint result is showing up twice. There's a chance it's a configuration issue on my end.

**Comment by joshmedeski** [comment]
Hey, so I figured it out! I had eslint both configued in null-ls and the LSP config.
