### ISSUE TITLE
feature: Add a other clean Theme

### ISSUE THREAD

**Issue by Hierosme** [LazyVim/LazyVim#4409]
### Did you check the docs?

- [X] I have read all the LazyVim docs
- [X] This is not a request for a new or existing extra (see above)

### Is your feature request related to a problem? Please describe.

The trouble about LazyVim default theme is a too mush color. That case trouble to me with the time. After long day of coding all that color not help me a lot.

Unfortunally it haven't any other dark clean and clean theme for a poor night developper.

### Describe the solution you'd like

by exemple add  'shaunsingh/nord.nvim' and few  others common developper theme.

I speack about more common IDE colorsheme  (Darcula, Monokai, etc ....)

### Describe alternatives you've considered

An alternative, can be to document more  how add a colorsheme section

Actually one page exist:
https://www.lazyvim.org/plugins/colorscheme

But the file lua/plugins/colorscheme.lua is a bit  ambugus for new nvim players.

- Can it be done via user home directory ?
- What about add more of one theme ?
- If the file do not exist can i create it ?
- If i add a new theme it will be install automatically ?

It fact the documentation look to be more for someone who allready know  what is colorsheme and how it work.

### Additional context

At the end of a hard day's work, I realize that LazyVim tires my eyes more than other IDEs.

Regards

**Comment by dpetka2001** [comment]
I doubt there's gonna be a collection of colorschemes. Users just install what they want and configure it according to their own preferences. The lines mentioned in the [docs](https://www.lazyvim.org/plugins/colorscheme) are pretty straightforward
```lua
return {
  -- add gruvbox
  { "ellisonleao/gruvbox.nvim" },

  -- Configure LazyVim to load gruvbox
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "gruvbox",
    },
  }
}
```
The LazyVim spec is only needed if you want LazyVim to start up with a default colorscheme other than `tokyonight`. You can switch between themes on the fly using the keymap `<leader>uC` (from the ones that you have installed) and if you have the `fzf-lua` Extra enabled then it has a subcommand `:FzfLua awesome_colorschemes`, which gives you a variety of other colorschemes that you can download and load on the fly as well. But if you want to customize each colorscheme you will still have to add a plugin spec in your configuration and change the defaults.

I believe that is plenty for a default Neovim distro. Users are encouraged to read the docs and familiarize themselves with how LazyVim works. Also questions like these by newcomers are more than welcome but better suited for `Discussions` rather here in my personal opinion. Please keep in mind I'm just a regular user like you expressing my personal opinion and in the end the maintainer has the final say.
