### ISSUE TITLE
feature: Change home page key binding from ctrl-f to "p"

### ISSUE THREAD

**Issue by loops** [LazyVim/LazyVim#4418]
### Did you check the docs?

- [X] I have read all the LazyVim docs
- [X] This is not a request for a new or existing extra (see above)

### Is your feature request related to a problem? Please describe.

The current binding of ctrl-f coincides with a very common navigation sequence that is in many
user's muscle memory.  Moving down a page in the Home screen is a useful feature, and it is
natural to use ctrl-f to do so. 

But currently ctrl-f is mapped to the "Filter Profile" function, so ctrl-f doesn't work, and it isn't
always obvious why.

### Describe the solution you'd like

It would be nice to change this binding to a single "p" instead.  That key can't be useful since
the Home page is read-only anyway.    And the capital key "P" is already mapped to
"Detailed Profile", so it seems like a natural fit.

### Describe alternatives you've considered

It isn't a huge deal, so perhaps it's not worth making any change at all at this point.  Or maybe
there is a better new mapping, than "p".

**Comment by dpetka2001** [comment]
The only `<c-f>` keybinding in LazyVim is for scrolling the completion docs and fzf-lua/telescope. `<c-f>` in Dashboard acts like normal already.

**Comment by loops** [comment]
Hey dpetka2001,

Thanks, my mistake.  I'll close this, and file it under Lazy.vim instead.
