### ISSUE TITLE
bug: Add all missing imports no longer works as expected

### ISSUE THREAD

**Issue by alivault** [LazyVim/LazyVim#4421]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.1

### Operating system/version

MacOS 14.5

### Describe the bug

When I use <leader>cM to add all missing import, I am presented with a dialog that has the same option twice:
<img width="871" alt="image" src="https://github.com/user-attachments/assets/0ee11204-ba27-499e-89a9-c2f88502a402">

Same with remove all unused code. When I use <leader>cu I get this message:
<img width="873" alt="image" src="https://github.com/user-attachments/assets/eb781897-eb45-46a3-a1e3-06859c9fbb75">
(also note <leader>cu is listed as "Remove unused imports" but the dialog says "Remove all unused code")
<img width="240" alt="image" src="https://github.com/user-attachments/assets/f2a1f751-6dbf-4e0b-ad60-b3d45504324e">

### Steps To Reproduce

1. remove an import
2. try using <leader>cM to auto add the missing import
3. observe the dialog with repeated options

### Expected Behavior

<leader>cM should auto import immediately, not show a dialog with the same option twice.

### Repro

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- bootstrap lazy.nvim
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

require("lazy").setup({
  spec = {
    -- add LazyVim and import its plugins
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- import any extras modules here
    -- { import = "lazyvim.plugins.extras.lang.typescript" },
    -- { import = "lazyvim.plugins.extras.lang.json" },
    -- { import = "lazyvim.plugins.extras.ui.mini-animate" },
    -- import/override with your plugins
    { import = "plugins" },
  },
  defaults = {
    -- By default, only LazyVim plugins will be lazy-loaded. Your custom plugins will load during startup.
    -- If you know what you're doing, you can set this to `true` to have all your custom plugins lazy-loaded by default.
    lazy = false,
    -- It's recommended to leave version=false for now, since a lot the plugin that support versioning,
    -- have outdated releases, which may break your Neovim install.
    version = false, -- always use the latest git commit
    -- version = "*", -- try installing the latest stable version for plugins that support semver
  },
  install = {
    -- try to load one of these colorschemes when starting an installation during startup
    colorscheme = { "tokyonight" },
  },
  checker = { enabled = true }, -- automatically check for plugin updates
  performance = {
    rtp = {
      -- disable some rtp plugins
      disabled_plugins = {
        "gzip",
        -- "matchit",
        -- "matchparen",
        -- "netrwPlugin",
        "tarPlugin",
        "tohtml",
        "tutor",
        "zipPlugin",
      },
    },
  },
})
```

**Comment by dpetka2001** [comment]
That comes from the LSP server itself. Do you have multiple LSP servers attached to the buffer? 

I don't do Typescript myself so I just asked ChatGpt to generate an example with imports and this is how it looks like with the Typescript Extra enabled.

[Screencast_2024-09-09-20-37-45.webm](https://github.com/user-attachments/assets/ad2d3d6a-c3f8-4646-b135-4db37f19cfa6)

**Comment by alivault** [comment]
Looks like I had two typescript clients attached:
<img width="674" alt="image" src="https://github.com/user-attachments/assets/cde88c53-86f4-4d11-ab2f-c90800f2d194">
`ts_ls` and `vtsls`

I uninstalled `ts_ls` using mason and now it's working.

I think the problem is that nvim-lspconfig renamed `tsserver` to `ts_ls`: https://github.com/neovim/nvim-lspconfig/pull/3232
And LazyVim is still trying to disabled the old name `tsserver`: http://www.lazyvim.org/extras/lang/typescript
LazyVim needs to be updated to disable `ts_ls` instead.

**Comment by dpetka2001** [comment]
There's already #4406 about that.

**Comment by alivault** [comment]
Nice. What's preventing it from being merged in?

**Comment by dpetka2001** [comment]
Wait for the maintainer to come back. See pinned issue.
