### ISSUE TITLE
bug: lualine inactive sessions do not appear

### ISSUE THREAD

**Issue by snaveevans** [LazyVim/LazyVim#4433]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.1

### Operating system/version

MacOS 13.3.1

### Describe the bug

When disabling bufferline and replacing it with lualine the `inactive_session` does not appear.  Normally lualine will display the "line" below each displayed buffer. While using neovim in conjunction with lazy.vim to load lualine it displays and works just fine.  Using the starter provided (https://github.com/LazyVim/starter) and only disabling bufferline & enabling lualine however it does not work.

Below is a directory with the least amount of changes:
https://github.com/snaveevans/dotfiles/tree/try-lualine/lvim

### Steps To Reproduce

1. Follow instructions for to use starter
2. add `disabled.lua` in plugins directory and add bufferline to it
3. add new file called `lualine.lua` in plugins directory and add basic spec
```
{
    'nvim-lualine/lualine.nvim',
    dependencies = { 'nvim-tree/nvim-web-devicons' }
}
```

4. re-open nvim
5. open 2 buffers in split view
6. note only 1 status line is displayed for the 2 buffers only showing information for the selected buffer

### Expected Behavior

2 statuslines should be shown for each buffer in their respective window

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    {
      "akinsho/bufferline.nvim",
      enabled = false,
    },
    {
      "nvim-lualine/lualine.nvim",
      dependencies = { "nvim-tree/nvim-web-devicons" },
    },
  },
})
```

**Comment by snaveevans** [comment]
Here is a screen shot, the top is is nvim using lazy.nvim with lualine configured, the bottom the `nvim -u repro.lua`
<img width="1830" alt="Screenshot 2024-09-13 at 9 00 58 AM" src="https://github.com/user-attachments/assets/7982ba5b-6863-435d-a0b8-114da68906f0">

**Comment by dpetka2001** [comment]
That's because of [vim.opt.laststatus](https://github.com/LazyVim/LazyVim/blob/3dbace941ee935c89c73fd774267043d12f57fe2/lua/lazyvim/config/options.lua#L83). Change that value in your `options.lua` to whatever you want.

**Comment by snaveevans** [comment]
@dpetka2001 thank you! that was it!
