### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by tne-ops** [LazyVim/LazyVim#4441]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.1

### Operating system/version

MacOS 14.6.1

### Describe the bug

installed LazyExtras Markdown options and want to use MarkdownPreview, it is enabled, but when I run it, I only get a windows that says `Node.js v20.11.1`

Tearing my hair out, trying to figure out what I've done wrong. The core MarkdownPreview talks about setting https://github.com/iamcco/markdown-preview.nvim/issues/188 but setting mkdp_browser doesn't seem to help.

I tried :healthcheck but nothing interesting there.

Is there a node log somewhere, seems like it is trying to start a node server?

The https://www.lazyvim.org/extras/lang/markdown#markdown-previewnvim explanation seems to say that <leader>cp is tied to MarkdownPreviewToggle so confused why this node message comes up. Is there more setup to do? 

I had this working in my old vimscript and there is a yarn install that is needed, is this done or do I need to do manually.

Sorry to be so stupid, I just can't figure out how to debug :-)

### Steps To Reproduce

1. vim README.md
2. <leader>cp

---
What is get is no preview in the default browser (Safari) and instead I get a message window that just says
```
Node version 20.11
```

Seems like it is trying to do some sort of node setup

### Expected Behavior

Should see the Markdown file in a browser and it sync scrolls as you edit it.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s -- Minimal repro lua config
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
    -- from https://www.lazyvim.org/extras/lang/markdown#markdown-previewnvim
    {
      "iamcco/markdown-preview.nvim",
      ft = "markdown",
      cmd = { "MarkdownPreview", "MarkdownPreviewToggle", "MarkdownPreviewStop" },
      build = function()
        require("lazy").load({ plugins = { "markdown-preview.nvim" } })
        vim.fn["mkdp#util#install"]()
      end,
      config = function()
        vim.cmd([[do FileType]])
      end,
    },
  },
})
```

**Comment by dpetka2001** [comment]
Related issue at `markdown-preview` repo https://github.com/iamcco/markdown-preview.nvim/issues/695. Not LazyVim related.

**Comment by tne-ops** [comment]
Oh thanks for this find. Didn't search markdown hard enough was looking for lazyvim as a key but affects all new macOS installs. Strange a new bug my old neovim/vimscript install works fine.

Sent via Superhuman iOS ( ***@***.*** )

**Comment by gotgenes** [comment]
@dpetka2001
>Not LazyVim related.

I disagree. LazyVim did not make the installation of this plugin start failing, but [LazyVim includes this plugin in the Markdown extra](https://www.lazyvim.org/extras/lang/markdown#markdown-previewnvim).

I think [this PR](https://github.com/AstroNvim/astrocommunity/pull/1187/) provides a helpful way forward. I found it linked in [the markdown-preview.nvim issue](https://github.com/iamcco/markdown-preview.nvim/issues/695) that you posted above.

**Comment by dpetka2001** [comment]
The plugin installs just fine in latest HEAD with Node 20.17.0 due to #4196 and it also opens correctly in the browser (Firefox that I use) the corresponding markdown file. You just have to wait for a new LazyVim release or follow HEAD if you don't want to wait.

**Comment by folke** [comment]
Just made a new release!

Still need to go through a lot or PRs tomorrow...

**Comment by tne-ops** [comment]
Wow that's awesome. Thanks again for all the amazing and hard work. Learning a lot about the innards of neovim and how cool lazyvim is on install.

Sent via Superhuman iOS ( ***@***.*** )

**Comment by stepbystepcode** [comment]
https://github.com/LazyVim/LazyVim/issues/2214#issuecomment-1870063574
It works!
