### ISSUE TITLE
bug: Weird Scrollbar Appears on UI

### ISSUE THREAD

**Issue by leehpham** [LazyVim/LazyVim#4442]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.1

### Operating system/version

MacOS 14.6.1

### Describe the bug

![Screenshot 2024-09-15 at 9 29 09 AM](https://github.com/user-attachments/assets/d6ef3ffd-3728-4563-b5da-d80811e7f051)

This weird scrollbar keeps randomly appearing on the UI.
Once it shows up, it doesn't go away.
When I quit NeoVim and reopen, it goes away but it appears again shortly.

This seems like it has something to do with the dialog box of the API doc (`Shift + K` shows these dialog boxes).

### Steps To Reproduce

1. Open a TypeScript file with Neovim.
2. Start writing some code.
3. View the API doc of a certain API by placing the cursor over it and press `Shift + K`.

### Expected Behavior

The weird scrollbar shouldn't appear on the UI.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
Disable `noice.nvim` and if that solves your problem, then create an issue at `noice.nvim` Github repo with your findings. Never seen this before.

**Comment by leehpham** [comment]
@dpetka2001 
I tried disabling `noice.nvim` and it seems the problem went away. Will create an issue at `noice.nvim` instead.
Thank you very much.
