### ISSUE TITLE
feature: disable mason

### ISSUE THREAD

**Issue by linsui** [LazyVim/LazyVim#445]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

I don't want to install binaries with mason. I always use the system package manager. But I can't simply disable it since it's depended by some other packages.

### Describe the solution you'd like

Currently I disable the auto install behavior with

```lua
    {
        "williamboman/mason.nvim",
        opts = {
            ensure_installed = {},
        },
    },
    {
        "neovim/nvim-lspconfig",
        opts = function(_, opts)
            for server, server_opts in pairs(opts.servers) do
                server_opts.mason = false
            end
        end,
    },
```

It seems working but I still need to install mason. I thought mason can be an optional package and I can disable it with a global option.

### Describe alternatives you've considered

The Mason can be checked before used. If it's disabled, then it's not used without throwing an error.

**Comment by folke** [comment]
You can now disable mason and mason-lspconfig with:

```lua
return {
  { "williamboman/mason-lspconfig.nvim", enabled = false },
 { "williamboman/mason.nvim", enabled = false },
}
```

Will make a new release in a bit

**Comment by linsui** [comment]
Wow, thanks for you help!
