### ISSUE TITLE
bug: Folds are not opening if caret is not moving.

### ISSUE THREAD

**Issue by vdegenne** [LazyVim/LazyVim#4451]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.1

### Operating system/version

Linux Fedora

### Describe the bug

When a fold is closed moving the caret left or right will open the fold which is good behavior but the fold won't open if `l` is pressed while the caret is already at the end of the line (similarly the fold won't open if `h` is pressed while the caret is at the beginning of the line) because it's not considered as a caret move, however this should be extended to simply h and l press, regardless the caret position (especially because when a fold is closed the caret is shown at the beginning of the line no matter what, which makes it difficult to determine which way to go to open the fold).

Here's a video of the current behavior:

https://github.com/user-attachments/assets/9fb5ea86-a915-471a-9ee6-62c5067ae812

(keystrokes can be seen in the bottom right corner of the video.)

### Steps To Reproduce

Working steps:
1. go at the first line of any open fold
2. place the caret at the beggining of the line (`0`)
3. close the fold using `zc`
4. press `l` - this should open the fold again

Failing steps:
1. go at the first line of any open fold
2. place the caret at the end of the line (`$`)
3. close the fold using `zc`
4. press `l` - this **should** but doesn't open the fold again

### Expected Behavior

Folds should open when `h` or `l` is pressed.

**Comment by dpetka2001** [comment]
That is default Neovim behavior, nothing to do with LazyVim. `l` and `h` are default Neovim mappings for folds. 

Minimal repro without LazyVim
```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
-- local lazypath = vim.fn.expand("~/projects/plugins/lazy.nvim/")
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

vim.opt.ignorecase = true
vim.opt.tabstop = 2
vim.opt.shiftwidth = 2
vim.opt.foldexpr = "v:lua.vim.treesitter.foldexpr()"
vim.opt.foldmethod = "expr"

vim.g.mapleader = " "

-- install plugins
local plugins = {
	{ "folke/tokyonight.nvim" },
	{
		"nvim-treesitter/nvim-treesitter",
		build = ":TSUpdate",
		opts = {
			ensure_installed = {
				"lua",
			},
		},
		config = function(_, opts)
			require("nvim-treesitter.configs").setup(opts)
		end,
	},
	-- add any other plugins here
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
	dev = {
		path = "~/projects/plugins/",
	},
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```
If you wish for these mappings to behave like how you want, you'd better create a feature request in Neovim repo. LazyVim just uses the folds in its custom statuscolumn, but doesn't set any mappings for folds.

**Comment by vdegenne** [comment]
Maybe I should have used the tag `feature request` here. Why couldn't this just be an improvement from LazyVim over the default behavior?
I am not a configuration wizard but isn't it just a matter of adding two new maps in `keymaps.lua`? such as:
```lua
map("n", "h", "<Cmd>foldopen<Cr>")
map("n", "l", "<Cmd>foldopen<Cr>")
```
Of course the above will show an error message if there are no folds under the cursor but again I'm no wizard but there could be an easy way to check that.

**Comment by vdegenne** [comment]
Here's the code if anyone interested:

```lua
local function open_fold_if_exists(direction)
  if vim.fn.foldlevel(".") > 0 then
    return "zo" .. direction
  else
    return direction
  end
end

map("n", "h", function()
  return open_fold_if_exists("h")
end, { expr = true, silent = true })
map("n", "l", function()
  return open_fold_if_exists("l")
end, { expr = true, silent = true })
```

**Comment by dpetka2001** [comment]
You can use `foldclosed()` instead of `foldlevel()`, which only returns a positive number when a fold is closed, whereas `foldlevel()` will still return the nested level even if a fold is open. This way you can also omit `direction` in the `if` branch.

**Comment by vdegenne** [comment]
@dpetka2001 Thanks, I made a PR, since this ticket was closed not sure if you guys are interested, but it's there.

**Comment by dpetka2001** [comment]
@vdegenne I'm just a simple user like you who just tries to help people. It's up to the maintainer to review your PR. I have no say whatsoever.
