### ISSUE TITLE
bug: Disabling mini.pairs starts neovim with an error

### ISSUE THREAD

**Issue by andradei** [LazyVim/LazyVim#446]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

v0.8.3

### Operating system/version

EndeavorOS (arch-based)

### Describe the bug

If I disable mini.pairs like:

```lua
-- file: lua/plugins/mini.pairs.lua

return {
  {
    'echasnovski/mini.pairs',
    enabled = false,
  },
}
```

and restart neovim, I get an error saying this plugin can't be found while autopairing still works.

![image](https://user-images.githubusercontent.com/2653546/225833315-f0dc90f5-a719-4230-8fa9-b44290ece100.png)

### Steps To Reproduce

1. Create a `~/.config/nvim/lua/plugins/mini.pairs.lua` with the contents in the description above
2. Restart neovim

### Expected Behavior

`mini.pairs` get's disabled and neovim doesn't show initialization errors.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
You can't have a `dot` in a module name. That's not lazy, that's just how lua works. `lua/plugins/mini.pairs.lua`

**Comment by andradei** [comment]
Oh! E treats `.` and `/` the same. Thank you for the correction.
