### ISSUE TITLE
bug: keymaps issue

### ISSUE THREAD

**Issue by alex35mil** [LazyVim/LazyVim#4461]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.1

### Operating system/version

macOS 14.6.1 (23G93)

### Describe the bug

When I set keymaps, both sequential and non-sequential via `lazy.keys`, they work unreliably. It can work one or two times, then stop working. Or it might doesn't work at all. Which-key doesn't pick it up either.

### Steps To Reproduce

1. Use repro config.
2. Hit `<C-a>` a few times and see if it works each time.
3. Hit `<C-b>b` a few times and see if it works each time.

### Expected Behavior

1. Bound action should be executed on each keymap dispatch.
2. Which-key should pick it up after `<C-b>`.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
    spec = {
        {
            "LazyVim/LazyVim",
            import = "lazyvim.plugins",
            keys = {
                { "<C-a>", [[<Cmd>echo "a"<CR>]], mode = "n", desc = "a" },
                { "<C-b>b", [[<Cmd>echo "b"<CR>]], mode = "n", desc = "b" },
            },
        },
    },
})
```

**Comment by dpetka2001** [comment]
It just doesn't show the notification (probably something to do with how `nvim-notify` shows subsequent same notifications). Just change the `rhs` to `WhichKey` instead of `echo 'something'` for example and you will see each time it will open the which-key menu.

**Comment by alex35mil** [comment]
Lol, that's a bummer. I figured what the issue is. When I set `keys` on a plugin spec, which is neither core nor extra in LazyVim, then these keys don't work. Should I open a new issue or update this one?

**Comment by folke** [comment]
@alex35mil I'd be very, very surprised that that's the case. 100% certain a config issue on your end.

And check what @dpetka2001 says. That is for sure the case and would explain why you thought it wasn't working. (but it does)

**Comment by alex35mil** [comment]
@folke I’m AFK right now, will double check later. But I used echo/notifier only in reproduction example, ie, it’s not what triggered the original issue. The original issue is that I simply can’t set any keymaps on plugins that are not a part of the LazyVim. When I literally copy/paste the same keymap to the keys section of the plugin that is a part of LazyVim, then this keymap works.

**Comment by dpetka2001** [comment]
A link to your dotfiles would be helpful.

**Comment by alex35mil** [comment]
@dpetka2001 Ironically, I bumped into it when I was setting up `diffview` 😅

I pushed my current config: https://github.com/alex35mil/dotfiles/tree/master/home/.config/nvim

Note I added [this keymap](https://github.com/alex35mil/dotfiles/blob/b4ab233bdbc8b7c00736945b2e914c7cf678a129/home/.config/nvim/lua/plugins/diffview.lua#L6) on the `diffview` spec, and it doesn't work for me. While [this keymap](https://github.com/alex35mil/dotfiles/blob/b4ab233bdbc8b7c00736945b2e914c7cf678a129/home/.config/nvim/lua/plugins/flash.lua#L8) added on the `flash` config works.

P.S. I use Neovide. `D` stands for `⌘`.

**Comment by dpetka2001** [comment]
This is too complicated and I can't go through the whole structure of your configuration. Sorry about that. Start simple with cloning the LazyVim starter template in a different directory than your current configuration (for example `~/.config/lazyvim`). Then add a simple `diffview.nvim` spec like in my example above in `~/.config/lazyvim/lua/plugins/diffview.lua`. You will see that it works. You should invoke Neovim with `NVIM_APPNAME=lazyvim nvim` (or whatever other name you will give the new directory that you will clone the LazyVim starter template).

This way you can still keep using your personal configuration and doing the migration at small steps, so you don't mess anything up. When you are satisfied with the process of migration, make a backup of your current configuration and rename `~/.config/lazyvim` to `~/.config/nvim`.

Unfortunately it's a problem with your process of migration.

**Comment by alex35mil** [comment]
I just tried to change this:

```lua
keys = {
    { "<D-g>d", fn.toggle_diff, mode = { "n", "v", "i" }, desc = "Git: Toggle diff" },
},
```

to this:

```lua
keys = function()
    return {
        { "<D-g>d", fn.toggle_diff, mode = { "n", "v", "i" }, desc = "Git: Toggle diff" },
    }
end,
```

and it works now 🤷‍♂️

**Comment by dpetka2001** [comment]
Can you try moving the `function fn.toggle_diff()` before the `NVDiffView` table and leave your mapping as it was previously?

**Comment by alex35mil** [comment]
Ah, yeah, that worked! I was sure that this poor man’s hoisting worked for my telescope config. But now I see that I changed it there to function too to disable the default keymaps.

**Comment by dpetka2001** [comment]
It's a problem with your functions that you then call in your keymaps. Put all the functions before `NVDiffView`. It's essentially the same as when you do `require("something")` inside a Lua table. It will get evaluated during the `lazy.nvim` parsing phase. If you put it in a function `keys = function()`, then you make it a closure and will be evaluated when called upon. By putting all the functions `fn.something` before `NviDiffView`, then the table `NVDiffView` and then the functions `NVDiffView.whatever` you shouldn't have a problem. Just cloned your dotfiles and tried that and it works.

**Comment by alex35mil** [comment]
Yup, the whole point of this `fn` thing is to hoist utility functions while keeping them below the spec.

**Comment by alex35mil** [comment]
Unfortunately, there's no way in Lua to pass things by reference, so the easiest solution that keeps utilities at the bottom + hoisted and wouldn't affect lazy semantics would be:

```lua
    keys = {
        { "<D-g>d", function() fn.toggle_diff() end, mode = { "n", "v", "i" }, desc = "Git: Toggle diff" },
    }
```
