### ISSUE TITLE
bug: LazyExtras for lang:lean not working

### ISSUE THREAD

**Issue by Karthik-Dulam** [LazyVim/LazyVim#4472]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.1 Build type: Release

### Operating system/version

Archlinux

### Describe the bug

Using the LazyVim starter pack or the minimal config with the lang:lean LazyExtra gives the following error and it gets stuck on "processing file". 
(Lean works on vs code so likely not a problem with the installation)
```
Error detected while processing BufNewFile Autocommands for "*":
Error executing lua callback: /usr/share/nvim/runtime/filetype.lua:35: Error executing lua: /usr/share/nvim/runtime/filetype.lua:36: BufNewFile Autocommands for "*"..Fi
leType Autocommands for "*"..function <SNR>1_LoadFTPlugin[20]..script /home/kar/.local/share/nvim/lazy/lean.nvim/ftplugin/lean/lean.lua: Vim(runtime):E5113: Error while
 calling lua chunk: .../.local/share/nvim/lazy/lean.nvim/ftplugin/lean/lean.lua:40: attempt to call method 'should_modify' (a nil value)
stack traceback:
        .../.local/share/nvim/lazy/lean.nvim/ftplugin/lean/lean.lua:40: in main chunk
        [C]: in function 'nvim_cmd'
        /usr/share/nvim/runtime/filetype.lua:36: in function </usr/share/nvim/runtime/filetype.lua:35>
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:35: in function </usr/share/nvim/runtime/filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_cmd'
        /usr/share/nvim/runtime/filetype.lua:36: in function </usr/share/nvim/runtime/filetype.lua:35>
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:35: in function </usr/share/nvim/runtime/filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:35: in function </usr/share/nvim/runtime/filetype.lua:10>
```

### Steps To Reproduce

1. Use the starter pack config or the minimal config
2. Install lean (elan) using the recommended steps at https://lean-lang.org/lean4/doc/quickstart.html
3. make an empty lean project and open a .lean file

### Expected Behavior

Process the file and run

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
That's a problem with the plugin itself. Kindly report it at the plugin's repo.

**Comment by Karthik-Dulam** [comment]
Thank you. Will do that.

**Comment by dpetka2001** [comment]
Should be fixed after updating `lean.nvim` to latest version.
