### ISSUE TITLE
bug: toggle_auto_expand_width in neo-tree will flash window

### ISSUE THREAD

**Issue by Guan9Wu** [LazyVim/LazyVim#4474]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.1

### Operating system/version

Archlinux

### Describe the bug

In Neo-tree, I toggle auto expand width to see the long file name, then my neovim window will always flash, as the video shows.

https://github.com/user-attachments/assets/1734e0fc-6755-42fb-9a91-911e5c131376

### Steps To Reproduce

1. Use Lazyvim defaut configure.
1. Open neo-tree.
3. toggle auto expand width when there has long file name.

### Expected Behavior

stable and not flashing.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
Cannot reproduce with the minimal repro. Following screencast

[Screencast_2024-09-21-19-06-14.webm](https://github.com/user-attachments/assets/0e42f23c-0e7b-4fd8-99e9-db9df9904fd8)

Maybe something to do with your terminal or your personal configuration? I'm using kitty as terminal.

**Comment by folke** [comment]
auto-expand doesn't work with edgy.

See https://github.com/folke/edgy.nvim?tab=readme-ov-file#%EF%B8%8F-limitations
