### ISSUE TITLE
bug: Node Module included in FZF Grep Search CWD

### ISSUE THREAD

**Issue by itokun99** [LazyVim/LazyVim#4475]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.1

### Operating system/version

Mac 14.6.1

### Describe the bug

How can i exclude node_module result search in fzf grep cwd search

<img width="627" alt="Screenshot 2024-09-22 at 15 40 10" src="https://github.com/user-attachments/assets/ec84b3ed-415e-41e3-b7fd-eb8805efad5a">

### Steps To Reproduce

1. open node js project
2. fzf grep search
3. type console.log

### Expected Behavior

hide node_modules in grep search

**Comment by dpetka2001** [comment]
How is this a LazyVim bug? Read the `fzf-lua` docs to see if you can configure it.
