### ISSUE TITLE
feature: nvim-ufo

### ISSUE THREAD

**Issue by Jomik** [LazyVim/LazyVim#448]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

I would like to be able to use https://github.com/kevinhwang91/nvim-ufo however I see now easy way to add
```lua
capabilities.textDocument.foldingRange = {
    dynamicRegistration = false,
    lineFoldingOnly = true
}
```

### Describe the solution you'd like

Have a field for adding custom capabilities in the lspconfig opts.

### Describe alternatives you've considered

Manually creating and maintaining a list of LSPs that I have installed.

**Comment by folke** [comment]
This is not a bug so please post in the discussions next time as is instructued in the issue template....



```lua
return {

  -- add folding range to capabilities
  {
    "neovim/nvim-lspconfig",
    opts = {
      capabilities = {
        textDocument = {
          foldingRange = {
            dynamicRegistration = false,
            lineFoldingOnly = true,
          },
        },
      },
    },
  },

  -- add nvim-ufo
  {
    "kevinhwang91/nvim-ufo",
    dependencies = "kevinhwang91/promise-async",
    event = "BufReadPost",
    opts = {},

    init = function()
      -- Using ufo provider need remap `zR` and `zM`. If Neovim is 0.6.1, remap yourself
      vim.keymap.set("n", "zR", function()
        require("ufo").openAllFolds()
      end)
      vim.keymap.set("n", "zM", function()
        require("ufo").closeAllFolds()
      end)
    end,
  },
}

```
