### ISSUE TITLE
bug: nvim in Ubuntu 24.04 cannot build treesitter [CLOSED - removed linuxbrew and reinstalled env natively)

### ISSUE THREAD

**Issue by dev4openid** [LazyVim/LazyVim#4485]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.11.0-dev

### Operating system/version

Ubuntu 24.04

### Describe the bug

Treesitter does not build at all.  Building from basic model all the plugins install and seems to operate with one exception.
I am following the recommended book at https://lazyvim-ambitious-devs.phillips.codes/course/chapter-1
The environment is:
Ubuntu 24.04
[/usr/lib/x86_64-linux-gnu/libc.so.6 ](libc6:amd64                                        2.39-0ubuntu8.2

BTW I have had correspondence with the Treesitter crowd, they have closed the issue and refer to yourselves, as they believe that it is a Lazyvim issue

In the many errors produced, I suspect that the check against libc6 (mine being 2.39  whereas the error signals a check for 2.38.   There are many errors relating to compilation. Might be a red herring?

The example I managed to capture is:
```
/home/linuxbrew/.linuxbrew/bin/ld: /usr/libexec/gcc/x86_64-linux-gnu/14/liblto_plugin.so: error loading plugin: /home/linuxbrew/.linuxbrew/lib/libc.so.6: version `GLIBC_2.38' not found (required by /usr/libexec/gcc/x86_64-linux-gnu/14/liblto_plugin.so)
collect2: error: ld returned 1 exit status
```

This being GLIBC_2.38 is redhat version vs. Debian/Ubuntu libc v2.39   - i.e. GLIBC is libc (just my libc is a slightly later version)  which is why I included the reference above (as indicated above)

### Steps To Reproduce

WHEN clean .config/nvim
DO
git clone https://github.com/LazyVim/starter ~/.config/nvim
rm -rf ~/.config/nvim/.git
THEN
Execute nvim

### Expected Behavior

nvim is to launch and execute all the plugins.
THEN
close  app and reopen
It should be fully usable (incl. treesitter)

### Repro

```lua
n/a
```

**Comment by dpetka2001** [comment]
Your correspondence with treesitter crowd doesn't mention anything about this being a LazyVim issue. They clearly say 

> In any case, this looks like you have a broken compiler installation; I strongly recommend to stick to the system compiler and not use linuxbrew etc. unless you know exactly what you're doing.

There's something wrong with at your OS level. Nothing to do with LazyVim.

**Comment by dev4openid** [comment]
Hi, well I have reinstalled all the compilers I am aware of - all in native
mode i.e. all sudo apt-get yet it still does not work.
I gave list to them of all the items I have made native.
So, please can someone advise on which compiler is the issue, then I can
investigate and remediate.
I'm kinda desperate here ;)
Thanks

**Comment by dpetka2001** [comment]
There's definitely something wrong with your OS. I just installed Ubuntu 24.04 in VirtualBox and installed Neovim and LazyVim without any problems. By default `gcc-13` is the installed compiler in Ubuntu. You more than probably ended up with a borked OS with your shenanigans installing `linuxbrew` and then uninstalling it and trying to install the native compiler. You should seek for proper guidance in Ubuntu support forums if there's a way to fix that or you should re-install your OS.

**Comment by Atticlmr** [comment]
this problem is caused by the version of glibc
you can try to download binary file of tree-sitter .
my system is ubuntu 22.04, so i download [ tree-sitter 24.0](https://github.com/tree-sitter/tree-sitter/releases/download/v0.24.0/tree-sitter-linux-x64.gz)

1. remove old version of tree-sitter
```
npm uninstall -g tree-sitter-cli
```
2. unzip tree-sitter you download, and move binary file into ` ~/.local/bin/`

```
gzip -d tree-sitter-linux-x64.gz
cd tree-sitter-linux-x64
sudo chmod +x tree-sitter

mv tree-sitter ~/.local/bin/tree-sitter
```

check version if suitable

```
tree-sitter --version
```

3. start nvim
```
nvim
```
