### ISSUE TITLE
feature: Allow FloatTerm buffers to be visible in buffer list

### ISSUE THREAD

**Issue by bbli** [LazyVim/LazyVim#4486]
### Did you check the docs?

- [X] I have read all the LazyVim docs
- [X] This is not a request for a new or existing extra (see above)

### Is your feature request related to a problem? Please describe.

Hi there currently when I use Telescope to search opened buffers, the terminal buffers created by Floaterm do not appear in that list

### Describe the solution you'd like

I would like for there to be an option to allow such buffers to be included in the buffer list. This is because sometime I would like to open a file and have the terminal on the side and in general, I would like to use Vim's native way of handling buffers/windows on these terminal buffers

### Describe alternatives you've considered

I investigated a bit with `vim.api.nvim_list_bufs`, but would like to know if LazyVim has an option to toggle this before going further

**Comment by dpetka2001** [comment]
I believe that depends on the plugin itself for how it creates the buffer for the floating terminal. It must be setting `buflisted = false` and it doesn't show up. Maybe make a feature request in the plugin repo or see if it provides a setting to configure it.

**Comment by bbli** [comment]
Add ok. I checked the plugin's repo and indeed it sets the buflisted to 0. Changing it to 1 fixes the issue. I will close this issue now. Thank you!
