### ISSUE TITLE
bug: Issue with grug-far Plugin - Error on Execution

### ISSUE THREAD

**Issue by albu-ali** [LazyVim/LazyVim#4498]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.1

### Operating system/version

Fedora Linux

### Describe the bug

Hey LazyVim Team,

I am experiencing an issue with the **grug-far** plugin in my Neovim setup. Every time I attempt to run it, I encounter the following error message:

```
Error executing vim.schedule lua callback: .../nvim/lazy/grug-far.nvim/lua/grug-far/actions/search.lua:110: attempt to index field 'stats' (a nil value)
stack traceback:
	.../nvim/lazy/grug-far.nvim/lua/grug-far/actions/search.lua:110: in function 'on_fetch_chunk'
	...azy/grug-far.nvim/lua/grug-far/engine/ripgrep/search.lua:210: in function 'on_finish'
	...azy/grug-far.nvim/lua/grug-far/engine/ripgrep/search.lua:98: in function 'on_finish'
	...grug-far.nvim/lua/grug-far/engine/fetchCommandOutput.lua:56: in function <...grug-far.nvim/lua/grug-far/engine/fetchCommandOutput.lua:54>
```

This error occurs specifically at line 110 of `search.lua`, indicating that the code is attempting to access the `stats` field, which appears to be nil. This issue persists regardless of the context in which I try to use the plugin.

I would appreciate any guidance or fixes you could provide regarding this matter.

### Steps To Reproduce

1. install lazyvim 
2. run checkhealth
3. open any file 
4. access grug-far using space+s+r
5. type any thing to replace and see the error  

### Expected Behavior

Expected the grug-far work without any issue 

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by albu-ali** [comment]
BTW I try the repro.lua with different device (that I use Arch on it BTW) and it show me very similar issue to this but at the end it give me the same error!

**Comment by dpetka2001** [comment]
The error comes directly from `grug-far`. Better report your issue at `grug-far` repo.

**Comment by albu-ali** [comment]
> The error comes directly from `grug-far`. Better report your issue at `grug-far` repo.

At last it's not from my setup this time :)

**Comment by dpetka2001** [comment]
Fixed upstream.
