### ISSUE TITLE
bug: `M.wk(lhs, toggle)` make it unsafe to use `toggle.map` setting keymap.

### ISSUE THREAD

**Issue by PFiS1737** [LazyVim/LazyVim#4502]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.1; Build type: RelWithDebInfo; LuaJIT 2.1.1725453128

### Operating system/version

Linux 6.10.10-arch1-1 

### Describe the bug

The usage of `M.wk(lhs, toggle)` at the end of `toggle.map` make it **unsafe** to use it setting keymap, since it failed to override the description.

### Steps To Reproduce

1. boot nvim with `nvim -u repro.lua`
2. follow the comment in the repro.lua

### Expected Behavior

Get which-key hint with a right description.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(
  vim.fn.system(
    "curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"
  )
)()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
    {
      "nvim-treesitter/nvim-treesitter",
      keys = {
        {
          -- add any keybindings in any plugins,
          -- then boot nvim, type `space+u`,
          -- you can see the description of `b` is " Disable Background" instead of "Test description",
          -- but if you type `b` then, it will notify "Test".
          "<leader>ub",
          function()
            vim.notify("Test")
          end,
          desc = "Test description",
        },
      },
    },
  },
})
```

**Comment by dpetka2001** [comment]
That's because `M.wk` is implemented to only be used to add dynamic description and icons to `which-key` menu. So, if you want to override the keys that have been defined with `LazyVim.toggle.map` you should also include a `which-key` spec where you overwrite the descriptions.
```lua
		{
			"folke/which-key.nvim",
			opts = {
				spec = {
					{ "<leader>ub", desc = "Test description" },
				},
			},
		},
```

**Comment by PFiS1737** [comment]
This solved my problem. Sorry for the trouble, and thank you. I will close this issue as it may not be a bug.

**Comment by dpetka2001** [comment]
I made a PR, so that this is not needed any more. Hopefully the maintainer will accept it or just reject it as not planned because the default works by design. If you could also check the PR locally that would be appreciated.
