### ISSUE TITLE
bug: search highlight no longer dissapeares

### ISSUE THREAD

**Issue by idelice** [LazyVim/LazyVim#4516]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.1

### Operating system/version

macos 14.3

### Describe the bug

When search using `/`, it highlights matches, but the highlights are not disappearing when pressing `esc` anymore.

### Steps To Reproduce

1. open a file with some text
2. search for a word that exists in that text file using `/`
3. press `enter`
4. press `esc`

### Expected Behavior

I expect all highlighted texts are no longer highlighted once i press `esc`

**Comment by dpetka2001** [comment]
Was not able to reproduce with minimal repro
```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```
Can you try with the above minimal repro and test if you can reproduce? Otherwise it's something in your personal configuration.

Following screencast with minimal repro and executing a search and pressing `<esc>` to clear the search highlights.

[Screencast_2024-10-01-18-29-20.webm](https://github.com/user-attachments/assets/e9f81c4a-568f-4b6d-abc6-a075cba07729)

**Comment by idelice** [comment]
> Was not able to reproduce with minimal repro
> 
> vim.env.LAZY_STDPATH = ".repro"
> load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()
> 
> require("lazy.minit").repro({
>   spec = {
>     { "LazyVim/LazyVim", import = "lazyvim.plugins" },
>     -- add any other plugins here
>   },
> })
> 
> Can you try with the above minimal repro and test if you can reproduce? Otherwise it's something in your personal configuration.
> 
> Following screencast with minimal repro and executing a search and pressing `<esc>` to clear the search highlights.
> Screencast_2024-10-01-18-29-20.webm

Can confirm it doesn't happen with the minimal repro.

What can cause this?

**Comment by dpetka2001** [comment]
Something in your personal configuration. A conflicting keymap or some other plugin or even some autocmd that messes up with search highlighting? Those are my guesses. You're the one who uses your configuration and introduces the changes compared to default LazyVim, so you'll have to debug it yourself.

**Comment by idelice** [comment]
> Something in your personal configuration. A conflicting keymap or some other plugin or even some autocmd that messes up with search highlighting? Those are my guesses. You're the one who uses your configuration and introduces the changes compared to default LazyVim, so you'll have to debug it yourself. Are you sure you didn't remap `<esc>` to something else?

`esc` was mapped to something else.. it happened after enabling a new plugin.

Thank you!
