### ISSUE TITLE
bug: Neotest watch toggle and querying Neotest help pages throws errors

### ISSUE THREAD

**Issue by rbhanot4739** [LazyVim/LazyVim#4517]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.1

### Operating system/version

Macos 14.7

### Describe the bug

I am running LazyVim with `python` and `test` extra and for some reason running the Neotest watch toggle and looking for neotest help pages breaks for me. When I run `require("neotest").watch.toggle(vim.fn.expand("%"))` via `<leader>tw` I get the following error trace

```
E5108: Error executing lua: ...bhanot/.local/share/nvim/lazy/nvim-nio/lua/nio/tasks.lua:100: Async task failed without callback: The coroutine failed with this message: 
...e/nvim/lazy/neotest/lua/neotest/consumers/watch/init.lua:36: attempt to call field 'supports_method' (a table value)
stack traceback:
	...e/nvim/lazy/neotest/lua/neotest/consumers/watch/init.lua: in function 'get_valid_client'
	...e/nvim/lazy/neotest/lua/neotest/consumers/watch/init.lua:51: in function 'get_lsp_client'
	...e/nvim/lazy/neotest/lua/neotest/consumers/watch/init.lua:110: in function 'watch'
	...e/nvim/lazy/neotest/lua/neotest/consumers/watch/init.lua:160: in function 'func'
	...bhanot/.local/share/nvim/lazy/nvim-nio/lua/nio/tasks.lua:173: in function <...bhanot/.local/share/nvim/lazy/nvim-nio/lua/nio/tasks.lua:172>
stack traceback:
	[C]: in function 'error'
	...bhanot/.local/share/nvim/lazy/nvim-nio/lua/nio/tasks.lua:100: in function 'close_task'
	...bhanot/.local/share/nvim/lazy/nvim-nio/lua/nio/tasks.lua:122: in function 'step'
	...bhanot/.local/share/nvim/lazy/nvim-nio/lua/nio/tasks.lua:150: in function 'toggle'
	...im/lazy/LazyVim/lua/lazyvim/plugins/extras/test/core.lua:117: in function <...im/lazy/LazyVim/lua/lazyvim/plugins/extras/test/core.lua:117>
```

Even if I try to search neotest help pages with `<leader>sh` it fails with following errors
```
E5108: Error executing lua: vim/_editor.lua:0: nvim_exec2(): Vim(help):E661: Sorry, no 'en' help for neotest.watch
stack traceback:
	[C]: in function 'nvim_exec2'
	vim/_editor.lua: in function 'cmd'
	...lazy/telescope.nvim/lua/telescope/builtin/__internal.lua:806: in function 'run_replace_or_original'
	...re/nvim/lazy/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'run_replace_or_original'
	...re/nvim/lazy/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
	...hare/nvim/lazy/telescope.nvim/lua/telescope/mappings.lua:293: in function <...hare/nvim/lazy/telescope.nvim/lua/telescope/mappings.lua:292>
```
Even if I directly do `:h neotest` I land on `neotest-python` help page and `neotest` help page.

### Steps To Reproduce

1. Load LazyVim with above config and open a python file.
2. Press `<leader>tw` or run  `=require("neotest").watch.toggle(vim.fn.expand("%"))` to toggle test watch. 
3. Open any file and press `<leader>sh` and type `neotest.watch` and hit `enter`. 

On both 2 and 3 you should see above mentioned errors.

### Expected Behavior

The `help` search via telescope or native help search should query neotest help page. And run watch to toggle the watch as demonstrated on Neotest github page.

### Repro

```lua
LazyVim config

local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
  local lazyrepo = "https://github.com/folke/lazy.nvim.git"
  local out = vim.fn.system({ "git", "clone", "--filter=blob:none", "--branch=stable", lazyrepo, lazypath })
  if vim.v.shell_error ~= 0 then
    vim.api.nvim_echo({
      { "Failed to clone lazy.nvim:\n", "ErrorMsg" },
      { out, "WarningMsg" },
      { "\nPress any key to exit..." },
    }, true, {})
    vim.fn.getchar()
    os.exit(1)
  end
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({

  spec = {
    -- add LazyVim and import its plugins
    {
      "LazyVim/LazyVim",
      import = "lazyvim.plugins",
    },
    { import = "lazyvim.plugins.extras.test.core" },
    { import = "lazyvim.plugins.extras.dap.core" },
    { import = "lazyvim.plugins.extras.lang.python" },
    { import = "plugins.neotest" },


  },
  defaults = {
    lazy = false,
    version = false,
  },
  install = { colorscheme = { "tokyonight", "habamax" } },
  checker = {
    enabled = true,
    notify = false,
  performance = {
    rtp = {
      -- disable some rtp plugins
      disabled_plugins = {
        "gzip",
        "tarPlugin",
        "tohtml",
        "tutor",
        "zipPlugin",
      },
    },
  },
})
```
Contents of `lua/plugins/neotest.lua`
```
return {
  "nvim-neotest/neotest",
  keys = {
    {
      "<leader>tT",
      function()
        require("neotest").run.run(LazyVim.root())
      end,
      desc = "Run All Test Files",
    },
  },

  opts = {
    adapters = {
      ["neotest-python"] = {
        dap = { justMyCode = true },
        pytest_discover_instances = true,
      },
    },
  },
}
```

#### Edit 1: 

The error message on search help could be happening for other plugins as well, atleast I experienced it for `mini.surround` as well, the same error that I was getting for `neotest`. Not sure if there is something wrong with my setup although I tested it pretty bare born and an almost vanilla LazyVim.

**Comment by dpetka2001** [comment]
This error comes straight from neotest plugin. You should report it at plugin's github repo if you want it resolved.

**Comment by rbhanot4739** [comment]
@dpetka2001 But the same is happening for `mini.surround` as well atleast for the help pages.

**Comment by dpetka2001** [comment]
The help pages are only available when the plugin is loaded. If you do `<leader>tt` then the plugin will load and the help pages will be available. That's how it works with Telescope. `Fzf-lua` on the other hand can search through the available help pages even if the plugin is not loaded.

**Comment by rbhanot4739** [comment]
@dpetka2001 Thank you, I think that makes sense, I didn't realize it. I filed the issue at Neotest repo.
