### ISSUE TITLE
bug: 'lspconfig.server_configurations.tailwindcss' doesn't exist in nvim-lspconfig anymore

### ISSUE THREAD

**Issue by iangrayhazzard** [LazyVim/LazyVim#4519]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.1

### Operating system/version

MacOS 15.1

### Describe the bug

nvim-lspconfig [renamed a directory from "server_configurations" => "configs" ](https://github.com/neovim/nvim-lspconfig/pull/3330)

lazyvim links directly to this directory which is now missing in `lua/lazyvim/plugins/extras/lang/tailwind.lua:31`

### Steps To Reproduce

update nvim-lspconfig to latest and see the errors when you open a buffer associated with tailwindcss lsp

### Expected Behavior

no error

**Comment by dpetka2001** [comment]
There's already #4518 about this. Just wait for it to be merged.
