### ISSUE TITLE
bug: unable to auto import Next Image component

### ISSUE THREAD

**Issue by alivault** [LazyVim/LazyVim#4529]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.1

### Operating system/version

macOS 14.5

### Describe the bug

when running `<leader>ca` on a missing Next Image component, the code action to import the Next Image is missing:
![Image](https://github.com/user-attachments/assets/448b73ac-a8b7-4931-9efb-fde1f687a11b)
Also `<leader>cM` fails to auto import the Next Image component.

### Steps To Reproduce

1. in a Next project, add an <Image/> and try to import it using `<leader>ca` or `<leader>cM`
2. observe it doesn't work

### Expected Behavior

it should work

### Repro

vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})

**Comment by folke** [comment]
That's not a LazyVim issue and more a lsp configuration issue on your end. Closing...
