### ISSUE TITLE
bug: unable to override neotest default config

### ISSUE THREAD

**Issue by Dronakurl** [LazyVim/LazyVim#4538]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.11.0-dev-888+g4075e613b

### Operating system/version

Ubuntu 24.04

### Describe the bug

I want to customize the call to pytest for neotest.

I set up the `test.core` extra and the `lang.python` extra.

As described here:
https://www.lazyvim.org/extras/test/core
... I now wanted to use custom command line arguments.

This is my configuration for that.

```lua
  {
    "nvim-neotest/neotest",
    opts = {
      adapters = {
        ["neotest-python"] = {
          runner = "pytest",
          args = { "-s", "--no-header", "--log-cli-level=DEBUG" },
        },
      },
    },
}
```

The problem is that the config, e.g. the runner and args, is completely ignored. I can put `runner='askdadja'` and still, pytest will run with the configuration given by the `pyproject.toml` 

I copied the full spec of the neotest config to try to pin down the problem. I thought, that maybe another config or the wrong config is called, but everything looks fine. In this part of the code, the config is the one I provided and also the adapter is supposed to work like this
```lua
elseif meta and meta.__call then 
    adapter(config)
```

As this configuration of neotest and neotest-python works outside lazyvim and also when overriding the configuration of `test.core` extra, this is an issue with lazyvim. The strange thing is that I could not pin down where the configuration is lost (see the above paragraph) 

### Steps To Reproduce

1. INstall test.core and lang.python Extras
2. Put the above config in the .config folder, for testing, set runner to some gibberish to see if the config is used
3. Run a test with neotest (I used "run nearest")
4. Config is not used

### Expected Behavior

The config should be used and the arguments used in the pytest call

**Comment by folke** [comment]
How is this a LAzyVim issue?

**Comment by Dronakurl** [comment]
Ah, you think, I should check if this works when I just use a plain neotest config?
I will try that.
I thought, maybe there is some other place where lang.python overrides my neotest.python config

**Comment by Dronakurl** [comment]
So I think it is really LazyVim overriding some config.
Here is a very basic `init.lua` that only installs neotest and neotest python.
You can try out that the config is respected


```lua
-- Bootstrap lazy.nvim
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
	local lazyrepo = "https://github.com/folke/lazy.nvim.git"
	local out = vim.fn.system({ "git", "clone", "--filter=blob:none", "--branch=stable", lazyrepo, lazypath })
	if vim.v.shell_error ~= 0 then
		vim.api.nvim_echo({
			{ "Failed to clone lazy.nvim:\n", "ErrorMsg" },
			{ out, "WarningMsg" },
			{ "\nPress any key to exit..." },
		}, true, {})
		vim.fn.getchar()
		os.exit(1)
	end
end
vim.opt.rtp:prepend(lazypath)

-- Make sure to setup `mapleader` and `maplocalleader` before
-- loading lazy.nvim so that mappings are correct.
-- This is also a good place to setup other settings (vim.opt)
vim.g.mapleader = " "
vim.g.maplocalleader = "\\"

-- Setup lazy.nvim
require("lazy").setup({
	spec = {
		-- add your plugins here
		--
		{
			"nvim-neotest/neotest",
			dependencies = {
				"nvim-neotest/nvim-nio",
				"nvim-neotest/neotest-python",
				"nvim-lua/plenary.nvim",
				"nvim-treesitter/nvim-treesitter",
				"antoinemadec/FixCursorHold.nvim",
			},
			config = function()
				require("neotest").setup({
					adapters = {
						require("neotest-python")({
							runner = "asdsaasd", --- some gibberish to see if the config works
							args = { "-s", "--no-header", "--log-cli-level=DEBUG" },
						}),
					},
				})
			end,
		},
	},
	-- Configure any other settings here. See the documentation for more details.
	-- colorscheme that will be used when installing plugins.
	install = { colorscheme = { "habamax" } },
	-- automatically check for plugin updates
	checker = { enabled = true },
})

vim.keymap.set("n", "<C-t>", function()
	require("neotest").run.run()
	vim.notify("Running tests")
end, { desc = "Run test" })
```

In neovim run `TSInstall python` 

Then try to run a test on a very basic python file in an otherwise empty directory

```python
import logging
log= logging.getLogger(__name__)

logging.basicConfig(filename='myapp.log', level=logging.INFO)


def test_assert():
    log.error("huhuH")
    assert False
```

**Comment by Dronakurl** [comment]
I pinned it down to the configuration of `test.core` 
Here is a configuration that actually uses the config for neotest, as it overrides the test extra's behaviour.
@folke: Could you please have a second look on this issue?

```lua
  {
    "nvim-neotest/neotest",
    dependencies = {
      "nvim-neotest/nvim-nio",
      "nvim-neotest/neotest-python",
      "nvim-lua/plenary.nvim",
      "nvim-treesitter/nvim-treesitter",
      "antoinemadec/FixCursorHold.nvim",
    },
    config = function()
      require("neotest").setup({
        adapters = {
          require("neotest-python")({
            runner = "adas", -- some gibberish to see if the config works
            args = { "-s", "--no-header", "--log-cli-level=DEBUG" },
          }),
        },
      })
    end,
  },
```

**Comment by folke** [comment]
How are you using the extras?
You are 100% certain that your own plugin configs come **after** importing the extras right?

**Comment by Dronakurl** [comment]
I disabled the LazyExtras and just put the full config of `test.core` into my config to debug.
What I found out, that this does not work

```lua
local adapter = require(name)
-- ... in the ifelse conditions, we end up here:
adapter(config)
```

but this does:
```lua
local adapter = require(name)(config)
-- ... then commenting the ifelse conditions
```

But I don't understand why. This is no fix, because I guess the conditions are there for a reason

**Comment by Dronakurl** [comment]
Yes, this works

**Comment by dpetka2001** [comment]
Unfortunately, I don't know much about neotest and if this change potentially breaks something else. So, I'll refrain from creating a PR for something that I don't fully understand and leave it up to Folke to verify if this is indeed the correct solution.

**Comment by dpetka2001** [comment]
But that only applies for the `neotest-python` adapter from what I've looked into the code. What if other adapters actually return a function in their `meta.__call()` function? Maybe this should be guarded only for the `neotest-python` adapter and for the rest just do `adapter(config)` like it is already? Really no idea if this is actually the solution for all adapters or only for the `neotest-python` adapter...

**Comment by dpetka2001** [comment]
So, I've looked into plenary, neotest-python, neotest-golang and neotest-jest and their `metatable.__call` functions all seem to return a table. Haven't gone through all the rest of the adapters mentioned in the neotest docs. Is it safe to assume that what I mentioned above is the norm for all adapters?

**Comment by folke** [comment]
Should be fixed now. Let me knwo if you'd still have issues!

**Comment by dpetka2001** [comment]
@folke does this hold true for all adapters? Is it possible that the call returns a function? Or is a table the norm for all neotest adapters? That's why i proposed the check about what `adapter(config)` returns but i'm really not familiar with this concept.

**Comment by folke** [comment]
WE always need to return something in the adapter, so I think it alsways needs to be set.
