### ISSUE TITLE
bug: Custom LSP server does not attach to buffer

### ISSUE THREAD

**Issue by Sleepful** [LazyVim/LazyVim#455]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.3

### Operating system/version

MacOS

### Describe the bug

When looking at `:LspInfo` my LSP server is not attached, an `LspAttach` event is never fired, although LspInfo shows it as a possible configuration:

```
 Press q or <Esc> to close this window. Press <Tab> to view server doc.
 
 Language client log: /Users/jose/.local/state/nvim/lsp.log
 Detected filetype:   elixir
 
 0 client(s) attached to this buffer: 
 
 Other clients that match the filetype: elixir
 
 Config: lexical
     filetypes:         elixir, eelixir, heex, surface
     root directory:    /Users/jose/Code/token_refresh
     cmd:               /Users/jose/Code/lexical/_build/prod/rel/lexical/start_lexical.sh
     cmd is executable: true
     autostart:         true
     custom handlers:   
 
 Configured servers list: tsserver, lexical, jsonls, lua_ls
```

Using `:LspStart lexical` doesn't help starting it.

Apparently functions like `launch()` inside `configs.lua` do launch because I was able to `print` stuff from the function.
I have been `print` debugging for a bit but it seems all the expected functions run fine, except `on_attach` functions which never trigger.

### Steps To Reproduce

This is what I tried for the config:
```lua
local custom_attach = function()
  print("Lexical has started.")
end

local lexical = {
  filetypes = { "elixir", "eelixir", "heex", "surface" },
  cmd = { "/Users/jose/Code/lexical/_build/prod/rel/lexical/start_lexical.sh" },
  settings = {},
}
return {
  {
    "neovim/nvim-lspconfig",
    init = function(_)
      print("init")
    end,
    opts = {
      servers = {
        lexical = {
          mason = false,
          filetypes = lexical.filetypes,
          on_attach = custom_attach,
          settings = lexical.settings,
        },
      },
      setup = {
        lexical = function(_, _)
          local lspconfig = require("lspconfig")
          local configs = require("lspconfig.configs")
          configs.lexical = {
            default_config = {
              filetypes = lexical.filetypes,
              root_dir = function(fname)
                print("finding root dir")
                local root = lspconfig.util.root_pattern("mix.exs", ".git")(fname) or vim.loop.os_homedir()
                print(root)
                return root
              end,
              cmd = lexical.cmd,
            },
          }
          return false
        end,
      },
    },
  },
}
```
Sorry if this isn't very helpful

### Expected Behavior

Expect the LSP client to attach to buffer.

**Comment by folke** [comment]
This isn't really a LazyVim issue, so closing.

You might check `:LspLog` to see if an error happened

**Comment by Sleepful** [comment]
I thought it might be related, lazy loading can cause... issues?
Anyway...
I updated Neovim to Nightly and now it works, no clue 🤦
