### ISSUE TITLE
bug: Python Extras Shows Duplicate Method Signature (Ruff and Pyright)

### ISSUE THREAD

**Issue by OceanTrader1** [LazyVim/LazyVim#4575]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0

### Operating system/version

MacOS 14.7

### Describe the bug

On insert mode, the method signature is displayed for Ruff and Pyright. This issue is similar to the duplicate diagnostics reported in https://github.com/LazyVim/LazyVim/issues/1819 and this [reddit post](https://www.reddit.com/r/neovim/comments/1b8ccyu/how_to_stop_automatic_display_of_signature_help/). Disabling the`hoverProvider` setting per the [ruff neovim guide](https://docs.astral.sh/ruff/editors/setup/#neovim) appears to have no effect on disabling the method signature from appearing in insert mode. While in normal mode, the hover shortcut `K` shows only one of the LSPs.

![Image](https://github.com/user-attachments/assets/58ddb79b-af34-44ad-9ead-ae7f5def2d9f)

![Image](https://github.com/user-attachments/assets/700b301a-8af0-46a7-837a-58dd1e18d12b)

### Steps To Reproduce

1. Create a fresh lazy vim installation `git clone https://github.com/LazyVim/starter ~/.config/nvim-test`
2. Add the python extras to the `Lazy.lua` configuration `{ import = "lazyvim.plugins.extras.lang.python" }`
3. Open a python file and let the LSPs auto install `NVIM_APPNAME=nvim-test nvim test.py`

### Expected Behavior

The expected behaviour when using the Python Extras default configuration is that only one of the LSPs provide method signature information while in insert mode.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    { import = "lazyvim.plugins.extras.lang.python" }
  },
})
```

**Comment by dpetka2001** [comment]
You have to do the same for `signatureHelpProvider` as with `hoverProvider`. It's up to the user to decide which one to choose over the other, pyright or ruff.

**Comment by dpetka2001** [comment]
Oh i see that `hoverProvider` is disabled by default for ruff in the Python Extra. It's pretty late for me now, so I'll create a PR about it tomorrow.

**Comment by jyuan0** [comment]
> Oh i see that `hoverProvider` is disabled by default for ruff in the Python Extra. It's pretty late for me now, so I'll create a PR about it tomorrow.

You might want to check that the duplicate is actually coming from ruff. I disabled and uninstalled ruff to test and I still see the duplicate. My guess is this is related to noice, but it's just a guess. Hope this helps.

**Comment by dpetka2001** [comment]
Yeah you're right. This seems to be a bug with `noice.nvim`. If I disable `opts.lsp.signature`, then it doesn't happen. As @jyuan0 said this also happens with only pyright and ruff uninstalled. This can't be solved here. Please create an issue at `noice.nvim` Github repo for it to be solved. I was also able to reproduce this with a minimal repo not including LazyVim, but including `noice.nvim`.

**Comment by OceanTrader1** [comment]
Ack. TY. As @jyuan0 pointed out, in this example, the duplicate signature is entirely coming from pyright and no signature is being provided by ruff. I also tested this using pyright in VSCode for comparison. I believe that the signature is intended to be displayed as an overload operator showing two different methods which explains why the bottom signature provides no syntax coloring because it is not currently activated. VSCode visualizes this in a slightly different manner by paginating the signatures (screenshots attached).

I agree this should be closed here. In light of this information, I would say that it is working as expected. Though, some may prefer a new feature in `noice.nvim` to paginate or limit the signatures when there are multiple signatures for a better user experience.

![Image](https://github.com/user-attachments/assets/23d0e51b-17be-4c07-b451-213bbf7e66e3)

![Image](https://github.com/user-attachments/assets/ac0ae1aa-901c-4cf7-aeec-12e97269993e)

**Comment by dpetka2001** [comment]
@OceanTrader1 You're right. I was just printing the default Neovim `vim.lsp.buf_request` and specifically the parameter `result` it provides and it does indeed return 2 objects for the signature. If you put a `return` in function `M:format` inside the loop, then it will stop at the first result. Not sure if this would be something the maintainer wants or not, so it's best, like you said, to create a feature request for this. 

By the way the same is happening in the cmp docs where you see entries depending on the number of signatures returned.
