### ISSUE TITLE
bug: types and function signatures in autocomplete popup don't appear until highlighted at least once.

### ISSUE THREAD

**Issue by flippette** [LazyVim/LazyVim#4580]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

Arch Linux

### Describe the bug

Types and function signatures don't appear in the autocomplete popup until highlighted at least once.

Initially, it looks like this (only the `(use ::path)` part appears):
![Image](https://github.com/user-attachments/assets/575830bf-1b52-40e5-b415-c8c22879cb6f)

Once I move the highlight selection around, types and signatures start to appear:
![Image](https://github.com/user-attachments/assets/6aa4919c-c067-4590-a4e6-49037116dea1)

### Steps To Reproduce

1. Trigger an autocomplete popup
2. Observe that types and signatures don't appear
3. Press Up/Down/C-n/C-p to move the selection
4. Observe that they start to appear

### Expected Behavior

Types and signatures should appear right away

### Repro

My config is just the default LazyVim config with a few extras enabled and snippets disabled.

https://github.com/flippette/nvim

**Comment by flippette** [comment]
(apologies for opening an issue in the middle of your vacation, folke 😅)

**Comment by dpetka2001** [comment]
Isn't that an issue with `nvim-cmp`?

**Comment by flippette** [comment]
I can't find anything in `nvim-cmp`'s issues, and I forgot to add that this doesn't happen with `clangd` 😅

**Comment by dpetka2001** [comment]
Can you reproduce this with a minimal repro without LazyVim? If yes, then it's a problem with either `nvim-cmp` or `rust-analyzer`. If not, then some configuration in LazyVim is causing this.

**Comment by dpetka2001** [comment]
So, I did a default LazyVim installation from scratch and only installed the Rust Extra and this doesn't seem to happen. Since I don't do Rust I just asked GPT to give me some Rust code.

Screencast following

https://github.com/user-attachments/assets/825bf8af-d9db-4296-bf2a-add239571662

**Comment by flippette** [comment]
Sorry for not replying earlier, I'm in the middle of midterms right now 😅



> So, I did a default LazyVim installation from scratch and only installed the Rust Extra and this doesn't seem to happen. Since I don't do Rust I just asked GPT to give me some Rust code. I can see the signatures from the beginning just as I type and the suggestions appear like in your second picture.
> 
> Screencast following
> Screencast_2024-10-15-13-16-03.webm

Huh, that's curious. I'll see what's wrong with my config then.

**Comment by dpetka2001** [comment]
No worries about replying. Just wanted to show you how it looks with a default LazyVim installation with just the Rust Extra enabled. Good luck with your exams 😄

**Comment by flippette** [comment]
I just updated and it seems to have been fixed recently, closing now.
