### ISSUE TITLE
feature: Enable catppuccin integration with bufferline if the colorscheme is catppuccin

### ISSUE THREAD

**Issue by xronin01** [LazyVim/LazyVim#4581]
### Did you check the docs?

- [x] I have read all the LazyVim docs
- [x] This is not a request for a new or existing extra (see above)

### Is your feature request related to a problem? Please describe.

Enable bufferline integration by default so you don't have to configure it manually
``` lua
return {
  {
    "akinsho/bufferline.nvim",
    opts = {
      highlights = require("catppuccin.groups.integrations.bufferline").get({})
    },
  },
}
```

### Describe the solution you'd like

.

### Describe alternatives you've considered

.

**Comment by dotfrag** [comment]
I'm enabling the integration but I see no difference on the status line, what am I looking for?

**Comment by dpetka2001** [comment]
@dotfrag You will see that the close button `x` is color red and the separator is also a different color. Just created a PR for this.

**Comment by dotfrag** [comment]
You beat me to it, I just pushed..

**Comment by dpetka2001** [comment]
How did you do it? My way has a minor drawback if `LazyVim.config.colorscheme` is a function.

**Comment by dotfrag** [comment]
Commented on PR.

**Comment by folke** [comment]
Did it a bit different. Will only work when catppuccin is configured as the colorscheme. Won't update bufferline when loading catppuccin later.
