### ISSUE TITLE
feature: customize priority of user extras

### ISSUE THREAD

**Issue by nowaylifer** [LazyVim/LazyVim#4584]
### Did you check the docs?

- [x] I have read all the LazyVim docs
- [x] This is not a request for a new or existing extra (see above)

### Is your feature request related to a problem? Please describe.

As I see, there is currently no way to change priority of user extras (plugins from "plugins.extras" directory) as it is done with some builtin extras; all user extras are given the same priority of 50.

### Describe the solution you'd like

Possible solution is to expose `prios` table from https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/xtras.lua as a property on `LazyVim` global object so that user can modify it.

### Describe alternatives you've considered

I don't see how it can be done right now.

**Comment by dpetka2001** [comment]
Would be great if you could test the linked PR locally.

**Comment by nowaylifer** [comment]
Doesn't work. Frankly, I thought it would work only because I did some overwrite of LazyVim's object method which executed upon VeryLazy event...

**Comment by dpetka2001** [comment]
Yes, I was also experimenting with this. I'll delete the PR. The modification you make to the table is taking effect after the file loads but the Extras would have loaded in the meantime. You want to modify the table before it gets parsed by `lazy.nvim`. But I don't know of any other way except directly modifying the file itself.

**Comment by nowaylifer** [comment]
Basically, I need me certain extras load before another one. Maybe `vim.g.xtras_prios` would work?

**Comment by dpetka2001** [comment]
Which Extras are you having problems with? The only one I'm aware of is a PR about Avante that also includes a plugin spec for `render-markdown.nvim` and had to add an explicit entry into the `xtras.lua` file, so that `lazyvim.plugins.extras.lang.markdown` gets before any other Extras. I'll also take a look at `vim.g.xtras_prios` that you suggested.

**Comment by nowaylifer** [comment]
I mean my own user extras in "plugin.extras" directory, not lazyvim extras. In theory `xtras.lua` can extens `vim.g.xtras_prios` table, which can be defined before LazyVim plugin is loaded.

**Comment by dpetka2001** [comment]
Can you try the new one? It seems to be working on my end, since `options.lua` get loaded before the other plugin specs.

**Comment by nowaylifer** [comment]
It does work!

**Comment by dpetka2001** [comment]
Thank you for the idea of `vim.g.xtras_prios`. I had completely forgotten that `options.lua` load before the plugins specs and wasn't able to come up with another way of modifying the table myself.
