### ISSUE TITLE
add a spell language

### ISSUE THREAD

**Issue by verga** [LazyVim/LazyVim#459]
A simple question: how do I add the equivalent of "set spelllang=fr"

I tried to add to the config/options.lua file 

    local opt=vim.opt
    opt.spelllang={ "fr"}

but this does not work. I get the error ` spellfile#LoadFile(): No (writable) spell directory found.`, and "failed to create site/spell"

I apologize if this my question is not relevant here: You may then close the issiue

**Comment by verga** [comment]
You may close this issue.

I crated a `.config/nvim/spell` directory, and added to .config/nvim/lua/config/options the line `vim.opt.spelllang = {"en", "fr"}` this solved the problem. 
In between I noted the **discussions** forums for this kind of questions.

Thank you, I recently changed to the lua configuration and I am learning.

**Comment by ditsuke** [comment]
@verga nice to see you have it sorted. You can close the issue yourself, should see a "close issue" button at the bottom somewhere.

**Comment by verga** [comment]
OK!
