### ISSUE TITLE
feature: allowing users to turn on/off submodules

### ISSUE THREAD

**Issue by Bekaboo** [LazyVim/LazyVim#46]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Currently users can only specify a single plugin directory, under which all submodules are loaded, I use my personal config as an example:

```
...
│   ├── modules
│   │   ├── base
│   │   │   ├── configs.lua
│   │   │   └── init.lua
│   │   ├── completion
│   │   │   ├── configs.lua
│   │   │   ├── init.lua
│   │   │   └── snippets
│   │   │       ├── cpp.lua
│   │   │       └── markdown.lua
│   │   ├── lsp
│   │   │   ├── configs.lua
│   │   │   ├── init.lua
│   │   │   └── lsp-server-configs
│   │   │       └── sumneko_lua.lua
│   │   ├── markup
│   │   │   ├── configs.lua
│   │   │   └── init.lua
│   │   ├── misc
│   │   │   ├── configs.lua
│   │   │   └── init.lua
│   │   ├── tools
│   │   │   ├── configs.lua
│   │   │   └── init.lua
│   │   ├── treesitter
│   │   │   ├── configs.lua
│   │   │   └── init.lua
│   │   └── ui
│   │       ├── configs.lua
│   │       └── init.lua
...
```

with this structure, if I setup Lazy with `require('lazy').setup('modules')`, all submodules (i.e., `base`, `completion`, `lsp`, etc) will be taken into consideration, which is great, but when nvim is used as an embedded editor in vscode, I would like to enable only a few modules, in which case it would be convenient to set Lazy with:

```
require('lazy').setup({
    'modules.base',
    'modules.misc',
    'modules.treesitter',
})
```

### Describe the solution you'd like

See above

### Describe alternatives you've considered

See above

**Comment by folke** [comment]
That's already possible. Check the docs on import or see example usage here:
https://github.com/LazyVim/starter/blob/bd148b899de50dda6689b36f796b34c49a12c121/lua/config/lazy.lua#L15

You can even inside a spec file add an import with an `enabled` property that returns false when it should not be imported

**Comment by Bekaboo** [comment]
Oh, I didn't realize `import` does this job. Thanks!

**Comment by Bekaboo** [comment]
Hi, I tried setup specs for my submodules with

```lua
require('lazy').setup({
    spec = {
        { import = 'modules.base' },
        { import = 'modules.completion' },
        ...
    }
})
```

however Lazy complains:

```lua
Error detected while processing /home/zeng/.config/nvim/init.lua:
Invalid plugin spec {
  ["nvim-web-devicons"] = <function 1>
}
Invalid plugin spec {
  LuaSnip = <function 1>,
  ["copilot-cmp"] = <function 2>,
  ["copilot.lua"] = <function 3>,
  ["nvim-cmp"] = <function 4>
}
Invalid plugin spec {
  ["aerial.nvim"] = <function 1>,
  ["mason-lspconfig.nvim"] = <function 2>,
  ["mason.nvim"] = <function 3>,
  ["nvim-lspconfig"] = <function 4>,
  ["nvim-navic"] = <function 5>
}
Invalid plugin spec {
  ["clipboard-image.nvim"] = <function 1>
}
...
```

seems like that Lazy sources the `config.lua` files under these submodules (i.e. `modules.base.config.lua`, `modules.completion.config.lua`, etc), but ideally only `init.lua` files should be sourced if we treat `modules.base`, `modules.completion` as *submodules* (think about what `require('modules.base')` and `require('modules.completion')` will do in lua). Could you help me address this issue?

**Comment by folke** [comment]
Ah, no, that's not possible.

What you could do however, is letting the spec modules decide themselves if they need to load, so use `modules` and inside one of the module's inits, just return `{}` if they don't need to be imported
