### ISSUE TITLE
bug: Failed loading config.keymaps after enabling treesitter-context extra plugin

### ISSUE THREAD

**Issue by Wakotu** [LazyVim/LazyVim#4619]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.2

### Operating system/version

 Arch Linux x86_64

### Describe the bug

After I enable the treesitter-context extra plugin., the following error prompted each time neovim startup:

```text
Failed loading config.keymaps

vim/keymap.lua:0: E31: No such mapping

# stacktrace:
  - vim/keymap.lua:0 _in_ **nomap**
  - lua/config/keymaps.lua:19
  - /LazyVim/lua/lazyvim/config/init.lua:251
  - /LazyVim/lua/lazyvim/config/init.lua:250 _in_ **_load**
  - /LazyVim/lua/lazyvim/config/init.lua:261 _in_ **load**
  - /LazyVim/lua/lazyvim/config/init.lua:184
```

### Steps To Reproduce

1. enable the treesitter-context plugin
2. open neovim 

### Expected Behavior

Do not prompt error message at startup

### Repro

vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})

**Comment by Wakotu** [comment]
I found adjusting position of the line `{ import = "plugins" },` is the reason that causes this bug.

### Original lazy spec:
```lua
  spec = {
    -- add LazyVim and import its plugins
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- editor
    { import = "lazyvim.plugins.extras.editor.outline" },
    { import = "lazyvim.plugins.extras.ui.treesitter-context" },
    -- import/override with your plugins
    { import = "lazyvim.plugins.extras.coding.copilot" },
    -- language
    { import = "lazyvim.plugins.extras.lang.python" },
    { import = "lazyvim.plugins.extras.lang.clangd" },
    { import = "lazyvim.plugins.extras.lang.rust" },
    { import = "lazyvim.plugins.extras.lang.typescript" },
    { import = "lazyvim.plugins.extras.lang.vue" },
    { import = "lazyvim.plugins.extras.lang.tailwind" },
    { import = "lazyvim.plugins.extras.lang.tex" },
    { import = "lazyvim.plugins.extras.lang.cmake" },
    { import = "lazyvim.plugins.extras.lang.markdown" },
    { import = "lazyvim.plugins.extras.lang.toml" },
    -- formatter
    { import = "lazyvim.plugins.extras.formatting.black" },
    { import = "lazyvim.plugins.extras.formatting.prettier" },
    -- linter
    { import = "lazyvim.plugins.extras.linting.eslint" },
    { import = "plugins" },
    -- snippets
    { import = "lazyvim.plugins.extras.coding.luasnip" },
  },
```

### buggy lazy spec
```lua
  spec = {
    -- add LazyVim and import its plugins
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- editor
    { import = "lazyvim.plugins.extras.editor.outline" },
    { import = "lazyvim.plugins.extras.ui.treesitter-context" },
    -- import/override with your plugins
    { import = "lazyvim.plugins.extras.coding.copilot" },
    -- language
    { import = "lazyvim.plugins.extras.lang.python" },
    { import = "lazyvim.plugins.extras.lang.clangd" },
    { import = "lazyvim.plugins.extras.lang.rust" },
    { import = "lazyvim.plugins.extras.lang.typescript" },
    { import = "lazyvim.plugins.extras.lang.vue" },
    { import = "lazyvim.plugins.extras.lang.tailwind" },
    { import = "lazyvim.plugins.extras.lang.tex" },
    { import = "lazyvim.plugins.extras.lang.cmake" },
    { import = "lazyvim.plugins.extras.lang.markdown" },
    { import = "lazyvim.plugins.extras.lang.toml" },
    -- formatter
    { import = "lazyvim.plugins.extras.formatting.black" },
    { import = "lazyvim.plugins.extras.formatting.prettier" },
    -- linter
    { import = "lazyvim.plugins.extras.linting.eslint" },
    -- snippets
    { import = "lazyvim.plugins.extras.coding.luasnip" },

    { import = "plugins" },
  },
```

**Comment by dpetka2001** [comment]
I just tried this and can't reproduce. I tried a default LazyVim installation from scratch with the buggy lazy spec that you mention and I see no problems when opening Neovim. The error comes from your `/lua/config/keymaps.lua` file. What do you have on line 19 in that file?

**Comment by dpetka2001** [comment]
Also it's not recommended to enable the Extras in your `lazy.lua` file any more. You should enable them via `:LazyExtras` command, because that way some Extras have to be loaded before/after others and have different priorities and `LazyExtras` takes care of that. Whereas if you import them in `lazy.lua` file, then the user is responsible from any conflicts that might occur due to bad priorities of Extras.

**Comment by Wakotu** [comment]
> I just tried this and can't reproduce. I tried a default LazyVim installation from scratch with the buggy lazy spec that you mention and I see no problems when opening Neovim. The error comes from your `/lua/config/keymaps.lua` file. What do you have on line 19 in that file?

line 19 was the first  `nomap` invocation line below.

```lua
local nomap = vim.keymap.del

nomap({ "i", "s" }, "<Tab>")
nomap({ "i", "s" }, "<S-Tab>")
```

**Comment by Wakotu** [comment]
> Also it's not recommended to enable the Extras in your `lazy.lua` file any more. You should enable them via `:LazyExtras` command, because that way some Extras have to be loaded before/after others and have different priorities and `LazyExtras` takes care of that. Whereas if you import them in `lazy.lua` file, then the user is responsible for any conflicts that might occur due to bad priorities of Extras.

thanks for tips.

**Comment by dpetka2001** [comment]
There's no mapping of `<Tab>/<S-Tab>`, that's why you get the error. `<Tab>/<S-Tab>` only get defined in `keys` for LuaSnip and nvim-cmp. So, you should also disable them from `keys` as described in the [docs](https://www.lazyvim.org/configuration/plugins#%EF%B8%8F-adding--disabling-plugin-keymaps).

**Comment by svonjoi** [comment]
> There's no mapping of `<Tab>/<S-Tab>`, that's why you get the error. `<Tab>/<S-Tab>` only get defined in `keys` for nvim-cmp. So, you should also disable them from `keys` as described in the [docs](https://www.lazyvim.org/configuration/plugins#%EF%B8%8F-adding--disabling-plugin-keymaps).

in my case problem has gone after removing this
```
vim.keymap.del("n", "<C-w>q")
```

**Comment by dpetka2001** [comment]
There was no such mapping in LazyVim to begin with, that's why you got the error. When you do `vim.keymap.del` for some key that doesn't exist in first place, then you get the error you mentioned in your OP post `vim/keymap.lua:0: E31: No such mapping`.

**Comment by svonjoi** [comment]
yeah that is, and after update the error start appearing at start

**Comment by dpetka2001** [comment]
So, this is not a bug but a wrong configuration issue from your end.

**Comment by svonjoi** [comment]
+1
