### ISSUE TITLE
bug: suggested usage of vim.fs.find for conform can be slow

### ISSUE THREAD

**Issue by noahbald** [LazyVim/LazyVim#4622]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

14.7

### Describe the bug

I found when running conform it would consistently take more than 1 or 2 seconds to run, and the cause was the usage of `vim.fs.find` in the formatter condition.
I've updated the body of the condition from what's recommended in the docs to the following.

```lua
-- before
condition = function(ctx)
  return vim.fs.find({ "biome.json" }, { path = ctx.filename, upwards = true })[1]
end

--after
condition = function(ctx)
  return vim.fs.find({ "biome.json" }, { path = ctx.filename, upwards = true, stop = vim.uv.cwd(), type = "file" })[1]
end
```

The `stop` parameters seems to be the big win here, my guess is that having a large dump of files in `~` may cause some slowdown, though this may not be appropriate for configs where you'd want to search in home.

### Steps To Reproduce

1. Enable conform in lazyvim
2. Enable format on save
3. Try saving a formattable file (e.g JavaScript) with `:w`

### Expected Behavior

The command `:w` should take a fraction of a section, even when running a formatter.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

local M = {
	has_biome_config = function(ctx)
		return vim.fs.find(
			{ "biome.json", "biome.jsonc" },
			{ path = ctx.filename, upwards = true }
			-- { path = ctx.filename, upwards = true, stop = vim.uv.cwd(), type = "file" }
		)[1]
	end,
}
M.has_biome_config = LazyVim.memoize(M.has_biome_config)

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    {
		"stevearc/conform.nvim",
		optional = true,
		opts = {
			formatters = {
				biome = {
					condition = M.has_biome_config,
				},
			},
			formatters_by_ft = {
				["javascript"] = { { "biome", "prettierd", "prettier" } },
				["javascriptreact"] = { { "biome", "prettierd", "prettier" } },
				["typescript"] = { { "biome", "prettierd", "prettier" } },
				["typescriptreact"] = { { "biome", "prettierd", "prettier" } },
				["vue"] = { { "biome", "prettierd", "prettier" } },
				["css"] = { { "prettierd", "prettier" } },
				["scss"] = { { "prettierd", "prettier" } },
				["less"] = { { "prettierd", "prettier" } },
				["html"] = { { "prettierd", "prettier" } },
				["json"] = { { "biome", "prettierd", "prettier" } },
				["jsonc"] = { { "biome", "prettierd", "prettier" } },
				["yaml"] = { { "prettierd", "prettier" } },
				["markdown"] = { { "prettierd", "prettier" } },
				["markdown.mdx"] = { { "prettierd", "prettier" } },
				["graphql"] = { { "prettierd", "prettier" } },
				["handlebars"] = { { "prettierd", "prettier" } },
			},
		},
	}
  },
})
```

**Comment by dpetka2001** [comment]
That depends on what users have in their home directory. Also this is just a suggestion to show an example, not active code in the codebase. Users adjust it to their needs. You can't seriously call this a bug. 

Just a fellow user like you.

**Comment by noahbald** [comment]
Sorry if I marked with the wrong label, yes this is really just a suggestion, hopefully to help others as reference in the future!

It can also be an issue if editing a file in node_modules for similar reasons, so there’s other cases worth considering too.
