### ISSUE TITLE
feature: remap which-key bindings

### ISSUE THREAD

**Issue by girishji** [LazyVim/LazyVim#467]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

How do you remap keys already defined for which-key (esp. those in the group). I was able to define new bindings, but even with 
'lazy = false' enabled, which-key bindings revert back.

### Describe the solution you'd like

a simple example will suffice

### Describe alternatives you've considered

na

**Comment by folke** [comment]
What do you mean?
Can you be explicit? Give an example?

**Comment by girishji** [comment]
I was able to do it. I just wanted to remap <leader>q to :quit and <leader>w to :write.

**Comment by girishji** [comment]
You can close this.
