### ISSUE TITLE
bug: Unable to input 'e' to edit the target file in lazygit within lazyvim.

### ISSUE THREAD

**Issue by Daydreamer-riri** [LazyVim/LazyVim#4675]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.2 Build type: Release LuaJIT 2.1.1713484068 Run "nvim -V1 -v" for more info

### Operating system/version

Windows 11

### Describe the bug

![Image](https://github.com/user-attachments/assets/2c1ab9e5-b0e7-458d-b036-989a7b3610a1)

### Steps To Reproduce

1. Enter <leader>gg 
2. Select a file 
3. Press 'e'

### Expected Behavior

Can directly open the target file.

**Comment by dpetka2001** [comment]
Duplicate of #4364

**Comment by Daydreamer-riri** [comment]
Sorry, I couldn't find this issue. I'm still unsure about what I can do. My lazygit config keeps getting overwritten. Where should I make changes? Thank you in advance for your response!

**Comment by Daydreamer-riri** [comment]
Sorry, I couldn't find this issue. I will follow the lazygit issues. Thanks for your reply!

**Comment by Daydreamer-riri** [comment]
After adding custom.yml and setting the editPreset, the result is as follows:

**Comment by dpetka2001** [comment]
No that's what the `nvim` preset does. It opens the file inside the lazygit instance instead of the parent nvim process. `nvim-remote` doesn't work on Windows and that's a lazygit bug. They have to fix it on their end.
