### ISSUE TITLE
bug: rust_analyzer conflicts with rustacean

### ISSUE THREAD

**Issue by blurskye** [LazyVim/LazyVim#4685]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

2.1.1727870382

### Operating system/version

arch linux

### Describe the bug

enabling lang.rust in lazy extras causes 2 instances of rust-analyzer be running at the same time, you get same diagnostics and inlay hints 2 times

```
lspconfig: require("lspconfig.health").check()

LSP configs active in this session (globally) ~
- Configured servers: ts_ls, rust_analyzer, taplo, tailwindcss, jsonls, lua_ls, typescript-tools
- OK Deprecated servers: (none)

LSP configs active in this buffer (bufnr: 15) ~
- Language client log: ~/.local/state/nvim/lsp.log
- Detected filetype: `rust`
- 3 client(s) attached to this buffer
- Client: `rust-analyzer` (id: 1, bufnr: [15])
  root directory:    ~/projectscx/rust/rust-test/lang-test/
  filetypes:         rust
  cmd:               ~/projectscx/rust/rust-analyzer --log-file /tmp/nvim.desync/YF5KU1/2-rust-analyzer.log
  version:           `rust-analyzer 0.3.2162-standalone`
  executable:        true
  autostart:         false
- Client: `copilot` (id: 2, bufnr: [15])
  root directory:    ~/projectscx/rust/
  filetypes:         
  cmd:               ~/projectscx/rust/node /home/desync/.local/share/nvim/lazy/copilot.lua/copilot/index.js
  version:           `v22.9.0`
  executable:        true
  autostart:         false
- Client: `rust_analyzer` (id: 3, bufnr: [15])
  root directory:    ~/projectscx/rust/rust-test/lang-test/
  filetypes:         rust
  cmd:               ~/.local/share/nvim/mason/bin/rust-analyzer
  version:           `rust-analyzer 0.3.2162-standalone`
  executable:        true
  autostart:         true
- Other clients that match the "rust" filetype:
- Config: tailwindcss
  filetypes:         html, css, php, blade, twig, vue, heex, astro, eruby, templ, svelte, elixir, eelixir, htmldjango, javascript, typescript, javascriptreact, typescriptreact, rust
  cmd:               ~/.local/share/nvim/mason/bin/tailwindcss-language-server --stdio
  version:           `?` (Failed to get version) Tried:
  `/home/desync/.local/share/nvim/mason/bin/tailwindcss-language-server --version`
  `/home/desync/.local/share/nvim/mason/bin/tailwindcss-language-server -version`
  `/home/desync/.local/share/nvim/mason/bin/tailwindcss-language-server version`
  `/home/desync/.local/share/nvim/mason/bin/tailwindcss-language-server --help`
  
  executable:        true
  autostart:         true
  root directory:    ~/projectscx/rust/Not found.

Docs for active configs: ~
- rust_analyzer docs: >markdown
  
  https://github.com/rust-lang/rust-analyzer
  
  rust-analyzer (aka rls 2.0), a language server for Rust
  
  
  See [docs](https://github.com/rust-lang/rust-analyzer/blob/master/docs/user/generated_config.adoc) for extra settings. The settings can be used like this:
  ```lua
  require'lspconfig'.rust_analyzer.setup{
    settings = {
      ['rust-analyzer'] = {
        diagnostics = {
          enable = false;
        }
      }
    }
  }
  ```
  
  Note: do not set `init_options` for this LS config, it will be automatically populated by the contents of settings["rust-analyzer"] per
  https://github.com/rust-lang/rust-analyzer/blob/eb5da56d839ae0a9e9f50774fa3eb78eb0964550/docs/dev/lsp-extensions.md?plain=1#L26.
      
  
  tailwindcss docs: >markdown
  
  https://github.com/tailwindlabs/tailwindcss-intellisense
  
  Tailwind CSS Language Server can be installed via npm:
  ```sh
  npm install -g @tailwindcss/language-server
  ```
  
  
```

### Steps To Reproduce

enable lang.rust from lazyExtras and have rust-analyzer install from mason(if not installed, it wont work either)

### Expected Behavior

it would disable loading of lsp from mason? not sure how it works

**Comment by dpetka2001** [comment]
You have this `cmd:  ~/.local/share/nvim/mason/bin/rust-analyzer` in your logs. So, you also have `rust-analyzer` installed via Mason. LazyVim does not do that. You installed it yourself somewhere in your personal configuration.

So, it's not a LazyVim bug.

**Comment by folke** [comment]
@dpetka2001 this has come up a couple of times.

Maybe we should add the below to the rust extra?

```lua
  {
    "neovim/nvim-lspconfig",
    opts = {
      servers = {
        rust_analyzer = { enabled = false },
```

**Comment by dpetka2001** [comment]
This can still be changed in user's config, no? Maybe you mean
```lua
setup = {
  rust_analyzer = function()
    return true
  end,
}
```
like you did with Typescript language server in the Typescript Extra?

**Comment by folke** [comment]
`enabled = false` should be enough in this case.
It will prevent loading rust_analyzer if it was installed by the user

**Comment by blurskye** [comment]
@dpetka2001 yes i get that, however it wont really work unless you have it installed from mason
you need rust-analyzer in path somehow, i doubt people will manually put it to path any other way, can mason's lsp spawing for rust not be disabled when rust.lang enabled?

**Comment by blurskye** [comment]
oh right, i see resolved with disabling that ig

**Comment by folke** [comment]
@blurskye you can't use mason's rust_analyzer since that won't work properly in all cases.

So you **do** need to have it installed locally to work with rustacean.

**Comment by dpetka2001** [comment]
@blurskye The correct way regarding `rustaceanvim` would be to install `rust-analyzer` via your Rust toolchain. That will also add it to your path. I've seen other similar problems where other users had installed rust-analyzer via their Linux distro package manager and that has also led to similar problems in the past.
