### ISSUE TITLE
bug: Inconsistent `nvim-treesitter` Initialization Behavior

### ISSUE THREAD

**Issue by ChasingZenith** [LazyVim/LazyVim#4687]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.2

### Operating system/version

ArchLinux

### Describe the bug

Hello,

I've noticed an inconsistency in the time/Event when `nvim-treesitter` initializes when opening `.tex` files.

- When I simply open Neovim and then open a .tex file (e.g., by typing :edit main.tex), the nvim-treesitter plugin initializes with the VeryLazy event.
- However, if I directly open a .tex file from the command line (e.g., nvim main.tex), the nvim-treesitter plugin initializes with the Start event.

### Steps To Reproduce

1. Prepare a minimal tex file `main.tex` like 
```latex
\documentclass{article}
\begin{document}
text $\alpha $ 
\end{document}
```
2. Install LazyVim and run `:TSInstall latex`
3. try The first way `nvim` then `:e main.tex` and `:Lazy` (I saw `VeryLazy` for `nvim-treesitter`), and the second way run `nvim main.tex` see `:Lazy` (I saw `nvim-treesitter` start at `Start` and vimtex give warning `Syntax highlighting is controlled by Treesitter!`)
4. If enable extra `lang.tex` , then the second way can't will raise a warning from vimtex

### Expected Behavior

If I do it in the second way the vimtex warning show up, the conceal for the latex symbol don't show up. What I notice is that `nvim-treesitter` plugin do not initialize consistently. Maybe that is not the reason. I hope consistent behavior for concealing, regardless of how I open the file.

### Repro

vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
-- not sure how to produce it with `nvim -u repro.lua` I just paste the config here
  {
    "lervag/vimtex",
    lazy = true, -- lazy-loading will disable inverse search
    ft={"tex"},
    config = function()
      vim.g.vimtex_mappings_disable = { ["n"] = { "K" } } -- disable `K` as it conflicts with LSP hover
      vim.g.vimtex_quickfix_method = vim.fn.executable("pplatex") == 1 and "pplatex" or "latexlog"
    end,
    keys = {
      { "<localLeader>l", "", desc = "+vimtex" },
    },
    dependencies = {
      {
        "nvim-treesitter/nvim-treesitter",
        opts = {
          ensure_installed = { "latex", "bibtex" },
          highlight = {
            enable = true,
            disable = { "latex" },
            additional_vim_regex_highlighting = { "latex" }
          },
        },
      },
    },
  },

  -- Correctly setup lspconfig for LaTeX 🚀
  {
    "neovim/nvim-lspconfig",
    optional = true,
    opts = {
      servers = {
        texlab = {
          keys = {
            { "<Leader>K", "<plug>(vimtex-doc-package)", desc = "Vimtex Docs", silent = true },
          },
        },
      },
    },
  },

  },
})

**Comment by dpetka2001** [comment]
This is because of https://github.com/LazyVim/LazyVim/blob/29dab35619bf6a3aafe7d71904fb31452bdd23a7/lua/lazyvim/util/plugin.lua#L88-L91

If we change in the if clause from `lang` to `lang ~= latex`, it seems to work. It seems that starting treesitter with `vim.treesitter.start` doesn't take into consideration the `highlights.disable` table. 

Not sure what the correct solution should be. Maintainer will know best.

**Comment by ChasingZenith** [comment]
Thanks @dpetka2001 . Can confirm changing `lang` to `lang = 'latex'` let me get expected behavior. It seems that the key to this issue is `syntax` being not configured. 

Since `vimtex` need `syntax`, and [`vim.treesitter.start()`](http://neovim.io/doc/user/treesitter.html#vim.treesitter.start()) disable syntax. Another workaround is to add the following to configuration file `lua/plugins/autocmds.lua`

```lua
vim.api.nvim_create_autocmd("FileType", {
  pattern = { "tex", "plaintex" },
  callback = function(event)
    vim.bo[event.buf].syntax = 'tex'
  end,
})
```
