### ISSUE TITLE
bug: Indent blankline gives error after update.

### ISSUE THREAD

**Issue by bhaumik-tripathi** [LazyVim/LazyVim#4688]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.11.0-dev-838+g66197dde7

### Operating system/version

Fedora 40

### Describe the bug

After a recent update, `indent-blankline` plugin is giving the following error when opening a file.
```lua
   Error  12:41:19 PM notify.error lazy.nvim Failed to run `config` for indent-blankline.nvim

.../share/nvim/lazy/indent-blankline.nvim/lua/ibl/utils.lua:22: char: expected table: 0x7f52d08ebe08, got string (│)

# stacktrace:
  - vim/shared.lua:0 _in_ **validate**
  - /indent-blankline.nvim/lua/ibl/utils.lua:22 _in_ **validate**
  - /indent-blankline.nvim/lua/ibl/utils.lua:34 _in_ **validate_config**
  - /indent-blankline.nvim/lua/ibl/config.lua:131 _in_ **validate_config**
  - /indent-blankline.nvim/lua/ibl/config.lua:275 _in_ **set_config**
  - /indent-blankline.nvim/lua/ibl/init.lua:57 _in_ **setup**
  - /chezmoi.nvim/lua/chezmoi/commands/__edit.lua:136 _in_ **execute**
  - /chezmoi.nvim/lua/chezmoi/commands/init.lua:34 _in_ **edit**
  - /chezmoi.nvim/lua/telescope/_extensions/find_files.lua:40 _in_ **run_replace_or_original**
  - /telescope.nvim/lua/telescope/actions/mt.lua:65 _in_ **key_func**
  - /telescope.nvim/lua/telescope/mappings.lua:293
```

I am not sure if the plugin is hindered by `chezmoi.nvim` or `telescope.nvim`.  I have not configured these plugins myself, directly installed from `LazyExtras` but the `stacktrace`  is pointing something in them.

Checking the docs for the indent plugin said that both `char` and `tab_char`  takes string values yet I am not sure why it is expecting a table. Changing the config to include the table character instead in the following way, I get an even bizarre error message.
```lua
{
    "lukas-reineke/indent-blankline.nvim",
    main = "ibl",
    ---@module "ibl"
    ---@type ibl.config
    opts = {
      indent = {
        char = { "│" },
        tab_char = { "│" },
      },
    },
  }
```
Error:
```lua
   Error  12:58:18 PM notify.error lazy.nvim Failed to run `config` for indent-blankline.nvim

.../share/nvim/lazy/indent-blankline.nvim/lua/ibl/utils.lua:22: tab_char: expected table: 0x7f88c3f6fc40, got table (table: 0x7f88c4221e50)

# (Same stacktrace as in above error.)
```

I have tried the above and also removed and reinstalled everything after removing `.local/share/nvim/lazy` without any success.
Please ask for any other information required, any help would be appreciated.

### Steps To Reproduce

1. Open any file and noice should give this error message.

### Expected Behavior

No error should occur as non of these plugins are configured by me directly.

### Repro

vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
    { import = "lazyvim.plugins.extras.util.chezmoi" },
    { import = "lazyvim.plugins.extras.editor.telescope" },
    { import = "plugins" },
  },
})

**Comment by dpetka2001** [comment]
You're using an old Neovim nightly from 26 September. Update to latest nightly. If you want to keep using nightly, then you should update every day because breaking changes might happen, otherwise stick with Neovim stable.
