### ISSUE TITLE
bug: tab added after copilot suggestions using blink.nvim

### ISSUE THREAD

**Issue by EricDriussi** [LazyVim/LazyVim#4692]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.2

### Operating system/version

Linux

### Describe the bug

With the repro config, when accepting copilot suggestions a tab gets added at the end of the text.

Not sure if it's the correct solution, but if I modify the keymap like so (note the `return cmp.hide()`):

```lua
{
	"saghen/blink.cmp",
	opts = {
		keymap = {
			["<Tab>"] = {
				function(cmp)
					if cmp.is_in_snippet() then
						return cmp.accept()
					elseif require("copilot.suggestion").is_visible() then
						LazyVim.create_undo()
						require("copilot.suggestion").accept()
						return cmp.hide()
					else
						return cmp.select_and_accept()
					end
				end,
				"snippet_forward",
				"fallback",
			},
		},
	},
},
```

The tab is *usually* not added. I'm guessing something needs to be returned here to prevent the fallback behavior from triggering.

### Steps To Reproduce

1. Start nvim with the repro config
2. Tab to accept a copilot suggestion (not a snippet)

### Expected Behavior

I would expect no tabs to be added if accepting a copilot suggestion.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
	spec = {
		{ "LazyVim/LazyVim", import = "lazyvim.plugins" },

		{ import = "lazyvim.plugins.extras.coding.blink" },
		{ import = "lazyvim.plugins.extras.coding.copilot" },
	},
})
```

**Comment by dpetka2001** [comment]
LazyVim uses `preset = "enter"` for `blink.cmp`. This preset doesn't create any mapping for `<Tab>`. So, it's normal that it appends a tab indeed. You would have to create the mapping in your personal configuration if you want to use `<Tab>` key to accept suggestions.

**Comment by dpetka2001** [comment]
Oh I missed the part about copilot and only looked the blink Extra, not the copilot Extra. I was wrong.
