### ISSUE TITLE
bug: using copilot (or another type of lsp on top of null-ls/lspconfig) can override custom binds for a certain language

### ISSUE THREAD

**Issue by amaanq** [LazyVim/LazyVim#47]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0-dev-588+g99cf11128

### Operating system/version

Arch Linux 6.1.4-zen2-1

### Describe the bug

cc: @appelgriebsch since I practically use his extras/lang/rust config

If I rebind a key like "K" (hover) to RustHoverActions, copilot calls the regular lsp_attach function and as a result any overridden keymaps like "K" are reset to their original one. Debugged by putting a few vim.notifys, namely in the rust setup [here](https://github.com/appelgriebsch/Nv/blob/ebb333e2bc67853df78a1aed98472fcca246a03c/lua/plugins/extras/lang/rust.lua#L30) ("rust config loaded"), right before the keymap "Hover" is set [here](https://github.com/amaanq/LazyVim/blob/f0ab044a3fad2daf295ba63ddc55f2c943063a55/lua/lazyvim/plugins/lsp/keymaps.lua#L19) ("keymaps on_attach reached"), and inside the base lsp-config on_attach function [here](https://github.com/LazyVim/LazyVim/blob/f0ab044a3fad2daf295ba63ddc55f2c943063a55/lua/lazyvim/plugins/lsp/init.lua#L55) ("client.name = x").

Result is the screenshot below, clearly copilot is the culprit always loading last and resetting the binds. A fix could be to check for the client name inside the on_attach function before setting keymaps, but I'd like a better fix that is in my own config that extends upon LazyVim, so as to not intrude on LazyVim itself with ugly conditional checks :sweat_smile: 

![image](https://user-images.githubusercontent.com/29718261/211911279-6737b83b-d410-4133-bf60-bd9cd632b9a3.png)

### Steps To Reproduce

1. Use copilot
2. Use an extra lang config that extends on a LazyVim config that overrides a default lsp keybind
3. Default lsp keybind is set when it should be the overridden one

### Expected Behavior

Overridden keybind should be set

### Repro

Using appelgriebsch/Nv with copilot added should trigger it

**Comment by appelgriebsch** [comment]
The sequence of the plugin initialization may matter for setting up the proper keymap behaviour.... AFAIK. So maybe would be good to check if GH-copilot is configured before rust-tools.

**Comment by amaanq** [comment]
Even after separating copilot.lua into extras/lang/copilot.lua and loading that before all the other lang plugins, and having it be loaded right away, it still loads after every language in lsp_onattach

**Comment by folke** [comment]
@amaanq you need to load it **AFTER** the default plugins. That's what I was saying. If you load it **before**, then lspconfig will overwrite those mappings.

**Comment by amaanq** [comment]
Really sorry about that..thank you!
