### ISSUE TITLE
bug: Terminal statusline flashing when typing

### ISSUE THREAD

**Issue by dotfrag** [LazyVim/LazyVim#4724]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

Linux

### Describe the bug

Statusline flashing when typing in terminal. This seems related to lualine, as it doesn't happen with plain nvim config.

https://streamable.com/2le4c0

### Steps To Reproduce

1. Open nvim (I'm using LazyVim starter for example)
2. `:lua Snacks.terminal()`
3. Start typing

### Expected Behavior

Either no flashing, or no statusline at all.

### Repro

LazyVim starter.

**Comment by folke** [comment]
Please open snacks issues in the snacks repo.
I also can't reproduce this...

**Comment by dotfrag** [comment]
I already did by [mistake](https://github.com/folke/snacks.nvim/issues/22), but are you sure? I tried using snacks repro and it's not reproducible there.

**Comment by dotfrag** [comment]
I solved it with 

```lua
    {
      "nvim-lualine/lualine.nvim",
      opts = {
        options = {
          disabled_filetypes = { "snacks_terminal" },
        },
      },
    },
```

**Comment by dpetka2001** [comment]
I can confirm it also happens to me after the latest changes that I pulled. Doesn't happen with snacks minimal repro which doesn't have Lualine, but it happens both on my local forked repo and a default LazyVim installation after I add `version = false`, so that it upgrades to latest HEAD.

**Comment by folke** [comment]
Good find and clearly a lualine issue then.
Probably also happens with just `:terminal`?

**Comment by dotfrag** [comment]
Doesn't happen with `:terminal` for me.

**Comment by dpetka2001** [comment]
No @folke it doesn't happen with `:terminal`. Only `Snacks.terminal` is affected in my environment.

**Comment by folke** [comment]
@dpetka2001 this is a repro:

```lua
vim.cmd("botright 20 split")
vim.cmd.terminal()
vim.keymap.set("t", "<esc><esc>", "<C-\\><C-n>")
vim.opt_local.winbar = "title: %{b:term_title}" -- this causes the flickering
vim.cmd.startinsert()
```
Would be great if someone could report to lualine...

**Comment by dpetka2001** [comment]
Was just about to create the issue with your minimal repro. But you did it faster 😛
