### ISSUE TITLE
bug:

### ISSUE THREAD

**Issue by danjessen** [LazyVim/LazyVim#4727]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.11.0-dev-4072+g2377443cd-Homebrew

### Operating system/version

macOS 15.1

### Describe the bug

Enabled the new blink extra. I'm experiencing issues when interacting with Friendly snippets. Normal suggestions / copilot suggestions work fine. But when selecting a friendly snippet the syntax for the file gets changed. Setting it manually afterwards, restores / fixes the bug.

https://github.com/user-attachments/assets/4b988652-1a35-4e5d-a0e3-3d28031c14f8

I'm running smarty a template language written in PHP. I'm not using treesitter highlighting. Just vim / regex based. Since this works the best for this language in my experience.

### Steps To Reproduce

1. Enable blink
2. Enable friendly snippets
3. Write code that triggers snippet
4. Syntax gets changed

### Expected Behavior

Syntax should stay at existing syntax. 

### Repro

vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})

**Comment by folke** [comment]
Please report this upstream instead. Not a LazyVim issue

**Comment by danjessen** [comment]
Sorry for the inconvenience. It was produced in the blink repo and a fix should be rolling out.
