### ISSUE TITLE
bug: Floating terminal is now static at bottom!

### ISSUE THREAD

**Issue by sentakuhm** [LazyVim/LazyVim#4740]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

Arch linux

### Describe the bug

after updating lazyvim, `ctrl+/` supposed to opned flaot terminal, but the terminal showed at the bottom.

![Image](https://github.com/user-attachments/assets/1585a2e8-9c80-45b1-bc47-686b4655227a)

### Steps To Reproduce

1. deleted lazyvim and all settings from `~/config/nvim` also removed nvim folders from `.cache` and `.local/share/nvim`
2. reinstall lazyvim following docs
3. open neovim
4. press `ctrl+/` to open floating-term
5. terminal is static at bottom of neovim

### Expected Behavior

opening floating term as usual.

### Repro

```lua

```

**Comment by dpetka2001** [comment]
This is not a bug. That's how Snacks opens terminals. If you want to change that behavior you can put in your Snacks config the following
```lua
  {
    "folke/snacks.nvim",
    -- dev = true,
    opts = {
       terminal = {
         win = {
           position = "float",
         },
       },
    },
  },
```
Or just call the directly the command `:lua Snacks.terminal(nil, { win = {position = "float"}})`.

**Comment by sentakuhm** [comment]
Thank you @dpetka2001

**Comment by Simbaclaws** [comment]
what keybind is currently used in lazyvim to close the floating terminal at the bottom? 

I would like to quickly be able to close/open it... I already found that doing: ```tnoremap <Esc> <C-\><C-n>``` allows you to go out of terminal mode with escape key. 

But I would like a way to instantly close the floating snack terminal. Does anyone know? Pressing ctrl + / again opens a new one to the right for me... When focussed on the terminal. 

It would also be cool to have a hide mode, so you can keep the terminal session in the background but hide the snack while you are working. I don't really know if that exists in snacks. I'm quite new to lazyvim and neovim in general.

ctrl + / does seem to close it when it's not the active window... But I hate pressing escape. Going to my other window with space + bb and then pressing ctrl + / to close it. Feels unintuative.

**Comment by dpetka2001** [comment]
@Simbaclaws #6774 is an attempt to fix the behavior you observe. We just have to wait until maintainer is back some time at end of February or early March, so that it can be merged. 

You can try the linked PR locally and see if it works for you.

**Comment by Simbaclaws** [comment]
what's the difference between hide underscore and hide slash in this case? Are they both bind to the same functionality, or does one of the two close vs hide? Thank you for linking the pr. I'll wait for the maintainer to merge it before using it. Thank you for your contribution.

**Comment by dpetka2001** [comment]
This depends on the terminal itself. Some terminals interpret the key sequence as `<C-/>` while others interpret it as `<C-_>`. So, we just map both, so that the behavior remains consistent regardless of how terminals interpret the key sequence.

In Neovim go into `insert` mode and then press `<C-v><C-/>` and you will see some printed characters. That's how your terminal will interpret the key sequence.

PS: For example on Windows and using Wezterm, the key sequence is interpreted as `<C-_>`, but on Linux with Kitty terminal it's interpreted as `<C-/>`.

**Comment by Simbaclaws** [comment]
ah that makes sense. And I suppose the default is hide and show the terminal, so that your sessions stay inside of it, like for example if you were to use tmux you would keep your session and not close the terminal? I can't wait to use this, it seems super useful.
