### ISSUE TITLE
bug: Zig integration broken

### ISSUE THREAD

**Issue by alosarjos** [LazyVim/LazyVim#4746]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

Arch Linux

### Describe the bug

On a clean installation, after installing the new Zig extra, as soon as I start witting it shows error messages

Here is a video too in case that helps:

https://github.com/user-attachments/assets/d3c45716-f5b4-4be2-aee6-1733097af163

### Steps To Reproduce

1. Install LazyVIm
2. Install Zig extra
3. Open a .zig file (main.zig for example)
4. Start typing

### Expected Behavior

Should not show error messages

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
Seems like snippets in zig lsp dont work. Not a LazyVim issues. Feel free to open a PR and/or report upstream

**Comment by alosarjos** [comment]
> Seems like snippets in zig lsp dont work. Not a LazyVim issues. Feel free to open a PR and/or report upstream

Upstream would be on the ZLS repository (The Zig LSP?)

**Comment by folke** [comment]
i have no idea. I don't do zig.
You could also try commenting on the PR that created the zig extra

**Comment by alosarjos** [comment]
For now I just disabled it for zig.

```lua
return {
  { "garymjr/nvim-snippets", opts = { friendly_snippets = true } },
}
```

**Comment by Eveeifyeve** [comment]
> For people stumbling across this; it's a bug in `friendly-snippets`, there's [a PR](https://github.com/rafamadriz/friendly-snippets/pull/504) dating back to 2024-10-08 over at their repo that would fix this.
> 
> For anyone not willing to wait until the fix upstream is implemented; you can work your way around [as I describe here](https://ziggit.dev/t/did-i-mess-up-my-lazyvim-config/6325/6?u=fobersteiner). Note though that this will make the attempt to update the plugin fail - which I'd consider OK since it seems to be inactive at the moment. The other option would be to disable snippets completely.

Fixed in https://github.com/rafamadriz/friendly-snippets/pull/531
