### ISSUE TITLE
bug: Visual issues when importing with blink.nvim

### ISSUE THREAD

**Issue by Redoxahmii** [LazyVim/LazyVim#4747]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.2

### Operating system/version

Arch Linux

### Describe the bug

After the latest update when using `blink.nvim` cmp i can't read anymore properly and it shows it as ghost text instead of showing it inside the cmp dialog that opens.
Is there some way to disable this because when using AI completion plugins that also provide ghost text completions it overlaps instead of working properly.
The image below should provide a better representation of the issue.

![Image](https://github.com/user-attachments/assets/592c5915-bae4-4a60-b919-f54795f99dd6)

The ghost text shows properly when not using any completion plugin in similar method but the default behavior should remain as it was before as it is more similar to how people are more comfortable with.

### Steps To Reproduce

1. Open a buffer and import something when using a AI completion ghost text configuration.

### Expected Behavior

Should not display over each other.
Preferred would be without the ghost text but instead use a proper dialog as it is something we are getting from LSPs so the differentiation should remain.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by Redoxahmii** [comment]
Thank you for the information.
I was also not sure if this issue is related to LazyVim or `blink.cmp` but before this update the dialog being displayed for the cmp entries the paths displayed in the dialog where not that faint.
I can barely read it in that menu anymore so i assumed that part was related to LazyVim.
Even after disabling the ghost text the dialog with cmp entries showing where we are importing from is actually not even showing the faint paths which i am a bit confused about whether that part was coming from blink or LazyVim.
If this is a `blink.cmp` issue then i will close this.
Thank you again.

**Comment by folke** [comment]
The way the blink completion menu looks, will change soon, but I'm waiting for a new blink release before I can update LazyVim.
Blink has a binary component, so its config / code version and bin version need to match.

On main, the `draw` function/table has been changed.
