### ISSUE TITLE
bug: CMP mapping lacks a description

### ISSUE THREAD

**Issue by IamSmeagol** [LazyVim/LazyVim#4755]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.1

### Operating system/version

WSL Ubuntu 22.04

### Describe the bug

When searching for cmp keybinds they lack a description and just say `cmp.util.keymap.set_map` which is very unclear. 

All cmp keybinds with this issue
![Image](https://github.com/user-attachments/assets/a636f542-4328-4ae1-9261-595e716e3cbf)

### Steps To Reproduce

1. Open telescope keybind search `<leader>sk`
2. Search for a cmp default binding such as `<C-space>` -- list [here ](https://www.lazyvim.org/plugins/coding)
3. The result tells the user that cmp is being called in some way, but leaves the user to search and find what it actually does in the lazyvim docs
![Image](https://github.com/user-attachments/assets/e1839dc8-a0e1-4b84-9db3-c37a6c245bbe)

### Expected Behavior

I would expect there to be a description like all the other plugin commands.  -- for example 
Compare to the result for `<Space>sk` which states "Key maps" (this is still a bit unclear in this menu, but in the which key - after `<Space>s` it is assumed that it's a search for keymaps)
![Image](https://github.com/user-attachments/assets/17ae2d35-4438-4439-9b99-502925ca5e69)

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
Those mappings are created using `nvim-cmp` functions and those functions are responsible for the description provided. Nothing to do with LazyVim.

**Comment by IamSmeagol** [comment]
> Those mappings are created using `nvim-cmp` functions and those functions are responsible for the description provided. Nothing to do with LazyVim.

Are we not able to manually set a description like the other keybinds?

**Comment by dpetka2001** [comment]
Not by using the helper `cmp.mapping` functions as far as i can tell. I found an old issue at `nvim-cmp` repo and it seems that you can use the `cmp.*` API directly with `vim.keymap.set`, but it doesn't take care of the fallback call, you'd have to define it yourself. I don't know if something has changed in the codebase since then (issue i found was from March 2024), so this is a question better asked at `nvim-cmp` repo itself.
