### ISSUE TITLE
bug: snacks keep spawn LazyVim `LazyVim.ui.statuscolumn` is deprecated error

### ISSUE THREAD

**Issue by fm39hz** [LazyVim/LazyVim#4756]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.2

### Operating system/version

Arch Linux 6.6.59-1-lts

### Describe the bug

![Image](https://github.com/user-attachments/assets/a1d97100-edd9-4ae9-9c9f-33dce0cceb0c)
after updating to the newest LazyVim, it keeps spawning this error, even though I'm not setting anything related to statuscolumn

### Steps To Reproduce

1. clone my config `https://github.com/fm39hz/nvim-lazyvim.git`
2. open any folder that's not neovim config

### Expected Behavior

snacks do not spawn the error message

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
This is only possible if you have that set in your `options.lua`

**Comment by iuga** [comment]
I'm experiencing the same issue as [fm39hz](https://github.com/fm39hz). Could you kindly provide more details on how you resolved this problem?
In my case, I've ensured that I'm not using `LazyVim.ui.statuscolumn` in my `options.lua` file, but the issue persists.

**Comment by folke** [comment]
@iuga that is totally unrelated to this issue...

**Comment by N3bukadne7ar** [comment]
I am experiencing the exact same issue, seemingly after some plugin updates. (No config changes from my side). Why was this closed?

**Comment by kobzar** [comment]
The same.
Just remove 
```lua
if vim.fn.has("nvim-0.9.0") == 1 then
  vim.opt.statuscolumn = [[%!v:lua.require'lazyvim.util'.ui.statuscolumn()]]
end
```
And errors gone. But maybe i am need to add something extend this?
