### ISSUE TITLE
bug: extras/vscode not working

### ISSUE THREAD

**Issue by LonJonn** [LazyVim/LazyVim#4757]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

MacOS 15.1

### Describe the bug

Since the latest update that added Snack.nvim, the VSCode extra stopped working as the latest changes around Snack.nvim do not consider VSCode, leading to nil references that break the config.

Here's a very quick and hacky workaround I've got "working" by editing the lazyvim source.
I just followed the errors in my vscode terminal and added conditionals to stop them from running in vscode env, so I'm sure there more places that need adjusting.

```diff
diff --git a/lua/lazyvim/config/keymaps.lua b/lua/lazyvim/config/keymaps.lua
index c4160be..26c361a 100644
--- a/lua/lazyvim/config/keymaps.lua
+++ b/lua/lazyvim/config/keymaps.lua
@@ -117,6 +117,7 @@ map("n", "[w", diagnostic_goto(false, "WARN"), { desc = "Prev Warning" })
 -- stylua: ignore start
 
 -- toggle options
+if not vim.g.vscode then
 LazyVim.format.snacks_toggle():map("<leader>uf")
 LazyVim.format.snacks_toggle(true):map("<leader>uF")
 Snacks.toggle.option("spell", { name = "Spelling"}):map("<leader>us")
@@ -130,6 +131,7 @@ Snacks.toggle.option("background", { off = "light", on = "dark" , name = "Dark B
 if vim.lsp.inlay_hint then
   Snacks.toggle.inlay_hints():map("<leader>uh")
 end
+end
 
 -- lazygit
 if vim.fn.executable("lazygit") == 1 then
@@ -153,10 +155,14 @@ map("n", "<leader>uI", "<cmd>InspectTree<cr>", { desc = "Inspect Tree" })
 map("n", "<leader>L", function() LazyVim.news.changelog() end, { desc = "LazyVim Changelog" })
 
 -- floating terminal
+if not vim.g.vscode then
 map("n", "<leader>fT", function() Snacks.terminal() end, { desc = "Terminal (cwd)" })
 map("n", "<leader>ft", function() Snacks.terminal(nil, { cwd = LazyVim.root() }) end, { desc = "Terminal (Root Dir)" })
 map("n", "<c-/>",      function() Snacks.terminal(nil, { cwd = LazyVim.root() }) end, { desc = "Terminal (Root Dir)" })
 map("n", "<c-_>",      function() Snacks.terminal(nil, { cwd = LazyVim.root() }) end, { desc = "which_key_ignore" })
+else
+  map("n", "<c-/>", function () require("vscode-neovim").action("workbench.action.terminal.toggleTerminal") end)
+end
 
 -- Terminal Mappings
 map("t", "<C-/>", "<cmd>close<cr>", { desc = "Hide Terminal" })
diff --git a/lua/lazyvim/util/mini.lua b/lua/lazyvim/util/mini.lua
index 28d38f5..feac7e7 100644
--- a/lua/lazyvim/util/mini.lua
+++ b/lua/lazyvim/util/mini.lua
@@ -121,15 +121,17 @@ end
 
 ---@param opts {skip_next: string, skip_ts: string[], skip_unbalanced: boolean, markdown: boolean}
 function M.pairs(opts)
+  if not vim.g.vscode then
   Snacks.toggle({
     name = "Mini Pairs",
     get = function()
       return not vim.g.minipairs_disable
     end,
     set = function(state)
       vim.g.minipairs_disable = not state
     end,
   }):map("<leader>up")
+  end
 
   local pairs = require("mini.pairs")
   pairs.setup(opts)
diff --git a/lua/lazyvim/util/ui.lua b/lua/lazyvim/util/ui.lua
index 14d0850..b6acc65 100644
--- a/lua/lazyvim/util/ui.lua
+++ b/lua/lazyvim/util/ui.lua
@@ -86,6 +86,10 @@ function M.foldexpr()
 end
 
 function M.maximize()
+  if vim.g.vscode then
+    return { map = function() end }
+  end
+
   ---@type {k:string, v:any}[]?
   local maximized = nil
   return Snacks.toggle({
```

I would create a PR but my lua skills are very basic and I'm sure I would cause more damage than good, but hopefully the diff can help a bit.

### Steps To Reproduce

1. Enable vscode under extras in LazyExtras with LazyVim 13
2. Open VSCode

### Expected Behavior

Snack.nvim and any other incompatible plugins that would break VSCode should be disabled / remapped

### Repro

```lua

```

**Comment by eightfiftytwo** [comment]
I'm still encountering this problem. Is it possible to reopen this issue?
I have done a clean reinstall and I can confirm [06071dd](https://github.com/LazyVim/LazyVim/commit/06071dd452baf1e9b8b5aab140553c4f51fa522e) has been applied.

```
Failed loading lazyvim.config.keymaps

...are/nvim.d/lazy/lazy/LazyVim/lua/lazyvim/util/format.lua:182: attempt to index global 'Snacks' (a nil value)

# stacktrace:

  - /LazyVim/lua/lazyvim/util/format.lua:182 _in_ **snacks_toggle**

  - /LazyVim/lua/lazyvim/config/keymaps.lua:120

  - /LazyVim/lua/lazyvim/config/init.lua:251

  - /LazyVim/lua/lazyvim/config/init.lua:250 _in_ **_load**

  - /LazyVim/lua/lazyvim/config/init.lua:258 _in_ **load**

  - /LazyVim/lua/lazyvim/config/init.lua:184
```

**Comment by folke** [comment]
How do you trigger this?

**Comment by eightfiftytwo** [comment]
Thank you for your quick response!

1. Clean install the starter template (and run sync in lazy.nvim)
3. Open with VSCode Neovim
4. ![Image](https://github.com/user-attachments/assets/52f9b4da-a067-4dbb-a741-1a374d64b762)

**Comment by oracleyue** [comment]
> I'm still encountering this problem. Is it possible to reopen this issue? I have done a clean reinstall and I can confirm [06071dd](https://github.com/LazyVim/LazyVim/commit/06071dd452baf1e9b8b5aab140553c4f51fa522e) has been applied.
> 
> ```
> Failed loading lazyvim.config.keymaps
> 
> ...are/nvim.d/lazy/lazy/LazyVim/lua/lazyvim/util/format.lua:182: attempt to index global 'Snacks' (a nil value)
> 
> # stacktrace:
> 
>   - /LazyVim/lua/lazyvim/util/format.lua:182 _in_ **snacks_toggle**
> 
>   - /LazyVim/lua/lazyvim/config/keymaps.lua:120
> 
>   - /LazyVim/lua/lazyvim/config/init.lua:251
> 
>   - /LazyVim/lua/lazyvim/config/init.lua:250 _in_ **_load**
> 
>   - /LazyVim/lua/lazyvim/config/init.lua:258 _in_ **load**
> 
>   - /LazyVim/lua/lazyvim/config/init.lua:184
> ```

 hi, I am new to LazyVim and got stuck at get stacktrace of loading error. May I know where/how do you get the complete stacktrace logs? (I tried `:mess`, `Noice all` not getting what I saw). Thanks a lot for your help!!

**Comment by eightfiftytwo** [comment]
I just copy and pasted it from the VSCode window shown in the screenshot above. You can get there by opening the bottom panel with Ctrl+` to open the terminal, and clicking over to the Output tab.

**Comment by oracleyue** [comment]
> I just copy and pasted it from the VSCode window shown in the screenshot above. You can get there by opening the bottom panel with Ctrl+` to open the terminal, and clicking over to the Output tab.

Ohh, it's from vscode. Got it, thanks a lot, really appreciate your help!

**Comment by oracleyue** [comment]
> I just copy and pasted it from the VSCode window shown in the screenshot above. You can get there by opening the bottom panel with Ctrl+` to open the terminal, and clicking over to the Output tab.

Ohh, it's from vscode. Got it, thanks a lot, really appreciate your help!

**Comment by folke** [comment]
I really can't reproduce this.

It all works as expected for me after my fix.

Can you make sure all your plugins are fully updated in regular Neovim before starting vscode?

If the problem persists, can you open your `init.lua`, add `vim.g.vscode = 1` at the top, and then open NEovim as normal and get me the errors you see?

**Comment by eightfiftytwo** [comment]
After making a new VSCode profile and combing through configs, I discovered the problem was a misconfiguration on my part. Sorry to have wasted your time, I'll try that first next time.

**Comment by mnowotnik** [comment]
If anybody is still encountering this: open Neovim and run update in Lazy.

**Comment by eightfiftytwo** [comment]
In my case, I moved the config folder and forgot to change `$NVIM_APPNAME`

**Comment by dgokcin** [comment]
@folke 

I added `vim.g.vscode` at the top of my `init.lua` and here is the error I have

```
E5108: Error executing lua [string "v:lua"]:1: module 'snacks.statuscolumn' not found:
        no field package.preload['snacks.statuscolumn']
cache_loader: module snacks.statuscolumn not found
cache_loader_lib: module snacks.statuscolumn not found
        no file './snacks/statuscolumn.lua'
        no file '/opt/homebrew/share/luajit-2.1/snacks/statuscolumn.lua'
        no file '/usr/local/share/lua/5.1/snacks/statuscolumn.lua'
        no file '/usr/local/share/lua/5.1/snacks/statuscolumn/init.lua'
        no file '/opt/homebrew/share/lua/5.1/snacks/statuscolumn.lua'
        no file '/opt/homebrew/share/lua/5.1/snacks/statuscolumn/init.lua'
        no file './snacks/statuscolumn.so'
        no file '/usr/local/lib/lua/5.1/snacks/statuscolumn.so'
        no file '/opt/homebrew/lib/lua/5.1/snacks/statuscolumn.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './snacks.so'
        no file '/usr/local/lib/lua/5.1/snacks.so'
        no file '/opt/homebrew/lib/lua/5.1/snacks.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        [string "v:lua"]:1: in main chunk
```

**Comment by dgokcin** [comment]
may be happening because of snacks, found an issue that seems more related.

https://github.com/LazyVim/LazyVim/issues/4756

**Comment by folke** [comment]
That's just not possible if you're using the proper way of loading LazyVim.
That error can only happen if you manually load your `options.lua` or don't properly import lazyvim plugins, or in the wrong order.

**Comment by folke** [comment]
Or even simpler, did you disable snacks?

**Comment by folke** [comment]
@dgokcin you are not even using the vscode extra!!

You have a copy of an old version of the extra https://github.com/dgokcin/dotfiles/blob/main/nvim/lua/plugins/vscode.lua

That of course won't work...

Would've helped a lot if you could have told me that. Sigh

**Comment by folke** [comment]
> I am having this issue after doing a clean install @mnowotnik update did not work for me. any idea what may be happening?

That is **NOT** a clean install...

**Comment by dgokcin** [comment]
> [@dgokcin](https://github.com/dgokcin) you are not even using the vscode extra!!
> 
> You have a copy of an old version of the extra https://github.com/dgokcin/dotfiles/blob/main/nvim/lua/plugins/vscode.lua
> 
> That of course won't work...
> 
> Would've helped a lot if you could have told me that. Sigh

I created that file from a previous version of `vscode.lua` to have more control over the custom keymappings that work only on VsCode. Naturally, the fix you did 3 weeks ago did not get reflected to my local config. Sorry for your frustration, was just trying to add more functionality.

Where do you think I should put the VsCode specific keybindings that does not exist in vscode extra to avoid further issues and follow lazyvim best practices?

**Comment by dgokcin** [comment]
> You can just add them to your regular `keymaps.lua`:
> 
> if vim.g.vscode then
>   -- add your mappings here
> end
> You also no longer need to enable the vscode extra, nor do you need to include what you have. That is all done automatically.
> 
> Feel free to create a PR to add some of those keymaps to the vscode extra, since I guess they are relevant for all users.

will do later this week, thanks!
