### ISSUE TITLE
bug: cannot use <c-j> <c-k> keys inside lazygit window after update to v13.2.0

### ISSUE THREAD

**Issue by batusai513** [LazyVim/LazyVim#4760]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.2

### Operating system/version

MacOS 14.6.1 (23G93)

### Describe the bug

Cannot use <c-k> <c-j> combo keys, or any other keys that clash with the current neovim, to move commits in the commit history inside the Lazygit window after updating to LazyVim 13.2.0

### Steps To Reproduce

1. Open lazyvim in a folder with a repository
2. Open LazyGit
3. Go to the Commit - Reflog panel
4. Try moving commits using <c-j> or <c-k> combo keys
5. the focus is moved to the currently opened code buffer

### Expected Behavior

when using <c-j> or <c-k> combo keys (or any other keys that clash with the current opened neovim) it should allow to move commits

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
Cannot reproduce with default LazyVim installation from scratch. Following screencast

https://github.com/user-attachments/assets/0b534ba1-c7f6-4f6d-b0e8-04382dedbbc9

**Comment by batusai513** [comment]
@dpetka2001 you are right, I had a very old autocommand that was adding some keybindings on termopen event but for some reason it was not causing this issue before, just after the lazyvim update to the version 13.

Thanks for your help.
