### ISSUE TITLE
bug: Massive numberwidth after opening file from telescope

### ISSUE THREAD

**Issue by barrelltech** [LazyVim/LazyVim#4762]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.2

### Operating system/version

macOS 15.1

### Describe the bug

When opening a file from telescope, previously open panes' gutter/number column/numberwidth value gets set to the padding value of the telescope window. (so if the telescope panel takes up 80% of the screen width, the numberwidth value gets set to 10% of the screen width).

![Image](https://github.com/user-attachments/assets/d8c4643d-97b1-45d6-b12b-93cfcb8740e8)

_Please note that in this image, I corrected the pane on the left, testing to make sure `set numberwidth=4` resolved the issue still. When the bug occurs, all panes except for the newly opened pane (in this case the center right was the newest pane) receive the updated numberwidth value_

This is on a fresh lazy vim installation, only customization is the clojure `LazyExtra` and the `kanagawa.nvim` theme installed. It does not happen every time I use Telescope, but happens ~10% of the time (about a dozen times in the 24 hours I've had lazyvim installed).

`:windo set numberwidth=4` resolves the issue (until opening another file breaks it again).

### Steps To Reproduce

1. install fresh lazyvim
2. install clojure extra
3. use telescope to navigate a project, opening vsplits with `<C-v>`. I've noticed no pattern so far when it happens

### Expected Behavior

`numberwidth` should not be set to telescopes padding value

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
Can you reproduce it without the clojure Extra? If not, then maybe one of the plugins that come with the Extra is causing this. I was neither able to reproduce it with the Clojure Extra nor without it. 

I tried pressing one time `<c-v>` to split vertically and then in the second vertical window I opened a few files with `<c-x>` to open them horizontally, in order to achieve the layout in your screenshot

**Comment by barrelltech** [comment]
It's a fairly intermittent issue. I'll program for hours and it won't happen, then it will happen several times in a row ¯\_(ツ)_/¯. 

All I use neovim for is clojure, so I would have to disable all language related files and work for a while until maybe it happens and maybe it doesn't. So it's unlikely I'll try to reproduce it without Clojure extras 😅 For me it's a better solution just to create a keymap to reset the numberwidths. 

I just wanted to report it so you guys know it's an issue on vanilla installs, and include the solution in case other people have the issue and want to know how to fix it since I couldn't find it in my searches. :)

**Comment by barrelltech** [comment]
FWIW I've used neovim with telescope and all of the clojure extras for many years and never seen this happen, so it's not a conflict just between the extra libraries. 

Only trying out lazyvim because I've heard so much about it!

**Comment by folke** [comment]
None of snacks.nvim, telescope.nvim or LazyVim ever change `numberwidth`, so there must be something else in your config doing that.
