### ISSUE TITLE
bug: cannot escape from terminal

### ISSUE THREAD

**Issue by piertoni** [LazyVim/LazyVim#4767]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.1 (wsl Linux),  0.10.2 (Windows)

### Operating system/version

Windows/Linux

### Describe the bug

On the latest version updated this morning both on a Windows machine and on a Linux machine I cannot escape from terminal window.

- ESC + ESC does not work to exit insert mode on the terminal.
- ctrl-w {h, j, k, l }, to move to different panels.

Thanks!

### Steps To Reproduce

`:terminal` and try to ESC+ESC or move around

### Expected Behavior

restore normal functionality

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
LazyVim no longer sets any terminal mappings. Only when starting a terminal from Snacks.terminal, which is what LazyVim uses under the hood.

**Comment by piertoni** [comment]
What I understand is that: if you launch the terminal from telescope with `<leader>fT`  or other variations you have working keybindings (like ESC + ESC to escape).
If you launch it instead with `:terminal` this is, I guess, managed directly by neovim and does not works with terminal keybindings.
At first I did not understood your answer (was too technical for me as I don't know much of lazyvim internals) and I was used to create a terminal with `:terminal`. But there is no problem to use `<leader>fT` it is even quicker.
Thanks
