### ISSUE TITLE
feature: Support FreeBSD

### ISSUE THREAD

**Issue by lakako** [LazyVim/LazyVim#4772]
### Did you check the docs?

- [x] I have read all the LazyVim docs
- [x] This is not a request for a new or existing extra (see above)

### Is your feature request related to a problem? Please describe.

install failed on freebsd

![Image](https://github.com/user-attachments/assets/51fed74e-4417-460f-b607-741e5630bb92)

### Describe the solution you'd like

Install lazyvim on freebsd successfully.

### Describe alternatives you've considered

On Linux, `make` and `gmake` refers to gnu make. On *BSD, make refer to `pmake`, `gmake` refer to gnu make. telescope's Makefile use gnu make syntax. 
Use gmake or cmake on platform other than Linux.

**Comment by folke** [comment]
You can just override the build command in your own config
