### ISSUE TITLE
bug: Windows auto session saving in nvim config directory or path with dash by LazyVim has stopped working

### ISSUE THREAD

**Issue by AddictArts** [LazyVim/LazyVim#4784]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

Windows 11

### Describe the bug

LazyVim 13.2.0 latest sessions are not created in <data>/sessions. This worked recently and then stopped working on Windows.

### Steps To Reproduce

1. CD to AppData\Local\nvim or in my case AppData\lazy-nvim
2. Open Neovim with LazyVim latest on Windows
3. Open some files
4. <leader>qq
5. Missing seesion file in <data>/sessions
### Expected Behavior

A session file created. I suspect from the error it is the "-" in the path somehow leaking through?
Error:

```
Error detected while processing VimLeavePre Autocommands for "*":
Error executing lua callback: vim/_editor.lua:431: VimLeavePre Autocommands for "*"..script nvim_exec2() called at VimLeavePre Autocommands for "*":0: Vim(mksession):E190: Cannot open "C:\Users\me\AppData\Local\lazy-nvim-data\sessions\C%Users%me%AppData%Local%lazy-nvim%%^[[31;1mSet-PSReadLineOption% ^[[0mC%Users%me%OneDrive%Documents%PowerShell%Microsoft.PowerShell_profile.ps1%164^[[0m
.vim" for writing
stack traceback:
        [C]: in function 'nvim_exec2'
        vim/_editor.lua:431: in function 'cmd'
        ...nvim-data/lazy/persistence.nvim/lua/persistence/init.lua:70: in function 'save'
        ...nvim-data/lazy/persistence.nvim/lua/persistence/init.lua:58: in function <...nvim-data/lazy/persistence.nvim/lua/persistence/init.lua:43>
```

I tried CMD.exe to see if that mattered

```
Error detected while processing VimLeavePre Autocommands for "*":
Error executing lua callback: vim/_editor.lua:431: VimLeavePre Autocommands for "*"..script nvim_exec2() called at VimLeavePre Autocommands for "*":0: Vim(mksession):E190: Cannot open "C:\Users\me\AppData\Local\lazy-nvim-data\sessions\C%Users%me%AppData%Local%lazy-nvim%%Microsoft Windows [Version 10.0.22631.4169]
.vim" for writing
stack traceback:
        [C]: in function 'nvim_exec2'
        vim/_editor.lua:431: in function 'cmd'
        ...nvim-data/lazy/persistence.nvim/lua/persistence/init.lua:70: in function 'save'
        ...nvim-data/lazy/persistence.nvim/lua/persistence/init.lua:58: in function <...nvim-data/lazy/persistence.nvim/lua/persistence/init.lua:43>
```

**Comment by folke** [comment]
Those session paths have weird shell output, so it seems your `vim.o.shell` is wrongly configured.
I'll update persistence to show an error in this case, but either way, this is a problem in your config.

**Comment by folke** [comment]
It seems that persistence is already checking errors for `git branch`.
Your `vim.o.shell` seems to not even return exit codes > 0.
