### ISSUE TITLE
bug: <Tab> no longer moves to next item in snippet

### ISSUE THREAD

**Issue by stefanlogue** [LazyVim/LazyVim#4787]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.1

### Operating system/version

macOS 15.0.1

### Describe the bug

When using a snippet (conventional commit message, for example), I used to be able to press <Tab> and it would take me from the first "input" to the next one. It now inserts a tab instead.

### Steps To Reproduce

1. Invoke any snippet with more than one "input" section
2. complete the first input
3. press <Tab>

### Expected Behavior

Expected the cursor to move to the next input.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    { import = "lazyvim.plugins.extras.coding.luasnip" },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
Is this with nvim-cmp or blink?
Using native snippets or luasnip or something else?
For blink / luasnip, are you using the extras?
Did you enable any AI completion source? Manually or through extras?

**Comment by stefanlogue** [comment]
1. nvim-cmp
2/3. luasnip extra, I've updated the repro to reflect this
4. I've got copilot as a completion source, configured manually, but the issue is AFTER the snippet has been already chosen, and I've edited the first "input"

**Comment by folke** [comment]
What does `:verbose imap <tab>` and `:verbose smap <tab>` say?

**Comment by stefanlogue** [comment]
```shell
13:06:57 msg_show   verbose imap <tab> No mapping found
13:07:07 msg_show   verbose smap <tab> s  <Tab>       * <Lua 114: ~/.local/share/nvim/lazy/LazyVim/lua/lazyvim/plugins/extras/coding/luasnip.lua:54>
	Last set from Lua (run Nvim with -V1 for more details)

```

**Comment by stefanlogue** [comment]
This is the completion menu:
![Image](https://github.com/user-attachments/assets/695d9c31-5442-479d-a0bb-986bd822f478)
This is after I select the item from the completion menu:
![Image](https://github.com/user-attachments/assets/098a5ff5-f7e3-4ec9-8398-3fb3eeebfae9)
This is what happens when I've pressed tab:
![Image](https://github.com/user-attachments/assets/d799fadd-6f80-418c-bc55-c1e878219fb0)

I would expect the cursor to move across to `title` instead

**Comment by dpetka2001** [comment]
Are you overwriting completely `nvim-cmp` in your personal configuration? `verbose imap <tab>` should show the keymap set by `nvim-cmp` for `<Tab>`. Also I could not reproduce this with default LazyVim installation with just Luasnip Extra enabled. Screencast following

https://github.com/user-attachments/assets/f2cf9b97-645b-4de6-a465-b5a02b4c510e

**Comment by stefanlogue** [comment]
Yes I'm overwriting `nvim-cmp` as I don't use `<tab>` to select from the completion menu:
```lua
function()
      vim.api.nvim_set_hl(0, "CmpGhostText", { link = "Comment", default = true })
      local cmp = require("cmp")
      local defaults = require("cmp.config.default")()
      return {
        preselect = cmp.PreselectMode.None,
        completion = {
          completeopt = "menu,menuone,noinsert",
        },
        snippet = {
          expand = function(args)
            require("luasnip").lsp_expand(args.body)
          end,
        },
        mapping = cmp.mapping.preset.insert({
          ["<C-n>"] = cmp.mapping.select_next_item({ behavior = cmp.SelectBehavior.Select }),
          ["<C-p>"] = cmp.mapping.select_prev_item({ behavior = cmp.SelectBehavior.Select }),
          ["<C-b>"] = cmp.mapping.scroll_docs(-4),
          ["<C-f>"] = cmp.mapping.scroll_docs(4),
          ["<C-Space>"] = cmp.mapping.complete(),
          ["<C-e>"] = cmp.mapping.abort(),
          ["<C-Enter>"] = cmp.mapping.confirm({ select = false }), -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
          ["<C-Y>"] = cmp.mapping.confirm({
            behavior = cmp.ConfirmBehavior.Replace,
            select = true,
          }), -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
        }),
        window = {
          completion = cmp.config.window.bordered(),
          documentation = cmp.config.window.bordered(),
        },
        sources = cmp.config.sources({
          { name = "nvim_lsp" },
          { name = "copilot" },
          { name = "luasnip" },
          { name = "path" },
          { name = "emoji" },
          { name = "buffer" },
        }),
        formatting = {
          format = function(_, item)
            local icons = require("lazyvim.config").icons.kinds
            if icons[item.kind] then
              item.kind = icons[item.kind] .. item.kind
            end
            return item
          end,
        },
        -- experimental = {
        --   ghost_text = {
        --     hl_group = "CmpGhostText",
        --   },
        -- },
        sorting = defaults.sorting,
      }
    end
```

I have not changed this configuration in while, and this behaviour has only been happening the last week or so

**Comment by folke** [comment]
You're missing this cmp mapping:

```lua
          ["<tab>"] = function(fallback)
            return LazyVim.cmp.map({ "snippet_forward", "ai_accept" }, fallback)()
          end,
```

**Comment by dpetka2001** [comment]
Why are you overwriting completely the `nvim-cmp` configuration. If you had just extended the default with your custom changes you wouldn't be having this problem.

**Comment by stefanlogue** [comment]
Was this a recent addition? Strange that it worked fine until recently.

I'm just going to extend the default instead to avoid these issues in future.

Am I able to remove the `ai_accept` part if I have copilot as a source in cmp already? I typically accept it the same way I would any other cmp source
