### ISSUE TITLE
bug: Parser not available for language "luap"

### ISSUE THREAD

**Issue by xushuhui** [LazyVim/LazyVim#479]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.1

### Operating system/version

Mac os 12.4

### Describe the bug

Nvim show error
`Installation not possible: ...vim/lazy/nvim-treesitter/lua/nvim-treesitter/install.lua:75: Parser not available for language "luap"

Installation not possible: ...vim/lazy/nvim-treesitter/lua/nvim-treesitter/install.lua:75: Parser not available for language "luadoc"
`

### Steps To Reproduce

1. install lazyvim 
2. Start Neovim

### Expected Behavior

No show error notify and No show so many notify 

<img width="963" alt="image" src="https://user-images.githubusercontent.com/13704743/227099140-73c1a4cc-6220-45f4-a668-1cbd36970b96.png">

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Update nvim-treesitter?
