### ISSUE TITLE
bug: blink.cmp always enabled after commit a7eca05

### ISSUE THREAD

**Issue by bruno-ortiz** [LazyVim/LazyVim#4795]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.2

### Operating system/version

MacOS 15.1

### Describe the bug

After I updated LazyVim tonight a message started poping up.

`Error while downloading blink.cmp pre-built binary: Can't download from github due to not being on a git tag but found no built version of the library. Either run cargo build --release via your package manager or switch to a git tag. See the README for more info.`

Looking at the loaded plugins I see that blink.cmp is being loaded even though I never enabled it in LazyExtras.

### Steps To Reproduce

1. Open nvim after updating to LazyVim 13.3.0.
2. See the error happening;
3. See that blink.cmp was enabled with copilot.lua

### Expected Behavior

Dont automatically load blink.cmp with copilot.lua when blink.cmp is not enabled in LazyExtras.

### Repro

**Comment by aofei** [comment]
https://github.com/LazyVim/LazyVim/blob/ad3e2b635401fbc575cdbefea73ade477320da2f/lua/lazyvim/plugins/extras/ai/copilot.lua#L61-L68

https://github.com/LazyVim/LazyVim/blob/ad3e2b635401fbc575cdbefea73ade477320da2f/lua/lazyvim/config/options.lua#L14-L16

It seems like this is caused by `vim.g.ai_cmp` being defaulted to `true`. So setting it to `false` might help.

**Comment by Eminem-x** [comment]
> [LazyVim/lua/lazyvim/plugins/extras/ai/copilot.lua](https://github.com/LazyVim/LazyVim/blob/ad3e2b635401fbc575cdbefea73ade477320da2f/lua/lazyvim/plugins/extras/ai/copilot.lua#L61-L68)
> 
> Lines 61 to 68 in [ad3e2b6](/LazyVim/LazyVim/commit/ad3e2b635401fbc575cdbefea73ade477320da2f)
> 
>  -- copilot cmp source 
>  { 
>    "nvim-cmp", 
>    optional = true, 
>    dependencies = { -- this will only be evaluated if nvim-cmp is enabled 
>      { 
>        "zbirenbaum/copilot-cmp", 
>        enabled = vim.g.ai_cmp, -- only enable if wanted 
> [LazyVim/lua/lazyvim/config/options.lua](https://github.com/LazyVim/LazyVim/blob/ad3e2b635401fbc575cdbefea73ade477320da2f/lua/lazyvim/config/options.lua#L14-L16)
> 
> Lines 14 to 16 in [ad3e2b6](/LazyVim/LazyVim/commit/ad3e2b635401fbc575cdbefea73ade477320da2f)
> 
>  -- if the completion engine supports the AI source, 
>  -- use that instead of inline suggestions 
>  vim.g.ai_cmp = true 
> It seems like this is caused by `vim.g.ai_cmp` being defaulted to `true`. So setting it to `false` might help.

If setting it to `false`, ai_cmp seems to disbale. how to use Codeium and Copliot?

**Comment by aofei** [comment]
> If setting it to `false`, ai_cmp seems to disbale. how to use Codeium and Copliot?

https://github.com/LazyVim/LazyVim/blob/ad3e2b635401fbc575cdbefea73ade477320da2f/lua/lazyvim/plugins/extras/ai/copilot.lua#L3-L11

https://github.com/LazyVim/LazyVim/blob/ad3e2b635401fbc575cdbefea73ade477320da2f/lua/lazyvim/plugins/extras/ai/codeium.lua#L3-L11

I think they should still work as "expected"?
