### ISSUE TITLE
bug: extras/biome not showing

### ISSUE THREAD

**Issue by nopears** [LazyVim/LazyVim#4810]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

MacOS 15.1

### Describe the bug

I saw biome exists in "extras" dir in repo, updated LazyVim but it's not showing in :LazyExtras

### Steps To Reproduce

1. Updated LazyVim to 13.3.1

### Expected Behavior

To be able to install biome extra

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
It will be on next release when it's done. If you want to use it right now, you can follow HEAD as described in the [docs](https://www.lazyvim.org/configuration/lazy.nvim).

**Comment by nopears** [comment]
Thank You
