### ISSUE TITLE
bug:

### ISSUE THREAD

**Issue by chrisgeo** [LazyVim/LazyVim#4817]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

13.0.0 (started), no on 13.4

### Operating system/version

macOS 15.x

### Describe the bug

I upgraded, apparently late to this party, to v13 last week.

Despite going through the docs, I can’t find the replacement for: Notifications, Messages/messages. 

Noice* only shows _some_ messages. So I’m probably missing something in, I think, Snacks?

### Steps To Reproduce

1. Open command palette, search for option
2. Notification is missing, capital Messages is missing

### Expected Behavior

1. Notification/Message commands are not missing

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
`Notifications` was a command of `nvim-notify`. That is no longer installed as LazyVim uses `snacks.notifier` by default. 

`messages` is still there, I don't know what you're talking about. It's a default built-in Neovim command.

I personally have moved onto `:lua Snacks.notifier.show_history()` and replaced the Noice keymap for history.

**Comment by chrisgeo** [comment]
> `Notifications` was a command of `nvim-notify`. That is no longer installed as LazyVim uses `snacks.notifier` by default.
> 
> `messages` is still there, I don't know what you're talking about. It's a default built-in Neovim command.
> 
> I personally have moved onto `:lua Snacks.notifier.show_history()` and replaced the Noice keymap for history.

> messages` is still there, I don't know what you're talking about

Because  I didn't say, "messages".  I was working with **M**essasges. I knew _m_essages works just fine.
