### ISSUE TITLE
bug:

### ISSUE THREAD

**Issue by ajmasia** [LazyVim/LazyVim#4838]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1713484068

### Operating system/version

Ubuntu 24.02

### Describe the bug

After installing the extra language pack for typescript, I find that the autocomplete after vtsls is loaded and the file is parsed is very slow.

https://github.com/user-attachments/assets/858f1527-b991-4419-acdb-ba60ab9090a3

### Steps To Reproduce

1. install typescript extra lang
2. open a typescript project
3. test autocomplete

### Expected Behavior

Autocomplete should work normally

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins", opts = { colorscheme = "catppuccin-macchiato" } },
    -- add any other plugins here
    { import = "lazyvim.plugins.extras.lang.typescript" },
    -- import/override with your plugins
    { import = "plugins" },

  },
})
```

**Comment by folke** [comment]
Can't reproduce and either way, LazyVim is not responsible for LSP server implementations, nor completion engines...

**Comment by folke** [comment]
**Still** not a LazyVim issue, sorry.

**Comment by folke** [comment]
And next time, please do some effort to provide a proper title for your bug report

**Comment by jfoliveiraramos** [comment]
I'm having the same issue as @ajmasia
LazyVim typescript extra does not work correctly. It times out constantly for any LSP functionality.
Enabling vstsls manually on Mason effectively works, so it appears not to be an issue of LSP implementation or blink auto completion.
