### ISSUE TITLE
bug: the which key plugin randomly stops working

### ISSUE THREAD

**Issue by rkaminsk** [LazyVim/LazyVim#4841]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.2 (via snap)

### Operating system/version

Ubuntu 22.04.5 LTS

### Describe the bug

Sometimes the which-key plugin stops working. The window at the bottom of the screen no longer appears but I can still use `<Leader>`-based keymaps (if I type them fast enough). Currently, I restart nvim if this happens. Does anyone experience similar issues? A workaround that does not require restarting nvim would also be nice.

### Steps To Reproduce

Unfortunately, this randomly happens and I don't know how to reproduce.

### Expected Behavior

A popup with keys appears if I press `<Space>`.

**Comment by fang2hou** [comment]
I have also met this problem when I was a newcomer to neovim.
Maybe just because you are in macro recoding (`q<register_name>`, e.g. `qa`) 🤔

**Comment by rkaminsk** [comment]
> I have also met this problem when I was a newcomer to neovim. Maybe just because you are in macro recoding (`q<register_name>`, e.g. `qa`) 🤔

That might be it! It did not know that the which key popup is not shown in macro recording mode. I will pay attention next time it happens. Most likely this is not a bug because my fingers sometimes mess up and the `q` key might be involved to close something. Thanks.

**Comment by folke** [comment]
Ah yes right, which-key indeed is disabled during macros, otherwise it messes them up...

**Comment by rkaminsk** [comment]
It might be worth to mention this somewhere. At least for me this is quite a tripwire because I often accidentally hit the `<q>` key. But maybe search engines will pick up this issue. Anyway, thanks for the hint and for LazyVim of course.  It's great!
