### ISSUE TITLE
bug: fzf-lua file selection for quickfix list does not work with <tab>

### ISSUE THREAD

**Issue by b0lle** [LazyVim/LazyVim#4846]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

MacOS 15.1.1

### Describe the bug

Hey,

[fzf-lua](https://github.com/ibhagwan/fzf-lua) has the default behaviour to select files with `<tab>`, which can then be send to the quickfix list. However, within LazyVim, the tab key causes to toggle the .gitignore filter.
Since I did not find any documentation about this behaviour in the LazyVim documentation, nor any options in fzf-lua to configure the selection key, I guess this behaviour is not intended.

### Steps To Reproduce

1. Open fzf-lua with `<leader>fg`
2. press `<tab>`

### Expected Behavior

The file should be selected instead of toggling the gitignore filter.

### Repro

```lua

```

**Comment by dpetka2001** [comment]
Works as intended for me. I can select files with `<tab>`. What does `:verbose tmap <tab>` show? Can you try with a default LazyVim installation with only `fzf` Extra enabled? My guess is you have some conflicting keymap in your personal configuration or from some plugin that you installed.

**Comment by b0lle** [comment]
hm, unfortunately there is no other mapping on tab. 
`:verbose tmap <tab>` returns `no mapping found`.

Ok, if its works for you ... I am on a relatively clean setup, but will do what you supposed.
