### ISSUE TITLE
bug: System level keybindings not working inLazy.Vim since latest update

### ISSUE THREAD

**Issue by ZedMuir** [LazyVim/LazyVim#4847]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.2

### Operating system/version

MacOS 15.1.1

### Describe the bug

I have keybindings for <c-h>, <c-j>, <c-k> and <c-l> mapped to <LEFT>, <DOWN>, <UP> and <RIGHT> using Hammerspoon. They have always worked throughout the entire system, including within Lazy.Vim up until the latest update. Now, the ONLY place the keybindings do not work is when Lazy.Vim is open. The continue to work in all other iTerm activities, and other apps. 

I have tried vim.keymap.del as described on Lazy.Vim guide; I have tried various other methods but things went South very quickly so reverted back to current config. 

`:verbose map <c-j>` shows no mapping. 

On my other MBP running the same MacOS 15.1.1, the keybindings still function as expected. Only difference is that LazyVim has not yet been updated to version 13.5.2. 

### Steps To Reproduce

1. Open NVIM
2. Open a file
3. Enter insert mode
4. Press <c-j> (for example) to move down
5. Nothing happens

### Expected Behavior

1. Open NVIM
2. Open a file
3. Enter insert mode
4. Press <c-j> (for example) to move down
5. Cursor moves down 1 line each time <c-j> is pressed (same as pressing <DOWN> arrow on keyboard (YUCK!))

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
Your description does not mention which key you have mapped to what, so I can't really understand what you're trying to do.

**Comment by folke** [comment]
LazyVim does not hijack system keymaps, so not a LazyVim issue

**Comment by ZedMuir** [comment]
Apologies for missing that; I should have checked the preview before pressing `Submit`!!. The formatter removed all the keymaps that I typed out! 

So, `<c-h>` is mapped to `<LEFT>`, `<c-j>` is mapped to `<DOWN>`, `<c-k>` is mapped to `<UP>` and `<c-l>` is mapped to `<RIGHT>`. This is done via Hammerspoon and therefore should not have issues. 

The keymaps work throughout the entire system and always have done until the latest update to Lazy.Vim 13.5.2. It is a real crazy bug that is driving me crazy as I have tried loads of fixes, albeit rather blindly. I do not understand what is causing the keymaps to not work in Lazy.Vim like they always did but I know that something is. 

If anyone has any ideas as to what it may be, it would be hugely appreciated. 

Config files: [https://github.com/ZedMuir/nvim-config](nvim-config)

**Comment by ZedMuir** [comment]
Updated original request so should make a bit more sense now.

**Comment by dpetka2001** [comment]
The above works fine for me in Kitty terminal that I tested. Maybe it's a terminal issue. Try Wezterm or Kitty and see if that works. Then you'll know it's terminal related. Also I don't use Hammerspoon, but maybe it causes some kind of conflict.

**Comment by ZedMuir** [comment]
Updated to Lazy.Vim 13.5.2 on my other system with the same config and same MacOS etc and all works as expected. Must be some crazy-ness on the new system that definietly is not Lazy.Vim related. Absolutely insane when these random quirks ruin your day and steal hours. 

Thanks for the input and apologies for wasting your time. 

Take care all.

**Comment by ZedMuir** [comment]
Even crazier is that all works fine when using nvim in tmux! Just for info in case anyone ever comes across this.

**Comment by ZedMuir** [comment]
Final point: I have determined without a doubt that it's was due to an update in iTerm2.  Latest version(s) have caused issues with keybindings and in particular with Neovim.
