### ISSUE TITLE
bug:

### ISSUE THREAD

**Issue by ChrisGVE** [LazyVim/LazyVim#4855]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

MacOS 15.2

### Describe the bug

When using `Snacks.dashboard` in the two panes configuration, the right pane menu is misaligned:
![Image](https://github.com/user-attachments/assets/e6b131bb-af06-451c-a4b3-64c603c94cff)

### Steps To Reproduce

Configuration for the dashboard section is as follows:

```lua
    dashboard = {
      sections = {
        { section = "header" },
        { pane = 2, height = 5, padding = 1 },
        { icon = " ", title = "Keymaps", section = "keys", indent = 3, gap = 1, padding = 1 },
        { pane = 2, icon = " ", title = "Recent Files", section = "recent_files", indent = 3, padding = 1 },
        { pane = 2, icon = " ", title = "Projects", section = "projects", indent = 3, padding = 1 },
        {
          pane = 2,
          icon = " ",
          title = "Git Status",
          section = "terminal",
          enabled = function()
            local obj = vim.system({ "git", "rev-parse", "--is-inside-work-tree" }):wait()
            return obj.code == 0
          end,
          cmd = "hub status --short --branch --renames",
          height = 5,
          padding = 1,
          ttl = 5 * 60,
          indent = 3,
        },
        { section = "startup" },
      },
    },
    styles = {
      notification = {
        wo = { wrap = true }, -- Wrap notifications
      },
    },
```

### Expected Behavior

When taking the standard Snacks preset for the header, the problem is solved:
![Image](https://github.com/user-attachments/assets/bc621f41-3aec-497f-8d38-e1215cca4248)

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
It's not misaligned. It's just the header that's wider than the pane width. Of you want to use two panes, use another header

**Comment by dpetka2001** [comment]
Just curious but can the panes be customized for their width? Or is it always 50-50? If that is possible, maybe OP can give left pane bigger width and right one less width to adjust for his situation?

**Comment by dpetka2001** [comment]
Another thing you could do that I also tested is copy the specific header into a txt file and then use a `terminal` section with `cmd = "cat logo.txt"` and some tweaks to `width` to make it align as you want. You might also want to shrink a bit the logo in the txt file (i.e removing the leading whitespace and maybe the whitespace in the `z` characters). In my laptop the sweet spot was 60 cells wide, but it may vary depending on your screen width.

**Comment by ChrisGVE** [comment]
@dpetka2001 I agree with you that it would be sweet if we could have sections that span the whole screen (typically "header" and "startup", but we could make others) and others that are placed in a left and a right pane.
