### ISSUE TITLE
错误：za or zA Error

### ISSUE THREAD

**Issue by rileychc** [LazyVim/LazyVim#486]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.3

### Operating system/version

macOS 13.2.1

### Describe the bug

When I enter the za or zA command, I always prompt that I can't find the fold.
And I can't find the file that defines the shortcut key starting with z.

### Steps To Reproduce

Go to the name location of the function definition and enter the shortcut key za

### Expected Behavior

Realize code folding

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by rileychc** [comment]
<img width="1450" alt="image" src="https://user-images.githubusercontent.com/116857974/227459802-040a2d64-4afb-4d4e-a5b3-57457667088f.png">
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/116857974/227459880-866fa227-aa37-4cf8-9019-d7bda4bb9c55.png">

**Comment by rileychc** [comment]
I solved it.Please close

**Comment by rileychc** [comment]
Can you tell me which file za and zA are defined?

**Comment by folke** [comment]
za and zA are internal Neovim keymaps. LazyVim does not change or define those.
