### ISSUE TITLE
feature: presets/layers

### ISSUE THREAD

**Issue by DanielFGray** [LazyVim/LazyVim#4876]
### Did you check the docs?

- [x] I have read all the LazyVim docs
- [x] This is not a request for a new or existing extra (see above)

### Is your feature request related to a problem? Please describe.

migrating to lazyvim from my own custom init.lua i've built over time, I would like to selectively enable/disable groups of lazyvim plugins and opt-in to features, as opposed to disabling a long list of plugins individually, and unmapping things

the docs have groups of plugins like "coding" "formatting" "linting" "LSP" "ui" etc, and I would like to enable specific groups, eg LSP and coding, or maybe only the UI

### Describe the solution you'd like

a default "preset" might provide the same set of features and plugins as today, or instead of the whole preset users might selectively enable different "layers"

as a side effect, users could then create, share, and import their own layers/presets

### Describe alternatives you've considered

going back to my own custom init.lua and copy/pasting parts of lazyvim config into it

**Comment by folke** [comment]
LazyVim core is already pretty minimal, and I don't see the need to further split this up.
Like you said, you can easily disable plugins you don't need, or just don't use LazyVim.
