### ISSUE TITLE
feature: Add extra plugin for coc.nvim

### ISSUE THREAD

**Issue by Veha0001** [LazyVim/LazyVim#4880]
### Did you check the docs?

- [x] I have read all the LazyVim docs
- [x] This is not a request for a new or existing extra (see above)

### Is your feature request related to a problem? Please describe.

I'm always frustrated because  of https://github.com/termux/termux-app/issues/3855#issue-2152283405.

### Describe the solution you'd like

CoC.nvim should work right?

### Describe alternatives you've considered

Uh.. ok please add coc.nvim!! _-_

**Comment by folke** [comment]
See that second checkbox you checked 🤷‍♂️

**Comment by Veha0001** [comment]
Ohseee..
