### ISSUE TITLE
feature: persistent theme

### ISSUE THREAD

**Issue by vdegenne** [LazyVim/LazyVim#4884]
### Did you check the docs?

- [x] I have read all the LazyVim docs
- [x] This is not a request for a new or existing extra (see above)

### Is your feature request related to a problem? Please describe.

Can we have persistent theme?
Using `<leader>uC` we can select a color theme, however unfortunately the theme is just set to the current session.

### Describe the solution you'd like

It'd be great to have a telescope shortcut when using `<leader>uC` to persist the selected theme item.

### Describe alternatives you've considered

Ideally! a command similar to `:LazyExtras` but for themes! (`:LazyThemes`) will open a menu with all available theme and pressing `x` on one of theme will persist the theme in the cache data so new session will always choose this theme from.)

(Ideally #2, the new selected theme will also apply to all current open sessions, not just the current focus or new session)

**Comment by dpetka2001** [comment]
You can set a persistent colorscheme as described in the [docs](https://www.lazyvim.org/configuration#icons--colorscheme).

**Comment by dpetka2001** [comment]
I implemented a rather hackish way to do that in fzf-lua
```lua
vim.keymap.set("n", "<leader>uC", function()
  local fzf = require("fzf-lua")
  fzf.colorschemes({
    actions = {
      ["default"] = function(selected)
        local colorscheme = selected[1]
        vim.cmd.colorscheme(colorscheme)

        -- Update the config file directly
        local config_file = vim.fn.stdpath("config") .. "/lua/plugins/core.lua"
        local content = vim.fn.readfile(config_file)

        -- Find and replace the colorscheme line
        for i, line in ipairs(content) do
          if line:match("colorscheme%s*=") then
            content[i] = string.format('      opts.colorscheme = "%s"', colorscheme)
            break
          end
        end

        vim.fn.writefile(content, config_file)
      end,
    },
  })
end, { desc = "Colorscheme with preview" })
```
I'm sure the same thing can be done in Telescope in `attach_mappings` function, but not willing to dig into Telescope API right now to do that. 
`/lua/plugins/core.lua` is where I keep the Lazyvim plugin spec and I used `opts.colorscheme` because the LazyVim `opts` is a function in my case, otherwise you could just use plain `colorscheme` instead if it's just a table.

**Comment by folke** [comment]
Thank you for the suggestion, but this feels like something for a plugin or something to add to your config like @dpetka2001 wrote

**Comment by vdegenne** [comment]
@dpetka2001 Thanks I tried using the same logic as last time, but for some reasons `:enhance` won't work and I don't know why:

```lua
  {
    "<leader>uC",
    function()
      local action_set = require("telescope.actions.set")
      require("telescope.builtin")["colorscheme"]({
        enable_preview = true,
        attach_mappings = function()
          action_set.select:enhance({
            post = function()
              vim.notify("insert logic here") -- NOT CALLED
            end,
          })
          return true
        end,
      })
    end,
    desc = "Colorscheme with Preview",
  },
```
Maybe Telescope haven't implemented enhancement for this particular picker. Or I am doing something wrong and if you see the problem just by looking at this piece of code please let me know.

But I think I am going back to fzf.

**Comment by vdegenne** [comment]
Hey nevermind there is actually an auto command for when the theme changes:

```lua
vim.api.nvim_create_autocmd("ColorScheme", {
    callback = function()

        -- Saving to `core.lua`

    end,
})
```

I will pick the logic you kindly shared.

**Comment by dpetka2001** [comment]
```lua
vim.keymap.set("n", "<leader>uC", function()
  require("telescope.builtin").colorscheme({
    enable_preview = true,
    attach_mappings = function(prompt_bufnr, _)
      local actions = require("telescope.actions")
      actions.select_default:replace(function()
        local selection = require("telescope.actions.state").get_selected_entry()
        vim.print(selection)
        actions.close(prompt_bufnr)
        vim.cmd.colorscheme(selection.value)

        -- Update the config file directly
        local config_file = vim.fn.stdpath("config") .. "/lua/plugins/core.lua"
        local content = vim.fn.readfile(config_file)

        -- Find and replace the colorscheme line
        for i, line in ipairs(content) do
          if line:match("colorscheme%s*=") then
            content[i] = string.format('      colorscheme = "%s",', selection.value)
            break
          end
        end

        vim.fn.writefile(content, config_file)
      end)
      return true
    end,
  })
end, { desc = "Colorscheme with preview" })
```
The `enhance` method is for extending the default Telescope action. So, the default Telescope action will get executed and then your additional custom setting as well. I tried to make it work with `enhance` but couldn't (presumably because of [this](https://github.com/nvim-telescope/telescope.nvim/blob/85922dde3767e01d42a08e750a773effbffaea3e/lua/telescope/builtin/__internal.lua), which seems to override the default action with its own custom action for the colorscheme picker and that's why `enhance` also doesn't work because it extends the default action I'm guessing), so I decided to use `replace` method to replace the entire default action with what we want to do.

**Comment by vdegenne** [comment]
Awesome! You always help me to find reasons to stay in Telescope. 
There is just one little improvement I'd like to add, the theme should change in all open sessions (e.g. for when we change to dark mode).

`vim.cmd.colorscheme(selection.value)` should be removed from the above execution and we need to find a way to hook lazy.vim reloader system to call `vim.cmd.colorscheme(vim.g.colors_name)` when the config file changes from the `writeFile` above.
I know it's possible because when one of the config file changes a notification appears in all sessions (https://github.com/folke/lazy.nvim/blob/56ead98e05bb37a4ec28930a54d836d033cf00f2/lua/lazy/manage/reloader.lua#L95).
However I couldn't track down the source of what causes this notification to pop everywhere, there must be a simple autocmd somewhere.

**Comment by vdegenne** [comment]
@dpetka2001 When the script you provided changes the content of `./lua/plugins/core.lua` the change detected notification spread out in all open sessions, that is why I believe it should be relatively simple to implement cross session theme change.

@folke Can you please check my last comment and point me in the right direction? Thanks!

**Comment by folke** [comment]
Check the code? This is all out of scope for LazyVim/lazy.nvim, but you can of course check the code

**Comment by vdegenne** [comment]
@folke I'm asking you to give me a clue to at least where to look at, since I've already check the code and it wasn't evident.

**Comment by vdegenne** [comment]
Ok I found out, not sure if that's optimal but it works so for now that'll do:

```lua
vim.api.nvim_create_autocmd("User", {
  pattern = "LazyReload",
  callback = function()
    local core = require("plugins.core")
    local colorscheme = nil
    for _, plugin in ipairs(core) do
      if plugin[1] == "LazyVim/LazyVim" and plugin.opts then
        colorscheme = plugin.opts.colorscheme
        break
      end
    end
    if colorscheme then
      vim.cmd.colorscheme(colorscheme)
    end
  end,
})
```

**Comment by vdegenne** [comment]
This seems to work better:

```lua
vim.api.nvim_create_autocmd("User", {
  pattern = "LazyReload",
  callback = function()
    vim.schedule(function()
      local core = require("plugins.core")
      local colorscheme = nil
      for _, plugin in ipairs(core) do
        if plugin[1] == "LazyVim/LazyVim" and plugin.opts then
          colorscheme = plugin.opts.colorscheme
          break
        end
      end
      if colorscheme then
        vim.cmd.colorscheme(colorscheme)
      end
    end)
  end,
})
```
or else the theme will be applied before some plugin reloading
