### ISSUE TITLE
bug: ESC keymap doesn't work as expected in snacks.terminal

### ISSUE THREAD

**Issue by Sheol27** [LazyVim/LazyVim#4885]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.1

### Operating system/version

MacOs 15.1

### Describe the bug

Previously, before snacks.nvim i had the following keymap

`vim.keymap.set("t", "<Esc><cr>", "<cmd>close<cr>", { desc = "Hide Terminal" })`

Currently with snacks.terminal it doesn't work anymore.

### Steps To Reproduce

1. Set the keymap
2. Open a snack.terminal and try trigger the keymap

### Expected Behavior

To close the terminal

### Repro

```lua

```

**Comment by dpetka2001** [comment]
Snacks.terminal has an internal mapping for `<esc>`. Please read the docs and also the discussion topics at snacks repo, because something similar has been asked there if i remeber correctly.
