### ISSUE TITLE
bug: Quickly opening file in neotree opens file in Noice notification

### ISSUE THREAD

**Issue by zolrath** [LazyVim/LazyVim#49]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.8.2

### Operating system/version

MacOS 11.5

### Describe the bug

When launching `vim` with no args and selecting a file from neotree, if there is an open noice popup the file will open inside the popup instead of replacing the dashboard.

![image](https://user-images.githubusercontent.com/454563/211932425-210f705b-2fe3-430f-b5e1-067d50b7f104.png)

### Steps To Reproduce

1. Run `vim` in the terminal with some state that causes a noice popup. For me, the most common case is the `lazy.nvim` Plugin Updates popup on launch.
2. Quickly hit `<leader>e` to open neotree
3. Select a file and hit enter
4. The file will open in the noice popup instead of the primary buffer.

### Expected Behavior

Expect the file to replace the LAZYVIM dashboard and open normally instead of in the small popup.

**Comment by folke** [comment]
That's not a LazyVim issue. Probably Neotree that opens the file in the first buffer it finds or soemthing like that

**Comment by zolrath** [comment]
Sure, I looked at it more as an integration issue of the components of LazyVim.
I'll look into if there's a way for neotree to ignore noice popups, but that feels like something that would eventually end up here.

**Comment by folke** [comment]
Great. Feel free to submit a pr

**Comment by zolrath** [comment]
This is now [fixed](https://github.com/nvim-neo-tree/neo-tree.nvim/pull/694) on main in neo-tree, so whenever a new version gets pushed out the problem will disappear!

**Comment by folke** [comment]
Great!! Thanks!
