### ISSUE TITLE
feature: Close the terminal and return the cursor to the previous position

### ISSUE THREAD

**Issue by WikiLiu** [LazyVim/LazyVim#4906]
### Did you check the docs?

- [x] I have read all the LazyVim docs
- [x] This is not a request for a new or existing extra (see above)

### Is your feature request related to a problem? Please describe.

1. cursor in **edit window** at normal mode 
2. Ctrl + / open a vertical window
3. Ctrl + / close the window
4. cursor turn to **neo-tree window** not in edit window

### Describe the solution you'd like

step 4, should cursor go back to original place? Just like old version.

### Describe alternatives you've considered

Snacks.terminal is faster but still have a little problem.

**Comment by WikiLiu** [comment]
> There was a discussion about something similar in [snacks repo](https://github.com/folke/snacks.nvim/discussions/153). Hope it helps you.

yes, as the discussion said, Press ctrl+q to actually return the cursor to the old position. But make me confused, I replaced ctrl+q in the code with ctrl+/ and it didn't work. I don't think hide or close need to change the logic of the old cursor position, right? At least not in previous versions.
I am not so well with Lua code, sry.

**Comment by folke** [comment]
Update snacks. This now is done automatically
