### ISSUE TITLE
bug: illuminate extra displays warning on nightly

### ISSUE THREAD

**Issue by davepgreene** [LazyVim/LazyVim#4910]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.11.0-dev-1252+gb1c907f219

### Operating system/version

Ubuntu 24.04.1

### Describe the bug

On neovim nightly, when using the [vim-illuminate extra](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/extras/editor/illuminate.lua), once a buffer with an LSP client is loaded the following warning appears: `position_encoding param is required in vim.lsp.util.make_position_params. Defaulting to position encoding of the first client.`

The issue is related to https://github.com/neovim/neovim/pull/31249 but I was unable to reproduce the issue without importing `lazyvim.plugins` in my minimal repro spec so I suspect the issue is in how LazyVim's LSP configuration interacts with vim-illuminate.

My sense is that this is an issue in vim-illuminate (specifically here: https://github.com/RRethy/vim-illuminate/blob/master/lua/illuminate/providers/lsp.lua#L84) but without a clean repro that doesn't include importing `lazyvim.plugins` I can't be sure.

### Steps To Reproduce

1. Use minimal repro
2. `nvim -u repro.lua repro.lua`
3. Press a key that invokes a move motion
4. Warning appears

### Expected Behavior

No warning appears.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    { import = "lazyvim.plugins.extras.editor.illuminate" },
  },
})
```

**Comment by folke** [comment]
Why do you report this here?

**Comment by davepgreene** [comment]
> Why do you report this here?

Because something in how LazyVim sets up LSPs is triggering the warning. Like I said, I suspect the actual issue is in vim-illuminate but I can't confirm that because of how LazyVim does all of its setup under the covers.
