### ISSUE TITLE
bug: Bug when pressing `Esc` and `j` or `k` keys simultaneously.

### ISSUE THREAD

**Issue by githubnotebooks** [LazyVim/LazyVim#4912]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

archlinux

### Describe the bug

When I quickly press Esc and j, the code on the current line moves down. What I want is for it to exit insert mode and move the cursor down, but instead, the current line moves down. 

When I quickly press Esc and k, the code on the current line moves up. What I want is for it to exit insert mode and move the cursor up, but instead, the current line moves up.

### Steps To Reproduce

If I press Esc and j quickly, and if it's not fast enough, I won't notice it. The time interval between the two keys is very short, and I even suspect that they need to be pressed simultaneously.

### Expected Behavior

I want Esc to exit insert mode and j to move the cursor down, rather than moving the code on the current line down.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
That's your terminal / tmux / OS / ...
This has popped up a bunch of times.
Check the discussions / bugs.
Not a LazyVim issue
