### ISSUE TITLE
feature: vim.notify(vim.inspect(x))

### ISSUE THREAD

**Issue by vdegenne** [LazyVim/LazyVim#4926]
### Did you check the docs?

- [x] I have read all the LazyVim docs
- [x] This is not a request for a new or existing extra (see above)

### Is your feature request related to a problem? Please describe.

I love using `:lua ...` in the editor to quickly check a value (that is also how I learn a lot of things about nvim and LazyVim environment!)

It'd be great if LazyVim could wrap the input in between `vim.notify(vim.inspect(...))` automatically behind the scene if the input happens to be a table, it'd be a great way to quickly find out the content of a value.

### Describe the solution you'd like

For instance typing `:lua vim.fn.getbufinfo()` would open a snack bar with the content returned by `vim.fn.getbufinfo()`,
explicitly, `:lua vim.notify(vim.inspect(vim.fn.getbufinfo()))`

### Describe alternatives you've considered

no alternative found

**Comment by folke** [comment]
From the readme:

```lua
-- Setup some globals for debugging (lazy-loaded)
        _G.dd = function(...)
          Snacks.debug.inspect(...)
        end
        vim.print = _G.dd -- Override print to use snacks for `:=` command

**Comment by folke** [comment]
So then do `:= vim.fn.getbufinfo()`

**Comment by vdegenne** [comment]
Thanks
