### ISSUE TITLE
bug(blink): documentation window not showing in fresh LazyVim setup

### ISSUE THREAD

**Issue by emnnipal** [LazyVim/LazyVim#4938]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

MacOS 15.1.1

### Describe the bug

The documentation window for blink.cmp is not showing, even after doing a fresh clone of the LazyVim repo without custom configurations.

![Image](https://github.com/user-attachments/assets/8f4c12ae-2fb7-49a7-ab5d-1be8e7762c65)

### Steps To Reproduce

1. Performed a fresh clone of the LazyVim repository to ensure there were no conflicting custom configurations.
2. Enabled fzf-lua and blink.cmp in LazyExtras.

Note: This functionality was working in LazyVim version 13.5.3 but is no longer working in the latest version (13.6.0). **At the time of testing, the version of blink.cmp used was v0.6.2.**

### Expected Behavior

When using blink.cmp, the documentation window should appear when hovering over a completion item.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
blink just made a new release. try again
