### ISSUE TITLE
bug: mini.indentscope not being disabled on dashboard

### ISSUE THREAD

**Issue by stefanboca** [LazyVim/LazyVim#4944]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.11.0-dev+1267-gc1378413c Build type: RelWithDebInfo LuaJIT 2.1.1720049189

### Operating system/version

Fedora Linux 41

### Describe the bug

Despite #4928, mini.indentscope is still not being disabled on the snacks dashboard. I believe this is because the `FileType` autocmd is not triggered for the dashboard, or because the autocmd is created after `FileType` is executed on the dashboard. I'm not sure how to fix this.

### Steps To Reproduce

1. Open `nvim` with mini.indentscope extra enabled
2. Cause mini.indentscope to be loaded, ex by opening a scratch buffer then closing it: `<leader>.`, followed by `q`
3. Move the cursor to the first line of the dashboard, ex `Find File`. mini.indentscope draws a line like the following on the dashboard:
![Image](https://github.com/user-attachments/assets/fbba1deb-6f7c-41a1-ad2f-e9cb57b36877)

### Expected Behavior

mini.indentscope is properly disabled on the dashboard

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    { import = "lazyvim.plugins.extras.ui.mini-indentscope" },
  },
})
```

**Comment by stefanboca** [comment]
@dpetka2001 loading the plugin on `BufReadPost` as you mention in the discussion doesn't fix this issue, because mini.indentscope can get loaded while the initial dashboard is still open, ex on opening a scratch buffer (see the reproduce steps above)

I tried added the following (from the snacks discussion) into `init` and it solved the issue.
```lua
vim.api.nvim_create_autocmd("User", {
  pattern = "SnacksDashboardOpened",
  callback = function(data)
    vim.b[data.buf].miniindentscope_disable = true
  end,
})
```
I don't see any issues with this, should I make a PR?

**Comment by dpetka2001** [comment]
Yes that was the suggested correct answer. I only tried to explain that `FileType` doesn't get triggered on startup that's all. If you want to make a PR go ahead and the maintainer will decide. I'm just a simple user like you.
