### ISSUE TITLE
bug(rust): Tries to `require()` mason-registry even when mason is not enabled

### ISSUE THREAD

**Issue by futile** [LazyVim/LazyVim#4957]
I have neither mason nor codelldb/dap enabled (no Mason because Nix), but lazyvim tries to `require("mason-registry")` anyway:

https://github.com/LazyVim/LazyVim/blob/b2f750558a3737879f8151e741e7a3988886e37f/lua/lazyvim/plugins/extras/lang/rust.lua#L99-L100

Error trace:

```
   Error  13:38:03 notify.error lazy.nvim Failed to run `config` for rustaceanvim

...im/lazy/LazyVim/lua/lazyvim/plugins/extras/lang/rust.lua:100: module 'mason-registry' not found:
	no field package.preload['mason-registry']
cache_loader: module mason-registry not found
cache_loader_lib: module mason-registry not found
	no file '/nix/store/hxcwr8j33p9m437a7jyzwbzxhsyj5dh4-luajit-2.1.1713773202-env/share/lua/5.1/mason-registry.lua'
	no file '/nix/store/hxcwr8j33p9m437a7jyzwbzxhsyj5dh4-luajit-2.1.1713773202-env/share/lua/5.1/mason-registry/init.lua'
	no file '/Users/frath/.local/share/nvim/lazy-rocks/telescope.nvim/share/lua/5.1/mason-registry.lua'
	no file '/Users/frath/.local/share/nvim/lazy-rocks/telescope.nvim/share/lua/5.1/mason-registry/init.lua'
	no file '/nix/store/hxcwr8j33p9m437a7jyzwbzxhsyj5dh4-luajit-2.1.1713773202-env/lib/lua/5.1/mason-registry.so'
	no file '/Users/frath/.local/share/nvim/lazy-rocks/telescope.nvim/lib/lua/5.1/mason-registry.so'
	no file '/Users/frath/.local/share/nvim/lazy-rocks/telescope.nvim/lib64/lua/5.1/mason-registry.so'

# stacktrace:
  - /LazyVim/lua/lazyvim/plugins/extras/lang/rust.lua:100 _in_ **config**
  - /nix/store/x137yfpy63v4mkn68fkaj5ky8yv53xwf-neovim-unwrapped-0.10.2/share/nvim/runtime/filetype.lua:36
  - /nix/store/x137yfpy63v4mkn68fkaj5ky8yv53xwf-neovim-unwrapped-0.10.2/share/nvim/runtime/filetype.lua:35
  - /fzf-lua/lua/fzf-lua/fzf.lua:284
```

Mason should be optional though, I think:

https://github.com/LazyVim/LazyVim/blob/b2f750558a3737879f8151e741e7a3988886e37f/lua/lazyvim/plugins/extras/lang/rust.lua#L44-L55

Explicitly the `optional = true`.

I used the "Reference in new issue" option btw., which didn't give me an issue template:

![Image](https://github.com/user-attachments/assets/3f3583a0-53a6-4221-90dd-fe326ad25708)

Just wanted to let you know.

**Comment by folke** [comment]
feel free to create a PR

**Comment by KamWithK** [comment]
Should probably check the path to see if they're available and if not only if mason is enabled use it?

**Comment by dpetka2001** [comment]
I believe you could wrap that whole path logic using `mason-registry` in a 
```lua
if LazyVim.has("mason.nvim") then
  ....
end
```
I don't use Nix, so you can test it out locally and create a PR if it works correctly.

**Comment by futile** [comment]
> I believe you could wrap that whole path logic using `mason-registry` in a
> 
> if LazyVim.has("mason.nvim") then
>   ....
> end
> I don't use Nix, so you can test it out locally and create a PR if it works correctly (which I think it should).

Thank you very much, that was exactly what I needed (didn't know how to limit the logic to be dependent on mason.nvim being available)!

Opened a PR: https://github.com/LazyVim/LazyVim/pull/4963 👍

Btw., I spent a few minutes looking for a guide on how to set up a development environment for LazyVim, before I realized that I can work in `~/.local/share/nvim/lazy/LazyVim`.

**Comment by dpetka2001** [comment]
For local development, I just did the following in my `~/.config/LazyVimDev/lua/config/lazy.lua`
```lua
  dev = {
    path = "~/projects/plugins",
    patterns = { "LazyVim" },
  },
```
I also have a different LazyVim installation for this. So, I created a dir `~/.config/LazyVimDev` and then inside that directory I did `git clone https://github.com/LazyVim/starter.git .` and just invoke Neovim with `NVIM_APPNAME=LazyVimDev nvim` (you can make this into an alias in your shell). And then you just clone the LazyVim repo into the `config.dev.path` that you have defined. Or you can do it in your normal configuration as is currently in `~/.config/nvim/` by just adding the above code snippet in your `lazy.lua` and then just comment out `pattern = { "LazyVim" }` if you want to use the LazyVim installed as a plugin or don't comment it out if you want to use the local git repo that you have cloned. 

It's up to you which workflow fits best your needs.
