### ISSUE TITLE
bug: blink + LuaSnip not working

### ISSUE THREAD

**Issue by vdegenne** [LazyVim/LazyVim#4958]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.2

### Operating system/version

Fedora 41

### Describe the bug

When using `blink` and validating a snippet, the cursor moves to the first placeholder but insert mode is exited. Unable to replace if there is a default value:

https://github.com/user-attachments/assets/dad2faed-7684-4ae8-896a-005613b032fa

### Steps To Reproduce

1. install both blink and luaSnip
2. type `if` and select the snippet
3. insert mode exited, you can't type something
4. unless you press `i` again but placeholder is not selected.

### Expected Behavior

...

### Repro

```lua

```

**Comment by folke** [comment]
Can't reproduce with default lazyvim and blink/luasnip extras.
You're probably overriding your `<tab>` key somewhere or made other incompatible changes in your config

**Comment by folke** [comment]
btw, for me when selcting the `if` snippet, `condition` isn't there and I'm directly in insert mode.

**Comment by folke** [comment]
wait, I tested incorrectly :)

**Comment by folke** [comment]
nope, still ok

**Comment by vdegenne** [comment]
I came back to report it works for some snippets.... Here's a snippet for which it will fail:

![Image](https://github.com/user-attachments/assets/20488d78-3d60-44d6-b7a0-53d48be571c0)

**Comment by folke** [comment]
either way, not a LAzyVim issue.
If you have an issue with luasnip/blink, report it there

**Comment by folke** [comment]
Neither of those linked issues are related?

**Comment by folke** [comment]
And seems to be a luasnip issue or an issue with your mappings

**Comment by vdegenne** [comment]
@folke but when `blink` is uninstalled it works well.
Also I did nothing but add `{ import = "lazyvim.plugins.extras.coding.luasnip" }` in my specs.

Can you open a js/ts file and try the `if` snippet (from luasnip) and tell me if it works. I'll be glad to open an isssue in blink repo if that's an overall problem.

**Comment by folke** [comment]
Just tried in a js file and works perfectly fine for me

**Comment by folke** [comment]
`condition` is `selected` and when I start typing it replaces it

**Comment by folke** [comment]
From your video it seems you're not using a snippet manager at all. Since you should be in SELECT mode, but you don't seem to be

**Comment by vdegenne** [comment]
Just to be clear I have two `if` snippet, a default one (when luasnip is not installed from the extras) and another one when luasnip is installed. The first one works while the other one fails.

https://github.com/user-attachments/assets/b5b050b8-2baa-42c1-b203-34fd6a213cc8

**Comment by folke** [comment]
They both work and behave the same in a clean lazyvim install with blink/luasnip extras

**Comment by folke** [comment]
ok, after updating luasnip and blink, I see the same as you.

**Comment by soifou** [comment]
Just a guess, can you add the following blink.cmp setting to see if this fix your problem?

```lua
completion = {
    accept = {
        create_undo_point = false,
    },
}
```

**Comment by vdegenne** [comment]
@soifou It does seem to fix the problem :) Thanks
Do you consider this to be an issue? I don't know the implication of turning that parameter off.

**Comment by vdegenne** [comment]
Never mind, tabulation to travel placeholders seem broken. I'll open an issue later.
