### ISSUE TITLE
bug: set secure 

### ISSUE THREAD

**Issue by craigmac** [LazyVim/LazyVim#496]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0 commit g3285cd6ec

### Operating system/version

macOS 12.5.1

### Describe the bug

A `.nvim.lua` file should be sourced from the current directory when set secure is on and you've trusted the file.

### Steps To Reproduce

1. `cd ~/.config/nvim`
2. put `vim.o.path = '.,,lua/**'` in a `.nvim.lua` file
3. add `vim.o.secure = true` to lua.config.options.lua file
4. start nvim, accept to trust the file
5. restart, and check `set path?` it won't have the value set in that filej

### Expected Behavior

path would be altered when starting nvim in ~/.config/nvim directory

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
vim.o.secure = true
```

**Comment by folke** [comment]
please debug this yourself. LazyVim, not lazy do anything special with .nvim.lua files. Add a print statement or something like that, check if you're using the secure functionality correctly...
