### ISSUE TITLE
feature: disable all default which-key

### ISSUE THREAD

**Issue by grimgort** [LazyVim/LazyVim#497]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

when you migrate your own configuration, the default wich-key values generate your own keyboard shortcut. Would it be possible to have an option to put no default wich-key value .
Thank you very much 

### Describe the solution you'd like

no idea

### Describe alternatives you've considered

no idea

**Comment by amaanq** [comment]
you can set the desc field in the options table when setting keymaps to what you like

**Comment by grimgort** [comment]
I don't understand what to do.
When I define my keymaps, I use for example :
vim.keymap.set("n", "gS", "<cmd>Telescope lsp_document_symbols<CR>", { noremap = true, silent = true })
But if this corresponds to a which-key table my shortcut is not translated with the right command

**Comment by grimgort** [comment]
I think I didn't make myself understood. In fact, the which-key shortcuts with a name overload override the vim.keymap shortcuts. example



```lua
local wk = require("which-key")
-- As an example, we will create the following mappings:
--  * <leader>ff find files
--  * <leader>fr show recent files
--  * <leader>fb Foobar
-- we'll document:
--  * <leader>fn new file
--  * <leader>fe edit file
-- and hide <leader>1
wk.register({
  f = {
    name = "file", -- optional group name
    f = { "<cmd>Telescope find_files<cr>", "Find File" }, -- create a binding with label
    r = { "<cmd>Telescope oldfiles<cr>", "Open Recent File", noremap=false, buffer = 123 }, -- additional options for creating the keymap
    n = { "New File" }, -- just a label. don't create any mapping
    e = "Edit File", -- same as above
    ["1"] = "which_key_ignore",  -- special label to hide it in the popup
    b = { function() print("bar") end, "Foobar" } -- you can also pass functions!
  },
}, { prefix = "<leader>" })
```
followed by vim.keymap.set("n", "<leader>ff", "<cmd>Telescope <cr>", { })

which key will keep as description "Find File" and not <cmd>Telescope <cr>

as lazyvim configures wichkey, this is not practical to remap the default lazyvim configuration

**Comment by amaanq** [comment]
> vim.keymap.set("n", "gS", "Telescope lsp_document_symbols", { noremap = true, silent = true })

```lua
vim.keymap.set("n", "gS", "Telescope lsp_document_symbols", { noremap = true, silent = true, desc = "This is what it does" })
```

**Comment by dpetka2001** [comment]
> I think I didn't make myself understood. In fact, the which-key shortcuts with a name overload override the vim.keymap shortcuts. example
> 
> ```lua
> local wk = require("which-key")
> -- As an example, we will create the following mappings:
> --  * <leader>ff find files
> --  * <leader>fr show recent files
> --  * <leader>fb Foobar
> -- we'll document:
> --  * <leader>fn new file
> --  * <leader>fe edit file
> -- and hide <leader>1
> wk.register({
>   f = {
>     name = "file", -- optional group name
>     f = { "<cmd>Telescope find_files<cr>", "Find File" }, -- create a binding with label
>     r = { "<cmd>Telescope oldfiles<cr>", "Open Recent File", noremap=false, buffer = 123 }, -- additional options for creating the keymap
>     n = { "New File" }, -- just a label. don't create any mapping
>     e = "Edit File", -- same as above
>     ["1"] = "which_key_ignore",  -- special label to hide it in the popup
>     b = { function() print("bar") end, "Foobar" } -- you can also pass functions!
>   },
> }, { prefix = "<leader>" })
> ```
> 
> followed by vim.keymap.set("n", "ff", "Telescope ", { })
> 
> which key will keep as description "Find File" and not Telescope
> 
> as lazyvim configures wichkey, this is not practical to remap the default lazyvim configuration

I don't understand what you're trying to achieve here. Can you be more specific with concrete example? What have you tried? And what do you expect it to do?
