### ISSUE TITLE
bug:  codeium can not use

### ISSUE THREAD

**Issue by CnsMaple** [LazyVim/LazyVim#4975]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.2

### Operating system/version

win11

### Describe the bug

![Image](https://github.com/user-attachments/assets/c4ebd5cd-3c9d-4fa6-ae75-4e1caeb10282)

### Steps To Reproduce

i only update the lazyvim, and the codeium can not to use

### Expected Behavior

the codeium can not to use

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
Have you tried with fresh LazyVim installation from scratch? Because I can't reproduce it. Granted I'm on Linux and not Windows and maybe it has to do something with the OS environment.

**Comment by CnsMaple** [comment]
I have tried reinstalling, but the problem still persists.It may be a problem with Windows

**Comment by folke** [comment]
That can only happen if you override the `config` function for the `blink` spec, or you're not using the blink extra.

**Comment by CnsMaple** [comment]
@folke According to your statement, if I annotate it, I should report the same error. but ......

https://github.com/user-attachments/assets/439b924d-9e01-47d8-9d7d-3a2574863f9c

**Comment by CnsMaple** [comment]
And, I only use the Codeium plugin, which has the same issue

**Comment by folke** [comment]
If you don't use `LazyExtras`, then you have to manually make sure you import the correct extras in the correct order.
In this case, the blink extra should be above the codeium one.

I really recommend using LazyExtras instead.

**Comment by CnsMaple** [comment]
Thank you, I have been using your template for a long time, and it can still work like this. I am now using Extras
