### ISSUE TITLE
bug: util.cmp.visible broken for blink.cmp

### ISSUE THREAD

**Issue by Trildar** [LazyVim/LazyVim#4985]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

Windows 11 22631.4541

### Describe the bug

Not sure if this utility function is still used anywhere in LazyVim itself, but thought it would be good to flag that recent refactors in blink.cmp have broken this function.

### Steps To Reproduce

N/A

### Expected Behavior

N/A

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
That's no longer used. Will remove
