### ISSUE TITLE
bug: all telescope root utilities actually use cwd in git projects

### ISSUE THREAD

**Issue by Murderlon** [LazyVim/LazyVim#499]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

`NVIM v0.9.0-dev-613+gef18c9f9b-dirty`. Later reinstalled at `NVIM v0.8.3`, problem still there.

### Operating system/version

macOS 13.2.1

### Describe the bug

I'm very happy with LazyVim and it's default keybindings, they're very sensible ❤️ 

Unfortunately the keybindings that use `util.get_root()`, such as the telescope keybindings, seem to behave different with and without git.

### Steps To Reproduce

Open a project with git at the root with neovim.

1. Go into some folder
2. Enter any file
3. `<leader><space>`  (or any telescope default keybinding that uses the same util)
4. Only results within that folder

### Expected Behavior

All results from root. This correctly works in projects without git for me.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
I've read in the code that `util.get_root()` will return first the lsp root_dir and then root pattern of file buffer and last root pattern of cwd in that specific order. So might it be that your lsp root_dir is not configured to be the same with root_dir of your project or whatever you want? Thus the discrepancy in the results? Because in my case, i don't experience this problem. I get root_dir and cwd results correctly, but my lsp root_dir is the same as my specific project I'm working on which coincides with the dir the `.git` dir resides.

**Comment by Murderlon** [comment]
Interesting! I just openend a Go project and it didn't happen there, but it does happen in JS/TS. Perhaps we can't trust the LSP root dir as it differs per LSP?

**Comment by amaanq** [comment]
> Interesting! I just openend a Go project and it didn't happen there, but it does happen in JS/TS. Perhaps we can't trust the LSP root dir as it differs per LSP?

I cannot reproduce this in a Go project, root dir search works fine

**Comment by Murderlon** [comment]
I figured it out. All LSP's had the correct root dir, except for `cssmodules-language-server`, and somehow that one takes precedence over all other LSPs to determine the root dir? I'm not sure if this is a bug with this particular LSP or something that can be done for LazyVim's side.

Depending on how common it is for a LSP to have a different root, there are three options:
- Leave things as is
- `get_root()` doesn't take into account the LSP root dir but the folder neovim was opened in
- `get_root()` checks all attached LSPs and takes the highest root?

**Comment by Murderlon** [comment]
> but I'm gonna say this is the lsps issue

Unfortunately null-ls and tsserver get it wrong too, and null-ls is used for a lot of things in LazyVim. I'm starting to think `get_root()` shouldn't try to be too smart about it and just use the root neovim was opened in.

**Comment by Murderlon** [comment]
Note that `tsserver` takes the nearest `tsconfig.json`, so `get_root()` will be incorrect for all monorepos!

Example: https://github.com/tus/tus-node-server.

**Comment by dpetka2001** [comment]
`tsserver` specifically looks for `root_pattern("package.json", "tsconfig.json", "jsconfig.json", ".git")`. Does the order here maybe matter? Could we maybe configure tsserver with `root_pattern( ".git", "package.json", "tsconfig.json", "jsconfig.json")` for example so that `.git` folder takes precedence over the other patterns? Not really sure just shooting around ideas.

**Comment by Murderlon** [comment]
I think that's the wrong way to go about this. I think it's clear that a LSP should be allowed to determine it's own root for whatever reason. The solution is not override all LSPs that have different roots, it's to simplify `get_root()` to only look at where neovim is opened, regardless of what LSPs determine.

**Comment by dpetka2001** [comment]
Let's wait for the maintainer to see what he thinks about that. If he agrees, it should be just a removal of some code from get_root() so that LSP root is not taken into consideration.

**Comment by Murderlon** [comment]
@folke would you mind elaborating on your decision? I'm not sure what's best for me to do here.

**Comment by folke** [comment]
The `get_root` util will try to determine the proper root directory for the buffer you're on. If you want to use the cwd instead, you can always do `<leader>fF` instead of `<leader>ff` (which is the same as `<leader><space>`.

I use this a lot in monorepos. I start Neovim in the monorepo root, then open a file in one of the packages and all the telescope commands then only list the files from that package.

When I want to open a file from another package I do `<leader>fF` instead.

I also always make sure that the root_dirs for my lsp clients are correct. If they're not correct, that can lead to other issues with the lsps as well.

Excluding `null-ls` from the get_root might be an option, but that would typically be the `cwd` anyway.

**Comment by Murderlon** [comment]
I'm just thinking about keeping LazyVim designed for the 80%+ use case. AFAIK people in general aren't used to a magic root switch within the same keybinding, so it's a bit unexpected. Furthermore I think it's taking too many assumptions that people working in monorepos only want to see files within that packages _most of the time_. And that's the important part, keeping the quick, pleasant keybindings to the common flow. You can do `<leader>fF` but it's harder to do fast and to accidentally do it without the uppercase letter.

> I also always make sure that the root_dirs for my lsp clients are correct. If they're not correct, that can lead to other issues with the lsps as well.

They are correct for me too. Indeed, inside a package with its own `tsconfig` I want to LSP to respect that, not the root. But how LSPs work shouldn't be tied to how our mind works regarding find and search. LSPs may determine different root's for all kinds of reasons, and I think we should let them and keep search and find predictable.

**Comment by folke** [comment]
You can easily make it so you always get the cwd:

```lua
require("lazyvim.util").get_root = function() return vim.loop.cwd() end
```

**Comment by Murderlon** [comment]
That's true! But I brought this up is not just for me, I'm just bringing up the debate because lots of people use LazyVim and I'm assuming, to the best of my ability, that most people would be less confused when these keybindings are predictable. It's currently surprising for users because:

- It's undocumented and happens automagically, suddenly are different even though you did the same keybinding
- From all the vim distros and personal configs I've seen come by over the years, I haven't seen something like this before. I'd argue most people aren't either so it's not common.
- When you figure it out, you start the process of mental overhead of keeping in mind when you want which keybinding for your global search. In some projects it's `<leader><space>` until it suddenly isn't! I'd say one of Vim's goals is that you can move at the speed of thought, you start to get muscle memory for things. This breaks you muscle memory. But having fixed keybindings wouldn't break it, in your mind you think I want CWD results and you press `<leader>fF`, otherwise the quick 'ol `<leader><space>`.

Wouldn't you say it's better for _you_ to have this `get_root` utility in your _personal_ config, while keeping it predictable for the rest of us?

**Comment by briandipalma** [comment]
FWIW 90%+ of my file and text searches are full monorepo so it would be nice to swap the cwd/root searches around.

This is especially true with `mini.files` which allows for very easy file movement within the same package. It makes `<space><space>` almost useless.

The mental toggling between cwd and root is probably the highest friction I have in LazyVim and I work in a large monorepo so I should feel its benefit the most.

**Comment by Murderlon** [comment]
In the meantime you can have this in your config to have it predictable. But I agree that upstreaming this would be ideal.

```lua
  {
    "nvim-telescope/telescope.nvim",
    keys = {
      {
        "<leader>fd",
        Util.telescope("git_files", { cwd = "$HOME/code/dotfiles" }),
        desc = "[F]ind [D]otfiles",
      },
      { "<leader><space>", Util.telescope("files", { cwd = false }), desc = "Find Files (root dir)" },
      { "<leader>ff", Util.telescope("files", { cwd = false }), desc = "Find Files (root dir)" },
      { "<leader>sg", Util.telescope("live_grep", { cwd = false }), desc = "Grep (root dir)" },
      { "<leader>sw", Util.telescope("grep_string", { cwd = false }), desc = "Word (root dir)" },
    },
  },

```

**Comment by folke** [comment]
```lua
require("lazyvim.util").get_root = vim.loop.cwd

**Comment by dvic** [comment]
What I did was just flip the "defaults" (i.e., `cwd = false` becomes the lowercase shortcut, as well as `<leader>/` and `<leader><space>`):

```lua
local Util = require("lazyvim.util")

return {
  "nvim-telescope/telescope.nvim",
  keys = {
    { "<leader>/", Util.telescope("live_grep", { cwd = false }), desc = "Grep (cwd)" },
    { "<leader><space>", Util.telescope("files", { cwd = false }), desc = "Find Files (cwd)" },
    { "<leader>ff", Util.telescope("files", { cwd = false }), desc = "Find Files (cwd)" },
    { "<leader>fF", Util.telescope("files"), desc = "Find Files (root dir)" },
    { "<leader>sg", Util.telescope("live_grep", { cwd = false }), desc = "Grep (cwd)" },
    { "<leader>sG", Util.telescope("live_grep"), desc = "Grep (root dir)" },
  },
}
```

This makes more sense to me and makes the searching more consistent when switching between regular repo's / mono repo's.
