### ISSUE TITLE
bug: `sources.completion.enabled_providers` has been replaced with `sources.default`

### ISSUE THREAD

**Issue by CnsMaple** [LazyVim/LazyVim#4990]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

win11

### Describe the bug

![Image](https://github.com/user-attachments/assets/6ff63188-fab8-4c89-967f-82756309b513)

### Steps To Reproduce

look image

### Expected Behavior

 look image

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by fang2hou** [comment]
Temp fix before lazyvim config updates
```lua
	{
		"saghen/blink.cmp",
		config = function(_, opts)
			opts.sources.default = opts.sources.completion.enabled_provider
			opts.sources.completion = nil

			opts.sources.providers.lsp.fallback = opts.sources.providers.lsp.fallback_for
			opts.sources.providers.lsp.fallback_for = nil
			require("blink.cmp").setup(opts)
		end,
	},
```

**Comment by mikavilpas** [comment]
Thanks for the fixes!

For anyone else following the main branch right now, set [this](https://www.lazyvim.org/extras/coding/blink#options) 
<img width="993" alt="Image" src="https://github.com/user-attachments/assets/5ae3ede8-9945-4d10-8935-119b80d277e0" />

```lua
vim.g.lazyvim_blink_main = true
```

**Comment by folke** [comment]
just update LazyVim? The lazyvim config works on latest main and stable of blink.

**Comment by mikavilpas** [comment]
Looks like I forgot to mention I use the nightly version of blink (its main branch).

Without this setting I get 
![Image](https://github.com/user-attachments/assets/f85f7387-fbb0-4de1-ab4e-c1045c18f51b)

But I think that's the expected behaviour - my message was just confusing.

**Comment by folke** [comment]
oh right, that makes sense indeed
