### ISSUE TITLE
bug: In a rust file, repeating an insert with a '>' character does not include that character

### ISSUE THREAD

**Issue by Strackeror** [LazyVim/LazyVim#4993]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

OpenSUSE Tumbleweed

### Describe the bug

The title is pretty self explanatory, when repeating an insert or text entry in a rust file, the entry is repeated without any of that character.
Attempting it with the minimal reproduction lua for rustaceanvim, it works normally, so I guess it's not that plugin causing this directly.
I tried the same with a json file, a c file and cpp file and none show that behavior.

### Steps To Reproduce

1. run `nvim -u repro.lua newfile.rs`
2. insert `1>0` in the new empty file
3. `.` to repeat the insert

only `10` is inserted on the repeat

### Expected Behavior

`1>0` should be inserted

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
Seems to be caused by nvim-ts-autotag.
That is active in rust, but not in lua.
File a bug there. Not a LazyVim issue

**Comment by Strackeror** [comment]
I would *not* have thought to look for a tag closing plugin in a rust file, thanks for the direction !
For anyone else coming across this, there's already an issue about this on that repo: https://github.com/windwp/nvim-ts-autotag/issues/166

**Comment by folke** [comment]
First thing to do in cases like this is `:verbose imap >`.
