### ISSUE TITLE
bug: blink doesn't start

### ISSUE THREAD

**Issue by OneOfOne** [LazyVim/LazyVim#4997]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.11.0-dev-1326+g3bb2d02759

### Operating system/version

Arch

### Describe the bug

```
Failed to run `config` for blink.cmp

...are/nvim/lazy/blink.cmp/lua/blink/cmp/config/sources.lua:77: `sources.completion.enabled_providers` has been replaced with `sources.default`. !!Note!! Be sure to update `opts_extend` as well if you have it set

# stacktrace:
  - /blink.cmp/lua/blink/cmp/config/sources.lua:77 _in_ **validate**
  - /blink.cmp/lua/blink/cmp/config/init.lua:46 _in_ **validate**
  - /blink.cmp/lua/blink/cmp/config/init.lua:55 _in_ **merge_with**
  - /blink.cmp/lua/blink/cmp/init.lua:7 _in_ **setup**
  - /LazyVim/lua/lazyvim/plugins/extras/coding/blink.lua:125 _in_ **config**
  - /LazyVim/lua/lazyvim/plugins/lsp/init.lua:185 _in_ **config**
  - vim/_editor.lua:0 _in_ **cmd**
```

### Steps To Reproduce

1. enable blink extra (and copilot in case that matters)

### Expected Behavior

work

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by OneOfOne** [comment]
setting `vim.g.lazyvim_blink_main = true` fixes it.

**Comment by folke** [comment]
or upgrading LazyVim.

**Comment by vdegenne** [comment]
Is there a way to rely on blink main branch? using `vim.g.lazyvim_blink_main = true` produces a new error.

**Comment by dpetka2001** [comment]
@vdegenne I made a PR for the new error with strict config validation. You might want to revert `blink` to a previous commit until the PR gets merged or just use the PR locally.

**Comment by vdegenne** [comment]
@dpetka2001 Nice~:) Yes that's this error. (for reference: https://github.com/LazyVim/LazyVim/pull/5017)
