### ISSUE TITLE
feature: add F2 to fullscreen Notification History window

### ISSUE THREAD

**Issue by vdegenne** [LazyVim/LazyVim#5028]
### Did you check the docs?

- [x] I have read all the LazyVim docs
- [x] This is not a request for a new or existing extra (see above)

### Is your feature request related to a problem? Please describe.

![Image](https://github.com/user-attachments/assets/1e21e854-4e3e-4dcc-a93e-3760e7eb068f)

This window can be too small.

### Describe the solution you'd like

Would be nice to have a shortcut (default to `F2`(?) similar to ffz) to fullscreen this window, sometimes the error message are lengthy, that would permit to have a quick view of everything without having to move the cursor around to reveal hidden parts.

### Describe alternatives you've considered

...

**Comment by vdegenne** [comment]
@folke That's great, but what about making a toggle_fullscreen method for `snacks.win`? That would be cool! So we can write:

```lua
Snacks.config.style("notification.history", {
  -- ....
  keys = {
    q = "close",
    ["<f2>"] = function(self)
      self.toggle_fullscreen()
    end,
  },
})
```

Also for the reason we could show the keys at the bottom (like in the scratch), it's more user-friendly:

![Image](https://github.com/user-attachments/assets/22836bdc-5b17-458d-bfce-c911073d40d7)

**Comment by folke** [comment]
Snacks.zen.zoom works for any window / floating window and is not limited to snacks windows.

**Comment by folke** [comment]
I personally also never ever use function keys.

**Comment by vdegenne** [comment]
I guess it's fine I can just call zoom on the window receiving `F2` (if I find how), the reasoning behind `:zoom()` was to make things more modulable and user friendly.
