### ISSUE TITLE
bug: warning spam, cmd_cwd

### ISSUE THREAD

**Issue by viktor21minds** [LazyVim/LazyVim#5035]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1713773202

### Operating system/version

MacOS 15.1.1

### Describe the bug

After updating to v14 i keep getting this error warned every time i open a new file. No idea how would i debug this even 
```
  Warn  17:42:53 notify.warn ...wrapped-0.10.2/share/nvim/runtime/lua/vim/lsp/client.lua:356: cmd_cwd: expected directory, got /Users/viktornagy/Code/21minds/21m-event-frontend/package.json
```

### Steps To Reproduce

update to 14

### Expected Behavior

to dont spam

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
Do you have any custom LSP server configuration in your personal dotfiles? That seems to be the problem.

**Comment by minusfive** [comment]
Probably related to this `lspconfig` regression? https://github.com/neovim/nvim-lspconfig/issues/3503

**Comment by zivkovicn** [comment]
having the same issue, waiting the https://github.com/neovim/nvim-lspconfig/issues/3503 - probably should resolve it tnx @minusfive

**Comment by dpetka2001** [comment]
Good catch @minusfive 😄

**Comment by jacobrreed** [comment]
https://github.com/neovim/nvim-lspconfig/pull/3505 PR opened, waiting on merge

**Comment by minusfive** [comment]
Thanks @jacobrreed!
