### ISSUE TITLE
bug: Log spam when typing

### ISSUE THREAD

**Issue by Freaksed** [LazyVim/LazyVim#5039]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.11.0-dev-973+gb7e8966715

### Operating system/version

wsl running arch

### Describe the bug

When I type I got red errors on the side of the screen with every key press.
Error executing vim.schedule lua callback: ...are/nvim/lazy/blink.cmp/lua/blink/cmp/lib/text_edits.lua:73: bad argument #2 to 'str_byteindex' (number expected, got string)
stack traceback:
	[C]: in function 'str_byteindex'
	...are/nvim/lazy/blink.cmp/lua/blink/cmp/lib/text_edits.lua:73: in function 'get_line_byte_from_position'
	...are/nvim/lazy/blink.cmp/lua/blink/cmp/lib/text_edits.lua:139: in function 'to_utf_8'
	...are/nvim/lazy/blink.cmp/lua/blink/cmp/lib/text_edits.lua:123: in function 'get_from_item'
	...link.cmp/lua/blink/cmp/completion/windows/ghost_text.lua:63: in function 'draw_preview'
	...link.cmp/lua/blink/cmp/completion/windows/ghost_text.lua:48: in function 'show_preview'
	...re/nvim/lazy/blink.cmp/lua/blink/cmp/completion/init.lua:52: in function 'callback'
	.../nvim/lazy/blink.cmp/lua/blink/cmp/lib/event_emitter.lua:28: in function 'emit'
	...re/nvim/lazy/blink.cmp/lua/blink/cmp/completion/list.lua:105: in function 'select'
	...re/nvim/lazy/blink.cmp/lua/blink/cmp/completion/list.lua:77: in function 'show'
	...re/nvim/lazy/blink.cmp/lua/blink/cmp/completion/init.lua:32: in function <...re/nvim/lazy/blink.cmp/lua/blink/cmp/completion/init.lua:29>
Error detected while processing CursorMovedI Autocommands for "*":
Error executing lua callback: ...are/nvim/lazy/blink.cmp/lua/blink/cmp/lib/text_edits.lua:73: bad argument #2 to 'str_byteindex' (number expected, got string)
stack traceback:
	[C]: in function 'str_byteindex'
	...are/nvim/lazy/blink.cmp/lua/blink/cmp/lib/text_edits.lua:73: in function 'get_line_byte_from_position'
	...are/nvim/lazy/blink.cmp/lua/blink/cmp/lib/text_edits.lua:139: in function 'to_utf_8'
	...are/nvim/lazy/blink.cmp/lua/blink/cmp/lib/text_edits.lua:123: in function 'get_from_item'
	...link.cmp/lua/blink/cmp/completion/windows/ghost_text.lua:63: in function 'draw_preview'
	...link.cmp/lua/blink/cmp/completion/windows/ghost_text.lua:32: in function <...link.cmp/lua/blink/cmp/completion/windows/ghost_text.lua:31>

### Steps To Reproduce

Update to v14
Open a file
Start typing

### Expected Behavior

It should not spam me with errors

### Repro

```lua
-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
```

**Comment by patelharsh9797** [comment]
New update got me so hard with popup and error.
Its goanna be hell lot of rides to make everything work again as it was!

**Comment by Freaksed** [comment]
yeah i did a hard git reset trying to get it to work even. and lazyhealth says everything is fine

**Comment by folke** [comment]
How is this a LazyVim issue?
If you're encountering bugs with blink, then open an issue in that repo.

**Comment by Freaksed** [comment]
because it was updating LazyVim that introduced this bug. the new version put in blink, and now everything is broken...

**Comment by folke** [comment]
Oh no!

**Comment by Freaksed** [comment]
yes not ideal... as i mentioned in an earlier comment i even tried doing a hard git reset on my nvim config to get the latest clean lazyvim. but it did not help

**Comment by Freaksed** [comment]
the lsp is also not working, but i figured a narrow bug was better

**Comment by folke** [comment]
There's a bug in lsp-config right now affecting multiple languages, so that might be it as well
https://github.com/neovim/nvim-lspconfig/issues/3503

**Comment by Freaksed** [comment]
i saw this, but i dont see lua/lspconfig/util.lua in my config

**Comment by folke** [comment]
What do you mean? You are using lspconfig and you don't need to have that file in your conifg to be affected.

Btw, if you still have nvim-cmp specs around, you need to remove those. Or install the nvim-cmp extra.

**Comment by skrobul** [comment]
For anyone landing here from search engines, I had same error/traceback and the solution was to update Neovim itself, don't remember which commit I had before but now it's at `NVIM v0.11.0-nightly+e8a6c1b`.
