### ISSUE TITLE
bug: completion plugins fore codium/copilot don't work

### ISSUE THREAD

**Issue by jacquesg** [LazyVim/LazyVim#5040]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

MacOS

### Describe the bug

Seeing the following since upgrading to 14. If I switch to `nvim-cmp`, this goes away, but, having other issues with that, so trying to make it work with `blink`.

<img width="787" alt="Image" src="https://github.com/user-attachments/assets/c334c625-ec99-4cf5-9e6e-326ff362d0bc" />

### Steps To Reproduce

Upgrade to 14.

### Expected Behavior

It should still work

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
You still have a nvim-cmp spec in your config.
If you want to keep using nvim-cmp, you need to enable the extra.
If not, renove that spec from your config.

**Comment by jacquesg** [comment]
The error is gone, thank you, removed my `nvim-cmp` config, but the ai plugins simply don't work.

**Comment by cjgratacos** [comment]
same, removed `nvim-cmp`, error is gone but ai plugins still don't work. Do we have to revert back to `nvim-cmp` to use ai plugins?

**Comment by folke** [comment]
I also just pushed an update to make sure nvim-cmp specs won't cause no longer issues,
so other users won't have this.

**Comment by folke** [comment]
All ai plugins work for me.

**Comment by cjgratacos** [comment]
thanks @folke going to test it out and report back

**Comment by jacquesg** [comment]
I've updated to the latest, the copilot lang server is running, but the completions are definitely not being presented:

<img width="617" alt="Image" src="https://github.com/user-attachments/assets/f296f1e6-fdbd-4a8f-84c3-d3e5350a7103" />

**Comment by jacquesg** [comment]
Could very well be due to this, which seems to have been reported:

```
unhandled error: ...al/share/nvim/lazy/nvim-lspconfig/lua/lspconfig/util.lua:256: bad argument #1 to 'lines' (/Users/jacquesg/dev/projects/asterias/deianira/package.json/package.json: Not a directory)```

**Comment by folke** [comment]
Yes, like I mentioned too many times already in this or other issues: https://github.com/neovim/nvim-lspconfig/issues/3503

**Comment by jacquesg** [comment]
I've reverted to the known good commit, error is gone, but still no completions for the ai plugins :)

**Comment by folke** [comment]
You are using the codeium extra right?
Did you do `:Codeium Auth`?

**Comment by jacquesg** [comment]
It was authed already, redid it, same result. I've got both codeium and copilot enabled, neither work

**Comment by folke** [comment]
the completions might be lower in the menu and not shown at the top. Did you check that?

**Comment by jacquesg** [comment]
Yep, they're not in the popup menu at all.

**Comment by Sairyss** [comment]
Having same issue here. Had nvim-cmp error at first. Reinstalled LazyVim from scratch, didn't add any custom config yet. Just added copilot from LazyExtras, authenticated. No errors now, but AI autocompletion doesn't work at all.

**Comment by folke** [comment]
Can you check again? Should be fixed now.

**Comment by jacquesg** [comment]
Yep, all working now for me! Thank you.

**Comment by folke** [comment]
great

**Comment by cjgratacos** [comment]
I know this is closed but it is working for me as well, thanks @folke and everyone

**Comment by rongxinyu** [comment]
Hi, may I ask how this issue was solved? 

I just installed the latest lazyvim and enabled ai (copilot) from lazy extras, but I am seeing only regular completions, no copilot.

I have authed copilot and loaded blink/blink-cmp-copilot/copilot.lua

**Comment by hirotaka** [comment]
After upgrading LazyVim, I had trouble seeing Copilot suggestions with blink-cmp.

In my case, deleting my current Neovim files and starting up again solved the issue!

```
mv ~/.local/share/nvim{,.bak}
mv ~/.local/state/nvim{,.bak}
mv ~/.cache/nvim{,.bak}
```
