### ISSUE TITLE
feature: which-key keymaps configurable

### ISSUE THREAD

**Issue by chuan137** [LazyVim/LazyVim#505]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

The keymaps are local to "which-key" config function, so overriding the settings is not possible. 

### Describe the solution you'd like

Would be nice to make the keymaps part of the option.

### Describe alternatives you've considered

My alternative for removing/changing the keymaps is to copy the code from Lazyvim into my own config and edit them in place.

**Comment by folke** [comment]
I just made some changes to make this configurable, but in the end it's not really worth the added complexity.

Overriding the `config` for which-key like you do now is the easier and better way I think.
