### ISSUE TITLE
bug:

### ISSUE THREAD

**Issue by farzadmf** [LazyVim/LazyVim#5052]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

MacOS 15.1.1

### Describe the bug

Cannot enable `nvim-cmp` (instead of `blink.cmp`) using the extra

### Steps To Reproduce

1. Start Nvim with the repo steps
2. When loaded, press `l` (to open `lazy.nvim`)
3. Find the `Disabled` section.
4. `blank.cmp` is mentioned there (expected); also `nvim-cmp` is there (not expected)

### Expected Behavior

Given that I enabled `nvim-cmp` extra, I expect `nvim-cmp` to not appear in the `Disabled` section

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
    { import = "lazyvim.plugins.extras.coding.nvim-cmp" },
  },
})
```

**Comment by folke** [comment]
`:LazyExtras`. just enable `nvim-cmp`

**Comment by farzadmf** [comment]
Hey @folke , thank you for your reply and sorry I missed updating the issue's title.

I've never used `:LazyExtras`, and I've been enabling extras with the approach I mentioned above (or least I thought I'm doing so).

I thought we can use extras in _either_ (not both) of two ways:
- Mention the `{ import = '...' }` in the config
- Use `:LazyExtras`

Isn't that the case? Do we need to do both?
