### ISSUE TITLE
bug: files with chinese characters can't be previewed with fzf-lua

### ISSUE THREAD

**Issue by hnsylzg** [LazyVim/LazyVim#5055]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.2

### Operating system/version

windows10

### Describe the bug

find file cannot display Chinese file names or preview the contents of Chinese file names![Image](https://github.com/user-attachments/assets/b8c14936-9324-476b-8650-1e4e37f1781f)

### Steps To Reproduce

nvim

### Expected Behavior

Display Chinese file names and contents normally

**Comment by hnsylzg** [comment]
The same problem occurs when I switch to telescope

**Comment by ibhagwan** [comment]
Can you see the Unicode chars in the neovim terminal?
Run `:new | term` and then `ls`, do the chars display properly?
How about if you run `fzf` within the neovim term?

If the characters aren’t displayed with the above you’re issue is not with LazyVim, if the above works, try running `:FzfLua profiles` and select `fzf-native`, this will prevent fzf-lua from doing any processing and will be equal to running fzf directly in the neovim terminal.

**Comment by ibhagwan** [comment]
Just tried random Chinese chars I found online, seems to work, is it possible your font isn’t configured properly on your windows terminal?

![Image](https://github.com/user-attachments/assets/6528a9a6-1f8c-44f3-a9b1-fa2529b44896)

**Comment by hnsylzg** [comment]
Running fzf in neovim terminal works fine, but switching to fzf-native still does not display Unicode chars properly![Image](https://github.com/user-attachments/assets/903453a5-75bf-48a3-b9d6-146987b07b89)

**Comment by ibhagwan** [comment]
> Running fzf in neovim terminal works fine, but switching to fzf-native still does not display Unicode chars properly

Do you have `fd` or `rg` installed? If so what’s the output of `fd` or `rg --files`? Do these work as expected?
Can you run `:FzfLua files debug=true`? I’d like to see which command was auto-detected to list files on your machine.

Can you run this and let me know if this is able to display Chinese characters?
```lua
:lua require('fzf-lua').fzf_exec({ '世', '界' })
```

**Comment by hnsylzg** [comment]
![Image](https://github.com/user-attachments/assets/b6573724-d0e7-4a7d-b03b-da49a2f71051)

**Comment by ibhagwan** [comment]
Also I assume dir.exe works so can you try:
```lua
:lua require('fzf-lua').files({ cmd = 'dir /s/b/a:-d' })
```

**Comment by hnsylzg** [comment]
![Image](https://github.com/user-attachments/assets/eeee1d8a-7f5e-4ac7-8c05-b140b92f06c4)
:lua require('fzf-lua').files({ cmd = 'dir /s/b/a:-d' })![Image](https://github.com/user-attachments/assets/ad913827-21fb-4da8-a32e-aafc4235b7cb)

**Comment by folke** [comment]
@ibhagwan maybe `formatter = "path.dirname_first"` is causing issues?

**Comment by ibhagwan** [comment]
> [@ibhagwan](https://github.com/ibhagwan) maybe `formatter = "path.dirname_first"` is causing issues?

Mentioned  it doesn’t work on fzf-native (no formatted) and also 

> The same problem occurs when I switch to telescope

@hnsylzg, I see the auto detected command for files was `dir.exe`, do you not have `rg` installed? I don’t have access to my windows VM anymore but perhaps dir doesn’t support UTF8?

Try:
```lua
:lua require('fzf-lua').files({ cmd = 'rg --files' })
:lua require('fzf-lua').files({ cmd = 'fd --type f' })
```

**Comment by hnsylzg** [comment]
I don't have rg, I downloaded fd![Image](https://github.com/user-attachments/assets/d8984ef8-46f2-41b3-b9f9-acaa015eb5bc)

**Comment by folke** [comment]
ok, great, so it works now?

**Comment by hnsylzg** [comment]
rg![Image](https://github.com/user-attachments/assets/8a867d95-b88a-42eb-86e0-00d05da772f2)

**Comment by ibhagwan** [comment]
> I don't have rg, I downloaded fd

Great, this seems to have solved the issue.

2 notes:
- You’ll need `rg` to use grep pickers (I see you already installed)
- The reason this works with Fzf in the term is because recently Fzf added an internal go file system enumeration library so it doesn’t rely on external commands anymore

I also found this which may solve your issue with `dir.exe`:
https://github.com/BurntSushi/ripgrep/blob/041544853c86dde91c49983e5ddd0aa799bd2831/FAQ.md?plain=1#L810-L814

```markdown
If you continue to have encoding problems, you can also force the encoding
that the console will use for printing to UTF-8 with
`[System.Console]::OutputEncoding = [System.Text.Encoding]::UTF8`. This
will also reset when PowerShell is restarted, so you can add that line
to your profile as well if you want to make the setting permanent.
```

**Comment by hnsylzg** [comment]
Can you give me some more specific modification steps? I just came into contact with lazyvim yesterday.

**Comment by folke** [comment]
Thanks for the help @ibhagwan!

**Comment by ibhagwan** [comment]
> Can you give me some more specific modification steps? I just came into contact with lazyvim yesterday.

Once you downloaded fd/rg you don’t need to modify anythinh, fzf-lua should auto-detect the utilities automatically, no config needed.

> Thanks for the help @ibhagwan!

YW @folke! Ty for your never ending contributions everywhere ☺️🙏

**Comment by hnsylzg** [comment]
I also want to ask which one is recommended between fd and rg, and why find file in linux will prevent previewing binary files, and will not organize under windows

**Comment by hnsylzg** [comment]
Thank you very much

**Comment by ibhagwan** [comment]
> I also want to ask which one is recommended between fd and rg, and why find file in linux will prevent previewing binary files, and will not organize under windows

Both are great to have but if you have to choose one, go with `rg`, since windows doesn’t have `grep` it’s a must for the grep pickers and it can also list files with `rg --files` (automatic).

The reason binaries won’t be recognized on Windows is because `perl` or `file` utilities are used to determine if a file is binary, both of which don’t exist on Windows.

**Comment by ibhagwan** [comment]
Another important note for Windows, exclude neovim fzf and rg from windows defender and you’ll get a speed boost.

**Comment by hnsylzg** [comment]
I added e:\msys64\usr\bin to the path and it worked. Thank you very much
