### ISSUE TITLE
bug: UI freeze when restoring from multiple swap files

### ISSUE THREAD

**Issue by moetayuko** [LazyVim/LazyVim#5061]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.2

### Operating system/version

Arch

### Describe the bug

nvim gui freezes when attempting to choose the swap file to recover from if there are multiple candidates

### Steps To Reproduce

1. edit a file named `foo`, make some random modifications, and then kill nvim process to generate a swap file
2. repeat once to generate the second swap file
3. start nvim, then `:e foo`
4. when prompted to take action for the swap file, press `r`
5. nvim tui freezes until pressing Esc

### Expected Behavior

be able to select the swap file

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
Can't reproduce. You're probably using `nvim-notify`?
That doesn't work well with `ui_attach` and I've removed hacks that trigger redraws.

Use `snacks.notifier` instead or fix the issue in `nvim-notify`

**Comment by dpetka2001** [comment]
Can't repro. Screencast following with steps from OP

https://github.com/user-attachments/assets/54067bb9-7ced-4a38-a5a6-47f3745084a5

**Comment by moetayuko** [comment]
> Can't reproduce. You're probably using `nvim-notify`? That doesn't work well with `ui_attach` and I've removed hacks that trigger redraws.
> 
> Use `snacks.notifier` instead or fix the issue in `nvim-notify`

no I'm using the default one provided by LazyVim, that is snacks.notifier, please check the following recording..

[![asciicast](https://asciinema.org/a/EH2DZk6671RbolBpOiwUnaruB.svg)](https://asciinema.org/a/EH2DZk6671RbolBpOiwUnaruB)

**Comment by moetayuko** [comment]
@folke @dpetka2001 could you double-check if the issue persists following my steps shown in the cast?

**Comment by dpetka2001** [comment]
I did double-check and unfortunately I can't reproduce it. I also took a video of the steps I followed in my previous comment. I believe they are the same steps as you described. I did it 4-5 times but nothing happened to me. Neovim continued to work like it also shows in my video.

**Comment by moetayuko** [comment]
> I did double-check and unfortunately I can't reproduce it. I also took a video of the steps I followed in my previous comment. I believe they are the same steps as you described. I did it 4-5 times but nothing happened to me. Neovim continued to work like it also shows in my video.

I reviewed your video again. As shown at 2:00, there are three swap files for test.lua. Then, you are prompted to take action for the swap file at 2:08. Did you press R here? You should be asked to enter number of swap file to use, but it didn't ask in the video.

**Comment by dpetka2001** [comment]
Yes, I always pressed `R` to recover. But it indeed did not prompt me to choose which one of the 3 swap files. It just chose which one to recover on its own. I don't know if that's expected behavior or not since I've never run into this issue before and never had to recover a file. I just tried to reproduce your steps described in your first post but couldn't reproduce it. 

I just tried with `nvim --clean` and it has the same behavior when pressing `R` to recover. If you want to choose from a swap file, then you have to manually enter the command `:recover` and then it shows you which available swap files exist and asks you to press a number to choose one. With `nvim --clean` it indeed shows you a menu and you are able to choose from a swap file, but default LazyVim does freeze when you enter the command `:recover`. No idea why, but it might have something to do with Snacks.notifier and in that case it would be better to create an issue at Snacks repo.

**Comment by moetayuko** [comment]
> Yes, I always pressed `R` to recover. But it indeed did not prompt me to choose which one of the 3 swap files. It just chose which one to recover on its own. I don't know if that's expected behavior or not

I guess you set some options to disable the choice. Using the config in `Repro` of OP should let you choose the swap file.
> 
> but default LazyVim does freeze when you enter the command `:recover`.

exactly, `:recover` behaves the same as my original report

**Comment by dpetka2001** [comment]
Even with repro from OP I still get same behavior with `R`. It just chooses the `.swp` file on its own and Neovim doesn't freeze. Only when I do `:recover` it freezes.

**Comment by moetayuko** [comment]
> Even with repro from OP I still get same behavior with `R`. It just chooses the `.swp` file on its own and Neovim doesn't freeze. Only when I do `:recover` it freezes.

alright. regardless of the default behavior, we've confirmed that a freeze happens when choosing from multiple swap files

**Comment by dpetka2001** [comment]
Yes, but that's probably due to Snacks.notifier if I would make a guess. So, you should probably open an issue at Snacks repo instead.

**Comment by folke** [comment]
Probably noice, so open an issue there.
Likely not possible to fix. Will need to look into it

**Comment by dpetka2001** [comment]
Can confirm that with `Noice` disabled the command `:recover` doesn't cause any freezes.

**Comment by moetayuko** [comment]
I found an old issue describing the same bug https://github.com/folke/noice.nvim/issues/262
