### ISSUE TITLE
bug: Blink needs curl (LazyVim 14)

### ISSUE THREAD

**Issue by uralets** [LazyVim/LazyVim#5064]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.11.0-dev

### Operating system/version

Ubuntu 24.04 Noble

### Describe the bug

Blink assumes you have CURL installed and when you don't the error Lazy spews isn't really informative.

Probably better to mention this in the News or the Changelog or somewhere.

### Steps To Reproduce

Open a file with nvim and Lazy 14 while not having curl in your $PATH

### Expected Behavior

A message clearly stating that CURL is required.

**Comment by dpetka2001** [comment]
That's mentioned in the [blink's repo](https://github.com/Saghen/blink.cmp?tab=readme-ov-file#requirements) already. 

I don't believe LazyVim should mention every single plugin's requirements when it's already mentioned in their github repo in my personal opinion.

**Comment by folke** [comment]
True, however, it would be nice if blink could implement something like in mason for windows, with `iwr`:
https://github.com/williamboman/mason.nvim/blob/main/lua/mason-core/fetch.lua

**Comment by uralets** [comment]
That's not an unexpected reply.

What I believe is that upgrading (automatic too) of Lazy shouldn't suddenly render a perfectly working setup broken.

Also I only propose *mentioning explicitly* that you need a dependency. Nothing else. An informative error message would've worked for me.
As of now I had to traverse the trace back and guess what was going wrong.

**Comment by folke** [comment]
Agree, will add to the docs and to the health checks

**Comment by folke** [comment]
Added to the docs. The new website will be auto-generated in an hour or so...
