### ISSUE TITLE
bug: mini.indentscope not installing nvim-blankline.nvim

### ISSUE THREAD

**Issue by Redoxahmii** [LazyVim/LazyVim#5068]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

Arch Linux

### Describe the bug

Enabling `mini.indentscope` indicates that it should install `indent-blankline.nvim` as dependency but that does not get installed.
This breaks the `mini-indentscope` as it does not work with `snacks.indent`.
If you enable the `indent-blankline.nvim` extra from `LazyExtras` then it properly animates and works again.

### Steps To Reproduce

1. Enable `mini.indentscope` in `LazyExtras`
2. Check if indents are being animated or not.

### Expected Behavior

Should install `indent-blankline.nvim` so it can work.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
	spec = {
		{ "LazyVim/LazyVim", import = "lazyvim.plugins" },
		{ import = "lazyvim.plugins.extras.ui.mini-indentscope" },
	},
})
```

**Comment by folke** [comment]
How is this a bug? That;s two different extras, that you can install independently

**Comment by Redoxahmii** [comment]
`mini.indentscope` does not work with snacks `indent` lines and should install `indent-blankline.nvim` when enabled.
That's the bug.
Did i miss something ?

**Comment by folke** [comment]
Why? You can use `mini.indentscope` without  `indent-blankline`. You can also use it with `snacks.indent`.
Some people just want to see scopes without indent guides.

**Comment by Redoxahmii** [comment]
This is the default indents without `mini.indentscope` which are already broken :

![Image](https://github.com/user-attachments/assets/8b868be7-e672-4ddc-93ea-50818948417f)

This is after i enable `mini.indentscope`:
![Image](https://github.com/user-attachments/assets/6439aae8-2da9-4823-92bd-58b07373330e)

It shows nothing.

And this is if i disable `snacks.indent` :
![Image](https://github.com/user-attachments/assets/22d45393-749a-4dd4-8fab-60c84df991e5)


Rest you can tell.

**Comment by folke** [comment]
Just updated snacks to show indent guides at a lower priority.

**Comment by Redoxahmii** [comment]
It works now when using with `mini.indentscope`.

Is this the intended experience of `snacks.indent` itself or is this something that can be changed to similar to `mini.indentscope` because the default behavior does not make any sense:

![Image](https://github.com/user-attachments/assets/9afd0708-e679-45f5-af2f-5d1761f65533)

This is how it looks with `mini.indentscope` as it actually highlights the correct indent:
![Image](https://github.com/user-attachments/assets/921fa658-805c-4b1d-aa2c-10931c29fad7)

**Comment by folke** [comment]
For me it all looks as it should. 
snacks indent uses both treesitter and indents to detect the scope.
Is it possible that your file is not correctly formatted and that the ending bracket of dashboard is too much to the left?

You can also disable treesitter scopes with:

```lua
      scope = {
        treesitter = {
          enabled = false,
        },
      },
```

**Comment by Redoxahmii** [comment]
Disabling `treesitter` option makes it somewhat closer to how it is in `mini.indentscope` and the formatting is correct.

The only remaining thing i would ask is if i can change behavior when on an empty char as it tends to highlight the scope forward whereas for `mini.indentscope` it would highlight the actual indent your cursor is on in the empty chars as well:

![Image](https://github.com/user-attachments/assets/7271c1d8-806f-4bde-8bc2-c6aaee9a219a)

![Image](https://github.com/user-attachments/assets/e36bd5d1-cadb-42b0-b680-152ea091e164)

**Comment by dpetka2001** [comment]
I believe that's because `mini.indentscope` calculates the scope based on the cursor column position, whereas `snacks.indent` computes it for each line. There's currently an open feature request about such feature.

**Comment by Redoxahmii** [comment]
Thanks for informing @dpetka2001.
I'll wait for it and hopefully it gets considered at least for now we can rely on `mini.indentscope` as `snacks.indent` needs a little more time.

**Comment by folke** [comment]
fyi: treesitter and indent scopes are now calculated based on the cursor position by default.

**Comment by Redoxahmii** [comment]
Thank you for your work just updated!

**Comment by folke** [comment]
If you'd still see that weird scope with treesitter enabled, would be great if you could share a minimal lua file that exhibits that behavior.

**Comment by Redoxahmii** [comment]
I tried to reproduce it but seems to have ironed out itself.
I tested with `scope.treesitter` to `true` and it does not exhibit that behavior anymore.
I also did test with `scope.cursor` to `false` and and treesitter enabled and it doesn't cause issues in that state too.

**Comment by Redoxahmii** [comment]
@folke sorry to inform again but using it with treesitter while in the file i sent above it is not causing issues but in a different lua file it is exhibiting that same behavior again and the cursor column does not seem to be functioning correctly:
![Image](https://github.com/user-attachments/assets/9e834b80-831b-4361-a0f0-26cd4f85ce17)

```lua
return {
	{
		"echasnovski/mini.hipatterns",
		opts = function(_, opts)
			local hi = require("mini.hipatterns")

			opts.highlighters = opts.highlighters or {}

			opts.highlighters = vim.tbl_extend("keep", opts.highlighters or {}, {
				hex_color = hi.gen_highlighter.hex_color({ priority = 2000 }),

				hl_group = {
					pattern = function(buf)
						return vim.api.nvim_buf_get_name(buf):find("lua/" .. M.module)
							and '^%s*%[?"?()[%w%.@]+()"?%]?%s*='
					end,
					group = function(buf, match)
						local group = M.hl_group(match, buf)
						if group then
							if M.cache[group] == nil then
								M.cache[group] = false
								local hl = vim.api.nvim_get_hl(0, { name = group, link = false, create = false })
								if not vim.tbl_isempty(hl) then
									hl.fg = hl.fg or vim.api.nvim_get_hl(0, { name = "Normal", link = false }).fg
									M.cache[group] = true
									vim.api.nvim_set_hl(0, group .. "Dev", hl)
								end
							end
							return M.cache[group] and group .. "Dev" or nil
						end
					end,
					extmark_opts = { priority = 2000 },
				},

				hl_color = {
					pattern = {
						"%f[%w]()c%.[%w_%.]+()%f[%W]",
						"%f[%w]()colors%.[%w_%.]+()%f[%W]",
						"%f[%w]()vim%.g%.terminal_color_%d+()%f[%W]",
					},
					group = function(_, match)
						local parts = vim.split(match, ".", { plain = true })
						local color = vim.tbl_get(M.globals, unpack(parts))
						return type(color) == "string"
							and require("mini.hipatterns").compute_hex_color_group(color, "fg")
					end,
					extmark_opts = function(_, _, data)
						return {
							virt_text = { { "⬤ ", data.hl_group } },
							virt_text_pos = "inline",
							priority = 2000,
						}
					end,
				},
			})
		end,
	},
}
```

**Comment by folke** [comment]
That's because the treesitter indents expand to blocks. See the docs for treesitter.
You can disable those with `opts.indent.scope.treesitter.blocks = false`.

The treesitter node will always expand to the nearest block type, if present.
From there it will follow cursor settings etc.

That's probably what you expect.

**Comment by folke** [comment]
Maybe I should disable treesitter blocks by default.
I personally also don't use them.
Just added that as a default, mainly because that;s how indent-blankline works...

Maybe treesitter blocks should be opt-int instead?

@dpetka2001 what do you think?

**Comment by Redoxahmii** [comment]
I've set `opts.indent.scope.treesitter.enabled = false` and it still does the same thing with cursor enabled.
Disabling treesitter completely does not seem to remedy the behavior.
But if i disable `treesitter.blocks` it works fine.

is disabling `opts.indent.scope.treesitter` not also affect the blocks identing or does the block method needs to be explicitly provided even if treesitter is disabled.

**Comment by folke** [comment]
Right, I see. It's because you;re using tabs. Will fix

**Comment by Redoxahmii** [comment]
![Image](https://github.com/user-attachments/assets/6b0add5e-7e12-4661-a7f7-6725055bbafc)

With treesitter disabled it still defaults to using blocks indent.
But if i enable treesitter and then set blocks to `false` it works correctly.

![Image](https://github.com/user-attachments/assets/2313d0db-c9fb-457d-ab46-b020667a8b57)

Should probably default to blocks indent being disabled when setting `scope.treesitter.enabled = false`.

**Comment by folke** [comment]
indent based scopes don't use treesitter blocks.
The problem was that indent based scopes used the wrong start indent when `cursor=true`.
Fixed now.
I also recommend using the treesitter scopes, since they will be based on the AST, and as such more correct.
You can even remove all formatting and scopes would still be detected properly.

**Comment by dpetka2001** [comment]
I've always had `indent.scope.treesitter.enabled = false` since the beginning, since it had more similar behavior to the old `indent-blankline`+`mini.indentscope`. I haven't updated yet local snacks repo and haven't looked into latest changes, so will do that gradually throughout the day.

**Comment by Redoxahmii** [comment]
Setting `indent.scope.treesitter.enabled = false` should be the default behavior in my opinion as that is something people are not only used to but mimics the same behavior as most editors.
While treesitter scopes should be more accurate due to AST they seem out of place at least when using cursor columns for rendering.

**Comment by Redoxahmii** [comment]
Just checked seems to work fine now by disabling `indent.scope.treesitter.enabled = false` with cursor columns.

**Comment by folke** [comment]
you mean `indent.scope.treesitter.blocks = false`.
having treesitter enabled is till better.

**Comment by folke** [comment]
Allright, just updated the default to disable blocks.

**Comment by Redoxahmii** [comment]
Sorry mistyped it

**Comment by Redoxahmii** [comment]
Cursor column render behavior seem to be still struggling with treesitter enabled.
![Image](https://github.com/user-attachments/assets/b8740b12-a8ba-4b41-ac6a-984b12f4a9f4)

Cursor column works correctly only if i disable treesitter as well.

**Comment by dpetka2001** [comment]
Yes, I also noticed that on the opening curly bracket when it's on its own on a separate line. I just keep treesitter disabled myself. I'm not that knowledgeable about Treesitter and probably don't use it to its full advantage, so I'm just going with what visually seems more close to my preferences myself.
