### ISSUE TITLE
bug: `Snacks.dashboard` does not respect LazyVim's picker configuration

### ISSUE THREAD

**Issue by PFiS1737** [LazyVim/LazyVim#5070]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.2, Build type: RelWithDebInfo, LuaJIT 2.1.1731601260

### Operating system/version

Linux 6.12.4-arch1-1

### Describe the bug

I enabled `lazyvim.plugins.extras.editor.telescope` to use Telescope instead of fzf. `LazyVim.pick.want()` outputs `telescope` as expected, but it does not work in the Dashboard.

### Steps To Reproduce

1. launch nvim with `repro.lua`
2. press `f` (or other dashboard keys)
3. shows fzf instead of telescope

### Expected Behavior

Should display Telescope's picker instead of fzf.

After reading the source code, I tried adding the following configuration to make it work:
```lua
{
  "folke/snacks.nvim",
  opts = {
    dashboard = {
      preset = {
        pick = LazyVim.pick.open,
      },
    },
  },
},
```
This resolved the issue for other key bindings, but the `f` key still behaves abnormally. When I press f, Telescope's picker appears, but it does not display any entries.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(
  vim.fn.system(
    "curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"
  )
)()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
    { import = "lazyvim.plugins.extras.editor.telescope" },
  },
})
```

**Comment by dpetka2001** [comment]
Can't repro with default LazyVim installation. Probably an issue with your personal config. Screencast of default LazyVim installation following

https://github.com/user-attachments/assets/95faf2f0-13ac-4bb5-a4ad-bcc9965c0bce

**Comment by PFiS1737** [comment]
Strangely, I can no longer reproduce the issue using the method you demonstrated in your video. However, my repro steps still work. You might want to try them: simply run `nvim -u repro.lua`
. It uses the `import` feature of `lazy.nvim` instead of `LazyExtras`.

**Comment by dpetka2001** [comment]
If you use the `import` feature, then you need to set the global variable to the correct value.

**Comment by dpetka2001** [comment]
See here in the [docs](https://www.lazyvim.org/extras/editor/telescope#options).

**Comment by PFiS1737** [comment]
Sorry, I missed this because I found that `vim.g.lazyvim_picker` is only used in `LazyVim.pick.want()`, which dynamically checks whether I enabled the extra and gives the right result.

I’ve added this configuration, but the issue I mentioned above still persists.
> but the `f` key still behaves abnormally. When I press `f`, Telescope's picker appears, but it does not display any entries.

**Comment by dpetka2001** [comment]
When you use the `import` feature, then you have to also define the global variable to your desired preference. That's why using `LazyExtras` is so much more comfortable.

I have no idea about Telescope indexing thing. I don't use Telescope. It seems it has something to do with how the `snacks.dashboard` action is called maybe? Not sure. Better ask at snacks repo about this. 

I believe it's because of [this code](https://github.com/folke/snacks.nvim/blob/a7608b13ea476ecca471cf0900a77b8dd1650d76/lua/snacks/dashboard.lua#L762-L764). Because of `pcall` it waits until the function finishes executing and then returns the results. Seems that telescope shouldn't be called with `pcall`?? Again better ask at snacks repo.

**Comment by PFiS1737** [comment]
Thanks for your response! I agree that this issue should probably be discussed further in Snacks. I’ll look into it more when I have time.

I’ll close this issue since it has served its purpose.

**Comment by dpetka2001** [comment]
@folke Do you have any ideas on this?

**Comment by folke** [comment]
Nope, and that `pcall` really can't get that telescope result.
Not using telescope myself, but with fzf-lua at least, I do get the loading progress.

**Comment by dpetka2001** [comment]
Yes, with fzf-lua i do get results myself as well. But just tried quickly switching to Telescope and when I search through my home directory for example which has a lot of files, then the Telescope window doesn't show the indexing progress. 

I made the following change here in [M.pick](https://github.com/folke/snacks.nvim/blob/0cfd6d783544e913c16ff85b963bf8dad6da5b84/lua/snacks/dashboard.lua#L751-L767). I commented out the telescope part in `try` table and then after the `for` loop I did 
```lua
  local ok, tele = pcall(require, "telescope.builtin")
  if ok then
    tele[cmd == "files" and "find_files" or cmd](opts)()
    return
  end
```
This correctly opens the Telescope picker immediately and shows its indexing process, but I do get an error 
```lua
Error executing vim.schedule lua callback: vim/_editor.lua:0: nvim_exec2(): Vim(lua):E5108: Error executing lua ...23/projects/plugins/snacks.nvim/lua/snacks/dashboard.lua:768: attempt to call a nil value
stack traceback:
	...23/projects/plugins/snacks.nvim/lua/snacks/dashboard.lua:768: in function 'pick'
	[string ":lua"]:1: in main chunk
	[C]: in function 'nvim_exec2'
	vim/_editor.lua: in function <vim/_editor.lua:0>
stack traceback:
	[C]: in function 'nvim_exec2'
	vim/_editor.lua: in function <vim/_editor.lua:0>
```
and it doesn't get me in `insert` mode by default. It gets me to `normal` mode. Apparently that error showing up has some kind of side-effect, but I just wanted to show the different behavior with the Telescope picker. If I use `dashboard.nvim` for example which is configured with `LazyVim.pick` it correctly opens the Telescope picker and also shows the indexing process.

**Comment by folke** [comment]
ok, that;s weird. Will check here

**Comment by folke** [comment]
Super super weird. Even when I change the whole function to:

```lua
function M.pick(cmd, opts)
  vim.schedule(function()
    vim.cmd([[Telescope find_files]])
  end)
end
```

It doesn't seem to work. When I do `:Telescope find_files` manually, it does work.

**Comment by dpetka2001** [comment]
Yes, it only shows results once the indexing process is finished. In my home directory it takes quite some time. In `~/.config/some_directory` it shows instantly.

**Comment by folke** [comment]
I don't understand how doing `:Telescope find_files` is different from doing exactly the same in `vim.schedule`

**Comment by dpetka2001** [comment]
Maybe it has to do with how `action` is executed in the dashboard?

**Comment by dpetka2001** [comment]
I changed in `ui.lua` in `snacks.dashboard` the key to
```lua
{ icon = " ", key = "f", desc = "Find File", action = "<leader><space>" },
```
and it shows immediately the Telescope picker while the indexing process is going on. Maybe indeed it has to do with how `action` is being executed? I'm just guessing here.

**Comment by folke** [comment]
That's what I mean that it's impossible. In a `vim.schedule` it should always work.

**Comment by dpetka2001** [comment]
But the only difference with default Snacks configuration is the way `action` gets executed. When it's executing as a command it doesn't show it. But when it executes as a keymap then it shows it. So maybe something in the way `action` executes as a command conflicts with Telescope. I also saw in the Telescope's spec that in `picker.open` function you just `require("telescope.builtin")` but with fzf-lua in `picker.open` function you `return require("fzf-lua")`.

**Comment by folke** [comment]
If you add the below at the end of your `init.lua` it's the same behavior:

```lua
vim.defer_fn(function()
  vim.cmd([[Telescope find_files]])
end, 1000)
```

Extremely weird. No idea what's causing this.

**Comment by dpetka2001** [comment]
Do you know why the code I mentioned above temporarily works
```lua
 local ok, tele = pcall(require, "telescope.builtin")
  if ok then
    tele[cmd == "files" and "find_files" or cmd](opts)()
    return
  end
```
and shows the indexing process but also throws an error? Does that maybe ring a bell for you as to what might be wrong?

**Comment by folke** [comment]
That code does not work for me...

**Comment by folke** [comment]
Wait, it does work!! But with that weird error indeed!

**Comment by dpetka2001** [comment]
Yes, I don't know what the error indicates unfortunately. And it also does not put you in `insert` mode but in `normal` mode in the Telescope prompt. But maybe that's cause by the error?

**Comment by folke** [comment]
The error is because you added `()`. If I remove that error is gone, but also the indexing.
I don't get it

**Comment by dpetka2001** [comment]
Yes, I first tried without `()` but got the same behavior and then thought maybe `require("telescope.builtin").find_files()` returns some other function and I had to actually call that. I just guessed.

**Comment by folke** [comment]
```lua
function M.pick(cmd, opts)
  vim.cmd([[Telescope find_files]])
  error("test")
end
```

With that `error` it works. If I comment that out, it doesn't

**Comment by dpetka2001** [comment]
I believe it has to do with how `action` in Snacks.dashboard executes the commands. I just swapped for this 
```lua
{ icon = " ", key = "f", desc = "Find File", action = ":lua LazyVim.pick()()" },
```
and it has the same behavior. But this same action in `dashboard.nvim` works correctly. The only difference is the `action` in Snacks.dashboard vs the `action` in dashboard.nvim from the way I see it. `LazyVim.pick()()` definitely works correctly as it was also working correctly in the past. But with Snacks.dashboard `action` it doesn't work correctly. Maybe you should have another look at how `action` executes commands in Snacks.dashboard?

**Comment by dpetka2001** [comment]
@folke I was lucky enough and believe I found where you should look at. [This code here](https://github.com/folke/snacks.nvim/blob/0cfd6d783544e913c16ff85b963bf8dad6da5b84/lua/snacks/dashboard.lua#L289-L299). If you just comment out lines 289 and 299 (so the `vim.schedule` part) then it executes correctly. I don't know if that has any other side-effects though. But hopefully it will lead you to the cause of it.

**Comment by folke** [comment]
Yes, but that should work with `vim.schedule`. For whatever reason it indeed seems that telescope can't be started from `vim.schedule`, which honestly doesn't make any sense.

Must be something to do with their async impl.

**Comment by dpetka2001** [comment]
For what reason did you use `vim.schedule`? I'm sure you must have one but I fail to understand. From what I've looked into `dashboard.nvim` doom theme they also just execute `vim.cmd` directly without scheduling it.

**Comment by folke** [comment]
Yep, just removed that. But still makes zero sense why telescope can't work from a `vim.schedule`...
