### ISSUE TITLE
bug:

### ISSUE THREAD

**Issue by shelper** [LazyVim/LazyVim#5071]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

MacOS 14.1

### Describe the bug

i recently updated my lazyvim, and i got the following strange behavior, i am not 100% sure it is from layzvim or from plugin installed by lazyvim 
but basically the hex number cannot show color for a value below specific threshold after upgrading .

<img width="451" alt="Image" src="https://github.com/user-attachments/assets/2f9b978b-78b5-4251-8592-344214e30d2b" />

### Steps To Reproduce

just put the #12461a and #12471a in any config buffer, one show green bg, one does not 

### Expected Behavior

both shoudl show bg color based on the hex 

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
What are you using to highlight the colors?

**Comment by folke** [comment]
Closing, since LazyVim does not come with a standard plugin that does coloring like that.
You can enable the `mini.hipatterns` extra though
