### ISSUE TITLE
bug: unexpected workspace/didChangeWorkspaceFolders request to the LSP server

### ISSUE THREAD

**Issue by artempyanykh** [LazyVim/LazyVim#5074]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.2

### Operating system/version

MacOS Sequoia 15.1.1

### Describe the bug

This is in relation to a bug report I received from a user of Marksman LSP: https://github.com/artempyanykh/marksman/discussions/377

I don't know if this is a problem with LazyVim's setup or one of its dependencies, but I can reproduce it on out-of-the-box LazyVim and can't with my vanilla nvim-lspconfig setup.

The problem is that neovim sends CWD as part of `workspace/didChangeWorkspaceFolders` request, which is not the right thing to do (at least for marksman) because it makes marksman treat CWD as the root of the project folder and hence recursively scan it for markdown documents. (and it's slow and problematic if CWD happens to be a home dir or some other large directory), e.g.:

```
[DEBUG][2024-12-13 21:13:56] .../vim/lsp/rpc.lua:286	"rpc.send"	{  jsonrpc = "2.0",  method = "workspace/didChangeWorkspaceFolders",  params = {    event = {      added = { {          name = "/Users/<USERNAME>",          uri = "file:///Users/<USERNAME>"        } },      removed = {}    }  }}
```

To avoid bogus root folders marksman has the following in `nvim-lspconfig`: https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/configs/marksman.lua#L10-L14 It also supports single-file mode so there's no need to have a made up root.

For now, I plan to check if the root is bogus when handling the request: https://github.com/artempyanykh/marksman/pull/380 But I'm curious if there's something on LazyVim's side that too.

### Steps To Reproduce

Vanilla LazyVim setup with markdown extras enabled.

1. Create test.md under `$HOME`
2. Open nvim and set debug on `vim.lsp.set_log_level("debug")`
3. Open the file `:e test.md`
4. Check `:LspLog` for `workspace/didChangeWorkspaceFolders` request.

### Expected Behavior

There should be no `workspace/didChangeWorkspaceFolders` request.

**Comment by folke** [comment]
Pretty sure that was due to a bug in lspconfig that has been fixed last night: https://github.com/neovim/nvim-lspconfig/issues/3503

LazyVim does not change any settings related to marksman.

Big fan btw, thank you for the great work you do on marksman!

**Comment by artempyanykh** [comment]
Thanks for the kind words and the quick response @folke!
