### ISSUE TITLE
bug: typescript autocompletion does not work after switching to blink?

### ISSUE THREAD

**Issue by kev0960** [LazyVim/LazyVim#5078]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0

### Operating system/version

Ubuntu 24.04.1 

### Describe the bug

It seems like after the recent lazyvim update, it replaced the completion plugin from the nvim-cmp to the blink. 

Unfortunately, this made the auto-completion drop-down boxes not to show up in the typescript projects. Auto-completions in other languages, such as C++ , Rust are working fine.

Below is the result from the LSPInfo:

```
- Client: `vtsls` (id: 3, bufnr: [10])
  root directory:    ~/bogobogo/server/
  filetypes:         javascript, javascriptreact, javascript.jsx, typescript, typescriptreact, typescript.tsx
  cmd:               ~/.local/share/nvim/mason/bin/vtsls --stdio
  version:           `?` (Failed to get version) Tried:
  `/home/jaebum/.local/share/nvim/mason/bin/vtsls --version`
  `/home/jaebum/.local/share/nvim/mason/bin/vtsls -version`
  `/home/jaebum/.local/share/nvim/mason/bin/vtsls version`
  `/home/jaebum/.local/share/nvim/mason/bin/vtsls --help`
  
  executable:        true
  autostart:         true
```

### Steps To Reproduce

![Image](https://github.com/user-attachments/assets/2f951f6d-6e22-4e0b-b715-7875cec67981)

No boxes show up in typescript (box .ts and .tsx)

### Expected Behavior

![Image](https://github.com/user-attachments/assets/50716e25-38eb-41f9-bf46-24e2f5c03aea)

It works in other languages (e.g. C++)

### Repro

```lua
this is the only config I use for lazyvim. Otherwise I follow the default.

return {
  {
    "neovim/nvim-lspconfig",
    opts = {
      inlay_hints = { enabled = false },
    },
  },
}
```

**Comment by folke** [comment]
Works as it should for me for typescript. Provide a repro if you want me to look at it.

**Comment by zilahir** [comment]
seems like i am having the same problem, after the latest update ts autocomplete, and autosuggest lists are not visible. i am trying to debug this further now.

**Comment by folke** [comment]
That's weird. Do let me know if you find anything.

**Comment by zilahir** [comment]
@folke  hmm, i can't seem to figure out whats wrong. removed my custom `lsp.lua` entirely, and its still not showing up. every other language i tried with it works as expected. something fishy is going on.

**Comment by kev0960** [comment]
@zilahir Yes - I can confirm that disabling htmx-lsp would bring the auto-completion back. Thanks for the suggestion!

**Comment by folke** [comment]
Would be great if you could submit a bug report in the blink repo, since if I understand correctly, a mis behaving lsp server seems to affect others as well?

**Comment by zilahir** [comment]
@folke yep, will do! 🙏
