### ISSUE TITLE
Plans to Add i18n Support to the Docs?

### ISSUE THREAD

**Issue by folke** [LazyVim/LazyVim#508]
### Discussed in https://github.com/LazyVim/LazyVim/discussions/506

<div type='discussions-op-text'>

<sup>Originally posted by **jcha0713** March 31, 2023</sup>
LazyVim is an excellent starting point for beginners using Neovim, and I would like to introduce this project to more (Korean) users. It would be really helpful to have i18n support in the documentation, and I would be more than happy to contribute by translating it into Korean. Is this something that could be considered?</div>

**Comment by folke** [comment]
More info at https://docusaurus.io/docs/i18n/introduction

**Comment by Coien-rr** [comment]
Maybe the Chinese version is also a great project ! ! ! 👏

**Comment by cStralpt** [comment]
and maybe indonesian version too! :)

**Comment by LionChenA** [comment]
If there is a Chinese one, please let me know. I'm willing to contribute.

**Comment by thyeun** [comment]
For Mandarin/Chinese and Malay/Indonesia, i can contribute too.

**Comment by spider8** [comment]
I would like to contribute to the Brazilian Portuguese version as well.

**Comment by baker221** [comment]
I can contribute to Chinese-Simplified, too.

**Comment by lghkv** [comment]
也许中文版也是一个伟大的项目

**Comment by samusz** [comment]
I'd be happy to help out for french.

**Comment by samusz** [comment]
> More info at [docusaurus.io/docs/i18n/introduction](https://docusaurus.io/docs/i18n/introduction)

Is this for the website or in neovim ?

**Comment by cattynip** [comment]
@samusz, No. That is the website that introduces the new feature regarding supporting different languages in the framework called [Docusaurus](https://docusaurus.io/), which helps developers create their documentation very quickly. He used it for the LazyVim website.

**Comment by cattynip** [comment]
@samusz, if you want to contribute to this repository, then you may want to add `README-FR.md` translate all sentences, and make a pull request.

**Comment by samusz** [comment]
Thanks for the shout-out @cattynip , I will propose a translation soon.
