### ISSUE TITLE
feature: add keybinding for vim.snippet.stop()

### ISSUE THREAD

**Issue by binhtran432k** [LazyVim/LazyVim#5083]
### Did you check the docs?

- [x] I have read all the LazyVim docs
- [x] This is not a request for a new or existing extra (see above)

### Is your feature request related to a problem? Please describe.

The current behavior of built-in snippets lacks of support for automatically stopping based on user behavior. This results in snippets highlights persisting which can lead to confusion during editing

### Describe the solution you'd like

Extend the behavior of the `<Esc>` or `<Cr>`

### Describe alternatives you've considered

Extend the behavior of the Redraw keybinding `<leader>ur`

**Comment by folke** [comment]
Good idea. Has been annoying me as well at times.
