### ISSUE TITLE
I'm on vacation from April 1 - April 15 🌴

### ISSUE THREAD

**Issue by folke** [LazyVim/LazyVim#509]
I won't be able to respond to issues/discussions while I'm gone. See you all in two weeks!

**Comment by amaanq** [comment]
Enjoy!

**Comment by WillEhrendreich** [comment]
have fun, thanks for all the work you do for us all, you deserve a great break!

**Comment by ca-mantis-shrimp** [comment]
Have a great break! Can't thank you enough for everything you do
