### ISSUE TITLE
bug: No notification about updates for plugins

### ISSUE THREAD

**Issue by pkropachev** [LazyVim/LazyVim#5092]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.2

### Operating system/version

Ubuntu 20.04

### Describe the bug

No notification about updates for plugins.

Before update to v14, notification about updates for plugins appeared during open neovim. But now I don't see such notification. I don't know how to troubleshoot it.

### Steps To Reproduce

1. There are updates for plugins.

![Image](https://github.com/user-attachments/assets/a9d74eaa-ab01-4bca-80c8-625a4c86d30d)

2. Open neovim.
### Expected Behavior

Notification about new updates should be displayed.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
It seems that [this commit](https://github.com/LazyVim/starter/commit/cb6349c8ae922d1c5745574f4d17b44f2731d451) disabled the notification by default in the LazyVim starter template. So, just set `checker.notify = true` in your `~/.config/nvim/lua/config/lazy.lua` file.

**Comment by pkropachev** [comment]
Thank you @dpetka2001!
