### ISSUE TITLE
feature: Add timeout config for `vim.lsp.buf.format`

### ISSUE THREAD

**Issue by kiooss** [LazyVim/LazyVim#51]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Some formatters may take more time than the default timeout_ms (1000 ms).

### Describe the solution you'd like

Add an option to LazyVim and apply it when calling `vim.lsp.buf.format`?

### Describe alternatives you've considered

The alternative solution maybe let user override `vim.lsp.buf.format`  in their own config.

**Comment by folke** [comment]
You can now override formatting options with:

```lua
  {
    "neovim/nvim-lspconfig",
    opts = {
       format = { timeout_ms = 1000 } 
    }
  }
```

**Comment by dankelley** [comment]
Re https://github.com/LazyVim/LazyVim/issues/51#issuecomment-1382429411, where should I put that material?  I tried creating `.config/nvim/lua/plugins/formatter.lua` with content as below, but it still times out.  (By contrast, when I reformat with lunarvim and the same 60,000 millisecond limit, it finishes with no complaint on a fairly complex R script.)

```lua
return {
    -- formatting time limit
    {
        "neovim/nvim-lspconfig",
        opts = {
            format = { timeout_ms = 60000 },
        },
    },
}
```

**Comment by dpetka2001** [comment]
I don't believe that's relevant any more, since LazyVim now uses `conform.nvim` for formatting. Take a look at the options available in the [docs](https://www.lazyvim.org/plugins/formatting#conformnvim) for how to configure the timeout.

**Comment by dankelley** [comment]
Thanks very much, @dpetka2001.  I'm new to lazyvim, so it took me a moment to figure out what to set.  In case anybody else runs across this later, the below shows the filename I created, and its contents.  With best regards, Dan.

```lua
cat ~/.config/nvim/lua/plugins/formatter.lua
return {
    -- formatting time limit
    {
        --"neovim/nvim-lspconfig",
        "stevearc/conform.nvim",
        opts = {
            format = { timeout_ms = 60000 },
        },
    },
}
```

**Comment by camin-mccluskey** [comment]
Thanks @dankelley, that seems to do the trick. Incase anyone else is struggling with this, the `opts` field name has changed to `default_format_opts` (instead place of `format`)
