### ISSUE TITLE
bug: codeium request failed when renaming a function

### ISSUE THREAD

**Issue by jacquesg** [LazyVim/LazyVim#5100]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

MacOS

### Describe the bug

When renaming a function using `<leader>cr` the completion engines seems to provide suggestions. The screenshot below show that codeium is invoked.

I suspect, no completions should be provided when renaming a symbol.

<img width="1858" alt="Image" src="https://github.com/user-attachments/assets/05b59e86-5b65-432c-a17e-178e17400b10" />

### Steps To Reproduce

1. Activate codeium
2. Rename a function (I've reproduced this with `vtsls`)
3. Observe the error messages.

### Expected Behavior

No suggestions should be provided, nor should it error.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by jacquesg** [comment]
I see, the weird thing is, this did not happen with v13, its new in v14.

**Comment by folke** [comment]
that's because `vim.ui.input` is now `snacks.input` which has lots of advantages.
You can disable it if you want.

**Comment by jacquesg** [comment]
Ok, not 100% sure this is only codeium, see below:

Completions are triggered here from some other source.

<img width="1227" alt="Image" src="https://github.com/user-attachments/assets/9b6538c0-de60-41ef-b72d-e1d6a1a3371e" />

**Comment by folke** [comment]
right, will disable completion in the dialog

**Comment by folke** [comment]
done

**Comment by jacquesg** [comment]
Thank you, sure you pushed? :)

**Comment by folke** [comment]
Yep, the changes are in `snacks.nvim`.

Ah, but you'll need a new release of blink.cmp that includes my PR https://github.com/Saghen/blink.cmp/pull/556

If you want to use the main blink branch and have a working rust install, you can add the below to your `options.lua`:

`vim.g.lazyvim_blink_main = true`

But better to wait for a new blink release.

**Comment by jacquesg** [comment]
Ah, makes sense. Thank you for the heads up. Really appreciate your good work!
