### ISSUE TITLE
bug: scrolling down at almost bottom scrolls window up but cursor stays the same

### ISSUE THREAD

**Issue by banjo** [LazyVim/LazyVim#5103]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0

### Operating system/version

MacOS 15.1.1

### Describe the bug

Since updating to v14 the default setting for the scroll with `ctrl+d` and `ctrl+u` has been messing with me. Not sure if this is the correct forum, if I perhaps should have opened a discussion or opened a ticket in the snacks plugin instead, but as this was the default behavior for me since updating, I figured I'll add it here.

Here is a GIF showing the issue, what I do is basically two things:
1. `ctrl+d`
2. `ctrl+u`
![Image](https://github.com/user-attachments/assets/78d0f619-5caf-439c-af74-79402ed91c0a)

As you can see, on the second press. The cursor remains but the window view scrolls down. 

### Steps To Reproduce

1. Default settings for scroll/animation (have not touched those)
2. Go 3-4 lines above the bottom and press `ctrl+u` once to get in position
3. `ctrl+d` to go down again
4. When pressing `ctrl+u` it still stays on the same position

### Expected Behavior

It should jump up the expected height for `ctrl+u`

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
    { import = "lazyvim.plugins.extras.coding.mini-surround" },
    { import = "lazyvim.plugins.extras.lang.typescript" },
    { import = "lazyvim.plugins.extras.lang.clangd" },
    { import = "lazyvim.plugins.extras.lang.tailwind" },
    { import = "lazyvim.plugins.extras.lang.json" },
    { import = "lazyvim.plugins.extras.lang.yaml" },
    { import = "lazyvim.plugins.extras.lang.go" },
    { import = "lazyvim.plugins.extras.lang.git" },
    { import = "lazyvim.plugins.extras.lang.python" },
    { import = "lazyvim.plugins.extras.lang.astro" },
    { import = "lazyvim.plugins.extras.lang.docker" },
    { import = "lazyvim.plugins.extras.lang.prisma" },
    { import = "lazyvim.plugins.extras.editor.telescope" },
    { import = "lazyvim.plugins.extras.editor.illuminate" },
    { import = "lazyvim.plugins.extras.editor.harpoon2" },
    { import = "lazyvim.plugins.extras.ai.copilot-chat" },
    { import = "lazyvim.plugins.extras.formatting.prettier" },
    { import = "lazyvim.plugins.extras.linting.eslint" },
    { import = "lazyvim.plugins.extras.util.dot" },
    { import = "lazyvim.plugins.extras.vscode" },
    { import = "lazyvim.plugins.extras.ai.copilot" },
    { import = "lazyvim.plugins.extras.test.core" },
    { import = "lazyvim.plugins.extras.dap.core" },
    { import = "lazyvim.plugins.extras.editor.overseer" },
    -- import/override with your plugins
    { import = "plugins" },

  },
})
```

**Comment by folke** [comment]
Sorry, but I've been looking at your screencast and your instructions, but I still don't get it.
You;re also mouse scrolling at some point.
What is wrong here?
Also, if you disable animations `<leader>ua`. Do you see anything different?
For me it behaves exactly the same.

**Comment by dpetka2001** [comment]
To me it looks like at the last step `zz` is being pressed instead. Are you sure you don't have some custom mapping or autocommand to center the screen?

**Comment by banjo** [comment]
Yeah sorry about the mouse scroll, tried to focus my terminal after started the recording.

Once I disabled the animations it started working as normal, I can try to show you the differences here in gifs, this is without animations, I just press `ctrl-u` and `ctrl-d` continuesly, and it is very smooth.
![Image](https://github.com/user-attachments/assets/cf064e6a-a93e-4c34-a5f4-9b95c71294b4)

Here I am trying to do exactly the same thing with animations, but it does not work the same as the gif above.
Whenever I have pressed `ctrl+d` to go down, it works. But when I press `ctrl+u` the window just moves down but the cursor stays on the same place. I have to press `ctrl+u` again to go up. I try to do it repeadetly in this gif.

![Image](https://github.com/user-attachments/assets/97e0bfb5-a0b4-4760-b0f4-6219b34dda28)

Sorry if it might not be the best description but I do exactly the same thing on the two gifs here (but on the second one, with animations, I have to press `ctrl+u` to times because the first time it just scrolls down).

**Comment by folke** [comment]
That;s not what's happens for me. For me without animations it's exactly like your first screencast.
did you change any relevant settings like `scrolloff`? Or remapped things like `G` to `Gzz` or anything like that?
I really need more info, since I can't reproduce this.

**Comment by folke** [comment]
You probably have `scrolloff=99` or another high value?

**Comment by banjo** [comment]
I found the mistake, apparently I have remapped the scrolling a long time ago and totally forgot about that. Sorry to have opened a ticket and thank you for the quick answer. 

```
vim.keymap.set("n", "<C-u>", "<C-u>zz", { desc = "scroll up and center" })
vim.keymap.set("n", "<C-d>", "<C-d>zz", { desc = "scroll down and center" })
```

**Comment by folke** [comment]
This might be relevant in your case. It's a reply to a comment on Reddit.
I assume the same applies to your keymaps, so unfortunately not possible to fix.

---

I looked into this and it's not really something that's possible to fix.

What happens when you do `Gzz`, is that Neovim will do the `G` first. That will instantly jump to the bottom and trigger `WinScrolled`.

Snacks then sees a big jump, so quicly resets your position as it was before your jump and starts animating to the bottom.

You still have `zz` in typeahead and that then no longers triggers, because the view has been restored in the meantime.

There's no way for me to know that `zz` happened.

As far as `WinScrolled` is concerned it didn't happen at all.

**Comment by banjo** [comment]
I see. Seems reasonable, I'll disable that keymap for now to test out the animations for a while.

Thank you very much, appreciate the help.
