### ISSUE TITLE
bug: lazygit is shake

### ISSUE THREAD

**Issue by CnsMaple** [LazyVim/LazyVim#5107]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

win11 pwsh

### Describe the bug

https://github.com/user-attachments/assets/b3f1b505-c50d-42b2-bf5f-e732d0387a3d

### Steps To Reproduce

see video

### Expected Behavior

see video

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by shouyierban** [comment]
everything changed, crazy!

**Comment by CnsMaple** [comment]
sorry, this is heirline issues, disable snacks_terminal on the winbar. Can solve it
