### ISSUE TITLE
After updating [14.4.0], the following error message often appears.

### ISSUE THREAD

**Issue by whxcode** [LazyVim/LazyVim#5108]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0

### Operating system/version

Ubuntu 22.04.3 LTS on Windows 10 x86_64

### Describe the bug

When I use <leader><leader> to search for files, the following error occurs.

![Image](https://github.com/user-attachments/assets/c3aa4bc3-b960-4168-b9b4-8d26e8d3da92)

This is my plugin list.
![Image](https://github.com/user-attachments/assets/168d45f7-3066-4468-90b7-deb84804e1ff)

### Steps To Reproduce

Open nvim and use <leader><leader> to search for files

### Expected Behavior

You can open this interface

![Image](https://github.com/user-attachments/assets/84517286-17de-4aef-a271-a437e594e788)

### Repro

```lua

```

**Comment by GauthierLi** [comment]
I have familiar issue like yours while typing imports in python script, seems like the issue of cmp:
```python
Error executing vim.schedule lua callback: ...re/nvim/lazy/blink.cmp/lua/blink/cmp/completion/list.lua:81: loop or previous error loading module 'blink.cmp.fuzzy'
stack traceback:
	[C]: in function 'require'
	...re/nvim/lazy/blink.cmp/lua/blink/cmp/completion/list.lua:81: in function 'fuzzy'
	...re/nvim/lazy/blink.cmp/lua/blink/cmp/completion/list.lua:68: in function 'show'
	...re/nvim/lazy/blink.cmp/lua/blink/cmp/completion/init.lua:32: in function <...re/nvim/lazy/blink.cmp/lua/blink/cmp/completion/init.lua:29>
```
![Image](https://github.com/user-attachments/assets/f884d8d4-bcdc-4c49-ad0e-f3150cf18a69)

**Comment by folke** [comment]
LazyVim swicthed to blink as default completion engine. You're poriobably using a plugin that expects nvim-cmp instead.

You can switch back to `nvim-cmp` with `:LazyExtras`.

@GauthierLi that is totally unrelated. You don't have `curl` installed, or you enabled `blink.cmp` version=false maunally and didn't built the plugin.
