### ISSUE TITLE
feature: hide messages on small screen

### ISSUE THREAD

**Issue by SimonAM** [LazyVim/LazyVim#511]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

When using a small screen (such as in a tmux split). The nvim-notify message ends up covering alot of screen estate. I would like a default setup for nvim-notify that works better for small screens. 

### Describe the solution you'd like

3. Add opacity. 

### Describe alternatives you've considered

1. Forcing nvim-notify to the bottom of the screen. 
2. Disabling nvim-notify
3. Adding opacity. 

### Additional context

<img width="959" alt="Screenshot 2023-03-31 at 10 32 31" src="https://user-images.githubusercontent.com/3391354/229068789-19bf8fbb-550a-46a0-a983-aa2d3083076d.png">

**Comment by folke** [comment]
You can check the nvim-notify docs to figure out what you want

**Comment by SimonAM** [comment]
[Get the notify-code from lazyvim-docs. 
](https://www.lazyvim.org/plugins/ui#:~:text=%7B%0A%20%20%22rcarriga/nvim,end%2C%0A%7D)

Add the following to opts:
` on_open = function(win)
    vim.api.nvim_win_set_option(win, "winblend", 30)
    vim.api.nvim_win_set_config(win, { zindex = 100 })
  end,`
  
  Enjoy your notify windows not covering your code for 3000 milliseconds.
