### ISSUE TITLE
bug: Profiler activation (`<leader>dpp`) triggers noice.nvim error messages about overwritten functions

### ISSUE THREAD

**Issue by pidgeon777** [LazyVim/LazyVim#5115]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.2

### Operating system/version

Windows 11 Pro 23H2

### Describe the bug

When activating the profiler using `<leader>dpp` in LazyVim, multiple error messages appear related to `noice.nvim` complaining about various functions being overwritten:
```log
   Info  10:48:22 notify.info Profiler Enabled **Profiler**
   Error  10:48:23 notify.error noice.nvim `vim.notify` has been overwritten by another plugin?

Either disable the other plugin or set `config.notify.enabled = false` in your **Noice** config.
  - plugin: noice.nvim
  - file: C:/Users/<USERNAME>/AppData/Local/nvim/.repro_snacksprofiler/data/nvim-data/lazy/noice.nvim/lua/noice/source/notify.lua
  - line: 44
   Error  10:48:23 notify.error noice.nvim `vim.lsp.buf.hover` has been overwritten by another plugin?

Either disable the other plugin or set `config.lsp.hover.enabled = false` in your **Noice** config.
  - plugin: noice.nvim
  - file: C:/Users/<USERNAME>/AppData/Local/nvim/.repro_snacksprofiler/data/nvim-data/lazy/noice.nvim/lua/noice/lsp/init.lua
  - line: 64
   Error  10:48:23 notify.error noice.nvim `vim.lsp.buf.signature_help` has been overwritten by another plugin?

Either disable the other plugin or set `config.lsp.signature.enabled = false` in your **Noice** config.
  - plugin: noice.nvim
  - file: C:/Users/<USERNAME>/AppData/Local/nvim/.repro_snacksprofiler/data/nvim-data/lazy/noice.nvim/lua/noice/lsp/init.lua
  - line: 69
   Error  10:48:23 notify.error noice.nvim `vim.lsp.util.convert_input_to_markdown_lines` has been overwritten by another plugin?

Either disable the other plugin or set `config.lsp.override["vim.lsp.util.convert_input_to_markdown_lines"].enabled = false` in your **Noice** config.
  - plugin: noice.nvim
  - file: C:/Users/<USERNAME>/AppData/Local/nvim/.repro_snacksprofiler/data/nvim-data/lazy/noice.nvim/lua/noice/lsp/override.lua
  - line: 48
   Error  10:48:23 notify.error noice.nvim `vim.lsp.util.stylize_markdown` has been overwritten by another plugin?

Either disable the other plugin or set `config.lsp.override["vim.lsp.util.stylize_markdown"].enabled = false` in your **Noice** config.
  - plugin: noice.nvim
  - file: C:/Users/<USERNAME>/AppData/Local/nvim/.repro_snacksprofiler/data/nvim-data/lazy/noice.nvim/lua/noice/lsp/override.lua
  - line: 55
10:48:19 msg_showcmd gj
```

### Steps To Reproduce

1. Start Neovim with the minimal reproduction config
2. Press `<leader>dpp` to activate the profiler
3. Observe multiple error notifications about overwritten functions

### Expected Behavior

The profiler should activate without showing these error messages.

I was also wondering if, when deactivating the profiler, the original function implementations should be restored.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
Yes, because that's exactly what the instrumentation does.
Nothing that can be done about it.

**Comment by pidgeon777** [comment]
I have a question regarding profiler usage in Neovim.

Consider a LazyVim setup with multiple plugins installed. Initially, when Neovim starts, it's very responsive. However, after several hours of use, it noticeably slows down (for example, when moving the cursor between windows or performing filesystem operations with oil.nvim).

In such a scenario of performance degradation, I'm wondering about the effectiveness of the profiler:

1. Would enabling the profiler with <leader>dpp during the slowdown, performing some operations (like those mentioned above), and then stopping it provide useful information about the cause of the performance issues?

2. Or would I need to start the profiler immediately after Neovim's launch and stop it when the slowdown begins to occur to get meaningful results?

The key question is about the best timing and methodology for using the profiler to diagnose these gradual performance degradations.
