### ISSUE TITLE
bug: cannot navigate buffer/fzf

### ISSUE THREAD

**Issue by jbrodriguez** [LazyVim/LazyVim#5116]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

macos 15.2

### Describe the bug

cannot navigate buffers on the fzf-lua popup
ctrl+n, ctrl+p don't work
up/down arrows don't work either

### Steps To Reproduce

1. <leader>fb
2. try to navigate buffers list with navigation keys

### Expected Behavior

should be able to navigate

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
That all works for me. You're probably overriding the `fzf-lua` spec's `config` function?

**Comment by jbrodriguez** [comment]
i didn't have fzf-lua until i installed the latest lazyvim update 🤷‍♂️

**Comment by dpetka2001** [comment]
I just tried a fresh LazyVim installation and it works correctly for me as well. Screencast following

https://github.com/user-attachments/assets/b5409a97-09af-464a-9e05-7fafe7b99259

Maybe you have some mappings in your personal configuration that cause conflict?

**Comment by jbrodriguez** [comment]
i see, weird because it only fails on the buffers popup, the other ones work, i do have a custom keybind to open buffers, but shouldn't cause it, ill double check
