### ISSUE TITLE
bug: blink is opening in inputs

### ISSUE THREAD

**Issue by vdegenne** [LazyVim/LazyVim#5122]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.2

### Operating system/version

fedora 41

### Describe the bug

From recent update, now blink is opening in inputs,

https://github.com/user-attachments/assets/92ec4b05-630e-4150-bfd2-55469bc9009e

It's annoying especially because pressing <Return> was previously used to accept the input but now <Return> will be intercepted by blink to autocomplete the selected item.

### Steps To Reproduce

rename an object in code
type something in the input

### Expected Behavior

no blink in input

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by vdegenne** [comment]
@dpetka2001 ah.. 😅  Thanks

**Comment by dpetka2001** [comment]
I'm following blink main by the way and I can confirm that it has been fixed.
