### ISSUE TITLE
bug: Disabled fzf-lua and enabled telescope, but telescope config not working

### ISSUE THREAD

**Issue by aniketgm** [LazyVim/LazyVim#5144]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.2 | Build type: Release | LuaJIT 2.1.1713484068 | Run "nvim -V1 -v" for more info

### Operating system/version

Windows 10 

### Describe the bug

FzfLua is great no doubt and I understand why switching to it was made the default in latest update. However, I would still want to stick with Telescope as I have a lot of things configured with and I don't want to go into "Reconfiguration" at the moment, since I'm in middle of big projects and everything was working fine till now.

The issue I'm facing now is that the telescope config does seem to be working. I have disabled fzf-lua plugin and enabled telescope from extras.

### Steps To Reproduce

1. I have disabled fzf-lua
```lua
{ "ibhagwan/fzf-lua", enabled = false },
```
2. Enabled telescope
```lua
{ import = "lazyvim.plugins.extras.editor.telescope" },
```
3. Created `plugins/telescope.lua` and added following telescope config in it. Issue: it's not working
```lua
  {
    "nvim-telescope/telescope.nvim",
    opts = {
      defaults = {
        layout_strategy = "flex",
        layout_config = { height = 0.65, width = 0.9, horizontal = { preview_width = 0.6 }, prompt_position = "top" },
        path_display = { truncate = 3 },
        sorting_strategy = "ascending",
      },
    },
  }
```
4. Open any telescope picker say `:Telescope find_files`. It is still showing this window and not adhering to the height, width config mentioned above:

![Image](https://github.com/user-attachments/assets/e9a836c4-f494-41e7-9783-6a33ef1bcd8f)
 

### Expected Behavior

Just that telescope config should be working, which is not happening currently. I'm getting the default telescope window config. 

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by aniketgm** [comment]
Nevermind.

The issue is resolved with moving the extras entry the `{ import = "plugins" },` entry.

Earlier my `lazy.lua` config was as below:
```lua
....
require("lazy").setup({
  spec = {
    -- add LazyVim and import its plugins
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- import/override with your plugins
    { import = "plugins" },
    -- { import = "lazyvim.plugins.extras.lang.markdown" },
    { import = "lazyvim.plugins.extras.editor.telescope" },
  },
  ....
}
```

So I just moved the entry above 🤦‍♂️
```lua
    { import = "lazyvim.plugins.extras.editor.telescope" },
    { import = "plugins" },
```

**Comment by dpetka2001** [comment]
You can just use the `:LazyExtras` command which automatically does it for you. If you stick with the `import` feature in your `lazy.lua` file, you might stumble upon other Extras with the same behavior. The order of the `import`s **does** matter in your `lazy.lua` config. Your `import = "plugins"` should always come last.

**Comment by kibin** [comment]
@aniketgm thanks, it helped
@dpetka2001 I have no telescope mention in my LazyExtras, was confused when I read about it in the changelog

**Comment by dpetka2001** [comment]
@dpetka2001 If you type the command `:LazyExtras`, then in the UI that will open you have to search for `editor.telescope`. It's there for sure if you have updated LazyVim to version 14.x

**Comment by aniketgm** [comment]
> Your `import = "plugins"` should always come last.

@dpetka2001 Good point and it took me some trial and error to understand this part. I'm not aware much about how lua works. Only enough to write (and sometimes copy-paste) configs.

Fine If I create a PR to mention this part in the docs ? If yes, I'll update the [Extras](https://www.lazyvim.org/extras) page to mentioned something like below at the end of the page:

*There are multiple ways to add. Check each section on how to add it.
NOTE: If you choose to add LazyExtras by way of adding the `import` statement in the `lazy.lua` file, then the `{ import = "plugins" },` line should come last inside the setup config:
```lua
require("lazy").setup({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- <Import LazyExtras of your choice here>
    { import = "plugins" }, -- then finally this line.
  },
})
```

**Comment by dpetka2001** [comment]
@aniketgm Don't ask me for permission to do something. I'm just a simple user like you, who's just been using LazyVim for quite some time.

Regarding what you're suggesting, it is related to [this PR](https://github.com/LazyVim/starter/pull/75). It was there, but got removed because it gave new users incentive to use this feature when they did not fully understand it. So that they would use `LazyExtras` instead. 

You could of course create a new PR for the docs if you like and the maintainer will decide.

**Comment by folke** [comment]
I'll just remove the manual import sections from all the extras docgen.

**Comment by folke** [comment]
done. site is building

**Comment by aniketgm** [comment]
> Don't ask me for permission to do something.

@dpetka2001, Oh that wasn't for you. I missed tagging folke. Lol.

I think PR is not required, he updated the docs. thanks.
