### ISSUE TITLE
bug: unabled to switch to nvim-cmp from blink

### ISSUE THREAD

**Issue by s1n7ax** [LazyVim/LazyVim#5147]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.11.0-dev

### Operating system/version

NixOS

### Describe the bug

when `coding.nvim-cmp` extra is added, nvim-cmp is installed but it's disabled

### Steps To Reproduce

1. add nvim-cmp extra
2. open a lua file
3. run `:Lazy` and look for nvim-cmp

### Expected Behavior

nvim-cmp should be activated but it's disabled along with blink

![Image](https://github.com/user-attachments/assets/8e24045d-4b42-4656-bb8e-7d120c84a305)

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    { import = 'lazyvim.plugins.extras.coding.nvim-cmp' },
  },
})
```

**Comment by dpetka2001** [comment]
If you're using the `import` feature then you also have to define the global variable `vim.g.lazyvim_cmp = "nvim-cmp"` in your `options.lua` file. Otherwise, if you do it from `:LazyExtras` it will resolve itself.

**Comment by s1n7ax** [comment]
@dpetka2001 Worked. Thanks. I don't know if you can update the release notes now but better if you can add that.

**Comment by folke** [comment]
`:LazyExtras` is the way to go always. There's other problems you can get from manually doing the imports (like not using priorities)
