### ISSUE TITLE
bug: Searching with fzf with error: unknown option: --no-scrollbar

### ISSUE THREAD

**Issue by carmosilva-vinicius** [LazyVim/LazyVim#5151]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.2 | Build type: Release | LuaJIT 2.1.1713484068

### Operating system/version

WSL: Ubuntu jammy 22.04 x86_64

### Describe the bug

After update Lazy plugins I am getting the a popup error below when I try to use some search keymap:

`[Fzf-lua] fzf error 2: unknown option: --no-scrollbar`

### Steps To Reproduce

1. Install the latest version of LazyVim
2. Try search using some of the keymaps:
```
<leader>ff
<leader>fg
<leader><leader>
```

### Expected Behavior

I expected a popup windows with search fields and the search results.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
You're using old fzf binary. Either install latest version of fzf or disable that option in your personal config.

**Comment by firubat** [comment]
@dpetka2001 Thanks, was experiencing the same issue and your comment + some search on installation solved it. The `apt` version in ubuntu/debian repos is very old. 

For others encountering this issue: I followed [this guide](https://bytexd.com/how-to-use-fzf-command-line-fuzzy-finder/), but encountered some problems that were solved after first removing the existing fzf. So the steps would be:

1. Remove old fzf if installed, e.g. `sudo apt remove fzf`
2. Clone repo `git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf`
3. Run installation script `~/.fzf/install` 
 You can choose `y` to accept the prompts. The important one is updating the shell configuration.
4. Resource shell config, e.g. `source ~/.bashrc`

**Comment by ibhagwan** [comment]
FYI, this shouldn’t bw an issue post https://github.com/ibhagwan/fzf-lua/pull/1608 as newer options are silently ignored with older binaries.
