### ISSUE TITLE
bug: Failed loading lazyvim.config.keymaps

### ISSUE THREAD

**Issue by pypeaday** [LazyVim/LazyVim#516]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0-dev-152+g1887d8d7d

### Operating system/version

Pop!_OS 22.04 LTS x86_64

### Describe the bug

Whenever I start lazyvim I get an error that lazyvim.config.kepmap couldn't be loaded. It doesn't appear to be affecting my own config, but the notification is certainly 1. troublesome to a new user and 2. an annoyance. I am not well-versed in even getting the output but here's a screenshot of the error: 
![image](https://user-images.githubusercontent.com/32268273/229238347-5ad74862-c467-4d9c-89fa-effaa1bbf599.png)

### Steps To Reproduce

1. Install lazyvim v1.24.0
2. Start lazyvim

### Expected Behavior

I would not expect there to be an error loading an included configuration

**Comment by dpetka2001** [comment]
If this is a new install you might want to delete `.config.nvim`, `.local/share/nvim` and `.local/state/nvim` and clone the starter repo again, as there is a chance there might have been an incomplete clone of the repo. That is assuming you didn't make any customizations to `lazyvim.config.keymaps` yourself.

**Comment by folke** [comment]
The reason you're getting that error is because you're using an older nightly build.

Either install a recent nightly, or install a stable version of Neovim

**Comment by pypeaday** [comment]
Thank you!
