### ISSUE TITLE
bug: nvim-cmp is disabled by default

### ISSUE THREAD

**Issue by muzili** [LazyVim/LazyVim#5160]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

Linux

### Describe the bug

The nvim-cmp plugin is disabled by default, it is reproduced with default configurations as well, here's the reproduce steps following the LazyVim Starter:

### Steps To Reproduce

1. Backup old config 

mv ~/.config/nvim ~/.config/nvim.bak
mv ~/.local/share/nvim ~/.local/share/nvim.bak

2. Clone the starter

git clone https://github.com/LazyVim/starter ~/.config/nvim

3. Comment the return code from lua/plugins/example.lua

diff --git a/lua/plugins/example.lua b/lua/plugins/example.lua
index 17f53d6..0bf5daf 100644
--- a/lua/plugins/example.lua
+++ b/lua/plugins/example.lua
@@ -1,6 +1,6 @@
 -- since this is just an example spec, don't actually load anything here and return an empty spec
 -- stylua: ignore
-if true then return {} end
+-- if true then return {} end

5. Start Neovim!
nvim

nvim-cmp is disable as blow picture shows:

![Image](https://github.com/user-attachments/assets/aa0fc757-583a-4401-8dce-80e3756c473e)

### Expected Behavior

nvim-cmp should be enabled by default.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by krshrimali** [comment]
Hi @muzili - AFAIK, I think this is expected. Starting v14.0.0 release, lazyvim moved to blink.cmp as the default completion engine (and moved nvim-cmp to extras). I think the completion should still work for you, just the engine is now different and possibly faster :)

More details in the release notes here: https://github.com/LazyVim/LazyVim/releases/tag/v14.0.0.

In case you would like to go back to nvim-cmp, you should just be able to install it from `:LazyExtras` command (there's more info here: https://www.lazyvim.org/extras/coding/nvim-cmp).

**Comment by muzili** [comment]
Got it, thanks a log.
