### ISSUE TITLE
bug: Wavy lines warnings in MD files

### ISSUE THREAD

**Issue by tieniu1** [LazyVim/LazyVim#5163]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.1

### Operating system/version

MacOS 13.7.1

### Describe the bug

Unexplained wavy line warning in md file.

### Steps To Reproduce

1. Open any md file
2. Add something
```
# LazyVim

A starter template for [LazyVim](https://github.com/LazyVim/LazyVim).
Refer to the [documentation](https://lazyvim.github.io/installation) to get started.

# LazyVIm

#### 1. 什么是语义化标签

display

If you want to customize rules for a specific directory, you can create .markdownlint-cli2.yaml

```

### Expected Behavior

![Image](https://github.com/user-attachments/assets/f78b7a41-d0b4-4846-a830-a47bdf87e278)

I'm a Neovim newbie and I'm loving LazyVim for helping me get started with Neovim for development work. Thank you for your hard work!

However, I've encountered some wavy lines warnings in my MD files and I'm not sure how to resolve them. I've searched through the issues and couldn't find a similar situation.

I've tried checking the :messages and using K to hover over the text with wavy lines, but they don't provide any information about what's causing the warnings.

I haven't installed any other Markdown extensions, and whether I use extras with { import = "lazyvim.plugins.extras.lang.markdown" } or not, the wavy lines are still present.

I have a .markdownlint-cli2.yaml file in my project root directory, and I've verified that the rules are working through the command line. However, .markdownlint-cli2 shows no errors.

Can someone please help me out? Thanks!

**Comment by Bing0722** [comment]
This is a spelling issue, you can do it like this. 
<img width="313" alt="Image" src="https://github.com/user-attachments/assets/b10816f8-996b-4897-99d9-533f6fadd97b" />

**Comment by dpetka2001** [comment]
Or just remove the autocmd as per the [docs](https://www.lazyvim.org/configuration/general#auto-commands) if you want to remove it as a whole.
