### ISSUE TITLE
Using jc-doyle/cmp-pandoc-references with blink

### ISSUE THREAD

**Issue by manolomartinez** [LazyVim/LazyVim#5172]
### Discussed in https://github.com/LazyVim/LazyVim/discussions/5117

<div type='discussions-op-text'>

<sup>Originally posted by **manolomartinez** December 16, 2024</sup>
Hi, I've been trying to use [cmp-pandoc-references](https://github.com/jc-doyle/cmp-pandoc-references) with the new blink.cmp, so far unsuccessfully. This is the relevant section of a config file called `pandoc.lua`:

    {
        "saghen/blink.compat",
        -- use the latest release, via version = '*', if you also use the latest release for blink.cmp
        optional = true,
        -- make sure to set opts so that lazy.nvim calls blink.compat's setup
        opts = {},
        version = not vim.g.lazyvim_blink_main and "*",
      },
    
      {
        "saghen/blink.cmp",
        dependencies = { "jc-doyle/cmp-pandoc-references" },
        providers = {
          -- create provider
          pandoc_references = {
            name = "pandoc_references", -- IMPORTANT: use the same name as you would for nvim-cmp
            module = "blink.compat.source",
          },
        },
        sources = {
          completion = { "pandoc_references" },
        },
      },
    

I'm a bit fumbling in the dark here, to be honest, but anyway now nvim complains with the following message:

    Failed to source `/home/manolo/.local/share/nvim/lazy/cmp-pandoc-references/after/plugin/cmp-pandoc-references.lua`
    
    vim/_editor.lua:0: /home/manolo/.config/nvim/init.lua..nvim_exec2() called at /home/manolo/.config/nvim/init.lua:0../home/manolo/.local/share/nvim/lazy/cmp-pandoc-references/after/plugin/cmp-pandoc-references.lua: Vim(source):E5113: Error while calling lua chunk: ...pandoc-references/after/plugin/cmp-pandoc-references.lua:1: module 'cmp' not found:
    ^Ino field package.preload['cmp']
    cache_loader: module cmp not found
    cache_loader_lib: module cmp not found
    ^Ino file './cmp.lua'
    ^Ino file '/usr/share/luajit-2.1/cmp.lua'
    ^Ino file '/usr/local/share/lua/5.1/cmp.lua'
    ^Ino file '/usr/local/share/lua/5.1/cmp/init.lua'
    ^Ino file '/usr/share/lua/5.1/cmp.lua'
    ^Ino file '/usr/share/lua/5.1/cmp/init.lua'
    ^Ino file './cmp.so'
    ^Ino file '/usr/local/lib/lua/5.1/cmp.so'
    ^Ino file '/usr/lib/lua/5.1/cmp.so'
    ^Ino file '/usr/local/lib/lua/5.1/loadall.so'
    stack traceback:
    ^I[C]: in function 'require'
    ^I...pandoc-references/after/plugin/cmp-pandoc-references.lua:1: in main chunk
    ^I[C]: in function 'nvim_exec2'
    ^Ivim/_editor.lua: in function 'cmd'
    ^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:510: in function <...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:509>
    ^I[C]: in function 'xpcall'
    ^I.../.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/util.lua:135: in function 'try'
    ^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:509: in function 'source'
    ^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:457: in function 'source_runtime'
    ^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:150: in function 'startup'
    ^I...anolo/.local/share/nvim/lazy/lazy.nvim/lua/lazy/init.lua:112: in function 'setup'
    ^I/home/manolo/.config/nvim/lua/config/lazy.lua:9: in main chunk
    ^I[C]: in function 'require'
    ^I/home/manolo/.config/nvim/init.lua:2: in main chunk
    
    # stacktrace:
      - vim/_editor.lua:0 _in_ **cmd**
      - ~/.config/nvim/lua/config/lazy.lua:9
      - ~/.config/nvim/init.lua:2
  
Any help appreciated! </div>

**Comment by folke** [comment]
Why do you create an issue about this here?
It should be a question the very least. 
And if there's a bug then maybe post it in the blink.compat repo?
I'm not here to fix everyone's issues...

**Comment by manolomartinez** [comment]
Oh, I'm sorry, I did post a question a couple days ago and github offered to make it an issue. Not knowing what the right etiquette was I simply accepted the offering. Apologies.

**Comment by folke** [comment]
Questions are still questions, even when they get unanswered...
I have work enough as it is.
