### ISSUE TITLE
bug:  Gopls not working

### ISSUE THREAD

**Issue by Evgenchu** [LazyVim/LazyVim#5173]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

NixOS

### Describe the bug

I am using LazyVim with the default configuration. For Go what I do is i just enable the extra lang.go and until recently everything was working fine. Today when i opened a go file I saw an error  " The language server is either not installed, missing from PATH, or not executable.".I updated it to the last version, still doesn't work, I don't think it is a LSP error because my other lsp servers are working fine. Any ideas why?

### Steps To Reproduce

1.Install gopls
2.Open a .go file

### Expected Behavior

Gopls works as it should normally.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
Just tried a fresh LazyVim installation from scratch and enabled the Go Extra and seems to be working as expected. Screencast following

https://github.com/user-attachments/assets/2c6eecdc-1f1d-4a20-aa4a-7dfe08c02ca3

Must be something in your personal configuration.

**Comment by dpetka2001** [comment]
I just saw you're using NixOS. I believe Mason is not compatible with NixOS, so you would have to install `gopls` yourself and then add `mason = false` in the `nvim-lspconfig` for `gopls`. There's also a [discussion](https://github.com/LazyVim/LazyVim/discussions/1972) for how to setup LazyVim in NixOS, so you might want to ask there a question for other NixOS users to help you.
