### ISSUE TITLE
bug:

### ISSUE THREAD

**Issue by alex-belost** [LazyVim/LazyVim#5178]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.2 Build type: Release LuaJIT 2.1.1731601260

### Operating system/version

macOS Sequoia 15.1.1 (24B91)

### Describe the bug

There is an issue with Conform and ESLint. The language server works correctly, validating errors, etc., but when I add it to Conform as a formatter, it doesn’t work and throws an error.

- ESLint is installed both locally and globally. 
- I checked its presence in node_modules.
- It was installed via LazyExtras.
- Installed the latest, clean LazyVim package

![Image](https://github.com/user-attachments/assets/e1e9157f-e148-4e2a-9d5e-ffb7d27078c5)

### Steps To Reproduce

1. Install a clean Angular project
2. Install all necessary dependency 
3. Setup eslint as a formatter in conform config

### Expected Behavior

You can use ESLint for formatting.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
How is this a LazyVim issue?
