### ISSUE TITLE
bug: `no-scrollbar` option breaks fzf-lua with skim

### ISSUE THREAD

**Issue by LoricAndre** [LazyVim/LazyVim#5193]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.11.0-dev-1035+g50e63c817

### Operating system/version

`Linux loric-cachy 6.12.3-1-cachyos #1 SMP PREEMPT_DYNAMIC Fri, 06 Dec 2024 16:18:56 +0000 x86_64 GNU/Linux`

### Describe the bug

(disclaimer: I am the main maintainer of [skim](https://github.com/skim-rs/skim))

When using fzf-lua with skim, an error is raised, complaining that `--no-scrollbar` is not a valid argument: 
> ` Fzf-lua fzf error 2: error: unexpected argument '--no-scrollbar' found`

This is expected behavior on skim's end (at least for now), as this option does not exist.
This does mean that the "default" options for fzf-lua do not work when setting the options as such:
```lua
return {
  'ibhagwan/fzf-lua',
  opts = {
    fzf_bin = 'sk',
  },
}

```

Would it be possible to either change this behavior somehow or include a warning somewhere in the docs, telling users to override the settings as such:
```lua
return {
  'ibhagwan/fzf-lua',
  opts = {
    fzf_bin = 'sk',
    fzf_opts = {
      ['--no-scrollbar'] = false,
    },
  },
}
```

Thank you very much for your impressive work

### Steps To Reproduce

1. Install fzf-lua
2. Create `lua/plugins/fzf.lua` with the following content, following `fzf-lua`'s docs:
   ```lua
    return {
      'ibhagwan/fzf-lua',
      opts = {
        fzf_bin = 'sk',
      },
    }
  
   ````
3. Call any picker, for instance using `<leader>ff`

### Expected Behavior

The picker opens

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    {
      'ibhagwan/fzf-lua',
      opts = {
        fzf_bin = 'sk',
      },
    }
  },
})
```

**Comment by folke** [comment]
@ibhagwan what would be nice is if we could set options for a specific  binary / version.
I see that you internally already do this for some options, so maybe a good idea to make it possible to this from config as well?

**Comment by ibhagwan** [comment]
> [@ibhagwan](https://github.com/ibhagwan) what would be nice is if we could set options for a specific binary / version. I see that you internally already do this for some options, so maybe a good idea to make it possible to this from config as well?


I’ve had it in my mind for a while that some of the versioning stuff needs refactoring, basically a function that adds up all options by version and nullifies options that aren’t compatible.

**Comment by ibhagwan** [comment]
Will obiously need more testing and also scouring the fzf changelog to add all options and their respective numbers but in case you wanna track it, it's in branch [compat_opts](https://github.com/ibhagwan/fzf-lua/tree/compat_opts):

https://github.com/ibhagwan/fzf-lua/compare/main...compat_opts

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/pull/1608 merged, see the notes in the PR for more info.

In short, no default option in fzf_opts should cause an issue with either older versions of fzf or skim as the codes will remove non compatible options.

**Comment by folke** [comment]
That' s awesome, thanks!!

**Comment by ibhagwan** [comment]
> That' s awesome, thanks!!

Just to clarify, you can now send any existing options in `fzf_opts` even “skim only” options like `--inline-info` or newer options like `--tmux`, any non compatible options will be silently ignored, this way we don’t have to manage different sets of options per binary/version.

**Comment by LoricAndre** [comment]
@folke thanks !

fyi, same error because of an outdated fzf: [https://www.reddit.com/r/neovim/s/S1CCkXJHsl](https://www.reddit.com/r/neovim/s/S1CCkXJHsl)
