### ISSUE TITLE
feature: consolidate <Leader> search, find, grep

### ISSUE THREAD

**Issue by gallo-s-chingon** [LazyVim/LazyVim#5204]
### Did you check the docs?

- [x] I have read all the LazyVim docs
- [x] This is not a request for a new or existing extra (see above)

### Is your feature request related to a problem? Please describe.

basic Lazyvim Starter <Leader> popup has:

`f find/file`
`/ grep`
`s search`

all of which seem redundant. 

### Describe the solution you'd like

my request would be to have a `keymap.lua` that has ALL the keybinds so one can edit to their liking more easily (especially for a prose writer like myself)

or simply map `<Leader>/` to search and all the `find/file` and `grep` options within "new" `search` since there are redundancies within search and find/file. and leave `<Leader>f` for `file' (only)

### Describe alternatives you've considered

I tried to add to keymaps.lua, but as a prose writer I kept getting errors when I open neovim and gave up

**Comment by dpetka2001** [comment]
> all of which seem redundant.

They're not redundant. Each is structured around logic about `search`ing text in files or `find`ing files. You deeming it redundant is a personal preference after all.

A similar [PR](https://github.com/LazyVim/LazyVim/pull/4660) was made in the past and maintainer decided it would add too much complexity for little benefit. 

So, I doubt something like this will happen. However, the maintainer has the final say.
