### ISSUE TITLE
every snippet has it's duplicate for some reason.

### ISSUE THREAD

**Issue by monoira** [LazyVim/LazyVim#5210]
### Discussed in https://github.com/LazyVim/LazyVim/discussions/5142

<div type='discussions-op-text'>

<sup>Originally posted by **milkpuff** December 17, 2024</sup>
 I enable lazyextra `coding.blink` and `coding.luasnip`:
![图片](https://github.com/user-attachments/assets/d88d16bd-b76a-47fe-a1c5-1823480368d8)
If disable `coding.luasnip`, snippets show once, but some snippet like `classi` raise error:
`/usr/share/nvim/runtime/lua/vim/lsp/_snippet_grammar.lua:177: snippet parsing failed`</div>

I also have this issue. I use luasnip with pretty basic setup.
here is [my LazyVim config](https://github.com/monoira/.dotfiles/tree/main/nvim/.config/nvim)

![Image](https://github.com/user-attachments/assets/0a17332e-1bff-465c-a30c-0359e7171198)

**Comment by dpetka2001** [comment]
This doesn't happen with `nvim-snippets`, so it must be some kind of incompatibility between Luasnip and blink. It would be wiser to report this problem to blink repo. In the meantime if you want to keep using Luasnip, just use nvim-cmp instead of blink.

**Comment by monoira** [comment]
when I use both luasnip and nvim-cmp with nvim-snippets disabled, snippets don't work at all.
I will stick around with blink until it gets fixed I guess.

**Comment by dpetka2001** [comment]
No need for re-opening any more.

**Comment by yxian9** [comment]
The blink.cmp v0.10.0 https://github.com/Saghen/blink.cmp/releases/tag/v0.10.0 seems addressed this issue and introduced a break chang. 

> The luasnip source has been removed in favor of a [snippets.preset = 'luasnip'](https://cmp.saghen.dev/configuration/snippets.html#luasnip)
