### ISSUE TITLE
bug: extra angle bracket added on newline in vue/svelte html template

### ISSUE THREAD

**Issue by kblcuk** [LazyVim/LazyVim#5222]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

MacOS 15.2

### Describe the bug

An extra closing angle bracket is added when you add a new line after a line that contains only angle bracket. This seems to affect at least vue and svelte files, but not usual html files (or jsx markup). Can be reproduced with vanilla LazyVim. I'd guess it's something specific to one of the default plugins (or configurations) LazyVim uses, since I don't observe this behaviour in LunarVim, for instance.

### Steps To Reproduce

Run `nvim -u repro.lua test.vue`.

Paste the following:
```vue
<template>
  <div 
    class="foo"
  >
  </div>
</template>
```

Type `:4` to go to line 4, press `o`.
Result will look like:

```vue
<template>
  <div 
    class="foo"
  >
  >
  </div>
</template>
```

The same manifests if you go to insert mode and add a newline with enter key.

### Expected Behavior

Result should look like

```vue
<template>
  <div 
    class="foo"
  >

  </div>
</template>
```

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  },
})
```

**Comment by kblcuk** [comment]
Well, I tried to repro it with just requiring nvim-treesitter and nvim-ts-autotag, but it didn't manifest; so I figured I'd file an issue here first.

```lua
require("lazy.minit").repro({
	spec = {
		{
			"nvim-treesitter/nvim-treesitter",
			opts = {
				sync_install = true,
				ensure_installed = {
					"html",
					"javascript",
					"typescript",
					"svelte",
					"vue",
					"tsx",
					"php",
					"glimmer",
					"rescript",
					"templ",
					"embedded_template",
				},
			},
			"windwp/nvim-ts-autotag",
		},
	},
})
```

But I'll ask in nvim-ts-autotag.
Thanks for looking into it, and have a nice vacation! 😁

**Comment by folke** [comment]
Well then it's not a nvim-ts-autotag bug is it?
So I wouldn't post a bug there either.
trouble shoot yourself first until you find what is causing this.
Once you find it file a proper bug report where needed.

**Comment by kblcuk** [comment]
Welp, I managed to narrow it down to `formatoptions` value, which is currently `opt.formatoptions = "jcroqlnt" -- tcqj` : https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua#L73

This also happens in vanilla neovim, so I guess it for some reason decides that comment symbol in vue or svelte templates is `>`. Odd.
