### ISSUE TITLE
bug: nvim-treesitter/install.lua:86: Parser not available for language "help"

### ISSUE THREAD

**Issue by netherstar** [LazyVim/LazyVim#524]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.3

### Operating system/version

Debian 11, Windows 11

### Describe the bug

How to fix that error 
![image](https://user-images.githubusercontent.com/12563466/229359291-c67b7d38-b394-4da4-b19e-6b87a2e2a4f9.png)

### Steps To Reproduce

Fresh install of Lazy Vim

### Expected Behavior

open nvim without that error message

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
If you do `:TSInstall help` it will try to reinstall it if available. Maybe this could solve your problem?

**Comment by Nhaaro** [comment]
it's a breaking change in nvim-treesitter
https://github.com/nvim-treesitter/nvim-treesitter/commit/93fa5df0a3f0aeb72df50a9d2110cb90fc5a0a13

**Comment by slavamak** [comment]
For me, it solves this problem
```lua
ignore_install = { "help" }
```

**Comment by goosegit11** [comment]
> For me, it solves this problem
> 
> ```lua
> ignore_install = { "help" }
> ```

where do you prefer to write this line?
init.lua or separate file in plugins folder? or something different?

**Comment by slavamak** [comment]
@goosegit11 yeah in plugins folder, you can see examples [here](https://www.lazyvim.org/configuration/examples)

```lua
return {
  'nvim-treesitter/nvim-treesitter',
  opts = function(_, opts)
    opts.ignore_install = { 'help' }

    if type(opts.ensure_installed) == 'table' then
      vim.list_extend(opts.ensure_installed, {
        'dockerfile',
        'git_config',
        'jsdoc',
        'make',
        'toml',
        'vimdoc',
      })
    end
  end,
}
```

**Comment by goosegit11** [comment]
> ```lua
> return {
>   'nvim-treesitter/nvim-treesitter',
>   opts = function(_, opts)
>     opts.ignore_install = { 'help' }
> 
>     if type(opts.ensure_installed) == 'table' then
>       vim.list_extend(opts.ensure_installed, {
>         'dockerfile',
>         'git_config',
>         'jsdoc',
>         'make',
>         'toml',
>         'vimdoc',
>       })
>     end
>   end,
> }
> ```

could you explain second part of that snippet?
```lua
    if type(opts.ensure_installed) == 'table' then
      vim.list_extend(opts.ensure_installed, {
        'dockerfile',
        'git_config',
        'jsdoc',
        'make',
        'toml',
        'vimdoc',
      })
```

**Comment by PRSouzaFM** [comment]
> > ```lua
> > return {
> >   'nvim-treesitter/nvim-treesitter',
> >   opts = function(_, opts)
> >     opts.ignore_install = { 'help' }
> > 
> >     if type(opts.ensure_installed) == 'table' then
> >       vim.list_extend(opts.ensure_installed, {
> >         'dockerfile',
> >         'git_config',
> >         'jsdoc',
> >         'make',
> >         'toml',
> >         'vimdoc',
> >       })
> >     end
> >   end,
> > }
> > ```
> 
> could you explain second part of that snippet?
> 
> ```lua
>     if type(opts.ensure_installed) == 'table' then
>       vim.list_extend(opts.ensure_installed, {
>         'dockerfile',
>         'git_config',
>         'jsdoc',
>         'make',
>         'toml',
>         'vimdoc',
>       })
> ```

You don't really need this second part - just up to 
return {
  'nvim-treesitter/nvim-treesitter',
  opts = function(_, opts)
    opts.ignore_install = { 'help' }
    end
    }
    would do

**Comment by goosegit11** [comment]
> > > ```lua
> > > return {
> > >   'nvim-treesitter/nvim-treesitter',
> > >   opts = function(_, opts)
> > >     opts.ignore_install = { 'help' }
> > > 
> > >     if type(opts.ensure_installed) == 'table' then
> > >       vim.list_extend(opts.ensure_installed, {
> > >         'dockerfile',
> > >         'git_config',
> > >         'jsdoc',
> > >         'make',
> > >         'toml',
> > >         'vimdoc',
> > >       })
> > >     end
> > >   end,
> > > }
> > > ```
> > 
> > 
> > could you explain second part of that snippet?
> > ```lua
> >     if type(opts.ensure_installed) == 'table' then
> >       vim.list_extend(opts.ensure_installed, {
> >         'dockerfile',
> >         'git_config',
> >         'jsdoc',
> >         'make',
> >         'toml',
> >         'vimdoc',
> >       })
> > ```
> 
> You don't really need this second part - just up to return { 'nvim-treesitter/nvim-treesitter', opts = function(_, opts) opts.ignore_install = { 'help' } end } would do

Yeah I understand, but I'm just curious about it. I'm newbie to neovim plugins (was using it as just a vim replacement for long, now I want to set up some plugins), so any info about neovim configuration will be helpful to me

**Comment by divxvid** [comment]
I was also facing the same issue after installing LazyVim yesterday and @slavamak's solution worked for me. 
Thanks mate!

**Comment by eyolf** [comment]
> @goosegit11 yeah in plugins folder, you can see examples [here](https://www.lazyvim.org/configuration/examples)

So "the plugins folder", where exactly would that be? I've tried to put it in .config/nvim/plugins, in .config/nvim/lua/plugins but no luck.

**Comment by dpetka2001** [comment]
Have you looked at the [docs](https://www.lazyvim.org/configuration). It clearly describes the file structure.

**Comment by PRSouzaFM** [comment]
> > @goosegit11 yeah in plugins folder, you can see examples [here](https://www.lazyvim.org/configuration/examples)
> 
> So "the plugins folder", where exactly would that be? I've tried to put it in .config/nvim/plugins, in .config/nvim/lua/plugins but no luck.

Navigate to ~/.config/nvim/lua/plugins
Create a file there called core.lua or [whatever].lua

Paste this code:
`  return {
{
    "nvim-treesitter/nvim-treesitter",
    opts = function(_, opts)
      opts.ignore_install = { "help" }
    end,
   }
  }
`
Also, please read the docs, they provide useful information in issues like these - plus you'll learn how to add and configure other plugins

**Comment by dpetka2001** [comment]
It must have been some mistake in your spec then. Paste the code in the previous post in a lua file as is and it should work.

**Comment by eyolf** [comment]
I did that too – even followed the naming suggestion, but still no luck.
This is a fresh installation from the kickstarter.vim init.lua file - could that be part of it?

**Comment by dpetka2001** [comment]
Well if kickstarter handles things different from Lazyvim then that may well be a problem. You should ask there if it's about kickstart.

**Comment by dpetka2001** [comment]
There is a section in kickstart init.lua about treesitter. Could you put there
```lua
opts = function(_, opts) opts.ignore_install = { "help" } end,
```
right before the `config` command? Maybe that would work. And delete the file that you previously created here as it seems kickstart has a bit different file structure than Lazyvim. Otherwise I don't know how kickstart internals work as I haven't used it and you'd be better off asking the community that actually uses it.

**Comment by eyolf** [comment]
Ah - I found it. It wasn't exactly there, but a little later in the init.lua script there is the line

  ensure_installed = { 'c', 'cpp', 'go', 'lua', 'python', 'rust', 'tsx', 'typescript', 'help', 'vim' },

where I changed 'help' to 'vimdoc', and it all work.
Thanks for all your assistance! Been a vim user for 20+ years, and now there's a whole new ecosystem to get used to ...

**Comment by dpetka2001** [comment]
Glad you found your way around :)

**Comment by baddate** [comment]
> @goosegit11 yeah in plugins folder, you can see examples [here](https://www.lazyvim.org/configuration/examples)
> 
> ```lua
> return {
>   'nvim-treesitter/nvim-treesitter',
>   opts = function(_, opts)
>     opts.ignore_install = { 'help' }
> 
>     if type(opts.ensure_installed) == 'table' then
>       vim.list_extend(opts.ensure_installed, {
>         'dockerfile',
>         'git_config',
>         'jsdoc',
>         'make',
>         'toml',
>         'vimdoc',
>       })
>     end
>   end,
> }
> ```

it works!

**Comment by folke** [comment]
fixed in the meantime. will make a new release soon

**Comment by danielb2** [comment]
i'm getting this error, but not even using lazyvim, just treesitter by itself. not using lua. seems this isn't a lazyvim issue

**Comment by amaanq** [comment]
it is called vimdoc now.

**Comment by danielb2** [comment]
> it is called vimdoc now.

that did it. thank you

**Comment by zobayer1** [comment]
Although not the same, I am getting the same error for "**Lua**" which is a bit strange.

```
Could not load parser for lua: "/usr/share/nvim/runtime/lua/vim/treesitter/language.lua:93: no parser for 'lua' language, see :help treesitter-parsers"
```

Any hint as to what's going wrong here?
