### ISSUE TITLE
bug: cannot clone codeium which is a dependency of blink.cmp

### ISSUE THREAD

**Issue by konosubakonoakua** [LazyVim/LazyVim#5251]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10

### Operating system/version

win11

### Describe the bug

```log
    ○ codeium.nvim  blink.cmp 
        Cloning into 'codeium.nvim'...
        fatal: 'C:/Users/me/AppData/Local/nvim-data/lazy/codeium.nvim' does not appear to be a git repository
        fatal: Could not read from remote repository.

        Please make sure you have the correct access rights
        and the repository exists.

```

### Steps To Reproduce

1. I don't want the ai cmp, so set `vim.g.ai_cmp = false`
2. I don't enable codeium in extras
3. automatically install blink.cmp which relies on `codeium.nvim` instead of `Exafunction/codeium.nvim`
4. cannot find repository, because lack of `Exafunction/`

### Expected Behavior

just don't clone codeium if not needed

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
How do you have Codeium enabled if not by LazyExtras? Give more reproducible steps. I set `vim.g.ai_cmp = false` and I don't have Codeium enabled in Extras, but I don't get the error you mention.

**Comment by konosubakonoakua** [comment]
Solved, I copy paste default config for blink.cmp to tweak curl settings, but there's a dependency list.
I delete them then it works now.
![Image](https://github.com/user-attachments/assets/034a54a4-9962-4a72-b40b-78e9ee87e909)
