### ISSUE TITLE
bug: Cursor position changes if a toggled split terminal goes on top of it.

### ISSUE THREAD

**Issue by mohammad-amin-khajeh** [LazyVim/LazyVim#5255]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

Arch linux kernel 6.12.4-zen1-1-zen

### Describe the bug

When my cursor is on the bottom side of the screen and I toggle the bottom terminal to run some commands, hiding the terminal will make it so that the my cursor is now on the top part of the terminal before it was hidden(if the toggled terminal window goes over my cursor that is).

### demonstration:
https://github.com/user-attachments/assets/8509a3d2-b69b-4370-bb4e-8d584546b281

### Steps To Reproduce

1. have the cursor at the bottom of the screen
2. toggle the default bottom terminal in lazyvim
3. hide the terminal
4. cursor position is changed

### Expected Behavior

Cursor position stays the same and does not change with toggling the split terminal.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
Change `vim.opt.splitkeep = "cursor"` in your `options.lua` file. That is what determines the behavior you describe.

**Comment by mohammad-amin-khajeh** [comment]
Apparently the default lazyvim uses `vim.opt.splitkeep = "screen"` which is why the strange behavior occurs, changing `vim.opt.splitkeep` in my `options.lua` indeed fixed that, many thanks.
