### ISSUE TITLE
bug: Scrolling is not working in VsCode

### ISSUE THREAD

**Issue by catalinux17** [LazyVim/LazyVim#5261]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.3

### Operating system/version

MacOS Sequoia 15.2

### Describe the bug

`gg` `G` `C-u` `C-d` does not work properly.
`gg` does not get me to the first line.
`G` does not get me to the last line.
not sure what happens when `C-u` is pressed. not what I would expect.

![Image](https://github.com/user-attachments/assets/4a39415c-e76c-400e-9bc1-a60441c6bd0c)

### Steps To Reproduce

1. Have VSCode extra package installed (optional)
2. Try movement motions in VSCode
3. Fail

### Expected Behavior

Smooth scrolling.

### Repro

```lua

```

**Comment by catalinux17** [comment]
`*` is not working every time.
![Image](https://github.com/user-attachments/assets/42c36650-495e-4471-81f4-39a121c1ae29)

**Comment by dpetka2001** [comment]
Can't reproduce

https://github.com/user-attachments/assets/9aa89a0d-148c-49fd-b4c2-3ce42946ecbb

Do you maybe have some plugin that overwrites the mappings? It all works as expected from my testing. I tried to emulate the steps that you described but didn't observe anything weird.

**Comment by xopo** [comment]
Is this the same vscode ? it is working on my machine :)
https://github.com/user-attachments/assets/0ed197f5-88da-4944-8ce0-fd96483f6ac9

- would you try on new instance ? Just reinstall and test, keep the old stuff....
- is it possible you have another keymap set for gg set by yourself or other package? 

![Image](https://github.com/user-attachments/assets/a9d28dc4-d863-40c5-8258-7d76834abb3f)

**Comment by catalinux17** [comment]
I've did reinstalled lazy neovim from scrath with all the plugins and extras and it worked.

thanks @dpetka2001 @xopo for replies!

**Comment by NavyD** [comment]
I found that disabling [ui.mini-animate](https://www.lazyvim.org/extras/ui/mini-animate) worked fine!
