### ISSUE TITLE
bug: LspInfo opening in new window instead of modal

### ISSUE THREAD

**Issue by theoribeiro** [LazyVim/LazyVim#5263]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2 Release

### Operating system/version

MacOS 15.2

### Describe the bug

Running LspInfo or pressing `<leader>cl` is opening what used to be the LspInfo modal as a tab instead. I looked into the changelog to try to understand if this was intended but it seems like a bug, please correct me if I'm wrong. 

### Steps To Reproduce

1. Run `:LspInfo`
2. See LspInfo window instead of modal

### Expected Behavior

LspInfo should open in a modal!

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
That has nothing to do with LazyVim. `nvim-lspconfig` changed this behavior a while ago. [This commit](https://github.com/neovim/nvim-lspconfig/commit/e6569c18c21be5166e4b9cc7530e828b8285c84e) is what introduced this behavior.

**Comment by theoribeiro** [comment]
@dpetka2001 Got it! Going to close this, then! Thanks for the answer.
