### ISSUE TITLE
bug:  font is not rendering correctly

### ISSUE THREAD

**Issue by Damon-GSY** [LazyVim/LazyVim#5269]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.3 Build type: Release LuaJIT 2.1.1734355927 

### Operating system/version

Mac 15.1.1

### Describe the bug

![Image](https://github.com/user-attachments/assets/86c97917-135e-40f3-b0a0-f2bf2648aa1c)
As you can see, the code is not correctly rendered. I have set the font to be FiraCode Nerd Font.

### Steps To Reproduce

I have not change anything and I just clone the start repo

```
git clone https://github.com/LazyVim/starter ~/.config/nvim
``` 

### Expected Behavior

![Image](https://github.com/user-attachments/assets/d048207e-fd12-4ae0-93e7-ee136bb2ea01)
It should be something like this 

### Repro

```lua
same as this repo "https://github.com/LazyVim/starter"
```

**Comment by dpetka2001** [comment]
What does that have to do with LazyVim? How the fonts are rendered is purely dependent on the terminal you use and how you've configured it with the fonts you want to use.

**Comment by Damon-GSY** [comment]
Hi, thank you for ur responding. 
I have set the font but it did not work, do you have any idea? ![Image](https://github.com/user-attachments/assets/bf862883-ca24-4369-bbe8-c77ef3ff43c7)

**Comment by dpetka2001** [comment]
Tokyonight has some settings regarding styles as you can see in the [docs](https://github.com/folke/tokyonight.nvim?tab=readme-ov-file#%EF%B8%8F-configuration) under **Default Options**. By default for `comments` and `keywords` it uses `italic`. You can try changing that according to your preferences, but this is not a LazyVim bug.

**Comment by Damon-GSY** [comment]
thank you. I have test it for a while but I have not successfully changed the theme.... Could you help me out:)

**Comment by dpetka2001** [comment]
What colorscheme would you like to use? The default is tokyonight. Or you can change it to something else if you'd like.

**Comment by Damon-GSY** [comment]
I just want the font is correctly rendered

**Comment by dpetka2001** [comment]
Do you mean the colors of the keywords?

**Comment by dpetka2001** [comment]
Sorry, but this is related to your terminal. I've configured Ghostty to use `FiraCode Nerd Font` like this 

![Image](https://github.com/user-attachments/assets/4a48eda0-7b0b-4f62-a2f4-aa40597a6a2d)

And I get the following with part of your code

![Image](https://github.com/user-attachments/assets/bcb95e96-5956-4e48-8ef9-0fd1e87d1cc6)

I don't use your terminal so don't know how to be of further help. Make also sure that the Nerd fonts version that you use is the latest. Maybe you're not on Nerd fonts v3.x or greater?

**Comment by Damon-GSY** [comment]
I may found the issue. 
[https://github.com/warpdotdev/Warp/issues/3925](url)
