### ISSUE TITLE
bug: LUA Language Server not executing

### ISSUE THREAD

**Issue by ionztorm** [LazyVim/LazyVim#5281]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.3

### Operating system/version

MacOS 15.2

### Describe the bug

I get the following warning whenever loading an lua file:

...lar/neovim/0.10.3/share/nvim/runtime/lua/vim/lsp/rpc.lua:800: Spawning language server with cmd: { "lua-language-server" } failed. The language server is either not installed, missing from PATH, or not executable.

Same issue experienced by another user in discussion 4266.

Checking LspInfo shows healthcheck could not be loaded for lspconfig and lua-language-server is not mounted.

### Steps To Reproduce

1. Install LazyVim
2. Open an .lua file

### Expected Behavior

No warning, LSP loads.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
Are [these your dotfiles](https://github.com/ionztorm/dotfiles/tree/main/nvim)?

**Comment by ionztorm** [comment]
> Are [these your dotfiles](https://github.com/ionztorm/dotfiles/tree/main/nvim)?

Those dot files are my own config and not my LazyVim install. I did not have this issue with that config.

I've backed those up, and run the following to ensure a fresh install:

rm -rf ~/.config/nvim
rm -rf ~/.local/state/nvim
rm -rf ~/.local/share/nvim

The issue is in a fresh install of LazyVim. The lua_ls / lua-language-server is installed on first load by Mason, as expected, and is listed as installed in Mason. It just fails to execute.

**Comment by dpetka2001** [comment]
You also have to `rm -rf ~/.cache/nvim`. 

I can't reproduce what you're describing with a fresh LazyVim installation. Screencast following

https://github.com/user-attachments/assets/f4c02416-444f-4c13-8f19-24e7fd093e50

**Comment by ionztorm** [comment]
> You also have to `rm -rf ~/.cache/nvim`.
> 
> I can't reproduce what you're describing with a fresh LazyVim installation. Screencast following
> 
>  Screencast_2024-12-31-01-09-09.webm

Let me give that a try and come back to you

**Comment by dpetka2001** [comment]
Also try the following steps exactly 
```sh
1. mkdir ~/.config/lazytest
2. git clone https://github.com/LazyVim/starter ~/.config/lazytest
3. NVIM_APPNAME=lazytest nvim and wait for the installation to complete
4. While Lazy UI is still open press `C` to check and `U` to make sure everything is updated
5. Restart Neovim with command from step 3
```
For cleanup
```sh
rm -rf ~/.config/lazytest
rm -rf ~/.local/share/lazytest
rm -rf ~/.local/state/lazytest
rm -rf ~/.cache/lazytest
```

**Comment by ionztorm** [comment]
> rm -rf ~/.cache/nvim

That fixed it, good spot! thanks, the cache removal did the trick

**Comment by dpetka2001** [comment]
Glad you got it solved 😄

**Comment by dpetka2001** [comment]
From inside Neovim type `:echo stdpath("cache")` and it will print out the cache path depending on your OS.
