### ISSUE TITLE
bug: `goto definition` disables zen mode when using telescope

### ISSUE THREAD

**Issue by mohammad-amin-khajeh** [LazyVim/LazyVim#5286]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.3

### Operating system/version

Arch linux kernel 6.12.7-zen1-1-zen

### Describe the bug

when using fzf everything works fine, but with telescope zen mode gets disables as soon as I press `gd` to go to a definition.

After looking into it for some time I realized [this](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/extras/editor/telescope.lua#L296-L296) is the line that's causing the bug.
apparently setting `reuse_win` to false fixes it.

### Steps To Reproduce

1. Enter zen mode while using telescope instead of fzf
2. press `gd` on a function, variable, class etc
3. zen mode is disabled.

### Expected Behavior

`goto definition` works the same in telescope and fzf, meaning it doesn't disable zen mode in telescope.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
The commit that intoduced this behavior is #1131. 

In my personal opinion this is just a personal preference, so you can change the mappings in your personal configuration if you'd like.

**Comment by mohammad-amin-khajeh** [comment]
I did change the default mappings in my lspconfig like so:

```lua
{
    "neovim/nvim-lspconfig",
    opts = function()
      -- "reuse_win = true" disables snacks' zen mode so I'm disabling that
      local keys = require("lazyvim.plugins.lsp.keymaps").get()
      keys[#keys + 1] = {
        "gd",
        function()
          require("telescope.builtin").lsp_definitions({ reuse_win = false })
        end,
        desc = "Goto Definition",
        has = "definition",
      }

      keys[#keys + 1] = {
        "gI",
        function()
          require("telescope.builtin").lsp_implementations({ reuse_win = false })
        end,
        desc = "Goto Implementation",
      }
      keys[#keys + 1] = {
        "gy",
        function()
          require("telescope.builtin").lsp_type_definitions({ reuse_win = false })
        end,
        desc = "Goto T[y]pe Definition",
      }
    end,
  }```

Sorry for not closing the issue yet, but I'm just wondering isn't the inconsistent behavior between fzf and telescope considered a bug of some kind? fzf does not have this issue

**Comment by dpetka2001** [comment]
Different preferences for different people? I don't use Telescope, so i don't know what the desired behavior should be. Apparently the OP of that PR thought differently than you. You could create a new PR and state your reasoning for changing the default and the maintainer will decide. In my personal opinion, behavior that can be customized through settings/mappings, but is not the default is not a bug.

**Comment by mohammad-amin-khajeh** [comment]
I see, yeah that's a fair point I'll make a PR later and see how it goes, thanks for the clarification.
