### ISSUE TITLE
bug: copilot not working

### ISSUE THREAD

**Issue by ChenZhongPu** [LazyVim/LazyVim#532]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.3

### Operating system/version

MacOS 13.3

### Describe the bug

I followed the instructions to install the `copilot`, but it does not work as expected.

```lua
    { import = "lazyvim.plugins.extras.coding.copilot" },
    { import = "plugins" },
```

In a Python file, the `:Copilot` command shows:

<img width="581" alt="image" src="https://user-images.githubusercontent.com/2310958/229991856-c913d414-f947-471e-9088-1647a9aa3691.png">

**It only offers suggestions for very naive completions**. For example, it is able to auto-complete `test_add()`:

<img width="713" alt="image" src="https://user-images.githubusercontent.com/2310958/229993632-ea4d1a81-8a4e-4935-bdf3-960db034a071.png">

But when I input other *advanced* function names (e.g., `def select_sort(a)`), it does not show any suggestion. 

<img width="298" alt="image" src="https://user-images.githubusercontent.com/2310958/229995694-ca424cba-5dd0-4c43-9ba8-1dc7f3637b51.png">

How to troubleshoot it? Is it caused by network issue? I also tested in VSCode, and everything went well.

### Steps To Reproduce

1. Enable `lazyvim.plugins.extras.coding.copilot`
2. Type `def select_sort(a):` in a Python file.

### Expected Behavior

Copilot should offer code suggestions.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by YareDaze20** [comment]
Hi, I have the same issue. Have you found a solution?

**Comment by partounian** [comment]
No solution yet?

**Comment by partounian** [comment]
Thanks for confirming it works! I'll see when I can give this another shot.

If you're willing to take a quick look:

I tried adapting the copilot logic in this repo for https://github.com/Allaman/nvim which I believe was based on LazyVim, however whatever I tried made nvim-cmp not show any results. 

Commit of my latest attempt to get it working https://github.com/partounian/nvim/commit/31984f85a8ed29308f4f1c673e45415de0bf235b

linking just in case
https://github.com/Allaman/nvim/issues/44

**Comment by folke** [comment]
It works in lazyvim, I'm not going to debug your personal config

**Comment by roshaans** [comment]
Have you found a solution yet? @ChenZhongPu

**Comment by ChenZhongPu** [comment]
> Have you found a solution yet? @ChenZhongPu

It turns out that the suggestion will not be shown when current line is empty. For example:

![image](https://user-images.githubusercontent.com/2310958/233535608-fbe94891-6e50-458a-80d6-1f8577115af7.png)

While it works when current line is NOT empty:

![image](https://user-images.githubusercontent.com/2310958/233535692-8bac645b-dcb9-4309-8f93-134b9f9dc789.png)

BTW, we can adding the following keymaps manually in order to trigger suggestion even if the line is empty: 

```lua
vim.keymap.set("i", "<M-[>", function()
  require("copilot.suggestion").prev()
end)

vim.keymap.set("i", "<M-]>", function()
  require("copilot.suggestion").next()
end)

vim.keymap.set("i", "<M-l>", function()
  require("copilot.suggestion").accept()
end)

vim.keymap.set("i", "<C-]>", function()
  require("copilot.suggestion").dismiss()
end)
```

**Comment by ChenZhongPu** [comment]
In addition, to quickly grasp the status the copilot, I suggest adding the following to the statusline. @roshaans 

```lua
  {
    "nvim-lualine/lualine.nvim",
    event = "VeryLazy",
    opts = function(_, opts)
      table.insert(opts.sections.lualine_x, function()
        return "🤖" .. require("copilot.api").status.data.status
      end)
    end,
  },
```

**Comment by folke** [comment]
@ChenZhongPu not showing on an empty line is a known issue of copilot-cmp, although it does seem to be working recently for me.

If you invoke those keymaps you mentioned, then that will interfere with copilot-cmp. It will no longer show suggestions that would be shown with the keymaps. In order to make copilot-cmp work, some features of copilot.lua have to be disabled.

I just added a lualine component for copilot:
* shows the copilot icon colored based on the status
* also shows the message when available (typically set for warnings)

Will make a new release in a bit

**Comment by ChenZhongPu** [comment]
> 
>     * shows the copilot icon colored based on the status
> 

Good job. But I think it is not very intuitive to distinguish status based on colors. Is it possible to add some animation when it is "in progress"?

**Comment by folke** [comment]
no, sorry

**Comment by folke** [comment]
I had accidentally picked the same color for Normal and InProgress. Fixed now.

**Comment by roshaans** [comment]
I was able to get it to work by manually loading the plugin configuration into `plugins/copilot.lua` and deleting ~.config/github-copilot/hosts.json` then running Copilot auth once again.

**Comment by niteshbalusu11** [comment]
I got copilot working but `Tab` doesn't seem to be the default key for making it auto-complete and I can't figure what the key binding is?
Can someone tell me what it is? `Tab` simply adds a tab.

**Comment by folke** [comment]
If you used the LazyVim extra, then that installs copilot-cmp. You'll get copilot suggestions as completions.

**Comment by niteshbalusu11** [comment]
> If you used the LazyVim extra, then that installs copilot-cmp. You'll get copilot suggestions as completions.

I tried the actual copilot plugin as well, that doesn't seem to complete with a tab too.

**Comment by niteshbalusu11** [comment]
Created a file in the plugins folder with this.

```
return {
  "github/copilot.vim",
}
```

**Comment by folke** [comment]
If you don't want to use cmp, I highly suggest you to use the lua copilot version instead https://github.com/zbirenbaum/copilot.lua

**Comment by niteshbalusu11** [comment]
> If you don't want to use cmp, I highly suggest you to use the lua copilot version instead https://github.com/zbirenbaum/copilot.lua

hmm, still the same problem. I get suggestions but `Tab` key doesn't insert the suggestion, not does `<CR>`

**Comment by niteshbalusu11** [comment]
> If you used the LazyVim extra, then that installs copilot-cmp. You'll get copilot suggestions as completions.

How do we accept the suggestion?

**Comment by folke** [comment]
tab is used by luasnip, so you'll have to configure copilot.lua to use another key, or disable luasnip
