### ISSUE TITLE
some trouble with indentation in Swift

### ISSUE THREAD

**Issue by jhchenchong** [LazyVim/LazyVim#536]
### Discussed in https://github.com/LazyVim/LazyVim/discussions/527

<div type='discussions-op-text'>

<sup>Originally posted by **jhchenchong** April  3, 2023</sup>
I'm a beginner in using vim, and I'm having some trouble with indentation in Swift. Can you help me solve this problem?
<img width="463" alt="截屏2023-04-03 09 18 55" src="https://user-images.githubusercontent.com/19201316/229391568-234dbff8-79ee-4d82-8519-ddbb37851445.png">
Thanks!</div>

**Comment by amaanq** [comment]
Doesn't belong here, should be at nvim-treesitter probably.

**Comment by jhchenchong** [comment]
> Doesn't belong here, should be at nvim-treesitter probably.

Thanks!
