### ISSUE TITLE
feature: support terminal in a split window

### ISSUE THREAD

**Issue by liulixiang1988** [LazyVim/LazyVim#539]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

I have tried many times to use vim when coding, but it's LazyVim that help me really achieve this goal. It's fantastic!

Currently we use `<leader>ft` to open terminal. If we want to change back to code, we have to type `exit` in shell and reopen it again in the next time. Could we support open terminal in the same window (like in the bottom or horizontal window)?

### Describe the solution you'd like

We can open terminal in the bottom or horizontal window. By that, we don't need to reopen terminal every time.

### Describe alternatives you've considered

None

**Comment by folke** [comment]
You should indeed use toggleterm for more advanced terminal usage

**Comment by rofrol** [comment]
For future me:

```lua
  {
    "akinsho/toggleterm.nvim",
    config = function()
      require("toggleterm").setup({
        open_mapping = [[<c-\>]],
        shade_terminals = false,
        -- add --login so ~/.zprofile is loaded
        -- https://vi.stackexchange.com/questions/16019/neovim-terminal-not-reading-bash-profile/16021#16021
        shell = "zsh --login",
      })
    end,
    keys = {
      { [[<C-\>]] },
      { "<leader>0", "<Cmd>2ToggleTerm<Cr>", desc = "Terminal #2" },
      {
        "<leader>td",
        "<cmd>ToggleTerm size=40 dir=~/Desktop direction=horizontal<cr>",
        desc = "Open a horizontal terminal at the Desktop directory",
      },
    },
  },
```

`<Leader>0` open second terminal vertically.

Taken from https://github.com/alpha2phi/modern-neovim/blob/268234975df52ef79237d248ad52a69590660e11/lua/plugins/toggleterm.lua#LL5C8-L5C8

**Comment by waflessnet** [comment]
hi, 
i add code in folders pluging, install ok but not work 

![image](https://github.com/LazyVim/LazyVim/assets/6413704/bb8d7a6a-20e9-405c-9d0c-afad6930ada1)

**Comment by TheRsKing** [comment]
> You should indeed use toggleterm for more advanced terminal usage

Are there plans to bring toggleterm by default?

**Comment by folke** [comment]
nope. I don't really see the need tbh.
Especially together with `edgy.nvim`, the lazy terminal is more than enough
![image](https://github.com/LazyVim/LazyVim/assets/292349/40f8f41f-dac7-4ed4-bdec-bb7172af5260)

**Comment by gogamid** [comment]
splitting the LazyTerm mirrors the open terminal :D 
is there a way to make it work? <C-/> to open terminal, "esc,esc" normal mode, split, again normal mode, <C-/> hides all the splits?
<img width="2045" alt="image" src="https://github.com/user-attachments/assets/96082ae0-da0e-4614-b370-f815455095d0">
