### ISSUE TITLE
bug: can't disable noice

### ISSUE THREAD

**Issue by ijsnow** [LazyVim/LazyVim#553]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.0-dev-958+g264fb6945-dirty

### Operating system/version

MacOS 13.0.1 (22A400)

### Describe the bug

Noice is a cool idea but it's not quite what I want in my vim setup. I don't necessarily want popups. I can ignore most of them other than when I'm editing `Cargo.toml` files and cargo workspace errors pop up repeatedly (each time rust-analyzer is invoked) and it renders me unable to fix my problem until (the lsp client gives up).

Did I miss a special flag for the noice plugin?

### Steps To Reproduce

1. Place this file in `lua/plugins/disabled.lua`:

```
return {
  { "folke/noice.nvim", enabled = false }, " does not get disabled
  { "echasnovski/mini.pairs", enabled = false }, " gets disabled
}
```

2. Open nvim
3. Do something in your workflow that sends a message that noice will display

### Expected Behavior

Messages aren't displayed by noice.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
  { "folke/noice.nvim", enabled = false },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by Dolvur** [comment]
I think you want to disable the "rcarriga/nvim-notify" plugin instead to get rid of the pop-ups. I was also getting annoyed by them overlaying the screen and found the plugin when browsing through [ui.lua](https://github.com/LazyVim/LazyVim/blob/79fe0455a02b791eae26e9934fdbaf075d9522ae/lua/lazyvim/plugins/ui.lua)

**Comment by 0atman** [comment]
I think it still can't be disabled, and the original bug stands, even though @ijsnow found a workaround for their issue.

I can't disable noice with this user plugin:

```lua
return {
  -- fix noice
  { "folke/noice.nvim", enabled = false },
}
```

**Comment by 0atman** [comment]
Wait, I'm confused, there's no mention of Noice outside of the user plugin config I just added...

```sh
$ pwd
/home/oatman/.config/nvim
$ rg noice
lua/plugins/noice.lua
2:  -- fix noice
3:  { "folke/noice.nvim", enabled = false },
```

**Comment by pynappo** [comment]
> Wait, I'm confused, there's no mention of Noice outside of the user plugin config I just added...
> 
> ```shell
> $ pwd
> /home/oatman/.config/nvim
> $ rg noice
> lua/plugins/noice.lua
> 2:  -- fix noice
> 3:  { "folke/noice.nvim", enabled = false },
> ```

lazyvim is just a plugin that itself contains a bunch of lazy.nvim specs to other plugins. the idea is that the configuration is largely hidden away to keep the user config folder minimal.

[lazyvim's starter config installs lazyvim and imports](https://github.com/LazyVim/starter/blob/741ff3aa70336abb6c76ee4c49815ae589a1b852/lua/config/lazy.lua#L12) lazyvim's lazy.nvim [specs.](https://github.com/LazyVim/LazyVim/tree/main/lua/lazyvim/plugins)

**Comment by 0atman** [comment]
@pynappo ah! thank you.

So I think this bug stands, I can reproduce it: Noice can't be disabled. 

I can make a new issue if appropriate?

**Comment by pynappo** [comment]
Not really sure, I'm not able to reproduce your bug. I have a fresh install of the lazyvim starter and put the snippet you posted in the specified location and noice disables for me just fine (as in, the cmdline is at the bottom of the screen).
![image](https://github.com/LazyVim/LazyVim/assets/43484729/0284b390-f7d7-4db8-af90-03b760f37470)

**Comment by dpetka2001** [comment]
I can confirm `noice` can be disabled just fine with the code provided above with a fresh LazyVim starter.

**Comment by 0atman** [comment]
Oh! Mine too! I thought Noice also did the notifications?

**Comment by 0atman** [comment]
It's these that I'm trying to remove:

![Screenshot from 2024-02-26 09-58-33](https://github.com/LazyVim/LazyVim/assets/114097/10ede0f8-c665-4661-9330-de185b6df384)

**Comment by dpetka2001** [comment]
Those come from `nvim-notify`.

**Comment by 0atman** [comment]
oh thank you! I will look into that config :-)

**Comment by 0atman** [comment]
```lua
return {
  { "rcarriga/nvim-notify", enabled = false },
}
```

Fixed it, my notifications are now small and in the bottom right where they should be! :tada:
