### ISSUE TITLE
feature: Change default `gt` mapping to `gy` to not overwrite vim's tabnext mapping

### ISSUE THREAD

**Issue by dimroc** [LazyVim/LazyVim#554]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

https://github.com/LazyVim/LazyVim/blob/7ce1b1519a45f48aa4b5f35b7b7a886b42fe56d8/lua/lazyvim/plugins/lsp/keymaps.lua#L19

The default mappings overwrite vim's standard tab navigation.

### Describe the solution you'd like

Change the mapping from `gt` to `gy` to prevent collision.

### Describe alternatives you've considered

I have used the current LazyVim's mapping of `<leader><tab>]` but it's 3 keystrokes and too slow.

**Comment by Gasol** [comment]
The suggested fix does not resolve the issue. Instead, it merely override the default key mapping from 'tabnext' to '[tabprevious](https://vimdoc.sourceforge.net/htmldoc/tabpage.html#gT)'. These key mappings have been the default for navigating tabs in Vim for many years.

**Comment by dimroc** [comment]
Agreed @Gasol. @folke, can we update the mapping to `gy` instead so we don't override the classic vim defaults of `gt` (tabnext) and `gT`(tabprev)?
