### ISSUE TITLE
bug: unable to update mason

### ISSUE THREAD

**Issue by MohammadTheShia** [LazyVim/LazyVim#555]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.0-1210-gd367ed9b2

### Operating system/version

Ubuntu 22.04

### Describe the bug

lazy update would fail due to mason update error:
error: Your local changes to the following files would be overwritten by checkout:
        	PACKAGES.md
        Please commit your changes or stash them before you switch branches.
        Aborting

### Steps To Reproduce

1. start nvim
2. run `:lazy` command
3. press `U` key to perform an update

### Expected Behavior

update all packages successfully.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
The error clearly tells you that you made changes to a file of mason. You shouldn't do that. Revert the changes and update
