### ISSUE TITLE
Disable Transparency and add border lines for LSP

### ISSUE THREAD

**Issue by Fabyao** [LazyVim/LazyVim#556]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

This is a subjective request and personally, I find the transparency with no border lines for LSP distracting and confusing. Having read the docs, its not obvious how one would disable the transparency and add border lines.

Apologies if I have missed it in the doc or there is a trivial way to do it.

### Describe the solution you'd like

I have tried the following. However, it seems something else is overriding these settings:
`vim.lsp.handlers["textDocument/hover"] = vim.lsp.with(vim.lsp.handlers.hover, {
        border = border,
      })
vim.lsp.handlers["textDocument/signatureHelp"] = vim.lsp.with(vim.lsp.handlers.signature_help, {
        border = border,
      })`

### Describe alternatives you've considered

Not found any

**Comment by Fabyao** [comment]
After some research, I have now found what controls transparency.
`opt.pumblend = 0`

For borders, you can add the following to your `hrsh7th/nvim-cmp` config:

```
local cmp_window = require "cmp.config.window"
window = {
  completion = cmp_window.bordered(),
  documentation = cmp_window.bordered(),
 },
```

For consistency, you can also add these to have borders:

`
local float = {
    focusable = true,
    style = "minimal",
    border = "rounded",
  }
vim.lsp.handlers["textDocument/hover"] = vim.lsp.with(vim.lsp.handlers.hover, float)
      vim.lsp.handlers["textDocument/signatureHelp"] = vim.lsp.with(vim.lsp.handlers.signature_help, float)`

Will close this ticket now. Sorry about the noise.

**Comment by Nikola-Milovic** [comment]
@Fabyao where can we add the `vim.lsp.handlers` to?

**Comment by robin-whg** [comment]
@Nikola-Milovic Did you figure it out? I can't figure it out.
