### ISSUE TITLE
bug: leap/flit config issue

### ISSUE THREAD

**Issue by trevarj** [LazyVim/LazyVim#56]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.8.2

### Operating system/version

Linux

### Describe the bug

Bad UX when doing a dot-repeat motion due to flit.nvim.

If you happen to do a dot-repeat after a motion (see reproduction steps below) it appears as if nvim has frozen. See: https://github.com/ggandor/flit.nvim/issues/13#issuecomment-1367265412

### Steps To Reproduce

1. Open a blank file
2. Type "delete" on one line. `<esc>yypggdtt` to delete till letter 't' on first line "delete"
3. Go to next line and press '.' to repeat on second "delete"
4. Appears that nvim has frozen, but you can `C-c` to get unstuck...

### Expected Behavior

User is aware that they are in flit mode or maybe make <esc> exit it 😕 
or https://github.com/tpope/vim-repeat added to dependencies of `leap.nvim`

### Repro

```Lua
-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	"folke/tokyonight.nvim",
	"folke/LazyVim",
	{
		"ggandor/leap.nvim",
		lazy = false,
		dependencies = { { "ggandor/flit.nvim", opts = { labeled_modes = "nv" } } },
		config = function(_, opts)
			local leap = require("leap")
			for k, v in pairs(opts) do
				leap.opts[k] = v
			end
			leap.add_default_mappings(true)
		end,
	},
	-- add any other plugins here
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by blakedietz** [comment]
Can confirm I've experienced this bug.

**Comment by folke** [comment]
Added vim-repeat. Thank you!
