### ISSUE TITLE
feature: overriding default whichkey hint

### ISSUE THREAD

**Issue by kha-dinh** [LazyVim/LazyVim#563]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

I want to add new which-key hints on top of the default one (e.g., "`+telescope`"). 
However, currently, there is no elegant way to do it. 
I need to copy the which-key configuration from [editor.lua](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/editor.lua), then run `wk.register` on the new set of keymaps.

### Describe the solution you'd like

I think additional keymaps could be exposed to the opt interface (`opt.keymaps = keymap`). The configuration script then replaces the default hints with the new ones.

### Describe alternatives you've considered

An alternative is to copy configs from `editor.lua` into your config.

**Comment by dpetka2001** [comment]
You don't have to copy the default which-key configuration again. Just add the new keys you want and they will be merged with the default which-key keymaps.
```lua
return {
  -- Modify which-key keys
  {
    "folke/which-key.nvim",
    opts = function()
      require("which-key").register({
        ["<leader>xl"] = {
          name = "+LSP (Telescope)",
        },
        ["<leader>un"] = {
          name = "+Notifications",
        },
        ["<leader>ut"] = {
          name = "+Treesitter",
        },
        ["<leader>cw"] = {
          name = "+LSP Workspace",
        },
        ["<leader>t"] = {
          name = "+Terminal",
        },
      })
    end,
  },
}
```
here I only specify the namespaces to be recognized by which-key and then in each plugin spec I specify the keys with appropriate description to be recognized.
