### ISSUE TITLE
bug: custom lsp config does not apply

### ISSUE THREAD

**Issue by storopoli** [LazyVim/LazyVim#565]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0

### Operating system/version

Linux

### Describe the bug

My objective is to override LazyVim/Mason defaults for `texlab`.

Following the documentation I've added a file `lua/plugins/lsp-texlab` in a config built from the starter template.
Additionally, this config was written as described in the [`texlab` LSP server configurations](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#texlab).

```lua
return {
  -- add texlab custom options to lspconfig
  "neovim/nvim-lspconfig",
  ---@class PluginLspOpts
  opts = {
    ---@type lspconfig.options
    servers = {
      -- texlab will be automatically installed with mason and loaded with lspconfig
      texlab = {
        settings = {
          build = {
            executable = "tectonic",
            args = {
              "-X",
              "build",
            },
            isContinuous = false,
            onSave = true,
          },
          formatterLineLength = 80,
          latexFormatter = "texlab",
        },
      },
    },
  },
}
```

But somehow it is not working. `texlab` is supposed to call `tectonic` instead of `latexmk`.

### Steps To Reproduce

1. Clone the starter template
2. Create a `lua/plugins/lsp-texlab` with the contents in the snippet above
3. With `tectonic` installed run `tectonic -X new`
4. open the `src/index.tex` in neovim
5. run `TexlabBuild`

### Expected Behavior

LazyVim LSP should use the custom settings

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by storopoli** [comment]
My bad I missconfigured something. It works flawlessly now!

**Comment by roao** [comment]
it works for me like:
```lua
return {
  {
    "neovim/nvim-lspconfig",
    opts = {
      servers = {
        texlab = {
          settings = {
            texlab = {
              inlayHints = {
                -- labelDefinitions = false,
                -- labelReferences = false,
                maxLength = 20,
              },
            },
          },
        },
      },
    },
  },
}
```
u can use `LspInfo` to check the configs of `texlab`
but the configs doesn't work at first when i open a `.tex` file until i change to insert mode and type a word, then the configs will work.
so weird.
