### ISSUE TITLE
bug: Disabling default options does not work

### ISSUE THREAD

**Issue by Ram-Z** [LazyVim/LazyVim#566]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0-dev-920+gc9b0fe1f41

### Operating system/version

Arch Linux

### Describe the bug

Trying to disable the default options following the [docs](https://www.lazyvim.org/configuration#default-settings) does not work. They are still loaded.

Loading the options seems to happen within [`init`](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/init.lua#L164), whereas merging `opts` happens in `setup` after the default `options.lua` has already been loaded. `lazyvim.config.init` is called from [`plugins/core.lua`](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/core.lua#L1).

Disabling `autocmds` and `keymaps` the same way works. Modifying `defaults.options` in `lua/lazyvim/config/init.lua` works as expected.

### Steps To Reproduce

1. Disable `options` using this plugin in `lua/plugins/disable-options.lua`
   ```lua
   return {
     {
       "LazyVim/LazyVim",
       opts = {
         defaults = {
           autocmds = false,  -- works
           options = false,  -- does not work
           keymaps = false,  -- works
         },
       },
     },
   }
   ```
2. run `nvim -V1 --headless -c "verbose set splitbelow? | q"`
   ```
     splitbelow
   	Last set from ~/.local/share/nvim/lazy/LazyVim/lua/lazyvim/config/options.lua line 38%
   ```

### Expected Behavior

When setting `defaults.options = false`, the default options should not be loaded.

### Repro

Run with `nvim -u repro.lua --headless -V1 -c "verbose set splitbelow? | q"`, first run is a bit verbose, but will end printing that `splitbelow` was set and where. Second run only prints the setting.

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "LazyVim/LazyVim",
    -- import lazyvim.plugins.core.lua which calls lazyvim.config.init
    import = "lazyvim.plugins",
    -- setting default to false is ignored
    opts = {
      defaults = {
        options = false,
      },
    },
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
```

**Comment by folke** [comment]
You're right. Its not possible to disable options this way. I've updated the docs and added a work-around: https://www.lazyvim.org/configuration#default-settings

**Comment by dpetka2001** [comment]
You're mentioning that to disable default options we should add `package.loaded["lazyvim.config.options"] = true` to our `init.lua`. Do you maybe mean to set it to `false`? Or am I  misunderstanding the use of `package.loaded()`?

**Comment by folke** [comment]
setting it to anything that isn't `nil` will work

**Comment by Ram-Z** [comment]
Thanks for the workaround, works great.
