### ISSUE TITLE
bug: /0.8.3/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 2765 for language vim

### ISSUE THREAD

**Issue by JasterV** [LazyVim/LazyVim#569]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.3

### Operating system/version

Pop!_OS 22.04 LTS x86_64

### Describe the bug

[Screencast from 04-12-2023 12:27:58 PM.webm](https://user-images.githubusercontent.com/49537445/231431125-b9b8cea8-4b46-4b8a-a1d4-9e6d99f256b6.webm)

### Steps To Reproduce

1. Install neovim 0.8.3
2. Install LazyVim
3. Copy the example.lua into core.lua on the plugins folder
4. Thats it lol

### Expected Behavior

To not display any errors

**Comment by JasterV** [comment]
As a tip, if I switch to neovim 0.8.2 everything works fine

**Comment by PRSouzaFM** [comment]
From my personal experience, this is due to having multiple parsers in the runtime directory. Can you try running
`:echo nvim_get_runtime_file('parser', v:true)` ?

**Comment by folke** [comment]
https://github.com/nvim-treesitter/nvim-treesitter#i-get-query-error-invalid-node-type-at-position
