### ISSUE TITLE
bug: neo-tree does not load when opening a directory after start

### ISSUE THREAD

**Issue by Ram-Z** [LazyVim/LazyVim#572]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0-dev-920+gc9b0fe1f41

### Operating system/version

Arch Linux

### Describe the bug

When opening a folder after start nvim, neo-tree is not loaded.

neo-tree should hijack the call to netrw, but since it is not loaded yet, it cannot do that.

### Steps To Reproduce

1. `nvim -u repro.lua`  _with the file below_
2. `:e .`  _edit any directory_
   *  Notice that netrw is used instead of neo-tree
4. <kbd>Space+fe</kbd>  _trigger the loading of neo-tree_
5. `:e .` _edit any directory_
   * Notice that neo-tree now opens the dir

### Expected Behavior

Opening a dir should be consistent, neo-tree should be loaded automatically when an attempt to open a dir in a buffer is made.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	"folke/tokyonight.nvim",
	"folke/LazyVim",
	-- add any other plugins here
	{
		"nvim-neo-tree/neo-tree.nvim",
		dependencies = {
			"nvim-lua/plenary.nvim",
			"nvim-tree/nvim-web-devicons", -- not strictly required, but recommended
			"MunifTanjim/nui.nvim",
		},
		-- something to make it lazy load
		keys = { { "<space>fe" } },
	},
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by Ram-Z** [comment]
Had a quick look at trying to address this while still lazy loading neo-tree... It seems neo-tree listens to the `BufEnter` event, then checks if it should be replacing netrw on directories.

When I saw the `event` option in `lazy.nvim` I thought it could be used to listen to an event and conditionally load the plugin. But it seems to only support a list of events.

**Comment by folke** [comment]
If you want this behavior, you should disable lazy loading of neo-tree. (`lazy=false`)

**Comment by Ram-Z** [comment]
Would it be possible to extend `lazy.nvim` to support a callback on events to decide whether a certain triggered event should load the plugin?

```lua
---@type LazyPluginSpec
{
  "nvim-neo-tree/neo-tree.nvim",
  lazy = true,
  event = {
    BufEnter = function()
      local stat = vim.loop.fs_stat(vim.api.nvim_buf_get_name(0))
      return stat and stat.type == "directory"
    end
  }
}
```

Something like this, if the function returns `true` the plugin is loaded and the event handler inactivated.
 It's a generic way of conditionally lazy loading on an event, I think it would have many other uses.

Maybe it would be better to have a separate `event_handler` opt?
```lua
---@type LazyPluginSpec
{
  "nvim-neo-tree/neo-tree.nvim",
  lazy = true,
  event = { "BufEnter", "BufWinEnter" },
  event_handler = function(_, event)
      if event == "BufEnter"
        local stat = vim.loop.fs_stat(vim.api.nvim_buf_get_name(0))
        return stat and stat.type == "directory"
      else
        return something_else()
    end
  }
}
```

**Comment by folke** [comment]
no
