### ISSUE TITLE
help: How can I disable ENTER key with cmp 

### ISSUE THREAD

**Issue by Cruising0904** [LazyVim/LazyVim#573]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9

### Operating system/version

Arch linux

### Describe the bug

While using cmp, pressing enter key acts completion. I didn't map to it. I seem to not find a way to disable it
![image](https://user-images.githubusercontent.com/29267295/231734352-e7c1c8d5-f591-4fb7-b1be-a20925446286.png)

When I want to move the cursor to below the line pressing enter against to what I  wanted. 
Before convert to lazyvim it was fine, no complete action. 

My config like using super tab so there's nothing related to Enter below the code I am sure.

### Steps To Reproduce

1. I could manage to setup super tab 
2. but can not disable enter key
3. quit neovim and enter again not works
4. at the moment using ^j to nbsp

### Expected Behavior

It's not a bug I think. I want to find a way to configure this

**Comment by Cruising0904** [comment]
Thank you! Solved because of you :)

**Comment by diego898** [comment]
@Cruising0904 How did you fix it?

**Comment by rkabrick** [comment]
I have the same question... I followed the link and added the suggested configuration to my own but I still am accepting the first autocomplete suggestion every time I hit enter and its maddening

**Comment by dpetka2001** [comment]
@rkabrick What did you add to your configuration? Show the code.

**Comment by victorbonato** [comment]
```lua
return {
  {
    "hrsh7th/nvim-cmp",
    dependencies = {
      "hrsh7th/cmp-emoji",
      "windwp/nvim-autopairs",
      opts = {},
    },
    keys = {
      {
        "<C-y>",
        function()
          require("cmp").mapping.confirm({ select = true })
        end,
      },
    },
    opts = function(_, opts)
      local cmp = require("cmp")
      local cmp_autopairs = require("nvim-autopairs.completion.cmp")
      cmp.event:on("confirm_done", cmp_autopairs.on_confirm_done())
      table.insert(opts.sources, { name = "emoji" })
      -- Disable ENTER completion
      opts.mapping = cmp.mapping.preset.insert(vim.tbl_deep_extend("force", opts.mapping, {
        ["<CR>"] = vim.NIL,
      }))
    end,
  },
}
```
This is my configuration if it helps, it fixed the problem for me

**Comment by dpetka2001** [comment]
@victorbonato You don't need the `cmp.mapping.preset.insert`, just the `vim.tbl_deep_extend` function to make it work. I don't know if you took it from some previous answer of mine that I gave in the past, but that was due to my lack of knowledge at the time. Also i don't quite understand why you define `<C-y>` in the `keys` section instead of in `opts.mapping` where you also disable the `Enter` key as well.

**Comment by mgeier** [comment]
It seems the default completion tool has been changed from `nvim-cmp` to `blink.cmp`.

I was able to disable the ENTER key with this:

```lua
return {
  "saghen/blink.cmp",
  opts = {
    keymap = {
      preset = "default",
    },
  },
}
```
