### ISSUE TITLE
bug: inconsistent use of unicode zzz character

### ISSUE THREAD

**Issue by perlguy** [LazyVim/LazyVim#578]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-46+ge23c6ebed

### Operating system/version

Linux (arch)

### Describe the bug

Two different unicode characters being used for "zzz", one of which exists in nerd fonts, the other does not.  Not sure if this is intentional - if it IS intentional, then it's not clear what the "broken" character is supposed to be.

000f04b2 (󰒲) is missing (not in nerd fonts or any other fonts I have installed), and used in the following locations

```
grep -R -n 󰒲  .
./lazy/lazy.nvim/lua/lazy/core/config.lua:59:      lazy = "󰒲 ",
./lazy/lazy.nvim/README.md:347:      lazy = "󰒲 ",
./lazy/lazy.nvim/doc/lazy.nvim.txt:443:          lazy = "󰒲 ",
./lazy/LazyVim/lua/lazyvim/plugins/ui.lua:249:        dashboard.button("l", "󰒲 " .. " Lazy", ":Lazy<CR>"),
```

0001f4a4 (💤) works, and is used in these locations:

```
grep -R -n 💤 .
./lazy/lualine.nvim/lua/lualine/extensions/lazy.lua:13:      return 'lazy 💤'
./lazy/lazy.nvim/README.md:1:# 💤 lazy.nvim
./lazy/lazy.nvim/README.md:462:      lazy = "💤 ",
./lazy/LazyVim/README-DE.md.txt:39:LazyVim ist ein Neovim setup aufgebaut auf [💤 lazy.nvim](https://github.com/folke/lazy.nvim). 
./lazy/LazyVim/README-DE.md.txt:52:- 💤 Passe deine Konfiguration einfach an und erweitere diese mit [lazy.nvim](https://github.com/folke/lazy.nvim)
./lazy/LazyVim/README.md:39:LazyVim is a Neovim setup powered by [💤 lazy.nvim](https://github.com/folke/lazy.nvim)
./lazy/LazyVim/README.md:52:- 💤 Easily customize and extend your config with [lazy.nvim](https://github.com/folke/lazy.nvim)
./lazy/LazyVim/README-CN.md:39:LazyVim 是由 [💤 lazy.nvim](https://github.com/folke/lazy.nvim) 驱动的一套 Neovim 配置，可以轻松自定义和扩展您的配置。
./lazy/LazyVim/README-CN.md:50:- 💤 使用 [lazy.nvim](https://github.com/folke/lazy.nvim) 轻松自定义和扩展您的配置
./mason/packages/lua-language-server/libexec/script/service/service.lua:207:        info.text = "💤Lua"
```

### Steps To Reproduce

Install lazyvim by cloning https://github.com/LazyVim/starter.
Start nvim and look at dashboard (missing glyph for Lazy entry).
Hitting "l" from dashboard (Screenshot below) shows both missing and working glyphs (missing at the top, working on  statusline below).
![image](https://user-images.githubusercontent.com/822223/231883498-a600fd98-7fb1-4a62-ac5d-a3e3bd4757c9.png)

### Expected Behavior

Have all UI characters/glyphs show properly if a nerd font is installed.

**Comment by dpetka2001** [comment]
There was a problem due the zzz icon being deprecated from nerd-fonts i think? Thus there was a change, you can see [here](https://github.com/LazyVim/LazyVim/issues/365). Have you updated your nerd-fonts? You may be using an older version and don't have the icon currently used in Lazyvim? Because I have no issue with current icons after I upgraded nerd fonts.

**Comment by perlguy** [comment]
Looks like the version of nerd-fonts-complete from the AUR is slightly out of date.  I have now manually downloaded the dejavu font directly from NF site, and it works as expected.  I *did* search for that new glyph by hexcode on the NF site, but I think I got the codes swapped and thought I already had the version with the new glyph.

It turns out I had OTHER fonts (unrelated to NF) still providing the glyph that has  been removed from NF.  I used the script below to find out exactly which fonts I had providing each glyph:

[https://gist.github.com/akostadinov/202550a1e2fd4ea8cf523d91b437fa09](url)

I think the only LazyVim files left with the old glyph are all README.md files, so it's not a huge issue at this point.  I'm ok with closing this as not-a-bug. (but please do update those READMEs so they use the new NF glyph.)

Thanks for the quick reply, and pointing me at the recent update to nerd fonts.
