### ISSUE TITLE
bug: Undeterministic behavior when disabling C-n in nvim-cmp 

### ISSUE THREAD

**Issue by bryant-video** [LazyVim/LazyVim#589]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.3

### Operating system/version

MacOS 12.5.1

### Describe the bug

I tried to disable C-n for selecting next item as described in other issue.
Here is the full spec 
```
return {
  "hrsh7th/nvim-cmp",
  dependencies = {
    "hrsh7th/cmp-emoji",
  },
  ---@param opts cmp.ConfigSchema
  opts = function(_, opts)
    local has_words_before = function()
      unpack = unpack or table.unpack
      local line, col = unpack(vim.api.nvim_win_get_cursor(0))
      return col ~= 0 and vim.api.nvim_buf_get_lines(0, line - 1, line, true)[1]:sub(col, col):match("%s") == nil
    end

    local luasnip = require("luasnip")
    local cmp = require("cmp")

    opts.mapping = vim.tbl_extend("force", opts.mapping, {
      ["<Tab>"] = cmp.mapping(function(fallback)
        if cmp.visible() then
          cmp.select_next_item()
        elseif luasnip.expand_or_jumpable() then
          luasnip.expand_or_jump()
        elseif has_words_before() then
          cmp.complete()
        else
          fallback()
        end
      end, { "i", "s" }),
      ["<S-Tab>"] = cmp.mapping(function(fallback)
        if cmp.visible() then
          cmp.select_prev_item()
        elseif luasnip.jumpable(-1) then
          luasnip.jump(-1)
        else
          fallback()
        end
      end, { "i", "s" }),
    })

    opts.mapping = cmp.mapping.preset.insert(vim.tbl_deep_extend("force", opts.mapping, {
      ["<C-n>"] = vim.NIL,
    }))
  end,
}
```
i also tried to do `cmp.config.disable` and also tried to combine this `["<C-n>"] = vim.NIL` to the opts.mapping function above where we set Tab and S-Tab. 

What happens is it will be disabled at first, but if i quit my coding file FileA, open another coding file FileB with nvim, C-n is back into effect, and if i now try FileA again, C-n is back as well. 
Thanks in advance for helping out!

Some more context: Im using tabnine.nvim, and i set C-n for AI autocompletion

### Steps To Reproduce

1. Copy the nvim-cmp above
2. open a coding file and test it out, it will be disabled
3. quit and open another coding file and back to this file, C-n is back
4. If that still doesnt reproduce the problem, try restart the computer, and you will see C-n is back

### Expected Behavior

C-n is disabled forever

**Comment by folke** [comment]
This is not a LazyVim issue. Check the cmp docs/issues
