### ISSUE TITLE
bug: EsLint  does not recognize my .eslintrc

### ISSUE THREAD

**Issue by mendesbarreto** [LazyVim/LazyVim#591]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0

### Operating system/version

macOS Ventura 13.2.1

### Describe the bug

I migrated my configuration to use LazzyVim, and now my eslint does not recognize .eslintrc

This is what happened to my project after I installed the Lazzy vim:
![Screenshot 2023-04-16 at 11 45 26 AM](https://user-images.githubusercontent.com/2684784/232324325-585320fd-08da-4e16-bff2-17a03e7cdd13.png)

### Steps To Reproduce

1. Follow the instructions of https://www.lazyvim.org/installation
2. Uncomment the extras typescript, eslint and prettier located on config/lazy.lua

Also tried to add the following:
https://www.lazyvim.org/plugins/extras/linting.eslint
https://www.lazyvim.org/plugins/extras/formatting.prettier

But the result still:
![Screenshot 2023-04-16 at 12 26 26 PM](https://user-images.githubusercontent.com/2684784/232326572-1a373d20-e310-44ff-bdef-ef2c460d21e4.png)

The project to test: https://github.com/mendesbarreto/hot-reload-typescript-template

### Expected Behavior

Estlint should read my [.eslintrc.cjs](https://github.com/mendesbarreto/hot-reload-typescript-template/blob/master/.eslintrc.cjs) and do not display `Relative import path` error.

### Repro

I am not sure what I should to add here =(

## My Config
[nvim.zip](https://github.com/LazyVim/LazyVim/files/11242851/nvim.zip)

**Comment by folke** [comment]
Those are errors from denols.

To disable deno in this project, create a file `.neoconf.json` with:

```json
{
  "lspconfig": {
    "denols": false
  }
}
```

**Comment by mendesbarreto** [comment]
> Those are errors from denols.
> 
> To disable deno in this project, create a file `.neoconf.json` with:
> 
> ```json
> {
>   "lspconfig": {
>     "denols": false
>   }
> }
> ```

Hello @folke that worked for me, thank you so much.

Wouldn't it be better to have this flag set to true by default? I ask because the number of projects that use React, Express, and React Native far outweighs those that use Deno. For example, on my machine, I have 10 Node projects, none of which are in Deno, now I need to put this config fine in all of them =( .

**Comment by folke** [comment]
That's something you'll have to pick up with lspconfig.
