### ISSUE TITLE
issue: Little delay when pressing escape

### ISSUE THREAD

**Issue by SpatialSymmetry** [LazyVim/LazyVim#593]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0-dev-46+ge23c6ebed

### Operating system/version

linux

### Describe the bug

I recently installed lazy vim and I am currently experiencing a slight delay when transitioning from insert mode to normal mode. It appears that one of the plugins that come with lazy vim is causing this issue, as it introduces a feature where pressing hjkl during this short delay moves lines around. I would like to disable this feature, but I am unsure which plugin is responsible for it. I believe this feature may not be suitable for everyone, especially for those who type at a fast pace like myself. Would anyone happen to have any suggestions on how to disable this feature or which plugin may be causing it? Thank you for your assistance.

### Steps To Reproduce

default lazyvim.

### Expected Behavior

no delay when pressing escape.

**Comment by folke** [comment]
That's your terminal. See https://github.com/LazyVim/LazyVim/discussions/163

**Comment by SpatialSymmetry** [comment]
Thank you for your prompt response! It seems that the issue is being caused by tmux.
