### ISSUE TITLE
bug: <leader>ul to toggle relative number toggles line number

### ISSUE THREAD

**Issue by rudfol** [LazyVim/LazyVim#608]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.0

### Operating system/version

win 10

### Describe the bug

Hi,

The normal default keymap malfunctions to toggle line number instead of relative number.

### Steps To Reproduce

1. Default lazyvim
2. Execute leader key with 'ul'
3. Toggles line number

### Expected Behavior

Toggle relative number

**Comment by folke** [comment]
The keymap is to toggle line numbers, not to toggle relative numbers

**Comment by rudfol** [comment]
Sorry about that I missed another Util.toggle which toggles 'number'. In effect toggling both relative num and num.

Cheers,

Joon
