### ISSUE TITLE
bug:  Load gruvbox colorscheme with options

### ISSUE THREAD

**Issue by loiccoyle** [LazyVim/LazyVim#62]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.8.2

### Operating system/version

Linux 6.1.5-arch2-1

### Describe the bug

I-m trying to load the `ellisonleao/gruvbox.nvim` colorscheme with the options:
```lua
return {
  "ellisonleao/gruvbox.nvim",
  opts = {
    contrast = "hard",
    transparent_mode = true,
  },
  config = function(_, opts)
    require("gruvbox").setup(opts)
  end,
}
```

I set `LazyVim` to load `gruvbox` with:
```lua
return {
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = function()
        require("gruvbox").load()
      end,
    },
  },
}
```

The colorscheme is set to `gruvbox` but the options aren't taken into account.

### Steps To Reproduce

I wasn't able to reproduce the bug using the recommended `repro.lua`, but if you add the provided plugin spec to a fresh setup of `LazyVim` the issue is reproducible.

1. Fresh install `LazyVim`
2. Add the provided plugin spec in the `~/.config/nvim/lua/plugins/` folder
4. Start nvim

### Expected Behavior

`nvim` should start with the  `gruvbox` colorscheme  using the configured options, in this case with `transparent_mode` and using the `hard` variant. Instead the default `gruvbox` options are used.

### Repro

```Lua
return {
  {
    "ellisonleao/gruvbox.nvim",
    opts = {
      contrast = "hard",
      transparent_mode = true,
    },
    config = function(_, opts)
      require("gruvbox").setup(opts)
    end,
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = function()
        require("gruvbox").load()
      end,
    },
  },
}
```

**Comment by folke** [comment]
It seems that gruvbox's latest release is very outdated. Add `version = false` to the gruvbox spec to fix it.

You also don't need the `config()` function in there, so just remove that too.

**Comment by loiccoyle** [comment]
Tthanks for your help and all your great plugins!
