### ISSUE TITLE
bug: Cannot override keymaps configured in "keys" property of lazy.nvim

### ISSUE THREAD

**Issue by stefanwatt** [LazyVim/LazyVim#63]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.8

### Operating system/version

Arch Linux

### Describe the bug

Setting a keymap that is already being set inside the "keys" property of a plugin will not work, as it'll be overridden once that plugin loads.

### Steps To Reproduce

1. clone lazyvim starter template
2. set `keymap("n", "<leader>/", "gcc", opts)` inside `lua/config/keymaps.lua`
3. press the key combination

### Expected Behavior

keymap works -> line/ block gets commented

### Actual Behavior
custom keymap has no effect
leader + / stlil opens telescope live grep as defined here: 
https://github.com/LazyVim/LazyVim/blob/5987570b5213c9a8b756fd8a169f8e92c05f5bfa/lua/lazyvim/plugins/editor.lua#L53

**Comment by folke** [comment]
I just pushed an update to `lazy.nvim`, so make sure to update that first.

Then you can skip a certain key for telescope with the code below:

```lua
return {
  "nvim-telescope/telescope.nvim",
  keys = {
    { "<leader>/", vim.NIL },
  },
}
```
