### ISSUE TITLE
bug: keymaps <C-j> <C-k> not working

### ISSUE THREAD

**Issue by multivac61** [LazyVim/LazyVim#632]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0

### Operating system/version

MacOS 13.2.1

### Describe the bug

Unable to use `<C-j>` and `<C-k>` to "Go to upper/lower window"

`<C-w> j/k` work as expected

### Steps To Reproduce

1. Install as mentioned in https://www.lazyvim.org/installation
2. Split window using `<S> w -`
3. Unable to navigate using default keybindings `<C-j> <C-k>`

### Expected Behavior

Navigate up/down windows using default keybindings `<C-j> <C-k>`

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Not LazyVim. Probably a mis-configured terminal or tmux...

**Comment by multivac61** [comment]
Sorry, you are right.

**Comment by mauromotion** [comment]
> Sorry, you are right.

May I ask you how you solved? I have the same issue, <c-hjkl> navigation keybindings to move in other windows stopped working for some reason. Both in alacritty or kitty, either inside or outside tmux, still the same issue.

**Comment by dpetka2001** [comment]
You have those mappings remapped to `harpoon.ui.nav_file` in your [config](https://github.com/mauromotion/dotfiles/blob/d798a2c47f07a3313cdcf1d43cdf918d506d0d70/nvim/lua/config/keymaps.lua#L11-L22). That's why they're not working to move in between Neovim windows.

**Comment by mauromotion** [comment]
Good call thanks!

I literally installed harpoon late at night at some point just to try it out and completely forgot about it...all good now!
