### ISSUE TITLE
bug: formatter does not work properly inside symlinks

### ISSUE THREAD

**Issue by albertfgu** [LazyVim/LazyVim#649]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0

### Operating system/version

Debian 10

### Describe the bug

I started putting my LazyVim dotfiles under my version control system (a common system which involves `gnu stow` to symlink https://alexpearce.me/2016/02/managing-dotfiles-with-stow/) and my formatter started behaving erratically. In particular, it would always convert spaces to tabs. I eventually traced it to the fact that symlinks are involved.

### Steps To Reproduce

**Fresh install of LazyVim starter**

```
rm -rf ~/.local/share/nvim ~/.local/state/nvim ~/.cache/nvim
rm -rf ~/.config/nvim
git clone https://github.com/LazyVim/starter ~/.config/nvim
rm -rf ~/.config/nvim/.git
```

**Symlink config folder**

```
cd ~/.config/nvim
mv lua ~
ln -s ${HOME}/lua .
ls -l  # double check the symlink
```

**Edit file**

1. `nvim lua/config/lazy.lua`
2. `<space>cf` or `:w` to trigger formatter
3. all spaces are converted to tabs in the file

### Expected Behavior

Note that only the files inside the symlink are affected; the files outside the symlink (e.g. in the above example, `nvim ~/.config/nvim/init.lua`) behave normally.

To be honest, this doesn't seem like a LazyVim issue _per se_, but I couldn't find any information about it online. Is this a known issue or has anyone seen something like this before? 

### Repro

```Lua
N/A (see Steps to Reproduce)
```

**Comment by folke** [comment]
indeed not a lazyvim issue

**Comment by azzamsa** [comment]
@albertfgu what is your final solution? I am having the same issue.
