### ISSUE TITLE
bug: error raised after enabling copilot

### ISSUE THREAD

**Issue by you-n-g** [LazyVim/LazyVim#656]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.8.1

### Operating system/version

Ubuntu 18.04.2 LTS

### Describe the bug

I followed the following instruction to enable copilot

![image](https://user-images.githubusercontent.com/465606/233686193-5d4914b3-d090-4725-aaa5-40a10e11f95f.png)

The copilot works.

But it always raise following error when I open an script file (e.g. shell script)
![image](https://user-images.githubusercontent.com/465606/233686452-50437a35-c62e-4491-951a-4ddc3a8bdd9e.png)

### Steps To Reproduce

Described in `Describe the bug`

### Expected Behavior

Described in `Describe the bug`

**Comment by you-n-g** [comment]
[err.txt](https://github.com/LazyVim/LazyVim/files/11297569/err.txt)
The full content of my error

**Comment by folke** [comment]
Seems to be a Neovim issue, but I pushed a work-around

**Comment by you-n-g** [comment]
Thanks so much!
It works now!
