### ISSUE TITLE
bug: disabled copilot-cmp throwing error

### ISSUE THREAD

**Issue by manishprivet** [LazyVim/LazyVim#660]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.3

### Operating system/version

MacOS 13.3.1

### Describe the bug

When disabling `copilot-cmp` while having `copilot` enabled, notify is throwing error

![image](https://user-images.githubusercontent.com/54291836/233767562-e2dc5a37-efce-4023-bfcf-394ff5452881.png)

### Steps To Reproduce

1. enable copilot in lazy.lua
```lua
    { import = "lazyvim.plugins.extras.coding.copilot" },
```
2. add this to plugins/copilot.lua 
```lua
return {
  {
    "zbirenbaum/copilot.lua",
    cmd = "Copilot",
    build = ":Copilot auth",
    opts = {
      suggestion = { enabled = true },
      panel = { enabled = false },
    },
  },
  {
    "zbirenbaum/copilot-cmp",
    enabled = false,
    dependencies = "copilot.lua",
  },
}
```

### Expected Behavior

Neovim should work as expected, however it is throwing error when going into insert mode

I believe the error is in this line:

https://github.com/LazyVim/LazyVim/blob/6c86952a0e8be1fd06786f12a627a073982fa114/lua/lazyvim/plugins/extras/coding/copilot.lua#L87

This `require` should not run if `copilot-cmp` is disabled

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
You're not supposed to disable that of course. The extra is to setup copilot-cmp
