### ISSUE TITLE
feature:  Supporting no return {} for modules in  https://github.com/LazyVim/starter/tree/main/lua/plugins

### ISSUE THREAD

**Issue by you-n-g** [LazyVim/LazyVim#661]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

If I create a module in https://github.com/LazyVim/starter/tree/main/lua/plugins
It will raise an error.
![image](https://user-images.githubusercontent.com/465606/233782855-a58eecc7-e625-4728-a2ee-affdfa59aaab.png)

### Describe the solution you'd like

If the users just want to implement some features (e.g. a batch of highlight, small functions and mappings for a specific feature),
it looks appropriate to place it into `lua/plugins` folder.  
But the `return {}` looks redundant to user.

I think it would be better to not raise any errors.

### Describe alternatives you've considered

Add `return {}` at the end of the file. 
But it looks redundant to user.

**Comment by folke** [comment]
Everything under plugins should return specs. That's how lazy works

**Comment by you-n-g** [comment]
Thanks for your reply.
Will there be a better place for  `a batch of highlight, small functions and mappings for a specific feature`?
I don't want to break them into different files.

**Comment by folke** [comment]
not sure what you mean tbh, but you can create lua files anywhere under `/lua/`, just `plugins` is reserved for lazy

**Comment by you-n-g** [comment]
Thanks for your reminder. @folke 
I load them with another piece of code now.
https://github.com/you-n-g/deploy/commit/85780920b1fe5cdee5949f9e2fd7ee4c5ccff270#diff-64dd7824be40cca324c81ba9668145a29869a745e388af96fa41570491f38fb1R4
