### ISSUE TITLE
Suggestion: toggle DAP repl instead of open

### ISSUE THREAD

**Issue by albertfgu** [LazyVim/LazyVim#662]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Thank you very much for adding DAP support. I have a very minor suggestion to improve the mappings.

There is currently a keymap to open the DAP REPL:
https://github.com/LazyVim/LazyVim/blob/6c86952a0e8be1fd06786f12a627a073982fa114/lua/lazyvim/plugins/extras/dap/core.lua#L85

I think it makes more sense to have it bound to a toggle instead, which has strictly more functionality IMO:
```lua
    { "<leader>dr", function() require("dap").repl.toggle() end, desc = "Toggle REPL" },
```

### Describe the solution you'd like

N/A

### Describe alternatives you've considered

N/A

**Comment by folke** [comment]
Feel free to submit a PR

**Comment by albertfgu** [comment]
https://github.com/LazyVim/LazyVim/pull/663
