### ISSUE TITLE
bug: floating terminal does not use `vim.o.shell`

### ISSUE THREAD

**Issue by qwertzui11** [LazyVim/LazyVim#668]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0

### Operating system/version

Ubuntu 20.04 / OpenSuse Tumbleweed

### Describe the bug

a floating terminal, opened by `<Leader>ft`, uses bash. which is the default login shell on my system (`chsh`).

however in `options.lua`, I'm setting `vim.o.shell = "fish"`. Which works well with the command `:terminal`.

### Steps To Reproduce

add the line `vim.o.shell = "fish"` to `options.lua`.

### Expected Behavior

a floating terminal should use the shell `fish`, not `bash`. Compare with `:terminal` which uses it correctly.

In my opinion the floating terminal should use the same shell as the non-floating terminal.

Thx for your time and this project! :love_letter:

**Comment by folke** [comment]
Fixed in https://github.com/folke/lazy.nvim/commit/0cbf4669138961c27566de684a0df95c01cd35ad

Will make a new release in a bit

**Comment by qwertzui11** [comment]
tested. works great!

Thx for the really quick response and fix! :heart_eyes:
