### ISSUE TITLE
feature: Improve discoverability of error messages

### ISSUE THREAD

**Issue by premell** [LazyVim/LazyVim#673]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

When there are config errors its hard to find helpful logs. Since LazyVim is using noice you cannot find the errors in the regular 'messages' view and instead have to go to 'Noice'. For new users its really hard to know why the error messages doesnt show up when you type 'messages', and its hard to look through all the plugins to find which one is responsible for error messages. 
[Screencast from 2023-04-24 20-32-16.webm](https://user-images.githubusercontent.com/65544203/234085131-d005e17b-0b2e-4ad2-ba73-d05eca6d1c15.webm)

### Describe the solution you'd like

There are a few alternatives

1) make 'messages' show the messages from noice aswell, or give you a message to use Noice instead.
2) have a FAQ or troubleshooting page where you say to write 'Noice' for error messages
3) Maybe make a dedicated log system, like LazyLog

### Describe alternatives you've considered

I included them in the solution

**Comment by folke** [comment]
You've disabled nvim-notify, or configured noice to show all messages in the mini view. That's not ideal.
Furthermore, those are `vim.notify` messages. And won't be shown in messages.
