### ISSUE TITLE
feature: document how you would load your profile for toggleterm window

### ISSUE THREAD

**Issue by kristoferjoseph** [LazyVim/LazyVim#68]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

When using toggleterm previously I added `opt.term = "bash -l"` to load my profile and have my own prefs in my toggleterm window. This doesn't seem to work with the LazyVim config so I would like to know how you would do this.

### Describe the solution you'd like

When using toggleterm previously I added `opt.term = "bash -l"` to load my profile and have my own prefs in my toggleterm window. This doesn't seem to work with the LazyVim config so I would like to know how you would do this.

### Describe alternatives you've considered

When using toggleterm previously I added `opt.term = "bash -l"` to load my profile and have my own prefs in my toggleterm window. This doesn't seem to work with the LazyVim config so I would like to know how you would do this.

**Comment by folke** [comment]
You can add the below in your `lua/config/keymaps.lua` file:

```lua
vim.keymap.set("n", "<leader>ft", function() Util.float_term({"bash", "-l"}, { cwd = Util.get_root() }) end, { desc = "Terminal (root dir)" })
vim.keymap.set("n", "<leader>fT", function() require("lazyvim.util").float_term({"bash", "-l"}) end, { desc = "Terminal (cwd)" })
```

**Comment by rofrol** [comment]
https://github.com/LazyVim/LazyVim/discussions/193
