### ISSUE TITLE
bug: disabling null-rs causes error

### ISSUE THREAD

**Issue by linsui** [LazyVim/LazyVim#684]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.0

### Operating system/version

NixOS

### Describe the bug

If I disable null-ls with `{ "jose-elias-alvarez/null-ls.nvim",   enabled = false }`, when I format the code I get errors.

### Steps To Reproduce

1. Disable null-ls
2. Format code

### Expected Behavior

When null-ls is disabled it's not used.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Fixed. Will create a new release in a bit

**Comment by linsui** [comment]
Thanks!
