### ISSUE TITLE
bug: E5113

### ISSUE THREAD

**Issue by lightmon233** [LazyVim/LazyVim#689]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.2

### Operating system/version

Windows 10

### I'm wondering how this occured and how I can fix it.
![image](https://user-images.githubusercontent.com/56477197/235366580-a6251a52-224e-4303-ae37-b96798712a02.png)

### Steps To Reproduce

just as the doc goes

### Expected Behavior

I expected all the things to go well just as it does on my linux machine

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
You probably had internet issues when installing lazy. Remove `~/.local/share/nvim/lazy` and try again

**Comment by lightmon233** [comment]
> You probably had internet issues when installing lazy. Remove `~/.local/share/nvim/lazy` and try again

thank you so much, I should have thought about that here in china.
