### ISSUE TITLE
bug: Typo in line 199 of example.lua?

### ISSUE THREAD

**Issue by hopezh** [LazyVim/LazyVim#694]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev-198+gd321deb4a-Homebrew

### Operating system/version

Utuntu 22.4 installed via vmware in windows 11

### Describe the bug

Should the word "ans" be "and" in line 199 in [example.lua](https://github.com/LazyVim/starter/blob/main/lua/plugins/example.lua)? 

`  -- add jsonls and schemastore ans setup treesitter for json, json5 and jsonc
`

### Steps To Reproduce

1. Open [example.lua](https://github.com/LazyVim/starter/blob/main/lua/plugins/example.lua). 

### Expected Behavior

`  -- add jsonls and schemastore and setup treesitter for json, json5 and jsonc
`

### Repro

```Lua
Nil.
```

**Comment by folke** [comment]
I'll fix it. Thanks
