### ISSUE TITLE
Help in understanding configuration

### ISSUE THREAD

**Issue by AlexisFinn** [LazyVim/LazyVim#706]
Hello. I'm sorry to open an issue for this, but it's driving me crazy.

I'm trying to reproduce the lazyvim behavior where the cmd prompt opens in a floating window when I type `:` and even auto-switches to Lua if I type `lua`. This is really cool and I want to integrate it into my configuration, but for the life of me I can't determine what plugin (if any) you are using and where it is configured.

If you could please point me to how you manage this it would be greatly appreciated.

Anyway this config is pretty awesome, and with the new `NVIM_APPNAME` env variable it makes it so much easier to try various pre-configured "nvim frameworks". Keep up the good work, I'm loving it and might totally switch to LazyVim in the future.

**Comment by loiccoyle** [comment]
It's from https://github.com/folke/noice.nvim

**Comment by AlexisFinn** [comment]
Tank you so much. :+1:
