### ISSUE TITLE
bug: prettierd keeps truncating my yaml files when formatting

### ISSUE THREAD

**Issue by aymanbagabas** [LazyVim/LazyVim#712]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev-1591+g066db5e7c-Homebrew

### Operating system/version

MacOS

### Describe the bug

Using the default extra plugin for prettier sometimes truncates my yaml files. Removing the extra plugin and using `null-ls` builtin for `prettier` _NOT_ `prettierd` solves the issue for me.

I don't see why LazyVim is using `prettierd` instead of `prettier` 🤔

### Steps To Reproduce

TBD

### Expected Behavior

Formatting files without truncating them

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
I have no problem at all with formatting yaml files.
prettierd is a lot faster than prettier. You can of course use prettier if you want.

**Comment by karambaq** [comment]
Faced the same issue several times, didn't know prettierd is the one who did it.

**Comment by caquino** [comment]
Same issue happening with me with yaml files, will try to play around with prettier/prettierd settings while a fix is not in place.

**Comment by robsonpeixoto** [comment]
@caquino, could you share an example?

**Comment by caquino** [comment]
@robsonpeixoto sorry for not answering before, I ended up going to bed. 

This is one example of the problem, please let me know if you need any sort of a debug log or similar.

![2023-06-28 09 16 36](https://github.com/LazyVim/LazyVim/assets/55999/7168792b-81a5-4fc4-bfbd-27cf932933ca)

[alacritty.yml](https://gist.github.com/caquino/d116736b87257423d4d141efb562304b)

**Comment by robsonpeixoto** [comment]
@caquino this bug is not happening on my machine.

**Comment by folke** [comment]
For what it's worth, I also never experienced that issue

**Comment by caquino** [comment]
Is there any way to "sniff" the communication between neovim and prettierd? Using prettierd manually does not show the same behavior so I would like to take a peek under the hook to try to isolate the problem.

**Comment by amaanq** [comment]
`:LspLog` maybe

**Comment by caquino** [comment]
I've managed to enable debug log for null-lsp and started a discussion on null-lsp repository https://github.com/jose-elias-alvarez/null-ls.nvim/discussions/1609

**Comment by caquino** [comment]
Quick question, by removing `lazyvim.plugins.extras.formatting.prettier` does it completely disable prettier or it will only disable prettierd? 
I'm trying to use prettier instead of prettierd to test.

**Comment by duckpuppy** [comment]
I'm seeing this same issue - also on Mac, also on fish shell (but I don't use asdf) and I use Kitty as my terminal.
