### ISSUE TITLE
bug: Failure during autoinstall - asked to report bug

### ISSUE THREAD

**Issue by pjgoodall** [LazyVim/LazyVim#713]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.8.3 LuaJIT 2.1.0-beta3

### Operating system/version

Ubuntu 22.04.2 LTS

### Describe the bug

```
...                                         
[nvim-treesitter] [13/18] Treesitter parser for python has been installed                                                
Error detected while processing VimEnter Autocommands for "*"..VimEnter Autocommands for "*"..User Autocommands for "Alph
aReady":                                                                                                                 
Failed to set extmark. Please report a bug with this info:                                                               
{                                                                                                                        
  line = { <1>{                                                                                                          
      hl = "LazyTaskError",                                                                                              
      str = "      "                                                                                                     
    } },                                                                                                                 
  segment = <table 1>                                                                                                    
}                                                                                                                        
Press ENTER or type command to continue    
```

### Steps To Reproduce

1. Exactly follow the installation instructions as in https://www.lazyvim.org/installation 

### Expected Behavior

successful install

### Repro

```Lua
-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
```

**Comment by folke** [comment]
Are you still getting this with the latest version? The version that had that issue was only live for a couple of hours yesterday

**Comment by pjgoodall** [comment]
I just had the same error after a full reinstall of nvim, and following the published procedure.

**Comment by folke** [comment]
You need to update lazy.

**Comment by pjgoodall** [comment]
I completely uninstalled it, and removed the nvim configuration as described in and reinstalled it as per the installation instructions - multiple times

**Comment by pjgoodall** [comment]
Have attached and asciicinema cast of reinstallation and run - please enjoy fumbles.
[LazyVim.zip](https://github.com/LazyVim/LazyVim/files/11416211/LazyVim.zip)
