### ISSUE TITLE
bug: LazyVim Init Error and 

### ISSUE THREAD

**Issue by Mengsen-W** [LazyVim/LazyVim#714]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-270+g648f77793 Build type: Debug LuaJIT 2.1.0-beta3 Compilation: /usr/bin/cc -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wimplicit-fallthrough -fdiagnostics-color=auto -fstack-protector-strong -DNVIM_LOG_DEBUG -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/data/mengsen_project/neovim/.deps/usr/include/luajit-2.1 -I/usr/include -I/data/mengsen_project/neovim/.deps/usr/include -I/data/mengsen_project/neovim/build/src/nvim/auto -I/data/mengsen_project/neovim/build/include -I/data/mengsen_project/neovim/build/cmake.config -I/data/mengsen_project/neovim/src -I/usr/include -I/data/mengsen_project/neovim/.deps/usr/include -I/data/mengsen_project/neovim/.deps/usr/include -I/data/mengsen_project/neovim/.deps/usr/include -I/data/mengsen_project/neovim/.deps/usr/include -I/data/mengsen_project/neovim/.deps/usr/include -I/data/mengsen_project/neovim/.deps/usr/include     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/local/share/nvim"  Run :checkhealth for more info

### Operating system/version

centos8

### Describe the bug

```
Error detected while processing VimEnter Autocommands for "*"..VimEnter Autocommands for "*"..User Autocommands for "AlphaReady":
Failed to set extmark. Please report a bug with this info:
{
  line = { <1>{
      hl = "LazyTaskError",
      str = "      "
    } },
  segment = <table 1>
}
```

and
```
                                ● LuaSnip 17.49ms ✔  build     ■■ build failed
                                    NOTE: jsregexp is optional, so not a big deal if it fails to build

                                    git submodule init
                                    which: no luajit in (/root/.nvm/versions/node/v19.7.0/bin:/root/.zplug/bin:/root/.gvm/pkgsets/go1.20.2/global/bin:/root/.gvm/gos/go1.20.2/bin:/root/.gvm/pkgsets/go1.20.2/global/overlay/bin:/root/.gvm/bin:/root/.local/
                                    bin:/root/miniconda3/bin:/root/miniconda3/condabin:/root/.cargo/bin:/usr/share/Modules/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/.ft:/root/bin)
                                    dirname: missing operand
                                    Try 'dirname --help' for more information.
                                    dirname: missing operand
                                    Try 'dirname --help' for more information.
                                    git submodule update
                                    make INCLUDE_DIR=-I/root/.local/share/nvim/lazy/LuaSnip/deps/lua51_include/ LDLIBS="-lluajit-5.1" -C deps/jsregexp
                                    make[1]: Entering directory '/root/.local/share/nvim/lazy/LuaSnip/deps/jsregexp'
                                    gcc -I/root/.local/share/nvim/lazy/LuaSnip/deps/lua51_include/ -O2 -fPIC -c jsregexp.c -o jsregexp.o
                                    gcc -I/root/.local/share/nvim/lazy/LuaSnip/deps/lua51_include/ -O2 -fPIC -c cutils.c -o cutils.o
                                    gcc -I/root/.local/share/nvim/lazy/LuaSnip/deps/lua51_include/ -O2 -fPIC -c libregexp.c -o libregexp.o
                                    gcc -I/root/.local/share/nvim/lazy/LuaSnip/deps/lua51_include/ -O2 -fPIC -c libunicode.c -o libunicode.o
                                    gcc -shared jsregexp.o cutils.o libregexp.o libunicode.o -lluajit-5.1 -o jsregexp.so
                                    /usr/bin/ld: cannot find -lluajit-5.1
                                    collect2: error: ld returned 1 exit status
                                    make[1]: *** [Makefile:17: jsregexp.so] Error 1                                                                                                                                                                          
~                                   make: *** [Makefile:52: jsregexp] Error 2
~                                   make[1]: Leaving directory '/root/.local/share/nvim/lazy/LuaSnip/deps/jsregex
```

and then

```
cmp tab not working, I don't know if it has anything to do with compilation errors
```

### Steps To Reproduce

1. rm -rf ~/.config/nvim ~/.local/share/nvim ~/.local/state/nvim ~/.cache/nvim
2. git clone https://github.com/LazyVim/starter ~/.config/nvim
3. nvim

### Expected Behavior

compilation success and \<Tab\> can be used

### Repro

```Lua
I not modify any of this starter
https://github.com/LazyVim/starter
```

**Comment by voltrevo** [comment]
I'm having this issue. What was the resolution?

**Comment by voltrevo** [comment]
Thanks for the update @AlexNabokikh. Unfortunately I ended up abandoning LazyVim due to this issue.
