### ISSUE TITLE
<Enter> should not accept the first suggestion

### ISSUE THREAD

**Issue by dgmora** [LazyVim/LazyVim#717]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

I tried this with docker, setting the syntax to `ruby`.
![Screenshot 2023-05-06 at 13 43 35](https://user-images.githubusercontent.com/3609616/236622051-769e044e-47c7-4e6f-b264-3689f653704c.png)

If at this point you type `<Enter>` to start writing the content new method `foo`, `foobar` gets selected from the suggestions. and you end up with `def foobar`

### Describe the solution you'd like

I think it is not possible to always know if the user wants to accept the first suggestion or type `<Enter>`. Even if it may not happen a lot, for me personally it is not acceptable to (sometimes) add unexpected content.

I would purpose that for the user to select the suggestion, the user has to type something, same as if you'd like to select the second suggestion. Maybe it could even be a configurable option?

### Describe alternatives you've considered

Typing `<space>` removes the suggestion, but leaves you with a space. I haven't seen if there's another way to cancel the suggestions, but I would still prefer that `<Enter>` works normally.

### Additional context

Thanks for the amazing work you're doing with LazyVim!

**Comment by dpetka2001** [comment]
You could press `Ctrl-e` which would close the selection menu if you're happy with what you've typed so far. Another way would be to disable the preselection, but then you would have to use `C-n`/`C-p` to select an item. Depends how you want to do it.

**Comment by folke** [comment]
Why is this a bug? Change it however you want in nvim-cmp

**Comment by dgmora** [comment]
No one said it's a bug, it's tagged as an enhancement. I think it's a better default that content doesn't get inserted unexpectedly and that if you want to type enter you don't need to dismiss the completion

**Comment by dgmora** [comment]
No one said it's a bug, it's tagged as an enhancement. I think it's a better default that content doesn't get inserted unexpectedly. 

The configuration for the mappings is done in LazyVim config, so I filed the issue here. I'll give it a try to configure it myself then.

**Comment by dpetka2001** [comment]
Lazyvim does not change `nvim-cmp` default mappings, it just adds some more for selecting next/previous item. `C-e` is default mapping for aborting selection, so you can use that as soon as you've typed whatever you want without accepting the selection `nvim-cmp` is suggesting. The other way would be to disable `nvim-cmp` preselection with the drawback i mentioned in my previous post. You can achieve that as is done [here](https://github.com/dpetka2001/dotfiles/blob/6546ff5f8af3e7690044f89da8a79c4505eba5f8/dot_config/nvim/lua/plugins/coding.lua#L20-L23). I personally prefer to disable preselection.
