### ISSUE TITLE
help about configuration

### ISSUE THREAD

**Issue by gliom** [LazyVim/LazyVim#72]
Hello.
The following isn't an issues, just a help like on a forum. I could have posted on a forum (for example of my GNU/Linux distribution) or on Reddit Neovim, but if they don't use LazyVim it's time wasted.
I've just installed LazyNvim (good work, thank you, I really like it). I don't know Lua language, nor Neovim enough because I migrated from Vim a few days ago.

I have some file written in vimscript. Where can I put these files to be loaded from lazynvim? If I put a plugin file 'foo.vim' in the '.../lua/plugins' directory, it doesn't work.

I want to disable 'witch-key' plugin, so I added it to "disable_plugin" array within '.../lua/config/lazy.lua' file. How can I see all the plugins?

Sometimes, I got messages like:
```
- Failed (18)
  cmp-buffer	fetch failed
    fatal: unable to access '.../cmp-buffer.git/': Could not resolve github.com
  lualine.nvim	fetch failed
  [...]
```
How fix these manually?

I'm using:
NVIM v0.9.0-dev-710+gef89f9fd46
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

Thank you.
Kind regards

**Comment by folke** [comment]
For user questions, there's the discussions forum https://github.com/LazyVim/LazyVim/discussions

you can put vimscript files in `~/.config/nvim/plugin/`

To disable a plugin, please see the examples in the docs.

Those errors are exactly what they say they are. You don't seem to be connected to the internet
