### ISSUE TITLE
bug: conflicting keymaps on fresh install with :checkhealth

### ISSUE THREAD

**Issue by mapleroyal** [LazyVim/LazyVim#736]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)
```
~$ nvim -v
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3
     system vimrc file: "$VIM/sysinit.vim"
   fall-back for $VIM: "/usr/share/nvim"
```

### Operating system/version

Arch with GNOME 44.1 (Wayland)

### Describe the bug
Conflicting keymaps according to `:checkhealth`:
```
WhichKey: checking conflicting keymaps ~
- WARNING conflicting keymap exists for mode **"n"**, lhs: **"gc"**
- rhs: ` `
- WARNING buffer-local keymap overriding global for mode **"n"**, buf: 0, lhs: **"c"**
- old rhs: `:e $MYVIMRC <CR>`
- new rhs: `<cmd>lua require("which-key").show("c", {mode = "n", auto = true})<cr>`
- WARNING buffer-local keymap overriding global for mode **"n"**, buf: 0, lhs: **"g"**
- old rhs: `:Telescope live_grep <CR>`
- new rhs: `<cmd>lua require("which-key").show("g", {mode = "n", auto = true})<cr>`
```

### Steps To Reproduce

1. Never have used any nvim stuff before this.
2. `sudo pacman -S neovim lazygit ripgrep fd pynvim wl-clipboard`
3. `git clone https://github.com/LazyVim/starter ~/.config/nvim`
4. add `vim.g.python3_host_prog = '/usr/bin/python3'` to `~/.config/nvim/init.lua`
5. `nvim` > `:checkhealth` > scroll to the bottom to see these warnings

### Expected Behavior

No conflicting keymaps on a brand new install.

### Repro

```Lua
Apologies, I'm new to nvim which is why I'm using lazyvim, and this Repro step is not clear to me. If it matters, the `init.lua` is this:


-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
vim.g.python3_host_prog = '/usr/bin/python3'
```
```

**Comment by dpetka2001** [comment]
This seems probably the same as issue #667 and maintainer said it's not anything to worry about. I also have the same errors when `checkhealth which-key` but they don't cause any problems.

**Comment by mapleroyal** [comment]
> This seems probably the same as issue #667 and maintainer said it's not anything to worry about. I also have the same errors when `checkhealth which-key` but they don't cause any problems.

I saw that issue as part of searching existing issues before posting. IMO it appears significantly different enough to warrant posting this. Granted, I am new which is why I'm using lazyvim in the first place.

**Comment by folke** [comment]
Yep, all ok. That's just the alpha dashboard shortcuts overriding global ones, which is what we want.
Nothing to worry about.
