### ISSUE TITLE
错误：java-language-server

### ISSUE THREAD

**Issue by cnxjk** [LazyVim/LazyVim#738]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.3

### Operating system/version

MacOS13.3.1

### Describe the bug

Failed (1)
  ◍ java-language-server
    ▼ Displaying full log
      Cloning into '.'...
      From https://github.com/georgewfraser/java-language-server
       * tag               v0.2.39    -> FETCH_HEAD
      + ./scripts/link_mac.sh
      + mvn package -DskipTests
      [INFO] Scanning for projects...
      [INFO]
      [INFO] ---------------------< org.javacs:javac-services >----------------------
      [INFO] Building javac-services 0.1-SNAPSHOT
      [INFO]   from pom.xml
      [INFO] --------------------------------[ jar ]---------------------------------
      [INFO]
      [INFO] --- resources:3.3.0:resources (default-resources) @ javac-services ---
      [WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
      [INFO] skip non existing resourceDirectory /Users/varungawande/.local/share/nvim/mason/.packages/java-language-server/src/main/resources
      [INFO]
      [INFO] --- compiler:3.8.0:compile (default-compile) @ javac-services ---
      [INFO] Changes detected - recompiling the module!
      [WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
      [INFO] Compiling 357 source files to /Users/varungawande/.local/share/nvim/mason/.packages/java-language-server/target/classes
      [INFO] ------------------------------------------------------------------------
      [INFO] BUILD FAILURE
      [INFO] ------------------------------------------------------------------------
      [INFO] Total time:  0.560 s
      [INFO] Finished at: 2023-05-07T12:47:39+05:30
      [INFO] ------------------------------------------------------------------------
      [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project javac-services: Fatal error compili
      [ERROR]
      [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
      [ERROR] Re-run Maven using the -X switch to enable full debug logging.
      [ERROR]
      [ERROR] For more information about the errors and possible solutions, please read the following articles:
      [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
      spawn: bash failed with exit code 1 and signal 0.

### Steps To Reproduce

Mason
java-language-server install

### Expected Behavior

安装失败了

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Sorry, but this is not a LazyVim issue. Check for help in the mason repo or the java lsp repo
