### ISSUE TITLE
Issue with tsc.nvim and nvim-notify integration

### ISSUE THREAD

**Issue by dmmulroy** [LazyVim/LazyVim#743]
# Issue with tsc.nvim and nvim-notify integration

Hello LazyVim team,

I'm the maintainer of [tsc.nvim](https://github.com/dmmulroy/tsc.nvim), a plugin that runs TypeScript's compiler asynchronously in NeoVim, and I've been working with one of our users (@phaalonso) to resolve [a problem they're encountering](https://github.com/dmmulroy/tsc.nvim/issues/17). 

The issue revolves around the integration of `tsc.nvim` with `nvim-notify`, a plugin that ships with LazyVim. The user reported that on trying to run `tsc.nvim`, it was spamming `nvim-notify` errors. After some troubleshooting, we made progress by overriding the default `nvim-notify` configuration that ships with LazyVim, and notifications started to appear. However, these notifications are not behaving as expected; instead of replacing a single one, multiple notifications are appearing.

Furthermore, we've noticed that there seems to be some peculiar usage of `nvim-notify` within LazyVim's codebase (found here: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/util/init.lua#L162-L197) which might be causing this issue.

To give you a better understanding of how `tsc.nvim` uses `nvim-notify`, our plugin replaces and reuses the same [nvim-notify record](https://github.com/rcarriga/nvim-notify/blob/master/doc/nvim-notify.txt#L61-L70). Here's the relevant part of our code:

```lua
local function notify()
    if not is_running then
      return
    end

    notify_record = vim.notify(
      format_notification_msg("Type-checking your project, kick back and relax 🚀", spinner_idx),
      nil,
      get_notify_options(
        (notify_record and { replace = notify_record.id }),
        (config.hide_progress_notifications_from_history and notify_called and { hide_from_history = true })
      )
    )

    notify_called = true

    spinner_idx = spinner_idx + 1

    if spinner_idx > #config.spinner then
      spinner_idx = 1
    end

    vim.defer_fn(notify, 125)
  end
```

You can find this section of the code in our repository here: https://github.com/dmmulroy/tsc.nvim/blob/main/lua/tsc/init.lua#L81-L104

I would appreciate your help in diagnosing and resolving this issue. Could you provide any insights on why the `nvim-notify` might be behaving this way and how we could possibly resolve this? Any help or guidance you could provide would be greatly appreciated.

Thanks!

**Comment by folke** [comment]
Noice actually overrides `vim.notify` and has `nvim-notify` as a possible route destination.

Noice proxies notifications to nvim-notify, but there was a bug in handing the `replace` parameter. I expected that to always be a record, but apparently a number is also fine.

Fixed now

https://github.com/folke/noice.nvim/commit/a9cc87b14e18bc3717746b45d79157c0adb43a4d

**Comment by dmmulroy** [comment]
Awesome - thanks so much for the help and quick turn around @folke!
