### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by kimusan** [LazyVim/LazyVim#747]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.2

### Operating system/version

Win 10

### Describe the bug

I am trying to install LazyVim in windows 10 via powershell 7.0 but during the  first startup I get below errors: 

![image](https://github.com/LazyVim/LazyVim/assets/1150049/142f2710-91f7-4873-9fa7-35551908cd7a)

Basically it looks like 200+ git.exe processes gets started in the background and after a short time it starts failing with the above timeout. The git process does not get killed so it continues to run in the background and it takes 55% cpu time and 2gb ram. 

Is there  a way to get past that timeout or maybe speed up the process?

### Steps To Reproduce

1. install lazyvim in neovim using powershell 7.0
2. see it fail

### Expected Behavior

LazyVim should install 

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Check the lazy.nvim docs and look for timeout.
But you probably just want to set concurrency=10 to limit the number of concurrent git processes

**Comment by kimusan** [comment]
thanks it did help to raise the timeout to 1200 instead of 120 but it still hangs for 20+ secs every time I start it (probably due to some git request in the background.

**Comment by folke** [comment]
That's definitely not normal. Must be something on your machine. Checking for updates takes about 3 seconds for me for over 100 plugins

**Comment by kimusan** [comment]
yeah I begin to suspect that windows tries to do something in the background like contacting network drives and waits for a timeout.
