### ISSUE TITLE
Formatters/Linters setup

### ISSUE THREAD

**Issue by kobzar** [LazyVim/LazyVim#749]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Please help me understand how to setup linters and formatters for diff langs
for example for python I am use "isort, black, flake8"
I don't use options format on save, so I want to format buffer by key combinatio
like ```map("<leader>ff", format fille)```

Thanks

### Describe the solution you'd like

Add examples on homepage

### Describe alternatives you've considered

This is default in lunar vim

**Comment by dpetka2001** [comment]
Did you read the docs? All you need is [mason](https://www.lazyvim.org/plugins/lsp#masonnvim) and [null-ls](https://www.lazyvim.org/plugins/lsp#null-lsnvim). As for format on save there is keybinding to toggle it on/off depending on your needs.
