### ISSUE TITLE
bug: Pressing <Leader>c in Visual mode deletes selection

### ISSUE THREAD

**Issue by francis-robert** [LazyVim/LazyVim#75]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0-dev-661+ga37c686d2

### Operating system/version

MacOS 12.6.1

### Describe the bug

When using visual mode to select text I often will press <Leader> to bring up the `which-key` prompt to see what options are available to me. If I click `c` to bring up the code options, however, it deletes my entire selection.

Here's a recording of the issue:
![visual-delete](https://user-images.githubusercontent.com/87673558/212940722-30b2468a-a3e7-4785-af3f-71b9e4792299.gif)

I followed this recommendation from StackOverflow to capture all of the keymaps to see if there was a separate issue mapping: https://stackoverflow.com/a/15756785

```
x  <Space>c    * <Cmd>lua require("which-key").show(" c", {mode = "v", auto = true})<CR>
	Last set from Lua
```

### Steps To Reproduce

1. Enter visual mode and select some text
2. Click <Leader> and wait to bring up `which-key` prompt
3. Click `c` to go to the code section
4. Text should be deleted

### Expected Behavior

Text should not be deleted and instead which-key should navigate to the next window

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
That's because no lsp is connected. Then the `<leader>c...` bindings won't be available. If you press `c` in which-key, it won't find a binding /group and so will just feed those keys, which in this case would be `<c>` (change).

So this all basically works as it should

**Comment by folke** [comment]
Are you sure it's connected? What does `:LspInfo` show when in the buffer?

**Comment by folke** [comment]
I also check if the functionality is available on the lsp server, so that's probably the reason you don't see the mappings :) Check the `has` attributes below.

```lua
  self:map("<leader>ca", vim.lsp.buf.code_action, { desc = "Code Action", mode = { "n", "v" }, has = "codeAction" })

  local format = require("lazyvim.plugins.lsp.format").format
  self:map("<leader>cf", format, { desc = "Format Document", has = "documentFormatting" })
  self:map("<leader>cf", format, { desc = "Format Range", mode = "v", has = "documentRangeFormatting" })
  self:map("<leader>cr", M.rename, { expr = true, desc = "Rename", has = "rename" })
```

**Comment by francis-robert** [comment]
![image](https://user-images.githubusercontent.com/87673558/212946397-dd017f5f-cd41-474d-87a1-d63b0fe08d65.png)

![lsp](https://user-images.githubusercontent.com/87673558/212946846-44e3720f-a3e1-45fc-8881-8b2d45d70b17.gif)

Other features like format on save work as expected

**Comment by folke** [comment]
yep
