### ISSUE TITLE
virtual_text/virtual_lines option

### ISSUE THREAD

**Issue by kobzar** [LazyVim/LazyVim#750]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

I can't find any info how to disable some option by default. 
In my lunar vim config I am use for it next string:

```
vim.diagnostic.config({ virtual_text = false })
vim.diagnostic.config({ virtual_lines = false })

```
And in my keybinding I call it when needed
```
lvim.builtin.which_key.mappings["gh"] = { "<cmd>lua require('lsp_lines').toggle()<cr>", "Toggle LSP lines" }
```
or "gl" to show error on selected line

Thanks.

### Describe the solution you'd like

.

### Describe alternatives you've considered

.

**Comment by dpetka2001** [comment]
It's in the [docs](https://www.lazyvim.org/plugins/lsp#nvim-lspconfig). Just disable `opts.diagnostics.virtual_text`. You should read more carefully the docs to understand how to configure Lazyvim.

**Comment by kobzar** [comment]
Sorry, but it still hard for understand. In witch place I must insert this line?
```
opts.diagnostics.virtual_text = false
opts.diagnostics.virtual_lines = false
```
Or I must add file in plugins dir to rewrite plugins options like 
lsp.lua
```
return {
  {
    "neovim/nvim-lspconfig",
    opts = {
      diagnostics = {
        virtual_text = false,
        virtual_lines = false,
      },
    },
    {
      "https://git.sr.ht/~whynothugo/lsp_lines.nvim",
      keys = { { "<leader>hl", "<cmd>lua require('lsp_lines').toggle()<cr>", desc = "Symbols Outline" } },
    },
  },
}

```

This is not working for me and key combination to.

**Comment by dpetka2001** [comment]
```lua
  {
    "neovim/nvim-lspconfig",
    opts = {
      diagnostics = {
        virtual_text = false,
        virtual_lines = true,
      },
    },
  },

  {
    "ErichDonGubler/lsp_lines.nvim",
    url = "https://git.sr.ht/~whynothugo/lsp_lines.nvim",
    opts = {},
    keys = {
      { "<leader>hl", "<cmd>lua require('lsp_lines').toggle()<cr>", desc = "Toggle lsp_lines" },
    },
  },
```
Can you test out this?

**Comment by kobzar** [comment]
No this is no work to. And I don't know how to add "gl" combination (show line diagnostics
But I can show how its look on lunarvim (My settings in first post)

https://github.com/LazyVim/LazyVim/assets/1912842/052fb387-5741-4d1f-bd9e-653d81716f0c

**Comment by dpetka2001** [comment]
The code that I put above works just fine for me. Just tested it out. It installed lsp_lines and worked like in your video. Just change `<leader>hl` to `<leader>gl` so that you toglle lsp_lines with that keybinding.

**Comment by dpetka2001** [comment]
Changed the code a bit, cuz in the site it mentions that the setup should be done after lspconfig
```lua
return {
  {
    "neovim/nvim-lspconfig",
    dependencies = {
      {
        "ErichDonGubler/lsp_lines.nvim",
        url = "https://git.sr.ht/~whynothugo/lsp_lines.nvim",
        opts = {},
        keys = {
          { "<leader>gl", "<cmd>lua require('lsp_lines').toggle()<cr>", desc = "Toggle lsp_lines" },
        },
      },
    },
    opts = {
      diagnostics = {
        virtual_text = false,
        virtual_lines = false,
      },
    },
  },
}
```
