### ISSUE TITLE
bug: Comment.nvim gets uninstalled

### ISSUE THREAD

**Issue by dpetka2001** [LazyVim/LazyVim#754]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev

### Operating system/version

Linux Mint 21.1

### Describe the bug

After the latest Lazyvim upgrade, the plugin that I used for comments `numToStr/Comment.nvim` gets uninstalled and `mini.comment` gets forcefully installed even though I have the following in my configuration
```lua
  {
    "echasnovski/mini.comment",
    enabled = false,
  },
```
I prefer using `Comment.nvim` over `mini.comment` because it also supports block comments, so I would like to keep it that way. Is there any solution to this? Am I doing something wrong? Up until the recent Lazyvim upgrade I didn't encounter any problems with having my configuration as described.

### Steps To Reproduce

Set the following spec for comments in a file
```lua
  {
    "echasnovski/mini.comment",
    enabled = false,
  },
  {
    "numToStr/Comment.nvim",
    event = "VeryLazy",
    opts = {
      ---Add a space b/w comment and the line
      padding = true,
      ---Whether the cursor should stay at its position
      sticky = true,
      ---Lines to be ignored while (un)comment
      ignore = nil,
      ---LHS of toggle mappings in NORMAL mode
      toggler = {
        ---Line-comment toggle keymap
        line = "gcc",
        ---Block-comment toggle keymap
        block = "gbc",
      },
      ---LHS of operator-pending mappings in NORMAL and VISUAL mode
      opleader = {
        ---Line-comment keymap
        line = "gc",
        ---Block-comment keymap
        block = "gb",
      },
      ---LHS of extra mappings
      extra = {
        ---Add comment on the line above
        above = "gcO",
        ---Add comment on the line below
        below = "gco",
        ---Add comment at the end of line
        eol = "gcA",
      },
      ---Enable keybindings
      ---NOTE: If given `false` then the plugin won't create any mappings
      mappings = {
        ---Operator-pending mapping; `gcc` `gbc` `gc[count]{motion}` `gb[count]{motion}`
        basic = true,
        ---Extra mapping; `gco`, `gcO`, `gcA`
        extra = true,
      },
      ---Function to call before (un)comment
      pre_hook = require("ts_context_commentstring.integrations.comment_nvim").create_pre_hook(),
      ---Function to call after (un)comment
      post_hook = nil,
    },
  },
```

### Expected Behavior

Don't forcefully uninstall `Comment.nvim` and install `mini.comment` in its place.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
So, I tried some things in my configuration and if I comment out the line
```lua
pre_hook = require("ts_context_commentstring.integrations.comment_nvim").create_pre_hook(),
```
then it doesn't get uninstalled. If I leave it be I get the following error
```
Failed to load `plugins.comments`

/home/jrn23/.config/nvim/lua/plugins/comments.lua:44: module 'ts_context_commentstring.integrations.comment_nvim' not found:
	no field package.preload['ts_context_commentstring.integrations.comment_nvim']
cache_loader: module ts_context_commentstring.integrations.comment_nvim not found
cache_loader_lib: module ts_context_commentstring.integrations.comment_nvim not found
	no file './ts_context_commentstring/integrations/comment_nvim.lua'
	no file '/usr/share/luajit-2.1.0-beta3/ts_context_commentstring/integrations/comment_nvim.lua'
	no file '/usr/local/share/lua/5.1/ts_context_commentstring/integrations/comment_nvim.lua'
	no file '/usr/local/share/lua/5.1/ts_context_commentstring/integrations/comment_nvim/init.lua'
	no file '/usr/share/lua/5.1/ts_context_commentstring/integrations/comment_nvim.lua'
	no file '/usr/share/lua/5.1/ts_context_commentstring/integrations/comment_nvim/init.lua'
	no file './ts_context_commentstring/integrations/comment_nvim.so'
	no file '/usr/local/lib/lua/5.1/ts_context_commentstring/integrations/comment_nvim.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.1/ts_context_commentstring/integrations/comment_nvim.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './ts_context_commentstring.so'
	no file '/usr/local/lib/lua/5.1/ts_context_commentstring.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.1/ts_context_commentstring.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'

# stacktrace:
  - lua/plugins/comments.lua:44
  - lua/config/lazy.lua:9
  - init.lua:6
```
and tries to uninstall the plugin. Any idea what might be causing it? Didn't have this problem with the configuration as it was until the recent Lazyvim upgrade.

**Comment by folke** [comment]
I removed https://github.com/JoosepAlviste/nvim-ts-context-commentstring from LazyVim, since `mini.comment` now support ts commentstrings out of the box.

The reason why Comment.nvim gets installed, is because your spec errors. You should have seen a clear error message about this.

It errors, because you are requiring ts-context-comment-string in the opts, without putting it in a closure (opts as a function). That way lazy can't parse the file, so it doesn't know about the comment.nvim plugin. By not putting it in a closure, comments.nvim, ts-comment-context string and tresitter wil all be loaded during startup.

Anyway, the way to fix it for you is to add the below somewhere in your config:

```lua
{'JoosepAlviste/nvim-ts-context-commentstring'}
```

**Comment by folke** [comment]
I just added a new commit with a breaking change. Forgot to do that:
https://github.com/LazyVim/LazyVim/commit/d41ef05cc00bf3502fb55512c265a02116127ca8

You probably want to add the below:

```lua
{
  "nvim-treesitter/nvim-treesitter",
  opts = {
    context_commentstring = {
      enable = true,
      enable_autocmd = false,
    },
  },
  dependencies = {
    "JoosepAlviste/nvim-ts-context-commentstring",
  },
}
```

**Comment by dpetka2001** [comment]
I already have that in my config as a dependency in treesitter. Still getting the error.

**Comment by folke** [comment]
Yes, that's because you;re loading conext comment string **before** lazy, while parsing the specs. That is never a good idea.

Change your `pre_hook` to:

```lua
      pre_hook = function(...)
        return require("ts_context_commentstring.integrations.comment_nvim").create_pre_hook(...)
      end,
```

**Comment by dpetka2001** [comment]
Yes that did the trick. Thank you so much.

**Comment by dpetka2001** [comment]
Sorry to bother again. Am I right in understanding that by putting it in a closure, it defers its `require` until after the plugin is loaded? Instead without a closure it `require`s it as the file is being parsed? Is there a chance that also means putting `opts` as a function is better for lazy loading plugins, since they are required when the plugin is loaded(until now I've putting all my `opts` as tables). Do you happen to have any resource to suggest for further reading on this? Is this a LuaJit thing or Neovim thing (or even maybe a `lazy.nvim` thing)?

**Comment by folke** [comment]
Tables are fine as long as you don't require anything like with ts-context-commentstring. Doing that could actually result in weird things happening.

So either use opts as a function, or just wrap the require in a function like the example I showed. Either method is fine

**Comment by dpetka2001** [comment]
Do you happen to have any suggestion on resources for further reading?

**Comment by folke** [comment]
not really. That's just how lua works. By wrapping the require in a function, the require will only happen when the pre_hook gets executed. As opposed to when your plugin file was loaded by lazy.

**Comment by dpetka2001** [comment]
Thanks for your insight. Hope I'll get a better understanding as I get more acquainted with Lua.
