### ISSUE TITLE
Question: how to override a keymap in "lazyvim.plugins.extras.dap.core"

### ISSUE THREAD

**Issue by georgikoemdzhiev** [LazyVim/LazyVim#760]
Hello, I am trying to override the nvim-dap plugin's "step_over" keymap (part of `lazyvim.plugins.extras.dap.core`). Currently, it is set to `<leader>dO`. Is it possible to change that? 

I suppose I can add the config in `~/.config/nvim/lua/config/keymaps.lua` but I am unsure how.

**Comment by dpetka2001** [comment]
I have the following to change keys in nvim-dap
```lua
return {
  -- Modify nvim-dap
  {
    "mfussenegger/nvim-dap",
    -- stylua: ignore
    keys = {
      { "<F10>", function() require("dap").step_over() end, desc = "Step Over" },
      { "<F11>", function() require("dap").step_into() end, desc = "Step Into" },
      { "<F12>", function() require("dap").step_out() end, desc = "Step Out" },
    },
  },
}
```
Just put it in a file in `~/.config/nvim/lua/plugins/` and change it to your needs.

**Comment by georgikoemdzhiev** [comment]
Awesome! Thank you very much!
