### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by xclidongbo** [LazyVim/LazyVim#763]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.2

### Operating system/version

MacOS 13.1

### Describe the bug

When I delete multiple lines, neovide crashes. For example: "5dj", "5dd"

### Steps To Reproduce

When I delete multiple lines, neovide crashes. For example: "5dj", "5dd"

### Expected Behavior

When I delete multiple lines, neovide not crashes.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Not a LazyVim issue. Best to disable Noice when using neovide. Neovide & Neovim 0.9.0 behaves badly with noice
