### ISSUE TITLE
feature: preferred code action for TypeScript lsp

### ISSUE THREAD

**Issue by joshmedeski** [LazyVim/LazyVim#764]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

When choosing a code action, the null-ls options are always shown first, which is often the option I don't want.

<img width="1113" alt="Screenshot 2023-05-15 at 12 13 06 PM" src="https://github.com/LazyVim/LazyVim/assets/2036594/e5208ac6-6ac8-4277-947e-85bad4701e34">

### Describe the solution you'd like

I'd like all `tsserver` code actions to be displayed first.

### Describe alternatives you've considered

I've considered disabling the null-ls options, but then I'd lose that functionality all together.

### Additional context

I've seen Neovim's LSP can setup `preferred` code actions. Perhaps that is the most obvious way of making sure the `tsserver` code actions are always shown first.

**Comment by folke** [comment]
Unfortunately there's no such option right now in Neovim. I'm sure there's plugins out there that can yield this behavior.

I think null-ls is always shown first, since that will be the first lsp to return its results

**Comment by joshmedeski** [comment]
Okay, thanks for the quick reply.
