### ISSUE TITLE
feature: Fast navigate to recent a directory/session from multiple candidates.

### ISSUE THREAD

**Issue by you-n-g** [LazyVim/LazyVim#770]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

I have multiple projects.  When I open neovim, I hope I can fast navigate into one of them.

### Describe the solution you'd like

When you start Lazyvim in Neovim (like in the image below), it presents you with the option to choose either "Recent Directories" or "List sessions", allowing you to select one of them.

![image](https://github.com/LazyVim/LazyVim/assets/465606/290d70db-c202-4b0b-b49c-ea438478925c)

### Describe alternatives you've considered

Some Vim plugins, such as Startify, provide similar features, but they may not be as convenient and may have bugs.

**Comment by folke** [comment]
You could install another session manager. See https://github.com/rockerBOO/awesome-neovim#session

This project is actually a fork of persistence.nvim that also includes a Telescope picker: https://github.com/olimorris/persisted.nvim

**Comment by you-n-g** [comment]
Thanks for your advice. Here is my new configuration for persistence which supports selecting sessions.

https://github.com/you-n-g/deploy/blob/2bf4119765d8900f2e180a045b403f1fcd087db0/configs/lazynvim/lua/plugins/session.lua#L24
