### ISSUE TITLE
[LazyVim in Alacritty with TokyoNight] Background is a wrong color when using LazyVim in tmux

### ISSUE THREAD

**Issue by Memnoc** [LazyVim/LazyVim#774]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0

### Operating system/version

Archcraft (Arch Linux)

### Describe the bug

 When starting a session in tmux in Alacritty, the background of LazyVim does changes to what it seems a default grey.

When I run `echo $TERM` both in and outside tmux I get `tmux-256color` however that does not seem to work - I have tried all the combinations of xterm-256color, tmux-256color, screen-256color and alacritty, but nothing works.  The current config is as follows:

tmux **version 3.3a**
```
set-option -sa terminal-features ',alacritty:RGB'
set-option -ga terminal-overrides ',alacritty:Tc'
```

alacritty **0.12.0 (5a728195)**
```
env:
  TERM: alacritty
```
Notice that I have the same colorscheme, TokyoNight Storm in LazyVim, Alacritty and Tmux.

This configuration (which I have tried multiple times) is working in macbook pro m2 running latest OS

```
set-option -sa terminal-features 'screen-256color'
set-option -ga terminal-overrides ',alacritty:Tc'
```
Running `:checkhealth` points out to an error, but following the instructions does not really fix the issue. Here is the output:

```
tmux ~
- OK escape-time: 10
- OK focus-events: on
- $TERM: tmux-256color
- WARNING Neither Tc nor RGB capability set. True colors are disabled. |'termguicolors'| won't work properly.
  - ADVICE:
    - Put this in your ~/.tmux.conf and replace XXX by your $TERM outside of tmux:
      set-option -sa terminal-features ',XXX:RGB'
    - For older tmux versions use this instead:
      set-option -ga terminal-overrides ',XXX:Tc

```

### Steps To Reproduce

Install Alacritty, LazyVim and Tmux and apply TokyoNight Storm to all of them from the official docs

1. start tmux with `$ tmux`
2. start LazyVim in tmux sessoin with `$ nvim`
3. Notice how the bg of LazyVim switches to a light-grey

### Expected Behavior

When starting tumux, the background should be the one set in your colorscheme.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
This is not a lazyvim, nor tokyonight issue. Check the docs for tmux and your terminal. I don't use tmux myself.

**Comment by Memnoc** [comment]
Fair enough, it seems more like a tmux issue than anything else. Since many others came and will come across the same issue, here is what fixed it for me.

A file along the line of **tmux-xterm-256color.conf** was created in my root directory. Deleting that file immediately fixed the issue. I suspect this the output of some commands I ran while debugging and I only caught that by mistake while working on some keybindings.

If you are using Alacritty and LazyVim + tmux with whatever colorscheme, on Arch, try out these settings:

alacritty.yml
```
env:
  TERM: alacritty
```
  
  .tmux.conf
```
set-option -sa terminal-features 'screen-256color'
set-option -ga terminal-overrides ',alacritty:Tc'
```
