### ISSUE TITLE
bug: TreeSitter | LazyVim documentation out-of-date

### ISSUE THREAD

**Issue by krishna-bala** [LazyVim/LazyVim#775]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.0

### Operating system/version

Ubuntu 18.04

### Describe the bug

In the "Full Spec" display for [TreeSitter | LazyVim](https://www.lazyvim.org/plugins/treesitter#nvim-treesitter), the `opts` table has the value `context_commentstring`. However, the `treesitter.lua` plugin defined in the [LazyVim repo](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/treesitter.lua) does not have the value `context_commentstring`. 

I stumbled upon this while updating Lazy as I have custom opts that assumes `context_commentstring` already exists.

### Steps To Reproduce

No steps to reproduce -- documentation issue.

### Expected Behavior

Expect the LazyVim documentation to match the repo.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
I made a breaking release that removed context_commentstring. https://github.com/LazyVim/LazyVim/releases/tag/v3.0.0

I just updated the docs to reflect this.
