### ISSUE TITLE
bug?: Cannot overwrite neo-tree.nvim settings

### ISSUE THREAD

**Issue by LangdalP** [LazyVim/LazyVim#780]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0

### Operating system/version

MacOS 13.3.1

### Describe the bug

I want to set `bind_to_cwd = true` for neo-tree.nvim, as you can check out here:
https://github.com/nvim-neo-tree/neo-tree.nvim/blob/v2.x/lua/neo-tree/defaults.lua#L405

I follow the [LazyVim documentation](https://www.lazyvim.org/plugins#%EF%B8%8F-customizing-plugin-specs) and create the following file `~/.config/nvim/lua/plugins/neo-tree.nvim.lua`:

```lua
return {
  {
    "nvim-neo-tree/neo-tree.nvim",
    opts = {
      filesystem = {
        bind_to_cwd = true,
      },
    },
  },
}
```

However, this gives the following error when I restart neovim:
```
Failed to load `plugins.neo-tree.nvim`

...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/plugin.lua:271: module 'plugins.neo-tree.nvim' not found:
	no field package.preload['plugins.neo-tree.nvim']
cache_loader: module plugins.neo-tree.nvim not found
cache_loader_lib: module plugins.neo-tree.nvim not found
	no file './plugins/neo-tree/nvim.lua'
	no file '/usr/local/share/luajit-2.1.0-beta3/plugins/neo-tree/nvim.lua'
	no file '/usr/local/share/lua/5.1/plugins/neo-tree/nvim.lua'
	no file '/usr/local/share/lua/5.1/plugins/neo-tree/nvim/init.lua'
	no file './plugins/neo-tree/nvim.so'
	no file '/usr/local/lib/lua/5.1/plugins/neo-tree/nvim.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './plugins.so'
	no file '/usr/local/lib/lua/5.1/plugins.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'

# stacktrace:
  - lua/config/lazy.lua:9
  - init.lua:2
```

Is this a bug? If not, how can I fix this?

### Steps To Reproduce

1. Attempt to overwrite any settings for `neo-tree.nvim`

### Expected Behavior

Should not get an error, and the overwritten settings should take effect. They do not.

**Comment by folke** [comment]
You can't have a **dot** in a lua module name. This is not a limitation of lazy, that's just how lua works
