### ISSUE TITLE
bug: Preview of colorscheme doesn't work on alpha-nvim or if preview window is not present due to limited space

### ISSUE THREAD

**Issue by thyttan** [LazyVim/LazyVim#783]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0-dev+116-gd4eff4052

### Operating system/version

Fedora 38

### Describe the bug

Preview of colorscheme doesn't work on alpha-nvim or if preview window is not present due to limited space. See screencast below.

[Screencast from 2023-05-19 20-36-09.webm](https://github.com/LazyVim/LazyVim/assets/97237430/6eb3f509-5767-4282-99fe-fa130203efc0)

I think this bug relates to https://github.com/nvim-telescope/telescope.nvim/pull/980 so maybe the bug report should be made there instead. Feel free to close this if that is the case.

### Steps To Reproduce

1. start lazyvim into LazyVims alpha-nvim screen.
2. do <leader>uC and highlight different colorschemes.
3. Preview colorscheme does not trigger.
4. exit the telescope window 
5. click 'n' to open new file
6. do <leader>uC and highlight different colorschemes.
7. preview colorscheme DOES trigger
8. make the terminal window small as to not leave room for telescopes preview window.
9. highlight different colorschemes.
10. preview colorscheme does not trigger.

### Expected Behavior

The colorscheme preview should trigger regardless of if the telescope preview window is displayed and also regardless of if a file is open.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
not a lazyvim issue indeed. Also not really a big deal is it? Just change the colorscheme when **not** being on the dashboard?
