### ISSUE TITLE
bug: Unable to update lazyvim

### ISSUE THREAD

**Issue by krish2487** [LazyVim/LazyVim#790]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0 

### Operating system/version

Endeavour OS

### Describe the bug

Hello,
I am unable to update lazyvim from the UI.
There are no additional config I have made or any changes that will prevent the OS from having an internet connection.
In fact the only plugin I have installed is [Venn](https://github.com/jbyuki/venn.nvim) but the issue existed before I installed this plugin.
A point of interest is that this installation (machine, OS , et all ) is less than a week old as I received a laptop from RMA recently. My other machine which runs a similar setup is working perfectly fine and I can update lazyvim from within the UI.. No problems there. 
 
I see the message "Could not resolve host : github.com". But I am able to access github from within the browser as is evident from me opening this issue on the same machine.
Further, I can also see from my ad blocker running on my DNS server that all the requests going to github are processed and not filtered / blocked in any manner.
I was wondering if anyone else is facing this issue or if I m missing some rather obvious steps.

Please find screenshots of lazyvim and my ad blocker 
![2023-05-21-16:44:06-screenshot](https://github.com/LazyVim/LazyVim/assets/23363406/c562bc86-4eb2-4577-b006-b15d74c6a0a8)
![2023-05-21-16:46:20-screenshot](https://github.com/LazyVim/LazyVim/assets/23363406/b444739c-d002-4dec-a568-7bdb43f6a30d)

### Steps To Reproduce

1. Open neovim
2. Press Leader + l
3. Press U

### Expected Behavior

I expect to see that lazyvim updates the plugins

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Sorry, but there's literally nothing I can do about this. Lazy just spawns a git process that doesn't seem to be able to connect to github. You'll have to figure this out yourself.

**Comment by krish2487** [comment]
I understand.. Its much less of a bug and more of a troubleshooting request..
If it is not too much trouble, can you suggest how I can go about troubleshooting it further.
I can ping github from the command line and I can access it in the browser.. 
I can clone and push and pull from the command line just fine - with or without credentials.

I m unable to see what could be the underlying issue just on nvim..

**Comment by folke** [comment]
no idea. this is clearly a networking issue on your computer. maybe check your firewall?

**Comment by krish2487** [comment]
Thanks.. I ll check.. 
Its as good as a starting point anyway.. :-) 
Thanks again for the help!

**Comment by krish2487** [comment]
Fixed it... For anyone else running into the same issue.
It was the DNS server. The homelab's ad guard DNS server was causing the issue..
A combination of the actual upstream DNS server and rate limiting was causing the issue.

**Comment by svartkanin** [comment]
Had the same problem, increasing the rate limit worked

**Comment by dinvlad** [comment]
Wow @krish2487 I had exact same issue - turned out I had a rate-limit set to 20/sec per client.. Curious if AdGuard does this by default, but setting it to 0 helped instantly!
