### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by iamxiaojianzheng** [LazyVim/LazyVim#799]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0

### Operating system/version

windows11

### Describe the bug

gcc comments cannot be used when editing vue file. 

Error message: (mini.ment) Option 'commentstring' is empty.

I have installed treesitter of vue

### Steps To Reproduce

1. TSInstall vue
2. open vue file 
3. gcc on any line

### Expected Behavior

[nvim-ts-context-commentstring](https://github.com/JoosepAlviste/nvim-ts-context-commentstring) is a comment function that supports vue files

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
I just pushed an update that uses nvim-ts-context-commentstring again. Will make a new release in a bit.

https://github.com/LazyVim/LazyVim/pull/796
