### ISSUE TITLE
bug: overriding formatoptions

### ISSUE THREAD

**Issue by loiccoyle** [LazyVim/LazyVim#80]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.8.2

### Operating system/version

Linux 6.1.6-arch1-1

### Describe the bug

I'm trying to set my own `vim.opt.formatoptions` in the `~/.config/nvim/lua/config/options.lua` file. 
But they are not taken into account and the default `formatoptions` defined by `lazyvim` are set. 

### Steps To Reproduce

1. Add `vim.opt.formatoptions="jcqlnt"` to `~/.config/nvim/lua/config/options.lua`
2. Start `nvim` 
3. Check formatoptions with `set fo?`

### Expected Behavior

User set `formatoptions` should take precedence over the default setting defined by `Lazyvim`.

Note that other options I changed like `wrap`  do get taken into account.

**Comment by folke** [comment]
You need to define those in `lua/config/options.lua`, not `lua/options.lua`

**Comment by loiccoyle** [comment]
Indeed sorry I missed typed, they are defined in `lua/config/options.lua`

**Comment by folke** [comment]
hmm, the ones from LazyVim also aren't set.

Apparently the Neovim, lua ftplugin overwrites those settings. Odd

See here: https://github.com/neovim/neovim/blob/775e2922908ceae221b35d3edc5e28e89f6b9647/runtime/ftplugin/lua.vim#L19

Either way, not a LazyVim issue I'm afraid.

You could change formatoptions with an filetype autocmd for lua.

**Comment by loiccoyle** [comment]
That is strange, thanks for the suggestion. 😀

**Comment by Shaker-Pelcro** [comment]
@loiccoyle I have the same issue, trying to do `vim.opt.formatoptions = "jqlnt"` in `lua/config/options.lua` doesn't work.
Did you manage to solve this issue?

**Comment by Shaker-Pelcro** [comment]
OK, for anyone trying to do the same, I managed to do override the "formatoptions" by adding this to the `lua/config/autocmds.lua` file ...

```lua
vim.api.nvim_create_autocmd("FileType", {
  command = "set formatoptions-=cro",
})
```

You can obviously change the "command" to whatever command you want to auto-run whenever you start neovim.
