### ISSUE TITLE
bug: vscode extras - comment in typescript

### ISSUE THREAD

**Issue by fveauvy** [LazyVim/LazyVim#802]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.0.9

### Operating system/version

MacOS 13.3.1

### Describe the bug

Thanks to your fix in #798, I can successfully use neovim in vscode.

I stumble upon a bug when I tried to comment some code in a Typescript file.

The following error appeared in neovim-vscode output :

```
E5108: Error executing lua vim/_editor.lua:0: nvim_exec2(): Vim(lua):E5108: Error executing lua ...l/share/nvim/lazy/LazyVim/lua/lazyvim/plugins/coding.lua:143: module 'ts_context_commentstring.internal' not found:
	no field package.preload['ts_context_commentstring.internal']
cache_loader: module ts_context_commentstring.internal not found
cache_loader_lib: module ts_context_commentstring.internal not found
	no file './ts_context_commentstring/internal.lua'
	no file '/opt/homebrew/share/luajit-2.1.0-beta3/ts_context_commentstring/internal.lua'
	no file '/usr/local/share/lua/5.1/ts_context_commentstring/internal.lua'
	no file '/usr/local/share/lua/5.1/ts_context_commentstring/internal/init.lua'
	no file '/opt/homebrew/share/lua/5.1/ts_context_commentstring/internal.lua'
	no file '/opt/homebrew/share/lua/5.1/ts_context_commentstring/internal/init.lua'
	no file './ts_context_commentstring/internal.so'
	no file '/usr/local/lib/lua/5.1/ts_context_commentstring/internal.so'
	no file '/opt/homebrew/lib/lua/5.1/ts_context_commentstring/internal.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './ts_context_commentstring.so'
	no file '/usr/local/lib/lua/5.1/ts_context_commentstring.so'
	no file '/opt/homebrew/lib/lua/5.1/ts_context_commentstring.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	...l/share/nvim/lazy/LazyVim/lua/lazyvim/plugins/coding.lua:143: in function 'get_commentstring'
	....local/share/nvim/lazy/mini.comment/lua/mini/comment.lua:345: in function 'make_comment_parts'
	....local/share/nvim/lazy/mini.comment/lua/mini/comment.lua:215: in function 'toggle_lines'
	[string ":lua"]:1: in main chunk
	[C]: in function 'nvim_exec2'
	vim/_editor.lua: in function 'cmd'
	....local/share/nvim/lazy/mini.comment/lua/mini/comment.lua:160: in function 'operator'
	[string ":lua"]:1: in main chunk
stack traceback:
	[C]: in function 'nvim_exec2'
	vim/_editor.lua: in function 'cmd'
	....local/share/nvim/lazy/mini.comment/lua/mini/comment.lua:160: in function 'operator'
	[string ":lua"]:1: in main chunk
```

### Steps To Reproduce

1. Add vscode extra plugin in LazyVim config.
2. Install and setup neovim-vscode in vscode.
3. Open a file and highlight a line in visual line mode (I got the issue with a Typescript as well as a json file)
4. Enter `gc` to comment.

### Expected Behavior

The lines should be commented and no error should appear in the output.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Right, I added that back again. Will fix!

**Comment by folke** [comment]
Fixed!

**Comment by fveauvy** [comment]
Come on, you can't be that fast @folke 🤯

**Comment by baker221** [comment]
I found that when I use vscode-neovim and LazyVim vscode plugin (mini-comment enabled). When I connect a remote server via ssh, the `gcc` command cannot comment the line correctly. The output is:
```
(mini.comment) Option 'commentstring' is empty.
```

**Comment by folke** [comment]
@baker221 just double checked and all plugins related to comments are loaded inside vscode. Must be the filetype of the specific file

**Comment by baker221** [comment]
Sorry I don't really understand the meaning. The file I work on is written in Python. The default behavior of vscode `command+/` can work well. I read the doc of mini-comments. I guess the problem happens because my server doesn't have treesitter?

> @baker221 just double checked and all plugins related to comments are loaded inside vscode. Must be the filetype of the specific file

**Comment by baker221** [comment]
> Sorry I don't really understand the meaning. The file I work on is written in Python. The default behavior of vscode `command+/` can work well. I read the doc of mini-comments. I guess the problem happens because my server doesn't have treesitter?
> 
> > @baker221 just double checked and all plugins related to comments are loaded inside vscode. Must be the filetype of the specific file

OIC. When I use `.py` file, the `gcc` command can work, but in `.ipynb` file cannot. This is not the reason of server or local. Sorry about that.

**Comment by folke** [comment]
probably because .ipynb files don't have commentstring or treesitter commentstrings set

**Comment by baker221** [comment]
Then is there any method solving this? At this moment I have to select the text by mouse (because in vscode the visual mode selection and mouse selection is different) and use `command+/`

**Comment by folke** [comment]
That filetype just needs a proper `:h 'commentstring'`

**Comment by baker221** [comment]
I tried `set cms="# %s"`, but still the following:
```
(mini.comment) Option 'commentstring' is empty
```

**Comment by folke** [comment]
Are you sure?

In that buffer, what do the following two return?

```lua
require("ts_context_commentstring.internal").calculate_commentstring()
vim.bo.commentstring
```

**Comment by baker221** [comment]
The first:
```
E492: Not an editor command: require("ts_context_commentstring.internal").calculate_commentstring()
```

The second is weird because I actually typed "commentstring".
```
"ommentstring" [New]
Cannot open file "ommentstring"
E480: No match: bo
```

**Comment by folke** [comment]
You need to execute both commands prepended with `:=`

**Comment by baker221** [comment]
Then the first is `nil` and the second didn't print anything.

**Comment by folke** [comment]
then you did not set the commenstring correctly
