### ISSUE TITLE
bug: Tailwind CSS extra is broken

### ISSUE THREAD

**Issue by dphaener** [LazyVim/LazyVim#816]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-216+g4720f4379-Homebrew

### Operating system/version

MacOS Ventura 13.4

### Describe the bug

After the most recent update the Tailwind CSS extra plugin stopped working. Specifically this line was throwing an error: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/extras/lang/tailwind.lua#L15, because `opts.filetypes_exclude` is `nil` and not a table.

It seems as if this is looking for the `{ "markdown" }` excludes setting but that does not exist in the `opts` table that is passed to the function. I copied that config over to my local setup and just replaced `opts.filetypes_exclude` with the literal `{ "markdown" }` and everything now functions as expected.

### Steps To Reproduce

1. Update to the latest LazyVim.
2. Enable the `tailwindcss` extra.
3. Open any file that is included in the tailwind css filetypes (css, html, etc).
4. See the error message

### Expected Behavior

The extra should function without any errors.

**Comment by folke** [comment]
It works in my setup as it should. Did you change any tailwindcss settings?

**Comment by folke** [comment]
I added a nil check, but it shouldn't be needed.

**Comment by dphaener** [comment]
No I didn't change any tailwind settings at all. Not sure what the deal is. 🤷
