### ISSUE TITLE
Feature request: Allow configuration outside of `/nvim`

### ISSUE THREAD

**Issue by hacker-DOM** [LazyVim/LazyVim#833]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Hi there! Astronvim has a feature where they allow you to have two directories. (I dont remember the details, but it's something like: ) one directory that is verbatim from the template and one directory which is just your config. I'm now publishing my dotfiles (from a top-level directory `~`), and it would be great if I could have one directory that has LazyVim, and then one where I would have my config and that I would 'git add' to my dotfiles.

Right now I dont want to delete the `.git` directory so that LazyVim can update itself, but I also can't have git track another git repasitory.... Does that make sense?

Thank you and apologies if this is already supported.	

### Describe the solution you'd like

.

### Describe alternatives you've considered

.

**Comment by folke** [comment]
The starter is not something that gets updated. LazyVim itself is just a plugin.
You don't even need the starter to useLAzyVim. All that's needed is a proper lazy.nvim setup and that's effectively what the starter is. So just remove the .git folder as is mentioned in the docs.

**Comment by folke** [comment]
The real LazyVim code resides in `~/.local/share/nvim/lazy/LazyVim` next to all your other plugins
