### ISSUE TITLE
What's the scrollbar plugin in lazyvim?

### ISSUE THREAD

**Issue by cxzhou35** [LazyVim/LazyVim#840]
I noticed that the screenshot in README file shows that the LazyVim has scrollbar, but I didn't find the according plugin in LazyVim source code for this feature, anyone who can tell me about it? Thanks a lot.

**Comment by folke** [comment]
That's a scrollbar part of noice. It's currently only used for lsp docs

**Comment by cxzhou35** [comment]
It's seems like the buffer also has scrollbar?

**Comment by folke** [comment]
no? Check the screenshot. Only the lsp doc window

**Comment by folke** [comment]
Although, maybe it does have a scrollbar. Might have been https://github.com/petertriho/nvim-scrollbar.

Used that for a while:

```lua
{
    "petertriho/nvim-scrollbar",
    event = "BufReadPost",
    enabled = false,
    config = function()
      local scrollbar = require("scrollbar")
      local colors = require("tokyonight.colors").setup()
      scrollbar.setup({
        handle = { color = colors.bg_highlight },
        excluded_filetypes = { "prompt", "TelescopePrompt", "noice", "notify" },
        marks = {
          Search = { color = colors.orange },
          Error = { color = colors.error },
          Warn = { color = colors.warning },
          Info = { color = colors.info },
          Hint = { color = colors.hint },
          Misc = { color = colors.purple },
        },
      })
    end,
  }
```

**Comment by cxzhou35** [comment]
This scrollbar? I am not sure.
<img width="1307" alt="image" src="https://github.com/LazyVim/LazyVim/assets/80182956/13ad7e43-2147-420d-ad73-bc0b8232df90">

**Comment by xingyuXXX** [comment]
> Although, maybe it does have a scrollbar. Might have been https://github.com/petertriho/nvim-scrollbar.
> 
> Used that for a while:
> 
> {
>     "petertriho/nvim-scrollbar",
>     event = "BufReadPost",
>     config = function()
>       local scrollbar = require("scrollbar")
>       local colors = require("tokyonight.colors").setup()
>       scrollbar.setup({
>         handle = { color = colors.bg_highlight },
>         excluded_filetypes = { "prompt", "TelescopePrompt", "noice", "notify" },
>         marks = {
>           Search = { color = colors.orange },
>           Error = { color = colors.error },
>           Warn = { color = colors.warning },
>           Info = { color = colors.info },
>           Hint = { color = colors.hint },
>           Misc = { color = colors.purple },
>         },
>       })
>     end,
>   }

Maybe add the scrollbar plugin into the extras? I think it's a very useful feature.
