### ISSUE TITLE
bug: Error detected while processing command line: Not an editor command: Lazy

### ISSUE THREAD

**Issue by DrymarchonShaun** [LazyVim/LazyVim#842]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.0

### Operating system/version

Arch Linux; kernel version 6.3.3-arch1-1

### Describe the bug

attempting to pass lazy `Lazy` commands from command line gives the following error.
```
$ nvim +Lazy

Error detected while processing command line:
E492: Not an editor command: Lazy
```

### Steps To Reproduce

Run `nvim +Lazy` from a shell

### Expected Behavior

The Lazy menu to open 

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Check the lazy.nvim docs

**Comment by DrymarchonShaun** [comment]
The only thing I could find that seemed related in any way is 

> Any command can have a bang to make the command wait till it finished. For example, if you want to sync lazy from the cmdline, you can use:

```
$ nvim --headless "+Lazy! sync" +qa
```

**Comment by folke** [comment]
yes, use `--headless`, or do something like `autocmd VeryLazy ....`
