### ISSUE TITLE
bug:  fix(neotest): support neotest adapaters that use setup() for custom setup  breaks neotest-python

### ISSUE THREAD

**Issue by frogmaster** [LazyVim/LazyVim#847]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0

### Operating system/version

arch linux

### Describe the bug

Neotest with neotest-python stopped working for me tonight.  I know nothing of lua, but some minor changes got it to work again: extras/test/core.lua around line 60

              if adapter.setup then
                adapter.setup(config)
              else --  elseif adapter.__call then
                adapter(config)
                --else
                -- error("Adapter " .. name .. " does not support setup")
              end

### Steps To Reproduce

Try to use neotest adapter without setup function.

### Expected Behavior

adapter works

**Comment by folke** [comment]
What is the spec you use?

**Comment by frogmaster** [comment]
~/.config/nvim/lua/plugins/neotest.lua

     return {
      "nvim-neotest/neotest",
      dependencies = {
        "nvim-neotest/neotest-python",
      },
      opts = {
        adapters = {
          ["neotest-python"] = {
            args = { "-s", "-vv" },
            runner = "pytest",
          },
        },
      },
      -- stylua: ignore
      keys = {
        {"<F4>", function() require("neotest").run.run() end, desc="Run nearest"},
        {"<F2>", function() require("neotest").run.run(vim.fn.expand("%")) end, desc="Run file"}
      },
    }

**Comment by folke** [comment]
Should be fixed now. I'll make a new release in a bit.

Let me know if it would still not be resolved.
