### ISSUE TITLE
bug: issues with python parser

### ISSUE THREAD

**Issue by lmaotrix** [LazyVim/LazyVim#849]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-357+g4c05b1a6a-Homebrew

### Operating system/version

windows 11 22H2 with wsl Ubuntu

### Describe the bug

I installed the language parser for python with ":TSInstall python", says it has been installed properly, but when running ":checkhealth" and checking the "parsers/features" section, it shows that no features are enabled for python parser, while they're enabled for all the other languages 

### Steps To Reproduce

1. open nvim
2. run :TSInstall python
3. open a python file
4. start coding in python

### Expected Behavior

syntax highlighting is supposed to work when typing in python and when running :checkhealth it should show that the features for python are enabled

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
This is clearly an issue with nvim-treesitter. Try removing the .so file for the python parser. If the issue persists, file an issue with nvim-treesitter.
