### ISSUE TITLE
bug: Pressing "q" Key Quits LazyVim Instead of Recording Macros

### ISSUE THREAD

**Issue by chadwithz** [LazyVim/LazyVim#855]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.3

### Operating system/version

Fedora 38

### Describe the bug

Pressing the "q" key causes LazyVim to quit instead of initiating macro recording like the version before.

### Steps To Reproduce

1. Update LazyVim plugin in Vim.
2. Open a file in Vim.
3. Press the "q" key.

### Expected Behavior

Pressing the "q" key should initiate macro recording, allowing me to record a series of actions or commands.

### Repro

```Lua
-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
```

**Comment by folke** [comment]
I can't reproduce this. What does `:verbose nmap q` say?

**Comment by chadwithz** [comment]
n  q           * <Lua 71: ~/.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/keys.lua:67>
	Last set from Lua

**Comment by folke** [comment]
That means you have `q` somewhere mapped in a plugin specs under `keys`. That's not LazyVim, so must be one of your custom specs.
