### ISSUE TITLE
bug: cannot configure DAP

### ISSUE THREAD

**Issue by cwrau** [LazyVim/LazyVim#857]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.1 Build type: Release LuaJIT 2.1.0-beta3     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/share/nvim"  Run :checkhealth for more info

### Operating system/version

ArchLinux

### Describe the bug

When trying to setup `nvim-dap` with `mason-nvim-dap` the `automatic_installation` doesn't work, as lazyvim configures `mason-nvim-dap` as a dependency of `nvim-dap` instead of the other way around.

This means `mason-nvim-dap` can't auto-install `nvim-dap`s packages, as they will always be empty because `nvim-dap` get's configured after `mason-nvim-dap`

---

Additionally, I can't figure out how to configure dap without removing the default config, there was https://github.com/LazyVim/LazyVim/issues/696, but that's been closed without a solution

### Steps To Reproduce

1. configure `nvim-dap` to add the `codelldb` adapter;
     ```
     return {
        {
          "mfussenegger/nvim-dap",
          config = function()
            vim.notify('nvim-dap')
            local dap = require("dap")
            dap.adapters.codelldb = {}
          end
         }
      }
2. open a file, something like `main.rs` should work 🤔
3. add a breakpoint to trigger dap; `<leader>db`
4. nothing happens

### Expected Behavior

`mason-nvim-dap` is able to auto-install packages required packages by `nvim-dap`

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here

-------------

I don't know how to setup dap this way 😅
```

**Comment by cwrau** [comment]
> Sorry, but this does work as it should. When using mason-nvim-dap, you of course also need to `DapInstall`.

Why "of course"? The point of the `automatic_installation` is to not have to do this.

> `mason-nvim-dap` doesn't check your dap install at all. It only configures adapters added though `mason`

That's not true, as with the `lspconfig-mason` and `mason-null-ls`, `mason-nvim-dap` *does* check it's parent for configuration; https://github.com/jay-babu/mason-nvim-dap.nvim/blob/main/lua/mason-nvim-dap/automatic_installation.lua#L6

`mason-lspconfig` checks `nvim-lspconfig` for configuration via [hooks](https://github.com/williamboman/mason-lspconfig.nvim/blob/main/lua/mason-lspconfig/lspconfig_hook.lua)

`mason-null-ls` checks `null-ls` via [lookup](https://github.com/jay-babu/mason-null-ls.nvim/blob/main/lua/mason-null-ls/automatic_installation.lua#L4-L13)

and `mason-nvim-dap` checks `nvim-dap` via [lookups](https://github.com/jay-babu/mason-nvim-dap.nvim/blob/main/lua/mason-nvim-dap/automatic_installation.lua#L4-L9) as well

**Comment by folke** [comment]
Ok, my bad. Will look into it later

**Comment by dpetka2001** [comment]
I setup python debugger and it did install automatically. I put the debugger in `mason-nvim-dap` by extending the `ensure_installed` and it got auto-installed as soon as I set a breakpoint and then in `nvim-dap` I just setup the debugger. Isn't that what you want? Do you want to also auto-install by looking at the `nvim-dap` spec and thus not having to configure `mason-nvim-dap`?

**Comment by folke** [comment]
I just looked into this and now that I understand what that actually does, I'm not a fan. I'll probably disable automatic install.

I'm not going to change the dep order.

In your config, just add `rust-tools` as a dep of `mason-nvim-dap`, assuming you setup the dap stuff in the config of rust-tools. (dap's lua modules will be available/loaded, so no worries)

**Comment by cwrau** [comment]
Can you explain why you don't like this?

In my opinion it's a very awesome, and in my opinion necessary, feature.

It's kinda like your startup check that clones LazyVim if it's not installed.

Without this feature I have to manually install all the tools I need in multiple places instead of just configuring them in one place. 

This makes the nvim config very declarative, which is nice and preferable in my opinion.

**Comment by folke** [comment]
As I mentioned, you can use this, by adding it as a dep of rust-tools.

The declarative way for me to install dap servers is using nvim-dap-mason's `ensure_installed`.

**Comment by cwrau** [comment]
Mh, this does not work, the setup function of `mason-nvim-dap` get's called before `rust-tools`'s 😕;

![image](https://github.com/LazyVim/LazyVim/assets/14326070/f44c09c5-8e11-4fe3-b50c-7ab6dc48ef11)

My `lsp-rust.lua`;

```lua
return {
  {
    "jay-babu/mason-nvim-dap.nvim",
    dependencies = {
      "simrat39/rust-tools.nvim"
    }
  },
  {
    "simrat39/rust-tools.nvim",
    dependencies = {
      "neovim/nvim-lspconfig",
      "nvim-lua/plenary.nvim",
      "Saecki/crates.nvim",
      "williamboman/mason.nvim",
      "mfussenegger/nvim-dap",
    },
    opts = {
      dap = {
        adapter = {
          type = 'server',
          port = "${port}",
          executable = {
            command = function()
              return require("mason-registry").get_package("codelldb"):get_install_path()
            end,
            args = {
              '--port',
              '${port}'
            }
          }
        }
      },
      tools = {
        hover_actions = {
          auto_focus = true
        }
      }
    },
    ft = 'rust',
    keys = {
      { '<leader>co', '<cmd>RustHoverActions<cr>', desc = "Hover Actions (Rust)" },
    },
    config = function(_, opts)
      require("rust-tools").setup(opts)
    end
  }
}
```

My `lsp.lua`;

```lua
return {
  -- add pyright to lspconfig
  {
    "neovim/nvim-lspconfig",
    dependencies = {
      "towolf/vim-helm",
    },
    ---@class PluginLspOpts
    opts = {
      ---@type lspconfig.options
      servers = {
        helm_ls = {},
        pyright = {
          before_init = function(_, config)
            local utils = require("utils.python")
            config.settings.python.pythonPath = utils.get_python_path(config.root_dir)
          end,
        },
        yamlls = {
          before_init = function(_, config)
            if config.settings == nil then
              config.settings = {}
            end
            if config.settings.yaml == nil then
              config.settings.yaml = {}
            end
            config.settings.yaml.keyOrdering = false
          end,
          on_attach = function()
            require("utils.yaml-schema-select").setup()
          end
        },
        rust_analyzer = {
          settings = {
            ['rust-analyzer'] = {
              cargo = {
                features = "all"
              }
            }
          }
        },
        gopls = {}
      },
    },
    init = function()
      local keys = require("lazyvim.plugins.lsp.keymaps")
      keys[#keys + 1] = { "=", "vim.lsp.buf.format" }
    end
  },
}
```

**Comment by folke** [comment]
That's because you add `  "mfussenegger/nvim-dap",` as a dep of rust tools.

With lazy.nvim, you don't need to specifiy most dependencies. lua deps are resolved automaticaly.

You can pretty much remove all those deps, unless you want some of them to load when rust-tools loads

**Comment by cwrau** [comment]
Even without this doesn't work, the order of stuff just get's weird;

![image](https://github.com/LazyVim/LazyVim/assets/14326070/5a294b74-24e7-4106-8dac-d92c8111da0b)

**Comment by folke** [comment]
Just check with `:Lazy profile`

**Comment by cwrau** [comment]
![image](https://github.com/LazyVim/LazyVim/assets/14326070/799213f6-745b-4be8-a6cb-e7d108b483b1)

**Comment by folke** [comment]
rust-tools is still loading dap. Are you sure you removed the dap dep?

**Comment by folke** [comment]
Also, why don't you just add rust to `ensure_installed` for nvim-mason-dap??

**Comment by cwrau** [comment]
> Also, why don't you just add rust to `ensure_installed` for nvim-mason-dap??

Because I don't want to manage the dependencies of my dependencies😅
When I remove the `rust-tools` I don't want to have to remember to also remove `codelldb`. Additionally, I don't care what `rust-tools` needs to debug my code, if they ever change their implementation they shall get that tool and a `Lazy clean` cleans everything else up, which get's called on startup anyways.

The software should, and is, be smart enough to figure out that I need that tool without me telling it

It's now just a problem of load / setup ordering 😅
