### ISSUE TITLE
How do I update?

### ISSUE THREAD

**Issue by aasutossh** [LazyVim/LazyVim#86]
I was on previous version, how do I get the new release?

**Comment by aasutossh** [comment]
I guess I didn't understand the concepts of LazyVim.
There's a plugin with all the plugins for LazyVim, isn't there?

**Comment by luxus** [comment]
you start here https://github.com/LazyVim/starter

**Comment by aasutossh** [comment]
> you start here https://github.com/LazyVim/starter

So instead of this repo, I should use the starter repo?

**Comment by aasutossh** [comment]
https://lazyvim.github.io/installation recommends to remove the `.git` folder. Is it fine?

**Comment by luxus** [comment]
You cannot use the git folder because you will not be able to update the repo.
So yes, it is saved to delete the folder.

**Comment by aasutossh** [comment]
Closing. I'll reopen if something happens.

**Comment by luxus** [comment]
good luck :D, maybe its better to checkout the discussion session for questions or reddit
