### ISSUE TITLE
E5113: Error while calling lua chunk: /root/.config/nvim/lua/config/lazy.lua:9: module 'lazy' not found:

### ISSUE THREAD

**Issue by lzyuz** [LazyVim/LazyVim#861]
Error detected while processing /root/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /root/.config/nvim/lua/config/lazy.lua:9: 
module 'lazy' not found:
        no field package.preload['lazy']
        no file './lazy.lua'
        no file '/__w/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/lazy.lua'
        no file '/usr/local/share/lua/5.1/lazy.lua'
        no file '/usr/local/share/lua/5.1/lazy/init.lua'
        no file '/__w/neovim/neovim/.deps/usr/share/lua/5.1/lazy.lua'
        no file '/__w/neovim/neovim/.deps/usr/share/lua/5.1/lazy/init.lua'
        no file './lazy.so'
        no file '/usr/local/lib/lua/5.1/lazy.so'
        no file '/__w/neovim/neovim/.deps/usr/lib/lua/5.1/lazy.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /root/.config/nvim/lua/config/lazy.lua:9: in main chunk
        [C]: in function 'require'
        /root/.config/nvim/init.lua:2: in main chunk

Hello， How to solve the error， OS is ubuntu1604 LTS

**Comment by folke** [comment]
Your initial clone of lazy.nvim failed. You would have seen an error.
Delete the lazy plugins directory and try again. Make sure you have proper internet

**Comment by Hooollin** [comment]
> In my case, the problem arose from my use of an outdated version of Git that didn't support the --filter=blob:none option. Consequently, the command used at the start of lua/config/lazy.lua failed.

you literally SAVED my day

**Comment by SJavad** [comment]
also my day has been saved bro ❤

**Comment by subhodeep2005s** [comment]
> also my day has been saved bro ❤

which git version fixed this thing

**Comment by syntxghost** [comment]
please

**Comment by dpetka2001** [comment]
https://www.lazyvim.org/#%EF%B8%8F-requirements
