### ISSUE TITLE
feature: only_custom_keys

### ISSUE THREAD

**Issue by matthis-k** [LazyVim/LazyVim#87]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

My personal keymap preferences are very different, so i would have to almost disable all keymaps

### Describe the solution you'd like

In the configuration, add a custom_keys_only option (for users to put in `lua/plugins/*.lua`), which will cause the key list to be replaced instead of extended

### Describe alternatives you've considered

A global option, but i think per plugin is more appropiate

**Comment by folke** [comment]
You can replace (or disable) all keymaps for a plugin with:

```lua
{
  "nvim-telescope/telescope.nvim",
  keys = function()
     return {}
  end
},
```

I'll add this to the docs to make it more clear

**Comment by folke** [comment]
Updated the docs at https://lazyvim.github.io/configuration/plugins#%EF%B8%8F-adding--disabling-plugin-keymaps
