### ISSUE TITLE
bug: Can't switch to right window in normal mode with C-l

### ISSUE THREAD

**Issue by wilfriedbarth** [LazyVim/LazyVim#874]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

Ventura 13.2.1

### Describe the bug

Unable to use `<C-l>` and `<C-h>` to go to left / right window.
`<C-w> h/l` work as expected.

### Steps To Reproduce

1. Start nvim with https://github.com/LazyVim/starter
2. Create two windows with `<S> w |`
3. Switch to left with `C-h`
4. Try to switch to right window with `C-l` (shouldn't work)

### Expected Behavior

I expect to be able to switch to right window with `C-l`.

### Repro

```Lua
https://github.com/LazyVim/starter/blob/main/init.lua
```

**Comment by folke** [comment]
That's your terminal settings. Using iterm2? Search issues
