### ISSUE TITLE
bug: docs menu not showing all extras

### ISSUE THREAD

**Issue by fredrikaverpil** [LazyVim/LazyVim#879]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

N/A

### Operating system/version

MacOS 13.4

### Describe the bug

Not sure if you see this too, but I have noticed that all extras don't show until you refresh the page.

Here's a screen recording made in an incognito window:

https://github.com/LazyVim/LazyVim/assets/994357/98f1def1-7038-46ba-a357-4e50af447d61

### Steps To Reproduce

1. Go to lazyvim.org
2. Click plugins, extras - and observe how not all items are showing
3. Refresh the page, now all menu items are visible

### Expected Behavior

All menu items are visible without refresh.

**Comment by folke** [comment]
Can't reproduce. The docs are using docusaurus. You probably just need to do a hard refresh of the page.
