### ISSUE TITLE
bug: Treesitter error evrytime I write a command

### ISSUE THREAD

**Issue by bassamsdata** [LazyVim/LazyVim#88]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.8.2

### Operating system/version

MacOS 12.6

### Describe the bug

**First**, I'd like to thank you for this amazing repo and plugin. I was impressed by the speed of neovim tbh comparing to my last config even though I was using lazy.

**But I have some issue though:**

Tree sitter issue appears whenever I open the command mode to write something. It appears after opening some `lua` files. 

Also `lua` files sometimes shows an error and open files without highlights. I need to quit vim and then re-open it again to solve the issue.

1. Here is some photos for the issue. the issue notification appears with every character I write in the command mode.
<img width="1095" alt="Screen Shot 2023-01-20 at 10 43 41 PM" src="https://user-images.githubusercontent.com/105807570/213842735-a6afe540-75e6-4dd5-88bb-ea9cbdb28594.png">
<img width="1046" alt="Screen Shot 2023-01-20 at 10 19 20 PM" src="https://user-images.githubusercontent.com/105807570/213842765-eb18052e-12c3-4c82-8293-b4a645a54b77.png">

2. **And here is a photo for the highlight issue:**
<img width="1385" alt="Screen Shot 2023-01-20 at 10 57 34 PM" src="https://user-images.githubusercontent.com/105807570/213842782-30f70010-6b71-40de-bb0b-570427770943.png">
<img width="1419" alt="Screen Shot 2023-01-20 at 11 21 10 PM" src="https://user-images.githubusercontent.com/105807570/213843194-50815441-9872-4f13-b387-0859f865d13f.png">

### Solutions I tried:
1. After that I deleted the `example.lua` file since it's written in the docs that this file is just an example and lazy don't load it already. But the issue persist.
2. I disabled the `noice.nvim`, the notification doesn't appear but it's still there wherever I open `lua` file.
the `checkhealth` command will give you an insight since it has many issue 🫣
3. I deleted every nvim folder even the cach and then re-installed it from the start, but the issue appeared like after opening neovim with lua multiple times.

<details><summary>checkhealth - CLICK ME</summary>
<p>

```lua

lazy: require("lazy.health").check()
========================================================================
## lazy.nvim
  - OK: no existing packages found by other package managers
  - OK: packer_compiled.lua not found

man: require("man.health").check()
========================================================================
  - OK: plugin/man.vim not in $VIMRUNTIME
  - OK: autoload/man.vim not in $VIMRUNTIME

noice: require("noice.health").check()
========================================================================
## noice.nvim
  - OK: **Neovim** >= 0.8.0
  - WARNING: **Neovim** 0.9.0 (nightly) is recommended, since it fixes some issues related to `vim.ui_attach`
  - OK: Not running inside **Neovide**
  - OK: You're not using a GUI
  - OK: **vim.go.lazyredraw** is not enabled
  - OK: **nvim-notify** is installed
  - OK: **TreeSitter vim** parser is installed
  - WARNING: **TreeSitter regex** parser is not installed. Highlighting of the cmdline for regex might be broken
  - OK: **TreeSitter lua** parser is installed
  - WARNING: **TreeSitter bash** parser is not installed. Highlighting of the cmdline for bash might be broken
  - WARNING: **TreeSitter markdown** parser is not installed. Highlighting of the cmdline for markdown might be broken
  - WARNING: **TreeSitter markdown_inline** parser is not installed. Highlighting of the cmdline for markdown_inline might be broken
  - OK: `vim.notify` is set to **Noice**
  - OK: `vim.lsp.handlers["textDocument/hover"]` is set to **Noice**
  - OK: `vim.lsp.handlers["textDocument/signatureHelp"]` is set to **Noice**
  - OK: `vim.lsp.handlers["window/showMessage"]` is set to **Noice**
  - OK: `vim.lsp.util.convert_input_to_markdown_lines` is set to **Noice**
  - OK: `vim.lsp.util.stylize_markdown` is set to **Noice**

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Other python executable: /usr/bin/python3
  - INFO: Python version: 3.10.9
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.
      - You may disable this provider (and warning) by adding `let g:loaded_ruby_provider = 0` to your init.vim

## Node.js provider (optional)
  - INFO: Node.js: v19.4.0
  - WARNING: Missing "neovim" npm (or yarn, pnpm) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim
      - Run in shell (if you use pnpm): pnpm install -g neovim
      - You may disable this provider (and warning) by adding `let g:loaded_node_provider = 0` to your init.vim

## Perl provider (optional)
  - WARNING: "Neovim::Ext" cpan module is not installed
    - ADVICE:
      - See :help |provider-perl| for more information.
      - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: /Users/bassam/.local/state/nvim/lsp.log
  - INFO: Log size: 0 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 14
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for help: ABI version 14
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for vim: ABI version 14

which_key: health#which_key#check
========================================================================
## WhichKey: checking conflicting keymaps
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"gc"**
  - INFO: rhs: `v:lua.MiniComment.operator()`
  - WARNING: buffer-local keymap overriding global for mode **"n"**, buf: 0, lhs: **"c"**
  - INFO: old rhs: `:e $MYVIMRC <CR>`
  - INFO: new rhs: `<cmd>lua require("which-key").show("c", {mode = "n", auto = true})<cr>`
  - WARNING: buffer-local keymap overriding global for mode **"n"**, buf: 0, lhs: **"g"**
  - INFO: old rhs: `:Telescope live_grep <CR>`
  - INFO: new rhs: `<cmd>lua require("which-key").show("g", {mode = "n", auto = true})<cr>`

```

</p>
</details>

side note: I don't use (cargo, npm, etc..) I use usually Python,R, SQL and config dotfiles.

Thank you so much.

### Steps To Reproduce

1. open any neovim config lua file.
2. start editing.
3. close neovim.
4. open neovim again and start editing any file in the plugin folder.
5. the issue appears.
6. It may not happen from the first 1 or 2 times but eventually will happen like after 3rd time of editing the config. 
7. Then it keeps happening.

### Expected Behavior

to be working properly without issues. 

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
This error is caused by treesitter. You should run `:TSUpdate` to fix it

**Comment by bassamsdata** [comment]
well, Treesitter is up to date and I just ran `TSUpdate` and still the same exact issue.

**Comment by bassamsdata** [comment]
Unfortunately, it become unusable with any file because of the errors. Before opening any file, there is no errors, but once I open any file, the issue starts.

Oh I noticed a pattern, If I do `nvim path/to/file.toml` there is no problems, but if I open `nvim` normally then open the same file, the hell starts.

but the errors persist in the `checkhealth`

```lua
noice: require("noice.health").check()
  - WARNING: `cmp.entry.get_documentation` is not configured to be handled by **Noice**

neoconf: require("neoconf.health").check()
  - WARNING: **TreeSitter jsonc** parser is not installed. Highlighting of jsonc files might be broken

nvim-treesitter: require("nvim-treesitter.health").check()
  - ERROR: vim(highlights): ...im/0.8.2/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 2765 for language vim
    vim(highlights) is concatenated from the following files:
    | [ERROR]:"/Users/bassam/.local/share/nvim/lazy/nvim-treesitter/queries/vim/highlights.scm", failed to load: ...im/0.8.2/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 2765 for language vim

```

**Comment by folke** [comment]
Please check this https://github.com/nvim-treesitter/nvim-treesitter#i-get-query-error-invalid-node-type-at-position

**Comment by bassamsdata** [comment]
Thanks a lot, that solved the issue. my bad, I thought the problem between lazy and treesitter. Should've searched in treesitter before. Thanks 🙏

**Comment by folke** [comment]
So what was the exact issue and how did you solve it?

Were there other directories? If so which ones? I'll see if I can fix this internally as well

**Comment by bassamsdata** [comment]
I was surprised that I had 2 directories. I don't know why. 
so after writing this command: `:echo nvim_get_runtime_file('parser', v:true)`
it shows 2 dirs:
`['/Users/bassam/.local/share/nvim/lazy/nvim-treesitter/parser', '/usr/local/Cellar/neovim/0.8.2/lib/nvim/parser']`

After I deleted this parser '/usr/local/Cellar/neovim/0.8.2/lib/nvim/parser' , everything worked like nothing happened 🤓.

(I was using small amount of plugins with lazy in my personal config and I was sure that I deleted the 4 folders (cach/share/state/config) before installing the new config so I'm not sure the what may caused this issue)

**Comment by folke** [comment]
ok, cool. I'll see if I can add an extra health check about this to nvim-treesitter upstream. Will keep this open for now, so I don't forget.

**Comment by folke** [comment]
Those are actually the built-in parsers, so not sure why that would cause issues

**Comment by folke** [comment]
Oh, you probably had nvi-treesitter built parsers in that directory too.
Do you remember any other parsers in that directory besides:
 c.so   help.so   lua.so   vim.so
?

**Comment by bassamsdata** [comment]
I remember that those were 4, I remember `lua` and `vim` but I'm not sure about the other 2. I noticed that those are built-in, but I deleted them already 🫣. I probably shouldn't do that.

**Comment by folke** [comment]
That's fine, since we are supposed to use the ones from nvim-treesitter anyway I think, so no big deal :)

**Comment by bassamsdata** [comment]
that's good to hear 🙂

**Comment by bassamsdata** [comment]
Just I wanna give an update on this issue:
As a result of upgrading NVIM to version 0.83, the issue returned, so I ran the following command to resolve it:
`mv /usr/local/Cellar/neovim/0.8.3/lib/nvim/parser parser.mv`

**Comment by RossSmyth** [comment]
I've been working on some developer settings for rust-lang/rust/, and based upon some developer feedback I was trying to find some more "batteries-included" environment rather than base nvim from some developer feedback. This issue makes Lazy not usable for this, as the developer do not know what treesitter is, nor what commands they should even look at trying to run. 

I attempted to run "TSUpdate" and it did not fix this error. 

I get 
```
...im-win64/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 2765 for language vim
```
and
```
Error running notification service: .../Local/nvim-data/lazy/noice.nvim/lua/noice/util/init.lua:234: Vim(append):Error executing lua callback: Failed to load parser: uv_dlopen: C:\Users\Ross\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\markdown.so is not a valid Win32 application.
```
Plus some other unexpected things that make Lazy hard to use. Thanks for your effort in this project, and I hope it continues to improve.

**Comment by folke** [comment]
In case anyone encounters these types of issues, please provide the output for 

```lua
local configs = require "nvim-treesitter.configs"
local utils = require "nvim-treesitter.utils"

local data = {
  install_dir = configs.get_parser_install_dir(),
  cache_dir = utils.get_cache_dir(),
  info_dir = configs.get_parser_info_dir(),
  ignored = configs.get_ignored_parser_installs(),
  win32 = vim.fn.has "win32",
  yaml = {
    found = vim.api.nvim_get_runtime_file("parser/lua.so", true) or {},
  },
}

vim.pretty_print(data)
```

**Comment by dat-le-4** [comment]
> In case anyone encounters these types of issues, please provide the output for
> 
> ```lua
> local configs = require "nvim-treesitter.configs"
> local utils = require "nvim-treesitter.utils"
> 
> local data = {
>   install_dir = configs.get_parser_install_dir(),
>   cache_dir = utils.get_cache_dir(),
>   info_dir = configs.get_parser_info_dir(),
>   ignored = configs.get_ignored_parser_installs(),
>   win32 = vim.fn.has "win32",
>   yaml = {
>     found = vim.api.nvim_get_runtime_file("parser/lua.so", true) or {},
>   },
> }
> 
> vim.pretty_print(data)
> ```

How can I run this? I have the same issue here.

**Comment by folke** [comment]
@dat-le-4 did you run `:checkhealth lazy` first?

To run that code, open a new file (test.lua), paste that code and do `:luafile %`

**Comment by dat-le-4** [comment]
i ran :checkhealth lazy and it's fine. Here is the result for :luafile %. 
<img width="1067" alt="Screenshot 2023-03-13 at 17 41 44" src="https://user-images.githubusercontent.com/96510793/224838727-2be9ea1b-194a-4ce4-ab84-7e271d550f43.png">

**Comment by folke** [comment]
what is the error you get? Did you already run `:TSUpdate`?

**Comment by dat-le-4** [comment]
I ran :TSUpdate and I got "Not an editor content"

**Comment by folke** [comment]
That doesn't make sense. Are you using LazyVim?
Open a lua file and then run the command?

**Comment by folke** [comment]
also, you never told me what error you got. Can you show me the exact error message?

**Comment by dat-le-4** [comment]
here is the error I get: ...im/0.8.3/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 2765 for language vim
I just figured out that treesitter doesn't load automatically when open LazyVim so I loaded it and ran TSUpdate. But that still doesn't resolve the problem.

**Comment by folke** [comment]
Ok, best to report to the nvim treesitter repo. Can't help you.

**Comment by futherus** [comment]
> I was surprised that I had 2 directories. I don't know why. so after writing this command: `:echo nvim_get_runtime_file('parser', v:true)` it shows 2 dirs: `['/Users/bassam/.local/share/nvim/lazy/nvim-treesitter/parser', '/usr/local/Cellar/neovim/0.8.2/lib/nvim/parser']`
> 
> After I deleted this parser '/usr/local/Cellar/neovim/0.8.2/lib/nvim/parser' , everything worked like nothing happened 🤓.

Encountered the same issue. I am using neovim from snap on Ubuntu 20.04. Snap package cannot be modified, therefore I cannot remove second parser directory. Is there any workaround?

**Comment by amaanq** [comment]
Don't use Neovim from snap, it always has issues like this, use HEAD or your distro's package manager
