### ISSUE TITLE
bug: error when running `]q` in go file

### ISSUE THREAD

**Issue by palango** [LazyVim/LazyVim#892]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.1

### Operating system/version

macOS 13.4

### Describe the bug

![Screenshot 2023-06-06 at 15 21 31](https://github.com/LazyVim/LazyVim/assets/90851/12c18f9b-b873-4a1b-a63b-c342f5e5b857)
 Links to this line: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/editor.lua#L381

### Steps To Reproduce

- Open an empty file
- Run `]q`
- Error is shown as notification

### Expected Behavior

Jump to next problem.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by debashisbiswas** [comment]
This seems to be vim's default behavior - if you use `:cnext` or `:cprev` when the quickfix list is empty, you always get this error. Just confirmed on a fresh install. The error looks worse here because it's presented as a Lua stack trace

**Comment by folke** [comment]
Indeed. I can show a prettier error message, but this is pretty low prio for me right now

**Comment by palango** [comment]
Ok, that makes sense. It just didn't feel right.

Feel free to close the issue.
