### ISSUE TITLE
bug: attempt to index field 'fn' (a nil value)

### ISSUE THREAD

**Issue by luchtech** [LazyVim/LazyVim#904]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.4.4

### Operating system/version

5.15.49-linuxkit

### Describe the bug

So I was stuck at Neovim 0.4.4 due to Linux distro limitation. I can't upgrade the Docker image myself as I don't own it so I looked for ways to still run lua. I found a way to source `init.lua` from `init.vim` by adding this line:

`luafile $HOME/.config/nvim/init.lua`

It seems to work since it brought me this error:

```
Error detected while processing /home/devilbox/.config/nvim/init.vim:
line    1:
E5113: Error while calling lua chunk: /home/devilbox/.config/nvim/lua/config/lazy.lua:1: attempt to index field 'fn' (a nil value)
```

### Steps To Reproduce

1. Use this docker image: devilbox/php-fpm:8.1-work-0.151

### Expected Behavior

LazyVim to start after running `nvim`.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by amaanq** [comment]
You're just gonna need 0.8 at a minimum, a lot of plugins require that :shrug:

**Comment by folke** [comment]
Yeah, exactly. I'd recommend the latest stable release.
