### ISSUE TITLE
bug: Keyboard shortcuts in Lazygit, which are also registered in nvim, trigger actions in nvim.

### ISSUE THREAD

**Issue by MatejBransky** [LazyVim/LazyVim#905]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0

### Operating system/version

MacOS Ventura 13.4

### Describe the bug

I'm trying to move commit down or up in the commit stack but the default assigned keyboard shortcuts `<C-j>` and `<C-k>` triggers nvim actions instead.

### Steps To Reproduce

1. focus commits panel in LazyGit
2. try to move a commit down or up in the stack with default shortcuts

### Expected Behavior

The related move action should be executed.

**Comment by folke** [comment]
You can delete those terminal mappings in your `lua/config/keymaps.lua`

```lua
vim.keymap.del("t", "<c-j>")
```

etc...
