### ISSUE TITLE
bug: the gpg password box triggered by the built-in lazygit is broken

### ISSUE THREAD

**Issue by 0x2E** [LazyVim/LazyVim#910]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

macOS 13.4

### Describe the bug

Hi. I found a bug with the terminal(or called windows?) used by the built-in lazygit. I cannot enter something properly into the gpg password box triggered by lazygit. However, lazygit-cli running in the floating terminal works fine.

In the first attempt of gpg password box, all input (except `<enter>`) was caught in the upper left corner of the window

In the second/third attempt, the input was fine at first and broken randomly. I tested it several times and couldn't find the keys would definitely cause this bug

When this bug occurs, somethimes a little nvim elements appear in the gpg window. So I guess this bug is caused by the terminal used by the built-in lazygit.

![lazygit](https://github.com/LazyVim/LazyVim/assets/29594728/8c068840-ac0b-4fd2-a647-654bb25a1f26)

BTW, LazyVim is awesome! Thank you for developing it.

### Steps To Reproduce

1. `<space>gg` to turn on the built-in lazygit
2. `c` to commit, gpg password box is triggered
3. enter something

### Expected Behavior

User input should be caught by gpg input box.

**Comment by folke** [comment]
lazygit-cli running in the floating terminal is exactly the same as the lazygit command.
Either way, not a LAzyVim issue. Not sure what's causing issues here.

I use polkit and get a graphical box to fill in my password to unlock my keychain/gpgkey
