### ISSUE TITLE
bug: edgy auto expand width flashes

### ISSUE THREAD

**Issue by fveauvy** [LazyVim/LazyVim#914]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

MacOS 13.4

### Describe the bug

Once edgy is open, if I press the "e" key to toggle auto expand width, the edgy panel is flashing.

https://github.com/LazyVim/LazyVim/assets/38651917/a16f4553-dcef-43e2-9dbd-c8f687e15741

### Steps To Reproduce

1. Open edgy panel
2. Create a file with a long name
3. Enter the "e" key to toggle auto expand

### Expected Behavior

Either preventing the use of `e` (auto expand feature) when edgy is enabled or manage the feature.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Check the limitations at the top of the readme. This is currently not supported.

**Comment by fveauvy** [comment]
Duly noted, thanks for your feedback and sorry for the trouble.
