### ISSUE TITLE
feature: add doc generation 

### ISSUE THREAD

**Issue by DrummyFloyd** [LazyVim/LazyVim#915]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Would be great to have such tool taht create the language doc automatically based on the fuinction (LSP)

### Describe the solution you'd like

https://github.com/kkoomen/vim-doge

vim doge seems to be a real good candidate, because support multiple language and still maintains
and be availabel trhough completion 

### Describe alternatives you've considered

nothing

### Additional context

nothing

**Comment by folke** [comment]
This one is pretty common for NEovim: https://github.com/danymat/neogen

I'm not planning to add this to LAzyVim, but it's of course very easy to add to your own config.
