### ISSUE TITLE
bug: "nvim ." momentarily opens netrw(?) before it opens neotree

### ISSUE THREAD

**Issue by shivahnshankar** [LazyVim/LazyVim#918]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.8.3 Build type: Release LuaJIT 2.1.0-beta3

### Operating system/version

Pop OS 22.04 LTS

### Describe the bug

When i open nvim in the current dir like "nvim .", a temporary "buffer" opens first before neotree is loaded. 
Not a major issue since this appears for a fraction of a second and maybe just an aesthetic issue but would be interesting to know what causes it. Or is there some configuration that i maybe missing?

### Steps To Reproduce

type "nvim ." in any folder
watch carefully and you can see some regexp before neotree is opened

### Expected Behavior

Ideally, just neotree should open without anything else showing up.

### Repro

```Lua
hmm..i see that netrw opens and i believe this is the same screen that flashes before the neotree plugin loads.
```

**Comment by folke** [comment]
neo-tree is lazy-loaded. If you don't want this behavior, set `lazy=false` for neo-tree.

As you mentioned this is not really an issue
