### ISSUE TITLE
bug: Auto-completion for Cmdline doesn't work

### ISSUE THREAD

**Issue by t18n** [LazyVim/LazyVim#920]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0

### Operating system/version

 macOS 13.2 22D49 arm64

### Describe the bug

![image](https://github.com/LazyVim/LazyVim/assets/14198542/d886bc67-a83f-4337-815c-dea27e73007c)

### Steps To Reproduce

1. Open nvim
2. `Shift + ;`
3. Type `he`

### Expected Behavior

When type `he`, the suggestion with `help` should pop up

### Repro

```Lua
Fresh lazyvim installation
```

**Comment by folke** [comment]
That's not how the Neovim cmdline works. You need to press `<tab>` to trigger completion.

Before you ask, no it's not possible for Noice to automatically trigger completion.

The Noice cmdline **IS** the real cmdline and behaves exactly the same. It just looks different.

**Comment by t18n** [comment]
@folke Sorry for my lack of knowledge. And thank you, pressing tab works :)
