### ISSUE TITLE
bug: Default lazyvim mappings in telescope are case sensitive to override: confusing behavior

### ISSUE THREAD

**Issue by Sleepful** [LazyVim/LazyVim#927]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

/

### Operating system/version

MacOS

### Describe the bug

this is default lazy vim config per
https://www.lazyvim.org/plugins/editor#telescopenvim

```lua
opts = {
  defaults = {
    prompt_prefix = " ",
    selection_caret = " ",
    mappings = {
      i = {
        ["<c-t>"] = function(...)
          return require("trouble.providers.telescope").open_with_trouble(...)
        end,
```

if I want to override this mapping I need to use LOWERCASE `c` when writing it on my own config:
```lua
opts = {
  defaults = {
    prompt_prefix = " ",
    selection_caret = " ",
    mappings = {
      i = {
        ["<c-t>"] = someOtherFunction
```

if I use UPPERCASE `C` then my mapping does not override lazy vim mapping:

```lua
opts = {
  defaults = {
    prompt_prefix = " ",
    selection_caret = " ",
    mappings = {
      i = {
        ["<C-t>"] = someOtherFunction -- this does not work!!!
```

### Steps To Reproduce

d

### Expected Behavior

d

**Comment by Sleepful** [comment]
@folke not here to tell you how to handle your repo, but it could be on the readme for future travelers. As a user I do not know about how the default+custom keys are handled without digging into the source code. I don't even know the specifics of lua table merging. I am good at just trying random stuff to see if it works. Just defining the default keys with the same `Case` every time would be helpful, some bindings have capital `C` and others lowercase `c`, it creates a very `wth` moment when a binding does not work even though it looks as correct as the other ones.

I do not know, my two cents, custom keybinds are a core feature of neovim! The default keybinds are awesome to discover all the functionality that you added to lazyvim, but a key_step of becoming a power user is removing/changing/adding. 

I would go so far to say that a `deep merge` is not good UX behavior. But... I guess... depends on what you expect. In this scenario, do you expect users to move their `opts` into a `config` function so that none of the defaults are used?

**Comment by folke** [comment]
If it bothers you so much, then post an issue at the telescope repo. 🤷🏼

As i said this is not a lazyvim issue. Lazyvim does not create those mappings. Those mappings are created by telescope.

**Comment by Sleepful** [comment]
@folke honestly what are you talking about?

You created those mappings right here: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/editor.lua#L167-L194 

I even linked it in the OP.

If you do not care then say so, but do not tell me to go make noise on another repo just because you cannot read through my issue.

**Comment by Sleepful** [comment]
This should go without saying but LazyVim is responsible for the default settings that it introduces and equally responsible for making those settings easy to change.

**Comment by folke** [comment]
Those are options for telescope. Again, telescope creates those mappings, not LazyVim.

```lua
require("telescope").setup({
  defaults = {
    prompt_prefix = " ",
    selection_caret = " ",
    mappings = {
      i = {
        ["<c-t>"] = function(...)
          return require("trouble.providers.telescope").open_with_trouble(...)
        end,
        ["<C-t>"] = function(...)
          return require("trouble.providers.telescope").open_with_trouble(...)
        end,
      },
    },
  },
})
```

Telescope does **NOT** differentiate between those two mappings.
When defining keymaps with `lazy.nvim`, so using `keys=...`, then `lazy.nvim` **DOES** know that that's the same keymap and would properly handle this case.

But as I mentioned before, Telescope does not. One of those two mappings will eventually be used. Which one? No idea, probably even random depending on what lua returns first and last.

Which is also good enough imo, the user can simply use the correct case.
