### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by NeilGirdhar** [LazyVim/LazyVim#928]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

Ubuntu

### Describe the bug

After updating all of the updated repositories in ~/.local/share/nvim/lazy have detached heads and are not updated.

### Steps To Reproduce

1. `:Lazy`
2. `U`

### Expected Behavior

Stay on main branch.

**Comment by folke** [comment]
Yes, that's to be expected.

**Comment by NeilGirdhar** [comment]
Thank you for the quick reply :smile: .

Yeah, I just realized that they are typically updated.  However, I did have a major problem the other day where Lazy was refusing to update something (wish I could remember why, but I think some of the files had been edited by the plugin).  When I went to the appropriate folder with the git repo, I couldn't pull to fix it (since it was on a detached head).  Wouldn't it be easier to stay on the main branch?

**Comment by folke** [comment]
Of course there's a reason they are on a detached state.
Detached simply means it's been set to a certain `commit`.

Lazy determines the target commit based on the spec's `version`, `tag`, `branch`, `commit`.

There is no other way.

There also shouldn't be another way since that's exactly what `git checkout [commit]` is intended to do.

**Comment by folke** [comment]
If you messed up a local plugin directory, you can just `x` and `i` from the lazy interface.

**Comment by NeilGirdhar** [comment]
I understand.  I figured it was something along those lines.  Thanks for the explanation.
