### ISSUE TITLE
feature: `flatten.nvim`

### ISSUE THREAD

**Issue by andresatierf** [LazyVim/LazyVim#929]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

When opening files from the lazygit float_term, for example, the files open inside the float_term, instead of the regular window

### Describe the solution you'd like

Would be nice to have [flatten.nvim](https://github.com/willothy/flatten.nvim) by default in LazyVim

### Describe alternatives you've considered

Not sure

**Comment by folke** [comment]
You can add this to your own config. Not interested in having this by default. Thank you for the suggestion!
