### ISSUE TITLE
bug: can't run all python test files with <leader>tT

### ISSUE THREAD

**Issue by fredrikaverpil** [LazyVim/LazyVim#931]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

macOS 13.4

### Describe the bug

I'm hitting `<leader>tT` to run all (Python) tests but that seems to do nothing. I [looked up the command](https://github.com/LazyVim/LazyVim/blob/2e7ad2b8257b7d25df0264a5b193da7af35f5a53/lua/lazyvim/plugins/extras/test/core.lua#LL80C1-L80C1) which is executed.

I just now tried to run this instead, which indeed runs all my tests:

```lua
require("neotest").run.run({ suite = true })
```

Is it possible that the keymap command is wrong or less reliable than running with `{ suite = true}`?

### Steps To Reproduce

1. Go to root of a python project, open neovim (and with neotest-python installed).
2. Bring up the test summary with `<leader>ts`.
3. Hit `<leader>tT` to run all tests (nothing happens).
4. Manually run `:lua require("neotest").run.run({ suite = true })` (all tests execute).

### Expected Behavior

I expected the `<leader>tT` provided by LazyVim would execute all my tests.

**Comment by folke** [comment]
That's a limitation of neotest-python, check the issues there
