### ISSUE TITLE
can not customize LSP keymaps,when mode is i

### ISSUE THREAD

**Issue by CnsMaple** [LazyVim/LazyVim#933]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [x] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.1

### Operating system/version

windows11

### Describe the bug

I refer to this: https://www.lazyvim.org/plugins/lsp
![image](https://github.com/LazyVim/LazyVim/assets/92523839/2e2c1cd5-636e-4975-82d3-062be112d480)
----------------------------------------------------------------------------------------------
I'm trying:
```lua
  init = function()
    -- LSP keymaps
    local keys = require("lazyvim.plugins.lsp.keymaps").get()
    -- disable a keymap
    keys[#keys + 1] = { "<c-k>", false}
  end,
```
But there is no effect in i-mode.

Then I tried:
```lua
  init = function()
    -- LSP keymaps
    local keys = require("lazyvim.plugins.lsp.keymaps").get()

    keys[#keys + 1] = { "<c-k>", "<cmd>echo 'hello'<cr>" }
  end,
```
There is no effect in mode i, but there is an effect in mode n.

So, what do I need to do to change the i mode key.
![image](https://github.com/LazyVim/LazyVim/assets/92523839/14723156-b4e8-4f44-9c05-3c477df6494b)

### Steps To Reproduce

no

### Expected Behavior

no

### Repro

```Lua
no
```

**Comment by folke** [comment]
You need to specify the mode as well. `{ "<c-k>", false, mode = "i"}`
