### ISSUE TITLE
bug: pearofducks/ansible-vim is  overwritten by the builtin yaml scripts when loading a yaml file

### ISSUE THREAD

**Issue by bartheerman** [LazyVim/LazyVim#935]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.1

### Operating system/version

macos 13.4

### Describe the bug

I installed pearofducks/ansible-vim for better Ansible support. When opening nvim with a new file with ft=yaml.ansible, this plugin works. But when I open a yaml file, the builtin yaml formatting and syntax takes over. It is not possible to use ansible-vim anymore.

### Steps To Reproduce

1. install pearofducks/ansible-vim. I added these lines in a file in `.config/nvim/lua/plugins/`:
```
    {
      "pearofducks/ansible-vim",
    }
```

2. open nvim. In a new file, enter the command: `:set ft=yaml.ansible`
3. type in a yaml file. It is formatted correctly using  pearofducks/ansible-vim
4. open a .yml file. The formatting and syntax is defined by the builtin yaml scripts
5. the command `:set ft=yaml.ansible` does not make nvim use pearofducks/ansible-vim. The builtin scripts are still used.

I tried to install pearofducks/ansible-vim with the option `ft`, but it did not help:

```
{
      "pearofducks/ansible-vim",
      ft = { "yaml.ansible" }
}
```

### Expected Behavior

It should be possible to continue using pearofducks/ansible-vim when entering `:set ft=yaml.ansible` after opening a yaml file.

**Comment by folke** [comment]
LazyVim does not include any specific yaml stuff.
Did you install the yaml language server?
If so that will attach to the buffer and format it.

**Comment by bartheerman** [comment]
I don't think a language server does indenting while editing?

**Comment by folke** [comment]
No idea. Either way, this is not a LazyVim issue
