### ISSUE TITLE
bug: Running Neoconf before a file is opened causes errors

### ISSUE THREAD

**Issue by mehalter** [LazyVim/LazyVim#945]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1 release

### Operating system/version

Arch Linux

### Describe the bug

When running `:Neoconf` before a file is opened, say on the alpha dashboard, errors pop up that Neoconf needs to be set up before setting up language servers.

I think this is basically because Neoconf is expected to be ran before `lspconfig` runs `setup` but actually uses `lspconfig`. If `lspconfig` is loaded first and triggers the dependency loading of Neoconf, then the `lspconfig` module is available but the `setup`  calls have not been run. If Neoconf is loaded by `:Neoconf` then it loads it's module first, then tries to load `lspconfig` when it tries to run `require("lspconfig"). Then `lspconfig` checks to resolve it's dependencies which it looks like Neoconf is loaded even though it's technically not finished its loading sequence. This is a result of a cyclic dependencies.

![2023-06-19_09:49:27_screenshot](https://github.com/LazyVim/LazyVim/assets/1591837/5c621451-3e9f-4c5e-8d07-502572f1e9c7)

### Steps To Reproduce

1. `nvim`
2. `:Neoconf`

### Expected Behavior

I would expect to be able to work with my Neoconf configuration successfully.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
When neoconf loads, it checks if any servers have already been setup in lspconfig. That did a require of "lspconfig.util", which triggered loading of `lspconfig`.

Just changed that check. It should only check if `package.loaded["lspconfig.util"]` exists.

See fix here https://github.com/folke/neoconf.nvim/commit/cfec478a530d4dbda0dbd0f9d3678460d1aae735

**Comment by mehalter** [comment]
Thanks! ❤️
