### ISSUE TITLE
bug: Nerd Font 3.0 broken icons in Neo-Tree

### ISSUE THREAD

**Issue by mageic-dev** [LazyVim/LazyVim#957]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

Ubuntu 22.04.2 LTS

### Describe the bug

Underlying issue in Neo-Tree v2 with some icons broken by Nerd Font v3.0 (but these are what's available to download from https://github.com/ryanoasis/nerd-fonts). Someone doing a fresh install of a Nerd Font and a fresh LazyVim install will get some broken icons right now.

Requesting that the workaround below be added in the Recipes section to correct Neo-Tree icons for people using Nerd Font v3 fonts:

```lua
  {
    "nvim-neo-tree/neo-tree.nvim",
    opts = {
      default_component_configs = {
        icon = {
          folder_empty = "󰜌",
          folder_empty_open = "󰜌",
        },
        git_status = {
          symbols = {
            renamed = "󰁕",
            unstaged = "󰄱",
          },
        },
      },
      document_symbols = {
        kinds = {
          File = { icon = "󰈙", hl = "Tag" },
          Namespace = { icon = "󰌗", hl = "Include" },
          Package = { icon = "󰏖", hl = "Label" },
          Class = { icon = "󰌗", hl = "Include" },
          Property = { icon = "󰆧", hl = "@property" },
          Enum = { icon = "󰒻", hl = "@number" },
          Function = { icon = "󰊕", hl = "Function" },
          String = { icon = "󰀬", hl = "String" },
          Number = { icon = "󰎠", hl = "Number" },
          Array = { icon = "󰅪", hl = "Type" },
          Object = { icon = "󰅩", hl = "Type" },
          Key = { icon = "󰌋", hl = "" },
          Struct = { icon = "󰌗", hl = "Type" },
          Operator = { icon = "󰆕", hl = "Operator" },
          TypeParameter = { icon = "󰊄", hl = "Type" },
          StaticMethod = { icon = "󰠄 ", hl = "Function" },
        },
      },
    },
  },
```

### Steps To Reproduce

1. Download updated Nerd Font (available from https://github.com/ryanoasis/nerd-fonts). These are Nerd Font v3.0.
2. Use font with terminal / nvim
3. See that at least the following icons are broken: selected empty new folder (should be diamond), git status rename (should be right arrow), git status unstaged (should be empty checkbox outline).

### Expected Behavior

The correct icons should appear, as they did for Nerd Font v2.0. I'm opening the ticket so that the workaround (as provided by Neo-Tree [here](https://github.com/nvim-neo-tree/neo-tree.nvim/pull/921/commits/1239e9d18e04935550001f22eec238f8bdbf2aa9#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) be added to the "Recipes" section so others may fix these easily.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
I've updated the offending icons.

**Comment by folke** [comment]
Either your terminal is not correctly rendering the glyphs, or you are not using a proper Nerd Font v3.

FiraCode is not a Nerd font. You need to use the `Fira Code Nerd Font` font.

But better is to configure a symbols font for your terminal and then you can use any font of your liking.

**Comment by augustocdias** [comment]
Well, when I wrote FiraCode and the others and meant their nerdfont variants. I have tried it in wez and kitty with the same result. I literally went to the nerdfonts website downloaded the latest version and overwritten it on my system. It is specific glyphs that are not working. Most of them are.

**Comment by folke** [comment]
I can assure you that all icons in LazyVim are Nerd Font v3.
If it's not working you're not using the proper font or your terminal settings are wrong.
I'm sure you'll figure it out

**Comment by mageic-dev** [comment]
@augustocdias Here's one way to check that your terminal font settings are correct:

Install the `lynx` package to be able to see a website in your terminal and then do: 

`lynx --display_charset=utf-8 'https://www.lazyvim.org/configuration#default-settings'` 

(or use whatever page is showing which icons are configured). You should be able to see the icons on lynx directly.
