### ISSUE TITLE
bug: <space><tab><f> not working (only tab works)

### ISSUE THREAD

**Issue by allestaire** [LazyVim/LazyVim#968]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.1

### Operating system/version

MacOS 12.2.1

### Describe the bug

Seems like the tab options is not working properly,
Also if there are errors on this, or any configuration regarding on this issue is not being documented
Also are there any thought on adding better documentation on how commands should work?
Seems like the documentation is much alienated

### Steps To Reproduce

1. nvim .
2. Open 2 files
3. try to navigate with <space><tab><[> for the previous tab

### Expected Behavior

Tab options should work.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
What exactly isn't working?

Tabs != buffers

The thing on top in neovim is a bufferlist. Tabs are the little numbered things top-right.
