### ISSUE TITLE
feature: Consider `BufNewFile` as indentlines and other related plugins

### ISSUE THREAD

**Issue by UtkarshVerma** [LazyVim/LazyVim#97]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

When I open a new file, I have to save it, quit it, and open it again so that NVIM loads the required plugins for me.

### Describe the solution you'd like

It would be great if plugins like indent lines and LSP start working directly on creating a new file. For the indent lines, LSP, and similar plugins, adding a `BufNewFile` would be enough I guess.

### Describe alternatives you've considered

Currently, I quit `nvim` and reopen it.

**Comment by folke** [comment]
That's just how NEovim works. Not related to LazyVim.

If you create a new file, you can save it and then do `:e` to let everything attach to the buffer

**Comment by zaynOm** [comment]
Here is a what works for me:

```lua
vim.keymap.set("n", "<leader>n", function()
  local file_name = vim.fn.input("Enter file name: ")
  if file_name and file_name ~= "" then
    vim.cmd("edit " .. file_name) -- Create and open the file
  else
    print("No file name provided!")
  end
end, { desc = "Create new file with name" })
```
