### ISSUE TITLE
bug: flash plugin does not work in VSCode

### ISSUE THREAD

**Issue by skalidindi** [LazyVim/LazyVim#975]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.1

### Operating system/version

MacOS Ventura 13.0

### Describe the bug

I have the following added inside lazy.lua
```
{ import = "lazyvim.plugins.extras.editor.flash" }
{ import = "lazyvim.plugins.extras.vscode" },
```

which means leap is disabled and the flash plugin is enabled. The flash plugin works great inside neovim but it is not enabled in VSCode.

I have tried to enable it by adding
```
return {
  "folke/flash.nvim",
  vscode = true
}
```
to the plugins folder but the search feature still does not work in VSCode.

### Steps To Reproduce

1. Have the above configuration mentioned in bug report inside lazy.lua
2. Add folke/flash.nvim plugin with vscode property set to true
3. Run VScode with NeoVim extension and run search command and notice search does not work

### Expected Behavior

I expect the search functionality to work with the above configuration set. Also, I suggest that the flash plugin should be enabled by default in VSCode when the flash extras section is added to lazy.lua.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Regular search wouldn't work in vscode.

I just tried with `s`, but it seems overlay extmarks don't work in vscode, so flash can't work properly.
