### ISSUE TITLE
Can't adjust the position of cmd line completion menu

### ISSUE THREAD

**Issue by GreenSleeper** [LazyVim/LazyVim#978]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0

### Operating system/version

Ubuntu x86_64  18.04.5 LTS

### Describe the bug

By default, lazyvim place the cmdline_popup and completion menu in the upper area, I tried to adjust the postition of them according to [display-the-cmdline-and-popupmenu-together](https://github.com/folke/noice.nvim/wiki/Configuration-Recipes#display-the-cmdline-and-popupmenu-together), the position of cmdline_popup changed but the popupmenu stays unchanged.

here is my configuration:
```lua
{
    "folke/noice.nvim",
    opts = {
      views = {
        cmdline_popup = {
          position = {
            row = "40%",
          },
          size = {
            width = 80,
          },
          border = {
            style = "none",
            padding = { 1, 1 },
          },
          filter_options = {},
          win_options = {
            winhighlight = "NormalFloat:NormalFloat,FloatBorder:FloatBorder",
          },
        },
        popupmenu = {
          relative = "editor",
          position = {
            row = "50%",
          },
          size = {
            width = 80,
          },
        },
      },
    },
  }
```

### Steps To Reproduce

1. install lazyvim
2. add the configuration above
3. type `:` and then hit `<TAB>`

### Expected Behavior

the position of popupmenu should've changed.

**Comment by folke** [comment]
It's cmdline_popupmenu. You should also disable the `command_palette` preset.

If you disable that preset, then the cmdline is actually shown in the center by default.

Please use discussions next time for user questions.
