### ISSUE TITLE
bug: util.get_root() returns forward slashes for Windows

### ISSUE THREAD

**Issue by fpohtmeh-github** [LazyVim/LazyVim#979]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0

### Operating system/version

Microsoft Windows 10 Pro N (10.0.19045)

### Describe the bug

Love LazyVim!

Opening of neotree with cwd and root is different for the repository root in Windows.
In one case it opens neotree with path that contains slashes, in another case - backslashes. So contents is empty if separators are not native.

Seems that source of the problem is util.get_root() function.
Additionally, neotree doesn't support forward slashes for Windows

### Steps To Reproduce

Start nvim in the root of a non-empty project
Press <leader>e.
Get the empty tree and invalid slashes in the path in the sidebar

### Expected Behavior

Tree is not empty

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
This should be reported to neo-tree. Forward slashes are valid on Windows
