### ISSUE TITLE
Icon or something else can't show on screen

### ISSUE THREAD

**Issue by Eobard-Thawne** [LazyVim/LazyVim#985]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.91

### Operating system/version

Ubuntu 22.04

### Describe the bug

When I finished git clone and opened nvim and installed plugins, the LazyVim icon was not displayed, only zzz and no other ICONS were displayed

### Steps To Reproduce

Use Ubuntu's snap to install nvim 0.91
Execute git clone and open nvim
Until plugins are installed

### Expected Behavior

None

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
The requirements mention that you need a Nerd Font v3 installed

**Comment by robsonpeixoto** [comment]
@Eobard-Thawne , this tutorial is amazing: https://www.youtube.com/watch?v=mQdB_kHyZn8
