### ISSUE TITLE
bug: Docker install method needs more verbosity 

### ISSUE THREAD

**Issue by zach-is-my-name** [LazyVim/LazyVim#99]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

v0.7.0

### Operating system/version

Ubuntu 22.04.1 LTS

### Describe the bug

Pasted the Docker install script from lazyvim.github.io and it either hangs or is too slow to know the difference

### Steps To Reproduce

```
[~]$ docker run -w /root -it --rm alpine:edge sh -uelic '
  apk add git lazygit neovim ripgrep alpine-sdk --update
  git clone https://github.com/LazyVim/starter ~/.config/nvim
  cd ~/.config/nvim
  nvim
'
```

### Expected Behavior

Install

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
What part seems to hang? When Neovim opens? That's where the clone of lazy.nvim happens. Just wait?

**Comment by zach-is-my-name** [comment]
The install of alpine.

**Comment by meicale** [comment]
> It was `fetch https://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz `
> 
> Just tried it again and the install proceeded as expected... strange... I had internet at the time because I immediately proceeded to file this issue...

I went to a similar problem, which seams caused by the problematic Internet connection.
